### ISSUE TITLE
Make Blocked Domains Resolve to Documentation IP Addresses

### ISSUE THREAD

**Issue by Compotation** [StevenBlack/hosts#1000]
The hosts file should return 192.0.2.0 and 2001:DB8:: per RFC 5737 and RFC 3849. Using 0.0.0.0 automatically redirects to my local web server which results in HSTS errors. By using the documentation addresses, the domains will never resolve to a real host.

**Comment by StevenBlack** [comment]
RFC 5737 clearly states:

> This memo provides information for the Internet community.  It does not specify an Internet standard of any kind.

RFC 3849 states:

>  This memo provides information for the Internet community.  It does not specify an Internet standard of any kind. 

Closing.
