### ISSUE TITLE
hosts file has line with unexpected content

### ISSUE THREAD

**Issue by alexsannikov** [StevenBlack/hosts#1004]
Hello,

I am using this repo as a source to build more "intellectual" filters lists for AdGuard Home.
I use some scripts to collapse the content and apply using regexp, as AdGuard Home supports it.

The following line which I found in "hosts" file (admalware) doesn't make sense and breaking my filters, leaving "www" only, which prohibit using any domain name starting from "www".
  
user@linux:/tmp $ cat hosts | grep "0.0.0.0 www "
0.0.0.0 www #.104.248.94.172
user@linux:/tmp $

**Comment by StevenBlack** [comment]
Thank you Alex @alexsannikov.

Ping Tomasz @FadeMind.  [These lines](https://github.com/PolishFiltersTeam/KADhosts/blob/b89a1cb138649ca89e567db48d4b2228b6b8a690/KADhosts.txt#L2028-L2031) (lines 2028 to 2031) appear to be a problem....

**Comment by StevenBlack** [comment]
I'm wondering if we should actively filter lines like this.  Thoughts?

```
0.0.0.0 104.248.94.172
0.0.0.0 142.93.134.136
0.0.0.0 159.65.193.7
0.0.0.0 167.99.34.247
```

**Comment by FadeMind** [comment]
Ping @azet12 @krystian3w

**Comment by krystian3w** [comment]
This is pages with fake flash player. Works on IP only.

**Comment by StevenBlack** [comment]
Thanks @krystian3w.  An IP address is NOT a valid host name.

See [RFC 952](https://tools.ietf.org/html/rfc952).  The status of RFC 952 is,

> This RFC is the official specification of the format of the Internet Host Table.

**Comment by krystian3w** [comment]
OK added on uBo list names "directory" used for scam and problematic websites without host name gone from KAD HOSTS.

**Comment by StevenBlack** [comment]
Thank you @krystian3w!

**Comment by StevenBlack** [comment]
This is fixed in [release 2.4.12](https://github.com/StevenBlack/hosts/releases/tag/2.4.12).

Thank you, everybody.

Closing.

**Comment by alexsannikov** [comment]
Sorry guys, I've opened new Issue #1006  https://github.com/StevenBlack/hosts/issues/1006 to point to the additional IP address in another list.
I am new in GitHub and thought comments are not available if ticket is closed already.
Thanks for understanding.

**Comment by krystian3w** [comment]
https://github.com/StevenBlack/hosts/issues/1006

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/KADhosts/issues/56
