### ISSUE TITLE
thehardtimes.net

### ISSUE THREAD

**Issue by CaptainFrosty** [StevenBlack/hosts#1005]
In reference to the list [/master/extensions/fakenews/hosts](https://github.com/StevenBlack/hosts/blob/master/extensions/fakenews/hosts) —just wanted to let you know that [thehardtimes.net](thehardtimes.net) is self-admittedly a parody news site—I'm assuming from the other sites on the list that your intended targets are opinion 'news', conspiracy theory, false flag sites, etc. and not parody.

thanks for your work
—jesse

**Comment by StevenBlack** [comment]
Ping @marktron, deferring to you on this.

**Comment by StevenBlack** [comment]
Thanks Mark @marktron.  Jesse @CaptainFrosty this will be live in the next release, coming shortly.

Closing.
