### ISSUE TITLE
Pure IP address in hosts file (the same issue as #1004)

### ISSUE THREAD

**Issue by alexsannikov** [StevenBlack/hosts#1006]
https://github.com/StevenBlack/hosts/blob/0a4d2661e1e45dfecec8019e7bb5cd26e42da5ff/extensions/porn/clefspeare13/hosts#L129

This has IP address only.

**Comment by krystian3w** [comment]
Who block forum?

**Comment by StevenBlack** [comment]
Ping Niclas @Clefspeare13, from line 129 in `clefspeare13/hosts`.   Thanks!

**Comment by Clefspeare13** [comment]
> 
> 
> Ping Niclas @Clefspeare13, from line 129 in `clefspeare13/hosts`. Thanks!

fixed, sorry

**Comment by dnmTX** [comment]
> which is why I'm inclined to add it back

@Clefspeare13  as Steven @StevenBlack  already [clarified it](https://github.com/StevenBlack/hosts/issues/1004#issuecomment-503640115) ,no dns resolver will block IP addresses. The lists here is for blocking domains and domains only.
If you don't mind stop adding them as it will create more and more issues here. Thank you for your understanding.

**Comment by StevenBlack** [comment]
Thanks Niclas @Clefspeare13.  Please don't add IP addresses as domains in hosts file.  It's completely ineffective.  IP addresses aren't routed through Hosts mechanisms.  Rather, it's domains that route through Hosts, in order to resolve the domain's IP address.

**Comment by StevenBlack** [comment]
This is fixed and included in [Release 2.4.13](https://github.com/StevenBlack/hosts/releases/tag/2.4.13).

Closing.

**Comment by Clefspeare13** [comment]
> 
> 
> Thanks Niclas @Clefspeare13. Please don't add IP addresses as domains in hosts file. It's completely ineffective. IP addresses aren't routed through Hosts mechanisms. Rather, it's domains that route through Hosts, in order to resolve the domain's IP address.

Ah I wasn't aware of this. Well, you learn new things every day, I'll be sure to avoid pure IP addresses going forward.

**Comment by krystian3w** [comment]
#1004

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/KADhosts/issues/56
