### ISSUE TITLE
Hentai Sites >> More coming soon

### ISSUE THREAD

**Issue by Danilopereira82** [StevenBlack/hosts#1008]
https://www.underhentai.net/
https://hentaistream.com/
https://hentaidude.com/
https://hentailove.tv/
https://latesthentai.com/
https://ohentai.org/
http://streamhentaimovies.com/
https://x-hentai.cf/
https://hentaiyes.com/
https://readhent.ai/
http://hentaistream.co/

BOORU IS CRAZY

https://furry.booru.org/
https://realbooru.com/
https://equibooru.tk/
https://thh.booru.org
https://drawfriends.booru.org
https://the-collection.booru.org
https://tlb.booru.org
https://vidyart.booru.org
https://dom.booru.org
https://joy2.booru.org
https://scat.booru.org
https://thewallpictures.booru.org
https://boob.booru.org
https://themadman.booru.org
https://5naf.booru.org
https://footbooru.booru.org
https://gravityfalls.booru.org
https://charri.booru.org
https://bara.booru.org
https://sai.booru.org
https://g.booru.org
https://catgirls.booru.org
https://m.booru.org
https://svtfoe.booru.org
https://adventuretime.booru.org
https://no.booru.org
https://elderrock.booru.org
https://size.booru.org
https://toonundies.booru.org
https://erpg.booru.org
https://fur.booru.org
https://guro.booru.org
https://rulexxx.booru.org
https://nyou.booru.org
https://dominatrix.booru.org
https://stuff.booru.org
https://model.booru.org
https://rule34stuck.booru.org
https://fantasma.booru.org
https://artwork.booru.org
https://cheesecake.booru.org
https://realfeet.booru.org
https://encryptbooru.booru.org
https://queens.booru.org
https://vulva.booru.org
https://characterlibrary.booru.org
https://simpsonsonly.booru.org/
https://futabooru.booru.org
https://bunnie.booru.org
https://cripple.booru.org
https://derselibrary.booru.org/
https://ewm.booru.org
https://inflatebooru.booru.org
https://red.booru.org
https://luigi3106.booru.org
https://nekochu.booru.org
https://sthg.booru.org
https://blueversusred.booru.org
https://eroshare.booru.org
https://kanayabooru.booru.org

**Comment by dnmTX** [comment]
@Danilopereira82  if you want all those listed above domains by you to be included refer to the [porn maintainer's repo](https://github.com/Clefspeare13/pornhosts) please.

**Comment by webtoonjoon** [comment]
The old Hentai site is basically dead now, and a lot of other popular manga, manhwa, anime, and gallery sites have also changed domains or gone offline over the years. If you're looking for working versions, here are some of the newer sites people are using:

Hentai / Manhwa Sites:
https://manytoon.pro/
https://manhwax.pro/
https://exhentai.co/
https://manhwahentai.pro/
https://mangahentai.pro/

Manga / Manhwa Sites:
https://batoto.one/
https://mangapark.pro/
https://vyvymanga.pro/

Anime / Movie Sites:
https://kissanime.stream/
https://ytsmx.stream/
https://ytsmx.one/
