### ISSUE TITLE
Miscellaneous issue with file size

### ISSUE THREAD

**Issue by johncena4201023** [StevenBlack/hosts#101]
This hosts file is so huge that it actually affects the `ipconfig /release` and `ipconfig /renew` commands in Windows. Sometimes it takes 15 seconds to reconnect to the internet.

Something I'd like to point out if anyone is having issues with their internet.

**Comment by StevenBlack** [comment]
@johncena4201023 what are the timings for each?  I presume you mean it's the `ipconfig /renew` that takes most of the time...

**Comment by lazeran** [comment]
disable DNS client service.

**Comment by StevenBlack** [comment]
Closing this one.
