### ISSUE TITLE
Add domains

### ISSUE THREAD

**Issue by davidsarkany** [StevenBlack/hosts#1010]
static.webminute.hu
bannerserver.hu
adx.jsecoin.com

**Comment by StevenBlack** [comment]
Hi Dávid @davidsarkany  – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
