### ISSUE TITLE
Convert the hosts

### ISSUE THREAD

**Issue by gloeyisk** [StevenBlack/hosts#1012]
Hello. Could anyone tell/teach me how to convert these hosts format to the one that can be applied for `/system/etc`? Here's the format

   ` ||05ee3a24ed11df058c8.com^$popup,third-party
    ||108.168.231.179^$popup,third-party
    ||128cash.org^$popup,third-party`

Thank you.

**Comment by llacb47** [comment]
Those are rules for AdBlock/UBlock Origin. Hosts rules cannot be as granular as those rules and can only block whole domains. This rule would block the first domain in your example in all cases, not just third-party pop-ups.
 ‘0.0.0.0 05ee3a24ed11df058c8.com‘

**Comment by gloeyisk** [comment]
> Those are rules for AdBlock/UBlock Origin. Hosts rules cannot be as granular as those rules and can only block whole domains. This rule would block the first domain in your example in all cases, not just third-party pop-ups.
> `0.0.0.0 05ee3a24ed11df058c8.com`

But how to convert around more than 10000 domains? It's not possible if I edit them manually.

**Comment by funilrys** [comment]
Hello there! Is someone else interested in a way to do that? I might create a PyPi package for that if it's useful :smile_cat: 

Actually, you can do that if you know a bit of Python ... 

I already wrote the code who decode the AdBlock/filter list format for [PyFunceble](http://pyfunceble.github.io) (Sorry Steve for the cross-reference) ... You just need to use it ... 

Here is a quick and dirty solution for those who want to convert AdBlock/UBlock Origin/filter list to hosts format  🙂 (Bugs can happen as it was written in 15/20 minutes while resting after hours of coding  :joy_cat: )

https://gist.github.com/funilrys/284f1c05119db5c7696eacdd8029e96a

Cheers and enjoy,
Nissar

**Comment by StevenBlack** [comment]
Thank you for the question, Gilang @gloeyisk.

Closing.

**Comment by felix-22** [comment]
PyFunceble has now oficially Adblock Decoder now, it's available in 2 forms:
- as a PyFunceble embedded version:
https://pyfunceble.readthedocs.io/en/latest/components/adblock.html
- as a standalone tool:
https://github.com/PyFunceble/adblock-decoder#adblock-filter-list-decoder

Adblock Decoder related issues are supported in this official thread: https://github.com/funilrys/PyFunceble/issues/13
