### ISSUE TITLE
Default list blocks Spotify email verification

### ISSUE THREAD

**Issue by superDuperCyberTechno** [StevenBlack/hosts#1015]
[The default list](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) apparently blocks Spotify email address verifications. The requested domain is _wl.spotify.com_ but I can't find any matches in the list...?

Resetting my hosts file granted me access.

**Comment by StevenBlack** [comment]
The only Spotify domain we list is `spclient.wg.spotify.com`.  This comes from http://winhelp2002.mvps.org/

Closing.
