### ISSUE TITLE
Youtube Ads 

### ISSUE THREAD

**Issue by thomasthomas11235** [StevenBlack/hosts#1017]
I'm scratching my head here. I have the default hosts file installed and working for most sites, but youtube ads are not being blocked. Is this just me, or have others experienced this?

**Comment by gkeegan** [comment]
YouTube ads can't be blocked by host files without blocking the actual video afaik.

**Comment by StevenBlack** [comment]
Thanks Thomas @thomasthomas11235, Keegan @gkeegan is correct.  Those ads come from the same domain as the vid.  It's painful, I know...

Closing.

**Comment by gloschtla** [comment]
Do those ads not all come from pagead2.googlesyndication.com?
https://superuser.com/a/882747/601553

**Comment by llacb47** [comment]
No. @gloschtla
