### ISSUE TITLE
[bug] TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#102]
Updating source someonewhocares.org from http://someonewhocares.org/hosts/zero/hosts
    
    Updating source hosts-file.net from http://hosts-file.net/download/hosts.txt 
    
    Updating source gambling from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts
    
    Updating source malwaredomainlist.com from http://www.malwaredomainlist.com/hostslist/hosts.txt
    
    Updating source tyzbit from https://raw.githubusercontent.com/tyzbit/hosts/master/data/tyzbit/hosts
    
    Updating source social from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/social-hosts
    
    Updating source StevenBlack from https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
    
    Updating source porn from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts
    Updating source adaway.org from http://adaway.org/hosts.txt
    
    Updating source mvps.org from http://winhelp2002.mvps.org/hosts.txt
    
    Updating source yoyo.org from https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
    
    Traceback (most recent call last):
      File "/home/tomasz/.hup/hosts/updateHostsFile.py", line 504, in <module>
        main()
      File "/home/tomasz/.hup/hosts/updateHostsFile.py", line 132, in main
        finalFile = removeDupsAndExcl(mergeFile)
      File "/home/tomasz/.hup/hosts/updateHostsFile.py", line 312, in removeDupsAndExcl
        writeData(finalFile, line)
      File "/home/tomasz/.hup/hosts/updateHostsFile.py", line 67, in writeData
        f.write(bytes(data, 'UTF-8'))
    TypeError: write() argument must be str, not bytes

@StevenBlack

**Comment by FadeMind** [comment]
@StevenBlack 
Issue happened since https://github.com/StevenBlack/hosts/commit/d67a7bc3be2c31e3b4870b7d236cb868e7939aec

Script from https://github.com/StevenBlack/hosts/commit/ec5178b7a581b40d7c4083b12785b75ecce80a6e working fine.

**Comment by StevenBlack** [comment]
Thanks Tomasz! @FadeMind

**Comment by FadeMind** [comment]
@StevenBlack 
Nope. The same issue still:

    OK, we'll only exclude domains in the whitelist.
    Traceback (most recent call last):
      File "/home/tomasz/.hup/hosts/updateHostsFile.py", line 504, in <module>
        main()
      File "/home/tomasz/.hup/hosts/updateHostsFile.py", line 132, in main
        finalFile = removeDupsAndExcl(mergeFile)
      File "/home/tomasz/.hup/hosts/updateHostsFile.py", line 312, in removeDupsAndExcl
        writeData(finalFile, line)
      File "/home/tomasz/.hup/hosts/updateHostsFile.py", line 67, in writeData
        f.write(bytes(data, 'UTF-8'))
    TypeError: write() argument must be str, not bytes

**Comment by StevenBlack** [comment]
What version of Python, what OS?

**Comment by FadeMind** [comment]
archlinux x86_64
python 3.5.1-2
python2 2.7.11-

but `python` call python 3.5.1

**Comment by FadeMind** [comment]
@StevenBlack 

calling `python2 updateHostsFile.py` working fine.
calling `python updateHostsFile.py` (python 3.5.1) make this error.

**Comment by FadeMind** [comment]
[tomasz@arch hosts]$ python2 updateHostsFile.py 
    Do you want to update all data sources? [Y/n] n
    OK, we'll stick with what we've  got locally.
    Do you want to exclude any domains?
    For example, hulu.com video streaming must be able to access its tracking and ad servers in order to play video. [Y/n] n
    OK, we'll only exclude domains in the whitelist.
     
    Success! The hosts file has been saved in folder
    /home/tomasz/.hup/hosts/
    It contains 370,820 unique entries.
    Do you want to replace your existing hosts file with the newly generated file? [Y/n] Moving the file requires administrative privileges. You might need to enter your password.
    Flushing the DNS Cache to utilize new hosts file...
    [tomasz@arch hosts]$

**Comment by StevenBlack** [comment]
Will fix for Python3.

**Comment by StevenBlack** [comment]
Commit c565266416f69f7d1e93ae9e2157b9e1c25b9258  walla!  :-)

**Comment by FadeMind** [comment]
:+1:
