### ISSUE TITLE
tags.news.com.au is neither adware nor malware

### ISSUE THREAD

**Issue by 9e3fce0a** [StevenBlack/hosts#1020]
https://github.com/StevenBlack/hosts/blob/5b0420f1038072d80a53ac5e74a087f2d7c1172f/data/StevenBlack/hosts#L84

tags.news.com.au appears to be used by News Corp as a way of tracking visits to legitimate news articles linked via social media campaigns. Because it isn't fakenews, it should be either removed or re-categorised as 'social'.

**Comment by funilrys** [comment]
Hello anonymous and welcome here,

Here is the commit that introduced it: https://github.com/StevenBlack/hosts/commit/36fab9ad8f6518024e2c4def34a3b1f1a73e2f59.

So let me ping @ValbonneConsulting, @mys721tx for more context before trying to do anything else.

Cheers

**Comment by mys721tx** [comment]
b831f6b is the first commit introduced so I really won't know why it is there.

**Comment by funilrys** [comment]
Ups my bad @mys721tx ... I just did a `git blame` ...

**Comment by funilrys** [comment]
So Steve @StevenBlack, it's yours...

**Comment by dnmTX** [comment]
Steve @StevenBlack. Sorry,not really related to the issue here but let me ask. Do we really need those comments there:
![hosts](https://user-images.githubusercontent.com/34774426/61675053-4e5c1f00-acbc-11e9-927f-2f5a244dba43.png)

**Comment by StevenBlack** [comment]
Thanks @9e3fce0a.  

You say yourself, *`tags.news.com.au` appears to be used by News Corp as a way of tracking visits to legitimate news articles linked via social media campaigns. *

That's reason enough to block.  This domain is present in the ad-hoc list, which is tracking, adware, malware, etc.  Nothing to do with Fake News anyway.

We block google domains for the same reasons this one stays blocked.

Closing.

**Comment by 9e3fce0a** [comment]
> Thanks @9e3fce0a.
> 
> You say yourself, *`tags.news.com.au` appears to be used by News Corp as a way of tracking visits to legitimate news articles linked via social media campaigns. *
> 
> That's reason enough to block. This domain is present in the ad-hoc list, which is tracking, adware, malware, etc. Nothing to do with Fake News anyway.
> 
> We block google domains for the same reasons this one stays blocked.
> 
> Closing.

This decision effectively blocks access to a legitimate news sources. Links generated by many News Corp outlet websites, including The Australian, redirect to the real article via `tags.news.com.au` . This domain is not just a transparent tracker - it's used as redirector that cannot be bypassed. Blocking this effectively blocks access to `theaustralian.com.au`. Please reconsider. Blocking other trackers, like Google's trackers, does not have this effect - i.e. it does not block access to Google services.

Otherwise, I guess all Australians who want to access legitimate news sources will have to stop using your hosts file, or create a fork that's suitable for Australians?

**Comment by Laicure** [comment]
I think, that's where the [whitelist](https://github.com/StevenBlack/hosts#how-do-i-prevent-domains-from-being-included) takes the spotlight.

**AdGuard Tracking Protection** also blocks that domain (**ublock** blocked it on my Chrome).

**Comment by StevenBlack** [comment]
@9e3fce0a The view from here is, if so-called "*legitimate news sources*" are tracking visitors and serving ads using the same domains and subdomains as the legitimate news, then those domains and subdomains are blocked by this hosts file.  

This is core to what we do here: block adware, user tracking, and other malfeasance.

**Comment by Tectract** [comment]
> a way of tracking visits

Yes, it should be blocked.

**Comment by spirillen** [comment]
> Otherwise, I guess all Australians who want to access legitimate news sources will have to stop using your hosts file, or create a fork that's suitable for Australians? That would be a shame, because your hosts file is such a valuable defensive security mechanism.

This [comment](https://github.com/StevenBlack/hosts/issues/1057#issuecomment-537128982) is also for you. It touches the way bait_sites are setup to make it appears that your "Hosts/DNS recursor" is _breaking_ there site.... Don't never ever forget who actually broke there site....

A: who added the unwanted_ware (malicious code) on same domain as needed code?

So dear Australia, your burned of criminals (holistically correct), and apparently some still are criminals against the mankind. Stop helping them, and boycott `news.com.au` and other bait sites like `theaustralian.com.au`... 

Don't forget they are doing there criminal actions because nobody punish them.

What would happens if they in the physically world was looking through your windows? (And this is was, as they also are looking through your toilet door)

**Comment by Mindfu7** [comment]
> > Thanks @9e3fce0a.
> > You say yourself, *`tags.news.com.au` appears to be used by News Corp as a way of tracking visits to legitimate news articles linked via social media campaigns. *
> > That's reason enough to block. This domain is present in the ad-hoc list, which is tracking, adware, malware, etc. Nothing to do with Fake News anyway.
> > We block google domains for the same reasons this one stays blocked.
> > Closing.
> 
> This decision effectively blocks access to legitimate news sources. Links generated by many News Corp outlet websites, including The Australian, redirect to the real article via `tags.news.com.au` . This domain is not just a transparent tracker - it's used as redirector that cannot be bypassed. Blocking this effectively blocks access to `theaustralian.com.au`. Please reconsider. Blocking other trackers, like Google's trackers, does not have this effect - i.e. it does not block access to Google services.
> 
> Otherwise, I guess all Australians who want to access legitimate news sources will have to stop using your hosts file, or create a fork that's suitable for Australians? That would be a shame, because your hosts file is such a valuable defensive security mechanism.

It's Newscorp so saying legitimate is a very big stretch anyway

**Comment by Tectract** [comment]
> redirector that cannot be bypassed

Sounds like a bug on theaustralian . com. Trackers / redirectors are malware. You should complain to their site editors.
