### ISSUE TITLE
Need to block

### ISSUE THREAD

**Issue by ghost** [StevenBlack/hosts#1021]
@StevenBlack
Hi,
These are AD servers in China. 
Can you join hosts to block them?
Adware + Malware
thank!

mi61l.cn
fexiaen.com
klapi.cn
bjhdrx.com
ailiyou1999.com
khlgauqt2000.com
qcoldtui1999.com
victory1999.com
tuigang1999.com

**Comment by StevenBlack** [comment]
Closing.

**Comment by spirillen** [comment]
Hi @ghost Most of these domains seems dead or disabled. In case you can provide more info on which domain is adware and which is malware, please feel free to submit them to https://gitlab.com/dns-firewall/dns/matrix/matrix/issues (1domain = 1 issue)
