### ISSUE TITLE
Support from hostsVN - advertising block of Vietnam

### ISSUE THREAD

**Issue by bigdargon** [StevenBlack/hosts#1023]
Hello!

I am from Vietnam, I have a project `hostsVN` for the purpose of blocking ads and tracking from advertisers from Vietnam. Wishing to support ad blocking projects that support blocking domains in Vietnam, so I created this issue hoping you will merge with hostsVN. The project has been maintained for more than 1 year and continuously updates new domain names.

Github: https://github.com/bigdargon/hostsVN/

Some sources use hostsVN:
- https://abpvn.com/android/
- https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/2437fd7f0b9586ef53a417dd63a59deac43452b0/Filters/filter.template#L92

I have a hosts file that supports all advertisers and followers that Vietnamese people regularly access. Link https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts

And the hosts file I categorized only includes domain name blocking ads and tracking in Vietnam. I hope you just need to merge this file. Link https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-VN

Thanks you!

**Comment by nmhung1985** [comment]
The project has also been included in nextdns lists.

**Comment by StevenBlack** [comment]
Hi @bigdargon I really like this.  Looking through your project, I see an active project with over 600 commits over a reasonably long period of time.  You evidently care very much about your hosts file.

I'm happy to add your data to this project.

For next steps, can I ask you to create a PR where your project information is added to [the data folder] with our [update.json file](https://github.com/StevenBlack/hosts/blob/master/data/StevenBlack/update.json) (sample) configured as you see fit?

Thanks!

**Comment by bigdargon** [comment]
Thanks @StevenBlack! I will try to create PR tomorrow! Glad to collaborate with you!
