### ISSUE TITLE
How do I add this to my PC/Host file? Help please!

### ISSUE THREAD

**Issue by Ovicron** [StevenBlack/hosts#1024]
First time I did this was several months ago and my friend helped me but I don't remember the process, what do I exactly do to get this thing up and running? Please help!

**Comment by spirillen** [comment]
https://github.com/StevenBlack/hosts#location-of-your-hosts-file

**Comment by Ovicron** [comment]
> 
> 
> https://github.com/StevenBlack/hosts#location-of-your-hosts-file

this doesnt help my pea brain understand how to do it.

alright, for exmaple i want the adware+malware thing, do I just copy the raw thing and edit it into my host file?
