### ISSUE TITLE
beautifulsoup4 version requirement

### ISSUE THREAD

**Issue by tiiiecherle** [StevenBlack/hosts#1027]
Hey,

first of all thanks a lot for this really good project again.

The requirements file contains

`beautifulsoup4==4.6.1`

Would changing to

`beautifulsoup4>=4.6.1`

be problematic in any way? Im using the latest beautifulsoup4 version and everything seems to work fine. After updating the pip modules they are downgraded on every run of my [script](https://github.com/tiiiecherle/osx_install_config/blob/master/09_launchd/9b_run_on_boot/root/1_hosts_file/launchd_and_script/hosts_file_generator.sh) which updates the hosts file on macOS using your project.

Thanks for looking into it in advance.

Kind regards

**Comment by StevenBlack** [comment]
Thanks @tiiiecherle.  I'll accept a PR for this, if you can do that.

**Comment by tiiiecherle** [comment]
I updated the [PR](https://github.com/StevenBlack/hosts/pull/1026) accordingly and added the change.

**Comment by StevenBlack** [comment]
Done!  Closing.
