### ISSUE TITLE
Follett Purchases not working

### ISSUE THREAD

**Issue by spookykidmm** [StevenBlack/hosts#1028]
I'm a college freshman and I was trying to purchase books for my classes. The issue I was encountering was when I got to the very end and clicked "place order", the button just spun and spun and nothing happened. I let it run for up to 30 minutes and still nothing. I believe it is something in the hosts list because I tried it on my phone with no adblocking software and the order went through in mere seconds. I am using the base hosts file

Website: https://www.bkstr.com/stetsonstore/home

I wish I had recorded all the requests the site made but I do not want to accidentally purchase my textbooks all over again

**Comment by StevenBlack** [comment]
Hi Spookykid @spookykidmm — we don't list `bkstr.com`.  You don't provide any other actionable info.... so closing.
