### ISSUE TITLE
hostsVN Extension - Idea for "Region" extensions?

### ISSUE THREAD

**Issue by ndrwy** [StevenBlack/hosts#1030]
I was wondering what everyone's thoughts are on making hostsVN as an extension and not as a core list, as to me it seems region-specific and I generally only visit English sites.

If it is made as an extension, then this opens the possibility of offering other region-specific extensions.

I definitely do appreciate the time and work put into hostsVN however!

**Comment by StevenBlack** [comment]
Thanks for the suggestion @ndrwy.

"Only visiting English sites" has nothing to do with what happens internally, within pages.

If you open Developer Tools, for example, it's common to see a single web page make dozens, or hundreds, of HTTP requests.  So what you see, and what you actually download, have little to do with each other, and even less to do with what's in your browser's address bar, or whether the site is English.

I currently think — happy to be convinced otherwise — a key to future host file quality is to embrace regional expertise.

**Comment by dnmTX** [comment]
There is no wrong side in this argument.
Users(like me,@ndrwy and probably many others) would like to have a choice and lists which are only relevant to their browsing habits.
On the other side,devs like to cover more ground,make more users happy.
So,at the end of the day it's up to you Steve @StevenBlack,it's you lists,your unpaid time.

@ndrwy,while ago i personally requested every time when the lists is generated to be coded to have 
`# Start ......` and `# End ....` on each lists in the unified hosts lists just for that purpose,so i can remove(on my end,once it's downloaded) any lists that i don't like or are not relevant to me.
If you are on Linux,you just need to create simple script to do that for you every time.
Hope this will help you....or..i guess...not.

**Comment by ndrwy** [comment]
> So,at the end of the day it's up to you Steve @StevenBlack,it's you lists,your unpaid time.

Totally agree. And yes since I do use the unified hosts on my router which has 128mb of memory, I'm extremely conscientious of blocklists, domain counts and usage.

My solution to this is `rm -r /home/data/hostsVN` in my Bash script which checks and downloads any updates to this repository prior to compiling my own custom unified list.

**Comment by StevenBlack** [comment]
Exploring implementation issues of regions here.  Is Asia a region?  Or is South East Asia a region?  And what of China?  Do we want a hosts file that omits China?  How about India, then?  Where does Russia start, and end, in this scheme of things?

So let's say we offer the ability to omit Vietnam.  Then Thailand, too?  The Philippines?  Who wants to implement that?   

This reminds me of [this video of Jason Fried (starting at 4:30)](http://www.youtube.com/watch?v=4H8RB24ZfRo&t=4m30s).

**Comment by bigdargon** [comment]
Most advertisers want to expand their network. You only access English pages, but are you sure they insert Vietnamese ads?

In Vietnam there are many users who also use Steven Black's hosts to be the default source of ad blocking, the combination will help users in Vietnam to thoroughly block advertising. For example: The default Pihole uses Steven Black's hosts, Adguard Home uses their default filter (hostsVN has combined with Adguard's filter), ...

Currently the list of hostsVN is only about 1,000 domain names, the size is less than 30kb. Estimates of the future will not increase much as there are few advertisers in Vietnam.

**Comment by StevenBlack** [comment]
I think regional differentiation has merits.  But I don't foresee this happening anytime soon.

So, closing.
