### ISSUE TITLE
Twitch app : unable to load

### ISSUE THREAD

**Issue by DaRochaRomain** [StevenBlack/hosts#1035]
With the default host file, I can't load the Twitch app. I got this error :

![image](https://user-images.githubusercontent.com/6987690/63883249-0a9fb800-c9d4-11e9-9453-12a61c30f55b.png)

Once you reset the host file, everything is fine.

**Comment by rjhancock** [comment]
Twitch works fine in the browser however. I also receive that error but when I looked at what was going on, it was saying it was unable to locate files inside of the app bundle on macOS.

**Comment by StevenBlack** [comment]
@DaRochaRomain I'm guessing you're on Windows?

We need to know, which domain Twitch needs to access...

**Comment by DaRochaRomain** [comment]
Yes i'm on Windows. And yes, twitch works fin in the browser but not the app. 

@StevenBlack How can I help you for that?

**Comment by rjhancock** [comment]
The blocks I'm seeing are to....

* https://c.amazon-adsystem.com/aax2/apstag.js
* https://www.googletagservices.com/tag/js/gpt.js
* https://cdn.krxd.net/controltag?confid=JYk8LCsC
* https://ssl.google-analytics.com/ga.js
* https://sb.scorecardresearch.com/beacon.js
* https://s.amazon-adsystem.com/iui3?d=3p-hbg&ex-src=twitch.tv&ex-hargs=v%3D1.0%3Bc%3D8858214122683%3Bp%3De75425fb-5407-7bd5-fd20-f462e98a8777
* https://cdn-gl.imrworldwide.com/conf/P34D56F9D-5684-4C83-8EE1-5EA7DE9CF45D.js
* https://s.amazon-adsystem.com/iui3?pid=a30f442a-e833-4300-a302-987199caf562

Only thing I can think of with these is the app is preventing loading if they can't track you.

**Comment by spirillen** [comment]
@DaRochaRomain you can ex. use [wireshark](https://www.wireshark.org/) and lookout for `[127.0.0.1|0.0.0.0]` responses when you open Twitch

An Alternative:
Post you public IP here, switch your DNS server settings to 

```cmd
DNS server ip addresses:
IPv4:
95.216.209.53
116.203.32.67

IPv6:
2a01:4f9:c010:410e::53
2a01:4f8:1c0c:5f61::53
```

Then I might be able to fetch your DNS queries

**Comment by spirillen** [comment]
> Only thing I can think of with these is the app is preventing loading if they can't track you.

 I solved this issue on my sisters PC a wail ago... but of curse I can't find my note about how.  
However I left no adware or trackware open on her end

**Comment by DaRochaRomain** [comment]
This is the connection I've got with Netlimiter. If this is not helping you, i'll install wireshark.

![image](https://user-images.githubusercontent.com/6987690/63969950-49507380-caa3-11e9-99a8-0e1bc8e52711.png)
![image](https://user-images.githubusercontent.com/6987690/63969977-540b0880-caa3-11e9-8000-f06f1a9adf27.png)
![image](https://user-images.githubusercontent.com/6987690/63969995-5cfbda00-caa3-11e9-831c-af7f335491af.png)

**Comment by spirillen** [comment]
Hmm there are not hit on any of those dumps

The only weird once, are those without any rdns which have no records

the only one comming up with some clue is 

`whois 192.108.239.254` which is Twitch (Amazon), but hosts files doesn't block based on IP addresses.


Is there someway you can monitoring the the app and make a dump in any kind of text and post?

Else I would recommend wireshark and then generate a text dump

**Comment by rjhancock** [comment]
Is this one by chance in the list? 

https://d2v02itv0y9u9t.cloudfront.net/

**Comment by spirillen** [comment]
> Is this one by chance in the list?
> 
> https://d2v02itv0y9u9t.cloudfront.net/

Nope
```shell
grep -Ri 'd2v02itv0y9u9t.cloudfront.net'
```
Returns nothing

**Comment by DaRochaRomain** [comment]
I might take a shot tomorrow, it's kinda late right now for it.

**Comment by rjhancock** [comment]
I just looked at the errors in safari compared to the twitch app. Both reject the same urls but works in Safari and not the app. The only different is the app has 5 errors for File not Found when trying to load source maps. I don't think this is a hosts related issue.

**Comment by spirillen** [comment]
@DaRochaRomain and @rjhancock could you try to clear your hosts files and switch your DNS setting to either mine Servers above or something like [9.9.9.9](https://www.quad9.net/) and see is the app is working?

**Comment by rjhancock** [comment]
Wireshark turned up nothing for me. Just did what you asked to yours and got this error
<img width="1662" alt="Screen Shot 2019-08-29 at 3 56 55 PM" src="https://user-images.githubusercontent.com/460240/63975912-bea54f80-ca75-11e9-8336-46ed0d119164.png">

**Comment by rjhancock** [comment]
I've confirmed it is the hosts file as clearing it brings it back up. Just don't know WHICH entry is crapping out.

**Comment by spirillen** [comment]
Leaving this issue open, as I currently is blank for an idea, and I have no way to install the client as I'm all Linux.....

But a cross reference from the DNS queries vs the hosts files there is one similar record, but it's only in the hosts file, not the dns query, so try to delete this line in the hosts
`stats.jtvnw.net` it is a guess

```c++
dnsdist -e "grepq('ttvnw.net')"
Time    Client                                          Server       ID    Name                      Type  Lat.   TC RD AA Rcode
-2122.9 95.216.209.53:37468                                          26250 video-edge-c2b48c.dfw02.abs.hls.ttvnw.net. AAAA            RD    Question
-2122.9 95.216.209.53:37468                             127.0.0.1:5301 26250 video-edge-c2b48c.dfw02.abs.hls.ttvnw.net. AAAA  30.0      RD    No Error. 0 answers
```
```python
dnsdist -e "grepq('twitch.tv')"
Time    Client                                          Server       ID    Name                      Type  Lat.   TC RD AA Rcode
-2143.4 95.216.209.53:37468                                          26762 irc-ws.chat.twitch.tv.    AAAA            RD    Question
-2143.4 95.216.209.53:37468                                          27786 client-event-reporter.twitch.tv. A               RD    Question
-2143.4 95.216.209.53:37468                                          28298 irc-ws.chat.twitch.tv.    A               RD    Question
-2143.4 95.216.209.53:37468                                          29834 irc-ws.chat.twitch.tv.    AAAA            RD    Question
-2143.4 95.216.209.53:37468                                          30602 client-event-reporter.twitch.tv. A               RD    Question
-2143.4 95.216.209.53:37468                                          30858 irc-ws.chat.twitch.tv.    A               RD    Question
-2143.4 95.216.209.53:37468                                          31114 irc-ws.chat.twitch.tv.    A               RD    Question
-2143.2 95.216.209.53:37468                             95.216.209.53:53 29834 irc-ws.chat.twitch.tv.    AAAA  227.0     RD    No Error. 1 answers
-2143.2 95.216.209.53:37468                             127.0.0.1:5301 31114 irc-ws.chat.twitch.tv.    A     212.3     RD    No Error. 9 answers
-2143.2 95.216.209.53:37468                             95.216.209.53:53 26762 irc-ws.chat.twitch.tv.    AAAA  274.0     RD    No Error. 1 answers
-2143.2 95.216.209.53:37468                             95.216.209.53:53 30858 irc-ws.chat.twitch.tv.    A     260.8     RD    No Error. 9 answers
-2143.2 95.216.209.53:37468                             95.216.209.53:53 30602 client-event-reporter.twitch.tv. A     263.2     RD    No Error. 9 answers
-2143.1 95.216.209.53:37468                             95.216.209.53:53 28298 irc-ws.chat.twitch.tv.    A     307.9     RD    No Error. 9 answers
-2143.1 95.216.209.53:37468                             95.216.209.53:53 27786 client-event-reporter.twitch.tv. A     310.0     RD    No Error. 9 answers
-2143.1 95.216.209.53:37468                                          33418 pubsub-edge.chat.twitch.tv. A               RD    Question
-2143.1 95.216.209.53:37468                                          33930 pubsub-edge.chat.twitch.tv. A               RD    Question
-2143.1 95.216.209.53:37468                                          34186 pubsub-edge.chat.twitch.tv. A               RD    Question
-2143.1 95.216.209.53:37468                             127.0.0.1:5301 34186 pubsub-edge.chat.twitch.tv. A     10.2      RD    No Error. 8 answers
-2143.0 95.216.209.53:37468                             95.216.209.53:53 33930 pubsub-edge.chat.twitch.tv. A     57.5      RD    No Error. 8 answers
-2143.0 95.216.209.53:37468                             95.216.209.53:53 33418 pubsub-edge.chat.twitch.tv. A     105.0     RD    No Error. 8 answers
-2143.0 95.216.209.53:37468                                          35210 irc-ws-edge.chat.twitch.tv. AAAA            RD    Question
-2142.9 95.216.209.53:37468                                          35722 irc-ws-edge.chat.twitch.tv. AAAA            RD    Question
-2142.9 95.216.209.53:37468                             127.0.0.1:5301 35722 irc-ws-edge.chat.twitch.tv. AAAA  50.9      RD    No Error. 0 answers
-2142.9 95.216.209.53:37468                             95.216.209.53:53 35210 irc-ws-edge.chat.twitch.tv. AAAA  98.2      RD    No Error. 0 answers
-2139.2 95.216.209.53:37468                                          36490 spade.twitch.tv.          A               RD    Question
-2139.2 95.216.209.53:37468                                          37002 spade.twitch.tv.          A               RD    Question
-2139.2 95.216.209.53:37468                             95.216.209.53:53 37002 spade.twitch.tv.          A     24.8      RD    Non-Existent domain
-2139.2 95.216.209.53:37468                             95.216.209.53:53 36490 spade.twitch.tv.          A     72.3      RD    Non-Existent domain
-2137.5 95.216.209.53:37468                                          37514 www.twitch.tv.            AAAA            RD    Question
-2137.5 95.216.209.53:37468                             127.0.0.1:5301 37514 www.twitch.tv.            AAAA  35.4      RD    No Error. 1 answers
-2135.8 95.216.209.53:37468                                          39050 gql.twitch.tv.            A               RD    Question
-2135.8 95.216.209.53:37468                                          39306 gql.twitch.tv.            AAAA            RD    Question
-2135.8 95.216.209.53:37468                             127.0.0.1:5301 39306 gql.twitch.tv.            AAAA  11.4      RD    No Error. 1 answers
-2135.7 95.216.209.53:37468                             127.0.0.1:5301 39050 gql.twitch.tv.            A     46.4      RD    No Error. 2 answers
```

Just a thought... does Twitch open another *.exe *.dll (subrutine) that do any request?

**Comment by StevenBlack** [comment]
I just want to say, thank you Richard @rjhancock and @spirillen, for their yeoman service in this issue!

**Comment by rjhancock** [comment]
No change by unblocking the stats domain.

I'm getting stumped on this as it's not making sense. All the domains that are blocked are trackers/ads. Same that are blocked in the browser.

It has to be something specific to the Twitch.app itself.

**Comment by spirillen** [comment]
Sometimes you simply just turning over to duckduckgo.com and do a search....


found this:

> Wont Work Unless you Whitelist and it can be more didn’t Test that much
> From what i can tell this was implemented on the last version of Twitch Client
```
pihole -w s.amazon-adsystem.com
pihole -w c.amazon-adsystem.com
pihole -w countess.twitch.tv
pihole -w pubsub-edge.twitch.tv
pihole -w cdn-gl.imrworldwide.com
```

then a fast digging
```shell
grep -Ri 's.amazon-adsystem.com'
data/someonewhocares.org/hosts:#0.0.0.0 s.amazon-adsystem.com 
data/mvps.org/hosts:0.0.0.0 s.amazon-adsystem.com
data/adaway.org/hosts:127.0.0.1 s.amazon-adsystem.com
```

```shell
grep -Ri 'c.amazon-adsystem.com'
data/someonewhocares.org/hosts:0.0.0.0 c.amazon-adsystem.com
data/mvps.org/hosts:0.0.0.0 c.amazon-adsystem.com
```
>  Peter Lowe’s Ad and tracking server list

So I suggest you try to remove them one by one until succes, and readd in revered order to see what is need on a more up to day release

**Comment by Lartza** [comment]
`s.amazon-adsystem.com` was the only one I needed to whitelist to fix the app from not working. Latest stable app today (7.5.7164.35290 I think?)

**Comment by StevenBlack** [comment]
The `s.amazon-adsystem.com` domain is listed here by virtue of `adaway.org`, `mvps.org`, `someonewhocares.org`, and `tiuxo`.  

I call that, a consensus.

So this isn't going to change anytime soon.

Closing this now, this conversation will serve as reference for Twitch users in the future.
