### ISSUE TITLE
New Ad Domain

### ISSUE THREAD

**Issue by rjhancock** [StevenBlack/hosts#1036]
Just found this domain while visiting a site. It's a proxy for other ad networks.

www.applicationunificationcontroller.com
www.dianomi.com

**Comment by spirillen** [comment]
Hi @rjhancock thx for sharing. I've added them to my source list with this [commit](https://gitlab.com/my-privacy-dns/matrix/matrix/commit/15b47a9c0374ec5eb6fdae6826d2dc259558f7aa)

Unfortunately is @StevenBlack Hosts list based on others list, and you should add this submission to any of the aggregated lists, and you are of curse always welcome to add them on [mine](https://gitlab.com/my-privacy-dns/matrix/matrix) and let's see If Steven&co will implant them in time :)

**Comment by StevenBlack** [comment]
Thanks Richard @rjhancock, I've added these to my ad-hoc list, and it will go live shortly.
