### ISSUE TITLE
New domains

### ISSUE THREAD

**Issue by oguz-ismail** [StevenBlack/hosts#1037]
Ads started showing up on 4channel.org, these are the domains they're loaded from:
ladsup.com
powerad.ai
hb.brainlyads.com
report.hb.brainlyads.com

**Comment by spirillen** [comment]
Hi @oguz-ismail thx for sharing your informations and founds, however `ladsup.com` is a "old" [found](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/161)

But I'll add the other to my [lists](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/172) :)

**Comment by StevenBlack** [comment]
Thanks @oguz-ismail, I've added these to the list.  This will go live in a few minutes.

I don't know what @spirillen means.  `ladsup.com` wasn't listed here before.  It is now.

**Comment by spirillen** [comment]
Hi @StevenBlack Nope not on your list as you usually request users to get in touch with the lists owner like anudedp :)

But I can recommend you to the also add this [ladsreds.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/103) which is the older but still active equivalent for [ladsup.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/161) and last in relation to these two suckers is [popunder.bid](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/108)
