### ISSUE TITLE
Add retry option for updateHostsFile.py

### ISSUE THREAD

**Issue by rEnr3n** [StevenBlack/hosts#1038]
Sometimes I get a network timeout when running `python updateHostsFile.py -as`

Please add an option to retry downloading from the source when that happens instead of just skipping it.

**Comment by StevenBlack** [comment]
This is a good suggestion, @rEnr3n.  I like it.

**Comment by funilrys** [comment]
.

**Comment by codeswhite** [comment]
A good approach to this would be checking connectivity before starting to fetch hosts.

**Comment by rEnr3n** [comment]
@codeswhite Partially. It's not good enough when network issues arise while it is downloading.
