### ISSUE TITLE
Unified Blocklist fraudulently lists website as malware

### ISSUE THREAD

**Issue by jaw-sh** [StevenBlack/hosts#1039]
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

```
0.0.0.0 kiwifarms.net
```

This domain contains no 3rd party tracking software, no malware, no crypto miners, or anything that negatively impacts the user's browser, system, or computer. Why is it blocked?

**Comment by StevenBlack** [comment]
@jaw-sh *fraudulently?*.  I beg your pardon?

Take this up with `CoinBlockerList` at  https://gitlab.com/ZeroDot1/CoinBlockerLists/issues

Closing.

**Comment by lewisje** [comment]
It [has been removed](https://gitlab.com/ZeroDot1/CoinBlockerLists/commit/f5727e1779a5a062932481fa089cea1a8c57665d) following [this upstream Issue](https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/44).
