### ISSUE TITLE
outlook/live online gets blocked by default

### ISSUE THREAD

**Issue by mad4coinz** [StevenBlack/hosts#104]
Is there some way we can automatically whitelist
dub123.mail.live.com
in social?
As far as I can tell it's the URL now used for hotmail/outlook online and although I don't see it specifically blocked there's a few entries for *.live.com
I'll try commenting the handful that get added to my hosts file when I get home tonight and then seeing which is the offending line but in the meantime thought I would ask on here to see if anyone else encountered this problem and how they resolved it.
Thanks!

**Comment by Laicure** [comment]
There's a _[whitelist](https://github.com/StevenBlack/hosts/blob/master/whitelist)_ file in the repo to list those domains so on generate, it will whitelist the domains you have listed.

Though maybe there's a reason why an outlook server/domain is listed by default in the said extension :/

**Comment by mad4coinz** [comment]
Thanks Laicure.
So putting an entry such as
`dub123.mail.live.com`
 in the whitelist will allow "passthrough"?

I figured that would work if I could see an entry in the host file that said
`0.0.0.0 dub123.mail.live.com`
but i don't
So i'll try it to see what happens. If that doesn't work then I'll add the domains
`watson.live.com`
's.gateway.messenger.live.com'
and anything else that isn't obviously an ad-server or analytics looking domain ending in .live.com
to the whitelist and re run the python script to regenerate the file and flush the lookup and see if that fixes it. Then will try to isolate which one(s) I can get rid of and which ones I need to keep?

**Comment by StevenBlack** [comment]
Hi @mad4coinz have a look at commit 987d6f4da8a36f — this is surely the culprit here.

@tyzbit what's your take on this?

**Comment by tyzbit** [comment]
The list may be too aggressive initially.

https://github.com/10se1ucgo/DisableWinTracking/blob/master/run.py#L252

There are 3 separate lists in the script; mine only included the `normallist` entries, so if that's causing issues I have no problem removing the entries mentioned or reverting the commit.

**Comment by mad4coinz** [comment]
thanks @StevenBlack & @tyzbit .
I don't think we need to revert the commit as there's some good blocking there, just need to do a bit more testing to see which are the offending entries as it does seem to be a bit aggressive.
Has anyone seen this commit affect watson functionality too? (i think it's siri for windows right?)
```
0.0.0.0 watson.live.com
0.0.0.0 watson.microsoft.com

```

**Comment by mad4coinz** [comment]
digging further now that I've added the *.live.com domains to the whitelist.
I run a trace route and
```
traceroute dub123.mail.live.com
traceroute to a-0009.a-msedge.net (0.0.0.0), 64 hops max, 52 byte packets
traceroute: sendto: No route to host
 1 traceroute: wrote a-0009.a-msedge.net 52 chars, ret=-1
 *traceroute: sendto: No route to host
traceroute: wrote a-0009.a-msedge.net 52 chars, ret=-1
 *traceroute: sendto: No route to host
traceroute: wrote a-0009.a-msedge.net 52 chars, ret=-1

```

Those servers aren't in the commit mentioned above in which case I'll see what the source is and whitelist them and see if that sorts my problem.

I can see they're in the hosts file

```
cat hosts | grep -n "\.a-msedge.net"
27762:0.0.0.0 a-0001.a-msedge.net
27763:0.0.0.0 a-0002.a-msedge.net
27764:0.0.0.0 a-0003.a-msedge.net
27765:0.0.0.0 a-0004.a-msedge.net
27766:0.0.0.0 a-0005.a-msedge.net
27767:0.0.0.0 a-0006.a-msedge.net
27768:0.0.0.0 a-0007.a-msedge.net
27769:0.0.0.0 a-0008.a-msedge.net
27770:0.0.0.0 a-0009.a-msedge.net

```

**Comment by StevenBlack** [comment]
Ya `tracert` and `ping` don't respect the hosts file... at least not on OS X.

**Comment by mad4coinz** [comment]
hmm, yes i do have a mac but I just googled what you mentioned and saw some mixed results from a forum, someone tested it to show that the host file WAS respected, it just needed to be edited with the correct simple editor and as my pings and trace routes have shown it does get used.

well i updated the whitelist to include the above servers and now I get

```
traceroute dub123.mail.live.com
traceroute to a-0009.a-msedge.net (204.79.197.211), 64 hops max, 52 byte packets
 1  10.0.0.1 (10.0.0.1)  4702.695 ms  0.804 ms  0.678 ms

```
and i can access my hotmail again

edited the whitelist again to only include
a-0009.a-msedge.net

re ran script
trace route and ping fine again
email still available. That will do! Those servers are in all the hosts files as blacklisted PITA!

thanks everyone

**Comment by StevenBlack** [comment]
WTF?  Now `ping` and `traceroute` are respecting my hosts file.

I could have sworn I tested this :frowning:

**Comment by mad4coinz** [comment]
And now we know!
here is the thread
I didn't touch the host file itself, just manipulated the whitelist and let the python script take care of the rest.
https://discussions.apple.com/thread/6113330?tstart=0

**Comment by matkoniecz** [comment]
According to readme

> This repository consolidates several reputable hosts files, and merges them into a single unified hosts file with duplicates removed.

so this seems offtopic (it is problem in one particular list - maybe in multiple lists). Have you tried reporting problem to maintainer of the list that caused this problem?

**Comment by mad4coinz** [comment]
this can be closed, I'll speak to the maintainers of the lists, though we did think it could have been something else at first.

**Comment by StevenBlack** [comment]
Closing
