### ISSUE TITLE
Please add to the gambling list

### ISSUE THREAD

**Issue by jimmys01** [StevenBlack/hosts#1042]
https://www.gamingcommission.gov.gr/index.php/mitroa/black-list

In this official Greek .gov site there is a blacklist of betting sites.
I would like also to find the "whitelist" of the betting site to block as well, because some of them are not in your lists.

**Comment by StevenBlack** [comment]
Thank you James @jimmys01.

Ping @Sinfonietta.

**Comment by StevenBlack** [comment]
Jimmy @jimmys01 do you have a direct link to this gambling list?

When I follow the link above ☝️☝️, I get a home page, written in Greek.  When I translate the page, turns out this data is in Excel format (`.xlsx`, or PDF format, which isn't usable for us.

We need curated, plain-text data.

**Comment by jimmys01** [comment]
Sure its an excel icon down below in the site
https://www.gamingcommission.gov.gr/images/epopteia-kai-elegxos/blacklist/blacklist.xlsx

**Comment by funilrys** [comment]
One may write a repo to parse it so that this project (or one of its components) can parse it... But, it's (probably) a lot of work until complete automation...

**Comment by spirillen** [comment]
> One may write a repo to parse it so that this project (or one of its components) can parse it... But, it's (probably) a lot of work until complete automation...

and even then.... have opened the zip, and I'm not a xsl guru, but looks pretty nasty to even extract the right file to extract the contents needed....

But if somebody can guide me to the right file I'm open to add it to my repo....

**Comment by StevenBlack** [comment]
Hey everybody, I'm going to halt this, right now.

If domain sources aren't plaintext, I'm not interested. 

Also: I don't trust governments to curate lists like this, on an ongoing basis.

Closing.

**Comment by spirillen** [comment]
I'll actually find a govemental list interesting... those on that list are properly not..

1. paying any taxes
1. following any laws
1. doing anything to get the last cent
1. pushes you into debt

And a gambling site is a gambling site.... but interesting thought... 

Someone who like to test for any false positives?
