### ISSUE TITLE
assets.adobedtm.com Needed by snagajob.com

### ISSUE THREAD

**Issue by ad5du** [StevenBlack/hosts#1043]
assets.adobedtm.com  Need to appy for a job on sangajob.com.

**Comment by ndrwy** [comment]
I don't think it's being blocked:

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
`# 0.0.0.0 assets.adobedtm.com #[affects landsend.com]`

Source: http://winhelp2002.mvps.org/hosts.txt

**Comment by ad5du** [comment]
Maybe it isn't on this list. I'm running pi-hole which blocks it, but It uses several lists. I googled it and it led me to here.  I don't have much experience with this.
Sorry if I'm mistaken.

**Comment by mads256h** [comment]
Open the pihole configuration page and go to Tools->Query Lists to find that the domain is being blocked by these lists:
```
Exact matches for assets.adobedtm.com found in:
   http://sysctl.org/cameleon/hosts
   https://hosts-file.net/ad_servers.txt
```
