### ISSUE TITLE
MalwareDomainList.com is stale, no update since February; suggest removing or set it as a optional list.

### ISSUE THREAD

**Issue by opav** [StevenBlack/hosts#1044]
MalwareDomainList.com list is stale, no update since February.   Even if it's updated, the fact that malware domains are ephemeral in nature, meaning once they are publicly known or listed, it is more or less dead.  Unless one have access to private (expensive) listings, subscribing to public malware domain listings is quite pointless.  

And having such a huge list is heavy on resources.

So I suggest its removal from the Unified list and be made as a optional list for those who still really wants it.

**Comment by ndrwy** [comment]
There's also adaway.org which hasn't been updated in 2 years by its author: https://github.com/StevenBlack/hosts/tree/master/data / https://github.com/AdAway/adaway.github.io/commits/master/hosts.txt

There's also UncheckyAds (last update 1 year ago), but the author is still active and the list is relatively small and specific: https://github.com/FadeMind/hosts.extras/commits/master

**Comment by dnmTX** [comment]
@ndrwy as you pointed out already they're in process of merging different,more frequently updated lists.So,give it time.
@opav 
![hosts](https://user-images.githubusercontent.com/34774426/64555049-296e4a80-d302-11e9-93f2-32f4e21bdd92.png)

**Comment by StevenBlack** [comment]
Hi @opav I agree, this list is getting stale, and yes, it's been awhile since its last update.

I'm inclined to keep this list awhile longer.  

With all lists, activity tends to come in waves.  All lists have periods where they are more dynamic than others.  It doesn't mean a quiet list isn't any good.

Let's revisit this in a few months.

**Comment by durablenapkin** [comment]
Just to follow up on this, AdAway merged jawz101/MobileAdTrackers yesterday! :) https://github.com/AdAway/adaway.github.io/pull/13

**Comment by StevenBlack** [comment]
So here are some stats.

* The last version of malwaredomainlist contains 1,105 domains.
* Of those, 246 domains are found within other curated sources in our default list — 22% of malwaredomainlist is covered.
* Therefore malwaredomainlist brings **859 unique domains** to our present list.

**Comment by lightswitch05** [comment]
In case @funilrys has an interest in setting up a PyFunceble run, here are the hosts that are in Malware Domain List only: https://gist.github.com/lightswitch05/7efdffd232b2dde88f13b607e3c80c10

**Comment by dnmTX** [comment]
@lightswitch05  Malware Domain List is already included in Ultimate-Hosts-Blacklist ->[Link](https://github.com/Ultimate-Hosts-Blacklist/MalwareDomainList.com) for a while now. Unique domains are not filtered though but you can at least check how many are [ACTIVE](https://github.com/Ultimate-Hosts-Blacklist/MalwareDomainList.com/blob/master/output/domains/ACTIVE/list) and compare it with your list.

**Comment by lightswitch05** [comment]
I should have known it was already setup. Thanks for the info @dnmTX. I’ll run a diff against the active list and the 860 hosts not already included in other lists and report my findings

**Comment by lightswitch05** [comment]
So, of the 860 hosts not covered in other lists, 378 are considered active per PyFunceble. [Active hosts that are only on Malware Domain List](https://gist.github.com/lightswitch05/5dfd786ca36d3c65685458989598bee9)

**Comment by StevenBlack** [comment]
MalwareDomainList updated yesterday, or thereabouts.

Closing.
