### ISSUE TITLE
Legit crypto domains blocked

### ISSUE THREAD

**Issue by taikanuri** [StevenBlack/hosts#1045]
many legit crypto sites get blocked by the standard list...
- binance.com
- bitfinex.com
- coinmarketcap.com
- even bitcoin.org :-)

can you please remove the legit sites from the list?
or move all crypto sites to a sub-list?

**Comment by mihaifm** [comment]
+1 for this. Any reason for blocking them?

**Comment by dnmTX** [comment]
The right place to ask,complaint etc. is here: https://gitlab.com/ZeroDot1/CoinBlockerLists/issues

**Comment by StevenBlack** [comment]
This has been partly addressed in https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/48 and partly fixed in [Release 2.5.8](https://github.com/StevenBlack/hosts/releases/tag/2.5.8), a few minutes ago.

**Comment by StevenBlack** [comment]
OK everyone, with [Release 2.5.9](https://github.com/StevenBlack/hosts/releases/tag/2.5.9) the CoinBlockerList is removed until their [Issue 48](https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/48) is resolved, which should be soon.

Closing.

**Comment by StevenBlack** [comment]
Meanwhile, I would LOVE to know the Gitlab URL scheme to fetch the version of a file at a particular commit hash.

Because I tried to redefine the CoinBlockerList update.json `url` element, but I couldn't get it to work with the previous version of a file on GitLab.

That's why CoinBlockerList is temporarily dropped entirely, which is a suboptimal resolution.

**Comment by spirillen** [comment]
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/2f489d2d926daa450db73853878cfd9e12db8ae4/hosts_browser

**Comment by StevenBlack** [comment]
@spirillen I tried that; that URL, and all attempts using `gitlab.com`, did not work.

[The URL we were using for CoinBlockerList](https://github.com/StevenBlack/hosts/blob/2d1d2a3f3d8ae003ee6b9a63fa0697e08431dfa2/data/CoinBlockerList/update.json) was to domain `zerodot1.gitlab.io`.

Specifically,

```
https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
```

That returns latest from `master` branch, which isn't what we want.

**Comment by spirillen** [comment]
Hey @StevenBlack that was for the master, yes but it was for helping with the layout of the url as I understood your request was

**Comment by StevenBlack** [comment]
@spirillen yes, we need to get the file from their commit `2f489d` because [our updateHostsFile.py](https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py) presently fails when fetching from `gitlab.com`.  We know fetching from `zerodot1.gitlab.io` works, but how to get a prior version from there?

**Comment by spirillen** [comment]
`2f489d` seems to be the latest...... = master 

as i can understand the commit you search from [#48](https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/48) is a realease without the `coinmarketcap.com`

Let me do some digging a let me find the solution for you :)

Should it be a temponary or permanent solution?

**Comment by StevenBlack** [comment]
Temporary until their Issue number 48 is sorted.

**Comment by spirillen** [comment]
This should do it
it's released 2019-08-13 17:19:05 
```shell
wget -qO - 'https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/19245ea9fe8021c5c8d88128e4298085c47422e5/hosts_browser' | grep 'coinmarketcap.com'
```

```shell
wget -qO - 'https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/19245ea9fe8021c5c8d88128e4298085c47422e5/hosts_browser' | more
# Contribute: https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/new
# Copyright: (c) ZeroDot1, 2019
# Description: This list disables browser based miners such as coin-hive
# Donate: http://bit.ly/CBLDonate Every donation keeps the future development going. Thank you.
# Homepage: https://github.com/ZeroDot1/CoinBlockerLists
# Last modified: 2019-08-13 17:19:05
# License: https://gitlab.io/ZeroDot1/CoinBlockerLists/LICENSE
# [CoinBlocker hosts List optional by ZeroDot1]
0.0.0.0 000.0x1f4b0.com
0.0.0.0 001.0x1f4b0.com
0.0.0.0 002.0x1f4b0.com
0.0.0.0 003.0x1f4b0.com
0.0.0.0 004.0x1f4b0.com
0.0.0.0 005.0x1f4b0.com
0.0.0.0 006.0x1f4b0.com
0.0.0.0 007.0x1f4b0.com
0.0.0.0 008.0x1f4b0.com
0.0.0.0 009.0x1f4b0.com
```

**Comment by StevenBlack** [comment]
@spirillen please.  Whatever you conjure, run it through UpdateHostsFile.py and see if it works.

Then and only then make this thread longer.

I didn't need this to be a long conversation.  I just want a solution.  Right now we're OK without CoinBlockerList.  I'm happy to leave it at that.

**Comment by funilrys** [comment]
Hi Steve @StevenBlack! I don't use GitLab anymore but this is the URL scheme I used in the past for one of my private projects.

(Hopefully this still works 😅)

```
https://gitlab.com/{owner_login}/{project_login_or_name}/raw/{branch_name}/{filename_or_path}
```

Cheers!
