### ISSUE TITLE
Tv ads records

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [StevenBlack/hosts#1050]
https://castoola.com/ is an italian company that make ads in italian tv channels.
I got some records from it:
- `discoveryad.castoola.tv`
- `cdn.discoveryad.castoola.tv`
- `cdn.castoola.com`
- `castoola.com`
- `castoola.tv.lan`

**Comment by StevenBlack** [comment]
Thanks Marco @MarcoDiFrancesco.  This checks out.  I've added these domains to my ad-hoc list and it will be live in the next release.

Closing.
