### ISSUE TITLE
Pull: List of bait-sites

### ISSUE THREAD

**Issue by spirillen** [StevenBlack/hosts#1060]
Based on comments, future, and simply fundamental democracy, I have been thinking... :thinking: 

:thought_balloon: Would there be an ordinance for a list of bait sites? If so I would be happy to provide the Repo to do this and set up an RPZ master and generate the hosts-file for such domains.

In case this could be feeling relevant and wanted, I would pleased for your submissions at this [repo list](https://gitlab.com/my-privacy-dns/matrix/matrix/tree/master/source/bait_sites)

(For those who thinking spam, well there is a first time for everything, it's open source and everything voluntarily)

Please cast you vote :+1: or :-1: or simply post you comment

(@StevenBlack I sincerely hope you are OK with this open question, otherwise we still good if you delete it)

**Comment by StevenBlack** [comment]
Hi @spirillen.  How is "bait-sites" any different than malware, trojans, phish, adware.

It seems categorically the same, to me.

**Comment by spirillen** [comment]
Hi @StevenBlack the differ should be found among those site who's have contents to drag you in for collecting your date, not serving usefully content for the contents sake.

Here my English comes a bit short, but let me try...

Just like `fake news` are posting a lot of "news" to get better search ranking for turning you into data collected zombie money.

I have never seen a such list/DB/RPZ that targets these companies like Google, Microsoft and Facebook who doesn't provide anything to you, but only takes from you for then letting other paying to them in hope of a successful manipulation of the choices you make.

We may never reverse the order of "it is the costumer who rules" and into this wild west web, where it have turned into the oppose through brainwashing banners, search result and articles based on data collected on everybody.

This list should the have those bad guys to be blocked and should not be ( I know the real world :sob: ) in a default list, but a optional list for those who choose to..

Did I succeed in explaining this in English?

**Comment by StevenBlack** [comment]
Yes, thank you @spirillen, that explains it well.

**Comment by StevenBlack** [comment]
@spirillen I'm closing this now.  If and when a good list of bait sites materializes, with a history of curation, then we'll consider it.

Closing.
