### ISSUE TITLE
More Porn to Block

### ISSUE THREAD

**Issue by Danilopereira82** [StevenBlack/hosts#1062]
https://murrtube.net/
https://www.superhentais.com/
https://animeshentai.site/
https://hentaipornobr.com/
https://pornsites.xxx
https://jav.movie/
http://javxxxvideos.com/
https://javtubehd.net/
https://hpjav.tv/
https://www.javbus.org/
https://www.javbus.com/
https://sohentais.com/

**Comment by StevenBlack** [comment]
Ping @sinfonietta.  Thanks.

**Comment by alexsannikov** [comment]
Addition (sorry if something is in list already).
Used "p.rn" word in national language for search in Google and parsing first 9 pages.

faporn.net
www.arrs.info
rukoeb.com
pornovideo.name
www.yaeby.cc
www.russkoepornohub.com
www.megahdporno.tv
pornomorda.me
porno-chiks.com
pornovideo.one
www.ebalovo.mobi
www.arrs.net
www.pornolenta.co
pornovidonline.com
pornosveta.tv
dojkihd.mobi
pornokrik.info
vuku.xyz
www.tiava.com
tvenporno.com
xdojki.mobi
xvideosx.mobi
pornomoloko.com
porno-tv.info
pornotv.online
rusex-club.me
hotubi.com
rusuka.net
pornovideo24.online
tytporno.online
pornoatom.com
ebistika.tv
skachateto.com
pornozona.org
www.jumpboobs.info
www.gaymaletube.com
hotfiesta.tv
mybrazz.com
100xyev.net
www.dreammovies.com
legalovo.net
www.pornotuberu.com
theporndude.com
lenporno.net
www.toroporno.com
brazzme.xyz
ebkino.com
prosto.ws
pornozima.info
www.ruporn24.com
www.pornoostrov.com
smurfik.net
www.sosalka.tv
www.pornorusskie.net
russkoeporno.net
sosushka.net
www.fulltube.xxx
xxxseks.online
mega-porno.me
www.doxera.online
xsporn.net
www.tubev.sex
orgazmtv.com
www.ebyt.online
dojki2.info
prokazi.net
cityporno.org
aziatki-porno.com
2porno.online
porno2017.mobi
topporno.tv
360hitz.net

**Comment by Sinfonietta** [comment]
@StevenBlack this is done in commit 9740ce1630a1618d53804066413c52c37504b31b.

**Comment by StevenBlack** [comment]
Closing.

**Comment by alexsannikov** [comment]
@Sinfonietta commit 9740ce1 is for 1st request, what about second part?
Thanks.
