### ISSUE TITLE
Two new domains

### ISSUE THREAD

**Issue by oguz-ismail** [StevenBlack/hosts#1069]
```
app.networkad.net
app.gelirartisi.com
```

**Comment by StevenBlack** [comment]
Hi @oguz-ismail  – thanks for this input.

You give no context, no reasons.  That's not how this works.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.

**Comment by oguz-ismail** [comment]
Sorry. These domains are used at eksisozluk.com -a relatively small social network-, blocking them doesn't affect the website's display or functionality. But anyways, I'll submit it to curated sources
