### ISSUE TITLE
script run with --noupdate should not ask "Do you want to update all data sources?"

### ISSUE THREAD

**Issue by matkoniecz** [StevenBlack/hosts#107]
> python updateHostsFile.py -n
> ←[94mDo you want to update all data sources?←[0m [Y/n]

the culprit is

> response = "yes" if auto else query_yes_no("Do you want to update all data sources?")
>     if response == "yes" and update:

query_yes_no should not be asked for update=False set by `update = not args.noUpdate`

**Comment by StevenBlack** [comment]
Thanks Mateusz @matkoniecz !
