### ISSUE TITLE
Some porn sites are still accessible with Alt URLs.

### ISSUE THREAD

**Issue by thanuj10** [StevenBlack/hosts#1072]
Hello, 

Recently I added the Unified + Porn hostsfile on my machine and I noticed some popular porn websites are still accessible. Most of them seem to be put in place to re-route users to the websites when the primary URL is geo-blocked or in-accessible.

I've come across the following sites that are still accesible - 
`https://www.pornhub.org`
`https://www.xvideos2.com`
`https://www.mypornbible.com`
`https://www.freesafeporn.com`

Some of the above sites are in the top 10 results when searching for the term porn on DuckDuckGo.

**Comment by ScriptTiger** [comment]
^Bump @sinfonietta and @clefspeare13.

**Comment by Clefspeare13** [comment]
Should be resolved in Clefspeare13/pornhosts@0817bf7

**Comment by StevenBlack** [comment]
Closing.
