### ISSUE TITLE
Skype Ads on Windows PC app

### ISSUE THREAD

**Issue by BiBi88** [StevenBlack/hosts#1073]
Starting to see these crop up today. Anyone know how to block these babies out again?

**Comment by spirillen** [comment]
Switch to [signal](https://www.signal.org/) a well known end to end encrypted messenger and phone program. And help spread democracy and freedom to the people

> Send high-quality group, text, voice, video, document, and picture messages anywhere in the world without SMS or MMS fees.

> Signal messages and calls are always end-to-end encrypted and painstakingly engineered to keep your communication safe. We can't read your messages or see your calls, and no one else can either.

**Comment by Laicure** [comment]
> Starting to see these crop up today. Anyone know how to block these babies out again?

I am seeing those too before, also in their Android app.
Though it is not appearing on my devices anymore.

I am using a [custom list](https://github.com/Laicure/HostsY_hosts#custom-hosts-files-sources-hosts) so I can't pinpoint the exact domain.

**Comment by StevenBlack** [comment]
I'm going to close this now because nothing actionable arises.
