### ISSUE TITLE
porn hosts

### ISSUE THREAD

**Issue by universalbyte** [StevenBlack/hosts#1074]
hi steve. can you wake up "clefspeare13" ? he didn't update his hosts for "3 months" ! i even uploaded more than "500" porn hosts to him.
thank you.

github.com/clefspeare13

**Comment by StevenBlack** [comment]
Ping @clefspeare13.

**Comment by StevenBlack** [comment]
@universalbyte I don't see any open PRs in  @Clefspeare13's repo.

Closing.

**Comment by spirillen** [comment]
Hi @StevenBlack you'll find his submissions under issues.. like this one https://github.com/Clefspeare13/pornhosts/issues/53

**Comment by StevenBlack** [comment]
@spirillen yes, I know.  It’s not even a week old.  It’s just a pasted list of domains, not a single word about content, origin, motivation, justification, call to action, nothing.

It’s not even a PR.

It’s a minimum effort contribution, and then it lands here, with no link, to waste my time, like it's my problem?

**Comment by spirillen** [comment]
But if you look at the Commits in the [Insights](https://github.com/Clefspeare13/pornhosts/graphs/commit-activity), then you'll notice it been quite some time ago the last contribution was added, and all tickets are rather old.

Therefor I have [forked](https://gitlab.com/my-privacy-dns/external-sources/pornhosts) the project, for time being temporarily, to get it back up to date, and trow in some optimizations.

So let me ask straight up, how many domains would you like in the list, as I can provide several millions at once, but that is way to many for a hosts file... So what would be the criteria for success?

**Comment by StevenBlack** [comment]
Niclas @clefspeare13 has been a good curated source for a very long time, many years, and his list will continue to be included here.   

Ping @sinfonietta, maybe?

**Comment by spirillen** [comment]
No doubt he have done a good work, and hopefully @Clefspeare13 will get back and enjoy moderating his list again :crossed_fingers:
