### ISSUE TITLE
Online games extention file

### ISSUE THREAD

**Issue by aramgrigoryan** [StevenBlack/hosts#1079]
Hi,
Could you please add also an extension for blocking online game websites?

Thanks.

**Comment by funilrys** [comment]
Hi @aramgrigoryan and welcome here!

What will be into that extension?

Cheers,
Nissar

**Comment by spirillen** [comment]
> Could you please add also an extension for blocking online game websites?

.............................................................. I'll guess :point_up:   `online games` :point_up:

**Comment by funilrys** [comment]
Du weiß schon worauf ich dachte @spirillen :joy:

**Comment by funilrys** [comment]
So, for those who don't understand:

An extension is a collection of lists that shares the same objective. 
What will be into that extension?

**Comment by spirillen** [comment]
Hallo @funilrys and @aramgrigoryan 

I do understand you question :smiling_imp: as there already is a cat of [gambling](/extensions/gambling) and a new one would have to be more specified definition as: 

* Sites hosting games online (e.g. y8.com (if that even exist anymore do to flash huge security issues)) 
* Sites serving / selling online games (e.g. blizzard.com) 
* Online gaming "tournaments" sites
* Online streaming of gaming (e.g. twitch.tv)
* All above...
* @aramgrigoryan ??

**Comment by aramgrigoryan** [comment]
@spirillen 
Yep, that's it. Websites with html5/flash mini-games that loads in your browser.

**Comment by spirillen** [comment]
@aramgrigoryan 

In the case of a group definition like:

```txt
This group contains sites serving small online browser-based flash/HTML5 games
```

Why wouldn't you add the following to the same group, which to me would make sense

- Online streaming of games

What @funilrys is up to is a more _WHY/WHO_ such a group should be there, the arguments is missing and so does a useful description of such group as do I.

@aramgrigoryan In case that such group would see the sunrise, how many domains would you be able to add yourself? Is there examples of curated lists

These are only preliminary questions for adding a suggestion as this, as @StevenBlack and other to add a comment and take a stand for your suggestion. My comments are not to dis-mental :bomb:  your idea down, but support it to grow  and make the necessary arguments.

Take these 5 question and add them to your answers from above

- Who ( Who should keep such list up to date )
- Why ( Mostly the same as above )
- When ( Update frequent )
- What ( to block )
- Where ( source )

If you have a huge list, that would kick your suggestion into a good start, I'm open to add another category to my [matrix](https://gitlab.com/my-privacy-dns/matrix/matrix) but there would need to be someone who curated well.

Into all this there will be the question of the total [size](https://github.com/StevenBlack/hosts/issues?utf8=%E2%9C%93&q=compression) of the hosts file. [Another](https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/23) issue on this

Just a couple of non-cents :smiling_imp:  from Europe

**Comment by funilrys** [comment]
.
