### ISSUE TITLE
preamble is not prepended

### ISSUE THREAD

**Issue by matkoniecz** [StevenBlack/hosts#108]
According to the readme 

> If you have custom hosts records, place them in file myhosts. The contents of this file are prepended to the unified hosts file during the update process.

but it is added after some other entries (see https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py#L366).

For example 
>  # This hosts file is a merged collection of hosts from reputable sources,
>  # with a dash of crowd sourcing via Github

is before any content from myhosts.

**Comment by StevenBlack** [comment]
The positioning is correct — below the file header comments — but I agree it's not properly described in the readme.  I'll fix.

Thanks Mateusz @matkoniecz !
