### ISSUE TITLE
Ubiquiti phone home server

### ISSUE THREAD

**Issue by DavidCWGA** [StevenBlack/hosts#1083]
Ubiquiti devices have begun phoning home to trace.svc.ui.com

Discussion: https://community.ui.com/questions/UI-official-urgent-please-answer/14259289-e4c3-4c5e-aaa0-02a5baa6cbbe

Would be nice to see this blocked.

**Comment by notDavid** [comment]
More discussion: https://news.ycombinator.com/item?id=21430997

**Comment by StevenBlack** [comment]
Thanks David @DavidCWGA.  I just appended `trace.svc.ui.com` to my data source.  This will go live in the next release.  Thanks to you as well, David @notDavid .
