### ISSUE TITLE
block ads.ad-center.com & associated hosts

### ISSUE THREAD

**Issue by rugabunda** [StevenBlack/hosts#1084]
look.utnldn.com
look.kfioplkn.com

look.ichlnk.com
look.udncoeln.com
look.fjfiln.com
look.ufinkln.com
hlok.qertewrt.com
look.opskln.com
look.ichlnk.com
look.ufinkln.com
look.utndln.com
look.djfiln.com
look.kfiopkln.com
look.udncoeln.com

goa.camimbu.com
zulu.r867qq.net

ads.ad-center.com
cdn1.ad-center.com
cdn2.ad-center.com
ads4.ad-center.com
ads.ad-center.com
ads-script.ad-center.com
www.ad-center.com

#these are closely associated and or interacting directly with ad-center https://threatcrowd.org/domain.php?domain=pwwysydh.com

pwwysydh.com
piz7ohhujogi.com

prjcq.com
pocofh.com
npmpecd.com
pt21na.com
pwdplz.com
pohs2oom.com
ps4ux.com
jadserve.postrelease.com
docaz.net
prjcq.com
e.serverbid.com
d303resfoavrtt.cloudfront.net
payae8moon9.com
pohs2oom.com

#all ptrs for ads.ad-center.com https://www.robtex.com/dns-lookup/ads.ad-center.com

ec2-46-137-77-217.eu-west-1.compute.amazonaws.com
ec2-46-137-110-83.eu-west-1.compute.amazonaws.com
ec2-54-243-100-198.compute-1.amazonaws.com
ec2-175-41-141-63.ap-southeast-1.compute.amazonaws.com
ec2-175-41-150-101.ap-southeast-1.compute.amazonaws.com
ec2-176-34-182-24.eu-west-1.compute.amazonaws.com
ec2-184-72-41-50.us-west-1.compute.amazonaws.com
ec2-184-169-151-9.us-west-1.compute.amazonaws.com
ec2-184-169-178-22.us-west-1.compute.amazonaws.com
ec2-184-169-182-88.us-west-1.compute.amazonaws.com

**Comment by spirillen** [comment]
`utnldn.com` = Expired
`kfioplkn.com` = Expired
`fjfiln.com` = Expired

**Comment by spirillen** [comment]
`http://pwwysydh.com/` sure comes with a spooky link `http://www.qfind.net/?__jsfail&domain_js=pwwysydh.com&feed=Mocha&subfeed=Accepted/DesktopRow` no httpS

![image](https://user-images.githubusercontent.com/44526987/68238212-01048300-0009-11ea-8669-29433b8eacad.png)

any one who have a closed environment where they can test that link?

I've tested and confirm the above obfuscating domains in the following subject

- [r867qq.net](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/490)
- [camimbu.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/489)
- [udncoeln.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/488)
- [kfiopkln.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/487)
- [djfiln.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/486)
- [utndln.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/485)
- [ufinkln.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/484)
- [ichlnk.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/483)
- [opskln.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/482)
- [qertewrt.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/481)
- [ufinkln.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/480)
- [udncoeln.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/479)
- [ichlnk.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/478)
- [ad-center.com](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/477)

**Comment by StevenBlack** [comment]
I would entertain a PR for these.
