### ISSUE TITLE
issue with blocking best.aliexpress.com

### ISSUE THREAD

**Issue by daniplaninc** [StevenBlack/hosts#1086]
best.aliexpress.com from host someonewhocares makes the aliexpress site not load for me. it seems they have switched to using best.aliexpress.com as their main domain.

I will add it to my pihole whitelist manually, since I am not sure whether or not this should be removed from the list. I just want to leave this issue so that people have an easier time finding out what the problem is

**Comment by spirillen** [comment]
If you thinks it is something Dan would need to re-consider, you should contact him directly https://someonewhocares.org/messages/

**Comment by StevenBlack** [comment]
Hi Dani @daniplaninc the domain `best.aliexpress.com` comes to us via someonewhocares.org.  You can contact Dan Pollock at hosts@someonewhocares.org.

Closing.
