### ISSUE TITLE
YouTube History Broken

### ISSUE THREAD

**Issue by Monodry** [StevenBlack/hosts#1089]
Just updated to latest version of standard Unified Hosts (Adware + Malware) and it seems to have broken history logging with youtube (any videos I watch isn't added to my history after). A quick LogDNS and it seems that there are 3 specific domains being blocked: 
```
r5---sn-p5qs7nes.googlevideo.com
r3---sn-p5qlsndr.googlevideo.com
yt3.ggpht.com
```
I'm not sure which one is causing it, but hopefully this helps narrow it down a bit.

**Comment by dnmTX** [comment]
@Monodry  search this repo for posts with **"YouTube History"** in them aaand you'll find out why.

**Comment by Monodry** [comment]
@dnmTX From the looks of it, seems like those issues were caused by the s & s2 youtube domains. I just find it strange that when I took the logs, neither of them seemed to be popping up.
Also, those posts for the most part were from months ago. This issue only started occurring once I updated the host to the most recent version (before that, I had the update from the beginning of this month). It would be kind of odd for an issue to have been presumably fixed only to be reintroduced in the same manner again in a later update.

**Comment by dnmTX** [comment]
> It would be kind of odd for an issue to have been presumably fixed only to be reintroduced in the same manner again in a later update.

**the issue** wasn't fixed,the domain(s) which were blocking the youtube history remained block and still are.
I just checked and neither of the listed by you domains are present in the lists here.Start whitelisting one at the time,this way you might be able to narrow it down.

**Comment by Monodry** [comment]
@dnmTX Hmm...I just went ahead and whitelisted all of them (including the s & s2 youtube domains) and it seems to be working again now. Not sure why I didn't have this problem just a couple of days ago, but I'm just glad it works now. Guess I'll just close out this issue then. Thanks for the help! :)
