### ISSUE TITLE
where to report probably tracking domain

### ISSUE THREAD

**Issue by omicron-b** [StevenBlack/hosts#1090]
Hello! I understand the priority is to report to one of the upstreams, but the only one specializing in tracking domains I found is https://pgl.yoyo.org/adservers which says
> Unfortunately it's probably not worth submitting anything at the moment - spam has taken over. 10,000 mails a month to sift through, even with automated checking, is just too much extra. Fuckin spammers. 

Anywhere else I can report probably tracking domain?
One of my android apps goes to `6cc62a7e.api.splkmobile.com` which, per my research, probably belongs to https://www.splunk.com:
>  The Data-to-Everything Platform 
>  Bring data to every question, decision and action. 

Or, should I create an MR here? Is it best to block `6cc62a7e.api.splkmobile.com` or `splkmobile.com` ?

**Comment by funilrys** [comment]
Is this a Badd-Boyz enough for you @MitchellKrogza ? 😁

**Comment by StevenBlack** [comment]
I think this issue raises a good question.  This repo's readme should  better indicate where and how to submit domains to curators.  At the moment, this isn't sufficiently explicit.

**Comment by spirillen** [comment]
> Is this a Badd-Boyz enough for you @mitchellkrogza ? grin

There is also a very tracking specific repo at https://gitlab.com/my-privacy-dns/matrix/matrix/tree/master/source/tracking :smiley: that one also loves input :+1: 

If you seek for the results as hosts formatted file you should then grab it here https://gitlab.com/my-privacy-dns/rpz-dns-firewall-tools/hosts/blob/master/matrix/hosts

This file then includes the adware, malicious, scamming, spyware and tracking

**Comment by m-svo** [comment]
Hi @spirillen 
I looked through this list and noticed lots of `.ru` domains and got interested since I am in Russia actually. Turns out list contains some (maybe not high quality) legit websites, like for example `stratege.ru`
You can check using local search engine, it shows green crown symbol for websites with "constant and returning userbase": https://yandex.ru/search/?lr=213&text=stratege

**Comment by StevenBlack** [comment]
I'm going to lock this thread now because @spirillen took this in a direction where now, another repo is being discussed here, in this repo.  This is now, therefore, off-topic.  Please take this unrelated conversation elsewhere.

Locking.
