### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Brennii96** [StevenBlack/hosts#1093]
Does anyone know where I can get a Google Analytics hosts list? I need to whitelist it to be able to access the dashboard and view traffic to my website.

Thanks_

**Comment by ScriptTiger** [comment]
I haven't had any issues with just unblocking analytics.google.com to check my dashboard. I also send myself daily reports so I don't need to check my dashboard all that often, unless I see something in a report I really want to drill down deeper into.

**Comment by StevenBlack** [comment]
Brendan @Brennii96 here are a couple of nice options.

* The [Tor browser](https://www.torproject.org/download/) ignores hosts files, entirely.  Given that Tor is probably a good app to have anyway, you could use Tor for specialized things like this.

* [Hostile](https://github.com/feross/hostile) is a nifty command line utility to easily add or remove domains from your hosts file.  If our hosts files are too aggressive for you, you can use `hostile` to remove domains, or you can use `hostile` in a bash script to automate a post process each time you download fresh versions of hosts.

@ScriptTiger we tend to forget, the vast majority of our users don't ever build....

**Comment by Brennii96** [comment]
I've whitelisted analytics.google.com and I get the following error:

![image](https://user-images.githubusercontent.com/16559757/70182165-33260500-16db-11ea-8ed3-7f9a641d3ad7.png)

I have of course cleared the cache and can access google analytics. I have no plugins installed for blocking ads or trackers so I'm assuming google have other domains for the analytics dashboard. 

I can only see domains like csi.gstatic.com being blocked in the network tab so I weren't sure if anyone would have a list I can whitelist. 

@StevenBlack thanks for Hostfile, I normally just edit files through terminal. I don't normally login to websites on Tor because it's easier to autofill using the keepass plugin for chrome.

**Comment by StevenBlack** [comment]
Brendan @Brennii96 unfortunately I'm not in a position to debug this for you.

I would just use Tor.  

Closing.
