### ISSUE TITLE
Domain bidder.rtk.io seems to be serving Ad's

### ISSUE THREAD

**Issue by wavesailor** [StevenBlack/hosts#1097]
The domain Domain bidder.rtk.io ends up quite a bit in my logs now. As far as I can see this is a platform for serving Ads.

**Comment by llacb47** [comment]
Here's one site it's on: `https://www.lared.cl/`

**Comment by wavesailor** [comment]
Does making a note of it here mean it will be added to the main blacklists?

**Comment by StevenBlack** [comment]
Hi @wavesailor  – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

I'll add this one to my ad-hoc domain list before the next release.

**Comment by spirillen** [comment]
That is at least added to https://github.com/BlackJack8/iOSAdblockList/blob/master/Hosts.txt#L587

And it is also confirmed here: https://urlscan.io/domain/bidder.rtk.io that it is used by *BLIIP* like `www.marketrealist.com`, `shark007.net/forum/index.php` etc.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/70592268-7a2f6100-1bd9-11ea-83af-dab46b75b036.png)

</details>

Thanks for sharing this @wavesailor i've added it to my matrix :smile: 

I also found these records other might be interested in

```
media.rtk.io
jita.rtk.io
sync.rtk.io
console.rtk.io
hexagram.rtk.io
login.rtk.io
bidder.rtk.io
thor.rtk.io
uk2.thor.rtk.io
nyc.thor.rtk.io
nj.thor.rtk.io
uk.thor.rtk.io
sfo.thor.rtk.io
bucket.rtk.io
grow.rtk.io
www.rtk.io
```

**Comment by StevenBlack** [comment]
Done!  Thanks @wavesailor and @spirillen.  Closing.
