### ISSUE TITLE
Interesting Google Ad not being blocked.

### ISSUE THREAD

**Issue by rjhancock** [StevenBlack/hosts#1100]
Found a page that seems like Google is bypassing the Little Snitch rules based on these hosts.

From what I can tell, there is javascript SOMEWHERE that seems to be creating a proxy then sending all requests through it vs using system host or being blocked by Little Snitch.

https://ww.9to5mac.com/2019/12/11/apple-dmca-iphone-encryption-tweet/

**Comment by llacb47** [comment]
The same technology is being used on `https://www-1.kansas.com/`. It proxies every request through the first-party server. The technology is apparently called Apomaya Adgain `https://apomaya.com/resources/data-sheets/AdGain.pdf` and is pending a patent `https://patents.google.com/patent/US20180189824A1/en`.

**Comment by rjhancock** [comment]
Interesting. Just reported that to Apple as a work around for ITP for the 3rd Party -> 1st Party redirection.

Not sure there is a way to block this from a hosts file but might be able to via a browser extension blocking the `data-aproxy-src` element but that would probably also disable the site.

**Comment by llacb47** [comment]
uBlock Origin fixes it via a scriptlet on `kansas.com`. I haven't reported `9to5mac.com` yet.

**Comment by spirillen** [comment]
That is actually scary reading you provide there @llacb47 :fearful: But thanks for sharing these concerns about our privacy in the future, and it will be a good question on how we in the future would find those transparent proxies to be able to block them on other than browsers by ex: the `data-aproxy-src` @rjhancock mentions.

**Comment by rjhancock** [comment]
I have noticed that disabling JavaScript on the site does prevent the proxy from working, but that is not a good long term solution.

I may have to look at the URL calls via Chrome to get a better idea what is going on. I'm fairly certain Apple will block it natively in Safari at some point but that doesn't solve the issue for others.

**Comment by rjhancock** [comment]
Looks like the latest Safari (13.1) released today blocks the method used by Apomaya. Tested both 9to5 and Kansas. Neither showed ads.

**Comment by llacb47** [comment]
What do you mean? Safari out of the box w/ no extensions on macOS? Their normal homepages didn't show ads, or just the redirected homepage served by Apomaya?

**Comment by rjhancock** [comment]
Safari, out of the box, no extension, on any page I went to on 9to5 Mac did NOT redirect to an Apomaya served page.

Note: I'm still using my LittleSnitch powered rules to block ads. Before it required disabling javascript and now it doesn't.

**Comment by llacb47** [comment]
Oh, well that (is / could be) because 9to5mac temporarily (?) removed the apomaya code from their site. It's still on 9to5google, `dronedj.com`, and `kansas.com`.

**Comment by rjhancock** [comment]
Damn. That's probably it then. ```Kansas.com``` I didn't see any ads, ```droned.com``` I did.
