### ISSUE TITLE
Whitelist OneDrive for Business / Office 365 domains

### ISSUE THREAD

**Issue by c0defre4k** [StevenBlack/hosts#1101]
These URLs need to be whitelistet as blocking them causes problems when connecting to OneDrive for Business. I have looked up the source of them and found them in "Steven Black's ad-hoc list". So I guess this is the right location for this issue?

* settings-win.data.microsoft.com
* v10.events.data.microsoft.com

According to these Links `settings-win.data.microsoft.com` is not used for telemetry data. Although `v10.events.data.microsoft.com` is also listed for telemetry data i can for sure say that it breaks the login to Ondrive for Business on my nas.
* https://docs.microsoft.com/de-de/windows/privacy/windows-endpoints-1903-non-enterprise-editions
* https://docs.microsoft.com/de-at/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fNetwork-requests-in-Office-365-ProPlus-eb73fcd1-ca88-4d02-a74b-2dd3a9f3364d

**Comment by llacb47** [comment]
I use organizational Office 365 and have no problems.

**Comment by spirillen** [comment]
According to the German [BSI](https://www.bsi.bund.de/) (Bundesamt für Sicherheit in der Informationstechnik) both domains are used for tracking

`v10.events.data.microsoft.com`
`settings-win.data.microsoft.com`

Source: http://wiki.mypdns.org/wiki/Domain/microsoft.com/Telemetry

**Comment by spirillen** [comment]
> Enable data sharing (Tracking/Spying)

> To enable data sharing, configure your proxy server to whitelist the following endpoints. You might need to get approval from your security group to do this.

`settings-win.data.microsoft.com` | Enables the compatibility update to send data to Microsoft.
`v10.events.data.microsoft.com` | Connected User Experience and Diagnostic component endpoint for use with Windows 10

Source: https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started#enable-data-sharing

**Comment by c0defre4k** [comment]
First of all thanks for your fast response!

Its interesting what microsoft understands under "dynamically updating its configuration". So I guess its OK to have these domains in that list. I'm going to manually whitelist them then.

I'm also not using an official client. My NAS maps that folder via WebDAV. And as microsoft doesn't offer some standard authentication everyone can use I have to use a proxy written node handlung that authentication.
