### ISSUE TITLE
Social network suggestion

### ISSUE THREAD

**Issue by Minteck** [StevenBlack/hosts#1102]
Hello,
I just want to suggest a social network: PinPages.

It's URL is https://pinpages.alwaysdata.net and should be added to the "social" block list.

Thanks.

**Comment by StevenBlack** [comment]
Thanks @Minteck.  Ping @Sinfonietta.

**Comment by Sinfonietta** [comment]
Hi @StevenBlack this is added in commit 4d2ff204fa1afe51e0b96f22dab3a4111c3b4ee7.

**Comment by StevenBlack** [comment]
Closing.
