### ISSUE TITLE
Windows 10 specific in-app Ad/Telemetry domains

### ISSUE THREAD

**Issue by Sumwunn** [StevenBlack/hosts#1106]
Hello, 

I've noticed three domains that popped on my Pi when I was mucking about with Windows 10 apps.

The first two are related to ads, and the third I'm guessing to be background in-app telemetry.
Blocking all three successfully blocked ads and did not appear to affect the apps I was using adversely in any way.

> adbroker.mp.dse.microsoft.com
> s10.adduplex.com
> rawtelemetry-east.servicebus.windows.net

It looks like adduplex is specific and that there may be "s5, s7," though I've only seen s10 in action. Since the domain itself belongs to the ad company AdDuplex, perhaps it should be blocked entirely?

Would https://github.com/FadeMind/hosts.extras be more appropriate for this?

Cheers

**Comment by spirillen** [comment]
Hi @Sumwunn thanks for sharing the information of your findings.

For your question about whether this is to be posted at @FadeMind list, I'll say post it everywhere you can find it as a good place. As broader it gets out, wider it is blocked.

I'm thankful for you sharing it, and as you can see I have blocked the 2 of 3 on domain level and the `adduplex.com` is blocked as wildcard. Not that I understand I didn't have this in either my list nor my RPZ zones is weird as it actually is old news, but never the less it's solved now.

Site note 1:
I have not been able to confirm that s5,s7.adduplex.com should be alive

Site note 2:
You can't block a domain entirely with a hosts file, this would require a DNS recursor, you could ex. read a bit more about that in this issue https://github.com/StevenBlack/hosts/issues/1057 and pick up some ideas :smiley: :santa:

**Comment by FadeMind** [comment]
@Sumwunn  @StevenBlack  Better place for this is https://github.com/crazy-max/WindowsSpyBlocker/issues

@crazy-max could you lookin at?? Thanks
