### ISSUE TITLE
Please take a look at https://lab.deep.bg/hosts.txt

### ISSUE THREAD

**Issue by braian87b** [StevenBlack/hosts#1107]
I found that hosts file, maybe it has some useful listings like facebook or so.
https://lab.deep.bg/hosts.txt

**Comment by StevenBlack** [comment]
Hi Brain @braian87b thanks for this.

Do you have any information on this outfit?  The domain default document serves something that looks parked.  Is there any cred here?

Another curious thing.  We've gone years and I don't think we've ever seen an `autodesk.com` domain listed here.  But of the 404 domains in this file, over 100 of them are for subdomains of `autodesk.com`.

So, it's weird?  What do you think?

**Comment by yspmedia** [comment]
the "x.gtld-servers.net" are the authoritative servers for the "com" top level domain, so they have all the "pointers" for the .com domains. You can see the nameservers for the TLD by running

```
$ dig @a.root-servers.net com. NS +noall +auth
com.                    172800  IN      NS      a.gtld-servers.net.
com.                    172800  IN      NS      b.gtld-servers.net.
com.                    172800  IN      NS      c.gtld-servers.net.
com.                    172800  IN      NS      d.gtld-servers.net.
com.                    172800  IN      NS      e.gtld-servers.net.
com.                    172800  IN      NS      f.gtld-servers.net.
com.                    172800  IN      NS      g.gtld-servers.net.
com.                    172800  IN      NS      h.gtld-servers.net.
com.                    172800  IN      NS      i.gtld-servers.net.
com.                    172800  IN      NS      j.gtld-servers.net.
com.                    172800  IN      NS      k.gtld-servers.net.
com.                    172800  IN      NS      l.gtld-servers.net.
com.                    172800  IN      NS      m.gtld-servers.net.
```

```
0.0.0.0 a.gtld-servers.net
0.0.0.0 b.gtld-servers.net
0.0.0.0 c.gtld-servers.net
0.0.0.0 d.gtld-servers.net
0.0.0.0 e.gtld-servers.net
0.0.0.0 f.gtld-servers.net
0.0.0.0 g.gtld-servers.net
0.0.0.0 h.gtld-servers.net
0.0.0.0 i.gtld-servers.net
0.0.0.0 j.gtld-servers.net
0.0.0.0 k.gtld-servers.net
0.0.0.0 l.gtld-servers.net
```

It not even close to cleaver or intelligent to block the com. root servers..... But if you love FP's and blocking the entire com. domain, go ahead

**Comment by StevenBlack** [comment]
Thanks @yspmedia.  Eyeballing the file, I missed that.

Closing.

**Comment by rjhancock** [comment]
Also look at the header. It's a hosts file to hold a company hostage.

"No Pay[in] No gain"

**Comment by braian87b** [comment]
Sorry I didn't see it well, I just was searching for facebook/fbcdn.net domains hosts file and that file appeared.
