### ISSUE TITLE
Why is cliqz blocked? They're a privacy focused webbrowser with ties to mozilla

### ISSUE THREAD

**Issue by thalessa** [StevenBlack/hosts#1108]
the company: https://0x65.dev

the browser (blocked): https://cliqz.com/

Mozilla Firefox used to ship with cliqz plugins: https://en.wikipedia.org/wiki/Cliqz

Have they turned bad?

**Comment by StevenBlack** [comment]
Hi @thalessa all `cliqz.com` domains come to us via [Badd-Boyz-Hosts](https://github.com/mitchellkrogza/Badd-Boyz-Hosts/issues).  Can you raise this issue there?  Thanks.

Ping Mitchell @mitchellkrogza!

**Comment by konark-cliqz** [comment]
Hi,

My name is Konark and I work with Cliqz.

We've added some details on an issue already opened about this on Badd-Boyz-Hosts.

You can find more details:
https://github.com/mitchellkrogza/Badd-Boyz-Hosts/issues/34#issuecomment-567894266

**Comment by funilrys** [comment]
Hey Steve @StevenBlack,

Please close. As I personally fixed this. Please report to the following:

* **My** Statement: https://github.com/mitchellkrogza/Badd-Boyz-Hosts/issues/34#issuecomment-568187665
* Addition to whitelist list: https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/005fb4fb0288af0a4e284b6bd7beff81df93fb0f
* Deletion confirmation: https://github.com/mitchellkrogza/Badd-Boyz-Hosts/blob/36d27993433047e5546159fe5a3c28249d625053/hosts#L660-L728
* For history: https://github.com/mitchellkrogza/Badd-Boyz-Hosts/issues/34

Note: It's not closed that @mitchellkrogza will review my decision in the coming weeks/months. But for now, it's whitelisted.

**Comment by StevenBlack** [comment]
Awesome.  Thanks Nissar.
