### ISSUE TITLE
listed / commented conflicts

### ISSUE THREAD

**Issue by braian87b** [StevenBlack/hosts#1109]
Hi, I just seeing the merged file:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
if you find (ctrl+f) 
`googletagservices`

there is found these lines:

```
0.0.0.0 googletagservices.com
0.0.0.0 www.googletagservices.com
#0.0.0.0 www.googletagservices.com		#interferes with techrepublic
```
So... how we should deal with these?, I suggest to add to the script a search to `interferes` comment and those domain remove them from the file.

**What do you think?**

Same for these...
```
0.0.0.0 googletagmanager.com
0.0.0.0 www.googletagmanager.com
# 0.0.0.0 www.googletagmanager.com #[affects ASUS]
```
for googleanalytics and analytics google if people actually wants them working, like me, it also need googletagmanager, since as far I know googletagmanager is a tool to have a single tag on sites to send statistics to tagmanager and not to deal putting and removing several tracking tags on sites. etc... right?

**Comment by StevenBlack** [comment]
Hi Braian @braian87b, grepping this we see a broad consensus about this.  Several sources agree, block this.

```
data/mvps.org/hosts
5877:0.0.0.0 www.googletagservices.com

data/someonewhocares.org/hosts
905:0.0.0.0 googletagservices.com
2023:#0.0.0.0 www.googletagservices.com		#interferes with techrepublic

data/StevenBlack/hosts
100:0.0.0.0 www.googletagservices.com

data/tiuxo/hosts
2094:0.0.0.0 www.googletagservices.com

data/yoyo.org/hosts
1743:0.0.0.0 googletagservices.com
```

**Comment by braian87b** [comment]
Interesting way to evaluate it, by concensus...
Do you have it at hand necessary commands for grep multiple sources at a time for evaluating like that?

It will be handy to me.

**Comment by StevenBlack** [comment]
@braian87b  I use [ack](https://beyondgrep.com/install/) on the repo root.

**Comment by spirillen** [comment]
My good how hard is it ???


`grep -Ri 'domain\.tld' path/to/search`

in this case `grep -Ri 'googletagservices.com' data/`

**Comment by StevenBlack** [comment]
@spirillen consider this is an official warning: you will be nice to visitors here, or YOU will not be here.

**Comment by braian87b** [comment]
Sorry, I forget about grep -Ri I actually used several times months ago.
Thanks.

**Comment by spirillen** [comment]
Why not just answer the users straight up? 

@braian87b asked straight up 
> Do you have it at hand necessary commands for grep multiple sources at a time for evaluating like that?

That what I answered him. But you obviously have a huge issue about other, and you are close to be reported for harassment @StevenBlack

**Comment by braian87b** [comment]
Relax both of you, no problem at all, I am accustomed to several kind of responses like the ones that Linus Torvals usually use, this is nothing in comparision.

**Comment by StevenBlack** [comment]
Notes:
* The first notification was [here](https://github.com/StevenBlack/hosts/issues/1103#issuecomment-566112829)
* Official warning is [here above](https://github.com/StevenBlack/hosts/issues/1109#issuecomment-567653161).
* December 19, 2019 4:20 PM blocked.

**Comment by yspmedia** [comment]
So the one providing the actual [answer](https://github.com/StevenBlack/hosts/issues/1109#issuecomment-567652521) to the [question](https://github.com/StevenBlack/hosts/issues/1109#issuecomment-567617543), is the one who is getting blocked??
