### ISSUE TITLE
Is there a preferred way to suggest missing hosts?

### ISSUE THREAD

**Issue by mehov** [StevenBlack/hosts#1112]
I noticed one of the tracking companies started using a different domain than they did before. It is not on your list right now. 

Is there a preferred way to suggest that host for inclusion, or should I just make a pull request? If so - are there any requirements (e.g. specific branch, comments, etc.)?

Checked [the wiki](https://github.com/StevenBlack/hosts/wiki) and [the existing issues](https://github.com/StevenBlack/hosts/issues?page=4&q=suggest&utf8=%E2%9C%93).

**Comment by StevenBlack** [comment]
Hi Alex @mehov, we're mostly an aggregator of [existing lists](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant) so, ideally, the submission should be made with one of these providers.

However it's also OK to fork this repo, add the domain(s) to [my ad-hoc list](https://github.com/StevenBlack/hosts/blob/master/data/StevenBlack/hosts) which is in the [StevenBlack](https://github.com/StevenBlack/hosts/tree/master/data/StevenBlack) data folder.  From there, I'll entertain a pull request.

**Comment by mehov** [comment]
Hi, 

I found a host that needs to be corrected. It's listed under this headline:

> # Spyware and user tracking
> # By entering domains here, it will prevent certain companies from
> # gathering information on your surfing habits. These servers do not
> # necessarily serve ads, instead some are used by certain products to
> # "phone home". Others use web cookies to gather statistics on surfing 
> # habits. Among other uses, this is a common tactic by spammers, to 
> # let them know that you have read your mail. 
> # Uncomment (remove the #) the lines that you wish to block, as some
> # may provide you with services you like.

I checked the [providers from your link](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant) but couldn't find it.

**Comment by StevenBlack** [comment]
Hi Alex @mehov, we already list `www.addtoany.com`.


```
$ ack addtoany
alternates/fakenews/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/fakenews-gambling/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/fakenews-gambling-porn/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/fakenews-gambling-porn-social/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/fakenews-gambling-social/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/fakenews-porn/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/fakenews-porn-social/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/fakenews-social/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/gambling/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/gambling-porn/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/gambling-porn-social/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/gambling-social/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/porn/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/porn-social/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

alternates/social/hosts
5814:0.0.0.0 www.addtoany.com
39644:# [addtoany.com]
39645:0.0.0.0 stats.addtoany.com

data/adaway.org/hosts
638:# [addtoany.com]
639:127.0.0.1 stats.addtoany.com

data/someonewhocares.org/hosts
1977:0.0.0.0 www.addtoany.com

hosts
5813:0.0.0.0 www.addtoany.com
39643:# [addtoany.com]
39644:0.0.0.0 stats.addtoany.com
```

**Comment by llacb47** [comment]
> Hi,
> 
> I found a host (`static.addtoany.com`) that needs to be added

**Comment by AnonymousPoster** [comment]
as @llacb47 ask, how does `stats.addtoany.com` becomes equal `static.addtoany.com`? do you actually read the questions?

**Comment by llacb47** [comment]
@AnonymousPoster are you a sockpuppet for @spirillen? Yes or no?
