### ISSUE TITLE
distinguish "vortex-win.data.microsoft.com"

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1113]
While _v10c.vortex-win.data.microsoft.com_ is for Diagnostics data Telemetry, the domain _de.vortex-win.data.microsoft.com_ is for **Microsoft Defender Advanced Threat Protection** - while the prefix (in this case ".de") is country specific.

So please remove

- vortex-win.data.microsoft.com

from your list.

Source: https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#endpoints

**Comment by StevenBlack** [comment]
Hi @beerisgood again, the `vortex-win.data.microsoft.com` domain comes to us via someonewhocares.org.  You can reach them at hosts@someonewhocares.org and make your case there.

Closing.

**Comment by beerisgood** [comment]
Done. Let's see what the author say

**Comment by beerisgood** [comment]
The author fix it!

**Comment by StevenBlack** [comment]
@beerisgood [release 2.5.37](https://github.com/StevenBlack/hosts/releases/tag/2.5.37), online now, incorporates these changes.

Thank you for your effort on this.
