### ISSUE TITLE
settings-win.data.microsoft.com

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1114]
**settings-win.data.microsoft.com** is needed for Microsoft Defender Advanced Threat Protection.

So please unblock it.
Source: https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#endpoints

**Comment by StevenBlack** [comment]
Hi @beerisgood the `settings-win.data.microsoft.com` domain comes to us via someonewhocares.org.  You can reach them at hosts@someonewhocares.org and make your case there.

Closing.

**Comment by beerisgood** [comment]
Done. Let's see what the author say

**Comment by beerisgood** [comment]
The author fix it!

**Comment by StevenBlack** [comment]
Thanks @beerisgood!  Beer IS good.
