### ISSUE TITLE
hosts/alternates/fakenews-gambling

### ISSUE THREAD

**Issue by mikko70** [StevenBlack/hosts#1116]
Please add:
mrjackpotspins.com, .cashstormslots.com, pikakasino.com, kalevalakasino.com, simppeli.com, wildz.com, kassu.com, campaign.rizk.com, fi.casiplay.com, in.casinoeuro.com, pelaa.com, fastbet.com, casinogods.com. kirsikka.com, slottyvegas.com, fortunelegends.com, promotions.betsafe.com, casinowinner.com, turbico.com, suomikasino.com, templenile.com, stakes.com, jackpotvillage.com, prontocasino.com, nopeampi.com, fi.888casino.com, karhukasino.com, start.duelz.com, promotion.eurolotto.com, hypercasino.com, wishmaker.com, kasinot.fi

**Comment by mikko70** [comment]
All are Gambling sites.

**Comment by llacb47** [comment]
@sinfoetta

**Comment by StevenBlack** [comment]
Thank you @mikko70, this is live and online now in [the latest release](https://github.com/StevenBlack/hosts/releases/tag/2.5.39).

Closing.
