### ISSUE TITLE
Support Android Flash From TWRP

### ISSUE THREAD

**Issue by alsyundawy** [StevenBlack/hosts#1119]
can you make this? like title

**Comment by StevenBlack** [comment]
Hi Harry @alsyundawy do you have technical details for this request?  Specifically, which domains?

**Comment by githubber101** [comment]
I think @alsyundawy is talking about a flashable file through recovery. But why though, when adaway and many solutions exist?

**Comment by AnonymousPoster** [comment]
@githubber101 adaway is adware and spyware :+1:

**Comment by alsyundawy** [comment]
adaway need root, but i am stick only use twrp as  boot recovery only for flashed img or zip only

**Comment by githubber101** [comment]
> adaway need root, but i am stick only use twrp as boot recovery only for flashed img or zip only

then there is nebula, netguard, blokada. or if you use android 9+, there is DNS providers like LibreDNS, dnswarden etc. Seriously, all options are one search away.
@AnonymousPoster , What??

**Comment by StevenBlack** [comment]
Seeing no actionable information arising, I'm closing this.

Harry @alsyundawy if you find out what domains are involved here, then we may be able to help.
