### ISSUE TITLE
malware Domain list seems to be down

### ISSUE THREAD

**Issue by FatnLazy** [StevenBlack/hosts#1124]
Hi Team,

it seems like Malware Domain List is down, is there some kind of technical maintenance?

**Comment by StevenBlack** [comment]
It's still down.

**Comment by Laicure** [comment]
down and.. out-dated?
Are they still updating the list?
Last timestamp (afair) was Feb 2018?

**Comment by StevenBlack** [comment]
I think you're right Laicurè @Laicure.

**Comment by durablenapkin** [comment]
Relates to #1044

**Comment by FatnLazy** [comment]
they web is up and running again
