### ISSUE TITLE
Commit 4fa04707 killed AdGuard Pro's VPN connectivity

### ISSUE THREAD

**Issue by williamli** [StevenBlack/hosts#1125]
@StevenBlack Your list works fine till around Jan 14th's update. 
Currently (after Jan 15th's update), it made AdGuard Pro's VPN connection (on iOS) to never successfully connect (works fine previously).

The list URL is https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by StevenBlack** [comment]
Hi William @williamli  I don't use AdGuard so you'll have to help me out.  Which domain is causing an issue here?

**Comment by williamli** [comment]
@StevenBlack AdGuard Pro's on-device DNS VPN gave up after a recent list update.

I can try to feed it various recent list updates to see at which version it killed the VPN.

**Comment by williamli** [comment]
## Tested using as AdGuard Pro's DNS Filters 

✅ https://raw.githubusercontent.com/StevenBlack/hosts/78e2c456dbafb402ced5b100be08e89538f61c5a/hosts

✅ https://raw.githubusercontent.com/StevenBlack/hosts/7460a11664e376fd73f53d9725e3a87abb30cb23/hosts

❌ https://raw.githubusercontent.com/StevenBlack/hosts/4fa04707f2a73682ae22a580a5463cad4ecd6c98/hosts


## Conclusion

@StevenBlack AdGuard Pro uses the `/hosts` file of this repo. After the most recent revision of of the `/hosts` file (https://github.com/StevenBlack/hosts/commits/master/hosts) at commit https://github.com/StevenBlack/hosts/commit/4fa04707f2a73682ae22a580a5463cad4ecd6c98#diff-85cf4e6d42a71e693fd780c8b29accdd , the list can no longer be used by AdGuard Pro.

**Comment by StevenBlack** [comment]
William @williamli hmmm... that commit contains a very large update by [adAway](https://adaway.org/).  Are you on Android, perchance?  The Adaway issues are located here: https://github.com/AdAway/AdAway/issues.

**Comment by williamli** [comment]
I don't have access to Android at this moment.
I am going to try to do a diff between the two files and see if I can work out why your list killed AdGuard.

**Comment by StevenBlack** [comment]
Sorry William @williamli the answer to my question was buried in the issue title.

**Comment by bigdargon** [comment]
@williamli Adguard Pro's VPN is limited by iOS, adding too many hosts will result in a VPN crash (Limited to about 50k rules). Therefore, I recommend that you use a rule like AdguardSDN built into Adguard Pro. Or use the hostsVN project I'm developing which is fully compatible with Adguard Pro.

Github: https://github.com/bigdargon/hostsVN

Link for Adguard Pro: https://raw.githubusercontent.com/bigdargon/hostsVN/master/filters/adservers-all.txt

**Comment by williamli** [comment]
Thanks for the tip @bigdargon.

Just confirmed this by only loading the additions that came in via 4fa04707 updates https://gist.githubusercontent.com/williamli/ff947e815c3258b95a037770f77881f2/raw/2afc186fa63e2ca6d8851045bbd7d1d8122d7f26/StevenBlack%2520-%2520hosts%25204fa04707%2520additions

The additions loaded fine (while under 50k).

**Comment by StevenBlack** [comment]
William @williamli and @bigdargon we've been over the 50k domain threshold before... I'm skeptical that the 50k number is the problem.  But I've been wrong many times before 😄

**Comment by williamli** [comment]
@StevenBlack Some users claim it can be used, some are saying there is a 50K limit https://forum.adguard.com/index.php?threads/can-i-use-both-adguard-pro-free-to-bypass-50k-filter-limit.29415/

Maybe we will see what the official AdGuard Team has to say about it at https://github.com/AdguardTeam/AdguardForiOS/issues/1416 🤷🏽‍♂️

**Comment by bigdargon** [comment]
@williamli You can track this https://github.com/AdguardTeam/AdguardForiOS/issues/1298

@StevenBlack The limit may be less or more, but most rules above 50k easily crash vpn.  Some applications that support the wildcard format help with this.

Adblock version 4.2.1 also supports wildcards (including hostsVN) https://apps.apple.com/vn/app/adblock/id691121579

**Comment by StevenBlack** [comment]
Thanks @bigdargon and @williamli, I'll stand-by.

I could revert the AdAway commit, but I'd rather not because, for the most part, it's a solid upgrade.  Let's wait and see what suggestions come from AdGard.

**Comment by bigdargon** [comment]
@StevenBlack iOS devices that use the host format will waste device resources. Fortunately some apps have developed rules-based domain blocking (like Adguard Pro) and wildcards (like Adblock).

For example, 
- With the domain name `doubleclick.net`, the host format will have to list all subdomains.
- But with rule format, it only takes 1 line `||doubleclick.net^` to block all subdomains.
- Or with the wildcard format, with a line of rules ` abc-*.com `, it will include the domain `abc-123.com` and `abc-xyz.com`.
