### ISSUE TITLE
api.particle.io is part of your list

### ISSUE THREAD

**Issue by No1089** [StevenBlack/hosts#1128]
Hi,

I don't see a way to request a removal of a URL.
api.particle.io is currently part of your list and I cannot trace either the source or date of addition. A bunch of users are unable to log in as a result and have to manually whitelist the url.

Thanks!
Chris

**Comment by No1089** [comment]
adaway.org is the source of the block.
We would appreciate early removal from your aggregate list.
https://github.com/AdAway/AdAway/issues/1570

**Comment by StevenBlack** [comment]
Let's see what AdAway responds, Chris @No1089.  I'm standing-by.

**Comment by Oarcinae** [comment]
+1 from me. It took down some of my home automation and took me awhile to figure out what was going on.

Kind of sucks not being able to open my garage door while on WiFi due to a blocklist update lol...

Thanks!

**Comment by No1089** [comment]
@StevenBlack We have had no response from AdAway as of yet, not even an acknowledgement.

This block merely affects our platform. api.particle.io does not serve any ads or does any form of tracking. We believe this was added erroneously.

**Comment by StevenBlack** [comment]
Give it a few more hours, Chris @No1089...

**Comment by StevenBlack** [comment]
This is now resolved, and packaged in [Release 2.5.46](https://github.com/StevenBlack/hosts/releases/tag/2.5.46), online now.

Thanks everybody.

Closing.
