### ISSUE TITLE
api.mobile.immobilienscout24.de

### ISSUE THREAD

**Issue by EggyM** [StevenBlack/hosts#1129]
Please remove entry:
0.0.0.0 api.mobile.immobilienscout24.de

If this domain is blocked, the Android app ImmobilienScout24 does not work any longer.

I whitelisted it anyway, but it is a little bit annoying to whitelist domains that are not in general for adds.

**Comment by StevenBlack** [comment]
Hi @EggyM thak you for this.

Advertising is not the only criteria.

The `immobilienscout24.de` domain comes to us via mvps.org.  You can petition for its removal by contacting winhelp2002@gmail.com.

Closing.

**Comment by AnonymousPoster** [comment]
That's not true, it comes from AdAway

```
git blame data/mvps/domain.list | grep 'api.mobile.immobilienscout24.de'
git blame data/adaway/domain.list | grep 'api.mobile.immobilienscout24.de'
^532fc11 data/mobileadtrackers/domain.list (Spirillen 2019-10-19 05:58:39 +0200  2306) api.mobile.immobilienscout24.de
```
