### ISSUE TITLE
A hostname to add

### ISSUE THREAD

**Issue by i336** [StevenBlack/hosts#113]
I'm not sure if you take hostname additions, but this is a really awesome project, I wanted to contribute, and I see you have your own small list :)

I don't use an in-browser adblocker, instead relying soley on the hosts file; it catches almost everything, but it currently isn't blacklisting

    s.zkcdn.net

which Reddit seems to be using for some of their on-site advertising (for subreddits, etc).

I don't mind this, but I've seen the *same* AMA ad on like the last 50 consecutive pages I've visited now... :bomb:

**Comment by FadeMind** [comment]
@i336 
Simply add hosts file from hosts-file.net
Here it is:

    [tomasz@arch ~]$ cat /etc/hosts|grep zkcdn.net
    0.0.0.0 s.zkcdn.net
    [tomasz@arch ~]$ cat .hup/hosts/data/hosts-file.net/hosts |grep zkcdn.net
    127.0.0.1       s.zkcdn.net
    [tomasz@arch ~]$

**Comment by i336** [comment]
Wow, that hosts file is *massive*. Merged! :D

I discovered the MVPS hosts file a few years ago, and stuck with that until I learned of this little project on Hacker News. I had no idea you could get files this comprehensive.

Thanks for this info!

**Comment by FadeMind** [comment]
@i336 yes.

![screenshot_20160319_142458](https://cloud.githubusercontent.com/assets/9846948/13898800/6010ad24-edde-11e5-87cd-c9855482c56f.png)
**ORIG. SIZE: 11,6 MB**
**XZ TARBALL: 1,9 MB**
`$ sha1sum *.xz`
`5a6990d4c128339293fda7c3c2d13d9526b68094  hosts.tar.xz`
`$ sha1sum *.zip`
`b17c7345d5bbdcedbcf74b3daf943cef00895e62  hosts.tar.xz.zip`

**Comment by StevenBlack** [comment]
Thanks @i336 !

**Comment by i336** [comment]
Aaand I'm now also using the hosts file you put together (wow, nearly 400k lines). Thanks!
