### ISSUE TITLE
Globo Play videos (brazilian tv streaming service) are blocked by glbimg.com hosts 

### ISSUE THREAD

**Issue by choice77** [StevenBlack/hosts#1130]
Site navigation https://globoplay.globo.com/ works well, but videos don't load.

If i removed the hosts bellow, the videos works well.

# [glbimg.com]
0.0.0.0 e.glbimg.com
0.0.0.0 i.glbimg.com
0.0.0.0 p.glbimg.com
0.0.0.0 v.glbimg.com

Tested on Samsung TV, Mobile Devices, Pc-Desktop

**Comment by dnmTX** [comment]
@choice77  those domains are blocked by AdAway. It's recommended to open a [issue](https://github.com/AdAway/adaway.github.io/issues) there and discuss it with the curators of the lists.

**Comment by choice77** [comment]
> @choice77 those domains are blocked by AdAway. It's recommended to open a [issue](https://github.com/AdAway/adaway.github.io/issues) there and discuss it with the curators of the lists.

Thanks,  dnmTX! I will do that!

**Comment by jawz101** [comment]
removed in Adaway

**Comment by choice77** [comment]
Thanks, jawz101! Problem solved!
