### ISSUE TITLE
mx.yandex.ru in host file

### ISSUE THREAD

**Issue by toxot** [StevenBlack/hosts#1131]
Hello, can u remove this record? its actually mail server, so i haven't idea why we should block it.

**Comment by StevenBlack** [comment]
Hi Artem @toxot, the `mx.yandex.ru` domain comes to us via AdAway, one of the sources of our hosts.

You can reach AdAway on their [Github Issues page](https://github.com/AdAway/AdAway/issues).

**Comment by jawz101** [comment]
removing.  Thanks
