### ISSUE TITLE
distributions-crashlytics-com.s3.amazonaws.com needed by Firebase App Distribution

### ISSUE THREAD

**Issue by gadgetchnnel** [StevenBlack/hosts#1132]
The domain distributions-crashlytics-com.s3.amazonaws.com has been added to this blocklist, but this is used by [Firebase App Distribution](https://firebase.google.com/docs/app-distribution l) and is preventing the download of beta apps via this.

**Comment by AnonymousPoster** [comment]
Isn't Firebase all about Google tracking/spying through out "apps" baits?

**Comment by StevenBlack** [comment]
Hi Steven @gadgetchnnel, the `distributions-crashlytics-com.s3.amazonaws.com` domain comes to us via AdAway, one of the sources of our hosts.

You can reach AdAway on their [Github Issues page](https://github.com/AdAway/AdAway/issues).  Can you please post this issue there?  Thanks.

**Comment by jawz101** [comment]
removing.  Thanks.  I've started visiting the StevenBlack issue tracker occasionally to catch the Adaway false positives.
