### ISSUE TITLE
apprep.smartscreen.microsoft.com

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1134]
*.smartscreen.microsoft.com* is used for Windows Defender Smartscreen which is a security feature and not telemetry.

Please unblock it.

https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1903-non-enterprise-editions

**Comment by StevenBlack** [comment]
@beerisgood comes to us via someonewhocares.org.  This is an upstream source.

Please submit this request to hosts@someonewhocares.org.

**Comment by beerisgood** [comment]
Done

**Comment by beerisgood** [comment]
It's fixed.
Thanks
