### ISSUE TITLE
mobile.impacttestonline.com - Why is it blocked?

### ISSUE THREAD

**Issue by sgu222e** [StevenBlack/hosts#1138]
Just a quick question, we subscribe to your list and it works great, but recently is has blocked login to impacttestonline, which is valid. The url in question is called when a user logs into the online portal for ImPACT, which is used by health care professionals to assist with diagnosing concussions and brain injuries.
I've whitelisted it on my piholes, but wanted to drop a note that it probably shouldn't be blocked.

**Comment by ScriptTiger** [comment]
> data\adaway.org\hosts:# [impacttestonline.com]
> data\adaway.org\hosts:127.0.0.1 mobile.impacttestonline.com

This is coming from Adaway, an upstream source. Could you open an issue there?
https://github.com/AdAway/AdAway/issues

For the most part we just aggregate from upstream sources, we don't curate the lists. The only list we have control over is the locally curated `hosts/data/StevenBlack/hosts`.

**Comment by sgu222e** [comment]
Will do, Thanks for the quick reply.
