### ISSUE TITLE
Do not block juiceplus.com

### ISSUE THREAD

**Issue by mwinker** [StevenBlack/hosts#1139]
juiceplus.com is nothing to be blocked, so please remove that entry from your hosts file (in the meanwhile, I added them to pihole's whitelist).

**Comment by StevenBlack** [comment]
@mwinker the `juiceplus.com` domain comes to us via KADhosts.  Can you please submit this issue with them?  Their issue page is https://github.com/PolishFiltersTeam/KADhosts/issues.

Hi Tomasz @FadeMind, can you comment?

**Comment by FadeMind** [comment]
About Kad please CC directly @krystian3w @hawkeye116477

**Comment by hawkeye116477** [comment]
This was blocked by @azet12. 

@xMaap https://github.com/PolishFiltersTeam/KAD/issues/784

**Comment by StevenBlack** [comment]
@krystian3w @hawkeye116477 @FadeMind thanks everybody.  Keep an eye on this, OK?

Closing.
