### ISSUE TITLE
Hosts file blocks images on jolse.com

### ISSUE THREAD

**Issue by vorkot11** [StevenBlack/hosts#1142]
Hello,
I am using the hosts file (adware + malware) and the last few versions have started blocking images on the Korean cosmetics site jolse.com, e.g. https://jolse.com/category/skincare/1018/. Is it possible to fix this?

Thanks,
Ia.

**Comment by AnonymousPoster** [comment]
Look for 

```
imgcdn1.poxo.com
akamai.poxo.com
```

**Comment by vorkot11** [comment]
Yes, this works, thank you.

**Comment by StevenBlack** [comment]
Hi @vorkot11 the `poxo.com` domains come to us from AdAway.

Hey @jawz101 can you take a look?

**Comment by jawz101** [comment]
done https://github.com/AdAway/adaway.github.io/commit/fcd731b861ab2b93c2f41e2154545cea01e2b781

**Comment by StevenBlack** [comment]
Thanks everybody.  This will be rectified in the next release, coming shortly.

Closing.
