### ISSUE TITLE
Consider including URLhaus domains

### ISSUE THREAD

**Issue by quinncomendant** [StevenBlack/hosts#1143]
URLhaus offers a hosts file containing only domains actively serving malware or added in the last 48 hours. It seems appropriate for merging in this project.

- text file download: https://urlhaus.abuse.ch/downloads/hostfile/
- documentation: https://urlhaus.abuse.ch/api/

**Comment by StevenBlack** [comment]
Thanks Quinn @quinncomendant — this is interesting.

I've sent an email to request permission to add this list.

**Comment by StevenBlack** [comment]
This is done in PR #1189!
