### ISSUE TITLE
TFC TV via Roku

### ISSUE THREAD

**Issue by santiagohl** [StevenBlack/hosts#1144]
This was recently added to the list of block domains ma345-r.analytics.edgekey.net  and it need to be removed as it breaks TFC tv programing via roku. for now I have added it to the white list so that we can watch TFC tv once again.

**Comment by AnonymousPoster** [comment]
You should add your complain to the devs behind tfc as they obviously have broken there product by adding [SpyWare](https://www.mypdns.org/wiki/SpyWare) to there sources and it is breaking the product

**Comment by santiagohl** [comment]
I appreciate your help and reaching out to me but I would need more than
the spyware definition to explain them the issues and why they need to
remove their tracker. Can you point me to the document that shows that the
service they are using to do analytics for their tv channel is a known
offender of privacy because that would really help to convince them to
chance analytics company.

**Comment by AnonymousPoster** [comment]
What's wrong with the link I posted? but alternatively `adaway/domain.list:ma345-r.analytics.edgekey.net` or the [wikipidia](https://en.wikipedia.org/wiki/Spyware)

```
grep -Ri '.analytics.edgekey.net' data/
data/hphosts_ad_servers/domain.list:79423.analytics.edgekey.net
data/hphosts_ad_servers/domain.list:ma180-r.analytics.edgekey.net
data/hphosts_ad_servers/domain.list:ma728-r.analytics.edgekey.net
data/adaway/domain.list:79423.analytics.edgekey.net
data/adaway/domain.list:ma102-r.analytics.edgekey.net
data/adaway/domain.list:ma1063-r.analytics.edgekey.net
data/adaway/domain.list:ma1120-r.analytics.edgekey.net
data/adaway/domain.list:ma1169-r.analytics.edgekey.net
data/adaway/domain.list:ma1226-r.analytics.edgekey.net
data/adaway/domain.list:ma1275-r.analytics.edgekey.net
data/adaway/domain.list:ma1288-r.analytics.edgekey.net
data/adaway/domain.list:ma1310-r.analytics.edgekey.net
data/adaway/domain.list:ma140-r.analytics.edgekey.net
data/adaway/domain.list:ma156-r.analytics.edgekey.net
data/adaway/domain.list:ma193-r.analytics.edgekey.net
data/adaway/domain.list:ma252-r.analytics.edgekey.net
data/adaway/domain.list:ma277-r.analytics.edgekey.net
data/adaway/domain.list:ma278-r.analytics.edgekey.net
data/adaway/domain.list:ma291-r.analytics.edgekey.net
data/adaway/domain.list:ma307-r.analytics.edgekey.net
data/adaway/domain.list:ma312-r.analytics.edgekey.net
data/adaway/domain.list:ma322-r.analytics.edgekey.net
data/adaway/domain.list:ma343-r.analytics.edgekey.net
data/adaway/domain.list:ma345-r.analytics.edgekey.net
data/adaway/domain.list:ma479-r.analytics.edgekey.net
data/adaway/domain.list:ma512-r.analytics.edgekey.net
data/adaway/domain.list:ma562-r.analytics.edgekey.net
data/adaway/domain.list:ma61-r.analytics.edgekey.net
data/adaway/domain.list:ma67-r.analytics.edgekey.net
data/adaway/domain.list:ma688-r.analytics.edgekey.net
data/adaway/domain.list:ma728-r.analytics.edgekey.net
data/adaway/domain.list:ma734-r.analytics.edgekey.net
data/adaway/domain.list:ma788-r.analytics.edgekey.net
data/adaway/domain.list:ma80-r.analytics.edgekey.net
data/adaway/domain.list:ma93-r.analytics.edgekey.net
data/adaway/domain.list:ma95-r.analytics.edgekey.net
data/mvps/domain.list:79423.analytics.edgekey.net
data/mvps/domain.list:ma156-r.analytics.edgekey.net
data/xorcan/domain.list:www.analytics.edgekey.net
```

```
dig axfr rpz.mypdns.cloud @axfr.ipv4.mypdns.cloud | grep 'analytics.edgekey.net'
*.analytics.edgekey.net.rpz.mypdns.cloud. 345600 IN CNAME .
analytics.edgekey.net.rpz.mypdns.cloud. 172800 IN CNAME .
```

And at last, how about this, which you wrote almost your self:

> Since you started to embed wellknown [spyware](https://en.wikipedia.org/wiki/Spyware) into your software and we do block wellknown analytics domains like `*.analytics.edgekey.net` we encounter breakage of over TFC-tv programing via roku.

There is plenty about the `analytics.edgekey.net` [online](https://duckduckgo.com/?q=%22analytics.edgekey.net%22&t=canonical&ia=web)

here is a link hits (tl;dr but fast skimming seems right)

`https://developer.akamai.com/tools/AdaptiveMediaPlayer/docs/web/amp-web-media-analytics/tutorial-1-overview.html`

The answer is that, a few searches, and you can gather enought prof for this point of view from various sources. One thing you have to keep in mind while searching for valid sources, is the criteria for (un-)safe ratings. ex. virustotal is only scanning for virus/trojans

**Comment by StevenBlack** [comment]
I think Anon @AnonymousPoster is right in this instance.

That said, `ma345-r.analytics.edgekey.net` comes to us via AdAway.  @jawz101 can you please take a look, and decide?  I'm happy either way.

Thanks everybody.

**Comment by jawz101** [comment]
removed.  It doesn't matter to me either way

**Comment by StevenBlack** [comment]
Thanks @jawz101.  Closing.
