### ISSUE TITLE
How to add to mobile devices without rooting

### ISSUE THREAD

**Issue by gonzobrains** [StevenBlack/hosts#1145]
Is there a way to update the hosts file on Android/iOS/other mobile devices without rooting?

**Comment by Laicure** [comment]
Not possible without root.
I just use DNS66 instead.

**Comment by moviuro** [comment]
@gonzobrains you can deploy the host files to a DNS server you control, and use that on your device ([first google result](https://devilbox.readthedocs.io/en/latest/howto/dns/add-custom-dns-server-on-android.html)). If you don't know how to do that, then use a hosted service that will do it instead (OpenDNS Family shield, or whatever else).

**Comment by jawz101** [comment]
NetGuard , Blokada, AdGuard, DNSfilter, DNS66

Many of these apps are on Fdroid and they all can use a blocklist such as a Stevenblack's

**Comment by StevenBlack** [comment]
Thanks everybody.  I'm closing this because, though informative, it's out of scope.
