### ISSUE TITLE
Automatically deploy hosts file to all machines on a network

### ISSUE THREAD

**Issue by gonzobrains** [StevenBlack/hosts#1146]
Is there a way to automatically deploy a new hosts file across all devices on a network?  If not, can the process be automated on a machine-by-machine basis?

**Comment by ScriptTiger** [comment]
If you're running Windows, yes:
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate

Basically you just put that script in a shared network location and it can manage all the machines on your network and keep their blacklists up to date, or even change to different blacklists at different times throughout the day if you want to allow some things before, during, or after certain times, whatever your needs are. The recommended way is to simply deploy it using a Schedule Task manged by an Active Directory Group Policy. However, the script itself doesn't require Active Directory and you could deploy it a number of other ways, as well, including on a machine-by-machine basis.

**NOTE: Please read the README before deploying it, as there are some special notes if you are deploying across a network from a shared network location. You should also be familiar with the command-line arguments before deploying it, as well, so you know how to correctly call the script from a Scheduled Task.**

**Comment by asocial-creep** [comment]
AcrylicDNS can do that too.

**Comment by ScriptTiger** [comment]
@asocial-creep, Acrylic DNS Proxy is a local caching DNS proxy server that does indeed come with a configuration file which they also call a "hosts file," a "custom hosts file" to be exact. Whenever the phrase "hosts file" is mentioned in this repository, however, it is referencing the standard default system hosts file that does not require any third-party software and is directly integrated into the operating system itself.

Also, I don't see anywhere in the Acrylic DNS Proxy documentation mentioning the ability to replicate the entries of either its own "custom hosts file" or the standard default system hosts file across systems. And to add to that, the Acrylic DNS Proxy is a local proxy server and is designed to serve queries only to the local machine and not to multiple machines across a network. So unless you are trolling, you are seriously confused about either what the Acrylic DNS Proxy is, what a hosts file is, or both.
