### ISSUE TITLE
Sling.com My Account login/webpage issue

### ISSUE THREAD

**Issue by Walker-TR** [StevenBlack/hosts#1148]
Unable to login to sling.com/account.  Get this error "An unexpected error has occurred." on webpage.

URL: https://oauth-client.p.sling.com/

Based off uBlock Orign log. This domain is being blocked causing the issue, tiqcdn.com^​

||tiqcdn.com^​--​ oauth-client.p.sling.com -- ​3 -- ​script -- ​https://tags.tiqcdn.com/utag/dish/sling/prod/utag.sync.js
||tiqcdn.com^​-- ​oauth-client.p.sling.com​ -- 3 -- ​script -- ​https://tags.tiqcdn.com/utag/dish/sling/prod/utag.js

Adding the domain, tags.tiqcdn.com, and , oauth-client.p.sling.com, to the whitelist has no effect.

Have to add a custom filter to allow it the website to load.

@@||tags.tiqcdn.com/utag/dish/sling/prod/utag.sync.js$script,domain=oauth-client.p.sling.com
@@||tags.tiqcdn.com/utag/dish/sling/prod/utag.js$script,domain=oauth-client.p.sling.com

Once you add the allow for it, the webpage loads and you can login.

**Comment by StevenBlack** [comment]
I'm confused.  Please resubmit something actionable, not a babbling stream of semi-consciousness.

Closing.
