### ISSUE TITLE
Please remove these urls

### ISSUE THREAD

**Issue by alfa-romero** [StevenBlack/hosts#1149]
I believe these urls were mistakenly added based on their close association to uconnect.tealiumiq.com. 

The following urls are actually used by FCA US LLC for their [Uconnect Mobile app](https://www.driveuconnect.com/uconnect-app.html) 

# [uconnectcar.com]
0.0.0.0 app3.prd.telematics.uconnectcar.com
0.0.0.0 app4.prd.telematics.uconnectcar.com

This is preventing the successful operation of the app on any network utilizing this host list. 

If you have questions please let me know.

**Comment by StevenBlack** [comment]
Hi Alf @alfa-romero the `uconnectcar.com` domains come to us from AdAway.

Hello @jawz101 can you please take a look, and decide?

**Comment by jawz101** [comment]
removed.

**Comment by StevenBlack** [comment]
Thanks @jawz101.  

@alfa-romero this will be corrected in the next release, later today.

Closing.
