### ISSUE TITLE
UNIFIED: One host not available

### ISSUE THREAD

**Issue by raziel-** [StevenBlack/hosts#115]
The "Unified Hosts" links on the main github page has one missing/unavailable link.
It's the Gambling-Porn-Social one wich triggers a 404:
https://raw.githubusercontent.com/StevenBlack/hosts/raw/master/alternates/gambling-porn-social/hosts

**Comment by StevenBlack** [comment]
Thanks @raziel- fixed!

**Comment by StevenBlack** [comment]
Note I fixed the URL, which is now 
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn-social/hosts
