### ISSUE TITLE
Import privacy-badger's blocking list ?

### ISSUE THREAD

**Issue by moodule** [StevenBlack/hosts#1150]
My [Privacy Badger](https://www.eff.org/privacybadger) from EFF has learnt to block hundreds of domains that weren't in my Pi-Hole blacklist.

What do you think of consolidating the blocking list the users ?

Or may-be run a web spider operating the privacy badger ?

**Comment by StevenBlack** [comment]
David @moodule what is the link to the actual list?  You've sent me on a goose-chase, with the link above ⬆️⬆️⬆️

**Comment by moodule** [comment]
sorry I thought you'd know it !!

the badger is a browser extension: it learns to block websites as you browse the web.

so every user of the extension will have his personal list of blocked domains, depending on where he went.

**Comment by StevenBlack** [comment]
Closing.
