### ISSUE TITLE
Amazon App Issue

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1152]
This host may cause the problem ->
amazon-adsystem.com

**Comment by ScriptTiger** [comment]
Just so we can be more thorough in helping you, can you be more specific as to why you think that specific domain is causing the problem? Were you using a separate application to monitor DNS calls and found that particular domain coming up a lot unresolved? Did you already test unblocking it and it resolves your issue? And can you be more specific as to what exactly "the problem" is, the specific "Amazon App Issue"? For example, is the app stalling out on the initial loading screen, are you having trouble with purchases, did you notice everything going slower in the app after implementing the blacklist, are you not able to sign into the app, etc., etc.?

**Comment by scafroglia93** [comment]
I tried to replicate the problem through the nextdns log, enabling the list of the amazon crasha app while viewing the articles by returning ooops with the classic dog

**Comment by scafroglia93** [comment]
![photo_2020-02-18_15-30-15](https://user-images.githubusercontent.com/8227101/74745316-027a5400-5264-11ea-8b84-3f1c19b02eb0.jpg)
![amazon](https://user-images.githubusercontent.com/8227101/74745319-03ab8100-5264-11ea-8c6f-a0f69fa51905.PNG)

**Comment by StevenBlack** [comment]
Hi @scafroglia93 the `amazon-adsystem.com` domain, and many related subdomains, come to us via five (5) different sources.

I don't think this is going to change.

Closing.
