### ISSUE TITLE
Can you explain how you use DNS66? 

### ISSUE THREAD

**Issue by prakhs123** [StevenBlack/hosts#1153]
Not possible without root.
I just use DNS66 instead.

_Originally posted by @Laicure in https://github.com/StevenBlack/hosts/issues/1145#issuecomment-585502226_

**Comment by Laicure** [comment]
Hey, this is out-of-scope in this repo but I will respond, just close this right away.

Use this [detailed guide](https://jonathansblog.co.uk/ad-blocking-on-android-using-dns666) to setup your DNS66.
Use/add this for your "HOSTS": `https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts`

**Comment by prakhs123** [comment]
I think its relevant as it is a way to enable "hosts" on android. Thanks.

**Comment by Laicure** [comment]
Then we will be endlessly talking about DNS66 and other apps just to enable "hosts" in android.
This is about hosts files not "how to deploy" and such.
You know... there's a [dns66 repo](https://github.com/julian-klode/dns66) where we can discuss this.

;)

**Comment by prakhs123** [comment]
Ok, so tell me where we should discuss about deploying "hosts" on android? @StevenBlack i suggest add something in read me, or tell me how should i search for things like how to deploy "hosts"

**Comment by StevenBlack** [comment]
Hi @prakhs123 and thanks Laicurè @Laicure.

I would certainly entertain a Pull Request to amend the [readme_template.md](https://github.com/StevenBlack/hosts/blob/master/readme_template.md) to include this information.
