### ISSUE TITLE
Reverse adblocker warning in spiegel.de

### ISSUE THREAD

**Issue by tiiiecherle** [StevenBlack/hosts#1155]
As spiegel.de was completely redesigned and relaunched blocking

`spiegel-de.spiegel.de`

leads to not being able to get passed the new options appearing on the website. Clicking accept leads to a warning that says it's not possible to save the needed cookie.

<img width="989" alt="549214" src="https://user-images.githubusercontent.com/7059936/74979323-b4657c00-542e-11ea-8693-5016a4bdbc20.png">

Reversing [#536](https://github.com/StevenBlack/hosts/issues/536) and therefore no longer blocking `spiegel-de.spiegel.de` makes the new accept button work again.

Thanks

**Comment by llacb47** [comment]
Use ublock origin, does it help?

**Comment by tiiiecherle** [comment]
> Use ublock origin, does it help?

There is no block origin for Safari on macOS. Adguard and Better are really good, but do not help here.

As stated above removing (or commenting out) `spiegel-de.spiegel.de` from /etc/hosts solves the problem.

**Comment by StevenBlack** [comment]
Thanks @tiiiecherle — I have removed `spiegel-de.spiegel.de` which comes to us via my own, ad-hoc list.

This will be reflected in the next release, shortly.

Closing.

**Comment by tiiiecherle** [comment]
Thanks, have a great weekend ;)
