### ISSUE TITLE
Misc ad & tracking domains

### ISSUE THREAD

**Issue by garbledos** [StevenBlack/hosts#1167]
I'm not sure if it's better to add these as an issue or pull request, but I'll try this first. Here is a list of ad and tracking domains seen in the wild that I propose are added to the list. So far, blocking these has not stopped the associated apps from functioning. 

#Misc websites
analytics-log.classlink.io
analytics.food.com
track.clevergadgets.co
arc.pixel.parsely.com

#Ubiquiti Unifi (trace.svc.ui.com is already in your list)
ping.ui.com

#Foxit - Windows
ad.foxitsoftware.com

#Plex Media Server - Various OS
analytics.plex.tv

#QNAP NAS
analytics.api.myqnapcloud.com ()

#Yelp app - Android
bunsen.yelp.com
bunsen-auditor.yelp.com

#Spotify app - Android
mc.tritondigital.com
traffic.omny.fm

#Canary Mail app - ios
pixels.canarymail.io

#Radiopublic app - ios
tracking.feedpress.it

#Part of ActiveCampaign email marketing
prism.app-us1.com
diffuser-cdn.app-us1.com

#Potential email marketing
path1.xtracloud.net
path2.xtracloud.net
path3.xtracloud.net

**Comment by StevenBlack** [comment]
Thank you for this, @garbledos.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Can you please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant)?  I have no knowledge of these domains, and I'm weary of adding a dozen domains I know nothing about.  Curators are better equipped for this.

Thanks!  Closing.
