### ISSUE TITLE
Flush DNS fails on Ubuntu 15.10

### ISSUE THREAD

**Issue by xHN35RQ** [StevenBlack/hosts#117]
Running the script fails when flushing DNS. For some reason these commands fail:

`sudo /etc/rc.d/init.d/nscd restart`
`sudo systemctl restart network.service`

And this one works:

`sudo systemctl restart networking.service`

Ubuntu 15.10 has the service running as `networking.service`

**Comment by StevenBlack** [comment]
Thanks @xHN35RQ Nick.

I'll look into this; I haven't had any issues and I'm using Ubuntu 15.10 in places so I'll try there.

**Comment by xHN35RQ** [comment]
I installed and configured `dnsmasq` so I can now use `sudo service dnsmasq restart` but it still fails in the script. I think the systemd locations are different on Ubuntu.

**Comment by StevenBlack** [comment]
@xHN35RQ how's that?

**Comment by StevenBlack** [comment]
Presuming this is fine.  Closing.

**Comment by xHN35RQ** [comment]
Ah sorry I didn't see the fix, missed it somehow. It will fail because `/usr/lib/systemd/system/networking.service` is not a location on the system.

**Comment by xHN35RQ** [comment]
Here's the output of service status networking:

```
service networking status
● networking.service - LSB: Raise network interfaces.
   Loaded: loaded (/etc/init.d/networking)
  Drop-In: /run/systemd/generator/networking.service.d
           └─50-insserv.conf-$network.conf
        /lib/systemd/system/networking.service.d
           └─systemd.conf
   Active: active (exited) since Tue 2016-03-29 16:52:07 PDT; 3 days ago
     Docs: man:systemd-sysv-generator(8)
  Process: 543 ExecStart=/etc/init.d/networking start (code=exited, status=0/SUCCESS)
```
So is `/etc/init.d/networking` the systemd service file? That seems odd.

**Comment by xHN35RQ** [comment]
Also for what it's worth, `service dnsmasq status`

```
service dnsmasq status
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: active (running) since Tue 2016-03-29 16:52:10 PDT; 3 days ago
  Process: 22190 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 790 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 765 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 701 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 788 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─788 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -r /var/run/dnsmasq/r...
```

So it looks like on Ubuntu 15.10 the systemd files are in `/lib/systemd/system/` and dnsmasq falls under that directory: `/lib/systemd/system/dnsmasq.service` but `networking.service` does not. This confuses me.
