### ISSUE TITLE
use-application-dns.net should not be 0.0.0.0 

### ISSUE THREAD

**Issue by dschaper** [StevenBlack/hosts#1172]
If the canary domain for Firefox returns an A or AAAA record then DoH is enabled in Firefox. 

Can this domain please be removed from the list? It overrides the Pi-hole canary disable function to have it on the hosts list.

**Comment by luzat** [comment]
For reference, explanation of the domain usage: https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet

**Comment by StevenBlack** [comment]
Thanks Dan @dschaper — the domain `use-application-dns.net` comes to us via AdAway.

@jawz101 can you please take a look at this, and advise?  Thanks!

**Comment by StevenBlack** [comment]
Whoops @jawz101 thanks, I see that's fixed already.

Keep one step ahead of me, I like that 😄 

Dan I'm going to spin a fresh release right now.

Closing.
