### ISSUE TITLE
cdn.trackjs.com

### ISSUE THREAD

**Issue by enguerran** [StevenBlack/hosts#1173]
Hi,

I recently installed a pi-hole on my local network and discovered a broken website https://tajinebanane.fr/. This is a shopify website and cdn.trackjs.com is needed to choose a delivery point.
I did some research on trackjs.com services. I understood well that it could trace many user behaviors when browsing websites, however I wonder if the blocking of the cdn.trackjs.com sub-domain is not overestimated since it obviously only serves static files (probably tracing the request otherwise).
I didn't find any complaints on the different sites (your github repository or pi-hole's discourse), but I saw that some domains like twitter analytics were unblocked due to malfunctions on the twitter site.
So I'm just asking the question: have other users had problems with broken sites because of the blocking of this domain?
Thank you for your work that I'm just discovering and good luck with the management of this issue.

**[edit]** github suggests me similar issues, and by following the white rabbit, I get to https://github.com/StevenBlack/hosts/issues/785#issuecomment-423130893 then to https://github.com/lightswitch05/hosts/commit/6a256c58cc46b43e5961373c3e5640743c178932#commitcomment-29582245 that explains probably the same concern as for ravenjs than for trackjs.com.
I kept the issue on your repository to help people finding a way to understand why trackjs.com is blocked.

> I'm a big fan of the EFF's DNT Privacy Policy. If you can update your privacy policy in accordance with the EFF's, then I could be convinced to remove it from the list.

Hey, I'm a big fan too! If the developers of trackjs.com pass by here, please take a look at this site: https://www.eff.org/dnt-policy

**Comment by StevenBlack** [comment]
Hi @enguerran!  The domain `cdn.trackjs.com` comes to us via mvps.org, which is a well-respected and reliable curator of hosts.

Please report this to their email: winhelp2002@gmail.com

From past experience, we can trust the people at mvps.org to do the right thing.

They are due to release an update soon so, if you hurry, maybe your appeal can land before they brew their next release.

Let me know how this turns out!

Closing.
