### ISSUE TITLE
Including channelwebsdks.azureedge.net breaks Windows 10 Quick Assist

### ISSUE THREAD

**Issue by moved-to-gitlab** [StevenBlack/hosts#1177]
The domain `channelwebsdks.azureedge.net` is included by default and [originates from the AdAway blocklist](https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt). That may make sense for their Android app but it prevents the Windows 10 "Quick Assist" app from connecting.

Can this domain be whitelisted please?

Here is a link to Microsoft's documentation confirming that URL is among those required for Quick Assist: https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-ready/network?view=o365-worldwide

**Comment by StevenBlack** [comment]
@jawz101 can you please take a look at this? Thank you, as always.

**Comment by jawz101** [comment]
removed

**Comment by StevenBlack** [comment]
Thanks @jawz101.  Closing.
