### ISSUE TITLE
ns.exitgames.com

### ISSUE THREAD

**Issue by danieljudd** [StevenBlack/hosts#1178]
This seems to be blocking some game servers such as "Bloody Trapland".

The URL belongs to https://www.photonengine.com/ which lists a few other popular titles.

**Comment by llacb47** [comment]
Already fixed in source list https://github.com/AdAway/adaway.github.io/commit/190410b47a55cec1339e48b6fe142d2ed62b4538

**Comment by StevenBlack** [comment]
Thanks LE @llacb47 for the assist.

Closing.
