### ISSUE TITLE
Usage permission

### ISSUE THREAD

**Issue by aizuon** [StevenBlack/hosts#1179]
I've used the unified hosts file from this repo to create an application that fetches hosts file periodically from the web and compares it to local hosts file and updates if its different. 

My question is if usage of this hosts file from outside sources is permitted. You can access my repo on https://github.com/aizuon/AutoAdBlock

Thanks in advance

**Comment by StevenBlack** [comment]
Hi @aizuon thank you for asking!  The license here is very permissive and as long as you comply with it, you’re good!

Best of luck and I’m always happy to help!

Closing.
