### ISSUE TITLE
Unpredictable whitelist behavior with subdomains or at least 'analytics.twitter.com'

### ISSUE THREAD

**Issue by WillPresley** [StevenBlack/hosts#118]
Hey Steven, love this repo and everything you've been doing with it. As in the title, I have included analytics.twitter.com (and just twitter.com) in my whitelist file, and the results aren't quite as expected. twitter.com in the whitelist properly unblocks urls.api.twitter.com, scribe.twitter.com and p.twitter.com (not the 3 I am concerned with) but fails to remove analytics from the final generated file. Including the hostname explicitly also does not work. analytics.twitter.com is now an actual UI-driven way to view the engagement on your tweets, which I find sometimes interesting haha, but I can't seem to get it unblocked using the generative methods I use for many other hosts without a problem. Just looking to see if you had any insight as to why that may be happening, if it's potentially on purpose, etc.

Thanks again!
Will

**Comment by StevenBlack** [comment]
Hi @WillPresley interesting.  I'll look into this today.

**Comment by StevenBlack** [comment]
@WillPresley testing this now, when I `add analytics.twitter.com` to the whitelist file, I get no `analytics.twitter.com` in any of the generated unified hosts files.

Did I understand this properly?

**Comment by WillPresley** [comment]
[**@StevenBlack**](https://github.com/StevenBlack) commented on [Mar 24, 2016, 6:20 PM EDT](https://github.com/StevenBlack/hosts/issues/118#issuecomment-201049588 "2016-03-24T22:20:52Z - Replied by Github Comment Enhancer"):
> [@WillPresley](https://github.com/WillPresley) testing this now, when I `add analytics.twitter.com` to the whitelist file, I get no `analytics.twitter.com` in any of the generated unified hosts files.
> 
> Did I understand this properly?

Yeah you understood the issue, but it didn't seem to happen to you. I just deleted the repo, synced a totally fresh version from GitHub, added just `analytics.twitter.com` to the whitelist file, and ran the script. I ended up **not** getting the host in my final file. I think I may have stumbled upon the issue though. If there are any other hosts in the whitelist file that are **below** analytics.twitter.com in the file, then ALL hosts in the file _except for_ analytics.twitter.com are properly whitelisted, but it is not. If twitter.analytics.com is at the BOTTOM of the whitelist file, then it and all other hosts in the file are blocked properly.

Is Python somehow stumbling over the subdomain having more periods than the script is expecting? I honestly haven't looked yet since I'm at work, but that seems to be what is happening. That is the result of my little bit of experimentation though. Definitely something weird going on, but putting it at the very bottom of the whitelist file seems to work, while putting it anywhere else in the 'order' causes it to be lost somehow, but all the other hosts are fine. Strange. Let me know if I can do anything else to help! Thanks for checking into it.

**Comment by WillPresley** [comment]
I guess testing it with other subdomains is one way to find out haha, I am just getting some coffee and not thinking super clearly yet. I can try that out later today if needed.

**Comment by borisschapira** [comment]
I have the same issue with `google-analytics.com` and `www.google-analytics.com`.
Nothing in the whitlist seems to unlock these domain and sub.

**Comment by StevenBlack** [comment]
Thanks Boris @borisschapira I'm going to dive into this today.  I'm a GA user myself.  I haven't looked at numbers in awhile so it's good motivation.

**Comment by borisschapira** [comment]
@StevenBlack No, thanks to you. I can't count how many hours (days) of webpage loading I've economized with this script. THANKS !

**Comment by StevenBlack** [comment]
@WillPresley and @borisschapira how's that now?

I just solved a couple of issues with whitelisting; I hope this helps.

**Take Note**:  if you whitelist `google-analytics.com` then that also whitelists all the subdomains of that.  In other words, the whitelist isn't an exact match.  It's a partial match.

**Comment by Gitoffthelawn** [comment]
@StevenBlack May want to document the "Take Note" (if it's not already).

**Comment by borisschapira** [comment]
@StevenBlack  It works for me, thanks a lot !

**Comment by StevenBlack** [comment]
Good suggestion @Gitoffthelawn.  Just noticed the whitelist wasn't documented at all.

**Comment by WillPresley** [comment]
[**@StevenBlack**](https://github.com/StevenBlack) commented on [Apr 1, 2016, 11:56 PM EDT](https://github.com/StevenBlack/hosts/issues/118#issuecomment-204640426 "2016-04-02T03:56:04Z - Replied by Github Comment Enhancer"):
> [@WillPresley](https://github.com/WillPresley) and [@borisschapira](https://github.com/borisschapira) how's that now?
> 
> I just solved a couple of issues with whitelisting; I hope this helps.
> 
> **Take Note**:  if you whitelist `google-analytics.com` then that also whitelists all the subdomains of that.  In other words, the whitelist isn't an exact match.  It's a partial match.

That took care of it perfectly for me! I popped analytics.twitter.com back into the middle of my whitelist (instead of the end) and now it works exactly as it should. I will leave this for you to close after my goof last time. THANK YOU! Amazing work in this repo by you and others, glad I could help the tiniest bit.

**Comment by StevenBlack** [comment]
Thanks @WillPresley!

Closing.
