### ISSUE TITLE
api.ipify.org is blocked

### ISSUE THREAD

**Issue by dark-nova** [StevenBlack/hosts#1180]
Hi,

I don't know if you pull changes from [AdAway](https://github.com/AdAway/adaway.github.io), but here is a relevant issue from there as well: AdAway/adaway.github.io#57. I did not see this entry in any of the other lists supplied by Pi-hole and the list used by AdAway also appears to be similar.

I use ipify, so please consider removing the entry as it has broken a personal project. (I have temporarily whitelisted the entry.)

**Comment by StevenBlack** [comment]
Hi @dark-nova thanks for this!  I trust the people who curate the AdAway list to do the Right Thing.

Closing.
