### ISSUE TITLE
Firefox DNS over HTTPS bypasses the local hosts file

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/hosts#1182]
Just leaving this here.  Heads up!  

Firefox' DNS over HTTPS feature is potentially really great.

One problem: this evidently bypasses the local hosts file.  So if this is enabled, you get the full advertising/tracking browsing experience.

Anybody have any ideas?

![2020-03-05_11-32-39](https://user-images.githubusercontent.com/80144/76003015-7c057980-5ed5-11ea-9d86-bf25466754d3.jpg)

**Comment by StevenBlack** [comment]
Thanks Nissar @funilrys.  I'd like to nominate this mozilla support page for a prize, as the worst.  Just awful.

**Comment by llacb47** [comment]
Related: https://github.com/StevenBlack/hosts/issues/1172

**Comment by swapneelp** [comment]
Just putting this as a concern that needs to be still looked at, if the user manually enables DOH in Firefox, it bypasses everything (hosts file, recursive resolver configured in the OS) i.e the canary domain workaround doesn't work.

**Comment by StevenBlack** [comment]
Yes Swapneel @swapneelp I agree.  I don't understand why this feature works this way.

I understand the browser encrypts the DNS request.  That has to happen somewhere, in a way that doesn't "leak" anything about the request.  

Maybe this is the only way this could work.  It just seems like, there must be a better way.

**Comment by swapneelp** [comment]
@StevenBlack DoH hijacks control of DNS away from network operators (like me) who use the DNS to block malicious content and protect small networks. A much saner option was DoT(rfc7858). DoH now raises the costs for everyone using DNS as a layer of defense. To summarise, the fantastic blocking lists that you folks curate and maintain will now need a solution at the OS packet layer to glue and make blocking work.

**Comment by trsantos** [comment]
The best way to prevent users from enabling this option is described here: https://github.com/mozilla/policy-templates#dnsoverhttps

**Comment by 3j9fkyahunqoxwqu** [comment]
> The best way to prevent users from enabling this option is described here: https://github.com/mozilla/policy-templates#dnsoverhttps

Agree.
Also they added ability to exclude domains from being resolved using DoH in FF75.

**Comment by XhmikosR** [comment]
@StevenBlack isn't this the same as #968 which has more info and is older? 🙂

**Comment by StevenBlack** [comment]
@XhmikosR same basic issue, yes.  Chrome (#968) and Firefox here.

**Comment by asocial-creep** [comment]
Why not just use uMatrix or uBlock origin? You can even host local files if you have something like xampp. Or for system wide use best is Acrylic DNS. Maybe YogaDNS too. I use uMatrix as hosts blocker and media type (scripts, images, videos, css) blocker in Chrome and Firefox.
