### ISSUE TITLE
How to contribute to hosts file?

### ISSUE THREAD

**Issue by me-ch** [StevenBlack/hosts#1185]
Hi, I would like to add 280 more subdomains of cdninstagram.com to this project's sources, I have already added them to my personal hosts file. How could I contribute to this project so that these might be added to the generator sources when a user selects the social extension?

**Comment by StevenBlack** [comment]
Hi @me-ch I'm guessing that `cdninstagram.com` is social media-related?

If so, then you can contact one of our social media curated sources.  Either @Sinfonietta [here](https://github.com/Sinfonietta/hostfiles/issues) or @tiuxo [here](https://github.com/tiuxo/hosts/issues).

Thanks!

Closing.
