### ISSUE TITLE
Unblock thewinesteward.com

### ISSUE THREAD

**Issue by irishboym4** [StevenBlack/hosts#1187]
Hello,  

I wanted to report that there is a domain, thewinesteward.com that is on the blocklist and shouldn't be. 

Thank you,

**Comment by StevenBlack** [comment]
Hi @irishboym4 the domain `thewinesteward.com` comes to us via Malware Domain List.

Can you please [contact them](https://www.malwaredomainlist.com/contact.php), and make your case there?  Thanks.

Closing.
