### ISSUE TITLE
Smart TV ads & tracker (2020)

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1195]
https://cloud.linuxfabrik.io/index.php/s/dJRTmz5aWQZgpFc

This is pdf about research for smart tv ads and tracker

It's my safe nextcloud space

**Comment by llacb47** [comment]
Better link: https://athinagroup.eng.uci.edu/projects/smarttv/

**Comment by StevenBlack** [comment]
Hi Lorenzo @scafroglia93 how is this actionable in a hosts file?

I hate issues such as this.  You're effectively saying, "*Steve, here is the entrance to a rabbit hole, buh-bye.*" while contributing almost no context, and no analysis.  You're just dumping this here.

Closing.

**Comment by AnonymousPoster** [comment]
Hi @scafroglia93 Sorry for the previously posted comments. 

You did link to a document longer than 140chars so your post(report) are therefore "fake"-news for non EU citizens :thinking: 

However I would be pleased if you would allow either me or one of you re-posting the report at https://www.mypdns.org/w/

**Comment by StevenBlack** [comment]
@AnonymousPoster fuck you.

**Comment by llacb47** [comment]
Go away @AnonymousPoster, you are a sockpuppet of spirillen. You already got banned from this repo once. 

https://github.com/mypdns/matrix/graphs/contributors
