### ISSUE TITLE
march262020.best

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1196]
Source ->
https://www.vmray.com/analyses/5b6f0d05a10d/report/network.html#f35d1067e184444db88cec6b0f67725b

Domain ->
march262020.best

**Comment by StevenBlack** [comment]
Thanks Lorenzo @scafroglia93, I've added this one.

Closing.

**Comment by dnmTX** [comment]
![March262020 best](https://user-images.githubusercontent.com/34774426/77862567-0645b280-71e2-11ea-98ff-da7b120c4e2c.png

might be a good idea to add it as well Steve @StevenBlack

**Comment by StevenBlack** [comment]
Absolutely Dan @dnmTX thanks.  Done.
