### ISSUE TITLE
Xbox Live for Windows Whitelist

### ISSUE THREAD

**Issue by t-makaro** [StevenBlack/hosts#1197]
The following domains are needed for xbox functionality on windows, but are blocked by your lists:
v10.events.data.microsoft.com
v10.vortex-win.data.microsoft.com

Source: https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

**Comment by StevenBlack** [comment]
Hi Tyler @t-makaro !

The domain `v10.events.data.microsoft.com` comes from my ad-hoc list.  This has been in the list for awhile, and nobody's complained.  Are you sure?

The domain `v10.vortex-win.data.microsoft.com` comes to us via `someonewhocares.org`.  That domain has been in this list for over 2-years, and nobody has said boo.

So I'm skeptical...  Again, are you sure?  Any xboxers out there, care to comment?

Tyler, what are you doing playing xbox?  Shouldn't you be finding fundamental particles, or saving us from the next near-earth fly-by, or something?  JK.  Hang in there, stay safe.

**Comment by StevenBlack** [comment]
Tyler @t-makaro, reading the link you posted, I see what you mean.

If I douse `v10.events.data.microsoft.com`, which I'm happy to do, you'll still need to submit `v10.vortex-win.data.microsoft.com` at someonewhocares.org.  Fair enough?  Contact Dan Pollock at hosts@someonewhocares.org.

**Comment by t-makaro** [comment]
Both of those domains were confirmed by Microsoft as needed for xbox functionaility. I'm not sure what functionality ```v10.vortex-win.data.microsoft.com``` breaks (I can still submit it), but ```v10.events.data.microsoft.com``` definitely breaks achievement unlock functionality (which is the functionality I'm more concerned about).

My guess is that most people who are affected by this just whitelist these and don't bother asking for upstream fixes, but I'm hoping to save at least someone the grief of figuring this out.

**Comment by StevenBlack** [comment]
Thanks Tyler @t-makaro.  The domain `v10.events.data.microsoft.com` is gone now and it will be in the next release, coming in 5.

Dan Pollock is a good egg and he'll eval `v10.vortex-win.data.microsoft.com` on its merits, and trust him to do the Right Thing.

**Comment by t-makaro** [comment]
Dan said that he removed ```v10.vortex-win.data.microsoft.com```.

**Comment by AnonymousPoster** [comment]
> The following endpoint is used by the Connected User Experiences and Telemetry component and connects to the Microsoft Data Management service. If you turn off traffic for this endpoint, diagnostic and usage information, which helps Microsoft find and fix problems and improve our products and services, will not be sent back to Microsoft.

| Source process | Protocol | Destination |
| -- | -- | -- |
| svchost | HTTPS | v10.vortex-win.data.microsoft.com/collect/v1 |

source: https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints
