### ISSUE TITLE
Add alternatives

### ISSUE THREAD

**Issue by pickfire** [StevenBlack/hosts#12]
Take a look at https://github.com/gaenserich/hostsblock which is written in bash and have lots of source to block. I hope you can put the alternative in [README.md](https://github.com/StevenBlack/hosts/). I also hope that you can add a license (I recommend [wftpl](http://www.wtfpl.net/).

**Comment by magikid** [comment]
To be clear, are you asking for a rewrite of the current updateHosts.py file from Python to bash?

**Comment by pickfire** [comment]
No, I am just suggesting to add an alternative at README.md to show others what are the alternatives.

**Comment by espress0** [comment]
Please include this list too:

https://adaway.org/hosts.txt

**Comment by pickfire** [comment]
+1 for the small list, but it will make some difference.

**Comment by StevenBlack** [comment]
@espress0 This looks like a nice resource, Danny.  I'll add this to the next build, coming soon.

**Comment by StevenBlack** [comment]
Also @espress0 I love that AdAway is on Github.

**Comment by StevenBlack** [comment]
Done!  Adaway.org's hosts file is now included.

Closing.
