### ISSUE TITLE
MA-774.022020: MyCERT Advisory - Espionage Campaign Based On Technical Indicators (APT40)

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1202]
Source ->
https://www.mycert.org.my/portal/advisory?id=MA-774.022020

Domain ->
yfleur.myftp.org
dynamics.ddnsking.com
accountsx.bounceme.net
vvavesltd.servebeer.com
capitana.onthewifi.com
kulkarni.bounceme.net
thestar.serveblog.net
invoke.ml

**Comment by StevenBlack** [comment]
Thank you Lorenzo @scafroglia93 — these have been added.

Closing.

**Comment by AnonymousPoster** [comment]
s/yfleur.myftp.org/byfleur.myftp.org/

![image](https://user-images.githubusercontent.com/5105020/78355760-8ab37f00-75ae-11ea-91a3-5b92788fb3aa.png)
