### ISSUE TITLE
Request: Separate "privacy/analytics/tracking" category from unified hosts

### ISSUE THREAD

**Issue by gajicm93** [StevenBlack/hosts#1207]
Hi. I'm writing this as someone who LOVES your project, regularly uses it, and recommends it all friends and family as the primary ad blocker.

BUT, I'm writing this as a general request related to my specific bug report (#1206), and as a software developer whose part of the job is to often work with services like Google Analytics and many other which are used to anonymously track users, and I'm sure I'm not alone. Also there's a lot of people whose job is to work directly with Ad services, but on to the point:

It's very often a problem for me that main "unified" hosts file also by default blocks all of these analytics services, and even general purpose public APIs as described in #1206. So my request is, if possible, to separate "privacy/analytics/tracking" category of domains from the unified hosts file, and maybe even legit Ad domains, and leave only malware and adware in the unified file which is *actually unwanted* for 99.99% of people.

So I'd like to see something like this:

UNIFIED (malware + adware)
UNIFIED + "legit advertising" (meaning Google AdSense, etc..)
UNIFIED + "privacy/analytics/tracking" (this would include all flavours of "analytics" services which mostly anonymously track users and actually do ZERO harm to anybody)

Thank you!

**Comment by llacb47** [comment]
If you use pihole, you can just whitelist these hosts. Also, it probably won't be possible for the unified host list to not include analytics, as the source lists make no distinction between adware, malware, or "legit" ads/analytics/tracking.

**Comment by gajicm93** [comment]
> If you use pihole, you can just whitelist these hosts. Also, it probably won't be possible for the unified host list to not include analytics, as the source lists make no distinction between adware, malware, or "legit" ads/analytics/tracking.

I'll take that into consideration, thanks.

**Comment by StevenBlack** [comment]
Hi Marko @gajicm93 I'd love to do that.

As LE @llacb47 points out, the distinction is tough because each hosts source granulates differently.  In general advertising is lumped with with general malware.

I suppose a solution to might be to seek out and implement finer-grained lists.

Are you on Mac or Linux?  [Hostile](https://github.com/feross/hostile) — mentioned in the ReadMe under [Interesting Applications](https://github.com/StevenBlack/hosts) — is a Good Thing.  It's easy to script that as a post-process, a bunch of one-liners to add or delete domains, right after fetching a fresh release.

**Comment by gajicm93** [comment]
> Are you on Mac or Linux? [Hostile](https://github.com/feross/hostile) — mentioned in the ReadMe under [Interesting Applications](https://github.com/StevenBlack/hosts) — is a Good Thing. It's easy to script that as a post-process, a bunch of one-liners to add or delete domains, right after fetching a fresh release.

I'm on a Mac so I'll look into it, thanks!
