### ISSUE TITLE
HOSTS addition to block ads

### ISSUE THREAD

**Issue by ADVENTAvenger** [StevenBlack/hosts#1209]
Please add:

0.0.0.0 tracking.scenepass.com
0.0.0.0 cdn.creativesumo.com
0.0.0.0 cdn3.bestcontenttrade.top
0.0.0.0 cdn2.bestcontenttrade.top
0.0.0.0 cdn1.bestcontenttrade.top
0.0.0.0 cdn.bestcontenttrade.top
0.0.0.0 a.bestcontentfood.top
0.0.0.0 b.bestcontentfood.top
0.0.0.0 a.bestcontenttrade.top
0.0.0.0 b.bestcontenttrade.top

This blocks everything on motherless.com when the site forces you to disable adblock, at least in Canada. The videos will work and ads will display "cannot connect" instead. 
![Ads](https://user-images.githubusercontent.com/32423321/78418451-30e0a280-760a-11ea-9918-08374acbd92c.png)
Happy fapping.

**Comment by StevenBlack** [comment]
Ping @sinfonietta, this one's yours, I think.

Closing.
