### ISSUE TITLE
deliveroo.com.sg (whitelist)

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1211]
whitelist please, is legit

**Comment by StevenBlack** [comment]
Thanks @scafroglia93 the domain `deliveroo.com.sg` comes to us via AdAway, so it's upstream.

Ping @jawz101, what say you?

**Comment by jawz101** [comment]
removed.  Thanks

**Comment by StevenBlack** [comment]
Thanks @jawz101 and thanks Lorenzo @scafroglia93.

This is live now in the latest release.

Closing.
