### ISSUE TITLE
A few domains to add.

### ISSUE THREAD

**Issue by CyanoTex** [StevenBlack/hosts#1214]
Here they are!

ads-bi.zenkube.com
services.insurads.com
cdn.insurads.com
msg-0209861dced41c7ef.insurads.com
messaging.insurads.com
adsaccount.appcpi.net
analytics.xl.pt
adservice.google.be

**Comment by StevenBlack** [comment]
Hi @CyanoTex thank you for this.

Can you please add some context?  Why should each of these be blocked?

**Comment by CyanoTex** [comment]
> 
> 
> Hi @CyanoTex thank you for this.
> 
> Can you please add some context? Why should each of these be blocked?

[I was told by Romain Cointepas over at nextdns/metadata to place these suggestions here, as the NextDNS recommended blocklist uses Steven Black among others.](https://github.com/nextdns/metadata/issues/91#issuecomment-609872727)

I did a search for 'ads' and 'analytics' on my NextDNS config's logs page and stumbled into these.

ads-bi.zenkube.com: A search on Google suggests it might be coming from [codefresh-io/zenkube?](https://github.com/codefresh-io/zenkube) I'm not sure, but it's on there.
Insurads domains: I quote from their [website](http://insurads.com): 
> The world's 1st time and attention insurance for digital advertisement.

I can't tell you much beyond that, because the service is invite only.
analytics.xl.pt: Analytics for xl.pt.
adservice.google.be: Advertising service for Google in Belgium. I think.

**Comment by StevenBlack** [comment]
Thanks @CyanoTex these domains are added.

Closing.
