### ISSUE TITLE
Whitelist -> hidemyass.com

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1219]
hidemyass.com is legit site (VPN)

**Comment by StevenBlack** [comment]
Thanks Lorenzo @scafroglia93 — I have reported this to Tomasz over in the add.Risk repo: https://github.com/FadeMind/hosts.extras/issues/31

**Comment by StevenBlack** [comment]
This is fixed in the 2.6.0 release, Lorenzo @scafroglia93.

Closing.
