### ISSUE TITLE
Azure Cloud

### ISSUE THREAD

**Issue by whosjose** [StevenBlack/hosts#122]
I've lost access to Azure Cloud Portal

https://azure.microsoft.com/en-us/account/

Thanks

Below are the links that needed to be in the whitelist file. 
```
*.azure.com
*.windows.net
*.azurecomcdn.net
*.azureedge.net
*.msecnd.net
login.microsoftonline.com
login.live.com

Third-party services:

*.sendgrid.com
*.newrelic.com
```

**Comment by berrythesoftwarecodeprogrammar** [comment]
might be the new tyzbit file which seems to block a lot of microsoft stuff

**Comment by StevenBlack** [comment]
If you can get me a list of domains used by Azure then I can help.

**Comment by StevenBlack** [comment]
See #104.

**Comment by zypeh** [comment]
I think I found a list from here [Azure Portal](https://feedback.azure.com/forums/223579-azure-portal/suggestions/11569407-document-urls-necessary-to-configure-corporate-fir)

**Comment by whosjose** [comment]
Thanks for all the help.
