### ISSUE TITLE
kinsing malware container

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1220]
Source ->
https://blog.aquasec.com/threat-alert-kinsing-malware-container-vulnerability

IoC ->
www.traffclick.ru
www.mechta-dachnika-tut.ru
www.rus-wintrillions-com.ru
rus-wintrillions-com.ru
stroitelnye-jekologicheskie-materialy2016.ru

**Comment by ammnt** [comment]
These domains in not registered now:
mechta-dachnika-tut.ru
rus-wintrillions-com.ru
stroitelnye-jekologicheskie-materialy2016.ru

You can check this via official WHOIS here:
https://cctld.ru/en/service/

**Comment by StevenBlack** [comment]
Thanks Lorenzo, I've added `www.traffclick.ru`.  Thanks @ammnt  for the assist.

Closing.
