### ISSUE TITLE
Multiple False Positive

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1223]
bet-at-home.com -> legit betting site
betclic.com -> legit betting site

**Comment by scafroglia93** [comment]
10bet.com
12bet.com
bet365.com

**Comment by John889** [comment]
Hi scafrogalia93,
Those are not blocked. 
jrktube.com    -->unblocked porn site
www.pornflix.to -->unblocked porn site

**Comment by scafroglia93** [comment]
> Hi scafrogalia93,
> Those are not blocked. 
> jrktube.com    -->unblocked porn site
> www.pornflix.to -->unblocked porn site

What ??

**Comment by dnmTX** [comment]
@scafroglia93  so what is the difference between legit betting site and non legit one?

**Comment by scafroglia93** [comment]
@dnmTX 
there have been cases where some betting sites operated without licenses and others that turned out to be fraudsters while continuing to operate

Can it be enough?

**Comment by dnmTX** [comment]
> Can it be enough?

Clear enough.Thanks 👍 
Now...let me clarify something to you. The **gambling** extension that you're using is intended to block all websites that in one way or another betting/gambling is involved,not the once without proper license only. The extension is optional and would advise you to just stop using it.

**Comment by scafroglia93** [comment]
@dnmTX 
I'm not using the gambling extension so that's the problem

**Comment by dnmTX** [comment]
@scafroglia93 report it directly to the upstream's list maintainer: `hosts@someonewhocares.org`
Sorry,should've check the lists first before "confidently" answering 😉

**Comment by scafroglia93** [comment]
I understand you, I also manage the lists that I keep manually to avoid false positives. You can find them on my git

**Comment by StevenBlack** [comment]
Hi Lorenzo @scafroglia93 

These domains appear to all be upstream from us.

Nissar @funilrys can you comment on behalf of Badd-Boyz for  `10bet.com ` and `12bet.com`?

Look, everyone, I don't care whether a gambling site operates with a licence, or not.  I only care about malware/adware/tracking, and I care that gambling sites are properly slotted into the gambling extension IF they are not involved in adware/malware/tracking.

Please note Antonio @scafroglia93 that "legit" has no meaning here.  There are countless "legit" sites that do all kinds of stupid things with their platforms.  The term "legit" is undefined, here.  That's how it will always be.  Sites either respect privacy and security, or they don't, regardless of what else they do, and whether that's legit, or not.

**Comment by mitchellkrogza** [comment]
At some point 10bet.com and 12 bet.com would have been flagged by me for referrer spam through my Nginx blocker project. They no longer appear in any logs from the past 14 months so removing them.

**Comment by StevenBlack** [comment]
Closing!  Thanks everybody.

**Comment by scafroglia93** [comment]
@dnmTX 
bet-at-home.com 
betclic.com
bet365.com 

For this -> hosts@someonewhocares.org ?
