### ISSUE TITLE
Unblocked ad site

### ISSUE THREAD

**Issue by oconnor0** [StevenBlack/hosts#1224]
I got served ads from qlzogd.edvfwlacluo.com; figured it was worth getting added to the lists. :)

**Comment by llacb47** [comment]
FYI:
this is a domain used for ad reinsertion. You can see sites using the same delivery method (by the same company, I believe):

```
https://ultimateninjablazingx.com/
http://www.alifeinbalance.net/price-book-chicken-parmesan/
```

Note: test in guest mode (i.e. without uBlock origin, because uBo fixes the reinsertion script).

**Comment by dnmTX** [comment]
Such a (sub)domains are alive for 24 hrs. and then another one replaces it.
Not sure how one can keep up with that:
![Edvfwlacluo](https://user-images.githubusercontent.com/34774426/79058743-4faced80-7c37-11ea-9706-ca4e1aed3114.png)

**Comment by oconnor0** [comment]
Oof, I didn't realize that. Almost need Windows and macOS and Linux to support wildcards in the hosts file. :)

**Comment by StevenBlack** [comment]
Hi Matthew @oconnor0 yes, wildcard in hosts files would have been nice.

Cheers!  Closing.
