### ISSUE TITLE
One analytics and one advert domain

### ISSUE THREAD

**Issue by CyanoTex** [StevenBlack/hosts#1226]
```
analytics.modul.ac.at
advertising-cdn.dpgmedia.cloud
analytics.inlinemanual.com
```

Found these unblocked while looking through search results on one of my NextDNS configurations. Not sure where these are present.

**Comment by CyanoTex** [comment]
Added `analytics.inlinemanual.com`.

**Comment by StevenBlack** [comment]
Thank you @CyanoTex I have added these to my ad-hoc list.  These will be live in the next release.

Closing.
