### ISSUE TITLE
Add biqle.com and biqle.org

### ISSUE THREAD

**Issue by angelss197200** [StevenBlack/hosts#1228]
biqle.com is a mirror form biqle.ru
It is a porn site

**Comment by StevenBlack** [comment]
Ping @sinfonietta.

**Comment by angelss197200** [comment]
add biqle.org too

**Comment by StevenBlack** [comment]
Ping @Sinfonietta (again).

**Comment by StevenBlack** [comment]
Thanks @sinfonietta.

Closing.
