### ISSUE TITLE
Github Sawfish IoC

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1234]
Source ->
https://github.blog/2020-04-14-sawfish-phishing-campaign-targets-github-users/

IoC ->
aws-update.net
corp-github.com
ensure-https.com
git-hub.co
git-secure-service.in
githb.co
glt-app.net
glt-hub.com
glthub.co
glthub.info
glthub.net
glthubb.info
glthube.app
glthubs.com
glthubs.info
glthubs.net
glthubse.info
slack-app.net
ssl-connection.net
sso-github.com
sts-github.com
tsl-github.com

**Comment by StevenBlack** [comment]
Thanks Lorenzo @scafroglia93, these are in the list now.

Closing.
