### ISSUE TITLE
Few more porn sites

### ISSUE THREAD

**Issue by sonarypt** [StevenBlack/hosts#1235]
I had my own repo on porn hosts file. 
[https://github.com/sonarypt/kdam.ageVN](https://github.com/sonarypt/kdam.ageVN)
At 20/04/2020, I checked and compared this hosts file to your repo's, I got over 1000 sites that are not included yet. This would be really helpful for the Faptronauts.

Have a nice week ahead.

**Comment by StevenBlack** [comment]
Hi @sonarypt — **faptronauts**, that's funny.

Running my [ghosts](https://github.com/StevenBlack/ghosts) utility, comparing your list with our base list + porn, I get the following: 1,702 domains in yours, not in ours.  So your list would make a very nice addition to the sources used here.

```bash
$ ./ghosts -m https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts -c https://raw.githubusercontent.com/sonarypt/kdam.ageVN/master/porn/hosts
--------------------------------------------------------------------------------
Base hosts file summary:
--------------------------------------------------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts
Domains: 74,587
Bytes: 2.2 MB
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Compared hosts file summary:
--------------------------------------------------------------------------------
Location: https://raw.githubusercontent.com/sonarypt/kdam.ageVN/master/porn/hosts
Domains: 2,858
Bytes: 69 kB
--------------------------------------------------------------------------------
Intersection: 1,156 domains
```

**Comment by StevenBlack** [comment]
@sonarypt here's a breakdown of TLD in your list.  I think some of these are not legitimate TLD.  One example: `.cumlouder` is not a TLD.

```bash
$ ./ghosts -m https://raw.githubusercontent.com/sonarypt/kdam.ageVN/master/porn/hosts --tld
--------------------------------------------------------------------------------
Base hosts file summary:
--------------------------------------------------------------------------------
Location: https://raw.githubusercontent.com/sonarypt/kdam.ageVN/master/porn/hosts
Domains: 2,858
Bytes: 69 kB
TLD tally:
   com: 2,161
   net: 240
   org: 77
   tv: 49
   xxx: 37
   xyz: 33
   info: 33
   me: 29
   top: 18
   vn: 13
   sexy: 11
   eu: 10
   co: 9
   to: 9
   biz: 8
   us: 8
   ru: 7
   mobi: 7
   cc: 7
   nl: 6
   pro: 5
   pw: 5
   porn: 4
   ws: 4
   site: 4
   vip: 4
   sex: 3
   in: 3
   br: 3
   video: 2
   de: 2
   it: 2
   club: 2
   bz: 2
   io: 2
   link: 2
   tech: 2
   rocks: 2
   jp: 2
   smoder: 2
   sx: 2
   today: 2
   fr: 2
   photos: 1
   urvy: 1
   chat: 1
   ly: 1
   download: 1
   gallery: 1
   cloud: 1
   html: 1
   agency: 1
   wiki: 1
   jamesdeen: 1
   asia: 1
   one: 1
   ms: 1
   cumlouder: 1
   ca: 1
   ooo: 1
   au: 1
   ch: 1
   yahoo: 1
   live: 1
   gg: 1
   uk: 1
--------------------------------------------------------------------------------
```

**Comment by StevenBlack** [comment]
@sonarypt I suppose one issue is, we only use actively curated lists here. The [sonarypt/kdam.ageVN](https://github.com/sonarypt/kdam.ageVN) repo is only one day old.  Can we discuss this in a few weeks or months?

See, a source of domains is not enough.  The sources need to be active, and have a track record of commitment to maintaining quality.

Sensible?

**Comment by StevenBlack** [comment]
@sonarypt I just added [an issue in the ghosts repo](https://github.com/StevenBlack/ghosts/issues/8) to be able to list domains that are unique in compared hosts file.

**Comment by sonarypt** [comment]
Thank you for your review. I will keep improving the hosts file.

**Comment by paulohpf** [comment]
can you guys add xvideosnovinhas.com too?

**Comment by Yodatoo** [comment]
Please add these:
www.searchcelebrityhd.com
lustcinema.com
www.pascalssubsluts.com
lp.21naturals.com
www.bestpornbabes.com
www.azporncomics.com
jodic-forum.org
www.viewgals.com
www.crazyexgfs.com
www.indianpornvideo.org
www.wyav.tv
www.aa-club.com.cn
www.girlsofdesire.org
www.tumbex.com
www.porn5f.com
www.52av.one
porn18.cc
www.yanzhao1.com

**Comment by Yodatoo** [comment]
@StevenBlack 
> I suppose one issue is, we only use actively curated lists here. ... 
> See, a source of domains is not enough. The sources need to be active, and have a track record of commitment to maintaining quality.

Which source (for porn domains) do you think it presently most actively curated?

**Comment by StevenBlack** [comment]
Ping @sinfonietta or @clefspeare13 can you have a look?

**Comment by Yodatoo** [comment]
> Ping @Sinfonietta or @Clefspeare13 can you have a look?

@Clefspeare13 says something like "not very active, go somewhere else".
I've tried @Sinfonietta. Tried to edit myself there, but not successful. I prefer to just provide domains to be added. Still looking for someone to accept my help.

**Comment by EVOTk** [comment]
Hello,
I hope to be in the right place!
can you add the following site in list :
balancetonporn.com

thank you

**Comment by lordruler** [comment]
Please add one more

www.girlsreleased.com

**Comment by ludwigschr** [comment]
Few more:

rtn.in.net
sweetygirlz.online
cute-girls.online
schoolgirls.online
vum.in.net

(YouTube comments)
