### ISSUE TITLE
Ad servers being hacked to distribute malicious ads

### ISSUE THREAD

**Issue by rai510** [StevenBlack/hosts#1242]
https://www.bleepingcomputer.com/news/security/revive-ad-servers-being-hacked-to-distribute-malicious-ads/

https://www.bleepingcomputer.com/news/security/revive-ad-servers-being-hacked-to-distribute-malicious-ads/

I even came across this domains on some websites i use safari browser and it never shows up on firefox because i use with ublock origin even sometime ublock even can't block this kind of domains on website i came across.

Thank You

**Comment by StevenBlack** [comment]
Hi @rai510 thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Although we occasionally accept well identified hosts for inclusion, going down rabbit holes looking for whatever you think you saw, or whatever some third party thinks they saw, really isn't our thing.   Moreover you post two links, above.  They are the same link.  This tells me, you put minimum effort into making a case for whatever this is.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).  

Closing.
