### ISSUE TITLE
Ad domains from zenkube and tuanguwen

### ISSUE THREAD

**Issue by CyanoTex** [StevenBlack/hosts#1245]
word-res.tuanguwen.com

word-bi.zenkube.com

cross-promos.tuanguwen.com

prod.zenkube.com

puzzle-recomd.zenkube.com

databoat.zenkube.com

word-v1.tuanguwen.com

-------

Found these domains that were being phoned home from this app:
https://play.google.com/store/apps/details?id=com.wordgame.words.connect

Blocking them seemed to help cut down on the ads.

I'm still not sure what these domains do but I know the game is contacting them from what I can tell.

**Comment by llacb47** [comment]
most of those look non-malicious.

**Comment by CyanoTex** [comment]
> most of those look non-malicious.

When I did a blanket block on both zenkube and tuanguwen the ads didn't come back. (。_。)

**Comment by StevenBlack** [comment]
Thanks @CyanoTex.  Added.
