### ISSUE TITLE
s-usc1c-nss-262.firebaseio.com is needed and is used by all Firebase Cloud Platform clients (thousands of companies) & apps.

### ISSUE THREAD

**Issue by johnozbay** [StevenBlack/hosts#1249]
Hey there @StevenBlack & @jawz101 👋🏻

This week we've started receiving support messages from tons of users telling us that they can't access our service while using PiHole, AdAway and others using these lists. 

Looks like the hosts file has : `s-usc1c-nss-262.firebaseio.com` on [line 8419](https://github.com/StevenBlack/hosts/blob/master/hosts#L8419)

Similar to #1132 – This domain is a general domain used by all Firebase platform customers. 
Firebase dynamically moves platform customers between subdomains to handle scaling. 
Here's an official explanation from a Firebase staff member on their forums ([source](https://groups.google.com/forum/#!msg/firebase-talk/SlCsde0zxQM/dszRNGD4BgAJ)) : 

**Q:**
> ... Would the service the clients connect to behind the scenes s-usc1c-nss-122.firebaseio.com be constant for a database "projectXYZ.firebaseio.com" or is this subject to change as well? 

**Staff Answer:**
> It is subject to change. You can be moved to a different server (the nss-### part of that URL) at any point and shouldn't rely on that for anything.

--

I believe that this week my service/app [Cryptee](https://crypt.ee), an [open-source](https://github.com/cryptee/web-client) on-device encrypted, privacy advocating, productivity tools service, which relies on Firebase (for things like websockets as a part of our real-time productivity tools, as well as fallback for censorship circumvention), got moved onto the `s-usc1c-nss-262.firebaseio.com` server to handle the load. And now users of these hosts lists are having issues accessing our platform. 

Having this domain blocked also means, other Firebase clients are (or will be) impacted by this as well, some of which include : [NYTimes Interactive](https://twitter.com/NYTInteractive/status/989224554269741057), [HackerNews API](https://github.com/HackerNews/API), occasionally [Mozilla Firefox itself](https://support.mozilla.org/en-US/kb/how-do-you-use-google-firebase-firefox) and companies like NPR News, Lyft, Shazam, and more according to some quick search on the internet. 

I can at least speak on behalf of my platform, Cryptee, where we don't have any ads, tracking, or anything alike. Sadly, our customer support team (incl myself) are working overtime to handle this service-is-not-accessible situation right now. 😅

If possible, it would be great if you could remove `s-usc1c-nss-262.firebaseio.com` from the lists as soon as possible. (and for future, all domains following the same `nss-###` pattern are a part of the same platform)

If you know which specific service/company is using this domain for serving malicious content / ads, I'd be more than happy to take the lead and reach out to Firebase team to have it taken down altogether, so that others who use the cloud platform for good purposes can continue to do so. 

Many thanks both ✌🏻

**Comment by johnozbay** [comment]
P.S. Seems like the same thing's happening to [RoamResearch](roamresearch.com) and [users have been talking about it on their reddit] as well : (https://www.reddit.com/r/RoamResearch/comments/fu9dao/cant_sign_in/).

**Comment by StevenBlack** [comment]
Thanks John!

Ping @jawz101.

**Comment by johnozbay** [comment]
Thanks a million for the quick response Steven! 🙏🏻 
Deeply appreciated!

**Comment by jawz101** [comment]
removed.  thank you

**Comment by johnozbay** [comment]
Many thanks for the quick turnaround time both 🙏🏻 
Stay safe and well ✌🏻

**Comment by StevenBlack** [comment]
Thanks everybody.  This is live and online [in the latest release](https://github.com/StevenBlack/hosts/releases/tag/2.6.9).

**Comment by johnozbay** [comment]
Massive thanks for all this!
