### ISSUE TITLE
Eventbot Banking Trojan

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1251]
Source ->
https://www.cybereason.com/blog/eventbot-a-new-mobile-banking-trojan-is-born

IoC ->
themoil.site
ora.carlaarrabitoarchitetto.com
ora.studiolegalebasili.com
rxc.rxcoordinator.com
Ora.blindsidefantasy.com
Pub.welcometothepub.com
marta.martatovaglieri.it

**Comment by StevenBlack** [comment]
Thanks Lorenzo @scafroglia93.  Added!
