### ISSUE TITLE
Robux phishing scams

### ISSUE THREAD

**Issue by CyanoTex** [StevenBlack/hosts#1252]
```
https://gainblox.com/
https://robux.dev (dead domain, CloudFlare gave me the provider's abuse email 👍)
https://grandmods.com/robux/
```

Law of the internet for Roblox says: If there're websites promising free robux, they're scams, no matter if they say they're legit or not.

**Comment by StevenBlack** [comment]
Thanks @CyanoTex, these are added in commit 79f628a0.

Closing.

**Comment by CyanoTex** [comment]
@StevenBlack Don't forget the last one.

Found out it was just their base of operations for this:
`https://grandmods.com/robux/`

**Comment by StevenBlack** [comment]
@CyanoTex Hosts files are for domains only.  The grandmods.com domain is just an uninitialized WordPress instance.

But I hear you.  Adding it now.

**Comment by CyanoTex** [comment]
Understandable but yeah, I think that look is on purpose.

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________
