### ISSUE TITLE
Xiaomi Tracking (Mint Browser)

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1253]
Source  ->
https://www.youtube.com/watch?v=62kxZunBQyI&feature=emb_title

Domain IoC ->
sa.api.intl.miui.com

We would need everyone's feedback to avoid malfunctions on the device

**Comment by scafroglia93** [comment]
More Source ->
https://www.bleepingcomputer.com/news/technology/xiaomi-tracks-private-browser-and-phone-usage-defends-behavior/

**Comment by StevenBlack** [comment]
I'm adding this to the list, Lorenzo @scafroglia93.

Xiaomi users will let us know if this hurts.
