### ISSUE TITLE
perswaysion spam campaign

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1254]
Source ->
https://www.group-ib.com/blog/perswaysion

IoC ->
as54rdxfzxs.appspot.com
asgh65tfsdxz.appspot.com
da032opzasz.appspot.com
dgyu536ds.appspot.com
eqit9pzsxz.appspot.com
etetdc4ed-exhausted-lizard-tc.mybluemix.net
gdh4szx.appspot.com
hg76ytsdas.appspot.com
hj67fadszx.appspot.com
hk567rsda.appspot.com
hksdf924pzxoias.appspot.com
iwe8pzosa.appspot.com
k87yfgsdaa.appspot.com
kga9szxosa.appspot.com
kj65rdasz.appspot.com
kj6787rsd.appspot.com
kr9apzxosa.appspot.com
nffdg43zx.appspot.com
oi8ytfzxa.appspot.com
ruw82qpzxas.appspot.com
tir94wepsdxox.appspot.com
tr54sdsazxas.appspot.com
tru465rsda.appspot.com
tu4dff-reflective-shark.eu-gb.mybluemix.net
ty65xcc-smart-manatee.mybluemix.net
ut45dfx-sweet-nyala.mybluemix.net
uy054eprsdoz.appspot.com
xasf32easzx.appspot.com
xoada0pzosa.appspot.com
y56gcvx-lean-bear-up.mybluemix.net
ytuy45fxs.appspot.com
yu56tdfcxc.appspot.com
yuhfdwesaa.appspot.com
odaiw3dda.bestnewsworld.info
otpe.bestnewsworld.info
uy6x.bestnewsworld.info
uy6x.c3y5-tools.com

**Comment by StevenBlack** [comment]
Thanks Lorenzo @scafroglia93.  Done.
