### ISSUE TITLE
Add maybe my block list?

### ISSUE THREAD

**Issue by socram8888** [StevenBlack/hosts#1260]
The pages come mainly from emails I receive myself, or from scammers.info, which nobody seems to be collecting and putting them into a list.

Most of the addresses in my list are apparently not blocked in any other list. The phising pages are not blocked by Google Safe Browsing list either, making them even more dangerous.

The list is available [as a domain list](https://orca.pet/notonmyshift/domains.txt) and also as a [hosts file](https://orca.pet/notonmyshift/hosts.txt).

All the domains I've collected are sorted by addition date along with the reason and source. I am keeping domains for a few months that have been affected even if the page returns 404 currently or domain not found, just in case the domain is still registered and up for being used in the short future.

**Comment by StevenBlack** [comment]
Hi Marcos @socram8888 thank you for this.

Does your list have a versionable history, or a track record that shows a history of curation?  That's important.

Using [ghosts](https://github.com/StevenBlack/ghosts) I see that there is very little overlap between the two lists, just six domains in common.  So including yours would give us 297 new domains.

```
$ ghosts -c https://orca.pet/notonmyshift/hosts.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 55,942
Bytes: 1.7 MB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://orca.pet/notonmyshift/hosts.txt
Domains: 303
Bytes: 10 kB
----------------------------------------
Intersection: 6 domains
```

**Comment by socram8888** [comment]
The domain list is a file available at my website's repository, along with the commit history: https://github.com/socram8888/orca.pet/commits/master/notonmyshift/domains.txt

I will be moving either today or tomorrow the file to its own repository, so changes to my pages are independent to that of the block list.

**Comment by StevenBlack** [comment]
The list has been alive for about a month.

I'll keep an eye on it.  I'm happy to include it once we know it's active over the long haul.

**Comment by socram8888** [comment]
Done, I've moved it into another repo so changes are easier to follow: https://github.com/socram8888/not-on-my-shift

**Comment by dnmTX** [comment]
This is now part of #1439 so can be easily closed.
**Ping Steven @StevenBlack**
