### ISSUE TITLE
pandemic malware

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1261]
Source ->
https://umbrella.cisco.com/blog/navigating-cybersecurity-during-a-pandemic-latest-malware-and-threat-actors

IoC ->
acalvet.com
acbras.com
arjoflor.com
arjoflos.com
bergadimspower.com
berkesteermaster.com
contatoonline1.com
famartil.com
oawyri.com
oawyr.com
parnerimcarpich.com
qpfhd.com
rjmwqf.com
rstmir.com
servicosfcporto.com
sirdexs.com
Megasena1.duckdns.org

**Comment by StevenBlack** [comment]
Thanks Lorenzo @scafroglia93 these have been added.
