### ISSUE TITLE
Add a list of child abuse websites

### ISSUE THREAD

**Issue by pornblocking** [StevenBlack/hosts#1263]
Please add this to the porn hosts file
```



```

**Comment by StevenBlack** [comment]
Thanks @pornblocking.

Ping @sinfonietta or @clefspeare13.

I'm thinking, child stuff goes into the main list?  What's child here?  Not sure OP's issue title is accurate.

**Comment by pornblocking** [comment]
@StevenBlack 
> What's child here?

The images and videos on website that I listed

**Comment by scafroglia93** [comment]
@StevenBlack 
The pictures are terrible

**Comment by llacb47** [comment]
If it's CP do **not** view it.

**Comment by scafroglia93** [comment]
Needed for law enforcement engage

I know, it's terrible

**Comment by StevenBlack** [comment]
Done.  Closing.

**Comment by llacb47** [comment]
Someone should report also at `https://report.cybertip.org/`
