### ISSUE TITLE
Zoom RAT

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1266]
Source ->
https://otx.alienvault.com/pulse/5eac5fbc246f37da533416ae

IoC ->
dabmaster.wm01.to

**Comment by StevenBlack** [comment]
Lorenzo @scafroglia93 can you please do me a kindness?

Please stop submitting single-domain issues.  Ten single-domain issues is about eight times more work than one 10-domain issue.

I just don't have time.  You understand?  Please close all your outstanding single-domain issues and re-submit as one issue.

Thanks.

**Comment by scafroglia93** [comment]
done
