### ISSUE TITLE
Phish link

### ISSUE THREAD

**Issue by CyanoTex** [StevenBlack/hosts#1269]
ctt.pt-particulares.mandalozz.com
Newly Registered Domain.

👇 The phish email it came with.
https://www.reddit.com/r/Scams/comments/gfqm9a/portuguese_ctt_pts_snail_mail_service_phishscam/

**Comment by CyanoTex** [comment]
@romaincointepas This might be of interest to you too.

**Comment by StevenBlack** [comment]
Thank you @CyanoTex.  This has been added.
