### ISSUE TITLE
Do you have a porn only host file?

### ISSUE THREAD

**Issue by pornblocking** [StevenBlack/hosts#1274]
Hi,

I am looking for a host file that **only** has porn sites. The one I am currently using "Unified hosts + porn" hosts file and I dont want the "Unified hosts" part if that makes sense.

Do you guys have this?

**Comment by StevenBlack** [comment]
Hi @pornblocking check out the [`extensions/porn`](https://github.com/StevenBlack/hosts/tree/master/extensions/porn) folder of this repo.  Each subfolder is one of our sources.  Find full details in the `update.json` file in each subfolder.

Closing.

**Comment by dnmTX** [comment]
@pornblocking  here is a raw link:
`https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts`
