### ISSUE TITLE
Unable to determine DNS management tool. Linux Mint

### ISSUE THREAD

**Issue by Lusitaniae** [StevenBlack/hosts#128]
For Linux Mint you can run
`sudo /etc/init.d/dns-clean start`

to run it automaticlly.

**Comment by StevenBlack** [comment]
Thanks @Lusitaniae.  It looks like this would work on Ubuntu as well.

**Comment by Lusitaniae** [comment]
Should I make a pull request? Is it only a matter of creating another block like this? https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py#L456

**Comment by StevenBlack** [comment]
Sure!  Become a [contributor](https://github.com/StevenBlack/hosts/graphs/contributors)!

Consider amending the [Linux section of readme_template.md](https://github.com/StevenBlack/hosts/blob/master/readme_template.md#linux) too.

**Comment by Lusitaniae** [comment]
I was reading a bit further on the issue, and it seems that Ubuntu (and thus, Mint) doesn't cache DNS by default. So the command I run above at most is refreshing a cache of 0 on dnsmasq.

It might be a better option to do something else in this case, instead of displaying an error.
So if running nscd fails on Ubuntu because is not found, just conclude running the script.
http://askubuntu.com/a/435379

**Comment by StevenBlack** [comment]
@Lusitaniae thanks for looking into this.  

I'm leaning toward adding a command that doesn't fail on mint and be done with it.
