### ISSUE TITLE
Porn sites

### ISSUE THREAD

**Issue by paulohpf** [StevenBlack/hosts#1280]
please, can you add **spankbang.com** and **redtube.com.br** to porn hosts?

**Comment by StevenBlack** [comment]
Hi Paolo @paulohpf.  `spankbang.com` is already blocked by our porn hosts.  The `redtube.com.br` domain would be new.

Ping @sinfonietta!

**Comment by paulohpf** [comment]
Thanks @StevenBlack , i saw spankbang is blocked with www. but the site open without www. and br.spankbang.com, i think it's better block the with "spankbang.com" so it blocks all spankbang's variants

**Comment by StevenBlack** [comment]
Hosts files don't work like that, Paulo @paulohpf.

Hosts files originate back to the very beginnings of the internet.  There are no wildcards in hosts files, and no generalizations.  Each domain and subdomains needs an explicit entry.

**Comment by paulohpf** [comment]
@StevenBlack i undestand, thanks for the explanation
