### ISSUE TITLE
whitelist mywot.com

### ISSUE THREAD

**Issue by 3xploiton3** [StevenBlack/hosts#1285]
https://github.com/nextdns/metadata/issues/215

**Comment by StevenBlack** [comment]
See Issue #199.

Please take this up with @fademind, I trust his judgment.

**Comment by FadeMind** [comment]
@StevenBlack WOT stealing data and spying users/tracking. Same does Ghostery or... Avast Developer. 
Regards.

**Comment by StevenBlack** [comment]
Thank you Tomasz @FadeMind.

Closing.
