### ISSUE TITLE
api.vsee.com

### ISSUE THREAD

**Issue by cyb3rsinn3r** [StevenBlack/hosts#1286]
VSee is used for Telehealth appointments and api.vsee.com is used for "quick" login - where the patient isn't required to create a VSee account. The hosts file was blocking it:

pihole -q vsee.com
 
 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   api.vsee.com

I've whitelisted it for now, can it be removed as a false positive? Alternatively, what was the reason for including api.vsee.com?

Thanks!

**Comment by StevenBlack** [comment]
Hi @cyb3rsinn3r the `vsee.com` domain comes to us via AdAway.

You can please submit this to  https://github.com/AdAway/adaway.github.io/issues.

Ping @jawz101, can you have a look?

**Comment by jawz101** [comment]
removed

**Comment by StevenBlack** [comment]
Thanks @jawz101.  @cyb3rsinn3r this will show in the next release, shortly.
