### ISSUE TITLE
Why block AWS Kinesis?

### ISSUE THREAD

**Issue by gchamon** [StevenBlack/hosts#1287]
Today I was left puzzled as to why `kinesis.us-east-1.amazonaws.com` was resolving to `0.0.0.0` as I was producing a plan with terraform to check out a production bug in our infrastructure.

It turns out that the DNS is in the hosts file. It didn't really take me too long to find, because of the handy DNS Query List tool in pihole, but still, why is this domain blocked here in the first place?

I managed to workaround it by whitelisting it in pihole, but is there some serious security consideration to justify blocking this domain? Is this abused somehow by shady domains?

Thanks!

**Comment by StevenBlack** [comment]
Hi Gabriel @gchamon the `inesis.us-east-1.amazonaws.com` domain comes to us via AdAway.

Ping @jawz101, can you have a look at this one?  Thanks.

**Comment by gchamon** [comment]
Thanks for the quick reply! Love the project btw!!

**Comment by jawz101** [comment]
I'll think about it.  Looking into the product Amazon Kinesis involves realtime analytics processing and I can see that be for ads and tracking

[YieldMo case study](https://aws.amazon.com/kinesis/case-study-yieldmo/)

[Veritone facial recognition and Sonos monitoring all of their customer's stereos- both mentioned on the Kinesis webpage](https://aws.amazon.com/kinesis/)

[Nielsen TV ratings, Salesforce, Zeta, Quantcast use cases](https://aws.amazon.com/advertising-marketing/?cards-body.sort-by=item.additionalFields.publishedDate&cards-body.sort-order=desc)

[Amazon Prime Video advertising at scale](https://aws.amazon.com/blogs/media/this-is-my-architecture-advertising-analytics-at-scale-for-live-events-featuring-amazon-prime-video/)

[more Amazon vids](https://www.youtube.com/watch?v=z1bTfK25kAY) demoing it for [realtime analytics](https://www.youtube.com/watch?v=OTLpzY_oyVs)

Someone can whitelist it but I'm not interested in doing so unless it affects me on my phone.

**Comment by StevenBlack** [comment]
Thanks @jawz101 I appreciate the thorough assessment here.

Gabriel @gchamon I trust the judgment our curators — they are Good People.

Closing.

**Comment by gchamon** [comment]
Thanks for the feedback, it was interesting to see ways kinesis is used directly to handle ads streams.

I will have to whitelist it, but I am happy to know this is not a wrongly blacklisted domain.

Just one more thought...

Kinesis is also available in the following regions:

![image](https://user-images.githubusercontent.com/9471861/82469836-f2f4ec00-9a9a-11ea-9fbc-3ef01b9c9b5f.png)

It might be interesting to discuss with the curators to add those regions to the list. As it stands now, only data streams based in North Virginia will be blocked. If ads streams are set in São Paulo, for instance, they will not be blocked by this list because `kinesis.sa-east-1.amazonaws.com` is not in the list.

**Comment by StevenBlack** [comment]
@jawz101 you got dis ⬆️ ?

**Comment by llacb47** [comment]
```
0.0.0.0 firehose.ap-east-1.amazonaws.com
0.0.0.0 kinesis.ap-east-1.amazonaws.com
0.0.0.0 logs.ap-east-1.amazonaws.com
0.0.0.0 firehose.ap-northeast-1.amazonaws.com
0.0.0.0 kinesis.ap-northeast-1.amazonaws.com
0.0.0.0 logs.ap-northeast-1.amazonaws.com
0.0.0.0 firehose.ap-northeast-2.amazonaws.com
0.0.0.0 kinesis.ap-northeast-2.amazonaws.com
0.0.0.0 logs.ap-northeast-2.amazonaws.com
0.0.0.0 kinesis.ap-northeast-3.amazonaws.com
0.0.0.0 logs.ap-northeast-3.amazonaws.com
0.0.0.0 firehose.ap-south-1.amazonaws.com
0.0.0.0 kinesis.ap-south-1.amazonaws.com
0.0.0.0 logs.ap-south-1.amazonaws.com
0.0.0.0 firehose.ap-southeast-1.amazonaws.com
0.0.0.0 kinesis.ap-southeast-1.amazonaws.com
0.0.0.0 logs.ap-southeast-1.amazonaws.com
0.0.0.0 firehose.ap-southeast-2.amazonaws.com
0.0.0.0 kinesis.ap-southeast-2.amazonaws.com
0.0.0.0 logs.ap-southeast-2.amazonaws.com
0.0.0.0 firehose.ca-central-1.amazonaws.com
0.0.0.0 kinesis.ca-central-1.amazonaws.com
0.0.0.0 logs.ca-central-1.amazonaws.com
0.0.0.0 firehose.eu-central-1.amazonaws.com
0.0.0.0 kinesis.eu-central-1.amazonaws.com
0.0.0.0 logs.eu-central-1.amazonaws.com
0.0.0.0 firehose.eu-north-1.amazonaws.com
0.0.0.0 kinesis.eu-north-1.amazonaws.com
0.0.0.0 logs.eu-north-1.amazonaws.com
0.0.0.0 firehose.eu-west-1.amazonaws.com
0.0.0.0 kinesis.eu-west-1.amazonaws.com
0.0.0.0 logs.eu-west-1.amazonaws.com
0.0.0.0 firehose.eu-west-2.amazonaws.com
0.0.0.0 kinesis.eu-west-2.amazonaws.com
0.0.0.0 logs.eu-west-2.amazonaws.com
0.0.0.0 firehose.eu-west-3.amazonaws.com
0.0.0.0 kinesis.eu-west-3.amazonaws.com
0.0.0.0 logs.eu-west-3.amazonaws.com
0.0.0.0 firehose.me-south-1.amazonaws.com
0.0.0.0 kinesis.me-south-1.amazonaws.com
0.0.0.0 logs.me-south-1.amazonaws.com
0.0.0.0 firehose.sa-east-1.amazonaws.com
0.0.0.0 kinesis.sa-east-1.amazonaws.com
0.0.0.0 logs.sa-east-1.amazonaws.com
0.0.0.0 firehose.us-east-1.amazonaws.com
0.0.0.0 firehose-fips.us-east-1.amazonaws.com
0.0.0.0 kinesis.us-east-1.amazonaws.com
0.0.0.0 kinesis-fips.us-east-1.amazonaws.com
0.0.0.0 logs.us-east-1.amazonaws.com
0.0.0.0 firehose.us-east-2.amazonaws.com
0.0.0.0 firehose-fips.us-east-2.amazonaws.com
0.0.0.0 kinesis.us-east-2.amazonaws.com
0.0.0.0 kinesis-fips.us-east-2.amazonaws.com
0.0.0.0 logs.us-east-2.amazonaws.com
0.0.0.0 firehose.us-gov-east-1.amazonaws.com
0.0.0.0 firehose-fips.us-gov-east-1.amazonaws.com
0.0.0.0 kinesis.us-gov-east-1.amazonaws.com
0.0.0.0 logs.us-gov-east-1.amazonaws.com
0.0.0.0 firehose.us-gov-west-1.amazonaws.com
0.0.0.0 firehose-fips.us-gov-west-1.amazonaws.com
0.0.0.0 kinesis.us-gov-west-1.amazonaws.com
0.0.0.0 logs.us-gov-west-1.amazonaws.com
0.0.0.0 firehose.us-west-1.amazonaws.com
0.0.0.0 firehose-fips.us-west-1.amazonaws.com
0.0.0.0 kinesis.us-west-1.amazonaws.com
0.0.0.0 kinesis-fips.us-west-1.amazonaws.com
0.0.0.0 logs.us-west-1.amazonaws.com
0.0.0.0 firehose.us-west-2.amazonaws.com
0.0.0.0 firehose-fips.us-west-2.amazonaws.com
0.0.0.0 kinesis.us-west-2.amazonaws.com
0.0.0.0 kinesis-fips.us-west-2.amazonaws.com
```

**Comment by jawz101** [comment]
hmm.... well maybe I need to just remove it.  When I see something like FIPS I feel like I would be causing some sort of crypto/authentication mechanism.

I went ahead and removed them.  If anyone has any more insight into the whole enchilada I'd be interested to know what they may be used for.

**Comment by tophee** [comment]
Has `kinesis.us-east-1.amazonaws.com` recently been added back to the list? Last night my Phyn water leak detector stopped working and I got it to work again by whitelisting `kinesis.us-east-1.amazonaws.com` based on the instructions at https://www.phyn.com/help/why-am-i-not-seeing-water-usage-events-in-water-use-plus-i-cant-run-plumbing-checks-and-im-getting-phyn-is-having-trouble-communicating-with-your-device-messages/.

Is it possible to whitelisting a domain only for a specific host?

**Comment by dnmTX** [comment]
**ping** @jawz101 for assist ☝️

**Comment by jawz101** [comment]
Removed. Thanks

**Comment by StevenBlack** [comment]
Thanks Jawz @jawz101!

**Comment by tophee** [comment]
@jawz101 So do I understand correctly that those kinesis domains are used both for adds and more essential stuff, which forces us to unblock it? If so, is this a general trend for corporations to circumvent adblockers?

**Comment by jawz101** [comment]
@tophee I don't know.  People kept talking about it so I removed it.

**Comment by ericlagergren** [comment]
@jawz101 the FIPS domains are AWS locations that only use FIPS cryptography. They're usually only used by government services or by companies selling to the government.

**Comment by jawz101** [comment]
@ericlagergren old post.  It's not in adaway

**Comment by ericlagergren** [comment]
@jawz101 I understand, just wanted to clarify that for you.
