### ISSUE TITLE
api.Vsee.com breaks the Vsee doctor/patient video conferencing app

### ISSUE THREAD

**Issue by dkowis** [StevenBlack/hosts#1288]
I don't think it's related to vsee.tk at all, but it completely wrecks the Vsee app, which I had to use today to talk to my doctor. I'm not sure it should be blocked.

[Reddit posting on /r/pihole](https://old.reddit.com/r/pihole/comments/gnjsnt/vsee_doctorpatient_video_conference_is_blocked_by/)

**Comment by dnmTX** [comment]
@dkowis the domain in question is already removed by the list maintainer due to earlier complaint.
See #1286 for more details.
You probably need to update your lists or Steven @StevenBlack needs to do a fresh lists update here,not sure to be honest as those changes were recent.

**Comment by StevenBlack** [comment]
Hi David @dkowis the `vsee.tk` is blocked by [KADHosts](https://github.com/bigdargon/hostsVN/issues).  

Tomasz @fademind can you advise?

**Comment by dkowis** [comment]
> 
> Hi David @dkowis the `vsee.tk` is blocked by [KADHosts](https://github.com/bigdargon/hostsVN/issues).

I don't believe the `vsee.tk` is a problem, only the `api.vsee.com`, just noting it's existence, sorry for the confusion there.

> 
> Tomasz @FadeMind can you advise?

**Comment by dkowis** [comment]
I did just do an update of the pihole, so I think everything is golden. I can close this! Thanks!

```
 Match found in Whitelist
   api.vsee.com
 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   adslvseed.qq.com
   vsee.tk
   www.vsee.tk
```

**Comment by StevenBlack** [comment]
Tomasz @FadeMind nevermind, sorry.

**Comment by FadeMind** [comment]
@StevenBlack about `KADHosts` issues please call maintainer directly @hawkeye116477 
Thank you.
