### ISSUE TITLE
Microsoft Account scam website

### ISSUE THREAD

**Issue by CyanoTex** [StevenBlack/hosts#1289]
`https://www.asistencia.sisteltools.com/www.microsoftonline.com/docs.pdf/pyot0itscfpq3xbul0dodauf.php?client_id=00000002-0000-0ff1-ce00-000000000000&redirect_uri=https%3a%2f%2foutlook.office.com%2fowa%2f&resource=00000002-0000-0ff1-ce00-000000000000&response_mode=form_post&response_type=code+id_token&scope=openid&email=&msafed=0&client-request-id=94672646-1d8d-4b9c-9a15-b53cde7683f4&protectedtoken=false&nonce=636383871058172645.2ab44e64-544b-4b65-a646-7d31873d7911&state=Dcs7EoAgDEVR0HE5EWJePi4HBmtLt2-Kc7tbSyl72lLtmeImJiHh3DXYL4Oe15jAYyAFJmGa0jAY-RIOl-U3c833aO832g8#`

Got this gem on my Spam folder.

**Comment by StevenBlack** [comment]
Hi @CyanoTex I'm really not keen on sending myself down rabbit holes.

I'm also never keen to click on malicious links.  Ever.

What's the lowdown, here.

Because I'm basically done following raw leads that, in effect, say: "*here's a link Steve, there's something there, but nothing I want to be bothered to take a few seconds to qualify and elaborate for you.*"

I work at a scale that many people don't appreciate.  You should see me email inbox.

**Comment by dnmTX** [comment]
@CyanoTex  you can't just post some malicious links here,anyone can accidentally click on it.
Steve @StevenBlack  if you don't mind please edit his post and wrap it up with back quotes.
Thank you 👍

**Comment by CyanoTex** [comment]
> Hi @CyanoTex I'm really not keen on sending myself down rabbit holes.
> 
> I'm also never keen to click on malicious links.  Ever.
> 
> What's the lowdown, here?
> 
> Because I'm basically done following raw leads that, in effect, say: "*here's a link Steve, there's something there, but nothing I want to be bothered to take a few seconds to qualify and elaborate for you.*"
> 
> I work at a scale that many people don't appreciate.  You should see me email inbox.

OneDrive scam saying "you got a secure document", sends you to a login page for a fake as hell Microsoft Office 365 login page which will send the login details to those scammers.

**Comment by dalisoft** [comment]
@CyanoTex add two entry in your hosts

```hosts
0.0.0.0 asistencia.sisteltools.com
0.0.0.0 www.asistencia.sisteltools.com
```

This should prevent you from any future spam clicking

**Comment by CyanoTex** [comment]
> @CyanoTex add two entry in your hosts
> 
> ```hosts
> 0.0.0.0 asistencia.sisteltools.com
> 0.0.0.0 www.asistencia.sisteltools.com
> ```
> 
> This should prevent you from any future spam clicking

Done.
