### ISSUE TITLE
add more to the porn list, sinfonietta is sleeping

### ISSUE THREAD

**Issue by Danilopereira82** [StevenBlack/hosts#1291]
https://www.xfantasy.com/
https://callista.su/
http://beasttracker.dog/
http://sxyprn.net/
https://www.xfantasy.com/
https://myporn.club/
https://sakuracircle.com/
http://bangextreme.se/
https://c.gorilandcomic.com/
https://gorilandcomic.com/
https://leporno.info
https://www.javlibrary.com
http://jav-legend.com/
https://pornkai.com
https://www.boyfriendtv.com
https://sanctuary.in.net
http://www.funeralofsmiles.com/
[ literotica stuff ]
https://literotica.com/
https://shop.literotica.com/
https://www.literoticavod.com/
https://vipcams.literotica.com/
https://forum.literotica.com/

**Comment by StevenBlack** [comment]
Hi @Danilopereira82 please post this at https://github.com/Sinfonietta/hostfiles/issues.  If it's already posted there, please don't re-post it here.  Thank you.
