### ISSUE TITLE
Github-hosted content results in error: "Can't download the hosts file. It contains unknown content."

### ISSUE THREAD

**Issue by PickJBennett** [StevenBlack/hosts#1299]
Hi @StevenBlack,

I've tried to add multiple raw hosts files, directly from Github, and not one has allowed me to download the hosts file. I'd really love to add several of the "Raw hosts" from https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant to my combined local hosts file.

I'm able to see the content of these hosts files directly in my browser without a problem.

I'm using the latest version of Gas Mask v0.8.6 on Mac OS X Mojave v10.14.6 (18G103).

Thank you for your help!

**Comment by StevenBlack** [comment]
Hi Rick @PickJBennett how are you attempting downloading these?  Using what url — can you provide a URL that isn’t working for you?  What is the OS you are using for this?

**Comment by PickJBennett** [comment]
Hi @StevenBlack,

It's easier to say which ones are working because there are fewer. I've been able to download a total of 7 inside the app, but almost all others have resulted in this error. I'm adding links like this: **+ Create button > Remote > Paste URL > Add button**

These next links are the ones that have downloaded correctly:

- https://www.malwaredomainlist.com/hostslist/hosts.txt
- http://sbc.io/hosts/alternates/gambling/hosts
- http://sbc.io/hosts/alternates/social/hosts
- http://sbc.io/hosts/alternates/fakenews/hosts
- https://winhelp2002.mvps.org/hosts.txt
- http://sbc.io/hosts/hosts

As for the ones that failed in the app, I've tested these (and other domains) that render perfectly in the browser:

- https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
- https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
- https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
- https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
- https://someonewhocares.org/hosts/zero/hosts
- https://urlhaus.abuse.ch/downloads/hostfile/
- https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0

Downloading these files manually, then adding them as local hosts files works fine. But I'd love to be able to auto-update the hosts files. :)

**Comment by StevenBlack** [comment]
This is a “feature” in GasMask, no doubt.  Hostman for Windows has a similar issue.

Try downloading from the mirror links instead.

Closing.
