### ISSUE TITLE
ModuleNotFoundError: No module named 'lxml'

### ISSUE THREAD

**Issue by coryb08** [StevenBlack/hosts#1303]
when running makeHosts.py I get `ModuleNotFoundError: No module named 'lxml'`

**Comment by funilrys** [comment]
Hi @coryb08  and thanks for your time. 

As stated in the [README](https://github.com/StevenBlack/hosts#generate-your-own-unified-hosts-file):

> First, install the dependencies with:
>
> ```
> pip3 install --user -r requirements.txt
> ```

Stay safe and healthy.

**Comment by dandonahoe** [comment]
@coryb08 

Got the same error and finally noticed other warnings about my pip and python being outdated.

One of these ended up fixing it. First line is part of the error message you're currently getting:

`/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install --upgrade pip`
`brew update && brew upgrade`
`brew reinstall python`

**Comment by funilrys** [comment]
Hi @dandonahoe @coryb08 !

As stated in the [README](https://github.com/StevenBlack/hosts#generate-your-own-unified-hosts-file):

> To generate your own unified hosts file you will need Python 3.5 or later.


Stay safe and healthy!

**Comment by coryb08** [comment]
Instructions were buried in readme
