### ISSUE TITLE
List of domains by category

### ISSUE THREAD

**Issue by heipei** [StevenBlack/hosts#1304]
Is there a way to get the blocklists with the category (adware/porn/fakenews) the domain belongs to next to it (e.g. as a comment or in CSV format)? Use-case is that I'd like to use these for programmatic purposes and not just blocking. Excuse my ignorance if there is a way that I haven't found yet.

**Comment by StevenBlack** [comment]
Hi Johannes @heipei, the file you seek is [here](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-porn/hosts) and [here is the readme for that](https://github.com/StevenBlack/hosts/tree/master/alternates/fakenews-porn).

As you can see our specialty variants are stored in the [`alternates` folder](https://github.com/StevenBlack/hosts/tree/master/alternates/).

From there you can run a quick bash script to clean all the lines.  You could also use my [ghosts](https://github.com/StevenBlack/ghosts) tool for that.  That repo has binaries for a variety of operating systems.  It's written in Go.

Closing.
