### ISSUE TITLE
Script not working anymore, FileNotFoundError in a random file that doesn't seems to be related to anything

### ISSUE THREAD

**Issue by FabioNevesRezende** [StevenBlack/hosts#1306]
So, I use to run the `updateHostsFile.py` regularly like every week just to keep updated to the most recent addresses but I noticed that now the script is not running anymore but also giving a strange error in a file that doesn't even seems to be related to the program.

What do I do:
I always run with this command and always worked
`python3 /home/fabio/src/hosts/updateHostsFile.py -a -r -b -e gambling porn social`

Now when I run I cant wait for hours and nothing happens, when I type CTRL+C to finally interrupt it, the console shows the following stack trace and error messages:

> $ python3 /home/fabio/src/hosts/updateHostsFile.py -a -r -b -e gambling porn
> ^CTraceback (most recent call last):
>   File "/usr/lib/python3.8/posixpath.py", line 177, in lexists
>     os.lstat(path)
> FileNotFoundError: [Errno 2] No such file or directory: 'OneDrive/criação/atendimento/mywebsite/node_modules/dom-accessibility-api/update.json'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/fabio/src/hosts/updateHostsFile.py", line 1696, in <module>
>     main()
>   File "/home/fabio/src/hosts/updateHostsFile.py", line 228, in main
>     update_all_sources(source_data_filename, settings["hostfilename"])
>   File "/home/fabio/src/hosts/updateHostsFile.py", line 673, in update_all_sources
>     all_sources = recursive_glob("*", source_data_filename)
>   File "/home/fabio/src/hosts/updateHostsFile.py", line 1561, in recursive_glob
>     return glob(stem + "/**/" + file_pattern, recursive=True)
>   File "/usr/lib/python3.8/glob.py", line 21, in glob
>     return list(iglob(pathname, recursive=recursive))
>   File "/usr/lib/python3.8/glob.py", line 74, in _iglob
>     for name in glob_in_dir(dirname, basename, dironly):
>   File "/usr/lib/python3.8/glob.py", line 94, in _glob0
>     if os.path.lexists(os.path.join(dirname, basename)):
>   File "/usr/lib/python3.8/posixpath.py", line 177, in lexists
>     os.lstat(path)
> KeyboardInterrupt
> 

So, the most strange for me is why the heck a `FileNotFoundError` at   `OneDrive/criação/atendimento/mywebsite/node_modules/dom-accessibility-api/update.json` is happening? this doesn't seems to make sense for me.

I'm using Artix linux with python version 3.8.3. Thanks for the help.

**Comment by funilrys** [comment]
Hi @FabioNevesRezende !
Welcome here and thanks for your time!

All scripts (at the current date-time) suppose that you are inside the Git (root) directory of this project.

So, in your case:

```
$ cd /home/fabio/src/hosts/updateHostsFile.py && python3 updateHostsFile.py -a -r -b -e gambling porn social && cd ${OLDPWD}
```

Stay safe and healty.

**Comment by FabioNevesRezende** [comment]
Well, that's strange, it really worked now but it also used to work in any directory, that's why I even had an alias to run in directly:

`alias hosts_update='sudo python3 /home/fabio/src/hosts/updateHostsFile.py -a -r -b -e gambling'`

Anyway, thanks for the help

**Comment by funilrys** [comment]
On my side (as one of the ones who wrote /modified/improved those scripts) it should not "work in any directory".

I don't know what kind of black magic you're using but it should not work :smile_cat: 

Your welcome!
