### ISSUE TITLE
List is blocking legitimate url:api.punchh.com

### ISSUE THREAD

**Issue by luisv5z** [StevenBlack/hosts#1309]
As discussed on [NextDNS Issue #260](https://github.com/nextdns/metadata/issues/260).

The list is blocking the login url for blazepizza.com

**Comment by StevenBlack** [comment]
Thanks Luis @luisv5z.

Ping @jawz101 — can you look at this?  Presently 13 `punchh.com` domains are blocked which indicates to me, `punchh.com` is unclean.

Luiz @luisv5z it's possible that Blaze Pizza has made some unfortunate choices.  I'm letting the folks at AdAway continue to decide.

**Comment by luisv5z** [comment]
@StevenBlack Got it, thanks for checking it out!

**Comment by jawz101** [comment]
geez.  Even going to their website they have a cookie consent box w/ an opt-out checkbox saying "So Not Sell My Personal Information"

I wish I had access to their developer documentation to see what they mean by

```
Reveal the Anonymous
Get to really know your customers, generating insights from every channel, in-store or online

Punchh Acquire
Supercharge your customer acquisition by optimizing omnichannel marketing and analytics. Easily and cost-effectively turn anonymous consumers into customers – and customers into brand loyalists.
```

If this does any location or proximity tracking, asks for phone/contacts/sensors/text/etc. permissions that would be my concern.

**Comment by jawz101** [comment]
Yeah, I'm going to stand firm that someone can whitelist this if they want it.  Looking at their privacy policy and the CEO's past experience with location-based stuff, I'm really not interested in allowing it.  These are the sorts of removals that make me lose the reason why I blocked them in the first place.

**Comment by dnmTX** [comment]
@jawz101  just FYI:

> "So Not Sell My Personal Information"

This only applies to California residents,everyone else is under the knife.

**Comment by jawz101** [comment]
If someone has can tell me that their apps don't have proximity, read cell info or location permissions, clipboard or sensor access I'd remove it.  sensor & clipboard permissions on Android cannot be controlled by the end user w/o something like XPrivacyLUA so I really don't have any way to prove they don't do something I cannot see.

**Comment by StevenBlack** [comment]
Good call, @jawz101.  Thank you, as always, for taking the time to review this.  Thanks for the comment, Dan @dnmTX.

There you have it, Luis @luisv5z.

Closing.

**Comment by llacb47** [comment]
`https://www.fastcasual.com/news/blaze-fast-fired-pizza-partners-with-punchh-for-mobile-app-launch/`

**Comment by StevenBlack** [comment]
Thanks LE @llacb47.  

I think I can safely say, people who *want* to be tracked and sold by a Pizza chain aren't typical of the people we serve, here 😄.

**Comment by luisv5z** [comment]
@StevenBlack @jawz101 Guys, thank you so much for this. 🙌🏽

I guess, the more you know...

**Comment by jawz101** [comment]
Well, I'm not one to dismiss them.  Like if all of the marketing is user initiated (Sign up for rewards points!) I'd feel like it's up to the user.

If they were tracking your location, using bluetooth proximity to throw coupons at you when you're near some place, requesting calendar, clipboard, microphone permission, etc.  Or if they sell your data to others.  How do I get that 3rd party twice-removed to delete my data that they got from the first person?  Stuff like that creeps me out and once I see a worse-case scenario I assume everyone does it.

I'd allow them if I knew how their stuff works.  Privacy policies are usually pretty vague on specifics.
