### ISSUE TITLE
OpenDNS categories

### ISSUE THREAD

**Issue by aysark** [StevenBlack/hosts#1312]
Great repo and I appreciate all the contributors' efforts!

I'm looking to also include a list of OpenDNS web content filtering categories- is this possible?  I'm sure there is an intersection of some of these with the existing alternates hosts files... but just wondering what the delta is?
![image](https://user-images.githubusercontent.com/654356/84538919-57285b80-aca7-11ea-834c-cce1a73d0a5e.png)

**Comment by StevenBlack** [comment]
Hi Aysar,  I hear you.  I would love to be able to offer this.

We don't have this level of granularity.  High quality actively curated hosts lists are hard to find.  The good ones all seem to be coarse grained.  

For example, the porn extension currently includes some Hentai that doesn't appear pornographic, to me.  This might matter to some people.  Presently we don't have a solution for that.

Despite that, I feel we're in a good place, right now.  We have five categories, four of which are optional and can be mixed.  The list above has 58 categories.  But if you look closely, they have five (`High`, `Moderate`, `low`, `none`, and `Custom`) and it's the `Custom` that has 58 subcategories.

I think 58 categories would be nice; I can't yet see how that would work, in practice.
