### ISSUE TITLE
Issue with ExpressVPN

### ISSUE THREAD

**Issue by ObsessedHacker** [StevenBlack/hosts#1314]
Something in the hosts file is blocking the connection to VPN, specifically ExpressVPN - https://www.expressvpn.com/
I downloaded this - https://github.com/StevenBlack/hosts/releases - Release 2.6.21 (latest)
So in order to solve this problem, I just deleted the file from my computer and now I'm able to connect to the VPN.
Which line is blocking the connection? And why is it in there?

**Comment by StevenBlack** [comment]
Hi @ObsessedHacker we are going to need to know, what domain we need to consider unblocking.  We can't just guess.  We don't block any domain with `expressvpn` in its name.

**Comment by ObsessedHacker** [comment]
> Hi @ObsessedHacker we are going to need to know, what domain we need to consider unblocking. We can't just guess. We don't block any domain with `expressvpn` in its name.

To be honest, I don't even know which line is causing this issue, I searched for every line that has "VPN" in it and didn't find "ExpressVPN", so I have no idea. But I do know that something in this file is blocking the connection.

**Comment by ObsessedHacker** [comment]
After some little tweaks to the file, I found that the issue is between the 30,000 lines mark to the 50,000 lines mark.
I found that out by deleting the lines and checking my connection.

**Comment by StevenBlack** [comment]
@ObsessedHacker over 500 developers follow this repo and its messages.

We don't need a play-by-play.  We need to know, which specific domain(s) are a problem for you.

Thanks.

**Comment by llacb47** [comment]
@ObsessedHacker I think you should use Fiddler to see which domain ExpressVPN is trying to connect to.

**Comment by ObsessedHacker** [comment]
Never mind, for some reason I think it worked out, I downloaded the latest hosts file, connected to the VPN and waiting a long time till I have a connection, so I don't know now if it's the VPN causing the issue or the hosts file, so anyway I'll close this issue now.
