### ISSUE TITLE
Italian Phishing

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1315]
italiapagamen.com
5306.findprofile.net.pl

**Comment by StevenBlack** [comment]
Thanks Lorenzo @scafroglia93.

Tomasz @FadeMind or Jarvis @PolishJarvis can you comment on `5306.findprofile.net.pl`?  Will you list that?

**Comment by StevenBlack** [comment]
Lorenzo @scafroglia93 I've added `italiapagamen.com` to my ad-hoc list in commit de675b7.

**Comment by StevenBlack** [comment]
Ping @hawkeye116477 — sorry I have a friend named Jarvis, and I see now, @PolishJarvis is a bot 😄

**Comment by hawkeye116477** [comment]
Seems this is very recent domain and can be more subdomains with random chars. Thanks, added :smile:.

**Comment by StevenBlack** [comment]
Thank you @hawkeye116477.

Closing!
