### ISSUE TITLE
Unblock constantcontact.com domains

### ISSUE THREAD

**Issue by YogiJB** [StevenBlack/hosts#1316]
constantcontact.com (with all subdomains)
This is a domain that sends newsletters and being used by legit organizations.

ecampaigns.cineplex.com
Newsletters from a trusted company.

Please unblock these domains/subdomains.

**Comment by StevenBlack** [comment]
Hi @YogiJB thanks for this.

As I research this, I think you need to know there are no "legit organizations" in this space.  The name-brand attached to a domain counts for exactly zero.  The only thing that matters is, does a domain track or trade its users?  Does it serve ads?  It it a path for malware?

Understad what I mean?

**Comment by StevenBlack** [comment]
@YogiJB the domain `constantcontact.com` comes to us via Awaway.

Ping @jawz101, what do you think?

@YogiJB take note: we don't list `ecampaigns.cineplex.com`.  We don't list any `cineplex` domain.

**Comment by jawz101** [comment]
removing.  Purely because the Adaway list is meant for traffic that comes from mobile apps (i.e. not email marketing, browser, or desktop app traffic.)
If I see those domains again I'll review it later

https://github.com/constantcontact/java-sdk

**Comment by StevenBlack** [comment]
Thanks Jawz! @jawz101.

@YogiJB this will go into wider distribution for the next release, soon.

Closing.
