### ISSUE TITLE
INFO WORK

### ISSUE THREAD

**Issue by eglabitalia** [StevenBlack/hosts#1319]
Hello Steven, congratulations on your extraordinary work. I've always wondered but how do you compile the host file and keep it updated? do you have special computers or software?

Best regards

Edward ( from italy)

**Comment by StevenBlack** [comment]
Thank you for the kind words Edward @eglabitalia.

It's mostly manual processes.  Here is my main workflow:

* Run a `git pull` locally. 
* Execute [`makeHosts`](https://github.com/StevenBlack/hosts/blob/master/makeHosts.py) here locally to refresh data and compile new `hosts` files.  This refreshes data from 27 different sources, and produces the 16 different amalgamated hosts files we offer here.
* I use [Git Tower](https://www.git-tower.com/) to display the `diff`s for each data source.  I look at every change from all sources, paying more attention to domains added than domains removed. I sometimes catch mistakes at this stage.  When I do, i abort the release, contact the source curator, ask questions.  This can delay the release by a day or two.
* Once everything looks good, I commit changes and push to GitHub.
* Next I use @webpro's most excellent [release-it](https://github.com/release-it/release-it) to create a release tag, commit, and push the release on GitHub.

Other than that, I watch our [Issues](https://github.com/StevenBlack/hosts/issues) page as often as I can, and try to stay abreast of what's happening in the security space, every day.

That's how I work.  Thank you for asking!

**Comment by eglabitalia** [comment]
Thanks for the reply Steven. Do an amazing job .. you are a really good developer. Congratulations again for the great job you do for all of us. 

Best regards
Edward

**Comment by StevenBlack** [comment]
Your welcome Edward @eglabitalia.  This repo is the collective work of [many contributors](https://github.com/StevenBlack/hosts/graphs/contributors) and, I'm happy to say, they are all awesome people.
