### ISSUE TITLE
Few MIUI domains

### ISSUE THREAD

**Issue by pidus** [StevenBlack/hosts#1326]
I found these domains while looking at the connection log using personalDNSfilter app on my Xiaomi phone. 

`api.device.xiaomi.net`
`api.sec.miui.com`

Blocking them in AdAway doesn't seem to break anything. 
As your list already blocks most MIUI/Xiaomi trackers I think maybe you would like to include them too. 
Thanks.

**Comment by Laicure** [comment]
Then this should go to @jaws101?
https://github.com/AdAway/adaway.github.io

**Comment by pidus** [comment]
@Laicure Well, Steven Black's own list blocks lots of MIUI domains which is why I posted them here. 

https://github.com/StevenBlack/hosts/blob/master/data/StevenBlack/hosts

**Comment by Laicure** [comment]
Oh what the pak!
Apologies, I read your post as Adaway already blocks MIUI domains.

**Comment by jawz101** [comment]
added to the adaway list.  StevenBlack should pull them in on their next update they get from Adaway

**Comment by StevenBlack** [comment]
Thanks everybody!  @pidus this will be live in the next release, coming soon.

Closing.
