### ISSUE TITLE
Could you help me change a host?

### ISSUE THREAD

**Issue by gallegonovato** [StevenBlack/hosts#1327]
Good afternoon:

First of all, thank you very much for your help and time.

It turns out I wanted to change a host I use in Adaway.  More specifically https://www.malwaredomainlist.com/hostslist/hosts.txt

I don't know if you could recommend me any other or substitute the one I mentioned for yours Unified hosts = (adware + malware) or Unified hosts + fakenews + gambling + porn + social?

I currently use your host https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts that I don't know if it opens the other hosts?

Receive a warm hug and forgive the inconvenience.

**Comment by StevenBlack** [comment]
Hi @gallegonovato, welcome, and thank you for this question.

I am having difficulty understanding what you are asking.

Can you ask again, in a different way?  You can ask in your own language, if you prefer.  We'll figure it out 😄

**Comment by gallegonovato** [comment]
Good afternoon, Steven:

  I've been using Adaway for years.  And I use several of her host lists.

But I would like to remove this from https://www.malwaredomainlist.com/hostslist/hosts.txt because when I update the host lists on adaway.  That list is always up to 5 months.  Which I understand has been out of date for some time.

And I use your hosts:

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Unified hosts = (adware + malware)

Unified hosts + fakenews + gambling + porn + social

My question is: your three host lists, what do I tell you?  Without enough to remove the other one I'm talking about.  Or do you know any other host list to replace it

Or even, if I may permutate the question.  There's a list of hosts that I know of, that help with privacy.

Get a warm hug and thank you for your time and help

En español:

Buenas tardes Steven:

 llevo usando Adaway desde hace años. Y uso varias listas de host suyas.

Pero querría quitar estar lista : https://www.malwaredomainlist.com/hostslist/hosts.txt ya que cuando actualizo las listas de host en adaway. Esa lista siempre pone para 5 meses. Lo que entiendo que lleva tiempo desactualizada.

Y uso sus host:

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Unified hosts = (adware + malware)

Unified hosts + fakenews + gambling + porn + social

Mi pregunta es: sus tres listas de host, que le comento. Sin suficiente para quitar la otra que le comento. O conoce usted alguna otra lista de host para sustituirla

O incluso, si me permute la pregunta. Hay alguna lista de host que conozca, que ayuden a la privacidad.

Reciba un cordial abrazo y gracias por su tiempo y ayuda

**Comment by StevenBlack** [comment]
@gallegonovato if I understand the question, try this:

1) Clone this repository
2) Remove sources you don't like from the `/data` folder
3) Rebuild hosts files with `makeHosts.py`
4) Pick whichever hosts file you would like from the root folder, or any of the `/alternates` folders.

**Comment by gallegonovato** [comment]
Good morning to Stevenblack:

Thanks for your help and time.

I don’t think we understand each other :(

The question I’m trying to ask you. Is if your host lists:

Unified hosts = (adware + malware) or Unified hosts + fakenews + gambling + porn + social

They could replace the host list https://www.malwaredomainlist.com/hostslist/hosts.txt. (which I use in Adawa and would like to delete it, and put another in its place)

The latter is not updated.

Or if you could recommend some other host list to improve privacy and security

A hug

**Comment by StevenBlack** [comment]
@gallegonovato my answer remains largely unchanged.

1. Clone this repository
2. **DO WHATEVER YOU NEED TO DO IN THE `/data` FOLDER**.  Make the edits you need to make.
3. Rebuild hosts files with makeHosts.py
4. Pick whichever hosts file you would like from the root folder, or any of the /alternates folders.

I'm going to close this issue now.
