### ISSUE TITLE
Found some ad domains

### ISSUE THREAD

**Issue by CyanoTex** [StevenBlack/hosts#1331]
Was doing a look through the family NextDNS config's logs. Some of these slipped through.

``macro.adnami.io
cl-ad.x-flow.app
adtracker.mkjigsaw.com
backend-ssp.adstudio.cloud
mjp.zimad.com
log-ads.r7.com
ad-dev.globalnoticias.pt``

**Comment by StevenBlack** [comment]
Thanks @CyanoTex these are added in commit 63379987.

Closing.
