### ISSUE TITLE
Adding two ads sites

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1334]
As mentioned in https://github.com/nextdns/metadata/issues/312
please add the following two sites:

```
https://runative-syndicate.com/

https://www.protectmobiletechieai.club/
```

Both are open annoying windows/ popups on a streaming site

**Comment by StevenBlack** [comment]
Hi Brew @beerisgood, this is done in commit ddafbad.

**Comment by beerisgood** [comment]
Wow that was fast.
Thanks!
