### ISSUE TITLE
More ad domains that aren't blocked

### ISSUE THREAD

**Issue by CyanoTex** [StevenBlack/hosts#1335]
Here's a batch of them, from the family NextDNS configuration.

`xad.dnoticias.pt ad.dnoticias.pt data.madovergames.com advert.puzzles.mkjigsaw.com adtracker.mkjigsaw.com`

**Comment by CyanoTex** [comment]
Note: Not sure if `data.madovergames.com` plays a role regarding game save data or data for a game. Goodbye Ads has blocked it regardless on my personal configuration.

**Comment by StevenBlack** [comment]
Thanks @CyanoTex.  I added four domains, leaving out `data.madovergames.com`.

Closing.

**Comment by CyanoTex** [comment]
Upon further thought, perhaps `data.madovergames.com` was blocked for a good reason over at Goodbye Ads. Can you add this domain to Unified Hosts?
