### ISSUE TITLE
New list sources

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#1347]
Hello. A few (well, a lot of) ad/malware domains have been compiled by the OpenWRT project:

https://github.com/openwrt/packages/blob/master/net/adblock/files/README.md

Could these be absorbed into this repo and regularly synced?

**Comment by StevenBlack** [comment]
Hi @hyder365 thank you for this suggestion.

Several of our sources, including our amalgamated list, are in that list.

Which component of that list do you recommend absorbing here?

Our main criteria is, the lists we carry are all actively curated.  We aren't interested in add-only buckets of countless domain names.  Quality, for us, comes from active curation.

**Comment by hyder365** [comment]
In particular I'm interested in the adguard list, which is well known and actively maintained. Slightly less important, but still nice to have, would be the ones specializing in mobile ads,YouTube ads, and smart TV telemetry. Many of the non-English lists, bitcoin miners, and so on are less important.

**Comment by StevenBlack** [comment]
@hyder365 we've talked about AdGuard before, particularly in Issue #1181.  Review that, so you're up-to-speed.

I think AdGuard would be a good addition.  I have concerns about how this list is properly curated.

**Comment by hyder365** [comment]
Thanks for the link. Even without AdGuard, some of these would be nice to add.

The YouTube one (https://github.com/kboghdady/youTube_ads_4_pi-hole) has made a big difference here!

**Comment by StevenBlack** [comment]
I'm considering adding several new sources, and this is one of them.

**Comment by dnmTX** [comment]
> I'm considering adding several new sources, and this is one of them.

Steve @StevenBlack  i've read some of the issues: [example](https://github.com/kboghdady/youTube_ads_4_pi-hole/issues/80).
Doesn't look like it works for everyone with some stating that the videos can't even start playing. Also the curator recommends 
the list to be updated at least daily. Not sure that you want go trough that hassle.

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX that clarifies things for me.
