### ISSUE TITLE
Are you currently open to general code tweaks/changes?

### ISSUE THREAD

**Issue by AlexanderCecile** [StevenBlack/hosts#1348]
Hello,

As the title indicates, I was curious whether or not you're currently accepting changes to the Python part of this project. I noticed a few things which I would be happy to work on, like some of the "helper" functions, for example.

There are also some slightly larger tasks/questions, but those can (and probably should) wait :)

Where is the best place for more informal discussion on the project?

Thank you for your time.

**Comment by funilrys** [comment]
Hi @AlexanderCecile  and welcome here!

Everything is welcome, I will be glad to review or discuss the changes! As of today, we still don't have a platform to discuss about this project, but it may come in the future.

You can contact me or Steve @StevenBlack on Keybase: 

* me: https://keybase.io/funilrys/chat
* Steve @StevenBlack: https://keybase.io/StevenBlack/chat

Otherwise, you can create an issue about what you are going to implement.

Stay safe and healthy!
Nissar

**Comment by AlexanderCecile** [comment]
Hi @funilrys 

Thank you for the information. I am somewhat new to this, I'm guessing that creating issues is preferred over discussing all the changes when the pull request is in?

Thank you.

**Comment by StevenBlack** [comment]
Hi Alexander @AlexanderCecile yes here in issues is a good place.  You can just continue in this issue if you like.

As for IDE, I use a terminal window for everything related to hosts.  And I use a text editor, of course.  There really isn't any package management going on here.

**Comment by AlexanderCecile** [comment]
@StevenBlack 

> As for IDE, I use a terminal window for everything related to hosts. And I use a text editor, of course.

I might have to do the same. I usually stick with PyCharm, but in the tests it complains on `sys.stdout.getvalue()`: _Unresolved attribute reference 'getvalue' for class 'TextIO'_ It's quite confusing, since I can run the tests from the command line just fine, yet using a run/debug configuration leads to an error (_AttributeError: '\_io.TextIOWrapper' object has no attribute 'getvalue'_) which *seems* to come from the IDE's test runner. If I can't figure this out, I think I'll try to reach out to the devs of the IDE.

**Comment by funilrys** [comment]
@AlexanderCecile, stick with Python 3.8. Just don't be tented to use f-string or walrus operator and we should be good.

For development, I personally use vscode and miniconda. 

Let us know if something weird is happening while you try to dig into the source code!

**Comment by AlexanderCecile** [comment]
@funilrys 

> stick with Python 3.8. Just don't be tented to use f-string or walrus operator and we should be good.

For backwards-compatibility? Are type hints alright, since they were introduced in Python 3.5?

> For development, I personally use vscode and miniconda.

Awesome, I use miniconda too!

> Let us know if something weird is happening while you try to dig into the source code!

Will do, I'm currently working on narrowing down the issue. It seems that the `BaseStdout` class and the test runner used by PyCharm don't mix well.

**Comment by XhmikosR** [comment]
BTW miniconda was giving me trouble setting up Windows CI. I don't see why we need miniconda on CI TBH. If we dropped it, we could test all OS'es equally on GitHub Actions CI :)

**Comment by AlexanderCecile** [comment]
@XhmikosR What was the issue?

**Comment by AlexanderCecile** [comment]
Update: The program appears to get stuck in `update_all_sources -> recursive_glob -> glob`. `glob()` is called with the `pathname` value `"*/**/update.json"`.

**Comment by funilrys** [comment]
@XhmikosR You have my OK to remove miniconda. I'll review your patch. Windows support is becoming important so for the future, so let's drop miniconda!

@AlexanderCecile Let's discuss it around PR/patches! :smile_cat:

**Comment by funilrys** [comment]
@AlexanderCecile 
> Edit: As an aside, how long should it take to run updateHostsFiles.py ? After a quick glance at the docs/code, I ran it with the arguments --auto --backup, and it seems like it might be frozen.

It depends on your network speed/bandwidth.

**Comment by AlexanderCecile** [comment]
@funilrys 

> @AlexanderCecile Let's discuss it around PR/patches! 😸

Who would be the best person to ask about general design/architecture choices? Can I just post them here? I don't want to make many changes to the code if they end up being a poor fit for the project as a whole.

**Comment by StevenBlack** [comment]
Just go ahead Alexander @AlexanderCecile, let's hear what's on your mind.  It's nice that you ask, but cut to the chase, it's all good!  👍

**Comment by AlexanderCecile** [comment]
What is the focus of this repo/project? Are people primarily here for the hand-curated lists of hosts, or the application which parses and combines the lists?

A few more assorted questions/comments:

- In the `prompt_for_update` function, there is a try statement which contains the following code: `open(hosts_file, "w+").close()`. The corresponding except catches `IOError` and `OSError`, which IIUC isn't necessary in Python 3, and prints `"ERROR: No 'hosts' file in the folder. Try creating one manually."` However, the `w+` mode will create the file if it doesn't exist, so if error does occur that can't be the cause, which means the message that is printed is not accurate.
- Why not use a simple class for the hostname, instead of just strings?
- What is the `domain_to_idna` function for?
- I find the name of the `get_file_by_url` function to be misleading. The code could be simplified greatly, using BeautifulSoup and lxml for this is overkill, the much more general and common requests library should be able to do the job just fine.
- Have you considered switching to the more modern and high-level pathlib for most file path operations?
- Is the `write_data` function really necessary?


There is probably more, I'll see if I can tweak the code and submit multiple PRs.

**Comment by StevenBlack** [comment]
@AlexanderCecile we're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.  This repository has over 900 issues and over 400 pull requests, and 2,200+ commits that, on aggregate, attest to what we do here.

Did you know... with git, and through the Github interface, you can find the full history on any line of code by using the `git blame` command (in git) or by selecting the line of code (here on Github) and clicking the little `...` button that will appear beside it, once the line is selected.

I feel I should say, we don't presently have any problems with our code.  It's been functioning reliably, and evolving, since 2012.  So I hear you 👂, but you're scratching an itch we really don't have.

I'm always happy to improve things....

**Comment by AlexanderCecile** [comment]
> Did you know... with git, and through the GitHub interface, you can find the full history on any line of code by using the git blame command (in git) or by selecting the line of code (here on GitHub) and clicking the little ... button that will appear beside it, once the line is selected.

What would I use that for, with respect to what I mentioned in my previous comment?

> I feel I should say, we don't presently have any problems with our code. It's been evolving functioning reliably since 2012. So I hear you 👂, but you're scratching an itch we really don't have.

How do you define "problem" ? Which part(s) of my comment are you referring to?

**Comment by StevenBlack** [comment]
Alexander @AlexanderCecile I'm going to close and lock this conversation now. I just don't have the bandwidth.

We're 17 messages deep and it appears to becoming circular.  I'm not going to parse this conversation for you.  You are either on the minimum required level, or not.  It appears not.

Thank you, nonetheless, for your input.
