### ISSUE TITLE
Hosts file URL not recognized by HostsMan

### ISSUE THREAD

**Issue by jw243** [StevenBlack/hosts#135]
When I try to add the url of your raw hosts file (https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-social/hosts) as a source to HostsMan, I get the error message "This source is not compatible. Server does not return all the necessary information". Could you do anything about it? Thanks.

**Comment by StevenBlack** [comment]
I don't use HostMan and I don't use Windows much.

Can you give me some info about the *necessary information* HostsMan requires?

**Comment by JamoCA** [comment]
@StevenBlack I think I may have identified the "necessary information"...
https://github.com/StevenBlack/hosts/issues/215#issuecomment-530031648

**Comment by StevenBlack** [comment]
Resolved in Issue #215.  Closing.
