### ISSUE TITLE
[adding] updatesecure.pro

### ISSUE THREAD

**Issue by andruyd** [StevenBlack/hosts#1350]
updatesecure.pro spoofs Windows UI for updates, malware/virus scanning

**Comment by StevenBlack** [comment]
@andruyd do you have documentation, or a reference, for this?  Thanks.

**Comment by CyanoTex** [comment]
> @andruyd do you have documentation, or a reference, for this?  Thanks.

Google Safe Browsing already has the website in their database.

More specifically, according to my NextDNS config block page, it falls under `googlesafebrowsing:social-engineering`.

![Screenshot_20200716-112322616.jpg](https://user-images.githubusercontent.com/62466866/87660457-99cdcf80-c74e-11ea-8b92-6ae556c5d40f.jpg)

**Comment by StevenBlack** [comment]
Thanks @andruyd this domain is added in commit 3cbdc649.

Closing.
