### ISSUE TITLE
Two specific ad domains

### ISSUE THREAD

**Issue by CyanoTex** [StevenBlack/hosts#1352]
Here I am, going through my family's NextDNS config and I found these two ad domains.

`advertising-cdn.dpgmedia.cloud advertisements.immowebapi.be`

**Comment by dnmTX** [comment]
`advertising-cdn.dpgmedia.cloud` is already blocked here

**Comment by CyanoTex** [comment]
> `advertising-cdn.dpgmedia.cloud` is already blocked here

That just leaves ImmoWeb then.

**Comment by StevenBlack** [comment]
Thanks @CyanoTex this is added in commit 3cbdc649. 

Closing.
