### ISSUE TITLE
[adding] more ads domains

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1353]
```
completesatisfaction.ltd
lp.mydirtyhobby.com
de.betano.com
makmoney.club
fgddl9szdof7.com
448ff4fcfcd199a.com
landings.twin.com
```

are another ads site.

Please see also 
`ww2.sponsorflyr.com`
from https://github.com/StevenBlack/hosts/issues/1344

**Comment by StevenBlack** [comment]
Thanks for this Brew @beerisgood.

Do you have any documentation on why we should include each of these hosts? Where do these come from?

**Comment by beerisgood** [comment]
Beer is good :D 

I got all of these on different streaming sites and they open itself and are real annoying.

**Comment by StevenBlack** [comment]
Thanks Beer @beerisgood.  These are added in commit 0f046591.
