### ISSUE TITLE
scam/malware/redirects hosts

### ISSUE THREAD

**Issue by mikalauskas** [StevenBlack/hosts#1354]
llink.site
bitstarz27.com
bitstarz28.com
bitstarz1.eu 
bs.direct
comilar-efferiff.icu
abdurantom.com
trafficmoose.com
pkmkkjwknvf.com
1144133033.rsc.cdn77.org
plkyjbew.com
found.ee
mobile-app-market-here6.life
laingriz15.live
bestprizesday3.life
coropolifonicocittadiladispoli.it
carniferou.club
ikunselt.com

**Comment by StevenBlack** [comment]
Thanks for this @mikalauskas.

Do you have any documentation on why we should include each of these hosts?  Where do these come from?

**Comment by mikalauskas** [comment]
After visiting this http://hdstreams.club/page/ch10.php i got bunch of redirects and popups. So i reloaded page many times and triggered redirects many times too (by clicking on page).

**Comment by StevenBlack** [comment]
Thanks @mikalauskas, these are added.
