### ISSUE TITLE
Tracking companies from german electronic shop

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1359]
In the german `https://www.saturn.de/` electronic shop i found the following data tracking/ selling companies under their "[privacy policies](https://www.saturn.de/de/shop/datenschutzerklaerung_cookies.html)":

```
www.bazaarvoice.com
zoovu.com
www.easy-m.de
www.communicationads.net
communicationads.net
www.home.neustar
prudsys.de
www.salesforce.com
www.thetradedesk.com
pvn.saturn.de
```

"www.bazaarvoice.com" and "www.salesforce.com" are already in your list but not the whole domain.
What did you think?

**Comment by StevenBlack** [comment]
Hi @beerisgood.  We certainly won't block the `salesforce.com` root domain.

Several of the others aren't domains they serve ads from, is that right?

We need to distinguish between the home pages of ad companies, and the domains they use to ferry ads to users.  We aren't in the business of taking ad companies off the web.  We aren't going to block `google.com` for example.

**Comment by StevenBlack** [comment]
Closing.

**Comment by beerisgood** [comment]
> Several of the others aren't domains they serve ads from, is that right?
>
Right.

> We need to distinguish between the home pages of ad companies, and the domains they use to ferry ads to users.
>
Okay. Fair enough
