### ISSUE TITLE
Redundancies 

### ISSUE THREAD

**Issue by Quorum75** [StevenBlack/hosts#1363]
Hi. 

I copy the host rules into [Redundant checker](https://abpvn.com/ruleChecker/redundantRuleChecker.html) and I ended up with 43678 redundancies and 341 warnings. 

Is it normal?

**Comment by StevenBlack** [comment]
Hi @Quorum75 the raw amalgamated lists we publish are supposed to be de-duplicated.  What redundancies are you seeing?

**Comment by StevenBlack** [comment]
This is a bum steer.  Thank you @Quorum75.  Closing.

**Comment by Quorum75** [comment]
Do you mean I should not use it? What's bad about this program?

**Comment by StevenBlack** [comment]
For starters, @Quorum75 I have no idea what you are referring to.  I have no idea what you mean by 'redundancies'.

We have zero duplicates.  

I suspect you posted your question in the wrong repo.  This has nothing to do with us.

**Comment by llacb47** [comment]
@Quorum75 That tool is for adblock lists. This is not an adblock list. 

`This script checks if there are any redundant rules in your Adblock Plus filter list. A rule is redundant if the content it blocks, hides or excludes is also blocked, hidden or excluded by another rule.`

There is no such thing as a "redundant rule" in a host file. Blocking google.com will not automatically block maps.google.com for example.

**Comment by krystian3w** [comment]
> We have zero duplicates.

KADHosts sometimes duplicate blocked domain when:

-  CERT Polska
- Private Company "Legalnie w sieci"

banned same fake/fraud "shop" in same time (intervals):
- 11:00 - 14:59 (4h - "Europe" day)
- 15:00 - 18:59 (4h - "Europe" day)
- 19:00 - 10:59 (16h - "Europe" night)

 KADHosts no have GNU/Linux `.sh` script to detect these situation and now is allways manual fixed after minimum 4 hours - few days by human.
