### ISSUE TITLE
Windows Defender reporting telemetry-blocking hosts file is a risk

### ISSUE THREAD

**Issue by jsob63** [StevenBlack/hosts#1365]
Hi,

I have been running your hosts file for quite a while, and haven't updated it in a while either, but the other day Windows Defender started complaining that my hosts file was malicious and had to be quarantined, etc.  This happened both at work and at home where I run your (old version) hosts file.

Has anyone else come up with this recently?  

I will try downloading the latest version and see if Windows Defender hits on it, but I thought I should also ask/report this here.

Thanks!

-John

**Comment by StevenBlack** [comment]
Hi @jsob63 yes this is explained here:  https://www.bleepingcomputer.com/news/microsoft/windows-10-hosts-file-blocking-telemetry-is-now-flagged-as-a-risk/

As I'm fond of repeating, Microsoft Windows is a shitshow.

We're still deciding what to do with this...

**Comment by XhmikosR** [comment]
IMHO any user who is tech-savvy enough to fiddle with HOSTS-file blocking knows the implications of this. Thus, they should ignore the warning. Otherwise, they should choose another solution like setting up a Pi-hole.

**Comment by StevenBlack** [comment]
Great take @XhmikosR.  I agree.

Closing.

**Comment by jsob63** [comment]
I disagree with this, because from my point of view having a hosts file that blocks many malicious sites like adv sites, etc. is one of the easiest ways to protect your online experience.;  It does not require much tech-savvy, and returns a great investment in security and performance on the web.

Setting up a Proxy Sever/Pi-Hole is exponentially more difficult.

I would rather see you cave in and allow Microsoft's Telemetry sites, with associated "Fuck you Microsoft" than see a new generation of users not use your great tool because Microsoft reports it as malicious.

-John

**Comment by jsob63** [comment]
An update on this.  I installed your latest hosts file back around the date of my last post, and so far Windows Defender has NOT hit on it.  So Microsoft may have fixed this and your hosts file is NOT being reported as malware today.

I am running Windows 10 2004 and;

# Date: 15 August 2020 20:27:39 (UTC)
# Number of unique domains: 59,086

Just FYI, and thank you for all your hard work on keeping this up!

-John

**Comment by jsob63** [comment]
An update on this.  I installed your latest hosts file back around the date of my last post, and so far Windows Defender has NOT hit on it.  So Microsoft may have fixed this and your hosts file is NOT being reported as malware today.

I am running Windows 10 2004 and;

# Date: 15 August 2020 20:27:39 (UTC)
# Number of unique domains: 59,086

Just FYI, and thank you for all your hard work on keeping this up!

-John
