### ISSUE TITLE
Obsolete/non-maintained lists

### ISSUE THREAD

**Issue by crssi** [StevenBlack/hosts#1367]
Hi

Are those list still maintained?:
MVPS hosts file
Dan Pollock – someonewhocares
~~yoyo.org~~

Thank you and cheers

**Comment by Laicure** [comment]
Oh those just updated, days ago:
![image](https://user-images.githubusercontent.com/8619566/89396600-565cf480-d741-11ea-9ac5-970a99bd42db.png)

I think, you should point to this instead:
![image](https://user-images.githubusercontent.com/8619566/89396728-7be9fe00-d741-11ea-9ca6-4837b6747db8.png)

**Comment by crssi** [comment]
Removing `yoyo.org` from the OP list since Peter Lowe responded almost instantly.
Thank you Peter.

**Comment by crssi** [comment]
@Laicure about `malwaredomainlist.com`.. even uBO has removed:
https://github.com/gorhill/uBlock/releases/tag/1.28.2
uBlockOrigin/uBlock-issues#1116
uBlockOrigin/uBlock-issues#984

**Comment by crssi** [comment]
@Laicure 
For the first two on the list, I am still unsure.
The update status might be also invoked by some collection scripts.

**Comment by Laicure** [comment]
For MVP, I am still receiving their monthly HOSTS update thing via email so I think they are still up.
And checking the MVP hosts commit: https://github.com/StevenBlack/hosts/commit/a4ff58d4cbe0e753a318dbf8ed7291504325f43d, they are still up and running.

**Comment by crssi** [comment]
The problem is they do not respond to requests. 😉 
The monthly HOSTS update might be some automated process.

**Comment by Laicure** [comment]
Ohh, I see. I got your point. ;)

**Comment by rjhancock** [comment]
And Someonewhocares is primarily updated when people send in ones they find or Dan finds them. It is maintained.

**Comment by StevenBlack** [comment]
Thanks @crssi.  The sources you list are all being maintained, in my view.

It's the middle of summer right now, in the middle of a pandemic.  I'm not holding anyone to task for being less responsive than we might otherwise expect.

Closing.

**Comment by crssi** [comment]
Thank you and cheers
