### ISSUE TITLE
Removing hosts from list

### ISSUE THREAD

**Issue by JPerkster** [StevenBlack/hosts#1369]
Howdy!

I work for Sugarsync.com, and I've noticed our www. domain is added to your black list. Is there a way we could get this removed?

Thanks!

**Comment by StevenBlack** [comment]
Hi Jacob @JPerkster.

The `sugarsync.com` domain comes to us from the [add.Risk](https://github.com/FadeMind/hosts.extras) list.

Tomasz @FadeMind can you please have a look, and comment?  Thanks!

**Comment by FadeMind** [comment]
@StevenBlack done 😁

**Comment by FadeMind** [comment]
Notice: `add.*`  hosts lists are taken from http://hostsfile.org/hosts.html directly (mirrored and cleaned up from false positives on my repo side). @JPerkster you should send request directly to maintainers of `hostsfile.org` lists.

**Comment by JPerkster** [comment]
Thanks to you both. I'll reach out to hostsfile today. 

I appreciate the help and quick responses!
