### ISSUE TITLE
SSH Proxy

### ISSUE THREAD

**Issue by bynw** [StevenBlack/hosts#137]
I was setting up an SSH proxy for my android device. I was running the base hosts file and I constantly received the message from my browser that the proxy server was refusing the connection. So when I changed back from the unified hosts file to the base hosts file that comes with android it the SSH proxy worked. I'm not seeing anything in the hosts file that would be causing that however so I'm not sure why and just looking for further assistance in this issue.

**Comment by StevenBlack** [comment]
Interesting @bynw 

Is this a public proxy we could check out, or something private?

**Comment by bynw** [comment]
It's  my own VPS hosted on digitalocean.

**Comment by bynw** [comment]
I can create a user for you on the host if you need one for testing. I'm
only using it right now as an ssh proxy.

**Comment by StevenBlack** [comment]
Maybe this is interesting:  [Why does SSH not consult /etc/hosts?](http://unix.stackexchange.com/questions/55014/why-does-ssh-not-consult-etc-hosts)

So at least we know that SSH is special in some respects here...

**Comment by bynw** [comment]
My Android tablet is running Lollipop 5.1. Rooted with Kingroot. So I can
view/edit/change the hosts file.

The default hosts file just has 127.0.0.1  localhost. And creating a socks
proxy works just fine when that is the hosts file that is active.

I have a Windows laptop I'm going to test this hosts file on at home this
evening. I have Firefox on that machine setup to use the socks proxy as
well. I will see if it works or doesn't work with the changed hosts file.

**Comment by bynw** [comment]
Just tested in Windows. It works fine there. So it seems to be an android/ssh/proxy issue.

**Comment by bynw** [comment]
And today it's magically working with the hosts file on the android device.
No fresh download or anything. Thanks for looking at it.

On Wed, May 25, 2016 at 10:23 AM, chris rheinherren <c.rheinherren@gmail.com

**Comment by StevenBlack** [comment]
Great!  Closing.
