### ISSUE TITLE
guce.advertising.com

### ISSUE THREAD

**Issue by DavidCWGA** [StevenBlack/hosts#1370]
Links into, and out of, techcrunch now bounce through guce.advertising.com, in order to set a tracking cookie.

advertising.com is listed here, but guce.advertising.com is not. Both TechCrunch and advertising.com are Verizon Media properties. guce.advertising.com is an alias for real.rotation.guce.aws.oath.cloud.

I don't know if listing it is actually a good idea, because it may break every Verizon-owned website, but I thought I'd bring it up here for discussion.

HN discussion: https://news.ycombinator.com/item?id=24072628

**Comment by llacb47** [comment]
Why bring it up if listing it is not a good idea, and will "break every Verizon-owned website"?

Also this is not new, has been happening for at least a year I think

https://github.com/lightswitch05/hosts/issues/188

**Comment by dnmTX** [comment]
It breaks Yahoo so NO 👎 . Any adblocker will take care of it as a post process though.

**Comment by StevenBlack** [comment]
Tank you David @DavidCWGA.

Dan @dnmTX why would we not list this?  Help me to understand.  I don't believe these companies should get a free-pass here.

In some sense, people who use Yahoo aren't those we serve, here.  Of maybe these are the people who need us most?

What am I missing?

**Comment by llacb47** [comment]
I think most people using this list would rather be able to access yahoo, techcrunch, engadget, and huffpost...

**Comment by dnmTX** [comment]
Steve @StevenBlack i use Yahoo all the time ¯\_(ツ)_/¯ (if you add it, i'll whitelist it on my end,i guess)
Everything that LE @llacb47 posted above ☝️ it's unfortunately the reality right now.
The comment section(in `Yahoo.com`) is suspended as of now but when it was working i've seen over 50,000 responses over some articles(who knows how many are using your list)
And in conclusion. Here i'm just stating the facts,nothing else. 
You're not missing anything,domains like `guce.advertising.com`(among others,cough...Verizon...cough) really deserve special place here but after you block them there is literally no way around accessing those websites.

**Comment by StevenBlack** [comment]
David @DavidCWGA, Dan @dnmTX I'm leaning towards blocking this.

Because this is the thin edge of the wedge.  Having slept on this for a few nights, the company's size, or reach, really shouldn't enter.  All the more reason to block it, in some sense.

At core, how much should utilitarian thinking influence moral thought? Arguably, zero.  But in more practical terms, we have an opportunity to stand up to this BS tactic and the question is, do we have the mettle for this.

**Comment by dnmTX** [comment]
Steve @StevenBlack  sure. You've read both sides of the argument and took decision. Fair is fair.
Just please,let's keep that issue open for a while longer and see how it goes. 👍

**Comment by DavidCWGA** [comment]
Discussion of this server comes up a lot on HN, I guess because HN links to TechCrunch a lot, and if you block it, TechCrunch breaks:

https://www.google.com/searchq=guce.advertising.com+site:news.ycombinator.com

But it's pretty blatant what it's doing. The URL it redirects you to is even called "collectIdentifiers". They're not subtle about it.

For what it's worth, it's not literally every Verizon site, just the ones owned by "Verizon Media", which used to be called "Oath". That is the following list of sites:

- AOL
- Autoblog
- BUILD
- Built By Girls
- Engadget
- Flurry
- HuffPost
- MAKERS
- Rivals
- RYOT
- TechCrunch
- Yahoo!

So the idea is that Verizon can track you across all those different sites. The redirect prevents you from avoiding any kind of cross-site tracking.
