### ISSUE TITLE
[WHITELIST] hb.wpmucdn.com

### ISSUE THREAD

**Issue by CyanoTex** [StevenBlack/hosts#1372]
``hb.wpmucdn.com`` apparently breaks acrcloud.com... if the image isn't obvious enough.
AdAway also blocks it.

![Screenshot_20200807-121038818 (1).jpg](https://user-images.githubusercontent.com/62466866/89640539-15372280-d8b0-11ea-8144-0a8dca78f9d7.jpg)

![Screenshot_20200807-121529007.jpg](https://user-images.githubusercontent.com/62466866/89640548-19634000-d8b0-11ea-92ae-4ece33bbbce1.jpg)

**Comment by StevenBlack** [comment]
Hi @CyanoTex we don't block any of these domains.

Closing.
