### ISSUE TITLE
Remove cdn.jsdelivr.net

### ISSUE THREAD

**Issue by perry** [StevenBlack/hosts#1377]
This is a very popular CDN for various JS and CSS libraries, and breaks potentially thousands of websites.

Is there a more specific reason that it is blocked?

<img width="1327" alt="Screenshot 2020-08-11 at 15 48 46" src="https://user-images.githubusercontent.com/952316/89877349-2eaad800-dbea-11ea-82c8-c7141ef1d985.png">

**Comment by StevenBlack** [comment]
Thanks Perry @perry the domain `cdn.jsdelivr.net` comes to us via mvps.org.

Can you please raise this with them directly?  Send an email to winhelp2002@gmail.com

Closing.
