### ISSUE TITLE
Make restarting network management tools toggleable

### ISSUE THREAD

**Issue by cryzed** [StevenBlack/hosts#138]
When you ask the user if they want to replace their existing hosts file and escalate privileges with `sudo`, that's imho all you should really do. The additional logic for flushing the DNS cache (restarting the entire network management) in `moveHostsFileIntoPlace` should at least be toggleable with a command-line switch and the user should be explicitly prompted after replacing the hosts file when running the script interactively.

The current behaviour makes it impossible for me to run the script in an automatic fashion regularly, because it would mean regular and sudden disconnects.

**Comment by StevenBlack** [comment]
@cryzed Yes, I think this is a good suggestion.  Thanks.

**Comment by StevenBlack** [comment]
Closing.  Thanks Chris @cryzed.
