### ISSUE TITLE
[Adding] servsave[dot]com

### ISSUE THREAD

**Issue by Ghalid** [StevenBlack/hosts#1380]
Malware/redirect domain that should be blocked: `www[dot]servsave[dot]com`

The above link is one letter away from a legitimate site, www.servsafe.com, and serves to trick people who misspell the URL. When navigated to, it redirects you to spam/malware popups.

**Comment by StevenBlack** [comment]
Thanks @Ghalid these are added in commit 539433a6.

Closing.
