### ISSUE TITLE
[Adding] hpanalytics.net - HP's TouchPoint Analytics Client

### ISSUE THREAD

**Issue by imnotender** [StevenBlack/hosts#1381]
Analytics Client silently installed on Windows' Driver Store on certain HP Omen Laptops, silently communicates over to HP without ANY user consent.

Example subdomain I found in a config file at said Driver Store folder:
us-west-2.kinesis.hpanalytics.net

This doesn't appear in any blocklist I've found so far, it'd be nice to have it here.

Sorry if there's a certain format required for these types of issues - I couldn't find one.

**Comment by llacb47** [comment]
Looks like a self-hosted implementation of Amazon Kinesis Data Streams

Related: https://github.com/StevenBlack/hosts/issues/1287#issuecomment-631595913

**Comment by StevenBlack** [comment]
Thanks Rafael @imnotender this is added in commit 30764ced.

Closing.
