### ISSUE TITLE
stats.nba.com is blocked

### ISSUE THREAD

**Issue by tiiiecherle** [StevenBlack/hosts#1382]
Hey,

thanks for this really nice project.

The following entry 
`stats.nba.com.edgekey.net `
blocks a main part of the official nba website 
[https://stats.nba.com](https://stats.nba.com)

Adding the entry to the whitelist solves the problem. I don't know why it is on the blocklist and if it can be whitelisted in general.

Thanks for having a look.

**Comment by StevenBlack** [comment]
Hi @tiiiecherle, thanks for that.

The domain `stats.nba.com.edgekey.net` domain comes to us via AdAway.  @jaws101, can you have a look?

Fair warning though, @tiiiecherle, if that domain trades, tracks, or otherwise betrays users, it won't be unblocked.

**Comment by llacb47** [comment]
@jawz101

**Comment by jawz101** [comment]
removed

**Comment by tiiiecherle** [comment]
It's working, thanks a lot to everyone who was helping so well and fast ;)

**Comment by StevenBlack** [comment]
Thanks @jawz101.

Closing!

**Comment by timkgh** [comment]
This is broken again. Can you please re-fix? Thanks.

**Comment by tiiiecherle** [comment]
Yes, I can confirm that [https://stats.nba.com](https://stats.nba.com) is blocked again. Thanks for fixing in advance.

**Comment by StevenBlack** [comment]
@jawz101 hi, it looks like `stats.nba.com.edgekey.net` is the culprit here.  Can you please have a look?

**Comment by jawz101** [comment]
I removed it again.  Sorry about that

**Comment by StevenBlack** [comment]
Thanks @jawz101 — closing.
