### ISSUE TITLE
Monitor hosts

### ISSUE THREAD

**Issue by mupaneu** [StevenBlack/hosts#1385]
Testing an antivir product, I had to learn my hosts file had been tampered with without notification by that solution. That's why I developed a monitor: https://github.com/mupaneu/PoSh/blob/master/Monitor-hosts.ps1

Any discussion and of course bug reports welcome. It's not intended to be a run-me-out-of-the-box tool though, it's a script for users understanding what it does.

**Comment by StevenBlack** [comment]
Hi @mupaneu 

I would entertain a pull request to include a link to this in our [readme template](https://github.com/StevenBlack/hosts/blob/master/readme_template.md) under [Interesting Applications](https://github.com/StevenBlack/hosts).  Be sure to specify this is watcher is a for Windows OS.

**Comment by mupaneu** [comment]
Thank you. I missed a notification of your comment of 19 Aug, but I got one about the stale state of this issue. I will have to learn pull requests. I will test and edit the script in PowerShell 7 on Debian, so it might be more useful then.
