### ISSUE TITLE
Import error at entry "pgl.example0101" from pgl.yoyo.org

### ISSUE THREAD

**Issue by spodermenpls** [StevenBlack/hosts#1386]
I am using your Hosts 'conglomerate' in conjunction with uMatrix for a while now, since Malwarebytes decided to close-source its "HpHosts" file and forcing me (and others) to look for an alternative. With exception of "Malware Domains", I was able to de-select all of uMatrix's preloaded stock filters (whose servers are unreliable at times) thanks to your unified file, so thanks for your work!

I was wondering for a longer time now why uMatrix is still using one single entry out of Peter Lowe's server list, when your hosts file is simultaneously active. After a while of comparison work today, I've figured out what causes it. In Peter Lowe's original "upstream" file (https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0), there is a entry called `pgl.example0101`, in your hosts file (https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts), it gets displayed as `pgl.example #0101` though, therefore rendering it a separate entry, when uMatrix compares it against the original while looking for duplicates. Did this change happen on purpose, or is it indeed an import error that could need a fix? I am not familiar with this (comparably weird) entry's history at Peter Lowe's list, its database entry on yoyo.org (https://pgl.yoyo.org/adservers/details.php?hostname=pgl.example0101) indicates no "legitimacy issues", though.

**Comment by dnmTX** [comment]
In both cases that domain is rendered invalid. The question is who to be reported to for removal.

**Comment by spodermenpls** [comment]
@pgl Would you be so kind and tell us if `pgl.example0101` still has a reason to exist in your list, or if it's obsolete?

**Comment by pgl** [comment]
@spodermenpls It's a canary domain, deliberately invalid, there for quality assurance purposes. In this particular case I'm going to keep it in the list, sorry.

Most entries on my list are validated once a week, and are removed after 6 failed checks.

**Comment by spodermenpls** [comment]
@pgl OK, thanks for your quick reply - no need to be sorry for not removing it, when it's serving a purpose. I've assumed it was some kind of "test beacon", since the Top Level Domain `example0101` is a bit too extravagant, even by today's ICANN standards. 😅

**Comment by spodermenpls** [comment]
@StevenBlack Since you closed my issue silently, are you going to edit `pgl.example #0101` back into the original `pgl.example0101`? This might save other uMatrix/ PL's list users from running into the same confusion as I had, when I wondered for quite some time which single PL's rule (seemingly) had been left out of your hosts file, and for what reason (e.g. your file is missing a rule?, false positive being left out on purpose, compatibility issue with uMatrix and your file).

**Comment by StevenBlack** [comment]
Thanks for the question @spodermenpls.

I don't think any of this is a problem.  Am I missing something?

**Comment by spodermenpls** [comment]
@StevenBlack If you don't deem it 'edit-worthy', that's OK too, but maintaining consistency between the two files wouldn't hurt either, I reckon.

**Comment by StevenBlack** [comment]
@spodermenpls sorry I was unclear.  I just don't understand how this is, in any way, a problem.  I asked you if I was missing something, and you replied blah blah.  Are we done, here?

**Comment by llacb47** [comment]
@StevenBlack @spodermenpls is saying, and I agree, that `0.0.0.0 pgl.example #0101` is not a valid host entry or hostname. so you should remove it or preserve the original format `0.0.0.0 pgl.example0101`. `example0101` is a valid TLD per `https://tools.ietf.org/id/draft-liman-tld-names-00.html`, but `example #0101` is not.
