### ISSUE TITLE
Blocking sdk.split.io is breaking my feature flags.

### ISSUE THREAD

**Issue by meek2100** [StevenBlack/hosts#1387]
Why is sdk.split.io blocked?  This isn't an ad service this is a service used for enabling/disabling new features through feature flags.

**Comment by StevenBlack** [comment]
Hi @meek2100 thank you for this.  It's more than ads, you know. 🙄 (sigh).

The `sdk.split.io` domain comes to us via AdAway.  @jawz101 can you please have a look?  Thanks.

**Comment by jawz101** [comment]
see https://github.com/StevenBlack/hosts/issues/1345

**Comment by StevenBlack** [comment]
Thanks @jawz101.  You know our issues better than I do 😄 

Closing.

**Comment by meek2100** [comment]
Thanks for the info.  I'll just whitelist this on my system then.
