### ISSUE TITLE
Add block for upee.online and app.upee.online

### ISSUE THREAD

**Issue by maisonmdsgreen** [StevenBlack/hosts#1388]
Hi add  upee.online and app.upee.online have hosted ads

https://app.upee.online/files/show/SQ-1596736253.jpg

Thanks

**Comment by dnmTX** [comment]
This will be a good edition to the AdAway's list as it is more focused on mobile.
**PING** @jawz101

**Comment by maisonmdsgreen** [comment]
@dnmTX I saw this on a computer version website.

**Comment by dnmTX** [comment]
> @dnmTX I saw this on a computer version website.

I was checking it out and it was showing that it was very active on Android platforms but either way it's fine 👍

**Comment by jawz101** [comment]
added to Adaway.  I was working on a pretty massive cleaning of the list before I wanted to add those

**Comment by maisonmdsgreen** [comment]
> added to Adaway. I was working on a pretty massive cleaning of the list before I wanted to add those

Thanks update
