### ISSUE TITLE
add these porn sites to blacklist

### ISSUE THREAD

**Issue by minutesinch** [StevenBlack/hosts#1390]
hi i found these persian porn site, so better add to black list(all of them are porn sites 100 tested)
shahvani.com
qombol.com
sex021.com
kir2kos.net
bia2sh.com
kir2kos.cc
looti.org
looti.net
sexiranian.party
shahvatnak.com
shahvatnakchat.chatovod.com
halohul.com
newsalloy.com
avizoone.com
iranxvid.com
irannaz.com
akssexy.com
bigsex.tv
smutcinema.com
kartalboy1.wordpress.com
solihinzubir.com
dastanhisexy.cc
reachporn.com
shahvani.me
sex021.net
feengly.wordpress.com
dastan-sexy.net
pornofilmer.icu
hugesex.tv
carnedelmercado.com
xnxxfap.com
rs-intrad.com
narenjitube.blogspot.com
xyzcomics.com
sexiseks.com
klipis.net
iranx.net
patogh.me
jendekhane.com
bokeptantetoge.icu
clearsexy.xyz
irxclip.com
imagetwist.com

**Comment by Sinfonietta** [comment]
@StevenBlack I just added these.  A few were duplicates of what I had before.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta.

Closing.
