### ISSUE TITLE
installeranalytics.com

### ISSUE THREAD

**Issue by russeg** [StevenBlack/hosts#1394]
found this when i installed TCC from jpsoftware.

**Comment by StevenBlack** [comment]
@russeg this looks like a company home page.  Are they tracking from their root domain?  That would be unusual.

Our mission is to stop ads, tracking, and malware in all its forms. We aren't in the business of removing companies from the internet, or hindering access to them. 

Closing.

**Comment by dnmTX** [comment]
`0.0.0.0 collect.installeranalytics.com`
not a bad idea to be added here in my opinion 👍

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX this is added in commit b8c4dfdc.
