### ISSUE TITLE
add new block source for mobile ads

### ISSUE THREAD

**Issue by minutesinch** [StevenBlack/hosts#1395]
https://filters.adtidy.org/extension/chromium/filters/11.txt

here all of mobile ad networks

**Comment by StevenBlack** [comment]
Thanks Mini @minutesinch thanks for this input.

This suggestion is not actionable for us.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).
