### ISSUE TITLE
some more porn sites

### ISSUE THREAD

**Issue by minutesinch** [StevenBlack/hosts#1399]
hdstream.xxx
hdjerk.com
hdselection.com
besthdxxx.com
tophd.xxx
sexable.tv
xxxshame.com
megasexpov.com
facialcumshot.info

**Comment by StevenBlack** [comment]
Thanks Mini @minutesinch.

Ping @sinfonietta

**Comment by Sinfonietta** [comment]
I have added these @StevenBlack.  I had the domain tophd.xxx already.

**Comment by Zorono** [comment]
and 
fakecop.com
fakehospital.com
fakebox.com
faketaxi.com
