### ISSUE TITLE
Add HOSTS file for AcrylicDNS

### ISSUE THREAD

**Issue by espress0** [StevenBlack/hosts#14]
AcrylicDNS can use * and regexp.

127.0.0.1 ad.ae.doubleclick.net
127.0.0.1 ad.ar.doubleclick.net
127.0.0.1 ad.at.doubleclick.net
127.0.0.1 ad.au.doubleclick.net
127.0.0.1 ad.be.doubleclick.net

will become

127.0.0.1 ad.*.doubleclick.net

OR

127.0.0.1 ad.ae.doubleclick.net ad.ar.doubleclick.net ad.at.doubleclick.net ad.au.doubleclick.net ad.be.doubleclick.net

Simple, eh?

**Comment by espress0** [comment]
http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome

**Comment by StevenBlack** [comment]
That's interesting!

Too bad it's Windows-only.

Nice concept, though.
