### ISSUE TITLE
redirect phishing bad sites

### ISSUE THREAD

**Issue by minutesinch** [StevenBlack/hosts#1400]
2cnjuh34jbpoint.com
exobafrgdf.com
sefsdvc.com
syndication.traffichaus.com
traffichaus.com
realsrv.com
syndication.realsrv.com

when i browse in sites i found som sites redirect to this sites, they are bad sites please block them!

**Comment by StevenBlack** [comment]
@minutesinch we already carry the following.

```
realsrv.com 
syndication.traffichaus.com 
traffichaus.com
```

Closing
