### ISSUE TITLE
new ad domains

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#1401]
Please add the following:

pressingfastenedphantom(.)com
turmoilexcessivetranslating(.)com
fairnessenhancedisposal(.)com

They are used for ads on 4chan/4channel as of ~3 days ago.

**Comment by dnmTX** [comment]
`0.0.0.0 pressingfastenedphantom.com` is **CONFIRMED**
not sure for the rest but it could be geo related....

**Comment by hyder365** [comment]
The last domain uses the exact same string (ntv.json ...) when I inspect the page. Hope this can go in soon.
