### ISSUE TITLE
Remove Microsoft ads or msn ads

### ISSUE THREAD

**Issue by ModiFlasher** [StevenBlack/hosts#1402]
Can you remove Microsoft and msn ads because it cause i can't login to Minecraft Windows 10 edition and Android

**Comment by StevenBlack** [comment]
Hi @ModiFlasher thank you for this request.

This is a technical matter.  We need specific details about your environment, and what it expects, to do anything here.

Seeing none of that, I'm closing this now, because your request isn't actionable.
