### ISSUE TITLE
Dynamic Theme Using Window Spotligth not work

### ISSUE THREAD

**Issue by maisonmdsgreen** [StevenBlack/hosts#1405]
Dyanamic Theme use mobile.pipe.aria.microsoft.com

Thanks

**Comment by StevenBlack** [comment]
Thanks Maison @maisonmdsgreen.

The `mobile.pipe.aria.microsoft.com` domains are listed in my ad-hoc list, and by AdAway.

@jawz101 what do we know about `mobile.pipe.aria.microsoft.com`?
