### ISSUE TITLE
Remove Tracker - Counter-Strike 1.6

### ISSUE THREAD

**Issue by ObsessedHacker** [StevenBlack/hosts#1407]
While playing Counter-Strike 1.6 I found a tracker.
https://imgur.com/bbzR6Pv

I tried adding these lines but none of them made a difference:
0.0.0.0 85.90.246.13
0.0.0.0 li1429-13.members.linode.com
0.0.0.0 www.li1429-13.members.linode.com

Can you help me block it?

**Comment by StevenBlack** [comment]
@ObsessedHacker did you clear your DNS cache? This procedure varies depending on the OS you are using.

Is this an in-browser game?  The browser has a cache, too.

**Comment by ObsessedHacker** [comment]
I thought I managed somehow to block it but I didn't.
It's not an in-browser game, it's a game.
I did clear up my DNS but I understand that the tracker in-game is forcing access to this URL by forcing it to the DNS cache.
So what can I do in a situation like that that the tracker itself is forcing it's way to the DNS cache?

**Comment by ObsessedHacker** [comment]
> @ObsessedHacker did you clear your DNS cache? This procedure varies depending on the OS you are using.
> 
> Is this an in-browser game? The browser has a cache, too.

I have windows 10.
I thought I managed somehow to block it but I didn't.
It's not an in-browser game, it's a game.
I did clear up my DNS but I understand that the tracker in-game is forcing access to this URL by forcing it to the DNS cache.
So what can I do in a situation like that that the tracker itself is forcing it's way to the DNS cache?

**Comment by StevenBlack** [comment]
I don't understand the question, @ObsessedHacker.  

There is no notion, no concept, no possible abstraction of "*forcing something to the DNS cache*".  

DNS is an external call, which may or may not be preempted by a cached result depending on the nature of the call, a prior result of the same (or closely similar) call, or the age of the cached result.  

This all happens is an entirely separate and distinct layer from the game's code.  The game may be programmed to panic, abort, or branch based on the success of the call, but you've given no actionable description of what's going on here.

Look, we're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

I don't think there is much we can do for you, based on what you've told us, which isn't actionable.

Can you please re-think and clarify what you're asking, and come back when you can give a concise and clear suggestion of what you need?

Closing.

**Comment by ObsessedHacker** [comment]
> I don't understand the question, @ObsessedHacker.
> 
> There is no notion, no concept, no possible abstraction of "_forcing something to the DNS cache_".
> 
> DNS is an external call, which may or may not be preempted by a cached result depending on the nature of the call, a prior result of the same (or closely similar) call, or the age of the cached result.
> 
> This all happens in an entirely separate and distinct layer from the game's code. The game may be programmed to panic, abort, or branch based on the response of the call, but you've given no actionable description of what's going on here.
> 
> Look, we're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.
> 
> I don't think there is much we can do for you, based on what you've told us, which isn't actionable.
> 
> Can you please re-think and clarify what you're asking, and come back when you can give a concise and clear suggestion of what you need?
> 
> Closing.

Okay I finally figured its out, It took me some research but this tracker is using multiple URLs.
So now I'm asking from you to add these lines to the hosts file, please:
0.0.0.0 85.90.246.13
0.0.0.0 richard.lv
0.0.0.0 riscript.org
0.0.0.0 linode.com
0.0.0.0 ns1.linode.com
0.0.0.0 ns2.linode.com
0.0.0.0 ns3.linode.com
0.0.0.0 ns4.linode.com
0.0.0.0 ns5.linode.com
0.0.0.0 www.linode.com
0.0.0.0 li1429-13.members.linode.com
0.0.0.0 www.li1429-13.members.linode.com

**Comment by StevenBlack** [comment]
Thanks for the clarification @ObsessedHacker.

There is zero chance we will block `linode.com`, or what appear to be its name servers.

**Comment by ObsessedHacker** [comment]
> Thanks for the clarification @ObsessedHacker.
> 
> There is zero chance we will block `linode.com`, or what appear to be its name servers.

So what can you indeed block?
0.0.0.0 85.90.246.13
0.0.0.0 richard.lv
0.0.0.0 riscript.org
0.0.0.0 li1429-13.members.linode.com
0.0.0.0 www.li1429-13.members.linode.com

This list is ok?

**Comment by dnmTX** [comment]
Hey @ObsessedHacker you using some [cheating software](https://github.com/RIscRIpt/flatcheat) to play that game and then complaining about trackers and whatnot here is the worst way to approach. Also you seem to be very unfamiliar on how hosts blocking works( posting IP's that can not be blocked in hosts files among others). Would advise you to just stop wasting everyone's time with your childish needs.

@RIscRIpt you mind shed some light on your creations just for the record here before more kids start blocking your domains for no reason(i'd assume) which might result of them misreading this issue altogether.

**Comment by RIscRIpt** [comment]
One of my [software](https://www.riscript.com/downloads/rHack) (which is very outdated, and I don't sell anymore) sends requests to my website to check for a license. And most probably he is using it without my approval (license).

Some (lots of) years ago, when it was cracked, these checks were not completely removed, so now I can abuse this to [track](https://www.riscript.com/rhack295check) and reveal users who didn't pay for my software.

I don't care if kids will locally block my domains.

Tho, I would not like my domains (and/or IPs) end up in your list :/

**Comment by StevenBlack** [comment]
No worries Richard @RIscRIpt 😄
