### ISSUE TITLE
bet365.com Incorrectly Marked as adware/malware

### ISSUE THREAD

**Issue by makit** [StevenBlack/hosts#1408]
Hi,

www.bet365.com is on the master adware list (https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts), when it should only really exist under gambling (https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts etc).

The site itself is a reputable betting site and isn't hosting ads from the root www.bet365.com domain - affiliate links and adverts are served via different domains.

Thanks

**Comment by StevenBlack** [comment]
Hi @makit — the `www.bet365.com` domain comes to the general list via someonewhocares.org.  So that's upstream from us.

You can report this by sending an email to hosts@someonewhocares.org and making your case.  Can you do that?

**Comment by makit** [comment]
Sure thing, thanks @StevenBlack
