### ISSUE TITLE
In readme file, Windows instructions to flush DNS cache seem poor 

### ISSUE THREAD

**Issue by catsmoke** [StevenBlack/hosts#1409]
[_note_: I'm new to contributing at _Github_. If I have posted here in error, then I apologize.]

Two points on [the _readme.md_ file's guidance to Windows users for flushing the DNS cache](https://github.com/StevenBlack/hosts/blob/master/readme.md#windows):

1. On my computer [Win7Pro64] executing `ipconfig /flushdns` requires having the Win service "DNS Client" running. This seems to contradict the current _readme.md_ file:

> Open a command prompt...and run this command:
> `ipconfig /flushdns`
> 
> Before flushing the DNS cache...run this command [_sic_ "these commands"]:
> `sc config "Dnscache" start=disabled`
> `sc stop "Dnscache"`

So the _readme.md_ tells the user to stop and to disable the DNS Client service "Before flushing the DNS cache"—yet for me flushing the DNS cache fails with the DNS Client service stopped and disabled. 

2. Instructions for a multiple-step sequence ideally list the steps in the order they are to be done but in the section of the _readme.md_ discussed above it seems the two steps (1. stopping-then-disabling the DNS Client service; 2. flushing the DNS cache) are listed in reverse order. The second listed step tells the user to do it "Before" the first step. The steps should be arranged in sequence.

**Comment by StevenBlack** [comment]
Hi Jesse @catsmoke.

Not being a Windows user, [I googled that](https://www.google.com/search?q=windows+how+to+flush+dns+cache&ie=utf-8&oe=utf-8&aq=t) and basically all top hits recommend `ipconfig /flushdns`.

Maybe you have a system-local issue, on this particular box?

But your point is well taken.  All our docs could be better.

**Comment by StevenBlack** [comment]
Jesse @catsmoke I've clarified the Windows instructions in commit 6ebfc1ed.

Thank you for your input.

Closing.
