### ISSUE TITLE
Bad Site Notification URL

### ISSUE THREAD

**Issue by minutesinch** [StevenBlack/hosts#1410]
notification.tubecup.net
tubecup.net

**Comment by minutesinch** [comment]
its also have malicious behavior scanned by virus total

**Comment by dnmTX** [comment]
Looks good to me. The domain is listed in a few ad-blocking lists as well: [sample](https://raw.githubusercontent.com/easylist/easylist/master/fanboy-addon/fanboy_notifications_thirdparty.txt)
Found some more in case it's approved(first two are the once OP mentioned. Easy copy/paste 😉 ):
`0.0.0.0 notification.tubecup.net`
`0.0.0.0 tubecup.net`
`0.0.0.0 events.tubecup.net`
`0.0.0.0 stats.tubecup.net`
`0.0.0.0 wps.tubecup.net`
`0.0.0.0 www.tubecup.net`
