### ISSUE TITLE
Phising Email and Site

### ISSUE THREAD

**Issue by minutesinch** [StevenBlack/hosts#1414]
yesterday i received email by Netflix without even registering in Netflix, its Phishing with Great Design received from 

mipangzuzumogu.bucincibay-anjaydlehayop3669416@lauenakmdszd.com

and its linked to

be careful dont click on them

http://kntlasaww.klauetuwnua.com/gafEH4CV 
kntlasaww.klauetuwnua.com

nevatet.lsopeisfw.com

please block all of them
also its newly registers site that have malwares it smart even and linked you to smart phishing sites randomly.

**Comment by StevenBlack** [comment]
Thank you Mini @minutesinch.

These are added in commit 468ba554

Closing
