### ISSUE TITLE
Malwarebytes domain blocked

### ISSUE THREAD

**Issue by thomasareed** [StevenBlack/hosts#1417]
There is a Malwarebytes-owned domain (home.mwbsys.com) included in the list. Although that particular subdomain doesn't exist anymore, the entire mwbsys.com domain is legit and owned by Malwarebytes, so it shouldn't be blocked.

**Comment by StevenBlack** [comment]
Hi Thomas @thomasareed, we don't list any `mwbsys.com` domains so this is out of our scope.

Closing.

**Comment by thomasareed** [comment]
It's definitely in there. If this is aggregated from somewhere else, can you at least say where?

**Comment by llacb47** [comment]
@thomasareed 

`0.0.0.0 home.mwbsys.org`

`mwbsys.org`

`.org`

**Comment by dnmTX** [comment]
@thomasareed  `home.mwbsys.org` and `mwbsys.org` both have [High VirusTotal detection](https://www.virustotal.com/gui/url/fa68bf9c818bc4c411a173aa143eabdbfdcd7d3362d6560efa43818af2e59423/detection) and also read [THIS](https://blogs.jpcert.or.jp/en/2020/03/elf-tscookie.html) which explains why is it blocked and why should remain here.

**Comment by thomasareed** [comment]
Okay, sorry, it's .org, not .com. Either way, both mwbsys.com and mwbsys.org domains are owned by Malwarebytes, and should not be blocked, regardless of what VirusTotal says. As I work for Malwarebytes, I know this as a fact. If you are unsure of the veracity of my claims to be an employee, please e-mail me at treed@malwarebytes.com and I can confirm.

**Comment by thomasareed** [comment]
Never mind, it seems mwbsys.org isn't in our control anymore... not sure when that happened!
