### ISSUE TITLE
Add MyEtherWallet and Metamask malicious crypto URLs ?

### ISSUE THREAD

**Issue by kolya182** [StevenBlack/hosts#1418]
MyEtherWallet is most Metamask most reputable and trusted web wallets in cryptocurrency (crypto) space. @StevenBlack would you considers adding them ?. Metamask already has curated host file https://github.com/MetaMask/eth-phishing-detect/blob/master/src/hosts.txt and for MEW (MyEtherWallet) i could write a script and to convert a https://github.com/MyEtherWallet/ethereum-lists/blob/master/src/urls/urls-darklist.json into `host` file.

**Comment by StevenBlack** [comment]
Thank you @kolya182 this is cool.  I've been wanting a reliable list of sketch coin domains.

We presently have zero overlap with the 1,059 domains in the first list. 

```
$ ./ghosts -c https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/master/src/hosts.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 56,999
Bytes: 1.7 MB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/master/src/hosts.txt
Domains: 1,059
Bytes: 28 kB
----------------------------------------
Intersection: 0 domains
```

**Comment by StevenBlack** [comment]
After transforming the second list with [jq](https://github.com/stedolan/jq): zero intersection over 2,221 domains.  (Used `jq -r .[].id source > dest`)



```
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 56,999
Bytes: 1.7 MB
----------------------------------------
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 2,221
Bytes: 47 kB
----------------------------------------
Intersection: 0 domains
```

**Comment by kolya182** [comment]
So would be approach here ?. Let me know if i can help. Can't wait to install in on pi-hole.

**Comment by StevenBlack** [comment]
> Let me know if i can help

Find a Bitcoin list that's just as good as this one is for Eth 😄

**Comment by StevenBlack** [comment]
@kolya182 I have a concern.  [MetaMask receives an avalanche of issues submitted](https://github.com/MetaMask/eth-phishing-detect/issues?q=is%3Aopen+is%3Aissue), is there nobody dealing with that?    I see a wall of issues with nobody acknowledging, or replying.

Active curation is a big deal in my mind.  Your thoughts?

**Comment by kolya182** [comment]
> > Let me know if i can help
> 
> Find a Bitcoin list that's just as good as this one is for Eth 😄

1. https://raw.githubusercontent.com/CryptoScamDB/blacklist/master/data/urls.yaml
2. https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/nocoin.txt
3. Bitcoin, Monero, Nimiq etc https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/hosts.txt

Cryptocurrency mining malware urls:
1. https://blog.avast.com/greedy-cybercriminals-host-malware-on-github
2. https://github.com/anudeepND/blacklist/blob/master/CoinMiner.txt
3. https://raw.githubusercontent.com/greatis/Anti-WebMiner/master/blacklist.txt


Other hosts founded along the way:
1. https://gist.github.com/opus-x/3e673a9d5db2a214df05929a4eee6a57
2. https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist
3. Big db https://github.com/jerryn70/GoodbyeAds

**Comment by kolya182** [comment]
> @kolya182 I have a concern. [MetaMask receives an avalanche of issues submitted](https://github.com/MetaMask/eth-phishing-detect/issues?q=is%3Aopen+is%3Aissue), is there nobody dealing with that? I see a wall of issues with nobody acknowledging, or replying.
> 
> Active curation is a big deal in my mind. Your thoughts?

Hi @StevenBlack , sorry for long delay 

I'm convinced @danfinlay and @409H doing a [great job](https://github.com/MetaMask/eth-phishing-detect/commits/master) maintaining the repository. Based on my experience in crypto it's just so many scammers out there imposing real projects, and not commenting on every PR make sense to me, but merging those that a really proven to be a scam. In general i think Metamask's list can be imported into `hosts` as is, because already has sufficient list of most scam resources and adds 5-10 new websites daily.

**Comment by kolya182** [comment]
@StevenBlack Hi, would you consider moving forward with this ?

**Comment by StevenBlack** [comment]
Hi @kolya182 thanks for being on top of this.

I just asked permission in https://github.com/MetaMask/eth-phishing-detect/issues/4769.

So yeah, let's do this.  I've created the `data/MetaMask/update.json` file in branch [`metamask.inclusion`](https://github.com/StevenBlack/hosts/tree/metamask.inclusion) and that's basically good-to-go, pending approbation..

**Comment by kolya182** [comment]
> Hi @kolya182 thanks for being on top of this.
> 
> I just asked permission in [MetaMask/eth-phishing-detect#4769](https://github.com/MetaMask/eth-phishing-detect/issues/4769).
> 
> So yeah, let's do this. I've created the `data/MetaMask/update.json` file in branch [`metamask.inclusion`](https://github.com/StevenBlack/hosts/tree/metamask.inclusion) and that's basically good-to-go, pending approbation..

For the sake of safer crypto space. Thank you.

**Comment by StevenBlack** [comment]
Thanks @kolya182 this is now included in this list.  Thanks for all your help! 

Since this is a material change to the list, this is live and online as a minor release increment, to [release 3.5.0](https://github.com/StevenBlack/hosts/releases/tag/3.5.0).

Closing!

**Comment by kolya182** [comment]
> Thanks @kolya182 this is now included in this list. Thanks for all your help!
> 
> Since this is a material change to the list, this is live and online as a minor release increment, to [release 3.5.0](https://github.com/StevenBlack/hosts/releases/tag/3.5.0).
> 
> Closing!

Hooray
`pinhole` received update
<img width="1071" alt="Screen Shot 2021-03-10 at 8 12 31 PM" src="https://user-images.githubusercontent.com/3277207/110734640-17ae8180-81dd-11eb-86c7-7ded7057143a.png">

**Comment by TPS** [comment]
@StevenBlack MetaMask eth-phishing-detect has changed its internal list format.  According to the [lists readme](https://github.com/MetaMask/eth-phishing-detect/blob/main/doc/lists-ref.md) & [commits](https://github.com/MetaMask/eth-phishing-detect/commits/main), the only list file anymore is https://github.com/MetaMask/eth-phishing-detect/blob/main/src/config.json , which internally combines the Blocklist, Fuzzylist, & Allowlist internally, & _that_ would be needed to be parsed out for our purposes here.  FWICT, the https://github.com/MetaMask/eth-phishing-detect/blob/main/src/hosts.txt that's been parsed here has not been updated in >1 year.
