### ISSUE TITLE
sellAring

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1424]
> Furthermore, these ads should stop as soon as the called person answers - but this does not always happen. In some cases the playback ran during the whole phone call, which makes communication almost impossible.
> 
> Another annoying thing is that the "post-call" ads block the screen for over a minute, which makes "quick calls" difficult.
> 
> Although sellAring claims not to collect any user information at all, the reality looks different: Research has shown that IMEI and MEID, among others, were collected. Last but not least, Android apps with sellAring consume a lot of resources.
> 

from https://android.izzysoft.de/help?topic=modwarnings#sellaring

We should block the whole domain (www.sellaring.com)

**Comment by StevenBlack** [comment]
Two thousand fucking twelve.
