### ISSUE TITLE
Tencent Social Ads

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1425]
`[Tencent Enters US Market With Ad Solutions And Access To Vast Amounts Of User Data](https://www.adexchanger.com/data-exchanges/tencent-enters-us-market-ad-solutions-access-vast-amounts-user-data/)`

from https://android.izzysoft.de/help?topic=modwarnings#tencentsocial

We should block the whole domain (oneaic.com)

**Comment by StevenBlack** [comment]
The link, which I followed and checked references, is from 2017.

Closing.
