### ISSUE TITLE
Upsight.com

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1426]
> [Lawsuit Alleges Disney Illegally Tracks Children Via Apps](https://threatpost.com/lawsuit-alleges-disney-illegally-tracks-children-via-apps/127261/)

from https://android.izzysoft.de/help?topic=modwarnings#upsight

We should block the whole domain (Upsight.com)

**Comment by StevenBlack** [comment]
Beer @beerisgood we aren't in the business of 'disappearing' companies from the internet.  So we aren't going to block the home domain unless they use that to deliver adware or scumware.

The references provided by the link above are from 2017.

This is a very stale trail, without specific actionable domains.

Closing.
