### ISSUE TITLE
ad pop up site

### ISSUE THREAD

**Issue by minutesinch** [StevenBlack/hosts#1427]
https://ttoc8ok.com/n2ymv15m7p?key=0f22c1fd609f13cb7947c8cabfe1a90d&submetric=14213579
https://ttoc8ok.com/

speared through torrent

**Comment by lightswitch05** [comment]
`ttoc8ok.com` has been blocked in this project since [Oct 15, 2017](https://github.com/StevenBlack/hosts/commit/34f1b5ffcdcb95d304cf5598682bf7e4f6e25424#diff-d42eb161de5c611d9de5263cc3cfce5aa4e6d40ba6f675192b957e105b3b71f1R10325) - originally added by the 'Badd-Boyz-Hosts' lists.

**Comment by lightswitch05** [comment]
Its also been included in Dan Pollock's list since Sep 15 2020

**Comment by StevenBlack** [comment]
Closing.
