### ISSUE TITLE
High disk usage Microsoft To Do

### ISSUE THREAD

**Issue by maisonmdsgreen** [StevenBlack/hosts#1430]
Microsoft To Do use Disk 3-5Mb second problem is block mobile.pipe.aria.microsoft.com
Disable Adlist solved problem

https://todo.uservoice.com/forums/597175-feature-suggestions/suggestions/37327276-high-disk-usage

Thanks
Maison

**Comment by StevenBlack** [comment]
Hi @maisonmdsgreen we've [discussed this before](https://github.com/StevenBlack/hosts/search?q=mobile.pipe.aria.microsoft.com&type=issues) and I don't expect this will change anytime soon.

Closing.
