### ISSUE TITLE
4 new sites (2 malicious + 2 suspicious/ adware)

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1433]
`https://psozyhotho.pro/` [[Virustotal](https://www.virustotal.com/gui/url/55463d2d729b522097bd8b615b0d2dcb2048b3a0030227bb190c2c6f2de7d0f9/detection)] which redirect to `https://remove-ads.xyz/` [[Virustotal](https://www.virustotal.com/gui/url/78985a36031ec7341a902ad1980ebf6745f889df476073b36acbb03105d707a8/detection)]

`https://400.route.to.adtracker.network/` which redirect to `https://www.prioritisemyhealth.com`

Got all 4 on a streaming site

**Comment by StevenBlack** [comment]
Beer @beerisgood who is the advertiser here, and who is the redirector?  It's not clear from your descriptions.

Reason is, redirects are legitimate. It's the target I want to squash.  

Unless the first link (of both description lines) is an annoying serial redirector.  But you don't say that.  I don't know what you're saying.  I avoid blindly following links posted here.

**Comment by beerisgood** [comment]
All sites are used on a streaming site which opens automatically.
The first one from both lines opens, which redirect to another one. So the targets are the latter ones.

**Comment by StevenBlack** [comment]
Thanks Beer @beerisgood these are added in commit d06c30d.

Closing.
