### ISSUE TITLE
Enforcing safesearch

### ISSUE THREAD

**Issue by Waltharnack** [StevenBlack/hosts#1436]
Hello, I know that it may very well be outside the scope of this project, but what about having the possibility to enforce safe search with search engines providing a safe search ip ?

It would be useful in conjunction with porn block list for example that does not block porn appearing in search results. 

You can obtain some of those ip by pinging : 

forcesafesearch.google.com 
strict.bing.com 
safe.duckduckgo.com
Yandex has 213.180.193.56

See :
[Google SafeSearch](https://support.google.com/websearch/answer/186669?hl=en)
[Yandex SafeSearch](https://yandex.com/support/search/schoolsearch.html)
[Bing SafeSearch](http://help.bing.microsoft.com/#apex/bing/en-us/10003/0)
[Duckduckgo SafeSearch](https://help.duckduckgo.com/duckduckgo-help-pages/features/safe-search/?ia=web)

The update script could probably generate entries by pinging the safe search engines domain names and adding an entries for all the owned domains of this search engine.

**Comment by StevenBlack** [comment]
Hi Simon @Waltharnack, thank you for this suggestion.

You're right, this is out of scope.  

It's possible we could use hosts as a hook for this, but we can't arbitrarily impose safesearch.  I imagine a curated porn list could do this, and deal with consequences incoming, but that's not our call.

Closing.
