### ISSUE TITLE
new ad domain

### ISSUE THREAD

**Issue by Sego1234** [StevenBlack/hosts#1437]
the ad domain is n(.)gameads(.)io

it shows ads for io games on websites like paper(.)io

**Comment by dnmTX** [comment]
**Confirmed** also `cdn.gameads.io` can be added as well 👍 
![Capture](https://user-images.githubusercontent.com/34774426/96943027-75dfff80-149c-11eb-8106-9aba82683ecf.PNG)

`0.0.0.0 n.gameads.io`
`0.0.0.0 cdn.gameads.io`
`0.0.0.0 api.gameads.io`
`0.0.0.0 banner.gameads.io`
`0.0.0.0 node.gameads.io`
`0.0.0.0 panel.gameads.io`
`0.0.0.0 shapez.gameads.io`

**Comment by StevenBlack** [comment]
Thanks @Sego1234 and thanks for the assist Dan @dnmTX.  This is added in commit 1cd35b6c.

Closing.
