### ISSUE TITLE
add more rt domains to the fakenews hosts

### ISSUE THREAD

**Issue by daywalk3r666** [StevenBlack/hosts#1438]
deutsch.rt.com
francais.rt.com
actualidad.rt.com

**Comment by StevenBlack** [comment]
Hi @daywalk3r666 this is an insufficient information, zero justification, minimum effort issue description.

Closing.

**Comment by daywalk3r666** [comment]
sry for not adding more infos. in your fakenews source is www.rt.com(russia today) but there are more domains for example in germany,france and spain.

www.deutsch.rt.com (germany)
www.francais.rt.com (france)
www.actualidad.rt.com (spain)
http://arabic.rt.com/ (arabic)

hope this is enough information @StevenBlack

**Comment by StevenBlack** [comment]
Over to you for your consideration, @marktron.  I can't judge these.

**Comment by marktron** [comment]
These are all country-specific versions of RT that have the same critiques of spreading Russian state propaganda as the English version, and are valid inclusions. I actually just published a new commit on [marktron/fakenews](https://github.com/marktron/fakenews/commit/0e0fbc2a0abb0e6e5637c204912846d8391b1bd7) that removed the `www` subdomain on RT's entry and will  block all of these now.
