### ISSUE TITLE
Considering the notonmyshift list

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/hosts#1439]
I'm considering https://orca.pet/notonmyshift/ as a new list.  
* Actively curated since May 3, 2020
* Github repo: https://github.com/socram8888/not-on-my-shift
* [ISC License](https://github.com/socram8888/not-on-my-shift/blob/master/LICENSE) (I've not seen this one before)

[Ghosts](https://github.com/StevenBlack/ghosts) report:

```
./ghosts -tld -c  https://orca.pet/notonmyshift/hosts.txt --intersection
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 57,558
Bytes: 1.7 MB
TLD tally:
   com: 30,473
   net: 6,433
   pl: 5,578
   eu: 912
   live: 910
   info: 828
   org: 827
   vn: 821
   jp: 817
   ru: 711
   de: 545
   xyz: 469
   nl: 422
   uk: 415
   cn: 326
   io: 321
   at: 296
   fr: 295
   co: 278
   in: 268
   biz: 235
   us: 221
   online: 202
   it: 178
   site: 172
   br: 171
   tv: 169
   tk: 163
   club: 146
   me: 132
   mobi: 123
   top: 116
   ca: 115
   cz: 110
   name: 100
 
  === 247 lines redacted ===

----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://orca.pet/notonmyshift/hosts.txt
Domains: 690
Bytes: 26 kB
TLD tally:
   com: 444
   life: 148
   space: 44
   online: 8
   ro: 5
   ru: 5
   site: 4
   xyz: 4
   id: 3
   es: 3
   top: 3
   it: 2
   store: 2
   info: 2
   shop: 2
   do: 2
   net: 2
   th: 2
   cm: 2
   email: 2
   me: 1
----------------------------------------
intersection: [
adsdk.yandex.ru
gmai.com
googlre.com
gopogle.com
mobile-global-apps-store.life
www.gmai.com
www.googlre.com
www.gopogle.com
www.mobile-global-apps-store.life
www.xiti.com
xiti.com
yotube.com
z3dmbpl6309s.com
]
Intersection: 13 domains
```

**Comment by jawz101** [comment]
one thing I'm doing with the Adaway list is checking the entries against the the list of the most commonly requested DNS lookups to the Cisco/Umbrella/OpenDNS 1 Million list.  My premise being if all of the devices that use OpenDNS/Umbrella servers do not attempt to look up DNS records then how effective is the entry.  This would complement something like PyFunceble that verifies whois records.

http://s3-us-west-1.amazonaws.com/umbrella-static/index.html

I trimmed about 1500 entries off of Adaway that were likely the results of old imports or from companies that no longer exist.

I've now been testing against the Steven Black host source lists by downloading, say, every 1 million file for the past 2 or 3 months, merging them, remove dups, and then compare to StevenBlack.  So far, only about 11,000 of the entries on Steven Black are even requested on a significant scale.  I've been working with the 1 million lists a bit over the past few months and combing its contents and I have to say that 1 million is enough to represent the activity we all collectively use.

When you notice that fonts.googleapis.com is consistently in like the top 50 name lookups in the world that is crazy.  Just fonts that Google hosts to 'beautify the web'.

Anyways, I just wonder how useful some entries are if no one looks them up.

**Comment by lightswitch05** [comment]
Here is addition-only diff against the current version of the unified list and the notonmyshift list. Doing a random spot check, all domains are currently resolving to `A` queries.

https://blocklist-tools.developerdan.com/versions/1b4d9373-0942-4bca-873a-c13191a6b19f/diff/8dab13d8-20b4-446e-8de1-fcd8a1d6ccb4?type=addition

**Comment by StevenBlack** [comment]
Thanks Dan @lightswitch05 that's interesting!

**Comment by dnmTX** [comment]
Steve @StevenBlack what's the hold up on this one?

**Comment by StevenBlack** [comment]
@dnmTX thank you for the reminder, Dan.

👋  Hello Marcos @socram8888 — can I include your list at https://orca.pet/notonmyshift/hosts.txt into the amalgamated hosts files and variants hosted here?

**Comment by socram8888** [comment]
Sure, go ahead!

**Comment by StevenBlack** [comment]
Thanks Marcos @socram8888!

**Comment by StevenBlack** [comment]
What took me so long?  Time flies.

Thank you again Marcos @socram8888.  *Not On My Shift!* is included in new [release 3.4.0](https://github.com/StevenBlack/hosts/releases/tag/3.4.0).

Closing!

**Comment by StevenBlack** [comment]
Marcos @socram8888 can you please have a look in the [Sources of hosts data unified in this variant](https://github.com/StevenBlack/hosts) section in the readme, I have this listed as `orca.pet` but I'm happy to call it, and list it, as you please.

**Comment by socram8888** [comment]
orca.pet is perfectly fine!
