### ISSUE TITLE
Phishing Site

### ISSUE THREAD

**Issue by minutesinch** [StevenBlack/hosts#1440]
received from email a lot
http://rdtzbv88.congkumon.biz/?7EYIPQ45
rdtzbv88.congkumon.biz

**Comment by StevenBlack** [comment]
You know Mini @minutesinch, we're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

It's true that I have my own ad-hoc file included in this list, but please understand, this is not an open bucket for the world to just add domains, one at a time, one issue at a time, endlessly.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).  These people have curation of domains in their workflow.  I want to focus on curating lists, not individual domains.  I'm just not set up to curate individual domains at scale.

Closing.
