### ISSUE TITLE
New fake news/spam and scam domain

### ISSUE THREAD

**Issue by msdlr** [StevenBlack/hosts#1441]
Hello, I've come across a new spam domain about this thing called 'Bitcoin UP' (which seems far from legit, but the page clearly tries to mimmick a National-scale Spanish newspaper) so I think these should be added to the blocklist:

```worldnewstoday.site``` (whose 'baity page' is this, so I'd bet the whole domain is used for variations of this page: https://worldnewstoday.site/es/up/?_subid=3pci1605f956047c4246&_token=uuid_3pci1605f956047c4246_3pci1605f956047c42465f956047c47387.92247737)

```bitcoin-upappl.com```: the actual page for getting people's CC information

Thanks in advance!

**Comment by StevenBlack** [comment]
Hi @msdlr thank you for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
