### ISSUE TITLE
Source list popularity- comparing StevenBlack sources to Cisco's Umbrella 1 million popularity list

### ISSUE THREAD

**Issue by jawz101** [StevenBlack/hosts#1442]
Cisco/Umbrella aka OpenDNS maintains a daily log of the 1 million most name lookups by all users of their services:

http://s3-us-west-1.amazonaws.com/umbrella-static/index.html

I interpret this as the current state of DNS lookups in the world.

Taking this information I use this to cull and evaluate the usefullness of Adaway and scrub out what might represent old companies, entries that have lost their function... etc.  Basically no one's devices looks up these domains.

example of the Adaway removals [link](https://github.com/AdAway/adaway.github.io/commit/fe5414af487ed313c408b80409345ee21b3ca08f)

Another check I've used is to verify whois records (that is, does someone currently own the domain).  funlrys has a tool designed for bulk checking of blocklists to do verify whois records https://github.com/funilrys/PyFunceble

Back to the Cisco 1 million.  For the Adaway commit I downloaded the daily 1 million entries for August 1st thru October 13 - about 79 files or so.  I then merged them, sorted them, pared it down to the unique entries, and then checked the Adaway list against it to see which entries had been used by anyone anywhere in that 2.5 month timeframe.  This removed about 1,500 entries from Adaway.

When I worked on MobileAdTrackers I started with a couple hundred entries and it grew to a few thousand over time by downloading and observing the crappy mobile apps and games we all typically install.  I had also found other mobile-oriented lists and imported them over time and it didn't seem like the right approach because I wanted MobileAdTrackers to be original so I've mostly been removing more than adding these days.  I figure there are realistically only 4-6000 entries at most that represent ads and trackers in the mobile space and maybe no more than 20,000 additional entries to cover the current state of the web and spam -excluding the shortlived, transient spam, malware, and adtech companies out there.

Anyways, I wanted to use this same Cisco Umbrella/OpenDNS 1 million check against the source lists for Steven Black.  I took these dated 1 million snapshots
```

top-1m-2020-08-15.csv
top-1m-2020-08-31.csv
top-1m-2020-09-08.csv
top-1m-2020-09-16.csv
top-1m-2020-09-24.csv
top-1m-2020-10-02.csv
top-1m-2020-10-06.csv
top-1m-2020-10-10.csv
top-1m-2020-10-13.csv
```

merged,sorted, removed dups and got about 2.1 million entries.  I then took the StevenBlack source lists and checked them against this set of name loookups from this 2 month timeframe and here are the results.

list | in top 1   million list | total entries | percent
-- | -- | -- | --
adaway | 6568 | 6872 | 95.58%
tiuxomasterads | 956 | 2214 | 43.18%
bigdargonVN | 529 | 1447 | 36.56%
yoyo | 1283 | 3545 | 36.19%
winhelp2002-mvps | 2096 | 9259 | 22.64%
FadeMind.add.2o7Net | 169 | 1286 | 13.14%
StevenBlack | 379 | 2937 | 12.90%
someonewhocares | 1579 | 14543 | 10.86%
FadeMind.add.Risk | 172 | 2567 | 6.70%
FadeMind.add.Spam | 4 | 73 | 5.48%
Badd-Boyz | 24 | 827 | 2.90%
KAD_without_controversies | 192 | 13146 | 1.46%
urlhaus-abuse | 19 | 1436 | 1.32%
davidonzoThreat-Intel | 10 | 2139 | 0.47%
malwaredomainlist | 5 | 1105 | 0.45%
FadeMind.add.Dead | 0 | 20 | 0.00%
FadeMind.UncheckyAds | 0 | 10 | 0.00%

My interpretation is that lists differ in value due to the changing landscape (mobile apps, websites, smart devices, spyware software, malware, spam email, etc.)

With the StevenBlack list I essentially get the same usefulness from about 11,000 entries.
https://github.com/jawz101/tinysbc (I don't actually use <this< list.  It was a one time experiment).

I don't want to dissuade larger lists except for the 100 thousand to 1.5 million huge combo lists

**Comment by StevenBlack** [comment]
Thanks for this @jawz101.  To clarify, the `StevenBlack` list above is my personal ad-hoc source list, not the amalgamated list.  I'm curious about stats for the amalgamated list.

Do you have the correct URLHaus list?  The one we use presently has 1339 domains and may be the most actively curated of all lists overall.  Lots of turnover, I'm surprised by its low percent-per-million shown here.

It's conceivable that some of the worst malware would not come from a top-million list, at least not initially.

**Comment by jawz101** [comment]
I downloaded the files linked in this repo's readme
