### ISSUE TITLE
domain cdn.tagcommander.com

### ISSUE THREAD

**Issue by mathieuruellan** [StevenBlack/hosts#1447]
Hi,

I'm using the (adware + malware) host file, preconfigured with my pihole.
My opinion is that it's a bad idea to add cdn.tagcommander.com. There is several websites using this cdn to hosts js files. Puting them in black list, makes interfaces not working well without error message.
My last personnal experience was with this user interface https://www.malakoffhumanis.com/ 
I can see in pihole forums similar problems with ubisoft store or laposte.fr.

**Comment by StevenBlack** [comment]
Thank you Mathieu @mathieuruellan the domain `cdn.tagcommander.com` comes to us via mvps.org and AdAway.  So two of our upstream sources are flagging this domain.  Please refer this to those list curators.
