### ISSUE TITLE
intel11.edgekey.net

### ISSUE THREAD

**Issue by slalik** [StevenBlack/hosts#1448]
Blocking `intel11.edgekey.net` breaks `downloadcenter.intel.com`, which is CNAME for `intel11.edgekey.net`. I suggest unblock `intel11.edgekey.net`.

**Comment by XhmikosR** [comment]
Yup, I just noticed it myself after I updated manually my Pi-hole today. It seems it's coming from AdAway, specifically [this  commit](https://github.com/AdAway/adaway.github.io/commit/1757a0a12d783ec7c47477f07a40b0dfd9fee206) (the commit message seems to be missing)

/CC @jawz101

**Comment by jawz101** [comment]
removed

**Comment by StevenBlack** [comment]
Thank you everybody, this is fixed and released in Release 3.1.4 just now.
