### ISSUE TITLE
This breaks the dotnet/cli package

### ISSUE THREAD

**Issue by aapis** [StevenBlack/hosts#145]
Microsoft uses `cs1.wpc.v0cdn.net` for nuget.org, and due to the `dotnet` package's reliance on nuget for just about everything the end result is you cannot execute `run` or `restore` commands if that host is blocked.  I propose simply commenting it out (as I've done in my fork, below) with a note as to why it's still there.

More details: https://github.com/yegcollective/hosts/pull/1

Admittedly, not a big issue for most users (I think).

**Comment by StevenBlack** [comment]
Sorry for the delay Ryan @aapis.

@tyzbit what do you think?  This host entry comes from your package.  Worth considering?

**Comment by tyzbit** [comment]
For the record; v0cdn.net is part of Verizon's Edge Cast CDN.  I don't have the justification documented why cs1.wpc was included, but to compare, there are multiple instances where Akamai's CDN is listed elsewhere.

I think a case can be made to keep the host blocked, but maybe list `nuget` as software affected by default blocking.  The only other instance I can think of that this line might affect is perhaps any on-demand streaming provided by Verizon, but that could use a different hostname and thus be unaffected.

Do we want to err on the side of more blocking, or not breaking things?

**Comment by aapis** [comment]
I'm ok with that too.  I think the overlap from users of this package and of .NET Core is probably pretty limited anyways.  Verizon doesn't operate in my country so it didn't affect anything else for me, but it may for Americans.

**Comment by StevenBlack** [comment]
Thanks for your input everybody! @aapis @tyzbit 

Closing.
