### ISSUE TITLE
g.live.com is blocked but needed for OneDrive to work

### ISSUE THREAD

**Issue by ts-ws** [StevenBlack/hosts#1450]
Hi,

I having some problem's with my OneDrive after a while I figure out that the problem was cause by my pihole blocking "g.live.com"
So I looked up in which list this domain was included.
I can't find it in any of my lists. But if I disabled "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts" the block is gone.
So is there a entry in the list I don't find which explains the block of the domain or is it a bug in the pihole?

**Comment by dnmTX** [comment]
@ts-ws  try whitelisting `g.msn.com` and see if that fixes the problem. Might work or might not. Let us know 👍

**Comment by ts-ws** [comment]
Hi,
yes whitelist g.msn.com have the same affect as whitelist g.live.com OneDrive is working fine after whitelist one of this domains.

**Comment by dnmTX** [comment]
Well...`g.msn.com` is Alias of `g.live.com` which proofs that Pi-Hole not only blocks the (black)listed domain(s) CNAMES but their Aliases as well which really needs to be addressed with their devs and solution to be find. Removing domains solely because it's a CNAME or Alias of the blocked domain it's unpractical and wrong as the former and later are very likely used to push advertisements and whatnot in many cases.

**Comment by llacb47** [comment]
Did you have a problem with Onedrive website, desktop app, or mobile app? Please be specific because "Onedrive" is not very helpful.

**Comment by ts-ws** [comment]
@llacb47 I had problems with the DesktopApp.
In the settings of the DesktopApp under the Tab "Back up" is normally a menu point called "Important PC Folders" the point is completely vanished if the g.msn.com/g.live.com domain is blocked.

Settings if g.msn.com is not blocked
![msn not blocked](https://user-images.githubusercontent.com/52138452/98171262-bbb2b400-1eef-11eb-9c15-b6553c4464b0.png)

Settings if g.msn.com is blocked
![msn blocked](https://user-images.githubusercontent.com/52138452/98171264-bc4b4a80-1eef-11eb-9cca-b117ea45a8de.png)

**Comment by StevenBlack** [comment]
Lars @ts-ws we don't list the `g.live.com` domain here.

The `g.msn.com` comes to us via Dan Pollock at someonewhocares.org.  You can make your case with him at hosts@someonewhocares.org.  Dan is very reasonable and he'll ultimately do the Right Thing.

**Comment by StevenBlack** [comment]
Closing this now.
