### ISSUE TITLE
Newrelic dashboard is broken

### ISSUE THREAD

**Issue by emlimap** [StevenBlack/hosts#1451]
I am no longer able to access newrelic with hosts file enabled in Adguard Home.

`service.newrelic.com` blocks newrelic dashboard as it is used as CNAME for both `one.newrelic.com` and `rpm.newrelic.com` and AGH does CNAME blocking.

`insights.newrelic.com` - used for querying customer data - https://newrelic.com/products/insights

`frame-infrastructure.newrelic.com` - Breaks infrastructure metrics dashboard

While newrelic does collect stats from browser and apps. It also does infrastructure monitoring so blocking newrelic outright breaks everything. These are the domains I had to whitelist to get dashboard to work but without allowing the browser/mobile app data collection

This site should give you an idea about domains in use https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/networks#browser-specific

**Comment by StevenBlack** [comment]
Hi @emlimap the `service.newrelic.com` domain comes to us via AdAway.  We don't list any other newrelic domain you cite.  

@jawz101 can you please look?  Thanks!

**Comment by jawz101** [comment]
removed.  thank you

**Comment by StevenBlack** [comment]
Thanks @jawz101 and thank you @emlimap for the issue.

This will propagate with the next release.

**Comment by emlimap** [comment]
@StevenBlack Looks like I got it mixed it up since they refer to CNAME `service.newrelic.com`. As a result, they got blocked as well.

@jawz101 Thank you removing the CNAME. Something I missed out in previous request, would you be able to remove `login.newrelic.com` as it breaks login page https://github.com/AdAway/adaway.github.io/blob/fb2e9ded3493ec3512be6f00c07ca673930b27dd/hosts.txt#L8698

Also `api.newrelic.com` breaks their CLI as well as anything that uses this endpoint. This endpoint is purely to manage newrelic configuration https://rpm.newrelic.com/api/explore (requires the api endpoint to be whitelisted for full page to load).

**Comment by jawz101** [comment]
I've removed those 2 now.  Thanks
