### ISSUE TITLE
This list is completely blocking the iOS ESPN to the point is not working at all.

### ISSUE THREAD

**Issue by iwilliamsj** [StevenBlack/hosts#1452]
site.web.api.espn.com
fan.api.espn.com
a.espncdn.com
w88.espn.com

all of them are being mistakenly blocked.

**Comment by StevenBlack** [comment]
@iwilliamsj we don't presently list any of these.

```
site.web.api.espn.com
fan.api.espn.com
a.espncdn.com
w88.espn.com
```

Closing.

**Comment by iwilliamsj** [comment]
Using NextDNS and the logs says is being blocked by NextDNS Ads & Trackers Blocklist and Steven Black.
<img width="893" alt="Screen Shot 2020-11-06 at 1 53 02 PM" src="https://user-images.githubusercontent.com/25371730/98403870-a052c080-2037-11eb-8e92-7d1d7c481a75.png">

**Comment by dnmTX** [comment]
@iwilliamsj  just FYI. `api.espn.com` is listed here so if NextDNS engaging some kind of a wildcard blocking,like `*.api.espn.com`,
that might be it. In this case you need to do some adjustments on your end.

**Comment by StevenBlack** [comment]
The `api.espn.com` comes to us via AdAway.  @jawz101 is this a mistake?  I defer to you, as always.

**Comment by jawz101** [comment]
removed
thank you

**Comment by iwilliamsj** [comment]
I use ESPN+ a lot to watch soccer games. This has successfully fixed the issue!!! Thanks in advance!

**Comment by iwilliamsj** [comment]
Damn it I spoke too soon it seems it still blocking all of this domains still. Will try to get in touch with NextDNS folks.
