### ISSUE TITLE
Malware Domain List certificate error, missing hosts file

### ISSUE THREAD

**Issue by b0gdanw** [StevenBlack/hosts#1455]
https://www.malwaredomainlist.com has a self-signed certificate, the file https://www.malwaredomainlist.com/hostslist/hosts.txt is missing

**Comment by StevenBlack** [comment]
Thank you Brogdan @b0gdanw.

In view of Issues #1403 ***Malware Domain List is obsolete*** and #1367 ***Obsolete/non-maintained lists*** it's time to pull the plug on MalwareDomainList.

**Comment by StevenBlack** [comment]
Fixed.  Closing.
