### ISSUE TITLE
Malware Domain List Down (again)

### ISSUE THREAD

**Issue by asche77** [StevenBlack/hosts#1456]
DNS seems to be broken - entry points to 127.0.0.1 
https://who.is/whois/malwaredomainlist.com/

`

Hostname | Type | TTL | Priority | Content
-- | -- | -- | -- | --
malwaredomainlist.com | SOA | 3600 |   | dns1.registrar-servers.com hostmaster@registrar-servers.com 1604939423 43200 3600 604800 3601
malwaredomainlist.com | NS | 1799 |   | dns1.registrar-servers.com
malwaredomainlist.com | NS | 1799 |   | dns2.registrar-servers.com
malwaredomainlist.com | A | 1799 |   | 127.0.0.1
malwaredomainlist.com | MX | 1799 | 10 | mail.malwaredomainlist.com
www.malwaredomainlist.com | A | 1711 |   | 127.0.0.1

`

**Comment by dnmTX** [comment]
@asche77 see #1455 and close this issue please. Thanks 👍
