### ISSUE TITLE
Malware Domain List Down

### ISSUE THREAD

**Issue by Mr-13** [StevenBlack/hosts#1457]
It appears that the Malware Domain List is now offline.

![image](https://user-images.githubusercontent.com/35493223/98782009-45491100-241d-11eb-8217-b9a2894ebb72.png)

**Comment by dnmTX** [comment]
List [already removed](#1455 ). You can close this issue. Thanks 👍

**Comment by Mr-13** [comment]
Ah! I should have checked it. Sorry for inconvenience. Closing this one.
