### ISSUE TITLE
SpeedCurve web app blocked

### ISSUE THREAD

**Issue by wildlyinaccurate** [StevenBlack/hosts#1458]
Hey there! Quick disclaimer: I work for SpeedCurve.

We just had a few reports[1][2][3] that the SpeedCurve web app is being blocked by PiHole, which I believe uses this hosts list. SpeedCurve provides a real user monitoring (RUM) tracker but that's only ever served from cdn.speedcurve.com (e.g. https://cdn.speedcurve.com/js/lux.js?id=520800816). Would it be possible to update this list to block only cdn.speedcurve.com so that the RUM tracker remains blocked but the rest of the web app works?

[1] https://twitter.com/mikestreety/status/1326607438271946753
[2] https://twitter.com/freshmango/status/1326620126268039173
[3] https://twitter.com/mlocik97/status/1334583330445139969

**Comment by StevenBlack** [comment]
Hi Joseph @wildlyinaccurate .

The `speedcurve.com` domain comes to us via Dan Pollock who curates the someonewhocares.org hosts file, one of our sources.

You can reach Dan at hosts@someonewhocares.org — please let us know how it goes!
