### ISSUE TITLE
Add Datatrics.com

### ISSUE THREAD

**Issue by filipecatraia** [StevenBlack/hosts#1463]
Just found [this one](https://www.datatrics.com/) on a website in Belgium. They seem to be doing multi-channel data aggregation to build customer profiles. Not really a fan.

**Comment by dnmTX** [comment]
Domains that i found that might be of interest:

`0.0.0.0 api.datatrics.com`
`0.0.0.0 api04.datatrics.com`
`0.0.0.0 api03.datatrics.com`
`0.0.0.0 app.datatrics.com`
`0.0.0.0 images.datatrics.com`
`0.0.0.0 network.datatrics.com`
`0.0.0.0 tr-v2.datatrics.com`
`0.0.0.0 track*.datatrics.com`
`0.0.0.0 tr.datatrics.com`
`0.0.0.0 tr-255418.datatrics.com`
`0.0.0.0 tr-255768.datatrics.com`
`0.0.0.0 tr-256089.datatrics.com`
`0.0.0.0 tr-op.datatrics.com`
`0.0.0.0 tr-reshift.datatrics.com`
`0.0.0.0 tracker.datatrics.com`
`0.0.0.0 usersync.datatrics.com`
`0.0.0.0 status.datatrics.com`
`0.0.0.0 mautic.datatrics.com`
`0.0.0.0 magento01.datatrics.com`
`0.0.0.0 woocommerce01.datatrics.com`
`0.0.0.0 ecommerce.datatrics.com`
`0.0.0.0 travel.datatrics.com`
`0.0.0.0 link.datatrics.com`

Steve @StevenBlack you got it from here 👍

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX and thank you Filipe @filipecatraia for submitting this issue.

This is added in commit de32eb3d.

Closing.
