### ISSUE TITLE
Add opengapps.com website

### ISSUE THREAD

**Issue by 1alessandro1** [StevenBlack/hosts#1465]
127.0.0.1 opengapps.com

This website redirects to phishing sites

**Comment by StevenBlack** [comment]
Thank you Alessandro @1alessandro1, that one is really, really bad.

Folks, don't click that.

In my next edit sesh, I'll add this.

I'm considering running a [Qubes os](https://www.qubes-os.org/) box to investigate heinous rabbit holes like this one.  Every domain linked should be blocked, too.

**Comment by StevenBlack** [comment]
Done!  Thank you Alessandro @1alessandro1.

Closing.

**Comment by 1alessandro1** [comment]
If there's a thing infinite in the universe, that's phishing for sure :)

Another couple of websites I stumbled upon even if I'm using a 400K+ hosts blacklist from molinero

127.0.0.1 guidalamoto.it
127.0.0.1 win-your-prize-now2.life
