### ISSUE TITLE
[3 Suspicious sites] https://privatewinners.com/ & https://track.wg-aff.com/ & https://www.pamsg.online/

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1466]
`https://privatewinners.com/` redirect to `https://triumphantplace.com/landing/roulette?sub_id_7=` which you already block on your https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts.

`https://track.wg-aff.com/` redirect to `wargaming-affliate.g2afse.com` is another suspicious.

`https://www.pamsg.online/` try to install a "MessengerTIme" fake:
![image](https://user-images.githubusercontent.com/9625159/99854773-beff9e00-2b85-11eb-8515-bdd8b06284af.png)

I found all on a streaming site

**Comment by StevenBlack** [comment]
Hi @beerisgood,

> `https://privatewinners.com/` redirect to `https://triumphantplace.com/landing/roulette?sub_id_7=` which you already block

Therefore, no problem.

> `https://track.wg-aff.com/` redirect to `wargaming-affliate.g2afse.com` is another suspicious.

Not seeing anything suspicious here.  Please elaborate.

> `https://www.pamsg.online/`

I'll add that.

**Comment by beerisgood** [comment]
> > `https://track.wg-aff.com/` redirect to `wargaming-affliate.g2afse.com` is another suspicious.
> 
> Not seeing anything suspicious here. Please elaborate.

before `https://track.wg-aff.com/` got blocked on my side, i see gambling on that site. Maybe solved now.

Thanks for adding the pamsg domain

**Comment by beerisgood** [comment]
> `https://privatewinners.com/` redirect to `https://triumphantplace.com/landing/roulette?sub_id_7=` which you already block on your https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts.

Looks like they remove the redirect:
![image](https://user-images.githubusercontent.com/9625159/100427278-85052f00-3092-11eb-9e2c-10552b6550ac.png)

@StevenBlack
