### ISSUE TITLE
Audible bookmarks blocked

### ISSUE THREAD

**Issue by EnigmaG** [StevenBlack/hosts#1467]
Audible needs "audible.sc.omtrdc.net" to remember the last place you listened to.

**Comment by dnmTX** [comment]
@EnigmaG  report it directly to the curator in [AdAway](https://github.com/AdAway/adaway.github.io/issues).Thanks 👍

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX.  Ping @jawz101 — thanks!

**Comment by StevenBlack** [comment]
Closing as this is reported upstream.
