### ISSUE TITLE
fls-eu.amazon.de 

### ISSUE THREAD

**Issue by dieechtenilente** [StevenBlack/hosts#1468]
Hi,

fls-eu.amazon.de is mandatory to use the Amazon App on Android. Otherwise you will get some nice dogs and "Something went wrong" messages.

Does somebody know if it is used for tracking, too?

**Comment by StevenBlack** [comment]
Hi Klaus @dieechtenilente, thank you for this.

The `fls-eu.amazon.de` domain comes to us via AdAway.

Ping @jawz101 — can you look at this?  Thanks!

**Comment by jawz101** [comment]
removing

**Comment by StevenBlack** [comment]
Thanks @jawz101!

Closing.

**Comment by jawz101** [comment]
I get requests to add this and then people say it breaks things.  I just want to be clear what these domains are 

https://github.com/AdAway/adaway.github.io/commit/e857556f53c5436eb7e434b5af299b26a5e961ce

>  add the other Amazon Forrester Log Service domains
> 
> Amazon Workspaces describes this as the domain for Forrester Log Service here https://docs.aws.amazon.com/workspaces/latest/adminguide/workspaces-port-requirements.html
> Forrester is a market analytics company https://go.forrester.com.  A usecase they present would be to do something like say 30% of the time people check out Amazon before making a purchase decision. https://go.forrester.com/analytics/
> 
> There are several case studies on their site.  Either way, if you experience breakage in any Amazon apps just whitelist entries if they cause problems.  Otherwise, they're hit often enough for inclusion.
