### ISSUE TITLE
ad domains

### ISSUE THREAD

**Issue by pendie** [StevenBlack/hosts#1469]
ck.jads.co
ads.juicyads.com
adserver.juicyads.com
adserver-a.juicyads.com
ads-a.juicyads.com
ck.juicyads.com
js.juicyads.com
manage.juicyads.com
mobile.juicyads.com
xapi.juicyads.com
juicyads.rocks

**Comment by StevenBlack** [comment]
Hi @pendie thank you for this.

We already block these `juicyads` domains.  You're suggesting at least 3 we already block.  Did you check this?

Secondly we aren't in the business of making companies invisible on the internet.   Do you think `juicyads` is serving ads from `manage.juicyads.com` and `xapi.juicyads.com`?  I don't think so.

```
ck.juicyads.com
js.juicyads.com
redir.juicyads.com
xapi.juicyads.com
www.juicyads.com
ads-a.juicyads.com
ads.juicyads.com
adserver.juicyads.com
mobile.juicyads.com
```

Closing.

**Comment by pendie** [comment]
hey friend try to check here
https://manhwas.men

**Comment by pendie** [comment]
I found it
ck.jads.co
![bandicam 2020-11-25 07-54-32-208](https://user-images.githubusercontent.com/68742906/100164825-ac71c580-2ef3-11eb-8ee4-4e1bfd23d2c6.jpg)
