### ISSUE TITLE
Any chance of getting update emails when new lists are posted?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [StevenBlack/hosts#147]

**Comment by StevenBlack** [comment]
I'm considering a cron job to generate new hosts files daily and pushing to Github if any of the underlying data has changed.

In that event I think daily emails would not be so useful :-)

Did you know... you can put `updateHostsFile.py` or the `makehosts` bash script in your own cron job to refresh data and create new hosts files yourself?

**Comment by GitTheHellOutaHere** [comment]
> Did you know... you can put updateHostsFile.py or the makehosts bash script in your own cron job to refresh data and create new hosts files yourself?

What language do you speaketh? It's all Greek to me!

**Comment by braian87b** [comment]
may be you could use somethink like https://www.followthatpage.com/ and point to watch https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by GitTheHellOutaHere** [comment]
Yeah, that would work too, thanks for the suggestion.
I was looking for a free app to do that, but it looks like everything is Internet-based now.

There was no real indication a cron job would be included in the near future, just that Steven was "considering" it. Therefore, monitoring the page for changes will suffice for now.

**Comment by notDavid** [comment]
fyi i recently found out you can use rss feeds for Github commits (and such): https://github.com/StevenBlack/hosts/commits/master/hosts.atom

So you should be able to use this link in for example [Monotony](https://itunes.apple.com/us/app/monotony/id533978766?mt=12) to get notifications of commits to the hosts file.

**Comment by StevenBlack** [comment]
Closing.
