### ISSUE TITLE
No internet

### ISSUE THREAD

**Issue by Yberial** [StevenBlack/hosts#1470]
Hello, the idea is great, on the other hand I have a little problem 
I use the automatic installer, I run the .bat everything goes well it works but once I restart my computer I no longer have internet, any idea? I am in WIFI key in 5 Ghz thx

**Comment by StevenBlack** [comment]
Hi @Yberial this is surely unrelated to your hosts file.  

Closing.

**Comment by Yberial** [comment]
Pourquoi à chaque fois que je l'enlève tout marche alors ?

**Comment by StevenBlack** [comment]
Branché?  Sans-fil?  Quel OS?  Quel fournisseur?  Quel marque wt modèle de boite?  Sapristi on est pas là pour résoudre les mille-et-unes choses qui sont présent chez vous.  Ecoute, ce fichier hosts tourne dans des milliers ou millions de circonstances, depuis 2012, et on a, j'usqu'ici, aucune indication que ça brique une connexion internet.

**Comment by Yberial** [comment]
I do not question at all your work which is excellent and super useful (in my quest for no fap !) but yet when I launch it it works except that, once the computer restarted I no longer have internet, my router is visible but there is written "no internet access" and the only way to find internet is when I delete the host file in windows no fail mode.

Connected? In wifi 
Wireless? Yes
Which OS? W10 last update
Which provider? Orange, France
Which brand and model of box? Livebox 5 Orange, with TP-Link Archer T4U AC1300 Dual Band V3.0 Wi-Fi Adapter (up to 867 Mbps - 5 GHz, USB 3.0, WPS) 

Thank you in advance and sorry for taking your time.
