### ISSUE TITLE
play.pulpower.com

### ISSUE THREAD

**Issue by beerisgood** [StevenBlack/hosts#1473]
the page opened on a streaming page

![image](https://user-images.githubusercontent.com/9625159/100441338-95bfa000-30a6-11eb-8af0-5a7b885587f5.png)

**Comment by StevenBlack** [comment]
@beerisgood we are mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

I simply cannot deal with incoming at a rate of one domain per issue.  Give me 25 domains in one issue, and then we can deal with it.  Good?

Closing.
