### ISSUE TITLE
Internet Connectivity Issue

### ISSUE THREAD

**Issue by Harshsrcc** [StevenBlack/hosts#1474]
Adding 'Unified Hosts + Porn + Social + Gambling' blocklist breaks my internet. Wifi Connects, but shows 'No Internet'. Additionally, I cannot amend the hosts file to undo changes.

**Comment by StevenBlack** [comment]
Hi @Harshsrcc thank you for this.

You understand, network connectivity and host resolution operate in vastly different layers, right?

How does a hosts file affect network connectivity?  Do you have someone local to you who can support you?  There's nothing we can do here....

Closing.
