### ISSUE TITLE
[Niconico] compatibility report

### ISSUE THREAD

**Issue by hashashin1191** [StevenBlack/hosts#1475]
**Describe the third party app**
 - Name: Niconico
 - Version: Web service and Android app

**Describe the compabitily issue**
* Unable to login on Android app.
* Unable to follow or unfollow user.

**Workaround**
If applicable, describe the whitelist domains to add to fix the issue:
 - api.nicovideo.jp
- public.api.nicovideo.jp
Please add tag `workaround-available` if a work around is available.

**Comment by StevenBlack** [comment]
Hi @hashashin1191 thank you for this.

The `nicovideo.jp` domains come to us from several sources.

Based on the host names, it's possible that `api.nicovideo.jp` and `public.api.nicovideo.jp` are overkill.  Those both come to us via AdAway.  @jawz101, what do you think?  I defer to your good judgment on this. as always.  Thanks!

**Comment by jawz101** [comment]
removed

**Comment by StevenBlack** [comment]
Thanks @jawz101!

@hashashin1191 this will be published in the next release, shortly.

Closing.
