### ISSUE TITLE
Internet connectivity issue

### ISSUE THREAD

**Issue by rgirishn** [StevenBlack/hosts#1476]
Exact same issue as https://github.com/StevenBlack/hosts/issues/1474
And similar to https://github.com/StevenBlack/hosts/issues/1470

Brand new Dell laptop that I was configuring for my son to take to school. Everything was working fine - all latest Windows 10 updates, all firmware updates done. WiFi connectivity was great.

I then updated the HOSTS file with the 'Unified Hosts + Porn + Social + Gambling' blocklist. Restarted the computer and WiFi connection to the router is good, but no internet connectivity.

I have read the comment you had for closing the 1474 ticket, and that the issue is unrelated. However, the issue is directly related to the hosts file update. I rolled back the changes to the file and everything is good again.

Feel free to mark this issue as unrelated etc and close, I am no longer using the blocklist. 

However, wanted you to be aware of the causal effect. Maybe it is blocking a DNS server or another resource that the ISP relies on, or an issue with DNS caching. Happy to help if you need any additional information. 

Thanks

**Comment by StevenBlack** [comment]
Hi @rgirishn thank you for this.

Look, you will have to solve your own Internet access issues, there is nothing we can do here to help you.

It sounds to me like you are accessing the Internet in a proprietary and non-standard way.  Whatever you are using, stop that, stop being a blind and traded computer user, beholden to whatever corporations have you by the balls.

Seriously.  I'm sorry, we just can't help you here.￼

**Comment by rgirishn** [comment]
Nothing non-standard or proprietary with the connection, believe me.

Have already fixed it by reverting to the original hosts file. Thanks for your wonderful attitude and help NOT

**Comment by StevenBlack** [comment]
> Nothing non-standard or proprietary with the connection, believe me.

Ya, right.  Good luck.

**Comment by rgirishn** [comment]
For those who might have the same problem, the issue appears to be "fixed" by disabling (registry edit) the DNS Client service. Not sure if that is the "right" solution though.

**Comment by StevenBlack** [comment]
This is Microsoft Windows bullshit.  One hundred percent.  Absolutely non-standard, and brain-dead.

**Comment by dnmTX** [comment]
> For those who might have the same problem, the issue appears to be "fixed" by disabling (registry edit) the DNS Client service. Not sure if that is the "right" solution though. Windows 10 Home

And how is that Steven's @StevenBlack business ?
You could've search a little better and fix it yourself instead of showing up here demanding.
If you looking for a **personal tech advisor/companion**,move along,there are **NONE** here !!!!

**Comment by rgirishn** [comment]
@dnmTX if you have nothing to contribute to the discussion, please move along. I did not ask for your help

**Comment by StevenBlack** [comment]
Now now Dan @dnmTX you know @rgirishn is just trying to get through life, like we all are.  Go easy.

At some point I'd like to talk about the next million/billion people who are, for sure, coming.

This all started with the idea of serving tech people who "get" it.  Increasingly we see folks from layers beneath that, bringing us their problems.

(Just now seeing @rgirishn snarky reply to you)

Hey zero-repo, zero-following, zero-follower @rgirishn random anon on GitHug: take a hike okay?

**Comment by rgirishn** [comment]
@StevenBlack nothing in here to get all worked up, relax. I had an issue with the hosts file and I wanted to bring to your attention. Go through my initial post, where was I demanding? I was just looking for suggestions if this was something encountered previously

**Comment by dnmTX** [comment]
Going easy and deleting my comment 😉

**Comment by licaon-kter** [comment]
Just a bit of info, a large hosts file (eg pick all lists combined) will overwelm DNS Client (service) on Windows 10 and 11. And until that service can parse the file, using one core at 100% the whole time (svchost.exe), Wi-Fi (at least) appears connected but no site is reached. During this time one can't edit the hosts file since it's locked by DNS Client.

After some time it might calm down and network will work.

On an 11 system not even after clearing up the hosts file, and after multiple restarts the connection won't work again. Retrying a day later it magically worked. Meh.

**Comment by Lateralus138** [comment]
@licaon-kter I use a process unlocker to unlock the hosts file from svchost (at least to update my hosts). There are several unlockers out there (I use IOBits).

**Comment by licaon-kter** [comment]
Hostman app does warn about this issue, also DNS Client is not needed unless one uses ipsec vpns and such, if net one might be able to disable it altogether. 

Hostman has that reduction function, list up to 9 hosts on a line, that might help too.

After the inital wait, all the restarts went fine and fast. Then again... I didn't flush the cache ;)
