### ISSUE TITLE
Blacklist: ads.phonepe.com

### ISSUE THREAD

**Issue by tillcash** [StevenBlack/hosts#1479]
ads.phonepe.com

**Comment by StevenBlack** [comment]
Hi @tillcash thank you for this.  We are mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).


Closing.
