### ISSUE TITLE
HTTP Error 403: Forbidden for adaway.org

### ISSUE THREAD

**Issue by cryzed** [StevenBlack/hosts#148]
You might want to consider adjusting the User-Agent (since it works with a browser) and not swallowing the complete exception potentially thrown in `getFileByUrl`. You can either catch the exception like this

```python
#[...]
except Exception as exception:
    print(exception)
```

or use `traceback.print_exc()` to print the entire traceback without aborting the script.

**Comment by FadeMind** [comment]
See: https://github.com/StevenBlack/hosts/pull/152

**Comment by cryzed** [comment]
@FadeMind thanks.
