### ISSUE TITLE
Reddit - #947 - clarification?

### ISSUE THREAD

**Issue by RanTrycl** [StevenBlack/hosts#1481]
I just now installed this so not familiar with how it works really.

I installed "social" extension and whitelisted reddit but reddit is still blocked. Is it not possible to use "social" and whitelist reddit?

Thanks for the help.

**Comment by dnmTX** [comment]
@RanTrycl  the intent of the **social extension** is to block everything related to any particular social network listed inside.
It's more like Parenting Control and less/none like filtering the bad stuff.

**Comment by RanTrycl** [comment]
Thanks a lot for the reply. Hmm, how is this setup for avoiding being "tracked around the web" by certain social networks then? Would the base host/non-extension blocks work at all for that?

**Comment by dnmTX** [comment]
Well there is no **guarantee** but yeah the base is compiled from several list sources that we know are very active and "fighting the good fight" every day.
Just FYI,any of the extensions listed here are meant to completely block and not filter.

**Comment by RanTrycl** [comment]
Very helpful, I understand a little better now, thanks!
