### ISSUE TITLE
Using new rules link

### ISSUE THREAD

**Issue by mandraid** [StevenBlack/hosts#1482]
I recently switched from using firebog.net's non-crossed list, to their tick list.  I noticed that a lot of the domains were never updated (to be allowed).  Is there a way to update the DB?  I am running this on my pi-hole.

**Comment by StevenBlack** [comment]
Hello @mandraid thank you for your question.

I'm having difficulty understanding why you posted it here.  It's about two different categories of things, mostly unrelated to what we do here.  Firebog is definitely unrelated.  Pi-Hole is downstream from here.  What *DB* are you talking about here?  Pi-Hole's?  That's my best guess: you're asking us for instructions on how to refresh Pi-Hole's data.

If so, [this is where your question belongs](https://github.com/pi-hole/pi-hole).

Closing.
