### ISSUE TITLE
js.gleam.io

### ISSUE THREAD

**Issue by Bertaz** [StevenBlack/hosts#1483]
Any reason why js.gleam.io is in the list?
With it blocked, gleam.io (a legit site for giveaways) doesn't load some images and load a broken homepage

**Comment by StevenBlack** [comment]
Hi @Bertaz thank you for this question.

The `js.gleam.io` domain comes to us via AdAway, one pf our sources.  @jawz101 can you please have a look?

@Bertaz you should be aware, there is no such thing as a "legit" site here.  The only thing that matters is what they deliver, behind the obvious UI and so-called mission.  If they are a vector for adware, surveillance, or malware, they get listed.

**Comment by dnmTX** [comment]
`*.gleam.io` is present in two other lists that i'm using which tells me that is far from so called **legit**:
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
and
https://gitlab.com/quidsup/notrack-blocklists/-/raw/master/notrack-blocklist.txt

**Comment by dnmTX** [comment]
bump @jawz101

**Comment by jawz101** [comment]
I'm still checking but likely not removing it.

**Comment by StevenBlack** [comment]
Thanks everybody.

Sorry @Bertaz.

Closing.

**Comment by Lateralus138** [comment]
@jawz101 I'm a grown up (at least by age) and I most certainly do want to sign up for *legit* contests 😋

**Comment by jawz101** [comment]
@Lateralus138 judging by the username we're about the same age B)

**Comment by Lateralus138** [comment]
I'm 43
