### ISSUE TITLE
A few new domains from the website klikponudba.com

### ISSUE THREAD

**Issue by betterwebleon** [StevenBlack/hosts#1490]
Hello,

there are some suspicious 3rd-party requests on the website `klikponudba.com` coming from the various domains, which might be relevant for adding them to hosts, such as:

- boostercentral.com
- boostifytheme.com
- cdn.codeblackbelt.com
- cdn.ghostmonitor.com
- cdn.judge.me
- cdn.pushowl.com
- cdn-spurit.com
- d1u9wuqimc88kc.cloudfront.net
- dashboard.wheelio-app.com
- disco-flipclock.netlify.app
- easygdpr.b-cdn.net
- monorail-edge.shopifysvc.com
- multifbpixels.website
- sp-seller.webkul.com
- sr-cdn.azureedge.net
- sy.salesmanago.pl
- wheelioapp.azureedge.net
- window-shoppers.azurewebsites.net

Related discussion: https://github.com/badmojr/1Hosts/issues/59

**Comment by StevenBlack** [comment]
Hello @betterwebleon thank you for this.

I'm going to pass on these.  Primary reason is, to add these to my personal ad-hoc list, I need the ability to curate these out someday, as appropriate.  The assertion that these are "*suspicious 3rd-party requests*" doesn't give me any insight.  I won't list a site unless I can see a tangible, actionable reason.

Thank you for the suggestion, though.  Perhaps one of our [curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant) would take these?

**Comment by betterwebleon** [comment]
Thank you for suggestion! 👍
