### ISSUE TITLE
My list of hosts

### ISSUE THREAD

**Issue by shreyasminocha** [StevenBlack/hosts#1491]
I found most of these through uMatrix. I usually avoid adding hosts that are already blocked in the other lists I use with uMatrix and uBO. I also usually avoid adding root domains, especially when they aren't serving scripts/images on third-party sites.

It isn't particularly large at the moment and it's also very new (I only recently realized I was finding enough of these to warrant making a separate list), but I'll try to consistently update it—time will tell.

- [List](https://raw.githubusercontent.com/shreyasminocha/shady-hosts/main/hosts)
- [Repository](https://github.com/shreyasminocha/shady-hosts) — [History](https://github.com/shreyasminocha/shady-hosts/commits/main)
- [CC0-1.0](https://l.shreyasminocha.me/CC0-1.0/2020-)

```sh
❯ ghosts -c https://raw.githubusercontent.com/shreyasminocha/shady-hosts/main/hosts

----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 58,750
Bytes: 1.8 MB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/shreyasminocha/shady-hosts/main/hosts
Domains: 135
Bytes: 4.0 kB
----------------------------------------
Intersection: 27 domains
```

Edit: moved repository and list to GitHub on dnmTX's suggestion.

**Comment by StevenBlack** [comment]
Hi Shreyas @shreyasminocha thank you for this.

Normally I require a notable track record of list curation before accepting and integrating a new source.

I've looked at some of your other projects, and I'm happy to include your list, provided you continue to actively update and curate it.  In particular, a good list isn't an add-only bucket.  Active curation means, keeping it pertinent and compact.

If you create a PR that includes a new folder with an `update.json` file like those found [in the data folder here](https://github.com/StevenBlack/hosts/tree/master/data), I'll merge it into a subsequent release.

Thanks Shreyas!  Stay awesome!

**Comment by ThomasSchmidt1** [comment]
Can you please remove the shady list from your steven-black-list??
The shady list is too aggresive. It blocks the domain cdn.privacy-mgmt.com. Without that domain it's impossible to access the important german news portal spiegel.de

**Comment by StevenBlack** [comment]
Hi Shreya @shreyasminocha I notice the shady-hosts blocks rollbar, too.

We've ]discussed Rollbar many times before here](https://github.com/StevenBlack/hosts/search?q=rollbar&type=issues).  We've concluded that Rollbar is OK as a significant developer tool.  Sentry is another example in this category.  Crashlytics, on the other hand, not OK 🙄   It just, depends.  We've drawn this line in the past and I'm happy with it.

**Comment by StevenBlack** [comment]
Thanks for your input Thomas @ThomasSchmidt1.  That will be rectified in the next release, imminently.
