### ISSUE TITLE
Blocking api.nuget.org breaks Visual Studio and dotnet CLI

### ISSUE THREAD

**Issue by MrCSharp22** [StevenBlack/hosts#1493]
Hi, I just noticed that the api.nuget.org endpoint is being blocked by this list. This breaks nuget features in Visual Studio and the dotnet cli which is needed for dotnet code-bases.

I'm currently working around it by adding the above endpoint to a whitelist but I'm sure others are running into error messages due to it.

Thanks

**Comment by StevenBlack** [comment]
Hello Sir @MrCSharp22 we don't block `api.nuget.org` domain.  Even just the string `nuget` appears nowhere in our lists.

Closing.

**Comment by MrCSharp22** [comment]
Thanks for the reply @StevenBlack . Just want to add a bit more details to this. I checked the logs again on nextdns and it seems that api.nuget.org is resolving to another domain which is being reported as blocked by this list. 
![image](https://user-images.githubusercontent.com/8640943/103451320-83282e80-4d16-11eb-872b-2e96fc8bfa00.png)

I checked and vo.msecnd.net is on the list under the shady-hosts sections.

I'm not sure what the next steps are.

Thank you

**Comment by dnmTX** [comment]
![VirusTotal](https://user-images.githubusercontent.com/34774426/103451533-a4dbd400-4c8a-11eb-8134-2a39b2eb6d55.png)

**Comment by dnmTX** [comment]
So....let's summarize: `api.nuget.org`(not listed here) is being blocked because it's CNAME `az320820.vo.msecnd.net`(not listed here either) is being blocked because there is a.....listed domains here `vo.msecnd.net` which apparently falls under the wildcard so everything that ends like this goes under the knife.
What a **"nice"** app is NextDNS.....**NOT** 👎 👎 👎 

![to cs](https://user-images.githubusercontent.com/34774426/103451893-246ba200-4c8f-11eb-923e-1d0c00181cd7.png)

**Comment by StevenBlack** [comment]
I'm inclined to agree Dan @dnmTX.

Upstream we can deal.

Downstream, wtf, not our bug.

C22 @MrCSharp22 this isn't dissing you.  I really appreciate your notice here.

**Comment by dnmTX** [comment]
On the other hand Steve @StevenBlack (let's look on both sides of the aisle for once) the domain `vo.msecnd.net` in it's form it's absolutelly useless(doesn't resolve,no IP etc.) unless you using it for wildcard blocking to block all those instantly generated domains aka `az320820.vo.msecnd.net` and so on. 
So i'm more then certain that  @shreyasminocha is using either NextDNS or some other resolver which does wildcard blocking on his end and now he's passing all those domain to you which are useless and kind of selfish of him.
So regardless that domain needs to go and who know how many more are on that list.
