### ISSUE TITLE
The recently added "shady-hosts" section interfere with IMDb iOS app

### ISSUE THREAD

**Issue by gjactat** [StevenBlack/hosts#1494]
Hello,

First of all, thanks for your amazing work !
Today, I noticed that the IMDb app complained about unreachable hosts (see snaphsot below). Using Fiddler, I noticed that the IMDb app makes use of the following GraphQL endpoint: 

`https://graphql.prod.api.imdb.a2z.com`

The recently added "shady-hosts" section seems to block all subdomains of "a2z.com" (line 45911, I'm no expert in filtering syntax but this is what I assumed), which is perhaps a bit too large ? I guess other services will rely on similar APIs to provide content.

From what I've seen, this graphql call provides the movies pitch (it remains empty when filtering is on).

Thanks for your attention.

![image](https://user-images.githubusercontent.com/1826064/103447248-d489dc80-4c88-11eb-9336-55cc5ba34d53.png)

**Comment by llacb47** [comment]
@shreyasminocha

**Comment by StevenBlack** [comment]
Hello Guillaume @gjactat.  We don't block `graphql.prod.api.imdb.a2z.com`.

> The recently added "shady-hosts" section seems to block all subdomains of "a2z.com"

This is not how hosts files function.  There are no wildcards with hosts files.  Domains are blocked explicitly, or not at all.

**Comment by dnmTX** [comment]
> This is not how hosts files function. There are no wildcards with hosts files. Domains are blocked explicitly, or not at all.

NextDNS proved us all wrong on that instance....unfortunately 😞

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX so the problem is downstream 🙄

So Shreyas @shreyasminocha listing the root `a2z.com` domain is probably a little too rude.  What do you think?

I should mention a subtle point @shreyasminocha — we typically avoid taking down company root domains unless they use the root domain as an ad/malware/tracking vector.  If it were otherwise, we'd block the `google.com` root domain and that would be absurd.  So we tread lightly on root domains unless we have a very clear reason.  Good?

**Comment by shreyasminocha** [comment]
> So Shreyas @shreyasminocha listing the root a2z.com domain is probably a little too rude. What do you think?

True, fixed. Will keep in mind. Sorry for the inconvenience OP.

**Comment by dnmTX** [comment]
@shreyasminocha would advise anything you have on that list that you used for wildcard blocking to  be removed.
Also if you can recall any listed CNAME's.
Much less inconvenience for all of us to be honest. Thank you 👍

**Comment by gjactat** [comment]
The latest Release (3.3.1) fixed the issue.
Thanks to all of you !
