### ISSUE TITLE
cdn.paddle.com 

### ISSUE THREAD

**Issue by sectary-want-holly** [StevenBlack/hosts#1495]
$subject blocks access to https://play.pocketcasts.com/podcasts. Please could it be whitelisted in the master list unless there is very good reason for it to be present?

**Comment by dnmTX** [comment]
another one for @shreyasminocha 😉

**Comment by StevenBlack** [comment]
Yeah, Shreya @shreyasminocha we can't block Paddle.  Several popular Mac apps fulfill through Paddle, including Pocket Casts, which is the podcatcher I use.  

Thank you for signalling this one @sectary-want-holly, good catch..

**Comment by sectary-want-holly** [comment]
Many thanks!
