### ISSUE TITLE
files.catbox.moe

### ISSUE THREAD

**Issue by NO-ob** [StevenBlack/hosts#1496]
Would it be possible to get files.catbox.moe removed from the list? I'm not sure why it would be on the list in the first place

**Comment by StevenBlack** [comment]
This is upstream.  The `files.catbox.moe` comes to us via [Digitalside Threat Intel](https://github.com/davidonzo/Threat-Intel) and you can make a case for this [here](https://github.com/davidonzo/Threat-Intel/issues) on their issues page.

cc @DavidDonzo Thanks David.

**Comment by llacb47** [comment]
@davidonzo

**Comment by NO-ob** [comment]
Okay i'll make an issue over there thankyou

**Comment by davidonzo** [comment]
3 malicious url detected in the last week.
Anyway, I can remove the domain withelisting it, considering the main site pourpose.

Next run the domain will be removed from the domain list, but related malicious urls will be shared in the urls list.
