### ISSUE TITLE
(whitelist) tv.sohu.com

### ISSUE THREAD

**Issue by Lonelier** [StevenBlack/hosts#1499]
tv.sohu.com is the official URL of Sohu TV, not a malicious domain name, please add it to the whitelist.
Thank you

**Comment by shreyasminocha** [comment]
This one is from https://someonewhocares.org/hosts under the <code>#\<<a href="https://en.wikipedia.org/wiki/Evercookie">evercookies</a>-sites\></code> section.

**Comment by StevenBlack** [comment]
Thank you for this @Lonelier.  Please submit this issue to Dan Pollock at hosts@someonewhocares.org, because this is where `tv.sohu.com` originates.  Dan's great, you can count on him to make the correct assessment here.

Closing.
