### ISSUE TITLE
this hosts file prevents pgp4win from working

### ISSUE THREAD

**Issue by jsBlackBelt** [StevenBlack/hosts#15]
After applying this to my hosts file, pgp4win stopped working. Kleopatra won't start.
After removing this from hosts file, pgp4win starts working again as normal.

**Comment by StevenBlack** [comment]
Thanks @jsBlackBelt.

Can you please tell me what lines in the hosts file you removed?

The strings `pgp4win` and `kleopatra` don't appear anywhere in the hosts file, and you give no other clues.

**Comment by jsBlackBelt** [comment]
Hi @StevenBlack ,

Well, I removed none.. 
When I applied the entire thing into my hosts file, `kleopatra` stopped working. When I removed the entire thing it worked again.
I have no idea what blocks it, I would have mentioned it if I had :(
I couldn't find out what blocks it either...

I wish I could give you more info, unfortunately this is all I have

**Comment by StevenBlack** [comment]
Closing.

**Comment by espress0** [comment]
@StevenBlack

Please remove this line "0.0.0.0 localhost", or fix it to "127.0.0.1 localhost".
This will do the trick.
