### ISSUE TITLE
Stream error (entry: carniferou.club)

### ISSUE THREAD

**Issue by ArmynC** [StevenBlack/hosts#1501]
**Hey!** I got a tip that `liveonscore.tv`'s videos aren't working. After a little check, it seems so.

![Capture](https://user-images.githubusercontent.com/16375271/104090974-03084880-5283-11eb-9802-c24362cf6a0b.PNG)

I tracked every log process and finally, it seems that `@@||cdn.carniferou.club^` entry fixed it. I think that that respective rule should be deleted (per #1354). Thanks! :blush:

**Comment by StevenBlack** [comment]
Hi Armyn @ArmynC  when I go to `liveonscore.tv` — I'm not linking that — I get a cluster of popups and other such scumbaggery.

This is precisely the shit we block here.

Closing.
