### ISSUE TITLE
MEGOGO TV

### ISSUE THREAD

**Issue by asgirich** [StevenBlack/hosts#1505]
Hi. When trying to view the TV channels offered by MEGOGO.NET, the page won't load.
https://megogo.net/en
for example https://megogo.net/en/tv/channels/3875741-history-hd-online.html

Whitelisting et.megogo.net, megogo.net and so don't help.

Thank you.

**Comment by shreyasminocha** [comment]
Does whitelisting `vcdn.biz` fix it? The example page only makes requests to *subdomains* of `vcdn.biz` though, so maybe OP is using NextDNS.

**Comment by asgirich** [comment]
no, don't help

**Comment by dnmTX** [comment]
@asgirich all the `.css` is coming from `*.vcdn.biz` subdomains. I'm just reconfirming that.
In addition you can whitelist `gemius.pl` and see if it'll help.

**Comment by StevenBlack** [comment]
Hi @jawz101, what are your feelings on `vcdn.biz`?

Thanks for the inquiry  AHyrych @asgirich.

As for the domain `gemius.pl` — it is heavily flagged by SomeoneWhoCares, and AdAway to a lesser extent.

```
data/adaway.org/hosts
5484:# [gemius.pl]
5485:127.0.0.1 gemius.pl
5486:127.0.0.1 gatr.hit.gemius.pl
5487:127.0.0.1 googlecm.hit.gemius.pl

data/someonewhocares.org/hosts
345:#0.0.0.0 pro.hit.gemius.pl	# May interfere with some video sites
447:0.0.0.0 arbo.hit.gemius.pl
915:0.0.0.0 gapl.hit.gemius.pl
966:0.0.0.0 idm.hit.gemius.pl
1392:0.0.0.0 seznam.hit.gemius.pl
1428:0.0.0.0 st1.hit.gemius.pl
4492:0.0.0.0 24ratownik.hit.gemius.pl
5115:0.0.0.0 adbg.hit.gemius.pl
5134:0.0.0.0 adclick.hit.gemius.pl
8569:0.0.0.0 gahu.hit.gemius.pl
8579:0.0.0.0 gapl.hit.gemius.pl
8584:0.0.0.0 gazeta.hit.gemius.pl
8651:0.0.0.0 gdeee.hit.gemius.pl
8652:0.0.0.0 gdelt.hit.gemius.pl
8653:0.0.0.0 gdelv.hit.gemius.pl
8660:0.0.0.0 gemius.pl
8701:0.0.0.0 ghmtr.hit.gemius.pl
8753:0.0.0.0 go2.hit.gemius.pl
8760:0.0.0.0 goldbach.hit.gemius.pl
8788:0.0.0.0 gspro.hit.gemius.pl
8925:0.0.0.0 huiwiw.hit.gemius.pl
9436:0.0.0.0 ls.hit.gemius.pl
10034:0.0.0.0 onet.hit.gemius.pl
10345:0.0.0.0 pro.hit.gemius.pl
10660:0.0.0.0 rp.hit.gemius.pl
10823:0.0.0.0 sec.hit.gemius.pl
10971:0.0.0.0 si.hit.gemius.pl
11539:0.0.0.0 tvn.hit.gemius.pl
```

**Comment by dnmTX** [comment]
> As for the domain gemius.pl — it is heavily flagged by SomeoneWhoCares, and AdAway to a lesser extent.

Agreed 👍 It was just proposal on my end(to see if it'll help with the issue on hand here) and not in any way  plea for removal.

**Comment by jawz101** [comment]
removed the vcdn.biz one.  It[ doesn't even look like Android apps](https://www.virustotal.com/gui/domain/vcdn.biz/relations) communicate with it.  I'll look at the gemius stuff later

**Comment by asgirich** [comment]
megogo.net site now open like normal site, without bugs, but tv channels  don't work still.
i trying research myself and find this domens:
et.megogo.net
meta.vcdn.biz
megogo.net
ad.turn.com
vs46.vcdn.biz
vs823.vcdn.biz
vs826.vcdn.biz
vs829.vcdn.biz
vs830.vcdn.biz
vs836.vcdn.biz
vs837.vcdn.biz
vs844.vcdn.biz
vs850.vcdn.biz
s1.vcdn.biz
s2.vcdn.biz
s4.vcdn.biz
s5.vcdn.biz
s6.vcdn.biz
s7.vcdn.biz
s9.vcdn.biz
www.google-analytics.com
api-interactive.megogo.net
edge-interactive.megogo.net
ls.hit.gemius.pl
dont now if it right
and its not easy for me to debug, because i cant to use whitelist functionality (asuswrt-merlin/unbound/ad-block)

**Comment by dnmTX** [comment]
@asgirich judging by this entry:
![hosts](https://user-images.githubusercontent.com/34774426/104773667-06944780-573b-11eb-8b50-d5568df9dbcb.png)
and also the discussion [here](https://github.com/FadeMind/hosts.extras/issues/22) you need to find a way to whitelist `ls.hit.gemius.pl` on your end and @jawz101 **do not remove any of it in your list** as it's proven to be a bad actor.

**Comment by asgirich** [comment]
its because, go to SSH, then: 1. unbound_manager advanced. 2. Advanced Tools Menu type "3". 3. type ea = Edit Ad Block Allowlist and in nano editor add
gemius.pl
ls.hit.gemius.pl
et.megogo.net
meta.vcdn.biz
megogo.net
ad.turn.com
vs46.vcdn.biz
vs823.vcdn.biz
vs826.vcdn.biz
vs829.vcdn.biz
vs830.vcdn.biz
vs836.vcdn.biz
vs837.vcdn.biz
vs844.vcdn.biz
vs850.vcdn.biz
www.google-analytics.com
api-interactive.megogo.net
edge-interactive.megogo.net
s1.vcdn.biz
s2.vcdn.biz
s4.vcdn.biz
s5.vcdn.biz
s6.vcdn.biz
s7.vcdn.biz
s9.vcdn.biz
save and megogo dont work,
THEN in unbound_manager ecb=Config-BlockSites and remove https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts and add this ones
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
https://someonewhocares.org/hosts/zero/hosts
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
and megogo work OK!

**Comment by asgirich** [comment]
i don't understand) to debug ad-blocking, install today https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts again, and megogo work, reboot router and megogo work again

tanx a lot, guys!!!))) its cool!

**Comment by asgirich** [comment]
its seams it work, adding vcdn.biz to whitelist is helping: ea = Edit Block Allowlist, and then check it out WinSCP /opt/share/unbound/configs - allowhost
thanx a lot, guys!

**Comment by StevenBlack** [comment]
So... close this?  We are good here?

**Comment by asgirich** [comment]
yes, thanks for your help, greatly appreciated!
