### ISSUE TITLE
neos.com.pl

### ISSUE THREAD

**Issue by patryk5717** [StevenBlack/hosts#1506]
Why was neos.com.pl blocked by you because it is not any source of advertising or other scam?

**Comment by StevenBlack** [comment]
Hi Patrick @patryk5717  thank you for raising this.

The `neos.com.pl` comes to us via [KADhosts](https://kadantiscam.netlify.app/), a very reputable and responsive outfit.  

data/KADhosts/hosts
6371:0.0.0.0 neos.com.pl
9554:0.0.0.0 www.neos.com.pl

Please raise this question [here](https://github.com/PolishFiltersTeam/KADhosts/issues). You can even inquire in Polish 😉  If this is in error, it will get fixed promptly.
