### ISSUE TITLE
German lottery domains (gambling)

### ISSUE THREAD

**Issue by crazyyzarc** [StevenBlack/hosts#1507]
Providers belonging to the German Lotto and Totoblock Association that are not yet blocked:

1. https://www.lotto-bw.de/
2. https://www.lotto-bayern.de/
3. https://www.lotto-brandenburg.de/
4. https://www.lotto-bremen.de/
5. https://www.lotto-hh.de/
6. https://www.lotto-hessen.de/
7. https://www.lottomv.de/
8. https://www.lotto-niedersachsen.de/
9. https://www.lotto-rlp.de/
10. https://www.saartoto.de/
11. https://www.sachsenlotto.de/
12. https://www.lottosachsenanhalt.de/

**Comment by StevenBlack** [comment]
Thank you @crazyyzarc.

Ping @sinfonietta.

**Comment by StevenBlack** [comment]
Thanks @sinfonietta.

@crazyyzarc these will be bundled in the next release.

Closing.
