### ISSUE TITLE
Ads on Xhamster.com Mobile version

### ISSUE THREAD

**Issue by Jpersh27** [StevenBlack/hosts#1509]
Seeing Several Intrusive Banner Ads on Xhamster.com that are on the Mobile Version of the website. Not on the Full Site version.

1.) First Live Girls Banner- Located both on the homepage and after you click on any random video.

2.) Second Live Girls Banner- Located Above Categories option and Show more related Video option after clicking on any random video.

3.) Third Live Girls Banner- Located below any clicked on video and at the bottom of the video page you are on.

The Mobile version of the site is becoming increasingly intrusive with these banner Ads. Mobile versions of sites like pornhub and xvideos are filtered well and the majority of the Ads are block on those popular sites.

I'm currently using IVPN on my Android Device and they have a Anti tracker feature curated by this host list. It updates daily and fetches the most recent version made available here on GitHub. 

They instructed me to open a support case on GitHub to see if I can get these specific Ads blocked on the website I provide which is the "Mobile version of the website xhamster.com"

**Comment by dnmTX** [comment]
@Jpersh27 there are alredy several `trafficstars.com` domains listed here.
You need to analyze on your end which (sub)domains are involved and post them here for feature blocking.

**Comment by Jpersh27** [comment]
@dnmTX Can I do it on Mobile or do I have to analyze it on a computer? What sub domains are my looking for? And last question how do I know if I got the right domain or not?

**Comment by Jpersh27** [comment]
@dnmTX 
Is this what your looking for exactly? Or something else?

https://eu-adsrv.rtbsuperhub.com/click/?subPublisher=banner:xhamster.com&zone=banner:xhamster.com&adformat=banner&auctionid=06fca419-29c0-4e0f-ba94-ba7ab10b01e0&uniqueid=2ec2c3a9513c9efee38c1289cdac10d7&name=trafficstars_banner_300x100_usa_mobile_&campaign=trafficstars-banner-android:xhamster.com&width=300&height=100&newservice=true&cmsid=landing--mlp8000--landing--da6016&tpcampid=3c84f5e5-06b7-4ec4-a58c-da46f112c2b6&imp_tagid=84&ba=f974326f-f578-4afd-901c-979c16433e72&uid=429f3597-022e-4431-bddc-b2c7f888c7dc&campaign_lp=1:landing--mlp8000--landing--da6016&product=iflirtsweb&bpath=4cfec918-0404-43be-a41c-4abe5eb2f98f:gif

**Comment by dnmTX** [comment]
Sure,it's a start but how did you found out that it's a TrafficStars related?
**ping Steven @StevenBlack** for consideration:
`0.0.0.0 eu-adsrv-cached.rtbsuperhub.com`
`0.0.0.0 us-east-adsrv.rtbsuperhub.com`
`0.0.0.0 rtb-api-aws.rtbsuperhub.com`
`0.0.0.0 rtb-api.rtbsuperhub.com`
`0.0.0.0 gl-adsrv.rtbsuperhub.com`
`0.0.0.0 eu-west-endpoint.rtbsuperhub.com`
`0.0.0.0 eu-am5-endpoint.rtbsuperhub.com`
`0.0.0.0 eu-adsrv-direct.rtbsuperhub.com`
`0.0.0.0 us-adsrv.rtbsuperhub.com`

P.S. Just in case **ping @jawz101** to help if desire 😉

**Comment by Jpersh27** [comment]
@StevenBlack @jawz101 and @dnmTX  

Here is a list I was able to compile:

0.0.0.0 lcdn.tsyndicate.com/sdk/v1/ad.js
0.0.0.0 lcdn.tsyndicate.com/sdk/v1/bi2.js
0.0.0.0 collector.xhamster.com
0.0.0.0 cdn.trafficstars.com
0.0.0.0 collector.xhamster.com
0.0.0.0 thumb-user.xhcdn.com
0.0.0.0 www.googletagmanager.com
0.0.0.0 www.google-analytics.com
0.0.0.0 19-9.b.cdn13.com
0.0.0.0 video.xhcdn.com
0.0.0.0 collector.xhamster.com
0.0.0.0 static-lvlt.xhcdn.com/xh-mobile/css/critical/v7f7c0e01.index-video.css
0.0.0.0 static-lvlt.xhcdn.com/xh-mobile/css/critical/v7f7c0e01.index-video.css

If its possible would someone be able to please look into the specific ads on the mobile version of the website? 

The mobile version is riddled with ads and this is one of the few websites I use frequently, but the ads are becoming a nuisance.  

I don't have any problems on either pornhub.com or xvideos.com while using the host file lists. I don't not know why not a single Ad is blocked on the mobile version of xhamster.com though its strange being all the three website are some of the most popular websites in there category.

If necessary I could provide screenshots of the ads that are appearing while on my android device and on the mobile version of the website.

**Comment by dnmTX** [comment]
**ok to add/exist in other blocklists:**
`0.0.0.0 lcdn.tsyndicate.com`
`0.0.0.0 collector.xhamster.com`
`0.0.0.0 video.xhcdn.com`

**already listed here:**
`0.0.0.0 cdn.trafficstars.com`
`0.0.0.0 www.googletagmanager.com`
`0.0.0.0 www.google-analytics.com`

**not related/need more info/likely broken website(s):**
`19-9.b.cdn13.com`
`thumb-user.xhcdn.com`
`static-lvlt.xhcdn.com`

**Comment by Jpersh27** [comment]
@dnmTX  So from what I'm gathering: 

-The first 3 listed can be added to the host list?

--The second 3 are already listed/on the host list. (No change needed)

-- The last 3 are broken links/not related to the website? (Nothing to add)

**Comment by dnmTX** [comment]
> @dnmTX So from what I'm gathering:
-The first 3 listed can be added to the hosts list. (Will be added once approved)?
--The second 3 are already listed/on the host list. (No change needed)

**CORRECT**

> -- The last 3 are broken links/not related to the website? (Nothing to add)

the third one provides the visual elemnts to the webplayer aka `.css`. 
If blocked you won't be able to to enjoy the pretty ladies there 😄 
Second one is very likely another visual elemnt so altogether **not harmful/not related to the problem in hand**
First one needs more info/research or you need to provide the entire link that the actual domain is associated with 
in order to be analyzed properly.

**Comment by Jpersh27** [comment]
@dnmTX  Thank you for your reply again and for explaining everything in detail. 

I was able to gather a few other links. I will list them below again:

0.0.0.0 tsyndicate.com/do2/click
0.0.0.0 tsyndicate.com
0.0.0.0 eu-adsrv.rtbsuperhub.com
0.0.0.0 www.imglnke.com
0.0.0.0 www.bangcreatives.com
0.0.0.0 optnx.com/cimp.php
0.0.0.0 optnx.com
0.0.0.0 thumb-l3.flixcdn.com

**Comment by dnmTX** [comment]
@Jpersh27 you need to start blocking those domains on your end and see if something breaks and post the results here.
I'm not able to do that on mobile and by the look of it @jawz101 is not available to look in to it and he's the mobile guru here so either wait or do some testing by yourself.

**Comment by Jpersh27** [comment]
@dnmTX 
- If you read my first comment I posted when creating the issue you'd have a better understanding.

**Comment by jawz101** [comment]
I just got a notification on this.  If someone wants to give me specific domains to address let me know.  I'm not too interested in researching it myself.

**Comment by Jpersh27** [comment]
@jawz101 What specific entries would you like me figure out and specify for you to address the Ads going unblocked on this domain?

@jawz101 There are several sub domains that Iisted above in the comments on this issue I raised. 

However @dnmTX believes I don't know anything about this host list and that I'm just a bot or just spamming this forum.......

Also @dnmTX didn't fully comprehend and read the first comment I made that explained the issue surrounding the Mobile version of the domain.

@jawz101 I researched the ads and determined the sub domains they were coming from and listed them above in the comments if you would like read over them.

@jawz101 If you don't have the time to help me or don't desire too please tell me.
 
I don't need another unhelpful individual posting unhelpful comments as @dnmTX eventually did.......

**Comment by StevenBlack** [comment]
I'm not liking where this is going.  

@Jpersh27 We're mostly an aggregator here.  Please bring this issue to @sinfonietta who is one of our porn extension curators.  Here's the link:  https://github.com/Sinfonietta/hostfiles/issues

Closing.
