### ISSUE TITLE
formatting error that needs to be looked at

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#1511]
Steve @StevenBlack to your attention:

![hosts](https://user-images.githubusercontent.com/34774426/105621731-4957be80-5dd0-11eb-8428-a9be87bfb327.png)
&
![hosts1](https://user-images.githubusercontent.com/34774426/105623895-018e6280-5de3-11eb-9522-cdfc610ce18d.png)

Also for some reason the latest 3.3.7 release is still not added to the list. Does it need more time or...?

You can close the issue when done. Thank you 👍

**Comment by funilrys** [comment]
I'm not sure those are erroneous @dnmTX 🤔  But maybe I'm wrong...

They all have `A` and `AAAA` records.

**Comment by lightswitch05** [comment]
I tons of issues like that in my list. They are wildcard DNS records- so literally any subdomain query will return valid results.

**Comment by lightswitch05** [comment]
Certificate transparency logs can sometimes be useful to help discover actually used subdomains vs. whatever crazy results you might get back from VirusTotal. Here is an example: https://crt.sh/?q=%25.beeglivesex.com

Only useful if they don't also use wildcard SSL certificates.

**Comment by lightswitch05** [comment]
Common Crawl is another good source that might have a little less random noise in it: http://index.commoncrawl.org/CC-MAIN-2020-50-index?url=*.beeglivesex.com&output=json

**Comment by dnmTX** [comment]
> I'm not sure those are erroneous @dnmTX 🤔 But maybe I'm wrong...

Apparently you are not,but it's a first for me for sure. Further research on `*.hpyrdr.com` showed that it's distributed by 
104.18.27.92 IP and there is even `127.0.0.1.hpyrdr.com` active domain in play(wtf? 🤔 )
The strange thing is that i couldn't find when those domains were committed here.
I guess it's a false alarm on my end so i'm closing this.
Nevertheless thanks for the input guys @lightswitch05 & @funilrys 👍 

P.S. Just reminder for Steve @StevenBlack to check why the latest 3.3.7 release is not in the list yet.

**Comment by StevenBlack** [comment]
> check why the latest 3.3.7 release is not in the list yet.

What does this mean, Dan @dnmTX?   The 3.3.7 release is not in what list?

**Comment by dnmTX** [comment]
Steve @StevenBlack when i use:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts  to check if the latest release is committed there,
in our case here is all those `*.livejasmin.com` domains they're not present.
Is there different link or something cause that's what i usually use to update my end?

**Comment by StevenBlack** [comment]
Good catch Dan @dnmTX!  I must have run `release-it` but didn't run `makeHosts.py` first.

Fixing that now.

**Comment by dnmTX** [comment]
Alright 😄. At least i was right about one thing. Thank you Steve @StevenBlack 👍
