### ISSUE TITLE
Site to be added under social

### ISSUE THREAD

**Issue by crAckZ0p** [StevenBlack/hosts#1512]
Good afternoon,
Sorry I don't normally use GitHub but a new site should be added under social. 

0.0.0.0 datememe.com

This is also listed as a chrome extension. I normally keep my network locked down but my daughter who is six years old was able to use this from her school issued Chromebook. One click sign up (daughters school login) added her real name, location, school email as well as her picture.

**Comment by dnmTX** [comment]
That is very disturbing,concidering that it's a **dating site** (aka 18+ or older !!!!) and their front page looks more like
coloring book for kids then anything else. So...let's lock down this for good:
`0.0.0.0 www.datememe.com`
`0.0.0.0 admin.datememe.com`
`0.0.0.0 blog.datememe.com`
`0.0.0.0 bn.datememe.com`
`0.0.0.0 c1.datememe.com`
`0.0.0.0 c2.datememe.com`
`0.0.0.0 c3.datememe.com`
`0.0.0.0 datememe.com`
`0.0.0.0 de.datememe.com`
`0.0.0.0 en.datememe.com`
`0.0.0.0 es.datememe.com`
`0.0.0.0 fr.datememe.com`
`0.0.0.0 hi.datememe.com`
`0.0.0.0 id.datememe.com`
`0.0.0.0 ja.datememe.com`
`0.0.0.0 jv.datememe.com`
`0.0.0.0 ko.datememe.com`
`0.0.0.0 pt.datememe.com`
`0.0.0.0 ru.datememe.com`
`0.0.0.0 th.datememe.com`
`0.0.0.0 vi.datememe.com`
`0.0.0.0 zh-cn.datememe.com`

**Comment by shreyasminocha** [comment]
A few more from their certificate:

- `blog.d8.io`
- `d8.io`
- `www.d8.io`

**Comment by StevenBlack** [comment]
Should these go in the default list, I wonder?  Thoughts, Dan @dnmTX and Shreyas @shreyasminocha?

**Comment by dnmTX** [comment]
> Should these go in the default list, I wonder? 

I'd say NO,unless you want to deal with bunch of crybabies(which...in my opinion is inevitable,considering the broad userbase here) and eventually their whole team and CEO poping up here and japing how honest the platform is.

**Comment by dnmTX** [comment]
....but it's...should i say past due to list @Sinfonietta's repo in the front page as the source for blocking social/gambling/porn...sites
😄

**Comment by StevenBlack** [comment]
I know Dan @dnmTX I wrestle with this.

We have 17 different readme in this repo.  @sinfonietta is included in all readme where his lists are included.  None of his lists are included in the default list, which is our homepage.

I'd love to figure a better way to present all this.  GitHub kind of limits what we can do here...

```
alternates/fakenews/readme.md
alternates/fakenews-gambling/readme.md
alternates/fakenews-gambling-porn/readme.md
alternates/fakenews-gambling-porn-social/readme.md
alternates/fakenews-gambling-social/readme.md
alternates/fakenews-porn/readme.md
alternates/fakenews-porn-social/readme.md
alternates/fakenews-social/readme.md
alternates/gambling/readme.md
alternates/gambling-porn/readme.md
alternates/gambling-porn-social/readme.md
alternates/gambling-social/readme.md
alternates/porn/readme.md
alternates/porn-social/readme.md
alternates/social/readme.md
extensions/readme.md
readme.md
```

**Comment by dnmTX** [comment]
Steve @StevenBlack i hear you,or maybe i'm not....complicated i know....
What i meant in my post that his repo is missing here:
![categories](https://user-images.githubusercontent.com/34774426/106307034-71a64980-6224-11eb-996d-a4c514a2ede4.png)

....where everyone is listed and for me personally if i have some concern to open issues i look there for guidance as i assume most of us here do.
Is it possible to list him there,i mean,every other repo is?

**Comment by Sinfonietta** [comment]
Hello @StevenBlack I have added these domains to my social medial list.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta!

Closing.
