### ISSUE TITLE
FP: Oukitel OTA domains

### ISSUE THREAD

**Issue by k03mad** [StevenBlack/hosts#1516]
Found in blocklist some `adups.cn/adups.com` domains, which serve OTA updates for Oukitel phones:

```
0.0.0.0 fota4.adups.cn
0.0.0.0 fota5.adups.cn
0.0.0.0 fota5s.adups.cn
0.0.0.0 fota5t.adups.cn

0.0.0.0 fota5.adups.com
0.0.0.0 fota5db.adups.com
0.0.0.0 fota5p.adups.com
0.0.0.0 fota5s.adups.com
0.0.0.0 fota5t.adups.com
0.0.0.0 fota5tbk.adups.com
```

`fota = Firmware Over-The-Air`

Reported to upstream, but there is no reaction...

refs and proof: https://github.com/AdAway/adaway.github.io/issues/205

**Comment by StevenBlack** [comment]
Thank you for this Kirill @k03mad.

@jawz101 can you please have a look, and advise?  Thank you as always.

**Comment by jawz101** [comment]
looks like I didn't get a notification because I accidentally turned off notifications.

Anyways, at the moment I don't think I'll be removing the entries.  A few years ago Adups made the news for being preinstalled spyware on Chinese Blu phones and others- screen grabbing and other shady stuff.

**Comment by StevenBlack** [comment]
Thanks @jawz101.

Sorry Kirill @k03mad these will stay blocked by our default list.

Closing.
