### ISSUE TITLE
Payusatax.com blocked

### ISSUE THREAD

**Issue by raidenii** [StevenBlack/hosts#1517]
Hi,

Looks like payusatax.com is blocked. Any specific reason for that? It's a legit website listed on irs.gov:

https://www.irs.gov/payments/pay-your-taxes-by-debit-or-credit-card

Thanks.

**Comment by lightswitch05** [comment]
Blocked by @FadeMind 'Risky Hosts' list. Looks like it's been in the list since the beginning - 2016.

**Comment by StevenBlack** [comment]
@raidenii so we're clear, a link from `.gov` means jack. We block tracking here, and `.gov` is, if anything, not admirable in that critical respect.

The whois records for domain `payusatax.com` look sketch.  But the IRS link checks out.

Let's see what T says.

**Comment by FadeMind** [comment]
@StevenBlack @lightswitch05 in these external lists are a lot false positive rules. Thanks for report. Regards
Main source is http://hostsfile.org/hosts.html mirrored and customized in https://github.com/FadeMind/hosts.extras

**Comment by dnmTX** [comment]
@FadeMind since you're here i have a question about `*.2o7.net` domains(maybe @lightswitch05 could pitch in on that too).
Aren't those serve as CNAME(s) only or this is not the case for all of them?

**Comment by FadeMind** [comment]
2o7 dot net is > https://www.wikiwand.com/en/Omniture (by Adobe > https://www.whois.com/whois/2o7.net) mirrored and enhanced in hosts.extras. Your call if you need to blocking these.

**Comment by StevenBlack** [comment]
Thanks everybody.  @raidenii this will be in the next release, coming momentarily.
