### ISSUE TITLE
files.slack.com

### ISSUE THREAD

**Issue by alfaridi** [StevenBlack/hosts#1518]
Is there any valid reason to include `files.slack.com`?

**Comment by shreyasminocha** [comment]
It's from [Threat-Intel](https://github.com/davidonzo/Threat-Intel). @davidonzo

**Comment by alfaridi** [comment]
Uhm, but I believe Slack is widely used by many companies. The `files.slack.com` is a file repository.

**Comment by PeterDaveHello** [comment]
I also noticed this issue yesterday, as @shreyasminocha says, tt's from Threat-Intel, and Threat-Intel is also referenced by another few lists, e.g. [EnergizedProtection](https://github.com/EnergizedProtection/block), so if you are using multiple block lists(I know may users are), the domain might also be blocked by some other block lists.

Issue https://github.com/davidonzo/Threat-Intel/issues/16 was opened earlier, feel free to leave comment if you found something important or helpful :)

**Comment by davidonzo** [comment]
Fixed, see the conversation on twitter: https://twitter.com/AdamSurak/status/1356152687289655297
The domain has been whitelisted, as ever in these cases. Of course, be carefull, since the downloaded file from the host is an effective malware.
