### ISSUE TITLE
Double 0.0.0.0 0.0.0.0  if sources have it header rule with it

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#1519]
@StevenBlack 
IF sources have `0.0.0.0 0.0.0.0` then python magic script made double of `0.0.0.0 0.0.0.0` in final hosts.
Simple add:
https://github.com/FadeMind/hosts.extras/tree/master/GoodbyeAds-Spotify-AdBlock-Extension
or other `GoodbyeAds` to data dir. Create new hosts file.
Results
![20210201-1612186170-001](https://user-images.githubusercontent.com/9846948/106465183-e9c97500-6499-11eb-97a6-8ba01d946a72.png)
![20210201-1612186152-001](https://user-images.githubusercontent.com/9846948/106465188-ea620b80-6499-11eb-83c3-e0e077809ce2.png)
In sources is:
![20210201-1612186260-001](https://user-images.githubusercontent.com/9846948/106465330-1e3d3100-649a-11eb-904f-a9bdad9c9a79.png)

CC @jerryn70 😉

**Comment by dnmTX** [comment]
@FadeMind we already went trough this: https://github.com/StevenBlack/hosts/issues/1511#issuecomment-766432518
