### ISSUE TITLE
Please open files.slack.com

### ISSUE THREAD

**Issue by ydwis40** [StevenBlack/hosts#1521]
I cannot upload files into my slackapp

I have follow that's files.slack.com has been added to this hosts files 
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by dnmTX** [comment]
Hmm......... 🤔

**Comment by BenvdStouwe** [comment]
I also cannot upload or view files in Slack because of this entry in thehosts file. 
 Exact matches for files.slack.com found in:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts 
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts

**Comment by Sprokket** [comment]
Better of adding files.slack.com in the whitelist on your pi. 

also contains the block. 
https://github.com/StevenBlack/hosts/tree/master/data/osint.digitalside.it

**Comment by ydwis40** [comment]
But by looking this lists 

https://osint.digitalside.it/Threat-Intel/lists/latesturls.txt

![image](https://user-images.githubusercontent.com/4518503/106600854-89b3fb00-658d-11eb-91ff-b939810289b1.png)

It's become only one file by someone who has share previewdocument-29-1.exe instead not actually all domain. Correct me if I'm wrong.

*Sorry if my english is bad.*

**Comment by StevenBlack** [comment]
Thanks everybody!  This will be live in the next version, coming shortly.

Closing.
