### ISSUE TITLE
wzrkt.com subdomain

### ISSUE THREAD

**Issue by argymeg** [StevenBlack/hosts#1522]
Hello,

Amid a flurry of connection attempts to wzrkt.com (which is included in the ad-hoc list) from my phone last night, there was also a successful connection to eu1-spiky.wzrkt.com. I'm not sure what the domain is in the first place but presumably the subdomain is no less suspect.

Thank you for all the good work!

**Comment by StevenBlack** [comment]
Thanks Argy @argymeg I've added this in commit 26704e1b.

Closing!
