### ISSUE TITLE
Base extension + Netguard = completely block any app

### ISSUE THREAD

**Issue by ddtuan99** [StevenBlack/hosts#1524]
I use Netguard with whitelist mode (block connection of all app include system apps, exclude some prefer apps). Excluded apps work fine untill filter mode is enabled (using Base extension list).

I also try to disable/enable and check app connection in between. I observe that app can connect right after filter mode disabled and cannot connect right after filter mode enabled.

Have you guys seen this before?

Take my apology if this issue is inapproriate. I can't reach out Netguard's dev so i post here in hoping to find some clue.

Really appreciate your time and effort!

**Comment by StevenBlack** [comment]
Hi @ddtuan99 thank you for this.

Your question is out of scope for this repo, but I'm happy to leave this issue open for a day or two in case someone has insight to share.

**Comment by ddtuan99** [comment]
Sometimes the filter works well with Netguard (yesterday i try to update the filter). This has happended in the past. It also means i need to stay with current filter because i don't know the next filter will work.

My guess is something related to DNS cache of android ...

Anyway thank you.
