### ISSUE TITLE
backblaze is blocked

### ISSUE THREAD

**Issue by jungle-boogie** [StevenBlack/hosts#1526]
Hi,

Thanks for maintaining the lists of bad hosts.

I would like to respectfully request the removal of this host: `f001.backblazeb2.com` from your hosts list:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

I think this was probably added to the hosts lists within the past week.

Backblaze is a legitimate cloud storage provider, and with it blocked, folks may not be able to connect to their backblaze accounts. I frequently use rclone to backup files to my backblaze account and discovered the host was blocked just the other day.

Thanks for the consideration!

https://www.backblaze.com
https://rclone.org

**Comment by jungle-boogie** [comment]
Looks like it was added with this commit:
https://github.com/StevenBlack/hosts/commit/840ee7d5be2f314d27e6ebefe3c6bb5206d59bc1#diff-4f8a2cc398d8664277a96a7843ab4958ab1d0a347cbe7c071fde0fcb58230793

**Comment by StevenBlack** [comment]
Thanks for this @jungle-boogie.

Davide @davidonzo can you please look at this — this one's urgent.  Thanks!

**Comment by davidonzo** [comment]
Hi Steven,

A malicious file has been shared via Backblaze.
This is the link to the latest VT report: https://www.virustotal.com/gui/file/bad08112a53a47a5bb856c7caad96f00ff2d29d109aee9118b56a5a62e59f5ef/detection

Anyway, as ever in these cases, I added the related host to the whitelist.
Considering the event, I'm running a new job to generate the repository content. It will finish in minutes.

Thanks for the advice.

Ciao!

Davide

**Comment by StevenBlack** [comment]
Thanks Davide!  I suppose this is an interesting point for consideration.  If malicious files are shared or hosted by BackBlaze, or Dropbox, or Google Drive, or Box, or iCloud, what should we do?  It's a tricky question.

**Comment by davidonzo** [comment]
Many hosts related to file sharing are just added to the whitelist.
I'm working hard to collect all possible involved hosts and have a valid domain exclusion list.

If someone have any up to dated resource to use as lookup, please, share with me!
Thanks!

Davide

**Comment by jungle-boogie** [comment]
Hello,

Thank you two for your prompt investigation into this issue. Now knowing a malicious file was shared via backblaze, I understand why backblaze was blocked.

**Comment by StevenBlack** [comment]
@jungle-boogie this is resolved and [release 3.3.11](https://github.com/StevenBlack/hosts/releases/tag/3.3.11) is now live.

Closing.
