### ISSUE TITLE
api.device.xiaomi.net should not be blocked

### ISSUE THREAD

**Issue by CB-wee** [StevenBlack/hosts#1531]
api.device.xiaomi.net is for managing "My devices" in Xiaomi's MIUI, and should not be blocked.

When it is blocked, I cannot access that option in MIUI.

**Comment by CB-wee** [comment]
api.device.xiaomi.net needs to be allowed, so this page can be shown on Xiaomi phones.
![Screenshot_2021-02-07-10-45-43-566_com xiaomi account](https://user-images.githubusercontent.com/34395942/107134977-cf0a5c80-68ee-11eb-9a46-b3b77a88deee.jpg)

**Comment by StevenBlack** [comment]
Thank you for this Bin @CB-wee.

@jawz101 can you please look at `api.device.xiaomi.net` and let us know what you think?  Thank you!

**Comment by jawz101** [comment]
removed thanks
