### ISSUE TITLE
post.spmailtechno.com [false positive]

### ISSUE THREAD

**Issue by 3xploiton3** [StevenBlack/hosts#1532]
https://github.com/nextdns/metadata/issues/568#issue-802926868

**Comment by StevenBlack** [comment]
Thank you @3xploiton3.  The domain `post.spmailtechno.com` comes to us via yoyo.org.

Can you please submit this request to pgl@yoyo.org, trust them to make the right call here.  Thank you!

**Comment by StevenBlack** [comment]
Ping Peter @pgl!  Thank you!

**Comment by pgl** [comment]
Hi there. This domain is used as a tracker for mails sent through Sparkpost.

If people are OK with their link clicks being tracked, then it would be best to allow this domain.

**Comment by StevenBlack** [comment]
Thanks Peter @pgl 

People here are NOT OK with their link clicks being tracked 😄 

I'm sorry @3xploiton3 it looks like this won't change.

Closing.
