### ISSUE TITLE
Suggestion of domains for consideration to be added

### ISSUE THREAD

**Issue by stefanbosak** [StevenBlack/hosts#1535]
Hi StevenBlack team,

let me suggest following domains for consideration:

**Google domains:**
fundingchoicesmessages.google.com (Google domain - https://developers.google.com/funding-choices)
*.fundingchoicesmessages.google.com (Google domain - https://developers.google.com/funding-choices)
googlesyndication.com (Google domain - Advertisement-related purposes)
*.googlesyndication.com (Google domain - Advertisement-related purposes)

**Microsoft domains:**
virtualearth.net (Microsoft domain - Bing maps)
*.virtualearth.net (Microsoft domain - Bing maps)

**Facebook domains:**
scanandcleanlocal.com (Facebook domain)
*.scanandcleanlocal.com (Facebook domain)

_cdninstagram.com (similar to fbcdn.net):_
scontent-b-{location}.cdninstagram.com = scontent-{location}-1.cdninstagram.com = external-{location}-1.cdninstagram.com = video-{location}-1.cdninstagram.com (host/IP is the same for scontent, external, video)

- for cdninstagram.com i would suggest to consider apply the same approach like already used for fbcdn.net (block all)
  fbcdn.net - is CDN to facebook sites content
  cdninstagram.com - is CDN more specific to instagram sites content
- if not possible then i would like to kindly ask to add following (Europe region - locations: Prague, Vienna, Warsaw):

scontent-prg1-1.cdninstagram.com
scontent-vie1-1.cdninstagram.com
scontent-waw1-1.cdninstagram.com

scontent-b-prg.cdninstagram.com
scontent-b-vie.cdninstagram.com
scontent-b-waw.cdninstagram.com

external-prg1-1.cdninstagram.com
external-vie1-1.cdninstagram.com
external-waw1-1.cdninstagram.com

video-prg1-1.cdninstagram.com
video-vie1-1.cdninstagram.com
video-waw1-1.cdninstagram.com

_fbcdn.net (example):_
scontent.f{location}-1.fna.fbcdn.net (host/IP is different for scontent, external, video)
instagram.f{location}-1.fna.fbcdn.net (host/IP is different for scontent, external, video)
external.f{location}1-1.fna.fbcdn.net (host/IP is different for scontent, external, video)
video.f{location}-1.fna.fbcdn.net (host/IP is different for scontent, external, video)

**other candidates for consideration:**
cookielaw.org (Cookie Law and privacy legislation)
*.cookielaw.org (Cookie Law and privacy legislation)
rsz.sk (trackers)
*.rsz.sk (trackers)
tracker.remp.sme.sk (trackers)

Thank you for your time and cooperation in advance (great and really very valuable project for many of us).

Have a nice day.

Stefan

**Comment by stefanbosak** [comment]
**Facebook domains - whatsapp:**
records media-{location}-1.cdn.whatsapp.net are gone because have been changed to media.f{location}-1.fna.whatsapp.net
it means all records media-{location}-1.cdn.whatsapp.net should be removed because they are not valid anymore

**Comment by dnmTX** [comment]
This looks like to be suggestion for the @Sinfonietta's **social list**(with some exceptions).
@stefanbosak could you please open a [ISSUE](https://github.com/Sinfonietta/hostfiles/issues) there and discuss it further with the curator. Thanks 👍

**Comment by StevenBlack** [comment]
Hi @stefanbosak thank you for this.

Hosts files don't support wildcards or variables in any way.

After deduplication, and considering we already block `googlesyndication.com` we're left with this, 20 domains.

```
cdninstagram.com
cookielaw.org 
external-prg1-1.cdninstagram.com
external-vie1-1.cdninstagram.com
external-waw1-1.cdninstagram.com
fbcdn.net
fundingchoicesmessages.google.com 
rsz.sk 
scanandcleanlocal.com 
scontent-b-prg.cdninstagram.com
scontent-b-vie.cdninstagram.com
scontent-b-waw.cdninstagram.com
scontent-prg1-1.cdninstagram.com
scontent-vie1-1.cdninstagram.com
scontent-waw1-1.cdninstagram.com
tracker.remp.sme.sk 
video-prg1-1.cdninstagram.com
video-vie1-1.cdninstagram.com
video-waw1-1.cdninstagram.com
virtualearth.net 
```

Look let's be honest there is zero chance I would support `virtualearth.net` unless it can clearly be shown malicious.

What's your beef with `cookielaw.org`?  I'm curious to know.

The bulk of the rest is for @sinfonietta **but** six of those are blocked already

```
$ ./ghosts -m https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts --clip --intersection
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
Domains: 90,939
Bytes: 2.7 MB
----------------------------------------
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 20
Bytes: 530 B
----------------------------------------
intersection: [fbcdn.net scontent-b-vie.cdninstagram.com scontent-b-waw.cdninstagram.com scontent-prg1-1.cdninstagram.com scontent-vie1-1.cdninstagram.com scontent-waw1-1.cdninstagram.com]
Intersection: 6 domains
```

That leaves us with ten for @sinfonietta...:

```
cdninstagram.com
external-prg1-1.cdninstagram.com
external-vie1-1.cdninstagram.com
external-waw1-1.cdninstagram.com
fundingchoicesmessages.google.com 
scontent-b-vie.cdninstagram.com
scontent-waw1-1.cdninstagram.com
video-prg1-1.cdninstagram.com
video-vie1-1.cdninstagram.com
video-waw1-1.cdninstagram.com
```

... and four for general list inclusion 

```
cookielaw.org 
rsz.sk 
scanandcleanlocal.com 
tracker.remp.sme.sk 
```

@stefanbosak can you make the case for the last four?

**Comment by dnmTX** [comment]
`scanandcleanlocal.com`  does NOT resolve....no known subdomains either

`tracker.remp.sme.sk`  aka `sme.sk`:
`SME or Denník SME is one of the most widely read mainstream broadsheets in Slovakia. 
Their website, SME.sk, is one of the most visited Internet portals in Slovakia`

`rsz.sk`  couldn't find anything to support the claim that it's a tracking domain(no known subdomains either)
It's Android based so very well could be malicious(no proof,just me speculating here 😉)

**Comment by stefanbosak** [comment]
Hi StevenBlack team members,

scanadncleanlocal.com - > it is used by Facebook mainly pointing to local stuff and localhost

tracker.remp.sme.sk -> this is tracker and can be blacklisted

*.rsz.sk -> also tracker can be considered as blacklisted entry but not as domain but as wildcard entry (RPZ)

I know that host lists does not support wildcards and so on.

Just to let you know for GCC (Google Global Caches) - examples:
r<1; 9>.<cachehash>.googlevideo.com (GGC cluster hosts)
r<1;9>.<provider>-<site><1;9>.c.youtube.com (local site provider ISP DC GGC cluster redirectors)
r1.<site><1;99>s<01;99>.c.youtube.com (local site Google DC GGC cluster redirectors)

FNA (Facebook Network Appliance) - examples:
{video,scontent,static,instagram,external}.f<site><1;9>-<1;9>.fna.fbcdn.net
{video,scontent,static,instagram,external}-<site><1;9>-<1;9>.cdninstagram.com
{media,video,scontent,static,external}.f<site><1;9>-<1;9>.fna.whatsapp.net

i am working on preparation of generated listing of many entries covering GGC, FNA.
After that i would like to share this content with you because potentially might be very usefull to many users.

Thank you for your time and cooperation in advance.

Stefan

**Comment by stefanbosak** [comment]
Regarding cookielaw.org (some information to share):
it is about ePrivacy regulations trying to analyse some stuff regarding cookies and related regulations in EU (GDPR)
i have seen this in the past several times, there were some trackers behind the curtain
some other partially related information can be found here (potentially also area for consideration in relation to trackers):

https://www.cookiebot.com/en/google-consent-mode/
https://blog.google/products/marketingplatform/360/measure-conversions-while-respecting-user-consent-choices/

Thanks.

Stefan

**Comment by stefanbosak** [comment]
> 
> 
> This looks like to be suggestion for the @Sinfonietta's **social list**(with some exceptions).
> @stefanbosak could you please open a [ISSUE](https://github.com/Sinfonietta/hostfiles/issues) there and discuss it further with the curator. Thanks 👍

Sure i would create separate/dedicated issue for mentioned list when i would have ready with listings for GGC (Google Global Cache) & FNA (Facebook Network Appliance) worldwide cache clusters to be more efficient within sharing regarding social list / category.

Thank you for advice to be able to use corresponding list(s) (more relavant content).

Stefan

**Comment by StevenBlack** [comment]
I'm so confused.   Such a rambling thread.

@stefanbosak for `cookielaw.org` — we aren't in the business of taking down businesses or organizations, just their vectors for adware and crap.  You say there are trackers behind `cookielaw.org`.  What trackers?  Where are they served from?  That's what we block.  Are the trackers coming from the raw `cookielaw.org` domain?  It's a wordpress site, lots coming as a result but I can see is objectionable.  What am I missing?

As stated above, `*.rsz.sk` isn't valid for hosts files, and `rsz.sk` resolves to a 403 "oops" page.  Are ads, trackers, or malware coming from `rsz.sk`?  They serve jQuery and a favicon, that's evidently all.  What am I missing?

After all this we get what, one domain?  🙄   Plus some instragram cdn stuff for @sinfonietta.  Got it.

**Comment by Sinfonietta** [comment]
@StevenBlack @stefanbosak I have addedd the Instagram domains in this issue.  Thank you!

**Comment by StevenBlack** [comment]
Closing.
