### ISSUE TITLE
[ADD SUGGESTION] vkcache.com 

### ISSUE THREAD

**Issue by DMNerd** [StevenBlack/hosts#1536]
This is an obnoxious domain that is used by either advertising or tracking on some video sharing websites. The worst thing is it makes callbacks literally every second under different domain prefix. I had to block it manually on my pihole. 

Example:
![Screenshot 2021-02-09 at 13 12 33](https://user-images.githubusercontent.com/7889445/107362049-8b734680-6ad8-11eb-94fd-60585bc75176.png)

**Comment by DMNerd** [comment]
One more piece of info - the randomness could suggest some sort of subdomain attack.
https://github.com/galprz/dns-random-subdomains-ddos-attack

**Comment by llacb47** [comment]
Are you joking? That is a CDN for VK, a Russian social network.

**Comment by DMNerd** [comment]
Apparently it is not anymore. The domain expired and it got snagged off bz someone else
![Screenshot 2021-02-09 at 13 54 05](https://user-images.githubusercontent.com/7889445/107366335-50741180-6ade-11eb-992d-025f78ed689d.png)

**Comment by DMNerd** [comment]
![Screenshot 2021-02-09 at 13 56 02](https://user-images.githubusercontent.com/7889445/107366544-90d38f80-6ade-11eb-8ba8-4263e7e54310.png)

The lookup on icann confirms it too

**Comment by DMNerd** [comment]
> Apparently it is not anymore. The domain expired and it got snagged off by someone else
> ![Screenshot 2021-02-09 at 13 54 05](https://user-images.githubusercontent.com/7889445/107366335-50741180-6ade-11eb-992d-025f78ed689d.png)
> 
> The name is obviously fake and the registrar is DropCatch.com which is domain marketplace for domains about to expire

**Comment by DMNerd** [comment]
> Are you joking? That is a CDN for VK, a Russian social network.
While it might have been at one point it definitelly is not anymore. The ip it is tied to is hosted in US and the registrar is definitelly not consistent with actual VK. 
It is just a very good camuflage.

**Comment by StevenBlack** [comment]
Thank you for this detailed report Adam @DMNerd.

Looking at this now.  It's too bad hosts files don't support wildcards, but this is a root domain I'm happy to include.  Even the root domain is horrible.

**Comment by StevenBlack** [comment]
Done.  Thanks Adam @DMNerd.

Closing.
