### ISSUE TITLE
www.4shared.com

### ISSUE THREAD

**Issue by adranger** [StevenBlack/hosts#1538]
Please whitelist `www.4shared.com`. It's a major file hosting website like Mega and MediaFire, but it's currently blocked by your hosts file. This site is used, for instance, by archivists who try to preserve old comic books. As an example, see the download link [at the bottom of this page](http://www.agibiteca.com.br/DescricaoPortal.aspx?Code=0MOKL0&Title=0%5d%u0082%u008c%u0087%7e%u00929%5e%u008c%u0089%7e%7c%u0082z%u00859k%7e%7e%7d%u0082%u0100%u00fc%u00889F9IJM9AgmB9S9h%u008c9fz%u008b%u0082%u0087%u0081%7e%u0082%u008b%u0088%u008c0). 

I'm aware that you expect list issues to be reported directly to their maintainers, and I've done so, but the person behind mvps is dealing with serious health issues (see the notice at https://winhelp2002.mvps.org/hosts.htm), and I don't know if I'll get a reply.

https://github.com/StevenBlack/hosts/blob/a204d5a1e9049dd12378fa5f9c5ab3fc6bf3d63e/data/mvps.org/hosts#L9887

**Comment by dnmTX** [comment]
> Please whitelist www.4shared.com.

@adranger no such a option exist here. Would advise you to either whitelist/remove on your end(if on a hurry) or
wait for the response from the original list maintainer(whenever that might be).

**Comment by funilrys** [comment]
Hi @adranger, knowing Steve @StevenBlack; you should ask upstream - first: https://github.com/StevenBlack/hosts/blob/a204d5a1e9049dd12378fa5f9c5ab3fc6bf3d63e/data/mvps.org/update.json#L6

**Comment by adranger** [comment]
@funilrys I said that I had already contacted the author.

@dnmTX he did reply:
>That entry has been removed ... and it will reflect in the next update ... due soon.
