### ISSUE TITLE
Gambling sites Suggestions

### ISSUE THREAD

**Issue by SamuelMwangiW** [StevenBlack/hosts#1540]
Kindly see below a non-comprehensive list of gambling sites from this side of the world for your consideration.
```
www.ke.sportpesa.com
ke.sportpesa.com
sportpesa.com
sportpesa.co.tz
www.sportpesa.co.tz
www.betway.co.ke
betway.co.ke
22bet.co.ke
www.22bet.co.ke
www.sportybet.com
sportybet.com
betpawa.com
www.betpawa.com
betpawa.ug
www.betpawa.ug
betpawa.ng
www.betpawa.ng
ke.betpawa.com
www.ke.betpawa.com
www.betpawa.co.tz
betpawa.co.tz
www.betpawa.co.zm
betpawa.co.zm
www.betpawa.com.gh
betpawa.com.gh
www.betpawa.co.zw
betpawa.co.zw
www.betika.com
betika.com
www.mozzartbet.co.ke
mozzartbet.co.ke
```

**Comment by StevenBlack** [comment]
Thank you Samuel @SamuelMwangiW — ping @sinfonietta (who curates a gambling source list).

**Comment by SamuelMwangiW** [comment]
Thanks @StevenBlack for maintaining such a helpful repository. I will make a point to raise future issues upstream where necessary.

**Comment by Sinfonietta** [comment]
These domains are added to my gambling list @StevenBlack @SamuelMwangiW thank you!

**Comment by freeman28** [comment]
I want betpawa command code

**Comment by freeman28** [comment]
> Kindly see below a non-comprehensive list of gambling sites from this side of the world for your consideration.
> ```
> www.ke.sportpesa.com
> ke.sportpesa.com
> sportpesa.com
> sportpesa.co.tz
> www.sportpesa.co.tz
> www.betway.co.ke
> betway.co.ke
> 22bet.co.ke
> www.22bet.co.ke
> www.sportybet.com
> sportybet.com
> betpawa.com
> www.betpawa.com
> betpawa.ug
> www.betpawa.ug
> betpawa.ng
> www.betpawa.ng
> ke.betpawa.com
> www.ke.betpawa.com
> www.betpawa.co.tz
> betpawa.co.tz
> www.betpawa.co.zm
> betpawa.co.zm
> www.betpawa.com.gh
> betpawa.com.gh
> www.betpawa.co.zw
> betpawa.co.zw
> www.betika.com
> betika.com
> www.mozzartbet.co.ke
> mozzartbet.co.ke
> ```

Can I hack betpawa ng
