### ISSUE TITLE
License implies copyright, but there is no copyright for non-creative works.

### ISSUE THREAD

**Issue by semirandombits** [StevenBlack/hosts#1547]
Seriously, not to be a pain, but how can a list of domain names be copyrightable?

**Comment by Lateralus138** [comment]
There's not just lists here, no? Code and documentation count as copyright-able I imagine.

**Comment by StevenBlack** [comment]
As ian @Lateralus138 suggests, this repo contains far more than lists @semirandombits.  Also, we preserve the copyrights from all the sources we aggregate.

Closing.
