### ISSUE TITLE
[whitelist] kaltura.com.edgekey.net

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1548]
Reference ->
![steven](https://user-images.githubusercontent.com/8227101/107885760-531aa080-6efc-11eb-9925-3b189ac797ec.png)

https://github.com/StevenBlack/hosts/issues/1542

**Comment by StevenBlack** [comment]
Thanks Lorenzo.

This comes from upstream at AdAway.  Ping @Jawz101 — thanks!

**Comment by jawz101** [comment]
removed.  thank you

**Comment by StevenBlack** [comment]
Thanks @jawz101.  Lorenzo @scafroglia93 this will be in the next release.

Closing.
