### ISSUE TITLE
Non GitHub mirror sbc.io Error 404 Not Found

### ISSUE THREAD

**Issue by mikhaelkh** [StevenBlack/hosts#1549]
'404 Not Found' response for http://sbc.io/hosts/hosts or other hosts variants.

**Comment by dnmTX** [comment]
@mikhaelkh use this link temporarily until the problem is fixed: https://www.celsoazevedo.com/hosts/ 

ping Steven @StevenBlack

**Comment by StevenBlack** [comment]
Hi Michael @mikhaelkh thank you for this.

Fixed!

Closing.
