### ISSUE TITLE
[blocklist] track.digital360.it

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1552]
founded inside nextdns log

**Comment by StevenBlack** [comment]
Lorenzo @scafroglia93 we're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

I'm absolutely NOT interested in trucking on a one-domain-per-issue basis.  That doesn't scale, and it doesn't work.  If you have a list of 20+ we can look at, on aggregate, then please submit that.  But please don't submit issues here each time to sense something in your logs.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
