### ISSUE TITLE
Domain Suggestion for Porn list

### ISSUE THREAD

**Issue by firebytrials** [StevenBlack/hosts#1555]
Consider adding the following. Thanks for you work.

www2.javhdporn.net/

**Comment by StevenBlack** [comment]
Thanks @firebytrials!  Ping @sinfonietta.

**Comment by Sinfonietta** [comment]
Added @StevenBlack.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and thank you for suggesting this @firebytrials.

Closing.
