### ISSUE TITLE
Please Add to blacklist 

### ISSUE THREAD

**Issue by opensource008** [StevenBlack/hosts#1556]
(PORN)

pinayflix.com
pinayrare.net
kantotin.com
xtorjack.com
rbreezy.org
xxxjojo.com
xbree.net
kainpopoy.com

Thank you

**Comment by StevenBlack** [comment]
Thanks @opensource008.  Ping @sinfonietta.

**Comment by Sinfonietta** [comment]
Added @StevenBlack.

Hey sorry for the delay, been busy.

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta I appreciate what you do, no issue for the delay.

Thanks for these, @opensource008.

Closing.
