### ISSUE TITLE
Suggestions for further tracking domains not covered yet.

### ISSUE THREAD

**Issue by KommX** [StevenBlack/hosts#1558]
Hi,

this is my first issue that I post to this project.
Here are some domains I found on german popular sites that aren't blocked yet. If you think they should be included elsewhere please direct me where you think this is better suited. I saw the [lists here](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant), but couldn't figure out, which one I should contact.

tagesschau.de:
- logs1413.xiti.com

spiegel.de:
- b174.s240.meetrics.net
- b95.s79.research.de.com
- s79.mxcdn.net
- s240.mxcdn.net
- s385.mxcdn.net
- zipservice.adalliance.io

zeit.de:
- responder.wt-safetag.com
- bid.sxp.smartclip.net

lidl.de:
- eu-tlp01.kameleoon.eu
- eu-tlp02.kameleoon.eu
- eu-tlp05.kameleoon.eu
- z9q9kj37oy.kameleoon.eu
- customers-lidl.kameleoon.com
- storage.kameleoon.eu
- www.lacmp.net

welt.de:
- p.vtracy.de
- www.asadcdn.com
- adstax-cdn.adrtx.net
- lmyd3iz3qn.kameleoon.eu

Some more I found in pi-hole logs, which I can't map to a specific site:
- logs1211.xiti.com
- b106.s240.meetrics.net
- b195.s240.meetrics.net

**Comment by StevenBlack** [comment]
Thanks @KommX.

Zero overlaps.

```
$ ./ghosts --clip --intersection
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 65,234
Bytes: 2.0 MB
----------------------------------------
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 16
Bytes: 334 B
----------------------------------------
intersection: []
Intersection: 0 domains
```

**Comment by StevenBlack** [comment]
Thanks @KommX these are added to the list.

Closing.

**Comment by KommX** [comment]
@StevenBlack 
I realized that you only add the first 16 domains to the list. Is something wrong with the last 7?

**Comment by StevenBlack** [comment]
Hi @KommX I think I added all the domains that were in the list, at that time.  

This was 29 days ago...

**Comment by KommX** [comment]
Hm, maybe I edited the list too late or something. I'll remove the entries that you didn't add in https://github.com/StevenBlack/hosts/commit/1485491816754f189f12d4a7ac0805a02659b31d and create a new issue with these and some more.
