### ISSUE TITLE
Fishing Domain request

### ISSUE THREAD

**Issue by NO-ob** [StevenBlack/hosts#1559]
Showed up in google results as: https://github.com.cnpmjs.org/topics/hackintosh-efi
https://github.com.cnpmjs.org/

It currently looks like this image but earlier on it was showing a github ui with repos etc, almost put my creds into their login page lel
![image](https://user-images.githubusercontent.com/15161159/109339556-b9d67d00-785f-11eb-8114-650800062a08.png)

**Comment by StevenBlack** [comment]
Thanks @NO-ob I hate scams like this.  This is added in commit 16070f1a and will ship in the next release.

Closing.
