### ISSUE TITLE
hosts\data\adaway.org detected by Windows Defender as "SettingsModifier:Win32/PossibleHostsFileHijack"

### ISSUE THREAD

**Issue by pedro7** [StevenBlack/hosts#156]
Just as a warning, Windows Defender is detecting hosts\data\adaway.org as https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?Name=SettingsModifier:Win32/PossibleHostsFileHijack .

I thought this should be logged somewhere, but feel free to close this :)

**Comment by StevenBlack** [comment]
I think I'm gonna close this.  :-)
