### ISSUE TITLE
Is whitelisting of s0.2mdn.net still the case?

### ISSUE THREAD

**Issue by crssi** [StevenBlack/hosts#1560]
Is https://github.com/StevenBlack/hosts/issues/419 still the case?
`s0.2mdn.net` seem pretty prevalent and blocking it I haven't found single site to break.
I would tried `mtv.ca` and `cbs.com` to recheck that whitelisting `s0.2mdn.net` is still needed, but those are geo-fenced and doesn't play in my region unfortunately.

Thank you and cheers

**Comment by StevenBlack** [comment]
Thank you for the question @crssi.

@tiuxo can you comment on this one?  I trust your judgment, it's your call.  Thanks!

**Comment by crssi** [comment]
@tiuxo ?

**Comment by crssi** [comment]
@StevenBlack how is this related to @tiuxo ?

Cheers

**Comment by StevenBlack** [comment]
@crssi it's because @tiuxo, one of our curators, lists this domain, which is why it's being listed here.

**Comment by crssi** [comment]
I see. Thank you
I have asked because I haven't found any such resource at his repository and have been puzzled a bit. 😉

**Comment by dnmTX** [comment]
Steve @StevenBlack it's actualy blocked only by AdAway. Two other lists has it but it's commented there due to interference with streaming sites.
@crssi i guess i'm not getting what the question here is but whatever it is we have that domain blocked here.
Is that what you prefer?

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX you're right about AdAway.

I'm showing [blocked by @tiuxo at line 1757](https://github.com/StevenBlack/hosts/blob/master/data/tiuxo/hosts#L1757).  Is that not what you see too?

**Comment by dnmTX** [comment]
Steve that might be the case but if look at the latest [release of the list](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) it's not there anymore very likely being duplicate,thus removed as such.

**Comment by Zyt3x** [comment]
Answer: Not at all.
