### ISSUE TITLE
Domain suggestions for adware list

### ISSUE THREAD

**Issue by r15ch13** [StevenBlack/hosts#1561]
```
audacity.de
audacity.es
audacity.fr
audacity.it
audacity.pl
vlc.de
```

Both provide installers containing adware.

Based on https://github.com/uBlockOrigin/uAssets/issues/1738

**Comment by StevenBlack** [comment]
Hi Richard @r15ch13 thank you for this.

These domains...

```
audacity.es
audacity.fr
```

... are already blocked here via someonewhocares.org.

Can you please submit these domains to Dan Pollock at hosts@someonewhocares.org since he's already curating these related domains.  Danke!

**Comment by r15ch13** [comment]
Mail is sent, thanks 👍🏽

**Comment by r15ch13** [comment]
Domains were added. 👍🏽
