### ISSUE TITLE
Using these lists in pfsense without pfblockerng

### ISSUE THREAD

**Issue by marcoczen** [StevenBlack/hosts#1562]
Hi guys,

Is it possible to use these lists(adware + malware )  in pfsense  without using pfblockerng  ? For example in an Alias  and then make a firewall rule using this Alias on the WAN Interface ?   

Kindly advise.

**Comment by StevenBlack** [comment]
Hi @marcoczen thank you for posting your question but I feel this is out of our scope.

Closing.

**Comment by cloudsvrtech** [comment]
> Hi @marcoczen thank you for posting your question but I feel this is out of our scope.
> 
> Closing.

Thank you.
My apologies.
I couldnt find an answer ( without pfblockerng )  anywhere else -  so i thought I try here.
