### ISSUE TITLE
CNAME-cloaked trackers

### ISSUE THREAD

**Issue by DavidCWGA** [StevenBlack/hosts#1563]
AdGuard has published a list of CNAME-clocked trackers. (And explained what a CNAME clocked tracker is, and how they work.)

https://github.com/AdguardTeam/cname-trackers

I'm not entirely sure of the format of their repo, I think the list is all the .txt files in this directory concatenated together, maybe:
https://github.com/AdguardTeam/cname-trackers/tree/master/trackers

It would be nice to see these ingested into the list.

**Comment by dnmTX** [comment]
**ping @ameshkov** 
Any chance of implementing combine(curated of course) list in a hosts format ( aka `0.0.0.0 domain.com` ) 
or just a plain list without the not needed characters that are used in adblocking software so can be added here as a addition 
to enhance the protection of everyone who uses the lists here?
Thanks as allways 👍

**Comment by ameshkov** [comment]
Hm, I guess we can do a plain list as well. Could you please file a feature request to the repo so that we didn't forget? :)

**Comment by dnmTX** [comment]
@ameshkov DONE! 
**for refference see:** https://github.com/AdguardTeam/cname-trackers/issues/3
Will wait for update. Thank you and @AdguardTeam for the excellent work as allways 👍

**Comment by durablenapkin** [comment]
Just wanted to comment and say that @AdguardTeam has generated combined lists: https://github.com/AdguardTeam/cname-trackers#the-lists

The list that would be of interest is: https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt

**Comment by DavidCWGA** [comment]
I manually added the new AdGuard list to my blocker about a week ago and so far nothing new seems to be broken that wasn't broken already.

**Comment by dnmTX** [comment]
Patience everyone,[it's not automated,yet](https://github.com/AdguardTeam/cname-trackers/issues/3#issuecomment-798907962)
We'll wait for official word from the @AdguardTeam 👍

**Comment by dnmTX** [comment]
Steve @StevenBlack this one is ready for your review and approval 👍 
**Raw Link:** https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX and David @DavidCWGA!  👍 Let's have a look.

Using [ghosts](https://github.com/StevenBlack/ghosts) straight-up:  9,168 domains, with a 3% overlap rate.  So including this list adds 8,883 domains.

```
$ ./ghosts -c https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 68,213
Bytes: 2.1 MB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt
Domains: 9,168
Bytes: 210 kB
----------------------------------------
Intersection: 285 domains
```

**Comment by StevenBlack** [comment]
The TLD breakdown:  Surprisingly strong on `.jp` Japan, which is interesting.  Any insight why Dan @dnmTX or Dave @DavidCWGA?  It's interesting that `.org` is much deeper than `.net`; that feels unusual, certainly not typical, say.  It's deep in `.de` and `.fr` too, and other European countries too.

```
$ ./ghosts -tld -m https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt
Domains: 9,168
Bytes: 210 kB
TLD tally:
   com: 5,640
   jp: 395
   de: 303
   org: 282
   fr: 225
   au: 193
   ca: 182
   uk: 180
   net: 142
   ru: 112
   nl: 110
   es: 101
   it: 98
   edu: 80
   be: 76
   se: 59
   ch: 58
   pl: 53
   at: 42
   eu: 40
   dk: 37
   br: 33
   no: 32
   io: 32
   fi: 30
   co: 30
   cz: 26
   nz: 26
   tr: 24
   ro: 21
   kr: 18
   sg: 16
   hu: 16
   cn: 14
   in: 14
   ie: 14
   tw: 13
   info: 12
   id: 12
   ua: 12
   il: 11
   us: 11
   tv: 11
   mx: 11
   pt: 10
   sk: 9
   me: 9
   app: 9
   bg: 9
   gov: 9
   pe: 8
   hk: 8
   my: 8
   gr: 7
   vn: 6
   dev: 6
   hr: 6
   eg: 6
   lt: 6
   ph: 5
   ee: 5
   tech: 5
   sncf: 5
   lv: 5
   ai: 4
   gg: 4
   by: 4
   pm: 4
   si: 4
   za: 4
   cl: 4
   cr: 3
   online: 3
   link: 3
   xyz: 3
   biz: 3
   la: 3
   blog: 3
   lu: 3
   ar: 3
   sh: 3
   group: 3
   nu: 3
   th: 3
   health: 2
   coop: 2
   bnpparibas: 2
   pro: 2
   hn: 2
   gt: 2
   kz: 2
   st: 2
   gh: 2
   digital: 2
   lk: 2
   today: 2
   ci: 2
   global: 2
   ae: 2
   saxo: 2
   one: 2
   pictet: 2
   media: 2
   abbott: 2
   cloud: 2
   life: 2
   rs: 2
   so: 2
   eus: 1
   clinic: 1
   technology: 1
   win: 1
   om: 1
   nyc: 1
   sa: 1
   science: 1
   pk: 1
   berlin: 1
   jcb: 1
   su: 1
   education: 1
   rocks: 1
   page: 1
   komatsu: 1
   tn: 1
   ec: 1
   marketing: 1
   school: 1
   bank: 1
   ntt: 1
   codes: 1
   store: 1
   asia: 1
   fm: 1
   host: 1
   name: 1
   ink: 1
   care: 1
   aero: 1
   kpmg: 1
   fyi: 1
   apple: 1
   photography: 1
   bauhaus: 1
   swiss: 1
   expert: 1
   py: 1
   works: 1
   world: 1
   bd: 1
   website: 1
   ke: 1
   gl: 1
   do: 1
   ma: 1
   canon: 1
   travel: 1
   plus: 1
   sandvik: 1
   lat: 1
   qa: 1
   md: 1
   garden: 1
   partners: 1
   guru: 1
   am: 1
   bh: 1
   email: 1
   ir: 1
   agency: 1
   tokyo: 1
   site: 1
   international: 1
----------------------------------------
```

**Comment by dnmTX** [comment]
Steve @StevenBlack their adblocker uses numerous country specific filters(optional of course),so i'm guessing that is what they do whith their DNS service. They have API that scans all the domains in their DNS service to find those clocked trackers,so this is just the result of the scan,if there are more of those in japanese domains,it's what it is.
Sorry but this is the best explanation that i can give based on figuring out the whole process of extracting those hidden trackers.

**Comment by StevenBlack** [comment]
I've [left a message](https://github.com/AdguardTeam/cname-trackers/issues/7), presenting intentions and requesting consent, with Andrey @ameshkov and Slava @slavaleleka.

Thank you for this, David @DavidCWGA and Dan @dnmTX.

**Comment by DavidCWGA** [comment]
A large number of the .jp entries use the hostname "smetrics", which seems to be the documented suggestion for setting up the Adobe ID Service:

https://experienceleague.adobe.com/docs/id-service/using/reference/analytics-reference/cname.html?lang=en#reference

Perhaps that service is just particularly popular in Japan.

**Comment by StevenBlack** [comment]
I think it's high time to modify [https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py](updateHostsFile.py) to accept domains in raw text form.  This should be an easy get (ha!).

**Comment by StevenBlack** [comment]
I think we'll go with Andrey's @ameshkov full list and, if we see problems, we'll pull back to a truncated, more conservative version.  See https://github.com/AdguardTeam/cname-trackers/issues/7

**Comment by StevenBlack** [comment]
Thanks Andrey @ameshkov, Nissar @funilrys, David @DavidCWGA , and Dan @dnmTX!

This is now live, in [Release 3.6.0](https://github.com/StevenBlack/hosts/releases/tag/3.6.0), released just now.

Closing!
