### ISSUE TITLE
scroller.com

### ISSUE THREAD

**Issue by Wiggum127** [StevenBlack/hosts#1564]
Dodgy domain serving scams and phishing pages.

**Comment by dnmTX** [comment]
Just to put it up here. Every domain and sub-domain associated with `*.scroller.com` that i tried,redirects to
`noclick.connexity.com` which is already listed here.
@Wiggum127  you mind providing more details to justify the need of blocking it,cause thus far i honestly don't see a reason for it.

**Comment by Wiggum127** [comment]
Fair point. 
I was browsing the net without filters activated and noticed this unwanted behaviour of scroller.com. When checking your host files I didn't find back scroller.com. Hence my suggestion. But I should have been looking for noclick.connexity.com, as you mentioned. Fair point.

You could still consider blocking scroller.com as it redirects you to nothing but junk. But I leave that up to your discretion.

**Comment by dnmTX** [comment]
Steve @StevenBlack what do you think? I can list here whatever i can find on `*.scroller.com` or leave it as is?

**Comment by StevenBlack** [comment]
Go for it Dan @dnmTX.

**Comment by dnmTX** [comment]
Here you go:

`0.0.0.0 www.scroller.com`
`0.0.0.0 m.scroller.com`
`0.0.0.0 yocto.scroller.com`
`0.0.0.0 atto.scroller.com`
`0.0.0.0 zepto.scroller.com`
`0.0.0.0 ftp.scroller.com`
`0.0.0.0 old.scroller.com`
`0.0.0.0 wwe.scroller.com`
`0.0.0.0 ww1.scroller.com`
`0.0.0.0 ww4.scroller.com`

**Comment by StevenBlack** [comment]
Dan @dnmTX  `ftp.scroller.com`?  Just making sure we're covering what we need, not shot-gunning the whole namespace.

**Comment by dnmTX** [comment]
Steve @StevenBlack the domain is present,it resolves(there is a IP assigned to it),beyond that i can only speculate what or how it's used for.
As i stated in my prevoius post **"i'll list here whatever i can find"** and you take it from there.
Whatever you think is not suitable just ignore it.
I'm just the extra set of eyes here 😉 👍

**Comment by dnmTX** [comment]
Steve @StevenBlack further research led to nowhere....i mean...besides discovering #1565 (unrelated 😉 )
So take into account that ALL of the above domains listed are redirecting to `noclick.connexity.com` which only serves junk as 
@Wiggum127 noted already and it's a part of the Shopzilla network.
Also `ftp.scroller.com` was tight to a IP which was riddled with pornware.
So,if you ask me,in this particular case here the `ftp.` part is more of a symbolic than something actual.
