### ISSUE TITLE
chtbl.com

### ISSUE THREAD

**Issue by SheepKid12** [StevenBlack/hosts#1567]
I understand why you'd want to add it to the list (it's a tracking domain, and most people that use lists like these don't want to be tracked), but in this case, I don't think it should be blocked.

My reasoning for this: Pocket Casts (or really, any podcast app) is unable to play certain podcasts I like to listen to that use [Chartable](https://chartable.com/) for their analytics.

Edit: I probably should have mentioned the following:

1. I'm using a Pi-Hole, and whitelisting the domain fixes the issue.
2. Looks like it was added in 82c18786d.

**Comment by StevenBlack** [comment]
Thanks @SheepKid12.  This is upstream.

Ping @jawz101 care to comment?  Whatever you decide.

**Comment by amit-bh** [comment]
Can confirm on Overcast app on iOS as well. Episodes failed to download until I whitelisted chtbl.com.

**Comment by jawz101** [comment]
removed.  thanks

**Comment by StevenBlack** [comment]
Thank you as always @jawz101.

Closing.
