### ISSUE TITLE
app.hubspot.com

### ISSUE THREAD

**Issue by acerbisgianluca** [StevenBlack/hosts#1568]
`app.hubspot.com` has been added in 3.4.5, but this domain points to the CRM web app and AFAIK it doesn't track emails.

**Comment by beaurepair** [comment]
It was added via AdAway
https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt

**Comment by jawz101** [comment]
removed.  thanks

**Comment by acerbisgianluca** [comment]
Thank you all, issue closed
