### ISSUE TITLE
api.ibeat-analytics.com & others

### ISSUE THREAD

**Issue by amit-bh** [StevenBlack/hosts#1569]
Hello, excuse me if my formatting is off or other info is needed. I am not a programmer but have a PiHole and noted these likely trackers not blocked by any lists:

api.ibeat-analytics.com
tracker.idocdn.com
ca-tracking.nextdoor.com

Only thing I see close is ibeat.indiatimes.com which is present currently in the list.

**Comment by StevenBlack** [comment]
Thank you Amit @amit-bh.

Potentially three new domains:

```
$ ./ghosts --clip
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 66,398
Bytes: 2.0 MB
----------------------------------------
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 3
Bytes: 67 B
----------------------------------------
Intersection: 0 domains
```

**Comment by dnmTX** [comment]
@amit-bh did you block them on your end to see if anything break first or you just saw it in the logs????
Do some testing first.
PiHole offers broader opportunities to perform that and you don't really need to be programmer in this case.

**Comment by amit-bh** [comment]
> @amit-bh did you block them on your end to see if anything breaks first or you just saw it in the logs????
> 
> Do some testing first.
> 
> PiHole offers broader opportunities to perform that and you don't really need to be programmer in this case.

I have them blocked on my Pi-hole for atleast 2-3 months with no issues.
