### ISSUE TITLE
Please add the FreeBSD usage instructions

### ISSUE THREAD

**Issue by yurivict** [StevenBlack/hosts#157]
You should include the FreeBSD usage section:
It is recommended that DNS requests are cached using nscd(8).
- Enable nscd daemon with the command:

```
# sysrc nscd_enable="YES""
```
- Start nscd daemon with the command:

```
# service nscd start
```
- Enable nscd DNS cache by changing the "hosts" line in /etc/nsswitch.conf to: 'hosts: cache files dns'

**Comment by StevenBlack** [comment]
Thanks @yurivict.

Can somebody on FreeBSD confirm this for me?  A pull request would be great :-)

**Comment by StevenBlack** [comment]
I still need someone to try this n FreeBSD.

**Comment by Guymer** [comment]
Hi, I just tried this on my FreeBSD 11.1 box and it appears to work. I manually added the line `nscd_enable="YES"` to my [/etc/rc.conf](https://www.freebsd.org/cgi/man.cgi?rc.conf(5)) file rather than use the [sysrc](https://www.freebsd.org/cgi/man.cgi?sysrc(8)) utility. That is just personal preference I think. My only comment on the whole method is that using [nscd](https://www.freebsd.org/cgi/man.cgi?nscd(8)) at all is optional. It will improve performance by caching the results of [/etc/hosts](https://www.freebsd.org/cgi/man.cgi?hosts(5)) but I think this is going to be of marginal benefit for my usage scenario.

**Comment by StevenBlack** [comment]
Thank you for the input, Thomas @Guymer!

**Comment by gfyoung** [comment]
So is there really anything that needs to be added for FreeBSD?  Sounds like these instructions weren't actually needed perhaps (can't confirm personally unfortunately)?

**Comment by Guymer** [comment]
I think a comment in the [Reloading Hosts File](https://github.com/StevenBlack/hosts#reloading-hosts-file) section about enabling [nscd](https://www.freebsd.org/cgi/man.cgi?query=nscd&sektion=8) and using [nscd.conf](https://www.freebsd.org/cgi/man.cgi?query=nscd.conf&sektion=5) on FreeBSD would be beneficial. The only difference between what I did and what @yurivict did was exactly *how* we each enabled [nscd](https://www.freebsd.org/cgi/man.cgi?query=nscd&sektion=8) in [rc.conf](https://www.freebsd.org/cgi/man.cgi?query=rc.conf&sektion=5). @yurivict's way is safer for new FreeBSD users.

**Comment by gfyoung** [comment]
@Guymer : So what command would they use to clear the DNS cache after they have enabled `nscd` (didn't realize it wasn't enabled by default)?  Something along the lines of `nscd --invalidate=????`

**Comment by Guymer** [comment]
@gfyoung : You can either restart the machine or run `service nscd restart` (as root) to restart the [nscd](https://www.freebsd.org/cgi/man.cgi?query=nscd&sektion=8) service.

**Comment by gfyoung** [comment]
@Guymer : Gotcha.  Just to double check:

* The commands for enabling `ncsd` from @yurivict require root as well?
* What is the full path to the `nscd` daemon? (e.g. `/etc/inid.d/nscd`) ?

**Comment by Guymer** [comment]
@gfyoung :
- yes, the commands to enable `ncsd` from @yurivict  require root; and
- the full path to the `nscd` service script is `/etc/rc.d/nscd` and the full path to the `nscd` binary is `/usr/sbin/nscd` (though this really should not be relevant).

**Comment by gfyoung** [comment]
> (though this really should not be relevant).

@Guymer : If you look at our code, we already have a section of logic for `nscd`.  Hence, I wanted to double check that we could just incorporate it into that section instead of writing custom logic for FreeBSD, hence the relevance.

**Comment by StevenBlack** [comment]
Thanks everybody!
