### ISSUE TITLE
cert source of phishing sites

### ISSUE THREAD

**Issue by k3s4** [StevenBlack/hosts#1571]
Hello,

can u please add following list as sources of hosts ? - https://hole.cert.pl/domains/domains.txt ?

https://www.cert.pl/news/single/ostrzezenia_phishing/
https://en.wikipedia.org/wiki/CERT_Polska

**Comment by dnmTX** [comment]
@k3s4 we already have reliable Polish List/Curators here: [KADhosts](https://github.com/PolishFiltersTeam/KADhosts)
Would advise you to discuss it with them,see if they willing to merge/combine them for better protection.
Oversight here is important in case of any issues/false-positives 👍

**Comment by StevenBlack** [comment]
Hi Kamil @k3s4 thank you for this suggestion.

Here's a preliminary breakdown: `hole.cert.pl` would add 3,585 new domains to our list.

```
$ ./ghosts -c https://hole.cert.pl/domains/domains.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 67,781
Bytes: 2.1 MB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://hole.cert.pl/domains/domains.txt
Domains: 10,577
Bytes: 230 kB
----------------------------------------
Intersection: 6,992 domains
```

**Comment by StevenBlack** [comment]
Kamil @k3s4 and Dan @dnmTX here's the TLD summary of `hole.cert.pl/domains/domains.txt`.

Dan @dnmTX I think a nice improvement to [`ghosts`](https://github.com/StevenBlack/ghosts) would be, summarize TLD of proposed lists, net of our main list.  In other words, a TLD summary of `hole.cert.pl/domains/domains.txt`, considering only the 3,585 domains that would be new.

```
$ ./ghosts -m https://hole.cert.pl/domains/domains.txt --tld
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://hole.cert.pl/domains/domains.txt
Domains: 10,577
Bytes: 230 kB
TLD tally:
   pl: 2,593
   com: 1,520
   eu: 1,130
   net: 840
   xyz: 595
   online: 442
   site: 374
   org: 216
   ru: 209
   info: 179
   me: 130
   space: 127
   live: 121
   fun: 109
   club: 93
   life: 92
   store: 84
   biz: 81
   at: 81
   icu: 77
   link: 75
   website: 74
   shop: 64
   cyou: 63
   pro: 61
   cc: 58
   casa: 58
   work: 57
   surf: 53
   su: 47
   pw: 43
   services: 41
   name: 41
   top: 41
   ir: 40
   tk: 37
   app: 35
   co: 32
   cf: 31
   ml: 29
   tech: 25
   host: 25
   ga: 25
   uno: 22
   digital: 19
   gq: 19
   cloud: 18
   in: 16
   art: 16
   cash: 12
   click: 12
   vip: 11
   it: 10
   today: 10
   us: 10
   page: 10
   io: 8
   news: 8
   id: 7
   bid: 7
   ink: 7
   bar: 7
   ng: 6
   de: 6
   money: 6
   br: 6
   cz: 6
   mobi: 6
   design: 6
   tr: 6
   ltd: 5
   support: 5
   press: 5
   group: 5
   so: 4
   cam: 4
   za: 4
   email: 4
   best: 4
   sh: 4
   dev: 4
   express: 4
   nl: 4
   contact: 4
   uk: 3
   ie: 3
   ca: 3
   world: 3
   au: 3
   pink: 2
   win: 2
   miami: 2
   ro: 2
   rw: 2
   rentals: 2
   my: 2
   consulting: 2
   cx: 2
   zone: 2
   pt: 2
   network: 2
   rest: 2
   vn: 2
   help: 2
   accountant: 2
   ch: 2
   guru: 2
   delivery: 2
   business: 2
   mx: 2
   vin: 2
   es: 2
   fit: 1
   clothing: 1
   tel: 1
   buzz: 1
   boutique: 1
   gg: 1
   finance: 1
   ceo: 1
   deals: 1
   capital: 1
   kim: 1
   care: 1
   technology: 1
   fitness: 1
   monster: 1
   blue: 1
   holdings: 1
   run: 1
   lol: 1
   tools: 1
   to: 1
   cat: 1
   bz: 1
   place: 1
   company: 1
   plus: 1
   cool: 1
   fyi: 1
   wiki: 1
   men: 1
   loan: 1
----------------------------------------
```

**Comment by StevenBlack** [comment]
For comparison, here is our current lists's TLD distribution.

```
$ ./ghosts --tld
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 67,781
Bytes: 2.1 MB
TLD tally:
   com: 33,859
   net: 7,466
   pl: 6,062
   eu: 1,461
   live: 1,185
   org: 972
   vn: 955
   info: 938
   biz: 917
   jp: 868
   xyz: 754
   ru: 705
   life: 589
   io: 517
   de: 499
   site: 472
   online: 426
   uk: 415
   co: 370
   nl: 370
   cn: 316
   fr: 265
   me: 260
   at: 257
   in: 243
   club: 206
   us: 201
   tv: 184
   space: 179
   icu: 171
   fun: 165
   top: 155
   pro: 153
...  < SNIP >
```

**Comment by dnmTX** [comment]
Steve @StevenBlack  i see what you mean,and in any other case this would be a good idea to summarize the TLD's,but...

> considering only the 3,585 domains that would be new

....not when it comes to phishing/malware sites where onliest rule is: **no rules applied**
Every hour on the hour they coming out whith more and more weird as s**t TLD's. ( *.lol   *.fitness   *.blue and so on)
I actually started to harden my system and luckily **dnsmasq** has the ability to do TLD wildcard blocking(among other things)
so i've been monitoring numerous lists just for that reason and if i show you what i've got so far you'll be amused.
So in this particular case i have to disagree with you and caution you not to compare it this way when it comes to phishing/malware.

P.S. I still stand by my first post the list offered here to be merged with KADhosts in order to be supervised/curated.

**Comment by StevenBlack** [comment]
Dan @dnmTX I think I have to point out Poland is a country of 37 million educated people positioned in a very intersecting juncture.

That's like saying, "*we already have one list from Canada, join them*" or "*We already have a list from the Southwest USA.  Work with them*" and to my mind that sounds absurd.

I think we evaluate all potential lists based on their merits.  And I propose we consider their origin as a distinct asset, not a cause for liability, *per se*.

**Comment by StevenBlack** [comment]
Dan @dnmTX I think it's useful to clarify, here is how I use the TLD breakdowns.

* I look at the top 10 or 20 or thirty TLDs.  What are the distribution of those?  Does that distribution make sense.  Does that distribution include `.ru` and `.cn` where I know we are weak.
* Then I look at the verry bottom of the list.  That's where glaring mistakes are typically found.  Looking at those 1 and 2-domain TLDs tells me a lot about the curation quality of the list, particularly if I find nonsense there.

I never look at the TLD list as a whole.  At least, never so far.  I look for trends and biases.

**Comment by dnmTX** [comment]
True!!! Poland=Big Country,one list obvously can't solve/protect all the users there.
My onliest concern is,what do we do when false-positives start popping up,accompanied with demending crybabies?

**Comment by dnmTX** [comment]
> particularly if I find nonsense there...

Steve @StevenBlack  define nonsense. Again,when it comes to malware sites and their TLD's as of late,it's realy hard for me to make sense to be honest but unfortunatelly that's the world we live in,so i have to roll with it.

**Comment by dnmTX** [comment]
Steve @StevenBlack:

> That's like saying, "we already have one list from Canada, join them" or "We already have a list from the Southwest USA. Work with them" and to my mind that sounds absurd.

Yes,it does sound selfish,to say the least but HERE...**OP** is just asking to include the list and he's not in any way associated
with it(aka owner/cuartor). 
So,i don't think this logic should be applied here,right?

**Comment by StevenBlack** [comment]
I think it's probably best if we don't judge, and presume best intentions.  It's another list to consider.  I think we should evaluate the list on its merits, and by what it brings, balanced by its risks, which we haven't really identified except hypothetically.

There has to be a history of mindful curation, and someone we can contact directly when issues arise.  OP didn't include this information, or much at all beyond "*please add following list as sources of hosts*".

Kamil @k3s4 what more can you tell us about the list you suggest?

**Comment by dnmTX** [comment]
**AMEN** 🎈 😃

**Comment by k3s4** [comment]
to be honest I didn't know before opening this issue that there is included something like "KADhosts" 
it looks like CERT hosts list should be included in KADhosts but it looks different actually..

```
$ ./ghosts -m https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt -c https://hole.cert.pl/domains/domains.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
Domains: 18,873
Bytes: 543 kB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://hole.cert.pl/domains/domains.txt
Domains: 10,581
Bytes: 230 kB
----------------------------------------
Intersection: 7,064 domains
```

in general I think CERT hosts list is solid and informations like how to remove false-positive etc is here - https://www.cert.pl/news/single/ostrzezenia_phishing/

**Comment by scafroglia93** [comment]
*info ->

this list is already covered by nextdns threat intelligence feeds

**Comment by ClusterByte-x** [comment]
[KAD](https://kadantiscam.netlify.app/)  already includes the CERT Poland list. The only reason to use the CERT direct list is the fast response and update time of 5 minutes. The list is co-created by Polish mobile operators such as Orange, Plus, T-Mobile and Play and the governmental organization [NASK](https://en.nask.pl/) ([.pl registrar](https://www.dns.pl/en/)). This is a really solid list with clear rules - phishing only.

**Report page:** https://incydent.cert.pl/#!/lang=en
**Contact e-mail:** cert@cert.pl/info@cert.pl

**Comment by krystian3w** [comment]
The second reason could be that CERT does not remove domains as they fall in WHOIS (deleted only 58 requests).

**Comment by mimi89999** [comment]
@StevenBlack Could you please reconsider adding `hole.cert.pl` source? It's true that it's already included in `KADhosts`, but the list is updated every 5 minutes and `KADhosts` syncs with it only every 4 hours. Considering the lifetime of phishing sites, 4 hours is way to long.

**Comment by krystian3w** [comment]
IMO this repo aslo can not handle automate updates on every 5 minutes (up to 288commits at day).

**Comment by StevenBlack** [comment]
@mimi89999 @krystian3w anyone can fork this repo and update the hosts list, and variants, as often as the want, or need.

You can do that several times per minute, if that's what you need.

We're in the business of providing moderated, curated, sensible hosts files for a wide audience for basically all devices.

But if you need to, fill your boots.

**Comment by krystian3w** [comment]
But DNS services may no support import own hosts file instead long time ago added your.
