### ISSUE TITLE
[whitelist] bet365.com

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1572]
this betting site was blocked by this list (info taken from nextdns log)

**Comment by dnmTX** [comment]
@scafroglia93 you need to forward your request for removal to `hosts@someonewhocares.org`

**Comment by StevenBlack** [comment]
Hi Lorenzo @scafroglia93 Dan Pollock at `someonewhocares.org` will be able to say why the `bet365.com` is blocked. Dan is normally very responsive.

Looking at activity from loading the `bet365.com` home page I can't immediately identify why it's blockable.

We block it, of course, in our gambling lists.

**Comment by scafroglia93** [comment]
I proceeded with the manual whitelist; we can close if it is not possible to proceed

**Comment by StevenBlack** [comment]
Closing.
