### ISSUE TITLE
add clubhouse to social block list.

### ISSUE THREAD

**Issue by Mlocik97** [StevenBlack/hosts#1574]

**Comment by StevenBlack** [comment]
Thanks @Mlocik97 

Ping @sinfonietta (who's our social list curator), thank you!

**Comment by dnmTX** [comment]
Steve @StevenBlack you mind sharing the color code of the label here. Thanks 👍

**Comment by StevenBlack** [comment]
Here you go Dan @dnmTX 

![2021-03-13_21-26-26](https://user-images.githubusercontent.com/80144/111055353-0070cd80-8443-11eb-98a8-e4af9ee0f86b.jpg)

**Comment by dnmTX** [comment]
Much Appreciated 👍  😄

**Comment by Mlocik97** [comment]
@dnmTX I will give you one tip... you can open chrome dev tools, and there is color picker or You can see background-color in "Computed" after selecting element.

**Comment by Lateralus138** [comment]
@Mlocik97 Also, if anyone is interested in 3rd party trusted software; Gpick in Linux or Colorpic in Windows (or AutoHotkey, if you script in that). Don't touch Mac often so can't tell about trusted software there.

**Comment by Sinfonietta** [comment]
What domains to add here?  I don't use Clubhuse.

**Comment by dnmTX** [comment]
@Sinfonietta start with those and hopefully @Mlocik97 will provide some feedback:
`joinclubhouse.com`
`www.joinclubhouse.com`
`welcome.joinclubhouse.com`
`community.joinclubhouse.com`
`staging.joinclubhouse.com`
`admin-staging.joinclubhouse.com`
`ios.joinclubhouse.com`
`testflight.joinclubhouse.com`

**Comment by Sinfonietta** [comment]
@StevenBlack @Mlocik97 I have added these domains to socialhosts.

**Comment by StevenBlack** [comment]
Closing!
