### ISSUE TITLE
MS Onedrive Sign-in.

### ISSUE THREAD

**Issue by Quorum75** [StevenBlack/hosts#1575]
With the latest update I cannot Sign-in into Onedrive application on my Mac anymore. 

Deleting the Host file is the only solution I found at the present time. 

Thanks.

**Comment by dnmTX** [comment]
@Quorum75 which version of the list here you're using? Provide the exact link please.

**Comment by StevenBlack** [comment]
Thanks for this @Quorum75. 

There's really not enough information provided here.

Closing.
