### ISSUE TITLE
New telemetry.

### ISSUE THREAD

**Issue by D0n-A** [StevenBlack/hosts#1576]
Hello! Found an [interesting ](https://raw.githubusercontent.com/tlvince/hosts/gh-pages/hosts)hosts file. It is already obsolete and based on your work, but there are new entries to add, I guess. For example, Nokia's telemetry blocking can be considered. Thanks.

**Comment by StevenBlack** [comment]
Hi Dmitrey @D0n-A, thank you for this.

I'm going to decline this suggestion because I can't verify the validity of any changes made there.

Closing.
