### ISSUE TITLE
Please add these Serbian ad hosts

### ISSUE THREAD

**Issue by kalehrl** [StevenBlack/hosts#1578]
Please block these hosts:
```
adrs.hit.gemius.pl
gars.hit.gemius.pl
hrgde.adocean.pl
ringierrs.adocean.pl
rs.adocean.pl
```
I tested them and didn't notice any adverse effects.
Thank you

**Comment by StevenBlack** [comment]
Thank you for these @kalehrl.

I'm in no position to assess these, and you provide no actionable context.

Also `.pl` is the country code for Poland, not Serbia.  But what's 800 km, right?  500 miles.  Three, maybe four countries between them.

**Comment by kalehrl** [comment]
That's no problem. It's all Slavland. :)
In all seriousness, I used an Android phone with Adaway and your hosts.
Your default hosts got rid of all the ads within the Serbian news app Blic owned by Ringier Axel Springer.
However, some news articles are from external sources so that's where I found some ads whose hosts I analyzed using Adaway and put them in my block list. I rebooted the phone and tried the same news and, voila, the ads disappeared.
I can now remove the hosts from my personal block list.
Thank you.

**Comment by krystian3w** [comment]
> Maybe the app was developed by Polish programmers.

Rather German programmers.

---

adocean = gemius = international (a lot of sites use this)

---

Also `.pl` tls is cheap so sometimes it's better to buy one than to go with `.live`.

**Comment by StevenBlack** [comment]
I'm going to close this.  I'm not interested in carrying these since there's no backing.
