### ISSUE TITLE
How can I use hosts file to my router?

### ISSUE THREAD

**Issue by gordimr** [StevenBlack/hosts#1580]
Currently, I am using the hosts file on my Windows PC.
But I would like to expand that to all the devices connected to the router.
How can I do that?

**Comment by StevenBlack** [comment]
This is the first result when I Google [`hosts file on router`](https://www.google.com/search?q=hosts+file+on+router).  This is your answer.

https://security.stackexchange.com/questions/133043/modify-the-hosts-file-of-the-router-and-redirect-trafic

Closing.
