### ISSUE TITLE
[Blacklist] Microsoft Tracking

### ISSUE THREAD

**Issue by abhigupta912** [StevenBlack/hosts#1582]
Please include the following from [Notebook Review Forums](http://forum.notebookreview.com/threads/windows-10-tweaks-and-fixes-index-post-1.779394/page-106#post-10996820):

0.0.0.0 a-0001.a-msedge.net
0.0.0.0 bingads.microsoft.com
0.0.0.0 choice.microsoft.com
0.0.0.0 choice.microsoft.com.nsatc.net
0.0.0.0 compatexchange.cloudapp.net
0.0.0.0 corp.sts.microsoft.com
0.0.0.0 corpext.msitadfs.glbdns2.microsoft.com
0.0.0.0 cs1.wpc.v0cdn.net
0.0.0.0 df.telemetry.microsoft.com
0.0.0.0 diagnostics.support.microsoft.com
0.0.0.0 i1.services.social.microsoft.com
0.0.0.0 i1.services.social.microsoft.com.nsatc.net
0.0.0.0 oca.telemetry.microsoft.com
0.0.0.0 oca.telemetry.microsoft.com.nsatc.net
0.0.0.0 pre.footprintpredict.com
0.0.0.0 redir.metaservices.microsoft.com
0.0.0.0 reports.wes.df.telemetry.microsoft.com
0.0.0.0 services.wes.df.telemetry.microsoft.com
0.0.0.0 settings-sandbox.data.microsoft.com
0.0.0.0 sqm.df.telemetry.microsoft.com
0.0.0.0 sqm.telemetry.microsoft.com
0.0.0.0 sqm.telemetry.microsoft.com.nsatc.net
0.0.0.0 statsfe1.ws.microsoft.com
0.0.0.0 statsfe2.update.microsoft.com.akadns.net
0.0.0.0 statsfe2.ws.microsoft.com
0.0.0.0 survey.watson.microsoft.com
0.0.0.0 telecommand.telemetry.microsoft.com
0.0.0.0 telecommand.telemetry.microsoft.com.nsatc.net
0.0.0.0 telemetry.appex.bing.net
0.0.0.0 telemetry.appex.bing.net:443
0.0.0.0 telemetry.microsoft.com
0.0.0.0 telemetry.urs.microsoft.com
0.0.0.0 vortex-sandbox.data.microsoft.com
0.0.0.0 vortex-win.data.microsoft.com
0.0.0.0 vortex.data.microsoft.com
0.0.0.0 watson.live.com
0.0.0.0 watson.microsoft.com
0.0.0.0 watson.ppe.telemetry.microsoft.com
0.0.0.0 watson.telemetry.microsoft.com
0.0.0.0 watson.telemetry.microsoft.com.nsatc.net
0.0.0.0 wes.df.telemetry.microsoft.com
0.0.0.0 www.bingads.microsoft.com

**Comment by dnmTX** [comment]
**Duplicates:**
`bingads.microsoft.com`
`reports.wes.df.telemetry.microsoft.com`
`sqm.telemetry.microsoft.com`
`statsfe2.ws.microsoft.com`
`telecommand.telemetry.microsoft.com`
`telemetry.appex.bing.net`
`vortex.data.microsoft.com`
`watson.telemetry.microsoft.com`
`wes.df.telemetry.microsoft.com`

**NXDOMAINs:**
`compatexchange.cloudapp.net`
`i1.services.social.microsoft.com.nsatc.net`
`oca.telemetry.microsoft.com.nsatc.net`
`statsfe2.update.microsoft.com.akadns.net`
`telecommand.telemetry.microsoft.com.nsatc.net`
`watson.telemetry.microsoft.com.nsatc.net`

**Comment by Zyt3x** [comment]
Microsoft relies on eSIM and there exists a 0000:0000:0000:0000. It's so stupid. Google uses cookies as backup, that's why Android still works.

Un, de, do. I'm Ōnō.

**Comment by Zyt3x** [comment]
| telemetry.appex.bing.net:443

Delete that.

**Comment by dnmTX** [comment]
Time to **BAN** the **TROLL** Steve @StevenBlack  🔨 (knock it down 😈 )
