### ISSUE TITLE
request whitelisting for hbbtv.mediaset.net

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1583]
is it possible to know why the following domain is blocked?

I opened a report but it was not taken care of, closed without a reason

**Comment by scafroglia93** [comment]
The service is necessary to enable multimedia functions within the satellite / digital terrestrial channels of the Italian broadcaster Mediaset

HBBTV -> Hybrid Broadcast Broadband TV
https://www.hbbtv.org/

**Comment by StevenBlack** [comment]
Hi Lorenzo, thanks for this.  I'm sorry it's quite possible I was unclear.  Let me try to be crystal clear.

I'm not accepting single-domain issue submissions here unless it's absolutely vital to list it — in other words, malware that urgently needs to be blocked, only.

Single domain issues don't workflow well.  They don't scale.  A single domain issue takes as much time to assess as a 20-domain issue.

I just don't have the cycles, and I don't have the bandwidth.

Please submit this to one of our list curators, who are perhaps better set-up to deal with single-domain issues.

Closing.
