### ISSUE TITLE
[new source]  scafroglia93 blocklists 

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1585]
I ask if it is possible to enter my malware list; it has been completely revised with a complete check to avoid false positives

It is currently used by notracking and oisd

https://github.com/scafroglia93/blocklists/blob/master/blocklists-main.txt

thanks

**Comment by StevenBlack** [comment]
Thanks Lorenzo @scafroglia93.  What's the licensing on this list?

**Comment by StevenBlack** [comment]
The basic [ghosts](https://github.com/StevenBlack/ghosts) summary
* 42,497 domains
* Under one percent intersection. 0.0083

```
$ ./ghosts -c https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 67,313
Bytes: 2.0 MB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt
Domains: 42,497
Bytes: 911 kB
----------------------------------------
Intersection: 353 domains
```

**Comment by StevenBlack** [comment]
Using [ghosts](https://github.com/StevenBlack/ghosts) to summarize TLD in this list.

```
$ ./ghosts --tld -m https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt
Domains: 42,497
Bytes: 911 kB
TLD tally:
   com: 27,683
   net: 2,111
   org: 1,463
   tk: 983
   us: 907
   xyz: 776
   pw: 587
   info: 520
   ng: 495
   biz: 475
   co: 460
   top: 430
   space: 423
   in: 399
   ru: 322
   uk: 285
   website: 260
   site: 252
   online: 229
   club: 154
   ml: 147
   gdn: 141
   ga: 126
   io: 114
   de: 113
   eu: 112
   cf: 107
   pro: 97
   icu: 92
   gq: 90
   br: 87
   me: 85
   it: 82
   fun: 77
   nl: 74
   za: 52
   mobi: 49
   au: 48
   live: 47
   at: 41
   pl: 40
   fr: 39
   ca: 38
   vn: 37
   cc: 36
   tech: 36
   su: 33
   es: 33
   asia: 32
   host: 32
   cl: 31
   cn: 30
   ug: 27
   jp: 27
   ro: 25
   ch: 24
   ir: 24
   pk: 23
   ua: 23
   onion: 22
   mx: 21
   ws: 20
   my: 20
   hu: 19
   work: 19
   trade: 17
   services: 17
   se: 16
   best: 15
   gr: 15
   to: 15
   email: 15
   store: 14
   today: 14
   id: 14
   click: 14
   tr: 13
   cz: 13
   be: 13
   nz: 12
   sk: 11
   bid: 11
   tw: 11
   win: 11
   dk: 10
   life: 10
   tv: 10
   ke: 10
   casa: 10
   il: 10
   lt: 9
   one: 9
   download: 9
   shop: 9
   agency: 9
   exe: 9
   sa: 8
   ar: 8
   lol: 8
   cloud: 8
   kr: 8
   red: 7
   monster: 7
   link: 7
   vip: 7
   date: 6
   bit: 6
   gg: 6
   sg: 6
   rs: 6
   ltd: 6
   kz: 6
   ae: 6
   pt: 5
   name: 5
   by: 5
   ly: 5
   cat: 5
   edu: 5
   th: 5
   city: 5
   center: 5
   ee: 5
   hk: 4
   press: 4
   hr: 4
   uz: 4
   no: 4
   nu: 4
   rocks: 4
   company: 4
   re: 4
   ec: 4
   si: 4
   stream: 4
   news: 4
   world: 4
   digital: 3
   tj: 3
   ma: 3
   network: 3
   ie: 3
   deals: 3
   app: 3
   fi: 3
   lk: 3
   bg: 3
   bz: 3
   am: 3
   pe: 3
   coupons: 3
   xn--p1ai: 3
   ne: 2
   review: 2
   mn: 2
   science: 2
   lv: 2
   ba: 2
   np: 2
   kg: 2
   mk: 2
   surf: 2
   mm: 2
   pet: 2
   uy: 2
   hosting: 2
   durban: 2
   ms: 2
   cm: 2
   group: 2
   im: 2
   band: 2
   llc: 2
   kh: 2
   md: 2
   ooo: 2
   fund: 2
   so: 2
   tips: 2
   accountant: 2
   cash: 1
   ve: 1
   restaurant: 1
   jpg: 1
   bn: 1
   gratis: 1
   ccn: 1
   bd: 1
   bet: 1
   business: 1
   st: 1
   dat: 1
   uno: 1
   is: 1
   xn--6frz82g: 1
   team: 1
   comh: 1
   gmbh: 1
   pa: 1
   garden: 1
   pub: 1
   srl: 1
   zw: 1
   or: 1
   gd: 1
   graphics: 1
   support: 1
   photos: 1
   comt: 1
   cab: 1
   health: 1
   gallery: 1
   buzz: 1
   des: 1
   shopping: 1
   works: 1
   guru: 1
   studio: 1
   az: 1
   faith: 1
   eg: 1
   futbol: 1
   af: 1
   cool: 1
   dz: 1
   navy: 1
   php: 1
   tm: 1
   cr: 1
   consulting: 1
   tube: 1
   sale: 1
   ls: 1
   vc: 1
   liv: 1
   xy: 1
   insure: 1
   odns: 1
   expert: 1
   global: 1
   education: 1
   art: 1
   cruisecouns: 1
   finance: 1
   inteleksys: 1
   photo: 1
   moe: 1
   lc: 1
   bar: 1
   ph: 1
   mv: 1
   bargains: 1
   ovh: 1
   xin: 1
   coml: 1
   guide: 1
   aero: 1
   coffee: 1
   tz: 1
   ac: 1
   rent: 1
   partners: 1
   ge: 1
   sh: 1
   tn: 1
   fj: 1
   games: 1
   events: 1
   blue: 1
   game: 1
   miami: 1
   mz: 1
   arpa: 1
----------------------------------------
```

**Comment by StevenBlack** [comment]
The **Intersection**.

```
$ ./ghosts -c https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt --intersection
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 67,313
Bytes: 2.0 MB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt
Domains: 42,497
Bytes: 911 kB
----------------------------------------
```
intersection: [12724.xyz 15438.xyz 21736.xyz 2no.co 4ourkidsky.com 4w6ylniamu6x7e3a.onion 5frjkvw2w3wv6dnv.onion acccountsgoog1e.com account-mail.info accountapp.xyz accountsgoog1e.com addahealingmusic.com adfuture.cn adobestats.com adroitpmps.com adsunflower.com afsasdfa33.xyz aiisa.am airjaldinet.ml alexandr01299.xyz alibaba.zzux.com alpinehandlingsystems.com ambirsr.tk api-resource.youzicheng.net api-rssocks.youzicheng.net aplsolutionsonline.com apoolcondo.com app.hkrevolution.club app.poorgoddaay.com appledaily.googlephoto.vip areyouabot.net armconsul.ru artizaa.com atnimanvilla.com au-ul.com au-xm.com auth-google.site auth-mail.email backgrounds.pk badoo-account-security.com bank-japanposst.jp bank-japanpost.com bank-japanpostjp.com bank-japanpostpo.jp behlenjoiner.com blockchainjoblist.com bmy.hqoohoa.com bodenstein.co.za bralibuda.com brightmega.com brightonrooms.co.uk broadpeakdefense.com brotherselectricco.com bslines.xyz bur.vueleslie.com busyserviceinc.com byte.inteleksys.com carnataldez.ml cdn.doublesclick.me changematterscounselling.com check-activity.com.ru chefeladlevi.com chrome-redirect.top cleanbydesignllc.com clooinfor.cf cloud.newsofnp.com com-auth.site com-enter.site com-gm.site com-google.site comericac.com compdate.my03.com coulsongraphics.com currantmedia.com customernoble.com dabmaster.wm01.to danangluxury.com dandyair.com davethompson.me.uk dbuhcbudyu.tk ddl.okgoodmobi.com deepikarai.com dentalsearchsolutions.com desktest1.xyz desktest5.xyz desktest9.xyz detorre.es dev.medialogistics2020.ca digitaltextile.com.ru dirproperties.com dlee889.mywire.org dokerest.xyz dokertest.xyz drive.staticcontent.kz droinjoin.xyz dw.adyboh.com edisonlee.net emails-support.site eom-nv.com epos-ua.com equilibrios.ga ergensu.com ewills.access.ly exchange.longmusic.com exilum.com facebooktoday.cc faraweel.com feb.kkooppt.com fedortest.xyz feylibertad.org files-downloads.com flixprice.com fly-analytics.com followergods.com freekremlin.com freetospeak.me fresh.ygto.com frosdank.com frostdank.com garant-help.com gcesab.com general-lcfd.com globalpagee-prod-webex.com gmail-warning.top go.onclasrv.com godoycrus.com goldenlion.sg google-activity.pw googlephoto.vip greenheartmed.org gucinowertr.tk gvoice8765.online gwiza1988.hopto.org haus-pesjak.at hitstation.nl hkrevolt.com home-storages.com hostfleek.com hotelkrome.com hpphhpph.com hrcorp1.site id-support-email.com ident.me ikexpert.com innovativemasonry.net inps-informa.online integer-ms-home.com inter1ads.com iuiuytrytrewrqw.gq jamshed.pk jannahqu.org japanp0st.jp jeddahcrumbly.com jibun.jp-bankq.com jintsung.cn jnachb.com jnb.jp-bankq.com jocoly.esvnpe.com joindroin.xyz jp-bamk.jp jp-bank-japanossts.jp jppost.jp-bankq.com keqiang.pro kkjjhhdff.site knalc.com koapkmobi.com lamatrest.xyz latamdcs.com lay.dubya.us ledampenergy.net lidoraggiodisole.it limkon.com load.collegesmooch.com localdates19.com loginwebmailnic.dynssl.com loneeaglerecords.com lp.cooktracking.com maceju.com magento-analytics.com mahalowood.com mail-auth.email mail-auth.online mail-google.email marketium.com matpincscr.com maymaychihai.com messager.cloud microcomm-group.com microsoft-live-us.com mioniough.com mktf.mx mnp.nkr.am motivation.neighboring.site motorcomunicacion.com movbmog.ga movie.poorgoddaay.com ms-break.com ms-home-store.com ms-rdt.com ms-upgrades.com mufg.jp-bankq.com murthydigitals.com mutlukadinlarakademisi.com my-short.com myaccount-support.top myamystills.com mybetterdl.com mycabinet.xyz mynavvfedera1.org mynavyfedera1.org mynavyfedral.org mynevyfedera1.org namilh.com nautcoins.com navyfedara1.org navyfedera1.com navyfedera1.org navyfederai.org nayfedera1.org nevyfedera1.org new.915yzt.cn news-deck.at news.hkrevolt.com news.hkrevolution.club news.poorgoddaay.com news2.hkrevolution.club newsha.jsonland.ir newtontool.ca nitroqensports.eu nomadztruck.com nordfreevpn.com novmintservices.com ns1.poorgoddaay.com nsdns.xyz nttdocomo-uh.com nttdocomo-xm.com nuwagi.com nvfjvtntt.cf oderstrg.site onclickmega.com online-office365.com onms-home.com optimus.com.sg osheoufhusheoghuesd.ru overcreative.com phamchilong.com poxypoxy.xyz praisesalways.ddns.net primecaviar.com priv.inteleksys.com ptgteft.com rakuten.jp-bankq.com ravenproductionsltd.com rc-room.com romashka.cn ronnietucker.co.uk ronswank.com roshnijewellery.com rossogato.com ruisgood.ru run-germany.com sacredscentsonline.com safetb-amazon.jp safety-amazon.jp saidialxo.com sales.inteleksys.com santyago.org saxtorph.net sbi.jp-bankq.com security-amazon.jp seven.jp-bankq.com shivakunwar.com.np shop.inteleksys.com skategirlchina.com skylarstetten.com smbc.bk-securityo.com smbc.jp-bankq.com spy.cashnow.ee ssl.newsofnp.com stagolk.com start.apiforssl.com startupforbusiness.com static.doublesclick.info status.search-sslkey-flush.com stillval.com sukhumvithomes.com sunflagsteel.com support-emails.host svr.hkrevolution.club sweet-diet.com switchnets.net t.grtyb.com t1bank.xyz tabxolabs.com taltus.co.uk tempinfo.96.lt testdhome1.xyz testdhome4.xyz testdom1.xyz testdom3.xyz testfor7.xyz tewoerd.eu thaivictory.co.th thediscoveryrun.com thiccnigga.me think1.com thumbeks.com ti.domainforlite.com ts3cardd.com tvjovem.net ubntrooters.serveuser.com ufz.doesxyz.com ultraeventgroup.com unclebillswv.com upgrade-ms-home.com upiserversys1212.com urldelivery.com uu.domainforlite.com uy6x.c3y5-tools.com vanscheers.com vhguyeu.ml view.inteleksys.com vkontak1e.com voice98765.online vpn4test.net warzone.io warzone.pw warzonedns.com wawa.cleansite.us webpresario.com whia7g.acquafufheirybveru.online wind.windmilldrops.com windows-avs-update.com windows-en-us-update.com windows-se-update.com wishesconcierge.com ws38.watashinonegai.ru wy.adyboh.com xizr.inteleksys.com xn--avyfedera-yubm.org xn--bckchain-v3a30f.com xn--blckchain-17c.com xn--blockcain-lmb.com xn--mynavyfedera-occ.org xn--navyfderal-36a.com xn--navyfedera-j0b.org xskcjzamlkxwo.gq xyz.cashnow.ee yandex-account-security.com yeichner.com zg.poorgoddaay.com zh.yomobi.net zvatrswtsrw.ml]
```
Intersection: 353 domains
```

**Comment by StevenBlack** [comment]
This feels very sketch.  The sub 1% intersection rate is implausible.

**Comment by StevenBlack** [comment]
This list contains 4536 `webcindario.com` domains.  That's 10% of this list.  In our base list we currently have four `webcindario.com` domains.

So we up the `webcindario.com` domains by a factor of 1134, or 113,400 percent.

```
$ curl https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt | grep webcindario | wc -l

    4536
```

**Comment by StevenBlack** [comment]
Lorenzo @scafroglia93 thank you for this, but I decline for the reasons elucidated above.

Closing.
