### ISSUE TITLE
4OD - https://www.channel4.com/

### ISSUE THREAD

**Issue by thebeanieman** [StevenBlack/hosts#1590]
Hello,

If you add this to the host file:
cdn.http.anno.channel4.com

The adverts at the start and in the middle of videos just get skipped :)

You can test with this:
https://www.channel4.com/programmes/ramsays-kitchen-nightmares/on-demand/38532-001

I have just setup Pi-Hole, I thought I would try block the videos loading on 4OD and was amazed how easy it is!

Thanks,
David

**Comment by StevenBlack** [comment]
Hi @thebeanieman  – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
