### ISSUE TITLE
More tracking domains seen on German sites

### ISSUE THREAD

**Issue by KommX** [StevenBlack/hosts#1591]
As a follow-up of #1558 I want to add more domains to the blocklist. They are ordered by main site I've seen them on.

The subdomains of `s400.meetrics.net` seem to be pretty numerous. I think it's a safe bet that we could add lbX.s400.meetrics.net with x \in [1-99].

welt.de
- p.vtracy.de
- www.asadcdn.com
- adstax-cdn.adrtx.net
- lmyd3iz3qn.kameleoon.eu

apotheken-umschau.de
- logs1407.xiti.com
- s400.mxcdn.net
- lb7.s400.meetrics.net
- lb70.s400.meetrics.net
- lb73.s400.meetrics.net
- lb74.s400.meetrics.net
- lb79.s400.meetrics.net
- pdw-usr.userreport.com

heise.de
- eu-tlp04.kameleoon.eu
- eu-tlp06.kameleoon.eu
- eu-tlp07.kameleoon.eu

golem.de
- lb5.s400.meetrics.net
- lb9.s400.meetrics.net
- lb13.s400.meetrics.net
- lb30.s400.meetrics.net
- lb49.s400.meetrics.net
- lb50.s400.meetrics.net
- lb62.s400.meetrics.net
- lb76.s400.meetrics.net
- lb78.s400.meetrics.net
- lb86.s400.meetrics.net
- lb90.s400.meetrics.net
- lb96.s400.meetrics.net

spiegel.de
- bls.adalliance.io
- traffic.emsservice.de
- static.emsservice.de
- te.technical-service.net

**Comment by StevenBlack** [comment]
Thanks @KommX I've added these in commit 777ffdea9.

Closing.
