### ISSUE TITLE
[Blacklist] Malware apps from Android devices

### ISSUE THREAD

**Issue by SaberAkiyama** [StevenBlack/hosts#1593]
List of malware sites:

```
wewjyw.qb6ges.com
cf.zcnewy.com
wscdn.xiaoshuzhan.net.whecloud.com
wscdn.xiaoshuzhan.net
vgl8ku.miccuu.com
cu.smaxdn.com
report.smaxdn.com
apply.smaxdn.com
tcq.xinfu300.com
ppp.xxpwgxx.com
```

Update: There is another malware sites as well.

```
qqq.xxpwgxx.com
www.bullishlifer.com
www.eternitynostalgia.com
www.cakgopfw892.com
```

**Comment by dnmTX** [comment]
`wewjyw.qb6ges.com`: expired(still resolves though)
The rest all have high VirusTotal detection. 
Steve @StevenBlack let me know if you want me to add whatever else i can find on each of them 👍

**Comment by SaberAkiyama** [comment]
> `wewjyw.qb6ges.com`: expired (still resolves though)
> The rest all have high VirusTotal detection.
> Android based indeed, @jawz101 might be interested adding them instead(just suggesting here).
> Steve @StevenBlack let me know if you want me to add whatever else i can find on each of them 👍

Sometimes, this sites was a false positive several years ago.

**Comment by StevenBlack** [comment]
Thanks Abdul @SaberAkiyama.  

Thanks Dan @dnmTX.  TBH I'm increasingly wary of justification-free incoming.   Maybe @jawz101 wants these, I sure don't, because there's no basis.

Closing.

**Comment by SaberAkiyama** [comment]
> Thanks Abdul @SaberAkiyama.
> 
> Thanks Dan @dnmTX. TBH I'm increasingly wary of justification-free incoming. Maybe @jawz101 wants these, I sure don't, because there's no basis.
> 
> Closing.

I don't think, @jawz101 didn't response to malicious apps from Android.

**Comment by jawz101** [comment]
I hadn't seen this issue until now.  Sorry about that.  Where did this list come from?

**Comment by SaberAkiyama** [comment]
> I hadn't seen this issue until now. Sorry about that. Where did this list come from?
> 
> I don't want the Adaway list to include mobile malware domains unless no other list blocks them and including those domains would serve the better good.
> 
> Otherwise, it's nice to have Adaway be about mobile ads & trackers period. Plus, I imagine malware domains aren't necessarily going to stick around long once they're figured out.

@jawz101 I see. Thanks for info about a malware apps. I guess I breakthrough the freaking annoying adware.

**Comment by jawz101** [comment]
@SaberAkiyama I thought about it more and I think the distinction is "I want to use this app/game.  I'll just block the ads & trackers."  Whereas malware is "Oh crap!  This is malicious! uninstall!"


I think would be nice to have a list for protection but it could be a mobile malware list instead of ads & trackers.  And if someone wants to make a list like that I think it would be awesome.  I don't think I could keep up with that.

**Comment by SaberAkiyama** [comment]
> I hadn't seen this issue until now. Sorry about that. Where did this list come from?

This list is from self installation application without any permission, and that's why you asked to block this list.
