### ISSUE TITLE
updateHostsFile.py throws exceptions when excluding domains from custom whitelist

### ISSUE THREAD

**Issue by sr093906** [StevenBlack/hosts#1594]
When using updateHostsFile.py to exclude domains from custom whitelist file, several errors occurred as follows.

![1](https://user-images.githubusercontent.com/8369201/113505104-672f6580-956f-11eb-8d6c-bd17f7664b13.jpg)

This seems an issue related to decode function. 

The custom domains I use come from https://github.com/EnergizedProtection/unblock/blob/master/basic/formats/domains.txt

Thanks for help in advance.

**Comment by StevenBlack** [comment]
Not enough info to resolve.

`7804: Illegal multibyte sequence` is due to your input.  Change your input.

Closing.
