### ISSUE TITLE
.backblazeb2.com endpoints have been added back to the list, please remove them

### ISSUE THREAD

**Issue by jacktronics** [StevenBlack/hosts#1595]
backblaze hosts tons of files, like AWS S3, the same way we cannot blacklist all AWS endpoints because they host too much website, can we prevent these endpoints from being added again ? Their removal from this list has been requested earlier this year and they're back ...

**Comment by dnmTX** [comment]
Looks like there are two domains listed in KADhosts,but checking the upstream list they're not present there 🤔 

**ping** Steven @StevenBlack  for further action.

**Comment by StevenBlack** [comment]
Thanks @jacktronics and thank you Dan @dnmTX.

I'll run a release right now, which should fix this.  Standby.

**Comment by StevenBlack** [comment]
**Update**: Yup, the release, which I am committing right now, is backblazeless.

Closing.
