### ISSUE TITLE
Nox Player tracking 

### ISSUE THREAD

**Issue by JobcenterTycoon** [StevenBlack/hosts#1596]
After i opened the Nox Player i saw a few suspect Domains in my DNS logger (unblocked):

`tracking-3-9f58.trnox.com`
`trcakingapp.trnox.com`

after i searching i found the Nox player is full with tracking (unblocked):
`bi.yeshen.com`
`pubstatus.sinaapp.com`
`tracking.apptrackerlink.com`

Better to block this?

**Comment by StevenBlack** [comment]
Thanks @JobcenterTycoon.

@jawz101 you have a `trnox.com` domain already. Would you assess these, and list them at your discretion?  Thanks!

**Comment by jawz101** [comment]
I'll add them.  THanks!

**Comment by StevenBlack** [comment]
Thanks @jawz101!
