### ISSUE TITLE
I detected new spyware adress

### ISSUE THREAD

**Issue by paledega** [StevenBlack/hosts#1597]
I created spyware adress that not included in our hosts file. (I am using pi-hole dns server)
```
grs.dbankcloud.eu
pushs.euromsg.com
sdk-log.appclicking.com
connect-dre.hispace.hicloud.com
api.glb.samsung-gamelauncher.com
```

We must block

**Comment by StevenBlack** [comment]
Hi @paledega thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
