### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by nrogers64** [StevenBlack/hosts#16]
I noticed that updateHostsFile.py isn't compatible with Python 3. I think you should either mention this in the README or, preferably, update updateHostsFile.py so that it is compatible with Python 3.

**Comment by StevenBlack** [comment]
Thanks!  Feel free to submit a pull request :-)

**Comment by mjl152** [comment]
Pull request submitted https://github.com/StevenBlack/hosts/pull/20

**Comment by StevenBlack** [comment]
@mjl152 this is great Michael!  Thanks for the PR.  I'll test this locally and try to merge this shortly.

**Comment by StevenBlack** [comment]
@mjl152 when I try this using Python 2.7.10 I get the following error after replying 'n' to 'Do you want to exclude any domains?'

    <snip />
    Traceback (most recent call last):
      File "UpdateHostsFile.py", line 319, in <module>
        main()
      File "UpdateHostsFile.py", line 50, in main
        finalFile = removeDups(mergeFile)
      File "UpdateHostsFile.py", line 174, in removeDups
        for line in mergeFile.readlines():
    IOError: [Errno 9] Bad file descriptor    

I've installed the `Future` module and the related backports described in the [Python-Future Quick Start Guide](http://python-future.org/quickstart.html).

I'd like this to work in Version 2 and 3 and, while I intend to soon upgrade to Python 3, I don't want to Kill Python 2 functionality here.

Any ideas, Michael?

**Comment by StevenBlack** [comment]
@mjl152 Michael [here's the failing line](https://github.com/mjl152/hosts/blob/c9a09054125d678ec5ddf28e64ea8cd27fc835c5/updateHostsFile.py#L174) in updateHostsFile.py.

**Comment by mjl152** [comment]
What OS? 

My test version is 2.7.10 on Windows 10 x64. When I hit n at that prompt I get

    OK, we won't exclude any domains.

**Comment by StevenBlack** [comment]
@mjl152 I'm OS X Yosemite 10.10.5 (which is latest).

**Comment by mjl152** [comment]
@StevenBlack Just tested on the latest Ubuntu 15.04 x64, and it works fine there. Must be an issue with either OS X or your installation. I don't have a Mac to test on. Can you try removing the backports? Your link says only to install them if you are using Python 2.6.

**Comment by StevenBlack** [comment]
@mjl152 thanks Michael, I'll chase this down at this end.  Thanks for checking all those end points.

**Comment by StevenBlack** [comment]
We've got this now!

Closing.
