### ISSUE TITLE
[whitelist] sgqcvfjvr.onet.pl

### ISSUE THREAD

**Issue by gita6t5** [StevenBlack/hosts#1602]
Blocks video playback
https://vod.pl/programy-onetu/onet-opinie-renata-kim-dawid-ciermiega-104/jfdernq
![Zrzut ekranu z 2021-04-07 19-14-22](https://user-images.githubusercontent.com/80338577/113907504-baa2ed00-97d5-11eb-8e68-bd0abb98dab8.png)

**Comment by StevenBlack** [comment]
Hi @gita6t5 thank you for this.

The domain `sgqcvfjvr.onet.pl` comes to us via `someonewhocares.org`.  Please email your concern to hosts@someonewhocares.org.

**Comment by StevenBlack** [comment]
Closing.

**Comment by krystian3w** [comment]
Also EasyPrivacy block this subdomain.
