### ISSUE TITLE
[whitelist] get.x-link.pl sdk.privacy-center.org prodxnews1blob.blob.core.windows.net

### ISSUE THREAD

**Issue by gita6t5** [StevenBlack/hosts#1603]
Blocks video playback
https://koscierzyna.naszemiasto.pl/waldemar-b-byly-senator-oskarzony-o-znecanie-sie-nad-psem/ar/c1-8213337
![Zrzut ekranu z 2021-04-07 19-33-51](https://user-images.githubusercontent.com/80338577/113909651-356d0780-97d8-11eb-860a-b1452a894c97.png)

**Comment by StevenBlack** [comment]
Hi @gita6t5 thank you for this.

The domains `get.x-link.pl` and `prodxnews1blob.blob.core.windows.net` come to us via `someonewhocares.org`.  Please email your concerns to hosts@someonewhocares.org.

The domain `sdk.privacy-center.org` comes to us via AdAway.  Please post this domain in https://github.com/AdAway/adaway.github.io/issues

**Comment by StevenBlack** [comment]
Closing.

**Comment by krystian3w** [comment]
Also blocked by I don't care about cookies.
