### ISSUE TITLE
remove codecguide.com site from fakenews-gambling-porn

### ISSUE THREAD

**Issue by lucknaumann** [StevenBlack/hosts#1607]
Hi, I noticed the fakenews-gambling-porn list contains the codecguide.com site twice. I've downloaded the K-Lite Codec Pack for years from there. I just recently added this list to uBlock Origin, but I'm not sure why it's on any list. It's not fake news, gambling, or porn, or even malware. Thanks.

**Comment by dnmTX** [comment]
@lucknaumann good catch,definitely false-positive.
If you don't mind report this directly upstream for removal: https://github.com/Clefspeare13/pornhosts/issues
Thanks 👍
