### ISSUE TITLE
Proposal: white-lists handled as extensions

### ISSUE THREAD

**Issue by braian87b** [StevenBlack/hosts#161]
I think for example have an extension called google ads to be able to enable google ads domains list for avoid problems while using google analytics or google adwords... or facebook ads (have several problems on the web ui when using these lists.
The "whitelists extensions" could be contributed to this repo as pull requests.
Whats are your opinions about this?

**Comment by StevenBlack** [comment]
Ya I dig this idea.

Sorry it took so long to reply.

**Comment by GlassGruber** [comment]
That would be nice indeed! Also I think it would be handy to have in the generated file a list of whitelisted domains too (since whitelisting a single domain can result in multiple domains actually whitelisted).

**Comment by StevenBlack** [comment]
@GlassGruber Thanks for bringing this to my attention again.  I hope to hit this soon.

If not soon then rattle my chain again 😄

**Comment by stereokai** [comment]
@StevenBlack Is now a good time to rattle that chain again? 😆
