### ISSUE TITLE
`covid19.relief-fund.live`

### ISSUE THREAD

**Issue by strict-block** [StevenBlack/hosts#1610]
**`SamuelMwangiW`** wrote:

>The above domain is a scam that scams users by purporting to offer relief funds.
> They direct traffic to `thaudray.com`, a known scamming site

**Comment by StevenBlack** [comment]
Thank you @strict-block.

I'm going to need corroborating evidence to act on ths.

**Comment by strict-block** [comment]
for my side: comments are stillized to Facebook plugins also comments sections no support login to any social account, I suppose nobody add new comment sended by from under last comment.

> ![Screenshot_2021-04-12 COVID-19 RELIEF FUND](https://user-images.githubusercontent.com/79422224/114350563-a65e4780-9b69-11eb-9fef-49fe83b884ed.png) |
> ----

**Comment by StevenBlack** [comment]
Thanks for the additional information @strict-block.

I decline.

Closing.
