### ISSUE TITLE
`maxjob3.com`

### ISSUE THREAD

**Issue by strict-block** [StevenBlack/hosts#1612]
`http://maxjob3.com/`

Spam advertised that it was Google paying $17,000 - $23,000 a month to work from home.

Possible found in comments of many articles on the Internet.

**Comment by StevenBlack** [comment]
Hi @strict-block – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
