### ISSUE TITLE
non existent sites

### ISSUE THREAD

**Issue by AdKiller** [StevenBlack/hosts#1613]
I noticed there are some non existent sites in the hosts list. For example, the very first entry: n2019cov.000webhostapp.com

Is the list checked for non existent sites at all?
If not, what would be the best way to check that programmatically?

**Comment by StevenBlack** [comment]
Hi @AdKiller,

The domain `n2019cov.000webhostapp.com` exists 😄 see below.

Our friend Nissar @funilrys has some neat resources for checking these things.  See [funilrys/PyFunceble](https://github.com/funilrys/PyFunceble) for example.

```
$ dig n2019cov.000webhostapp.com

; <<>> DiG 9.10.6 <<>> n2019cov.000webhostapp.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41092
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;n2019cov.000webhostapp.com.	IN	A

;; ANSWER SECTION:
n2019cov.000webhostapp.com. 3599 IN	CNAME	us-east-1.route-1.000webhost.awex.io.
us-east-1.route-1.000webhost.awex.io. 60 IN A	145.14.144.89

;; Query time: 248 msec
;; SERVER: 192.168.21.10#53(192.168.21.10)
;; WHEN: Wed Apr 14 23:14:19 EDT 2021
;; MSG SIZE  rcvd: 121
```

Closing.

**Comment by AdKiller** [comment]
Just to clarify it says: 

Website is no longer available
The authors have deleted this site.
Start your website

**Comment by felix-22** [comment]
Feel free to open a feature request on https://github.com/funilrys/PyFunceble to detect `non-existent but still not dead` sites.
