### ISSUE TITLE
How to build a "re-googled" version?

### ISSUE THREAD

**Issue by luvicsoura** [StevenBlack/hosts#1614]
I have tried the basic host file and I have it's great to use as a regular user, however using it as a web developer dependent on google/facebook services --- mostly due to company's business requirements --- is annoying, at the very least. I'd like to know if there's an easy way to build a version of the host file that does not block google "tracking" and only blocks ads. I could fork the project, for sure, but I'd like to know if there's a better way before getting myself into a such a time consuming task.

**Comment by StevenBlack** [comment]
Hi Victor @luvicsoura I hear you, I've been in the same situation before, and it can be a pain.

I use [Hostile](https://github.com/feross/hostile) a lot and it's very handy if you want to remove a few domains from the hosts file.  This presumes you aren't on Windows.

Every list blocks Google and Facebook tracking so, to answer your question, not really possible to build that from the sources we use.

**Comment by StevenBlack** [comment]
Closing.
