### ISSUE TITLE
Please don't take sides on the horrible censuring political arena. Conservative news <> fake news.

### ISSUE THREAD

**Issue by CodeSapiens** [StevenBlack/hosts#1620]
Please remove **infowars.com** from your fakenews list. I will assume this was added by accident, and hope you have not turned political. Keep up the good work at blocking malicious stuff, but leave opinion regarding what is fake or not up to intelligent human beings to decide. Thanks.

**Comment by dnmTX** [comment]
@CodeSapiens refer to https://github.com/marktron/fakenews/issues to further discuss your issue with the upstream list curator

**Comment by StevenBlack** [comment]
@CodeSapiens here is a quote from the first paragraph of the [InfoWars Wikipedia article](https://en.wikipedia.org/wiki/InfoWars).  The article is based on 123 citations.  

> InfoWars is an American far-right conspiracy theory and fake news website owned by Alex Jones. It was founded in 1999, and operates under Free Speech Systems LLC.

I'm sorry, but you appear to be truly basic. Your epistemology is problematic. I recommend you consider addressing that.

cc @marktron

Closing.

**Comment by CplBDJ** [comment]
What about theblaze.com? The [wikipedia](https://en.wikipedia.org/wiki/Blaze_Media) article says nothing about fake news but it's on your list.
