### ISSUE TITLE
Domains for porn list

### ISSUE THREAD

**Issue by Ratemi** [StevenBlack/hosts#1621]
Hi! Can you add these sites to the porn list?

www.poringa.net
m.poringa.net
www.pornogratisdiario.com
tubepornstars.tv
tubepornstars.site
pornjuices.com
www.orgasmatrix.com
petardas.xxx
babosas.com
www.pornocasero.com.ar
www.xxxenespanol.com

Thanks!

**Comment by StevenBlack** [comment]
Thank you @Ratemi.

Ping @sinfonietta

**Comment by Sinfonietta** [comment]
These have been added @StevenBlack

**Comment by StevenBlack** [comment]
Thanks @Ratemi and @Sinfonietta.

Closing.
