### ISSUE TITLE
en.wikipedia.org blocked by comment in hosts file.

### ISSUE THREAD

**Issue by jgfam69qy2** [StevenBlack/hosts#1622]
Hi!
I am using the hosts file in a pi-hole and it seems that line 66888 in hosts has a comment pointing to the source of sitename that is not being treated as such.
The line reads
`0.0.0.0 oralse.cx  # en.wikipedia.org/wiki/List_of_shock_sites`
at the moment I am not certain if this is specific to the pihole engine or if there is a syntax problem.
will research further.

Steps to reproduce:
with the hosts file added to adlists in pihole, try `$dig en.wikipedia.org @pihole-ip` 

Workaround: 
Whitelist the en.wikipedia.org domain.

**Comment by jgfam69qy2** [comment]
Please disregard. linked to a different blocklist I did not check before that for some reason explicitly includes en.wikipedia.org

**Comment by StevenBlack** [comment]
Thanks John @jgfam69qy2 

The `#` character indicates a comment...
