### ISSUE TITLE
[whitelist] widget-mediator.zopim.com

### ISSUE THREAD

**Issue by jostyee** [StevenBlack/hosts#1625]
It blocks loading of zendesk chat widget.

<img width="337" alt="Screenshot 2021-04-23 at 10 27 53 AM" src="https://user-images.githubusercontent.com/88564/115809387-97577f00-a41e-11eb-86b8-3e6cb8ee1861.png">

**Comment by StevenBlack** [comment]
Thank you Josta @jostyee.

Domain `widget-mediator.zopim.com` comes to us via AdAway.  @jawz101 what do you think?

**Comment by jawz101** [comment]
removed.  thanks

**Comment by jostyee** [comment]
Thank you.

**Comment by StevenBlack** [comment]
Thank you Josta @jostyee and thanks, as always, @jawz101.
