### ISSUE TITLE
Stripe

### ISSUE THREAD

**Issue by jokr0815** [StevenBlack/hosts#1626]
Hi,
what do you think about adding m.stripe.com & js.stripe.com
I found cookies used by https://polylang.pro/
According to this page https://webcookies.org/cookies/m.stripe.network/21700171 it is grabbing same data...
Thanks
Jo

**Comment by StevenBlack** [comment]
Thanks for the suggestion @jokr0815.

We won't be blocking Stripe for cookies.  A specific subdomain perhaps, but not the whole thing.

Closing.
