### ISSUE TITLE
YouTube app not showing recently played videos

### ISSUE THREAD

**Issue by 1nekomata** [StevenBlack/hosts#1627]
some comment in this hosts file is somehow blocking the youtube app from updating the recently watched page. as soon as i use a different hosts file it works just fine

**Comment by StevenBlack** [comment]
Hi @1nekomata thank you for your observation.  This is an old issue, see #1379 ***Issues with YouTube history***

This is wontfix here, but you can always whitelist `s.youtube.com`.

Closing.

**Comment by 1nekomata** [comment]
ok didnt knew it was an old one. thank you a lot!
