### ISSUE TITLE
Latest update from urlhaus blocks entire'.info' TLD

### ISSUE THREAD

**Issue by felix** [StevenBlack/hosts#1628]
The latest update form urlhaus add the following line to all lists -- at least in the alternate folders -- which results in the entire '.info' TLD being blocked:

```
0.0.0.0 info #@192.210.163.201
```
Perhaps my unbound script it not reading them correct in which case ignore this issue.

**Comment by dnmTX** [comment]
@felix thanks for the report. There are bunch of bad lines in the upstream list apprently that the script here tried to fix it by
placing a comment.
Nevertheless this needs fixing like...yesterday. 
@felix if you don't mind report those directly to them for hopefully quick resolution: `cosntacptamem@abuse.ch`
Listing here all of them:
`a.stro.lo.gy.t.em.r@45.144.225.135`
`alumni.Hildred.Ibbott@46.249.33.79`
`App.Are.ntf.yn.q@45.144.225.242`
`desce.n.d.a.sls@gfold1.webselffiles01.com`
`drolukse.rokz@gfmodd1.webselffiles01.com`
`hildred.Ibbott@45.144.225.242`
`i.n.t.E.Rloca.l.qs.j.y@moreirawag.ac.ug`
`info@192.210.163.201`
`pr.o.p.os.alsc.vh@192.210.163.201`
`pr.o.p.os.alsc.vh@gfold1.webselffiles01.com`
`Prud.E.Nttg.Ri@51.79.44.155`
`s.hu.d.es.h.d.u.E54.78.16247@46.249.33.79`
`s.hu.d.es.h.d.u.e54.78.16247@gfold1.webselffiles01.com`
`unrel.a.t.ed.o.j.b.v@194.38.20.199`
`yeq.i.u.j.ia.n.3@192.210.163.201`

Thank you 👍

**Comment by johnwick1** [comment]
> 
> 
> The latest update form urlhaus add the following line to all lists -- at least in the alternate folders -- which results in the entire '.info' TLD being blocked:
> 
> ```
> 0.0.0.0 info #@192.210.163.201
> ```
> 
> Perhaps my unbound script it not reading them correct in which case ignore this issue.

Same issue with unbound script sorting list, all domains in .info down

local-zone: "info" redirect
local-data: "info A 0.0.0.0"

**Comment by dnmTX** [comment]
I just sent email to the upstream curator. Let's see how it goes.

**Comment by dnmTX** [comment]
**For keeping track:**
Steve @StevenBlack looks like they have [presense in GitLab](https://gitlab.com/curben/urlhaus-filter) and similar issue
was [posted there](https://gitlab.com/curben/urlhaus-filter/-/issues/38) by @p1r473. So far no reply 🤔

**Comment by StevenBlack** [comment]
I just reverted branch master to f87007cc which is release 3.6.6.

**Comment by dnmTX** [comment]
Steve @StevenBlack their email is `contactme@abuse.ch`. Once the list is back in use here you need to correct this!

**Comment by StevenBlack** [comment]
Closing.

**Comment by StevenBlack** [comment]
Tanks Felix @felix, by the way...

**Comment by dnmTX** [comment]
Got response from upstream:

> Thanks for the note, this has been fixed.
>Regards,
>abuse.ch

Looks like we're good on both ends 😉 

P.S. Steve @StevenBlack reminder to fix the email in [update.json](https://github.com/StevenBlack/hosts/blob/master/data/URLHaus/update.json) for any fature inquiries.
The correct one is contactme@abuse.ch . Thank you 👍
