### ISSUE TITLE
fe80::1%lo0 localhost error on dnsmasq

### ISSUE THREAD

**Issue by braian87b** [StevenBlack/hosts#163]
this line:

```
fe80::1%lo0 localhost
```

throws error on dnsmasq running on OpenWRT based firmware.

**Comment by braian87b** [comment]
Wed Aug 17 04:04:33 2016 daemon.err dnsmasq[5245]: bad address at /tmp/block.hosts line 6

**Comment by StevenBlack** [comment]
I don't really see what I can do here.  Any suggestions?

**Comment by braian87b** [comment]
this could be fixed when whitelist feature is added, "localhost" could be added.
or maybe just add to Docs a warning saying that fe80::1%lo0 could raise an error when hosts is used on dnsmasq, my dnsmasq didn't resolve and was because of that.
