### ISSUE TITLE
Malware urls

### ISSUE THREAD

**Issue by NO-ob** [StevenBlack/hosts#1631]
https://blog.netlab.360.com/stealth_rotajakiro_backdoor_en/

A recently discovered piece of malware sends data to urls could they be added to the list plox

news.thaprior.net 
blog.eduelects.com 
cdn.mirror-codes.net 
status.sublineover.net

**Comment by StevenBlack** [comment]
Thanks @NO-ob these are added in commit 97766531

Closing.

**Comment by NO-ob** [comment]
Thankyou
