### ISSUE TITLE
docs.pipenv.org is an impostor

### ISSUE THREAD

**Issue by dheerajreal** [StevenBlack/hosts#1635]
The domain docs.pipenv.org appears to be related to [pipenv](https://github.com/pypa/pipenv)
But it's an older domain for the project and is now under unknown control.
[See here](https://github.com/pypa/pipenv/pull/4167)
Moreover, the site has some suspicious links to external domains that might be mailcious.
[See here](https://github.com/pypa/pipenv/issues/4671)

> Wow, this is a creative use of an expired domain.
> 
> I let pipenv.org expire, as it appeared few people used it, as opposed to the pypa site
> 

_Originally posted by @kennethreitz in https://github.com/pypa/pipenv/issues/4671#issuecomment-819071394_

**Comment by StevenBlack** [comment]
Thank you Dheeraj @dheerajreal.  This is added in commit 708fc8a.

Ref: https://github.com/pypa/pipenv/issues/4671

**Comment by TPS** [comment]
@StevenBlack I think you didn't go far enough.  Per https://github.com/pypa/pipenv/issues/4671#issuecomment-819080886, it'd be better to add `pipenv.org` & `www.pipenv.org`, as well. 🙇🏾‍♂️

**Comment by TPS** [comment]
> Well, if nobody friendly owns the domain name, then I guess the right thing to do is submit `*.pipenv.org` to Google Safe Browsing and similar malware lists:
> 
> https://safebrowsing.google.com/safebrowsing/report_general/

The only domains I could find besides `docs.` are `www.` & the root domain.

**Comment by funilrys** [comment]
Hi Steve @StevenBlack, took a bit more time to do some enumeration and then test everything I could find with [PyFunceble 4](https://github.com/funilrys/PyFunceble/tree/dev) and although there is/was much more subdomains behind that wildcard, the only available at this time are the following:

```
pipenv.org
www.pipenv.org
docs.pipenv.org
```

As they are all part of the Badd-Boyz-Hosts, they should be merged here on your next release. 

Stay safe and healthy.
