### ISSUE TITLE
googleoptimize.com might cause to page not function properly

### ISSUE THREAD

**Issue by saper-2** [StevenBlack/hosts#1636]
Hello,

Blocking loading ```googleoptimize.com``` (full URL: ```https://www.googleoptimize.com/optimize.js?id=xxxxxx``` ) might make web page not function properly or won't load at all (if there is used dynamic loading on the page).

So far I found this to be issue with one Polish website (big electronic&computer store in Poland): https://x-kom.pl/ .
Blocking googleoptimize causes the mentioned page to not work: products in categories are not loaded when changing page, or when applying filters.

**Comment by dnmTX** [comment]
**ping** @shreyasminocha it's one of yours.

**Comment by shreyasminocha** [comment]
Fixed in 3.6.10.

**Comment by StevenBlack** [comment]
Thanks @saper-2, Dan @dnmTX and Shreyas @shreyasminocha.

Closing.
