### ISSUE TITLE
Datadog blocked

### ISSUE THREAD

**Issue by rchenzheng** [StevenBlack/hosts#1637]
Why is datadog being blocked? As a Developer I use this almost on a daily basis

```
# [datadoghq.com]
0.0.0.0 api.datadoghq.com
```

**Comment by StevenBlack** [comment]
Thanks Richard @rchenzheng.

@jawz101 can you please have a look at `api.datadoghq.com`?  Thank you, as always.

Richard @rchenzheng if you're on a Mac or Linux check out [hostile](https://github.com/feross/hostile) which is great to scrub a domain out of a big hosts file with minimum fuss (until we can get this resolved).

**Comment by jawz101** [comment]
removed.  thanks

**Comment by StevenBlack** [comment]
Thanks @jawz101!

Closing.
