### ISSUE TITLE
Minecraft Hosts

### ISSUE THREAD

**Issue by jamierocks** [StevenBlack/hosts#1638]
Hey :wave: 

There are a bunch of trackers used by Minecraft mods, but aren't currently covered by hosts.

I started my own hosts list a while back (https://github.com/jamiemansfield/minecraft-hosts/blob/master/lists/tracking.txt) - but would happily assimilate that into another list. I'm open to suggestions :)

**Comment by StevenBlack** [comment]
Hi Jamie @jamierocks thank you for this offer.

This would add eight domains:

```
$ ghosts --clip
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 79,163
Bytes: 2.4 MB
----------------------------------------
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 0
Bytes: 8 B
----------------------------------------
Intersection: 0 domains
```

**Comment by StevenBlack** [comment]
Jamie @jamierocks I would entertain a pull request for this.  

This involves a creating a subfolder under `./data` and therein place an `update.json` file with your data.  From there everything is automatic, as the `readme.md` files in this repository are adorned from `./data`.

Good?

**Comment by jamierocks** [comment]
That sounds great to me :)

I've submitted GH-1639 to add the data, and it seems to works for me locally (running updateHostsFile.py).
