### ISSUE TITLE
This necessary to run using Python old version

### ISSUE THREAD

**Issue by braian87b** [StevenBlack/hosts#164]
This was necessary in order to be able to run on an old Python version:

```
sed -i 's/python3/python/g' makeHosts
sed -i 's/[{]:,[}]/{0:d}/g' updateHostsFile.py
sed -i 's/[{]:,[}]/{0:d}/g' updateReadme.py
./makeHosts
```

**Comment by StevenBlack** [comment]
@braian87b which version of Python are you using?

In your view, should we include this as a tip in the docs?

**Comment by braian87b** [comment]
I just wanted to run the scripts on an old CentOS box, and even when I ran yum update/yum upgrade python later python complained about those curly brackets "{:,}" lines 141 at `updateHostsFile.py` and 44 and 63 at `updateReadme.py` it works well when replaced to "{0:d}" and as the script runs well on python 2 should be fine to have just "python" on `makeHosts` (on machines with python 3 only `python` usually works as an alias to python3.

Please, if you could add to Wiki/docs or modify the source code any option will be fine 👍

**Comment by funilrys** [comment]
@StevenBlack This one can be closed.
