### ISSUE TITLE
Content Blocker Test

### ISSUE THREAD

**Issue by mpaunovic** [StevenBlack/hosts#1641]
On Android, using personalDNSfilter, with your Unified hosts = (adware + malware) list enabled, I got 87%. Here's the test...

https://d3ward.github.io/toolz/src/adblock.html

Just to let you know, it looks like some domains are missing in your list. Could you please fix it?

Thank you!

**Comment by dnmTX** [comment]
> it looks like some domains are missing in your list. Could you please fix it?

aaand which domains are the missing ones?

**Comment by StevenBlack** [comment]
Thank you for this Milan @mpaunovic.  You'll get a much better score if you use the list with the social media extension.

https://github.com/StevenBlack/hosts/blob/master/alternates/social/readme.md

Closing because this isn't really actionable.
