### ISSUE TITLE
No internet 5-10 minutes on Windows startup

### ISSUE THREAD

**Issue by mataski** [StevenBlack/hosts#1642]
There's blank load screens on browsers and no program can connect to internet for first 5 to 10 minutes (depending on which hosts file used, the bigger the slower)

Assuming it takes time to load 80k lines in hosts file. No issue with default hosts.

Is this normal behavior? Any way to speed it up?

Windows 10 x64

**Comment by ScriptTiger** [comment]
Try the `--compress` or `-c` switch when you build your hosts file.

If you don't know how or don't have the proper setup (Python, etc.) to build your own hosts file, you can check out the pre-generated "Compressed" downloads at the following link:

https://scripttiger.github.io/alts/

There is also a Windows script that can keep your hosts file up to date automatically for you that I've maintained over the years, but new Windows updates are constantly breaking things here and there. But feel free to check it out and see if it works for you:

https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate
