### ISSUE TITLE
Move the new minecraft-hosts out of the main unified lists

### ISSUE THREAD

**Issue by rtm516** [StevenBlack/hosts#1644]
These hosts don't come under adware or malware so shouldn't be in the unified list as that is against what the readme states.
https://github.com/StevenBlack/hosts/blob/master/data/minecraft-hosts/hosts

**Comment by dnmTX** [comment]
> These hosts don't come under adware or malware 

Steve @StevenBlack,he refers to this:
![hosts](https://user-images.githubusercontent.com/34774426/117735035-4f747e00-b1ba-11eb-9f69-cce68f4fc4de.png)
...you might want to change or delete that part so no confusions in the feature.
