### ISSUE TITLE
[Phishing/BlackList] Dummy domain

### ISSUE THREAD

**Issue by 1alessandro1** [StevenBlack/hosts#1645]
0.0.0.0 urgente.eu

This domain is nonsense, I'd recommend to blacklist this since has been used in phising links such as the following:

http://urgente.eu/?rid=MaV6sbg

[DO NOT CLICK]

**Comment by StevenBlack** [comment]
Thank you Alessandro @1alessandro1.  This is added in commit 9cd1d30d.

Closing.
