### ISSUE TITLE
new spam domain: sylviagreen club

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#1646]
The spam domain sylviagreen(dot)club is being spread via SMS/email, so we could add it.
![spammer](https://user-images.githubusercontent.com/67167176/118033861-4ceb6300-b337-11eb-89be-7510667f893f.jpg)

**Comment by dnmTX** [comment]
@hyder365 you sure you don't know Sylvia Green? Looks to me like personal message from a close friend.

**Comment by hyder365** [comment]
Never heard the name before and totally unsolicited message. The broken English isn't a great sign either.

**Comment by dnmTX** [comment]
The domain redirects to `localbestdating1.com`(malicious !!!)

**Comment by hyder365** [comment]
Ping?

**Comment by dnmTX** [comment]
Steve @StevenBlack any decisions made yet on this one?

**Comment by StevenBlack** [comment]
Thanks for the reminder Dan @dnmTX, I'll add this to the next release.

**Comment by StevenBlack** [comment]
Done!  Closing.
