### ISSUE TITLE
Doubt about your hosts

### ISSUE THREAD

**Issue by gallegonovato** [StevenBlack/hosts#1647]
Good afternoon:

First of all let me thank you for all your work, effort. And for everything you do.

I happen to be using Adaway. And within it I have:

StevenBlack
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts

StevenBlack Complete
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

StevenBlack Unified Hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Is it just me or do I have your hosts in triplicate.

Thanks a lot for your help

**Comment by StevenBlack** [comment]
Hi @gallegonovato thank you for the kind words.

Using your nomenclature above,

* "StevenBlack" presently contains 3,108 domains and is a small component of both "StevenBlack Complete" and "StevenBlack Unified Hosts".

* "StevenBlack Unified Hosts" presently contains 80,993 domains and is a major component of "StevenBlack Complete".

* "StevenBlack Complete" presently contains 114,521 domains and is a superset of both.

I hope this helps!

Closing.
