### ISSUE TITLE
False Positive? www3.corelight.com 

### ISSUE THREAD

**Issue by BeanBagKing** [StevenBlack/hosts#1648]
Not sure how this one ended up on the list, but I believe it's a false positive. The domain belongs to https://corelight.com/ and hosts things such as http://www3.corelight.com/nsm@home (link on https://corelight.blog/2021/03/15/translating-query-into-action/).

I'm sure this came from some other list, If you know which one, I'll submit it there.

I'm not affiliated with Corelight, just noticed it while scoping out the @home program.

**Comment by dnmTX** [comment]
@BeanBagKing  it's listed in [AdGuard cname-trackers](https://github.com/AdguardTeam/cname-trackers),you can open a [ISSUE](https://github.com/AdguardTeam/cname-trackers/issues) and discuss it with the curators.

**Comment by TPS** [comment]
@BeanBagKing Close this FTW, as associated question is sufficiently answered upstream?
