### ISSUE TITLE
False positive for px-conf.perimeterx.net and client.perimeterx.net

### ISSUE THREAD

**Issue by omriiluz** [StevenBlack/hosts#1650]
Hello,
A few of the domains used by [PerimeterX](https://www.perimeterx.com/) are flagged for blocking in your list, for example `px-conf.perimeterx.net` and `client.perimeterx.net` but also others. These domains are used by PerimeterX, a cyber security and anti-fraud company, to protect thousands of sites and applications from various cyber attacks. 

PerimeterX is fully compliant with privacy regulations all over the world (GDPR, CCPA, etc. ). We do not sell user information or use it in any way other than to decide if if the user is a threat to the site. 

By not being able to access these domains certain apps and sites, your users (and ours) will have negative experience and might not be able to use sites and apps as a result. 

Would highly appreciate if you can remove these domains from the list.

**Comment by dnmTX** [comment]
**For reference and updates see:** https://github.com/AdAway/adaway.github.io/issues/251

**Comment by StevenBlack** [comment]
Hi Omri @omriiluz thank you for this.  We carry `perimeterx.net` domains from a variety of sources — it's not just one source list, it's in many source lists.

It's hard to reconcile what you claim, with what appears to be a broad consensus about `perimeterx.net`.

That said I'm sure we'll get to the bottom of it.  This is your hill to climb, however.  We're not in the business of deplatforming companies, just their noxious vectors.

**Comment by omriiluz** [comment]
Thanks for the feedback Steven. I understand that the burden of proof is on us and I'm willing to provide more information or even jump on a call to show you our platform. We have nothing to do with ads - we do not buy, sell, target, personalize or do anything that can even be remotely related ads.
We profile the user in real time to understand if it's a bot or human - think reCaptcha but better - and we do not use this information for anything beyond the real time profiling. You can see our commitment in our privacy policy and the compliance certifications we have - https://www.perimeterx.com/resources/compliance/

**Comment by omriiluz** [comment]
@StevenBlack the main block is coming from the upstream feed referenced above, and they just removed our entries. would it be possible to pull the adawy upstream?

**Comment by StevenBlack** [comment]
@omriiluz I'll create a release now.  Please standby.

**Comment by StevenBlack** [comment]
Omri @omriiluz this is now live and online in release [3.7.4](https://github.com/StevenBlack/hosts/releases/tag/3.7.4).

Thanks everybody!

Closing.
