### ISSUE TITLE
False positive: stats.pingdom.com

### ISSUE THREAD

**Issue by Bertware** [StevenBlack/hosts#1651]
Blocking stats.pingdom.com completely blocks public status pages, which are not used for tracking or gathering statistics, but to communicate downtime and server issues.

Example broken sites: http://status.trafiklab.se/, http://status.inera.se/, http://status.svd.se/ . This system is used worldwide, the examples just happen to be Swedish. The status pages cannot be opened at all when the stats.pingdom.com domain is blocked.

I have tracked this down to the AdAway list: https://github.com/AdAway/adaway.github.io/issues/252

**Comment by StevenBlack** [comment]
Thanks for this @Bertware.

The domain `stats.pingdom.com` comes to us via Adaway.  Ping @jawz101, what do you think?

**Comment by jawz101** [comment]
removing

**Comment by StevenBlack** [comment]
Thank you as always @jawz101!

@Bertware this will be reflected in the next release, coming shortly.

Closing.

**Comment by dnmTX** [comment]
Busy day for Stevo @StevenBlack  😄
