### ISSUE TITLE
Remove h-tdcanada.online-metrix.net - prevents logging in to iOS App

### ISSUE THREAD

**Issue by amit-bh** [StevenBlack/hosts#1652]
Hello, I want to request removing h-tdcanada.online-metrix.net from the list.

 I have been having trouble logging on to the TD Canada Mobile App (iOS) recently on wifi but no issues when I switch to cellular data. It kept displaying error "Unfortunately, we're not able to log you in right now. Please try again later." 

Upon whitelisting h-tdcanada.online-metrix.net on my pi-hole, I can successfully log on to the app. Curiously enough, if I log on with data but then switch over the wifi afterwards, I can browse the app fine. Seems this domain is needed for logging into the mobile app (the desktop site doesn't seem to be affected).

**Comment by StevenBlack** [comment]
Hi Amit @amit-bh thank you for this.

The domain `h-tdcanada.online-metrix.net` comes to us via AdAway.  @jaws101 can I ask you to have a look at this one too?  As usual I defer to you.

**Comment by dnmTX** [comment]
**ping** @jawz101 for assist 👍 
Brother,you missed this one somehow 😉

**Comment by jawz101** [comment]
removed.  thanks

**Comment by StevenBlack** [comment]
Thanks @jawz101.

This is reflected in the new release coming shortly.
