### ISSUE TITLE
learn.cisecurity.org is blocked?

### ISSUE THREAD

**Issue by sudarpo** [StevenBlack/hosts#1653]
Hi

I was trying to download CIS Benchmarks today, and curious to find out that learn.cisecurity.org is blocked.

CIS = Center for Internet Security, refer https://en.wikipedia.org/wiki/Center_for_Internet_Security

Do you mind if I ask why learn.cisecurity.org is blocked?
It's not a fake news or some illegitimate downloads.

Thanks in advance.

**Comment by StevenBlack** [comment]
Hi @sudarpo thank you for your question.

The domain `learn.cisecurity.org` comes to us via Adguard.  Andrey @ameshkov what's your feeling about `learn.cisecurity.org`?

@sudarpo please understand that there are no 'legit' websites for justification.  Any site that engages in tracking or trading on its users, nevermind malware and other things, is a candidate for listing.  

Let's see what Andrey @ameshkov has to say.

**Comment by ameshkov** [comment]
Well, that's a CNAME of `go.pardot.com` and that's why it got there.

From our experience, `go.pardot.com` cnames are often used as click-tracking domains (i.e. clickthrough domains which purpose is to set cookies & redirect further).

**Comment by StevenBlack** [comment]
Thank you Andrey @ameshkov, that's a good take.

I'm sorry @sudarpo, this won't be changing.

Closing.

**Comment by sudarpo** [comment]
Thanks for the update, @StevenBlack and @ameshkov 
Appreciate the response.
