### ISSUE TITLE
Hey Steven, can you block this pages?

### ISSUE THREAD

**Issue by 1066-007** [StevenBlack/hosts#1663]
https://www.deviantart.com/
https://www.newgrounds.com/

They aren't porn sites but they contain porn images and sometimes videos.

**Comment by dnmTX** [comment]
![1066-007](https://user-images.githubusercontent.com/34774426/119250808-3e3b5200-bb68-11eb-8ed0-39e70ad39baf.png)

**Comment by StevenBlack** [comment]
Thank you anon @1066-007.

Ping @sinfonietta I'll leave these to you to list?

**Comment by llacb47** [comment]
No, they should not be listed.

**Comment by Sinfonietta** [comment]
@StevenBlack I won't list these, maybe somebody else?

**Comment by StevenBlack** [comment]
Thanks @1066-007 closing this now.

**Comment by rautamiekka** [comment]
By this logic you'd have to block Facebook and Google Drive, for starters, as a porn source.
