### ISSUE TITLE
ibeat analytics

### ISSUE THREAD

**Issue by ghost** [StevenBlack/hosts#1667]
`ibeat.indiatimes.com` is blocked by our list, but following are not blocked,
* `api.ibeat-analytics.com`
* `ibeat-analytics.com`
![Screenshot_20210526_115257](https://user-images.githubusercontent.com/59839368/119612727-da3fb480-be19-11eb-8273-5a254cef8892.jpg)

ibeat analytics belongs to indiatimes (a news site)
![Screenshot_2021_0526_115721](https://user-images.githubusercontent.com/59839368/119612796-f2afcf00-be19-11eb-84e9-5d5c917fc88d.jpg)
https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics-vendors/
<details><summary>Transcription (click to expand)</summary>
Ibeat Analytics

Type attribute value: `ibeatanalytics`

Adds support for Ibeat Analytics. More details for adding Ibeat support can be found at [Ibeat Integration Support](https://ibeat.indiatimes.com/support.html#h.a5rit14mwie1)
</details>

* [urlscan.io report](https://urlscan.io/result/df23887d-5d30-46d8-9d7a-52c24fe8c4e0/)
* [AlienVault report](https://otx.alienvault.com/indicator/domain/ibeat-analytics.com)

**Comment by StevenBlack** [comment]
Thanks @bnainar I think this is ok.  It's not our mission to deplatform companies in legal industries, just intercept their vectors for analytics and shenanigans.  The root domain and the `api` domain aren't malicious domains, or are they?

**Comment by dnmTX** [comment]
>  just intercept their vectors for analytics and shenanigans
I call blocking:
0.0.0.0 api.ibeat-analytics.com
0.0.0.0 ibeat-analytics.com
right on target and far from deplatforming,in my opinion,of course 😉
