### ISSUE TITLE
[Blacklist] Binance

### ISSUE THREAD

**Issue by vincentDcmps** [StevenBlack/hosts#1669]
Hello could you add these url use by binance apps.

www.hanqiweb.red
www.hanqiweb.cn
www.hanqiweb.net
www.shyqxxy.com
domain-config-1259603563.file.myqcloud.com
static-file-1259603563.file.myqcloud.com
report.binance.im
jpush.binance.im
sensors.binance.cloud
nbstream.binance.com
fstream.binance.ccf
stream.binance.cc

**Comment by StevenBlack** [comment]
Merci Vincent.

I'm going to decline listing these domains. 

Several motivations for this. 

One motivation is [Gibbs Rule](https://ncis.fandom.com/wiki/Gibbs%27s_Rules) #23 - "*Never Mess with a Marine's Coffee, if you Want to Live*".

Before blocking anything from Binance, Kraken, Poloniex, Coinbase etc I need to see some analysis that shows it doesn't affect trading.

**Comment by StevenBlack** [comment]
Closing.
