### ISSUE TITLE
Battery drain from YouTube Music due to Google Tag getting blocked

### ISSUE THREAD

**Issue by arter97** [StevenBlack/hosts#1670]
First reported by XDA:
https://www.xda-developers.com/psa-using-an-ad-blocker-a-bug-in-google-play-music-may-be-draining-your-battery/

It seems like this is still the case with YouTube Music:
https://twitter.com/arter97/status/1397973993529823233

The app retries the connection to Google Tag without any sleep, resulting in consuming a CPU core 100% (this is a 8 core phone, so anything higher than 12.5% is consuming an entire core) and causing massive battery drains on Android.

While it seems to be the case that Google Tag is used for analytics, causing a massive battery drain over it isn't worth it.

The issue is gone after removing:
```
www.googletagmanager.com
www-googletagmanager.l.google.com
googletagmanager.com
googletagservices.com
www.googletagservices.com
```

One thing I found weird is that the hosts file here already whitelists www.googletagservices.com for some reason, but is overridden with another non-commented entries:
```
# 0.0.0.0 www.googletagmanager.com #[affects ASUS]
#0.0.0.0 www.googletagservices.com              #interferes with techrepublic
```

**Comment by dnmTX** [comment]
Well Park @arter97 the article suggest to whitelist it until google decide to fix their crap.It's a bug after all and the domain in question is a...one of the most popular tracking domains.
@jawz101 what do you think,it's in your list,still...i'm all 👎 for removing it.

**Comment by arter97** [comment]
The article dates back to 2017, so I'm not entirely sure if Google even wants to fix it.

I'm now told that GMS may also misbehave like this, which may mean all Android users with Google Play services may be affected.
https://twitter.com/luca020400/status/1397986103114842113 (LineageOS director)

IMHO, this repo should serve practical use-cases. If users are paranoid enough to take security and privacy to that extreme, they should have other means (e.g., VPN, Firefox with Facebook container, etc) to protect themselves.

As this repo is the simplest form of ad blocking, I believe that possible battery drains from this isn't worth it for practical users.

**Comment by jawz101** [comment]
I don't want to drain my battery for the sake of blocking a domain so I'll remove it though it bugs me that blocking a domain would cause battery drain.

**Comment by StevenBlack** [comment]
Most of those domains are included by several other curators.  So this has little or no practical effect on this list.

Which is fine by me. 👀

**Comment by dnmTX** [comment]
> Which is fine by me. 👀

And **ME** 😉

**Comment by dnmTX** [comment]
> I don't want to drain my battery for the sake of blocking a domain so I'll remove it....

@jawz101 this here....i believe is the first complaint since 2017,don't you find that strange?

**Comment by jawz101** [comment]
@dnmTX not from @arter97.  I recognize the name from XDA.  They've been doing Android kernel stuff for 5+ years.

**Comment by 0mega28** [comment]
I am using Adaway to block ads, YT music was still taking 100% CPU after whitelisting the domains listed in the issue.

But, after whitelisting googleads.g.doubleclick.net YT music is taking 22% CPU.
