### ISSUE TITLE
speakol

### ISSUE THREAD

**Issue by bnainar** [StevenBlack/hosts#1672]
# Domain(s) to be blocked:
* `cdn.speakol.com`
# Who?
> Speakol is a MENA region-focused content discovery & recommendation platform. It provides Premium Native Ads to the most relevant audience.

Based in Egypt.
Functions like Taboola
# Found where?
https://m.khaleejtimes.com/news/dubai-coin-cryptocurrency-was-never-approved-by-any-official-authority
![IMG_20210529_220639](https://user-images.githubusercontent.com/59839368/120077880-43e5ea00-c0ca-11eb-90fd-3531200e73ba.jpg)

**Comment by StevenBlack** [comment]
Thank you for this Nainar @bnainar.

What are we looking at here?  I don't understand.

**Comment by dnmTX** [comment]
On the screenshot(left column),where it says "paid content".i think 🤔

**Comment by bnainar** [comment]
@StevenBlack, it's like Taboola. In the screenshot, from below paid
content, those "reactions" are provided by the news website itself

**Comment by dnmTX** [comment]
@bnainar it's actually `cdn.speakol.com` according to AdGuard,which already took care of it for me 😄 
Test it,post results please 👍 
![Capture1](https://user-images.githubusercontent.com/34774426/120119646-79d4ae00-c15e-11eb-8834-0d7f6d872e99.PNG)

**Comment by dnmTX** [comment]
Steve @StevenBlack no doubt it belongs here,so i made one easy copy/paste for ya 😉 :

`0.0.0.0 mc.speakol.com`
`0.0.0.0 rd.speakol.com`
`0.0.0.0 inline.speakol.com`
`0.0.0.0 pixel.speakol.com`
`0.0.0.0 cdn.speakol.com`
`0.0.0.0 recommendation.speakol.com`
`0.0.0.0 crawler.speakol.com`
`0.0.0.0 ads.speakol.com`
`0.0.0.0 plugins.speakol.com`
`0.0.0.0 publishers.speakol.com`
`0.0.0.0 www.speakol.com`
`0.0.0.0 speakol.com`
`0.0.0.0 cstorage.speakol.com`
`0.0.0.0 pstorage.speakol.com`
`0.0.0.0 api.speakol.com`
`0.0.0.0 analytics.speakol.com`
`0.0.0.0 alert.speakol.com`
`0.0.0.0 dev.speakol.com`
`0.0.0.0 dev.publishers.speakol.com`

**Comment by bnainar** [comment]
How did you find this many domains? I was checking my DNS logs, but only
found `rd` subdomain. Curious about your methodology, @dnmTX

**Comment by dnmTX** [comment]
> How did you find this many domains?

@bnainar the rest are just additional(not employed in that specific websites),but concidering the nature of the domain,mine as well add the rest.Might save you looking that **paid content** somewhere else 😉

**Comment by StevenBlack** [comment]
Thanks everybody!  This is added in commit a6d995d94d56c7d4f10fd915c13b37943dcf5f6c.

Closing.

**Comment by bnainar** [comment]
@StevenBlack, why are you creating a new release just for this domain? Or is this a periodic thing that you do? Also what's the update on other new issues

**Comment by StevenBlack** [comment]
Please read the [release notes](https://github.com/StevenBlack/hosts/releases/tag/3.7.7) @bnainar.
