### ISSUE TITLE
FB Account Phishing URL

### ISSUE THREAD

**Issue by bctrainers** [StevenBlack/hosts#1677]
Came across a new one tonight; the first page that a user is directed to is `cnnnewsonlinetogsdqq.wixsite.com/my-site-10` but clicking the fake video image redirects to this URL: `dense1-madeindefense.ml/01jj/`

URL root is fluff: `dense1-madeindefense.ml`

Not quite sure which host list to contact outside of StevenBlack hosts for the addition of `dense1-madeindefense.ml` as phishing.

**Comment by dnmTX** [comment]
Isn't better to block the root of the problem,aka `cnnnewsonlinetogsdqq.wixsite.com` ?
It's smells fishy just by reading it.

**Comment by krystian3w** [comment]
IMO both if user start new free wixsite or any other sended to Facebook posts/"sponsored" ads.
