### ISSUE TITLE
c.hrzn-nxt.com

### ISSUE THREAD

**Issue by DavidCWGA** [StevenBlack/hosts#1679]
Also loaded by the SiriusXM site, c.hrzn-nxt.com hosts Javascript claiming to be "the worlds most powerful web analytics platform".

Weirdly, while c.hrzn-nxt.com resolves, hrzn-nxt.com does not.

**Comment by StevenBlack** [comment]
Thank you David.  Added in commit 9cca4f1, and will be live in the next release.
