### ISSUE TITLE
Blocking lptag.liveperson.net breaks Sirius XM support chat

### ISSUE THREAD

**Issue by DavidCWGA** [StevenBlack/hosts#1680]
lptag.liveperson.net is in the list but blocking it breaks the Sirius XM support chat - the chat button on this page:
https://www.siriusxm.com/contact-us

doesn't load.

**Comment by StevenBlack** [comment]
Hi David @DavidCWGA thank you for this.

The `lptag.liveperson.net` domain is blocked by three of our curators. Evidently there's more to this than first meets the eye.

```
data/adaway.org/hosts
7030:127.0.0.1 lptag.liveperson.net

data/mvps.org/hosts
3593:# 0.0.0.0 lptag.liveperson.net

data/shady-hosts/hosts
366:0.0.0.0 lptag.liveperson.net
```

**Comment by dnmTX** [comment]
The page loads fine on my end. `lptag.liveperson.net` doesn't appear to be even blocked in console 🤔

**Comment by GBT7** [comment]
This is also breaking the support verification my cell provider uses. I would assume it breaks anything using liveperson, which isn't great
