### ISSUE TITLE
new lists from hp threat intelligence

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1681]
https://raw.githubusercontent.com/hpthreatresearch/iocs/main/CryptBot/domains.txt
https://raw.githubusercontent.com/hpthreatresearch/iocs/main/TA551/domains.txt

**Comment by StevenBlack** [comment]
Thank you for the suggestion Lorenzo @scafroglia93.  I'm going to decline carrying these because the source repos are sparse, don't link to what they supposedly represent, and there's no license.

Closing.
