### ISSUE TITLE
Unblocking cdn.iubenda.com

### ISSUE THREAD

**Issue by vin047** [StevenBlack/hosts#1682]
`cdn.iubenda.com` is blocked, which prevents usage of their auto-updated privacy policy feature. Is it possible to unblock this domain?

Was advised to raise the issue on this repo from https://github.com/nextdns/metadata/issues/527

Thanks!

**Comment by StevenBlack** [comment]
Thank you Vinoth @vin047!

Ping @jawz101 can you please comment on domain `cdn.iubenda.com`?  Thanks!

**Comment by jawz101** [comment]
removed.  thanks

**Comment by StevenBlack** [comment]
Awesome!  Thanks @jawz101 and thank you Vinoth @vin047.  This will be live in the next release, coming shortly.

Closing.
