### ISSUE TITLE
[Phishing/BlackList] Scam gmail domain

### ISSUE THREAD

**Issue by 1alessandro1** [StevenBlack/hosts#1683]
Misspelling `gmail.com` sometimes leads to `gmial.com`, hence I recommend to add:

```
0.0.0.0 www.gmial.com
0.0.0.0 gmial.com
``` 

The url is also flagged as malicious on virustotal by reputable sources as Kaspersky

https://www.virustotal.com/gui/url/90b2d7d1b15105f16abb81880c0daa4317f42e812194f9a280cb04b4ac6fb6aa/detection

![image](https://user-images.githubusercontent.com/46293832/121892469-538d4180-cd0c-11eb-9dee-7d9786443a69.png)

**Comment by StevenBlack** [comment]
Thank you @1alessandro1 this is added in commit f67b8cfc and will be included in the next release.
