### ISSUE TITLE
AdsKeeper

### ISSUE THREAD

**Issue by ghost** [StevenBlack/hosts#1685]
**Blocking these domains causes the video player to fail. I honestly don't know why**
# Which domain(s)?
* `lentpedigreecompletely.com`
* `jsc.adskeeper.com`
# Found where?
* http://tamilyogi.best/jagame-thandhiram-2021-hd-720p-tamil-movie-watch-online/
# Example requests
* http://lentpedigreecompletely.com/aa/0d/9c/aa0d9c81fc3d5faa8213fe91d97a7e04.js
* https://jsc.adskeeper.com/t/a/tamilyogi.cat.1075376.js
# Notes
* Homepage of AdsKeeper - https://adskeeper.com
* AdsKeeper provides Taboola-like ads
* lentpedigreecompletely.com requests a whole array of domains serving pop-under and pop-up ads

**Comment by dnmTX** [comment]
> Blocking these domains causes the video player to fail. I honestly don't know why

Neither one is listed here,so what do you want us to do about it?

**Comment by dnmTX** [comment]
Steve @StevenBlack would advise you to back quote all the links and close this one as well(and delete/remove #1686 completely).
By the look of it,this so called **user** deleted his account,just another troll,very likely was trying to spread malware.

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX.

**Comment by dnmTX** [comment]
Steve @StevenBlack  back quote !!!!
