### ISSUE TITLE
WIP

### ISSUE THREAD

**Issue by EYp5xsEGMmD5Y3tfbgq3pNGfVbA9rn3R94ubaKi** [StevenBlack/hosts#1686]
* https://togenron.com/apu.php?zoneid=1535173, found on https://masstamilan.fm/drishyam-2-malayalam-songs#
* http://dudslubesviol.com/fZneYvVYz9u/26342 and http://catwenbat.com/rOvKq7eWSpomiq/13736 on http://isaidubb.co/tamil/tamil-dubbed-movies-download.html

**Comment by dnmTX** [comment]
You either `back quote` your malicious links or your post will be deleted for sure ❗

**Comment by StevenBlack** [comment]
Closing.
