### ISSUE TITLE
Link Shortener used by Iowa Government Agency

### ISSUE THREAD

**Issue by spacetimeengineer3** [StevenBlack/hosts#1688]
Found lnks.gd on the gambling list. This is used by the Iowa Department of Public Safety and is a good link. 

[Example Link](https://lnks.gd/l/eyJhbGciOiJIUzI1NiJ9.eyJidWxsZXRpbl9saW5rX2lkIjoxMDIsInVyaSI6ImJwMjpjbGljayIsImJ1bGxldGluX2lkIjoiMjAyMTA2MTguNDIxNDAwNzEiLCJ1cmwiOiJodHRwczovL2Rwcy5pb3dhLmdvdi90YW1hLWNvdW50eS1zaGVyaWZmcy1vZmZpY2UtYW5kLWRjaS1pbnZlc3RpZ2F0aW5nLXN1c3BpY2lvdXMtZGVhdGg_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWdvdmRlbGl2ZXJ5In0.i4DowABuKkYG-EY5kKRHE1vxYOitq8RaM3RyD5Be4nI/s/600941620/br/108164725435-l)

**Comment by StevenBlack** [comment]
Hi Erick @spacetimeengineer3 thank you for this.

The `lnks.gd` domain comes to us via yoyo.org.  Can you please raise this at pgl@yoyo.org?  Thank you.

**Comment by StevenBlack** [comment]
Ping Peter @pgl can you have a look at the `lnks.gd` domain?

**Comment by spacetimeengineer3** [comment]
[Link to my Pull Request](https://github.com/StevenBlack/hosts/pull/1689)

I was originally trying to submit a pull request. As this is my first ever pull request, I screwed it up.

**Comment by spacetimeengineer3** [comment]
Reopening due to incompetency

**Comment by spacetimeengineer3** [comment]
After looking into it, lnks.gd is a tracking url shortener. Which is why it's on the list.

**Comment by dnmTX** [comment]
Aha.....

**Comment by pgl** [comment]
These are my favourite types of issue reports, when they're solved by the time I get to look at them.
