### ISSUE TITLE
clustrmaps.com False positive?

### ISSUE THREAD

**Issue by TPS** [StevenBlack/hosts#1690]
There's nothing @, e.g., https://clustrmaps.com/bl/about that hints @ anything nefarious, & whitelisting gives a useful site w/ less-than-average bad bits.  Could this be reverified?   I can't tell which (if any) upstream list(s) to contact.

**Comment by dnmTX** [comment]
@TPS  tha will be MVPS HOSTS : `winhelp2002@gmail.com`

**Comment by TPS** [comment]
E-mail sent.  Thanks, @dnmTX. 🙇🏾‍♂️

I'll update here whenever I receive a response.

**Comment by dnmTX** [comment]
@TPS turns out that the domain is present in one more list: [yoyo.org](https://github.com/StevenBlack/hosts/blob/master/data/yoyo.org/hosts) and he might needs to be contacted as well.
**ping** Peter @pgl for assist 👍

**Comment by dnmTX** [comment]
@TPS to make it easier,next time just the search engine on the top and choose `in this repository`. It shows up right away:
![Search · clustrmaps com](https://user-images.githubusercontent.com/34774426/122861791-aacf7b00-d2e5-11eb-8a00-8d8ed13a9c1a.png)

**Comment by TPS** [comment]
Not yet implemented in the app (which I use).  I'll file that omission appropriately.

**Comment by pgl** [comment]
Take a look at the privacy policy: https://clustrmaps.com/bl/policy

> **Information We Collect from Other Sources**
> ...
> We may also get information from third party services about individuals who are not yet our users (...but we hope will be!), which we may use, for example, for marketing and advertising purposes.

> ** How We Use Information**
> ...
> To personalize your experience using our Services, provide content recommendations and serve relevant advertisements.

> ** How We Share Information**
> ...
> Third Party Vendors: We may share information about you with third party vendors who need to know information about you in order to provide their services to us. This group includes vendors that help us provide our Services to you (like payment providers that process your credit and debit card information) and those that help us understand and enhance our Services (_like analytics providers_).

(my emphasis on the last part)

etc.

So: they collect information, get data about you from other sources, use that for ads, share it with others. This happens without the possibility of opting out, if they're being loaded in the background from another site.

**Comment by TPS** [comment]
That's _not_ particularly ominous, especially in context of the **Choices** & **Your Rights** sections.  Reading the doc & using the site, whatever tracking 3rd parties they use are either opt-in or already handled via other entries (e.g., `ssl.google-analytics.com`).

**Comment by pgl** [comment]
@TPS OK cool, if you don't mind then bypass the block. @StevenBlack feel free to remove this when ingesting my list.

**Comment by pgl** [comment]
Side note: No offence meant here, but I think the general attitude of "that's not particularly ominous" is sort of how we ended up with everyone collecting, sharing, and buying data in the first place.

Let's say someone needs to find an abortion doctor away from where they live. They use clurstrmaps.com to search for one via an embed on another site. Now their IP, location, browser fingerprint, that's been shared with ad and marketing companies who then sell it on and the person has had no way to opt out; even done directly on the site, there's no way to prevent that happening (as far as I can tell from the privacy policy).

Side side note: putting a link to their privacy policy in the footer as "Policy Policy" doesn't smack of attention to detail.

![image](https://user-images.githubusercontent.com/1181139/122917446-52888f80-d35e-11eb-984d-07b4bd58b3cb.png)

**Comment by StevenBlack** [comment]
@TPS Thank you for the suggestion, this domain's inclusion won't change.

Closing.
