### ISSUE TITLE
Google Ads

### ISSUE THREAD

**Issue by Quorum75** [StevenBlack/hosts#1691]
These requests are tagged by AG Pro as advertising but they are not blocked. Is it normal?

pki-goog.l.google.com

gstaticadssl.l.google.com

![image](https://user-images.githubusercontent.com/49731083/123544741-fa360100-d754-11eb-8aeb-66687d19f615.png)

![image](https://user-images.githubusercontent.com/49731083/123544746-fd30f180-d754-11eb-96ad-a7065a143056.png)

**Comment by dnmTX** [comment]
`pki-goog.l.google.com` is a NO NO see: `https://pki.goog/`

**ping** @lightswitch05  Dan you have this listed,any input,from what you can remember: `gstaticadssl.l.google.com`
This looks like CNAME to me 🤔

**Comment by lightswitch05** [comment]
`fonts.gstatic.com` is a CNAME to `gstaticadssl.l.google.com` and causes lots of complaints. No doubt that's why it's not listed here.

**Comment by dnmTX** [comment]
Thanks Dan @lightswitch05 👍 
Sorry @Quorum75 but that's another NO NO 😉

**Comment by StevenBlack** [comment]
Thank you for the great diligence everybody!  Closing.
