### ISSUE TITLE
Analytics dealabs.digidip.net

### ISSUE THREAD

**Issue by Quorum75** [StevenBlack/hosts#1692]
Advertising/Analytics not blocked. 

dealabs.digidip.net

From https://digidip.net

I blocked it and at the present time I don't see any issue on https://www.dealabs.com

![image](https://user-images.githubusercontent.com/49731083/123544854-9a8c2580-d755-11eb-9299-22c7cae331f5.png)

**Comment by dnmTX** [comment]
Steve @StevenBlack this one is confirmed.Let me know if you want me to gig out some more 👍

**Comment by StevenBlack** [comment]
Thanks @Quorum75 and thank you Dan @dnmTX.  This is added in commit https://github.com/StevenBlack/hosts/commit/150d84202db5f4cd4eecfb2c51692be12603bc34 and will be included in the next release.

Closing
