### ISSUE TITLE
Analytics cds.s5x3j6q5.hwcdn.net

### ISSUE THREAD

**Issue by Quorum75** [StevenBlack/hosts#1693]
Identified as analytics. 

https://www.highwinds.com

![image](https://user-images.githubusercontent.com/49731083/123544949-0a9aab80-d756-11eb-9595-14ecc7c7bf6c.png)

**Comment by dnmTX** [comment]
I don't know about that particular domain with no context given but in general `....hwcdn.net` is a content delivery network and 
Windows is using some of their domains to deliver updates. I'd be carefull with this one.

**Comment by Quorum75** [comment]
OK. I will keep it blocked because I don't use Windows. I'll see if I gave any issue.
