### ISSUE TITLE
Netguard and google drive

### ISSUE THREAD

**Issue by PhilZ-cwm6** [StevenBlack/hosts#1695]
Hi,

The Netguard android app uses the default hosts list provided here
However, once enabled, Google Drive can no longer download files on Android, either by the Drive App or in chrome browser
Disabling the ad block service using this hosts lists solves the issue

This is only since a few weeks probably.

Let me know if you need more logging info so that I could try to identify the offending entries

**Comment by PhilZ-cwm6** [comment]
Sorry
Doesn't seem to be related to your database but to an issue in main app.
I will reopen if it sounds not the case

Best regards

**Comment by PhilZ-cwm6** [comment]
Well, sorry, it is really related to the filtering list
Once traffic is filtered using this list, Drive cannot download any file on Android

**Comment by StevenBlack** [comment]
Thanks Phil @PhilZ-cwm6.

In order to assess this we'll need to know which specific domains are problematic.  Are you able to assist with that?

**Comment by PhilZ-cwm6** [comment]
Yes, however I am narrowing it to a bug in the Netguard app
Would be great if you can confirm that the following logged domains are properly passed, as they are the ones logged for google drive. Please ignore the chrome entry on top of the list

![Screenshot_2021-06-29-01-42-16-683_eu faircode netguard](https://user-images.githubusercontent.com/2428217/123867289-70da2680-d92e-11eb-843f-ade3868b2c20.jpg)
![Screenshot_2021-06-29-01-46-54-024_eu faircode netguard](https://user-images.githubusercontent.com/2428217/123867293-720b5380-d92e-11eb-8fdf-e5de50ab2c51.jpg)

**Comment by dnmTX** [comment]
@PhilZ-cwm6  none of the: `ajax.googleapis.com` `android.googleapis.com` `content-autofill.googleapis.com` are listed here.
You got confirmation on this one.

**Comment by PhilZ-cwm6** [comment]
Thank you
I will close it as soon as it is sorted out with app developer 
Best regards

**Comment by PhilZ-cwm6** [comment]
It is definately not related to the hosts list, but some issue in Netguard on some devices, or some devices with Netguard VPN
