### ISSUE TITLE
False positive: cdn.cloud.altbalaji.com

### ISSUE THREAD

**Issue by specter78** [StevenBlack/hosts#1696]
Breaks the website

**Comment by StevenBlack** [comment]
Thank you @specter78 we need you to provide more details. Breaks which website, for starters?

**Comment by specter78** [comment]
@StevenBlack Sorry for not being clear. I thought it was pretty obvious. 

altbalaji.com is a streaming website and resources fail to load when the domain is blocked.

To test: Try loading the homepage. Images fail to load when the domain is blocked.

**Comment by dnmTX** [comment]
> Images fail to load when the domain is blocked.

Confirmed.
**ping** @jawz101 for assist 👍

**Comment by jawz101** [comment]
removed.  thanks

**Comment by specter78** [comment]
@dnmTX I personally don't use it to watch shows. I do, however, use NextDNS and found this issue while troubleshooting for a relative.

**Comment by StevenBlack** [comment]
Thank you @specter78, Dan @jawz101 and @jawz101.

This will be reflected in the next release.

Closing!

**Comment by dnmTX** [comment]
> Thank you @specter78, Dan @jawz101 👈 

You're most welcome 😄
