### ISSUE TITLE
[to add] Chase Bank Scam

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#1699]
Just got that stupid spam message on my phone and did  some digging. 
Hopefully it will save some poor soul of catching malware:
<img width="375" alt="Screenshot 2021-06-30 at 12 53 24 PM" src="https://user-images.githubusercontent.com/34774426/124012046-4cba2c00-d9a6-11eb-9bcc-c03b0ce95256.png">

**All malicious,all connected:**
`# Chase Bank Scam. See #1699`
`0.0.0.0 www.secure-verify-info.ddns.info`
`0.0.0.0 secure-verify-info.ddns.info`
`0.0.0.0 www.secure-verify-account.ddns.info`
`0.0.0.0 secure-verify-account.ddns.info`
`0.0.0.0 www.secure-verify-update.ddns.info`
`0.0.0.0 secure-verify-update.ddns.info`
`0.0.0.0 www.security-update.ddns.info`
`0.0.0.0 security-update.ddns.info`
`0.0.0.0 update-security.ddns.info`
`0.0.0.0 www.update-security.ddns.info`
`0.0.0.0 www.security-update.ocry.com`
`0.0.0.0 security-update.ocry.com`
`0.0.0.0 update-information.zzux.com`
`0.0.0.0 www.update-information.zzux.com`
`0.0.0.0 information-security.zzux.com`
`0.0.0.0 www.information-security.zzux.com`
`0.0.0.0 information-update.dynamic-dns.net`
`0.0.0.0 www.information-update.dynamic-dns.net`
`0.0.0.0 www.security-info.zyns.com`
`0.0.0.0 security-info.zyns.com`
`0.0.0.0 update-security.qhigh.com`
`0.0.0.0 www.update-security.qhigh.com`
`0.0.0.0 www.security-update.qhigh.com`
`0.0.0.0 security-update.qhigh.com`
`0.0.0.0 www.seure-update.fartit.com`
`0.0.0.0 seure-update.fartit.com`

Thanks Steve @StevenBlack 👍

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX these are added in commit 1c5c2dc.

Closing.

**Comment by dnmTX** [comment]
Steve @StevenBlack another day....another message...another domain 😄 :
`0.0.0.0 account-verify.otzo.com`
`0.0.0.0 www.account-verify.otzo.com`
