### ISSUE TITLE
Questions and request

### ISSUE THREAD

**Issue by lencc** [StevenBlack/hosts#17]
I have a few questions and one request.

**1st question**
As far as I understand, in order to add new <code>hosts</code> file in Windows, the file has to be downloaded and one can simply replace the original <code>hosts</code> file in *\etc* map.
I have read in my <code>hosts</code> file (in Windows) that *"each entry should be kept on an individual line."*
I opened one <code>hosts</code> file from your list and the domains are added without spaces between domain names and IP addresses. They are also not kept on individual lines. I suppose this doesn't matter - or am I missing something?

**2nd question & request**
I read on the webpage that your amalgamated <code>hosts</code> file can be updated automatically. But I do not know the step-by-step procedure to set this up.
Could you explain it? This is also a request: you could write a brief "quick guide" on the GitHub Wiki page, in case anyone else will have the same question in the future.

**3rd question**
I saw that you are combining a few sources in your lists.
I have also found a few more lists to block malware sites. These are:
**a)** Malware domains: www.malwaredomains.com (in addition to already implemented "Malware domain list")
direct link (file): http://mirror1.malwaredomains.com/files/justdomains
**b)** Spam404: http://www.spam404.com
direct link (list): http://spam404bl.com/spam404scamlist.txt
**c)** DisableWinTracking (tool): https://github.com/10se1ucgo/DisableWinTracking
direct link (list used by the tool): https://gist.githubusercontent.com/10se1ucgo/fcb774d781a66ea9d31f/raw/b99089721fcd9d8c5718224e23f275d3b99c06e2/ips+domains.txt

Could you check them out?
I think, there are around 15.000 more websites blocked within these two lists in addition to the current ones. They could be implemented beside current sources - if they fit into your amalgamated <code>hosts</code> file.

**Comment by StevenBlack** [comment]
As far as I know the `hosts` file works just fine in Windows.

Maybe this is a side-effect of the particular editor or viewer you are using?

To update the `hosts` file the terminal command would be `c:\blah\blah> python updateHostsFile.py`

Thanks for suggesting these additional sources!  I'll check them out.

**Comment by lencc** [comment]
I added one more list. It was made for blocking tracking domains in Windows 10, but I believe they can be added for other Windows versions as well. The link is added in the upper post (paragraph **c)** within 3rd question).

These domains are being used in [DisableWinTracking](https://github.com/10se1ucgo/DisableWinTracking) tool, which I found on [reddit](https://www.reddit.com/r/Windows10/comments/3fn46j/i_made_my_own_userfriendly_windows_10_privacy/). When you will be updating sources for your amalgamated <code>hosts</code> file, you could include this one as well.

**Comment by StevenBlack** [comment]
Closing this issue because none of the suggested sources present data in host-file compatible format.
