### ISSUE TITLE
EasyList Adservers as hosts file

### ISSUE THREAD

**Issue by ProgramComputer** [StevenBlack/hosts#1701]
Repository can be found here https://github.com/ProgramComputer/Easylist_adservers_hosts .

**Comment by dnmTX** [comment]
Even if the list is adopted to fit hosts lists aka remove `||.......^$third-party` add `0.0.0.0 .....` it's still NO GO due to adblockers in general perform wildcard blocking  so they need to list just the top level domain and afterwards all of it's subdomains will be blocked.
Hosts lists can not do this.Here you need to list every subdomain,which is determined to cause problems.
Just for example:   
there is a listed rule `||adkernel.com^`  and if converted to `0.0.0.0 adkernel.com` will do absolutely nothing but block their website(if they have one),because this where the possible danger comes from and i'm posting here just a small part:
![VirusTotal](https://user-images.githubusercontent.com/34774426/124174940-93755800-da72-11eb-9532-eb324c8d8bcb.png)

@ProgramComputer  you get ALL THIS 👆 ??? If you do,just close this issue,please.

**Comment by dnmTX** [comment]
Same goes for your [pull request](https://github.com/StevenBlack/hosts/pull/1700) but this is more like a NOTE to
Steven @StevenBlack,not to accept anything that comes from AdBlocking lists !!!!

**Comment by StevenBlack** [comment]
(chill Dan @dnmTX 🙃)

The `.tld` breakdown (top-25) and intersection magnitude (scroll to the bottom)

```
$ ghosts --clip --tld
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 81,793
Bytes: 2.5 MB
TLD tally:
   com: 40,907
   net: 8,175
   pl: 6,058
   xyz: 1,353
   jp: 1,248
   org: 1,235
   live: 1,201
   info: 1,069
   vn: 1,016
   ru: 1,009
   de: 921
   biz: 906
   eu: 839
   site: 683
   uk: 640
   io: 592
   life: 580
   fr: 542
   online: 483
   cyou: 448
   nl: 422
   icu: 419
   co: 418
   cn: 360
   club: 352
... snip ...
----------------------------------------
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 14,476
Bytes: 352 kB
TLD tally:
   com: 10,257
   club: 875
   net: 872
   info: 294
   top: 286
   pro: 254
   xyz: 227
   fun: 204
   site: 112
   biz: 87
   online: 68
   ru: 68
   co: 63
   io: 62
   space: 61
   org: 55
   casa: 36
   icu: 32
   uk: 29
   de: 29
   cam: 29
   me: 22
   work: 20
   media: 18
... snip ...   

----------------------------------------
Intersection: 1,075 domains
```

**Comment by StevenBlack** [comment]
These TLD proportions don't feel plausible.  It's not Asia-centric, which we really need more than anything.  

It seems `.club` and `.top`-specific, actually.  It's just odd.

**Comment by dnmTX** [comment]
> (chill Dan @dnmTX 🙃)

i've said my peace ¯\_(ツ)_/¯

**Comment by ProgramComputer** [comment]
Using another converter
`
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/ProgramComputer/Easylist_adservers_hosts/main/hosts
Domains: 11,313
Bytes: 281 kB
TLD tally:
   com: 8,002
   club: 864
   net: 558
   top: 280
   info: 221
   pro: 220
   xyz: 217
   fun: 204
   site: 108
   biz: 72
   online: 61
   space: 58
   casa: 36
   icu: 32
   co: 30
   cam: 29
   ru: 23
   org: 23
   io: 18
   work: 18
   pw: 12
   me: 11
   live: 10
   website: 9
   mobi: 8
   uk: 8
   media: 7
   ... snip ...
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 81,793
Bytes: 2.5 MB
TLD tally:
   com: 40,907
   net: 8,175
   pl: 6,058
   xyz: 1,353
   jp: 1,248
   org: 1,235
   live: 1,201
   info: 1,069
   vn: 1,016
   ru: 1,009
   de: 921
   biz: 906
   eu: 839
   site: 683
   uk: 640
   io: 592
   life: 580
   fr: 542
   online: 483
   cyou: 448
   nl: 422
   icu: 419
   co: 418
   cn: 360
   club: 352
   ... snip ...
----------------------------------------
Intersection: 400 domains
`

**Comment by ProgramComputer** [comment]
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/ProgramComputer/Easylist_adservers_hosts/main/EasyListChina+EasyList/hosts
Domains: 16,714
Bytes: 400 kB
TLD tally:
   com: 11,005
   cn: 1,304
   net: 997
   club: 870
   top: 495
   ... snip ...
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 81,793
Bytes: 2.5 MB
TLD tally:
   com: 40,907
   net: 8,175
   pl: 6,058
   xyz: 1,353
   jp: 1,248
----------------------------------------
Intersection: 500 domains

**Comment by StevenBlack** [comment]
I don't like where this is going.  This doesn't strike me as a serious curation, as opposed to an ad-hoc improvisation.

Sorry Paul @ProgramComputer I decline this suggestion.

Closing.
