### ISSUE TITLE
Uptime.com

### ISSUE THREAD

**Issue by dynek** [StevenBlack/hosts#1702]
Hello,

How did `uptime.com` end up being populated in your list ?

Thank you

**Comment by dnmTX** [comment]
**ping** @shreyasminocha for assist

**Comment by dnmTX** [comment]
@dynek the domain was removed upstream and next update will synchronize so you can close this 👍 
@shreyasminocha thanks 👍

**Comment by dynek** [comment]
Thank you guys 👍
