### ISSUE TITLE
ipfs.io is blocked

### ISSUE THREAD

**Issue by ThatIsAPseudo** [StevenBlack/hosts#1704]
Hi there, first of all many thanks for your lists.
I noticed that the domain `ipfs.io` is blocked but it's official website of the IPFS protocol, is there something wrong with it?

**Comment by dnmTX** [comment]
@ThatIsAPseudo It doesn't appear to be listed upstream anymore. Be patient,next update will remove it from the lists here 👍

**Comment by StevenBlack** [comment]
Thank you @ThatIsAPseudo — I'm closing this now.
