### ISSUE TITLE
Doubt with StevenBlack's and  adaway 's host list

### ISSUE THREAD

**Issue by gallegonovato** [StevenBlack/hosts#1707]
Good afternoon:

I wanted to take this opportunity to thank you for your superb hosts and your MORE THAN EXCEPTIONAL WORK.

I was looking at Adaway's host and your hosts: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

And in this one the Adaway host is already included. Since inside it is:

```
# Start adaway.org

# AdAway default blocklist
# Blocking of mobile ad providers and some analytics providers
#
# Project home page:
# https://github.com/AdAway/adaway.github.io/
#
# Get the latest version of this file:
# https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
#
# License:
# CC Attribution 3.0 (http://creativecommons.org/licenses/by/3.0/).
#
# Contributions from:
# Kicelo, Dominik Schuermann.
# Other changes and contributors maintained in the commit history at.
# https://github.com/AdAway/adaway.github.io/commits/master
#
# Contribute:
# Create an issue at https://github.com/AdAway/adaway.github.io/issues
#
```

Having your hosts would no longer include adaway's host. And if we put your hosts https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts so, correct me if I'm wrong, you already have in your hosts the adaway host. So having the native adaway host would be having extra host lists. Since your hosts already include the adaway one and we would be protected with your hosts by including the adaway one.

That is to say in the Adaway application to have https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts would already include the Adaway one and this last one would be left over since you already have it incorporated. And the things or hosts, or blocked things would not be repeated?

A hug and thanks for your time and effort and help. And I apologize if I did not explain myself well.

Pd: I apologize for my previous message. I don't know why the text is enlarged. The only thing I can think of is because I copied the #'s. 

From the host...

So please do not take it badly. Since it is not my intention those changes of size in the text. But I don't know why it changes it and I don't know how to make it all the same.

**Comment by StevenBlack** [comment]
Thanks for this @gallegonovato.

I fixed the above by placing the above between three tic characters like this

    ```
    Some code
    ```

**Comment by StevenBlack** [comment]
@gallegonovato I'm not sure I understand what you are suggesting.

Our build process removes duplicate domains so even if lists carry common domains, it's not a problem because a domain will only list once.

AdAway is part of our "core" list that is present in all our variants.  This is all explained in all the readme files.  We have 16 different variants, and all 16 readme files are clear about this, no?

**Comment by gallegonovato** [comment]
Good afternoon chef:

First of all apologize with the ruckus I had in my previous reply, which changed everything github. I'm still very new to github jeje.

I also apologize for not having explained myself well. It's the problem of mentally translating thoughts, you think one thing and when you express it I skate more than a skateboard jajajaja

The other day I was putting your hosts on my cousin's Windows. And when copying the things inside the hosts file of Windows. First I pasted his hosts. More specifically https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts and then paste the adaway one. But this Windows told me to replace things. To which I said no.

So far so good. But my question is with my Adaway. Since I have its font https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts and the native Adaway font (which is already included in the Adaway application).

Then the doubt arose in my mind. If I already have your tremendous hosts, then I wouldn't need the Adaway list. Since this is already included in your hosts as you say. Then if I delete the Adaway source, I would not lose what blocks this list of hosts. Because it is already inside yours. I don't know if I am right.

It is to free up ram usage and time when Adaway updates the hosts. Since it is already in yours. Have yours and adaway's. This last one would be left over, or it could be deleted.

Thanks a lot for your work and effort. And above all patience with me ;) . And millions for all your work and your tremendous lists of hosts.

**Comment by StevenBlack** [comment]
Hi @gallegonovato you are correct.  All our hosts files contain AdAway's hosts, by default.

You can only have one hosts file.  So I don't understand when you say, `Then if I delete the Adaway source...`.

I suspect you may be over-thinking this.  Just pick a hosts file, use it, and don't worry about other hosts files.

You won't be "saving ram".  Our hosts files are between 2.5 and 3.3 Mb in size.  On my Mac, I have to scroll down several pages to find processed that use that little RAM, nevermind that little *difference* in RAM.

A single Firefox or Chrome tab uses 10 to 100 times more RAM than your hosts file.

Closing.

**Comment by gallegonovato** [comment]
Good afternoon: 

Thank you very much for your help and time. About deleting the Adaway font. I was commenting on it because the Adaway application comes from the factory (so to speak) the list of Adaway and its Unified hosts. That I changed in my Adaway for the Unified hosts + fakenews + gambling + porn + social (that is, I changed the unified for the most complete one of yours). And that is why he said to remove the Adaway font (already included in adaway), since having his own, it already includes the Adaway font. And so when from the mobile with data, I update the host list in Adaway. It avoided consuming data and mobile resources. Because when you already have your list that includes Adaway's. It is to have duplicated things, and as in Windows only one applies. I beg you please don't take what I was asking you wrong. It is not because their hosts used ram or others on the pc or mac. As you well say, there are things that spend more resources. He commented on it for lightening (so to speak) on the mobile. Since Adaway's own application, when bringing the two hosts from origin, only one applies. And my cell phone is not currently a machine. A Nexus 6p with lineages without gaps. Thus it freed him from the use of resources and especially mobile data. I beg your pardon if I did something wrong, it was not my intention. Only that I saw that by having hers because I saw others having the other. I thank you again for all your work, time, effort. And patience with me. And I beg your pardon if I have offended you or did something wrong. It was not my intention. Receive a warm hug
