### ISSUE TITLE
Suggestion of possible new sources for your host lists

### ISSUE THREAD

**Issue by gallegonovato** [StevenBlack/hosts#1708]
Good morning:

I take this opportunity to thank you again for all your work and effort. And for your help in my previous question. In which at the end I understood what you wanted to tell me. And it has been of great help to me.

So I thank you again for your help and time. And for being there helping newbies. Or more than newbies like me.

I take this opportunity. To tell you about some possible new sources for your host lists. In order to make your host lists more impenetrable.

I am sorry and I ask for forgiveness, if this that I am doing, seems bad to you. It is not my intention to offend you. Nor to belittle your work. I just wanted to help you and the only way I could think of was this.

The new sources for your hosts, that I wanted to tell you about are:

1 Host Pro
https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/hosts.txt

Adguard Mobile Dns
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt
            
Anudeep Coinminer
https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt

Biroloter
https://raw.githubusercontent.com/biroloter/Mobile-Ad-Hosts/master/hosts

Blocklistproject
https://blocklistproject.github.io/Lists/ads.txt

Blocklistproject Tracking
https://blocklistproject.github.io/Lists/tracking.txt

D3ward
https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt

Data Master
https://raw.githubusercontent.com/DataMaster-2501/DataMaster-Android-AdBlock-Hosts/master/hosts

Developerdan Extended
https://www.github.developerdan.com/hosts/lists/hate-and-junk-extended.txt

Frogeye
https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt

Frogeye 2
https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt
            
GoodbyeAds
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt

Jmdugan
https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/google/all

Kaabir
https://raw.githubusercontent.com/kaabir/AdBlock_Hosts/master/host.txt

Kaabir Android
https://raw.githubusercontent.com/kaabir/AdBlock_Hosts/master/Android.txt

Jmdugan
https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/google/non_localized 

Jorgu81 Google
https://gitlab.com/Jorgu81/hosts/raw/master/Google/HostsGoogle

Jorgu81 Mozilla
https://gitlab.com/Jorgu81/hosts/raw/master/Mozilla/Mozilla

Jorgu81 Blocklist
https://gitlab.com/Jorgu81/hosts/raw/master/Router/Blocklist

Leftover
https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_leftover.txt

Leftover Agresive
https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_leftover_aggressive.txt

Molinero
https://hblock.molinero.dev/hosts

Nickspaargaren
https://raw.githubusercontent.com/nickspaargaren/no-google/master/google-domains

Nocoin
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt

Notracking
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt

Oisd Basic
https://hosts.oisd.nl/basic/

Orca
https://orca.pet/notonmyshift/hosts.txt
 
Pete Lowe blocklist hosts
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
           
Privacy Block List
https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/newhosts-final-Dual.hosts

Sebsauvage
https://sebsauvage.net/hosts/hosts

Ultimate Host
https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/master/hosts/hosts0

Winhelp 2002
https://winhelp2002.mvps.org/hosts.txt

ZeroDot1
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts

ZeroDot1  Browser
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts_browser

ZeroDot1 Opcional
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/hosts_optional

https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/download_here/mobile/hosts ( https://github.com/Clefspeare13/pornhosts )

https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt

https://github.com/KodoPengin/GameIndustry-hosts-Template

https://github.com/blocklistproject/Lists?

https://codeberg.org/twann/filters

I hope they can be of help to you in your work. And make your host lists more impenetrable.

I apologize if I did something wrong or offended you. It was not my intention. On the contrary.

Receive a warm embrace

**Comment by StevenBlack** [comment]
Thank you for this @gallegonovato.  I'd be far more receptive to one or two candidates, and reasons why those would be a good fit.

Giving us a list of 40+ sources, including some we carry already, isn't providing much insight.

Thank you regardless!

Closing.
