### ISSUE TITLE
Youtube Ads Are Back?

### ISSUE THREAD

**Issue by RyzaJr** [StevenBlack/hosts#171]
Youtube ads used to be blocked, now all of a sudden they are back.

I updated to the most recent hosts file to see if it is fixed, but it's still there.

**Comment by StevenBlack** [comment]
@RyzaJr this repo aggregates several host sources so, if YouTube ads are blockable, I'm sure someone will pick that up and we'll get it when they do.

It's possible that YouTube changed their ad delivery mechanism?

Closing.
