### ISSUE TITLE
List of domain names that aren't acceptable in your listings

### ISSUE THREAD

**Issue by Prajwal-Koirala** [StevenBlack/hosts#1710]
```
0.0.0.0 0.0.0.0.beeglivesex.com
0.0.0.0 0.0.0.0.hpyrdr.com
0.0.0.0 0.0.0.0.creative.hpyrdr.com
```

**Comment by dnmTX** [comment]
And why not,if they resolve just alright with ipv4 and ipv6 address and on top of that are flagged as malicious:
https://www.virustotal.com/gui/domain/0.0.0.0.beeglivesex.com/details

**Comment by StevenBlack** [comment]
Thanks for this Prajwal @Prajwal-Koirala and thank you Dan @dnmTX for the research and sharing your findings.

Closing.
