### ISSUE TITLE
bad address localhost

### ISSUE THREAD

**Issue by 13werwolf13** [StevenBlack/hosts#1714]
```
Jul 22 16:00:03 OpenWrt dnsmasq[3696]: bad address at /tmp/sbhosts line 22
```

```
fe80::1%lo0 localhost
```

**Comment by dnmTX** [comment]
@13werwolf13 what script you're using to fetch the hosts frome here?
Paste just that line here.

**Comment by 13werwolf13** [comment]
in crontab:
```
0 * * * *       /gethosts.sh
```

in script:
```
#!/bin/bash
/usr/bin/curl -s https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts -o /tmp/sbhosts
```

in config:
```
        list addnhosts '/tmp/sbhosts'
```

**Comment by dnmTX** [comment]
Great,now add this to the script so to look like this:
```
#!/bin/bash
/usr/bin/curl -s https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts -o /tmp/sbhosts
sed -i '/^127./,/.0.0$/d' /tmp/sbhosts
```
It will get rid of all of them,which you don't need in the first place as `OpenWrt` already took care of it by populating 
your `resolv.conf` and `resolv.dnsmasq` accordingly 👍

**Comment by 13werwolf13** [comment]
yes, I already thought about it.
I created this appeal thinking that you had a typo, but I already realized my mistake.

**Comment by dnmTX** [comment]
No typos,it just any of it is not needed for routers with custom firmware,especially when IPv6 is disabled.

**Comment by 13werwolf13** [comment]
in my device ipv6 works
but this line seemed to me wrong and reading the logs confirmed it

now I already realized that I was wrong

**Comment by dnmTX** [comment]
@13werwolf13  your `cron` setup:
`0 * * * *       /gethosts.sh`
....it runs on every minute. That's insane 😄

**Comment by 13werwolf13** [comment]
@dnmTX 
> ....it runs on every minute. That's insane 😄 

No, not every minute, every houre

**Comment by dnmTX** [comment]
> No, not every minute, every hour

Sure,my bad. But still,it's way to often. We're happy here if Stevo @StevenBlack push update once weekly 😉

**Comment by 13werwolf13** [comment]
> > No, not every minute, every hour
> 
> Sure,my bad. But still,it's way to often. We're happy here if Stevo @StevenBlack push update once weekly 😉 

It doesn't matter at the moment, I'm still testing my new config on a new device and its up-time is rarely more than half an hour.
