### ISSUE TITLE
whitelist newsletters.bancsabadell.com ?

### ISSUE THREAD

**Issue by icf20** [StevenBlack/hosts#1716]
Those awful people dong the web work now handle all the appointments using the domain `newsletters.bancsabadell.com` if this domain is blocked all appointments request via web will fail

**Comment by dnmTX** [comment]
@icf20 the domain is listed in [cname-trackers](https://github.com/AdguardTeam/cname-trackers/blob/master/combined_disguised_trackers_justdomains.txt).You can open a [issue](https://github.com/AdguardTeam/cname-trackers/issues) there and discuss it further with the maintainers.

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX I agree.  Closing.
