### ISSUE TITLE
Please include source from "spam404.com"

### ISSUE THREAD

**Issue by qarqun** [StevenBlack/hosts#1718]
Hi,

Possible to include spam404 database as your sources of hosts?
https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt

The db is available as filterlist in ublock origin. 
Thinking if you can unified this source will be a good idea.

Thanks.

**Comment by StevenBlack** [comment]
Thank you for this @qarqun 

That file is a mess.  It would take awhile to write a parser to make this file usable.

I decline.

Closing.

**Comment by felix-22** [comment]
Hi

> StevenBlack : That file is a mess.

Calling a file a mess just because it is in a different format is offensive, the file is not a mess, it's a tidy file, just that in a different format - [Adblock](https://adblockplus.org/) format, the list is also available in a pure domain format:
https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt, 
main repo https://github.com/Spam404/lists

**Comment by StevenBlack** [comment]
Please be free to take offense. I don't care.

That file is an obvious mess.

I wasn't referring to the list format. So we're clear.

The most basic attribute of a quality, properly curated list is it must be sorted.  Preferably annotated with comments.  

I don't care how it's sorted.  By domain, by TLD, chronologically, categorically... It shouldn't be an obvious dumpster fire. Like this list for example.

**Comment by felix-22** [comment]
> I wasn't referring to the list format. So we're clear.

Okay, clear now, I didn't even notice that it was unsorted anyway

By the way, a story: someone has been trying here: https://github.com/AdguardTeam/AdguardFilters/issues/51906 to explain to AdGuard Filters guys they should try to sort [their big list](https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt) and remove duplicates :smiley:
