### ISSUE TITLE
Please include source host from "urlhaus"

### ISSUE THREAD

**Issue by qarqun** [StevenBlack/hosts#1719]
Hi,

Possible to include "urlhaus" database as your sources of hosts?

**Note:** I know there is "urlhaus" source already include as source in your repo, but i find out the repo below is more frequently updated twice a day and have more info. 
You can refer the homepage for more info.

Homepage: https://gitlab.com/curben/urlhaus-filter
https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt

The db is available as filterlist in ublock origin. 
Thinking if you can unified this source will be a good idea.

Thanks.

**Comment by StevenBlack** [comment]
Hi @qarqun thank you for this suggestion.

The file https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt isn't a hosts file.  It's a list of IP addresses.

Hosts files work with domains, not IP addresses.

Closing.
