### ISSUE TITLE
YouTube watched status

### ISSUE THREAD

**Issue by itsHardStyl3r** [StevenBlack/hosts#172]
Is it an issue that youtube videos are not marked as watched?

**Comment by StevenBlack** [comment]
@HardStyl3rTV how do you mean?  I'm not familiar with this facet of YouTube.  Can you clarify?

**Comment by blaqkr** [comment]
What I do is modify the hosts file, adding a # before "0.0.0.0 s.youtube.com"
Sadly, google uses that domain to update things like history(watched videos) and other things apart from the ads (so, you'll see the video ads, but not the ones in the rest of the page)

**Comment by StevenBlack** [comment]
Another option is to use the `[whitelist](https://github.com/StevenBlack/hosts/blob/master/whitelist)` file and build your own hosts file using the [updateHostsFile.py](https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py) script.

It's easy :-)

**Comment by HardStyl3rTV** [comment]
so how can I fix it?

**Comment by StevenBlack** [comment]
@HardStyl3rTV see [How do I prevent domains from being included?](https://github.com/StevenBlack/hosts) in the readme.

**Comment by HardStyl3rTV** [comment]
@SteveBlack, yeah, but I don't know which youtube domain I have to exclude. ;)

**Comment by Atavic** [comment]
Try whitelisting
_1e100.net_

**Comment by HardStyl3rTV** [comment]
@Atavic still doesn't work.

**Comment by Atavic** [comment]
netstat command via CLI or TCPView by Sysinternals or TcpLogView by Nirsoft may help.
Once you are viewing a video, look at the remote addresses your browser connects to and try whitelisting those addresses.

**Comment by blaqkr** [comment]
I wasn't going to reply because I already told you the domain, it's s.youtube.com, in the hosts list there's s.youtube.com and s2.youtube.com, you should only exclude the former

**Comment by MohannadNaj** [comment]
well, for me, removing `s2.youtube.com`  from hosts list fixed the issue for me. including `s.youtube.com` has no effect, and removing `s2.youtube.com` also has no effect for the ads, youtube ads still remain blocked.

Screenshot of what I'm talking about:
![Screenshot](https://i.imgur.com/yM7bT7d.png)

"Loading Playlists" forever.

commenting\removing only `s2.youtube.com` from the hosts\list, fixed it.

**Comment by iSumitYadav** [comment]
please comment the line 0.0.0.0 s.youtube.com, as after installing the hosts file, YouTube watched history stopped updating for new watched videos. And commenting it, made watched history work again.
But whenever i update hosts, it get uncommented again. I'm currently using Android work Magisk module Unified hosts Manager, and moreover the whitelist functionality is broken, as i put s.youtube.com in whitelist file on my sdcard but that didn't work and only commenting that address in the hosts file itself worked!
Thanks

**Comment by StevenBlack** [comment]
@iSumitYadav the domain `s2.youtube.com` comes to us via `someonewhocares.org`.  This is an actively curated list, and they are normally very responsive and understanding.

Please make your case by addressing an explanatory email to hosts@someonewhocares.org.

**Comment by iSumitYadav** [comment]
@StevenBlack Thanks, I'll write a mail to somewhocares.org
