### ISSUE TITLE
suggest a note for tags.tiqcdn.com entry on marksandspencer.com

### ISSUE THREAD

**Issue by Antonius-git** [StevenBlack/hosts#1720]
Huge fan of the compilation, been using it for many years and will probably have a few suggestions for additions at some point :)
Got round to checking out an issue today and finally narrowed it down; felt others should know:

Users of marksandspencer.com (MnS) who wish to return one of the items they've ordered will click for their preferred method of postage (both collection in store or collection via courier work fine). Unfortunately, for Royal Mail (UK), the links generate a QR code which you can print off to attach to your parcel, however, the links will NOT work at all (they fail to load anything) if a connection to 'tags.tiqcdn.com' is blocked. 

It is only by removing/commenting out this entry from the blocklist that the site works correctly (confirmed by eliminating other variables). Additionally with uBO only, uBO did not detect any malevolent connections to tags.tiqcdn.com (+ connections) on the page in question; uBO is happy to connect to it to allow the site to function as intended but it seems this is the case for another site so it's possibly just indicative of it not hitting a uBO blocklist.

As it's clearly a nefarious (tracking) domain, I do see the need to keep the entry, however perhaps an addendum should be added to it: e.g. "#may cause issues [generating returns labels] on marksandspencer.com

It's certainly an irritating problem and one that will affect users who happen to do returns on MnS and use a DNS blocklist. 

I'm personally inclined to remove the entry altogether and let uBO keep an eye on it (as a more dynamic approach) because of the hit to the site's functionality vs having to edit the blocklist on the fly/switch to another DNS server. 
Although there are sites that have connections to tags.tiqcdn.com (example, tsb.co.uk) where uBO doesn't block the obvious tagging...so blocking it at DNS does have merit. 

For my resolution: I will block it everywhere on uBO only (remove the dns blocklist entry) but allow it on MnS. 
Bit of a mess really!

**Comment by dnmTX** [comment]
**ping** @jawz101 for assist 👍 
Your entry is listed(there is another one in yoyo.org list but it's removed as duplicate so no need to bother him for that) and if not too much trouble you can add some comment `#may cause issues on marksandspencer.com`  next to it.
Thanks as allways 😉

**Comment by jawz101** [comment]
I don't do the comment thing but it did inspire me to find that there is also a tags-eu.tiqcdn.com so I added it.

**Comment by StevenBlack** [comment]
Thank you for the kind words @Antonius-git and thanks for the suggestion.

There will always be side effects like this one.  I hate that.
