### ISSUE TITLE
Malicious domains

### ISSUE THREAD

**Issue by rai510** [StevenBlack/hosts#1721]
Research done by Bitdefender
 https://www.bitdefender.com/blog/labs/luminousmoth-plugx-file-exfiltration-and-persistence-revisited/

Already search this domain on website like virus total and urlvoid.

Malicious Domains

www.updatecatalogs.com

microsoft.updatecatalogs.com 

webmail.mmtimes.net 

myanmar.flymna.net 

new.mmtimes.org

**Comment by StevenBlack** [comment]
👍  Thank you @rai510 I've added these and this will be in the next release.

Closing.
