### ISSUE TITLE
Blocklist Suggestion 

### ISSUE THREAD

**Issue by rai510** [StevenBlack/hosts#1724]
https://github.com/hpthreatresearch

This blocklist list is maintained Hp Wolf security team and they do research every month. I am using this blocklist and never have any issue work flawlessly on my pihole.

https://threatresearch.ext.hp.com/blog/

Can you please add this lists to your blocklist. 

https://github.com/hpthreatresearch/iocs/blob/main/TA551/domains.txt
https://github.com/hpthreatresearch/iocs/blob/main/CryptBot/domains.txt

Thank you.

**Comment by StevenBlack** [comment]
Looking at these two.  Collectively that would add 627 domains, zero intersection with existing domains.

```
$ ghosts --clip
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 85,386
Bytes: 2.6 MB
----------------------------------------
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 469
Bytes: 9.7 kB
----------------------------------------
Intersection: 0 domains


$ ghosts --clip
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 85,386
Bytes: 2.6 MB
----------------------------------------
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 158
Bytes: 2.2 kB
----------------------------------------
Intersection: 0 domains
```

**Comment by rai510** [comment]
As you can see today latest commit by the research team this morning and they kept up to date.

**Comment by dnmTX** [comment]
Steve @StevenBlack in case you decide to add those two,will the script trim the blanks?

**Comment by StevenBlack** [comment]
Looking at curation history.... some observations.

For https://github.com/hpthreatresearch/iocs/blob/main/TA551/domains.txt:
* The file itself states 2020-12-14 as the earliest modification but this repo's oldest commit is from 2021-05-10
* This file appears to be an add-only bucket.  No entries have been removed since the first commit.

**Comment by dnmTX** [comment]
> This file appears to be an add-only bucket. No entries have been removed since the first commit.

Same observations here btw,no curation whatsoever. I can only guess how many are death weight/obsolete.
Didn't want to mention this earlier cause i'm allways the one criticizing,so....kept quiet this time  ¯\_(ツ)_/¯

**Comment by StevenBlack** [comment]
Looking at https://github.com/hpthreatresearch/iocs/blob/main/CryptBot/domains.txt

* Shorter history, back to June 8 2021.
* The most recent commit is August 2 but the file says `2021-07-18`.
* Also an add-only bucket.
* 158 domains, all of them with `.top` TLD. Our current tally of `.top` TLD is 197.

I'm inclined to decline these domains or, say, wait until a curation track record is established.

**Comment by dnmTX** [comment]
> or, say, wait until a curation track record is established

😄
