### ISSUE TITLE
UC Browser tracking

### ISSUE THREAD

**Issue by JobcenterTycoon** [StevenBlack/hosts#1725]
The "UC Browser" is full with tracking and there are a few unblocked tracking Domains:

`gjapplog.ucweb.com`
`logssug.ucweb.com` (tracks every visited URL)
`attr.union.ucweb.com` (tracks Google-Advertising-ID and MAC Adress)

source: `https://www.kuketz-blog.de/uc-browser-datensendeverhalten-android-app-browser-check-teil17/`

**Comment by StevenBlack** [comment]
Hi @JobcenterTycoon thank you for this.

These are added in commit https://github.com/StevenBlack/hosts/compare/f929591b...e22343e9

Closing.
