### ISSUE TITLE
Suggested host source

### ISSUE THREAD

**Issue by gallegonovato** [StevenBlack/hosts#1726]
Good afternoon:

I am writing to you with a question or suggestion. 

I happened to be looking at the Exodus Privacy website for an application. It occurred to me that it would be wonderful to have a host on Exodus Adaway (for example).

I went looking to see if there was one. And I only found https://blokada.org/mirror/v5/exodusprivacy/standard/hosts.txt but it is for blokada.

So, I don't know what you think. But it would be a very good option to add to your lists or as a source for your hosts.

I hope you take my suggestion into consideration. Best regards and thank you for your time.

**Comment by dnmTX** [comment]
The list is made out of top level domains only and with wildcard blocking in mind so the bottom line is it's just not suitable for use in hosts lists.

**Comment by StevenBlack** [comment]
Thanks Dan @dnmTX and thank you for the suggestion @gallegonovato.  That's right, the lack of subdomain specificity here is a problem.

Closing.
