### ISSUE TITLE
New redirect website found

### ISSUE THREAD

**Issue by coreynj** [StevenBlack/hosts#173]
0.0.0.0 syndication.exdynsrv.com

**Comment by StevenBlack** [comment]
We don't actually tally and maintain sites here.

You can add this site to your own recipe.  See [How do I include my own custom domain mappings?](https://github.com/StevenBlack/hosts) in the docs.

You could also submit this to one or more host file maintainers.  See the [data folder](https://github.com/StevenBlack/hosts/tree/master/data) for those.
