### ISSUE TITLE
logfiles.zoom.us - Blocking Will Cause Zoom Client Issues

### ISSUE THREAD

**Issue by joshlemon** [StevenBlack/hosts#1730]
You'll likely need to remove the `logfiles.zoom.us` domain as it'll throw a number of certificate issues for anyone using the Zoom client within their Orgs and including this list for domain blocking.

https://github.com/StevenBlack/hosts/blob/b4bcdc8a92f575ab10f5a5662a53ba939179991b/data/adaway.org/hosts#L12780

I'm not advocating that this is no longer used for ad tracking with Zoom, only that how Zoom is using it with their client has changed to HTTPS which causes Certificate Error issues if you block the domain using this list.

**Comment by StevenBlack** [comment]
Thanks for this Josh @joshlemon.

Ping @jawz101 can you please have a look?  Thank you, as always.

**Comment by lightswitch05** [comment]
I use zoom regularly, this certificate issues only shows up for me if I have a local dev server running bound to `0.0.0.0`. The certificate errors are annoying, but go away when I kill the server

**Comment by StevenBlack** [comment]
Danlel @lightswitch05 that's a fine insight!

I wonder why we don't see more of this being reported.

When I'm running a local dev webserver instance, I guess I'm never concurrently browsing the web.

**Comment by jawz101** [comment]
Removed.  Thanks

**Comment by StevenBlack** [comment]
Thanks @jawz101 I really appreciate your actions and responses to issues here.

**Comment by StevenBlack** [comment]
Closing.
