### ISSUE TITLE
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts / www.veikkaus.fi

### ISSUE THREAD

**Issue by sevkar** [StevenBlack/hosts#1731]
Veikkaus Oy Ab is Finnish official gambling company. Why this is in list?

**Comment by sevkar** [comment]
Also veikkaus.fi is there.

**Comment by rautamiekka** [comment]
Why do you think a gambling site is included in a gambling blocklist ?

**Comment by sevkar** [comment]
Fakenew-gambling, fake gambling sites? This is like porn and jesus blocking sites same list.

**Comment by sevkar** [comment]
List removed, problem solved.

**Comment by rautamiekka** [comment]
Fakenews != fake gambling sites. Fake news sites + gambling sites, not fake gambling sites.

**Comment by sevkar** [comment]
Fake news and gambling sites = different things.

**Comment by rautamiekka** [comment]
The list is an automatically created combination of those 2. There are separate lists for everything, and even some combinations which don't include the other.
