### ISSUE TITLE
Block www.portuguesinhas.com [PORN]

### ISSUE THREAD

**Issue by jfoclpf** [StevenBlack/hosts#1734]
Please block Block www.portuguesinhas.com 

safer to block everything under *.portuguesinhas.com because the name is porn suggestive 

It is clear PORN

Thanks

**Comment by StevenBlack** [comment]
Thanks João @jfoclpf!

Ping @sinfonietta or @clefspeare13.

**Comment by dnmTX** [comment]
> Ping @Sinfonietta or @Clefspeare13.

noticed who manages the repo ☝️ . If it was me i'd drop it in a heartbeat ❗

**Comment by jfoclpf** [comment]
PR made here: https://github.com/Clefspeare13/pornhosts/pull/369

**Comment by StevenBlack** [comment]
Thanks João @jfoclpf, closing.
