### ISSUE TITLE
whitelist contribution

### ISSUE THREAD

**Issue by braian87b** [StevenBlack/hosts#174]
Here is a whitelist that I found... (comments are not mine)

    cat<<'EOF' > whistelist
    #ad.doubleclick.net #This may interefere with www.sears.com
    #ads.imeem.com #Seems to interfere with the functioning of imeem.com
    #analytics-api-samples.googlecode.com
    #click.linksynergy.com #Maybe ads
    #google-analytics.com
    #googleadservices.com
    #googlesyndication.com
    #hb.disney.go.com #[disabled affects links]
    #link.p0.com #[Affects email newsletters]
    #rad.msn.com #[affects MSN Messenger]
    #refer.ccbill.com #affiliate program, to add it back, remove the #
    #secure-au.imrworldwide.com
    #stat.livejournal.com #There are reports that this may mess up CSS on livejournal
    #stats.surfaid.ihost.com #This has been known cause problems with NPR.org
    #transfer.go.com #may interfere with Disney websites
    #www.apmebf.com #qksrv     significa "cookie server"
    #www.tkqlhce.com #qksrv    significa "cookie server"
    ad.ca.doubleclick.net #intereferes with video on globeandmail.com
    adfarm.mediaplex.com #may interfere with ebay
    ads.msn.com #This may cause problems with zone.msn.com
    ak.imgfarm.com #may cause problems with iwon.com
    appleglobal.112.2o7.net #[affects Apple site]
    appleglobal.112.2o7.net #breaks apple.com
    applestoreus.112.2o7.net #breaks apple.com
    auto.search.msn.com #Microsoft uses this server to redirect
    broadcasthost #We dont want to define a broadcasthost
    cdn.visiblemeasures.com #[affects Collegehumor.com videos]
    clk.atdmt.com #[disabled affects MS downloads]
    ebay.doubleclick.net #may interfere with ebay
    global.msads.net #This may cause problems with zone.msn.com
    google-analytics.com #breaks some sites
    imagesak.secureserver.net #[affects GoDaddy programs/webmail]
    lads.myspace.com #blocks myspace media/video players
    localhost # We dont want to redefine localhost
    metrics.apple.com #[affects Apple site/MacOS]
    metrics.sprint.com #[affects login]
    rmads.msn.com #This may cause problems with zone.msn.com
    s0.2mdn.net #[affects video stream]
    s0.2mdn.net #This may interfere with some streaming 
    securemetrics.apple.com #[affects Apple site/MacOS]
    sitefinder-idn.verisign.com #of trying to hijack mistyped
    sitefinder.verisign.com #Verisign has joined the game 
    ssl.google-analytics.com #breaks some sites
    static.2mdn.net #[affects Youtube]
    switch.atdmt.com #[disabled affects Hotmail signup]
    us.i1.yimg.com #Uncomment this to block yahoo images
    www.google-analytics.com #breaks some sites
    www.youtube-nocookie.com #[affects various videos]
    EOF

**Comment by Gitoffthelawn** [comment]
Looks interesting.  Where did you find it?

**Comment by braian87b** [comment]
I don't remember well, but about a year and half or two ago I was writing a script like this one in bash, and I have downloaded this list from somewhere or maybe I made by myself... ??, but with a google search I found this below, I think I remember filtered the commented lines and reviewed later that list manually.

	#<spyware-sites>
	# Spyware and user tracking
	# By entering domains here, it will prevent certain companies from
	# gathering information on your surfing habits. These servers do not
	# necessarily serve ads, instead some are used by certain products to
	# "phone home". Others use web cookies to gather statistics on surfing 
	# habits. Among other uses, this is a common tactic by spammers, to 
	# let them know that you have read your mail. 
	# Uncomment (remove the #) the lines that you wish to block, as some
	# may provide you with services you like.

	#<maybe-spy>
	#127.0.0.1 auto.search.msn.com  # Microsoft uses this server to redirect
	                                # mistyped URLs to search engines. They
	                                # log all such errors.
	#127.0.0.1 sitefinder.verisign.com	# Verisign has joined the game 
	#127.0.0.1 sitefinder-idn.verisign.com	# of trying to hijack mistyped
						# URLs to their site. 
						# May break iOS Game Center.

	#127.0.0.1 s0.2mdn.net		# This may interfere with some streaming 
					# video on sites such as cbc.ca
	#127.0.0.1 ad.doubleclick.net   # This may interefere with www.sears.com
					# and potentially other sites. 
	127.0.0.1 media.fastclick.net	# Likewise, this may interfere with some
	127.0.0.1 cdn.fastclick.net	# sites. 
	#127.0.0.1 ebay.doubleclick.net		# may interfere with ebay
	#127.0.0.1 google-analytics.com			# breaks some sites
	#127.0.0.1 ssl.google-analytics.com
	#127.0.0.1 www.google-analytics.l.google.com
	#127.0.0.1 stat.livejournal.com		# There are reports that this may mess 
	 					# up CSS on livejournal
	#127.0.0.1 stats.surfaid.ihost.com	# This has been known cause 
						# problems with NPR.org
	#127.0.0.1 www.google-analytics.com		# breaks some sites
	#127.0.0.1 ads.imeem.com		# Seems to interfere with the functioning of imeem.com
	#</maybe-spy>

here: [http://someonewhocares.org/hosts/](http://someonewhocares.org/hosts/)

**Comment by Gitoffthelawn** [comment]
Thanks for figuring that out @braian87b

**Comment by StevenBlack** [comment]
We already carry http://someonewhocares.org/hosts/.

Closing.
