### ISSUE TITLE
Remove static.ordergroove.com from blocklist

### ISSUE THREAD

**Issue by remitaffin** [StevenBlack/hosts#1740]
Ordergroove was added to AdAway by mistake and was removed about 1 hour ago:
https://github.com/AdAway/adaway.github.io/commit/9ad48c8291928ef968770767f978f174160ce525

Would it be possible for you to also remove us from your blocklist? https://github.com/StevenBlack/hosts/blob/master/data/adaway.org/hosts#L8922-L8923

Ordergroove does not provide any ads or irrelevant content to the customers. For more information about what we do and how we provide value to our customers, please see the original request:
https://github.com/AdAway/AdAway/issues/2815

Thanks!

**Comment by ler762** [comment]
On 8/19/21, Remi Taffin wrote:
> Ordergroove was added to AdAway by mistake and was removed about 1 hour
> ago:
> https://github.com/AdAway/adaway.github.io/commit/9ad48c8291928ef968770767f978f174160ce525
>
> Would it be possible for you to also remove us from your blocklist?
> https://github.com/StevenBlack/hosts/blob/master/data/adaway.org/hosts#L8922-L8923
>
> Ordergroove does not provide any ads or irrelevant content to the customers.
> For more information about what we do and how we provide value to our
> customers, please see the original request:
> https://github.com/AdAway/AdAway/issues/2815

Could you explain this
  "While Ordergroove injects dynamic content to load the subscriptions
modal inside the product page (via static.ordergroove.com), "

I'm missing why you think that should be allowed.  The screenshot supplied
  https://user-images.githubusercontent.com/9221626/120524666-4df73980-c3a5-11eb-892f-323a89f8256d.png
shows a GNC.com web page with an order form "injected by
static.ordergroove.com" that sure looks like an ad to me.
And the screenshot looks like the url bar has a padlock.. I'd be
interested in hearing how static.ordergroove.com was able to inject
content into a 3rd party webpage.
  (or does gnc not have a problem with ordergroove taking their customers?)

Thanks!

**Comment by StevenBlack** [comment]
This is resolved upstream/

Thanks Remi @remitaffin.

Closing.
