### ISSUE TITLE
Whitelist mrgugu.com

### ISSUE THREAD

**Issue by andreasbrett** [StevenBlack/hosts#1741]
Please whitelist mrgugu.com (currently in **hosts** and **alternates/fakenews-gambling-porn-social/hosts**). It's an online shop for (extraordinary and/or weird) clothing.

**Comment by dnmTX** [comment]
@andreasbrett  if you don't mind report it upstream: https://github.com/PolishFiltersTeam/KADhosts/issues  👍

**Comment by andreasbrett** [comment]
Thanks for the hint. It's online so closing this one.

https://github.com/PolishFiltersTeam/KADhosts/issues/45
