### ISSUE TITLE
False positive - cdn.shortpixel.ai ?

### ISSUE THREAD

**Issue by pdobrescu** [StevenBlack/hosts#1743]
Hello and thanks for creating and maintaining this awesome list!

I am contacting you on behalf of ShortPixel and we are providing an [image optimization service](https://shortpixel.com/) used by tens of thousands of websites and has nothing to do with ads, malware, or other types of reasons why domains are present on your lists. The domain `cdn.shortpixel.ai` is used to serve optimized images for the sites through our [WordPress plugin](https://wordpress.org/plugins/shortpixel-adaptive-images/) and we do our best to block any site that misuses our services. However, that's not always possible as you already know.

Therefore, I'm kindly asking you to tell us what do we need to do to be removed from your lists and I assure you of our full cooperation. We don't know the reasons why we have been added to the https://github.com/StevenBlack/hosts/blob/master/data/adaway.org/hosts list and we'll do our best to fix whatever issue has caused our domain to be listed here. I was only able to identify that it was added in [this commit](https://github.com/StevenBlack/hosts/commit/5c47b168d148362e5be2604a8b214640c48137a4), which contained an update of that list:

Thank you!

**Comment by llacb47** [comment]
ping @jawz101

**Comment by jawz101** [comment]
removed.  thanks

**Comment by pdobrescu** [comment]
Wow, this was super fast! You guys are awesome! Many thanks @jawz101 and @llacb47 ! Keep up the great work!

This issue can now be closed.

**Comment by StevenBlack** [comment]
Thanks for this Pedro @pdobrescu.

This is now live in the latest release.

Closing!
