### ISSUE TITLE
[request] add block for Pegasus domains to (adware + malware)

### ISSUE THREAD

**Issue by Domiuns** [StevenBlack/hosts#1744]
Hi can you add these domains https://github.com/AmnestyTech/investigations/blob/master/2021-07-18_nso/domains.txt from the github repository https://github.com/AmnestyTech/investigations/tree/master/2021-07-18_nso (NSO Group Pegasus Indicator of Compromise) to (adware + malware)?
you can read more at https://www.washingtonpost.com/investigations/interactive/2021/nso-spyware-pegasus-cellphones/ or search Pegasus spyware.

Thank you very much, have a nice day.

**Comment by StevenBlack** [comment]
Hi @Domiuns thank you for this.

I'm very tepmptd to include this.  But there is no license to do this.  See https://github.com/AmnestyTech/investigations/issues/11.

**Comment by StevenBlack** [comment]
@Domiuns I notice that Dan Pollock, one of our source list curators, who publishes the [someonewhocares](https://someonewhocares.org/) now includes these Pegasus domains.  So by extension, so do we, starting with the latest release.

(I had the 1,406 domains from AmnetsyTech in my system clipboard when I ran this)

```
$ ghosts --clip
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 89,493
Bytes: 2.7 MB
----------------------------------------
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 1,406
Bytes: 25 kB
----------------------------------------
Intersection: 1,406 domains
```

Closing.

**Comment by Domiuns** [comment]
Thanks @StevenBlack for updating the list to include the domains.
