### ISSUE TITLE
Microsoft websites don't work

### ISSUE THREAD

**Issue by ccfman2004** [StevenBlack/hosts#1748]
What addresses do I have to delete to get Microsoft websites like xbox.com properly working as nothing loads or works properly unless I remove the hosts file?

**Comment by StevenBlack** [comment]
Hi Charles @ccfman2004 thank you for this.  I don't own an xBox, and I don't know anyone who does.

Can you help us identify which listed domains xBox depends?

**Comment by ccfman2004** [comment]
I have no idea. That's why I asked here as sites like support.microsoft.com and support.xbox.com don't work unless the hosts file is removed. I couldn't even file a repair request when the hosts file from here was loaded.

**Comment by Konfekt** [comment]
Same goes for the Windows Update; seemingly some servers that it depends on to install KB5005033 figure on the hosts lists, leading to an error code 0x8007045b. It is hard to pinpoint which ones --- removing all those that match `microsoft` does not suffice to make the update go through.

**Comment by LipkeGu1810** [comment]
https://docs.microsoft.com/de-de/windows/privacy/manage-windows-20h2-endpoints

**Comment by Zelo72** [comment]
The following domains are accessed when calling support.xbox.com and support.windows.com:

```
support.xbox.com
wcpstatic.microsoft.com
www.xboxab.com
auth.assist.gameservices.xboxlive.com
content.assist.gameservices.xboxlive.com
uhf.microsoft.com
browser.events.data.microsoft.com
statics-marketingsites-neu-ms-com.akamaized.net
mem.gfx.ms
static2.sharepointonline.com
inbox.assist.gameservices.xboxlive.com
spoprod-a.akamaihd.net
support.microsoft.com
img-prod-cms-rt-microsoft-com.akamaized.net
support.content.office.net
login.microsoftonline.com
www.microsoft.com
login.live.com
web.vortex.data.microsoft.com
logincdn.msauth.net
browser.pipe.aria.microsoft.com
prod-video-cms-rt-microsoft-com.akamaized.net
amp.azure.net
```
The following domains are on the SB list:

```
browser.pipe.aria.microsoft.com
web.vortex.data.microsoft.com
```

I don't believe these cause the page to be inaccessible.

Greets,
Gerd

**Comment by ccfman2004** [comment]
It's not that the page is inaccessible, the page can't fully load or gives me a website error.  I wasn't able to complete an Xbox repair request until I removed the hosts file from here so there is a domain being blocked in it that is causing the repair request site not to fully work.  As for the Xbox Support site the page just gives me an animated circle and never loads anything.

**Comment by Zelo72** [comment]
Works fine for me with SB hosts active.

![grafik](https://user-images.githubusercontent.com/62211544/135212287-c5718f9b-f82d-4388-ab73-827c68f60ccb.png)

**Comment by remmah** [comment]
I have encountered the issue with support.xbox.com not loading.

The following entry appears to be responsible:

`statics-marketingsites-eus-ms-com.akamaized.net`

Allowing that domain will cause support.xbox.com to load.

**Comment by ccfman2004** [comment]
> I have encountered the issue with support.xbox.com not loading.
> 
> The following entry appears to be responsible:
> 
> `statics-marketingsites-eus-ms-com.akamaized.net`
> 
> Allowing that domain will cause support.xbox.com to load.

That did the trick. Thanks

**Comment by StevenBlack** [comment]
Thank you for the followup Charles @ccfman2004!

The domain `statics-marketingsites-eus-ms-com.akamaized.net` comes to us via Adaway. I don't expect to request the removal of this domain.

**Comment by ccfman2004** [comment]
It seems that whether the support site works or not depends on what country you have set to view. If you set the xbox site to use the UK section the site works as it should. If you use the USA section that hosts entry stops it from working.

Maybe attach a comment next to entry letting users know that support.xbox.com may not work if that entry is enabled.

**Comment by StevenBlack** [comment]
Thanks Charles @ccfman2004 that's interesting.

**Comment by StevenBlack** [comment]
Closing.

**Comment by ccfman2004** [comment]
I can definitely confirm that statics-marketingsites-eus-ms-com.akamaized.net does indeed prevent support.xbox.com from loading on MacOS 11 in the US.  I used a fresh hosts file I downloaded April 17 2022 from here. If I don't comment anything support.xbox.com does not load and gets stuck on the Xbox logo with the spinning ring of light. If I only comment out statics-marketingsites-eus-ms-com.akamaized.net and flush DNS cache support.xbox.com loads instantly. 

Not exactly sure why it requires that address but I can't get the site to load unless I comment it out.

Thanks.

**Comment by StevenBlack** [comment]
Thank you Charles @ccfman2004.

Ping @jawz101, can you assess domain `statics-marketingsites-eus-ms-com.akamaized.net`?  It's for xBox users...

**Comment by jawz101** [comment]
removed

**Comment by StevenBlack** [comment]
Thanks J @jawz101!
