### ISSUE TITLE
Hosts-BL: Simple executable/binary tool to reformat host file black lists to a number of different formats

### ISSUE THREAD

**Issue by ScriptTiger** [StevenBlack/hosts#1749]
Greetings all!

I've been a bit quiet the last couple years since COVID kicked off due to the tighter resources and higher stress levels I'm sure many of us have been dealing with. However, I've started to go back through some of my older projects and rewrite them in Go. Of course, the original scripts serve as a good prototype and everyone that contributed to those projects, I thank you immensely and your feedback and contributions are, of course, still welcome, as always.

The new Go versions run in a fraction of the time it takes an interpreted language to perform the same task, use a fraction of the resources overall, it's a simple enough language to allow me to make meaningful iterations fairly quickly (this was a big reason for not going with C, Rust, etc.), and it's super quick and easy to cross-compile. But rest assured, I will also continue to maintain all of my old scripts since there is still a niche use case there for those Windows users that don't want to use third-party executables.

Available for Windows, Linux, and Mac:
https://github.com/ScriptTiger/Hosts-BL

While this application is cross-compiled for Windows, Linux, and Mac, I actually only have minimal experience and access to modern Mac architectures. So while I can directly address OS-specific issues for Windows and Linux, since I use those daily, Mac users may need to do further testing and let me know if there's anything that's funky happening on Mac.

**Comment by StevenBlack** [comment]
Hi @ScriptTiger I would entertain a PR that adds a reference to [Hosts-BL](https://github.com/ScriptTiger/Hosts-BL) to the [readme_template](https://github.com/StevenBlack/hosts/blob/master/readme_template.md) under the [Interesting Applications](https://github.com/StevenBlack/hosts/blob/master/readme_template.md#interesting-applications) section.

**Comment by ScriptTiger** [comment]
@StevenBlack, always a pleasure to entertain you :P

Seems you've been going a bit wild with Go yourself as of late, so excited to see we're finally speaking the same language.

**Comment by StevenBlack** [comment]
Closing!
