### ISSUE TITLE
hostsfile disrupts `bower install`

### ISSUE THREAD

**Issue by supernintendo** [StevenBlack/hosts#175]
Using this hosts file, `bower install` with [bower](https://github.com/bower/bower) will fail with a `CERT_HAS_EXPIRED` error every time. I'll try to look into this more to identify the problematic entry.

Best,

Matyi

**Comment by StevenBlack** [comment]
Thanks.  Keep an eye on this.

**Comment by funilrys** [comment]
Hi there,
any update on this ?

**Comment by supernintendo** [comment]
No idea; I no longer use this project or Bower.

Best,

**Comment by funilrys** [comment]
@StevenBlack Can you reproduce ? 
This may be closed.

**Comment by StevenBlack** [comment]
Closing.
