### ISSUE TITLE
Malware domain to be added

### ISSUE THREAD

**Issue by pradorocchi** [StevenBlack/hosts#1752]
I am not sure if here is the right place for me to suggest and addition, or submit it for analysis [as an issue]
Please correct me with instructions if I am doing this the wrong way :) Thanks.

Purpose:
I suggest an addition to malware domains, which is the URL below. 
The URL when accessed on MacOS, using a macbook [which is what I use], tries to induce the person to install a malware.. (which is signed by apple and is a long and persistent well known history...) and it is not considered "Minor" 
I haven't tested it on MS Windows.. but I suppose should try to do something similar and potentially dangerous .. 

StevenBlack DNS block list does not have this domain yet, I just checked it. 

(PS: out of context here on the writeup: I also use AdGuard, and AdGuard is not aware of this domain either.. [I will notify the developers and send a push request to them later,  ince I am an active member of the filters developers, and although I am not part of the company, I develop filters here on github as a free contributor to their filters)

Continuing: 
So I ask you, Steven, to please verify the URL and analise it, decide about it, and: include it on the DNS filter lists, or not, or send it to 3rd party appropriate entities [which are other source block lists used here]... etc.. :)

the URL, which shows a page instructing, and inducing, the user to install the mentioned fake antivirus package:

https://org-upgrade.com/MACE-03-02-b72QFwKeRMtHXETTKQRVRAep/error.html?prod=Norton&xe=aHR0cHM6Ly9lb21zZXkuZGltdXJxLmNvbS9yZWRpcmVjdD9sPWFIUjBjSE02THk5a2JDMWtiM2R1Wm1GemRDNWpiMjB2UDJFOU16QXpOVE1tWXoweU1UZzBPRE1tY3pJOU5tVTBNR1l3WlRndE5qSXdaQzAwTnpJekxXSXdPVFl0TmpRd05HTTJOVGhqTlRVMUpuTXpQVEV4T1RRME5Ua18mdD0xNjMwMzc2NjU4Jmg9ODA5NGU1MGIxOTgwM2U3OWFhYWEzNThkZjM4MjcyOTI_&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYzMDM3NTMzOH19fV19&Key-Pair-Id=APKAIVB2XEI4JJOOG6RA&Signature=gb4hnyqhfOM72W-wbzl9MZxxELKjbRH21dlAEh4hbTW4hCUWQpyYR5yAp4TLq3d3LdkXgVvcMEZ-OVtPnyq0GnJLVUnbBCXOEYbk4lzQ4IsALDV5dd9RKLjzbhr1miw7EJie0AONUZZiB7mZEG4o7mBDflTXV

  

for any questions: feel free to ask me.

My expectations: 
just to contribute and help/try to put some order on the entropy on the bad world of unwanted ads/fakeinducers/badurls/etc..
 
Which I owe a debit of gratitude to you (as a happy user of the StevenBlack lists for years), and your effort on making the internet a better navigation world.

**Comment by StevenBlack** [comment]
Hi Rafael @pradorocchi thank you for this.  Which domain, specifically, should be added?

I'm not following that link 🙃

**Comment by dnmTX** [comment]
`0.0.0.0 org-upgrade.com`

P.S. @pradorocchi be a responsible person and backquote that link please.

**Comment by StevenBlack** [comment]
Done!  Thanks Rafael @pradorocchi and thank you for the reminder Dan @dnmTX.
