### ISSUE TITLE
whitelist cdn.jsdelivr.net

### ISSUE THREAD

**Issue by blizzardengle** [StevenBlack/hosts#1754]
This site is used to serve [LESS](https://lesscss.org/) via https://cdn.jsdelivr.net/npm/less@4.1.1

**Comment by StevenBlack** [comment]
Hi Christopher @blizzardengle thank you for this.  The `cdn.jsdelivr.net` domain comes to us from two sources.

@brijrajparmar2 why is this in your list?

The other source is mvps.org, one of our oldest and most respected curators.  Christopher @blizzardengle please submit this to winhelp2002@gmail.com and see what they say.

**Comment by brijrajparmar27** [comment]
hello Steven @StevenBlack, 

thankyou for informing me, i have removed `cdn.jsdelivr.net` from my list.
it looks like my script mistakenly flagged the given cdn as one for the targeted porn site ones, this is unusual, i'll look into it.

thanks again.     :)

**Comment by dnmTX** [comment]
Steve @StevenBlack small correction. 
The domain is commented therefore harmless and @blizzardengle doesn't need to contact mvps.org at all:
![hosts](https://user-images.githubusercontent.com/34774426/131785437-8573a3ff-240e-4944-aaef-124f87606a45.png)

**Comment by Lateralus138** [comment]
Sorry if this is not directly related to this issue, but it's related to *JSDELIVR* and my cli tool for the *HOSTS* files here so I don't know where to ask/comment.

My cli tool uses `cdn.jsdelivr.net` to download the files at this repo and so I was slightly concerned when I seen this issue, but ***am I correct in assuming (from what I'm reading here) that this service (cdn.jsdelivr.net) is safe to keep using?*** I'll be rewriting this tool sometime soon anyway with a different method, but I want to make sure my tool is safe *in the meantime* and I've not read or heard anything bad about this service before.

**Comment by brijrajparmar27** [comment]
hello @Lateralus138 

JSDelivr is a free public CDN for open-source projects, it's addition to my hosts list was a pure mistake from my end and as far as mvps.org host goes, as dnmTX pointed out The domain is commented therefore harmless.

we have no reason to believe cdn.jsdelivr.net is not safe to keep using.

thanks for reaching out.

**Comment by Lateralus138** [comment]
Hi @brijrajparmar27
Thanks for the prompt reply and I figured as much. Like I said, I'm just making sure.
Again. much appreciated!

**Comment by StevenBlack** [comment]
Thanks @blizzardengle and everyone for the assist.

Closing.
