### ISSUE TITLE
go-mpulse.net

### ISSUE THREAD

**Issue by gyCfjSnO** [StevenBlack/hosts#1756]
Unable to checkout and pay for groceries when domain `go-mpulse.net` is blocked when using the Woolworths (large Australian grocery chain) App on Android.

Whitelisting `go-mpulse.net` allowed me to pay, when it isn't whitelisted the text box to input CVV disappears.

**Comment by dnmTX** [comment]
**ping** jawz101 for assist 👍

**Comment by jawz101** [comment]
What's the group opinion on this one?

https://github.com/akamai/boomerang
https://developer.akamai.com/tools/boomerang/

**Comment by gyCfjSnO** [comment]
Any reason why having it blocked stopped the payment gateway from loading in the app?

**Comment by gyCfjSnO** [comment]
Thought this would be relevant but this domain and response is generated before the app calls `go-mpulse.net`

`Domain
iframe.payments.woolworths.com.au
Type
A
Protocol
Plain DNS
Response details
DNS server
tls://dns10.quad9.net:853
Elapsed
35 ms
Response
CNAME: api.payments.woolworths.com.au.edgekey.net. (ttl=3096)
CNAME: e3032.a.akamaiedge.net. (ttl=8258)
A: 104.98.18.129 (ttl=20)`
![Screenshot_20210903-120523](https://user-images.githubusercontent.com/49738152/131939659-3ed3a205-2c18-4287-9d8e-5edeeb772827.png)

**Comment by dnmTX** [comment]
Usually is because of poorly implemented error handling(if any at all),so i'd assume that this is the case here.

**Comment by dnmTX** [comment]
This one is redy for closing Steve @StevenBlack 👍

**Comment by StevenBlack** [comment]
Thanks everybody!

Closing.

**Comment by gyCfjSnO** [comment]
> This one is ready for closing Steve @StevenBlack 👍

Just wanted to check if it will be removed from StevenBlack's List as well?

As it was removed from AdAway List.

Thank you!

**Comment by StevenBlack** [comment]
@gyCfjSnO the domain is completely removed, yes.
