### ISSUE TITLE
audioboom.com

### ISSUE THREAD

**Issue by kzshantonu** [StevenBlack/hosts#1757]
Popular and legitimate podcast hoster

**Comment by dnmTX** [comment]
**ping** @jawz101 for assist

**Comment by jdelStrother** [comment]
Hi there - I work at Audioboom. Let us know if there's anything we can do to fix this.

**Comment by jawz101** [comment]
it's been removed yesterday

**Comment by StevenBlack** [comment]
Thanks @jawz101 and thanks for reporting the issue Kazi @kzshantonu.

Closing.
