### ISSUE TITLE
Cinemagia Android has placeholders

### ISSUE THREAD

**Issue by gemoshi07** [StevenBlack/hosts#1758]
Hello, I'm talking about this [app](https://play.google.com/store/apps/details?id=cinemagia.mobile) and inside of it I see some placeholders from ads between rows(you press on "TV" button from the bottom of the screen, then go to any category from there, e.g "Filme la TV" and the placeholders are there).  Can this issue be fixed? Thanks!

**Comment by StevenBlack** [comment]
Thank you for this @gemoshi07.

We can't help because we need to know which specific domains are used to convey these ads.

Closing.
