### ISSUE TITLE
sentry.io

### ISSUE THREAD

**Issue by houmark** [StevenBlack/hosts#1759]
sentry.io is a legit service that helps websites and web apps receive crash reports from visitors. It should not be blocked, it's services like this that make the internet better. As a developer and maintainer of a platform, it helps us monitor the stability of our platform and the performance of the platform.

**Comment by StevenBlack** [comment]
Thanks for this @houmark.

Ping @jawz101 it looks like `sentry.io` has reappeared on the AdAway list.

**Comment by jawz101** [comment]
removed.  thanks

**Comment by StevenBlack** [comment]
Thanks @jawz101!

@houmark this is now resolved in the [latest release](https://github.com/StevenBlack/hosts/releases).

Closing.

**Comment by pcjmfranken** [comment]
Their website and documentation is all about custom events, breadcrumb trails, data enrichment, info level alerts, business intelligence, live cross-environment monitoring, automated forwarding to third parties.

If Google Analytics is blocked, these types of services should be also - especially considering their popularity with installable software which enables access to far more invasive data collection.
