### ISSUE TITLE
Blocking anything related to google request

### ISSUE THREAD

**Issue by troublew** [StevenBlack/hosts#176]
Hie, I'm searching since a long time a hosts file which would ban anything related to google, but I don't find anything.
Can you add an extension doing that or at least just point me out a hosts file who index all of the google domains?
Thanks.

**Comment by AKJT** [comment]
Here are two **lists** of **google domains**.
Maybe this is what you are looking for.

https://github.com/racaljk/hosts/blob/master/hosts#L393
https://github.com/txthinking/google-hosts/blob/master/hosts

Just change the ip :hammer:

**Comment by Atavic** [comment]
Ban anything? Block the Google owned IP on router/firewall.

**Comment by troublew** [comment]
That's what I was searching for, all the Google owned IP. I don't know where to find them.
And by banning ip, you mean adding rules in iptables? I don't know if hosts can block any ip.

**Comment by Atavic** [comment]
Command query for the owned netblocks:
`nslookup -q=TXT _spf.google.com 8.8.8.8` 

A second query on the returned netblock list:
`nslookup -q=TXT _netblocks.google.com 8.8.8.8`
`nslookup -q=TXT _netblocks2.google.com 8.8.8.8`
`nslookup -q=TXT _netblocks3.google.com 8.8.8.8`

All of the above in a [bash script](https://gist.github.com/Atavic/bf6c56322eefbde89ea7c7d0e134058c) that should give the officially owned ip list.
