### ISSUE TITLE
coininsider.com blocked

### ISSUE THREAD

**Issue by mokahless** [StevenBlack/hosts#1761]
coininsider.com is blocked in hosts but appears to be a normal news site.

I double-checked by searching the URL on reddit to see if there were any scam issues and all appears normal.

**Comment by StevenBlack** [comment]
Hi @mokahless thank you for this.

The domain `coininsider.com` comes to us from the KADhosts list.  Can you please report this concern at the link below?  Thanks.

https://github.com/PolishFiltersTeam/KADhosts/issues
