### ISSUE TITLE
remove clickhouse.com

### ISSUE THREAD

**Issue by gowthamgts** [StevenBlack/hosts#1765]
please remove clickhouse.com from the blocklist. currently it's a valid domain.

more context: https://news.ycombinator.com/item?id=28595911

**Comment by StevenBlack** [comment]
Hi @gowthamgts – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

The MVPs list currently has `www.clickhouse.com`.  Please submit this concern to winhelp2002@gmail.com
