### ISSUE TITLE
make a new list for porn lovers

### ISSUE THREAD

**Issue by geekytricky** [StevenBlack/hosts#1767]
make a new list of bad porn sites and others, exclude good ones (example: pornhub, xvideos etc)

**Comment by StevenBlack** [comment]
Thanks @geekytricky, that's an interesting idea. However I'm not sure I want to be picking porn for some people, you know? 😄 

Closing.

**Comment by felix-22** [comment]
Indeed, a good idea, I've been thinking about this as well, even before I've found this thread. 

All anti-porn lists I found in internet are same type: block all porn, as if no one visits porn sites, when the truth is that half the people do visit, and they only need to block the bad porn sites.

Many porn sites are really badware and should be blocked: 
- porn farms, fake porn sites, badware porn sites <== they are useless, have no content
- some disgusting category of porn like: zoo / animal <== disgusting, only perverts and psychos watch it and do it, normal people don't do that
- stupid hentai / anime / manga <== why even to watch these stupid anime porn sites? As if real porn sites don't exist, of which there are plenty
- gays <== disgusting as well

**Comment by rautamiekka** [comment]
>   * zoo / animal <== disgusting, only perverts and psychos watch it and do it, normal people don't do that

Not how it works. You've no clue what you're talking about.

>   * stupid hentai / anime / manga / cartoon / 3d <== why even to watch these stupid artifical porn sites? It's like doing it with an inflatable or a plastic doll, only crazy people watch it, as if real porn sites don't exist, of which there are plenty...

That's your problem, don't project your prefs as global fact.

>   * gays <== disgusting as well

_Does someone here got a racist card or 2 ?_
