### ISSUE TITLE
Please add sessions.bugsnag.com & in.appcenter.ms to the list.

### ISSUE THREAD

**Issue by CanIHelp101** [StevenBlack/hosts#1768]
A VPN provider utilizes this list however, these are 2 common domains on iOS atleast, that most apps automatically connect to, to gather various analytics data and privacy invasive Bug/Crash Reporting. Please cosider adding "in.AppCenter.ms" and "sessions.bugsnag.com" to the list.

**Comment by StevenBlack** [comment]
Thank you for this suggestion @CanIHelp101.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
