### ISSUE TITLE
[review] orca.pet list revalidation

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#1769]
Link to the curator's issue(for refference):
https://github.com/socram8888/not-on-my-shift/issues/12
Will wait for response,hopefully resolution as well 👍

**Comment by dnmTX** [comment]
@spodermenpls just FYI. That whole(original) `autodiscover.*` list is purely based on assumption. 
Reading trough the article you posted the author symply described the problem and the next thing was:
"Hey,we don't know what's the next `autodiscover.*` domain will be so haow about we cover them all.We'll add every possible TLD out there to it so to be on the safe side"
This is not how you mitigate an issue,by making up none existing domains and certanly not how things work here!

**Comment by dnmTX** [comment]
Steve @StevenBlack  the curator [replied](https://github.com/socram8888/not-on-my-shift/issues/12#issuecomment-932043141) so up to you. 
My opinion,still the same: 👎

**Comment by StevenBlack** [comment]
A list of things that bug me about all this:

* This issue affects only ***Microsoft Exchange*** servers.  Supposedly an old bug in MS Exchange that MS never fixed.  I reckon the number of Exchange servers running this hosts file is pretty close to zero. This list exists to protect userland devices, not misconfigured Microsoft Exchange servers from bugs Microsoft itself has determined is not a bug.
* The curator accepted, without discussion, the word of a GitHub anon with no history, and quadrupled the size of the list.
* 8,400 domains were added without the merest validation.  I caught the error. I often catch curation errors, but this takes the cake.  So I question the curatorial attention to detail. This reminds me of the [CoinblockerList incident](https://github.com/StevenBlack/hosts/issues/1045) 🙄.
* After all this, 880 `autodiscover.*` domains remain, which is still a 25% increase in orca.pet's list size. Looking at curation patterns generally, over the years, adding several hundred domains like this doesn't happen very often.

There's nothing cool about this.  Red flags everywhere.

**Comment by dnmTX** [comment]
....and to add to the posted above(i couldn't described it better Steve 👍 ) part of the curator'reply:
```
The idea behind adding these domains before they exist is exactly to have them blocked before they supposed to be a threat - playing whack-a-mole with the isn't gonna be fun.
```
This is not a curation,not even close. It's a pure gambling. Not cool 👎

**Comment by spodermenpls** [comment]
@dnmTX 
> @spodermenpls just FYI. That whole(original) `autodiscover.*` list is purely based on assumption. Reading through the article you posted the author simply described the problem and the next thing was: "Hey,we don't know what the next `autodiscover.*` domain will be so how about we cover them all.We'll add every possible TLD out there to it so to be on the safe side" This is not how you mitigate an issue,by making up non existing domains and certainly not how things work around here!

I've only re-posted the article by that group of analysts that the Issue reporter had brought up, which started the latest newscycle on this issue. I've read about this issue shortly before, however only in articles in my native German tongue, which most people here probably aren't fluent in. 😅

One interesting detail I've learned about is Microsoft being in the process of buying up / registering all available Autodiscover domains to pull them off the market, before they might get used for malfeasance.

**Comment by StevenBlack** [comment]
He's gone.
