### ISSUE TITLE
Add hulkoutdoor.com is.gd mplmnt.io to the list

### ISSUE THREAD

**Issue by ahasbini** [StevenBlack/hosts#1770]
The following URL attempts to trick a user into fraud transactions appearing as a legitimate company. The URL performs redirects to other hostnames.

URL received via SMS:
https://is.gd/ARAMEXQATAR

URL Redirects:
http://hulkoutdoor.com/PARCELARAMEX/AE/
http://www.hulkoutdoor.com/PARCELARAMEX/AE/
https://sk.mplmnt.io/ARAMEXINTERNATIONAL/CRF/

Thanks

**Comment by ahasbini** [comment]
Further looking into each hostname and have the following updated details:

is.gd is a link shortener, this appears to be legitimate website used for questionable means.
hulkoutdoor.com homepage appears to be a website that sells products.
sk.mplmnt.io does not have a homepage and returns HTTP 500 INTERNAL SERVER ERROR.
mplmnt.io homepage appears to be service provider for software solutions.

IMHO, the following should only be added to the list for publishing URL that redirects the user to a phishing site/fraud transactions.

hulkoutdoor.com
sk.mplmnt.io
mplmnt.io

**Comment by StevenBlack** [comment]
Thank you for these suggestions @ahasbini, and for the followup legwork.

![IMG_3520](https://user-images.githubusercontent.com/80144/135701785-87f1e92d-9c8c-4a04-a878-90eda77129b7.GIF)

**Comment by StevenBlack** [comment]
My guess: `hulkoutdoor.com` has been hacked, and the actionable domain here is `sk.mplmnt.io`.

**Comment by StevenBlack** [comment]
Thanks @ahasbini this is going live in the next release.

Closing.
