### ISSUE TITLE
add revmasters.com rowilo.com webpartners.co tuvene.com

### ISSUE THREAD

**Issue by lowfuel** [StevenBlack/hosts#1772]
These all seem to be related to online gambling ad servers and/or the affiliate destinations they redirect you to.

**Comment by StevenBlack** [comment]
Hi @lowfuel thank you for this.

I'm going to need more evidence to consider block these domains.

In particular, the `revmasters.com` and `webpartners.co` appear to be home pages. The sort of operations you describe never serve from their root domains.  We're not in the business of making companies go dark on the web, just their vectors for adware, tracking, and malware.  So I'm going to need the specific domains they use, not just their root domains.

**Comment by dnmTX** [comment]
Steve @StevenBlack  `revmasters.com` and `webpartners.co` are online gambling sites so **ping** @Sinfonietta for them.
I couldn't find anything on the other two as they're newly registered.
Hope this helps 👍

**Comment by lowfuel** [comment]
Hi @StevenBlack! Sorry for the lack of info, this was my first time reporting anything here, I wasn't sure what the protocols were.
These domains came from my logs after my son clicked on a suspect link (oof), resulting in a plethora of gambling and sports related redirects leading to endless ads.

From what I can tell from my logs, rowilo.com and tuvene.com were the sites doing the redirects, and they appeared in my list as root domains. Perhaps they are legitimate redirect services?

For the other two, the specific domains were:
record.revmasters.com
record.webpartners.co

I hope that helps. And apologies if this was a mis-report.

Cheers,

Jason

**Comment by Sinfonietta** [comment]
This is done @dnmTX thankyou.

**Comment by StevenBlack** [comment]
All-good Jason @lowfuel thanks for all your input, appreciate it.  We'll sort this.  @Sinfonietta, our gambling curator, has listed the gambling domains already.  The redirects are next.
