### ISSUE TITLE
Bogus porn host: *.bp.blogspot.com

### ISSUE THREAD

**Issue by Berbe** [StevenBlack/hosts#1773]
The following hosts:
- `1.bp.blogspot.com`
- `2.bp.blogspot.com`
- `3.bp.blogspot.com`

belong to the `porn` list.

However, these domains are used by blogger, ex-blogpost to host static content, generally pictures.
Blocking these domains hurts viewing any content hosted on this platform.

Shouldn't those domains be removed from any blacklist?

**Comment by dnmTX** [comment]
@Berbe you can open a issue [upstream](https://github.com/Clefspeare13/pornhosts/issues) and discuss it further with
**whoever** is curating that list.
If it gets removed there,it will be no longer present here as well.

**Comment by dnmTX** [comment]
Steve @StevenBlack the repo doesn't exist anymore and considering who was the curator,i'd say just remove it from here 👍

**Comment by StevenBlack** [comment]
Dan the repo you mention:  8 commits.  

```
$ ghosts -m p -c https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Adult
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts
Domains: 132,312
Bytes: 4.0 MB
----------------------------------------
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Adult
Domains: 86,358
Bytes: 1.4 MB
----------------------------------------
Intersection: 10,867 domains
```

**Comment by StevenBlack** [comment]
Dan @dnmTX putting clefspeare13 in my system clipboard, running head-to-head with the repo you mention:

```
$ ghosts -m https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Adult --clip
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Adult
Domains: 86,358
Bytes: 1.4 MB
----------------------------------------
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 30,816
Bytes: 926 kB
----------------------------------------
Intersection: 5,070 domains
```

**Comment by dnmTX** [comment]
> @dnmTX I wonder what happened.

I don't know,but concidering who was managing that repo(hint: it wasn't Clefspeare13) i honestly don't care.
I don't block porn on my end so it's all the same for me.You got the last call as allways 👍 

About **ShadowWhisperer** don't look at the commits as there is either something wrong with the commit history or is somehow set just to show the latest.
I've been keeping my eye on that whole repo there for a while now and can assure you there are at least 3 to 5 commits per day on majority of his lists there(he keeps on adding like crasy).
So...don't judge by that is my point 👍

**Comment by dnmTX** [comment]
Well...it was a suggestion of a list that i knew of as a "gap filler" i guess.
I usually don't search for such a lists so my knowledge there is very limited 😉
