### ISSUE TITLE
Experian and Clearscore blocked

### ISSUE THREAD

**Issue by mercyground** [StevenBlack/hosts#1777]
https://home.experian.co.uk/

https://app.clearscore.com/

Looks like the following need unblocking if u want to find out your credit score. ~~(Didn't do any serious checking. Just made new rule to exempt the following)~~

~~api.segment.io - AdGuard DNS filter
api2.branch.io~~
**auth.split.io
sdk.split.io**
~~streaming.split.io
events.split.io~~

Listed in the https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts file : 
_auth.split.io
cdn.split.io
events.split.io
sdk.split.io_

email.clearscore.com - This is needed if u try to click links via their emails.

:edit: had another play and looks like you only need the auth and sdk links. Also, my bad. Turns out some of the blocks are AdGuards blocks not yours. 😊

**Comment by dnmTX** [comment]
**ping** @jawz101 for assist 👍 

@mercyground  regarding `email.clearscore.com` you need to whitelist it on your end. Nothing can be done abou it here or upstream for that matter.
