### ISSUE TITLE
hosts rules from rlwpx.free.fr 

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#178]
@StevenBlack 
What do you think about review and merge some hosts rules from http://rlwpx.free.fr/WPFF/hosts.htm ?

Original language is FRA, Google translate in to ENG screen:
![image 002](https://cloud.githubusercontent.com/assets/9846948/18613736/d5afabd4-7d80-11e6-8463-fbbca097482c.png)

Regards

**Comment by StevenBlack** [comment]
I'm fluent in French; I love the explanations in their docs.

Those are quite large host files.  `hosts.sex` blocks [collegehumor.com](http://www.collegehumor.com/video/6478387/the-six-girls-youll-date-in-college) which feels like overkill.

Like Issue #177 this one would require pre-processing after download and before amalgamation.
