### ISSUE TITLE
Remove clickhouse.com from blacklist

### ISSUE THREAD

**Issue by anergictcell** [StevenBlack/hosts#1781]
Hi,
I was wondering if `clickhouse.com` should be removed from the blacklist. This is a public website for a database technology:
- https://clickhouse.com/
- https://github.com/ClickHouse/ClickHouse

The URL was added to the blacklist in 2014 (https://github.com/StevenBlack/hosts/commit/11af008f43b02959e9d9dae8890f8d7b1338db66), but the ClickHouse Database was only founded in 2016 (https://en.wikipedia.org/wiki/ClickHouse). Maybe it was a tracker beforehand and has never been updated?

Blacklist record:

https://github.com/StevenBlack/hosts/blob/33823d682c995ecaa1ea5c4557522587b74107ee/data/mvps.org/hosts#L269

**Comment by alexey-milovidov** [comment]
+1

We have bought this domain from previous owner.
The history of this domain is no longer relevant.

ClickHouse is an open-source database technology.
And we don't run ads :)

**Comment by dnmTX** [comment]
Sweet....got downvoted by all GRU officers on duty in GitHub.
Glad to  be of help **братушки** 😄

**Comment by StevenBlack** [comment]
@anergictcell as you are aware, the domain `www.clickhouse.com` comes to us from mvps.org, which is a very reputable list curator.  This is upstream from us.  Please make your case by sending an email to winhelp2002@gmail.com.

**Comment by indy-singh** [comment]
FYI this should be removed from the list. Clickhouse is just another database technology like BigQuery, Cassandra, Postgres.

If you are going to keep Clickhouse on the list, then by the same logic you should add _all_ database technologies to the list.

**Comment by rjhancock** [comment]
As was stated on Oct 10, 2021, take it upstream as they are the ones that have it in their list. If they remove it, this list will update accordingly.

**Comment by StevenBlack** [comment]
I've removed `www.clickhouse.com` from our copy of the mvps list.  The root domain, `clickhouse.com` was not blocked.

Closing.
