### ISSUE TITLE
Whitelist st.bahn.de

### ISSUE THREAD

**Issue by Zocker1999NET** [StevenBlack/hosts#1782]
When using the Android app "DB Navigator" from "Deutsche Bahn" (a German railway company), the app requires to access the domain `st.bahn.de` to allow the user to buy tickets in the app. Otherwise, the app shows the message "There is no valid certificate on the device to establish a secure connection. Please check your system settings or update your operating system.". After unblocking `st.bahn.de`, the app proceeds so the user can buy a ticket.

I discovered & tested this with Lineage OS 18.1 (Android 11) and the app AdAway.

**Comment by StevenBlack** [comment]
Thank you for this Felix @Zocker1999NET.

This comes to us via the AdguardTeam cname trackers list.  Please see their [readme](https://github.com/AdguardTeam/cname-trackers) that explains why this domain is listed.
