### ISSUE TITLE
OneDrive sync client needs g.live.com, which is blocked

### ISSUE THREAD

**Issue by daspek** [StevenBlack/hosts#1783]
Hello,
I'm from the OneDrive team at Microsoft. We've heard reports (and one of our colleagues noticed) that Pi-hole is blocking the OneDrive sync client from working, and it seems to be because of the `g.msn.com` block in the hosts list here. OneDrive actually uses `g.live.com`, which is a CNAME of `g.msn.com` -- it doesn't appear that `g.live.com` itself is blocked, but it appears to be impacted due to being a CNAME of the msn variant. OneDrive uses this endpoint to read configuration data which is necessary for its operation (documented [here](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide), and also called out in #1748, which tracks other Microsoft apps being broken).

It looks like this issue has been raised in the past (eg. #1450) but didn't get resolved. The previous recommendation was to reach out to Dan Pollock. Not sure if that happened. I'm happy to do that if that's still the right next step. Please let me know how we can help get this resolved for our customers.

Thanks,
daron

**Comment by dnmTX** [comment]
> The previous recommendation was to reach out to Dan Pollock. Not sure if that happened. I'm happy to do that if that's still the right next step.

☝️ 👍

**Comment by daspek** [comment]
Thanks, @StevenBlack! I heard back from Dan and he said he removed the listing. What are the next steps to get things refreshed?
