### ISSUE TITLE
I built the script with Py2exe.

### ISSUE THREAD

**Issue by crborga** [StevenBlack/hosts#179]
I was able to change a few lines and build the script in py2exe if anyone is interested. Being able to replace the hosts within the script would make it complete. Here my modified script.
[HostsFileGenerator.zip](https://github.com/StevenBlack/hosts/files/478783/HostsFileGenerator.zip)

I modified updateHostsWindows.bat as well to run UpdateHostsFile.exe first so it can be run all together.
Also, the telemetry urls are included in myhosts. Just empty that file if you do not want that.

**Comment by StevenBlack** [comment]
Hi @crborga, thank you!

Can you please put this in your own repo, ideally as a new branch of this repo, and submit a [pull request](https://help.github.com/articles/about-pull-requests/)?

Try it! 😄  You'll find this is a much better, more functional way of presenting suggestions and enhancements.
