### ISSUE TITLE
Remove sun-***.userapi.com from porn list

### ISSUE THREAD

**Issue by shinkei078** [StevenBlack/hosts#1798]
Dear @StevenBlack! Thank you for your quick reaction in #1793 

Please unblock the following nodes if possible:

sun9-1.userapi.com
sun9-3.userapi.com
sun9-8.userapi.com
sun9-9.userapi.com
sun6-21.userapi.com
sun6-22.userapi.com
sun6-23.userapi.com
sun9-11.userapi.com
sun9-23.userapi.com
sun9-28.userapi.com
sun9-29.userapi.com
sun9-30.userapi.com
sun9-31.userapi.com
sun9-32.userapi.com
sun9-38.userapi.com
sun9-39.userapi.com
sun9-46.userapi.com
sun9-51.userapi.com
sun9-53.userapi.com
sun9-56.userapi.com
sun9-57.userapi.com
sun9-58.userapi.com
sun9-59.userapi.com
sun9-60.userapi.com
sun9-65.userapi.com
sun9-73.userapi.com
sun9-76.userapi.com
sun9-78.userapi.com
sun9-87.userapi.com

They contain most of the images of users and their photos. For debugging, you can use the profile of Pavel Durov (founder vk.com), https://vk.com/id1 and scroll in bottom.

**Comment by porn-records** [comment]
Well @shinkei078 if you try to visit https://18.ukdevilz.com/video/redhead you will find lots of `.userapi.com` porn

And the right place for debating this records is at the list maintainers repository which is found here https://mypdns.org/my-privacy-dns/porn-records/-/issues/337

<details><summary>ukdevilz.com</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +12 |  |  | 18.ukdevilz.com | 3 | image | `https://sun9-4.userapi.com/impf/Xb1FUSufZ1l6RdeIvr7hGQ7UdtYt6rU8RCrhuA/HALhlcGS-zo.jpg?size=320x240&quality=96&keep_aspect_ratio=1&background=000000&sign=0ca3bdacffc6c9d1b6f2b899cf55f0ef&c_uniq_tag=MszAMWzpSR0-avIM0UEUVs0LP5h6UjL0b5Q9LkV2VYU&type=video_thumb` |
| +12 |  |  | 18.ukdevilz.com | 3 | image | `https://sun9-66.userapi.com/impf/fcGmOppnkWTaTWLycSGyMxIQ8Ds6YRigH_x3Jg/oTtrtgxrhm8.jpg?size=320x180&quality=96&sign=26506641d94545330810f740ab29b438&c_uniq_tag=-EaGAAfvE3vo0Cs4lQnB_VyUVYxR7KDrj6R44um1xM8&type=video_thumb` |
| +12 |  |  | 18.ukdevilz.com | 3 | image | `https://sun9-37.userapi.com/impf/McSxUSAdsuSxJoJnIwBvcIL_0BXjt_uFyWCGUw/3XRgR65JK5c.jpg?size=320x240&quality=96&keep_aspect_ratio=1&background=000000&sign=1823ef396700c7578a253aaf6ac2f38d&c_uniq_tag=aDiUnQtsKlmWt_dDx5KBsujEOBw5SJyfNJL5PUj5HfU&type=video_thumb` |
| +12 |  |  | 18.ukdevilz.com | 3 | image | `https://sun9-77.userapi.com/impf/c855336/v855336158/24246b/-fx4kZ3sbg8.jpg?size=320x180&quality=96&sign=5d54e0abe89f54fb4c32f4ce0d09c909&c_uniq_tag=PWwCU0fOtw7ZDTq1JwiTH4fR_Emk76vAej0JIP2L0VQ&type=video_thumb` |
| +12 |  |  | 18.ukdevilz.com | 3 | image | `https://sun9-4.userapi.com/impf/c851332/v851332958/9cbdc/FLHKuZJ3Ams.jpg?size=320x240&quality=96&keep_aspect_ratio=1&background=000000&sign=a296e9c480901b5310188793fd4755b3&c_uniq_tag=SVkEANx6IgBwqiI4zlioH3ItYtMNbU_kr0lx29wllL4&type=video_thumb` |
| +12 |  |  | 18.ukdevilz.com | 3 | image | `https://sun9-36.userapi.com/impf/c858224/v858224186/97b1e/9lZRO1qO9EE.jpg?size=320x180&quality=96&sign=982f243624a33d0d7fc4111ec63c7664&c_uniq_tag=j5f3FjgHQr2VjcpuElqg9nasjXSTJfNGRn2-xDL-OYo&type=video_thumb` |
| +11 |  |  | 18.ukdevilz.com | 3 | image | `https://sun9-32.userapi.com/impf/c840635/v840635624/8723b/CnZk9XH_PzA.jpg?size=320x240&quality=96&keep_aspect_ratio=1&background=000000&sign=328acd327a990f2842233d16e4bb8880&c_uniq_tag=ucE06tXnh1GFSziHF-nbHC9my-GtS4yAz56CJfEsenM&type=video_thumb` |
</details>

On noodlemagazine.com there are plenty as well

<details><summary>noodlemagazine.com</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +7 |  |  | adult.noodlemagazine.com | 3 | image | `https://sun9-22.userapi.com/impf/c841032/v841032505/29dbd/HZzBNvCufHk.jpg?size=320x240&quality=96&keep_aspect_ratio=1&background=000000&sign=0dee432229f121cf1e592ff51038d3a8&c_uniq_tag=R_cP8s3kRI1fDgm_ISed8xQnchctPgft0UT5neo05RM&type=video_thumb` |
| +7 |  |  | adult.noodlemagazine.com | 3 | image | `https://sun9-59.userapi.com/impf/4RCN32vBWl7siXN6jMGWMdss04xUrwMZKYJUnw/Xcix1U5wq68.jpg?size=320x180&quality=96&sign=f9c6c4e89d43cba38c21c384640bca97&c_uniq_tag=QeeV1DtfRaVIfqhPfqKrogkTt5o4hDq6EQ4yTyv90xc&type=video_thumb` |
| +7 |  |  | adult.noodlemagazine.com | 3 | image | `https://sun9-42.userapi.com/impf/c853624/v853624395/220faf/I1To2GnqoIo.jpg?size=320x240&quality=96&keep_aspect_ratio=1&background=000000&sign=201d69081a695ba976e103ae75c81334&c_uniq_tag=fvKNQg1UFV7ni5HXCDLj1LU_6mmr8U-tPiPeRnWGPYM&type=video_thumb` |
| +7 |  |  | adult.noodlemagazine.com | 3 | image | `https://sun9-13.userapi.com/impf/c857636/v857636912/131521/q-zAZ-51kzc.jpg?size=320x240&quality=96&keep_aspect_ratio=1&background=000000&sign=075598b1c2f253ef9a04fd39f7e0834e&c_uniq_tag=rMAfrg7Z6st6jFTCqj1e3pLWTLRB5F3fy8Yst9oPDes&type=video_thumb` |
| +7 |  |  | adult.noodlemagazine.com | 3 | image | `https://sun9-67.userapi.com/c639616/v639616708/4016c/c44__cGbSVg.jpg` |
</details>

While `artsporn.com` seems to have stopped using `.userapi.com` we can move it to the strict lists...
