### ISSUE TITLE
Microsoft telemetry and collecting data

### ISSUE THREAD

**Issue by ChazyTheBest** [StevenBlack/hosts#18]
Hi, I just saw some Microsoft related sites in the list, but there are more sites missing.

Here is a list of most related Microsoft sites that collects data: http://developer.team/software/16258-destroy-windows-10-spying-142.html
And some extra IPs here: http://foro.elhacker.net/scripting/vbs_script_para_personalizar_windows_10-t439704.0.html (inside the vbs script).

I could make a PR. Check them and tell me something.

**Comment by espress0** [comment]
Blocking MS FQDNs in Windows HOSTS is fine. But you'll need WSUS to update windows.

And
                    F.WriteLine "0.0.0.0 65.55.108.23 "
                    F.WriteLine "0.0.0.0 65.39.117.230"
                    F.WriteLine "0.0.0.0 23.218.212.69 "
                    F.WriteLine "0.0.0.0 134.170.30.202"
                    F.WriteLine "0.0.0.0 137.116.81.24"

These lines block nothing because proper HOSTS format is {IP} {FQDN}, not {IP} {IP}.

> but there are more sites missing

Sure. I'll block:
127.0.0.1 *azure* *cortana* *windows* *microsoft* *msft*

Overkill XD

**Comment by ChazyTheBest** [comment]
Blocking those domains does not prevent me from getting updates, I just got a Windows Defender definition update. So blocking those should be fine.

So you're sure those IP's won't be blocked? I'll tell the one who wrote the script lol

Hahaha I'm just telling this because I think no one wants being spied by "no one". (not just M$...) It's a shame if we want access good features/applications we must renounce to our privacy... (no matter the platform)

In the vbs script post (#16 answer) there's a link to an article (in czech i think) saying that Windows 10 does not read the hosts file... Ok, if that's true we are fkd up...

**Comment by lencc** [comment]
@ChazyTheBest I think the links from the vbs script (from your 2nd link) are also provided here:
http://paste2.org/A1sv86VF
I found the link on the [reddit discussion](https://www.reddit.com/r/Windows10/comments/3f38ed/guide_how_to_disable_data_logging_in_w10) on how to disable data logging.

Besides, I hope hosts file still works okay in Windows 10. There is a discussion (http://www.overclock.net/t/1569236/localghost-a-traffic-analysis-of-windows-10) that Windows 10 ignores some rules from hosts file in order to keep user tracking..

**Comment by ChazyTheBest** [comment]
So that means we can forget about it, there's no way to prevent Microsoft from collecting our personal data anymore... ;(

**Comment by NetworkPro** [comment]
Microsoft list:
0.0.0.1 vortex.data.microsoft.com
0.0.0.1 vortex-win.data.microsoft.com
0.0.0.1 telecommand.telemetry.microsoft.com
0.0.0.1 telecommand.telemetry.microsoft.com.nsatc.net
0.0.0.1 oca.telemetry.microsoft.com
0.0.0.1 oca.telemetry.microsoft.com.nsatc.net
0.0.0.1 sqm.telemetry.microsoft.com
0.0.0.1 sqm.telemetry.microsoft.com.nsatc.net
0.0.0.1 watson.telemetry.microsoft.com
0.0.0.1 watson.telemetry.microsoft.com.nsatc.net
0.0.0.1 redir.metaservices.microsoft.com
0.0.0.1 choice.microsoft.com
0.0.0.1 choice.microsoft.com.nsatc.net
0.0.0.1 df.telemetry.microsoft.com
0.0.0.1 reports.wes.df.telemetry.microsoft.com
0.0.0.1 wes.df.telemetry.microsoft.com
0.0.0.1 services.wes.df.telemetry.microsoft.com
0.0.0.1 sqm.df.telemetry.microsoft.com
0.0.0.1 telemetry.microsoft.com
0.0.0.1 watson.ppe.telemetry.microsoft.com
0.0.0.1 telemetry.appex.bing.net
0.0.0.1 telemetry.urs.microsoft.com
0.0.0.1 settings-sandbox.data.microsoft.com
0.0.0.1 vortex-sandbox.data.microsoft.com
0.0.0.1 survey.watson.microsoft.com
0.0.0.1 watson.live.com
0.0.0.1 watson.microsoft.com
0.0.0.1 statsfe2.ws.microsoft.com
0.0.0.1 corpext.msitadfs.glbdns2.microsoft.com
0.0.0.1 compatexchange.cloudapp.net
0.0.0.1 cs1.wpc.v0cdn.net
0.0.0.1 a-0001.a-msedge.net
0.0.0.1 statsfe2.update.microsoft.com.akadns.net
0.0.0.1 sls.update.microsoft.com.akadns.net
0.0.0.1 fe2.update.microsoft.com.akadns.net
0.0.0.1 diagnostics.support.microsoft.com
0.0.0.1 corp.sts.microsoft.com
0.0.0.1 statsfe1.ws.microsoft.com
0.0.0.1 pre.footprintpredict.com
0.0.0.1 i1.services.social.microsoft.com
0.0.0.1 i1.services.social.microsoft.com.nsatc.net
0.0.0.1 feedback.windows.com
0.0.0.1 feedback.microsoft-hohm.com
0.0.0.1 feedback.search.microsoft.com
0.0.0.1 apps.skype.com

0.0.0.1 rad.msn.com
0.0.0.1 preview.msn.com
0.0.0.1 ad.doubleclick.net
0.0.0.1 ads.msn.com
0.0.0.1 ads1.msads.net
0.0.0.1 ads1.msn.com
0.0.0.1 a.ads1.msn.com
0.0.0.1 a.ads2.msn.com
0.0.0.1 adnexus.net
0.0.0.1 adnxs.com
0.0.0.1 az361816.vo.msecnd.net
0.0.0.1 az512334.vo.msecnd.net
0.0.0.1 ssw.live.com
0.0.0.1 spynet2.microsoft.com
0.0.0.1 spynetalt.microsoft.com

**Comment by lencc** [comment]
The complete "Microsoft list" has already been suggested [here](https://github.com/StevenBlack/hosts/issues/17). However, it seems the last two rules are new:
0.0.0.1 spynet2.microsoft.com
0.0.0.1 spynetalt.microsoft.com

**Comment by matkoniecz** [comment]
Is it even on topic? This repository is defined as

> This repository consolidates several reputable hosts files, and merges them into a single unified hosts file with duplicates removed.

So creation of new lists seems to be offtopic here.

**Comment by StevenBlack** [comment]
@matkoniecz is right. 

What this repo needs is links to hosts files that are actively maintained.  

I'm going to close this now because it's an old issue...
