### ISSUE TITLE
Unblock www.amazonbusiness.com

### ISSUE THREAD

**Issue by haas94** [StevenBlack/hosts#1805]
Please unblock www.amazonbusiness.com it is legit business website. Thank you
Exact match for www.amazonbusiness.com found in:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by dnmTX** [comment]
Steve @StevenBlack the request was [denied](https://github.com/AdguardTeam/cname-trackers/issues/21) upstream.

**Comment by StevenBlack** [comment]
Thank you @haas94 and thanks Dan @dnmTX for the assist.

@haas94 this won't change.

Closing.
