### ISSUE TITLE
cs.prd.msys.playstation.net

### ISSUE THREAD

**Issue by JailSeed** [StevenBlack/hosts#1806]
Hello! Why is cs.prd.msys.playstation.net blacklisted? It used by Sony Headphones mobile app to get news about new firmware and so on.

**Comment by dnmTX** [comment]
@JailSeed it's upstream from **someonewhocares.org**.
You need to contact Dan Pollock: hosts@someonewhocares.org for the removal request.

**Comment by JailSeed** [comment]
@dnmTX @StevenBlack Dan removed it, thanks.

**Comment by StevenBlack** [comment]
Thank you everybody!  @JailSeed this will be reflected in the next release, possibly later today.

Closing.
