### ISSUE TITLE
Remove cloud.jumpcloud.com from block lists

### ISSUE THREAD

**Issue by tbridgejc** [StevenBlack/hosts#1808]
Hello maintainers,

We saw that cloud.jumpcloud.com was added to the hosts file here, and we'd like to understand why it happened. We're fairly certain there is no adware or malware associated with the domain. Could you please advise?

We're happy to work on what needs to be done.

Best,
Tom

**Comment by dnmTX** [comment]
Steve @StevenBlack you mind explain to the nice Gentleman here why can't be removed from here and neither upstream(Adguard's cname-trackers). Thanks 👍

**Comment by tbridgejc** [comment]
@dnmTX One of our customers brought it to us, because they noticed that it was causing end user invitations from our platform to not be delivered to their end users.

**Comment by bctrainers** [comment]
The domain seems to have been integrated to @StevenBlack's lists via AdGuard's CNAME filter. You may need to open an issue with them in regards to that domain name being added.

Your `cloud.jumpcloud.com` has a CNAME to `go.pardot.com`, which is what appears to have triggered its addition. 

```bash
root@box004:~# dig cloud.jumpcloud.com A @4.2.2.5

; <<>> DiG 9.11.5-P4-5.1+deb10u6-Debian <<>> cloud.jumpcloud.com A @4.2.2.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52661
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 8192
;; QUESTION SECTION:
;cloud.jumpcloud.com.           IN      A

;; ANSWER SECTION:
cloud.jumpcloud.com.    300     IN      CNAME   go.pardot.com.
go.pardot.com.          2998    IN      CNAME   pi.pardot.com.
pi.pardot.com.          169     IN      CNAME   pi-ue1.pardot.com.
pi-ue1.pardot.com.      364     IN      CNAME   pi.t.pardot.com.
pi.t.pardot.com.        30      IN      CNAME   pi-ue1-lba6.pardot.com.
pi-ue1-lba6.pardot.com. 578     IN      A       18.232.28.189

;; Query time: 38 msec
;; SERVER: 4.2.2.5#53(4.2.2.5)
;; WHEN: Sat Nov 06 15:11:05 CDT 2021
;; MSG SIZE  rcvd: 171
```

https://github.com/AdguardTeam/cname-trackers/search?q=cloud.jumpcloud.com

**Comment by StevenBlack** [comment]
Hi Tom @tbridgejc thank you for this question.

We include the Adguard CNAME list because it's a list of cloaked trackers. Here DNS CNAME records are used to hide the true provider of the response to requests.

I hope this clarifies it!

Closing.
