### ISSUE TITLE
Website Broken - trk.klclick.com

### ISSUE THREAD

**Issue by gyCfjSnO** [StevenBlack/hosts#1810]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):
```trk.klclick.com```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.14

### Detail:

- Your Issue Detail: Unable to unsubscribe from marketing emails I am receiving to my email address. Picture attached of my AdGuard Home blocking ```trk.klclick.com``` as the domain ```trk.klclick.com``` is on a blocklist I am using. I crosschecked other lists using ```https://blocklist-tools.developerdan.com/entries/search``` which brought me to your list which has the domain blocked.

![image](https://user-images.githubusercontent.com/49738152/140669540-5670e828-cb43-46c9-bf9a-396342d2bb83.png)

**Comment by dnmTX** [comment]
`@@||klclick.com^$important` 👍 👍 👍 👍 👍

**Comment by dnmTX** [comment]
Steve @StevenBlack this one is tracking domain through and through.
If OP wants to be tracked he can easaly whitelist it on his end(as pointed out at my previous post ☝️ ).
No need to expose everyone else here to that crap.
I guess he is the last person who doesn't know: **DO NOT CLICK OR UNSUBSCRIBE ON ANYTHING JUNK MAIL** ¯\_(ツ)_/¯

**Comment by gyCfjSnO** [comment]
I have blocked @dnmTX due to the hostility and rudeness they have shown towards me.

**Comment by StevenBlack** [comment]
Thank you for the detailed issue report @gyCfjSnO.

I'm sorry you feel vexed, Dan @dnmTX tends to become over-amped at times.

The domain `trk.klclick.com` is not blocked here, but `klclick.com` is blocked, via yoyo.org, one of our best curators. 

Hosts files work with specific domains. Wildcards are not a thing with hosts files. Possibly someone downstream is using our list in wildcard-supporting blocking mechanisms.  Nothing we can do about that.

I don't expect this particular listing to change.

At the heart of this, unscrupulous marketing firm is using dodgy services as part of its "unsubscribe" mechanisms. Shocking! 🙃 

A tip: if you install a Tor browser, Tor bypasses all local hosts files and conventional upstream DNS.  You could paste the "unsubscribe" URL into Tor and that will work.

Closing.
