### ISSUE TITLE
using KAD-hosts stops Windows login

### ISSUE THREAD

**Issue by amwink** [StevenBlack/hosts#1811]
When I use the full list of sites in hosts, internet access is totally blocked.
I'm logging in from the Netherlands, my provider is called Ziggo.

Trying to find which site causes this, but at the moment I have a problem restoring the old 'hosts' file. Access denied.
I was adding parts of the list to stop this happening, but after adding the KAD-hosts list, I cannot get any further.

What is the best thing to do now,and are there any diagnostics that would be useful for your?
Has any of the KAD-hosts been used by providers before?

**Comment by dnmTX** [comment]
@amwink it looks like you experiencing widely known issue in Windows and large(custom) hosts file.
It's not the KAD-hosts perse but Window's built in DNS cache service.
Start by disabling that service(look for **DNS Client** service in services),restart your PC and see if it's better.
It won't hurt to report the results here 👍

**Comment by amwink** [comment]
Ah, widely known and I was completely ignorant of it. That does do the trick, thank you very much!

My host file is now ~ 5MB, combining the largest set from this site 
and another set called "how to make the internet not suck (as much)"
