### ISSUE TITLE
Major issues with attempting to dump list into Akamai - keeps seeing erroneous data

### ISSUE THREAD

**Issue by StewAlexander-com** [StevenBlack/hosts#1813]
Apparently Akamai's blacklist only accepts formatting in the xxx.xxx.xxx format, I used lots of regex to no avail to attempt to clean up the list to import but no luck

Anyone else have any ideas on how to turn this list into something digestible as domain block list?

Thank in advance

**Comment by StevenBlack** [comment]
Hi Stew @StewAlexander-com, what do you mean when you say, `xxx.xxx.xxx` format.  Also, what OS are you running? I'm guessing Windows, which is quite limited in what its able to do for you, out of the box.

**Comment by StewAlexander-com** [comment]
Hi Steven,

So It's Akamai's Threat Intelligence solution - a cloud solution probably hosted in their own cloud environment as Akamai is a huge organization that mirrors websites like Apple for them, so when you go to Apple you have a quicker path to the website etc.

There's a bulk import to this cloud solution, 

![image](https://user-images.githubusercontent.com/48565067/140960349-0c9c8ddf-0d4d-4180-a400-d965bd17c364.png)
----
![image](https://user-images.githubusercontent.com/48565067/140960436-dfbc6c92-4b16-4146-9c56-2dec507ba680.png)
-----
![image](https://user-images.githubusercontent.com/48565067/140960516-95212477-32b6-4c29-a32a-584e92b7bed6.png)

**Comment by StevenBlack** [comment]
@StewAlexander-com the hosts list is a text file.

Maybe just open the list in a text editor, remove the leading `0.0.0.0 ` and all lines that start with `#` and use that?

This might be a 2 or 3 step thing in [VS Code](https://code.visualstudio.com/) or any good code editor.  Good luck!

Closing.
