### ISSUE TITLE
[Blacklist] "ghosthis.review' as a redirect to a different website

### ISSUE THREAD

**Issue by SaberAkiyama** [StevenBlack/hosts#1814]
List to Blacklist:
```
ghosthis.review
```

**Comment by StevenBlack** [comment]
Hi Abdul @SaberAkiyama thank you for this.

Can you provide more information? What are you asking?

**Comment by SaberAkiyama** [comment]
> Hi Abdul @SaberAkiyama thank you for this.
> 
> Can you provide more information? What are you asking?

When I'd click from current website, I've seen a different address and suddenly it directly to a different website.

**Comment by StevenBlack** [comment]
Sorry Abdul, I don't understand.  Maybe I'm missing something?

When I navigate to https://ghosthis.review/ I get a 404 page and I'm not in a different place.

Please help me understand.

**Comment by SaberAkiyama** [comment]
I see. I guess I closed this issue.
