### ISSUE TITLE
Add LINE messenger in-app ad servers

### ISSUE THREAD

**Issue by nicolasmaia** [StevenBlack/hosts#1815]
a.line.me
ad-center.line.me
lap-click.tr.line.me
lt-click.tr.line.me
obs.line-scdn.net
optout-api.tr.line.me
sch.line.me
tr.line.me

**Comment by StevenBlack** [comment]
Hi Nicolas @nicolasmaia.

And we would block these domains because...?

I need to see a clear case for this.

**Comment by nicolasmaia** [comment]
They serve in-app ads.

**Comment by StevenBlack** [comment]
I'm sorry Nicolas @nicolasmaia that's not enough justification to move me to deplatform a bunch of domains.  

Closing.

**Comment by nicolasmaia** [comment]
Wait, do I need to prove it? How would one do that?
