### ISSUE TITLE
blocklists-tag

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1816]
The list includes malicious domains inserted in the Google Threat Group blog (1:1)

Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-tag.txt

**Comment by StevenBlack** [comment]
Thank you for this Lorenzo @scafroglia93.

Assessing using [ghosts](https://github.com/StevenBlack/ghosts) this would add 65 new domains.

```
$ ghosts -c https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-tag.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 94,351
Bytes: 2.9 MB
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-tag.txt
Domains: 86
Bytes: 2.2 kB
Intersection: 21 domains
```

Looking at the list TLDs, that looks good too.

```
$ ghosts --tld -m https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-tag.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-tag.txt
Domains: 86
Bytes: 2.2 kB
TLD tally:  (20 unique TLD)
   com: 31
   org: 13
   site: 10
   io: 4
   xyz: 4
   space: 3
   tech: 3
   online: 3
   net: 3
   me: 2
   app: 1
   it: 1
   info: 1
   gd: 1
   sg: 1
   club: 1
   de: 1
   live: 1
   fun: 1
   host: 1
----------------------------------------
```

**Comment by scafroglia93** [comment]
https://github.com/scafroglia93/blocklists

Here are the other lists I manage; I'm splitting everything to improve management.

If you find some lists of your interest (they are all sorted and referenced) you can insert them without problems

**Comment by StevenBlack** [comment]
Lorenzo @scafroglia93 I think I'd like to include your Amnesty list, `blocklists-amnenstytech`. Can you add a license to your repo to facilitate this?

Would you craft a PR for that one, pointing to the `raw` file? That's to give you contributor credit for the commit. That's a small thing, but I think it matters.

Can you brief me on some of the others? What's notable? What's choice among the others?  You need a readme 😄.

**Comment by scafroglia93** [comment]
Done, all repo was licensed
