### ISSUE TITLE
Possible False Positive - Fabrics-Store

### ISSUE THREAD

**Issue by baeckel** [StevenBlack/hosts#1817]
I noticed this domain on an allow-list I was cleaning up & it showed up in the 3.9.20 list when I cross-referenced.

It shows up as the following in add.Risk:
fabrics-store.com
www.fabrics-store.com

It appears to be legit & VirusTotal indicates that it's clean.

**Comment by dnmTX** [comment]
**ping** @FadeMind for assist 👍

**Comment by FadeMind** [comment]
@dnmTX done

**Comment by StevenBlack** [comment]
Hey thanks everybody!

@baeckel this will reflect in the next release, possibly later today.

Closing.
