### ISSUE TITLE
Add hiperdex.com

### ISSUE THREAD

**Issue by ayushhdwi** [StevenBlack/hosts#1818]
It is a manhwa site with some of the popular ones but also contains content unsafe for minors

**Comment by StevenBlack** [comment]
Thank you for this Ayush @ayushhdwi.

@tiuxo would you consider adding this one? I'm not in a position to do so for the next few days.

**Comment by StevenBlack** [comment]
Thanks Ayush @ayushhdwi after visiting this site I've decided to add it to our main list because of its heinous use of popups.  This is done in commit 7bcea82.

Closing.

**Comment by leumasme** [comment]
I think this should be revisited. I see nothing unusual on the site aside from the usual low quality banner ads (common for piracy-adjacent sites); just got warned about this via URLcheck which marked the host as malware/adware based on your host list.

**Comment by zoltarTheGreat** [comment]
Sorry to necro this old post but i disagree with the addition to the main list. 
I think it should be moved to the adult material list really. If the original issue was meant to protect minors from adult content.
