### ISSUE TITLE
I need to block only ads , but allow trackers

### ISSUE THREAD

**Issue by keerthirajap** [StevenBlack/hosts#1819]
Hi Team,

Is there any host list available to block only ads but allow tracker.

**Comment by StevenBlack** [comment]
Hi Keerthi @keerthirajap I've been thinking about offering a finer-grained mix of hosts files.  Just porn, or just social media for example.  Nobody has ever asked to allow trackers before 😄 so I suppose that's another angle to consider.

Looking at our list of curators, I don't think any of them are ads-only. Does anyone have more insight into this?

**Comment by gothic-bum** [comment]
You can remove all tracking servers from Peter Lowe's list by using a query string parameter:
https://pgl.yoyo.org/adservers/news.php?#trackers-filtering
  
Example:
https://pgl.yoyo.org/as/serverlist.php?notrackers=1

**Comment by StevenBlack** [comment]
Does @gothic-bum's suggestion work for you,  Keerthi @keerthirajap?

**Comment by keerthirajap** [comment]
@StevenBlack, I stuck up with some work and will try your suggestion after sometime. You can close the issue.

But I will be happy if you are able to separate publish.
