### ISSUE TITLE
China list hosts

### ISSUE THREAD

**Issue by ookangzheng** [StevenBlack/hosts#182]
Can anyone provide some china list hosts.. thanks

**Comment by Atavic** [comment]
You need a list of Internet service providers as China Telecom? If so, check:
https://github.com/17mon/china_ip_list/blob/master/china_ip_list.txt

**Comment by ookangzheng** [comment]
I need some easylist china ads filter to hosts files 
like this  https://github.com/ookangzheng/cjxlist

**Comment by Atavic** [comment]
https://github.com/search?utf8=%E2%9C%93&q=adblock+china
