### ISSUE TITLE
Unified hosts = (adware + malware) = false Positive Qhost with eset.

### ISSUE THREAD

**Issue by philibeur** [StevenBlack/hosts#1822]
Unified hosts = (adware + malware) = false Positive Qhost with eset. (updated today)

**Comment by StevenBlack** [comment]
@philibeur I don't understand what you are trying to say.

We don't list any `qhost` domains.

Closing.

**Comment by philibeur** [comment]
Il's more clear with a screen shot?

**Comment by StevenBlack** [comment]
@philibeur ceci n'est pas notre bug. Il n'y a pas de cheval troie dans nos fichiers, c'est juste du texte.
