### ISSUE TITLE
c.bing.com is preventing Skype Linux Alpha from logging in

### ISSUE THREAD

**Issue by wrsg** [StevenBlack/hosts#183]
For some reason, the Linux alpha client of Skype depends on c.bing.com, when this host is commented out, SKype works fine. I don't know what can be done about this, since I guess c.bing.com is a genuinely bad host but its messing up Skype Linux so that's also not good.

**Comment by Atavic** [comment]
Check https://prism-break.org/ for alternatives.

**Comment by StevenBlack** [comment]
`c.bing.com` is a domain listed by mvps.org who are people who, ostensibly, are affiliated with the MS MVP program.

That's just weird.

**Comment by giulio92** [comment]
I agree with @wrsg I have the same problem with Skype for macOS, the application still connects during login but I appear offline. Can you please re-enable the Skype's needed domains? A lot of people use Skype for personal/job reasons

**Comment by StevenBlack** [comment]
I've sent the following to the administrators of the MVPs hosts file.  Let's see what they say.


> From: Steven Black <steveb@stevenblack.com>
> To: winhelp2002@gmail.com
> Subject: MVPs hosts file
> Date: Wed, 12 Oct 2016 15:47:48 -0400
>
> Hi!
>
> The current edition of the MVPs hosts file contains these two references 
> to bing.
>
> 0.0.0.0 bat.bing.com
> 0.0.0.0 c.bing.com
>
> I am being told that this interferes with logging-in to skype on Linux.
>
> See this bug report:
>   https://github.com/StevenBlack/hosts/issues/183
>
> Thanks for looking into this, and thanks for all you do!
>
> Steven Black

**Comment by Atavic** [comment]
@wrsg @giulio92 Do you use Skype Translator?

> When you use Skype’s translation features, Skype collects and uses your conversation to help improve Microsoft products and services.

**Comment by StevenBlack** [comment]
I received a reply, the next version of the mvps hosts file will not include `c.bing.com`.

**Comment by giulio92** [comment]
@Atavic No I do not use it. Anyway even the Web version of the Skype client ([web.skype.com](url)) doesn't work if you forbid `bat.bing.com` and `bat.bing.com`

**Comment by StevenBlack** [comment]
@giulio92 can you confirm again that `bat.bing.com` is vital for Skype on Linux?  Clearing `c.bing.bat` isn't enough?

The response I got was clearing just `c.bing.com` in their next release.

**Comment by giulio92** [comment]
@StevenBlack I tried removing only `c.bing.com` from the host file but both Skype versions didn't work, obviously I have tried by flushing the DNS cache and rebooting my Mac but Skype still wasn't able to connect. I suppose `bat.bing.com` is also needed. Just give me time to test this

**Comment by giulio92** [comment]
Ok everyone, I have made the test using Charles with my MacBook Pro. I downloaded the: Unified hosts = (adware + malware), and I flushed DNS Cache using:

`sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder`

Then I have found that:

```
c.bing.com
bat.bing.com
```

are safe to be blocked because they are not required by Skype macOS client application, instead:

`s.gateway.messenger.live.com` 

is the one to blame, if I comment this one from the host file and I flush my DNS cache Skype will be working fine

**Comment by StevenBlack** [comment]
@FadeMind Tomasz can you remove `s.gateway.messenger.live.com` from Telemetry?

**Comment by FadeMind** [comment]
@StevenBlack https://github.com/FadeMind/hosts.extras/commit/56b1003fb9f18d03e48ef898300dfcee63dd4d54

**Comment by wrsg** [comment]
@Atavic I don't use the translator.
