### ISSUE TITLE
keystoken / bid.glass

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#1831]
Some new ads on 4chan are pointing to keystoken.io with images served by bid.glass

for example https://bid.glass/creatives/2/m/c/c/2mccsd8rf2mViC.gif

I don't know which domain should be blocked, if not both, so just wanted to submit an issue for consideration.

**Comment by hyder365** [comment]
OK, turns out bid.glass is entirely an advertisement serving platform, so I think it's the one we want.

**Comment by dnmTX** [comment]
> so I think it's the one we want

It's already listed in **shady-hosts**:
![hosts](https://user-images.githubusercontent.com/34774426/145726088-4425c0bf-a6bf-4d73-a236-79562ae4fe06.png)

**Comment by hyder365** [comment]
Yep, my cache was too old. Things move quick! Thanks.
