### ISSUE TITLE
Update for  adware malware hosts file

### ISSUE THREAD

**Issue by smed79** [StevenBlack/hosts#1832]
Hi, 
below a list of malicious domains (scam, spam, fake download...)

<details><summary>CLICK to show list</summary>
<p>

```
cloudshare.nocoshop.ru
easyfiles.nocoshop.ru
filedrive.nocoshop.ru
filekeeper.nocoshop.ru
filestation.nocoshop.ru
gouploads.nocoshop.ru
linkbox.nocoshop.ru
liquidfile.nocoshop.ru
mirroruploads.nocoshop.ru
openshare.nocoshop.ru
quicklinks.nocoshop.ru
secretfiles.nocoshop.ru
sendbox.nocoshop.ru
smartfiles.nocoshop.ru
tinyfiles.nocoshop.ru
turbobit.nocoshop.ru
uberupload.nocoshop.ru
upandshare.nocoshop.ru
weupload.nocoshop.ru
zippyfiles.nocoshop.ru

easyfiles.topupload.ru
filekeeper.topupload.ru
linkbox.topupload.ru
liquidfile.topupload.ru
mirroruploads.topupload.ru
openshare.topupload.ru
sendbox.topupload.ru
turbobit.topupload.ru
uberupload.topupload.ru
weupload.topupload.ru
zippyfiles.topupload.ru

cloudshare.uploadbox.world
filedrive.uploadbox.world
filestation.uploadbox.world
gouploads.uploadbox.world
quicklinks.uploadbox.world
secretfiles.uploadbox.world
smartfiles.uploadbox.world
tinyfiles.uploadbox.world
uberupload.uploadbox.world
upandshare.uploadbox.world

arabianpdfbooks.info
james-joyce.site
kutib-lilajhiza.info
nathanielhawthorne.site
samuel-beckett.site
tahmil-kutib-pdf.info
uberupload.online
```

</p>
</details>

Regards,

**Comment by dnmTX** [comment]
@smed79 what happened? You completely abandoned your list that....i'm still using for pete sake 🤔 
Why can't you make a own list,maintain it on the regular and Steve @StevenBlack will be happy to include it here and i'm more then happy also to vouch for you as we've done work in the past over Ultimate.Hosts.....
Just....don't disappear again please 😉

**Comment by StevenBlack** [comment]
Yep, thanks @smed79 that's a good addition.  Done!  See commit e1fd2666.

Thanks @smed79!

Closing!

**Comment by smed79** [comment]
@dnmTX It's not that I'm lazy to maintain my lists but I've been pretty busy lately. I'll do my best to be available more often.

:wink:
