### ISSUE TITLE
Add incoming-telemetry.thunderbird.net

### ISSUE THREAD

**Issue by thomasmerz** [StevenBlack/hosts#1834]
Because I found many queries in my AdBlocker (Pi-Hole) from my family members which doesn't care to disable telemetry in their Thunderbird instance, please add `incoming-telemetry.thunderbird.net` for **Thunderbird** which is still missing. `incoming.telemetry.mozilla.org` for **Firefox** is already included, so it should also include other telemetry domains from Mozilla.

I'll prepare a PR, so you just will have to review and merge. Kind regards!

**Comment by dnmTX** [comment]
@thomasmerz `incoming.telemetry.mozilla.org` comes from **yoyo.org** list and it's probably better if Peter @pgl take care of this to be maintained properly.

**Comment by dnmTX** [comment]
Steve @StevenBlack this can be closed now 👍
