### ISSUE TITLE
Please add us.conveyts.com to blocklist

### ISSUE THREAD

**Issue by cgwprs** [StevenBlack/hosts#1836]
This domain us.conveyts.com is being used by a malicious text to harvest personal data. They are pretending to be the United States Postal Service. Thank you

**Comment by dnmTX** [comment]
When you see something like this,means it's all shady as hell:
![conveyts com](https://user-images.githubusercontent.com/34774426/146687232-f71db4bf-685b-4f8c-ab45-e12a5fe54ff6.png)

**Comment by StevenBlack** [comment]
Thank you for this @cgwprs. This is added in commit f576662.

Closing.
