### ISSUE TITLE
images.dwell.com & assets.dwell.com blocked

### ISSUE THREAD

**Issue by anudeepND** [StevenBlack/hosts#1838]
This is a reference to https://github.com/anudeepND/whitelist/issues/217. dwell.com is a legit site, `images.dwell.com` is used to load images on the site `assets.dwell.com` is used to download custom fonts.

![chrome_EqVDwaItJx](https://user-images.githubusercontent.com/26179946/146790138-f336a360-9bca-4689-be23-34e89e85e322.jpg)

![chrome_Vssv1UHHb7](https://user-images.githubusercontent.com/26179946/146790148-09f57101-82c7-4558-ac26-f71ab3a4ae2e.jpg)

**Comment by dnmTX** [comment]
**ping** @jawz101 for assist. Thanks 👍

**Comment by jawz101** [comment]
removed.  thanks

**Comment by StevenBlack** [comment]
Awesome thanks @jawz101.

Anudeep @anudeepND this is going live in the next release, moments from now.
