### ISSUE TITLE
2 scam sites

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#1840]
pokemoney . biz
pokemoney . shop

These two related domains are scam sites that claim to sell Pokemon cards for substantially less than their market value. Visiting the .biz domain redirects me to ww25 . pokemoney . biz, so there may be some other subdomains worth blocking too.

**Comment by StevenBlack** [comment]
Thanks Devon @hyder365 these are added in commit 22373a2.

Closing!
