### ISSUE TITLE
IoC for the current log4shell attack campaign

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1843]
https://github.com/nextdns/metadata/pull/863

Source ->
https://cert-agid.gov.it/download/log4shell-iocs-raw-domain.txt

AGID ->
The Agenzia per l'Italia Digitale - Agency for Digital Italy (AgID) is the technical agency of the Presidency of the Council of Ministers.

**Comment by StevenBlack** [comment]
Closing.  See #1846 for reasons why.
