### ISSUE TITLE
[threat intelligence] unc1878 domains (CERT-GEORGIA)

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1844]
Source ->
http://blacklists.cert.gov.ge/

Source1 ->
https://www.trusted-introducer.org/directory/teams/cert-ge.html

Lists ->
http://blacklists.cert.gov.ge/unc1878_domains.txt

**Comment by StevenBlack** [comment]
Closing, same reasons as explained in #1846.
