### ISSUE TITLE
[threat intelligence] unc1878 domains (CERT-GEORGIA)

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#1846]
Source ->
http://blacklists.cert.gov.ge/

Source1 ->
https://www.trusted-introducer.org/directory/teams/cert-ge.html

Lists ->
http://blacklists.cert.gov.ge/domains_malware.txt

**Comment by StevenBlack** [comment]
Thank you for this Lorenzo @scafroglia93.

I'm sure you know, there are thousands of possible lists out in the world.

I'm actually not interested in hearing about any of them unless they are remarkable.

I need to ask you to please refrain from suggesting lists here unless they are remarkable.

If a list is remarkable, then please tell me why, making the case for why a particular list is remarkable.

Just posting links just wastes your time, and mine.

If this list is remarkable, please tell us why.

Closing.
