### ISSUE TITLE
new pronographic pages, for blocking

### ISSUE THREAD

**Issue by patos803** [StevenBlack/hosts#1847]
videosdemadurasx.com
  videospornogratisx.net
  pampaporno.com
  veopornogratis.xxx
  bingoporno.com
  puritanas.com
  pornoplay.online
  jovencitas.gratis
  pornfuror.com
  folieporno.fr
  videosxxxporno.xxx
  videosporno.name
  pornogratisvideos.net
  wallaporno.com
  cuecaporno.xxx

Please add the following pornographic pages.

**Comment by dnmTX** [comment]
@patos803 you can refer directly to one of the porn lists curators if you'd like:
https://github.com/Sinfonietta/hostfiles/issues

**Comment by StevenBlack** [comment]
Ping @sinfonietta — thanks!

**Comment by Sinfonietta** [comment]
@StevenBlack I have just added these 👍
