### ISSUE TITLE
Remove contentful.com from blacklist.

### ISSUE THREAD

**Issue by hudson-thomas** [StevenBlack/hosts#1848]
Hi, I was hoping to get `contentful.com` or at least `graphql.contentful.com` removed from the blacklist. It serves the menus and images for [staples.ca](url) and a couple of other major sites listed here: [https://trends.builtwith.com/websitelist/Contentful](url).

I can't quite find the commit that made this issue start but it was within the last month or so.

Thanks for your help.

**Comment by dnmTX** [comment]
**ping** @jawz101 for assist and evaluation 👍

**Comment by StevenBlack** [comment]
Thank you for this Hudson @hudson-thomas.

Yes @jawz101 https://graphql.contentful.com redirects to https://www.contentful.com/developers/docs/references/graphql/#/introduction and this is Mos Def a [graphql](https://graphql.org/) front end.

Thanks for looking at this.

Thanks Dan @dnmTX for the assist.

**Comment by jawz101** [comment]
removed.  thanks

**Comment by StevenBlack** [comment]
@jawz101 thanks man, awesome.

I'm gonna male another release, right now.

**Comment by StevenBlack** [comment]
Closing!
