### ISSUE TITLE
scam shopping site

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#1850]
www.concosua.us
concosua.us
name.shoplazza.store (www.* is an alias for this)

It's another scam site that happens to market Pokemon cards for ~30% of retail value, but also seems to be selling lots of other unrelated products that might be fake too.

https://old.reddit.com/r/PokemonTCG/comments/rrqani

**Comment by StevenBlack** [comment]
Thank you for this Devon @hyder365.

It's not our place to judge stuff like this. We're into blocking ads, active malware, and optionally things like porn, gambling, social media...

It's well beyond our scope, our expertise, and our interest, to judge where people shop online.

Closing.
