### ISSUE TITLE
sbc.io (#Twitter includes t.co - which blocks Tweetbot links)

### ISSUE THREAD

**Issue by MBehr2** [StevenBlack/hosts#1854]
t.co wasn't blocked until then latest update. I've unselected that from my Hosts file updater for the time being.
It seems that Peter Lowe's list incorporated via Little Snitch, also contains the entry as well. Also unselected as well.

Temporary till this is resolved.

**Comment by dnmTX** [comment]
`t.co` is not listed here. You might need to update your lists first,make sure,before posting about non existing issues!

**Comment by MBehr2** [comment]
Apologies if this list isn't yours? http://sbc.io/hosts/alternates/fakenews-gambling-porn-social/hosts

**Comment by dnmTX** [comment]
Steve @StevenBlack are your alternative lists not in sync or something with the latest update from here?

Mick @MBehr2 apologies,completely forgot about that there is a additional non github lists involved.

**Comment by MBehr2** [comment]
# Title: StevenBlack/hosts with the fakenews, gambling, porn and social extensions
#
# This hosts file is a merged collection of hosts from reputable sources,
# with a dash of crowd sourcing via GitHub
#
# Date: 03 January 2022 02:06:37 (UTC)
# Extensions added to this file: fakenews, gambling, porn, social
# Number of unique domains: 148,400
#
# Fetch the latest version of this file: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
# Project home page: https://github.com/StevenBlack/hosts
# Project releases: https://github.com/StevenBlack/hosts/releases
#
# ===============================================================

**Comment by dnmTX** [comment]
@MBehr2 my vision is still fine here. Large fonts are not needed to prove your point.
Now...compare your list with https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts which is the latest,updated here
and where Peter Lowe's lists is present,allways and you'll see that the `t.co` domain isn't listed.

**Comment by StevenBlack** [comment]
Hi Mick @MBehr2!  

Twitter is a social media company.

The version of the hosts file you are using explicitly blocks social media.  Note the `social` in the URL:

```
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
```

**THEREFORE** maybe a different flavor of hosts file is right for you?  See the options here: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

Closing.

**Comment by dnmTX** [comment]
Sooo...it wasn't Peter Lowe's lists from the beginning...great 🤔
