### ISSUE TITLE
Request to remove d.ifengimg.com from blacklist

### ISSUE THREAD

**Issue by humsg** [StevenBlack/hosts#1855]
Hi, can you please have **d.ifengimg.com** removed from blacklist? It serves the whole site's thumbnails of news at www.ifeng.com. I checked my blacklist and finally found out that it is blocked in yours. To whitelist the domain of **d.ifengimg.com** is harmless. 

Thank you for your time.

**Comment by dnmTX** [comment]
**ping** @jawz101 for assist 👍

**Comment by jawz101** [comment]
thanks.  Removed.  At one point a long time ago I merged an Asian list that seemed to have good coverage of that region and that was probably left over.  I wish I could scrub out some of those false positives.

**Comment by humsg** [comment]
yes for sure, but it is a chaos for an Asian list, there is a limited restriction for privacy, and it will take a lot of efforts to make it work properly. Some can cause problem dramatically, I did and still testing out all my browsing record monthly.
here is a blacklist I am using for Chinese region: https://github.com/privacy-protection-tools/anti-AD, they update daily I suppose.

Thank you for your help.
