### ISSUE TITLE
Blacklisting of static.cloud.coveo.com blocks search functionality on certain sites

### ISSUE THREAD

**Issue by NJarZe** [StevenBlack/hosts#1856]
Hello,

The addition of static.cloud.coveo.com to the blacklist has broken the search functionality on certain sites. 
Is this a malicious/ad-tracking site that should remain blocked? 

Thanks!

**Comment by dnmTX** [comment]
One more for ya @jawz101 😉

**Comment by jawz101** [comment]
removed.  thanks

**Comment by StevenBlack** [comment]
Thanks Nestor @NJarZe and @jawz101! 

Closing.
