### ISSUE TITLE
New Github Porn Extension (Repo)

### ISSUE THREAD

**Issue by bd-g** [StevenBlack/hosts#1857]
https://github.com/4skinSkywalker/Anti-Porn-HOSTS-File

Possible addition to the porn extension - has 22 individual contributors and is added to a few times a year on average.

Not sure if @StevenBlack has scripts to check the uniqueness of the hosts on this list versus what is already contained, or any other criteria to add a repo, but I would be willing to do the leg work on that if needed.

**Comment by dnmTX** [comment]
No License and there are some domains with arabic language that most of the resolvers will just throw error.
Steve @StevenBlack  if you're interested,will deep dive even more. Those are just my observations on the surface 👍

**Comment by bd-g** [comment]
I noticed the license as well, just finished submitted a PR to them to add a simple MIT license. Assuming that license is added, any other legwork I could do to make this an easy review for you guys? I checked and there are quite a few unique, legitimate domains that should be blocked that are not yet included in the existing extension repos.

**Comment by dnmTX** [comment]
@bd-g let's wait for Steven @StevenBlack,whenever time permits to run [ghosts](https://github.com/StevenBlack/ghosts) and will go from there 👍

**Comment by StevenBlack** [comment]
Thanks for this @bd-g.

This would add `(41806-14380) = 27,426` domains to our porn list.

The license is a showstopper...

```
$ ghosts -m p -c https://raw.githubusercontent.com/4skinSkywalker/Anti-Porn-HOSTS-File/master/HOSTS.txt  
                                                                                             
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts
Domains: 141,195
Bytes: 4.3 MB
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/4skinSkywalker/Anti-Porn-HOSTS-File/master/HOSTS.txt
Domains: 41,806
Bytes: 1.3 MB
Intersection: 14,380 domains
```

**Comment by StevenBlack** [comment]
From a TLD perspective, this looks generally okay. A few TLD near the bottom are questionable.  The bottom of the .TLD audit often reveals sloppy curation, but this is generally OK.

```
$ ghosts -tld -m https://raw.githubusercontent.com/4skinSkywalker/Anti-Porn-HOSTS-File/master/HOSTS.txt  
                                                                                              
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/4skinSkywalker/Anti-Porn-HOSTS-File/master/HOSTS.txt
Domains: 41,806
Bytes: 1.3 MB
TLD tally:  (256 unique TLD)
   com: 23,965
   net: 3,381
   pl: 1,731
   ru: 1,650
   de: 1,443
   org: 898
   info: 548
   me: 309
   tv: 308
   nl: 299
   uk: 287
   it: 284
   pro: 284
   biz: 273
   co: 271
   xxx: 270
   fr: 238
   cz: 228
   eu: 228
   br: 207
   us: 204
   xyz: 176
   ua: 154
   in: 153
   club: 147
   se: 126
   dk: 123
   cc: 121
   io: 110
   es: 106
   mobi: 104
   au: 102
etc...
   tz: 2
   ist: 2
   pink: 2
   love: 2
   lc: 2
   pa: 2
   gov: 2
   lgbt: 2
   ag: 2
   skceske-porno: 2
   ac: 2
   lu: 2
   store: 2
   team: 2
   pf: 2
   center: 2
   ms: 2
   je: 2
   global: 2
   monster: 2
   services: 2
   film: 2
   travel: 2
   wine: 2
   green: 2
   ke: 2
   siteen: 2
   al: 2
   media: 2
   tt: 2
   trade: 2
   work: 2
   cr: 2
   gallery: 2
   rodeo: 2
   tips: 2
   cloud: 2
   sx: 2
   cf: 2
   kg: 2
   men: 2
   atabout: 2
   care: 1
   gd: 1
   vet: 1
   click: 1
   fund: 1
   pictures: 1
   ooo: 1
   buzz: 1
   wales: 1
   gratis: 1
   supply: 1
   shop: 1
   fyi: 1
   surf: 1
   press: 1
   pet: 1
   bingo: 1
   sale: 1
   mm: 1
   bar: 1
   adult: 1
   dev: 1
   cool: 1
   credit: 1
```

**Comment by StevenBlack** [comment]
Comparing the proposed wist with our non-porn base list we get this, which is interesting:

So there's a 5,477 domain intersection with our non-porn list. I consider this a pretty strong indication of Type I errors though, in fairness, our base list contains quite a few shady porn popup domains.


```
$ ghosts -c https://raw.githubusercontent.com/4skinSkywalker/Anti-Porn-HOSTS-File/master/HOSTS.txt  
                                                                                                  
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 100,735
Bytes: 3.1 MB
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/4skinSkywalker/Anti-Porn-HOSTS-File/master/HOSTS.txt
Domains: 41,806
Bytes: 1.3 MB
Intersection: 5,477 domains
```

**Comment by dnmTX** [comment]
> So there's a 5,477 domain intersection with our non-porn list. I consider this a pretty strong indication of Type I errors though, in fairness, our base list contains quite a few shady porn popup domains.

Following up on this as it got my attention for sure.
Steve @StevenBlack uploading the intersection domains so you can see them.
Probably 99% has nothing to do with porn and to me that whole list more and more looks like some **all-in-one** with
focus on blocking porn but still....
Adding it as a addition to the porn extension is just nonsense to me so i'm 👎 

[intersections.txt](https://github.com/StevenBlack/hosts/files/7823999/intersections.txt)

**Comment by StevenBlack** [comment]
Dan @dnmTX I can understand being a catch-all list because a hosts file is a singular thing, presuming no aggregation methods...

**Comment by dnmTX** [comment]
> Dan @dnmTX I can understand being a catch-all list because a hosts file is a singular thing, presuming no aggregation methods...

It's your call Steve @StevenBlack,i only voiced my opinion as usual 👍

**Comment by bd-g** [comment]
A PR has been merged and there is now a license on the repo. Can we re discuss this?

**Comment by StevenBlack** [comment]
Thanks @bd-g.

Quick check against our current porn list.

Summary: This would add `(41,800 - 14,321) = 27,479` domains to our porn list.

Our current porn list adds `(149,352 - 100,796) = 48,556` domains to our base list. So in effect, this would increase our porn list by `(27,497/48,556) = 56%`, increasing the porn component to `(27,497 + 48,556) = 76,053` domains.

Does anybody feel like we need to add 27,479 domains to our porn list? Like, who's beset by porn, or even seeing porn, when our porn list is active right now? What would the extra 27,479 domains buy us?

That said, maybe our porn curation squad needs to be revitalized? It seems to take awhile for our current curators to execute updates.


```
ghosts -m p -c https://raw.githubusercontent.com/4skinSkywalker/Anti-Porn-HOSTS-File/master/HOSTS.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts
Domains: 141,835
Bytes: 4.3 MB
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/4skinSkywalker/Anti-Porn-HOSTS-File/master/HOSTS.txt
Domains: 41,800
Bytes: 1.3 MB
Intersection: 14,321 domains
```

**Comment by bd-g** [comment]
I would say blocking porn (along with gambling perhaps) is a use case where if you are using it, you probably want to seal off anything and everything. 

New sites pop up everyday. With that said, distributing the load/responsibility to update regularly across more contributors seems like a good thing to me, not a bad one.

**Comment by bd-g** [comment]
Any new thoughts on this? If not, might make sense to close the issue instead of leaving it hanging open.

**Comment by StevenBlack** [comment]
Thanks @bd-g I've decided to decline. Thank you for the suggestion, and I'm sorry this issue remained open and unanswered for so long.
