### ISSUE TITLE
Hiperdex host removal

### ISSUE THREAD

**Issue by aditya-shri** [StevenBlack/hosts#1859]
Please remove hiperdex host from the master host list as it's a manga site and it's safe

**Comment by dnmTX** [comment]
Aditya @aditya-shri see #1818 for more details and why it was listed here.

**Comment by StevenBlack** [comment]
Thank you for this Aditya @aditya-shri, and thank you Dan @dnmTX for the assist.

Closing.

**Comment by aditya-shri** [comment]
@dnmTX Thanks for pointing out the issue.

But most people use hiperdex with tachiyomi app but since it's blocked and whitelisting it also doesn't work so can it be added to other categories instead of the main one.

**Comment by dnmTX** [comment]
> and whitelisting it also doesn't work

What do you mean by that,give more details please
