### ISSUE TITLE
RFC: graph.microsoft.com

### ISSUE THREAD

**Issue by TPS** [StevenBlack/hosts#1864]
Per https://docs.microsoft.com/en-us/graph/overview-major-services, `graph.microsoft.com` deserves some consideration for blocking, but am concerned about problems like #1853.  What do y'all think?

**Comment by StevenBlack** [comment]
Hi @TPS thank you for this.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Can you please submit this suggestion to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant)?  Thanks!

Closing.

**Comment by TPS** [comment]
👌🏾, @StevenBlack,  so refiled @ https://github.com/shreyasminocha/shady-hosts/issues/9.
