### ISSUE TITLE
dl.dropboxusercontent.com is in the blocklist: impossible to download file from dropbox web UI

### ISSUE THREAD

**Issue by Belphemur** [StevenBlack/hosts#1868]
Hello,

`dl.dropboxusercontent.com` has been added to the blocklist and this block downloading any file from the dropbox ui.

I'm pretty sure this is a little too much to block the whole dropbox service.

**Comment by StevenBlack** [comment]
Wow. Thanks @Belphemur that's just unacceptable.

This is fixed in the latest release, live and online now.

Thanks again for the heads-up!

Closing.

**Comment by dnmTX** [comment]
Steve @StevenBlack you dropping the entire list,because of one false-positive?
I could've contact the curator about it,he usually responds in a timely manner.
Can you give more details about that unusual move. I guess i'm missing something 🤔

**Comment by StevenBlack** [comment]
Hi Dan @dnmTX I'm curious what other options do I have? Wait? How long? How long should I tolerate Dropbox being offline? Hours?  Minutes?  How about zero; it's Dropbox. That's one heck of a false positive.

**Comment by Belphemur** [comment]
Also, there is a danger with URL based Domain blocklist.

Since they have an automatic process where they take a given URL and transform into domain, this can lead to a lot of false positives.

It's not because a URL on the domain is malicious that the whole domain is.

Nonetheless, I've also reported the false positive to their github repo.

**Comment by dnmTX** [comment]
> I would recommend keeping this list out of this blocklist

And i **WOULD** recommend...from the  bottom of my heart. Start using **GOOGLE SAFEBROWSING** and forget about that list here.
Plenty of crybabies already here. Need no more !!!!!!

**Comment by StevenBlack** [comment]
Dan @dnmTX please try be nice to visitors here 😄.

Excuse moi Antoine, j'ai aucune idée de quoi il parle.

**Comment by dnmTX** [comment]
I'm trying...but there are limits Steve @StevenBlack,especially when it comes to a valuable lists,that keeps us all a bit safer,the one you just dropped because of....cry me a river here.
I honestly don't remember seeing anywhere around here or in any blocklist in circulation for that matter guarantees to be given against false-pasitives.
User end knowledge on how to navigate around such a issues is required as this whole thing is,to say the least,experimental.
If even the basic of a knowledge is not present,well....i'd say,**Google Safebrowsing** is your friend !!!!!

**Comment by StevenBlack** [comment]
Not everyone is into Google or Chrome Dan @dnmTX.

Remember when CoinBlockerList listed every crypto exchange one day? Then it took awhile to get that resolved? I don't want to replay that.

Listing `dl.dropboxusercontent.com`, that's not a little thing. That's not a common false-positive. That's a major fuckup. I just need to know, how did THAT happen?  Maybe it's an innocent mistake and, if so, that's fine; I get it.  But we don't know that.

Here's how I see it: I set the bar. Listing `dl.dropboxusercontent.com` is way below the bar. I need to make sure everyone understands, to be on this list, you gotta bring your A-game. I trust curator judgment, and I trust my judgment too: no fucking way is this list blocking `dl.dropboxusercontent.com`.

Until that's resolved, and I'm reassured the A-game is back, then we'll talk about restoring that source.

**Comment by FadeMind** [comment]
For what purpose is `whitelist`? 
If you just purge whole soruce based on one falsepositive, what about video streaming domains `gemius` things in common?

https://oisd.nl/excludes.php?w=gemius.pl

or

https://oisd.nl/excludes.php?w=hit.stat24.com

https://oisd.nl/excludes.php?w=ipla.hit.stat24.com

https://oisd.nl/excludes.php?w=pro.hit.gemius.pl

etc.

False positve?
Domain goin to `whitelist` and owner of repo have opened new issue ticket on site.

**Comment by StevenBlack** [comment]
Tomasz @FadeMind `whitelist` is for userland, downstream; not here.
