### ISSUE TITLE
Contributing to gambling list?

### ISSUE THREAD

**Issue by Stig124** [StevenBlack/hosts#1869]
Hello,

I'd like to add the betting sites of my home country (France) to the gambling list, but I don't find a way to do so. In the upstream list on the README, there is only links for the malicious sites lists but none from the extensions.

Do I need to fork this repo, and modify the file directly (or add a folder (like for the porn extension) then my list in)? Or is there someone to contact about contributing to the gambling extensions?

**Comment by StevenBlack** [comment]
Hi @Stig124 

User @sinfonietta is one of our gambling curators, in [this repo here](https://github.com/Sinfonietta/hostfiles).

I agree that this is hard to find.  I'll try to improve this.

This repo has 17 different readme files 😄 and it's never clear which sources are unique to each readme.

* [readme.md](https://github.com/StevenBlack/hosts/blob/master/readme.md)
* [alternates/fakenews/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews/readme.md)
* [alternates/fakenews-gambling/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-gambling/readme.md)
* [alternates/fakenews-gambling-porn/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-gambling-porn/readme.md)
* [alternates/fakenews-gambling-porn-social/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-gambling-porn-social/readme.md)
* [alternates/fakenews-gambling-social/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-gambling-social/readme.md)
* [alternates/fakenews-porn/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-porn/readme.md)
* [alternates/fakenews-porn-social/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-porn-social/readme.md)
* [alternates/fakenews-social/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-social/readme.md)
* [alternates/gambling/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/gambling/readme.md)
* [alternates/gambling-porn/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/gambling-porn/readme.md)
* [alternates/gambling-porn-social/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/gambling-porn-social/readme.md)
* [alternates/gambling-social/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/gambling-social/readme.md)
* [alternates/porn/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/porn/readme.md)
* [alternates/porn-social/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/porn-social/readme.md)
* [alternates/social/readme.md](https://github.com/StevenBlack/hosts/blob/master/alternates/social/readme.md)
* [extensions/readme.md](https://github.com/StevenBlack/hosts/blob/master/extensions/readme.md)

**Comment by Stig124** [comment]
> This repo has 17 different readme files smile and it's never clear which sources are unique to each readme.

I can help making a unified README if you need

**Comment by StevenBlack** [comment]
Thank you for this kind offer @Stig124.

We have a unified readme, it's [readme_template.md](https://github.com/StevenBlack/hosts/blob/master/readme_template.md) which gets updated whenever I run a release.

**Comment by StevenBlack** [comment]
Closing!  Thanks @Stig124.
