### ISSUE TITLE
FadeMind's add.Risk/hosts is adding sites that do not fit the base definitions

### ISSUE THREAD

**Issue by creedflan738** [StevenBlack/hosts#187]
FadeMind's add.Risk/hosts is injecting into the unified hosts file for adware and malware sites like twttr.com (an alias for twitter.com) and drunkenstepfather.com (a site that belongs in the porn list, not the master). Please either tighten up the criteria for what gets put in this child list, or stop incorporating it directly into the main list.

**Comment by StevenBlack** [comment]
Thanks @creedflan738!  I'll take that under consideration.
