### ISSUE TITLE
Tiktok captcha verification blocked with standard Unified Hosts file

### ISSUE THREAD

**Issue by MultiKoopa** [StevenBlack/hosts#1870]
I recently tried to open a vm.tiktok link, which is shared from the Tiktok app I think

https://vm.tiktok.com/TTPdh1RG3o/

It redirected me to this:

![tiktoksendhelp](https://user-images.githubusercontent.com/30543543/150681639-42f4756c-b2b2-45b8-a580-7845f298af22.png)

Full URL: https://m.tiktok.com/v/6983513482733964549.html?_d=secCgYIASAHKAESPgo8YeQtZ0G57GfP0lrk44u0%2Fizc8Nt%2Bviur%2BDHGpe7%2FTDKKumJPtHu97BgWnTZkOWGB%2B7Old0E%2FeF%2Blqq5AGgA%3D&checksum=bd65643ed931017224bc7a0dff849ed3caa0543c08f82423963a1e02cf10e14f&language=en&preview_pb=0&sec_user_id=MS4wLjABAAAAWDht20BFCFi2h1E_7dExsCwQUbVee2at0-oAeD3kYNX7whtimaBoqzfVlgAO4ZkB&share_app_id=1233&share_item_id=6983513482733964549&share_link_id=7EB5B298-EDC3-4BE1-B37E-BA8DFBB2F139&source=h5_m&timestamp=1642943774&tt_from=copy&u_code=df6a1j659de2ed&user_id=6887326505606251526&utm_campaign=client_share&utm_medium=ios&utm_source=copy
 
I had no idea what was happening. If I opened the link on my phone's browser, it worked just fine, and just sent me to the actual tiktok video, which I could then share with my desktop. 

on a whim, I disabled my hosts file, and then saw this: 

![tiktokcaptcha](https://user-images.githubusercontent.com/30543543/150681675-edda5091-81e3-4f26-b754-074cd05ecaef.png)

Seems one of the recent updates to the Unified Hosts file is screwing with Tiktok's Captcha verification, because I used to be able to open the vm.tiktok links fine a little while ago.

No idea which domain it could be though. Anybody have any ideas?

**Comment by StevenBlack** [comment]
Hi @MultiKoopa thank you for this.

In our main list we block:

```
ads.tiktok.com
analytics.tiktok.com
```

That's not gonna change, I reckon. On first approximation, those don't appear to be the problem here

If TikTok's engineering requires routing through these or other sketch domains, that's on TikTok, not on us.

Personal observation: if a business relies on a 600+ character URL with 15 distinct parameters and ids, that's on them.

Here is the breakdown of that URL.  See what I mean? This exactly illustrates what our base list is all about. Enough with the tracking. 🤷

```
https://m.tiktok.com/
v/
6983513482733964549.html?
_d=secCgYIASAHKAESPgo8YeQtZ0G57GfP0lrk44u0%2Fizc8Nt%2Bviur%2BDHGpe7%2FTDKKumJPtHu97BgWnTZkOWGB%2B7Old0E%2FeF%2Blqq5AGgA%3D
checksum=bd65643ed931017224bc7a0dff849ed3caa0543c08f82423963a1e02cf10e14f
language=en
preview_pb=0
sec_user_id=MS4wLjABAAAAWDht20BFCFi2h1E_7dExsCwQUbVee2at0-oAeD3kYNX7whtimaBoqzfVlgAO4ZkB
share_app_id=1233
share_item_id=6983513482733964549
share_link_id=7EB5B298-EDC3-4BE1-B37E-BA8DFBB2F139
source=h5_m
timestamp=1642943774
tt_from=copy
u_code=df6a1j659de2ed
user_id=6887326505606251526
utm_campaign=client_share
utm_medium=ios
utm_source=copy
```

**Comment by MultiKoopa** [comment]
....damb that's a lot lol

I guess my only option then is to send the link to my phone and then get the real link sent back to my desktop. definitely not disabling my hosts file for Tiktok or anyone really

thanks for the explanation!

**Comment by bigdargon** [comment]
Please try to whitelist the subdomain `byteoversea.com`

**Comment by MultiKoopa** [comment]
> Please try to whitelist the subdomain `byteoversea.com`

Not sure how I'd force that captcha to appear again on Tiktok

**Comment by bigdargon** [comment]
@MultiKoopa I'm using nextdns and tiktok is working fine
![Screenshot 2022-01-26 at 09-45-01 Astralblaster on TikTok](https://user-images.githubusercontent.com/10969626/151095521-5ab48c59-2e76-4dd1-a451-044e063bc1eb.png)

**Comment by MultiKoopa** [comment]
> @MultiKoopa I'm using nextdns and tiktok is working fine ![Screenshot 2022-01-26 at 09-45-01 Astralblaster on TikTok](https://user-images.githubusercontent.com/10969626/151095521-5ab48c59-2e76-4dd1-a451-044e063bc1eb.png)

@bigdargon yeah, it was a captcha I got at random that was the problem

**Comment by StevenBlack** [comment]
Thanks everybody I'm going to close this because it doesn't appear actionable.
