### ISSUE TITLE
Firefox wont run while using this host file

### ISSUE THREAD

**Issue by DemigodTheDonMecca** [StevenBlack/hosts#1872]
First of all Steve I will tell you I am a faithful user of your block list and have been for over three years now. Just want to let you know that there is an odd blocklist you have created and the address to the list is as follows
#----------‐-----------------------------

https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/EnglishFilter/sections/adservers.txt 

I'm not a pro at finding things especially on such a huge list I wouldn't know where to begin or what software to use but there is something in that list that is causing Mozilla Firefox to block almost all web pages and it says they are not secure, you can even go to https and it still doesn't fix the issue. The only pics I have found is to turn off that list but I think it would be a great list if you could find the entry or whatever is causing Firefox to malfunction and lock every web page saying it's not secure. Sorry if I'm doing this wrong but I'm new to this website and trying to learn but I'm maybe 6 months into using it other than grabbing your host files. Please excuse my ignorance if I've done anything wrong. Thank you very much and keep up the tedious immensely grateful for us work at creating these lists.

<img>https://i.imgur.com/KEr1fNw.png</img>

<img>https://i.imgur.com/wlPkLbT.png</img>

**Comment by StevenBlack** [comment]
Hi @DemigodTheDonMecca thank you for this.

The link above isn't our list, and it's also not a hosts file 😄.

We carry one list from Adguard, not the one you link above.

Closing.

**Comment by DemigodTheDonMecca** [comment]
Reply was fast and I understand your knowledge and dedication to your work. Out of curiosity why can I add raw lists/filters and they remove ads that were there like on a Warez site. Their loaded with ads so much so that you can barely find the download button without having pop-up and redirect and cookie notices and whatnot but once I have finished adding the list I use as filter list and this is not effective with the standard add guard lists but once I add the list I have found and our exactly like the one I sent to you all of a sudden the whereas sites show Almost perfectly clean Alma pop-ups disappear The Readirects go away and the eyes left all over the pages all of a sudden disappear after I've added these lists and I am left with a clean site that looks like a site that isn't out to make money with ads and click bait and the site is totally clean other than the intended writing with big gaps in between where the odds were but now it's just clear real estate. Do you know why this is happening and it does not happen with the regular adguard filters until I add my 15 or so list similar to the ones that I sent to you. Sorry if I insinuated they were your list I didn't mean to state that and I did not know whose list they were I just knew I got it from your site or at least from following a link on your site. And don't take this as complaining because I appreciate all the work you put in and other people do because without you guys we would be bare naked swimming with sharks and it would not end well and the internet is only becoming more risky to use by the day. I use a guard VPN as well and I use DNS Crypt without any filter but just the standard one that has ad blocking built in. I have been experimenting with this for over a year to learn how about this are blocking project and invested in a lifetime license to add guard and a lifetime to adguard zpn because it works better than anything else I have tried and I'm just lost as to why you state your lists or whoever's list it is is not the proper list and should not work inside the adguard program but no matter what I do to the program the odds don't disappear at least not most of them until I add the list that are identical to the one I sent you. I'm not being pushy I'm actually quite curious as to what you can tell me about host files and Adblock filters because I want to do things correctly. Thank you for getting back to me and I hope you have a great day. Sorry for the long response.
-------- Original message --------From: Steven Black ***@***.***> Date: 2022-01-25  11:56 a.m.  (GMT-04:00) To: StevenBlack/hosts ***@***.***> Cc: DemigodTheDonMecca ***@***.***>, Mention ***@***.***> Subject: Re: [StevenBlack/hosts] Firefox wont run while using this host file
  (Issue #1872) 

Hi @DemigodTheDonMecca thank you for this.

The link above isn't our list, and it's also not a hosts file 😄.

We carry one list from Adguard, not the one you link above.

Closing.
