### ISSUE TITLE
p*rn lists

### ISSUE THREAD

**Issue by Danc2050** [StevenBlack/hosts#1874]
On `https://asianpornwebsites.com/` there are many websites which are not included in the `p*rn` filter. Here is a partial list of the websites I found were not blocked on the `p*rn` list:
[pn.txt](https://github.com/StevenBlack/hosts/files/7947737/pn.txt)

**Comment by StevenBlack** [comment]
Thank you Daniel @Danc2050 for this.

Ping @sinfonietta, can you consider listing these?

**Comment by 1boii** [comment]
I went through the site and found a total of [165](https://github.com/Sinfonietta/hostfiles/pull/169/commits/20278f882ad0b9c55e7ef310ca6f9eac9960d39d) new domains. They have been added to my pending [PR](https://github.com/Sinfonietta/hostfiles/pull/169).

**Comment by Danc2050** [comment]
Wow, that is amazing amount of websites. Another website I found that most likely has more: `https://theporndude.com/top-asian-porn-tube-sites`.

I am a computer scientist and I wonder if there is actually a way to visit websites at random and use AI to identify websites (for later review). That would be interesting...

**Comment by 1boii** [comment]
Yeah, I found that site too. In fact, I'm creating a list of these "directory" sites: https://github.com/1boii/hosts/blob/main/data/directory-sites I haven't gone through all of them yet.

`I am a computer scientist and I wonder if there is actually a way to crawl the internet and use AI to identify/categorize websites (for later review). That would be interesting...`
I've been considering this as well. My [repo](https://github.com/1boii/hosts) contains a list of adult actresses names (about 15k) which I extracted from different adult sites. The idea is to combine these actress names with keywords and let a script crawl a search engine like duckduckgo to collect possible sites which can then be reviewed (after depublication etc. of course)

**Comment by rautamiekka** [comment]
> The idea is to combine these actress names with keywords and let a script crawl a search engine like duckduckgo to collect possible sites which can then be reviewed (after deduplication etc. of course).

May be just me, but that sounds like an even bigger cat-and-mouse than any hosts file project will ever be. Simply put: I can't see that working in any resemblance of good enough. Much like trying to use parental controls to block kids from viewing porn.

**Comment by StevenBlack** [comment]
@Danc2050, @1boii, @rautamiekka here's a point of personal philosophy about porn lists, and the vision for porn blocking in our lists.

* Our amalgamated lists are used in a wide variety of platforms and applications, including some notable downstream processes and pipelines, but also some memory and resource-constrained ones.

* It's never going to be feasible, or practical, to block all porn. 

* It's never possible to define a line that makes everybody happy. 

* A personal aspiration of mine: never having to deal directly with deeply stupid people.

So here's the vision: our porn hosts files serve to help keep porn out of your home and away from your kids.  Also to keep porn away from you, if you're overly tempted by that.

I think our porn lists do a great job right now. I don't hear much complaining. We're approaching a point of diminishing returns, where increasing the list size provides marginal, possibly negligible benefits.

**Comment by Danc2050** [comment]
I agree. Using a service like Klazify is quite expensive and I doubt anyone would be willing to put up that kind of capital. Though I still like the idea of catching as many porn sites as possible as soon as they come up, there is probably at least one new porn site put up every minute, somwehere in some country, and if someone is dedicated enough, they can seek it out or may stumble across it. Thank you for the great list @StevenBlack and those that contribute to it.
