### ISSUE TITLE
sentry.io is blocked again?

### ISSUE THREAD

**Issue by kenrick95** [StevenBlack/hosts#1875]
Same issue as #1759 However `sentry.io` appeared in the block list again after this update few days ago

https://github.com/StevenBlack/hosts/commit/986882538f0fa82a1934fa0d94d27361e697dbcc#diff-78b046f93928be9299bb40a2406592b657eb81da15594e9952c493265e984273R8898-R8911

**Comment by StevenBlack** [comment]
Looks like Adaway added sentry to their curation.

All of these in `data/adaway.org/hosts`

```
8898:# [sentry.io]
8899:127.0.0.1 sentry.io
8900:127.0.0.1 ingest.sentry.io
8901:127.0.0.1 o107031.ingest.sentry.io
8902:127.0.0.1 o129937.ingest.sentry.io
8903:127.0.0.1 o325556.ingest.sentry.io
8904:127.0.0.1 o334541.ingest.sentry.io
8905:127.0.0.1 o400018.ingest.sentry.io
8906:127.0.0.1 o472445.ingest.sentry.io
8907:127.0.0.1 o491168.ingest.sentry.io
8908:127.0.0.1 o502263.ingest.sentry.io
8909:127.0.0.1 o534899.ingest.sentry.io
8910:127.0.0.1 o77029.ingest.sentry.io
8911:127.0.0.1 disney.my.sentry.io
```

Kenrick @kenrick95 you can make the case by filing an issue here: https://github.com/AdAway/adaway.github.io/issues. I trust @jawz101 to decide.

**Comment by jawz101** [comment]
they were all recently removed

**Comment by StevenBlack** [comment]
Thanks as always @jawz101!

Closing.
