### ISSUE TITLE
t.paypal.com required for steam purchases

### ISSUE THREAD

**Issue by Taoquitok** [StevenBlack/hosts#1876]
Without whitelisting the domain `t.paypal.com`, steam is unable to complete purchases via paypal, instead getting stuck at the point pressing purchase, and requiring you to go and cancel the purchase to repeat.  
The behaviour was noticed by re-attempting the purchase and getting a `Your transaction cannot be completed because you have another pending transaction on your account` message.  
Whitelisting the domain, cancelling the transaction in steam (_Account details -> view purchase history -> [pending purchase] -> cancel transaction_), and retrying confirms it now works

**Comment by StevenBlack** [comment]
Thank you for this Iain @Taoquitok.

Ping @jawz101, what do you think?  Thanks!

**Comment by jawz101** [comment]
removed.  thanks.  I see some chatter on the web in regards to this domain causing some breakage now

**Comment by StevenBlack** [comment]
Awesome!  Closing.
