### ISSUE TITLE
Add these websites to the main blocklist

### ISSUE THREAD

**Issue by prorounak2005** [StevenBlack/hosts#1878]
0.0.0.0 arc.io
0.0.0.0 swallowcrockerybless.com
0.0.0.0 uptimecdn.com
0.0.0.0 velocitycdn.com
0.0.0.0 bknkz.flndmyiove.net

**Comment by StevenBlack** [comment]
🙄 thank you anon for this is a zero-effort, information-free, justification-free waste of time.

Closing.
