### ISSUE TITLE
Problems with using Les Mills on demand

### ISSUE THREAD

**Issue by Dri3Pinter** [StevenBlack/hosts#1879]
Last week I had suddenly problems with the content of Les Mills on demand behind Pihole.
I noticed api.vhx.tv is on the blocklist. After whitelisting api.vhx.tv the content is accessible again.
Is it possible to remove api.vhx.tv from the list?

**Comment by StevenBlack** [comment]
Thank you for this @Dri3Pinter. Ping @jawz101, thank you in advance for looking into this.

**Comment by jawz101** [comment]
removed.  thanks

**Comment by StevenBlack** [comment]
Thanks @jawz101 — closing.
