### ISSUE TITLE
Unable to login into your phone app on android when `vortex.data.microsoft.com` is blocked

### ISSUE THREAD

**Issue by soredake** [StevenBlack/hosts#1881]
https://play.google.com/store/apps/details?id=com.microsoft.appmanager

**Comment by StevenBlack** [comment]
Thank you for this @soredake.

This is upstream from us. Shreyas @shreyasminocha what do you think?

**Comment by shreyasminocha** [comment]
>     web.vortex.data.microsoft.com
>     web.vortex.data.msn.com

Considering the precedent for blocking similar domains (EasyPrivacy and [NextDNS](https://github.com/nextdns/metadata/blob/master/privacy/native/windows)), I'm a little hesitant. @soredake can you confirm that you're able to login when you unblock `web.vortex.data.microsoft.com`?

**Comment by soredake** [comment]
> >     web.vortex.data.microsoft.com
> >     web.vortex.data.msn.com
> 
> Considering the precedent for blocking similar domains (EasyPrivacy and [NextDNS](https://github.com/nextdns/metadata/blob/master/privacy/native/windows)), I'm a little hesitant. @soredake can you confirm that you're able to login when you unblock `web.vortex.data.microsoft.com`?

Yes, after whitelisting i am able to login into the app.

**Comment by shreyasminocha** [comment]
I've removed these two domains. Hope the next release fixes the login issue @soredake!

**Comment by StevenBlack** [comment]
Thank you @shreyasminocha!
