### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by look-at-the-sky** [StevenBlack/hosts#1883]
cdn.donmai.us is currently included in the porn list but it also serves the safe-only variant of Danbooru (safebooru.donmai.us) therefore it should be removed.
Speaking of Danbooru, betabooru.donmai.us should also be added to the list.
Also a domain in the fakenews extension blocked me from downloading something off Dropbox, but I can't remember what it was.

**Comment by seebeedub** [comment]
the vhx.tv rule blocks the Criterion Channel streaming service. 
PiHole says it is in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts but I don't see it so I'm  confused. Anyway whitelisting it solved my issue watching Criterion Channel on Roku
Thanks

**Comment by StevenBlack** [comment]
Thank you for this @look-at-the-sky.

The domain `cdn.donmai.us` is used to serve porn so it stays blocked in our porn list.

@seebeedub we don't list domain `vhx.tv`.  Maybe log in to Pi-Hole and refresh sources?

Closing.

**Comment by seebeedub** [comment]
Yes - it was an old list. My bad - thank you!
