### ISSUE TITLE
coins-bit.info (Phishing)

### ISSUE THREAD

**Issue by 3xploiton3** [StevenBlack/hosts#1885]
Phishing link i think
info@juntopublishing.com
ig8o1z8u2@r3b2fa.coins-bit.info

https://i.imgur.com/IznOhqJ.png

**Comment by StevenBlack** [comment]
Hi @3xploiton3 – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.

**Comment by 3xploiton3** [comment]
yeah and this one included

![image](https://user-images.githubusercontent.com/19517680/152669514-8bb1d6dd-7530-43dc-a803-70a6fd163d94.png)

**Comment by StevenBlack** [comment]
Look @3xploiton3 let me explain how this works.

You come to us with no context, no justification, just links.

This isn't an add-only bucket.  Lists require curation.  How do I test that these are what you "think" these are? How do I know there is any quality proposed by you?  How am I supposed to deal with eventually clearing these from my list when there is no longer any need for these?

You're coming here and creating work for me.  Here's news: I don't need people to come here and create work for me as a result of essentially ZERO evidence.

You actually said,

> Phishing link i think

Thank you very much!  I decline.
