### ISSUE TITLE
Steven black, Eric Roberts, Andrew Black

### ISSUE THREAD

**Issue by Nimotaj** [StevenBlack/hosts#1886]
The names listed above are the men who have rewired my car and my home to live stream my private life without my consent. They also post my bathroom visits. These men live below my mother's home and also next door to me. They have been served a cease and desist letter from my attorney's. So any people who are aware of this I advise to displace yourself from these men who have violated several laws by California penal codes. Thanks

**Comment by rautamiekka** [comment]
https://github.com/4skinSkywalker/Anti-Porn-HOSTS-File/issues/57

**Comment by StevenBlack** [comment]
🙄
