### ISSUE TITLE
Please add these websites to the blocklist 

### ISSUE THREAD

**Issue by prorounak2005** [StevenBlack/hosts#1888]
1) swallowcrockerybless.com

i) Reason - This is the website responsible for showing ads on many websites like rarbg.to (a torrent website).

2. bknkz.flndmyiove.net

i) Reason - Scam dating website. Serves malicious ads if u go to the website. The reason to block this website is because in many youtube spam comments they promote these website like "dateus.uno" , "stepsister.uno" and all these website redirects us to  bknkz.flndmyiove.net. This website is blocked in the "Ublock - Badware risk blocklist"

![image](https://user-images.githubusercontent.com/69617708/152672530-74b43815-a9b3-43b0-b8bf-c41d5c4b0998.png)

![image](https://user-images.githubusercontent.com/69617708/152672361-b41b50b6-84c6-4423-885b-02dd6284ccd1.png)

3. closureevaporatefume.com

i) Serves ads on websites like mangasee ( A website to read managa) . 
![image](https://user-images.githubusercontent.com/69617708/152672503-9ff4a948-7eb4-4a13-bf65-07bc1894c18a.png)

**Comment by StevenBlack** [comment]
Ping @sinfonietta I think these are appropriate for your list?

**Comment by Sinfonietta** [comment]
@StevenBlack I have added these

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta.

Closing.
