### ISSUE TITLE
What does "white" mean in hosts?

### ISSUE THREAD

**Issue by evildog1** [StevenBlack/hosts#189]
Hi, I have seen some hosts list that have "white" in it. What does "white" mean in hosts? 

```
white ad.dmm.com
white app-adforce.jp
white imgstat.ameba.jp
white lh3.googleusercontent.com
white rd.rakuten.co.jp
white scontent.xx.fbcdn.net
white setting.adzcore.com
white static.xx.fbcdn.net
white ws.tapjoyads.com
white www.google-analytics.com
white www.googleadservices.com
```

**Comment by Laicure** [comment]
Hello,

Where did you find those? (I supposed that is your whitelist..?)

**Comment by evildog1** [comment]
I found a japanese hosts somewhere that i already forgot

**Comment by Laicure** [comment]
/hmm On my POV, that list will break the hosts file.
The **white** thing there should be an IP like 0.0.0.0, maybe the white is just an indicator that _it is_ a whitelist.

**Comment by evildog1** [comment]
oh ok. thanks for your help
