### ISSUE TITLE
clickserve.dartsearch.net

### ISSUE THREAD

**Issue by 0ABDL0** [StevenBlack/hosts#1893]
It's a website used for Googles shopping and virtually everything else has it whitelisted, just wanted to let you guys know as it brakes sthe shopping tab without whitelisting.

**Comment by 0ABDL0** [comment]
To give further explaining, the domain gets hit from how I've seen it only when the user clicks a Google Shopping domain as a redirector, the two intial redirect urls are blocked by every other domain list but this domain has been whitelisted by nearly everyone at this point since it isn't shown up anywhere else other than manually clicking a Google shopping AD when searching for a product so it is only observed when manually clicked.

**Comment by StevenBlack** [comment]
Hi @0ABDL0 thank you for this.

The `clickserve.dartsearch.net` comes to us via Dan Pollock's list at `someowhocares.org`.  You can reach Dan at hosts@someonewhocares.org.

**Comment by 0ABDL0** [comment]
> Hi @0ABDL0 thank you for this.
> 
> The `clickserve.dartsearch.net` comes to us via Dan Pollock's list at `someowhocares.org`. You can reach Dan at [hosts@someonewhocares.org](mailto:hosts@someonewhocares.org).

I have sent an email to the address, thank you for letting me know and hopefully it gets fixed thanks again for your time.
