### ISSUE TITLE
Fake news list barely maintained

### ISSUE THREAD

**Issue by SharkTH** [StevenBlack/hosts#1898]
Marktron's fakenews list is barely maintained. The last commit was 16 months ago, and there are open pull requests dating back to 2017.

**Comment by StevenBlack** [comment]
Thank you for your point of view @SharkTH.

I don't put much stock in those stale PRs, they're not merge worthy for reasons I don't care to discuss here other than to say, I have no problem with that.

I'm happy with the state of our Fake News list as curated by @marktron.  I'd also be happy to accept other curated sources of Fake News domains, but this one stays.

Closing.
