### ISSUE TITLE
A very agressive domain

### ISSUE THREAD

**Issue by ray-lacomuna** [StevenBlack/hosts#1903]
Here is a domain that has some very aggressive and invasive advertising startegies. It's a particularly annoying sports betting site, so far I've been able to find 3 hosts for it:

caliente.mx
www.caliente.mx
online.caliente.mx

**Comment by StevenBlack** [comment]
Thank you for this Ray @ray-lacomuna.

Ping @sinfonietta since this looks like it's all about gambling.

**Comment by ray-lacomuna** [comment]
You are welcome, @StevenBlack . Glad to be of some help.

**Comment by Sinfonietta** [comment]
@StevenBlack I have added these.

**Comment by StevenBlack** [comment]
Thank you everybody!  Closing.
