### ISSUE TITLE
RT.COM

### ISSUE THREAD

**Issue by NickDimou** [StevenBlack/hosts#1904]
I am wondering why rt.com is considered fake news, but cnn.com or others are not. Is this a biased decision? Are there more of this in StevenBlack hosts lists?

**Comment by StevenBlack** [comment]
Thank you for your question Nick @NickDimou.

I don't curate the Fake News extension, @marktron does that.  I think Mark does a great job and he takes tons of flak and heat for it, for which I am grateful.

Biases in media is actually an widely studied academic subject.  Here's (below) a summary from one source, https://mediabiaschart.com

You cite CNN.  While I certainly don't endorse CNN, and they certainly skew left, your assertion that it's "fake news" doesn't stand up according to any source I've ever seen.  It gets things wrong, as all news organizations do, but *fake news*, that's categorically not the case according to all research I've ever seen.

<img width="1175" alt="2022-02-24_13-08-25" src="https://user-images.githubusercontent.com/80144/155582327-a3484775-568e-4ce5-ab80-78b685d67225.png">

**Comment by StevenBlack** [comment]
Closing.

**Comment by NickDimou** [comment]
The question is not answered, but I appreciate the "effort".
