### ISSUE TITLE
Add NSFW subreddits as a part of porn blocking

### ISSUE THREAD

**Issue by defa02005** [StevenBlack/hosts#1907]
Hi, so I was thinking whether it'll be possible to block nsfw subreddits. On googling, many of them show up in any general nsfw search. 

Will having a full link like www.reddit.com/r/Example, etc. be helpful in blocking them, and only them, such that reddit and other subs are still accessible?

**Comment by StevenBlack** [comment]
Hi @defa02005 thank you for your question.

Hosts files operate on domains only.  Take this diagram for example, which comes from the [URL Wikipedia Article](https://en.wikipedia.org/wiki/URL).  We only operate on the `Host` segment, not the subsequent pathing.

![Hosts](https://en.wikipedia.org/wiki/URL#/media/File:URI_syntax_diagram.svg)

**Comment by StevenBlack** [comment]
Closing!
