### ISSUE TITLE
Host files doesn't work in Safari

### ISSUE THREAD

**Issue by elcansaito** [StevenBlack/hosts#1908]
Firstly, I want to thank Steven to create such excellent host files. Impressive!!!. 
Writing to you to see if you could let us know why host files work well in Chrome but not in Safari. The same website, for example, www.elmundo.es, doesn´t show. any ads in chrome but in Safari is full of it.  Safari Version 15.3 and Mac is Monterey.
In the same context, when I added the websites at the end of the host files adding...0.0.0.0 elpais.com and 0.0.0.0 elmundo.es, chrome allows to open el mundo.es but not elpais.com, however, safari open both pages but with many ads.

![Untitled 3](https://user-images.githubusercontent.com/8972010/156697625-e05e5e36-1b24-4733-a586-34b8d62dd474.png)

**Comment by StevenBlack** [comment]
Hi @elcansaito thank you so much for your very kind acknowledgment!

I think this describes two browsers, one with a primed cache, and one with a clean cache.

* [This article](https://support.apple.com/en-us/HT201265) explains how to clear the cache in Safari on iOS.

* [This article](https://www.macrumors.com/how-to/clear-safari-cache/) explains likewise for MacOS.

Does this help?

**Comment by elcansaito** [comment]
Hi @StevenBlack thanks for your prompt reply. 
I have already cleaned the cache, run the code in the terminal to restart the DNS as you indicated. 
Searched online to figure it why, and I found this article but I don´t really understand the reason.
https://superuser.com/questions/1657925/some-websites-bypass-hosts-file-in-safari

My understanding is that adding the website in the host.file will prevent ads to appear on that website, but I might be wrong. In any case, it should be the same for both browsers. I´ll restart the computer several times to see if that takes effect.
Thanks again Steven,
J

**Comment by StevenBlack** [comment]
> My understanding is that adding the website in the host.file will prevent ads to appear on that website

@elcansaito no, that's not how it works.  

When you add a host to the hosts file, with a `0.0.0.0` prefix or a `127.0.0.1` prefix, requests to that domain never leave your machine.  Instead, those requests get resolved as `404` on your own machine.  It prevents requests from ever getting to that domain.

**Comment by elcansaito** [comment]
Thanks again @StevenBlack for your reply. 
I realised that I can't open two pages in chrome since I added it to the host files, but I can open all of them in Safari  (with all the ads). In chrome, the only one I can open www.elmundo.es doesn't appear with ads, so this means adding to the host file works but in some weird way. 
I was using https://winhelp2002.mvps.org/hosts.htm this for a long time, and I don't see the ads in those pages in my laptop using that has files that is obsolete now. 
Maybe the question is, how can I remove the ads from those websites? If adding the website at the end of the host file is not the solution, how could I remove them? I think the solution should be easy because how can it be that using an obsolete host file I cannot see the ads in my laptop and using yours in my desktop Mac I see them (I see them using all the different host file I tried). It must be software? Sorry for my long text, I won't bother you again.

**Comment by rjhancock** [comment]
If you have Private Relay enabled, it bypasses everything local and will use a remote DNS over local.

`System Preferences -> Network`

If `Limit IP address Tacking` is enabled, Private Relay is enabled.

**Comment by rjhancock** [comment]
Another, and probably better, option on macOS is to use LittleSnitch then subscribe to the hosts lists. Private Relay doesn't effect it (that I know of) and it still offers the same protection that is configurable per network.

**Comment by elcansaito** [comment]
Hi Rjhan,

Thanks a million. I just unchecked the Limit IP and it worked perfectly, no more ads in those pages. 
Really appreciate it.

**Comment by StevenBlack** [comment]
Thanks again for this @rjhancock!

Closing.
