### ISSUE TITLE
Question/Request - replace aag.yahooapis.jp

### ISSUE THREAD

**Issue by hakaishi** [StevenBlack/hosts#1909]
Would it be possible to replace aag.yahooapis.jp in the hosts file with im.c.yimg.jp, or is there any strong reason to keep it even though it breaks a lot of functionalities?

Additionally, blocking s.yimg.jp and gsub.push.yahooapis.jp will also remove a lot of ads. Blocking im.c.yimg.jp will remove commercials.

(Blocking gsub.push.yahooapis.jp might also break certain things. Needs some testing)

Best regards,
Hakaishi

**Comment by StevenBlack** [comment]
Hello Christian @hakaishi thank you for this question.

The domain `aag.yahooapis.jp` comes to us from @tiuxo (https://github.com/tiuxo/hosts/issues) which is one of our upstream curators.  Please submit this request the [issues there](https://github.com/tiuxo/hosts/issues)?  

Thanks!

**Comment by hakaishi** [comment]
Thanks! I'll try and ask there.

**Comment by StevenBlack** [comment]
Closing.
