### ISSUE TITLE
Missing porn site

### ISSUE THREAD

**Issue by AskMeAboutDoom** [StevenBlack/hosts#1915]
Hi. cin.pw is missing from the porn block list.

**Comment by StevenBlack** [comment]
Thank you @AskMeAboutDoom.

Ping @sinfonietta, can you evaluate this for inclusion?

**Comment by 1boii** [comment]
Added in https://github.com/1boii/hosts/commit/1ed8086949c826de5825d449117477a7dfe10f6d

**Comment by Sinfonietta** [comment]
@StevenBlack this domain does not respond for me.

**Comment by Sinfonietta** [comment]
@StevenBlack this domain finally responded.  It's Japanese cartoons...

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta.

Closing.
