### ISSUE TITLE
updateHostsFile.py Issue

### ISSUE THREAD

**Issue by bd-g** [StevenBlack/hosts#1917]
This seems to be associated with the updated readme template and other commits included in the release yesterday. When running updateHostsFile.py, I get the following error right after it asks me if I want to exclude any other domains.

(Edited to keep long directory chains private)
```
Traceback (most recent call last):
  File "updateHostsFile.py", line 1803, in <module>
    main()
  File "updateHostsFile.py", line 304, in main
    update_readme_data(
  File "updateHostsFile.py", line 1245, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

As you can see, using python 3.10, and I  just freshly installed dependencies using the requirements.txt file.

**Comment by StevenBlack** [comment]
Hi @bd-g thank you for raising this.

In our readme, in the [Option 2: Generate it in your own environment](https://github.com/StevenBlack/hosts) section, it's stated that we support Python 3.5 and upwards for that.

Try this with Python 3.5+?

**Comment by StevenBlack** [comment]
@bd-g we require python 3.5, at minimum.

I'm sorry maybe I was unclear about that?  What would you suggest we change in the readme so that's crystal clear?

Here's the [History of Python](https://en.wikipedia.org/wiki/History_of_Python) Wikipedia article. Python 3.1 hasn't been supported for a full decade.  We don't support it either.

**Comment by bd-g** [comment]
Perhaps you misread. I am using python 3.10 (ten), not 3.1 (one). I believe my point still applies.

**Comment by StevenBlack** [comment]
Oh I'm sorry @bd-g that's a fair point and I misread that.

**Comment by StevenBlack** [comment]
Does anybody have input on this?

Works fine with Python 3.9.10, which is what I use.

**Comment by bd-g** [comment]
I can try and debug more to figure it out  when I have time -- just wanted to open the issue as soon as I noticed, even if I didn't have a solution yet

**Comment by XhmikosR** [comment]
It actually works fine on CI with Python >=3.6 on latest Ubuntu, macOS and Windows: https://github.com/StevenBlack/hosts/actions/runs/1983250291

Must be something specific to your system :/

**Comment by funilrys** [comment]
Hallo everyone, just a little tip: Look at the format or LINT of all your JSON files.

That error happens when a JSON file is not correctly formatted. An empty JSON file should actually have the content `{}`.

Stay safe and healthy!

\selfunilrys Reminder: Better handling of this.

**Comment by bd-g** [comment]
Found the problem, stemming from a module dependency specifically for python 3.10 - thanks everyone!
