### ISSUE TITLE
legitimate site blocked: www.catholic.com & go.dynamiccatholic.com

### ISSUE THREAD

**Issue by KK1L** [StevenBlack/hosts#1918]
Neither www.catholic.com nor go.dynamiccatholic.com should be on this list.

Thanks.

**Comment by gothic-bum** [comment]
> [www.catholic.com](http://www.catholic.com)

`www.catholic.com` isn't found in the [list](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts), but `wvw.catholic.com` is. Note the w**V**w.

Details matter.

**Comment by StevenBlack** [comment]
Hi Ron @KK1L thank you for this.

So we're clear, there are no "legitimate" domains here.

It doesn't matter if a domain belongs to the Holy Sisters relict of Mother Theresa of Calcutta. If the domain employs scum practices, or vehicles crapware or worse, they get listed here.

These domains come to us frum upstream, via the AdguardTeam `cname` trackers. These are sites that use their domains (like `wvw.catholic.com`) to serve content from another domain entirely.  Makes it look like it comes from in-house, but it doesn't.  That's not cool here.

The AdguardTeam `cname` trackers issues are here: https://github.com/AdguardTeam/cname-trackers/issues.  Good luck with that. I'm predicting this isn't going to change.

**Comment by StevenBlack** [comment]
Closing.
