### ISSUE TITLE
More dirty sites

### ISSUE THREAD

**Issue by AskMeAboutDoom** [StevenBlack/hosts#1926]
ssdm.me
hentaihub.se
ko.hentai.desi
jp.hentai.desi
acg-manhua.com
hentaidock.com
rokuhentai.com
doujinshi.fans
tvtty300.com
m.nyaal.com
mantiantang521.buzz
re-hentai.com
ko.hentai-img.com

**Comment by StevenBlack** [comment]
Ping @sinfonietta thanks!

**Comment by Sinfonietta** [comment]
@StevenBlack these appear to be all Hentai.  I'm unsure and not convinced about blocking art in my porn list.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta whatever you decide is fine with me.

Closing.
