### ISSUE TITLE
false positive t.stripe.com

### ISSUE THREAD

**Issue by jameskimmel** [StevenBlack/hosts#1928]
t.stripe.com is not porn but a payment provider.

**Comment by StevenBlack** [comment]
Hi James @jameskimmel thank you for this.

So we're clear, there are no "legitimate" domains here.

It doesn't matter if a domain belongs to the Holy Sisters relict of Mother Theresa of Calcutta. If the domain employs scum practices, or vehicles crapware or worse, they get listed here.

That said, the domain `t.stripe.com` comes to us from upstream via the [shady-hosts list](https://github.com/shreyasminocha/shady-hosts/issues). Shreyas @shreyasminocha can I ask you to please look at this one?  Thanks.

**Comment by jameskimmel** [comment]
Hi @StevenBlack 

Not sure what you mean exactly. 

Stripe.com is a payment company that has nothing to with porn or crapware. Stripe is huge, that is why falsely blocking them has big negative impact..

**Comment by jameskimmel** [comment]
There seems to be a language barrier. No it is not clear. 
I don't understand why it is on the blocklist. 
I don't understand why you are trying to say with the Mother Theresa stuff either.

But it seems that my contribution is not wanted here.

**Comment by StevenBlack** [comment]
James @jameskimmel you know what else is "huge"?  Google. We block a whole lot of Google here.  

We also block parts of Facebook, Amazon, Microsoft, Twitter, Netflix, Disney, ...

It doesn't fucking matter who owns the domain.  If the domain employs scum practices, or vehicles crapware or worse, they get listed here.

This is not hard to understand for most people.

**Comment by jameskimmel** [comment]
I still don't get what you are trying to achieve by blocking t.stripe.com.
Maybe there was a fake shop at that domain some time ago. 
That shop could just switch to b.stripe.com and evict your list or a new sincere shop opens up and is wrongfully on your list. 

Maybe you can enlighten me?

**Comment by StevenBlack** [comment]
James @jameskimmel please consult the [readme](https://github.com/StevenBlack/hosts/blob/master/readme.md) first.  I'm happy to answer any questions you may have, but only after you've got some understanding of what we do here.  We've been doing this a long, long time.
