### ISSUE TITLE
Paramount Plus blocked on adware+malware

### ISSUE THREAD

**Issue by BlohoJo** [StevenBlack/hosts#1929]
Recently, the following was added to the [adware+malware blocklist:](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts)

```
# [cbsaavideo.com]
0.0.0.0 vod-gcs-cedexis.cbsaavideo.com
```

This effectively blocks all video playback on Paramount Plus.

I use this list in Adguard to try to block ads and malware, not entire video streaming services.

**Comment by StevenBlack** [comment]
Thanks for this @BlohoJo.

This come to us via the Adaway list, so it originates upstream.  @jawz101 what are your thoughts? Thank you as always.

**Comment by jawz101** [comment]
I removed it the next day

**Comment by StevenBlack** [comment]
Thanks @jawz101.

@BlohoJo this will go live in the next release, due shortly.

Closing.
