### ISSUE TITLE
Bad name error

### ISSUE THREAD

**Issue by ar51an** [StevenBlack/hosts#1930]
There are 4 entries in host file that dnsmasq reports as bad name:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

0.0.0.0 27--01bbcpolice.powercoremedia.com
0.0.0.0 27--m01police.55fifayellow.com
0.0.0.0 www.27--01bbcpolice.powercoremedia.com
0.0.0.0 www.27--m01police.55fifayellow.com

**Comment by StevenBlack** [comment]
Hi @ar51an thank you for this.

The following bash command...

```
domains=(27--01bbcpolice.powercoremedia.com 27--m01police.55fifayellow.com www.27--01bbcpolice.powercoremedia.com www.27--m01police.55fifayellow.com)
for i in "${domains[@]}"
do
   dig "$i"
done
```

Yields this insight (edited for brevity)

```
;; ANSWER SECTION:
27--01bbcpolice.powercoremedia.com. 1798 IN CNAME test-1051022712.eu-central-1.elb.amazonaws.com.
test-1051022712.eu-central-1.elb.amazonaws.com.	59 IN A	18.157.65.30

;; ANSWER SECTION:
www.27--01bbcpolice.powercoremedia.com.	1573 IN	CNAME test-1051022712.eu-central-1.elb.amazonaws.com.
test-1051022712.eu-central-1.elb.amazonaws.com.	49 IN A	18.157.65.30
```

So two of those are no "bad names" because they actually resolve as `CNAME` mappings.

```
27--01bbcpolice.powercoremedia.com. ➡️ test-1051022712.eu-central-1.elb.amazonaws.com.	49 IN A	18.157.65.30
www.27--01bbcpolice.powercoremedia.com. ➡️ test-1051022712.eu-central-1.elb.amazonaws.com.	49 IN A	18.157.65.30
```

So I'm not trusting what dsnmasq reports.
