### ISSUE TITLE
Just a few more pron sites

### ISSUE THREAD

**Issue by calebvisage** [StevenBlack/hosts#1931]
deepfakepornvideos.com/
deepfakeporn.net/
deepfucks.com/
celebritysex.co/
deepfake-porn.com/
pornbest.pro/
pornhd.josex.net/

_PS: Thank you for your work_

**Comment by StevenBlack** [comment]
Thanks Caleb @calebvisage 

Ping @sinfonietta, add these to your list?

**Comment by Sinfonietta** [comment]
@StevenBlack @calebvisage I have added these

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta. Closing.
