### ISSUE TITLE
New Hosts Repo: Illegal Mod Sites

### ISSUE THREAD

**Issue by a2937** [StevenBlack/hosts#1933]
There's a Github repository/website that is keeping track of which websites are distributing illegal/malware-infested mods for various games. Can you add that the list to the unified hosts? 

[Hosts file](https://api.stopmodreposts.org/hosts.txt) 

[Github repository where everything is updated](https://github.com/StopModReposts/Illegal-Mod-Sites)

**Comment by StevenBlack** [comment]
Thank you for this suggestion Aaron @a2937.

Using [ghosts](https://github.com/StevenBlack/ghosts) to assess (see below).

This would add 1,052 domains with no overlap, which is interesting.

```
$ ghosts -c https://api.stopmodreposts.org/hosts.txt

----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 132,576
Bytes: 4.6 MB
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://api.stopmodreposts.org/hosts.txt
Domains: 1,052
Bytes: 30 kB
Intersection: 0 domains
```

**Comment by a2937** [comment]
Certain sites redistributing mods are known to contain malware. There are 58 websites listed just for the Minecraft one. 

 [Link to Evidence](https://github.com/StopModReposts/Illegal-Mod-Sites/blob/master/lists/minecraft.yaml)

![Screenshot of page](https://i.imgur.com/PG8K1Po.png)

**Comment by a2937** [comment]
As this repo's mission was to protect against malware, I believed it would be ideal to add it to the unified lists.

**Comment by StevenBlack** [comment]
You see though Aaron @a2937, that's not what the repo's readme says.

You may be right that a secondary concern of that repo is malware related to Minecraft, and that's good and fine.

But we're not in the business of carrying domains that distribute unauthorized mods related to Minecraft. I don't want to add 1,500 domains trusting that a few are generally concordant with our aims.

I'm really into hot sources that are very closely aligned with what we want to do. We really can't be policing communities.

THAT SAID you know you can fork out Hosts repo and extend it for your specific use case? You can then offer that to the Minecraft community, and staying synchronized with future evolution here is easy. The licensing of this repo permits you to create and maintain derivative works, and that's all-good!

**Comment by StevenBlack** [comment]
Closing.
