### ISSUE TITLE
clefspeare13/pornhosts not being updated regularly?

### ISSUE THREAD

**Issue by thomasmerz** [StevenBlack/hosts#1934]
Hi @StevenBlack ,

it looks to me that https://mypdns.org/clefspeare13/pornhosts/-/tree/master/download_here/0.0.0.0 is 1 day old, but https://github.com/StevenBlack/hosts/tree/master/extensions/porn/clefspeare13 is 5 months old.

Shouldn't your copy being updated regularly?
Am I wrong or is your really copy really much too old?

Kind regards!

**Comment by StevenBlack** [comment]
Hi Thomas @thomasmerz thank you for this. I am aware that our cached copy of Clefspeare's repo is aging.  It's not likely that I'll include this version because it appears to be mostlt bot-curated, and for other reasons I won't elaborate at this time.

Closing.
