### ISSUE TITLE
Problem with host file

### ISSUE THREAD

**Issue by przemeg25** [StevenBlack/hosts#1936]
Hi everyone. I wanted to block the porn sites using the host file so I opened the notepad as an administrator, copied **the whole text** from this link https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts and saved it in C:\Windows\System32\drivers\etc as hosts file. Now I cannot enter any site at all and the Internet connection seems not to be working at all. If I want to change this HOSTS file back into the blank file it says that I cannot access this file as some other process is currently using it. I restarted the system but the problem still appears. I hope you can help me.

**Comment by StevenBlack** [comment]
Closing.
