### ISSUE TITLE
Blocking Apple Wallet provider

### ISSUE THREAD

**Issue by cwanja** [StevenBlack/hosts#1937]
Hello,

Today I discovered that `wallet-api.urbanairship.com` is included in a block list and it is preventing "Add to Apple Wallet" functionality. Recommended to whitelist this domain or can it be removed?

Identified in:
`https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts`

Thanks.

**Comment by StevenBlack** [comment]
Hi @cwanja thank you for this.

"...preventing "Add to Apple Wallet" functionality..." what, and where, exactly?  Also, you can't mess with hosts files on iOS so it's doubly unclear what you mean.

We need a much better sense of the issue before elevating this.

**Comment by cwanja** [comment]
Sorry for not much more detailed. Let me clarify. 

Southwest iOS app has an ‘Add to Apple Wallet’ functionality for boarding passes. That functionality calls the URL provided. Not using the local hosts files on iOS, my iPhones DNS servers are a Pi-hole on my LAN with one of my block lists being pulled from this repo. 

While on WiFi, Pi-hole logs show the references domain being blocked when trying to click on the Apple Wallet functionality in Southwest iOS app. No pass opens up. 

When on cellular, functionality works fine in iOS app and able to load the boarding pass as an Apple Wallet card.

**Comment by StevenBlack** [comment]
Yes @cwanja that helps a lot.  

@jawz101 what do you think?

**Comment by jawz101** [comment]
Removed.  Thank you

**Comment by StevenBlack** [comment]
Thank you as always @jawz101!

**Comment by StevenBlack** [comment]
@cwanja this will be reflected in the next release, coming shortly.
