### ISSUE TITLE
Was told to report these here by adaway team

### ISSUE THREAD

**Issue by derpyderpaderp** [StevenBlack/hosts#1938]
I was told by someone on the adaway team that I should report this here. 

An app I use called Ifunny has ads that are not being blocked anymore by any adblockers used and someone found a way to block them blocking these links here https://raw.githubusercontent.com/CapedCrusader42/IfunnyAdBlocker/main/IfunnyAdblock 

I have tested them and they are confirmed working when adding them in the blocklist in the app blockada. 

Can you please add these to the list of blocks so I can again just use privateDNS? Thank you for all you do.

**Comment by StevenBlack** [comment]
Thank you for this @derpyderpaderp.

Using [ghosts](https://github.com/StevenBlack/ghosts) to compare, we already carry 40 of the 65 domains in that list.

Therefore we would carry 25 new domains so you can use *Ifunny* without ads? I don't think so.

Can you narrow that down a little?

For example, no way I'm blocking `2.us.pool.ntp.org`. See http://ntp.org/ for more info. This could break the internet for a lot of people.

I'm willing to do something realistic, but not something really dumb 😄 

Good?


```
$ ghosts -c https://raw.githubusercontent.com/CapedCrusader42/IfunnyAdBlocker/main/IfunnyAdblock -unique
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 109,598
Bytes: 3.5 MB
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/CapedCrusader42/IfunnyAdBlocker/main/IfunnyAdblock
Domains: 65
Bytes: 1.4 kB
Intersection: 40 domains
----------------------------------------
Unique in comparison list —  25 domains [
    2.us.pool.ntp.org
    brahe.apptimize.com
    cdn.bidmatrixdsp.com
    crpr.trckswrm.com
    dns.msftncsi.com
    e.reddit.com
    edge-mqtt.facebook.com
    events.ifunny.co
    firebase-settings.crashlytics.com
    firebaselogging-pa.googleapis.com
    in.appcenter.ms
    inapps.appflyer.com
    ipv6.msftconnecttest.com
    logs.ifunny.co
    md-a-c.apptimize.com
    mtalk.google.com
    pagead.googlesyndication.com
    prebid-cache.ifunny.co
    prebid.ifunny.co
    prebids.adnsx.com
    service.cmp.oath.com
    smadex.com
    us-trk.bidmatrixdsp.com
    usnotice.wofdsp.com
    woobids.com
]
```

**Comment by derpyderpaderp** [comment]
I am not the one who made the list and I am not sure how they got these as the host files, I am just taking advice from someone from the adaway github and they told me to report them here to have a broader outreach. I don't even know where to look when it comes to this stuff so I wouldn't know what to narrow down and what could potentially break what.

So instead of trying to help I will just close it before I make myself look even more like an idiot. Thank you for your time anyways.

**Comment by StevenBlack** [comment]
@derpyderpaderp it wasn't my intent to make you appear in less than good light. I'm sorry if that's how it came across.

I just need a realistic list of domains to add.  One that doesn't include `2.us.pool.ntp.org` for example.  

I don't need to include a whole list, just a contracted list of domains that I could add to an existing list.
