### ISSUE TITLE
azure.com being blocked

### ISSUE THREAD

**Issue by cryptocryptocryptocrypto** [StevenBlack/hosts#1940]
The following domain is causing many false positives and I'd recommend it be removed from the block list.

azure.com

Additionally, the list of top level domains used by Azure in the link below should be removed and if there is intel on a more specific domain then that should only be added:

https://docs.microsoft.com/en-us/azure/security/fundamentals/azure-domains

Thank you.

**Comment by StevenBlack** [comment]
Hello @cryptocryptocryptocrypto thank you for this.

We don't block any `azure.com` domain or subdomain.

Closing.
