### ISSUE TITLE
Unified hosts = (adware + malware) incorrectly blocks video content at dziendobry.tvn.pl

### ISSUE THREAD

**Issue by jed84** [StevenBlack/hosts#1941]
Unified hosts = (adware + malware)
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
incorrectly blocks video content at https://dziendobry.tvn.pl/ and other websites

Example:
https://dziendobry.tvn.pl/gwiazdy/klaudiusz-sevkovic-z-pierwszej-edycji-programu-big-brother-swietuje-51-urodziny-5428788

This occurs as:
0.0.0.0 prodxnews1blob.blob.core.windows.net 
being incorrectly blocked

This should be whitelisted:
@@||prodxnews1blob.blob.core.windows.net^$script

**Comment by StevenBlack** [comment]
Hello @jed84 thank you for this.

The domain `prodxnews1blob.blob.core.windows.net` comes to us from upstream via someonewhocares.org. Please send an email to Dan Pollock at hosts@someonewhocares.org to urge him to reconsider.

**Comment by jed84** [comment]
@StevenBlack The domain is now removed from https://someonewhocares.org/hosts/
