### ISSUE TITLE
Why are byet/ifastnet services blocked?

### ISSUE THREAD

**Issue by shruuub** [StevenBlack/hosts#1943]
Hello.
Thanks for this Blacklist. But why are the services provided by byet.org blocked? Sure, their practices may not be everyones favorite, but as far as I'm concerned they arent doing any harm.

**Comment by StevenBlack** [comment]
Hello @shruuub thank you for this.

This issue comes from upstream, via mvps.org.

You can make your case for removal by sending an email to winhelp2002@gmail.com

Closing.
