### ISSUE TITLE
okx.com

### ISSUE THREAD

**Issue by merganon** [StevenBlack/hosts#1945]
Hey Steven,

I saw that okx.com was added to the unified hosts list, however I don't see any issue or pull request where OKX was suggested to be added. It seems like it was added manually.

OKX is a cryptocurrency exchange. What's the reason to have it in the list?

Note: I am not affiliated with OKX. I just care about non-opinionated filter lists.

Thank you for your work by the way!

**Comment by merganon** [comment]
Thank you for your work by the way!

**Comment by StevenBlack** [comment]
Hello @merganon thank you for this.

The domain `okx.com` comes to us from upstream, via the [KADhosts list](https://github.com/FiltersHeroes/KADhosts/issues).

Can you submit this to their Issues page? https://github.com/PolishFiltersTeam/KADhosts/issues

Ping @krystian3w can you assess the inclusion of domain `okx.com`?

**Comment by krystian3w** [comment]
In Poland can buy dangerous use:

https://forexrev.pl/ostrzezenia-4-04-fincloud-cryptobull-nexfx/

**Comment by StevenBlack** [comment]
Thank you @krystian3w.

Whatever you decide is fine with me.

Closing.

**Comment by merganon** [comment]
This sounds like a Poland-only issue. @StevenBlack 's hosts are used by people worldwide.

It looks like KADhosts is focused on Polish users - why is this included in the unified hosts list? I suggest we branch out to different countries/languages, just like EasyList has filters for different countries.

**Comment by StevenBlack** [comment]
@merganon I beg your pardon?

What an insulting, arrogant comment.

Yeah @merganon, you do that. Fill your boots.  Now go away.

**Comment by merganon** [comment]
I think you misunderstood me.

There is a reason why EasyList has decided to create different filters for German, Spanish, Chinese, Slovenian, etc. people. because it could create false positives, just how it happens with okx.com at the moment.

**Comment by StevenBlack** [comment]
@merganon I can tell you with confidence: my list is not for you.

I trust you understand that.

Now please, go away, or I will block you.

**Comment by merganon** [comment]
Yes, I understand you now. I just had a glance and it seems like KADhosts is heavily opinionated, they are blocking lots of crypto-related pages. Leaving it here so others know to avoid using your hosts if you are calling KADhosts "reputable".

![image](https://user-images.githubusercontent.com/74573436/163075433-15cea5b7-57cb-44ce-9034-47cf9152db79.png)

https://github.com/FiltersHeroes/KADhosts/issues/14

**Comment by StevenBlack** [comment]
Sorry for all this @krystian3w. I have blocked this repugnant asshole.

I know that nobody works harder than you guys. Nobody is more diligent and reliable than the maintainers of KADhosts.  Not just recently, but consistently, over many, many years.

@krystian3w I asked you for comment, and you replied promptly, with documentation.  You are a ⭐ and I apologize for all of this. You deserve better. Thank you for all you guys do.

I am locking this issue now.
