### ISSUE TITLE
ms4.applovin.com not blocked. Can see Ads on Reddit Sync Android app

### ISSUE THREAD

**Issue by C0dDex** [StevenBlack/hosts#1946]
Please add following domain. 
`ms4.applovin.com`

or  main domain `applovin.com`

**Comment by StevenBlack** [comment]
Thank you for this @C0dDex.

@jawz101 I see you're carrying many `applovin.com` domains already. Would you carry this one too?

@C0dDex if @jawz101 decides to carry this domain, you'll see it listed in an upcoming release soon.

**Comment by jawz101** [comment]
added.  thanks!

**Comment by StevenBlack** [comment]
Thanks @jawz101!

@C0dDex this addition will land in the next release.  Thank you for the suggestion.

Closing.

**Comment by C0dDex** [comment]
Thank you

**Comment by C0dDex** [comment]
assets.applovin.com
pdn.applovin.com
prod-a.applovin.com
prod-ms.applovin.com

new sub domains. please block.

@StevenBlack
@@jawz101

**Comment by StevenBlack** [comment]
@C0dDex we already list these domains.

You probably need to flush
* your OS DNS cache
* your browser cache.
