### ISSUE TITLE
remove okx.com from blacklist

### ISSUE THREAD

**Issue by nevesigor** [StevenBlack/hosts#1948]
Please remove www.okx.com and okx.com, it's just one crypto exchange as any other online.

**Comment by StevenBlack** [comment]
Hello @nevesigor thank you for this.

This was recently discussed in Issue #1945. The domain `okx.com` comes to us from upstream, via the KADhosts list. Maintainers there are aware of this request about the `okx.com` domain, and I leave the decision in their capable hands.

Closing.
