### ISSUE TITLE
Porn list blocks 4chan

### ISSUE THREAD

**Issue by trollogyadherent** [StevenBlack/hosts#1950]
Hello, 4chan can be used to browse a whole lot of things that are not porn (contained to specific boards). I don't know if these hosts policy is "any porn on domain -> block", but if not, please consider removing 4chan.org and a couple other affected domains.

**Comment by StevenBlack** [comment]
Hi @trollogyadherent thank you for this.

Unfortunately hosts files work only at the domain-level. So it's an all or nothing thing.

Thanks for the troll! 

Closing.
