### ISSUE TITLE
Need help to block youjizz's backend video server and also a possible solution

### ISSUE THREAD

**Issue by defa02005** [StevenBlack/hosts#1953]
Quoting initially from #1952 
"I've been using the list with ublock origin. I observed that for almost all porn sites, even temporarily unblocking doesn't open the site and it shows broken links, at times no images, because some great people have also blocked some core component in the porn sites, which I'm not sure of.

[youjizz.com](https://youjizz.com), however is an exception since clicking on a video actually plays it, and I realize we'll need to block the backend as well. I suggest possibly adding "abre-videos.cdn1122.com" to the list of blocked sites, but I'm not fully sure if there's a better solution or not.

Please help, otherwise add it to the list of blocked sites"

More details:

- How a blocked site shows up when I try to open the page: 
<img width="946" alt="image" src="https://user-images.githubusercontent.com/87270290/164757172-817b8b3b-d986-4acb-ab83-136c1213e90b.png">

- How it appears after clicking temporarily unblocking: 
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/87270290/164757326-ead344ff-cd13-44f0-a1bf-8f8b4c1dbc4f.png">
As you can see that the site looks kind of broken, and the videos can't be played. Which in my opinion, is a good thing. I think it has to with filters like cdn-xvideos, etc. in the porn list. This is true for most of the sites. However, some sites still load completely on clicking temporarily. For eg: 

1. [ftvgirls.com](https://ftvgirls.com)
2. [ftvhunter.com](https://ftvhunter.com), etc.

- In case of youjizz, the home page looks like this after clicking temporarily: 
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/87270290/164757672-d0dd288b-2d70-4c2e-9fc2-505d183467cb.png">
Although, there are no thumbhnails showing up on videos, on clicking the video, it still plays correctly. 

This is the behavior I was trying to look into. On viewing page source, I could see that the video links were being loaded from cdn on youjizz, and also the photos on the ftv sites were being loaded from another cdn thing. 

If I add "abre-videos.cdn1122.com" for youjizz in ublock, then the videos also don't play. This is what I was trying to dig deep into. There are many cdn links in the porn hosts file as well, which I believe are causing a behavior that allows porn to remain blocked even after clicking temporarily for unblocking. I've find it really helpful, which is why I was trying to understand it and also block it for other sites.

If you approve of this, I can add it for a few sites which I know can be fully temporarily unblocked. The only thing is that I don't have a complete knowledge of it, and was looking for opinions. A way to do it is to open the console in the browser and look at the video url, or do that from the page source.

**Comment by StevenBlack** [comment]
@defa02005 thank you for this.

Please don't open new issues for directly related subjects.

I think you need to clear your browser cache, your DNS cache, or both.

Using the porn extension, nothing related to youjizz shows up at all.  All this is working as expected.

Closing.

**Comment by defa02005** [comment]
Thanks @StevenBlack, and sorry for this. I actually thought I'd add more info and maybe reopen so you can take a look, but it didn't show any option to reopen the issue, which is why I created the new one. Thanks for what you suggested, I'll maybe try on some other device some time later.
