### ISSUE TITLE
YouTube app history not being recorded.

### ISSUE THREAD

**Issue by iambeingtracked** [StevenBlack/hosts#1958]
I use pi-hole, which by default ships with this filterlist. Recently, I've noticed that in the youtube app for freebsd (ios i meant) doesn't properly record history. It may record some videos, but not all. Which filter may be causing this?

**Comment by StevenBlack** [comment]
Hi @iambeingtracked this issue has come up before, notably

* #1379 
* #1862 

... and some others.

YouTube uses this domain for multiple purposes, including ads, and we decided to continue blocking this.

**Comment by noXi89** [comment]
IMHO this it's a bad decision to block important features. A lot of people have this issue, not knowing that pihole is the problem.
