### ISSUE TITLE
mobile ad networks, analytics, tracking

### ISSUE THREAD

**Issue by jawz101** [StevenBlack/hosts#196]
I was wondering if some of these domains might make the list.  I cannot find them on any of the typical blocklists out there but I see them constantly on my phone via NetGuard logs.

These just came from DNS requests from Lastpass, Netflix, Runtastic, Avast! antivirus, YouTube and a few other apps on my phone

med.heyzap.com
www.googleadservices.com
www.googletagmanager.com
secure.insightexpressai.com
169.54.33.154 *.36a9.ip4.static.sl-reverse.com    (mixpanel.com analytics)
a.fiksu.com
api.segment.io
cdn.segment.com
dc.services.visualstudio.com    (Visual Studio analytics)
e.crashlytics.com    (found in many apps)
settings.crashlytics.com
mobile-service.segment.com
analytics-prod-ingress.bricknet.com
tags.otherlevels.com
admin.brightcove.com
app.adjust.com
fonts.googleapis.com
brahe.apptimize.com
md-a-c.apptimize.com
appload.ingest.crittercism.com
s.amazon-adsystem.com
device-metrics-us-2.amazon.com
14716.engine.mobileapptracking.com
stats.appsflyer.com
t.appsflyer.com
t.singular.net
control.kochava.com

**Comment by Atavic** [comment]
Those Softlayer _static.sl-reverse.com_ connections could come from Avast or others and are definitely tracking the user.

**Comment by StevenBlack** [comment]
So... the way this repo works is, we aggregate actively curated lists of hosts that are involved, one way or another, in bad activity.

Maybe you could suggest these hosts to an organization that actively curates these lists?

If you would like to actively start curating a lists of hosts, then I'd be happy to include what you've got.

Closing.
