### ISSUE TITLE
Add to list

### ISSUE THREAD

**Issue by black-cerberon** [StevenBlack/hosts#1963]
Ads, BigData and RTB
```
bs.serving-sys.com
bs.serving-sys.ru
match.new-programmatic.com
mitdmp.whiteboxdigital.ru
sync.upravel.com
tech.rtb.mts.ru
```
suspect:
```
s.uuidksinc.net
sync.bumlam.com
```

**Comment by StevenBlack** [comment]
Hello @black-cerberon thank you for this.

We already list domains `bs.serving-sys.com` and `sync.upravel.com`.

As for the others, you provide no reasons to list them, so I respectfully decline.

Closing.
