### ISSUE TITLE
More CNAME cloacking domains for your list

### ISSUE THREAD

**Issue by ammnt** [StevenBlack/hosts#1964]
Hello, sir!

Thank you for your awesome project!👋🏼 Please consider adding these CNAME cloacking hosts to your list:
[cnames.txt](https://github.com/StevenBlack/hosts/files/8601767/cnames.txt)

I hope it will be useful😋

Thank you.
Best regards.

**Comment by StevenBlack** [comment]
Hello @ammnt thank you for this.  I'll only entertain carrying lists with a track record of active curation.

We already list most of the items in the list you provide...

Closing.
