### ISSUE TITLE
Add malicious Ads from Asia Porn Website

### ISSUE THREAD

**Issue by Nathan9745354** [StevenBlack/hosts#1967]
Hi , I discovered most of 90% porn ads were blocked by the host list but some are missing.

Website: 
https://avgle.com/
https://netflav.com
https://jable.tv/

Domain:
0.0.0.0 cdn.ggsfq.com
0.0.0.0 adserve.work
0.0.0.0 lammasbananas.com
0.0.0.0 creative.xlviirdr.com
0.0.0.0 go.xlviirdr.com
0.0.0.0 ads.adxadserv.com
0.0.0.0 go.xxxjmp.com
0.0.0.0 creative.xxxjmp.com
0.0.0.0 adxadserv.com
0.0.0.0 cdn.ggsfq.com

**Comment by StevenBlack** [comment]
Thank you for this Nathan @Nathan9745354.

Ping @sinfonietta, can you look at these please?

Nathan @Nathan9745354 @sinfonietta is one of our porn extension curators, so he'll evaluate these.

**Comment by Nathan9745354** [comment]
Hi StevenBlack,

I am spending a time for find out porn ads of domain and keep update to this post.

Thank you.

**Comment by Nathan9745354** [comment]
> Thank you for this Nathan @Nathan9745354.
> 
> Ping @Sinfonietta, can you look at these please?
> 
> Nathan @Nathan9745354 @Sinfonietta is one of our porn extension curators, so he'll evaluate these.

@StevenBlack @Sinfonietta

HI all , 

It's seen still not update domain of Ads and Malware list.

Please help to check.

**Comment by StevenBlack** [comment]
Nathan @Nathan9745354 I'm sure @sinfonietta will get to this soon.

Note that @sinfonietta's porn hosts are NOT included in our base list. The porn extension, which includes @sinfonietta's porn hosts, is active in variants that include porn.

**Comment by Sinfonietta** [comment]
@StevenBlack I have added these.

**Comment by Nathan9745354** [comment]
Hi @ StevenBlack ,

Can you consider add those domain to Ads+Malware? Because this is ads domain and porns are just one of those ads.

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta.

Closing.
