### ISSUE TITLE
Twitter links broken

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#1968]
The pgl.yoyo.org ad server list (which we're sourcing for this list) has just added "t.co" to their block list.

https://pgl.yoyo.org/adservers/serverlist.php?hostformat=nohtml

All Twitter links go through this redirection URL, so it makes Twitter partially unusable. I first contacted the maintainer of that upstream list to get it removed, but was told "it's a bounce tracker" so it would be left there intentionally.

For practical purposes, we either need to whitelist that domain in the generation scripts, or stop pulling from yoyo.org altogether.

**Comment by StevenBlack** [comment]
Hi Devon @hyder365 I am aware.

I've paused fetching form `yoyo.org` at a version prior to the addition of `t.co`.

See commits 0677b534b17005943694c869426ca3b97bd0a46b and 0f8ad83645bcecedf980bd682fb77d5c18410ce1.

I have no intention of blocking general-use URL shorteners at this time.  I prefer to block the targets of these shortened URLs.
