### ISSUE TITLE
Add Overwolf tracking

### ISSUE THREAD

**Issue by icedterminal** [StevenBlack/hosts#1970]
Captured from Fiddler.

```
0.0.0.0 tracking.overwolf.com
0.0.0.0 analyticsnew.overwolf.com
0.0.0.0 raf.overwolf.com
```

- `tracking` is self explanatory.
- `analyticsnew` is aggressive in nature and records a users *every click* within the software UI.
- `raf` unsure of what it does entirely but includes tracking. I think it means "Recruit a Friend."

**Comment by StevenBlack** [comment]
Thank you for these @icedterminal. I've added these in commit fb1b7a1c. This will reflect in the next release, coming shortly.

Closing.
