### ISSUE TITLE
Add gambling website: freeslotshub.com

### ISSUE THREAD

**Issue by a2937** [StevenBlack/hosts#1972]
Website : www.freeslotshub.com

It seems like a bunch of gambling websites point to this one.

**Comment by Sinfonietta** [comment]
@StevenBlack I have added this to my gambling list.

**Comment by Lateralus138** [comment]
I stepped in cat poop some how and got it in the carpet and have no idea how to get it out

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta closing now.
