### ISSUE TITLE
dirtyshack.com

### ISSUE THREAD

**Issue by ScatPornEnthusiast** [StevenBlack/hosts#1975]
I love scat porn. I was wondering why it wouldn't load. Turns out it's blocked. 

There are lots of ads on these poop fetish sites that aren't popular enough to be blocked. 

Would be great not to block the porn just the ads.

**Comment by StevenBlack** [comment]
> There are lots of ads on these poop fetish sites that aren't popular enough to be blocked.

@ScatPornEnthusiast what makes you say that?  There's no "popularity" threshold for ad serving domains.  🤷🏻 

I'm gonna need specific ad domains to block...

**Comment by moralground** [comment]
What the fuck

**Comment by StevenBlack** [comment]
Jeremy @moralground I know, right?

**Comment by ScatPornEnthusiast** [comment]
There's to many to ad domains to count I've been blocking them 1 by 1 myself. I didn't realize they were the same afs on each site i don't really visit those sites unless I'm doing the dead.
