### ISSUE TITLE
Opera browser ads/tracking

### ISSUE THREAD

**Issue by JobcenterTycoon** [StevenBlack/hosts#1984]
Hello, i have a interesting behavior with the Opera Browser i tested:

After i started Opera it connect to 2 domains:

`speeddials.opera.com`
`merchandise.opera-api.com`

The DNS logger also show 3 CNAME domains

`speeddials.geo.opera.com`
`ams-speeddials.opera.com`
`am4-speeddials.opera.com`

While searching i saw the second domain clearly get used for ads, see `https://forums.opera.com/topic/36540/merchandise-opera-api-com`

The first domain seems to be a ad and tracking domain, see `https://www.kuketz-blog.de/opera-datensendeverhalten-desktop-version-browser-check-teil13/` and `https://www.netmeister.org/blog/browser-startup.html` also domains get send to `speeddials.opera.com`

<details>
<summary> screenshot </summary>

<img width="932" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/174500526-fa25b6ef-eedf-447c-bc54-8324b996072c.PNG">

</details>

Im not sure if `speeddials.opera.com` only get used for ads/tracking or if it have other purposes too. I tested a bit and removed all sites from the front page and added a few own one. Opera connect to the site directly to fetch the icons

Please take a look

**Comment by StevenBlack** [comment]
Thank you for your observation @JobcenterTycoon.

I'm struggling to uncover, what are you asking of us here?  Can you frame this as a specific issue, a specific question, and not as above ⬆️⬆️⬆️ which is a narrative of, well, I don't know.

**Comment by JobcenterTycoon** [comment]
> I'm struggling to uncover, what are you asking of us here?

Can you add `speeddials.opera.com` and `merchandise.opera-api.com` to the blocklist?

**Comment by StevenBlack** [comment]
Thanks @JobcenterTycoon, done!

Closing.
