### ISSUE TITLE
More eBay blocks

### ISSUE THREAD

**Issue by Redback813** [StevenBlack/hosts#1985]
backstory.ebay.com.au
devicebind.ebay.com.au
edgetrksvc.ebay.com.au
srv.au.ebayrtm.com
pulsar.ebay.com.au
ir.ebaystatic.cn
ir.ebaystatic.com

Cheer's

**Comment by StevenBlack** [comment]
Thank you for this @Redback813.

Why would we want to block these particular eBay domains?

**Comment by StevenBlack** [comment]
@Redback813 I need to know, *why* would we block these domains? I need reasons, enumerated.

**Comment by Redback813** [comment]
It all about trackers on both the mobile and desktop.

**Comment by StevenBlack** [comment]
Thank you @Redback813. I have decided to decline.

Thank you for this suggestion!
