### ISSUE TITLE
high cpu usage every 30 seconds (ONLY WITH INTERNET ACTIVE)

### ISSUE THREAD

**Issue by gitrepository97** [StevenBlack/hosts#1988]
is it possible by any means to get high CPU usage spike every 30 seconds because i integrated this hosts file on my PC?

**Comment by StevenBlack** [comment]
Hello @gitrepository97 thank you for your question.

Host file handling is an operating-system specific implementation detail.  Moreover all implementations will be affected by physical constraints, particularly available RAM, and possibly other constraints.

Without information about your rig and it's OS, it's impossible to say.

If you're running Windows on a basic box with limited RAM, then yes. If this is the case, the first thing to try is increase the size of your swap file to help your machine manage shipping volatile memory to and from disk.

**Comment by gitrepository97** [comment]
for everyone encountering this issue: it is caused by the fact that the windows DNS cache service is closed. So make sure to activate it if you want to get rid of the CPU spikes.
