### ISSUE TITLE
link.aclu.org breaks unsubscribe

### ISSUE THREAD

**Issue by DavidCWGA** [StevenBlack/hosts#1990]
Emails from the ACLU include an unsubscribe link that points to link.aclu.org. Since this is in the list, it makes unsubscribing impossible while you use it.

**Comment by StevenBlack** [comment]
Hi David @DavidCWGA I don't see any `aclu.org` links currently in this list. Maybe you mistyped that?

**Comment by DavidCWGA** [comment]
Ah, it's because it's a CNAME for cb.sailthru.com, which is listed.
