### ISSUE TITLE
Add porn sites

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#1992]
Hello @StevenBlack @sinfonetta, may you add the following sites to the porn filter:

cambeauties.com
kawaiifu.com
thothub.is
thothub.su
thethothub.com
fans-here.com
jable.tv
3hentai.net
xxxfree.watch
crockotube.com
maturehits.com
fphentai.com
bestanime3.xyz
redbeeg.com
theporndude.fun
namethatpornad.com
slayed.com
oornag.nu
findhernudes.com
simply-cosplay.com

Thank you for all your work!

**Comment by StevenBlack** [comment]
Thank you @g1t3m.  Ping @sinfonietta!

**Comment by Sinfonietta** [comment]
I have added these too @StevenBlack.

**Comment by StevenBlack** [comment]
@Sinfonietta 👍🏻
