### ISSUE TITLE
An important link is defunct in README

### ISSUE THREAD

**Issue by XploreInfinity** [StevenBlack/hosts#1997]
[This Section](https://github.com/StevenBlack/hosts#warning-using-this-hosts-file-in-windows-may-require-disabling-dns-cache-service) contains the following block of text:
> Use the disable-dnscache-service-win.cmd file to make proper changes to the Windows registry. You will need to reboot your device once that's done. See the [the comments within the cmd file](https://github.com/StevenBlack/hosts/blob/master/disable-dnscache-service-win.cmd) for more details.

The link given in this block is outdated. It needs to be replaced by [this link](https://github.com/StevenBlack/hosts/blob/master/disable-dnscache-service-win.bat)

**Comment by StevenBlack** [comment]
Thank you @XploreInfinity for signalling this!

**Comment by XploreInfinity** [comment]
Happy to help :)

**Comment by StevenBlack** [comment]
Fixed!  Closing.
