### ISSUE TITLE
add this metric.gstatic.com

### ISSUE THREAD

**Issue by holequantum** [StevenBlack/hosts#1998]
2fbb2cdf-dnsotls-ds.metric.gstatic.com
ac0c3f6d-dnsotls-ds.metric.gstatic.com
4faff701-dnsotls-ds.metric.gstatic.com
this type of url android uses for what i don't know but i have manually blocked them and see no other requests can pass through and this does bot block my system function or any issue that i encounter in last 10month or so in all of my devices hope it can be added in core repo.

**Comment by danielchristiancazares** [comment]
This should not be blocked as it *will* cause issues for a subset of Android users. You can view full discussion on https://help.nextdns.io/t/60hz6md/metric-gstatic-com-is-not-blocked-but-it-should-be

**Comment by holequantum** [comment]
Okey thanks
