### ISSUE TITLE
extensions\social\hosts is detected as false positive Win32/Qhost trojan in ESET Smart Security

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#200]
@StevenBlack  FYI

https://forum.eset.com/topic/10047-stevenblacks-hosts-extensionssocialhosts-is-detected-as-false-positive-win32qhost-trojan/

**Comment by StevenBlack** [comment]
Well, that's the point  😄 

To be honest, I'm getting tired of Windows ecosystem bullshit.

**Comment by StevenBlack** [comment]
@FadeMind can you take care of educating there people?

**Comment by FadeMind** [comment]
Only this ONE file (`extensions\social\hosts `) is false positive as Win32/Qhost (due HIPS ESET automatic rules). 
This issue is for information purpose (and educating) for noobs. 
Power users whos using custom hosts will be just ignore this misleading.

**Comment by kronflux** [comment]
onoez, better stop using this trojan!

**Comment by redactedscribe** [comment]
For the past several weeks, Eset has been detecting the hosts files as Win32/Qhost again.
