### ISSUE TITLE
Domains in list break Ring Central app

### ISSUE THREAD

**Issue by smcclosr** [StevenBlack/hosts#2002]
For the web app https://app.ringcentral.com, the following domains need to be removed:

som.ringcentral.com
mpsnare.iesnare.com

from the lists:

master/hosts
master/alternates/fakenews-gambling-porn/hosts

Once they are whitelisted, the site works.

**Comment by jawz101** [comment]
removed.  Looks like iesnare is made by a company called Iovation which is now a subsidiary of [TransUnion](https://www.transunion.com/privacy/iovation).  A product detect fraudulent activity w/ fingerprinting.

**Comment by smcclosr** [comment]
Thanks for the updates,  I will just continue to whitelist them on my side.
