### ISSUE TITLE
Few sites

### ISSUE THREAD

**Issue by Artem13327** [StevenBlack/hosts#2004]
Porn:
xxx-brawl.xyz
brawl-stars-xxx.xyz
Social:
rad.msn.com
Hosts file:
https://github.com/hoshsadiq/adblock-nocoin-list

**Comment by StevenBlack** [comment]
Thank you @Artem13327!

Ping @sinfonietta for inclusion.

**Comment by Sinfonietta** [comment]
@StevenBlack Iadded the porn domains above.

I can't judge the rad.msn.com domain so I did not add this one.

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta all good!  Closing.
