### ISSUE TITLE
LINE news is broken

### ISSUE THREAD

**Issue by a77841s** [StevenBlack/hosts#2005]
URL www.googletagmanager.com is filtered, some news on LINE cannot be browsed.
were you able to fix it?

**Comment by StevenBlack** [comment]
Hi @a77841s this is insufficient info to evaluate.

Try again?

**Comment by FadeMind** [comment]
@StevenBlack @a77841s 
`www.googletagmanager.com`
is used common and sadly it is required for work properly many sites. Many blocklists blocked it. 

https://oisd.nl/excludes.php?w=googletagmanager.com
https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/Filters/exclusions.txt
