### ISSUE TITLE
smart.link is blocked

### ISSUE THREAD

**Issue by humsg** [StevenBlack/hosts#2009]
Can you please unblock smart.link for apple app link that forward the link to apple store?

thank you

**Comment by jawz101** [comment]
I'm hesitant but I dunno.  It's owned by [Kochava](https://www.kochava.com/) which is a tracking company

https://www.kochava.com/smartlinks-just-got-smarter/

https://support.kochava.com/links-overview/creating-and-editing-smartlinks/

and I block all of their other stuff

**Comment by StevenBlack** [comment]
Thanks @jawz101 that's good enough for me.

Closing.
