### ISSUE TITLE
Integrate a list of compromised stores that contain Javascript malware

### ISSUE THREAD

**Issue by kowalcj0** [StevenBlack/hosts#201]
https://gitlab.com/gwillem/public-snippets/snippets/28813

**Comment by StevenBlack** [comment]
@kowalcj0 thanks.  Interesting.  So's the accompanying blog post.

How often is this list updated?  Is it actively curated?

Issue #180 applies here since this list isn't in host file format.

**Comment by StevenBlack** [comment]
I am closing this now since it appears that this source, while interesting, is not actively curated into the future.

**Comment by kowalcj0** [comment]
Hi @StevenBlack 
Sorry but I missed your first response, it looks like the list not abandoned as it was edited on 2017-01-10 11:08:11 UTC
Let's see if the owner would like to contribute to this project.
