### ISSUE TITLE
Add this porn sites, please...

### ISSUE THREAD

**Issue by abbbw** [StevenBlack/hosts#2013]
safadahsh.blogspot.com
chrismarsan.blogspot.com
fabricadecornos.blogspot.com

**Comment by StevenBlack** [comment]
Thank you @abbbw.

Ping @sinfonietta, can you handle these?

**Comment by Sinfonietta** [comment]
@StevenBlack these have been add.

**Comment by StevenBlack** [comment]
Thanks again @Sinfonietta.

Closing.
