### ISSUE TITLE
add these domains to porn category - (new domains + issue #2013 domains + issue #2004 porn domains)

### ISSUE THREAD

**Issue by abbbw** [StevenBlack/hosts#2016]
007zeed.com
3xmuscles.com
4porno.com.br
8hentai.net
acervox.com
acompanhantebrasil.com.br
amadoraslindas.com
amateurporntube.net
american-porno.com
animeshentai.biz
asmaisgatasdoinstagram.blogspot.com
assesphoto.com
assistirhentai.com
b2wblog.com
bananasfamosas.com.br
besiktassu.com
bigbootiez.blogspot.com
boafoda.blog
bondageco.com
brawl-stars-xxx.xyz
bucetas.blog
bucetaspeludas.com.br
caiunanet.ws
callescortgirls.ca
caseirosexo.com
chrismarsan.blogspot.com
cinepornogratis.com
clipvs.net
completeporndatabase.com
contoerotico.com
cooch7.com
cuckoldtube.net
downloadfromxvideos.com
drivebygirls.com
eoquetemprahj.com
escortsaffair.com
fabricadecornos.blogspot.com
fadadosexo.com
famosaspeladasbrasil.blogspot.com
femdomhd.org
fetishfemdom.adult
fikante.com
filmeporno.blog
filmeporno.vlog.br
filmesdesexo.blog
filmesporno.blog
filmesporno.com.br
filmesporno.net.br
findhername.net
fisting.sexy
florenpornfile.com
fotoscaiunanet.com
fotosdebucetas.com
fotosmulherpelada.com
garotaporno.com
gay93.com
gayupornotube.com
gimmedick.com
gostosas.blog
gostosaseamadoras.com
gozadinhas.com
gozarsexo.com
gruposputaria.blog.br
gsexy.com.br
guiaadulto.com
hairypornpic.com
hdxxxpics.com
hentai.pro
hentaib.net
hentaifoda.com
hentaihome.net
hentaikai.com
hentailegendado.com
hentaipro.tv
hentaiteca.net
hihi18.com
homenspeladosbr.com
hotchicks.tv
hotguyspissing.com
hotmusclegay.net
hotspicybrown.com
hotwifecaps.com
hqporno.net
ilhadoporn.com
ilhadoprazer.com.br
incesto.blog.br
instagramlivesbr.blogspot.com
iporno.xxx
japanmasaj.com
juicechan.net
kickin.info
les-lundis-daltor.com
ligadasnovinhas.com
lokolokolokomelo.blogspot.com
lontv.cc
megaporno.com.br
meuscontoseroticos.com
muitomachoman.blogspot.com
mulheresafoder.com
mulheresnofunk.blogspot.com
mundohentaioficial.com
musasdetodosostempos.blogspot.com
musasporno.com
nakedinfluencers.com
netporn.net
nhentaibr.com
nordestinas.com
novinhabucetuda.com
novinhaspeladas.net
nudesdozap.com
oloxablog.com.br
parupr0n.blogspot.com
pecattus.com.br
piriguetes.com
pluck1080porn.com
pocomu.com
porn15s.com
pornmite.blogspot.com
porno16.com
porno18.blog.br
pornobom.com.br
pornocaseiro.vlog.br
pornofiel.com
pornogram.xxx
pornogratis.com.br
pornogratis.tv.br
pornogratis.vlog.br
pornomaneiro.com.br
pornoonline.com.br
pornoprive.xxx
pornoputaria.com
pornorazzo.com
pornosexohd.com
pornosfilmes.com
pornotarado.com
pornotree.com
pornous.net
pornpicsasian.com
prazer360.com.br
princessfemdom.com
putaxvideos.com
quadrinhosdesexo.com
quadrinhoseroticos.com.br
redtub.online
safadahsh.blogspot.com
safadasnaweb.com.br
saltsbr.com.br
sandrinha-lorinha.blogspot.com
scortrio.com
secrethostess.com
seusvideosporno.com
sexflexible.com
sexgai.org
sexindiantube.net
sexo9.com
sexoamador.blog
sexocoroas.com.br
sexogostoso.online
sexonovinha.tk
sexopornogay.com.br
sexosempudor.com
sexvids.co
soamadorasbr.com
socaseiras.com.br
sogatinhas.net
subcuckolds.com
sumosear.ch
superhentai.blog
superhq.com.br
sweetlicious.net
tatarada.com.br
teencurves.com
terceiroz.com
tesudas.net
thehentai.net
tia-tanaka.com
tonsofcock.com
topdebrasilia.com.br
universidadedoprazer.com
vagabundasdoorkut.net
vainovinha.net
videopornosgratis.com.br
videosamadores.blog
videosdesexo.com.br
videosdesexoxxx.blog.br
videosdesuavizinha.com
vipbook.com.br
vlxxx.cc
whornyfilms.com
x-videos.mobi
xhwide2.com
xnudes.net
xnxxvn.org
xoxoteiras.com
xplastic.com.br
xporno.blog
xvideo-sexo.com
xvideo.vlog.br
xvideos.tv.br
xvideos0.biz
xvideosanal.org
xvideosbr.blog
xvideosbr.to
xvideosfoda.com
xvideosgratis.com.br
xvideosincesto.com
xvideosporno.blog.br
xvideosporno.net
xvideosup.com.br
xvideosvip.blog
xvideosxbr.com.br
xvidios.blog.br
xxx-brawl.xyz
xxxbuceta.com.br
xxxfetishclip.com
xxxonlinetube.com
xxxvideos.cz
youngsexparties.com
youpussy.net
zoiofilmesadulto.com

**Comment by StevenBlack** [comment]
Thank you for this @abbbw.

Ping @sinfonietta for inclusion.

**Comment by Sinfonietta** [comment]
@StevenBlack this is added!

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and thank you @abbbw.

Closing.
