### ISSUE TITLE
tongji.baidu.com

### ISSUE THREAD

**Issue by chainofhonor** [StevenBlack/hosts#2019]
tongji.baidu.com

This is not a junk website
This is Baidu's official website

**Comment by StevenBlack** [comment]
Thank you for this @chainofhonor.

Please understand, there are no legitimate domains here. If a domain is used for shady purposes, it gets blocked. It doesn't matter if it's Baidu, Google, or any other organization.

The domain `tongji.baidu.com` comes to us via the list from someonewhocares.org.  Please make your case with Dan Pollock at hosts@someonewhocares.org.

Closing.
