### ISSUE TITLE
Porn URLs and question.

### ISSUE THREAD

**Issue by Jezza-x3** [StevenBlack/hosts#202]
Where are you getting your porn list from? I'm trying to comment some porn sites that aren't blocked.

2 that I know of are

incestflix.com
tabooclub.com

**Comment by StevenBlack** [comment]
Hi @Jezza-x3 this is in the [update.info file](https://github.com/StevenBlack/hosts/blob/master/extensions/porn/update.info).

This list gets updated once in awhile.  Perhaps submit a PR there?

**Comment by GitTheHellOutaHere** [comment]
Ooooh, incest - thanks for that link!  😈

FYI - tabooclub redirects to hustlerstaboo.com

And anyone who believes that those people on incestflix are really related is a moron!
But it _MUST_ be true - it’s on the Internet!
