### ISSUE TITLE
Please Add the following Pornography Domains to Block

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#2020]
Hello @StevenBlack and @Sinfonietta,

Please add the following pornography domains to the Porn Hosts blocker:

tribbinglesbians.com
panochasyculos.com
omorashi.org
youleaked.com
hentaifc.com
aveliporn.com
humpingmasturbation.com
xxxa.com
xxxxsx.com
pornevening.com
eliteporn.cc
cloudixgirls.com
nebyda.com
hentaiheart.com
novelcrow.com

**Comment by StevenBlack** [comment]
Thanks @g1t3m!

Ping @sinfonietta for inclusion.

**Comment by Sinfonietta** [comment]
@StevenBlack these are added.

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta!

Closing.
