### ISSUE TITLE
Add blocklist for dating sites

### ISSUE THREAD

**Issue by ww00xx** [StevenBlack/hosts#2023]
Please include dating sites into Social for example:

- tinder.com
- bumble.com
- badoo.com
- okcupid.com
- hinge.co
- coffeemeetsbagel.com
- happn.com
- weareher.com
- clover.co
- pof.com
- match.com

and so on...

**Comment by StevenBlack** [comment]
Thank you for this @ww00xx.

Ping @sinfonietta, would you consider adding these?  Seems right and reasonable to me.

**Comment by Sinfonietta** [comment]
@StevenBlack I have added these to my social-hosts list.

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta and thank you @ww00xx for the suggestion.

Closing.

**Comment by ww00xx** [comment]
I just found this host list for dating sites https://www.github.developerdan.com/hosts/lists/dating-services-extended.txt
