### ISSUE TITLE
new fraud site: secur()hopp()to

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#2028]
I'm getting text messages like the following with links to secur . hopp .to which is definitely a scam.

![QfGnQwR](https://user-images.githubusercontent.com/67167176/182497842-9c387f1c-2472-4710-b5e4-cbcd0fc3552c.png)

**Comment by StevenBlack** [comment]
Thanks Devon @hyder365 I've added this and it goes live in the next release, in a few minutes.

Closing.
