### ISSUE TITLE
Cannot connect to link.vudu.com

### ISSUE THREAD

**Issue by ccfman2004** [StevenBlack/hosts#2031]
One of the blocked addresses also blocks link.vudu.com which is needed for password reset and other things.

**Comment by StevenBlack** [comment]
Thank you for this Charles @ccfman2004.

We don't list the domain `link.vudu.com`. Can you be more specific about which domain we carry that may be causing this issue?

**Comment by ccfman2004** [comment]
I don't know how to find out.

**Comment by gothic-bum** [comment]
@StevenBlack:

`link.vudu.com` is an alias for the CNAME `cb.sailthru.com` which is included in the AdAway blocklist.

**Comment by ccfman2004** [comment]
It seems like companies are trying harder and harder to go though ad sites when users need to do required stuff like reset their password.  You can't reset your Vudu password without having access to link.vudu.com.

**Comment by StevenBlack** [comment]
Thanks @gothic-bum, that's right.

From the [sailthrough.com](https://www.sailthru.com/) home page:

> Sailthru's cross-channel customer engagement solution is built to help marketers connect on a deeper level with each and every consumer, by delivering personalized experiences across email, web, mobile, and now, SMS. It’s designed to help you move at the speed of your customer… so you can achieve more, faster.

Sorry Charles @ccfman2004 this isn't going to change here.

Closing.

**Comment by ccfman2004** [comment]
Can you at least add a comment next to it so people know to I comment it if they need to reset their Vudu password as it blocks the ability to do so?

**Comment by StevenBlack** [comment]
Charles @ccfman2004 the record comes from upstream. It gets overwritten when it's fetched for each new release.

The solution here would be for vudu.com to cut the crap. It's their choice to hitch to that train, and encumber this critical facet of their infrastructure.  This is vudu.com's problem.
