### ISSUE TITLE
More Porn Sites to Add

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#2032]
Hello,

I've discovered a few more porn sites not included in the filter:
xgames.zone
highporn.net
javla.fun
javdoe.to
javfinder.li
javfree.la

Thank you for your continued work on the filters!

**Comment by StevenBlack** [comment]
Thank you for this @g1t3m.

Ping @sinfonietta for inclusion?

**Comment by g1t3m** [comment]
Hello @Sinfonietta and @StevenBlack, I've found more sites in addition to the ones above:
xgames.zone
highporn.net
javla.fun
javdoe.to
javfinder.li
javfree.la
hentai.name
pururin.to
pornwild.com
slut.ws
safebooru.org

**Comment by g1t3m** [comment]
👆👆👆👆

**Comment by MiiJack** [comment]
Would like to add one : videos-xxx-gratuit.com

**Comment by Sinfonietta** [comment]
@StevenBlack I have added all these.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and thank you @g1t3m.

Closing.

**Comment by Azirine** [comment]
> safebooru.org

safebooru.org is not a porn site.
