### ISSUE TITLE
error in updating source

### ISSUE THREAD

**Issue by pokegamer5547** [StevenBlack/hosts#2033]
I'm trying to add this to my hosts file so i added it in url key just like mentioned.  But when updating it's always showing error in updating source for that link.  This is that link. 
https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt
![Screenshot_20220806-185336_Termux](https://user-images.githubusercontent.com/65234485/183250829-2a67667e-ac86-4da7-b49a-2ad4f678046d.png)

![Screenshot_20220806-185551_Termux_1](https://user-images.githubusercontent.com/65234485/183250915-705cb1d9-4a17-4647-b252-038faf95b5ce.png)

**Comment by StevenBlack** [comment]
Thank you for this @pokegamer5547 

That URL resolves correctly for me.  Both these work for me:

* URL in a web browser.
* `$ curl https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt`.

**Comment by pokegamer5547** [comment]
> Thank you for this @pokegamer5547
> 
> That URL resolves correctly for me. Both these work for me:
> 
>     * URL in a web browser.
> 
>     * `$ curl https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt`.

Yes you're right, it's working fine for me in both cases as well. It's only not working during hosts updating. 
![Screenshot_20220808-070739_Termux](https://user-images.githubusercontent.com/65234485/183321914-d252f7b9-0e15-4794-a839-f8a3c0890d7d.png)

I dont get it where i am going wrong. 
I created a newfolder in data folder and then copied update.json file from other list and modified it's url with what it's showing.

**Comment by StevenBlack** [comment]
@pokegamer5547 when i run this hosts file through our software it crashes. When I remove `try...except...` code wrappers I see this more detailed error.

```
Updating source data/StevenBlack from https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/encodings/idna.py", line 167, in encode
    raise UnicodeError("label too long")
UnicodeError: label too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/steve/temp/hosts/updateHostsFile.py", line 1829, in <module>
    main()
  File "/Users/steve/temp/hosts/updateHostsFile.py", line 254, in main
    update_all_sources(source_data_filename, settings["hostfilename"])
  File "/Users/steve/temp/hosts/updateHostsFile.py", line 757, in update_all_sources
    updated_file = get_file_by_url(update_url)
  File "/Users/steve/temp/hosts/updateHostsFile.py", line 1568, in get_file_by_url
    res_text = "\n".join([domain_to_idna(line) for line in req.text.split("\n")])
  File "/Users/steve/temp/hosts/updateHostsFile.py", line 1568, in <listcomp>
    res_text = "\n".join([domain_to_idna(line) for line in req.text.split("\n")])
  File "/Users/steve/temp/hosts/updateHostsFile.py", line 1514, in domain_to_idna
    splited_line[index] = splited_line[index].encode("IDNA").decode("UTF-8")
UnicodeError: encoding with 'IDNA' codec failed (UnicodeError: label too long)
```

There's garbage in the file you're trying to import.  

Closing.
