### ISSUE TITLE
Add ls.dtrace.nvidia.com

### ISSUE THREAD

**Issue by SoftwareRat** [StevenBlack/hosts#2034]
Just used for NVIDIA telemetry

**Comment by StevenBlack** [comment]
Thank you for this @SoftwareRat.

I'm going to need much more justification to block this domain. In particular, I'm going to need some insight into potential platform and os-specific side effects.

**Comment by FadeMind** [comment]
@StevenBlack 
```
ping /n 3 ls.dtrace.nvidia.com

Pinging ls.dtrace.nvidia.com [34.232.100.37] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 34.232.100.37:
    Packets: Sent = 3, Received = 0, Lost = 3 (100% loss),
```

- https://domain.glass/ls.dtrace.nvidia.com
