### ISSUE TITLE
New Delivery Scam Link

### ISSUE THREAD

**Issue by adsdawdfawdcwacdaw** [StevenBlack/hosts#2037]
Friend just got this scam link in a text
 
 "EVRI: Your parcel has been returned to our depot following a failed delivery attempt. Please visit https://evri-package-gb.web.app to reschedule a delivery."
 
 https://evri-package-gb.web.app

**Comment by StevenBlack** [comment]
Thank you @adsdawdfawdcwacdaw I just added this to my list.

Closing!
