### ISSUE TITLE
New Scam tecnique on Discord

### ISSUE THREAD

**Issue by 1alessandro1** [StevenBlack/hosts#2038]
Hello, I propose to ban the following address and its subdomains

```
https://nl-crypto.com
```

Since they try to induce the user to register for a "free" bitcoin withdrawal with a promo code

![image](https://user-images.githubusercontent.com/46293832/184160483-14e57c4d-bab6-4e36-acef-7ad86c275a57.png)

Fooling the user to enter the code, then pay a certain amount to access the full funds

![image](https://user-images.githubusercontent.com/46293832/184161180-a1262ae3-fde0-46bc-a989-2263a18856bd.png)

Clearly a scam here

![image](https://user-images.githubusercontent.com/46293832/184160731-41488033-20c6-4088-92a6-79b21ef4264a.png)

**Comment by StevenBlack** [comment]
Thank you @1alessandro1 what a great domain inclusion request!  See, this is how it's done.  I'm adding this now.

**Comment by StevenBlack** [comment]
Closing!
