### ISSUE TITLE
Disabling DNS Cache service breaks WSL

### ISSUE THREAD

**Issue by numpad0** [StevenBlack/hosts#2039]
Following [this part of README.md](https://github.com/StevenBlack/hosts#warning-using-this-hosts-file-in-windows-may-require-disabling-dns-cache-service) and changing value for `HKLM\SYSTEM\CurrentControlSet\Services\Dnscache\Start` from `2` to `4` seems to cause Windows Subsystem for Linux fail to start as a side effect, causes the error below. 

A warning might be helpful, and [increasing cache size might be helpful instead(haven't tested yet)](https://answers.microsoft.com/en-us/windows/forum/all/host-file-entries-slow-down-startup-connection-to/27d86d30-d4b8-4ea5-9f61-ac9ada3c023a).

```
C:\Users\>bash
The service has not been started.
```

**Comment by StevenBlack** [comment]
Thank you for this @numpad0.  I appreciate this suggestion.  This feels kind of edge, and out of scope.  I don't think we should be warning userland about all the things that could go south when editing the Windows registry.  Also, what you describe, *changing value for `HKLM\SYSTEM\CurrentControlSet\Services\Dnscache\Start` from `2` to `4` s*, isn't what we say in our docs.

Thank you anyway though!

Closing.
