### ISSUE TITLE
spam/porn domain: dollvip()com

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#2041]
I've started getting spam messages on discogs.com (of all places...) like the following. I'm unsure if it's malware or porn since I didn't click it.

![spam](https://user-images.githubusercontent.com/67167176/184515992-5442ec5c-c5bd-44ab-a7a9-688f18425d42.png)

**Comment by StevenBlack** [comment]
Hi Devon @hyder365, thank you for this.

I can't proceed to consider this unless I'm given specific information about the domains involved.

Closing.
