### ISSUE TITLE
Broke app functionality audid-api.taobao.com

### ISSUE THREAD

**Issue by Maario03** [StevenBlack/hosts#2042]
Hi, by blocking this domain "audid-api.taobao.com", some of the functions of AliExpress have stopped working. For example I can't see my orders.  By whitelisting this domain, the problem disappears.
Its getting blocked only by this list on NextDNS,
I'm using it alongside 1host(pro) and oisd which didn't block it.

**Comment by miaLDN** [comment]
audid-api.taobao.com is still blocking AliExpress app functionality.  I have a blank page and "Please check your network connection and refresh".

Again, this domain appears only on this list, not on more aggressive lists from elsewhere.
