### ISSUE TITLE
s.youtube.com breaks YouTube history 

### ISSUE THREAD

**Issue by Maario03** [StevenBlack/hosts#2043]
Hi, so this domain "s.youtube.com" is getting blocked by your list causing YouTube history, search's and shorts to not work properly

**Comment by StevenBlack** [comment]
Hi Maario @Maario03 thank you for this.

This has been discussed many times here over the years. If you search `s.youtube.com` in this repo, you'll see the issues were this is raised and addressed.

This isn't going to change. Sorry.

Closing.
