### ISSUE TITLE
Remove ocs-dl.fra1.cdn.digitaloceanspaces.com from blocklist

### ISSUE THREAD

**Issue by hudson-thomas** [StevenBlack/hosts#2047]
Hi, I recently reinstalled KDE Plasma on my Debian machine and noticed that I got a "Connection refused" error whenever I tried to install a new theme or similar content. I went through my logs and noticed that the opendesktop.org [ocs-url](https://www.opendesktop.org/p/1136805/) is the main download site for these packages, not the KDE store. The domain that was causing the issues is ocs-dl.fra1.cdn.digitaloceanspaces.com . After whitelisting, the problem went away. 

Thanks for your help!

**Comment by gothic-bum** [comment]
`ocs-dl.fra1.cdn.digitaloceanspaces.com` is an alias for the CNAME `cds.b5g9b8e4.hwcdn.net`.

I just checked and neither of these are included in the current blocklist (dated 17 August 2022 14:24:22 UTC).

**Comment by hudson-thomas** [comment]
Wow. What a massive brain fart. I just checked and it turns out that the CNAME was in a personal blocklist for Plex ads. My bad. Sorry for wasting everyone's time. @gothic-bum Thanks for bringing this to my attention.
