### ISSUE TITLE
block on `action.greenpeace.org.uk` breaks Greenpeace site

### ISSUE THREAD

**Issue by bikerpatch** [StevenBlack/hosts#2049]
The block on `action.greenpeace.org.uk` breaks the Greenpeace UK charity site

`action.greenpeace.org.uk` is a non-malicious URL and likely to have been aggregated incorrectly.  Which list do you source this from?  I can then look to check with the upstream list owner

**Comment by gothic-bum** [comment]
`action.greenpeace.org.uk` is an alias for the CNAME `go.pardot.com`.

Pardot tracking domains are blocked by many lists.

**Comment by StevenBlack** [comment]
Hello @bikerpatch thank you for this.

First of all, let me begin by saying this:

So we're clear, there are no "legitimate" domains here.

It doesn't matter if a domain belongs to the Holy Sisters relict of Mother Theresa of Calcutta. If the domain employs scum practices, or vehicles crapware or worse, they get listed here.

I trust that this is crystal clear.

The domain `action.greenpeace.org.uk` comes to us from upstream, from the curated hosts of [adguard-cname](https://github.com/AdguardTeam/cname-trackers/issues). CNAME records are links that are cloaked to appear as another.

Let's check on the domain `action.greenpeace.org.uk` shall we?

```
dig action.greenpeace.org.uk                                                                          17:13:41
action.greenpeace.org.uk. 300	IN	CNAME	go.pardot.com.
go.pardot.com.		7200	IN	CNAME	pi.pardot.com.
pi.pardot.com.		300	IN	CNAME	pi-ue1.pardot.com.
pi-ue1.pardot.com.	30	IN	CNAME	pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com.
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 60 IN A 18.208.125.13
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 60 IN A 3.215.172.219
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 60 IN A 34.237.219.119
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 60 IN A 3.92.120.28
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 60 IN A 52.54.96.194
```

So you're claiming that `go.pardot.com`, masquerading as `action.greenpeace.org.uk` is legitimate?

I don't think so.

That said, you're welcome to make your case with the [Adguard CNAME team](https://github.com/AdguardTeam/cname-trackers/issues). Good luck with that.

Closing.

**Comment by bikerpatch** [comment]
Appreciate the detail but woah... wind your neck in.  A CNAME by itself is not a malicious construct.. otherwise it wouldn't exist.  In fact it happens frequently in SaaS vendors that provide hosted software services (finance, hr, security, etc) to small and midsize companies, including those that need to embed those legitimate services into their own site and still satisfy CORS.  A CNAME is not a measure of malicious or subversive intent.

The actual reason why pardot.com is on the list is that it is owned by Salesforce cloud, a CRM and marketing tool used to track engagement of customers and users.  And it may well be used to track users who don't willingly provide information (which is why I use PiHole and this covers the intent of why it is on the lists), in other cases it's used to aggregate form-filled registration information provided by choice, a more advanced form of Google Forms, which is why it breaks this site.

I appreciate it comes from upstream, hence the question as to where, though in future you could be less passive aggressive to your user base.

**Comment by Lateralus138** [comment]
I don't speak for this project as I'm just one of the so-called "users" so don't take what I say out on them, but how about you appreciate that this is a public service doing "users" a favor instead of some product

**Comment by Lateralus138** [comment]
I don't speak for this project as I'm just one of the so-called "users" so don't take what I say out on them, but how about you appreciate that this is a public service doing "users" a favor rather than some product who needs these users. I'd say Steven is far too nice to some of the idiots who come here and is biting his tongue being as "professional" while dealing with some of these fucks so if he is being "passive aggressive" it's probably all he can do not to snap on people (not to speak for him as I know and have seen him speak up and for himself before). As for me I don't give a shit about your little offended ass and you can "wind your" own fucking "neck in".

**Comment by bikerpatch** [comment]
You can't tar everyone who comes in with the same brush.  Remember I'm a user as well, originally looking to contribute to the success of this stuff.  I sit on my sofa, wondering why sites I visit get blocked.  I've whitelisted the URL already in Pi-Hole.. but maybe this would help someone else in the same position..

It was a simple question really, expecting a simple answer.  Steven didn't even need to be the one to respond to it, assuming others know the answer.  I can see this isn't the community for me.  Best of luck

**Comment by Lateralus138** [comment]
I said not to take it out on them. I'm speaking for myself alone. My comments are not reflective of the community here. I'm my own asshole speaking for myself (as clearly stated already).
