### ISSUE TITLE
More Porn Sites

### ISSUE THREAD

**Issue by Azirine** [StevenBlack/hosts#2050]
Hello @Sinfonietta and @StevenBlack, I've found more porn sites to be added:

4tube.monster
betabooru.donmai.us
bigboobsalert.me
ceporn.org
cliphunter.global
desimms.ink
dinotube.monster
dogfart.rocks
freehdx.io
freexcafe.club
gigantits.net
instantfap.biz
iwanktv.club
mallusex.pro
nsfw.irish
pichunter2.xyz
porndig.me
pornolaba.cc
pornovideoshub.world
primecurves.me
telugusex.cc
thumbzilla2.co
tube8in.net
tubesafari.net
vidz7.club
xlxx.live
xmissy.pro

And the following should be removed:

safebooru.org

**Comment by StevenBlack** [comment]
Thank you for this @Azirine!

Ping @sinfonietta, thanks!

**Comment by Sinfonietta** [comment]
@StevenBlack these are now added.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta, thanks @Azirine.  Closing.
