### ISSUE TITLE
Unity telemetry

### ISSUE THREAD

**Issue by nandlab** [StevenBlack/hosts#2053]
Can you please add the domain `prd-lender.cdp.internal.unity3d.com` to the hosts list?

The Unity IDE uses this address for telemetry. The IDE works fine if it is blocked.

**Comment by StevenBlack** [comment]
Thank you for this Ethan @nandlab.

Can you describe how you've come to this conclusion about `prd-lender.cdp.internal.unity3d.com`?

**Comment by nandlab** [comment]
I was analyzing the network traffic of Unity with opensnitch and mitmproxy and tried to block as much as possible. Connections to `prd-lender.cdp.internal.unity3d.com` do not seem to be necessary to log in into Unity Hub and start working with the Unity Editor.
This is what can be found in Unity Hubs Javascript (notice cdp-analytics):
```
const defaultCloudUrls = {
    dev: {
        core: 'https://andy-core.cloud.unity3d.com',
        collab: 'https://andy-collab.cloud.unity3d.com',
        webauth: 'https://accounts-dev.unity3d.com',
        identity: 'https://api-int.unity.com',
        license: 'https://license-dev.hq.unity3d.com',
        activation: 'https://activation-dev.hq.unity3d.com',
        perf: 'https://staging-perf.cloud.unity3d.com',
        portal: 'https://id-int.unity.com',
        hub_installer_location: 'https://public-cdn.cloud.unity3d.com/hub/dev/',
        'activity-feed': false,
        analytics: 'http://localhost:5000/v1/events',
        'cdp-analytics': 'http://localhost:5000/v1/events',
        analyticsOptOut: 'https://remote-config-proxy-stg.uca.cloud.unity3d.com/',
        livePlatform: 'https://live-platform-api.stg.ld.unity3d.com/graphql',
    },
    staging: {
        core: 'https://staging-core.cloud.unity3d.com',
        collab: 'https://staging-collab.cloud.unity3d.com',
        webauth: 'https://accounts-staging.unity3d.com',
        identity: 'https://api-staging.unity.com',
        license: 'https://license-staging.hq.unity3d.com',
        activation: 'https://activation-staging.hq.unity3d.com',
        perf: 'https://staging-perf.cloud.unity3d.com',
        portal: 'https://id-staging.unity.com',
        hub_installer_location: 'https://public-cdn.cloud.unity3d.com/hub/stage/',
        'activity-feed': false,
        analytics: 'https://cloud-staging.uca.cloud.unity3d.com',
        'cdp-analytics': 'https://stg-lender.cdp.internal.unity3d.com',
        analyticsOptOut: 'https://remote-config-proxy-stg.uca.cloud.unity3d.com/',
        livePlatform: 'https://live-platform-api.stg.ld.unity3d.com/graphql',
    },
    production: {
        core: 'https://core.cloud.unity3d.com',
        collab: 'https://collab.cloud.unity3d.com',
        webauth: 'https://accounts.unity3d.com',
        identity: 'https://api.unity.com',
        license: 'https://license.unity3d.com',
        activation: 'https://activation.unity3d.com',
        perf: 'https://perf.cloud.unity3d.com',
        portal: 'https://id.unity.com',
        hub_installer_location: 'https://public-cdn.cloud.unity3d.com/hub/prod/',
        'activity-feed': false,
        analytics: 'https://analytics.cloud.unity3d.com',
        'cdp-analytics': 'https://prd-lender.cdp.internal.unity3d.com',
        analyticsOptOut: 'https://config.uca.cloud.unity3d.com/',
        livePlatform: 'https://live-platform-api.prd.ld.unity3d.com/graphql',
    }
};
```
The other analytics domains like `stg-lender.cdp.internal.unity3d.com` can be probably blocked too btw.

**Comment by gothic-bum** [comment]
What is the *actual* information is being sent to the domain(s) that proves they are being used for user tracking and/or privacy-violating purposes? Or is it simply the word "analytics" that raises concern?

**Comment by nandlab** [comment]
I don't remember exactly what was being sent, but I think it was some hardware information stuff.

**Comment by gothic-bum** [comment]
> I don't remember exactly what was being sent, but I think it was some hardware information stuff.  
  
So why is this bad? Perhaps the hardware information is needed for valid purposes, such as displaying and/or serving content based on the device type (e.g. mobile vs desktop).
  
One would hope that any decision to add a domain to a blocklist – which is used by millions of people – would be based on actual data and a specific determination that it is harmful, rather than being based simply on speculation and guessing.

**Comment by StevenBlack** [comment]
Thank you for your input @gothic-bum — please be extra-kind to new folks who come here.  I presume good faith always. At least at the outset I do.  I try 😄 

Ethan @nandlab has already provided the information I requested. This is actually an exquisite quality ask, now. At least, far beyond what we most times accept here.

Ethan @nandlab I'm going to go with the two analytics domains in the `production` data set you've uncovered.  Namely...

```
...
'cdp-analytics': 'https://prd-lender.cdp.internal.unity3d.com',
analyticsOptOut: 'https://config.uca.cloud.unity3d.com/',
...
```

As a Unity3D user, I ask you to please be vigilant and let us know if you detect side-effects or grumble from that community.  Cool?

**Comment by nandlab** [comment]
Thank you!

Of course I will notify you if I detect or hear about any side-effects.
