### ISSUE TITLE
add more porn sites (part 1: I will send it in two parts to prevent the bot from accusing me of spam)

### ISSUE THREAD

**Issue by abbbw** [StevenBlack/hosts#2054]
123gayporn.com
amantevip.com
animeshentai.tv
aquariumgays.com
assanalized.com
aumenteseutesao.com
avaliemeupaunovo.blogspot.com
avantajados.com
bananaboyshot.blogspot.com
bandeiradois.blog.br
bbwfuckpic.com
beeg1.net
bigtitstubehd.com
blog-da-porra.blogspot.com
blogcorno.com
blogdascaxorras.net
blogmaxegatos.com
blogsapekas.blogspot.com
boycollector.net
boysnaweb.net
boysreserve.blogspot.com
brancoquernegro.blogspot.com
brazzerspornvideos.com
bucetascabeludas.com.br
bucetasebundas.com.br
caiunanetnovinha.com.br
calcinhamolhada.com.br
caminhoneiropelado.com
candyschoolgirls.com
cccccccddddv.blogspot.com
centraldegruposwhats.com.br
cenzao.com.br
clipsporno.net
contosdebanana.blogspot.com
coroascaseiras.org
cuckoldman.vip
daddyfuckoldman.com
erosedionisio.blogspot.com
famousmaleexposed.blogspot.com
fapdick.net
faphouse.com
fetish-zona.com
forcedcinema.net
fotoscaiunaweb.online
fotosdeamadoras.com
fotosporno.blog
fotospornobr.com
fruitycams.com
galaxiagay.org
garotosdotados.com
gaybananasbrasil.com
gaymachotube.blogspot.com
gayporncocks.blogspot.com
germanthreesome.com
gesek.info
girlnude.link
gostosashd.blog.br
gostosaspelada.com
gostosaspornosafadas.com
grannyhotvideo.com
gulagay.com
hardteentube.com
hentaifusion.me
hentaigay.com.br
homempelado.net
homensquentes.com.br
hotindiangayporn.com
hqhentai.online
humoracobrar.blogspot.com
igorsclouds.com
jalurtajir.com
jsc-dorian-gray.com
kabinedasnovinhas.com
kinguys.com
lesbiansgranny.net
mangashentais.com
massagecum.com
matureanaltube.com
meninosonline.net
metendonanovinha.com.br
metflixgay.blogspot.com
meumundogay.com
meusexogay.com
milfslesbian.com
milfzr.com
molequeserolas.blogspot.com
mundomachogifs.blogspot.com
mundomais.com.br
musasbrasil.com
musculoduro.net
mydesipapa.net
mygrannie.com

**Comment by Sinfonietta** [comment]
@StevenBlack these are added to my list.

**Comment by StevenBlack** [comment]
Thank you again @Sinfonietta, thanks @abbbw.  Closing.
