### ISSUE TITLE
add more porn sites (part 2: I sent it in two parts to prevent the bot from accusing me of spam)

### ISSUE THREAD

**Issue by abbbw** [StevenBlack/hosts#2055]
mylfvideos.com
myownprivatelockerroom.net
nacamacomrafa.blogspot.com
nahoragay.blogspot.com
nervoh.blogspot.com
new-mexile.blogspot.com
novinhafudendo.com
novinhas.tv
novinhasnudes.com.br
oldmandaddy.com
oldmaturetv.com
ongaytube.com
onlyhotguys.com
onlyleaks.fun
oubaba.top
ousadasdofacee.blogspot.com
outdoorbanger.com
padapawn.com
peggingsex.co.uk
phimditnhau.co
picanteeproibido.com.br
pontodevistagay.com.br
pornobox.blog
pornobrasileiro.vlog.br
pornofrog.com
pornogay.biz
pornogay.today
pornosacana.com
pornozudo.com
pornpic.com
pornpics365.com
povheaven.com
punheta-entre-amigos.blogspot.com
punhetaesexoempublico.blogspot.com
pussyslide.com
putasnovinhas.com
randomale.net
redpornworld.blogspot.com
scatshop.com
secretas.com
seemewank.com
sexhdfor.me
sexivideo.net
sexoamador18.com
sexogay.blog
sexogay.net.br
sexolesbicas.club
sexopornogay.blog.br
sexosemfrescuras1.blogspot.com
showyourtinydick.com
sodotados.com
sonovinhasbr.com
sonovinho.com
squirtgameporn.com
strapcams.com
straponsessions.com
suamulher.com
supertudogay.com
teedollasign.com
teenporncams.net
teensforall.com
tesaog.com.br
testosterona.blog.br
thebestofcafucus.com
theblowjobplace.com
thekinkykingdom.com
topgalaxia.com
topvideosgay.com
upteenxxx.com
vaiamador.com
verdadeiroboysnanet.blogspot.com
videosdesexo.xxx
videosnudes.com
wasvid.com
whatsdosexo.com
xhqporno.com
xhstream.com
xngay.com
xoxoteiros.blog.br
xvideos69.com.br
xvideos-hd.blog
xvideos-hd.com
xvideos-net.com
xvideos-tv.com
xvideos.kim
xvideosprive.com.br
xvideosx.org
xvidiosporno.net
xxxgaysporno.com
xxxtrannyvideo.com
xxxvideo.blog.br
youngjapaneseporn.com

**Comment by Sinfonietta** [comment]
@StevenBlack I have added these also.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta, thanks @abbbw.  Closing.
