### ISSUE TITLE
ccleaner avast domains 

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#2059]
I found that ccleaner after launch connecting to these domains. One of them is already blocked.
I found thread forum about `ipm-provider.ff.avast.com` here https://malwaretips.com/threads/%C2%B5block-origin-blocks-https-ipm-provider-ff-avast-com.101594/

Here is a full list of them
```
ip-info.ff.avast.com
ipm-provider.ff.avast.com
ipmcdn.avast.com
ncc.avast.com
shepherd.ff.avast.com
```
Already blocked:
`analytics.ff.avast.com` 

@StevenBlack  please consider add them to your list. Before PR I want discous this in this issue ticket. 

![20220826-1661528429](https://user-images.githubusercontent.com/9846948/186942313-4dfac57f-e0fc-4cce-a48e-43960ff50fcb.png)

**Comment by StevenBlack** [comment]
Block 'em all, I say.  No love for Avast here.  Will you PR this Tomasz @FadeMind?

**Comment by FadeMind** [comment]
@StevenBlack PR awaits 😉
