### ISSUE TITLE
Blocklist for stalkerware

### ISSUE THREAD

**Issue by jvoisin** [StevenBlack/hosts#2063]
[Echa](https://echap.eu.org/) is maintaining a [list]( https://github.com/AssoEchap/stalkerware-indicators ) of Indicator of Compromises for [stalkerware]( https://en.wikipedia.org/wiki/Stalkerware ), and automatically generates a [list]( https://github.com/AssoEchap/stalkerware-indicators/blob/master/generated/hosts) of [c2]( https://en.wikipedia.org/wiki/Botnet#Command_and_control ).

Would it be possible to make use of it?

**Comment by StevenBlack** [comment]
Hi Julien @jvoisin thank you for this interesting suggestion.

Yes it's possible to make use of this.

To make it happen for you, right now, clone this repo, add a folder named `./data/echa` using it's own `./data/echa/update.json` file setting... 

```
...
  "url": "https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts"
...
```

... then run `[updateHostsFile.py](https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py)` and you've got your new enhanced `hosts` file loaded.

To make this happen generally, for everyone, I'm just a little concerned that this list has `831` domains and we only have `2` of them.  Using [ghosts](https://github.com/StevenBlack/ghosts) here's what I see:

```
ghosts -c https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts   20:08:42
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 136,942
Bytes: 5.0 MB
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
Domains: 831
Bytes: 18 kB
Intersection: 2 domains
```

It's a bit shocking the intersection is only 2 domains. The overlap between this 831 domain list and our 136,935 domain list is just 0.2%.

How is it possible that this group found 829 domains that have somehow escaped the notice of a wide group of very dedicated list curators over a period of 10-years? 

Not saying this isn't possible. I'm just asking, how does this happen?

**Comment by Te-k** [comment]
The answer is quite simple : no one really paid attention to Stalkerware. We have spent a lot of time analyzing stalkerware apps and extracting command and control domains for them. The list is quite restrictive, on our repo, we are listing both watchware (apps developed to monitor phones openly) and stalkerware apps (apps monitoring phones activity secretly) and we are listing both websites and C2 domains (you can see the full list [here](https://github.com/AssoEchap/stalkerware-indicators/blob/master/ioc.yaml)). This hosts file only contains C2 domains for stalkerware applications, so it should have a low rate of false positives.

The two domains that belong to both lists are : 
```
0.0.0.0 alog.umeng.com
0.0.0.0 push.mobilefonex.com
```

The first one is coming from Steven Black's ad-hoc list, the second from AdAway.

**Comment by StevenBlack** [comment]
Yes. Agreed. But stalkerware is a specialization of tracking, which is a heavily watched and analyzed category by most, maybe all, our curated sources.

**Comment by Te-k** [comment]
Hi, apologies for the delay.  I am personally not that surprised that there is such a small overlap with your blocklist, stalkerware aren't trackers, they are spyware sold for abusive people to spy on their partner. And from experience, until a few years ago, no one really paid attention to this market. This topic hasn't been considered as a privacy issue and studied in the same way ads or cyber crime activities have been studied. 
I think it would be a great addition to your block list. Should I submit a PR?

**Comment by StevenBlack** [comment]
Merci pour ceci @Te-k!

Here's another look at the comparison:

```
$ ghosts --clip                                                                                         

----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 195,226
Bytes: 6.9 MB
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 843
Bytes: 18 kB
Intersection: 2 domains
```

I **still** don't get how this is plausible. The overlap between this 843 domain list and our 195,226 domain list is minuscule.

But yes, a pull request speaks loudly 😄 I'd entertain a PR for this.
