### ISSUE TITLE
More Porn Sites

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#2065]
Hello @StevenBlack and @Sinfonietta,

Please add the following porn sites to the filter:
leaknudes.com
thothub.vip
clipcelebrity.com
fuckher.vip
nsfwleak.com
vip-porn.com
clippussy.com
fapgrams.com
fapello.com
nudesleaked.net
onlynudes.tv
fanslyleaks.net
dirtyleak.com
fappgirls.com
femaleak.com
pornscn.com
fappinghd.com
hotgirle.com
cineforest.net
pornhubcum.com
slutsclip.com
nudeof.com
virtualmodelschool.com
leakhub.vip
tabootube.xxx
xxbrits.com
thotsfan.com
hornyfanz.io
leakxxx.com
red.xxx
simpcity.su
epawg.com
en.vidmo.pro

As always, your work is appreciated!

**Comment by StevenBlack** [comment]
Thanks @g1t3m.  Ping @sinfonietta!

**Comment by g1t3m** [comment]
👆🏿👆🏿👆🏿👆🏿👆🏿👆🏿

**Comment by Sinfonietta** [comment]
These have been added @StevenBlack @g1t3m

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta closing!
