### ISSUE TITLE
Porn sites

### ISSUE THREAD

**Issue by sefinek24** [StevenBlack/hosts#2068]
porngur.com
maxiporn.com
adultporn.me
hd-porn.video
animalporn.me
sonmompornincestxxx.com
lusthero.com
porn-hub.live
chinaporns.com
iwankwank.com
porm.club

**Comment by Hyperpolymath** [comment]
If you leave them as naked domains (as in without the www., etc. bit), it should not hyperlink them, and create linkbacks, trackbacks, refbacks and pingbacks from the sites, reducing traffic and minimising additional 'profiling' the sites and their standing, as well as traffic. If they only work with the www/other prefix, you can manually remove these in this edit tool. Just a suggestion.

**Comment by StevenBlack** [comment]
@Hyperpolymath that's not how hosts files work. 

Hosts files work with the full (sub)domain names.  So `example.com` and `www.example.com` are two different hosts, and to block both we need both. Also there is nothing magical or special about the `www.` prefix.

Anyway it's not about links and back links at all. We need the fully qualified (sub)domain(s) here.

Thank you for these domains @sefinek24 ping @sinfonietta to include these.
