### ISSUE TITLE
Porn Site

### ISSUE THREAD

**Issue by NeedingMuchHelp** [StevenBlack/hosts#2069]
Hi, please block these sites:

ehentai.to
nhentai.to 

For the first, I was able to block it by making my own host file with
0.0.0.0 ehentai.to
BUT
for the second, I could not block it with
0.0.0.0 nhentai.to    or   https://nhentai.to

Could you please investigate and let me know why? That way I can continue to build my list. (Currently I use adaway to apply host file, and then uninstall -- because otherwise I find myself disabling the blocking.... stupid I know but I need help). 

Thanks!

**Comment by StevenBlack** [comment]
Thank you for this @NeedingMuchHelp.

Ping @BigDargon for possible inclusion.

**Comment by bigdargon** [comment]
> Could you please investigate and let me know why? That way I can continue to build my list. (Currently I use adaway to apply host file, and then uninstall -- because otherwise I find myself disabling the blocking.... stupid I know but I need help).

It is possible that the device DNS is still cached after you add it to the block list.

**Comment by StevenBlack** [comment]
Thanks @bigdargon!

Closing.
