### ISSUE TITLE
Android设备使用问题

### ISSUE THREAD

**Issue by wst4288** [StevenBlack/hosts#207]
请问我在手机上把hosts文件替换后，还是进不了谷歌怎么回事？
是不是文件需要修改？

**Comment by StevenBlack** [comment]
如果你有root权限，你可以替换`/ etc`文件夹中的hosts文件。
我希望这有帮助。
我的中文很糟糕，对不起。

**Comment by wst4288** [comment]
谢谢您的耐心解释。
我有root权限
也替换了system/etc/hosts
但替换了之后还是上不了谷歌，不知道是什么原因导致的。

**Comment by kemingcao** [comment]
` This repo provides several hosts files tailored to you need to block.` 
@wst4288 这个repo里面的内容不是你需要的，或者你可以尝试vpn相关的东西。

**Comment by wst4288** [comment]
我突然明白了。这个hosts是用来去广告的 ，不是用来翻墙的。

**Comment by StevenBlack** [comment]
@wst4288 这是正确的。 我祝你计算愉快。

**Comment by StevenBlack** [comment]
@wst4288 我认为你需要的是VPN软件 - 创建一个私人隧道穿过墙。

**Comment by ookangzheng** [comment]
翻墻的Hosts 
https://github.com/racaljk/hosts

**Comment by StevenBlack** [comment]
这是非常有趣！   然而，我的项目的目标是阻止不良来源。  祝你好运

**Comment by StevenBlack** [comment]
我现在结束这个问题。
