### ISSUE TITLE
Problem with weather.com (mparticle.com) - solved by old.reddit.com

### ISSUE THREAD

**Issue by Rusenche** [StevenBlack/hosts#2071]
> Hello
> 
> I´m using Chrome with uBlock Origin and when i go to weather.com, i cannot use the search bar.
> 
> This problem only started today.
> 
> Is there anything i can do about it without removing it?
> 
> Cheers.

https://old.reddit.com/r/uBlockOrigin/comments/x3fskl/problem_with_weathercom/ - open this address, read the reviews and be sure of the decision.

> as one of them might be blocking **mparticle.com**, which is the domain causing breakages if blocking it.

https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts - the problematic **mparticle.com** contains:

> 0.0.0.0 nativesdks.mparticle.com
> [mparticle.com]
> 0.0.0.0 config2.mparticle.com
> 0.0.0.0 cookiesync.mparticle.com
> 0.0.0.0 identity.mparticle.com
> 0.0.0.0 jssdkcdn.mparticle.com
> 0.0.0.0 jssdkcdns.mparticle.com
> 0.0.0.0 jssdks.mparticle.com
> 0.0.0.0 pixels.mparticle.com
> 0.0.0.0 s2s.mparticle.com
> 0.0.0.0 static.mparticle.com
> 0.0.0.0 engage.mparticle.com
>0.0.0.0 engage.mparticle.com

**Comment by StevenBlack** [comment]
Hello @Rusenche thank you for this.

Various `mparticle.com` domains are blocked by several of our curated sources.

This is a clear sign that this isn't going to change.

Maybe `weather.com` needs to reconsider what it uses behind the scenes? Here we serve those who don't want to be tracked or sold.

Closing.
