### ISSUE TITLE
`static.cloudflareinsights.com` blocks IPTV service

### ISSUE THREAD

**Issue by vb4472** [StevenBlack/hosts#2072]
`static.cloudflareinsights.com` and `cloudflareinsights.com` blocks the IPTV service provided by https://nimitv.com/en.html from starting. 

Endless loading screen displayed unless `static.cloudflareinsights.com` is whitelisted.

**Comment by StevenBlack** [comment]
Thank you for this @vb4472.

These `cloudflareinsights.com` are listed by three of our curated sources.

So this isn't going to change.

This is an unfortunate choice made by this IPTV provider. They have to live with their choices. The people we server here don't want to be tracked or traded by companies like that.

Closing.
