### ISSUE TITLE
Not all YouTube ads are blocked

### ISSUE THREAD

**Issue by holygamer** [StevenBlack/hosts#2073]
Hi, I'm using this: https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate

I've disabled all Chrome extensions and I'm not using any built-in feature to resolve domains remotely, such as DoH, DoT, VPN, proxy, etc. I don't have any system VPNs, etc. My DNS settings are also at the Windows defaults. 

It doesn't block ads in YouTube when Chrome is in Incognito mode. In non-incognito mode it blocks most ads on YouTube such as on Linus Tech Tips but not all ads such as an ad I got here: https://www.youtube.com/watch?v=MUWhJ_PrlyA
I also saw a popup banner ad on this video: https://www.youtube.com/watch?v=fzBCR_C26QE

I was wondering why that is? Thanks

**Comment by StevenBlack** [comment]
Hello @holygamer thank you for your question.

I'm not seeing a popup banner ad when I view that YouTube video.

Hosts files only block domains by name.

Last time I checked, YouTube pre-ads, and mid-video ads, are served by the same domains as those used to serve the videos.

So nothing we can do about that.

Closing.
