### ISSUE TITLE
[New] Add new extension source from hostsVN

### ISSUE THREAD

**Issue by bigdargon** [StevenBlack/hosts#2074]
Hi,

Currently, I have started to expand the [extension](https://github.com/bigdargon/hostsVN/tree/master/extensions) project with new contents classified as `adult`, `gambling`, `threat`, `ip blocklist`.

I have 2 sources `adult` and `gambling` that seem to work for your project.

`adult`: https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/adult/hosts

`gambling`: https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/gambling/hosts

Although the project is newly added and the domains are still few, I guarantee it will be constantly updated!

Thank you!

**Comment by StevenBlack** [comment]
Thank you @bigdargon! Your track record is good here 😄 

I have added these two extensions in commit 62be492.

Can you please make a pull requests with the two new `update.json` files filled as you'd like?  Thanks!

This is going live in the next release, in a few minutes.
