### ISSUE TITLE
Amazon Video blocked - whitelist requets

### ISSUE THREAD

**Issue by jondagle** [StevenBlack/hosts#2077]
Starting Sunday, i could not stream Amazon Prime Video on Apple TV without whitelisting this site:
`s3-iad-ww.cf.videorolls.row.aiv-cdn.net `

Video would not start. Oddly there was no issue just two days before...

**Comment by StevenBlack** [comment]
Hi @jondagle this comes to us from upstream.

@jawz101 hi, can you please have a look?  Thanks.

**Comment by jawz101** [comment]
removed thanks

**Comment by StevenBlack** [comment]
Thank you @jawz101.

@jondagle this will reflect in the next release.

Closing.

**Comment by jondagle** [comment]
Appreciate the fast work. Cheers!
