### ISSUE TITLE
Please clarify information regarding sources

### ISSUE THREAD

**Issue by chew-z** [StevenBlack/hosts#208]
This is great project and very helpful. I am a fan of this project for a long time but I run my own private fork of it cause in the end I do some things differently. 

My observation is that with projects growth there is more and more sources, alternative sources etc. It become very difficult to just come here and grab some sources (ie. lists) without reading Issues and insides of files. (add.Dead, add.Spam, ... )

A map or separate readme file describing sources and their variants and overlaps or perhaps short readme in each source folder would be very useful for someone who like me wants to come here on a self-service buffet basis.

**Comment by rjk40** [comment]
Agree

**Comment by StevenBlack** [comment]
@chew-z good idea.

@everyone, I'm open to pull requests that move quickly in this direction.

**Comment by StevenBlack** [comment]
@chew-z and @rjk40 how's [this](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant)?

**Comment by rjk40** [comment]
I am just hungry to learn as much as i can but i can sometime get too far ahead of myself and loose track of the tasks that lays the framework for the rest to come. I have a few ideas that i pawnder about. I have to implement a flow chart and learn the the essential languages barriers. Diagram flowchart ideas are great but it does come down to 1 and zeros. I have much to learn and many miles to walk before i can become an acomplished anything. Lots to obsorb.ll
