### ISSUE TITLE
Quizlet e-mail verification subdomain is not an adware/malware site

### ISSUE THREAD

**Issue by Hell01World** [StevenBlack/hosts#2081]
ablink.account.quizlet.com is Quizlet e-mail verification subdomain.

This subdomain is blacklisted in Steven Black's Ads and Malware Collection, at least according to Portmaster.
![Screenshot from 2022-09-10 16-54-41](https://user-images.githubusercontent.com/110909985/189488973-3f41ee64-b3fd-4927-b970-89c396f94267.png)

**Comment by StevenBlack** [comment]
Hello @Hell01World thank you for this.

We don't presently list any `quizlet.com` domains.

Closing.
