### ISSUE TITLE
Don't block videolan.org

### ISSUE THREAD

**Issue by pssandhu** [StevenBlack/hosts#2082]
www.videolan.org is the homepage of VLC media player

https://github.com/StevenBlack/hosts/blob/05272f9a1f034450b8c4fe317203d25249f02be9/extensions/porn/bigdargon/hosts#L926

I assume this accidentally slipped in again (#240).

**Comment by bigdargon** [comment]
@pssandhu Sorry! I will remove it!

**Comment by FadeMind** [comment]
@StevenBlack many false positives here.

**Comment by StevenBlack** [comment]
Thanks for this @pssandhu.

Thank you for the quick reply @bigdargon.

Tomasz @FadeMind can you provide examples?

**Comment by FadeMind** [comment]
https://github.com/bigdargon/hostsVN/issues?q=is%3Aissue+is%3Aclosed+label%3A%22false+positive%22

It is not often, but happen. Someones are criticals, other just mistaken (like vlc twice).

**Comment by StevenBlack** [comment]
Thanks everybody.

Closing.
