### ISSUE TITLE
Gambling Site missing in the list

### ISSUE THREAD

**Issue by GautamMKGarg** [StevenBlack/hosts#2083]
1x001.com
1x002.com
lotto60.com

**Comment by GautamMKGarg** [comment]
@bigdargon These are few more gambling sites.

1xbet.in
1xbetonline.in
j1cleoil.site
1wbae.xyz

**Comment by bigdargon** [comment]
@GautamMKGarg Added! Thank you!

**Comment by StevenBlack** [comment]
Thank you @bigdargon.  Closing.
