### ISSUE TITLE
Inappropriate blocking

### ISSUE THREAD

**Issue by kirbyan** [StevenBlack/hosts#2087]
Using this list on pihole, access to cdn.optimizely.com is blocked. This completely breaks nike.com, and it is not possible to view products. Whitelisting this domain restores functionality.

**Comment by StevenBlack** [comment]
Hi @kirbyan thank you for this.

The domain `cdn.optimizely.com` comes to us via two different list curators so I'm guessing, this isn't going to change.

This is a questionable engineering decision by nike.com.

Closing.
