### ISSUE TITLE
Access to adlist connection refused.

### ISSUE THREAD

**Issue by Ragziesoft** [StevenBlack/hosts#2088]
When i update Gravity on my Pihole web interface i get this ;

[i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

How to resolve, Thanks

**Comment by StevenBlack** [comment]
Hi @Ragziesoft thank you for your question.

```
$ curl https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
```

... works for me. So it's definitely available and online.

**Comment by Ragziesoft** [comment]
So could you guide me on how do i resolve it in my case.

**Comment by StevenBlack** [comment]
Hi @Ragziesoft 

Works great from here.

I don't know what to suggest.

![2022-09-17_23-48-44](https://user-images.githubusercontent.com/80144/190884860-67b07277-2377-4fab-a3e1-fcc63a7abbdf.jpg)

**Comment by Ragziesoft** [comment]
Is there a way to download the adlist separately and save it in cached list?

**Comment by vdanielgeorge** [comment]
Try the non github link

**Comment by Ragziesoft** [comment]
Okay success
![stevblk](https://user-images.githubusercontent.com/5304451/190891817-b2d78cb5-d578-4085-8531-c38b732ef2c2.png)
