### ISSUE TITLE
Gmail calling is broken

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [StevenBlack/hosts#209]
As of the Dec. 2nd update for [unified hosts + gambling](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts), I’ve been fighting to keep the Google Talk Plugins working in Gmail.

I make phone calls through Gmail and now I must switch from my extended hosts file back to the original before I can call; Otherwise Gmail shows this:

![gmail error](https://cloud.githubusercontent.com/assets/15519219/21034393/64c6e8de-bd6c-11e6-901b-28ebd50c7d87.png)

As soon as I switch, the calling feature becomes available again.

![gmail error 2](https://cloud.githubusercontent.com/assets/15519219/21034707/a2ec69de-bd6e-11e6-9e6a-c9f48917dbc0.png)

While working on this issue I noticed there are lots of duplicate entries in the list. For example, google-analytics and ssl.google-analytics appear several times. I thought it was supposed to be "de-duped."

It’s difficult finding the offending entry since so many addresses use the same server.
Little Snitch shows that clients.l.google.com is being blocked, but all these addresses use that server:

![gmail error 1](https://cloud.githubusercontent.com/assets/15519219/21034478/fb1eaccc-bd6c-11e6-9ae6-c325faa1e67e.png)

**Comment by StevenBlack** [comment]
`ssl.google-analytics.com` is not duplicated.   There is one live entry, and one commented entry.  The commented entry comes from someonewhocares.org.  We don't remove comments.

    $ ack ssl.google-analytics

    alternates/gambling/hosts
    14962:0.0.0.0 ssl.google-analytics.com
    22050:#0.0.0.0 ssl.google-analytics.com

    alternates/gambling-porn/hosts
    14962:0.0.0.0 ssl.google-analytics.com
    22050:#0.0.0.0 ssl.google-analytics.com

    alternates/gambling-porn-social/hosts
    14962:0.0.0.0 ssl.google-analytics.com
    22050:#0.0.0.0 ssl.google-analytics.com

    alternates/gambling-social/hosts
    14962:0.0.0.0 ssl.google-analytics.com
    22050:#0.0.0.0 ssl.google-analytics.com

    alternates/porn/hosts
    14962:0.0.0.0 ssl.google-analytics.com
    22050:#0.0.0.0 ssl.google-analytics.com

    alternates/porn-social/hosts
    14962:0.0.0.0 ssl.google-analytics.com
    22050:#0.0.0.0 ssl.google-analytics.com

    alternates/social/hosts
    14962:0.0.0.0 ssl.google-analytics.com
    22050:#0.0.0.0 ssl.google-analytics.com

    data/mvps.org/hosts
    6802:0.0.0.0 ssl.google-analytics.com

    data/someonewhocares.org/hosts
    324:#0.0.0.0 ssl.google-analytics.com

    history.md
    468:  * Blocked ssl.google-analytics.com, which the MVPs block.

    hosts
    14961:0.0.0.0 ssl.google-analytics.com
    22049:#0.0.0.0 ssl.google-analytics.com

**Comment by GitTheHellOutaHere** [comment]
ssl.google.com IS duplicated in the unified + gambling file, and not just a comment.

Maybe it’s because two files are combined?

![ssl2](https://cloud.githubusercontent.com/assets/15519219/21038800/91628076-bd8d-11e6-825a-571e85d2c280.png)![ssl1](https://cloud.githubusercontent.com/assets/15519219/21038799/913c1b3e-bd8d-11e6-9e0e-1a725227a82b.png)
