### ISSUE TITLE
tag.aticdn.net

### ISSUE THREAD

**Issue by smed79** [StevenBlack/hosts#2090]
Hi,

blocking `tag.aticdn.net` break the video player at `information.tv5monde.com`

e.g. `https://information.tv5monde.com/video/etats-unis-bataille-politique-autour-de-l-immigration`

Thank you.

**Comment by FadeMind** [comment]
@smed79 @StevenBlack upstream whitelist https://oisd.nl/excludes.php?w=tag.aticdn.net

**Comment by FadeMind** [comment]
@smed79 better contact directly with maintainer of https://winhelp2002.mvps.org/hosts.htm

`To contribute a listing for our resources, or any other comments: winhelp2002 AT gmail DOT com`

Here is jut raw.

**Comment by smed79** [comment]
> better contact directly with maintainer

Done via email.
