### ISSUE TITLE
Add these domains

### ISSUE THREAD

**Issue by CassiusBETA** [StevenBlack/hosts#2091]
restart-api.palmplaystore.com
api.hisavana.com
common.xshareapp.com
hisavana.com
toolmatrix.plus

From this app (Shows ads with these domains)
https://play.google.com/store/apps/details?id=com.transsion.phonemaster&hl=en&gl=US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dphone+master&pcampaignid=APPU_1_FDEnY4-yFrnU2roPltuSkA0

**Comment by StevenBlack** [comment]
Thanks for this @CassiusBETA.

To be honest I hate issues framed like this.

* block these domains 
* list of domains
* no explanation, no motivation, just a link encrusted with UTM garbage that always seems to lead to a dead end, or a rabbit hole of nonsense.

Essentially, "You figure it out @StevenBlack".

No thanks. I'm not clicking that link.  I hope you understand why.

Closing.
