### ISSUE TITLE
Fix for "forms.office.com"

### ISSUE THREAD

**Issue by lyrad87** [StevenBlack/hosts#2092]
Crosspost from https://github.com/nextdns/metadata/pull/1074

> Can't start when "Click to start" is pressed
>
> The domain` c.office.com` has been CNAME blocked `c.msn.com` by `Steven Black's hosts` and `Ad-wars`
>
> Link: https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAO__SYWlsFUMFZERjEzMTRNS0JCRjVaWVExRkZTMEtGWi4u

I don't know if Ad-wars is an upstream source of yours, so I thought I mention this person's issue here.

Thanks for all you do!
Cheers

**Comment by bigdargon** [comment]
Adaway reported https://github.com/AdAway/adaway.github.io/issues/348
Dan Pollock – [someonewhocares](https://someonewhocares.org/) emailed

**Comment by StevenBlack** [comment]
Thanks everybody!

Closing.
