### ISSUE TITLE
Minecraft user presence and AB testing

### ISSUE THREAD

**Issue by nandlab** [StevenBlack/hosts#2093]
I have installed the official Minecraft Launcher and analyzed the HTTPS traffic with mitmproxy. I found a few suspicious domains which can probably be blocked. I did not try to block them yet, but I just wanted to share my analysis.

I will tell about the effect of blocking later.

## User Presence
Domain: `userpresence.xboxlive.com`

### Usage
POST request to `userpresence.xboxlive.com/users/xuid({xuid})/devices/current/titles/current` to tell Microsoft that you (user with xuid) are present. These requests happen every 5 minutes when the launcher is open. This behaviour cannot be disabled in the launcher.
[This](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/reference/live/rest/uri/presence/uri-usersxuiddevicescurrenttitlescurrentpost) is what Microsoft says about this request.

### Possible Side Effects when Blocked
The API to find out if other users are online is on the same domain, so it will not work. But I do not see any way to see the presence of other users in the launcher anyway, so maybe this information is not even accesible to normal users.

## AB Testing?
Domain: `xboxab.com`

### Usage
When I opened the Minecraft launcherm, the first GET request to `https://www.xboxab.com/ab` returned the following JSON:
```
{
    "AssignmentContext": "mctes210cf:30346368;mctca895:30470918;mctca431:30470919;mctca657:30470906;mctca973:30470912;mctca585
:30475207;mctca111:30475209;mctca987:30475208;mcbedrockpreview22:30552877;gamescom22:30554466;",
    "Configs": [
        {
            "Id": "MCLauncher",
            "Parameters": {
                "TCADOBootstrapMigrationLinux": true,
                "TCADOBootstrapMigrationMacOS": true,
                "TCADOBootstrapMigrationWin32": true,
                "TCADOMigrationGameCore": true,
                "TCADOMigrationLinux": true,
                "TCADOMigrationMacOS": true,
                "TCADOMigrationWin32": true,
                "TestBoolean": false,
                "gamescom22": true,
                "mcbedrockpreview22": true
            }
        }
    ],
    "Features": [
        "mctes210cf",
        "mctca895",
        "mctca431",
        "mctca657",
        "mctca973",
        "mctca585",
        "mctca111",
        "mctca987",
        "mcbedrockpreview22",
        "gamescom22"
    ],
    "FlightingVersion": 53518085,
    "Flights": {
        "2v5c": "mctes210cf",
        "3nyi": "mctca895",
        "3nyk": "mctca431",
        "3nyl": "mctca657",
        "3nym": "mctca973",
        "3o2v": "mctca585",
        "3o2w": "mctca111",
        "3o2x": "mctca987",
        "4ak2": "mcbedrockpreview22",
        "4b0t": "gamescom22"
    },
    "ImpressionId": <some hex value>,
    "ParameterGroups": []
}
```
Afterwards the GET requests to `https://www.xboxab.com/ab` repeat 15 minutes, but it starts returning `304 Not Modified`.
It sends a `X-MSEDGE-CLIENTID` as a HTTP header, which makes the client identifiable.

To me it looks like some kind of forced [A/B testing](https://en.wikipedia.org/wiki/A/B_testing) experiment, where certain features are enabled or disabled on the client.

### Side effects when blocked
The launcher will probably work in the default configuration.

**Comment by nandlab** [comment]
I have blocked these domains and Minecraft single player still works. I have to check multiplayer though.

**Comment by StevenBlack** [comment]
Thank you for this @nandlab.

@jamierocks can you please evaluate this for inclusion in your list?  Thanks!

**Comment by jamierocks** [comment]
### User Presence

I'm generally hesitant when it comes to the Xbox services APIs, since they are/can be used by such a large pool of games - and its very difficult to know what and how they're used by those games. Minecraft is somewhat of an oddity as it doesn't really integrate with Xbox a great deal (user-facing), but plenty of others do - and it's those that stand to be broken.

### AB Testing

That does indeed look like AB testing - is there any precedent for blocking such domains by lists consumed by hosts? I'm not opposed to adding a second list to minecraft-hosts to account for these (currently I only target tracking domains, but open to expansion).

**Comment by StevenBlack** [comment]
@jamierocks this is your call. I don't Minecraft. So I don't know.

Closing this here, leaving this in your capable hands.
