### ISSUE TITLE
tracking site: hits.sh

### ISSUE THREAD

**Issue by moralground** [StevenBlack/hosts#2095]
hits.sh describes itself as a "Hit Counter for Your GitHub or Any Kind of Websites You Want."

In reality this just means IP harvesting and logging. It's a site that gets loaded silently in the background, unbeknownst to users visiting pages. I'd like to propose we add it to the host list.

**Comment by StevenBlack** [comment]
Thank you Jeremy @moralground.  This has been added.

Closing.
