### ISSUE TITLE
Youtube ads hosts

### ISSUE THREAD

**Issue by hunggiadao** [StevenBlack/hosts#2096]
I noticed that some Youtube videos have ads blocked, some don't (videos from IGN channel for example). I looked up some repos and found a few Youtube hosts. Can you check and add these hosts to your file?

https://github.com/Ewpratten/youtube_ad_blocklist
https://gist.github.com/anilshanbhag/7576643
http://sobolev.us/remove-youtube-ads/
https://www.reddit.com/r/dropgoogle/comments/5tnjxl/block_youtube_ads_2017_hosts_file/

Also I don't know if hosts file can block ads on Youtube in place of an adblocker. Please let me know. Thanks a lot.

**Comment by gothic-bum** [comment]
Many YouTube ads are served first-party, so they cannot be blocked on the DNS level (e.g. via hosts file) without blocking YouTube itself.
  
JavaScript injection is therefore used by many content blocking extentions (e.g. uBlock Origin) to block YouTube ads by removing specified properties from requests made using `JSON.parse()` and/or `Response.json()`.

For more detail, see:
https://github.com/gorhill/uBlock/wiki/Resources-Library#json-prunejs-
https://github.com/easylist/easylist/wiki/Youtube-Issues

**Comment by StevenBlack** [comment]
Hi Hung @hunggiadao thank you for this.

We have many closed issues here about Youtube and its domains and subdomains.

I feel we're in a good place right now.  I think we're doing all we can.

As @gothic-bum explains, this isn't strictly a hosts file problem.

Closing.
