### ISSUE TITLE
Not a gambling site

### ISSUE THREAD

**Issue by eeerm** [StevenBlack/hosts#2097]
pixabay.com in the gambling section is a free stock photo website

**Comment by StevenBlack** [comment]
Thank you @eeerm.

Ping @sinfonietta can you evaluate this, since this is included via your source list?  Looks like a mistake.

**Comment by Sinfonietta** [comment]
@StevenBlack @eeerm yes thank you fixed.

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta closing.
