### ISSUE TITLE
Renault car vendor API is blocked (gigya.com)

### ISSUE THREAD

**Issue by thierolm** [StevenBlack/hosts#2098]
Since some days the Renault vhicle API domains (gigya.com) are blocked by your hosts file, which is used by pihole project
Could U please check and remove the correspondig block entries?

API URL: https://renault-api.readthedocs.io/en/latest/reference/gigya.html
Official german renault URLs/Domains: https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_de_DE.json

**Comment by metanoia02** [comment]
This domain is also used for The Open University student website.

**Comment by StevenBlack** [comment]
Hi Markus @thierolm thank you for this.

Which `gigya.com` subdomain is specifically required here?  Same question for you @metanoia02.

Various `gigya.com` subdomains are blocked by four of our curators. Unless you can provide the specific `gigya.com` subdomain, and someone can show that it isn't used for tracking, then this won't change.

So I need more specific info.

**Comment by thierolm** [comment]
Hi Steven,
there are several projects on git, which are providing Renault vehicle informations.
I'm using https://github.com/evcc-io/evcc which is using **accounts.eu1.gigya.com** domain to load my car parameters (ZOE).
There are also other git projects like https://github.com/edent/Renault-Zoe-API.
In one of its issues the My Reanult App API Domains are named: https://github.com/edent/Renault-Zoe-API/issues/18

It would be really great if your host list would not block

- accounts.eu1.gigya.com.

Its necessary to login and get the token for the My Renault app: https://apps.apple.com/de/app/my-renault/id1440073013

**Comment by StevenBlack** [comment]
Thanks Markus @thierolm.  We don't block `accounts.eu1.gigya.com`.

As for everything else, thank you for those links but going down rabbit holes, looking for meaning, is not my gig. Not what I signed-up for.

Again, I need specific `gigya.com` subdomains to consider so I can route this request to the proper upstream curator(s). Everything else is just noise.  

So please, can you distill "*(where) My Reanult App API Domains are named*" and then tell me specifically, which domains?

**Comment by thierolm** [comment]
I'm using pihole+unbound docker image.
pihole uses by default https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts as adlist.
In this file you can find **eu1.gigya.com**.
![image](https://user-images.githubusercontent.com/77847348/192339898-e4223479-fb6a-4dd1-ae66-b689dc23a0f9.png)

**Comment by StevenBlack** [comment]
@thierolm you said, twice: **`accounts.eu1.gigya.com`** 🙄 

Why is this so hard? Just tell me which domains we need to look at.

I'm closing this issue now. When and if you start understanding what's required, I'll consider it.  Stop wasting my time.
