### ISSUE TITLE
German HbbTV image.ard.de

### ISSUE THREAD

**Issue by realzoulou** [StevenBlack/hosts#2099]
Line # 19328:
`0.0.0.0 image.ard.de`
belongs to German public TV broadcast station "ARD" aka "DasErste" https://www.ard.de/

image.ard.de is used by the Hybrid broadcast broadband TV (HbbTV) service of this station, used for streaming video content with SmartTVs.
See also (German) https://blog.leon-wallis.de/mediatheken-pi-hole , which describes how to whitelist image.ard.de in Pi-hole.

Can `image.ard.de` please be removed from `hosts `file? It **is** a trust-able server.

**Comment by gothic-bum** [comment]
> Can `image.ard.de` please be removed from `hosts `file? It **is** a trust-able server.

How is it a "trust-able server"?

`image.ard.de` is an alias for the CNAME `image-ard-de-cddc.at-o.net` which **is** a tracker.

**Comment by realzoulou** [comment]
Thanks a lot for opening my eyes. I should have checked this upfront using any of the DNS lookup web pages.
