### ISSUE TITLE
0.0.0.0 != localhost == 127.0.0.1

### ISSUE THREAD

**Issue by espress0** [StevenBlack/hosts#21]
Please replace this line "0.0.0.0 localhost" to "127.0.0.1 localhost".
"0.0.0.0 localhost" is incorrect.

(I don't know why, I just can't make a pull request.)

**Comment by steveriley** [comment]
For the use here in a hosts file, 0.0.0.0 might result in faster behavior for certain browsers and operating systems. In fact, you can just use a single 0 rather than 0.0.0.0 and reduce the size of the file, too.

http://www.dslreports.com/forum/r16790135-Large-Hosts-file-0-0-0-0-or-127-0-0-1
http://www.dslreports.com/forum/r24621780-hosts-127-0-0-1-vs-0-0-0-0
https://www.google.com/?gws_rd=ssl#q=0.0.0.0+or+127.0.0.1+in+hosts+file

**Comment by StevenBlack** [comment]
> you can just use a single 0 rather than 0.0.0.0 and reduce the size of the file, too.

@steveriley well blow me down.  Isn't THAT interesting!  Thanks!

**Comment by StevenBlack** [comment]
Added label 'enhancement` — going to try `0` in lieu of `0.0.0.0` because, man, that rocks.

**Comment by StevenBlack** [comment]
OK the latest commit now uses `0` instead of `0.0.0.0`.  Works great +1

**Comment by dgutkowsky** [comment]
well, under Windows 10 "0 instead of 0.0.0.0" does not work for me...
I had to replace with 0.0.0.0

**Comment by StevenBlack** [comment]
OK.  I concede :-)

I've just updated the hosts file which uses 0.0.0.0 now.

Thanks for all the input!

**Comment by steveriley** [comment]
Well I feel pretty bad about that, sorry. For a 0 being the same thing as 0.0.0.0, I was just basing it on what I read. Next time, I'll test something myself before confirming it on forum like this.

**Comment by dgutkowsky** [comment]
For the record:
there should be also "127.0.0.1 localhost", not  "0.0.0.0 localhost" :)
cheers

**Comment by espress0** [comment]
> there should be also "127.0.0.1 localhost", not "0.0.0.0 localhost" :)

+1

0.0.0.0 is for not-localhost
127.0.0.1 is for localhost

localhost should not be 0.0.0.0, because many software expect localhost is 127.0.0.1.

**Comment by StevenBlack** [comment]
@espress0 [line 8 of the current hosts file](https://github.com/StevenBlack/hosts/blob/master/hosts#L8) says

    127.0.0.1 localhost

Have a look :-)
