### ISSUE TITLE
Why are location services included?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [StevenBlack/hosts#210]
I installed software that needs a geo-location service to tell me where the server I’m connected to is located. I discovered that several of them are being blocked by the hosts file. WHY?

freegeoip.net
gd.geobytes.com
geoplugin.net
ip-api.com

**Comment by StevenBlack** [comment]
Because we aggregate several reputable and well-curated sources.

These are likely blocked for very good reasons because the sources we aggregate are trustable.  They are not infallible.  If you have a problem, please take it up with them.

Closing, and locking.
