### ISSUE TITLE
eu1.gigya.com

### ISSUE THREAD

**Issue by thierolm** [StevenBlack/hosts#2101]
Hi,

blocking `eu1.gigya.com` (line #7195)
breaks the My Renault App (Android+IOS) using `accounts.eu1.gigya.com` to login.

App in Google-Playstore: https://play.google.com/store/apps/details?id=com.renault.myrenault.one.fr

Thank you.

Pls check `dig` output:
```sh
thierolm@tserver:~$ dig accounts.eu1.gigya.com

; <<>> DiG 9.16.1-Ubuntu <<>> accounts.eu1.gigya.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26813
;; flags: qr rd ra; QUERY: 1, ANSWER: 10, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;accounts.eu1.gigya.com.                IN      A

;; ANSWER SECTION:
accounts.eu1.gigya.com. 280     IN      CNAME   farm5.eu1.gigya.com.
farm5.eu1.gigya.com.    524     IN      CNAME   lb.eu1.gigya.com.
lb.eu1.gigya.com.       240     IN      A       52.31.157.92
lb.eu1.gigya.com.       240     IN      A       52.17.121.244
lb.eu1.gigya.com.       240     IN      A       52.19.57.181
lb.eu1.gigya.com.       240     IN      A       54.229.120.124
lb.eu1.gigya.com.       240     IN      A       52.30.9.119
lb.eu1.gigya.com.       240     IN      A       52.212.156.205
lb.eu1.gigya.com.       240     IN      A       52.17.82.217
lb.eu1.gigya.com.       240     IN      A       52.49.16.186

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Di Sep 27 18:11:49 CEST 2022
;; MSG SIZE  rcvd: 242
```

**Comment by StevenBlack** [comment]
Markus @thierolm hosts files work with fully qualified domains.  

The domains `eu1.gigya.com` and `accounts.eu1.gigya.com` are NOT related in a hosts file context.  Blocking `eu1.gigya.com` does NOT block `accounts.eu1.gigya.com`.

There is no "inheritance", no wildcards, with hosts files.

I need to know, which SPECIFIC domains are required by this car maker so I can route this to the proper upstream list.

It's quite possible that when Renault decided to use `gigya.com` for whatever services they think they need, they place their customers in a compromised position.

This list serves people who do not want to be tracked. This trumps whatever car you drive.

**Comment by thierolm** [comment]
OK, thx understood, will continue my research ... and come evtentually back, when I'm having more insights.
