### ISSUE TITLE
ads trackers

### ISSUE THREAD

**Issue by trackerct** [StevenBlack/hosts#2104]
for
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

iot-logser.realme.com
iot-eu-logser.realme.com
iriscoremetadataprod.blob.core.windows.net
performance.radar.cloudflare.com
applog.matrix.easebar.com
sigma-statistics-push.proxima.nie.easebar.com
mcount.easebar.com
who.nie.easebar.com
appdump.nie.easebar.com
usermetrics.lidlplus.com
search-log-1.tapatalk.com
lidlplusprod.blob.core.windows.net
self.events.data.microsoft.com
mon-va.tiktokv.com
collect.analytics.unity3d.com
functional.events.data.microsoft.com
androidtvwatsonfe-pa.googleapis.com
v10.events.data.microsoft.com
statsfe2.update.microsoft.com
global.asimov.events.data.trafficmanager.net
onedscolprdcus09.centralus.cloudapp.azure.com
edge.activity.windows.com
edge.activity.windows.com.akadns.net
edge-global.activity.windows.com.akadns.net
edge-emeu1.activity.windows.com.akadns.net
pf2am3-edge.activity.windows.com.akadns.net
a1h91ecnmw3isq-ats.iot.us-west-1.amazonaws.com
unagi.amazon.com
data.media-lab.ai
toblog.tobsnssdk.com
www.adspirit.com
cdn.consentmanager.mgr.consensu.org
consentmanager.mgr.consensu.org
crm.adflex.com.tr
ic3.events.data.microsoft.com
browser.events.data.microsoft.com
browser.events.data.msn.com
report-edge.agora.io
api-js.datadome.co
api.leanplum.com
log.core.cloud.vewd.com
customerevents.netflix.com IoT Telemetry
nrdp.nccp.netflix.com IoT Telemetry
api.miwifi.com
settings.data.microsoft.com
dlwnextsetting.blob.core.windows.net
evoke-windowsservices-tas.msedge.net
web.diagnostic.networking.aws.dev
psstats.superkinglabs.com
livelogs.slike.in
report-oversea.agora.io
report-oversea2.agora.io
report.banorte.glassboxdigital.io
redevents-bigdata.redefine.pl
total-rekall.metrics.indazn.com
self-events-data.trafficmanager.net
onedscolprdeus02.eastus.cloudapp.azure.com
onedscolprdcus01.centralus.cloudapp.azure.com
4ae1981d8d1a370d08bf3d24f50f5baf47ef1b62.cws.conviva.com
hpoahhuy2rocr9xb2kii0o2xeetb41663016176.uaid.imrworldwide.com
dishanalyticsandtesting.sc.omtrdc.net
tuplogpublic.bangcdn.net
akoss.bangcdn.net
mobile-data.onetrust.io
crash-reporting.duowan.com
sla-intl.trustlook.com
plausible.io
cdn.ftd.agency
suphelper.com
go.trouter.skype.com

**Comment by gothic-bum** [comment]
[Once again](https://github.com/StevenBlack/hosts/issues/2100), you are requesting to have a bunch a domains blocked with no specific explanation of why they should be blocked.

You also need to consider (or ideally determine) if the blocking of any of these domains could cause site/app breakage.
As just single example, `settings.data.microsoft.com` is used for Windows apps to dynamically update their configuration.

**Comment by trackerct** [comment]
iot-logser.realme.com -realme mobile tracker

iot-eu-logser.realme.com -realme mobile tracker

iriscoremetadataprod.blob.core.windows.net 

performance.radar.cloudflare.com -cloudflare tracker
 
applog.matrix.easebar.com -app tracker

sigma-statistics-push.proxima.nie.easebar.com -tracker/stats

mcount.easebar.com -app tracker/counter

who.nie.easebar.com -ip tracker

appdump.nie.easebar.com -apptracker

usermetrics.lidlplus.com -tracker/metrics

search-log-1.tapatalk.com -tracker

lidlplusprod.blob.core.windows.net

self.events.data.microsoft.com -event tracker

mon-va.tiktokv.com -tiktok tracker

collect.analytics.unity3d.com -tracker/analytics

functional.events.data.microsoft.com -event tracker

androidtvwatsonfe-pa.googleapis.com -android watson tracker

v10.events.data.microsoft.com -events tracker

statsfe2.update.microsoft.com -update tracker

global.asimov.events.data.trafficmanager.net -events tracker
 


edge.activity.windows.com -activity tracker

edge.activity.windows.com.akadns.net -activity tracker

edge-global.activity.windows.com.akadns.net -activity tracker

edge-emeu1.activity.windows.com.akadns.net -activity tracker

pf2am3-edge.activity.windows.com.akadns.net -activity tracker
a1h91ecnmw3isq-ats.iot.us-west-1.amazonaws.com -iot tracker

unagi.amazon.com -amazon ads

data.media-lab.ai -app tracker

toblog.tobsnssdk.com -app tracker

www.adspirit.com -ads

cdn.consentmanager.mgr.consensu.org -ads

consentmanager.mgr.consensu.org -ads

crm.adflex.com.tr -ads

ic3.events.data.microsoft.com -events tracker

browser.events.data.microsoft.com -events tracker

browser.events.data.msn.com -events tracker

report-edge.agora.io -tracker

api-js.datadome.co -ads tracker

api.leanplum.com -tracker

log.core.cloud.vewd.com -tracker

customerevents.netflix.com IoT Telemetry

nrdp.nccp.netflix.com IoT Telemetry

api.miwifi.com -wifi tracker



web.diagnostic.networking.aws.dev -diagnostic tracker

psstats.superkinglabs.com -tracker stats

livelogs.slike.in -tracker

report-oversea.agora.io -tracker

report-oversea2.agora.io -tracker

report.banorte.glassboxdigital.io -tracker

redevents-bigdata.redefine.pl -events tracker

total-rekall.metrics.indazn.com -tracker metrics

self-events-data.trafficmanager.net -events tracker



dishanalyticsandtesting.sc.omtrdc.net -tracker analytics

tuplogpublic.bangcdn.net -app tracker

akoss.bangcdn.net -app tracker

mobile-data.onetrust.io -tracker

crash-reporting.duowan.com -crash analytics

sla-intl.trustlook.com
plausible.io -tracker

cdn.ftd.agency -ads

suphelper.com -tracker

go.trouter.skype.com -skype tracker

**Comment by gothic-bum** [comment]
Once again:
You need to determine if the blocking of any of these domains could cause site/app breakage, and if so, clearly state what the impact is.  

As an example using just one of the domains you are requesting to block:
`self.events.data.microsoft.com` is used to connect to the Microsoft 365 admin center's shared infrastructure, including Office in a browser.  If this is blocked, users won't be able to save documents to the cloud or see their recently used documents.

**Comment by StevenBlack** [comment]
Thank you for your input Goth @gothic-bum.

@trackerct thank you for these suggested domains, but I respectfully decline to add these.  Mostly because your Github account is barely a week old, and you're anon with no track record. I hope you understand.

Closing.

**Comment by trackerct** [comment]
co-vcode-api.vivoglobal.com
co-vcode-h5-od.vivoglobal.com
asia-vcode-or.vivoglobal.com
asia-exstatic.vivo.com
vcm-static.vivo.com
asia-commonitor-stsdk.vivoglobal.com
asia-romsp-unifyconfig.vivoglobal.com
asia-stp.vivoglobal.com
asia-vcode-api.vivoglobal.com

freegeoip.live
geocheck.sim-technik.de
ipapi.co
logs.browser-intake-datadoghq.com
rum.browser-intake-datadoghq.com
analytics.coollabs.io
statistic.live.126.net
m.equinoxplus.com
akamai.tiqcdn.com
app.anch.co
crash.uu.easebar.com
mobile.uu.easebar.com
uumov.fp.ps.easebar.com
uuov.fp.ps.easebar.com
uu.fp.ps.netease.com
mg.uu.163.com
adx.adsgaga.com
177657.tracking.hyros.com
ma1226-r.analytics.edgesuite.net
netperform-lz.vodafone.com
js-eu1.hscollectedforms.net
forms-eu1.hsforms.com
restapi.netmera.com
eturkcell.netmera.com
adiu.amap.com
alimelog.taobao.com
localization.services.pbs.org
cc-api-data.adobe.io
app-1c835e5474e6a378.mobileapi.usebutton.com
logs.us-east-1.amazonaws.com
vmweb-va.byteoversea.com
mcs-va.tiktok.com.edgekey.net
appad.cyberlink.com
abtest.tantanapp.com
report.tantanapp.com
client-tracking.tantanapp.com
sc-report.tantanapp.com
deviceid.tantanapp.com
counter.tantanapp.com
lorempixel.com
analytics-lal-nba.yinzcam.com
ads-lal-nba.yinzcam.com
api.adtech.etermax.com
gdpr-tcfv2.sp-prod.net
mynt-test-privacy.my.onetrust.com
analytics.meaww.com
vmweb-va.byteoversea.com
mssdk-va.tiktok.com
sf16-muse-va.ibytedtos.com
sotalcloud.blob.core.windows.net
xtrapath1.izatcloud.net
xtrapath2.izatcloud.net
xtrapath3.izatcloud.net
fl-badger-prod-statscluster.moonfroglabs.com
internetbrands-d.openx.net


log.uu.easebar.com
crash.uu.easebar.com
mobile.uu.easebar.com
uumov.fp.ps.easebar.com
uuov.fp.ps.easebar.com
uu.fp.ps.netease.com
mg.uu.163.com
adx.adsgaga.com
log-mediation.smartvisionapp.com
cfg.smartvisionapp.com
cfg-mediation.smartvisionapp.com
wcpstatic.microsoft.com
statics-marketingsites-neu-ms-com.akamaized.net
mybbc-analytics.files.bbci.co.uk
a1.api.bbc.co.uk
cdn3.optimizely.com
report.netgear.glassboxdigital.io
api.instabug.com
cdn.optimizely.com
s2s.aniview.com
zerossl.crt.sectigo.com
stream-us-east-1.getpublica.com
s0.2mdn.net
status.metaxads.com
rtbus.ssp.metaxads.com
policy.seraphic-corp.com
uk-script.dotmetrics.net
clientlog.baechat.my
vmweb-va.byteoversea.com
mssdk-va.tiktok.com
sf16-static.i18n-pglstatp.com
sf16-muse-va.ibytedtos.com
analytics.zenly-app.com
log.tpns.sgp.tencent.com
vibeacon.onezapp.com
htrace.wetvinfo.com
mtrace.wetvinfo.com
vibeaconstr.onezapp.com
btrace.wetvinfo.com
vtrace.wetvinfo.com
logs.us-east-1.amazonaws.com
g792337343.co
177657.tracking.hyros.com
b-code.liadm.com
seo.apps.avada.io
instant.page
cdn-app.pathfactory.com
consent.cookiefirst.com
freegeoip.live
cdn-cs.conductor.com
my.hellobar.com
snippet.growsumo.com
partnerlinks.io
partnerstack.ada.support
static.ada.support
rollout.ada.support
grsm.io
cdn.subscribers.com
utt.impactcdn.com
e1e6d41a09e1.cdn4.forter.com
ws.zoominfo.com
api.indicative.com
log-va.tiktokv.com
ads.dogusdigital.com
rt.visilabs.net
tags.bluekai.com
collector.puhutv.com
lgr.visilabs.net
ma1226-r.analytics.edgesuite.net
ads.dygdigital.com
api.vip.miui.com
sdkconfig.ad.xiaomi.com
data.sec.miui.com
an.yandex.ru
sapphire-api.target.com
goto.target.com
uefa.sb.blueconic.net
eu1.clevertap-prod.com
public.edigitalresearch.com
x.everestop.io
api.speedspot.org
b2.etrality.com
net.etrality.com
a.58dac16e7b2c86c19cfe48914a6e8fcdac9ae06fe5cf53369beaa45b.com
survey.survicate.com
sdk.iad-06.braze.com
o540540.ingest.sentry.io
mam.netease.com
wannos.127.net
statistic.live.126.net
mam6.netease.com
zn2rjw8v8ecfgyigt-paypalxm.siteintercept.qualtrics.com
c.paypal.com
b.stats.paypal.com
o436621.ingest.sentry.io
api.segment.io
api2.branch.io
d32z5ni8t5127x.cloudfront.net
tnc16-alisg.isnssdk.com
tnc16-useast1a.byteoversea.com
tnc16-useast1a.isnssdk.com
tnc16-alisg.byteoversea.com
ads.api.vungle.com
gdl.news-cdn.site
api.imotech.tech
da.anythinktech.com
tk.anythinktech.com
api.anythinktech.com
analytics.coollabs.io
coolify.io
coollabs.io
direct.applog-lb-texas.useast5.byteoversea.net
mcs-va.tiktok.com
mcs-va.tiktok.com.edgekey.net
auditrecording-pa.googleapis.com
cmdts.ksmobile.com
sa.api.intl.miui.com
qualcomm.sc.omtrdc.net
metrics.brightcove.com
edge-elb.api.brightcove.com
xtrapath1.izatcloud.net
xtrapath2.izatcloud.net
xtrapath3.izatcloud.net
www-alv.google-analytics.com
secure.insightexpressai.com
alb.reddit.com
events.redditmedia.com
cdn.parsely.com
browser-http-intake.logs.datadoghq.com
o248881.ingest.sentry.io
s13.cnzz.com
stream-us-east-1.getpublica.com
j.6sc.co
cdn.b0e8.com
polyfill.io
sotalcloud.blob.core.windows.net
zncvomiueeqmfxynn-tracfone.siteintercept.qualtrics.com
bf37534ykp.bf.dynatrace.com
imagesvc.meredithcorp.io
srtb.msn.com
cn.bing.com
in.appcenter.ms
static-mon.yandex.net
collect.tealiumiq.com
smetrics.vodafone.co.uk
vodafoneuk.tt.omtrdc.net
api.bugfender.com
netperform-lz.vodafone.com
gcpsmapi.vodafone.com
hellosmpl.com
lb.revotas.com
revocdn.revotas.com
eturkcell.netmera.com
sdkapi.netmera.com
restapi.netmera.com
certify-js.alexametrics.com
id.ad-plus.com.tr
searchanalytics.turkcell.com.tr
fast.fonts.net
log.byteoversea.com
gecko-sg.byteoversea.com
mon.byteoversea.com
mon.isnssdk.com
mon-va.tiktokv.com
api-eu1.hubspot.com
js-eu1.hscollectedforms.net
forms-eu1.hsforms.com
js-eu1.hs-banner.com
js-eu1.hs-scripts.com
livewp.site
ntm.netmera-web.com
js-eu1.usemessages.com
cdn.netmera-web.com
[www.tapresearch.com](http://www.tapresearch.com/)
mr.fullstory.com
adminlogin.liveperson.net
api.pushio.com
mobile-http-intake.logs.datadoghq.eu
sdk.fra-01.braze.eu
h.trace.qq.com
oth.eve.mdt.qq.com
othstr.beacon.qq.com
oth.str.mdt.qq.com
btrace.qq.com
iqoption.com
event.id-iqoption.com
api3.siftscience.com
cdn.krxd.net
service.cmp.oath.com
o77029.ingest.sentry.io
m.stripe.com
bf97804kct.bf.dynatrace.com
trk.storyly.io
track.saygames.io
tag.targeting.unrulymedia.com
rclog.rcplatformhk.com
alogsus.umeng.com
alogus.umeng.com
rcscdata.livuchat.com
sdk-api-v1.singular.net
subway-surfers.sng.link
click.snapchat.com
at.iocnt.net
logs152.xiti.com
config-at.iocnt.net
config.mpianalytics.com
sdk.privacy-center.org
scmetrics.shell.com
dc.services.visualstudio.com
shell.data.adobedc.net
shell.tt.omtrdc.net
mobile-collector.newrelic.com
api.rudderlabs.com
hm.baidu.com
mc2m55m4y9pvd1q7lngvt61w9tjq.device.marketingcloudapis.com
swasc.kaufland.com
pok.mintegral.net
vlogerads.com
l.urioy.com
api.urioy.com
api-sdk.datadome.co
o315582.ingest.sentry.io
o502112.ingest.sentry.io
customers.kameleoon.com
public.profitwell.com
static.fbot.me
3zutpy0bjn.kameleoon.eu
campaign.fbot.me
api.iterable.com
static.hotjar.com
o534899.ingest.sentry.io
log.go.com
unid.go.com
identity.mparticle.com
config2.mparticle.com
dominospizza.sc.omtrdc.net
dominos.bttn.io
app-1c835e5474e6a378.mobileapi.usebutton.com
l1-1.anzu.io
server.bidstack.com
pinpoint.us-east-1.amazonaws.com
tracker-api.my.com
ip4.tracker-api.my.com
cc-api-data.adobe.io
adobemobiledev.sc.omtrdc.net
csdkapi-policy.adobe.com
cc-api-behance.adobe.io
sensors.binance.cloud
c.riskified.com
h.online-metrix.net
log.bntrace.com
jpush.bntrace.com
[www.mokexapp.cloud](http://www.mokexapp.cloud/)
client-analytics.braintreegateway.com
get.venmo.com
widget.criteo.com
creditonebank.sc.omtrdc.net
mobile.confsettings.com
md-a-c.apptimize.com
click.emails.creditonebank.com
sdk.iad-05.braze.com
bf76686hfr.bf.dynatrace.com
o331365.ingest.sentry.io
regionconfig.amplitude.com
ipapi.co
balancer.voximplant.com
images-dl.taboola.com
o248881.ingest.sentry.io
servicemagic.sc.omtrdc.net
sdk.out.usbla.net
api-analytics.prod.birdapp.com
mobile-production.content-square.net
edge.adobedc.net
engage.vzw.com
scache.vzw.com
track.tenjin.com
static.site24x7rum.eu
salesiq.zoho.com
zohotagmanager.cdn.pagesense.io
apptics.zoho.com
ff54f-92afa.api.pushwoosh.com
post-log.pushwoosh.com
d0bc1-29659.api.pushwoosh.com
tags.bluekai.com
rt.visilabs.net
lgr.visilabs.net
datacollector-dre.dt.hicloud.com
zc.adswizz.com
a-fds.youborafds01.com
tls13.taboola.map.fastly.net
api64.com
co4.telecommand.telemetry.microsoft.com.akadns.net
geller-pa.googleapis.com
secure.leadforensics.com
admedo.activehosted.com
admedo.com
heapanalytics.com
kvinit-prod.api.kochava.com
events.split.io
ace.naver.com
lcs.naver.com
d3clybje3sun07.cloudfront.net
api2.branch.io
metrics2.data.hicloud.com
dnkeeper.hicloud.com
grs.dbankcloud.cn
grs.dbankcloud.asia
grs.platform.dbankcloud.ru
connectivitycheck.platform.dbankcloud.com
sdk-b.apptornado.com
sdk.appbrain.com
infoevent.startappservice.com
adsmetadata.startappservice.com
sdk-exchange.startappservice.com
adsmetadata.mobileadexchange.net
info.startappservice.com
pls.prd.mz.internal.unity3d.com
answers.chartboost.com
perf-events.cloud.unity3d.com
evt.mxplay.com
mxvp-feature-toggle-prod-1.zenmxapps.com
i.mxplayer.j2inter.com
live.mxplay.com
mon-va.byteoversea.com
mcs-va.tiktokv.com
platform.linkedin.com
mon-va.byteoversea.com
ipcheck.tmgrup.com.tr
api.segment.io
getir-prod.api.kustomerapp.com
consent.cookiebot.com
tr.hit.gemius.pl
gatr.hit.gemius.pl
ad01.tmgrup.com.tr
cdn.dimml.io
vsh.visilabs.net
cdn.cookie-script.com
static.axept.io
cdn.firstpromoter.com
loader.wisepops.com
app.mindbehind.com
ghmtr.hit.gemius.pl
static.bitlo.com
dc.services.visualstudio.com
cookiehub.net
fg8vvsvnieiv3ej16jby.litix.io
[www.clickcease.com](http://www.clickcease.com/)
[www.clarity.ms](http://www.clarity.ms/)
cdn.ywxi.net
dmxleo.dailymotion.com
vendorlist.dmcdn.net
sdk.iad-01.braze.com
alog.umengcloud.com
speedtest.dailymotion.com
corp.sts.microsoft.com
rum.browser-intake-datadoghq.com
logs.browser-intake-datadoghq.com
bestwesterninternati.tt.omtrdc.net
[www.datadoghq-browser-agent.com](http://www.datadoghq-browser-agent.com/)
s2.go-mpulse.net
p11.techlab-cdn.com
0.datadog.pool.ntp.org
jenson.api.swiftkey.com
telemetry.api.swiftkey.com
king-contenido-prod.secure2.footprint.net
p.midasplayer.com
servicelayer.king.com
ccss.play.king.com
o248881.ingest.sentry.io
mobile.yandexadexchange.net
report.appmetrica.yandex.net
imptrk.siteplug.com
cookie-cdn.cookiepro.com
api.theadex.com
de.ioam.de
config.ioam.de
lms.ebayk.liberty-prod.classifiedscloud.io
cdn.permutive.app
sanalytics.verizon.com
engage.vzw.com
cdp.cloud.unity3d.com
config.uca.cloud.unity3d.com
helium-rtb.chartboost.com
cdn.personaclick.com
assets.cookieseal.com
cdn-api.admost.com
med-api.admost.com
telve-3cf61.firebaseio.com
app.tr.adjust.com
datacollector-dre.dt.hicloud.com
remote.appsgeyser.com
config.appsgeyser.com
ads.appsgeyser.com
stat.appsgeyser.com
cdn.i-artserveis.net
scopely-wheeloffortune.adsbynimbus.com
adsgard.aprod.scopely.io
fenrir-resolver.aprod.scopely.io
6b73d00a-d4a1-4350-825a-cd3f49afa460.register.collector.scopely.io
wof.aia.apponboard.com
niantic.api.kws.superawesome.tv
infoevent.startappservice.com
hoverfly.papercrowns.com
get.geojs.io
mebed.dm-event.net
pebed.dm-event.net
tofu.dmcdn.net
r.remarketingpixel.com
[www.skassets.com](http://www.skassets.com/)
cdn.izooto.com
adsxyz.com
sdk.fra-01.braze.eu
nan46ysangt28eec.com
ad.particlenews.com
log.particlenews.com
toblog.tobsnssdk.com
wkrd.tingyun.com
plausible.io
rallydisprove.com
ad.mail.ru
htlb.casalemedia.com
colossalcoat.com
cmp.optad360.io
get.optad360.io
prg.smartadserver.com
ads.vidoomy.com
c2shb.ssp.yahoo.com
[www.adspirit.com](http://www.adspirit.com/)
adspirit.de
cdn.consentmanager.mgr.consensu.org
consentmanager.mgr.consensu.org
cdn.adspirit.de
crm.adflex.com.tr
adtarget.com.tr
link.medium.com
o43253.ingest.sentry.io
serve.tercept.com
events.mapbox.com
sdk-01.moengage.com
manager.smartlook.com
topapps-func.pinsightmedia.com
api.snapkit.com
ceres.iad-03.braze.com
kvinit-prod.api.kochava.com

**Comment by trackerct** [comment]
a.8392c6e79df6ad8a3ab1fa972ec327855198c2d4cdf46aacc93d0c76.com
api.apphud.com
sensors.yodo1api.com
conn-service-eu-03.allawnos.com
heytapmobi.com
heytapmobile.com
heytapdl.com
allawntech.com
allawnos.com
receiver.habby.mobi
crosspromo.voodoo.io
vs-api.voodoo-tech.io
remote-settings-v2.voodoo-tech.io
ip-api.com
adsdk.yandex.ru
visitor-service.tealiumiq.com
collect-eu-west-1.tealiumiq.com
collect.tealiumiq.com
mobile-sdk-lib-eu-1.brilliantcollector.com
b57f1629.api.splkmobile.com
exchange.buzzoola.com
data.videonow.ru
ad.adriver.ru
ssp.bidvol.com
match.ads.betweendigital.com
ads.adlook.me
px.adhigh.net
relap.io
mc.webvisor.org
statsb.nativeroll.tv
analytics.cn.ru
a.utraff.com
pub-eu.p.otm-r.com
smetrics.samsung.com
samsung.bttn.io
public-graylog.iadvize.com
api.iadvize.com
app-43ac17f771cc4393.mobileapi.usebutton.com
datingshall.life
js.nextpsh.top
lkpmprksau.com
vionito.com
forlumineoner.com
sevokop.com
t85itha3nitde.com
ad.mediawayss.com
informer.yandex.ru
track.swaptrap.live
analytics.helpukrainewinwidget.org
ad.mox.tv
s.znctrack.net
securecd-smnd.com
data.emb-api.com
config.emb-api.com
mobile-production.content-square.net
4420.api.swrve.com
4420.identity.swrve.com
4420.content.swrve.com
api.getblueshift.com
ampcid.google.com
news_uk.amp.permutive.com
srv.pixel.parsely.com
pac.thesun.co.uk
ccpa.sp-prod.net
elb.the-ozone-project.com
upratihun.fra-01.braze.eu
com-upday-main.collector.snplow.net
ccpa.sp-prod.net
dsh7ky7308k4b.cloudfront.net
edge.uniconsent.com
cdn.petametrics.com
uid.mavencoalition.io
amprtc.media.net
ad.turn.com
cm.adform.net
eb2.3lift.com
prebid-match.dotomi.com
prebid.a-mo.net
ssum.casalemedia.com
x.bidswitch.net
sync.go.sonobi.com
acdn.adnxs.com
ow.pubmatic.com
ping.chartbeat.net
query.petametrics.com
amp-edge.ccgateway.net
confiant-integrations.global.ssl.fastly.net
internetbrands-d.openx.net
js-sec.indexww.com
certify-amp.alexametrics.com
cdn.parsely.com
secure.quantserve.com
d15kdpgjg3unno.cloudfront.net
jelly.mdhv.io
dyv1bugovvq1g.cloudfront.net
ev.api.bdg.com
cmp.quantcast.com
tracker-api.my.com
ip4.tracker-api.my.com
localization.services.pbs.org
sdk-exchange.startappservice.com
da.chartboost.com
cdn2.inner-active.mobi
pad-v3.presage.io
sab.richaudience.com
analytics.rayjump.com
net.rayjump.com
live.chartboost.com
lazy.rayjump.com
policy.rayjump.com
configure.rayjump.com
infoevent.startappservice.com
trackdownload.startappservice.com
info.startappservice.com
adsmetadata.mobileadexchange.net
adsmetadata.startappservice.com
disney-magic-kingdom.extads.gameloft.com
report.dfs.glassboxdigital.io
mobile-sdk-lib-ca-1.brilliantcollector.com
mobile.eum-appdynamics.com
smetrics.discover.com
app.discover.com
m.equinoxplus.com
j.6sc.co
smetrics.autodesk.com
akamai.tiqcdn.com
app.anch.co
data.pendo.io
o547266.ingest.sentry.io
services.projone.net
o283670.ingest.sentry.io
go.onelink.me
idfp.tongdun.net
log-collector.shopee.tw
c-api-bit.shopeemobile.com
log-collector.shopee.sg
sdk.iad-06.braze.com
api.radar.io
creativecdn.com
mobileproxy.bluekai.com
ecn.dev.virtualearth.net
movip.wps.com
cloudservice14.kingsoft-office-service.com

angelfish.mydatamanagerapp.com
bluewhale-tbastro-02.mydatamanagerapp.com
common-api.smart-sense.org
api.smart-sense.org
analytics.zenly-app.com
log.tpns.sgp.tencent.com
vibeacon.onezapp.com
htrace.wetvinfo.com
mtrace.wetvinfo.com
vibeaconstr.onezapp.com
btrace.wetvinfo.com
vtrace.wetvinfo.com
logs.us-east-1.amazonaws.com
alimelog.taobao.com
adiu.amap.com
grs.platform.dbankcloud.ru
browserr-dre.dbankcdn.cn
hapselli.api.appboy.eu

**Comment by StevenBlack** [comment]
@trackerct please stop.

There is zero chance I'm accepting domains submitted like this.

We already block over a third of those you've listed here.

```
ghosts --clip
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 154,638
Bytes: 5.6 MB
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 323
Bytes: 10 kB
Intersection: 112 domains
```
