### ISSUE TITLE
Not a fake news site, but satire

### ISSUE THREAD

**Issue by martru118** [StevenBlack/hosts#2108]
thebeaverton.com shouldn't be in the fakenews block list as it is satirical

**Comment by StevenBlack** [comment]
Thank you for this @martru118.  I agree.

Mark @marktron can you remove The Beaverton from the Fake News list?  It's The Onion, only Canadian.

**Comment by StevenBlack** [comment]
Ping @marktron thanks.

**Comment by StevenBlack** [comment]
Thank you Mark @marktron and thank you for submitting this issue @martru118.

Closing.
