### ISSUE TITLE
learn.cisecurity.org is legit, repository for hardening guidelines on a wide range of systems. 

### ISSUE THREAD

**Issue by MNy03** [StevenBlack/hosts#2109]
Hi, 

Great list and whitelisted this one explicitly for my own installation for now. Check cisecurity.org for more info. 

Thanks for giving it your time of day. 

With kind regards,

**Comment by StevenBlack** [comment]
Hello @MNy03 thank you for this.

```
dig learn.cisecurity.org                                                                              10:51:22

learn.cisecurity.org.	300	IN	CNAME	go.pardot.com.
go.pardot.com.		5827	IN	CNAME	pi.pardot.com.
pi.pardot.com.		211	IN	CNAME	pi-ue1.pardot.com.
pi-ue1.pardot.com.	0	IN	CNAME	pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com.
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 10 IN A 34.237.219.119
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 10 IN A 3.92.120.28
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 10 IN A 3.215.172.219
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 10 IN A 18.208.125.13
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 10 IN A 52.54.96.194
```

So the domain `learn.cisecurity.org` is actually being served by `pardot.com`, whose domains are blocked by many of our upstream curators.  So de-listing `learn.cisecurity.org` would have no effect.  It's odious tracking, disguised.

Which goes to show, nothing is deemed "legit" here. If a domain engages in tracking, or sells its users, or distributes malware, scamware, or worse, it gets blocked.

Closing.
