### ISSUE TITLE
Why are location services included, Part deux.

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [StevenBlack/hosts#211]
It’s frustrating when [threads are closed](https://github.com/StevenBlack/hosts/issues/210#issuecomment-265939823) before you have a chance to respond.

On Dec. 8, 2016 Steven Black said
>we aggregate several reputable and well-curated sources.

>These are likely blocked for very good reasons because the sources we aggregate are trustable. They are not infallible. If you have a problem, please take it up with them.

I’m not about to waste more time contacting your several sources.
I appreciate the efforts to maintain the lists, but lately they’re causing more issues than I want to deal with.

AFAIK these aren’t trackers, they are location services:
freegeoip.net
gd.geobytes.com
geoplugin.net
ip-api.com

I doubt that freegeoip.net, an open-source location service, is part of a nefarious adware/malware/phishing/whatever ring that needs to be blocked.

>freegeoip.net provides a public HTTP API for software developers to search the geolocation of IP addresses. The freegeoip web server is free and open source.

Geobytes is shown as being part of rackspace.com, a cloud hosting service.

Since these sites are included in the file and I’m not about to keep removing them every time I update, I’ll no longer update. 32,000+ entries are a lot more protection than 95% of people have, and a lot more than I need.

Now you can lock this topic.

**Comment by blaqkr** [comment]
There's a pretty big section about how to create your own hosts file, and how to exclude domains from being added. The whole purpose of this repo is to combine several sources, if you find something's wrong then those are the ones you need to contact. This are the 2 options you have, but you choose to do nothing.

In the end, you are complaining to the wrong guy because of your laziness.

**Comment by StevenBlack** [comment]
@blaqkr 👍 

@GitTheHellOutaHere pause and think for a moment: what could marketers, spammers, and other nefarious agents ***possibly*** do with location tracking?   You know, maybe this repo just isn't for you.

**Comment by GitTheHellOutaHere** [comment]
They could maybe find out which city in the world I live in. OH NO! What ever would I do then?

I must be incredibly lucky (better buy a lotto ticket) because I’m not aware of _ever_ receiving spam or malware attacks based on my geographic region, even before I changed my hosts file.

Attackers don’t care _where_ you are, they want to get you _wherever_ you are.
They’re not going to knock on my firewall just because I live in X_city USA.

Lots of apps rely on geolocation services, so attempting to block them all in a list is counterproductive. In fact, only half the ones my newly-installed app uses are currently listed. Should I be worried about the others? **I’m not!**
