### ISSUE TITLE
Fakenews? ...[WARNING] self censorship at sight!

### ISSUE THREAD

**Issue by Shituation** [StevenBlack/hosts#2110]
RT is in fakenews category, that makes me think this will block to your view of the world which is probably tied to CNN, Fox news, BBC, Skynews and other western news sites.

Not a good thing to do.

**Comment by StevenBlack** [comment]
![disbelief](https://user-images.githubusercontent.com/80144/195433520-885a07af-66eb-43a3-9254-ad182210d106.gif)
