### ISSUE TITLE
Sites added to blocklist that prevent 4G/5G mobile IMS services on Vodafone.

### ISSUE THREAD

**Issue by Tricky-M** [StevenBlack/hosts#2111]
**False Blocks**

The following items that have been added to the block list https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts are preventing some of Vodafone's IMS services from functioning, for example RCS Chat (new version of SMS). This is shown by opening Google messages and withing Settings -> Chat the status when on network running a blocklist with these will continually say "Connecting...". 

Generally, *.ims.vodafone.com URI's are used for connecting to IMS services within the Vodafone network.

```
# [vodafone.com]
0.0.0.0 mplusps.ims.vodafone.com
0.0.0.0 mpluswf.ims.vodafone.com
```

Please could these be **removed** from blocklist.
(I assume that 'mplusps = messaging plus packet switched' and 'mpluswf = messaging plus WiFi')

Thanks

**Comment by StevenBlack** [comment]
Thank you for this @Tricky-M.

Ping @jawz101 what do you think? Thanks!

**Comment by jawz101** [comment]
I've stepped down from AdAway list maintenance

**Comment by StevenBlack** [comment]
@jawz101 I'm sorry to hear that.

Who should I ping for this?

**Comment by jawz101** [comment]
Oops I edited my reply above

**Comment by Tricky-M** [comment]
Didn't realise the association with the AdAway list, I also raised [AdAway #3403](https://github.com/AdAway/AdAway/issues/3403), which may be the incorrect location.
