### ISSUE TITLE
False Positive: nexusrules.officeapps.live.com

### ISSUE THREAD

**Issue by anxiouslelimo** [StevenBlack/hosts#2112]
<img width="626" alt="Untitled" src="https://user-images.githubusercontent.com/115996455/196190565-7c588850-66e2-4c9f-b1f0-4916c1e3d691.png">

Request to whitelist **nexusrules.officeapps.live.com**.
The following endpoints are used to connect to the Microsoft 365 admin center's shared infrastructure, including Office in a browser. For more info, see Office 365 URLs and IP address ranges. You can turn this off by removing all Microsoft Office apps and the Mail and Calendar apps. **If you turn off traffic for these endpoints, users won't be able to save documents to the cloud or see their recently used documents.**

**Comment by StevenBlack** [comment]
Thank you for this @anxiouslelimo.

I agree. This is removed in commit 6c9377b which will be included in the next release.
