### ISSUE TITLE
personaclick / tawk / efilli

### ISSUE THREAD

**Issue by trackerct** [StevenBlack/hosts#2114]
personaclick.com  :
Marketing Automation & One-Click Personalization Suite

PersonaClick offers a reliable intelligent toolset built for online stores. Keep all of your important customer data like gender, age, clothing and shoe size, body type, brand preference, and other niche-specific parameters in one place.

cdn-static.personaclick.com
cdn.personaclick.com
pictures.personaclick.com
static.personaclick.com
api.personaclick.com

tawk.to :
tawk.to makes it easy to deliver personalized and real time customer service
Monitor traffic on your website and be there when visitors need you most.

-Geo IP Tracking
-Unlimited Agents
-Track Sentiment
-Unlimited History
-Track Engagement
-Detailed Reporting
-Ban/Unban Visitors
-Agent Alerts

vsa98.tawk.to
vsa99.tawk.to
vsa78.tawk.to
vsa113.tawk.to
vsa31.tawk.to
vsa57.tawk.to
vsa107.tawk.to
vsa61.tawk.to
vsa19.tawk.to
vsa105.tawk.to
vsa8.tawk.to
va.tawk.to
embed.tawk.to

efilli.com :
Website is the systems that allow visitors to manage personal data shared with sites, allowing companies to examine these permissions and optimize tracking systems.

riza.efilli.com
cdn.efilli.com
fg8vvsvnieiv3ej16jby.litix.io

can you add blocklist please. thx

**Comment by StevenBlack** [comment]
Hi @trackerct thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
