### ISSUE TITLE
Remove saa.paramountplus.com from fake news & gambling hosts file

### ISSUE THREAD

**Issue by jdrch** [StevenBlack/hosts#2119]
The above domain is found in https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hostss. It is neither a fake news nor a gambling site. Paramount Plus is a streaming service like Netflix.

**Comment by gothic-bum** [comment]
> It is neither a fake news nor a gambling site. Paramount Plus is a streaming service like Netflix.  
  
`saa.paramountplus.com` is an alias for the CNAME `paramountplus.com.data.adobedc.net` which is a disguised tracker.

**Comment by StevenBlack** [comment]
Yup @gothic-bum is right.

```bash
$ dig  saa.paramountplus.com all                                                                                                                                                                                                                                                         

saa.paramountplus.com.	61	IN	CNAME	paramountplus.com.data.adobedc.net.
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.226
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.186
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.237
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.225
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.232
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.151
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.20
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.229
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.139
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.15
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.104
paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.165
```

**Comment by jdrch** [comment]
> Yup @gothic-bum is right.
> 
> ```shell
> $ dig  saa.paramountplus.com all                                                                                                                                                                                                                                                         
> 
> saa.paramountplus.com.	61	IN	CNAME	paramountplus.com.data.adobedc.net.
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.226
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.186
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.237
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.225
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.232
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.151
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.20
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.229
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.139
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.15
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.104
> paramountplus.com.data.adobedc.net. 180	IN A	63.140.38.165
> ```

@gothic-bum is correct that it's a tracker, *but that's not what the list is for*. The list is for fake news and gambling sites, specifically. Blocking this URL breaks Paramount+ unnecessarily for people who want to block fake news and gambling but aren't as concerned about tracking, such as myself.

Either the URL is in the wrong list or the list is inaccurately named.

**Comment by StevenBlack** [comment]
@jdrch I recommend you read the [readme](https://github.com/StevenBlack/hosts/blob/master/readme.md) in this repo.

In short, and to clarify because you've misunderstood: fake news, gambling, porn, and social, and their various combinations, are ***OPTIONAL EXTENSIONS*** to the base list which includes adware and malware.

In other words, the base list is always included here.

I trust that now you understand what we do here.  We protect everybody from adware and malware, and users have the ***OPTION*** to include other things.

Closing.
