### ISSUE TITLE
Block mym.fans?

### ISSUE THREAD

**Issue by sundowndev** [StevenBlack/hosts#2122]
Hi, should `mym.fans` be considered as a porn site ? It has nearly the same content policy as onlyfans.

```
0.0.0.0 mym.fans
0.0.0.0 media.prod-v2.mym.fans
```

**Comment by StevenBlack** [comment]
Merci Raphaël!

Ping @sinfonietta can you evaluate this for your list? Thanks!

**Comment by Sinfonietta** [comment]
@StevenBlack these are added too.

**Comment by StevenBlack** [comment]
Thank you everybody.  Closing.
