### ISSUE TITLE
False-Positive: px-cloud.net

### ISSUE THREAD

**Issue by omriiluz** [StevenBlack/hosts#2126]
Hello,
I created an issue and PR on an upstream feed blocking px-cloud.net. https://github.com/shreyasminocha/shady-hosts/issues/11

PerimeterX (now HUMAN Security) is an application security and anti fraud solution and we use that domain as part of our service. We take user privacy very seriously and comply with all major privacy regulations (https://www.perimeterx.com/resources/compliance/). 

This block is causing issues on a large number of web sites, would appreciate if you can whitelist this domain.

**Comment by StevenBlack** [comment]
Thank you for this Omri @omriiluz.

We don't block the domain `px-cloud.net`.

We block ...

* `collector-px8fcgygk4.px-cloud.net`, and 
* `client.px-cloud.net`

@shreyasminocha is indeed the curator of the list that brings `client.px-cloud.net` to us.

**Comment by shreyasminocha** [comment]
Resolved upstream :+1:

**Comment by StevenBlack** [comment]
Thanks Shreyas @shreyasminocha!

Omri @omriiluz this will be live in the next release.
