### ISSUE TITLE
Block geozo

### ISSUE THREAD

**Issue by dasyad00** [StevenBlack/hosts#2127]
I recently came across a website which serves Taboola-like ads (see [example](https://www.idxchannel.com/syariah/tanpa-riba-catat-21-aplikasi-investasi-syariah-terdaftar-di-ojk)). So far, I have identified 3 domains linked with these ads (mainly involved with displaying).

```
geozo.com	
amp.geozo.com	
media.geozo.com
```

**Comment by hagezi** [comment]
And additionally `cdn.geozo.com`

**Comment by StevenBlack** [comment]
Hi @dasyad00 thank you very much for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
