### ISSUE TITLE
How to identify which blocklist a domain is on?

### ISSUE THREAD

**Issue by ambiamber** [StevenBlack/hosts#2128]
I looked in the generated hosts file for a comment that would elucidate which of the block lists contained a particular domain but the only thing I found is a comment that appears to be a section header and that comment consisted only of the word `ads`. 

Aside from finding all of the consolidated lists by hand and going through them OR writing new code to do that is there a way to go from `example.com` to a list name like `Foobie's stinky hosts`?

Thanks.

**Comment by StevenBlack** [comment]
Thank you for your question @ambiamber.

If you're on Mac or Linux you can use `grep`, `rg` (ripgrep), or `ack`.  The folder names will come up in the results. You're looking for files in the `data` or `extensions` folders.

If you're on Windows, you can use search in the file manager. I'm sure there are command line tools in Windows that can search through plaintext files in the terminal.

Ask Google 😄 

Closing.
