### ISSUE TITLE
Block graph.instagram.com

### ISSUE THREAD

**Issue by devipasigner** [StevenBlack/hosts#2130]
Hello, you have the domain 'graph.instagram.com' whitelisted. I would like to request a review of the domain again since I think it was falsely whitelisted. I am aware that the domain 'graph.facebook.com' breaks facebook sign in on mobile devices and marketplace however 'graph.instagram.com' has not broken anything on instagram for me. This is coming from someone who has been using instagram with 'graph.instagram.com' blocked for over a year.  I think that while you were whitelisting 'graph.facebook.com' there was some confusion between the two Meta domains.

**Comment by StevenBlack** [comment]
Hi @devipasigner thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
