### ISSUE TITLE
Block fundingchoicesmessages.google.com

### ISSUE THREAD

**Issue by a77841s** [StevenBlack/hosts#2131]
Some websites will have ads for this domain.

**Comment by StevenBlack** [comment]
Hi @a77841s thank you for this.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
