### ISSUE TITLE
Fidelity iOS Face ID

### ISSUE THREAD

**Issue by cwanja** [StevenBlack/hosts#2133]
I believe `activate1.Fidelity.com` is blocking Face ID from working on iOS. Can register and enroll Face ID on cellular, re-login on cellular with Face ID no problem. Turn on WiFi behind Pi hole using this blocklist and get an error that Fidelity has detected an issue with Face ID activation and requires me to re-login.

**Comment by StevenBlack** [comment]
Thank you for this observation @cwanja.

The domain `activate1.Fidelity.com` is a `CNAME` record that points to `fidelity.activate.ensighten.com`.

We block many `ensighten.com` domains and these come to us via five different upstream curators. Furthermore this cesspool continues through the domain `nc0.co` which is also blocked.

I'm sorry but this isn't going to change.

Closing.


```bash
$ dig activate1.Fidelity.com all                                                                        
activate1.Fidelity.com.	3290	IN	CNAME	fidelity.activate.ensighten.com.
fidelity.activate.ensighten.com. 590 IN	CNAME	fidelity.edge.nc0.co.
fidelity.edge.nc0.co.	3290	IN	CNAME	edge-geo.nc0.co.
edge-geo.nc0.co.	116	IN	A	3.233.164.149
```
