### ISSUE TITLE
Replacing content of /etc/hosts failed.

### ISSUE THREAD

**Issue by DaniSpringer** [StevenBlack/hosts#2135]
I ran
```
docker run --pull always --rm -it -v /etc/hosts:/etc/hosts ghcr.io/stevenblack/hosts:latest updateHostsFile.py --auto --replace --extensions gambling porn fakenews
```
And, after lots of other output, got
```
Success! The hosts file has been saved in folder 
It contains 167,478 unique entries.
Running in container, so we will replace the content of /etc/hosts.
Replacing content of /etc/hosts failed.
```
And upon testing, Safari loads any and all of the above.
What to do?

**Comment by DaniSpringer** [comment]
Actually, I manually copied the entire file to /etc/hosts (by running `sudo cp hosts /etc/hosts`) and while /etc/hosts now shows all the text... nothing is being blocked. What am I missing?

**Comment by StevenBlack** [comment]
Thank you for this question Daniel @DaniSpringer.

Have you tried flushing your browser cache?  Flushing your workstation DNS cache?

Lots of DNS caching going on typically 😄

**Comment by StevenBlack** [comment]
Closing.

**Comment by DaniSpringer** [comment]
> Thank you for this question Daniel @DaniSpringer.
> 
> Have you tried flushing your browser cache? Flushing your workstation DNS cache?
> 
> Lots of DNS caching going on typically 😄

Sorry but I don't understand

**Comment by StevenBlack** [comment]
Hi Daniel @DaniSpringer these links should help:

* [How to Clear Safari's Cache](https://www.macrumors.com/how-to/clear-safari-cache/)
* [How to Flush your DNS Cache on Mac](https://mackeeper.com/blog/flush-dns-cache-on-mac/)

**Comment by DaniSpringer** [comment]
> Hi Daniel @DaniSpringer these links should help:
> 
> * [How to Clear Safari's Cache](https://www.macrumors.com/how-to/clear-safari-cache/)
> * [How to Flush your DNS Cache on Mac](https://mackeeper.com/blog/flush-dns-cache-on-mac/)

Thanks! Did that just now.
Just to be sure I understand, does it make sense for me to copy, for example, this https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn/hosts and then paste it as a replacement of whatever is in my /etc/hosts file? Should that work?

**Comment by DaniSpringer** [comment]
> Hi Daniel @DaniSpringer these links should help:
> 
> * [How to Clear Safari's Cache](https://www.macrumors.com/how-to/clear-safari-cache/)
> * [How to Flush your DNS Cache on Mac](https://mackeeper.com/blog/flush-dns-cache-on-mac/)

@StevenBlack so, I tested some gambling sites, and unless I happen to be unlucky, the few I tried were all blocked (time out errors, if that is the expected behavior...), however some specific, paid p@@@ sites still worked, even though they were listed in the hosts, namely www.livej@@@in.com

What can be done?

Thanks

**Comment by DaniSpringer** [comment]
> Hi Daniel @DaniSpringer these links should help:
> 
> * [How to Clear Safari's Cache](https://www.macrumors.com/how-to/clear-safari-cache/)
> * [How to Flush your DNS Cache on Mac](https://mackeeper.com/blog/flush-dns-cache-on-mac/)

@StevenBlack might the issue be with any https website? (as opposed to http)

**Comment by StevenBlack** [comment]
Daniel @DaniSpringer if the hosts file is working you should receive a fail-to-connect error in, I'm guessing, 10 ms or less. That's because the request should never leave your box. So NOT a timeout error. You should see the error before your enter key has had time to spring back up, basically.

HTTP or HTTPS has no bearing.  The first fails on port 80, the second on port 443. But either way, the request never leaves your box.

These difficulties are always due to cache. Clear your caches.

By the way, the `etc/hosts` file is in your box' hard drive, not the `etc/hosts` within Docker.

**Comment by DaniSpringer** [comment]
@StevenBlack 
In that case, it is not working at all. I cleared cache in both ways as per the links you posted. Not sure what else to check. May you advise?
Thank you
Note: does the link I gave above "work" for you when using the p@@@ host file?
And it seems many gambling sites are down on their own, so it's tricky for me to test whether my hosts file is working, but it seems like it is not.

**Comment by StevenBlack** [comment]
Daniel @DaniSpringer it's trivially easy to check if your hosts file is working.

Pick a domain in the hosts file.  Say `googleanalytics.com`.  Paste that in your browser bar. If you get back nothing, it's working. If you get back a website, keep debugging.

In a terminal window, what does this command return? It should return a ton.

```bash
$ cat /etc/hosts
```

**Comment by StevenBlack** [comment]
Daniel @DaniSpringer are you using Onion / Tor?  That always bypasses the hosts file.

**Comment by DaniSpringer** [comment]
@StevenBlack 
cat /etc/hosts does print a ton
Not using Onion/Tor at the moment
I might be using a VPN. Would that be an issue?

**Comment by StevenBlack** [comment]
Daniel the domain `www.livej@@@in.com` or `www%2Elivej%40%40@in.com` or whatever garbage you pasted there is not in our hosts file.

**Comment by DaniSpringer** [comment]
@StevenBlack www.livejasmin.com
Not sure what you mean by garbage
Thanks

**Comment by StevenBlack** [comment]
@DaniSpringer 

<img width="926" alt="2022-11-18_00-16-19" src="https://user-images.githubusercontent.com/80144/202625248-5f5cf7fe-75f6-45e5-ab98-64459dece757.png">


I'm out of ideas. Let us know when you figure out what's unique about your box.

**Comment by DaniSpringer** [comment]
@StevenBlack oh. I was trying to censor it, but I guess that wouldn't work.
What might be unique? Let's see...

I use [accountable2you](https://accountable2you.com)
I use iCloud Private Relay
Latest macOS
Apple M1 chip
Can't think of anything else

**Comment by gothic-bum** [comment]
> I use iCloud Private Relay  
  
Disable it. Private Relay uses Oblivious DNS over HTTPS (ODoH), and therefore ignores the local hosts file.

**Comment by DaniSpringer** [comment]
@gothic-bum I will try that now, thank you! And what would be the approach to make it work with Private Relay enabled?

**Comment by DaniSpringer** [comment]
@gothic-bum @StevenBlack so firstly, porn seems blocked now that iCloud private relay is off, so thank you.

Interestingly, googleanalytics.com still works, after clearing all the caches.

Also: some sites are specifically written with "www", and visiting them without that, still works, while visiting them with it, does not.

**Comment by gothic-bum** [comment]
Reboot your Mac to clear all caches, and then test again.

**Comment by DaniSpringer** [comment]
@gothic-bum did but we'll retry to be sure, thanks

**Comment by gothic-bum** [comment]
Test from Terminal:  
  
`ping -c 5 googleanalytics.com`

**Comment by DaniSpringer** [comment]
@gothic-bum I get:
PING googleanalytics.com (0.0.0.0): 56 data bytes
ping: sendto: Socket is not connected
ping: sendto: Socket is not connected
Request timeout for icmp_seq 0
ping: sendto: Socket is not connected
Request timeout for icmp_seq 1
ping: sendto: Socket is not connected
Request timeout for icmp_seq 2
ping: sendto: Socket is not connected
Request timeout for icmp_seq 3

--- googleanalytics.com ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss

**Comment by DaniSpringer** [comment]
This is the start of my hosts file. Maybe something is wrong:
`
# Title: StevenBlack/hosts with the gambling and porn extensions
#
# This hosts file is a merged collection of hosts from reputable sources,
# with a dash of crowd sourcing via GitHub
#
# Date: 14 November 2022 02:39:48 (UTC)
# Extensions added to this file: gambling, porn
# Number of unique domains: 211,509
#
# Fetch the latest version of this file: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn/hosts
# Project home page: https://github.com/StevenBlack/hosts
# Project releases: https://github.com/StevenBlack/hosts/releases
#
# ===============================================================

127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
ff00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
0.0.0.0 0.0.0.0

# Custom host records are listed here.


# End of custom host records.
# Start StevenBlack

#=====================================
# Title: Hosts contributed by Steven Black
# http://stevenblack.com

0.0.0.0 eu1.clevertap-prod.com
0.0.0.0 wizhumpgyros.com
0.0.0.0 coccyxwickimp.com
`

**Comment by DaniSpringer** [comment]
https://stackoverflow.com/a/37189530

**Comment by DaniSpringer** [comment]
I tried commenting out
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
And now we're back to stripchat.com working and www.stripchat.com not working...

I'm completely out of ideas, but I will gladly try any suggestions you might have. Thanks!

**Comment by gothic-bum** [comment]
> ping: cannot resolve https://stripchat.com: Unknown host
> It does work in safari.  
  
That means Safari is bypassing your hosts file.  
  
What you need to do is restore your DEFAULT hosts file, and then add a test entry to determine why Safari is not using it for DNS resolution (for example, perhaps it is due to a VPN, or with software you installed).

**Comment by DaniSpringer** [comment]
@gothic-bum ok. Online I see various versions of what a default hosts file should look like. What is the correct way to reset it to whatever it originally was?

**Comment by DaniSpringer** [comment]
Upon checking redirection as per here https://apple.stackexchange.com/a/295367 , i get a lot more output than that:

name: website.com
ipv6_address: 2606:4700:10::ac43:1b6a
ipv6_address: 2606:4700:10::6816:42c3
ipv6_address: 2606:4700:10::6816:43c3

name: website.com
ip_address: 104.22.66.195
ip_address: 172.67.27.106
ip_address: 104.22.67.195

**Comment by DaniSpringer** [comment]
@StevenBlack thanks.
Upon testing using a almost empty hosts file, it appears that, in order to block example.com, I must do this:
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##

127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost

0.0.0.0 example.com
0.0.0.0 www.example.com
::1 www.example.com
::1 example.com
```
Now, if this works for any site that is great, but any chance you can update the script to generate the current lines with the above versions? Manually editing each one is of course not practical.

Thanks.

**Comment by funilrys** [comment]
Steve @StevenBlack, I think it's time for us to also include the IPv6 format ... What's your opinion on this?

**Comment by DaniSpringer** [comment]
@StevenBlack just so I understand, I would need the file to include IPv6 format?
If so, any plans to include it any time soon?
And how would I get it? (Would it be in the same way I tried using the current one?)

Thanks

**Comment by StevenBlack** [comment]
Ho Daniel @DaniSpringer.

IPv6 is not a top priority presently.  

The highest priority right now is keeping a lid on the hosts file size, because many classes of devices, and Windows OS devices, can't cope with large hosts files.  I think we're already too large.

Adding IPv6 would more than double the file size.  That won't happen until we reorganize centrally around the notion of "Limited devices (and MS-Windows machines)" and "Everything else".

If you need [defcon-3 level readiness](https://en.wikipedia.org/wiki/DEFCON) or better, then maybe this hosts file isn't for you.

**Comment by DaniSpringer** [comment]
> Hi Daniel @DaniSpringer.
> 
> IPv6 is not a top priority presently.
> 
> The highest priority right now is keeping a lid on the hosts file size, because many classes of devices, and Windows OS devices, can't cope with large hosts files. I think we're already too large.
> 
> Adding IPv6 would more than double the file size. That won't happen until we reorganize centrally around the notion of "Limited devices (and MS-Windows machines)" and "Everything else".
> 
> If you need [DEFCON-3 level readiness](https://en.wikipedia.org/wiki/DEFCON) or better, then maybe this hosts file isn't for you.

1. You can make a separate file for IPv6
2. Please take your attitude elsewhere!

**Comment by gothic-bum** [comment]
@DaniSpringer: 
  
An IPv4/IPv6 dual stack configuration (which you are apparently using) would require a hosts file with both IPv4 and IPv6 entries.

**Comment by DaniSpringer** [comment]
> @DaniSpringer:
> 
> An IPv4/IPv6 dual stack configuration (which you are apparently using) would require a hosts file with both IPv4 and IPv6 entries.

So we can have two versions of the hosts file. One 4 and one 4+6.
Thanks

**Comment by gothic-bum** [comment]
As @StevenBlack pointed out, some platforms already have issues with the current size of the IPv4 hosts file, and an IPv4+IPv6 hosts file would essentially double that size.

**Comment by DaniSpringer** [comment]
> As @StevenBlack pointed out, some platforms already have issues with the current size of the IPv4 hosts file, and an IPv4+IPv6 hosts file would essentially double that size.

I get that. But this would help those whose setup would handle it. (I’m actually not sure what it depends on. RAM? Windows/Mac? Internet speed? Something else?)

thanks
