### ISSUE TITLE
Blocking sdk.split.io causes issues with the EA Desktop App

### ISSUE THREAD

**Issue by Steltek** [StevenBlack/hosts#2137]
Hello,

I've recently noticed an issue with the EA Desktop App wherein it would not show me the 'View Properties' and 'Repair' menus on any of my PCs. After some extensive debugging, I've traced the root cause back to my network (running a VPN makes the option appear) and more specifically the Pihole blocking sdk.split.io. (If that domain is blocked, the EA App takes a bit longer to start up, and the 'View Properties' menu becomes unavailable.

Domain blocked:
![2022-11-12 17_28_07-EA](https://user-images.githubusercontent.com/1315116/201484200-38d13e0b-621f-40c6-8941-3b5c47c8a063.png)

Domain whitelisted in pihole:
![2022-11-12 16_53_22-EA](https://user-images.githubusercontent.com/1315116/201484003-1471e0fa-4d08-47fa-b5d9-82b3e3095c57.png)

Not sure if that warrants removing it, but at least this way the information is out there.

**Comment by StevenBlack** [comment]
Thank you for this @Steltek.

This is from the Adaway list which is no longer actively maintained.

I've paused refreshing the Adaway list (commit 10cb94) and removed the domain `sdk.split.io` from our copy of this list (commit 0ddc209).

This will reflect in the next release, coming soon.

Closing.
