### ISSUE TITLE
Coveo is blocked by AdAway again...

### ISSUE THREAD

**Issue by spoolr** [StevenBlack/hosts#2142]
I was trying to order off of leevalley.com and have been prevented from this for more than month.  This past ticket reports #1856 that it affects the search function of sites, which it does, but it's also stopping orders from going through.  It's been super frustrating.  

Steven, this is contained in AdAway, but the maintainer reports he has moved on.  Coveo themselves have added a ticket over there, but this is full on effecting ecommerce as well and I don't know if they are aware of that.  Maybe it's unique to leevalley.com's implementation, but it's impossible to order from there with coveo blocked.  It's full on broken their site.  I've whitelisted it myself, and I won't be ordering from there again anytime soon, but for the benefit of anyone else, this needs to be addressed if possible.

**Comment by StevenBlack** [comment]
Thank you for this @spoolr.

Since Adaway is unmaintained, I've paused refreshing from this source and taken its last version onboard here.

This is fixed in commit 62f5fe5.  This will reflect in the next release.

Closing!
