### ISSUE TITLE
Update hosts file with url

### ISSUE THREAD

**Issue by m0tt** [StevenBlack/hosts#2146]
May I ask you to add the following url: ams[dot]creativecdn[dot]com to the hosts file?

**Comment by StevenBlack** [comment]
Thank you for this @m0tt. Why would we do that?

**Comment by m0tt** [comment]
I'm sorry @StevenBlack for the late reply. I wanted to add this url because on some pages I see ads served by this address.

**Comment by gothic-bum** [comment]
> on some pages  
  
I highly doubt @StevenBlack (or anyone else) is going to be able to correctly guess what pages they are.

You should provide a specific example with the exact URL, plus any steps necessary to reproduce the issue.
