### ISSUE TITLE
Incompatible with HostsMan

### ISSUE THREAD

**Issue by hl2guide** [StevenBlack/hosts#215]
The lists seem to be incompatible with Hostsman. I always get:

"This source is not compatible. Server does not return all the necessary information."

![1](https://cloud.githubusercontent.com/assets/17044982/21100324/9c5d8ad8-c0c7-11e6-924f-d54037a5a3e8.png)

**Comment by StevenBlack** [comment]
Please tell me the URL you've entered in the `File name or URL` box.

**Comment by hl2guide** [comment]
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts

**Comment by hl2guide** [comment]
It's the social hosts list.

**Comment by StevenBlack** [comment]
Looks to me like it wants a .zip file.  Try 
   https://github.com/StevenBlack/hosts/raw/master/alternates/social/hosts.zip

I'm guessing  :-)

**Comment by StevenBlack** [comment]
Looking briefly at http://www.abelhadigital.com/hostsman – it's possible HostsMan is abandonware?

**Comment by FadeMind** [comment]
@StevenBlack this issue came from this
![image 011](https://cloud.githubusercontent.com/assets/9846948/21109608/1dc0a9f8-c09a-11e6-9385-e6200c7eb29b.png)
aaaand it is:
![image 012](https://cloud.githubusercontent.com/assets/9846948/21109680/61cc2532-c09a-11e6-9fd6-2bc480f65a3b.png)

PYTHON script corrupt line 
![image 013](https://cloud.githubusercontent.com/assets/9846948/21109726/a0e36302-c09a-11e6-9868-6cd504276727.png)

**Comment by hl2guide** [comment]
Just tried: https://github.com/StevenBlack/hosts/raw/master/alternates/social/hosts.zip

Does not work with the exact same error :(

**Comment by FadeMind** [comment]
@StevenBlack 
See:
![image 013](https://cloud.githubusercontent.com/assets/9846948/21109851/25d60d76-c09b-11e6-89ac-31778dcabd36.png)
In all generated hosts file present this bug.

**Comment by StevenBlack** [comment]
Hostman should not be barfing on this...

**Comment by FadeMind** [comment]
@StevenBlack double... I will fix ASAP

**Comment by FadeMind** [comment]
@StevenBlack 
https://github.com/FadeMind/hosts.extras/commit/f870b18ef3aff60d24c989c0c0ab031816d9bcee

Done. Please refresh all hosts variants.

Apologize for annoying issue.

**Comment by StevenBlack** [comment]
OK!  @hl2guide give it a whirl now!

**Comment by aequis** [comment]
Same issue here. Still not working.

**Comment by hl2guide** [comment]
Yep not working.

The only reason I'm using HostsMan is to automate the update of the hosts file by schedule.

Is there any other more suitable tool that anyone knows?

**Comment by StevenBlack** [comment]
I'm not sure what else we can do.  It appears that this one's on Hostman.

**Comment by hl2guide** [comment]
ok thanks for your work :D your lists are so useful!

**Comment by Laicure** [comment]
> Is there any other more suitable tool that anyone knows?

Hey @hl2guide, I just updated my hosts fork from @StevenBlack for Windows' task scheduler compatibility. You might want to check the [Testing Release](https://github.com/Laicure/HostsY/releases) ;)

**Comment by StevenBlack** [comment]
@hl2guide try this:

   http://sbc.io/hosts/hosts

This is a mirror for the hosts files in this repo, with the root of this repo mapping to sbc.io/hosts

**Comment by Jezza-x3** [comment]
@StevenBlack The sbc.io/hosts leads to a 403 forbidden error. The /hosts/hosts works, however. - Only tested loading the page, not using in HostsMan.

**Comment by StevenBlack** [comment]
Yes use the URL I provided.  The 403 on /hosts is intentional.

**Comment by Jezza-x3** [comment]
@StevenBlack How are we supposed to do the alternative ones such as social, gambling, porn, and all combined, etc.?

**Comment by StevenBlack** [comment]
Sorry I was unclear.

`sbc.io/hosts/hosts/` maps to the root of this repo.  Tack `hosts` on to that and you get the default hosts file.

Tack `alternates/social/hosts' and you get...

http://sbc.io/hosts/alternates/social/hosts

Spot the pattern?

**Comment by Jezza-x3** [comment]
@StevenBlack I have great news. It works. 👍 

I guess all that's left is to edit the master ReadMe and show this near your raw and link files. Then say in a tiny footnote that they work with HostsMan. You can totally close this now as it's fully solved. Thanks for your hard work StevenBlack!

**Comment by StevenBlack** [comment]
@Jezza-x3 ya, this is all sketch at the moment because I'm not in a position to make official changes until sometime tomorrow.  This may not be the server or URL we'll use long-term but it's fine for now.

**Comment by Jezza-x3** [comment]
@StevenBlack Alright. I have a site I purchased called lovex3.me (got it free) and I could totally put them on there but have no idea how or what it would encompass.

**Comment by hl2guide** [comment]
@StevenBlack Tried out "http://sbc.io/hosts/hosts" it works in HostsMan :dancing_men: 👯

**Comment by JamoCA** [comment]
I was interested in using HostsMan to manage local web server names (for testing) and encountered this same issue when connecting to a REST endpoint to retrieve the HOST data.

I monitored the requests & responses and determined that HostsMan performs a "head" request when clicking the "Test Connection" button.  It's also looking for both "Content-Length" and "Last-Modified" headers.  If your server isn't returning these headers, it will fail the HostsMan connection test.

**Comment by StevenBlack** [comment]
James @JamoCA can you please try it now?  Bring...

```
http://sbc.io/hosts/hosts
```

into Hostman?  I changed the headers returned by sbc.io.

**Comment by JamoCA** [comment]
@StevenBlack I was able to troubleshoot the comparitive differences between valid & invalid sources by using [Postman](https://www.getpostman.com/) _(cross-platform; free)_

Success!  When I perform a GET (or HEAD) request using Postman to the [URL](http://sbc.io/hosts/hosts), I see that both "Content-Length" and "Last-Modified" headers are returned.  I entered the URL into the HostsMan "Add Source" pop-up and clicked "Test Connection" and it returned "The source seems to be compatible."

**Comment by StevenBlack** [comment]
Awesome!  Thanks James @JamoCA.
