### ISSUE TITLE
Issue with epicgames tracking domain (Epic Games Launcher)

### ISSUE THREAD

**Issue by VL4DST3R** [StevenBlack/hosts#2151]
I noticed an issue crept up when blocking the `tracking.epicgames.com` domain, namely store marketplace no longer works if this is being blocked, also mentioned here: https://forums.unrealengine.com/t/unreal-marketplace-section-of-epic-games-launcher-unresponsive/475586/5
Was wondering if this should be considered for removal since it breaks functionality.

**Comment by StevenBlack** [comment]
Thank you for this Vlad.

I understand what you're saying. I feel this this issue belongs to `epicgames.com`. Here's why.

Our mission is serving people who don't want to be tracked. So I'm going to decline your suggestion on principle.

Closing.

**Comment by VL4DST3R** [comment]
> I understand what you're saying. I feel this this issue belongs to epicgames.com. Here's why.

While i agree its shitty implementation on their end, i doubt this will ever be addressed, i remember nvidia doing something very similar if you blocked their telemetry services, thats why i figured it had no other choice but to be ignored for the time being. 

> Our mission is serving people who don't want to be tracked. So I'm going to decline your suggestion on principle.

Im sorry but that sounds kinda obtuse? So you're going to block anything regardless if it breaks site functionality or not?
I also follow Ublock issue tracker and the consensus from what ive seen there is block eveything as long as you don't literally break the entire site/main functionality. Breaking the entire epic store kinda fits this description. Mind you, i believe this issue is also present in the web browser when accessing their store, not just the launcher.

**Comment by VL4DST3R** [comment]
Fair enough.
