### ISSUE TITLE
Suggestion: commercial use friendly version?

### ISSUE THREAD

**Issue by flatsiedatsie** [StevenBlack/hosts#2154]
I've done a search, but couldn't find anything, so here's my suggestion:

It would be great if there could be a version of the main list (adware + malware) that is OK for commercial use. 

I work on a [plugin](https://github.com/createcandle/hotspot) for an open source [smart home controller](https://www.candlesmarthome.com/) which could integrate your list. But of course I can't guarantee that all the users of the controller will use it in a non-commercial setting.

As far as I can tell it would only mean excluding two sources:
- MVPS hosts file
- Dan Pollock

Having such a version might speed up adoption by commercial parties too? The more people are protected, the better.

I know I could run the script myself without the NC source but I thought it would be valuable to have something like that available in a central trusted source.

**Comment by flatsiedatsie** [comment]
I did a quick test. The resulting hosts file still contained 145.000+ domains

**Comment by StevenBlack** [comment]
Hello @flatsiedatsie thank you for this.

Well if it's any help, I am this close 🤏🏻 to dropping the MVPs hosts file from this amalgamated list because it's effectively abandonware at this point.

**Comment by flatsiedatsie** [comment]
Sorry to hear that. 

I suspect Dan Pollock's list is stil relevant though?

So the question remains :-)

**Comment by StevenBlack** [comment]
Good bot!

But I want to keep this issue active.
