### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by trackerct** [StevenBlack/hosts#2155]
please remove this domains. Streaming video not working, break sites.

beggarlyfilmingabreast.com
cdn.sgmntfy.com
cdn.segmentify.com
per2.segmentify.com
key.seckeyserv.me

**Comment by StevenBlack** [comment]
Thank you for this @trackerct.

- We don't list `beggarlyfilmingabreast.com`.
- We don't list `cdn.sgmntfy.com`
- The domain `cdn.segmentify.com` comes to us from adaway.
- We don't list `per2.segmentify.com`
- We don't list key.seckeyserv.me.

@trackerct you're fucking with me.  Please don't post here anymore.  if you post another issue here I will block you.

**Comment by gothic-bum** [comment]
Only `cdn.segmentify.com` is included the latest release (3.11.32) of the hosts file.

And Segmentify is a tracker.

From https://segmentify.github.io/segmentify-dev-doc/integration_web/:
  
> Segmentify javascript library uses data layer to collect information. To send events to Segmentify to track visitor behavior, you should add information to data layer in given format. Events tracked by Segmentify are given below:
> 
> * page
> * product
> * basket
> * checkout
> * user
> * custom
> * interaction
> * form
> * search
>
