### ISSUE TITLE
please block this site

### ISSUE THREAD

**Issue by superislam** [StevenBlack/hosts#2156]
hello please may you block this site [https://نسوانجى.net](https://xn--mgbkt9eckr.net/)

**Comment by StevenBlack** [comment]
Hello @superislam now why would we do that?  Please explain.

**Comment by superislam** [comment]
> Hello @superislam now why would we do that? Please explain.

Oh ok it's a porn forum and site

**Comment by StevenBlack** [comment]
Thanks @superislam.  Ping @sinfonietta for inclusion.

**Comment by Sinfonietta** [comment]
Yes @StevenBlack this site is porn and I have added it.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta.  Closing.

**Comment by thomasmerz** [comment]
My Pi-hole says 😞 
```
  [i] Target: https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 19516 domains, 1 domains invalid!
      Sample of invalid domains:
      - نسوانجى.net
  [i] List stayed unchanged
```

**Comment by StevenBlack** [comment]
Hi Thomas @thomasmerz.

Ping @Sinfonietta!

**Comment by Marshmello2023** [comment]
I took adblocker test and it states that only 88% of the ads are blocked. These hosts were unblocked though- 

analyticsengine.s3.amazonaws.com
affiliationjs.s3.amazonaws.com
advertising-api-eu.amazon.com
amazonclix.com
advertising-api-eu.amazon.com
freshmarketer.com
cdn.luckyorange.com
w1.luckyorange.com
api.bugsnag.com
browser.sentry-cdn.com
d.reddit.com
samsung-com.112.2o7.net
amazonaax.com
mediavisor.doubleclick.net
app.bugsnag.com
app.getsentry.com
analytics.facebook.com
ads.facebook.com
advertising.twitter.com
widgets.pinterest.com
appmetrica.yandex.com
extmaps-api.yandex.net
analytics-api.samsunghealthcn.com
data.mistat.india.xiaomi.com
data.mistat.rus.xiaomi.com
logservice.hicloud.com
logservice1.hicloud.com
metrics-dra.dt.hicloud.com
logbak.hicloud.com
click.oneplus.cn
supportmetrics.apple.com

**Comment by ler762** [comment]
> if AdGuard or other DNS-based adblocker can do?

It looks like bind can do both idn (xn--.*) as well as UTF-8

```
$ tail -6 $RPZ

; test for ??international domain?? names
; xn--xxw-jgq.adj.st    CNAME   .
xxwᏚ.adj.st             CNAME   .

; --- end ---

$ dig xn--xxw-jgq.adj.st

results in

(xn--xxw-jgq.adj.st): query: xn--xxw-jgq.adj.st IN A +E(0)K (127.0.0.1)
(xn--xxw-jgq.adj.st): rpz QNAME NXDOMAIN rewrite xn--xxw-jgq.adj.st/A/IN via xn--xxw-jgq.adj.st.rpz.zone

as does

$ dig xxwᏚ.adj.st

(xn--xxw-jgq.adj.st): query: xn--xxw-jgq.adj.st IN A +E(0)K (127.0.0.1)
(xn--xxw-jgq.adj.st): rpz QNAME NXDOMAIN rewrite xn--xxw-jgq.adj.st/A/IN via xn--xxw-jgq.adj.st.rpz.zone

```

**Comment by thomasmerz** [comment]
@ler762 , sure, both can handle it:

```
$ dig نسوانجي.net

; <<>> DiG 9.16.33 <<>> نسوانجي.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41866
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;نسوانجي.net.		IN	A

;; ANSWER SECTION:
نسوانجي.net.	300	IN	A	0.0.0.0

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun Dec 11 15:05:31 CET 2022
;; MSG SIZE  rcvd: 63
```

But Pi-hole doesn't "like" it and says it's an invalid domainname:

![image](https://user-images.githubusercontent.com/18568381/206908441-2d6b653b-8ddf-4d1b-8c80-0b8b3167781a.png)

**Comment by thomasmerz** [comment]
@yubiuser, can you (or other Pi-hole core-devs) explain us why some domains with punycode are "invalid" for Pi-hole? I didn't figured out by searching in source code… Thanks 😘

**Comment by yubiuser** [comment]
Because no browser or app should request those IDNs, but will convert them to punycode first. Therefore the punycode representation should be blocked.
__

> I didn't figured out by searching in source code

You need to look for the issues. 
https://github.com/pi-hole/pi-hole/issues?q=is%3Aissue+punycode+is%3Aclosed

**Comment by thomasmerz** [comment]
Regarding https://github.com/StevenBlack/hosts/issues/2156#issuecomment-1339669140 … @Sinfonietta , can you please take care of this? As @yubiuser wrote, you should add the punycode-domain and not the IDN.

**Comment by Sinfonietta** [comment]
@StevenBlack this is fixed, I am sorry for the long delay.

**Comment by StevenBlack** [comment]
Thank you everybody.  Closing.
