### ISSUE TITLE
Please Add these Porn Sites

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#2157]
Hello @StevenBlack and @Sinfonietta,

Here are more porn sites to add to the filter:
epawg.com
en.vidmo.pro
fullporner.com
2chen.moe
8chan.moe
nutchaser.com
erothots.co
4hdxxx.com
nudeleakers.com
cambabes.tube
celebforum.co
celeb.to
jerkmate.tv
fapnation.com
flashthepublic.com
hdsupersex.com
xxteenhub.com
bestvideoleak.com
newdayporn.com
newporntv.me
goodnightporn.com
xvideoleaks.com
goldengirlporn.com
whereismyporn.com
nicetitties.net
javtv.cc
javtv.to
javtc.net
njav.tv
njavtv.com
beeg.day
beeg.yachts
jav.casa
anybunny.casa
sexfreemovie.fun
javshy.one
javcrave.com
javpornfull.com
javvideoporn.com
javvideos.porn
xxxtube.porn

I will append this list if I find more sites to add to the blocklist. I'm thankful for your work!

**Comment by StevenBlack** [comment]
Thank you @g1t3m.  Ping @sinfonietta thanks.

**Comment by Sinfonietta** [comment]
@StevenBlack I have added all of these.

**Comment by g1t3m** [comment]
Thank you both for adding these sites. Here are a few more I came across:

wetqueen.com
dankwank.net
pornito.xxx
pornfaze.com
danielleftv.com
leaked.fans
thothub.org

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta closing.
