### ISSUE TITLE
new ad domain: danbo[.]org

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#2158]
danbo . org describes itself as "self-serve advertising" and is currently running ad links on several 4chan boards.

**Comment by StevenBlack** [comment]
Hi Devon @hyder365 thank you for this.

We generally don't block root domains unless those root domains are used to serve adware or malware.  We aren't here to de-platform businesses in the ad industry, but just their delivery vectors.

As far as I can tell blocking this root domain blocks exactly no ads, right?

Closing

**Comment by hyder365** [comment]
Blocking this root domain would block both the ad links and the ad images:

ad:

https://danbo.org/gate?ref=HcWhBoFxQ6Kkcog&redir=https%3A%2F%2Fwww.amazon.com%2F-%2Fen%2FZulu-Alitspa%2Fe%2FB0B19C1YPC%2Fref%3Ddp_byline_cont_pop_book_1&d=27

ad image:

https://danbo.org/assets/creatives/4chan-fbf8011b77029c09a6f9e5269821948fa42b8417.gif

So I think it is very much worth adding...

**Comment by StevenBlack** [comment]
Thanks Devon @hyder365, fair enough.  Reopening.

**Comment by StevenBlack** [comment]
Devon @hyder365 this is included in commit 147b6d and will be live in the next release.  Thanks again!

Closing.
