### ISSUE TITLE
Please remove s.w.org

### ISSUE THREAD

**Issue by diego-betto** [StevenBlack/hosts#2159]
Hi,

s.w.org is used as a CDN by WordPress WooCommerce. 
Blocking the domain breaks the official websites.

![image](https://user-images.githubusercontent.com/11378282/204290768-e18b024a-70f7-4273-9617-8d4f17ea671b.png)

**Comment by StevenBlack** [comment]
Thank you for this Diego @diego-betto.

The domain `s.w.org` is removed in commit 0c0e2691.

This will reflect in the next release.

Closing.

**Comment by diego-betto** [comment]
Thank you! :)
