### ISSUE TITLE
Cannot block ads on Hotstar

### ISSUE THREAD

**Issue by AdityaGarg8** [StevenBlack/hosts#2162]
Except for goodbye ads, no list has ever been able to block ads on Hotstar.

So I extracted the relevant domains from there. Since goodbye ads has a lot of false positives, maybe we could add the following to the unified list to add Hotstar support?

agl-intl.hotstar.com
bifrost-api.hotstar.com
cws-hotstar.conviva.com
events-analytics.hotstar.com
fp-analytics.hotstar.com
hb-analytics.hotstar.com
logs.hotstar.com
service.hotstar.com
settings-analytics.hotstar.com
videoads.hotstar.com
vs.hotstar.com

Tried and tested and it works well.

**Comment by AdityaGarg8** [comment]
I added them to a block list here

https://gist.github.com/AdityaGarg8/ad87f0f6f6a1f785df3e1e1a885afaa0/raw/d0f03f78e8fdba906ff5cc29468f9774774bc486/indian_ott.txt

**Comment by StevenBlack** [comment]
Thank you for this Aditya @AdityaGarg8.

We already list three of these domains. In commit 5ca0d2e2 I added the others.  Thank you again!

```
agl-intl.hotstar.com 
fp-analytics.hotstar.com 
hb-analytics.hotstar.com
```

**Comment by AdityaGarg8** [comment]
Thanks!
