### ISSUE TITLE
Maybe remove bifrost-api.hotstar.com

### ISSUE THREAD

**Issue by russeg** [StevenBlack/hosts#2165]
bifrost-api.hotstar.com

If blocked, Disney+ Asia will show a "No Internet Connection" banner at the bottom that never goes away.

**Comment by AdityaGarg8** [comment]
Hi @StevenBlack 

Removing this domain still blocks ads for me, so we can safely remove this.

**Comment by StevenBlack** [comment]
Thank you @AdityaGarg8.

@russeg this is removed in commit 0a55ff4c and will be live in the next release, coming shortly.

Closing.

**Comment by danm3d** [comment]
This also seems to be the domain for watch history being remembered on Vidaa OS TVs in MEA territories (or at least the Continue Watching For... feature) 
(Hisense, Toshiba, etc.)
