### ISSUE TITLE
Please Add these Ads/Marketing Sites

### ISSUE THREAD

**Issue by edinhodiluviano** [StevenBlack/hosts#2166]
mkt.momentoeditorial.com.br
www.eventos.momentoeditorial.com.br

taken from this brazilian news: https://www.telesintese.com.br/a-anatel-tem-que-se-reposicionar-diz-alexandre-freire/

**Comment by StevenBlack** [comment]
Thank you for this Edinho @edinhodiluviano.

I'm not finding anything actionable here. In particular, there's nothing I can see in the link you provide.

Listing the websites of companies in the marketing and advertising business isn't what we do here. We list domains that actually serve ads, or worse.

In other words: we aren't in the business of taking companies off the internet. We block their vectors.

Closing.
