### ISSUE TITLE
analytics.shein.com

### ISSUE THREAD

**Issue by RainmakerRaw** [StevenBlack/hosts#2167]
Please consider adding this domain to the blocklist. Shein is a large international clothing retailer, sometimes used by my wife. I found this domain allowed in my DNS logs and it doesn't appear to be blocked by any of the main blocklists, including yours. 

I have had it manually blacklisted in AdGuard Home (`||analytics.shein.*^`) for months now, and it has never caused issues using the site but nor has any blocklist ever picked it up. I would suggest the reason for inclusion is apparent from the url itself. 

Please note that the website also redirects to local versions, so you may consider also kindly adding `analytics.shein.co.uk` and/or other variants as required (those are the two I know of, and I see you have a hostsfile format rather than broader abp format list which would allow wildcards). 

Thanks for your consideration.

**Comment by StevenBlack** [comment]
Thank you @RainmakerRaw those two are added in commit 64ba96ee and this will be live in the next release.

Closing.

**Comment by RainmakerRaw** [comment]
Thank you! Please forgive my replying to a closed issue, but on further investigation (which I'm embarrassed I didn't carry out sooner) it seems that `analytics.shein.com` is now simply a CNAME. Whether they moved their analytics to a separate server, or outsourced, I'm unsure. It used to be its own A record and IP. 

Regardless, if you added the root domain `250analytics.com`, you'd likely weed out a lot of other missed analytics subdomains/CNAMES elsewhere. I note that some other blocklists do now include this particular domain, but alas not yours (yet?). Two birds, one stone, etc. Just a suggestion.
