### ISSUE TITLE
Fixing the display of photos on mail.ru.

### ISSUE THREAD

**Issue by ShiGhost** [StevenBlack/hosts#2168]
Photos of news blocks and notifications are not loaded due to blocking `r.mradx.net`.

**Comment by gothic-bum** [comment]
Comment at the top of a file (https://r.mradx.net/img/5D/9E99F0.js) served from that domain:
  
> /*! Ads.js - Mail.ru external ads-async / Release date: 21.11.2022 / Version: 1.1.30 */!

**Comment by StevenBlack** [comment]
@gothic-bum sorry, I'm unsure what to do here.

I like issue that say, one way or another, the scoop 😄

**Comment by gothic-bum** [comment]
I just wanted to point out using a specific example that the domain `r.mradx.net` does have resources related to serving ads.  
  
Obviously if this domain is required for the `mail.ru` site to function, then it will likely be a judgement call if it should be included in the hosts file or not. And for what it's worth, `mradx.net` was *removed* today from the AdGuard DNS filter and tagged as "Incorrect Blocking": https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1148

I hope that helps, and best regards. :)

**Comment by StevenBlack** [comment]
Thank you for this clarification @gothic-bum.

I have removed domain `r.mradx.net` in commit 39238e04.  This will be live in the next release!

Closing.
