### ISSUE TITLE
ads-cdn.grab.com

### ISSUE THREAD

**Issue by russeg** [StevenBlack/hosts#2171]
from Grab (the asian Uber) app

**Comment by bigdargon** [comment]
Blocking this domain will not receive discount codes, coupons when ordering food on the app

![37E8F48C-6F4F-4F89-87DA-408E3668CD00](https://user-images.githubusercontent.com/10969626/207221236-5cba75bc-a09b-41aa-8c67-fc71ea7c59b6.png)

**Comment by russeg** [comment]
Eww coupon codes 😁  Ignore it then.

I have added tons of Grab domains on my NextDNS, as long as ordering works all good for me.

**Comment by StevenBlack** [comment]
Thank you @russeg and @bigdargon.

Closing.
