### ISSUE TITLE
(www.)getfirefox.com is not porn or adblock-worthy - please remove from all blocklists

### ISSUE THREAD

**Issue by thomasmerz** [StevenBlack/hosts#2172]
FYI: @sinfonietta 

`getfirefox.com` is redirecting to: `https://www.mozilla.org/de/firefox/new/?redirect_source=getfirefox-com` - please remove it from any/all blocklists. Thank you 👍🏻

![image](https://user-images.githubusercontent.com/18568381/207261702-49311a2d-045f-45cc-973f-b8a834b5c8c3.png)

```
 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/extensions/porn/clefspeare13/hosts:
   getfirefox.com
   www.getfirefox.com
 Match found in https://mypdns.org/clefspeare13/pornhosts/-/raw/master/download_here/0.0.0.0/hosts:
   www.getfirefox.com
```

**Comment by StevenBlack** [comment]
Thank you Thomas @thomasmerz this is fixed in commit d4c69898.  This will go live in the next release.

This was in the @clefspeare13 list, which is no longer maintained, that I've taken permanently into this repo as an archived resource.
