### ISSUE TITLE
More Porn Sites to Add

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#2175]
Hello @StevenBlack and @Sinfonietta,

I've compiled more porn sites to add to the filter:

wetqueen.com
dankwank.net
pornito.xxx
pornfaze.com
danielleftv.com
leaked.fans
thothub.org
faponic.com
fapachi.com
deepertv.com
nhentai.website
hentaiera.com
hentairox.com
xlecx.one
nana.my.id
koushoku.org
porn-video-clips.net
escortsgreeneyes.com
tbassflick.com
modelsfreecams.com
fuckmeblack.com
galacticgirls.com
glamourfilms.com
babecenterfolds.com
xxxlipsblog.com
bbwstar.com
incestflix.xxx
pornglob.com
fatsexstar.com
adultworldmedia.com
fetish666.com
xxxvampiresex.com
pornbts.com
resortgirls.escortbook.com
pornobrazzers.com
porn-brazzers.com
joiparadise.com

Thank you for your awesome work!

**Comment by StevenBlack** [comment]
Ping @Sinfonietta!

**Comment by Sinfonietta** [comment]
@StevenBlack I have added these to my list.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and thank you @g1t3m. This is included in the latest release.
