### ISSUE TITLE
Non-github mirrors deprecated?

### ISSUE THREAD

**Issue by Frenzgyn** [StevenBlack/hosts#2176]
Hi! 
First thing, thanks for all the work.

I am an Hostsman for Win user and I noticed that the non github mirrors are not updates since 30 Nov, they're not actively supported anymore and I missed the announce or anything bad happened? 

Thanks!

**Comment by MultiKoopa** [comment]
I also use Hostsman for Windows, and noticed the same thing. Was wondering about that.

**Comment by StevenBlack** [comment]
Thank you for this @Frenzgyn.  You're right, this is a bug.

**Comment by StevenBlack** [comment]
This is now fixed @Frenzgyn. Thanks again for the heads-up.

Closing.

**Comment by MultiKoopa** [comment]
is this happening again?

**Comment by Frenzgyn** [comment]
> is this happening again?

Yep, it seems so. 

@StevenBlack , sorry to tag you directly, but it seems futile to open a new issue.

**Comment by StevenBlack** [comment]
Thank you @MultiKoopa and @Frenzgyn.  I'm happy to report, this is now fixed!

**Comment by MultiKoopa** [comment]
Thank you!
