### ISSUE TITLE
help

### ISSUE THREAD

**Issue by krma12** [StevenBlack/hosts#2177]
can someone teach me how to use it??

**Comment by gothic-bum** [comment]
Since you provided absolutely no information about your specific configuration, you may find the following links helpful with learning what a `hosts` file is, and how to replace/edit it:  

https://en.wikipedia.org/wiki/Hosts_(file)
https://www.whatsmydns.net/hosts-file.html

**Comment by StevenBlack** [comment]
Thank you for the assist @gothic-bum.

@krma12 please review the links provided by @gothic-bum then read the [repository readme](https://github.com/StevenBlack/hosts/blob/master/readme.md). After that, we're happy to assist with specific questions.

Closing.
