### ISSUE TITLE
amazon forum falsely blocked

### ISSUE THREAD

**Issue by privacyonly** [StevenBlack/hosts#2178]
https://www.amazonforum.com/

d1bd3wxsyuz0t7.cloudfront.net

**Comment by gothic-bum** [comment]
It is not falsely blocked. It is a deceptive site.

https://safebrowsing.google.com/safebrowsing/diagnostic?site=http%3A%2F%2Fd1bd3wxsyuz0t7.cloudfront.net%2F

https://www.virustotal.com/gui/url/f3846b1929a49a4c5b98624a99779f611ebe580f343c9f36a3f3aa4dec4d4809

**Comment by StevenBlack** [comment]
Thank you for the assist @gothic-bum.

Thank you for opening this issue @privacyonly, but I decline to entertain this request.

Closing.
