### ISSUE TITLE
Failed to download hosts sources

### ISSUE THREAD

**Issue by virusfreak7** [StevenBlack/hosts#2179]
Hi @StevenBlack 
Hosts not updating from sources. please look into it

![Screenshot_20221221-105750](https://user-images.githubusercontent.com/66295145/208828686-50a1d94b-e5ae-4c74-ba65-0613ec2ba229.jpg)

**Comment by StevenBlack** [comment]
@virusfreak7 works here.  I'm gonna need a lot more information about your app, your platform, etc.

Closing.
