### ISSUE TITLE
Paramount+ on SkyQ Receiver: tags.tiqcdn.com

### ISSUE THREAD

**Issue by the0bone** [StevenBlack/hosts#2180]
Hi,
due to the block of tags.tiqcdn.com Paramount+ is not working on SkyQ Receiver in Germany.

**Comment by StevenBlack** [comment]
Hello @the0bone thank you for this observation.

That's a tracker. It comes to us from upstream, via yoyo.org.  Please make your case with pgl@yoyo.org.

**Comment by amit-bh** [comment]
Will also add, blocking tags.tiqcdn.com seems to block logging into Sunlife insurance portal

**Comment by StevenBlack** [comment]
Thank you for this observation Amit @amit-bh.

So we're clear, there are no "legitimate" domains here.

It doesn't matter if a listing a domain interferes with fundraising by the Holy Sisters relict of Mother Theresa of Calcutta. If the domain vehicles tracking, adware, or worse, it gets listed here.

This repository serves people who value privacy and online safety, not Sunlife Insurance. If Sunlife or Paramopunt or SkyQ want people using their websites, maybe they should be  less scummy about it.
