### ISSUE TITLE
Add these porn site to the porn host file

### ISSUE THREAD

**Issue by z2typ** [StevenBlack/hosts#2184]
There are the list of some porn sites that are on first or second page of simple google search
https://www.xvideos51.com/
https://www.pussyboy.net/
https://www.pornbfvideo.com/
https://www.sexvid.pro/

**Comment by StevenBlack** [comment]
Ping @sinfonietta for inclusion.

**Comment by Sinfonietta** [comment]
@StevenBlack I have added these to my list.

**Comment by StevenBlack** [comment]
Thank you @z2typ and @Sinfonietta!

Closing.
