### ISSUE TITLE
Please add these porn sites

### ISSUE THREAD

**Issue by wombabin** [StevenBlack/hosts#2185]
Pinging @Sinfonietta for inclusion.

imhentai.xxx
tmohentai.com
porncomixinfo.net
gntai.net
manga18fx.com

**Comment by Sinfonietta** [comment]
@StevenBlack I have added these to my list.

**Comment by StevenBlack** [comment]
Thank you @wombabin and @Sinfonietta!  These domains are included in the latest release.

Closing.
