### ISSUE TITLE
Soundcloud not playing on iOS

### ISSUE THREAD

**Issue by firstdivision** [StevenBlack/hosts#2186]
With pi-hole enabled I cannot get to SoundCloud songs on my iOS device; if I go off my network and onto cell service it works.  It looks like SoundCloud is trying to load something in the background that if blocked prevents it from playing?

Example link that I've tested:
[SoundCloud ](https://soundcloud.com/achane/heading-south)

It works on desktop (Firefox) though - so I'm not sure what's going on.  Why would it work one way and not the other - iOS / Safari must be trying to do something different (or soundcloud is changing behavior based on browser)?

As best I can tell from looking at the query page it's something to do with "geolocation.onetrust.com"? (not sure but it's my best guess).

**Comment by StevenBlack** [comment]
Hello @firstdivision thank you for this.

The domain `geolocation.onetrust.com` is blocked by tow of our curated lists, upstream from us.  When you whitelist that, does it resolve the issue?

**Comment by firstdivision** [comment]
I whitelisted both A and HTTPS and it works.
