### ISSUE TITLE
Amazon Video stopped working (EU)

### ISSUE THREAD

**Issue by nilvanis** [StevenBlack/hosts#2187]
Just noticed Amazon Video stopped playing videos today.
App seems to be working fine, but when a video is to be played it throws an error.

Apparently whitelisting api.eu-west-1.aiv-delivery.net solves the problem for a particular EU region.

**Comment by StevenBlack** [comment]
Thank you for this Nilvanis @nilvanis.

We don't presently block the domain `api.eu-west-1.aiv-delivery.net`... I just made a new release a few moments ago.

**Comment by nilvanis** [comment]
Thanks @StevenBlack 
Amazon Video works like a charm again with an updated gravity and without `api.eu-west-1.aiv-delivery.net` explicitly on the whitelist.
