### ISSUE TITLE
Malware spreading forum (en.xachinaproject.fun)

### ISSUE THREAD

**Issue by 0x11DFE** [StevenBlack/hosts#2190]
The owner of this website is multi-accounting and spreading his malware (RedLine).
https://en.xachinaproject.fun/threads/9/ https://en.xachinaproject.fun/threads/11/ -> https://bazaar.abuse.ch/sample/d5e2e0e79a64e6fd5d96fa7b9cf2d27cc2d07f68bfd09a64824c2d6b208c22f6

**Comment by pukpuker** [comment]
Да сайт норм, вы че рагули

**Comment by Gusenkov7** [comment]
Норм форум, так-то лучший в своем роде, стиллеров, вирусни нет, автор глупец американский и ничего не понимает...

**Comment by StevenBlack** [comment]
Tesla @0x11DFE thank you for this suggestion.

Alexey @pukpuker спасибо за это.  

@Gusenkov7 пожалуйста, будь милым. Мы все здесь хорошие люди.

Я позабочусь об этом.

**Comment by 0x11DFE** [comment]
The malware was updated, And i am being attacked by Russians. Oh i remember the malware has timezone based checks...
SHA256: bc981589e3b87e8ff9292af7e40662b33933fa896dc214677b2bbf1b3d4fabe4

![explorer_8cyVtAmZq2](https://user-images.githubusercontent.com/43712252/211228091-38627ecf-f630-4089-9cd3-0d97fd830449.png)

**Comment by 0x11DFE** [comment]
They also have a mirror hosted at antihohol.cloud

**Comment by pukpuker** [comment]
> The malware was updated, And i am being attacked by Russians. Oh i remember the malware has timezone based checks... SHA256: a4fbd5dfa976d2526590065d16e166ae2ba5b58a17bdcc8d1efbaca35ae55cdd
> 
> ![explorer_8cyVtAmZq2](https://user-images.githubusercontent.com/43712252/211228091-38627ecf-f630-4089-9cd3-0d97fd830449.png)

How u can reverse throw dnspy, if file c++ with vmp xD

**Comment by 0x11DFE** [comment]
> > The malware was updated, And i am being attacked by Russians. Oh i remember the malware has timezone based checks... SHA256: a4fbd5dfa976d2526590065d16e166ae2ba5b58a17bdcc8d1efbaca35ae55cdd
> > ![explorer_8cyVtAmZq2](https://user-images.githubusercontent.com/43712252/211228091-38627ecf-f630-4089-9cd3-0d97fd830449.png)
> 
> How u can reverse throw dnspy, if file c++ with vmp xD

It is packed and no this malware is made in C#.

**Comment by StevenBlack** [comment]
Thank you to everyone for their input on this.

I've decided to list domain `en.xachinaproject.fun`.

Closing.

**Comment by pukpuker** [comment]
-

**Comment by 0x11DFE** [comment]
> 

They have a mirror running the website is still up!
https://antihohol.cloud/

**Comment by 0x11DFE** [comment]
http://asfamilystyle.ru/

**Comment by pukpuker** [comment]
> http://asfamilystyle.ru/

рагулих, че по сайту? Вроде все норм

**Comment by 0x11DFE** [comment]
> > http://asfamilystyle.ru/
> 
> рагулих, че по сайту? Вроде все норм

Sure yes it only spreads malware...

**Comment by 0x11DFE** [comment]
@StevenBlack Please add the domain to the list.
