### ISSUE TITLE
jbhivi.store

### ISSUE THREAD

**Issue by gyCfjSnO** [StevenBlack/hosts#2191]
Can you kindly please block `https://jbhivi.store/`

It is a phishing website and targets https://jbhifi.com.au, they have [put up a post on Facebook warning the public and in the screenshot is the URL](https://m.facebook.com/JBHiFi/photos/a.214773761888730/6299810073385038/?type=3&mibextid=Nif5oz)

**Comment by StevenBlack** [comment]
Thank you for reporting this @gyCfjSnO.  I'll have a look.

**Comment by gyCfjSnO** [comment]
> Thank you for reporting this @gyCfjSnO. I'll have a look.

Looks like the domain registrar has temporary put a hold on the domain since I reported it for abuse.

**Comment by StevenBlack** [comment]
Thank you @gyCfjSnO yes, this domain appears deleted.

Closing.
