### ISSUE TITLE
Australia Post | ssl.o.auspost.com.au

### ISSUE THREAD

**Issue by gyCfjSnO** [StevenBlack/hosts#2192]
I keep getting an error in the Australia Post tracking app on Android. The error I get is `Connection issues, try again later. (Error 500)`

I checked AdGuard Home and the list I use `HaGeZi Personal Black & White` seems to be blocking `ssl.o.auspost.com.au` but I couldn't find out why.

I have opened an issue on HaGeZi's GitHub and in the interim checked `https://urlfilter.adtidy.org/v1/checkDomain?domain=ssl.o.auspost.com.au` and found you were also blocking this domain. 

Hoping you can look into it as it might be a false positive?

**Comment by gothic-bum** [comment]
`ssl.o.auspost.com.au` is an alias for the CNAME `o.auspost.com.au.ssl.d2.sc.omtrdc.net` which is a disguised tracker.

**Comment by StevenBlack** [comment]
Thank you for this @gyCfjSnO.

This is a CNAME domain that points to `o.auspost.com.au.ssl.d2.sc.omtrdc.net`.

This is so sketch. I decline to unblock this.

```bash
$ dig ssl.o.auspost.com.au all                                                                          

ssl.o.auspost.com.au.	756	IN	CNAME	o.auspost.com.au.ssl.d2.sc.omtrdc.net.
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	63.140.38.123
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	63.140.38.100
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	63.140.38.0
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	63.140.38.160
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	63.140.38.20
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	63.140.38.229
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	63.140.38.169
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	63.140.38.201
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	63.140.38.149
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	63.140.38.120
```
