### ISSUE TITLE
.DS_Store files causes crash / request

### ISSUE THREAD

**Issue by lavventura** [StevenBlack/hosts#22]
Hi there,

I have to say right away that I'm no programmer, just started learning my first language (Python), those are only my observations and please do not laugh at my terminology ;).

First off, I'm really happy about how your script works, this is something that I've been looking for, fixes my problem without an app.
I've been using Gas Mask, it's an OS X app which allows you to use different hosts files and combine them into one from different remote sources with auto-updating. 
It didn't allow for using so many hosts source files combined into one - crashed when putting one too many, sometimes died on it's own (so I wrote a launchdaemon which kept it alive but then at some point I would get stuck with two instances running at the same time...)

[Python 2.7.10 / OS X 10.10.4]
Everything worked fine when I ran the script for the first time. 
However, when I've decided that I'm feeling adventurous and added my own hosts to /data/ then the script showed an error right from the start.  .DS_Store does not have hosts file and update file (can't give you an exact reading because I've fixed this issue since yesterday). 
And then I realized that I first ran the script before Finder added .DS_Store files to the folder.
That means your script reads the hidden system files and treats them as if they were another hosts source.

I don't know what system you are using but (wiki) .DS_Store is the name of a file in the Apple OS X operating system for storing custom attributes of a folder such as the position of icons or the choice of a background image.
Maybe you could put something in your script that ignores those files?

I've installed an app called Asepsis, which keeps all .DS_Store files in one folder and links them to corresponding folders. Then I deleted those files from your script's folder via terminal and the script started working again.

Also, I managed to create a hosts file which is readable by your script from malwaredomains.com by running a function in terminal which adds specified text string to every line in a text file. 
Maybe you  could do some magic voo-doo which would allow your script to re-do/re-organize the contents of a file to a 127.0.0.1 domain.com format?
There are many lists, used by different blockers, but they are in such a weird line format that I've got (currently) no clue how to re-organise them in bulk by some set rules and make them usable for a hosts file.

Now, after adding malwaredomains.com list and my private one I'm at 36361 unique entries.

**Comment by FrancoGag** [comment]
Adding this after "# Project Settings" solves this issue
 ```python
DS_STORE = BASEDIR_PATH + '/data/.DS_Store')
if os.path.isfile(DS_STORE):
    os.remove(DS_STORE)
```

**Comment by Atavic** [comment]
Well known Apple trash files.
