### ISSUE TITLE
Add these sites that keep popping up on Facebook

### ISSUE THREAD

**Issue by Swoooshhh** [StevenBlack/hosts#2201]
Pervuse.com
Familygid.com

**Comment by StevenBlack** [comment]
Thank you for this Anon @Swoooshhh we should block these domains because...?

**Comment by Swoooshhh** [comment]
> Thank you for this Anon @Swoooshhh we should block these domains because...?

They are porn sites, unless I made an issue on the wrong host file l

**Comment by StevenBlack** [comment]
Ping @sinfonietta for inclusion upstream.
