### ISSUE TITLE
Australia Post

### ISSUE THREAD

**Issue by gyCfjSnO** [StevenBlack/hosts#2202]
I believe the following websites are phishing websites and target [Australia Post](https://auspost.com.au/).

```
auspost-record.com
alert-auspost.com
auspost-input.com
```

The last two domains listed above are only accessible from a mobile device. I will be working on reporting all domains listed above to the appropriate web host and domain registrar for removal.

Lastly here are the VirusTotal links for the domains: [auspost-record](https://www.virustotal.com/gui/url/1a8d8de0b743f9a1849f4010b33ff1e7de23a63174b473b727a36454802dd4e4?nocache=1), [alert-auspost](https://www.virustotal.com/gui/url/60cc78d1f53c0b2dfc3bb363f36ad22e94d904dae3a597dbfead5452bf092a42?nocache=1), [auspost-input](https://www.virustotal.com/gui/url/27eb1f41311b9fd5dcc8eced002afb87c843932928c85d450c28c1366e180d2b?nocache=1)

![auspost-record com](https://user-images.githubusercontent.com/49738152/212236058-cb36e859-c09b-457b-96a9-57b12807f5f2.png)
![alert-auspost com](https://user-images.githubusercontent.com/49738152/212236071-3b99e4bd-f9e7-4a44-8d46-fe7149b5cc14.png)
![auspost-input com](https://user-images.githubusercontent.com/49738152/212236077-6f7261f9-2ce2-4253-8da6-a8cbe5aa0161.png)

**Comment by StevenBlack** [comment]
Thank you @gyCfjSnO these are added in commit b7122ca2.

Closing.
