### ISSUE TITLE
mywot.com is blocked

### ISSUE THREAD

**Issue by Batman2814** [StevenBlack/hosts#2204]
The domain for mywot.com is blocker by rule blocklist rules. It should be unblocked because it WOT tells you if the website in details if it safe and what the ratings of the website is. So if you can have it unblocked.

**Comment by StevenBlack** [comment]
Hello @Batman2814 thank you for this.

Please see issue #1285.

It doesn't matter what a website tells us. If the website is involved in adware, tracking, or worse, it gets listed here.

Has `mywot.com` changed?

**Comment by StevenBlack** [comment]
I just checked `mywot.com`. Its home page does 112 requests including 5 XHR requests, 19 JS requests, a web socket, a web worker...

This `mywot.com` website is not OK.

Closing.
