### ISSUE TITLE
Recommend SwitchHosts?

### ISSUE THREAD

**Issue by noyannus** [StevenBlack/hosts#2205]
Is [Switchhosts](https://github.com/oldj/SwitchHosts) worth mentioning in the Readme?
Have not tried yet, so unsure if it is worth a recommendation.

**Comment by StevenBlack** [comment]
Thank you for this @noyannus. I'm sure if it was comemndable, someone using it would recommend it.

Closing.

**Comment by noyannus** [comment]
After months of use I now can recommend it. The UI could be a bit improved, but functionally it is OK.
![2023-04-29_09-04-30](https://user-images.githubusercontent.com/6339921/235289244-87fb9410-75af-4eef-a323-051497969ed9.png)
