### ISSUE TITLE
ads script js add request 

### ISSUE THREAD

**Issue by halilnevzat** [StevenBlack/hosts#2206]
https://dyncdn2.com/static/20/js/showads.js

its a ads script that loads ads randomly.

**Comment by StevenBlack** [comment]
Thank you for this Halil @halilnevzat.

Checking this, here's what I get.

```bash
$ curl https://dyncdn2.com/static/20/js/showads.js                                                      

var abbz = true;
```

That's it. Nothing malicious here.

Closing.
