### ISSUE TITLE
15 invalid domains found when retrieving the list with Pi-hole

### ISSUE THREAD

**Issue by Trainax** [StevenBlack/hosts#2207]
Hello. After updating Pi-hole to the latest version I noticed some invalid domains when retrieving the list. I tried looking at open issues and I couldn't find one which talked about this. I'm sorry if this has already been discussed.

![immagine](https://user-images.githubusercontent.com/30187360/212568490-900fd281-e1c3-4c34-90b0-1493c3346388.png)

Thanks for your work on the list! It's very useful

**Comment by StevenBlack** [comment]
Thank you for this Davide @Trainax.

Line numbers would be helpful. 

I presume this refers to some domains at top-of-file. This isn't an issue since these domains come from hosts files included in various operating systems.

Closing.
