### ISSUE TITLE
new host file

### ISSUE THREAD

**Issue by www-k9** [StevenBlack/hosts#2209]
Hello , 

Could you please include my hosts file
https://github.com/www-k9/hosts 

You can consider it as Arabic Filter
It will be updated frequently

Thank you

**Comment by StevenBlack** [comment]
Hello @www-k9 thank you for your generous offer.

For now I must respectfully decline.

To accept your list I need to see a track record and a history of curation.

Joining Github today, creating a repo today, and making three commits today, is insufficient history, and no basis for trust.

Let's talk again in several months.

Closing.

**Comment by www-k9** [comment]
Hello @StevenBlack ,

Could you please check it back  again now ?

And if it is still not ready , can you tell me what is the minimum requirement you are looking for ?

Thank you.

**Comment by StevenBlack** [comment]
Hello @www-k9 thank you for your question.

I'll happily consider including your hosts list after you've established a track record of dedication to the serious and ongoing task of its curation.

Two weeks is just not a long time to be doing this.

Consider it from this point of view. What would YOU require to propagate the work of a new and anonymous GitHub user onto potentially millions of networks and devices worldwide, belonging to people who trust you?

How would you answer that?

I suspect your answer would be, "I require much more than the visible evidence here."

Am I correct?

**Comment by www-k9** [comment]
Hello @StevenBlack ,

Thank you for your patience and attention .

> Consider it from this point of view. What would YOU require to propagate the work of a new and anonymous GitHub user onto potentially millions of networks and devices worldwide, belonging to people who trust you?

> How would you answer that?

> I suspect your answer would be, "I require much more than the visible evidence here."

> Am I correct?

Yes

> Hello @www-k9 thank you for your question.
> 
> I'll happily consider including your hosts list after you've established a track record of dedication to the serious and ongoing task of its curation.
> 
> Two weeks is not a long time to be doing this.
> 
> Consider it from this point of view. What would YOU require to propagate the work of a new and anonymous GitHub user onto potentially millions of networks and devices worldwide, belonging to people who trust you?
> 
> How would you answer that?
> 
> I suspect your answer would be, "I require much more than the visible evidence here."
> 
> Am I correct?

**Comment by www-k9** [comment]
Hello again @StevenBlack ,

Could you please check it back again now ?
I really hope to be an a little piece in your great work.

Thank you
