### ISSUE TITLE
Please add these gambling sites

### ISSUE THREAD

**Issue by OakSquirrel** [StevenBlack/hosts#2211]
https://mysticlake.com/
https://www.ticasino.com/
https://treasureisland.com/casino/
https://fanduel.com/
https://betmgm.com/
https://draftkings.com/
https://www.bovada.lv/
https://www.betus.com.pa/
https://www.betonline.ag/
https://www.actionnetwork.com/
https://caesars.com/
https://pointsbet.com/
https://wynnbet.com/
https://betfredsports.com/
https://littlesixcasino.com/
https://www.stcroix-casinos.com/
https://www.canterburypark.com/
https://runaces.com/
https://www.jackpotjunction.com/
https://grandcasinomn.com/
http://www.blackbearcasinoresort.com/
http://www.prairiesedgecasino.com/
https://www.northernlightscasino.com/
https://www.starcasino.com/

**Comment by StevenBlack** [comment]
Thank you for this @OakSquirrel.

Ping @bigdargon for inclusion upstream.

**Comment by OakSquirrel** [comment]
@bigdargon are you able to help with this inclusion request?

**Comment by OakSquirrel** [comment]
@bigdargon Thank you for your help. I was not aware of the full gambling filter. I will definitely check it out. I was looking for something exactly like this.
