### ISSUE TITLE
Please add these hosts

### ISSUE THREAD

**Issue by Cuupa** [StevenBlack/hosts#2215]
Adware: 
vogulprecast.com
ee.vogulprecast.com
popupblockergold.com
lps1.cyber-guard.me
cyber-guard.me
supremeadblocker.info

scam:
offer.great1waytowsuccess.com
great1waytowsuccess.com

PS: great work

**Comment by StevenBlack** [comment]
Hello Simon @Cuupa thank you for these suggestions.

Why would we include each one of these? Thank you for clarifying.
