### ISSUE TITLE
Google Plus hosts

### ISSUE THREAD

**Issue by strotee** [StevenBlack/hosts#2216]
hey, long time user of your hosts file. I was perusing the file and wondered why Google Plus domains were commented out plus why they still point at 127.0.0.1.  Thanks for the upkeep on this project.

`# Google Plus`
`#127.0.0.1 plus.l.google.com`
`#127.0.0.1 plus.sandbox.google.com`
`#127.0.0.1 plusone.google.com`
`0.0.0.0 plus.google.com`

**Comment by StevenBlack** [comment]
Hi @strotee! 

Those lines are found in our social media extensioned variants only.

Closing.

**Comment by StevenBlack** [comment]
@strotee those lines say `#127.0.0.1 ...` because they are comments. The Python parsers here don't touch comments.  In this case the upstream curator of social media domains uses `127.0.0.1` as the ip address.
