### ISSUE TITLE
Dyson App Digital Assistant

### ISSUE THREAD

**Issue by azafrak** [StevenBlack/hosts#2219]
Hello ,

The digital assistant does not work in the dyson app. Stevenblack and Nextdns get stuck in their hurdles. Can you help remove the following obstacles?

vms.boldchat.com
mcpwgrxj4n94hv1pvdyqw0zwdxyq.device.marketingcloudapis.com

![AD6D426E-15F7-432C-8529-659B2ED7B885](https://user-images.githubusercontent.com/30311445/214412437-fe08629e-7795-45e0-af4c-da3037e45a78.png)
![4EC186DF-B221-43F7-B937-478D0B27B5FC](https://user-images.githubusercontent.com/30311445/214412465-1ab7225d-acac-4a82-b34a-ad86f65b3463.png)
![8338F0FE-08AE-42F7-9EE2-DB13373E7091](https://user-images.githubusercontent.com/30311445/214412471-94196c71-8189-4b36-9fcc-782b7c3f838f.jpeg)

**Comment by StevenBlack** [comment]
Thank you for this @azafrak.

The domain `vms.boldchat.com` comes to us from upstream at Shady-Hosts. Ping @shreyasminocha can you look into this one for us.

The domain `mcpwgrxj4n94hv1pvdyqw0zwdxyq.device.marketingcloudapis.com` is a CNAME record that cloaks `s50.device.marketingcloudapis.com.`. Let's see if unblocking `vms.boldchat.com` fixes this, first.

```bash
$ dig mcpwgrxj4n94hv1pvdyqw0zwdxyq.device.marketingcloudapis.com +all                                   15:44:36
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48442
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; NSID: 32 39 6d 32 32 31 ("29m221")
;; QUESTION SECTION:
;mcpwgrxj4n94hv1pvdyqw0zwdxyq.device.marketingcloudapis.com. IN A

;; ANSWER SECTION:
mcpwgrxj4n94hv1pvdyqw0zwdxyq.device.marketingcloudapis.com. 237	IN CNAME s50.device.marketingcloudapis.com.
s50.device.marketingcloudapis.com. 57 IN A	161.71.33.241
```

**Comment by shreyasminocha** [comment]
I've removed `vms.boldchat.com` :+1:

**Comment by StevenBlack** [comment]
Thank you @shreyasminocha!
