### ISSUE TITLE
Kinda neat-freak

### ISSUE THREAD

**Issue by COALROCK8642** [StevenBlack/hosts#2223]
Can you just sort these lists?

**Comment by StevenBlack** [comment]
Thank you for your question @COALROCK8642

Presently there is no option to sort our hosts files during generation.  I would entertain a pull request for that 😄.

I have a repo named [ghosts](https://github.com/StevenBlack/ghosts) which can sort hosts files (among other manipulations). Ghosts is written in Go, hence the "G".

The reason we don't sort amalgamated hosts files is to preserve or curator's file headers and comments.

Closing.
