### ISSUE TITLE
Please add these Porn sites

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#2224]
Hello @StevenBlack and @Sinfonietta,

Here are more porn sites to add to the porn blocklist:

wetqueen.com
dankwank.net
pornito.xxx
pornfaze.com
danielleftv.com
leaked.fans
thothub.org
faponic.com
fapachi.com
deepertv.com
nhentai.website
hentaiera.com
hentairox.com
xlecx.one
nana.my.id
koushoku.org
porn-video-clips.net
escortsgreeneyes.com
tbassflick.com
modelsfreecams.com
fuckmeblack.com
galacticgirls.com
glamourfilms.com
babecenterfolds.com
xxxlipsblog.com
bbwstar.com
incestflix.xxx
pornglob.com
fatsexstar.com
adultworldmedia.com
fetish666.com
xxxvampiresex.com
pornbts.com
resortgirls.escortbook.com
pornobrazzers.com
porn-brazzers.com
joiparadise.com
hanimehentai.tv
okhentai.net
myhentaigallery.org
xhomealone.com
haho.moe
pervuse.com
familygid.com
nhentai.xxx

As always, your work is appreciated!

**Comment by StevenBlack** [comment]
Thank you for this @g1t3m.

We already 37 of the 45 domains listed above ⬆️⬆️⬆️ 

Those we don't carry yet are:

familygid.com 
haho.moe 
hanimehentai.tv 
myhentaigallery.org 
nhentai.xxx 
okhentai.net 
pervuse.com 
xhomealone.com

Ping @sinfonietta

**Comment by StevenBlack** [comment]
Closing.
