### ISSUE TITLE
Cannot complete Android initial setup with Family Link

### ISSUE THREAD

**Issue by Anoni-Mouse** [StevenBlack/hosts#2226]
Hello, 
First of all, a big big THANK YOU for the great work, I love it.

I have my Raspberry Pi 4 with Pi-Hole installed and getting the default Steven Black list of hosts to block using my local DNS and it works like a charm. I have a 11 years-old kid who messed his Android phone which is also managed by Google Family Link, so I had to reset the phone and start from scratch. So at the Android initial setup pages, I selected the language, then connected to my Wi-Fi (which gives me the IP address with the DNS server of my local Pi-Hole running on Raspberry). Then I inserted my kid's Google account and subsequently Google prompted me (as a family manager) to insert my credentials to help my kid finish his phone setup. At this point, Google tries to install the Family Link app/component to manage the phone by downloading and installing this necessary software used to manage content, apps, permissions etc. Here the download failed and I have tried several times, even restarting the phone and retrying the steps again and again. Then I had this hint that it might be the DNS (which uses the hosts from Steven Black), and hence I disabled the DNS filtering for few minutes, and guess what? Now I could finish setup on my kid's phone correctly.

Unfortunately I don't have the logs at hand to show you what endpoints were blocked. Has anyone encountered this issue before? Is it a known issue? If yes, what are the domains I have to white list in order to let this go smoothly in the future? I have to reset other 2 devices managed by Google's family link

Thank you

**Comment by StevenBlack** [comment]
Thank you for this @Anoni-Mouse and thank you for your very kind words!

I'm going to need the the download domains required by Google to narrow this down. Does anybody know?

**Comment by Anoni-Mouse** [comment]
> 

Wow! That was a fast reply! You ROCK!
Well, I can help here, I have to reset other two devices, but I need some help/instructions on how to do that. Where do you want me to check? Maybe Pi-Hole is a good start point, but I use it as is without fiddling around on the techy stuff, so I'd appreciate if you have some steps to follow, traces to enable on pi-hole etc, so as I can come up with a good repro

**Comment by StevenBlack** [comment]
@Anoni-Mouse we would need to watch the network traffic to assess the interactions between the phone and various domains during this process.  This isn't easy.

**Comment by icedterminal** [comment]
I'm just creeping around. Thought I'd provide something that may help.

At the time I am commenting, this was posted four days ago. Act fast as the log could still be there. Pi-hole rotates logs once a day at midnight (00:00). The oldest log is kept for five days and is then deleted on the next rotate. The pi-hole UI only shows the 100 most recent queries.

The logs are kept at `/var/log/pihole`. The file in question will be the oldest so it should be named `pihole.log.5.gz`. You can use SSH via command line to`sudo` copy this file to a location where you can change permissions. As it is normally locked for everyone but the software. Extract the log file and open with any text editor.  When you open the log, on the left you will see the time stamp, and on the right whether it was queried, blocked, forwarded or replied. Like this:

```
Feb 13 03:18:06 dnsmasq[1568]: query[HTTPS] ms.applovin.com from 192.168.1.53
Feb 13 03:18:06 dnsmasq[1568]: gravity blocked ms.applovin.com is NODATA
```

If you remember the time at which setup this phone (think hard!) you can narrow it down. This is what I did to back track an ad that popped up for a mobile game. I needed to block the domain but was away from my system at the time. I jotted down the time and grabbed the log when I got back.

An alternative is to use `pihole-FTL.db` located at `/etc/pihole`. It's an SQLite3 database that contains the same information. But this requires the use of an additional piece of software. An open source one is here: https://sqlitebrowser.org/dl/

**Comment by StevenBlack** [comment]
Hey thanks @icedterminal that's a really nice summary of some of Pi-hole's internal workings.

**Comment by icedterminal** [comment]
I just happen to think about this. In the event OP doesn't have the log anymore, in my spare time I can clone a fresh AVD state and set up a family link using my development emails. This should allow me to replicate the OP situation and find the offending domain. That way a real phone doesn't have to be reset and we don't have to wait for someone else to report the same problem.

**Comment by icedterminal** [comment]
I wasn't able to reproduce with a default pihole configuration. The family link process does ping `clients.google.com` variations which are known first party tracking domains. This makes sense here in terms of tracking your childs device. Additional domains are:

- play.googleapis.com
- android.googleapis.com
- accounts.google.com
- play.google.com
- *.googleusercontent.com
- sl.gstatic.com
- safebrowsing.googleapis.com
- people-pa.googleapis.com
- firebaseinstallations.googleapis.com
- families.google.com
- www3.l.google.com
- connectivitycheck.gstatic.com
- kidsmanagement-pa.googleapis.com

**Comment by StevenBlack** [comment]
Closing.
