### ISSUE TITLE
Broken Site: cdn.jwplayer.com is required for https://365.rtvslo.si / 4d.rtvslo.si

### ISSUE THREAD

**Issue by dmovztoq** [StevenBlack/hosts#2227]
The slovenian national radio-television organization's VOD portal will not function if cdn.jwplayer.com is blocked. The site will not load the crucial "rtv4d-main-player" html element because of missing code that is necessary for the embedded JWPlayer videos to work.

This was recently added in StevenHosts additions on February 7 2023 - I had to whitelist it.

**Comment by Salvoxia** [comment]
The same is true for eurosport.com live stream

**Comment by StevenBlack** [comment]
I have removed the domain `cdn.jwplayer.com`.  This will be live in the next release.

Closing.
