### ISSUE TITLE
Rifftrax channel/app (Roku) fails to start due to two filters

### ISSUE THREAD

**Issue by BlohoJo** [StevenBlack/hosts#2230]
The Rifftrax channel on Roku will not start if the following filter is active:

`assets-secure.applicaster.com`

Disabling this filter will allow the channel to start, but nothing will play if the following filter is active:

`cdn.jwplayer.com`

Disabling this filter will then allow the channel to function normally.

**Comment by StevenBlack** [comment]
Thank you for this @BlohoJo.

We are in the process of evaluating `cdn.jwplayer.com` now.

**Comment by StevenBlack** [comment]
I have removed the domain `cdn.jwplayer.com`.  This will be live in the next release.

Closing.
