### ISSUE TITLE
False domain

### ISSUE THREAD

**Issue by azafrak** [StevenBlack/hosts#2231]
Hello,

I was going to watch Video through the mobile application, but the Video did not open. When I checked, jwplayer had blocked it.

The issue was fixed when I added it to the permissions list.

I think this domain is wrong. Can you please remove it from the list?

*.cdn.jwplayer.com

**Comment by sudarpo** [comment]
Just curious, what kind of Video are you watching? What is the website URL?

**Comment by sudarpo** [comment]
This is duplicate issue - #2227 
https://github.com/StevenBlack/hosts/issues/2227

**Comment by azafrak** [comment]
> Just curious, what kind of Video are you watching? What is the website URL?

inattv APK. 

Don't worry, I'll show you with a photo when I get home :)

**Comment by azafrak** [comment]
> Just curious, what kind of Video are you watching? What is the website URL?

Do you believe now that it doesn't really work? If this address is blocked, videos do not work on Video playback platforms using jwplayer.

![7F0FD916-20A0-4069-88A4-922E43982E1A](https://user-images.githubusercontent.com/30311445/218831703-d29fefc3-74e4-46a9-8f9b-da736eb27475.png)
![6BB5810C-7A1C-4016-BE69-8732B34736B5](https://user-images.githubusercontent.com/30311445/218831723-074ac787-4c92-41ad-9dee-184f786ed55d.jpeg)

**Comment by sudarpo** [comment]
Sure thanks for the clarification. Again, this is same issue as #2227 

You can find cdn.jwplayer.com added on 7 Feb 2023, commented as 'Add ad and tracker domains.'
If you need this, you can add to your whitelist.

https://github.com/StevenBlack/hosts/commit/627205edd907b6d91aa49f3aa0c87fd0699c2b1d

**Comment by StevenBlack** [comment]
I have removed the domain `cdn.jwplayer.com`.  This will be live in the next release.

Closing.
