### ISSUE TITLE
Sites not found or blog removed from Blogger

### ISSUE THREAD

**Issue by abbbw** [StevenBlack/hosts#2235]
amateurcreampie.org
camcordersex.com
casadoscornos.blogspot.com
creampieinternal.com
depositodevideos.com.br
incestland.com
triplexangels.com

**Comment by StevenBlack** [comment]
@abbbw what are you saying here? Can you please clarify?  We don't carry most of these domains.

**Comment by abbbw** [comment]
> 

I'm sorry, I think I made a mistake. Well, just these ones (all are on the list):

depositodevideos.com.br
incestland.com
triplexangels.com
casadoscornos.blogspot.com

  It seems that the browser is unable to connect to these domains, so I believe they can be removed from the list.

**Comment by StevenBlack** [comment]
@abbbw we do not remove domains because browsers cannot connect to them. This is about so much more than browsers.

Closing.
