### ISSUE TITLE
Use `networking.hostFiles` for Nixos instead of `networking.extraHosts`

### ISSUE THREAD

**Issue by rafa-dot-el** [StevenBlack/hosts#2236]
Refactor the usage of `extraHosts` 
https://github.com/StevenBlack/hosts/blob/543acefaf78eb06f9f99cac0b6b6b1f6d09f4f50/flake.nix#L24
to use [`networking.hostFiles`](https://search.nixos.org/options?channel=22.11&show=networking.hostFiles)

**Comment by StevenBlack** [comment]
Thank you for this Rafa @rafa-dot-el.

We would do this because... ?

Please provide a reason. 😄

**Comment by rafa-dot-el** [comment]
I forgot this point, sorry. It is suggested by the documentation, it points out to use it

```
For adding hosts from derivation results, use {option}`networking.hostFiles` instead.
```
[Reference](
https://github.com/NixOS/nixpkgs/blob/38593bc3c0ee89bbee1ee58519e7585a356850c6/nixos/modules/config/networking.nix#L51)
