### ISSUE TITLE
Dont't block client-uc.heytapmobi.com

### ISSUE THREAD

**Issue by Hill-98** [StevenBlack/hosts#2237]
Blocking client-uc.heytapmobi.com will cause the account service exception of OPPO mobile phone system.

**Comment by StevenBlack** [comment]
Thank you for this question Zhong @Hill-98 Hill-98.

The domain `client-uc.heytapmobi.com` comes to us from upstream. Please submit this request to https://github.com/AdAway/adaway.github.io/issues.  Thanks!

**Comment by Hill-98** [comment]
I have reported this issue upstream https://github.com/AdAway/adaway.github.io/issues/354#issuecomment-1291652025

and issues reported by others https://github.com/AdAway/adaway.github.io/issues/361

But AdAway doesn't seem to be actively maintained anymore, so can you guys delete it individually?

**Comment by Hill-98** [comment]
@StevenBlack Hi, According to https://github.com/AdAway/adaway.github.io/issues/357, AdAway is currently unmaintained and we should probably consider abandoning it for now. Because no one maintains it, there may be a large number of false positive domain names.
