### ISSUE TITLE
Please Add These Porn Sites

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#2238]
Hello @StevenBlack and @sinfonietta,

May you add the following sites to the porn filter? As always your work is appreciated!

newvidporn.net
hanimehentai.tv
okhentai.net
myhentaigallery.org
xhomealone.com
haho.moe
pervuse.com
familygid.com
nhentai.xxx
sexynudes.tv
pornrat.net
tubeleakporn69.com
xteenagertube.net
iwansexhd.com
lovepornxx.com
famousluts.com
porn-word.com
videoxgirl.com
xxx-leakvid.com
wiki-porn.com
viralporno.net
sexleak-vid.com
pornxxteen.com
sexvidnow.com
xstarhub18.net
pornzonexxx.com
xcelebhub18.com
rainporn18.net
sunnyxporn69.com
relaxhub18.com
hornytub.com
hotxteens.net
hotmissvid.com
relaxpornvip.net
69xvideo.com
tubxxxporn.com
sexfreetime.com
sexvidnow.com
superpornx.com
huntersex.net
xnxxhdvid.com
sextubex.net
videopornxxx.net
allxsex.com
alohaxxx.com
porndhvideo.com
vipporntoday.com
thotdaily.com
skyporns.com
worldxporn.com
freeporn99.net
dirtysquirters.com
singlehotpic.blogspot.com
taboodude.com
pervyvideos.com
justincestporn.com
xvideos.one
newvideo18.net
porn4u.today
livecamparison.com
onlyhotleaks.com
uncensoredhentai.xxx
nyahentai.red
hentaistream.xxx
animeporn.tv
hentaiking.com
hentaifox.xxx
videopornvip.com
indianxvideos.net

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta.

Closing!
