### ISSUE TITLE
How to compile a host only for windows

### ISSUE THREAD

**Issue by MacgyverJohnson** [StevenBlack/hosts#224]
Hello @StevenBlack 
Is it possible to make a windows only host file? I mean without adaway which has many domains that targets only android users? How to exclude a host file from the unified host? Any python script??
Thanks

**Comment by StevenBlack** [comment]
Hi @MacgyverJohnson,

One way would be to clone the repo, and delete the folders that aren't for you, then run `python updateHostsFile.py`  specifying any extensions you'd like along with the remaining base data in the folders you kept.  In the future, data is only refreshed for the folders you've kept.

Unfortunately there is no reliable mobile - desktop segmentation other than the ones you may casually notice.

May I ask... why?  

Testing here, and by others, shows very little scale degradation in the number-range of hosts files we amalgamate, 10^5 hosts.  10^6 and 10^7 is different but there's not much to worry about at mid-10^5 hosts.

**Comment by MacgyverJohnson** [comment]
Thanks fo the swift reply.....
I just wanted to reduce the host file size....According to some sites too large host file degrades performance (I never found any definitive answer and the posts were outdated as well)
Is there any truth to it?
Thanks

**Comment by StevenBlack** [comment]
Windows is the OS that suffers most with large hosts files.

As I said, that typically happens with 10^6 number of hosts.  We're 10^5.
