### ISSUE TITLE
www.tvpassport.com

### ISSUE THREAD

**Issue by sr093906** [StevenBlack/hosts#2240]
In https://github.com/StevenBlack/hosts/blob/master/data/StevenBlack/hosts

Why is this site included?

**Comment by StevenBlack** [comment]
Thank you for your question Internet Anon @sr093906. Why do you want to know?

**Comment by StevenBlack** [comment]
@sr093906 I've written this before, in other past issues.

So we're clear, there is no "legit site" here.

It doesn't matter if listing a domain interferes with fundraising by the Holy Sisters relict of Mother Theresa of Calcutta. If the domain vehicles tracking, adware, or worse, it gets listed here.

This project serves people who value privacy and online safety. That's what we do here.

**Comment by StevenBlack** [comment]
@sr093906 it's not what a website does visibly, for the user.  Local TV Listings are 100% fine, nominally.

This is all about what a site does invisibly, all without the user's knowledge or consent.  So Local TV Listings, with shenanigans, that's what's not cool.
