### ISSUE TITLE
Broken site

### ISSUE THREAD

**Issue by mooreye** [StevenBlack/hosts#2243]
URL: https://www.leroymerlin.pl/podlogi-drewniane-panele-scienne/listwy-i-akcesoria-wykonczeniowe/listwy-przypodlogowe-pcv,a200,ps13937.html

With filter: https://i.imgur.com/UxCgIKr.png
Without filter: https://i.imgur.com/ELn7SzD.png

products don't load on site

**Comment by icedterminal** [comment]
Thanks for your report.

After reviewing the web console, it appears the product listings are delivered via a known tracking platform: https://www.dynamicyield.com/ - It is found in two hosts providers. This service is much like Optmizely in how it operates. Selling itself as a way to personalize user experience. It has a focus on commerce that targets and uniquely tracks users. As such, the domain is added to the host based on principle. If you find it has broken as service, you can whitelist it on your end.

**Comment by StevenBlack** [comment]
Thank you for this issue @mooreye. And thank you @icedterminal for the assist.

@icedterminal is correct, and this isn't going to change.

Closing.
