### ISSUE TITLE
github.com is blocked?

### ISSUE THREAD

**Issue by GreatWizard** [StevenBlack/hosts#2244]
I don't understand why github.com is blocked by using this hosts file (https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) within FreshTomato adblocker system.

Currerntly, I whitelisted github.com so here I am :wink:

Any ideas?

**Comment by StevenBlack** [comment]
Hello Guillaume @GreatWizard.

We don't list the domain `github.com` in any of our hosts files.

Closing.

**Comment by GreatWizard** [comment]
Hi @StevenBlack , I'm aware github is not in the blocklist but I'm still investigating from where the issue come from. Maybe FreshTomato acting strangely with "github.com.cnpmjs.org" :upside_down_face:
