### ISSUE TITLE
Add to porn list

### ISSUE THREAD

**Issue by 0xFlo** [StevenBlack/hosts#2245]
Could you please add the following to the porn list?

```
systems01.com
proxy.systems01.com
proxy.proxy-site-tor.com
streamtape.com
dood.yt
streamvid.net
```

Especially systems01.com would be the worst offender for anyone relying on the anti-porn hosts file. 
The other ones are known porn stream hosts.

I'm also wondering what happened to the other proxy sites mentioned below. It seems like the decision was made to add them to the porn extension, but most of these still work... 

https://github.com/StevenBlack/hosts/pull/763
https://github.com/StevenBlack/hosts/issues/754
#763 
#754

**Comment by Pkhrl** [comment]
Please add this as well:
https://watchporn.to

**Comment by StevenBlack** [comment]
Than k you Florian @0xFlo and @Pkhrl.

Ping @sinfonietta for inclusion upstream.

**Comment by gitols** [comment]
I've adding this on the upstream site from @Sinfonietta but do I need to include it here to? I saw that the last update mentioned adding domains coming from the issues section here.
https://github.com/Sinfonietta/hostfiles/issues/230

**Comment by Sinfonietta** [comment]
@StevenBlack and @0xFlo these domains are added.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta.

Closing.
