### ISSUE TITLE
Question: DNS Cache disabling.

### ISSUE THREAD

**Issue by Lagomorpheus** [StevenBlack/hosts#2247]
I've been using this list for awhile and only just now noticed the .bat to disable the cache service.

Does this make it so websites block instantly without having to wait 10+ minutes for it to update any time a change in hosts or connection changes? Windows had made the cache instant but following an update it went back to being slow, if I run the disabler will my PC work fine? 

Also if you have an m.2 SSD will the cache load instantly even with the service enabled?

**Comment by icedterminal** [comment]
Quote myself from reddit: 

> You shouldn't modify or replace the hosts file directly with such a large one. Windows has problems processing it.

https://www.reddit.com/r/WindowsHelp/comments/116qjca/_/

I actively participate in Windows help subs and this particular use case pops up often and with an array of problems people experience. There are also multiple issues in this repo regarding Windows acting up. See here: #2138 #2094 #2064 #2039 - some have potential workarounds you may try.

I highly encourage you to find a way to use this upstream with PiHole or similar. It's really easy to set up and is inexpensive to do with a raspberry pi board. Every device can benefit, not just your computer.

**Comment by Nyx1197** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by StevenBlack** [comment]
Thank you for your question @Lagomorpheus.

As someone once said, there are two problems in computer science:
1. Naming things
2. Cache invalidation
3. Off-by-one errors 😄 

Within the bat file, this line...

```
ipconfig /flushdns
```
flushes DNS cache, so the new hosts file takes immediate effect, yes. Without this, the `cache invalidation`, and the extent of that, is hard to determine or predict.

With Windows I find the hosts file size problems depend on which version of Windows is running, how much RAM is onboard, DNS configuration, and potentially other settings incoherently and varyingly buried in Windows config dialogs. If Windows gets slow suddenly, it might be related to the hosts file and, then again, it might not.

@icedterminal enumerates some seemingly related issues here.

**Comment by StevenBlack** [comment]
Closing!
