### ISSUE TITLE
Why block hits.sh ?

### ISSUE THREAD

**Issue by silentsoft** [StevenBlack/hosts#2252]
Hello. I am the author of the [https://hits.sh/](https://hits.sh/).
I noticed that #2095 this issue makes my site to be blocked.

The guy who created that issue(#2095) said:
> In reality this just means IP harvesting and logging. It's a site that gets loaded silently in the background, unbeknownst to users visiting pages. I'd like to propose we add it to the host list.

Sadly, it's not true. I don't harvesting IP address and logging.
I just simply do `count = count + 1` and return the badge image inside of my logic. [This](https://github.com/silentsoft/hits/blob/dev/src/main/java/org/silentsoft/hits/service/HitsService.java) is the actual source code that I've described.

I'm pretty sure that all of my users who uses "hits.sh" wants to count and **display** the badge image to website to visitors as **their** content.

Please remove "hits.sh" from hosts.

Thanks,

**Comment by silentsoft** [comment]
@hyder365 Can you show me evidence of where the 'curl https://hits.sh/ > /dev/null' you mentioned was located? Also, the purpose of this site is not to track, but to display the number of URL requests as a badge image. I don't understand why my site should be blocked.

**Comment by silentsoft** [comment]
@hyder365 If counting views based on your definition is considered a privacy-invading tactic, then should stackoverflow.com also be blocked since it displays 'Viewed n times' when a question is posted on the site? And do all viewers of that question know that the 'Viewed n times' counter increases by 1 each time someone views it? Furthermore, if the author of the AUR package you mentioned requested stackoverflow.com instead of hits.sh to increase the view count on a question they posted on the site, should stackoverflow.com also be blocked?

**Comment by silentsoft** [comment]
@hyder365 Your argument is contradictory. The URL for hits.sh that you raised as an issue (`https://hits.sh/aur.archlinux.org/packages/cemu.svg`) is a URL for requesting a .svg image, and the response is also intended for image rendering, not just for counting, as it is in `image/svg+xml` format. Similarly, the URL for stackoverflow.com is intended for rendering questions and answers, not just for counting.

I cannot agree that a website should be blocked simply because someone did not use it for its intended purpose.

**Comment by StevenBlack** [comment]
Guys @hyder365 @silentsoft can we please just stop?

Let it go. This isn't going to change.

Thank you for this interesting discussion but now, out of respect for the 567 watchers of this repository, let's zip it.

Thanks.
