### ISSUE TITLE
barip15, any idea what this is?

### ISSUE THREAD

**Issue by harryray33** [StevenBlack/hosts#2253]
My Firefox keeps trying to connect with barip15.com. I have it neutralised through the Host file, Ublock and my firewall.

I noticed that this is a blocked entry on the list, Does anybody have any idea what this domain is?

Thanks.

**Comment by StevenBlack** [comment]
Hello @harryray33 thank you for this question.

We don't carry the domain `barip15.com` in any of our lists.

Closing.
