### ISSUE TITLE
Internert Speed Slow -- Reason Host file Dnsclient issue(need help)

### ISSUE THREAD

**Issue by arrqamafaq** [StevenBlack/hosts#2256]
Hey guys i just add a large chunk of sites into my host file, but now my internet is not working properly. I am not able to replace the file as it show already open nor am I able to save it as old. Can anyone help me how do I solve this issue?

**Comment by StevenBlack** [comment]
Hello Arquam, thank you for your question.

You don't mention your operating system, but you'll need to `run as administrator` or `sudo` to edit your hosts file.

**Comment by arrqamafaq** [comment]
I resoved the issue in safe mode. Thanks for replying
