### ISSUE TITLE
cdn.cookielaw.org is blocked, what is the reason?

### ISSUE THREAD

**Issue by scspijker** [StevenBlack/hosts#2257]
https://github.com/StevenBlack/hosts/blob/845595b8b72b0bdc0e8d95a9890f09373a471ce9/data/StevenBlack/hosts#L2503

Heya,

Why is [cdn.]cookielaw.org blocked?

I could find these issues:
 - https://github.com/StevenBlack/hosts/issues/1535
 - https://github.com/StevenBlack/hosts/issues/1668

Both declined adding cookielaw.org / cdn.cookielaw.org. If there is a good reason to block them, great, I'll create a whitelist, but I can't find why this domain is blocked? 
The reason I ask is because this prevents logging into https://app.sketchup.com/ which is a pretty major app to block. Might be EU specific. If the block is legit, I'll request them to remove the tracker as a "block" to logging in, but I'd like to be sure.

Thanks!

**Comment by StevenBlack** [comment]
Hello stijn @scspijker thank you for your question.

I added `cdn.cookielaw.org` after network-tracing what goes on when loading the cnn.com home page.  CNN, like most other American news (sic) websites, is a cluster of tracking and bad actions. `cdn.cookielaw.org` is a part of everything that's bad about the web right now.

See for yourself, then come back to tell me why `cdn.cookielaw.org` is, in any way, legit.

Closing.

**Comment by icedterminal** [comment]
When implemented poorly, in your case, the service is interrupted. This something you need to take up with Sketchup. Cookielaw's service ironically has its own tracking accessible from the dashboard.

This is more of an opinion piece, but Cookielaw has failed at what intended to do and for the most part sucks. If you care about your privacy, you use script blockers, ad blockers, filters, etc. The prompts and the service provided are largely just ignored by people anyway as they tap "Accept all" and be done with it. https://www.itpro.com/network-internet/web-browser/369894/the-cookie-law-is-finally-crumbling-good-riddance

**Comment by StevenBlack** [comment]
@icedterminal if I understand this ⬆️ correctly, `cookielaw.org` helps create and dish those annoying cookie notifications and pop-ups? That useless and massively failed euro-regulatory concept?

I didn't know that 😄

**Comment by icedterminal** [comment]
@StevenBlack They do indeed. They were the first in directing and educating web developers on how to comply with the new regulations. OneTrust is the company behind it all. At the Cookie Law website, you are directed to create an account at https://www.cookiepro.com/ which is the dashboard I speak of. I must admit when it was new, I was going to use it. But backed out after reviewing it all. The irony was not lost on me.

**Comment by scspijker** [comment]
Thank you for explaining the issue 🙏

**Comment by Simie** [comment]
Just wanted to chime in, blocking this domain breaks functionality on some websites.

On the login page on www.nuget.com (https://authentication.nutmeg.com/login), it seems that it's waiting for a file from this domain to load before redirecting to another URL. Whitelisting the domain fixes it.

**Comment by Caligatio** [comment]
I ended up having to whitelist cdn.cookielaw.org as blocking it made it so the irritating cookie banner on every Dotdash Mereidth property (of which there are many) not closable on mobile devices. This includes Firefox on Android with uBO.

I completely understand they underpin undesirable behaviors but it also is terrible to have to browse websites with only half of your screen usable because of the aforementioned banner.

**Comment by krystian3w** [comment]
https://github.com/StevenBlack/hosts/issues/2361

**Comment by xrvk** [comment]
> I completely understand they underpin undesirable behaviors but it also is terrible to have to browse websites with only half of your screen usable because of the aforementioned banner.


I can also report the California utility provider pge.com does not work after authenticating. Blocking cookielaw prevents all website functionality on the pay bill section from functioning, with a giant grey loading screen covering most of the page/functionality on desktop & iOS browser.

**Comment by krystian3w** [comment]
With AdGuard premium you can load surrogate on iOS (if somebody made for AdGuard purpose)*.

On PC enough will be uBlock Origin with customized `userResourcesLocation`*.

\* - if the network bug does not hinder the injection of fake content (as I understand the RU AdList project (which also cleans Ukrainian sites without a problem), the surrogate works for them).

----

In a very good variant, maybe the already added `set-cookie`/`trusted-set-cookie` (or `set-local-storage`/`set-trusted-local-storage`) is enough.

----
----


But this should be considered in addition to filtering at the HOST/Pi-Hole/DNS level.

**Comment by krystian3w** [comment]
Perhaps one needs to investigate how the list works with uBo Lite where the HOSTS list has been added:

https://github.com/search?q=repo%3Agorhill%2FuBlock%20StevenBlack&type=code


So that the list would not fly away overnight without attempting repairs at https://github.com/uBlockOrigin/uAssets/blob/master/filters/ubol-filters.txt.

**Comment by StevenBlack** [comment]
I would like to make one thing clear to everybody.

If a website uses CookieLaw, and their website fails to load or deliver if CookieLaw is not responding, this is **their problem**, not ours.

In other words, if a website fails to work because they ***rely*** on CookieLaw, we're not gonna whitelist CookieLaw because of a CookieLaw customer's abject stupidity.

**Comment by bigpcjunky** [comment]
> > I completely understand they underpin undesirable behaviors but it also is terrible to have to browse websites with only half of your screen usable because of the aforementioned banner.
> 
> I can also report the California utility provider pge.com does not work after authenticating. Blocking cookielaw prevents all website functionality on the pay bill section from functioning, with a giant grey loading screen covering most of the page/functionality on desktop & iOS browser.

I also had a problem with pge.com recently after years of use.  I don't know who is right or wrong, but I think this is the only block list that has cookielaw.org on it.

**Comment by starball5** [comment]
> See for yourself, then come back to tell me why cdn.cookielaw.org is, in any way, legit.

@StevenBlack I'm not that technologically adept with respect to cookies and tracking. I don't know how to see for myself. With as much humility as I can give, would you mind explaining how to do that or just "giving the answer" of what's wrong with cookielaw.org and why it's desirable to block it?

**Comment by StevenBlack** [comment]
@starball5 you may be aware that, on some websites, we see an avalanche of requests — hundreds of requests in many cases — occurring long after Document is complete.

How many requests to cookielaw are required for any web page? How many requests to cookielaw should be required for any web page?  

Seeing cookielaw requests scroll by in the ad-infinitum cascades of requests, dozens of times, makes me decide, that's quite enough.

This cookie nonsense is EU bullshit and I've decided, this has to stop. I'm here to serve and protect a specific subset of the population who think, "Say No To Tracking".

If meek compliance with EU bullshit is your thing, then maybe this hosts file is not for you. There's nothing wrong with meek compliance with EU bullshit, it's just not what we do here.

**Comment by starball5** [comment]
@StevenBlack Thanks for your reply. I actually know very little about cookie laws. The main reason I use this hosts file (in addition to an ad blocker) is as a general protection measure against fetching and loading nasty resources.

My ignorance is not lost on me. But exactly because of my ignorance, I still have a question (and you sound sick of this topic, so if you don't feel like answering please feel free to just ignore me). You said:

> I'm here to serve and protect a specific subset of the population who think, "Say No To Tracking".

Could you spell out for me (I probably sound pretty dumb right now) how blocking this domain serves to prevent tracking?

**Comment by StevenBlack** [comment]
Thank you for your question @starball5.

The [readme](https://github.com/StevenBlack/hosts/blob/master/readme.md) is fairly clear about what we do here. It's not just about tracking.

Google `Clay Shirkey "enshittification"` for articles and interviews about the steady enshittification of all things online.

Telling you right now: this cookielaw thing won't change here.

**Comment by icedterminal** [comment]
> Could you spell out for me (I probably sound pretty dumb right now) how blocking this domain serves to prevent tracking?

Cookielaw service directly tracks interaction. When you click anything in that modal, their service records it and is available for the domain web admin to see in the dashboard. You're supplying the domain with analytical information you may not want to provide or comply with. "I'm going to tell you I don't want this tracking crap, while also allow you to track that I don't want to be tracked." The web admin can check in any time "What kind of content do our users prefer to let us throw at them? Let's check the dashboard and see!"

I hope this answers your question.

**Comment by starball5** [comment]
@icedterminal Thanks. Is this information looked at by anyone other than the domain web admin for their own domain? Ex. Does OneTrust have any statement about whether they look at that information?

**Comment by StevenBlack** [comment]
@starball5 I think that's enough. This project is used by millions, starred and watched by thousands, and we're way off-topic now.

Maybe take this to Facebook or something? 

This is a technical project with clear goals that do not include bombing bandwidth from contributors and interested parties.

I'm locking this convo now.
