### ISSUE TITLE
Edge Discover Tab : This content is blocked. Contact the site owner to fix the issue.

### ISSUE THREAD

**Issue by d0tiKs** [StevenBlack/hosts#2261]
I have identified that the entries in my hosts file are blocking the Discover Tab of edge.

I get this message inside the tab : This content is blocked. Contact the site owner to fix the issue.
![discovertab](https://user-images.githubusercontent.com/7963736/227059580-709c7d66-dfa7-4bc4-b20f-3c93889f7f3b.png)

I suspect that multiple entries needed, I tried to make comment the first half and the second half only, and it still didn't work.
If I comment everything it does. 
I also tried to identify which where the faulty entries using wireshark, I may have found some but it was not enough to make it work.
Is it a known behaviour ? If so do you know which entries I should remove to make it work.

edit : typo
edit2 : I updated my hosts file with only the 3.12.15 **fakenews** one and the issue persists

**Comment by icedterminal** [comment]
I can't seem to reproduce this using a default configuration.

Perhaps it is a conflicting extension or something you've added?

**Comment by StevenBlack** [comment]
Thank you for this Alessandro @d0tiKs.

I don't use Edge, maybe someone who does, just like @icedterminal, can provide more info for us?

Alessandro I'd like to say this as charitably and as generously as possible. Please don't misunderstand. This is not a dig, this is more a statement of focus and strategic intent. 

This hosts file is not made for users of the "Discover" tab of anything, nevermind Microsoft Edge.  There are potentially 8-billion internet users on earth, and this hosts file isn't made for the vast majority of them.  We serve internet users who don't want to be tracked, traded, or sold, in any way.  In some sense, our hosts files are "anti-discover-tab", if that makes sense. I think this is what makes our hosts files special.

Not a dig — that's just how I see it in the big-picture.

**Comment by icedterminal** [comment]
Unfortunately being unable to reproduce this has limited my ability to provide any potential solution. This leads me to believe your hosts file is directly replacing the one on Windows. This may seem fine in theory, but for one reason or another, it breaks Windows itself or programs. I've tested the capability of Windows hosts and it appears to struggle once the file is between 1 and 2 MB. Depending on the hardware. A work around is to disable DNS caching. It is not a solution as doing so can slow down Internet browsing and may not actually help in some situations.

Can you verify where your hosts is located?

I wholeheartedly agree with @StevenBlack here. The Discover feature is intrinsically tracking. The content it delivers to you is based around what is supplied to it by interaction, or passively following you along the web. It's a conflict of interest. Even with a working discover, the blocked domains for tracking do not allow for the feature to properly cater. It will be less relevant to you.

**Comment by d0tiKs** [comment]
@StevenBlack I'm not mad at all don't worry, and I understand that microsoft embed lots of tracking in this kind of features ^^. I just wanted to know if anyone knew which entries was triggering it. Most of the time I don't use edge anyway, but I like tinkering hence my problem. I didn't expect it to be fixed either I understand that your hosts file goals is to block most if all trackers even if some software break along the way. 

@icedterminal The struggle you mentioned when the hosts file is getting big rings another bell to my daily usage, when I boot up windows it takes a huge time to DNS queries to work. Perhaps I should open another issue if it's not already the case.

**Comment by icedterminal** [comment]
I managed to reproduce it by directly replacing the hosts file on a VM. Took a few days of waiting. Basically the issue is Windows. If you disable DNS caching and clear it, after reboot it works. Keep in mind DNS is now slower because no lookups are cached.

With caching enabled for such a large hosts file, Windows processes it incorrectly or doesn't process it at all. The cache can also corrupt which just throws the DNS service for a loop and nothing Internet related works.

Options:

- Disable the DNS cache service. I don't recommend this option.
- Revert to the default hosts file and use AdGuard DNS servers.
- Revert to the default hosts file and use a dedicated device with PiHole installed.
