### ISSUE TITLE
Ad domain: grow.gab.com

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#2266]
The Gab subdomain [grow.gab.com](https://grow.gab.com/) ("Gab Ads") exists only to buy and show advertisements on the platform. The images being served for ads on the timeline and in chats are hosted there.

Two example advertisement URL images:

https://grow.gab.com/galahad/532a98e5d368f8a700b52c4ba4bfc0c5

https://grow.gab.com/galahad/f964b81d6e220ce4ba4a106a6a69943e

I was unable to find any URLs on this domain that aren't related to advertisements.

edit: Here's an example ad URL (not image) for completeness' sake: https://grow.gab.com/go/63d3052c666792c0f804a23f

**Comment by StevenBlack** [comment]
Thank you for this Devon @hyder365.  This domain is added in commit 8bc7fd9b and will be included in the next release.

Closing.
