### ISSUE TITLE
Block Oppo Telemetry

### ISSUE THREAD

**Issue by norilana** [StevenBlack/hosts#2267]
Oppo Telemetry Domain

heytapdl.com
heytapmobile.com

**Comment by StevenBlack** [comment]
Thank you for this Anon @norilana.

We should block these domains because...?

**Comment by StevenBlack** [comment]
I'm sorry Anon, you have no history, no cred, and you provide no tangible evidence. I can't go forward with this request.

Closing.

**Comment by icedterminal** [comment]
> It is blocked by most lists, but not regionally but oisd, 1hosts pro etc.

Can you provide a source? A link to a relevant inclusion request on one of these hosts files that declare what the domains is used for is a great start.

> It is already known what these areas are used for

I don't know what these are used for either. So you can't really claim it is known. I'm sure I could Google these domains but that's not my job nor is the maintainers job.

> you have made your intention very clear, I don't need to prove anything to you.

See previous statement. When we don't know what these domains are for exactly, this is where proof comes in. To expedite an inclusion, you can debug a request to see the contents (see Fiddler/Wireshark) or link to a relevant inclusion request found on an alternative host source. This helps verify that tracking or ad delivery is present and blocking these domains doesn't harm the functionality of other services.

If a domain was accepted was accepted at face value, a lot of the web would be broken (see Google APIs). Which makes things worse for everyone.
