### ISSUE TITLE
No internet access after installing - Unified hosts = (adware + malware)

### ISSUE THREAD

**Issue by dephunk** [StevenBlack/hosts#2268]
As title suggests, had to go into safe mode to return to original host file that solved the issue.

OS Name:	Microsoft Windows 10 Pro
Version:	        10.0.19045 Build 19045

**Comment by StevenBlack** [comment]
Hello @dephunk thank you for your question and I'm sorry to hear about your issue.

Please see the discussion in...

* #2064

... which seems to resolve the problem.  This is a Windows issue. No other OS has problems with hosts files like ours.

Closing.
