### ISSUE TITLE
Porn site to block

### ISSUE THREAD

**Issue by Blackdarked** [StevenBlack/hosts#2269]
sexsot.com
hentaiz.ai

It seems like these sites have just been moved to newer domains.

**Comment by StevenBlack** [comment]
Thank you for this @Blackdarked

Ping @sinfonietta for inclusion in the porn list.

**Comment by Sinfonietta** [comment]
@StevenBlack and @Blackdarked the first domain did not connect for me, but I added the second domain.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and @Blackdarked closing this now.
