### ISSUE TITLE
Request to unblock a few domains

### ISSUE THREAD

**Issue by GBT7** [StevenBlack/hosts#2270]
Hi,
It appears that a few domains are blocked on this hosts list which I can't for the life of me figure out why.

act.fossilfueltreaty.org
emails.khanacademy.org
www2.citizensclimatelobby.org

As per [this link](https://rethinkdns.com/search?q=www2.citizensclimatelobby.org), it appears that not just the Citizens' Climate Lobby link is being blocked, but also act-on, which is what they use for the www2 subdomain. This breaks most links coming from CCL.

As per [this link](https://rethinkdns.com/search?q=act.fossilfueltreaty.org), it appears that act.fossilfueltreaty.org is just blocked outright. Why? This is the domain in which the Fossil Fuel Non-Proliferation Treaty can be signed ([see here](https://act.fossilfueltreaty.org/endorse))

With regard to the Khan Academy email domain, [here](https://rethinkdns.com/search?q=emails.khanacademy.org) it shows that the domain isn't necessarily blocked, but Sailthru is, which effectively breaks all the email links.

Other domains I've encountered problems with (but can better understand why) are:

clicks.aweber.com
lptag.liveperson.net
avantlink.com

Blocking these breaks newsletter links, customer support chats, and product referral links, respectively.

I get that many people want to block all trackers no matter the cost, but can there at least be an option to opt out of blocking referral and redirect links? For the most part, they only track the people who click them directly, and there is no way around them once they're blocked.

Thanks.

**Comment by StevenBlack** [comment]
Hi @GBT7 thank you for raising this issue.

Let's look, shall we?

### `act.fossilfueltreaty.org`

```
$ dig act.fossilfueltreaty.org all                                                                      

act.fossilfueltreaty.org. 14399	IN	CNAME	go.pardot.com.
go.pardot.com.		1288	IN	CNAME	pi.pardot.com.
pi.pardot.com.		298	IN	CNAME	pi-ue1.pardot.com.
pi-ue1.pardot.com.	28	IN	CNAME	pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com.
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 58 IN A 52.54.96.194
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 58 IN A 3.215.172.219
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 58 IN A 3.92.120.28
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 58 IN A 34.237.219.119
pi-ue1-public-lb-f0209c6950285322.elb.us-east-1.amazonaws.com. 58 IN A 18.208.125.13
```

Well surprise, surprise. The domain `act.fossilfueltreaty.org` is a  `CNAME` record that goes through `pardot.com` subdomains and many or its incarnations.

If we unlist `act.fossilfueltreaty.org` then you're still going to be blocked by the many `pardot.com` domains we block here.

Do you want me to continue @GBT7, because I can continue.  Or have you seen enough. I've certainly seen enough.
