### ISSUE TITLE
Scam/phish site: transive[.]top

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#2271]
There are numerous scams on Facebook advertising "amazon mystery boxes" that come with a variety of items included. You can only buy one with a credit card number, of course, no paypal or similar. Upon ordering one, you're sent a text message in broken English with a shortened link like "t.ly/USSCxxxx" and told to update your contact info.

This link resolves to "transive.top" which was created less than a month ago and is currently hosted by Aceville PTE, a high-risk scam ISP. I'd like to propose we include transive.top in the blacklist as either a scam or phishing site. It's kind of both.

**Comment by StevenBlack** [comment]
Thank you Devon @hyder365, I have added both of these.  Those will go live in the next release.

Closing.
