### ISSUE TITLE
Please Add these Porn Sites

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#2272]
Hello @StevenBlack and @Sinfonietta,

I've included a list of porn sites to add to your filter below:
kerrykerry.ng
sakurahentai.info
ksk.moe
simplyhentai.org
hitomila.to
theindex.moe/library/hentai
999hentai.to
999hentai.tv
overwatchfuck.com
xxxmangacomix.com
gifhq.com
savemp4.red
tiktits.com
nudes18.fun
leaked.fun
ofleakss.com
leakplanet.net
nudoleaks.io
thotshub.tv
watchporn.to
newasiaporn.com
topasiansporn.com
lesbianlist.com
mzporn.com
freepornc.com
nudesify.com
erofound.com
sex-leaks.com
x-porn.fr
pornhdmate.com
fapeza.com
zbporn.net
twpornstars.com
xxx-tranny.com
pussyspace.lol
vtranny.com
fappedia.com
albumporn.com
hotgirlchina.com
leakshemale.com
xfapping.com
epornlink.com
1shemale.com
shemalegalaxy.com
porn.dreamhosters.com
foxtube.tv
nudegirlsleaks.com
hentaiforce.net

Thank you for your hard work!

**Comment by StevenBlack** [comment]
Thanks @g1t3m!

**Comment by Sinfonietta** [comment]
@StevenBlack these are added to my porn list.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and @g1t3m.

Closing.
