### ISSUE TITLE
Long delay in which Browsers work but not anything else

### ISSUE THREAD

**Issue by Feper24** [StevenBlack/hosts#2273]
Hi,

I just found out that using this hosts file (the lightest option for example) caused my computer, ISP, modem configuration and whatnot to take quite some to be able to successfully initiate networking in anything but Internet Browsers.

Like 10m or more in which I could only use Opera, Edge, Chrome, etc but NOTHING else worked, including apps and windows online services like the integrated search option.

I tried extreme stuff like formatting windows, factory reset the modem and nothing fixed the issue but replacing this host file with the default one from windows.

please let me know if there's a way for me to provide more information through a certain tool

**Comment by StevenBlack** [comment]
Hello @Feper24 thank you for your question. I'm sorry ti hear about these difficulties.

Please see the discussion in...

* #2064

This is a Microsoft Windows issue. No other OS has problems such as this, and others.

Closing.

**Comment by Feper24** [comment]
Awesome! Thanks for your hard-work and dedication :D
