### ISSUE TITLE
Microsoft OneNote Sync is Blocked

### ISSUE THREAD

**Issue by ArtiomL** [StevenBlack/hosts#228]
Following one of the latest updates - MS OneNote isn't able to sync notebooks.

Possibly because of:

- 0.0.0.0 nexus.officeapps.live.com
- 0.0.0.0 officeclient.microsoft.com
- 0.0.0.0 mobile.pipe.aria.microsoft.com

**Comment by FadeMind** [comment]
@ArtiomL This issue please report directly in https://github.com/crazy-max/WindowsSpyBlocker/issues
I just copy `spy` rules in to @StevenBlack Hosts project.
See: https://github.com/StevenBlack/hosts/tree/master/data/WindowsSpyBlocker

![image 018](https://cloud.githubusercontent.com/assets/9846948/21498545/be23f474-cc2d-11e6-9b6a-b3cc04ff5c19.png)

Other way:
Install Python 3.5 runtime and rebuild hosts file directly. Add these domains to whitelist file.

**Comment by StevenBlack** [comment]
See commit 6057f22.  Closing.
