### ISSUE TITLE
porn site to block

### ISSUE THREAD

**Issue by realprime** [StevenBlack/hosts#2290]
I found a few sites associated to Xhamster's
1. xhbranch.com
2. xhbranch0.com
3. xhbranch1.com
4. xhbranch2.com
5. xhbranch3.com
6. xhbranch4.com
7. xhbranch5.com
8. xhbranch6.com
9. xhbranch7.com
10. xhbranch8.com
11. xhbranch9.com
12. xhbranch10.com
13. xhadult.com
14. xhadult0.com
15. xhadult1.com
16. xhadult2.com
17. xhadult3.com
18. xhadult4.com
19. xhadult5.com
20. xhadult6.com
21. xhadult7.com
22. xhplanet.com
23. xhamster18.com
24. xhamster19.com
25. xhamster20.com
26. xhamster22.com
27. xhamster18.desi
28. xhamster19.desi
29. xhamster20.desi
30. xhamster22.desi

and a few more sites which are redirecting to each other if I click on any of the content.
1. xxxvideoindian.com
2. desiporn.su
3. desi-porn.me
4. bestdesiporn.pro
5. fulldesiporn.pro
6. desi-porn.org
7. xxxindiantubes.com
8. goldindianporn.pro
9. xxxdan3.com
10. pornindian.me
11. homeindianporn.com
12. getdesixxx.com
13. indianpornpage.com
14. xchudai.com
15. indianpclips.com
16. topindianp.com
17. hottestphd.com
18. xxxindiangirls.pro
19. allindianpornvideos.com
20. goindianpornmovies.com
31. alldesisex.com
32. tophindiporn.com
33. getdesihub.com
34. ohindiangirls.com
35. 4kindiangirls.com
36. 4kindianfuck.com
37. besthindixxx.com
38. goindianfuck.com
39. indiantubeporn.pro
40. desipornfilms.pro
41. dirtyindianporn.pro
42. cuteindiansex.pro
43. indiansexporn.pro
44. indianfuckvids.pro
45. allindianporntube.com
46. xxx69night.com
47. superchatlive.com
48. cuteindianfuck.com
49. dirtydesiporn.com
50. 4kdesisex.com
51. nudeindianfuck.com
52. tamil-xxx-videos.com
53. new-indian-xxx.com
54. fuckdesixxx.com
55. indianfuckvids.pro
56. 3isx.com
57. indianphq.com
58. indianpornhindi.com
59. popindian.com
60. hottestindiansite.com
61. mostdesixxx.com

**Comment by StevenBlack** [comment]
Thank you for this @realprime.

Ping @sinfonietta for inclusion in your list.

**Comment by realprime** [comment]
hello @Sinfonietta can please include the above list in the host's list

**Comment by Sinfonietta** [comment]
@StevenBlack sorry for the delay I have just added these.

**Comment by StevenBlack** [comment]
Awesome. Thank you @Sinfonietta and @realprime.  Closing.
