### ISSUE TITLE
Odd domain with update

### ISSUE THREAD

**Issue by AG-lucky** [StevenBlack/hosts#2292]
[i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Imported 204471 domains, ignoring 21 non-domain entries
      Sample of non-domain entries:
        - 0.0.0.0
        - -043ns11.net.daraz.com
        - -16marketing.net.daraz.com
        - -access-logs-active.net.daraz.com
        - -access-logsacc-sandbox.net.daraz.com

**Comment by StevenBlack** [comment]
Thank you for this @AG-lucky.  These domains are no longer listed.

Closing.
