### ISSUE TITLE
More Porn Sites for the Blocklist

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#2293]
Hello @StevenBlack and @Sinfonietta,

I've discovered the porn sites below that should be added to the filter:

starpornhd.com
pornhdvid.com
xxtikporn18.com
xxx69leakporn.com
xsexclipsx.com
42videoxxx.com
cutegirlleakvid.com
hotvidsex.com
onlygirls18.net
hotvidsex.com
cyberpornx.net
sixteenxxx.com
nudestarx.com
porntrexhd.com
porngirlhd.net
pornwildhd.com
kutaporn.com
videohd18.com
wetlook.biz
perfectgirls.xxx
bigoiledupasses.com
badhoes.tv
rob3rt.online
dreamtoon.net
xxxrotator.com
naked.chiks.org

Ask always, thank you for your work!

**Comment by StevenBlack** [comment]
Thank you @g1t3m!

**Comment by Sinfonietta** [comment]
@StevenBlack these are added.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and thanks again @g1t3m.  Closing.
