### ISSUE TITLE
Block `bueromoebelservice.com`

### ISSUE THREAD

**Issue by WebworkrNet** [StevenBlack/hosts#2294]
**Lists in use:**
- Unified Hosts
- Fakenews
- Gambling
- Porn
- Social

**Client:**
Blokada/Android

**Domains:**
```
bueromoebelservice.com
```

**Details:**
Spam

https://www.virustotal.com/gui/domain/bueromoebelservice.com

![chrome_screenshot_1681894740762](https://user-images.githubusercontent.com/43509007/233027604-a638158a-53e1-4bb3-af7f-0b79e2fc5999.png)

**Comment by StevenBlack** [comment]
Thank you @WebworkrNet this is added in commit cd216e04.
