### ISSUE TITLE
Block `*.beautydates.cn`

### ISSUE THREAD

**Issue by WebworkrNet** [StevenBlack/hosts#2296]
**Lists in use:**
- Unified Hosts
- Fakenews
- Gambling
- Porn
- Social

**Client:**
Blokada/Android

**Domains:**
```
beautydates.cn
www.beautydates.cn
hhoneyann96.beautydates.cn
*.beautydates.cn
```

**Details:**
Malicious, spam, suspicious

`http://honeyann96.beautydates.cn/`

https://www.virustotal.com/gui/url/797fba9ca1eaf7c03c031a193fc7f5126476bfd7d5d28edaf9ecb133e122ef31/detection/u-797fba9ca1eaf7c03c031a193fc7f5126476bfd7d5d28edaf9ecb133e122ef31-1661791580

![chrome_screenshot_1681926561448](https://user-images.githubusercontent.com/43509007/233158618-27dbac15-f4aa-40c4-8c78-667ec0730460.png)

`beautydates.cn`

https://www.virustotal.com/gui/domain/beautydates.cn

![chrome_screenshot_1681926707264](https://user-images.githubusercontent.com/43509007/233159227-2442ed49-4362-4cda-9ffa-d2b00a53d6b3.png)

**Comment by StevenBlack** [comment]
Thank you for this Denis @WebworkrNet.

We produce lists that are in the order of 10^5 elements in length.

Please try to aggregate multiple suggestions in one single issue.

Because using "N" issues for "N" domains is approximately N-times the work.

**Comment by StevenBlack** [comment]
Denis @WebworkrNet in this particular case, wild card characters are not supported in hosts files.

**Comment by StevenBlack** [comment]
Thank you Denis these domains are added in commit 80057472.

Closing.
