### ISSUE TITLE
Block `*.nilaima.com`

### ISSUE THREAD

**Issue by WebworkrNet** [StevenBlack/hosts#2297]
**Lists in use:**
- Unified Hosts
- Fakenews
- Gambling
- Porn
- Social

**Client:**
Blokada/Android

**Domains:**
```
nilaima.com
www.nilaima.com
*.nilaima.com
```

**Details:**
Malware

`http://www.nilaima.com/link.php`

https://www.virustotal.com/gui/url/806b0009b78f1c3aa3cdad4a5f157b036cb49c69db8b69fb156b1166a9296d87/detection/u-806b0009b78f1c3aa3cdad4a5f157b036cb49c69db8b69fb156b1166a9296d87-1544716427

![chrome_screenshot_1681932033633](https://user-images.githubusercontent.com/43509007/233178478-0975fb5e-5658-42fa-8a1a-9baa89792090.png)

**Comment by StevenBlack** [comment]
Thank you Denis these domains are added in commit 80057472.

Closing.
