### ISSUE TITLE
Possible failure in Unified hosts + fakenews + gambling + porn + social

### ISSUE THREAD

**Issue by gallegonovato** [StevenBlack/hosts#2298]
Good afternoon:

I have been using your Unified hosts + fakenews + gambling + porn + social blocklist on Adaway for some time now.

I come across this entry:

<# 0.0.0.0 cdn.jsdelivr.net #[affects spireenergy.com]>

And Adaway instead of bypassing the block. It puts that entry as blocked.

Check the rest of the sources of the hosts I use. And in none of them it comes up.

Could it be that Adaway puts it as blocked because of the space between the # and the 0.0.0.0?

It should not be:

#0.0.0.0 cdn.jsdelivr.net #[affects spireenergy.com]

So that it has no effect?

Best regards and thanks for your time and help.

**Comment by StevenBlack** [comment]
Hello @gallegonovato thank you for this.

The `#` character is a comment in hosts files. This line is ignored.

So the subsequent space has no effect  👍🏻 

Closing.

**Comment by gallegonovato** [comment]
Good afternoon @StevenBlack

Please excuse me for replying so late. But a family member is in the hospital and I've lost my mind. As we say here (i.e. I forgot to check the answer)

Thank you for your response and help. 

I just showed up in Adaway and Magisk blocked me. And I didn't know why until on xda magisk, I was told about that entry.

And I came out in blocked but I did not put it and I do not know why it goes there.

Recommend always allow and activate it from time to time. Or always allow?

A hug
