### ISSUE TITLE
Block `idcdn.de`

### ISSUE THREAD

**Issue by WebworkrNet** [StevenBlack/hosts#2299]
**Lists in use:**
- Unified Hosts
- Fakenews
- Gambling
- Porn
- Social

**Client:**
Blokada/Android

**Domains:**
```
idcdn.de
```

**Details:**
Tracker
https://confection.io/trackers/idcdn-de/

**Comment by StevenBlack** [comment]
Thank you Denis these domains are added in commit 80057472.

Closing.

**Comment by hagezi** [comment]
@WebworkrNet @StevenBlack 

Blocking causes the site layout of articles on some German news sites not to be displayed correctly.

Reproduce: Open the page, click on an article.

Sites that are affected:

`fr.de
m.fr.de
www.fr.de
www.fuldaerzeitung.de
www.merkur.de
www.ovb-online.de
www.rga.de
www.schwaebische-post.de
www.tz.de
www.ruhr24.de
www.echo24.de
www.ingame.de
www.in-muenchen.de
www.giessener-allgemeine.de
www.heidelberg24.de
www.op-online.de
www.buzzfeed.de
www.kreiszeitung.de
www.24hamburg.de
www.rosenheim24.de
www.hna.de
www.wa.de
www.fnp.de
www.soester-anzeiger.de
www.come-on.de
www.chiemgau24.de
www.mannheim24.de
www.24rhein.de
24hamburg.de
buzzfeed.de
chiemgau24.de
come-on.de
echo24.de
fnp.de
heidelberg24.de
hna.de
ovb-online.de
rga.de
ruhr24.de`

**Comment by StevenBlack** [comment]
Thank you Gert @hagezi and @darkBuddha.

This is fixed in commit cef27e5 which will be live in the next release.
