### ISSUE TITLE
Stuck on identifying network

### ISSUE THREAD

**Issue by Chaython** [StevenBlack/hosts#2302]
With the hosts in my windows 11 hosts file after waking/booting network will be stuck on identifying for a random amount of time like 30 minutes.

**Comment by StevenBlack** [comment]
Hi Chayton @Chaython.  Please see [Warning: Using this hosts file in Windows may require disabling DNS Cache service](https://github.com/StevenBlack/hosts#warning-using-this-hosts-file-in-windows-may-require-disabling-dns-cache-service) in the repo readme.

Closing.
