### ISSUE TITLE
2 non-domain entries?

### ISSUE THREAD

**Issue by ahoier** [StevenBlack/hosts#2307]
[i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Imported 171163 domains, ignoring 2 non-domain entries
      Sample of non-domain entries:
        - 0.0.0.0
        - www
  [i] List has been updated

this was an output from my pihole gravity update.

**Comment by StevenBlack** [comment]
Thank you for this @ahoier.

`0.0.0.0` is legit.

I cannot find a line with just `www` in the domain.

Closing.

**Comment by hagezi** [comment]
> I cannot find a line with just `www` in the domain.

Found the following entry in the list which causes the www message in Pi-hole:
`0.0.0.0 www #.|kunkc.com`
