### ISSUE TITLE
false positives

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#2309]
I'm an edgy 2006 teenager who has traveled into the future to try and access hottopic.com, but unfortunately some DNS blocks are breaking the site's functionality.

Example page: https://www.hottopic.com/product/hatsune-miku-vocaloid-group-girls-t-shirt/16695237.html

Clicking on any of the shirt sizes produces a loading graphic that loops indefinitely, so you can never actually proceed.

Domains on this page being blocked (for me) include:

	cdn.cookielaw.org
	cdn.cquotient.com
	cdn.gladly.com
	cdn-scripts.signifyd.com
	na-library.klarnaservices.com
	tags.tiqcdn.com

At least four of which are from this blacklist:

	0.0.0.0 cdn.cookielaw.org
	0.0.0.0 cdn.gladly.com
	0.0.0.0 tags.tiqcdn.com
	0.0.0.0 cdn.cquotient.com

While **cdn-scripts.signifyd.com** seems to get pulled in from https://github.com/notracking/hosts-blocklists/ cc: @notracking and **na-library.klarnaservices.com** I'm not sure about yet.

I don't quite have the liberty to unblock one at a time and restart unbound for the network since there are other users here. Would anyone be able to help get to the bottom of this with me?

**Comment by hagezi** [comment]
@hyder365 

I can't find any problems with the following domains blocked:

```
cdn.cookielaw.org
cdn.cquotient.com
cdn.gladly.com
cdn-scripts.signifyd.com
tags.tiqcdn.com
```

The problem occurs when the following domain is blocked: `na-library.klarnaservices.com`

![grafik](https://user-images.githubusercontent.com/104343908/234403446-2794c930-e226-4159-977a-276b0804e0e3.png)
