### ISSUE TITLE
block tesla-blockchain.net

### ISSUE THREAD

**Issue by pokegamer5547** [StevenBlack/hosts#2313]
Lists in use:

    Unified Hosts
    Fakenews
    Gambling
    Porn
    Social

Client:
Android

Domains:
tesla-blockchain.net

Details:
Phishing and malware

![Screenshot_20230428-203439_Firefox Beta](https://user-images.githubusercontent.com/65234485/235183841-dc3eec9e-8c22-45db-a241-ddcc904030e5.png)

**Comment by StevenBlack** [comment]
@pokegamer5547 why are you sending us a screen shot that doesn't actually say anything about what you claim?

Closing.
