### ISSUE TITLE
Qualcomm A-GPS domain - izatcloud.net

### ISSUE THREAD

**Issue by hlqviet** [StevenBlack/hosts#2314]
Hi. It has just been added recently in #2312 due to a misleading article. Blocking this domain will prevent A-GPS from working which means limiting phone functionality.

Here is some info:
- https://www.reddit.com/r/privacy/comments/12yii9u/comment/jhojlr7/
- https://blog.brixit.nl/nitrokey-dissapoints-me/

It has also been removed in hagezi/dns-blocklists#984

**Comment by StevenBlack** [comment]
Thank you @hlqviet — I am removing this now.

**Comment by mtxadmin** [comment]
Oh, yeah!
https://github.com/ShadowWhisperer/BlockLists/pull/95
