### ISSUE TITLE
More Porn Sites

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#2315]
Hello @StevenBlack and @Sinfonietta,

I've discovered more porn sites toadd to the blocklist:

starpornhd.com
pornhdvid.com
xxtikporn18.com
xxx69leakporn.com
xsexclipsx.com
42videoxxx.com
cutegirlleakvid.com
hotvidsex.com
onlygirls18.net
hotvidsex.com
cyberpornx.net
sixteenxxx.com
nudestarx.com
porntrexhd.com
porngirlhd.net
pornwildhd.com
kutaporn.com
videohd18.com
wetlook.biz
perfectgirls.xxx
bigoiledupasses.com
badhoes.tv
rob3rt.online
dreamtoon.net
xxxrotator.com
naked.chiks.org
egirls.wtf
thot-tv.com
vipreddit.blogspot.com
melkormancin.com
redtock.com
leakingirls.com
hardgif.com
fap.bar
phub.porn
netfapx.com
glamino.com
xfree.com
dudethrill.com
sexytube.me
vids4tube.com
masturflix.com
striptk.com
tiktok.pm
nudetiktok.cc
masturhub.com
topinsearch.com
lacomics.net
hqporncomics.com
rule34comic.party
anycomics.com

Thank you for maintaining this blocklist!

**Comment by Sinfonietta** [comment]
@StevenBlack these are added.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta.  Closing.
