### ISSUE TITLE
Add Sprig tracking

### ISSUE THREAD

**Issue by icedterminal** [StevenBlack/hosts#2316]
[Sprig](https://sprig.com/), formerly branded [UserLeap](https://twitter.com/Sprig/status/1430562367075614724), has a new domain that provides the same tracking function as an existing, already blocked domain. That domain is: `api.userleap.com`.

The new domain that should be blocked is:
```
0.0.0.0 api.sprig.com
```
The queries captured from Fiddler have identical SDK paths and contents. A DNS lookup reports both domains share some IPs. As it is functionally the same as UserLeap, there is unlikely to be any broken websites as a result of blocking. It's a recent addition to Twitch. Caught my eye.

**Comment by StevenBlack** [comment]
Thank you @icedterminal this is added in commit 0541b566.

Closing!
