### ISSUE TITLE
Block `1493c7cc8b.com 547a6c91f1.com 5c88c350e2.com adultdvdparadise.com c58f1b26aa.com dontexist.org for-joiyvidspics.site maxofzavdaft.com`

### ISSUE THREAD

**Issue by WebworkrNet** [StevenBlack/hosts#2318]
**Lists in use:**
- Unified Hosts
- Fakenews
- Gambling
- Porn
- Social

**Client:**
Blokada/Android

**Domains:**
```

1493c7cc8b.com
f443620b6f.1493c7cc8b.com

547a6c91f1.com
f199baefda.547a6c91f1.com

5c88c350e2.com
f93bad83b8.5c88c350e2.com

adultdvdparadise.com

c58f1b26aa.com
fafeef7fc5.c58f1b26aa.com

dontexist.org
yugiyhoolol.dontexist.org

for-joiyvidspics.site

maxofzavdaft.com
```

**Details:**
Malicious

https://www.virustotal.com/gui/domain/1493c7cc8b.com

![chrome_screenshot_1683212921105](https://user-images.githubusercontent.com/43509007/236250065-8eb52292-fd76-4bfc-9b62-8bfe306fb8f3.png)

https://www.virustotal.com/gui/domain/547a6c91f1.com

![chrome_screenshot_1683213017991](https://user-images.githubusercontent.com/43509007/236250525-5917fc4a-1219-4aee-bf3a-2cc5dc3975a8.png)

https://www.virustotal.com/gui/domain/5c88c350e2.com

![chrome_screenshot_1683213119930](https://user-images.githubusercontent.com/43509007/236250948-08d8a6de-f885-4b0f-a791-b420082f89c3.png)

https://www.virustotal.com/gui/domain/adultdvdparadise.com

![chrome_screenshot_1683213229199](https://user-images.githubusercontent.com/43509007/236251443-c6a8a32c-281d-4830-882f-c3b803babf1f.png)

https://www.virustotal.com/gui/domain/c58f1b26aa.com

![chrome_screenshot_1683213332031](https://user-images.githubusercontent.com/43509007/236252057-72de1bca-2a0e-4a9a-8102-d6dbd03eb6f3.png)

https://www.virustotal.com/gui/domain/fafeef7fc5.c58f1b26aa.com

![chrome_screenshot_1683213574691](https://user-images.githubusercontent.com/43509007/236253137-224573a2-3b9e-42e1-8a52-1d06413dea64.png)

https://www.virustotal.com/gui/domain/dontexist.org
![chrome_screenshot_1683213712187](https://user-images.githubusercontent.com/43509007/236253757-3b450438-95ce-4950-b15d-52bf39c1cea3.png)

https://www.virustotal.com/gui/domain/for-joiyvidspics.site

![chrome_screenshot_1683213845510](https://user-images.githubusercontent.com/43509007/236254328-c847fed6-1ef1-4db4-9390-f78553014dbd.png)

https://www.virustotal.com/gui/domain/maxofzavdaft.com

![chrome_screenshot_1683213924509](https://user-images.githubusercontent.com/43509007/236254666-3b0f32af-596d-4968-980f-cb5f9af1a00a.png)

**Comment by bigdargon** [comment]
The domains below you should block CNAMEs will be more effective, because these random domains will constantly register new.

```
f443620b6f.1493c7cc8b.com
f199baefda.547a6c91f1.com
f93bad83b8.5c88c350e2.com
fafeef7fc5.c58f1b26aa.com
```
Should block
```
cdn28786515.ahacdn.me
cdn12359286.ahacdn.me
puwpush.com
```
More https://github.com/AdguardTeam/cname-trackers/blob/master/trackers/ahacdn_me.md
