### ISSUE TITLE
Unblock gamesnostalgia.com

### ISSUE THREAD

**Issue by LewisSpring** [StevenBlack/hosts#2319]
I'm not aware of any reason why this site is blocked.
Please can you remove it from the list? If you can tell me which upstream list it is I'm more than happy to post an issue there.
Cheers

**Comment by StevenBlack** [comment]
Hello Lewis @LewisSpring thank you for your question.

We don't presently list the domain `gamesnostalgia.com`.

Closing.

**Comment by StevenBlack** [comment]
Maybe that's using an older version of the list? There's some latency downstream. We don't carry it now, that's certain. Cheers!

**Comment by icedterminal** [comment]
Cloudflare, like Google and OpenDNS, uses a more hands-off approach when it comes to managing their primary DNS. They don't actively block or filter anything on that one. This includes their alt 1.0.0.1, the IPv6, DoH and DoT resolvers.

The exception to this is their dedicated, alternative (not primary) filtering and blocking DNS resolvers 

> While 1.1.1.1 can safeguard user privacy and optimize efficiency, it is designed for direct, fast DNS resolution, not for blocking or filtering content.
> 
> https://1.1.1.1/family/

If you're using 1.1.1.2 or 1.1.1.3 or those alts with IPv6, DoH or DoT, it's being blocked there. If you are not, then someone else is blocking it.

The Radar service you visited is largely automated. It's user curated to a degree. You can submit feedback on any domain. What's likely happened is someone downloaded an old game, someones AV complained about it being malware (false positive) and then someone added a feedback. Cloudflare slapped the tags on it and there you have it.

I just downloaded a dozen random games (Defender remained silent) then submitted them to Virus Total. Here is one: https://www.virustotal.com/gui/file/e9abf3193ca0a98101fd9f784a012dcc581e527878e7a2c3df99c507d97ab111

These are all from much smaller vendors and as such I believe is false positive. Double check things on your end and if you want, submit feedback to Radar.
