### ISSUE TITLE
Porn sites to add

### ISSUE THREAD

**Issue by Veeten** [StevenBlack/hosts#2321]
Those sites are not included in the blocklist:
tubxporn.xxx
rexporn.sex

**Comment by StevenBlack** [comment]
Thank you @Veeten.

Ping @sinfonietta for inclusion in your list.

**Comment by Sinfonietta** [comment]
@StevenBlack these are added.

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta. Closing.
