### ISSUE TITLE
Block `caremed.de financialanalystinfo.com mailtransfere.shop restitution.eu.com`

### ISSUE THREAD

**Issue by WebworkrNet** [StevenBlack/hosts#2323]
**Lists in use:**
- Unified Hosts
- Fakenews
- Gambling
- Porn
- Social

**Domains:**
```
caremed.de
financialanalystinfo.com
mailtransfere.shop
restitution.eu.com
```

**Details:**
Spam

https://www.virustotal.com/gui/domain/caremed.de

![chrome_screenshot_1683524893987](https://user-images.githubusercontent.com/43509007/236744033-f11fe320-6225-42c9-9b66-3f3751ef1da6.png)

https://www.virustotal.com/gui/domain/financialanalystinfo.com

![chrome_screenshot_1683525021605](https://user-images.githubusercontent.com/43509007/236744267-fa3c4222-93f6-48ff-b622-34dd4a605106.png)

https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3afinancialanalystinfo.com&run=toolpage

![chrome_screenshot_1683525127131](https://user-images.githubusercontent.com/43509007/236744544-a7cc5d9e-b336-4bed-9c97-53a19a700b5a.png)

https://www.virustotal.com/gui/domain/mailtransfere.shop

![chrome_screenshot_1683525371183](https://user-images.githubusercontent.com/43509007/236745220-59aa9e33-219e-4396-80d6-8e1c4ee194ae.png)

https://www.virustotal.com/gui/domain/restitution.eu.com

![chrome_screenshot_1683525279667](https://user-images.githubusercontent.com/43509007/236744995-29b93eee-b553-47ce-a740-73a11835c4d7.png)

**Comment by hagezi** [comment]
`caremed.de` - German Work and Travel insurance
`financialanalystinfo.com` - tracking domain used for processing email/marketing statistics such as views/clicks/optouts
`mailtransfere.shop` - DEAD domain
`restitution.eu.com` - only SOA Record, no A/AAAA, whitelisted on https://otx.alienvault.com/indicator/domain/restitution.eu.com

**Comment by icedterminal** [comment]
> `financialanalystinfo.com` - tracking domain used for processing email/marketing statistics such as views/clicks/optouts

So this is the only one that has the potential to be included. However, in blocking that TLD you remove the ability to [unsubscribe at their site](http://financialanalystinfo.com/main.php?action=manunsub). The ideal solution would be find out what sub domains, if any, are in use with the emails they are present in. This requires input from those that encounter it.
