### ISSUE TITLE
pornhub regional version

### ISSUE THREAD

**Issue by whamola** [StevenBlack/hosts#233]
i can see that regional version (e.g. it.pornhub.com br.pornhub.com etc) of the site are not included in the porn list!
can i suggest modification on the hosts or it's all up to Steven Black? new to github, please forgive my ignorance
Have a great day!

**Comment by Jezza-x3** [comment]
See my issue #202 

Hope this helps!

**Comment by whamola** [comment]
where do i have to submit a pull request exactly? thanks!

**Comment by raziel-** [comment]
@whamola 
https://github.com/StevenBlack/hosts/pulls

**Comment by StevenBlack** [comment]
Hi @whamola please make suggestions to the curators of the porn extension:

*  @Clefspeare13 at https://github.com/Clefspeare13/pornhosts
*  @Sinfonietta at https://github.com/Sinfonietta/hostfiles

**Comment by Clefspeare13** [comment]
@whamola I've added the localized versions to my hosts file. If you come across this for any other sites, please let me know: https://github.com/Clefspeare13/pornhosts/issues

**Comment by StevenBlack** [comment]
Thanks @Clefspeare13!

Hosts files here are updated with this latest change.

Closing.

**Comment by uBlock-user** [comment]
Why is pornhub.com listed in Unified Hosts list ? It should in Unified + porn, but NOT in Unified list itself! Please remove it.

**Comment by StevenBlack** [comment]
@uBlock-user we're just the aggregator.

pornhub.com is currently listed by the Badd-Boyz repo.  Open this issue [here](https://github.com/mitchellkrogza/Badd-Boyz-Hosts/issues).

CC @mitchellkrogza

**Comment by mitchellkrogza** [comment]
@uBlock-user attended to in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/5f4f74424e0de3ec8a7f1d819941eeb1eee0ff0f it's a remnant from a very early list I began with. The porn sites that do exist in my lists are all sites that use referrer spam techniques against my web sites, pornhub.com is not one of them and hence removed.

**Comment by uBlock-user** [comment]
@mitchellkrogza Thank you for the prompt response and explanation.

**Comment by StevenBlack** [comment]
@uBlock-user the latest version of pre-generated consolidated hosts is live and online.  Thanks @mitchellkrogza.
