### ISSUE TITLE
suggestion for porn blacklist

### ISSUE THREAD

**Issue by Theoldnation** [StevenBlack/hosts#2333]
daftsex.app is another variation of daftsex but without their video player so the site works as normal

**Comment by StevenBlack** [comment]
Thank you @Theoldnation.

Ping @sinfonietta for inclusion.

**Comment by Sinfonietta** [comment]
@StevenBlack these are added.

**Comment by StevenBlack** [comment]
👍🏻 @Sinfonietta. Closing.
