### ISSUE TITLE
Unblock telemetry-console.api.playstation.com

### ISSUE THREAD

**Issue by luis-oliveira92** [StevenBlack/hosts#2334]
Hi, the domain telemetry-console.api.playstation.com is currently being blocked, this prevents the PlayStation 5 consoles from syncing info related to play time and recently played games.

**Comment by StevenBlack** [comment]
Thank you Luis @luis-oliveira92 this is removed in commit [7a452ee](https://github.com/StevenBlack/hosts/commit/7a452ee53781201b995800b4a2ab4052b8b8df46).
