### ISSUE TITLE
serasearchtop.com

### ISSUE THREAD

**Issue by smed79** [StevenBlack/hosts#2339]
Hi,

please, introduce `serasearchtop.com`

The domain is used to inject ads (or malicious code) via malicious google chrome extension (PDF Toolbox).

for details, see 

https://palant.info/2023/05/16/malicious-code-in-pdf-toolbox-extension/

Thank you.

**Comment by StevenBlack** [comment]
Thank you Anon @smed79 this is added in commit e1a2bf21 and will be live in the next release.

Closing.
