### ISSUE TITLE
AI porn sites to block

### ISSUE THREAD

**Issue by willyw0nka** [StevenBlack/hosts#2343]
- pornify.cc
- pornpen.ai
- pornlabs.net
- pornmake.ai
- pornwhow.ai
- ai-porn.ai
- made.porn
- spicy.porn
- pornworks.ai
- sexy.ai
- pornjoy.ai
- pornjourney.ai
- aipornhub.net

**Comment by StevenBlack** [comment]
Thank you Albert @willyw0nka.  Ping @sinfonietta for inclusion in the porn list.

**Comment by Sinfonietta** [comment]
@StevenBlack these are added.

**Comment by StevenBlack** [comment]
Thanks @Sinfonietta. Closing.
