### ISSUE TITLE
iOS Malware Domains

### ISSUE THREAD

**Issue by Eow2022yia** [StevenBlack/hosts#2344]
Hi there,

Please can you add the following domains to the malware filter blacklist:

addatamarket.net
backuprabbit.com
businessvideonews.com
cloudsponcer.com
datamarketplace.net
mobilegamerstats.com
snoweeanalytics.com
tagclick-cdn.com
topographyupdates.com
unlimitedteacup.com
virtuallaughing.com
web-trackers.com
growthtransport.com
anstv.net
ans7tv.net

Source:
https://securelist.com/operation-triangulation/109842/

**Comment by StevenBlack** [comment]
Thank you @Eow2022yia these are added in commit 97b0146f. This will go live in the next release.

Closing.
