### ISSUE TITLE
Invalid domain

### ISSUE THREAD

**Issue by pallebone** [StevenBlack/hosts#2347]
Hi there,

Thank you for these lists. I notice there is an invalid domain:
0.0.0.0 ttps

On list: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Detection:

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 188935 exact domains and 0 ABP-style domains (ignored 2 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"
        - "ttps"

Kind regards
Peter

**Comment by StevenBlack** [comment]
Thank you for this Peter @pallebone 

I'm seeing this on line 192768 of the unified hosts file...

```
0.0.0.0 ttps
```
This seems to be coming from URLHaus.  I have sent them an email about this.

**Comment by StevenBlack** [comment]
I'm thinking our parsers should catch this...

**Comment by pallebone** [comment]
Just an update: still appearing today - 

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 188935 exact domains and 0 ABP-style domains (ignored 2 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"
        - "ttps"

**Comment by StevenBlack** [comment]
@pallebone this will be fixed in the next release as this is now fixed upstream.

**Comment by StevenBlack** [comment]
Closing!

**Comment by pallebone** [comment]
[i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 190102 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"
Thanks - appears fixed.

**Comment by rdwebdesign** [comment]
Looks like the `ttps` domain is back:

```
  [✓] Parsed 202389 exact domains and 0 ABP-style domains (ignored 3 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"
        - "ttp"
        - "ttps"
```
