### ISSUE TITLE
hosts file blocks amazon browsing history

### ISSUE THREAD

**Issue by alexmcwi** [StevenBlack/hosts#2349]
I've had this issue for a while and it wasn't until now that I was able to narrow it down to the hosts file.

Does anyone know which entry in the hosts file prevents amazon from adding items I look at to my browsing history on the site?

When I'm on Amazon and I go to Accounts & Lists / Browsing history ( https://www.amazon.com/gp/history?ref_=nav_AccountFlyout_browsinghistory ) none of the items I looked at shows up on the list. If I disable the hosts file (e.g. rename it, so it's not used by my computer), then items I look at show up on the list.

Thanks!

**Comment by StevenBlack** [comment]
Thank you for this @alexmcwi.

if you're the sort of person who wants to have your online activity tracked, this hosts file is Mos Def not for you.

Closing.

**Comment by alexmcwi** [comment]
You don't know. I see ;-)

Don't close it please. Maybe someone knows the answer. 

I'm as big a fan of activity tracking as you are, but we both know that with or without the hosts file amazon knows who I am. Ebay, for example, has the same feature ("your viewed items") and doesn't rely on a separate server to implement it.

Needless to say, besides blocking tracking, the hosts file also cuts down cpu usage by browsers dramatically (75%, 80%?), as ads have a tendency to eat up the computer, and the more tabs one has open, the worse it gets.

PS: I really miss the wiki.

**Comment by alexmcwi** [comment]
Took a bit of trial and error, but in case other people here need this functionality, the host to comment out from the file is fls-na.amazon.com

I don't know what implications this might have with tracking me when I'm NOT on amazon's web site, but from conversations with their support people, months ago, because I thought my amazon browsing history broke on their end, they can still see users' browsing history regardless of what's in the hosts file.
