### ISSUE TITLE
Fakenews

### ISSUE THREAD

**Issue by iandoug** [StevenBlack/hosts#235]
hi

I think the FakeNews lists should be in a separate file ... not everyone is going to agree on what is fake news and what is not. While the intention is fine, at the moment the long embedded lists are verging on Net Nanny or censorship .... IMHO :-)

thanks.

**Comment by Jezza-x3** [comment]
The fakenews list is maintained by a user other than Steven Black. 

Steven has made it clear that the person has good intentions and he will keep it here. 

You DO NOT have the get one with fake news blocked. You have a choose the hosts you will get. If you choose it, it is your fault. 

See issue #232

**Comment by iandoug** [comment]
Hi
Excuse my ignorance. I came here from 
https://www.darrentoback.com/this-script-updates-hosts-files-using-a-multi-source-unified-block-list-with-whitelisting

which I understood as this project being a python script to combine a bunch of blacklists into one massive hosts file. Which I took as meaning "needs all the lists in the repo". After your comment I took a closer look and now see that I should not take all the lists...

I think it would be clearer if the readme spelled that out, or if for example each catogory (malware, ads, porn, etc) had its own list, and then a separate section of the readme, after a heading like "premerged lists" or somesuch, gave the various pre-merged combos which now exist.

Thanks, Ian

**Comment by inoas** [comment]
@iandoug that confirms my [assumption](https://github.com/StevenBlack/hosts/issues/232#issuecomment-272877491) that people will simply download the hole list.

I do agree that there should be a sane recommended default.

**Comment by StevenBlack** [comment]
Hi @iandoug thanks for stopping-by.

> I think it would be clearer if the readme spelled that out, or if for example each catogory (malware, ads, porn, etc) had its own list, and then a separate section of the readme, after a heading like "premerged lists" or somesuch, gave the various pre-merged combos which now exist.

Up-front, at the [very top of the repo, there is this table](https://github.com/StevenBlack/hosts#unified-hosts-file-with-base-extensions) with links to individual readme for each variant.

I'm open to suggestions to make this more clear.

The default list is Adware + Malware and this is the one most people download as it's the one featured in the root of the repo.

**Comment by iandoug** [comment]
TBH, further to my previous message about your script being a combining / de-duping script, I initially interpreted the list of variants as being a collection from different places, which your script would then reduce down, dedup etc. 

ie I took the variants as "pre-cleanup" rather than "post-cleanup".

**Comment by kronflux** [comment]
Regardless of the fact that this is managed by another source, and every other factor - I think that the initial post here is incorrect regardless.
Fake news would be defined as any news from a non-reputable source(ie: sources which regularly post bogus or clickbait articles)
Which of those articles are fake or not is irrelevant. The idea is to block the source, not the individual news. If something is "real" news, it will absolutely be on a more reputable news source as well.

**Comment by inoas** [comment]
@kronflux so there there is regularily posted bogus on google.com, twitter.com, facebook.com, amazon.com (reviews), nyt, wp, rt, fox news, reddit et. al.

E.g. `all` social network platforms and any major news source (as they copy from news distributors like reuters or dpa, and as they are politically heavily influenced... I for once like nyt for the most part, still doesn't change the bias fact).

You really want to ban all of those?

**Comment by Mahaveer-Jeevagan** [comment]
Why isn't traboola and outbrain  in the list yet? They are both adware and
click bait

**Comment by inoas** [comment]
@Mahaveer-Jeevagan agreed, however that has nothing to do with Fake News and is a quite clear case ;-) (imho).

**Comment by iandoug** [comment]
@inoas I agree with your viewpoint... I don't know the compiler of the list, I just hope it was not simply a case of taking that "Official List of Fake News Sites" that was published a few months back. IIRC there were some problems with that list.
There's also allegations of the TLAs having people embedded in reputable news organisations to push particular agendas.

**Comment by kronflux** [comment]
@inoas, I believe you're missing the point. This list is targeted at websites that are specifically NEWS sites, which regularly post fake news articles.
Social media does not fall under that category. People DO post fake news on social media, however social media itself do NOT claim to be news sites(legitimate or otherwise)
Also, most commonly people post fake news on social media as LINKS to OTHER websites, which are often these fake news sites.

So no, absolutely we would not ban those websites based on the fact that fake news is available on them, the concept of fake news sites is quite clear - independent websites dedicated to presenting news articles, which often post fake news articles without citation or sources of their news.

**Comment by inoas** [comment]
So google posts a lot of fake news through their AMP. Ban AMP/Google?

**Comment by kronflux** [comment]
Alright, well you appear to have no serious thoughts on this, nor do you seem to be capable of understanding the concept so I'll just leave this as is, and not reply further. Thanks for your input.

I believe this issue can be closed, I see no further progress being able to come from it @StevenBlack 
Personally I'm very happy with this list, and I think many others are as well.

**Comment by StevenBlack** [comment]
It is what it is.

I'm always happy to improve things.  Pull Requests resonate best with me  😄 

Closing!
