### ISSUE TITLE
Telstra - Our coverage maps

### ISSUE THREAD

**Issue by gyCfjSnO** [StevenBlack/hosts#2350]
### Which domain(s) should be unblocked?

`cdnssl.clicktale.net`

### Why should the domain(s) be unblocked?

When the domain `cdnssl.clicktale.net` is blocked you are unable to view the coverage map overlay at https://www.telstra.com.au/coverage-networks/our-coverage

This is what it should look like:

![image](https://github.com/StevenBlack/hosts/assets/49738152/df6a8c72-0555-431c-b71e-bfc43fe2f1e3)

**Comment by StevenBlack** [comment]
Thank you for this Anon @gyCfjSnO.

This domain comes to us from two separate curators.

This isn't going to change.

Closing.

**Comment by gyCfjSnO** [comment]
> Thank you for this Anon @gyCfjSnO.
> 
> This domain comes to us from two separate curators.
> 
> This isn't going to change.
> 
> Closing.

I've raised approximately 12 GitHub issues with various list maintainers.

Could you point me in the right direction as to whom the two separate curators are?

**Comment by StevenBlack** [comment]
Dude @gyCfjSnO this ABSOLUTELY isn't going to change.

https://contentsquare.com/clicktale/

And from https://www.softwareadvice.com/ca/crm/clicktale-profile/

> Clicktale is a customer engagement software that helps improve web usability, customer experience and increases the user conversion rate. Its customer analytics feature collects a bevy of data information and can track a users movement while using the site.

...and...

> Clicktale offers experience analytics for web, mobile and experience analytics for apps. Its features include experience center, heat maps, session replays, conversion analytics, advanced data analytics and psychological analytics.

Forget it.  Hard stop.

**Comment by gyCfjSnO** [comment]
@StevenBlack I hope you are doing well. I noticed that your reply was a bit harsh and dismissive. That might not reflect your intention, but it could hurt someone’s feelings. Is everything okay with you? I’m here to listen if you want to share anything.
