### ISSUE TITLE
Adding Google Colab option to README

### ISSUE THREAD

**Issue by ScriptTiger** [StevenBlack/hosts#2353]
Thoughts on adding a Google Colab option to the README for generating your own hosts file? I think it might even beat Docker as far as simplicity and ease of access.

https://colab.research.google.com/drive/1tYWXpU2iuPDqN_o03JW9ml3ExO80eBLq?usp=sharing

**Comment by StevenBlack** [comment]
Hi @ScriptTiger. Thanks! Pull requests speak loudly 😄 

I'll probably be merging PR #2335 soon so please watch for merge conflicts.

**Comment by ScriptTiger** [comment]
Roger! Just thought I'd send out some feelers first. I'll send a PR later. I'll keep the footprint as minimal as possible to reduce conflicts, basically just a note in the "Option 3: Generate it in your own environment" section. I'm not going to presume it to be the best option off the bat, so I'll just leave it there and if others want to rearrange the order of preference, that can be a discussion later.
