### ISSUE TITLE
Please add zhihu-web-analytics.zhihu.com

### ISSUE THREAD

**Issue by HeyBroWhatsUp** [StevenBlack/hosts#2356]
This url is a tracking url. 
<details><summary>Request header</summary>
<p>

:Authority:
zhihu-web-analytics.zhihu.com
:Method:
POST
:Path:
/api/v2/za/logs/batch
:Scheme:
https
Accept:
*/*
Accept-Encoding:
gzip, deflate, br
Accept-Language:
zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7
Content-Encoding:
gzip
Content-Length:
744
Content-Type:
application/x-protobuf
Dnt:
1
Origin:
https://www.zhihu.com
Referer:
123456
Sec-Ch-Ua:
"Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Windows"
Sec-Fetch-Dest:
empty
Sec-Fetch-Mode:
cors
Sec-Fetch-Site:
same-site
User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
X-Za-Batch-Size:
8
X-Za-Clientid:
123456
X-Za-Log-Version:
3.3.74
X-Za-Platform:
DesktopWeb
X-Za-Product:
Zhihu
</p>
</details>

**Comment by StevenBlack** [comment]
Thank you @HeyBroWhatsUp, this is added in commit 343eec32 and will be live in the next release.

Closing.
