### ISSUE TITLE
please block assistant-chronopost.com

### ISSUE THREAD

**Issue by lf-novelt** [StevenBlack/hosts#2358]
new French SMS phishing campaign

`assistant-chronopost.com` maskerading official https://chronopost.fr

**Comment by lf-novelt** [comment]
yeah, probably. Sites like this like to hide for some specific ip locations / user agent to avoid detection
![image](https://github.com/StevenBlack/hosts/assets/46479127/8810734c-7e83-471a-824f-a8e0dc484e03)

**Comment by iam-py-test** [comment]
Thanks.
Would you mind putting ` around the link in the OP so people don't accidentally click on it? Thanks

**Comment by StevenBlack** [comment]
Merci Louis @lf-novelt.  This is added in commit 107082b and will be live in the next release.

Closing.
