### ISSUE TITLE
Hosts file makes the Internet not work at all and makes the DNS Client have high CPU usage.

### ISSUE THREAD

**Issue by gabrielvicenteYT** [StevenBlack/hosts#2360]
When I use any of the hosts files in here, the Internet doesn't work anymore. When I use the default hosts file, everything works fine.

**Comment by StevenBlack** [comment]
Hi @gabrielvicenteYT you're using Windows — which is a dumpster fire OS, and the only one with this issue — and the remedy for this is covered in the readme: [Warning: Using this hosts file in Windows may require disabling DNS Cache service](https://github.com/StevenBlack/hosts).

Closing.
