### ISSUE TITLE
False positive on tvn24.pl?

### ISSUE THREAD

**Issue by dabiOW** [StevenBlack/hosts#2361]
I'm not really technical enough to be able to tell what exactly is the problem, but something about this host file blocks all images on [tvn24.pl](https://tvn24.pl/)

**Comment by iam-py-test** [comment]
Caused by blocking `cdn.cookielaw.org`

**Comment by krystian3w** [comment]
Maybe someone create(d) a surrogate similar to: https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-redirects.md#didomi-loader

Assuming the HOSTS/DNS/Pi-Hole/Router level ban does not block such a filter:

```adb
||cdn.cookielaw.org^$script,xhr,redirect=cookielaw-loader.js,domain=tvn24.pl
```

It is possible that the entire family of TVN sites may have similar damage as long use same GDPR manager.
