### ISSUE TITLE
ad domains for zoro.to pop up ads

### ISSUE THREAD

**Issue by zherk** [StevenBlack/hosts#2365]
naicoapt.com
checaigu.net
hauganes.net
jirtesee.net
meltaigh.net
poucoaga.com
psaltard.net
ptaickug.com
ribumpin.com
shartems.com
shugnais.net
thaudray.com
tzegilo.com
tooshecu.com
zaumaico.com

These are some popup ad domains I've found for zoro.to. 

I was mostly playing whack a mole with these until I found 2 of the mob spawners. naicoapt.com and thaudray.com beget the most of the other ads I think. checaigu.net flags malicious in virustotal https://www.virustotal.com/gui/domain/checaigu.net and its on some other lists. the rest just enter me into popup redirect hell on duckduckgo browser iOS 123movies style. 
I have some other domains but I think they might be getting into false positive territory.

these are the potentially false positives that i also wanted to get rid of on zoro and added to my manual blocklist:

s7.addthis.com
secret-options.com
adblocker-vpn.com
5fd74.v.fwmrm.net

(\.|^)mysafe-search\.net$
(\.|^)online-metrix\.net$
(\.|^)trackints\.com$
(\.|^)naicoapt\.com$

**Comment by StevenBlack** [comment]
Thank you for this @zherk.  I decline to accept these suggestions.

Closing.
