### ISSUE TITLE
Invalid domain on list

### ISSUE THREAD

**Issue by pallebone** [StevenBlack/hosts#2366]
[i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 194049 exact domains and 0 ABP-style domains (ignored 2 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"
        - "dataexpertitsolucionesinforma"

dataexpertitsolucionesinforma is not a domain name.

- P

**Comment by rai510** [comment]
Having same issue on my pihole

**Comment by StevenBlack** [comment]
Thank you Peter @pallebone.

This comes to us via URLHaus.

```
data/URLHaus/hosts
448:127.0.0.1	dataexpertitsolucionesinforma
```

I have just contacted them about this.

**Comment by StevenBlack** [comment]
Peter @pallebone this is rectified and the problem domain is no longer included in the [latest release](https://github.com/StevenBlack/hosts/releases/tag/3.13.6).

Closing.
