### ISSUE TITLE
GoodbyeAds Spotify

### ISSUE THREAD

**Issue by Eow2022yia** [StevenBlack/hosts#2367]
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Spotify-AdBlock.txt

Hi there,

Would you please consider adding GoodbyeAds Spotify to your lists/hosts?

This can reduce Spotify ads and it does not break the app/website.

Thank you.

**Comment by StevenBlack** [comment]
Thank you for this @Eow2022yia we've [talked about Spotify here many times before](https://github.com/search?q=repo%3AStevenBlack%2Fhosts+spotify&type=issues).

This isn't going to change.  Too many different apps, devices, web, there's even command line clients for Spotify. Our experience is, list something, break something somewhere else.

Closing.
