### ISSUE TITLE
false positive - secur.hopp.to

### ISSUE THREAD

**Issue by shaulgo** [StevenBlack/hosts#2372]
Hey, hopp.to is a link-in-bio product by Wix.com. 
secur.hopp.to has been deleted. But it affects our domain - hopp.to.

Please remove secur.hopp.to from you list.
It would be amazing if our domain can be allowlisted. But it seems this is only a blocklist.

Thanks

**Comment by StevenBlack** [comment]
Hello Shaul @shaulgo I've removed the domain `secur.hopp.to` in commit ab9caa39 and that will reflect in the next release, coming shortly.

Closing.
