### ISSUE TITLE
suggestion porn black list

### ISSUE THREAD

**Issue by jobbb2** [StevenBlack/hosts#2375]
Best regards

127.0.0.1 www.deutscher-amateursex.com
127.0.0.1 bookmark.xxx
127.0.0.1 www.beautymovies.com
127.0.0.1 privatefotze.com
127.0.0.1 www.fickfilme.org
127.0.0.1 www.pornoschlange.com
127.0.0.1 www.peniszeigen.com
127.0.0.1 watchmdh.to
127.0.0.1 dirtykontakt.com
127.0.0.1 www.pornojenny.net
127.0.0.1 www.yoochat.net
127.0.0.1 redrube.mobi
127.0.0.1 dirtyclips.to
127.0.0.1 www.amateurpin.xxx
127.0.0.1 xvideis.cc
127.0.0.1 www.hardcoreente.com
127.0.0.1 www.bokep.video
127.0.0.1 www.fkk-filme.com
127.0.0.1 www.desixnxxvideos.com
127.0.0.1 porn-hab.com
127.0.0.1 www.iporno.site
127.0.0.1 www.pornomaa.com
127.0.0.1 spangbang.biz
127.0.0.1 arabpornotube.org
127.0.0.1 www.xxxvideosex.net
127.0.0.1 www.xtube.video
127.0.0.1 zoozhamster.com
127.0.0.1 zoo.zone
127.0.0.1 www.cuntpornvideos.com
127.0.0.1 www.pornviola.com
127.0.0.1 www.porntubesweet.com
127.0.0.1 www.niceonepussy.com
127.0.0.1 www.azpornvideos.com
127.0.0.1 watchpornvideo.online
127.0.0.1 www.hdtubepussy.com
127.0.0.1 outdoorporn.one
127.0.0.1 xxxindianporn.org
127.0.0.1 www.influencersgonewild.video
127.0.0.1 www.365xxx.org
127.0.0.1 www.loveherfeet.com
127.0.0.1 www.foothound.com
127.0.0.1 footadoration.com

**Comment by StevenBlack** [comment]
Thank you for this @jobbb2.  Ping @sinfonietta for inclusion.

**Comment by jobbb2** [comment]
Hello https://github.com/StevenBlack

please validate my suggestion for the porn blacklist. Thank you.

**Comment by StevenBlack** [comment]
@jobbb2 please read the repo readme.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

When you post a list like this here, you're creating work for me. I ping @sinfonietta as a courtesy to you, but the better place to post this is to @sinfonietta directly. In other words, I'm not a porn list curator.

**Comment by jobbb2** [comment]
sorry. thank you for information. I had only looked in your issues and found that other users have posted there porn blacklist links. Best regards.
