### ISSUE TITLE
Please add pr0n domains

### ISSUE THREAD

**Issue by TheUnfapper** [StevenBlack/hosts#2377]
### Discussed in https://github.com/StevenBlack/hosts/discussions/2376

<div type='discussions-op-text'>

<sup>Originally posted by **TheUnfapper** July  2, 2023</sup>
Hello here are pr0n websites that aren't blocked by current version of the hosts file made for it. I wanted to try to do a pull requests etc but seemed a pain in the a** for me I don't understand it I'm sorry.

The 2 first are french tchat but like 95% of it are just pr0n related rooms with pics shared etc.
The others are websites with pr0n videos or gifs.
All of them are not blocked by the current host version, few have some videos or content blocked but not everything at all.
So here is the list if you can add it it could be cool,

0.0.0.0 coco.fr
0.0.0.0 coco.gg
0.0.0.0 porn112.com
0.0.0.0 hdporn112.com
0.0.0.0 balancetanude.fr
0.0.0.0 pornomanoir.com
0.0.0.0 tubeporno.fr
0.0.0.0 fr.xgroovy.com
0.0.0.0 xgroovy.com
0.0.0.0 nuespournous.com
0.0.0.0 xhamster.com
0.0.0.0 pornheed.com
0.0.0.0 sexy.lesdebiles.com
0.0.0.0 reference-sexe.com
0.0.0.0 sexetag.com
0.0.0.0 veuxtube.com
0.0.0.0 amateuretsexe.com
0.0.0.0 video-creampie.com
0.0.0.0 lebon.porn
0.0.0.0 filmsexeporno.com
0.0.0.0 pornvids.fr
0.0.0.0 pornxxxxtube.net
0.0.0.0 masturhub.com
0.0.0.0 freeanimalporn.tv
0.0.0.0 singeporno.com
0.0.0.0 xxxi.porn
0.0.0.0 tubixe.com
0.0.0.0 sexetag.com
0.0.0.0 fr.filmepornoerotico.com
0.0.0.0 filmepornoerotico.com
0.0.0.0 fr.pornheed.com
0.0.0.0 pornheed.com
0.0.0.0 pornwoody.com
0.0.0.0 nuespournous.com
0.0.0.0 fr.rajwap.xyz
0.0.0.0 rajwap.xyz
0.0.0.0 pornego.com
0.0.0.0 fr.pictoa.com
0.0.0.0 pictoa.com
0.0.0.0 balancetanude.fr
0.0.0.0 young-pussy.com
0.0.0.0 teen18hd.com
0.0.0.0 teenagefucking.com
0.0.0.0 tightbaldpussy.com
0.0.0.0 girlscanner.org
0.0.0.0 acuptube.com
0.0.0.0 hotporn.today
0.0.0.0 missav.com
0.0.0.0 nudeuse.fr
0.0.0.0 balancetanude.fr
0.0.0.0 webtoonporn.xyz
0.0.0.0 webtoonporn.com
0.0.0.0 hentai18.net
0.0.0.0 hentaicomics.pro
0.0.0.0 mrpornosexe.com</div>

**Comment by StevenBlack** [comment]
Thank you for this @TheUnfapper.

Ping @sinfonietts for inclusion.

@TheUnfapper we already carry 10 of those 50 domains.  Using [ghosts](https://github.com/StevenBlack/ghosts)

```
$ ghosts -m p --clip --intersection                                                                     20:26:25
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts
Domains: 245,455
Bytes: 7.7 MB
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 50
Bytes: 1.2 kB
intersection: [filmsexeporno.com masturhub.com pictoa.com pornheed.com pornxxxxtube.net rajwap.xyz singeporno.com teenagefucking.com xgroovy.com xhamster.com]
Intersection: 10 domains
```

**Comment by Sinfonietta** [comment]
@StevenBlack I have added these, I'll take care of the duplicates in a sec.

**Comment by StevenBlack** [comment]
👍🏻 @Sinfonietta 

Closing.
