### ISSUE TITLE
STM32CubeIDE Usage Statistics

### ISSUE THREAD

**Issue by nandlab** [StevenBlack/hosts#2380]
[STM32CubeIDE](https://www.st.com/en/development-tools/stm32cubeide.html) by default sends usage-statistics to ST to "improve its products". You can opt-out of the usage-statistics in the preferences, which is not very intuitive and easy to miss.

When usage statistics is on, this domain is requested via DNS: `stmicroelectronics.d3.sc.omtrdc.net` (as seen in Wireshark)

The `omtrdc.net` [is known](https://better.fyi/trackers/omtrdc.net/) as an analytics and tracking platform from Adobe.

Can you please add `stmicroelectronics.d3.sc.omtrdc.net` to the blocklist?

**Comment by StevenBlack** [comment]
Thank you for this Ethan @nandlab.

This is added in commit bdf4bafb and will reflect online soon.

Closing.
