### ISSUE TITLE
It would be possible to block Threads connections?

### ISSUE THREAD

**Issue by gallegonovato** [StevenBlack/hosts#2385]
Good afternoon @StevenBlack 

I would like to propose if it would be possible to block all, or all, Threads connections.

I am commenting because of this: https://www.genbeta.com/redes-sociales-y-comunidades/threads-va-a-saber-todo-ti-informe-privacidad-apple-informacion-bancaria-incluso-tu-salud

Best regards and thanks for your help and time.

**Comment by StevenBlack** [comment]
Hello @gallegonovato thank you for this.

We would need to know which domains are used by Threads.

Ping @sinfonietta for the social list?

**Comment by gallegonovato** [comment]
Good afternoon @StevenBlack

Many thanks to you for your help and time. 

At the moment there is no application here. But I have been doing some checking.

I put Threads.com on https://www.whois.com/whois/threads.com . It came up:

ns-1039.awsdns-01.org
ns-1731.awsdns-24.co.uk
ns-404.awsdns-50.com
ns-875.awsdns-45.net
threads.com

Then on another website https://viewdns.info/reverseip/?host=threads.com&t=1 , https://viewdns.info/dnsreport/?domain=threads.com 

I don't know if you can help 

Thanks for your time and help.

**Comment by StevenBlack** [comment]
Thank you for this @gallegonovato.

Whois is never goint to tell us which domains are used by Threads.

Regardless, I won't include Threads in our main blocklist. It would go in our Social Media extension, and be part of lists that incluse social media blocking.

That said, this issue isn't actionable until we know what domains are *actually* used by Threads.

**Comment by gallegonovato** [comment]
Good afternoon @StevenBlack

I agree with you on adding it to the social part. 

About the pages I put you, it was what I managed to find from that connection. But as I was telling you I don't know if they are or not until the application itself makes them.

I hope to have if it is possible to hunt those connections. Because the truth is that it's amazing how much it wants to know about us.

A hug and thanks for your time and help.

**Comment by iam-py-test** [comment]
FYI, it's threads.net not threads.com

**Comment by gallegonovato** [comment]
Good afternoon @iam-py-test

You are right. I don't know why I went for the .com 

Thanks for the clarification 👍 

A hug

**Comment by iam-py-test** [comment]
I made the same mistake; it happens

**Comment by StevenBlack** [comment]
I'm closing this issue now because it's not actionable.

I'm sure one of our social media curators will add Threads as soon as they are moved to do so. This isn't something that we can launch here.

Closing.

**Comment by gallegonovato** [comment]
Good afternoon @StevenBlack

Thank you very much for your help and time.

We look forward to hunting down those connections.

By the way I was told by a co-worker that it came up on his Adaway:

a.ns.facebook.com
b.ns.facebook.com
c.ns.facebook.com
d.ns.facebook.com
dns.facebook.com
mixer.com
l.wl.co

He doesn't want stuff from Facebook if he can block it?

A hug 

Good afternoon @iam-py-test

The truth is that so many variables you can put after the point. That they drive you crazy.

A hug

**Comment by gallegonovato** [comment]
Good afternoon @StevenBlack and @iam-py-test.

Sorry to bother you guys. 

Now they're even going to add Nvidia stuff to Mozilla https://www.noticias3d.com/noticia/92380/firefox-soporta-nvidia-video-super-resolution.html

I even imagine they will put telemetry to Nvidia....

But I imagine that Nvidia will have a lot of connections and if they are blocked maybe it is not feasible or they break things of who uses their graphics. 

It's getting harder and harder to look for privacy and security. 

A hug
