### ISSUE TITLE
Whitelist/false positive: cdn.cookielaw.org

### ISSUE THREAD

**Issue by Linx-ESP** [StevenBlack/hosts#2387]
Wallapop (second hand market in Spain and Italy) won't load any searches with the domain blacklisted. Doesn't have any issues loading the frontpage.

Related to https://github.com/StevenBlack/hosts/issues/2257

**Comment by StevenBlack** [comment]
Thank you for this Linx @Linx-ESP.  This isn't going to change.  Contact Wallapop, this is their bug.

Closing.
