### ISSUE TITLE
Social: Google Plus

### ISSUE THREAD

**Issue by mueller-ma** [StevenBlack/hosts#239]
IMO google + should be in the social host file. What do you think about it?

**Comment by kronflux** [comment]
I believe you have a misunderstanding of how this hosts file project works.
It combines several hosts files from other reputable sources who regularly update and curate their lists, to make one massive master list.
It does not add or remove individual entries based on user suggestions - to have something added, you must go and find the curator of the social lists, and ask them to add to their own lists, which will in turn be added here via updates.

**Comment by Sinfonietta** [comment]
Today I learn google plus is still a thing  😸  just kidding.

@StevenBlack [I just added google plus to the social media hosts](https://github.com/Sinfonietta/hostfiles/commit/ca71293a1cedbaae059052f8903b57e5d259c4f2).  I think there must be other related domains but this is the main one.

**Comment by StevenBlack** [comment]
@mueller-ma @Sinfonietta @kronflux thanks everybody!

Commit 895977 and new build is online now.
