### ISSUE TITLE
Add to Ad list

### ISSUE THREAD

**Issue by ahsandar** [StevenBlack/hosts#2398]
Can see Citymapper app using applvn and showing ads, there seems to be a new domain being used. Adding it to regex block in pihole blocks it

ms4.applvn.com

**Comment by StevenBlack** [comment]
Thank you Ahsan @ahsandar this is added in commit [1aa462c](https://github.com/StevenBlack/hosts/commit/1aa462c141d86a492be714af7472cb84c54bfa8e) and will go live in the next release.
