### ISSUE TITLE
Removing non-existent domains

### ISSUE THREAD

**Issue by c1sc0** [StevenBlack/hosts#24]
Hi! There are some non-existent domains in list, that could be deleted?

**Comment by Sadi58** [comment]
Perhaps they should better be reported to each list maintainer.
I wonder if there's a small script to check for dead URLs in a list.

**Comment by hd074** [comment]
I think something like this was discussed in issue #13.

At this point the hosts file is always generated from scratch. 
So non-existent URLs that are deleted by the maintainers of the single lists wont show up in the newly generated hosts file.

**Comment by StevenBlack** [comment]
I'm not worried about no-longer-active domains making the list.  There is near zero cost to this.  And with actively curated host files, these will eventually be culled.

Small quibble: how can we know a domain isn't live?  On the server-side, it's easy to not respond to naked or unsupported URLs on port 80, and it's easy to ignore `ping` and other commands to the domain.

I'm happy to let host file maintainers worry about this.  Or not.

**Comment by Gitoffthelawn** [comment]
I think your "small quibble" is not so small! :-)  Probably would have to do a whois lookup and see if each domain is still registered.

But anyways, I'm interested in your comment about "near zero cost".  That would depend on the number of no-longer-active domains, correct?  10 or 20 domains probably doesn't make any noticeable difference, but 10K+ no-longer-active domains would start to make a difference in memory footprint and lookup speed, correct?
