### ISSUE TITLE
Why is videolan.org blocked?

### ISSUE THREAD

**Issue by mueller-ma** [StevenBlack/hosts#240]
Official website of the vlc player

**Comment by kronflux** [comment]
It's not?

Which list are you using? I'm using the Unified hosts + fakenews + gambling list, with several of my own additions as well..
I have zero issues connecting to videolan.org..

You can also check here:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

as you can see with a simple search, there is no reference to videolan.org.

**Comment by mueller-ma** [comment]
@kronflux https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts

**Comment by gromain** [comment]
It's in the porn list here: https://github.com/StevenBlack/hosts/blob/9e81c6a051f5ed927b1c44f68e1d5e1c22d573ea/extensions/porn/clefspeare13/hosts#L5273

**Comment by kronflux** [comment]
Ah yes, it appears you're correct.
 @mueller-ma, your grep is incorrect, it is found in only one of those lists, not all of them. Perhaps invalid syntax? I'm not great with grep.

It is, as @gromain pointed out, in the porn list from @Clefspeare13

However, that list, and individual entries from it are not managed by @StevenBlack, they are managed by the individual source, and therefore you need to take it up with them, not here - as individual entries are not modified in this project.

**Comment by Clefspeare13** [comment]
I have removed videolan from my list. Apologies.

**Comment by mueller-ma** [comment]
@kronflux Maybe this is a sign that we shouldnt trust every source we have right now

**Comment by kronflux** [comment]
Thank you, @Clefspeare13! :)

**Comment by mueller-ma** [comment]
IMO when adding a website to a blocklist it should be checked.

**Comment by kronflux** [comment]
They ARE checked by the individual maintainers of those lists. Sometimes things slip through. Don't get upset over it, look how quickly Clef fixed it upon finding out about it.

This project, however, has nothing to do with maintaining lists, only combining them into one. Therefore that comment belongs on the individual list's suggestions/issues area, NOT this one.

**Comment by StevenBlack** [comment]
@mueller-ma  I always check additions when I build new host files.   

Commit 92416150d5d41c05967e50a14d36e0695f219cfb rectifies this.

Closing.

**Comment by mueller-ma** [comment]
@kronflux Sure, in this case @Clefspeare13 reacted very fast. As Steven mentioned he checks the urls, so they are double checked.

**Comment by inoas** [comment]
> @kronflux Maybe this is a sign that we shouldnt trust every source we have right now

As I pointed out in the Fake News issues, the real point here is that these host lists cross over from pure ad/spam/virus sites to hoax/porn, to news.

As there is obviously a high demand for low level blocking of what destructs the web (ads, spam, viruses, but also to some degree hoax/porn, 'news') it is effectively time to create a community based review tool.

Not being a kernel hacker but maybe an idea would be to have a low level daemon (similar to LittleSnitch on macOs) that records DNS (and IP) requests and compares to the hosts file and if there is a match triggers something. Then some UI tool could pick it up and show which domains have been blocked. 

Another way that would be cool are different threshold levels, like crowd-sourcing ad-blocking where people (think bugmenot but against ads) where people would report DNS/IPs and based on their crowd trust, and your threshold level things would be blocked. You could then also set a trust rating per crowd user where you "believe" a certain user between 0 and 100% (0.00 to 1) in terms of blocking DNS and IP.

E.g. the only way this could become really better and a the same time not a maintenance hell for a very few volunteers managing the current hosts block lists would be to crowdsource the whole approach.
