### ISSUE TITLE
5 new potential additions for ads/tracking blocklist

### ISSUE THREAD

**Issue by amit-bh** [StevenBlack/hosts#2402]
Please see following 5 for ads/tracking blocklist. Thank you for all your hard work! (Edit: found some more and added)

adsninjacdn.b-cdn.net
cdn.adsninja.ca
nom.telemetrydeck.com
api.ibeat-analytics.com
mads.amazon.com (seems like ad domain from FireTV)

**Comment by StevenBlack** [comment]
Thank you Amit @amit-bh these area addded in commit 96a0e1bf and will be live in the next release.
