### ISSUE TITLE
phone adware: madqudden

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#2403]
There's an Android adware/malware that randomly loads up "madqudden.com" with advertisements about earning passive income. Google results for this term are basically non-existent, but I just witnessed it in person.

Screenshot of the site: https://www.site-shot.com/9fdqZjY5Ee60LwJCrBEACA

I'd like to propose adding it to the blocklist. Thank you.

**Comment by iam-py-test** [comment]
Do you need help removing this from your device?

**Comment by StevenBlack** [comment]
Hi Devon @hyder365 thank you for this.

When I follow the link above ⬆️ I get `Snapshot: 9fdqZjY5Ee60LwJCrBEACA doesn't exists`.

**Comment by StevenBlack** [comment]
Devon @hyder365 are you sure it's `madqudden.com` and not a subdomain of that?  Answering this may require some sleuthing.

See, we aren't in the business of making companies go dark on the internet, just their vectors for adware and malware. If they have any scale at all, most offenders don't use their root domain for that.

**Comment by StevenBlack** [comment]
Thank you Devon @hyder365 this is added in commit 7311969c and will be live in the next release.

Closing.
