### ISSUE TITLE
Add ad resources (Amazon, FreshWorks, Bugsnag, Sentry, Pinterest, TikTok, Yahoo, OEMs)

### ISSUE THREAD

**Issue by devlysh** [StevenBlack/hosts#2406]
**Amazon:**
analyticsengine.s3.amazonaws.com
analytics.s3.amazonaws.com
advertising-api.amazon.com
advertising-api-eu.amazon.com
advertising-api-fe.amazon.com

**FreshWorks:**
freshmarketer.com
claritybt.freshmarketer.com
fwtracks.freshmarketer.com

**Bugsnag:**
api.bugsnag.com
app.bugsnag.com

**Sentry:**
browser.sentry-cdn.com
app.getsentry.com

 **Pinterest:**
widgets.pinterest.com

**Reddit:**
events.reddit.com

**TikTok:**
ads-api.tiktok.com
analytics-sg.tiktok.com
business-api.tiktok.com
log.byteoversea.com

 **Yahoo:**
udc.yahoo.com
udcm.yahoo.com
adtech.yahooinc.com

**Apple:**
advertising.apple.com
api-adservices.apple.com
books-analytics-events.apple.com

**Realme:**
bdapi-ads.realmemobile.com
bdapi-in-ads.realmemobile.com

**OnePlus:**
click.oneplus.cn

**Oppo:**
ck.ads.oppomobile.com

**Xiaomi:**
data.mistat.xiaomi.com
data.mistat.*.xiaomi.com (data.mistat.intl.xiaomi.com, data.mistat.india.xiaomi.com, data.mistat.rus.xiaomi.com...)

**Huawei:**
metrics.data.hicloud.com
metrics2.data.hicloud.com
grs.hicloud.com
logservice.hicloud.com
logservice1.hicloud.com
logbak.hicloud.com

**Samsung:**
analytics-api.samsunghealthcn.com

**Comment by StevenBlack** [comment]
Thank you for this Artem @devlysh but I decline this inclusion request.

Closing.

**Comment by devlysh** [comment]
I see. Alright. I guess you know better.
May I ask what was the reason of denial?
