### ISSUE TITLE
Google Pixel Ads filtering

### ISSUE THREAD

**Issue by robertjamesm** [StevenBlack/hosts#2407]
Google Pixels Ads are filtering through.

**Comment by StevenBlack** [comment]
Thank you for this Robert @robertjamesm.

This issue, as written, contains no actionable information.

Closing.

**Comment by robertjamesm** [comment]
What do you mean no actionable information? This issue is not resolved. Display ADs from google are not being blocked by your list. I’m not sure what else you want me to explain?
