### ISSUE TITLE
phone adware: santknow

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#2408]
Similar to the one described in the previous issue. I think there is some adware on the phone that's loading a variety of ad websites. 

ad link: https://santknow .com/fashion/0809/873938047014535168.html

screenshot: https://files.catbox.moe/1ni0hl.jpg

No results on google for this site other than the site itself.

**Comment by iam-py-test** [comment]
Would you mind passing these onto the person who's device it is:
- https://malwaretips.com/blogs/how-to-reset-chrome-browser-settings-on-android-phone/
- https://support.google.com/accounts/answer/9924802?co=GENIE.Platform%3DAndroid

**Comment by StevenBlack** [comment]
Thank you for this Devon @hyder365.

What "previous issue" are you referring-to here?

**Comment by iam-py-test** [comment]
https://github.com/StevenBlack/hosts/issues/2403 I assume?
