### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by KnownStormChaser** [StevenBlack/hosts#2409]
jj203.equitablebank.ca is being blocked, but is a legitimate link used for a banking app. Because it is blocked, the app won't work properly.

**Comment by StevenBlack** [comment]
@KnownStormChaser thank you for this.

We presently don't list the domain `jj203.equitablebank.ca`.

Closing.

**Comment by KnownStormChaser** [comment]
Forgot to mention that the link actually redirects to h-equitablebank.online-metrix.net, which in turn is also blocked by the filter.

**Comment by StevenBlack** [comment]
Thanks Sebastian @KnownStormChaser.

We don't list the domain `h-equitablebank.online-metrix.net` either.

Whatever it is you are experiencing, this is not going to change here.  Please report this to your bank, and suggest the security industry is aware of their tracking, and their app should still work if their tracking activity is blocked.

In other words, the bank's app should still work even if their dodgy affiliations outside their main line of business are broken.
