### ISSUE TITLE
Blocking mybbc-analytics.files.bbci.co.uk breaks BritBox for Chromecast

### ISSUE THREAD

**Issue by ineffyble** [StevenBlack/hosts#2410]
Not sure if this is something suitable to address here, but I've discovered that the inclusion of `mybbc-analytics.files.bbci.co.uk` on the blocklists breaks the BritBox app for Google Chromecast.

Unlike with the Android (and presumably other) apps, which ignore the failure, the Chromecast app will spin for 30s and then show "something went wrong" unless this host is whitelisted.

Looks like I'm not the first to discover this: https://www.reddit.com/r/pihole/comments/nlhu3y/bbc_iplayer_connection_error_could_this_be_caused/

**Comment by StevenBlack** [comment]
Thank you for this Effy @ineffyble.

This domain is blocked by several of our list curators.  

So this won't change. 

This appears to be an issue with BritBox.

Closing.
