### ISSUE TITLE
Google Display ADs from google are not being blocked.

### ISSUE THREAD

**Issue by robertjamesm** [StevenBlack/hosts#2412]
Google Display ADs from google are no longer being blocked.

**Comment by iam-py-test** [comment]
Do you see these on Google search, or another website? What browser/OS are you using?
Can you share a screenshot and a URL where these ads appear?
Thanks

**Comment by StevenBlack** [comment]
This is a duplicate of #2407.

@robertjamesm you won't be posting or participating here anymore.
