### ISSUE TITLE
List block sky decoder from working. 

### ISSUE THREAD

**Issue by lollo03** [StevenBlack/hosts#2413]
Hi, in the list there are 2 entries related to sky:
- metrics.sky.com
- analytics.global.sky.com

Apparently, if a sky decoder can't reach these two urls it won't work. I fixed whitelisting *.sky.com

**Comment by StevenBlack** [comment]
Thank you for this Lorenzo @lollo03.

This appears to be an issue with Sky who make their trackers critical to their function.  This is their choice. We're here to block trackers, not help Sky to track.

Closing.

**Comment by lollo03** [comment]
Ok, I see your point but I think that in this case allowing these 2 tracker can be beneficial.

If you have a sky decoder you are forced to whitelist these 2 tracker... not advanced user (who maybe don't know how to whitelist urls) will choose to don't use the list in the first place just for this problem.

Also, these trackers can only really work if you have a sky decoder in your house...
