### ISSUE TITLE
Compatibility with maza

### ISSUE THREAD

**Issue by sbstn87** [StevenBlack/hosts#2415]
Hi,

regarding this issue at maza repositury:
https://github.com/tanrax/maza-ad-blocking/issues/20

Can something be done on the hosts file side to help resolve this?

**Comment by sbstn87** [comment]
Oh, I have just noticed that you have already posted a solution on the maza's GitHub. Once again thank you very much for your input!

**Comment by StevenBlack** [comment]
@sbstn87 I am closing this issue now since it's up to Maza to decide if they want to support raw hosts files.

**TAKE NOTE** that you can use the `--skipstatichosts` flag to generate hosts files in this repo that don't include the header hosts in question here.
