### ISSUE TITLE
[porn] False positive, libgen.is.

### ISSUE THREAD

**Issue by mabequinho** [StevenBlack/hosts#2418]
Please consider removing libgen links from porn list.

**Comment by mabequinho** [comment]
https://github.com/StevenBlack/hosts/issues/2337

**Comment by StevenBlack** [comment]
Thank you    Lucio @mabequinho.

Ping @sinfonietta, looks like all of these could be false positives, the first one looks invalid:

```
9546:0.0.0.0 libgen.i
9547:0.0.0.0 libgen.is
9548:0.0.0.0 libgen.onl
```

**Comment by StevenBlack** [comment]
Closing!
