### ISSUE TITLE
Unable to access `https://secure.gaug.es`

### ISSUE THREAD

**Issue by NetOperatorWibby** [StevenBlack/hosts#242]
This isn't such a big deal because I can access it just fine on my phone, but I'd like to be able to access it on my computer. No idea what it's using that's being blocked. There's no mention of `gaug.es` in this repo so it must be a third-party script.

Oh well.

**Comment by NetOperatorWibby** [comment]
What the hell, I searched this repo and nothing came up. That's weird as hell, maybe GitHub can't handle it? Anyhoo, I am using Gauges for my site analytics.

**Comment by kronflux** [comment]
Yeah you can't use the search repository function for the hosts files, they are too large and don't get indexed fully.
Next time view raw and search with your browser :)
