### ISSUE TITLE
False Positive KEPW.org 

### ISSUE THREAD

**Issue by agrovista** [StevenBlack/hosts#2423]
KEPW is a Low Power public radio station in Eugene Oregon, not an advertising network

**Comment by StevenBlack** [comment]
Thank you for this @agrovista.

The domain `kepw.org` comes to us from upsteam.

Please make this request as an issue at the following URL: https://github.com/FiltersHeroes/KADhosts/issues

Ping @krystian3w thank you!

**Comment by agrovista** [comment]
Will do Thank You !

**Comment by krystian3w** [comment]
Page was infected: https://github.com/FiltersHeroes/KADhosts/issues/56

**Comment by StevenBlack** [comment]
Thank you @krystian3w.

Closing.
