### ISSUE TITLE
Add to Porn List

### ISSUE THREAD

**Issue by g1t3m** [StevenBlack/hosts#2424]
Hello @StevenBlack and @Sinfonietta,

Here is an additional list of porn sites to be added to the filter:

Fapdungeon.com
packsvids.com
sinsofteens.com
booru.plus
https://vipreddit.blogspot.com/?m=1
Mangatoto.com
https://oldfashionbootyblog.blogspot.com/?m=1
exposedtostrangers.com
javsky.tv
xxx-sexhub.com
porngirlhd.net
world18hd.com
https://nerdyslutsch.blogspot.com/?m=0
3movs.com
hotxteens.net
videohd18.com
hentaicom.com

Thank you for your continued work on this list!

**Comment by StevenBlack** [comment]
Thank you for this @g1t3m.

Here you provide 17 domains, didn't bother to clean up the protocol or the path and query parameters, thus creating work.  I cleaned that up only to find, we already carry 7 of those 17 domains.

Please don't post minimum-effort, zero-check, drive-by issues here.  We have contributing repositories that specialize in listing porn.  Please submit there.

Closing.
