### ISSUE TITLE
[Help Wanted] Filtering comments out of hostfiles in Linux

### ISSUE THREAD

**Issue by mueller-ma** [StevenBlack/hosts#243]
Hi,

I'm using a hostfile from this project on my local dns server to block ads. However I have some problems in my script with inline comments:

```
# copy dns to all_domains (tempfile)
cat StevenBlack-hosts | grep '^0.0.0.0' | egrep -v '^$|#|127.0.0.1|255.255.255.255|::1' | cut -d " " -f 2 >> $all_domains
# include local blacklist and hostfiles from other sources
cat $manuell_blacklist >> $all_domains

# remove comments and empty lines
cat $all_domains | egrep -v '^$|#' | sort | uniq  > $all_domains_uniq
# dns entries should be resolved with zone containing 0.0.0.0
cat $all_domains_uniq | sed -r 's/(.*)/zone "\1" {type master; file "\/etc\/bind\/db.blocked";};/' > $zonefile
```

This will remove entries like
`foo.bar # This may interefere with example.com`

**Comment by StevenBlack** [comment]
@mueller-ma nice!   Thanks for this.

Probably should make a flag for this, and make what you do the default.

**Comment by mueller-ma** [comment]
I can provide the full script, maybe to the wiki page. But there are some lines very quick and dirty

**Comment by mueller-ma** [comment]
https://github.com/StevenBlack/hosts/wiki/Bind-DNS-Server
https://github.com/mueller-ma/block-ads-via-dns

**Comment by StevenBlack** [comment]
Hey @mueller-ma this is great!

**Comment by mueller-ma** [comment]
@StevenBlack It still has the limitation I mentioned in the first post

**Comment by StevenBlack** [comment]
I'll try to change the python script today.

**Comment by StevenBlack** [comment]
Done!  Closing!

**Comment by StevenBlack** [comment]
Reopening this because I want to document and link to @mueller-ma's repo.
