### ISSUE TITLE
Add malware site 1piecemanga

### ISSUE THREAD

**Issue by LeoniePhiline** [StevenBlack/hosts#2436]
hxxps://w61.1piecemanga.com/

**Comment by StevenBlack** [comment]
Thank you for this Leonie @LeoniePhiline.

Yup.  Also invoked from here the following domains too:

```
fbet.com
stemboastfulrattle.com
onwardrespirationcommandment.com
```

**Comment by StevenBlack** [comment]
@LeoniePhiline these are added in commit e998360d and will be live in the next release.  Thanks!

Closing!

**Comment by LeoniePhiline** [comment]
Thanks so much for maintaining this list!
