### ISSUE TITLE
Addition to Porn List

### ISSUE THREAD

**Issue by JonathanSpalding** [StevenBlack/hosts#2439]
Add the following url to porn list please:

camera.com

**Comment by StevenBlack** [comment]
Thank you for this Jon @JonathanSpalding.

Ping @sinfonietta for inclusion in the porn list.

**Comment by Sinfonietta** [comment]
@StevenBlack I have added camera.com.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta.  Closing.
