### ISSUE TITLE
new list hpHosts

### ISSUE THREAD

**Issue by proxenus** [StevenBlack/hosts#244]
http://hosts-file.net/

Just wanted to mention this list if you'd like to review adding it. I've added it locally myself, here is my update.json:

{
    "name": "hpHosts",
    "description": "hpHosts is a community managed and maintained hosts file.",
    "homeurl": "http://hosts-file.net/",
    "frequency": "weekly",
    "issues": "http://mysteryfcm.co.uk/?mode=Contact",
    "url": "https://hosts-file.net/download/hosts.txt"
}

**Comment by StevenBlack** [comment]
Hi @proxenus thank you for the suggestion.

We've looked at [hosts-file.net](http://hosts-file.net/) before.  Back in those days hosts-files.net had 300,000+ hosts.  Our findings were:

1. Hosts numbers on the order of 10^6 makes some systems, notably WIndows and low-end Android, almost unusable.
2. At that time I felt there was not nearly enough curation activity for a hosts file that size.

[Here are issues related to that discussion](https://github.com/StevenBlack/hosts/search?q=hphosts&type=Issues&utf8=%E2%9C%93).

Closing.

**Comment by FadeMind** [comment]
@proxenus see: 
https://github.com/FadeMind/hosts.extras/tree/master/hpHosts
https://github.com/FadeMind/hosts.extras/tree/master/hpHosts.partial

CC @StevenBlack 

And If you want using hosts file with HpHosts merged see my external repo: https://github.com/FadeMind/hosts.extended

Customize WHITELIST before using (lots of ad tracking website is blocked here.

**Comment by Gitoffthelawn** [comment]
http://hosts-file.net/ad_servers.txt now contains only 48K hosts, and is included by default with AdAway.

Should it be included?

**Comment by StevenBlack** [comment]
Gi @Gitoffthelawn!

DO we know approximately how often this source is updated?

**Comment by Gitoffthelawn** [comment]
Hi! Steven :)

IIRC, I've seen it updated every 2-4 weeks.

It is included in AdAway by default, as indicated here: https://github.com/AdAway/AdAway/wiki/HostsSources

**Comment by Gitoffthelawn** [comment]
@StevenBlack 

Real interested in your opinion on this.

AdAway is very strict on what they include, and they include http://hosts-file.net/ad_servers.txt as one of their select few preset hosts lists.

At the same time, I notice that it does not have too much overlap with other lists.  This can be a very good thing, or a bad thing.  Good for more coverage, bad if blocks too much.

I've taken a fairly close look at it, and the entries look good.  But, of course,, I did not research all 48K entries! :)

What are your thoughts?
