### ISSUE TITLE
`127.0.0.1	local` breaks mDNS 

### ISSUE THREAD

**Issue by unbeatable-101** [StevenBlack/hosts#2449]
Hello, I’ve been using your base host list in the AdGuard DNS blocking app on iOS and noticed that mDNS (e.g. being able to connect to my Mac and access files from my phone using `computer-name.local`) hasn’t been working ever since I started using this list since any request to a .local domain returns the ip address `127.0.0.1`, as opposed to the private ip of the desired computer. Disabling the list solves the problem. Is there a reason for the host file to be set up like this?

**Comment by StevenBlack** [comment]
Thank you for this question @unbeatable-101.

The `127.0.0.1 local` entry does not match, never did match, and shou;ld not match `.local` domain addresses.

In your scenario, this would appear to be a bug in AdGuard DNS.

The `127.0.0.1 local` hosts entry is present in some operating systems' hosts files.
