### ISSUE TITLE
Idea for another recipe

### ISSUE THREAD

**Issue by lizucarulz** [StevenBlack/hosts#245]
It would be great if we could download a hosts file containing only fakenews + gambling + porn + social. Why? We could easily whitelist any site in our browser (thus supporting it) if we use _adblocking_ **only** at browser level. I saw there are scripts, hosts files containing only fakenews/gambling etc. but I think another row in your table with my suggested recipe is a solution more comfortable for many users. Thank you for your work.

**Comment by funilrys** [comment]
@lizucarulz without unified hosts?

**Comment by lizucarulz** [comment]
Yes.

**Comment by StevenBlack** [comment]
Hi @lizucarulz that's easy!

If you go to the [home page of the full-bird hosts file](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-gambling-porn-social/readme.md) all the sources (including extensions) are listed, including links to the raw data.

I suppose this could be made more clear  😄 

For starters the repo home page features the base list which has no extensions.

Second, in the pages for the extended hosts files, it's not clear which source is for which facet of extension.

I'll fix that.

**Comment by lizucarulz** [comment]
I don't think I made myself understood. I use fakenews.txt, gambling.txt, porn.txt. I **don't** use unified hosts (aka ad+malware). Is there a public link for a file that is **strictly** fakenews.txt + gambling.txt + porn.txt?

**Comment by StevenBlack** [comment]
Not presently, no.

**Comment by funilrys** [comment]
I don't think it's a good idea at all @StevenBlack @lizucarulz ...
You should create your own `myhosts` with a frequential cron which `wget` and merge the files into it.

In linux you can - with the following - append the content of a file to another

```
cat fileDownloaded.txt >> myhosts
```

**Comment by lizucarulz** [comment]
We **already** have different combinations of unified hosts and gambling, fakenews, publicly available and downloadable.

Plus, many sites with valuable content ask you to disable any adblocker you may have. I want to disable adblocking in my browser for any site, but still be able to use fakenews/gambling/porn lists.

I bet there are many people willing to use Steven Black's hosts file but they can't because their favorite sites ask them to disable ad blocking. And not all people are used to scripting.
