### ISSUE TITLE
False positive superlogout.github.io

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [StevenBlack/hosts#2451]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><title></title><meta name="generator" content="DB Browser for SQLite"><meta name="date" content="YYYY-09-DDT01:19:05.472"><style type="text/css">br{mso-data-placement:same-cell;}</style></head><body>

0.0.0.0 superlogout.github.io
--

</body></html> False positive

**Comment by StevenBlack** [comment]
Thank you for this @HydraDragonAntivirus this is fixed in commit 
6cc3bec and will be live in the next release.

Closing.
