### ISSUE TITLE
False positive: cdn[-eu].dynamicyield.com

### ISSUE THREAD

**Issue by makuhlmann** [StevenBlack/hosts#2452]
These two entries in the blocklist can cause some web pages to malfunction:

0.0.0.0 cdn.dynamicyield.com
0.0.0.0 cdn-eu.dynamicyield.com

Example:
https://nl.nbb.com/nl/

![Screenshot 2023-09-20 224136](https://github.com/StevenBlack/hosts/assets/19255462/557dd931-1fed-41a2-accb-d5f5bc833814)
![Screenshot 2023-09-20 224225](https://github.com/StevenBlack/hosts/assets/19255462/511458ab-3560-4aef-857b-09f04da78b56)

**Comment by MrRawes** [comment]
those domains are from adaway

**Comment by makuhlmann** [comment]
Adaway has no active maintainer since October 2022
https://github.com/AdAway/adaway.github.io/issues/357

**Comment by StevenBlack** [comment]
Thank you for this @makuhlmann.

Subdomains of `dynamicyield.com` appear in several of our upstream inputs and, for this reason, this isn't going to change.

I think it's better to advise `nl.nbb.com` that their website's delivery is critically dependent on a known tracking organization, and their website should still work if the tracking service doesn't respond.

In other words, their bug.

Closing.
