### ISSUE TITLE
False positive: analytics.twitter.com

### ISSUE THREAD

**Issue by whotheff** [StevenBlack/hosts#2454]
I tried to view my Twitter (now X) profile statistics, but i got blocked by StevenBlack_ADs. Please define blocking rule which blocks the tracking, but allows viewing the statistics which reside on analytics.twitter.com.

**Comment by StevenBlack** [comment]
Hello @whotheff thank you for this.

This isn't going to change. The whole point of this project is to fight trackers such as this.

Closing.
