### ISSUE TITLE
Bug in host file

### ISSUE THREAD

**Issue by ar51an** [StevenBlack/hosts#2455]
Please remove the last dot in the below entry from the "Unified hosts + porn" hosts file. It failed the unbound converted blocklist. This entry originated from the porn hosts file and propagated into all unified hosts with porn.

`0.0.0.0 cast.porngo.com.`

https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts

**Comment by StevenBlack** [comment]
Thank you @ar51an this is fixed in commit 38e53dd6 and will be live in the next release.
