### ISSUE TITLE
False ban vk.com

### ISSUE THREAD

**Issue by KS1VA** [StevenBlack/hosts#2457]
False ban vk.com and vkcache.com

**Comment by StevenBlack** [comment]
Thank you @KS1VA.

Ping @sinfonietta, the domain `vk.com` does not appear to be porn anymore.

**Comment by wachawo** [comment]
I would not trust the opinion of a person whose nickname in Russian means "spy's identity card." xDDD

**Comment by Sinfonietta** [comment]
@StevenBlack this is done.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta.  Closing.

**Comment by akavi1** [comment]
so vk.com is technically just a Russian social media site, but there is a LOT of porn hosted on the site. I think it would be best to either block vk.com entirely or if possible block only the videos on vk.com with something like vk.com/*video-* where * are wildcards. I've noticed that the videos have multiple different URLs but they all contain "videos-" somewhere.
