### ISSUE TITLE
Add www.relax-porn.com to the porn list

### ISSUE THREAD

**Issue by jamieburchell** [StevenBlack/hosts#2459]
Noticed this wasn't blocked while testing the pornlist

**Comment by jobbb2** [comment]
its always blocked from StevenBlack pronlist !

**Comment by StevenBlack** [comment]
Hi @jamieburchell thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.

**Comment by jamieburchell** [comment]
How would I know which list to submit to? Is there a particular list for this type of content?
