### ISSUE TITLE
Merging my own list?

### ISSUE THREAD

**Issue by mitchellkrogza** [StevenBlack/hosts#246]
Hi Steven

I have quite an extensive list of bad referrer domains which I would like to send a PR for and contribute to this project. Does your generator take care of handling duplicates that may already be on on other lists in the repo and do you have a general PR template?

**Comment by StevenBlack** [comment]
Hi @mitchellkrogza 

Yes, the process de-dupes.

Ideally you would place this list in your own repo, and the file amalgamation process fetches your latest version whenever it's invoked.  This way you can continue to curate this list.  Ongoing curation is a key aspect of all this...

**Comment by mitchellkrogza** [comment]
Thanks for the reply Stephen, I have a large list that is curated and added to almost daily.  Do I just create a new folder in /hosts/data with just a composer.json file and specify in that file where my plain text list file resides? Does you script then take care of creating the hosts file in my folder for me ? or must I point it to a text file that's already in the correct format?

**Comment by mitchellkrogza** [comment]
Hi Steven, sent a PR, hope I got it right 😄 
https://github.com/StevenBlack/hosts/pull/248
