### ISSUE TITLE
Remove non-domain 0.0.0.0 from the list

### ISSUE THREAD

**Issue by as-spaargaren** [StevenBlack/hosts#2460]
PiHole Update Gravity log:

[i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 135875 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"

**Comment by StevenBlack** [comment]
That line was introduced in this commit...

* https://github.com/StevenBlack/hosts/commit/71f2b8ee3f538a17e273ba3aca4f43c599355e3c

... on April 13 2017.

Tomas @FadeMind do you remember this?  I'm thinking of removing this line.

```
0.0.0.0 0.0.0.0
```

**Comment by FadeMind** [comment]
Report bug to pihole devs. This line shouldn't be removed. Otherwise Windows network tools will not work properly. @StevenBlack  your call.

**Comment by FadeMind** [comment]
See also https://www.howtogeek.com/225487/what-is-the-difference-between-127.0.0.1-and-0.0.0.0/

**Comment by StevenBlack** [comment]
Thanks for this Sander @as-spaargaren.

After review, this isn't going to change.  Just ignore that belch from PiHole; it's harmless.

Thank you for the assist Tomas @FadeMind!

Closing.
