### ISSUE TITLE
openstreetmap.org tiles are blocked

### ISSUE THREAD

**Issue by pedjas** [StevenBlack/hosts#2462]
I use only https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts ad list in my Pi-Hole.

When I try to access openstreetmap.org, site loads but standard map tiles do not load. 

Pi-Hole reports 

tile.openstreetmap.org
(blocked dualstack.n.sni.global.fastly.net)
Blocked (regex blacklist, CNAME)

tile.openstreetmap.org should not be blocked.

**Comment by StevenBlack** [comment]
Hello @pedjas thank you for this.

We don't block the domain `tile.openstreetmap.org`, nor do we block domain `dualstack.n.sni.global.fastly.net`.  I'm unsure if we ever did.  

Closing.

**Comment by pedjas** [comment]
Why is then domain blocked? I only have this list in Pi Hole. Nothing else. I do not have this domain in custom block list.

**Comment by hagezi** [comment]
@pedjas `Blocked (regex blacklist, CNAME)` You have a RegEx rule in your personal blacklist that blocks the `fastly.net` domain.
