### ISSUE TITLE
[Feature Request] [New Category] Add a category for AI/SEO domains

### ISSUE THREAD

**Issue by cyberhardt** [StevenBlack/hosts#2464]
I had the displeasure to find some of those creepy AI-made SEO domains a few times while doing web searches. They seem to be growing in number, and are an annoyance to everyone. My suggestion is to add a new category for these SEO websites, not only to prevent whatever bad things they may do with our data but also to avoid giving them SEO score.

An example of such domain is: https://novelattractive.blogspot.com/

**Comment by StevenBlack** [comment]
Thank you for this suggestion @cyberhardt.

In order to have a new category for this, we need to have a category curator, with a track record, to maintain it.

This may be something to consider some day, but it doesn't appear to be a thing right now.

Closing.
