### ISSUE TITLE
DNS Server

### ISSUE THREAD

**Issue by Jezza-x3** [StevenBlack/hosts#247]
Is there anyway possible for a DNS server to be made with your host file? For non-root Android and iPhone users? Like these https://alternate-dns.com/ https://noad.zone/

**Comment by qutorial** [comment]
Hi there. 
My fork of this project supports dnsmasq DNS server.
https://github.com/qutorial/angryhostsfile
Like this you can build your own DNS server. Arguably it is a slightly stronger blocking.

**Comment by Jezza-x3** [comment]
I have no idea how to set up a DNS server. I would love to start one with Google Cloud Platform, but I am not sure how to go about that.

**Comment by mueller-ma** [comment]
If you want to use the DNS in your local network only you can buy a Raspberry Pi

**Comment by Jezza-x3** [comment]
I'm wanting more of a public one that's online. I can host it on GCP if possible, I just have no idea how to set it up.

**Comment by mueller-ma** [comment]
You could use openDNS, however it is not FOSS

**Comment by k0nsl** [comment]
...or you could use unbound: https://www.unbound.net/

I am using it for myself and several devices, dedicated servers and virtual private servers to block unwanted crap: https://blog.k0nsl.org/2016/08/17/blocking-malicious-sites-at-dns-level/

Mirror on GitHub: https://github.com/k0nsl/unbound

**Comment by Atavic** [comment]
OpenDNS is owned by Cisco.

**Comment by StevenBlack** [comment]
@Jezza-x3 you might like [Block ads and malware via local DNS server](https://github.com/mueller-ma/block-ads-via-dns "Block ads and malware via local DNS server") by @mueller-ma.

**Comment by Jezza-x3** [comment]
I understand. I was wanting it for when I wouldn't be on a local network. I know there is an app on the Google Play store that allows you to set a fake local VPN with a custom DNS server as you can't change the DNS server of your mobile data without root. So I thought creating a public DNS server would be awesome, but it would require money to operate and knowledge that I don't have. 

You can close this now. Thanks @StevenBlack
