### ISSUE TITLE
Additional porn domains

### ISSUE THREAD

**Issue by sussynuggetz** [StevenBlack/hosts#2471]
asianpinay.cc
bangpinay.com
epornz.com 
euttube.com
fakboi.org
fapxxx.com
floozytube.com
freecoolporn.com
hadesex.com
hqfuck.com
hqtubesearch.com
kadyotan.com
ladyboyshere.com
lootedpinay.com
moregrannies.com
nastypornvids.com
neonpussy.com
newpornsearch.com
nud8.com
oldpussy.tv
olderwomen.tv
pinayflix.me
pinayflix2.com
pinayflixtv.com
pinayflixtv.net
pinayreel.tv
porn3.tv
pornmovieshere.com
sarapbabe.com
sarapbabe.tv
sexnest.tv
sexrasta.com
shemale3.tv
shemalehere.com
shemalemap.com
trannymap.com
xbreezy.tv
xgent.com
rbreezy.xyz

**Comment by StevenBlack** [comment]
Thank you @sussynuggetz.

Ping @sinfonietta for inclusion in the porn list.

**Comment by Sinfonietta** [comment]
@StevenBlack this is added.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta.  Closing.
