### ISSUE TITLE
Porn Domains

### ISSUE THREAD

**Issue by anxiouslelimo** [StevenBlack/hosts#2474]
Request to include following porn domains

aagmaal.mom
aagmaal.motorcycles
uncutwebseries.life
aagmaal.to

**Comment by StevenBlack** [comment]
Thank you for this @anxiouslelimo.

Ping @sinfonietta for inclusion in the porn list.

**Comment by Sinfonietta** [comment]
@StevenBlack done!

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta.  Closing.
