### ISSUE TITLE
False positive: ia601500.us.archive.org

### ISSUE THREAD

**Issue by Maffsie** [StevenBlack/hosts#2476]
The unified hosts +fakenews +gambling feed includes ia601500.us.archive.org, one of the CDN hosts for the Internet Archive, which should not be blocked.

It seems to be coming from the fakenews list: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts

**Comment by krystian3w** [comment]
CERT Poland ban, I recommend spam via his form and e-mail.

https://cert.pl/kontakt/
https://cert.pl/en/contact/

Due to the fact that on the default Polish DNS it will be blocked without filtering using services other than DNS (Pi-Hole, router, AdGuard Home).

**Comment by StevenBlack** [comment]
Thank you @krystian3w.

@Maffsie this is resolved now in the latest release.  Thank you for the heads-up.

Closing.
