### ISSUE TITLE
two errors in gambling-porn list causing issues in pfsense

### ISSUE THREAD

**Issue by garyn87048** [StevenBlack/hosts#2478]
Hi -

The gambling-porn list when read into DNSBL in pfsense causes two errors at lines 54037 with text 
`local-data: "momandsons0.0.0.0 60 IN A 10.10.10.1"` and at line 12364 with text `local-data: "beeg.globa0.0.0.0 60 IN A 10.10.10.1"`

The line numbers are approximate as pfsense removes comments line and possibly does some sorting.  The problem text above matches.

Thank you!

Gary

**Comment by garyn87048** [comment]
The line numbers above are totally wrong.  I should have saved a copy of the original before I edited it.  :-)

**Comment by StevenBlack** [comment]
Thank you for this Gary @garyn87048.

Ping @sinfonietta can you please fix this as these are found in your gambling list.

**Comment by garyn87048** [comment]
@StevenBlack - done:  https://github.com/Sinfonietta/hostfiles/issues/265

**Comment by Sinfonietta** [comment]
@StevenBlack this is done!

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta.  And thank you @garyn87048. Closing.
