### ISSUE TITLE
s.dmmew.com

### ISSUE THREAD

**Issue by VanHoevenTR** [StevenBlack/hosts#2479]
I propose adding `s.dmmew.com` to the list. It's an ads deliver for an android game

![image](https://github.com/StevenBlack/hosts/assets/70694330/30da9a97-8716-4c81-b24a-0f282dc19475)

**Comment by StevenBlack** [comment]
Thank you @VanHoevenTR. This is added in commit 4a8813eb and will go live in the next release.
