### ISSUE TITLE
track.spe.schoolmessenger.com is legit site

### ISSUE THREAD

**Issue by sgrigorov** [StevenBlack/hosts#2486]
Hello, 

track.spe.schoolmessenger.com is a legitimate site and is included in email links sent by schools. 
It should not be blacklisted.

Thanks,

**Comment by StevenBlack** [comment]
Thank you for this Stan @sgrigorov.

I've said this many times.

So we're clear, there are no "legitimate" domains here.

It doesn't matter if listing a domain interferes with fundraising by the Holy Sisters relict of Mother Theresa of Calcutta. If the domain vehicles tracking, adware, or worse, it gets listed here. This project serves people who value privacy and online safety. End of story.

"Sent by schools" is not a free pass for anyone to do veiled tracking of users.

Closing.
