### ISSUE TITLE
XBox Game Pass on PC does not work with porn filter

### ISSUE THREAD

**Issue by enlightdm** [StevenBlack/hosts#2489]
When I open xbox game pass for PC application, my game library is empty, and even searching for games I already own shows no results, so Xbox is not working properly with porn filter.

If I disable the porn filter, xbox app starts working again.

Using master filter instead fixes the problem.

**Comment by enlightdm** [comment]
Adding exceptions for

v10.events.data.microsoft.com
v10.vortex-win.data.microsoft.com

Seems to work.

**Comment by enlightdm** [comment]
I have narrowed down the filter list until I found these:

0.0.0.0 azurefd.net
0.0.0.0 www.azurefd.net

It seems the porn filter (https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts) is blocking **Microsoft Azure Front Door** domain entirely.

Info on domain here:

https://www.netify.ai/resources/domains/azurefd.net

**Comment by StevenBlack** [comment]
Thank you for this Federico @enlightdm.

Ping @sinfonietta this is probably a Type I error in your list.

**Comment by Sinfonietta** [comment]
@StevenBlack I just fixed this

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and Federico @enlightdm.

This is live and online now in the latest release.

Closing.
