### ISSUE TITLE
False positive "www.blogspot.com"

### ISSUE THREAD

**Issue by Chocolate4U** [StevenBlack/hosts#2492]
`www.blogspot.com` is entirely blocked in porn list.

**Comment by StevenBlack** [comment]
Thank you for this @Chocolate4U.

We don't list the domain `blogspot.com`, nor do we list `www.blogspot.com`.  We list specific subdomains only.

Closing.

**Comment by Chocolate4U** [comment]
Thanks for reply. `www.blogspot.com` is indeed in porn hosts file, on line 24568
https://github.com/StevenBlack/hosts/blob/05cdb4d0a2161aed9e83307c3cfe5c145460862d/alternates/porn-only/hosts#L24568

**Comment by StevenBlack** [comment]
I'm sorry @Chocolate4U you're right.  I swear I checked, obviously not well.

Reopening this now.

**Comment by StevenBlack** [comment]
Thanks @Chocolate4U this is fixed in commit bc8d4dfc and will be live in the next release.

Closing.
