### ISSUE TITLE
Remove Non-Domain entry

### ISSUE THREAD

**Issue by StainlessSteele** [StevenBlack/hosts#2494]
Whenever I update my lists from this repo, I get a warning that a non domain entry for 0.0.0.0 was removed/ignored:
"  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 148940 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"
"

**Comment by iam-py-test** [comment]
I think this line is needed: https://github.com/StevenBlack/hosts/issues/2460
Thanks
