### ISSUE TITLE
Weed Out Invalid Entries?

### ISSUE THREAD

**Issue by u2n** [StevenBlack/hosts#2495]
Nice project. Any chance of cleaning out old, dead-end entries before updating? That would clearly add value to the lists.

A spot check reveals that many of the entries are no longer valid. Whether host admins pulled the plug on the undesirable sites or the bad actors moved along voluntarily, there's nothing to block at these URLs.

Of course there is some risk, I suppose, that a previously-removed entry could become active again, but that seems quite unlikely.

Apologies if this has been suggested and resolved before.

**Comment by StevenBlack** [comment]
Thank you for thus @u2n.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

This request should be addressed to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Bit it's not "quite unlikely" that sleepers exist. That's literally how many of the biggest malware events of the past few years pulled it off. It's a huge threat vector.

Closing.
