### ISSUE TITLE
What methodology is used to determine fakenews?

### ISSUE THREAD

**Issue by mark-styx** [StevenBlack/hosts#2496]
@rodrigopolo thank you for that quote from air.tv.

If you follow the link to the [Breitbart News English Wikipedia article](https://en.wikipedia.org/wiki/Breitbart_News) I posted for you, take note that the article is extensively backed by citations.

Is fake news a judgment call?  Absolutely.  However one has to draw the line somewhere.  I personally agree with @marktron, who is the arbiter here.  In my view, it's not even a close-call in this instance.

I'm gonna lock this thread now because I have a limited capacity for bullshit.

_Originally posted by @StevenBlack in https://github.com/StevenBlack/hosts/discussions/1713#discussioncomment-1026520_

First, let me say that I am very grateful of this work on balance.

However, I browsed through the list of blocked content and a large number of the blocked sites are local news organizations and the ones I visited appear to be quite legitimate and not obviously ideologically driven. I think it is perfectly reasonable to ask what qualifies a source as 'fakenews'? Frankly, I don't think much of a judgement call is necessary to determine if something is fake. The question should be, 'Does the outlet present provably fake information as fact with no corrections?' rather than 'Does the outlet present information from a perspective that is incompatible with my own?'. The former is honest while the latter is intended to reinforce personal bias. Your baseless dismissal of the concerns from @rodrigopolo suggests that the lists are ideologically driven rather than fact-based and that's incredibly unsettling. I don't think 'my sources are better than yours based on these other sources', or 'you are basic and your ideological framework is wrong because I disagree with it' are a legitimate basis for such discrimination.

From my perspective, there should be either:
1. A well-documented and consistently applied criteria that qualifies news sources as legitimate or not; Such as "Does the site clearly label pieces as opinions or disguise them as fact?" and "Does the site attempt to gain legitimacy using the nameplate of a well known publication?" (a lot of the .news domains on the blocklist appropriately fit this bill). This enables transparency and for lists to become more refined and higher quality through democratized discourse.
2. An honest disclaimer of the ideological bias that serve as the foundation for how the list was generated. This circumvents legitimate questions like: Why 'The Huffington Post of the Right', as described by a left wing organization, is blocked but not the actual 'Huffington Post'?

Anything short of this is dishonest and intentionally manipulative. Further, since many of the blocked publications are local news organizations, this disproportionately damages small local  publications with no recourse who have no idea they're the target of a widespread block list for some arbitrary and undocumented offense that could very well have been legitimate reporting. With that being said, its perfectly fine to have ideologically or politically driven blocklists, but the people who are coming here looking for quality lists should be aware of the criteria the domains were evaluated against without having to go through it line by line.

**Comment by StevenBlack** [comment]
> Anything short of this is dishonest and intentionally manipulative. 

Thank you for this Mark @mark-styx.

So we are clear.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated Fake News sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.

**Comment by rodrigopolo** [comment]
@mark-styx I don't know if you watched a BBC interview to Elon Musk, where he pointed out how that news network engaged in promoting fake news, an he also expressed concerns on how Wikipedia is political and ideological driven network, at the end, the main issue is honesty, being clear and factual on what type of content applies into certain category and to describe as clear as possible that category, anything else is extra. Thank you for your review on this issue.

**Comment by iam-py-test** [comment]
> Elon Musk

With all due respect, Elon Musk is not a reliable source of information<sup>i.e. [[1]](https://www.theatlantic.com/ideas/archive/2023/09/musk-antisemitism-anti-defamation-league-twitter/675235/)</sup>

**Comment by rodrigopolo** [comment]
@iam-py-test With all due respect, no one is, including the citations you provided, it is engaging in the typical "he says, she says", that is why everyone has to rely on verifying the facts in order to avoid an ad hominem fallacy ¯\_(ツ)_/¯
