### ISSUE TITLE
beaconsX.gvt2.com

### ISSUE THREAD

**Issue by KommX** [StevenBlack/hosts#2499]
I can see that

- beacons.gcp.gvt2.com
- beacons.gvt2.com

are already being blocked.

In my logs I can see requests to

- beacons5.gvt2.com
- beacons4.gvt2.com
- beacons3.gvt2.com
- beacons2.gvt2.com

which aren't blocked yet. I guess, it would make sense to add these as well, wouldn't it?

**Comment by StevenBlack** [comment]
Hi @KommX thank you for this.

I just added these in commit d7be1222 and they will be live in the next release.

Closing.

**Comment by KommX** [comment]
@StevenBlack 
I noticed, that there is also 'beacons5.gvt3.com' which I haven't included in my initial post.
Should I open a new issue for that additional domain?
