### ISSUE TITLE
Just add few sources

### ISSUE THREAD

**Issue by qwertygc** [StevenBlack/hosts#25]
http://sourceforge.net/projects/adzhosts/

http://rlwpx.free.fr/WPFF/hosts.htm

http://winhelp2002.mvps.org/hosts.htm
Regards

**Comment by StevenBlack** [comment]
@qwertygc on a déja http://winhelp2002.mvps.org/hosts.htm

Pour les deux autres, je ne suis pas confortable avec le format.  Plusieurs domaines sur la même ligne est difficile, même impossible, à évaluer.

Aussi, quand on parle de centaines de milliers de domaines, où sont les limites pratiques pour l'entretient?

**Comment by qwertygc** [comment]
Bonne question. Juste une question, vous vous basez aussi sur des listes d'adblocker ?

**Comment by StevenBlack** [comment]
@qwertygc voici la liste; c'est un répertoire dans le repo:
    https://github.com/StevenBlack/hosts/tree/master/data

**Comment by qwertygc** [comment]
D'accord. Je vais essayer de vous proposer quelques uns de plus.
