### ISSUE TITLE
Is '0.0.0.0' or '127.0.0.1' better in DNSMASQ to block the domain?

### ISSUE THREAD

**Issue by WFANG12719** [StevenBlack/hosts#2510]
Hi, all, 
Just curious about: 
 For block purpose, some people tend to mark the domain as 127.0.0.1 and some mark as 0.0.0.0. 
 Do you know which entry is better/faster for DNSMASQ to run efficiently?

**Comment by StevenBlack** [comment]
Hello @WFANG12719 thank you for this question.

Last time I tested this, `0.0.0.0` is faster in all cases. I can't comment on specific use cases, but in a hosts file context, `0.0.0.0` is better speed-wise.

Closing.
