### ISSUE TITLE
Cloudflare test sites for malware and adult content

### ISSUE THREAD

**Issue by be-rock** [StevenBlack/hosts#2511]
Hi,

Cloudflare DNS has 2 test sites setup that can be used to verify DNS Resolver Malware, Adult content respectively. Can we please get these added to the block list?

https://malware.testcategory.com/
https://nudity.testcategory.com/

Source: https://developers.cloudflare.com/1.1.1.1/setup#test-1111-for-families

Thank you.

**Comment by iam-py-test** [comment]
In my opinion, it would be better to have a dedicated test domain for StevenBlack than adding test domains for specific services.
Thanks

**Comment by StevenBlack** [comment]
Thank you for this @be-rock.

I don't understand why we would want to list those two domains. Can you please clarify?  This gets us what, exactly?

**Comment by iam-py-test** [comment]
I guess the OP wants a way to test if this list is functioning (or rather whatever software they are using this list with).
Thanks

**Comment by be-rock** [comment]
Yes, exactly, this would give us the opportunity to test that DNS blocking is working as expected through services such as Pi-Hole with network devices that don't have utilities like nslookup in place. For example, on children's devices, where if some domains did resolve unexpectedly, we would not actually want it to render on a device. 
The 2 provided cloudflare domains would give us an opportunity to test blocking without risking exposure of adult content on children's devices.
Thank you for the consideration and for the great project.

**Comment by broken-software** [comment]
Since this is your own use case, why don't you add to your blacklist file and generate your own host?

**Comment by be-rock** [comment]
I am happy to do that @broken-software, thanks. Feel free to close this issue then if the consensus is this would not be valuable to include in the hosts lists.

**Comment by StevenBlack** [comment]
Thanks @be-rock, user @broken-software has the best take, I think. If this is something you need, then it's wide-open to for you to do that.  But community-wide, I don't many benefits.

Closing. Thank you again for the suggestion.
