### ISSUE TITLE
Seriously ? Why blocking cdn.jsdelivr.net with master/hosts

### ISSUE THREAD

**Issue by agencetelecom** [StevenBlack/hosts#2518]
cdn.jsdelivr.net is not accessible anymore from 
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by trailmax** [comment]
Yes, indeed! I thought I was going mad - half of the web-pages stopped working, including Stackoverlow.

**Comment by devtimi** [comment]
If this affected you please [report the npm package as malware](https://www.npmjs.com/support?inquire=security&security-inquire=malware&package=prebid-universal-creative&version=1.16.0). If npm allows this behavior they become complicit in the abuse of their platform, and jsdelivr legitimately becomes an ad server worth blocking.

**Comment by StevenBlack** [comment]
As others have said, this is fixed two days ago.

Closing.
