### ISSUE TITLE
cdn.cookielaw.org blocks legitimate websites like PG&E from working

### ISSUE THREAD

**Issue by misosoup7** [StevenBlack/hosts#2519]
I haven't logged in to my PG&E account in a while but when I did today, I found that it doesn't work without downloading a javascript from cdn.cookielaw.org to generate the message about accepting cookies. This was blocked in March of 2023, can we remove this value. I'm also pretty sure cookielaw.org doesn't serve ads.

**Comment by StevenBlack** [comment]
This has been discussed many times before, and this is not gonna change.

Closing.
