### ISSUE TITLE
Mysterious inclusion of addons.mozilla.org

### ISSUE THREAD

**Issue by zymase** [StevenBlack/hosts#252]
Latest update of _Unified hosts file with social extensions_ includes **_addons.mozilla.org_**

First, amazing to find _addons.mozilla.org_ in the list, so I checked each and every Raw hosts and found no entry of _addons.mozilla.org_

The file including _addons.mozilla.org_ : https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts

The Raw hosts checked individually from : https://github.com/StevenBlack/hosts/blob/master/alternates/social/readme.md

Who wouldn't be,
1- Surprised to find _addons.mozilla.org_ in a HOSTS file,
2- Have an entry included in a unified HOSTS file but not in either the sources of the concatenation?

I really appreciate this work, but I have to mention my surprise and of course my eager to understand how and why this oddity is possible. Thanks.

**Comment by funilrys** [comment]
WoW don't use firefox but I'm surprised too 😮

**Comment by zymase** [comment]
@funilrys , the browser has nothing to do with a HOSTS file!

**Comment by zymase** [comment]
It seems the _addons.mozilla.org entry_ comes from the  _Mitchell Krog's - Badd Boyz Hosts_ list included in the _Unified hosts file with social extensions_  installed this very morning.

In this _Unified hosts file with social extensions_ , at https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts, addons.mozilla.org appears under the _Mitchell Krog's - Badd Boyz Hosts_ source entry, and dated **Wed Feb 22 15:59:54 SAST 2017**

Latest list of _Mitchell Krog's - Badd Boyz Hosts_ available, raw, at https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts is dated **Thu Feb 23 11:51:02 SAST 2017**

This may be an explanation though I don't think so because I didn't encounter the issue until this morning whilst I've been using Unified hosts file with social extensions for over a week, and updates replace and do not add, here.

**Comment by thedummy06** [comment]
I found it too, I just commented it out, but is eerie, I was actually gonna report it here. You beat me to it. Cheers!

**Comment by zymase** [comment]
@thedummy06 , social entries add to others, they are not exclusive of other lists.

**Comment by funilrys** [comment]
Reference: #248

**Comment by mitchellkrogza** [comment]
Sorry guys, copy and paste error. Was fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/96aa234e149e00365fb12e2531dcf21c9034dc7e yesterday.

**Comment by zymase** [comment]
@funilrys thanks for the link/info
@mitchellkrogza OK, thanks for acknowledging. The purpose was not to accuse/condemn but to understand. Cold case!

**Comment by mitchellkrogza** [comment]
No problem at all, merging my list has also quickly helped me pick up some errors and problems. All for the better as I use a single list for multiple projects and it needs to be clean.

**Comment by StevenBlack** [comment]
Thanks everybody!  The latest sources are pushed to master here.

**Comment by StevenBlack** [comment]
Closing.

**Comment by mitchellkrogza** [comment]
Hi Steven just pushed a big update with 551 deleted / expired domains on https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/e4c822e9ca6ea6df7d3ea01450ad693a045fba01
