### ISSUE TITLE
Blocking jQuery url preventing sites from loading.

### ISSUE THREAD

**Issue by Raptr24** [StevenBlack/hosts#2520]
Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
  ajax.googleapis.com

This is preventing jQuery from loading on any site that does not use a local copy.

**Comment by stevietv** [comment]
this is a dupe of #2516

**Comment by StevenBlack** [comment]
This is fixed two days ago.

Closing.
