### ISSUE TITLE
Instagram does not load 

### ISSUE THREAD

**Issue by inbalboa** [StevenBlack/hosts#2527]
www.instagram.com in https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts

Seriously?

**Comment by StevenBlack** [comment]
Thank you for this Serhiy @inbalboa.

We do not list the domain `www.instagram.com` in that list.

Closing.

**Comment by TwisX** [comment]
If you open the file and do a search, it's definitely there! I use this list and it's there as well: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts

Had to whitelist `www.instagram.com` in pfBlockerNG.

**Comment by StevenBlack** [comment]
@TwisX and @inbalboa you are right and I am mistaken.

I am reopening this issue.

The issue is upstream. Ping @sinfonietta — can you please review the inclusion of domain `www.instagram.com` in the porn list? Thanks.

**Comment by Sinfonietta** [comment]
@StevenBlack I have just merged a PR that removes this.

**Comment by ScriptTiger** [comment]
Just reading through the issues and this one appears to have already been resolved.
