### ISSUE TITLE
"go.sonomotors.com" and many more are not badware links, please remove the "pardot.com" blockade

### ISSUE THREAD

**Issue by jensb** [StevenBlack/hosts#2528]
Sono Motors (sonomotors.com) is a car company, this link is used in their newsletters.

The block is caused by a CNAME alias to "pi.pardot.com", which again points to an Amazon AWS hostname probably shared by many legitimate services.

I would suggest not to block "pardot.com" and its subdomains.

**Comment by jensb** [comment]
You're welcome! :-)

**Comment by StevenBlack** [comment]
Thank you for this @jensb.

Maybe you misunderstand what we do here.

There are no legitimate websites here. If a site does user tracking, or worse, it gets listed here.

Several of our upstream curators agree that pardot.com is a problem. Therefore I do not expect this to change.

Closing.

**Comment by jensb** [comment]
Yes, then I actually misunderstood the intentions of your list.

I applaud your efforts, but unfortunately in this case using this list does not pass the "family test": it breaks too many links in newsletters, on shopping sites and on social media.

But I'm sure this is exactly what you intend to accomplish, and please continue doing this!
