### ISSUE TITLE
Why is xnxx.com added by default to the hosts file? 

### ISSUE THREAD

**Issue by bennyprofane** [StevenBlack/hosts#253]
Is there a reason xnxx.com is added to the default hosts file? Is that site malicious? Asking for a friend.... My friend doesn't remember it being blocked in previous versions. Other similar sites are not added by default so my friend was curious as to why that site is being blocked in the main hosts file and is not part of a porn extension.

**Comment by FadeMind** [comment]
https://github.com/mitchellkrogza/Badd-Boyz-Hosts/blob/master/hosts#L3358

@StevenBlack @mitchellkrogza

**Comment by funilrys** [comment]
Reference: #248

**Comment by mitchellkrogza** [comment]
Picked it up in logs sending phishy redirects and strange behavior. Very much a heavy porn site and blocked as a result.

**Comment by mitchellkrogza** [comment]
Busy running a script against a years worth of logs, probably going to take till tomorrow to complete running. If I don't see enough results for xnxx it will be removed along with anything else that scores a low score

**Comment by StevenBlack** [comment]
@benlowry meanwhile, your friend may like to know that Tor (Onion) browsers bypass hosts files.  

Friends don't let friends browse edgy sites without Tor.

**Comment by benlowry** [comment]
Thanks @StevenBlack, glad to know it but that's actually a different Ben heh.

**Comment by bennyprofane** [comment]
I know this article is from 2013 but nbc news says that xnxx.com is safe

"The results were more encouraging than Longmore expected. Porn sites xvideos.com, livejasmin.com, redtube.com, xnxx.com, youporn.com, and adultfriendfinder.com earned a 0 percent risk rating."

http://www.nbcnews.com/id/51498128/ns/technology_and_science-tech_and_gadgets/t/are-all-porn-sites-really-riddled-malware/

It's not really a tor-worthy site in my opinion, pretty standard content on par with other popular clearnet sites like pornhub or youporn.

**Comment by StevenBlack** [comment]
Whoops sorry @benlowry.

**Comment by mitchellkrogza** [comment]
Will be sorted in today's commit. Thanks for the heads up guys.

**Comment by PromoFaux** [comment]
Just my two-cents.. I would say that there should not be _any_ porn sites in a blacklist for adware/malware (unless the direct URL is known to be a hotbed of viruses and malware). Treading a fine line between safety and censorship there... besides, there are already lists for those that want to (for some weird reason) block porn on their networks.

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/5443b12687c8ee9b1462b308d4311f77b894864e along with a few others.

**Comment by mitchellkrogza** [comment]
@PromoFaux A lot of the porn sites listed in my list come from my nginx logs where they are sending referrer spam. I'm going to of course continually revise the list thanks to all your inputs here and any sites marked safe by Google Safe Browsing etc should not be in here. Still tweaking a script I wrote yesterday to grep through an entire year's worth of logs and anything that scores below a certain number of attempts against my sites will probably be dropped unless they start re-appearing again.

**Comment by StevenBlack** [comment]
New host files are up!

Closing.

**Comment by evansoner** [comment]
I find a few domains which must not be here. Where I can report this list?

**Comment by mitchellkrogza** [comment]
Please report issues at https://github.com/mitchellkrogza/Badd-Boyz-Hosts

**Comment by Jezza-x3** [comment]
@evansoner please don't comment on an issue that's 2 months old, closed, and is irrelevant. Open a new issue with your concerns.

**Comment by mitchellkrogza** [comment]
@evansoner please log issues at https://github.com/mitchellkrogza/Badd-Boyz-Hosts as you can see with all issues logged with me I am very responsive to fixing them.
