### ISSUE TITLE
Allow co.vaicore.site and int.vaicore.site - Paramount+ Chromecast is broken as result

### ISSUE THREAD

**Issue by andritolion** [StevenBlack/hosts#2530]
The domains co.vaicore.site and int.vaicore.site should be allowed, otherwise media casted from the Paramount+ app to a Chromecast will not load, as the player UI never loads.

**Comment by StevenBlack** [comment]
Thank you for this Andrew @andritolion.

I've written this before here, several times.

It doesn't matter if listing a domain interferes with fundraising by the Holy Sisters relict of Mother Theresa of Calcutta. If the domain vehicles tracking, adware, or worse, it gets listed here. This project serves people who value privacy and online safety. 

Now that said, those `vaicore.site` domains come to us from the [AdAway list](https://github.com/AdAway/adaway.github.io/tree/master) which is mostly dormant. We operate with a cached version of that list now.

I'm gonna remove those domains from our cache.  One of the other active curators will pick up this domain if it's still problematic.

**Comment by StevenBlack** [comment]
Andrew @andritolion this will be active in the next release, coming shortly.

**Comment by FadeMind** [comment]
CC @sjhgvr

**Comment by sjhgvr** [comment]
> CC @sjhgvr

oisd sourced from: https://raw.githubusercontent.com/bigdargon/hostsVN/master/source/adservers-all.txt
Fixed. Thanks 👍

**Comment by FadeMind** [comment]
CC @hagezi

**Comment by hagezi** [comment]
`vaicore.site` is tracking and belongs to Kochava (Measure Everything with Kochava): https://www.kochava.com/

It is used by Paramount, the blocking did not lead to problems so far, unfortunately I cannot test Chromcast. But someone who has the possibility to test it should verify this.

More Kochava Domains:
```
co.akisinn.info
co.dewrain.life
co.vaicore.site
co.vaicore.xyz
int.akisinn.info
int.akisinn.me
int.akisinn.site
int.dewrain.life
int.dewrain.site
int.dewrain.world
int.vaicore.site
int.vaicore.store
int.vaicore.xyz
int.vlancaa.site
int.vlancaa.fun
tok.vaicore.xyz
...
```

`co.vaicore.site` is also blocked in Cloudflare Secure DNS, for whatever reason.

ping @bigdargon @bongochong @Alex-302 (`||co.vaicore.site^`/ `||int.vaicore.site^`)

**Comment by bigdargon** [comment]
I refer to blocking domain tracking elsewhere
https://github.com/AdguardTeam/AdguardFilters/issues/93230
https://github.com/AdAway/adaway.github.io/issues/281
https://github.com/r-a-y/mobile-hosts/issues/16

**Comment by StevenBlack** [comment]
Thank you everybody.

I am adding the domains `co.vaicore.site` and `int.vaicore.site` to my ad-hoc list.

**Comment by Alex-302** [comment]
@hagezi we already have https://github.com/AdguardTeam/AdguardFilters/commit/c8f210061cbc2ce1c075f880a02d05b33520209c
