### ISSUE TITLE
Unblock static.klaviyo.com

### ISSUE THREAD

**Issue by Maronato** [StevenBlack/hosts#2534]
Blocking `static.klaviyo.com` breaks product reviews and product questions in Shopify stores.

The domain is blocked by AdAway, which is [unmaintained](https://github.com/AdAway/adaway.github.io/issues/357).
`static.klaviyo.com` doesn't serve trackers. Their tracker domain seems to be `telemetrics.klaviyo.com` instead.

No other blocklist that I could find is blocking `static.klaviyo.com`, so it feels like a false positive by AdAway.

**Comment by StevenBlack** [comment]
Thank you for this Gustavo @Maronato.

C'mon!  `fastly.net` gets no slack here.

```bash 
$ dig static.klaviyo.com 
                                                                               
static.klaviyo.com.	3	IN	CNAME	klaviyo-onsite.map.fastly.net.
klaviyo-onsite.map.fastly.net. 15 IN	A	151.101.2.133
klaviyo-onsite.map.fastly.net. 15 IN	A	151.101.66.133
klaviyo-onsite.map.fastly.net. 15 IN	A	151.101.130.133
klaviyo-onsite.map.fastly.net. 15 IN	A	151.101.194.133
```

This is tracking shit. Closing.

**Comment by orzel** [comment]
I dont know anything about klaviyo.com, but your dig shows that it uses fastly, which provides among other services CDN services for lot of sites. I think it's unfair to block IPs from this CDN
