### ISSUE TITLE
I'd like to be able to block video and streaming sites.

### ISSUE THREAD

**Issue by ivandimitrov8080** [StevenBlack/hosts#2535]
Hello,

I'm addicted to youtube. It's a full time job at this point. I've watched 48 hours of youtube in the past week.

I'd like to be able to block platforms like that in an attempt to get off of them.

Maybe a bulk file would be nice - yt, twitch, vimeo, tiktok etc...

**Comment by StevenBlack** [comment]
Hello Ivan @ivandimitrov8080 thank you for your question.

You can manually add domains to your copy of the hosts file. It's very easy to do, simply with a text editor.

Closing.
