### ISSUE TITLE
Gumroad is blocked as porn

### ISSUE THREAD

**Issue by ryanccn** [StevenBlack/hosts#2539]
Gumroad is used for selling a wide range of things including software, merch, etc. However, the blocking of `app.gumroad.com` blanket blocks anything on Gumroad since Gumroad checkouts are done on `app.gumroad.com`.

**Comment by StevenBlack** [comment]
Hi Ryan @ryanccn thank you for this.

As far as I can tell, the domain `app.gumroad.com` is in the porn list variants only. That's a limited blast radius 😓 but still.

The issue is upstream. Ping @sinfonietta can you please urgently have a look? Thanks!

**Comment by Sinfonietta** [comment]
@StevenBlack the `app.gumroad.com` domain is removed now.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and thank you for making this issue Ryan @ryanccn.

Closing.
