### ISSUE TITLE
To be able to use history and red progress line in youtube you must:

### ISSUE THREAD

**Issue by AngelTsTsvetkov** [StevenBlack/hosts#254]
#0.0.0.0 s2.youtube.com
#0.0.0.0 s.youtube.com

**Comment by StevenBlack** [comment]
That is true, @AngelTsTsvetkov.  

[Here are in-source comments related to that](https://github.com/StevenBlack/hosts/blob/bc9ad64460da8596526a4153a18cc66305d2dfb1/data/someonewhocares.org/hosts#L1392).

These hosts have been in the amalgamated hosts file since 2012.  I don't expect this to change.

**Comment by AngelTsTsvetkov** [comment]
Sorry, but i didn't see this source comment when I install different hosts variation files from zip file. Otherwise I wouldn't bother to write here ...
