### ISSUE TITLE
Additional ad sites [upstream inclusion request]

### ISSUE THREAD

**Issue by Lovelaces** [StevenBlack/hosts#2541]
These sites are deceitful ad sites that purports to serve a particular purpose but actually just makes unknowing users run through numerous ads and ad-related surveys before realizing they've been tricked:

pssgames.com
primeleech.com
link.premiumgenerator.cyou
anydebrid.com
okdebrid.com
hotdebrid.com
youdebrid.com
hot4share.com

**Comment by StevenBlack** [comment]
Thank you for this @Lovelaces.

It's not that simple.

Advertising is a legitimate legal business, and we are not in the business of deplatforming advertising companies from the internet.

If we blindly blocked "ad sites" then we would list `google.com`, wouldn't we?

What we list here are the domains used to serve ads. That's not what I'm seeing in this issue.

Closing.
