### ISSUE TITLE
Alternative Malware List Without Ads

### ISSUE THREAD

**Issue by alsyundawy** [StevenBlack/hosts#2542]
Can you support for Alternative Malware List Only Without Ads then combine with fakenews, gambling, porn and social

**Comment by alsyundawy** [comment]
Hi dear, thank you for replying to this discussion.

do you remember that I once req for fakenews-gambling-porn-only without Unified hosts = (adware + malware)?

So now, if only you could, please separate them again. Unified hosts = (adware + malware) only specifically for malware and adware without a list of advertisements

**Comment by StevenBlack** [comment]
Hi @alsyundawy we don't have this granularity from any of our upstream sources.

Therefore that's not possible.

Closing.

**Comment by alsyundawy** [comment]
oh ok @StevenBlack but i have sample for upstream 

https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/threat/hosts
https://raw.githubusercontent.com/blocklistproject/Lists/master/alt-version/ransomware-nl.txt	
https://raw.githubusercontent.com/blocklistproject/Lists/master/alt-version/scam-nl.txt	
https://raw.githubusercontent.com/blocklistproject/Lists/master/alt-version/phishing-nl.txt	
https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/hosts_nsfw.txt
https://gitlab.com/quidsup/notrack-blocklists/-/raw/master/malware.list
https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-hosts.txt
https://raw.githubusercontent.com/Import-External-Sources/hosts-sources/master/data/phishing_army_blocklist_extended/domain.list
https://raw.githubusercontent.com/Import-External-Sources/hosts-sources/master/data/migueldemoura_malware/domain.list
https://raw.githubusercontent.com/hrshadhin/hosts/master/sources/KADhosts/hosts
https://raw.githubusercontent.com/EnergizedProtection/mirror/master/active/filter/disconnect.me-malware.txt
https://raw.githubusercontent.com/EnergizedProtection/mirror/master/active/filter/adguard-spyware.txt
https://raw.githubusercontent.com/EnergizedProtection/mirror/master/active/filter/adguard-mobile-spyware.txt
https://raw.githubusercontent.com/EnergizedProtection/mirror/master/active/filter/disconnect.me-malvertising.txt
https://raw.githubusercontent.com/EnergizedProtection/mirror/master/active/filter/ck-malware.txt
https://raw.githubusercontent.com/EnergizedProtection/mirror/master/active/filter/adguard-spyware-firstparty.txt
https://raw.githubusercontent.com/EnergizedProtection/mirror/master/active/filter/adware-filters.txt
https://v.firebog.net/hosts/Prigent-Malware.txt
https://v.firebog.net/hosts/RPiList-Malware.txt
https://v.firebog.net/hosts/RPiList-Phishing.txt
https://phishing.army/download/phishing_army_blocklist_extended.txt
https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt

**Comment by StevenBlack** [comment]
Thank you for this @alsyundawy 

What we do here is well expressed in the repo readme.

We amalgamate well-curated sources of hosts that possess track records and underlying processes ONLY.

This issue is closed.
