### ISSUE TITLE
blocking cdn.cookielaw.org causes some sites to not work (homedepot.ca)

### ISSUE THREAD

**Issue by bluevalien** [StevenBlack/hosts#2551]
https://github.com/StevenBlack/hosts/blob/8009dc6a69a7f80be91c1b4058ef78f4c1dabaa8/data/StevenBlack/hosts#L2498

I found that blocking this domain causes home depot's search to fail. 
`Sorry, something went wrong. Please try again.`
![image](https://github.com/StevenBlack/hosts/assets/15284113/446b8808-d681-4f7c-adcb-11a5e3861508)

Maybe not a reason to remove it but I wanted to share in case someone else finds this and open the discussion. 

EDIT: adding info just to be complete.
Everything is up-to-date AFAIK
`Pi-hole v5.17.2 FTL v5.23 Web Interface v5.21`
uname: `Linux pihole2 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux`
/proc/cpuinfo `Raspberry Pi 3 Model B Rev 1.2`

homedepot.ca was tested in brave, chrome and edge on windows 10

**Comment by StevenBlack** [comment]
Thank you for this @bluevalien.

We've discussed cookielaw many times before, here in issues.

Please report this Home Depot website bug to Home Depot.

If a website fails when a third party site is unreachable, that's their problem.

Closing.

**Comment by bluevalien** [comment]
thanks, I should have looked closer. Makes sense now.
For those who find this thread,  there's a good discussion here:
https://github.com/StevenBlack/hosts/issues/2257#issuecomment-1468453178
I have little hope that I'll get the home-depot folks to fix this.
