### ISSUE TITLE
whitelist two domains

### ISSUE THREAD

**Issue by Konfekt** [StevenBlack/hosts#2556]
These domains

```
# stiftung-warentest/sueddeutsche.de payment
id-eu.piano.io
buy-eu.piano.io
cdn.piano.io
piano.io
cdn-eu.piano.io
c2-eu.piano.io

# magentacloud.de login
tags-eu.tiqcdn.com
```

block the payments of [German journal sites](https://www.kuketz-forum.de/t/stiftung-warentest-artikel-freischalten-funktioniert-nicht/6213/21) respectively [user cloud service](https://telekomhilft.telekom.de/t5/MagentaCLOUD/Sammelthema-Magenta-Cloud-kein-Login-mehr-moeglich/td-p/5679492/page/6#answers)

**Comment by StevenBlack** [comment]
Thank you for this Enno @Konfekt.

This isn't going to change.  Closing.

**Comment by Konfekt** [comment]
Good to know, and personally of little concern as your white list already works around it. Is this due to upstream reasons? Or rather, not throwing out the baby with the bath water?

**Comment by StevenBlack** [comment]
Enno @Konfekt this is a tracking domain, and it doesn't matter if German journal sites use it. This is their problem, not ours.

Like I've written many times before:

> It doesn't matter if listing a domain interferes with fundraising by the Holy Sisters relict of Mother Theresa of Calcutta. If the domain vehicles tracking, adware, or worse, it gets listed here. This project serves people who value privacy and online safety.

**Comment by Konfekt** [comment]
Thank you, makes sense (the baby in the bath water), and sorry for taking your time. Be this closed issue serve a hint for Telekom and Warentest customers.
