### ISSUE TITLE
Block conversionbear.com

### ISSUE THREAD

**Issue by kevintraver** [StevenBlack/hosts#2561]
Reason to block:

Conversion / tracking metrics

**Comment by StevenBlack** [comment]
Thank you for this Kevin @kevintraver.

This is a link to a company home page. We aren't in the business of de-platforming companies. We don't have enough staff lawyers for that.

We restrict domains that are used to vector adware, malware, or worse. Blocking legal company websites is not what we do here.

Closing.

**Comment by kevintraver** [comment]
Ok, Thank you for the explanation.
