### ISSUE TITLE
I NEED HELP QUICK

### ISSUE THREAD

**Issue by I-JMC** [StevenBlack/hosts#2563]
Hello,
I'm really dumb right now, I put for my hosts file the 6 572kb file but I have a really low end computer so now it is constantly at 100% CPU all the time and I tried everything editing the file in admin mode, take ownership, delete it, rename it and nothing worked it was either you don't have the permissions (even though I'm admin) or this action could not be done as this file is already in use by another process, so now my pc is almost unusable and when I terminate the process in the task manager it only gets back right after changing nothing, I tried to follow the steps of Microsoft support but it also doesn't work.
Please someone help me quick.
Hope you have a great day

**Comment by I-JMC** [comment]
Please someone help...

**Comment by I-JMC** [comment]
Thank you very much, I was able to solve the issue by going in safe mode deletng the massive hosts file and re put the old hosts file which was only 3kb I then flushed my dns don't know why as I think it would automaticly re flush at restart but I wasn't sure. But thank you very much the only problem is that idk why but when I had the problem when trying to connect to the Wifi it would kick me out and I could never connect to it the other problem is that my laptop isn't old it's just a new potato PC (I have a Intel N100 CPU (and it's my PC for school 😬)) and I on't think it would have been able to download the IObit Unlocker. But still thank you very much, I am amazed someone answered this quickly. I don't really understand the thing with the compressed hosts file.
God bless you,
- ICaPICo

**Comment by Lateralus138** [comment]
For future reference an unlocker program can be a machine saver, so if I advise you to get one, but of course, that's your prerogative.

If you are interested in testing the compression method you can manually download the hosts file again (or you renamed it or something) and put it in a different directory and then use my "Hosts Compress" tool to compress the file and it should solve your issue. My program is recommended by this Steven's repository in the [Interesting Applications](https://github.com/StevenBlack/hosts#interesting-applications) section or you can find it here: [Hosts Compress](https://github.com/Lateralus138/hosts-compress-windows) with information about how to use it and the Releases.

**Comment by I-JMC** [comment]
Thank you very much !!!

**Comment by Lateralus138** [comment]
>  I don't really understand the thing with the compressed hosts file tbh.

My repository explains it quite well I think.

I just wouldn't give up on trying the option if I were you as it should be a viable option and no one should have to go without protection in my opinion :D
