### ISSUE TITLE
Stoneskirts.pl suggestion to remove from list

### ISSUE THREAD

**Issue by r2alter** [StevenBlack/hosts#2564]
Stoneskirts.pl hosted online shop with clothes and shouldn't be blocked. 

Greetings!

**Comment by StevenBlack** [comment]
Thank you for this @r2alter.  What we do, here, is explained in the readme.

Like I've written many times before:

> It doesn't matter if listing a domain interferes with fundraising by the Holy Sisters relict of Mother Theresa of Calcutta. If the domain vehicles tracking, adware, or worse, it gets listed here. This project serves people who value privacy and online safety.

Closing.
