### ISSUE TITLE
It disables the Youtube history.

### ISSUE THREAD

**Issue by aakashtheseeker** [StevenBlack/hosts#2565]
https://github.com/StevenBlack/hosts/blob/01b3c89fbfdaa1156c37b04267eecdb9271c0f8d/data/someonewhocares.org/hosts#L1057

Please remove this host line. It disables the Youtube history. I can't add this host link to whitelist or allow list because I'm using DNS filtering (like ControlD, NextDNS or Rethink) which uses this list. Please fix this issue in your next update. I just love this blocklist. Thanks.

**Comment by StevenBlack** [comment]
Hi Aakash @aakashtheseeker thank you for this.

[We have talked about the domain `s.youtube.com` here many times before](https://github.com/search?q=repo%3AStevenBlack%2Fhosts+s.youtube.com&type=issues) and, hate to break it to you, this isn't going to change anytime soon.

But thank you for bringing this to attention. What we do here is, draw the line. The domain `s.youtube.com` is an edge case, certainly, but we've determined it's a tracker, so we're OK blocking it.

Closing.
