### ISSUE TITLE
Dominos Pizza needs tags.tiqcdn.com

### ISSUE THREAD

**Issue by blizzardengle** [StevenBlack/hosts#2567]
For whatever reason Dominos Pizza needs `tags.tiqcdn.com` to work and StevenBlack_ADs (DNSBL_ADs_Basic) in pfSense blocks it.

**Comment by StevenBlack** [comment]
Hi Christopher @blizzardengle thank you for this!

This report should be directed to Dominos Pizza. 

We don't serve Dominos Pizza here. We serve people who don't want to be tracked and traded online. 

We won't stop listing tags.tiqcdn.com anytime soon.

Closing
