### ISSUE TITLE
Add cdn.liftoff-creatives.io to Ads

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [StevenBlack/hosts#2568]
## Domain(s) to add

cdn.liftoff-creatives.io

## Reason

It serves ads for multiple apps, including but not limited to terabox. This domain belongs to "Liftoff" (according to [Netify](https://www.netify.ai/resources/domains/liftoff-creatives.io)) which is a "mobile app marketing and retargeting platform"

## Add to list

Ads/Adware

## Other info
This service seems to be very new, not that many lists have this domain according to [Blocklist tools](https://blocklist-tools.developerdan.com/entries/search?q=cdn.liftoff-creatives.io). Blocking this domain does not seem to have any significant effects besides the removal of ads (yet).

**Comment by hagezi** [comment]
As an addition: `product-cdn.liftoff-creatives.io`

**Comment by SodaWithoutSparkles** [comment]
I also found these domains after liftoff was blocked

```
biddingmax.apse.trk.rixserv.com
et-l.w.inmobi.com
i.l-new.inmobicdn.net
```

**Comment by StevenBlack** [comment]
Thank you gentlemen @SodaWithoutSparkles @hagezi these domains are added in commit  3a51262 and will appear in the next release.

Closing.

**Comment by Devkiller41069** [comment]
Get this shit off my phone. Thess low life hacker losers. Waste lf free air
