### ISSUE TITLE
A legitimate domain is being blocked

### ISSUE THREAD

**Issue by drakofrost** [StevenBlack/hosts#257]
There's one entry in the hosts file that it's blocking images hosted on Blogger/Blogspot, the address is the following:

1.bp.blogspot.com

It's breaking several blogs, can you remove it?

Examples:

http://submundo-hq.blogspot.com.br/
http://cinespacemonster.blogspot.com.br/2015/10/v-batalha-final-aka-v-original.html

**Comment by StevenBlack** [comment]
@mitchellkrogza can you please advise?

**Comment by mitchellkrogza** [comment]
Will be addressed in today's commit.

**Comment by drakofrost** [comment]
I appreciate it.

**Comment by mitchellkrogza** [comment]
No problem, appreciate you alerting me to it, helps a lot keeping a legit
list. That domain is from a very early list I started with when I branched
off into my own projects.

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/13486d1092c0e51f9fb58ce5deb8e8d1034bd27e

**Comment by StevenBlack** [comment]
Regenerated. Thanks everybody!

Closing.
