### ISSUE TITLE
Watched YouTube video do not add to history

### ISSUE THREAD

**Issue by meskal1** [StevenBlack/hosts#2570]
After update hosts YouTube video do not add to history any more in mobile app.

**Comment by iam-py-test** [comment]
[I am sorry, but this concern has been raised many times](https://github.com/StevenBlack/hosts/issues?q=s.youtube.com), and StevenBlack has made it clear they do not intend to remove this domain.
You are free to allowlist it yourself if this is an issue for you.
Thank you
