### ISSUE TITLE
Previously removed streaming domains added back 

### ISSUE THREAD

**Issue by dschaper** [StevenBlack/hosts#2572]
`medium.ngtv.io` was removed with https://github.com/StevenBlack/hosts/issues/2363 / https://github.com/StevenBlack/hosts/commit/bbe11d622e3317ff6b43927cbc211486c785e94b

The domain was added back to the list with https://github.com/StevenBlack/hosts/commit/85984027fddd28383a1a78e0f13df008ffbf2716 

Can you please remove the domains again, we've received reports that this is causing video streaming issues.

Thanks!

**Comment by StevenBlack** [comment]
Thank you for this Dan @dschaper.

The domain `medium.ngtv.io` is removed in commit 88878285 and this will reflect in the next release.

Closing.
