### ISSUE TITLE
click.discord.com is listed

### ISSUE THREAD

**Issue by mdstricklin** [StevenBlack/hosts#2574]
click.discord.com is listed. That is a valid subdomain that is used during some login processes like email-verifying a login at a new location). I had to add it to my pihole whitelist because it was picked up from your hosts list. Please remove it.

**Comment by iam-py-test** [comment]
I am sorry, but this has been reported and discussed before: https://github.com/StevenBlack/hosts/issues/2505
click.discord.com is primarily used for tracking, and as such it is blocked by Peter Lowe's list (which is included in the filterlists here). I do not believe it will (and should) be removed, but you are free to contact Peter and discuss the subject with him should you wish.
Thank you.

**Comment by StevenBlack** [comment]
Thank you for this @mdstricklin.

This likely isn't going to change. This issue should be raised with Discord.

Closing.

**Comment by mdstricklin** [comment]
This isn't an issue with Discord, you walnut. I can't believe this is a known issue and you're just leaving it in addressed for reasons unknown. Your list is the only one I've ever had issues from, and this stance is bizarre so it sounds like my best course action is just to remove your list.

**Comment by StevenBlack** [comment]
You do that Anon @mdstricklin.  We serve people who don't want to be tracked. That's our mission, and those are our people. This list is not a good fit for you, and that's OK.

**As I've stated here many times before**:

> It doesn't matter if listing a domain interferes with fundraising by the Holy Sisters relict of Mother Theresa of Calcutta. If the domain vehicles tracking, adware, or worse, it gets listed here. This project serves people who value privacy and online safety.

**Comment by mdstricklin** [comment]
Sounds like PiHole needs to update to a new default then, because they are using your list to serve people that are primary concerned with blocking advertisements, not trackers. Not sure if you were aware. Might want to recommend to them that they chose a new default to ship with, since your list seems to be an ill fit.

**Comment by StevenBlack** [comment]
Thank you for your comments Anon @mdstricklin.  I suggest you take this suggestion to the Pi-Hole repository. Here's the link:

https://github.com/pi-hole/pi-hole/issues

**Comment by sefinek24** [comment]
> This isn't an issue with Discord, you walnut. I can't believe this is a known issue and you're just leaving it in addressed for reasons unknown. Your list is the only one I've ever had issues from, and this stance is bizarre so it sounds like my best course action is just to remove your list.

I absolutely agree with what you've written, @mdstricklin

**Comment by lmstearn** [comment]
Peter Lowe's link actually lists https://click.discord.com which is 404, the jump links in the emails are of the form `https://click.discord.com/ls/click?upn=XXX...` which resolve to `https://discord.com/authorize-ip#token=YYY...`.
If this is relevant, a job for a concerned body (or bodies) to determine which directories of **click.discord** contain the trackers?
Thanks. 😄

**Comment by pgl** [comment]
PS: Regarding ads vs. trackers, my list is available with only ad servers included: https://pgl.yoyo.org/as/formats.php#notrackers
