### ISSUE TITLE
cloudflare entries prevennt actual usage

### ISSUE THREAD

**Issue by boostchicken** [StevenBlack/hosts#2575]
Currently if you are using the master list it will break cloudflare because of the cloudflare entires

**Comment by StevenBlack** [comment]
Thank you for creating this issue John @boostchicken.

I'm going to need specific details.

With latest active, I just logged into Cloudflare, loaded my dashboard, and accessed all my usual use cases successfully.

So I have no idea about what you are referring-to.

**Comment by StevenBlack** [comment]
Seeing no reply, closing this now.
