### ISSUE TITLE
List of suggestions for sources of hosts data Gambling (Indonesia)

### ISSUE THREAD

**Issue by alsyundawy** [StevenBlack/hosts#2578]
List of suggestions for sources of hosts data Gambling (Indonesia)

https://raw.githubusercontent.com/alsyundawy/TrustPositif/main/judi-Sep23_20Feb2024.txt

**Comment by StevenBlack** [comment]
Thank you for this @alsyundawy.

Let's use [ghosts](https://github.com/StevenBlack/ghosts) to assess what's there, compared to our `base + gambling` list:

```
ghosts -m g -c https://raw.githubusercontent.com/alsyundawy/TrustPositif/main/judi-Sep23_20Feb2024.txt 
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts
Domains: 162,604
Bytes: 4.9 MB
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/alsyundawy/TrustPositif/main/judi-Sep23_20Feb2024.txt
Domains: 156,202
Bytes: 2.9 MB
Intersection: 55 domains
```

This fails basic credulity.

We have several gambling curators who've been doing this a very long time.

The suggested list comes in at 156,202 domains with only 55-domains overlapping. How is this possible, in any imaginable way?

The second problem is, our mission is providing hosts lists that are compatible with a wide range of devices. The principal problem is Windows OS which is a shitshow when it comes to hosts file handling.  In our experience here — see the issues — Windows OS can barely handle the list we have now.

Third problem is, search the list for `sex` or `crypto` or `bitcoin` and it's pretty clear this isn't just a gambling list.

Given the above, I must decline the suggestion. However thank you for suggesting it!

Closing.

**Comment by alsyundawy** [comment]
i am engineer internet service provider from indonesia

indonesia have rules to bloking porn, scamming, copyright & gambling from indonesia Ministry of Communication and Informatics (Kementerian Komunikasi dan Informatika Republik Indonesia) kominfo.go.id. this list not for publik but for internet service provider only. they send daily list to all ISP via email, then make compilation then for you just gambling site online

https://prnt.sc/1BDFIiDzZKhC

https://prnt.sc/URdIgYVh1Z5x

you can check list https://trustpositif.kominfo.go.id/

https://prnt.sc/IOTww_OEit_b

**Comment by alsyundawy** [comment]
switched source to https://raw.githubusercontent.com/alsyundawy/TrustPositif/main/gambling_indonesia.txt

update now with latest db
