### ISSUE TITLE
Some legitimate sites blocked.

### ISSUE THREAD

**Issue by tkalfaoglu** [StevenBlack/hosts#2579]
Hi. I found that some legitimate sites were blocked. 
www.rt.com:
 - https://blocklist.sefinek.net/generated/0.0.0.0/forks/StevenBlack.fakenews-gambling-porn.txt (disabled)

sputniknews.com:
Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
  id.sputniknews.com
Match found in https://blocklist.sefinek.net/generated/0.0.0.0/ads/blocklistproject.ads.txt:
  comet.sputniknews.com
Match found in https://blocklist.sefinek.net/generated/0.0.0.0/forks/neodevpro.neodevhost.txt:
  id.sputniknews.com (disabled)
  sputniknews.com (disabled)
Match found in https://blocklist.sefinek.net/generated/0.0.0.0/forks/justdomains.adguarddns.txt:
  comet.sputniknews.com
Match found in https://blocklist.sefinek.net/generated/0.0.0.0/forks/notracking.hostnames.txt:
  id.sputniknews.com
Match found in https://blocklist.sefinek.net/generated/0.0.0.0/forks/StevenBlack.fakenews-gambling-porn.txt:
  id.sputniknews.com (disabled)
  sputniknews.com (disabled)
Match found in https://blocklist.sefinek.net/generated/0.0.0.0/forks/StevenBlack.hosts.txt:
  id.sputniknews.com

Otherwise great lists!  Thanks and keep up the good work.

**Comment by StevenBlack** [comment]
Hello Turgut @tkalfaoglu thank you for this.

We have talked about the domain `rt.com` here before, [several times](https://github.com/StevenBlack/hosts/issues?q=is%3Aissue+rt.com+is%3Aclosed) and also [here](https://github.com/StevenBlack/hosts/pull/1449) and, as you can see, this is not going to change.

As for Sputnik News, I refer you to [this extensively sourced and footnoted Wikipedia article](https://en.wikipedia.org/wiki/Sputnik_(news_agency)).  In particular, please read paragraph 2, which I am reproducing here (below).

Frankly, I feel personally insulted that you would think, for even one second, that I would buy-in to this "*legitimate site*" nonsense. 

I stand with Ukraine 🇺🇦 and you and your puppet master can go fuck yourselves.

![2024-02-23_23-01-22](https://github.com/StevenBlack/hosts/assets/80144/e93d131f-6db7-47ea-8e81-b1ab2aca06f3)
