### ISSUE TITLE
Wrong domain entry in hosts file

### ISSUE THREAD

**Issue by ar51an** [StevenBlack/hosts#2581]
Hello,
Steven, below entry in the porn hosts file is breaking my converted unbound blocklist. Either comment the whole line or remove it. 

`0.0.0.0 .0.0.0 # handcore-henry.prvn.fetlifeblog.com`

https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-only/hosts

**Comment by Sinfonietta** [comment]
@StevenBlack this is now fixed.

**Comment by StevenBlack** [comment]
Thank you @ar51an and thank you for the quick response @Sinfonietta!

This is rectified in [Release 3.14.55](https://github.com/StevenBlack/hosts/releases/tag/3.14.55) which is online now.

Closing.
