### ISSUE TITLE
Add porn list

### ISSUE THREAD

**Issue by atrimioo** [StevenBlack/hosts#2582]
eroticmoviesonline.me
forum.lewdweb.net
lewdcorner.com
dmiregirls.su
youcams.xyz
hdporn92.net
sis001.com
178mh.com
db.bepis.moe
vintageplayboymags.co.uk
mmda.booru.org
afreecatv.com
k2s.club
new-jav.net
leaksmodels.com
leakonly.com
mybdsm.net
humiliation-pov.org
transsexual-hd.com
ilovescat.net
tubefemdom.net
bdsmup.net
femdomxxx.net
nsfwai.com
tabooporns.com
taboohome.com
incestvidz.com
incezt.net
girlscanner.online
javfun.me
mega-porno.me
porncomixonline.net
mycomicsxxx.com
youjav.net
neocities.org
vixenleaks.com
vlixa.com
erofights.com
cosplay.jav.pw
anihideck.org
vhentai.org
animefox.org
hentaiz.org
anitokyo.tv
sankakucomplex.com
oreno3d.com
goldencomics.art
ornfreex.app
livesexonline.com
kantotero.net
furaffinity.net
saishuu.com
tubehentai.com
hentaichannel.com
doujincorner.com
hentaiartists.com
hentaigamesplanet.com
pixxxparody.com
xxxmallvideoteasers.com
moekyun.co
iluvtoons.com
narutopixxx.com
mrporngeek.xyz
hentaigem.com
hentairoshi.com
ricedigital.co.uk
theprinceofporn.com
besthentai.world
player.fm
hentaidude.tv
betterwaifu.com
filmeshentai.com
thehentai.net
patreon.com
best-hentai-games.com
vidlink.org
oppai.stream
hstream.moe
hanime1.me
eporn.com
archivebate.com
myav.com
nsfwr34.com
hentaifox.tv
aniporn.com
watchhentai.net
hentais.tube
hentaitube.online
rou.video
javfan.one
hentaini.com
javdoe.sh
91rb.net
manwa.me
doujin.bar
xiuren.org
nicesss.com
meijuntu.com
qiuyeshudian.com
bnwo.world
sissyhypno.com
hypnopornvideos.com
pmvhaven.com
avjoy.me
playav.tv
transvids.wtf
hmvmania.com
dnaav.com
fengyuetongtian.com
177pica.com
prefap.com
sfmcompile.club
hentaix.io
mandrahentai.com
hentaila.com
3dsexanime.xyz
anchira.to
wholesomelist.com
hentaienvy.com
toonily.me
manhwa18.net
eahentai.com
bondagecomixxx.net
xcomics.se
manhwa18.cc
mangadass.com
dexyscan.com
hentaiwebtoon.com
omegascans.org
madaradex.org
mikocon.com
anime-sharing.com
doujinantena.top
comicbox.xyz
manhwas.net
mihentai.com
pornxtheatre.com
myduckisdead.org
sleazemovies.com
rarelust.com
film1k.com
pornktube.com
prefap.com
drtuber.des
pornobae.com
javtiful.com
avgle.com
senzuri.tube
javfinder.ai
javenglish.cc
7mmtv.sx
camcaps.ac
peachurbate.com
camshowdownload.com
camsmut.com
pornfactors.com
pornorips.to
bestpornstars.org
best-moviez.ws
adultdvdtalk.com
myjavbay.com
javjunkies.org
tokyo-tosho.net
pornrips.to
lovetorrent.net
sehuatang.net
nextjav.com
141jav.com
projectjav.com
reddxxx.com
gonewildbrowser.com
porninaminute.org
mitaku.net
bunkr-albums.io
coomer.su
kemono.su
tik.pm
rule34.dev
kusowanka.com
r34.app
spicymags.xyz
downmagaz.net
dfdude.com
mags.guru
adultload.ws
adultmagazine.net
adultmagazinespdf.com
pdfmagazines.club
gay-hotfile.errio.net
cat.yupdates.art
pbc.xxx
blcollection.co
nifty.org
fictionmania.tv
reddit-doesnt-like-this.site
megapornlist.com
bigpornlist.net
toppaidpornsites.com
bestpayadultsites.com
dirtywarez.org/cat/adult
iwara.tv
hentaiplay.net
mitestream.com
mangamonks.com
toonitube.com
hentai20.io
manga18.club
manhwaden.com
omegascans.org
otomi-games.com
betterrepack.com
h-suki.com
hcapital.tk
dl-raw.se
eroeronews.com
hentaigamecg.com
panda.chaika.moe
sheet.zohopublic.com
battwo.com
mangadistrict.com
manhwas.men
oktoon.com
toonily.com
webtoon.xyz
mangadex.org
constellarcomic.com
lunarscan.org
hemdomblog.com
hentag.com
gravure-idol-ranking.com
mabui-onna.com
asmr.one
155.fun
9kko.ktyaku.com
5prb.zapnpvc.me
6klt.ktyaku.com
2ye.zapnpvc.me
gnm.nbgvvd.com
51cg1.com
51cg.fun
h2wqz1.pwiizxssw.com
h2wqz2.pwiizxssw.com
h2wqz3.pwiizxssw.com
h2wqz4.pwiizxssw.com
h2wqz1.nhhjboejby.com
h2wqz2.nhhjboejby.com
h2wqz3.nhhjboejby.com
h2wqz4.nhhjboejby.com

**Comment by StevenBlack** [comment]
Thank you for this @atrimioo.

Using [ghosts](https://github.com/StevenBlack/ghosts) to evaluate these domains, we list 55 of the 245 domains you provide already.

That's actually not great. Someone now has to go though the whole list to validate each domain because, at the outset, this submission is marginal on a subjective quality basis.

@sinfonietta can you use this for inclusion?

```
$ ghosts -m p --clip                                                                                    

----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts
Domains: 244,602
Bytes: 7.1 MB
----------------------------------------
Compared hosts from clipboard summary:
----------------------------------------
Location: clipboard
Domains: 245
Bytes: 3.6 kB
Intersection: 55 domains
```

**Comment by StevenBlack** [comment]
Thanks you everybody.  Closing.
