### ISSUE TITLE
Remove from list

### ISSUE THREAD

**Issue by PythonGermany** [StevenBlack/hosts#2583]
media.xxxlutz.com
www.xxxlutz.de
www.xxxlutz.at

Context:
XXXLutz (www.xxxlutz.com) is an Austrian furniture store chain

**Comment by StevenBlack** [comment]
Thank you for this @PythonGermany.

Ping @sinfonietta can you evaluate this for false positivity?  Thanks!

**Comment by Sinfonietta** [comment]
@StevenBlack you can close this.
