### ISSUE TITLE
Remove rtnl.bxcl.de

### ISSUE THREAD

**Issue by trevh3** [StevenBlack/hosts#2585]
This is the host for my toniebox - a kids toy. Can’t use the product without this host. 

Added to blocklist via 7b8b936

**Comment by trevh3** [comment]
Here’s the PR: https://github.com/StevenBlack/hosts/pull/2586

**Comment by trevh3** [comment]
I’ve found find the original context for adding this domain to the blocklist. https://media.ccc.de/v/37c3-11993-toniebox_reverse_engineering#t=3146

Beginning at 32 minutes they discuss this domain. I might be fine with leaving it on the blocklist.  Would be interested in the company weighing in here. I’ve sent them an email with a link to this issue. Recording every interaction with this kids toy is not really OK.

**Comment by xRuffKez** [comment]
Blocked since Day one. NEVER had issues with two Tonie Boxines. Also not with new figurines!
