### ISSUE TITLE
request: Add a new category: AI-generated

### ISSUE THREAD

**Issue by Tomaz-Vieira** [StevenBlack/hosts#2590]
I seem to be getting more and more SEO-optimized AI-generated sites lately, and it takes some time to realize I'm wasting my time with AI-generated content. Would you accept a new category for those kinds of sites?

**Comment by StevenBlack** [comment]
Hello Tomaz @Tomaz-Vieira thank you for this suggestion.

I think this would depend on the quality of domain curation in that particular category. I haven't seen anything related to this, yet.


Offhand this could be something like our fake news extension. It's seems similar in a lot of ways.

**Comment by Tomaz-Vieira** [comment]
I interpret "fake news" as content that is maliciously crafted, while the AI one is just very lazily so (and in fact it's mostly composed of true statements).

But I guess I can also start my own list and then you can decide if it's worth merging it into yours =)
Anyway, thank you for your work, it really makes browsing the web viable again o/
