### ISSUE TITLE
logging/tracking domains

### ISSUE THREAD

**Issue by Raviu56** [StevenBlack/hosts#2594]
log.al-hiwar.com
telemetry.eyeo.com
xiaomi.telemetry.eyeo.com
opentelemetry-collector.shared-services.us-east-1.general.prod.wildlife.io
log.saas.zeasn.tv
ilogs.bytefence.com
logcollection.ronghub.com
tuplogpublic.bangcdn.net
logging.vstlsrv.com
detaillog-global.coolccloud.com
logreport-global.coolccloud.com
uplog.qbox.me
logs.jetgadget.xyz
vskit-log.vskit.tv

**Comment by StevenBlack** [comment]
Thank you for this @Raviu56.

You come by these domains how, exactly?

**Comment by StevenBlack** [comment]
Thank you @Raviu56 bit I decline this suggestion.
