### ISSUE TITLE
Tracker by salesforce, for a certain banking app

### ISSUE THREAD

**Issue by karolyi** [StevenBlack/hosts#2595]
Hey,

I use a certain 3-letter banking app (I don't want to name it here), that uses the host `mcgthfrqrs95vdbzkhtchf5fc0g4.device.marketingcloudapis.com `. Is there a way to put it into the blocked host list?

Cheers!

**Comment by StevenBlack** [comment]
Thank you for this László @karolyi.

To be perfectly honest I'm not into vague issues like this where I'm supposed to accept veiled references to de-platform a domain.  

Why would someone not want to mention the full details of a specific technical problem?

Please provide full details, or close this issue, thanks!

**Comment by karolyi** [comment]
Okay.

The bank is the N26 bank in Germany, they're using this API to track users.

I was reluctant to tell for privacy reasons.

**Comment by XhmikosR** [comment]
Did you try blocking it yourself @karolyi and see if everything still works with N26?

Blocking something without testing is dangerous and can lead to breakage.

**Comment by karolyi** [comment]
I did.

As a preface, I'm using trackercontrol from F-Droid on my android phones.

Logging in already took about 20 minutes just because the constantly blocked requests to `firebaseinstallations.googleapis.com`: another 'telemetry'. The application ruthlessly tries to connect there — as well as to this host — before finally giving up and letting me log in.

This didn't change after blocking this host locally, so you can safely put it into the blacklisted hosts.

**Comment by StevenBlack** [comment]
Thank you László @karolyi I have added this domain and it will be live in the next release.
