### ISSUE TITLE
Remove KATWARN (`kwrn.eu`,`www.kwrn.eu`, `profile.omega.kwrn.eu`)

### ISSUE THREAD

**Issue by WebworkrNet** [StevenBlack/hosts#2596]
**Lists in use:**

- Unified Hosts
- Fakenews
- Gambling
- Porn
- Social

**Domains:**
```
kwrn.eu
www.kwrn.eu
profile.omega.kwrn.eu
```
**Details:**

These domains belong to the German KATWARN (warning system). When blocked, the app does not work correctly.

https://en.wikipedia.org/wiki/EUwarn

Related to #2305.

**Comment by bondskin** [comment]
I don't see them blocked (anymore)

**Comment by StevenBlack** [comment]
Thank you for this Denis @WebworkrNet.

@bondskin is correct: we don't list these domains.

Closing.
