### ISSUE TITLE
Add facturasmex.cloud

### ISSUE THREAD

**Issue by pulpon6** [StevenBlack/hosts#2601]
It's a phishing domain downloading malware 
https://www.virustotal.com/gui/domain/facturasmex.cloud/details

**Comment by iam-py-test** [comment]
Appears to have been taken down by their hosting provider:
![This account has been suspended. Please contact the billing/support department as soon as possible.](https://github.com/StevenBlack/hosts/assets/84232764/0f4aad4c-3741-43b9-b79c-c5b7705600b1)
Thank you

**Comment by pulpon6** [comment]
You have to put an extension url for the malware 
facturasmex.cloud/b08

**Comment by iam-py-test** [comment]
[That URL just redirects to Microsoft](https://tria.ge/240312-mrc4qagh58/behavioral1). Is a specific browser/region/referer required?
Thanks

**Comment by StevenBlack** [comment]
Thanks everyone.

Closing.
