### ISSUE TITLE
Doujindesu - Pornography

### ISSUE THREAD

**Issue by caliphdev** [StevenBlack/hosts#2605]
```
doujindesu.xxx
doujindesu.tv
```

**Comment by StevenBlack** [comment]
Thank you @caliphdev.

Ping @sinfonietta for evaluation and possible inclusion in the porn list.

**Comment by Sinfonietta** [comment]
@StevenBlack I have added these.

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and @caliphdev.

Closing.
