### ISSUE TITLE
Youtube watch history 

### ISSUE THREAD

**Issue by S1lentkid89** [StevenBlack/hosts#2607]
The blocklist caused iOS youtube app not to save watch history. Videos watched on the phone are not saved to my watch history at all. I also use the blocklist on my Mac where the watch history saves normally - watching through safari browser.

**Comment by StevenBlack** [comment]
Thank you for this @S1lentkid89.

We have discussed this [many, many times before](https://github.com/StevenBlack/hosts/issues?q=is%3Aissue+Youtube).

Let me explain: what we do here is serve people who don't want to be tracked, sold, served ads, or threatened, for any reason. That is what we do here.

This isn't going to change.

Closing.
