### ISSUE TITLE
block argo.svcmot.com

### ISSUE THREAD

**Issue by userforsource** [StevenBlack/hosts#2611]
This is s tracking domain used in motorola devices
https://forums.lenovo.com/t5/motorola-one-fusion/what-to-know-about-this-url/m-p/5118436
I have tested this and blocked for 2years no issues faced.

**Comment by StevenBlack** [comment]
Thank you for this @userforsource.

That is not a domain.

We certainly won't be blocking the domain `forums.lenovo.com`.

Closing.

**Comment by liamengland1** [comment]
`argo.svcmot.com` is not a domain?

**Comment by StevenBlack** [comment]
Thank you for your persistence @userforsource.

This domain is added in commit 700a10b5.

**Comment by devastatorx** [comment]
As a heads up, this may well be a tracking domain, but it is also the domain motorola uses to determine if a device has been online long enough to allow (ungrey) the 'oem unlock' toggle in 'developer settings' to allow bootlloader unlocking on eligible devices.  I ended up finding this out after leaving a device on wifi for what should have been the requisite amount of time only to find out that it did not ungrey the toggle.  This isn't an issue if the device has an active sim, but if it doesn't and the device is only on wifi the check-in never occurs for the countdown to begin.
