### ISSUE TITLE
block airtel analytics.

### ISSUE THREAD

**Issue by userforsource** [StevenBlack/hosts#2614]
`digianalytics.airtel.in`
`adconfig.wynk.in`
`sdk-01.moengage.com`
`clarity.ms`

**Comment by StevenBlack** [comment]
Thank you for this @userforsource.

I need more information and specific motivations to block domains.

**Comment by userforsource** [comment]
Sure this domains are from airtel thanks app.
https://play.google.com/store/apps/details?id=com.myairtelapp
First one is for analytic which is evident from the url 2nd one is from wink music which is also drom same brand airtel and used for ads 3rd and 4th are for probably ads and tracking as i have blocked that manually and checked everything works as it should be.

**Comment by StevenBlack** [comment]
Thanks @userforsource.  I decline this suggestion.

**Comment by userforsource** [comment]
Can you tell me why you declined it.

**Comment by StevenBlack** [comment]
@userforsource because thousands maybe millions of people rely on me to make these decisions and this suggestion landed completely half-baked, and subsequently nothing changed my view of that.

**Comment by userforsource** [comment]
Thanks for your response subsequently i find that this domains are blocked in HaGeZi - Multi PRO++ and OISD and 1host.
