### ISSUE TITLE
StevenBlack blocks GOG Store in Heroic Games Launcher

### ISSUE THREAD

**Issue by xerhaxs** [StevenBlack/hosts#2615]
I stumbled upon the following problem:

The unified-hosts blocklist is unfortunately blocking a domain that is needed to get the heroic games launcher gog store working.
It would be nice to remove this blocking domain to get gog running again.

**Comment by StevenBlack** [comment]
Thank you for this @xerhaxs.

This is not actionable because of insufficient information. 

Closing.
