### ISSUE TITLE
Mistake on line 22

### ISSUE THREAD

**Issue by waheedullahkhan001** [StevenBlack/hosts#2616]
I got this error:
`bad address at /etc/hosts line 22`

This is the line:
`fe80::1%lo0 localhost`

source: http://sbc.io/hosts/hosts

**Comment by StevenBlack** [comment]
Thank you for this Waheedullah @waheedullahkhan001.

This is not a mistake. Refs:

* https://stackoverflow.com/questions/30851101/localhost-meaning-of-fe801lo0
* https://superuser.com/questions/241642/what-is-the-relevance-of-fe801lo0-localhost-in-etc-hosts

Closing.
