### ISSUE TITLE
Stupid question? hp host vs yours

### ISSUE THREAD

**Issue by Droyk** [StevenBlack/hosts#262]
@StevenBlack I am a user of hp host just knew this project so I want to know which is best one [hp host](https://hosts-file.net/?s=Download) or yours I saw you have way less hosts then hp?

**Comment by StevenBlack** [comment]
@Droyk the primary difference is:

* Hosts here come from actively curated sources.  It seems implausible to me that a host source with 573,000 hosts changes so little, one way or another.  In my view, personal judgment, hp-hosts needs ten-times current activity before I consider it "curated".

* Hosts here strike a balance between size and usability.  Hp-hosts is an 18mb hosts file.  Good luck with that on most MS Windows installation, or on mobile devices.

**Comment by Droyk** [comment]
I want to know which blocks the most I am not tech geek my friend suggested me hp host so I installed it and didn't have any problems so far that's why I asked

**Comment by Droyk** [comment]
@StevenBlack which blocks the most?

**Comment by StevenBlack** [comment]
@Droyk  The number we block is in the `readme`:  between 35,336 and 45,487 depending on your selected mix.

hp-hops blocks 570,000+.

**Comment by Droyk** [comment]
So as I said above it seems that hp is best in blocking of adware and malware

**Comment by StevenBlack** [comment]
Whatever you say.

Closing.

**Comment by Droyk** [comment]
do you think I am not correct? if not will you be able to tell me why I am not correct?
