### ISSUE TITLE
DNS Client overloaded when using biggest host file, causing "permanent" internet connection loss

### ISSUE THREAD

**Issue by Master-64** [StevenBlack/hosts#2620]
When using a KVM, I've noticed that using one of the massive host files will end up essentially bricking the Windows 10 DNS Client application service that runs in the background. This in turn causes noticeable software slowdown across the entire system, and also prevents any and all proper internet connections. Due to how the DNS Client is bricked, it prevents all writing to the host file, and it never gets resolved (+ what seemed like a memory leak was occurring, alongside a considerable amount of CPU usage, leaving this client running for hours never fixed itself). Manually closing the DNS Client seemed to not allow the host file to be reverted, so you'd essentially be stuck without internet if you were an average user.

The only method I was able to use to recover the DNS Client from essentially bricking the system's NAT was to use the registry editor to prevent the DNS Client service from being automatically ran, then clearing the hosts file.

I'm unsure whether the KVM is causing the issue (as it virtualizes the NAT) or whether it's a separate issue.

My test bench ran on Windows 10 10.0.19045 Build 19045, using this repository's Release 3.14.62, using this host file: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts

**Comment by StevenBlack** [comment]
Thank you for this @Master-64.

Have you read [Warning: Using this hosts file in Windows may require disabling DNS Cache service](https://github.com/StevenBlack/hosts) in our readme file?

As far as I can tell, this is all documented, yes?

**Comment by Lateralus138** [comment]
@Master-64 Fair warning that if you use the disabling DNS cache method then things like WSL will not be accessible.
