### ISSUE TITLE
Add Snapchat to the social list

### ISSUE THREAD

**Issue by PitWenkin** [StevenBlack/hosts#2626]
Would it be possible to add Snapchat to the social list?

Some of the domain they use:

- accounts.snapchat.com
- api-kit.snapchat.com
- app-analytics-v2.snapchat.com
- app.snapchat.com
- asia-southeast1-gcp.api.snapchat.com
- aws.api.snapchat.com
- aws-cf.api.snapchat.com
- aws.duplex.snapchat.com
- aws-proxy-gcp.api.snapchat.com
- bitmoji.api.snapchat.com
- chat-gateway-prod.chat.snapchat.com
- click.snapchat.com
- direct-response-gcp.api.snapchat.com
- europe-west1-gcp.api.snapchat.com
- gcp.api.snapchat.com
- help.snapchat.com
- hoops.games.snapchat.com
- intg.snapchat.com
- jaguar-prod.snapchat.com
- lens.games.snapchat.com
- lens.snapchat.com
- link.snapchat.com
- mvm.snapchat.com
- premium-stories.snapchat.com
- pro-accounts.snapchat.com
- pro-stories.snapchat.com
- share.snapchat.com
- shows.snapchat.com
- sks.snapchat.com
- snapchat-com
- snapchat.com
- staging-us-east1-aws.api.snapchat.com
- static.snapchat.com
- story.snapchat.com
- support.snapchat.com
- topic-sticker-vending.snapchat.com
- tr6.snapchat.com
- tr.snapchat.com
- t.snapchat.com
- usc1-gcp-v61.api.snapchat.com
- usc1-gcp-v62.api.snapchat.com
- us-central1-gcp.api.snapchat.com
- use4-gcp-v4.api.snapchat.com
- use4-gcp-v6.api.snapchat.com
- us-east1-aws-acc.api.snapchat.com
- us-east1-aws-acc-test.api.snapchat.com
- us-east1-aws.api.snapchat.com
- us-east1-aws-cf.api.snapchat.com
- us-east1-aws.gateway.snapchat.com
- us-east-1-bitmoji.api.snapchat.com
- us-east4-gcp.api.snapchat.com
- us-east4-gcp-ineg.api.snapchat.com
- webattachments.snapchat.com
- web.snapchat.com
- www.snapchat.com

Possibly their own CDN:
- cf-st.sc-cdn.net

Domain of the parent company:
- marketing-web-api.snap.com
- snap.com

**Comment by StevenBlack** [comment]
Thank you for this Pit @PitWenkin.

Ping @sinfonietta for inclusion.

**Comment by PitWenkin** [comment]
Some more domains:

- app-analytics-v2.snapchat.com
- aws-proxy-gcp.api.snapchat.com
- aws.duplex.snapchat.com
- us-east1-aws.api.snapchat.com
- us-east4-gcp.api.snapchat.com
- usc1-gcp-v62.api.snapchat.com

**Comment by PitWenkin** [comment]
Some more domains:
- app.snapchat.com
- europe-west1-gcp.api.snapchat.com
- topic-sticker-vending.snapchat.com
- tr6.snapchat.com
- tr.snapchat.com
- us-east1-aws-acc.api.snapchat.com

**Comment by StevenBlack** [comment]
Pit @PitWenkin did you know... you can edit issues you create, and your comments, so appending to an existing list is easy.

**Comment by PitWenkin** [comment]
> Pit @PitWenkin did you know... you can edit issues you create, and your comments, so appending to an existing list is easy.

As I don't know if someone is already working on this, I did not want to edit the original list, will do from now on ;)

**Comment by StevenBlack** [comment]
It's always easier to deal with one, unified thing.

Subsequent comments means, whoever acts will need to scroll to even notice the amendments.

**Comment by PitWenkin** [comment]
I've merges the orignal list and the two updates into on list together with some new domains I found

**Comment by Sinfonietta** [comment]
@StevenBlack I think I just merged this on my end

**Comment by PitWenkin** [comment]
> @StevenBlack I think I just merged this on my end

Yes, you did
