### ISSUE TITLE
Amplitude.com completely blacklisted by Adaway

### ISSUE THREAD

**Issue by 3x071c** [StevenBlack/hosts#2627]
Hi! I tracked down an issue with Amplitude.com (an analytics service) being blocked to one of your aggregated host files from adaway.org. I would've normally contacted them but their host file doesn't seem to be open source and if I understand correctly you are maintaining a cached version of the dormant list. The API endpoints for user tracking (data ingestion) are all at specific subdomains like `api*.amplitude.com`, Peter Lowe has [included them exactly](https://github.com/search?q=repo%3AStevenBlack%2Fhosts%20amplitude&type=code). Adway blacklists the entire `amplitude.com` domain, which is less precise. Could you remove this entry? (I'm not affiliated with amplitude, was just curious and noticed it was blocked)

**Comment by StevenBlack** [comment]
Thank you for this Victor @3x071c.  This is a reasonable request and, you're right, I'm wary of blocking root domains that are not used as vectors for adware, tracking, or worse.

This is resolved in commit 7f4075c8 and will go live soon.

Closing.
