### ISSUE TITLE
Please add spiegel.com because it's NOT the english version of german newspaper spiegel.de

### ISSUE THREAD

**Issue by thomasmerz** [StevenBlack/hosts#2629]
The title says it all. Just have a look at it - how many people have gone there by accident because they mistyped `.de` or thought it would be the english version!? 😱

**Comment by StevenBlack** [comment]
Hello Thomas @thomasmerz thank you for this.

It's not in our mission to do that.

That said, ping @sinfonietta for inclusion in our porn list.

**Comment by thomasmerz** [comment]
Done: https://github.com/Sinfonietta/hostfiles/pull/307
