### ISSUE TITLE
Youtube history - enable history?

### ISSUE THREAD

**Issue by Chompyy** [StevenBlack/hosts#263]
This isn't an issue persay, but I notice after applying all the Hosts, I am losing the functionality to have youtube video history. How would I enable the youtube video history? A lot of times I watch a few videos and would like to go back into Youtube history to find it again.

I read from a few posts disabling s2.youtube.com could help, is there any other hosts that I need to remove as well to enable history again? 

Thanks!

**Comment by Chompyy** [comment]
Hi Steven,
I tried removing s2.youtube.com, and so far the history on my youtube account doesn't seem to grab previously watched videos. I watched a few videos earlier this morning and they don't appear in the history at all. Is there anything extra I would have to remove from the hosts file?

**Comment by StevenBlack** [comment]
@Chompyy ... I didn't know that youtube video history is a thing.  Interesting.  Well, this is something you know.  When you figure this out, please tell us what worked for you.  

By the way, I recommend [Pinboard](https://github.com/moment/moment/issues/166) to preserve and curate your finds.

**Comment by Jezza-x3** [comment]
It's s.youtube.com and s2.youtube.com that are both required. (Well at least s.youtube.com is.) I know because I have both excluded from the list and the youtube history works for me.

**Comment by Chompyy** [comment]
@Jeza-x3, thanks! I'll give this a try and report back if it works! Appreciate the help

**Comment by Jezza-x3** [comment]
@Chompyy Any news?

**Comment by Chompyy** [comment]
@Jezza-x3 @StevenBlack , So what ending up working was Jezza suggestion of removing both s.youtube & s2.youtube. Now i'm not sure if both need to be removed, but I have removed both for now :)

**Comment by StevenBlack** [comment]
@Chompyy great!  Closing.
