### ISSUE TITLE
allow stat counter

### ISSUE THREAD

**Issue by userforsource** [StevenBlack/hosts#2630]
https://gs.statcounter.com/os-market-share/desktop/worldwide
This is just a brand that tracks market share of desktop and os and stuff.

**Comment by StevenBlack** [comment]
Thank you for this @userforsource.

[We've talked about Statcounter before](https://github.com/search?q=repo%3AStevenBlack%2Fhosts+statcounter&type=issues) and this isn't going to change.

Closing.
