### ISSUE TITLE
adbox.lv and b.adbox.lv

### ISSUE THREAD

**Issue by ugjka** [StevenBlack/hosts#2631]
Add adbox.lv and b.adbox.lv to the blocklist. Those domains serve ads for Latvia's biggest email provider.

**Comment by StevenBlack** [comment]
Thank you for this Uģis @ugjka.

We generally don't block company websites, only the subdomains they use to deliver adware, tracking, or worse.  Advertising is a legal business employing millions of people worldwide.  We're not here to deplatform companies, just their pipelines.

**Comment by ugjka** [comment]
Their domain is inbox.lv

**Comment by ugjka** [comment]
Oh, I see, the ad delivery is done via b.adbox.lv and adbox.lv shouldn'd be blocked
