### ISSUE TITLE
Unblock fast.appcues.com

### ISSUE THREAD

**Issue by BlueCannonBall** [StevenBlack/hosts#2633]
The unified hosts + adware + malware list has this domain, even though blocking it totally breaks some of the College Board's websites. See https://myap.collegeboard.org, where a script loaded from this domain is required to display anything at all.

**Comment by StevenBlack** [comment]
Thank you for this @BlueCannonBall.

I have written this many times before. Here it is again.

> It doesn't matter if listing a domain interferes with fundraising by the Holy Sisters relict of Mother Theresa of Calcutta. If the domain vehicles tracking, adware, or worse, it gets listed here. This project serves people who value privacy and online safety.

So the issue here belongs to College Board; Please take this up with them. 

Closing.
