### ISSUE TITLE
## Inefficient regular expression

### ISSUE THREAD

**Issue by namka279** [StevenBlack/hosts#2634]
## Inefficient regular expression

This part of the regular expression may cause exponential backtracking on strings containing many repetitions of '..'.

[Show more details](https://github.com/StevenBlack/hosts/security/code-scanning/20)

_Originally posted by @github-advanced-security in https://github.com/StevenBlack/hosts/pull/2400#discussion_r1290244171_

**Comment by funilrys** [comment]
I can look into this, but please give us a working link and example that we can integrate into our tests.

Otherwise, I recommend closing this issue.

**Comment by funilrys** [comment]
Okay, I found the reference: https://github.com/StevenBlack/hosts/pull/2400#discussion_r1572687558 

@StevenBlack, please close as per https://github.com/StevenBlack/hosts/pull/2400#discussion_r1573227094 .

Thank you for your time @namka279.
