### ISSUE TITLE
Authentic domain being blocked 

### ISSUE THREAD

**Issue by wealstarrr** [StevenBlack/hosts#2635]
Hello,

HOSTS file block click.discord.com which is an authentic domain that verifies the geolocation of the user and validate their IP address to be able to login to the Discord app. 

Please whitelist this domain, it's not ad, malware, annoyance or anything else.

Domian: https://click.discord.com

Kind regards

**Comment by m-klecka** [comment]
click.discord.com is also used to verify email address for discord

**Comment by iam-py-test** [comment]
[This issue has been discussed before](https://github.com/StevenBlack/hosts/issues?q=click.discord.com).
click.discord.com is primarily used for tracking links in emails, and as such StevenBlack has decided to blocklist it.
Unless new information has come to light, I doubt they will reconsider.
In the future, please check for existing issues before opening a new one.
Thank you

**Comment by m-klecka** [comment]
> [This issue has been discussed before](https://github.com/StevenBlack/hosts/issues?q=click.discord.com).
> click.discord.com is primarily used for tracking links in emails, and as such StevenBlack has decided to blocklist it.
> Unless new information has come to light, I doubt they will reconsider.
> In the future, please check for existing issues before opening a new one.
> Thank you

If it's been discussed then it should be unblocked. The link also has legitimate use besides tracking - you cannot confirm the creation of discord account unless you go through that link, which they provide only though click.discord.com and theres no other way. Blocking this makes discord unusable.

**Comment by iam-py-test** [comment]
> click.discord.com is **primarily** used for tracking links in emails

and the policy of this list is to block any website which is primary used for tracking.
If you disagree with that policy, you may allowlist the domain yourself.
Additionally, you can contact Discord and request they stop tracking their users. Ultimately, it is their fault for using a tracking domain in account creation emails. Obviously they probably won't care, but it's worth a try. 
In any case, I am not the maintainer of this list; this is not my decision to make. I am just trying to provide information.
Thank you.

**Comment by StevenBlack** [comment]
@m-klecka and @wealstarrr this issue should be raised with Discord. Tell them, mixing scummy into their core workflows is a choice. Discord gets no free pass here.

Thank you for the assist @iam-py-test.
