### ISSUE TITLE
Remove legitimate research company domain

### ISSUE THREAD

**Issue by AHaymond** [StevenBlack/hosts#2638]
I work for TapResearch and recently discovered after enabling this host list via ControlD that my companies domain is included. I would like to work to work with you to get that removed from the list. Please let me know what we can do to remove our domain and keep it off.

Effected domain:

tapresearch.com

**Comment by StevenBlack** [comment]
Thank you for this Adam @AHaymond.

The domain `www.tapresearch.com` is removed in commit c2b40a35 and that will reflect in the next release.

Closing.

**Comment by ler762** [comment]
> The domain www.tapresearch.com is removed in commit c2b40a3
<https://github.com/StevenBlack/hosts/commit/c2b40a35beb278e79ab1a43d63e62452aa3ee551>
and that will reflect in the next release.

It looks like they go for www.tapresearch.com if api.tapresearch.com is
blocked:

13-Apr-2024 18:05:49.976 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#59365 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/HTTPS/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 18:05:49.976 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#60043 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/AAAA/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 18:05:49.976 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#52644 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/A/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 18:05:50.160 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#59094 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/HTTPS/IN via www.tapresearch.com.rpz.zone
13-Apr-2024 18:05:50.160 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#53905 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/AAAA/IN via www.tapresearch.com.rpz.zone
13-Apr-2024 18:05:50.160 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#61884 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/A/IN via www.tapresearch.com.rpz.zone
13-Apr-2024 18:11:00.188 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#52576 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/HTTPS/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 18:11:00.188 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#52325 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/AAAA/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 18:11:00.188 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#50088 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/A/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 18:11:00.204 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#50029 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/HTTPS/IN via www.tapresearch.com.rpz.zone
13-Apr-2024 18:11:00.204 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#54808 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/AAAA/IN via www.tapresearch.com.rpz.zone
13-Apr-2024 18:11:00.204 rpz: info: client @0x7fnnn
2600:4040:xx:xx::1111#62547 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/A/IN via www.tapresearch.com.rpz.zone
13-Apr-2024 18:29:14.373 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#49460 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/HTTPS/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 18:29:14.373 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#57446 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/AAAA/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 18:29:14.373 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#52319 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/A/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 18:29:14.425 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#53764 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/HTTPS/IN via www.tapresearch.com.rpz.zone
13-Apr-2024 18:29:14.425 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#51164 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/AAAA/IN via www.tapresearch.com.rpz.zone
13-Apr-2024 18:29:14.425 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#63481 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/A/IN via www.tapresearch.com.rpz.zone
13-Apr-2024 22:23:52.149 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#51436 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/HTTPS/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 22:23:52.149 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#53980 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/AAAA/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 22:23:52.149 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#63444 (api.tapresearch.com): rpz QNAME NXDOMAIN
rewrite api.tapresearch.com/A/IN via api.tapresearch.com.rpz.zone
13-Apr-2024 22:23:52.173 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#54527 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/HTTPS/IN via www.tapresearch.com.rpz.zone
13-Apr-2024 22:23:52.173 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#55152 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/AAAA/IN via www.tapresearch.com.rpz.zone
13-Apr-2024 22:23:52.173 rpz: info: client @0x7fnnn
2600:4040:xx:xx::2222#52409 (www.tapresearch.com): rpz QNAME NXDOMAIN
rewrite www.tapresearch.com/A/IN via www.tapresearch.com.rpz.zone
