### ISSUE TITLE
host removal request

### ISSUE THREAD

**Issue by dmnc-net** [StevenBlack/hosts#2639]
file: hosts#L126835
host: `h.seznam.cz` (host for loading ad scripts)
affecting services: all from the Seznam company, i.e. mapy.cz, email.cz, ...

Reason: Seznam is now offering ad-free products (their whole ecosystem) with a subscription. So on the 1st visit of any product of the ecosystem, the user is redirected to `https://cmp.seznam.cz/nastaveni-souhlasu`, it is a consent about ads and without choosing (pay or stay with ads) one can't continue. This page checks this file: `https://h.seznam.cz/js/cmp2/scmp-cw.js` or throws the error.

At this moment I'm whitelisting `h.seznam.cz`. I don't know if it is possible to negotiate with Seznam about skipping `h.seznam.cz` for this consent redirect, but I don't believe that.

**Comment by StevenBlack** [comment]
Thank you for this @dmnc-net.

The domain `h.seznam.cz` comes to us from upstream at https://someonewhocares.org.

Please make your case by email to Dan Pollock at hosts@someonewhocares.org.

Closing.
