### ISSUE TITLE
Can no longer verify discord email because `click.discord.com` is blocked

### ISSUE THREAD

**Issue by vincejv** [StevenBlack/hosts#2641]
domain `click.discord.com` is used for verifying emails on a new discord account

**Comment by StevenBlack** [comment]
Thank you for the assist @strotee.

Vince @vincejv as you can see, we've discussed this before and this is not going to change.

Closing.

**Comment by ler762** [comment]
On Mon, Apr 29, 2024 at 3:27 PM Vince JV wrote:

> If this you policy, thank you so much for clarifying, will remove your
> blocklist from now pn my network and if someone points out on a public
> forum like reddit that the website is not working, my first suggestion
> would be to remove this list.
>

With all due respect, if you don't keep an allow-list that allows traffic
to sites that are in a block-list you're Doing It Wrong.
