### ISSUE TITLE
Error with Line 22

### ISSUE THREAD

**Issue by Chrome-GitHub** [StevenBlack/hosts#2644]
Title: StevenBlack/hosts
Date: 04 May 2024 02:31:28 (UTC)

Potential bug at line 22:
fe80::1%lo0 localhost

dnsmasq log:
May  4 16:40:24 dnsmasq[389259]: bad address at /zram/hosts line 22

Notes:
Once line 22 was manually deleted, then it loads without the error message

**Comment by StevenBlack** [comment]
Hello @Chrome-GitHub thank you for this!  We've discussed this before...

* https://github.com/StevenBlack/hosts/issues/2616
* https://github.com/StevenBlack/hosts/issues/2473
* ... and others

This is not an error.  Well, it is an error at DSNMasq. Someone should report this to them 😉 

Closing.
