### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by viktorhungary** [StevenBlack/hosts#2645]
Neither discord nor the DeepL desktop application works

**Comment by xRuffKez** [comment]
```s.deepl.com``` needs to be allowed

**Comment by StevenBlack** [comment]
Thank you for this @viktorhungary.

Discord has multiple issues — we've discussed this many times before here.  It's completely up to Discord to clean up its practices.  Please raise this issue with Discord.

This won't change here.

Closing.
