### ISSUE TITLE
Add to Gambling

### ISSUE THREAD

**Issue by mirokrastev** [StevenBlack/hosts#2648]
These popular gambling sites in Bulgaria are not blocked:
www.palmsbet.com
www.betano.bg
www.pokerstars.bg
everbet.bg
slotino.bg

The first three are contained in the Gambling adlist, but without the `www` subdomain.

**Comment by StevenBlack** [comment]
Thank you Miroslav @mirokrastev!

Ping @sinfonietta for evaluation and inclusion.

**Comment by Sinfonietta** [comment]
@StevenBlack this is done!

**Comment by StevenBlack** [comment]
Thank you again @Sinfonietta and thanks also @mirokrastev.
