### ISSUE TITLE
whitelist -> services.brid.tv

### ISSUE THREAD

**Issue by scafroglia93** [StevenBlack/hosts#2649]
I would like to inform you that the following domain is used within the site www.gazzettadimodena.it

The block prevents access to the service

![immagine](https://github.com/StevenBlack/hosts/assets/8227101/47a8bb7e-7632-4879-8a6c-93ec0a07e914)

Cheers

**Comment by StevenBlack** [comment]
Thank you for this Lorenzo @scafroglia93.

If *Gazetta Di Modena* crashes when domain `services.brid.tv` is unreachable, this is a bug, and it belongs to *Gazetta Di Modena*, not us.

Closing
