### ISSUE TITLE
list with dnsmasq

### ISSUE THREAD

**Issue by ghithhhub222345** [StevenBlack/hosts#265]
hello, 
can we also have lists for dnsmasq /dnsmasq with server?
or can anyone help me how to convert the hosts file to dnsmasq?

**Comment by oznu** [comment]
I have a project that converts the standard Unified Hosts File (adware + malware) to dnsmasq/bind formats which might help.

https://github.com/oznu/dns-zone-blacklist

You could also use the hosts file in dnsmasq directly.

**Comment by sarming** [comment]
i think configuring dnsmasq to use it as an additional host file should work just fine

**Comment by erlepereira** [comment]
Alternatively, to do this via shell you can use something like this:
wget -O- <insert LINK to the file you choose> | awk '$1 == "0.0.0.0"  { print "address=/"$2"/0.0.0.0/"}' > /etc/dnsmasq.d/malware.conf

example:
`wget -O- https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts | awk '$1 == "0.0.0.0"  { print "address=/"$2"/0.0.0.0/"}' > malware.conf`

you could also use that line in a cron job to have it run periodically

**Comment by dgoerger** [comment]
Don't forget to print an extra line for IPv6, per #47. I use [this script](https://github.com/dgoerger/dotfiles/blob/7e920e081ec9d8ff440f76511e331d06b6dbae3d/cookbooks/workstation/files/dnsblock_updater), although @erlepereira's script uses awk more elegantly and I may update mine accordingly. 😄

**Comment by ScriptTiger** [comment]
As mentioned in #47, can someone draft something for the "Interesting Applications" section on this so this issue can be closed?

**Comment by dgoerger** [comment]
@ScriptTiger I believe the `nxdomain` variants of @oznu's [repo](https://github.com/oznu/dns-zone-blacklist) should handle both ipv4 and ipv6 without any additional configuration. At least, this is true of nxdomain behaviour under BIND9 and Unbound on Fedora and OpenBSD.

**Comment by erlepereira** [comment]
@ScriptTiger I have created a quick gist with some notes and a script file I use in cron to achieve the above in dnsmasq 
gist -- https://gist.github.com/erlepereira/c11f4f7a3f60cd2071e79018e895fc8a

I could add more if needed, but I think it would suffice for the 'Interesting Applications" section. Let me know if more would be required.

**Comment by ScriptTiger** [comment]
That's up to Steven. I think recently he has been leaning towards supporting different formats internally, as he referenced in https://github.com/StevenBlack/hosts/issues/434. But as we don't really offer any Python script support or a README reference at the moment, I'm sure a PR for either would be welcomed at this point since we definitely get enough issues about it.
