### ISSUE TITLE
add {a,s}.{pem,meg}srv.com

### ISSUE THREAD

**Issue by cattokomo** [StevenBlack/hosts#2651]
a.pemsrv.com
s.pemsrv.com
a.megsrv.com
s.megsrv.com

Reason: Porn ads

**Comment by StevenBlack** [comment]
Ping @sinfonietta for inclusion

**Comment by Sinfonietta** [comment]
@StevenBlack these are added

**Comment by StevenBlack** [comment]
Thank you @Sinfonietta and thanks again @cattokomo.
