### ISSUE TITLE
Remove pipenv.org from blocked hosts

### ISSUE THREAD

**Issue by Crissal1995** [StevenBlack/hosts#2653]
Why are they being blocked in the first place?

**Comment by StevenBlack** [comment]
Hello Christiano @Crissal1995 thank you for this issue.

Please see issue #1635 for the reasons why various `pipenv.org` domains are blocked.

Closing.

**Comment by Crissal1995** [comment]
Oh, didn't catch this thread.

Thanks for the info, I removed it from my whitelist.
