### ISSUE TITLE
ck.ads.oppomobile.com block it

### ISSUE THREAD

**Issue by userforsource** [StevenBlack/hosts#2655]
This is a ads website

**Comment by StevenBlack** [comment]
Thank you for this @userforsource.

Please do not submit issues here without full details and documentation supporting your claims.

I am not keen on accepting issues from anon.

Closing.

**Comment by userforsource** [comment]
This is a advertisement website how can i give you more info i have an oppo device i find this and i post here.
If you don't want to include you are free to do so but i find hagezi and adguard blocks it. Thanks
