### ISSUE TITLE
Stray space in "urdxh.com" domain name just added

### ISSUE THREAD

**Issue by akorn** [StevenBlack/hosts#2656]
Hi, in e07d760324bbfd1aa39c29ce5d96e6c390faad8e you added the line

```
0.0.0.0 urdxh .com
```

That space character makes ".com" an alias for "urdxh", which I don't think is intended.

**Comment by StevenBlack** [comment]
Thank you very much András @akorn. Fixed!  And fixed prior to its release 😄.
