### ISSUE TITLE
Whitelist s.youtube.com

### ISSUE THREAD

**Issue by McBruno712** [StevenBlack/hosts#2657]
Libre DNS is blocking YouTube app from logging watch history since YouTube changed how it works this February. 

For it to work again we will need to whitelist s.youtube.com

**Comment by StevenBlack** [comment]
Thank you for this Bruno @McBruno712 this has been discussed here many times before, and what you ask is not gonna happen.  

Please see these repo search results which, honestly, would have been a trivially minimum effort from you before opening this issue.

https://github.com/StevenBlack/hosts/issues?q=is%3Aissue+s.youtube.com+

Closing.
