### ISSUE TITLE
Blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [StevenBlack/hosts#2662]
[i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 238508 exact domains and 0 ABP-style domains (ignored 8 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"
        - "porngifs.ca.netisrouter_bc62ce4b1d4f"
        - "gif-porn.net.netisrouter_bc62ce4b1d4f"
        - "porngifer.com.netisrouter_bc62ce4b1d4f"
        - "www.xnxxsks.com.netisrouter_bc62ce4b1d4f"

**Comment by StevenBlack** [comment]
Thank you for this @AyanokojiK1yotaka.

Ping @sinfonietta!  These `_bc62ce4b1d4f` suffixes come from your porn list. Can you please fix?  Thanks!

**Comment by Sinfonietta** [comment]
@StevenBlack this is fixed
