### ISSUE TITLE
add backup?

### ISSUE THREAD

**Issue by stokebreakup** [StevenBlack/hosts#2664]
What if all hosts files are hosted and shared in a decentralized way?

**Comment by StevenBlack** [comment]
Thank you for this @stokebreakup.

Can you write up what you mean by this?

**Comment by StevenBlack** [comment]
@stokebreakup I certainly hear 'ya.

On one hand, if GitHub ceases to exist, we've got 99 other problems 😄 

This repo has been mirrored into Gitlab for many years....

https://gitlab.com/StevenBlack/hosts

This repo has been forked a few thousand times.... I think we're OK. Maybe I should mirror to [SourceHut](https://sr.ht/~stevenblack/) as well.

**Comment by StevenBlack** [comment]
Thanks @stokebreakup I think we're good.

Closing.
