### ISSUE TITLE
Not working on Chinese sites

### ISSUE THREAD

**Issue by OshekharO** [StevenBlack/hosts#2666]
Ads are not being blocked not Chinese sites, none of your filter worked.

Example: https://m.xs777.org/shu/269380/231867072.html

**Comment by StevenBlack** [comment]
Thank you for this @OshekharO.

Unfortunately there is nothing actionable raised by this issue so I am closing this now.  

If the hosts file isn't having an effect this is surely a situation-local problem, for example tunnelling through a VPN, or Tor, or something else.
