### ISSUE TITLE
Blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [StevenBlack/hosts#2667]
[i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 241524 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"

**Comment by StevenBlack** [comment]
Thank you for this @AyanokojiK1yotaka.

This is not a bug.

Closing.
