### ISSUE TITLE
gc.zgo.at

### ISSUE THREAD

**Issue by prk60091** [StevenBlack/hosts#2668]
I am wondering what the rationale is for blocking gc.zgo.at  

It is merely a tool to provide the website with statistics as to page views. It does not track- It does not serve ads It counts visitors to a webpage

**Comment by StevenBlack** [comment]
Thank you for this @prk60091.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [shreyasminocha/shady-hosts](https://github.com/shreyasminocha/shady-hosts/issues).

Closing.

**Comment by prk60091** [comment]
I just did as you suggested- however it does not appear that ‘anybody is there anymore’— there are open issues from last year and the last update was 9 months ago.

**Comment by StevenBlack** [comment]
Thanks @prk60091 let's see what happens.

Ping @shreyasminocha!

**Comment by StevenBlack** [comment]
Done!  @prk60091 this will reflect in the next release, coming soon.

**Comment by prk60091** [comment]
thank you-
keep up the good fight
