### ISSUE TITLE
[FALSE POSITIVE] Malwarebytes flags hosts file as malware

### ISSUE THREAD

**Issue by robinhood2014** [StevenBlack/hosts#2669]
After hearing about yet another vulnerability in Windows, I decided to boost my Internet security by installing Malwarebytes. When I ran my initial scan, I noticed that it flagged a modified version (using hostcompress-x64.exe) of your hosts file as malware! I've used this hosts file for quite some time and never had any malware issue before, so why has Malwarebytes chosen _now_ to warn me about what I strongly believe to be a false positive? I'm enclosing the scan log.
[false-positive.txt](https://github.com/user-attachments/files/15848234/false-positive.txt)

**Comment by iam-py-test** [comment]
[Report the false positive to Malwarebytes](https://forums.malwarebytes.com/forum/42-file-detections/).
Thanks

**Comment by Lateralus138** [comment]
And in my response to his same issue with my tool that created his hosts file:
[https://github.com/Lateralus138/hosts-compress-windows/issues/3](https://github.com/Lateralus138/hosts-compress-windows/issues/3)

**Comment by StevenBlack** [comment]
Thank you for this Brandon @robinhood2014.

There's nothing we can do about that. But thank you for the heads-up.

Closing.

**Comment by iam-py-test** [comment]
[Malwarebytes has fixed the detection for the Hosts Compress tool](https://forums.malwarebytes.com/topic/313512-hostscompressexe/)
