### ISSUE TITLE
Youtube "Skippable video ads" can't be removed

### ISSUE THREAD

**Issue by AngelTsTsvetkov** [StevenBlack/hosts#267]
At present we f...k 3 of 4 types youtube ad: "Display ads", "Overlay ads" and "Sponsored cards".
Good for us!
But the 4th type- "Skippable video ads" still f...k us. So any ideas?

**Comment by Jezza-x3** [comment]
@AngelTsTsvetkov What browser/OS?

**Comment by AngelTsTsvetkov** [comment]
IE11/Windows Insider Preview 15061

**Comment by Jezza-x3** [comment]
@AngelTsTsvetkov Any reason you are using Internet Explorer even though it's pretty much deprecated?

**Comment by AngelTsTsvetkov** [comment]
IE11 is the MOST SECURED browser if you know how to set property security settings and zones!!!
Even Edge can't do that- Chrome and Firefox (and Edge) are for child, not for professionals!!!
Thats why from years i do not use any realtime antivirus/adware/etc and have not any speed or security problems. From years!!!
Is it enough reasons?

**Comment by Jezza-x3** [comment]
Alright. Well I don't have IE so I can't exactly test the hosts file compatibility with the skip ads. Do you have any exclusions set in your hosts file? 

If not I'd recommend you to get adblock plus for IE as I don't know if any alternative.

**Comment by Jezza-x3** [comment]
Also when did you last update your hosts file? Have you experienced this recently or always? When did it start?

**Comment by AngelTsTsvetkov** [comment]
1.exclusions sets: s.youtube.com, s2.youtube.com to be able to use history red line in youtube
2.adblock plus have bug and not work in my browser/OS->this is the main reason to find this place some weeks ago
3.last host update- 2-3weeks from now.
4.I have experienced always (from 2-3weeks as I found this site)

**Comment by AngelTsTsvetkov** [comment]
Open this site and see if you see the skip video advertisement in the beginning?
https://www.youtube.com/watch?v=czhJfC1SuU0&t=267s

**Comment by Jezza-x3** [comment]
Please update your hosts file with the latest one and check again. 

You could try using an adblock DNS server. Google DNS adblock and try the first one or second and tell me your luck. 

I never have ads on my PC. I use adblock and the hosts file with beta Google​ Chrome. I'm on mobile so I can't exactly test it now. Sorry about that.

**Comment by Jezza-x3** [comment]
@AngelTsTsvetkov I do have the skippable ads show up while having adblock off with the hosts file enabled.

**Comment by AngelTsTsvetkov** [comment]
The problem with skippable ads is much bigger than update the hosts fileor using DNS server

**Comment by StevenBlack** [comment]
I'm closing and locking this thread.
