### ISSUE TITLE
unblock wl.spotify.com

### ISSUE THREAD

**Issue by Mtillmann** [StevenBlack/hosts#2673]
I don't know if Spotify is delivering ads through that domain but it is extensively used for Account Management (Unsubscribe from Mail, Passwort recovery etc). Blocking this domain breaks the aforementioned features, which IMO creates more problems than it is worth.

**Comment by StevenBlack** [comment]
Thank you for this, Martin.

We've discussed the domain `wl.spotify.com` before, notably [here](https://github.com/StevenBlack/hosts/issues/1727), [here](https://github.com/StevenBlack/hosts/issues/2021), and [here](https://github.com/StevenBlack/hosts/issues/1015).

This isn't going to change.

Closing.

**Comment by Mtillmann** [comment]
Hi Steve, thanks for the feedback. I didn't find the issues. It's sad that spotify employs such shady tactics. What helped me in the end was the [pihole browser extension](https://github.com/badsgahhl/pihole-browser-extension?tab=readme-ov-file) which offers easy access to temporarily un/block certain domains!
