### ISSUE TITLE
network log

### ISSUE THREAD

**Issue by appledevs1** [StevenBlack/hosts#2674]
Hi,
i have some individuals pulling misc activities that are in violation to your code of conduct. Could you kindly help me understand why your github domain would be showing up several times in my network log? This has been an ongoing thing all while doing activities online that dont include gaming, app or website development, etc. Basically just normal stuff like google searching music, porn, shopping, and self help books and task. Also could you recommend a network tool that’s simple to understand and monitor dns hijacks phishing malware iphone mitm and or signs of pegasus useage/etc attempts?

**Comment by StevenBlack** [comment]
Thank you for this Anon @appledevs1.

There isn't anything actionable in your question, so I am closing this now.
