### ISSUE TITLE
Additional for privacy cockroaches

### ISSUE THREAD

**Issue by toviszsolt** [StevenBlack/hosts#2675]
- `(\.|^)amazon-adsystem\.com$` → amazon ads script
- `(\.|^)connect\.facebook\.net$` → meta pixel base script
- `(\.)posthog\.com$` → yet another hog, do it like `Session replay - Watch users interacting with your app or website.`

**Comment by StevenBlack** [comment]
Thank you for this Zsolt @toviszsolt.

There are no wild card characters in hosts files.  Also, we already block some of these.

Closing.

**Comment by toviszsolt** [comment]
@StevenBlack 

Yes, I can see that you are maintaining a host file, so I didn't open a PR, but an Issue.
I thought you would focus on the content rather than the format.

A useful tip: If you do not close the issue in front of the users, you give them a chance to communicate further. Usually users will close the issue.
