### ISSUE TITLE
Consider adding adsco.re subdomains

### ISSUE THREAD

**Issue by mensarunner** [StevenBlack/hosts#2679]
It appears adsco.re is in my PI-HOLE block list because yoyo.org includes it. However, some subdomains of adsco.re are not being blocked and I believe they should be. My PI-HOLE log shows these:

c.adsco.re
4.adsco.re
6.adsco.re
frwrz661fasv.l4.adsco.re

I initially planned to ask yoyo.org to add the subdomains but their site states "I only add top level ad server domains" and "Unfortunately, including all subdomains would be too time consuming for me". Can you please consider adding them? Thanks

**Comment by mensarunner** [comment]
It appears I missed a couple. Here are 2 more:

frwrz661fasv.n4.adsco.re
frwrz661fasv.s4.adsco.re

**Comment by StevenBlack** [comment]
Thank you @mensarunner.  These are added in commit 7d8475ddb.

Closing.
