### ISSUE TITLE
I have ads, im using 

### ISSUE THREAD

**Issue by zerotwo2** [StevenBlack/hosts#2680]
How to fix this ads?https://h5.g123.jp/game/tsukimichi?platform=exoclick&utm_source=exoclick&utm_campaign=tsukimichi_en_NewDisplayCpc_adn_sp&utm_adgroup=cr_normal_tier3_entertainment_cpc_and&exotracker=opdPPRHPVHVXHNZU4XXzqp5qK7Z3TSy21S2U0uldRLKqeqV1U0zqZnTummdXW6V0rqLK7bbrLXWVTzUS1OmrusmsqdK6Z0rpXSuldM6V0rpnV12by62bTaW2Z1xy001XS21TWXV22TWWTurq0o2r13p134on0ploplqtr4szm14prtdK4XWoSA3JGDcznOldK6V0rpXSuldK6V01k11VFl1FrnOldK6V0rpXSuldK6V0rrKd6tNc6KrdJaK5d.Npd6KtZ7Zq9rNrZnB9gA--&lang=en

This is the only one ads ihave when i browsing.

**Comment by zerotwo2** [comment]
![Uploading Screenshot_2024-06-28-10-12-25-684_com.android.chrome.jpg…]()

**Comment by zerotwo2** [comment]
![Screenshot_2024-06-28-10-12-25-684_com android chrome](https://github.com/StevenBlack/hosts/assets/36228728/cffce684-cebb-4662-a768-ad4d2c88742e)
AdAds

**Comment by StevenBlack** [comment]
Thank you for this @zerotwo2 but this is not help board for addressing individual websites 🙂

Closing.
