### ISSUE TITLE
Request to add kimcartoon.li to list of domains

### ISSUE THREAD

**Issue by pinckpockett** [StevenBlack/hosts#2689]
The site kimcartoon.li has a very tough anti adblock detector which makes it impossible to stream videos without disabling your adblocker and tracker protection in your browser.

Once you do so, you are greeted to popups, redirects, and ads that continued malware.

The site owner seems to show little regard for this issue and has even taunted ublock origin

Because of this, I believe that the site is essentially malware and there should be a consideration to add it to the malware blocklist.

**Comment by StevenBlack** [comment]
Thank you for this suggestion @pinckpockett.

We are not in the business of deplatforming businesses from the internet for reasons like this.

Therefore I decline your suggestion.

Closing.

**Comment by pinckpockett** [comment]
Thanks for getting to my request. If I may ask, what would be considered a site that would be added to your hosts file? Would that be the ad domains, but not the website it is hosted on itself?
