### ISSUE TITLE
makeHostsWindows.bat with four extension not work

### ISSUE THREAD

**Issue by AngelTsTsvetkov** [StevenBlack/hosts#269]
The follow code (of makeHostsWindows.bat) produce hosts file with size 1 055 132 but must be more than 1 300 000 bytes, so some extensions not work. OS windows insider preview + Python-3.6.0-embed-amd64 (not using blacklists)
________________________________________________________________________________________________________
:UPDATES
	::These create various alternate hosts files by combining and adding the gambling, porn, and social media extensions.
	updateHostsFile.py -a -z -n -o alternates/fakenews-gambling-porn-social -e fakenews gambling porn social
	::Update the readmes.
	updateReadme.py
	GOTO END

**Comment by StevenBlack** [comment]
This makes no sense, so I'm closing this.

@AngelTsTsvetkov here's how this is supposed to work.  If you find a problem

1) Fork the repo
2) Create a new branch.
3) Fix the code.
4) Test the code.
5) Push to your remote fork.
6) Submit a pull request.

Thanks.

**Comment by AngelTsTsvetkov** [comment]
the line "updateHostsFile.py -a -z -n -o alternates/fakenews-gambling-porn-social -e fakenews gambling porn social" not work

**Comment by AngelTsTsvetkov** [comment]
Hoe to produce hosts file with four extensions????
