### ISSUE TITLE
Crowdstrike Fake domains

### ISSUE THREAD

**Issue by pulpon6** [StevenBlack/hosts#2692]
Fake domains 

•	crowdstrike-helpdesk[.]com
•	crashstrike[.]com
•	bsodsm8r[.]xamzgjedu[.]com
•	crowdstrikebsodfix[.]blob[.]core[.]windows[.]net
•	crowdstrikecommuication[.]app
•	fix-crowdstrike-apocalypse[.]com
•	supportportal-crowdstrike-com[.]translate[.]goog
•	crowdstrike-cloudtrail-storage-bb-126d5e[.]s3[.]us-west-1[.]amazonaws[.]com
•	crowdstrikeoutage[.]info
•	clownstrike[.]co[.]uk
•	whatiscrowdstrike[.]com
•	clownstrike[.]co
•	microsoftcrowdstrike[.]com
•	crowdfalcon-immed-update[.]com
•	crowdstuck[.]org
•	failstrike[.]com
•	winsstrike[.]com
•	t[.]me/Crowdstriketoken
•	crowdstrikebluescreen[.]com
•	crowdstrike0day[.]com
•	crowdstrike-bsod[.]com
•	crowdstrikedoomsday[.]com
•	crowdstrikefix[.]com
•	crowdstrikedown[.]site
•	crowdstriketoken[.]com
•	fix-crowdstrike-bsod[.]com

**Comment by iam-py-test** [comment]
Some of these domains aren't actually malicious
i.e. clownstrike.co.uk is making fun of Crowdstrike

**Comment by StevenBlack** [comment]
Thank you for this Ricardo @pulpon6.

We aren't in the business of policing "fake" domains.  That would be an endless and hopelessly losing proposition.  It's just outside our mission, here.

Therefore I decline this suggestion.

Closing.
