### ISSUE TITLE
Overwolf Ad network

### ISSUE THREAD

**Issue by icedterminal** [StevenBlack/hosts#2697]
Curse Forge operator, Overwolf, has acquired ad and monetization network "NitroPay" which is now embedded in the Curse/Overwolf clients.

https://blog.overwolf.com/overwolf-acquires-gaming-ad-tech-leader-nitropay/

The following domain is the analytics portion and should be added to this list.
```
tracker.nitropay.com
```

It is currently found in the EasyPrivacy list when using uBlock.

**Comment by StevenBlack** [comment]
Thank you for this @icedterminal.

This is added in commit 2eaa823ea.

Closing.
