### ISSUE TITLE
Append blacklist to main hosts file by default

### ISSUE THREAD

**Issue by akavi1** [StevenBlack/hosts#2698]
I don't understand why the blacklist file isnt appended by default. If there is something added to the file, we can assume the user wants to blacklist those domains. The list is empty unless the user adds something to it, so appending the blacklist by default won't have any unwanted effects, and will only make it easier for those who utilize the blacklist.
Same goes for the whitelist

**Comment by StevenBlack** [comment]
Thank you for this @akavi1.

Please read the `readme.md` file, which explains what we do here, and how all this works.

Closing.

**Comment by akavi1** [comment]
Yea I read the readme. Still dont understand why this isnt enabled by default the way myhosts is blocked by default. Is the logic that the user might have multiple blacklist files with different filenames? Even then, It still makes sense to append the file named "blacklist" by default and have the user add on additional lists if necessary
`--blacklist <blacklistfile>, or -x <blacklistfile>: Append the given blacklist file in hosts format to the generated hosts file.`

**Comment by StevenBlack** [comment]
@akavi1 the reason this is not enabled by default is, we ship blacklists.  Lots of them. Every hosts file here is a black list.  It's what we do here: maintain lists of hosts.

You want to add your own blacklist?  You can do that. Knock yourself out. There's a flag for that.  It's there, specifically for you to use.

If creating a bash/batch file is too hard, to automate whatever you want to do downstream from us, then maybe using this raw project just isn't for you.
