### ISSUE TITLE
Problem with duplicate domain finder

### ISSUE THREAD

**Issue by akavi1** [StevenBlack/hosts#2699]
Example:
m.vk.com is included in the list of blocked porn domains. As a result, writing vk.com in the blacklist flie does not block the website. It thinks blocking m.vk.com is the same as blocking vk.com, but this is not the case. 
vk.com remains unblocked even if m.vk.com is on the hosts list

**Comment by StevenBlack** [comment]
Hi @akavi1 thank you for this.

I am having difficulty parsing what you've written above ⬆️.

Can you please state the problem as clearly and as concisely as possible, please?

I should probably mention, with hosts files, wild cards do not exist, and logical cascades do not exist.  So the domains `vk.com` and `m.vk.com` are separate and distinct, with no relation whatsoever to each other.

Hosts files are everywhere. They are also ancient artifacts from the earliest days of the internet.  Maybe this clarifies things?

If so, please close this issue.

**Comment by akavi1** [comment]
If you add vk.com to the blacklist file and run the updateHostsFile, vk.com does not get added to the main hosts file. But if you do the same thing with google.com for example, it does get added.

**Comment by StevenBlack** [comment]
@akavi1 please post your code.  Please first note that you must use the `--blacklist` flag in order to include the blacklist file in the final products.  THEN you have to clear your browser cache and quite likely your DNS cache as well.  This is all explained in the readme.

**Comment by StevenBlack** [comment]
Closing.
