### ISSUE TITLE
ping connect to blocked site if 0 is used instead of 0.0.0.0 

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#27]
When 0 is set instead of 0.0.0.0 in TARGET_HOST I can connecting with domains via ping:

    [tomasz@arch ~]$ ping -c 2 doubleclick.com
    PING doubleclick.com (173.194.113.72) 56(84) bytes of data.
    64 bytes from fra02s21-in-f8.1e100.net (173.194.113.72): icmp_seq=1 ttl=57 time=53.0 ms
    64 bytes from fra02s21-in-f8.1e100.net (173.194.113.72): icmp_seq=2 ttl=57 time=52.3 ms
    
    --- doubleclick.com ping statistics ---
    2 packets transmitted, 2 received, 0% packet loss, time 999ms
    rtt min/avg/max/mdev = 52.378/52.705/53.032/0.327 ms

    [tomasz@arch ~]$ ping -c 4 creative.ak.fbcdn.net
    PING a34.dsw4.akamai.net (2.18.213.218) 56(84) bytes of data.
    64 bytes from 2.18.213.218 (2.18.213.218): icmp_seq=1 ttl=59 time=59.8 ms
    64 bytes from 2.18.213.218 (2.18.213.218): icmp_seq=2 ttl=59 time=60.5 ms
    64 bytes from 2.18.213.218 (2.18.213.218): icmp_seq=3 ttl=59 time=60.1 ms
    64 bytes from 2.18.213.218 (2.18.213.218): icmp_seq=4 ttl=59 time=59.8 ms
    
    --- a34.dsw4.akamai.net ping statistics ---
    4 packets transmitted, 4 received, 0% packet loss, time 7133ms
    rtt min/avg/max/mdev = 59.828/60.080/60.527/0.333 ms

After revert to TARGET_HOST to value 0.0.0.0 I have:

    [tomasz@arch ~]$ ping -c 4 creative.ak.fbcdn.net
    PING creative.ak.fbcdn.net (127.0.0.1) 56(84) bytes of data.
    64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.052 ms
    64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.068 ms
    64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.066 ms
    64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.065 ms
    
    --- creative.ak.fbcdn.net ping statistics ---
    4 packets transmitted, 4 received, 0% packet loss, time 3001ms
    rtt min/avg/max/mdev = 0.052/0.062/0.068/0.011 ms

and now all is FINE. 

Please revert commit about changing TARGET_HOST from 0.0.0.0 in to 0. This just not work properly.

**Comment by lavventura** [comment]
czemu Polacy zawsze o wszystko muszą się rzucać? Ty już drugi raz.

**Comment by StevenBlack** [comment]
Hi @FadeMind, can I have a bit more info?  What OS are you using?

**Comment by FadeMind** [comment]
@StevenBlack archlinux x64, testing branch.

**Comment by StevenBlack** [comment]
Hmmm... OK.  I think I'll add a run-time question that asks if the user wants `0` or `0.0.0.0 (default)`.

But I'd love to know, what in archlinux (and possibly others) makes `0` problematic.

**Comment by FadeMind** [comment]
I made bash script for arch for automate updating hosts (and applying changes if needed).
https://github.com/FadeMind/archbash/blob/master/steven_black_custom_hosts_file/hup

Results when 0.0.0.0 is set as localhost

    [tomasz@arch ~]$ ping -c 1 0
    PING 0 (127.0.0.1) 56(84) bytes of data.
    64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.054 ms
    
    --- 0 ping statistics ---
    1 packets transmitted, 1 received, 0% packet loss, time 0ms
    rtt min/avg/max/mdev = 0.054/0.054/0.054/0.000 ms
    [tomasz@arch ~]$ ping -c 1 0.0.0.0
    PING 0.0.0.0 (127.0.0.1) 56(84) bytes of data.
    64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.052 ms
    
    --- 0.0.0.0 ping statistics ---
    1 packets transmitted, 1 received, 0% packet loss, time 0ms
    rtt min/avg/max/mdev = 0.052/0.052/0.052/0.000 ms
    [tomasz@arch ~]$ ping -c 1 creative.ak.fbcdn.net
    PING creative.ak.fbcdn.net (127.0.0.1) 56(84) bytes of data.
    64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.046 ms
    
    --- creative.ak.fbcdn.net ping statistics ---
    1 packets transmitted, 1 received, 0% packet loss, time 0ms
    rtt min/avg/max/mdev = 0.046/0.046/0.046/0.000 ms
    [tomasz@arch ~]$ cat /etc/hosts |grep localhost
    0.0.0.0 localhost 
    # This *must* be the first line: 127.0.0.1     localhost   #
    #<localhost>
    0.0.0.0 localhost.localdomain 
    #fe80::1%lo0    localhost
    #</localhost>
    [tomasz@arch ~]$ 

Regards
