### ISSUE TITLE
Spotify block - spclient.wg.spotify.com - search/home do not open.

### ISSUE THREAD

**Issue by ventz** [StevenBlack/hosts#270]
Hi,

Noticed that "spclient.wg.spotify.com" is on the pi-hole block list via https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts, but with that domain blocked, Spotify refuses to open the default screen/search/etc.

**Comment by FadeMind** [comment]
I cannot reproduce this issue. Spotify works fine on my side. Searching in Spotify and spotify web app works fine

**Comment by StevenBlack** [comment]
Confirming: Spotify works normally, search and all, with our hosts file.  

It worked with a 2-week old version and, after updating to the latest build a few minutes ago, it still works.

Using OS X.

**Comment by ventz** [comment]
This seems to occur on the iPad for some reason.

Make sure it's not cached -- it looks like the client(app) caches it after it can access it once for quite some time.

I just tried on a new iPad and it will not load the main screen while it's blocked.

**Comment by mpch** [comment]
The new HTML5 Spotify web version crashes with last version of the files 

There are lots of requests to this URL that fails 
spclient.wg.spotify.com
This URL is commented in line 13985 and it's added again in line 38514

**Comment by Mas0x** [comment]
Can confirm spotify (iOS) app does not work with due to the blick, very limited functionality....

**Comment by Mas0x** [comment]
That auto correct though 😂

**Comment by prometheanfire** [comment]
looks like it was noted and commented out, but then readded.

```
./hosts:# 0.0.0.0 spclient.wg.spotify.com #[affects mobile app]
./hosts:0.0.0.0 spclient.wg.spotify.com
```

**Comment by FadeMind** [comment]
@StevenBlack  @prometheanfire 

Revised in https://github.com/FadeMind/hosts.extras/commit/61f798c860e463b540889aed6a6df5066e85e5df

In future main hosts file update issue should be gone.

**Comment by StevenBlack** [comment]
Done Tomasz!  @FadeMind
