### ISSUE TITLE
Add to porn blocklist

### ISSUE THREAD

**Issue by nwanati** [StevenBlack/hosts#2703]
https://anyxxx.me/

**Comment by StevenBlack** [comment]
Thank you for this @nwanati.

Ping @sinfonietta for inclusion in our porn hosts.

**Comment by strotee** [comment]
This URL appears already in the hosts file. In fact, it's there twice.

**Comment by StevenBlack** [comment]
Right you are, @strotee.  Thanks.

Closing.
