### ISSUE TITLE
Version without Header?

### ISSUE THREAD

**Issue by Baerbeisser** [StevenBlack/hosts#2706]
Maybe i missed it, do you have a version without the '127.0.0.1 localhost' etc. etc. header?
Because your header causes issues on my machine (guess because it's usually 127.0.0.1 $HOSTNAME) and i have to strip it via sed in my update script, via the #==== separators, but that's a hack.

**Comment by StevenBlack** [comment]
Hi @Baerbeisser thank you for your question.

We provide the full source code in [updateHostsFile.py](https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py) which you are free to modify or extend for your own use.

A bash or batch file that trims the first few lines of the hosts file, or truncates the lines before `# Custom host records are listed here` is also trivial for you to create for yourself, is it not?

Closing.
