### ISSUE TITLE
yfincance issue

### ISSUE THREAD

**Issue by fabiodm7** [StevenBlack/hosts#2708]
Hi Steven, I'm using yfinance to retrieve some trade data, but it seems that the domain fc.yahoo.com is blocked in the [StevenBlack/hosts](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) file.

Could you please review this and consider removing that domain from the blocklist?

Thank you!

**Comment by StevenBlack** [comment]
Thank you for this Fabio @fabiodm7.

I have removed domain `fc.yahoo.com` and this will reflect in the next release due shortly.
