### ISSUE TITLE
Sea of Thieves fakenews-gambling-social blocked connection

### ISSUE THREAD

**Issue by ElenaNya** [StevenBlack/hosts#2709]
seems that the hosts file is not allowing a proper connection to the Sea of Thieves servers through Steam (stuck on "loading supplies"); I'm not sure about Xbox. I'm using a slightly modified version of this:

https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts (I might be wrong, and I apologize in advance—maybe something I added is causing the issue).

[hosts.zip](https://github.com/user-attachments/files/16787769/hosts.zip)

![image](https://github.com/user-attachments/assets/b5dfd5bd-c99c-4896-90fe-1e7514f3a6b0)

**Comment by StevenBlack** [comment]
Thank you for this Elena @ElenaNya.

We don't block any of the domains listed in the top half of your screen shot above ⬆️ 

We don't block `ntp.msn.com`...

I'm mystified what you mean by "Sea of Thieves servers".

In short, I can't decipher what you're asking, and the info you've chosen to provide has proven to be a time sink for me.  Thanks!

Closing.
