### ISSUE TITLE
hosts in list that have a trailing '.'

### ISSUE THREAD

**Issue by proxenus** [StevenBlack/hosts#271]
I came across this problem with hphosts.partial which I know isn't used here directly, but this fix would apply to any list that could have such a mistake. A trailing period breaks deduplication. I'm also porting the consolidated hosts lists to bind and while a trailing . is tolerated in the hosts file it is a fatal error in bind.

here is how I fixed it:

updateHostsFile.py line 337:

replace
        line = line.rstrip() + "\n"
with:
        line = line.rstrip()
        # Trim trailing periods
        line = line.rstrip('.') + "\n"

**Comment by StevenBlack** [comment]
Thanks @proxenus!
