### ISSUE TITLE
false positive: transfer.adttemp.com.br

### ISSUE THREAD

**Issue by hyder365** [StevenBlack/hosts#2711]
The domain "transfer.adttemp.com.br" is a public instance of the transfer.sh software, used for temporary file hosting (similar to catbox.moe). It's currently on the blacklist. There's nothing inherently bad about it.

**Comment by StevenBlack** [comment]
Thank you for this Devon @hyder365.

This domain comes to us from upstream at URLHaus.

Please report this, and make you case, at contactme@abuse.ch.

Closing.
