### ISSUE TITLE
blocked - deriv.com?

### ISSUE THREAD

**Issue by PinkFreud** [StevenBlack/hosts#2712]
I see that deriv.com was blocked in 0e90c2f88d.  These guys look like a legitimate company, even sponsoring a yearly Perl and Raku workshop at https://act.yapc.eu/lpw2024/.  Was this block intentional?

**Comment by StevenBlack** [comment]
Thank you for your question @PinkFreud.

Just for general FYI, there are no "legitimate" sites or companies here.  If they are involved in tracking, adware, malware, or worse, they get listed.

The domains `deriv.com` and `www.deriv.com` come to us from upstream, the good folks at KADhosts.

You can investigate their rationale by submitting an issue here:
  https://github.com/PolishFiltersTeam/KADhosts/issues

Closing.
