### ISSUE TITLE
spam website

### ISSUE THREAD

**Issue by olumolu** [StevenBlack/hosts#2714]
1000fapvids.online
ddbca.localmeets.link
localmeets.link

Why should these domain(s) be blocked?
https://trafficlight.bitdefender.com/info/?url=http://ddbca.localmeets.link
https://www.fortiguard.com/webfilter

**Comment by StevenBlack** [comment]
Thank you for this Aritra @olumolu.

I'm taking two of those domains in commit f3069eb63.

```
1000fapvids.online
ddbca.localmeets.link
```

I can't see a justification for the root `localmeets.link` domain here.

Closing!

**Comment by olumolu** [comment]
This domins do dns rebinding attack and open random pop up websites you can check your self. This are phishing websites.

**Comment by olumolu** [comment]
Here is hagazi
https://github.com/iam-py-test/my_filters_001/commit/1621f86ea71cad7c765fd9884e8bb915c0356a33
I have submitted because of the nature of the website.
Before closing request you could have asked me.

**Comment by olumolu** [comment]
Here is hagazi
https://github.com/iam-py-test/my_filters_001/commit/1621f86ea71cad7c765fd9884e8bb915c0356a33

The root domain is used for this sketchy purposes so blocking this root does not make a issue as i have yet to find a legitimate searvice or stuff over this root domain.
