### ISSUE TITLE
Advertising domain: ably-realtime.com

### ISSUE THREAD

**Issue by Thomas-Schubert** [StevenBlack/hosts#2717]
See above

**Comment by StevenBlack** [comment]
Thank you for this Thomas @Thomas-Schubert.

I must say, not to you specifically, but in general: Issues like this one are my least favorite of all.  There's no context, no motive, no justification. There's no sense of scale to this "advertising domain".  With no tangible details, I'm supposed to de-platform this domain.

I'm just not keen on stuff like this.

Closing this issue now, purely on principle.
