### ISSUE TITLE
Additional gambling site

### ISSUE THREAD

**Issue by Blacksmoke16** [StevenBlack/hosts#2720]
Came across `xoilactvx.com`, which seems pretty sus and could be a good addition to the gambling list. Didn't seem to fit in any of the upstream lists so creating this.

**Comment by bigdargon** [comment]
The domain name `xoilactvx.com` is just a live football TV site (no copyright) and contains betting ads. This site is not a gambling site.

**Comment by StevenBlack** [comment]
Thank you for this George @Blacksmoke16, and thank you @bigdargon for the assist.

I'll defer to @bigdargon here because they are local to the site's market, and I trust this judgment.

Closing.

**Comment by StevenBlack** [comment]
@Blacksmoke16 that said, I absolutely agree with you. That site looks sus.  Like guys, it's not 1995 anymore.

**Comment by bigdargon** [comment]
The bookmaker sponsors this website, so the website owner will place advertisements, inserting links to the bookmaker's home page. The football matches are broadcast live without copyright and often the football commentator will directly read the bookmaker's advertisement.

Site Description
```
Xoilac TV là trang phát trực tiếp bóng đá hôm nay, link xem bóng đá xoilac hoàn toàn miễn phí, xôi lạc tv chiếu trực tuyến tất cả các giải bóng đá Việt Nam và thế giới (Euro, Cúp Nam Mỹ - Copa America, Ngoại Hạng Anh,..)
```

Translated
```
Xoilac TV is a live football streaming site today, xoilac football viewing link is completely free, xoilac tv broadcasts online all Vietnamese and world football tournaments (Euro, South American Cup - Copa America, Premier League,..)
```

Bookmaker homepage `https://6686.vn/`

Betting link `https://6686vn67.com/`

@StevenBlack Betting domains will often have random letters or numbers added to them to create a new domain. I only add the original domains in the upstream update to the repo, and the random domains will be added in the full source. We have done this before https://github.com/bigdargon/hostsVN/issues/333

```
6686vn1.com
6686vn10.com
6686vn100.com
6686vn101.com
6686vn102.com
6686vn103.com
6686vn11.com
6686vn12.com
6686vn13.com
6686vn14.com
6686vn15.com
6686vn16.com
6686vn17.com
6686vn18.com
6686vn19.com
6686vn2.com
6686vn20.com
6686vn21.com
6686vn22.com
6686vn23.com
6686vn24.com
6686vn25.com
6686vn26.com
6686vn27.com
6686vn28.com
6686vn29.com
6686vn3.com
6686vn30.com
6686vn31.com
6686vn32.com
6686vn33.com
6686vn34.com
6686vn35.com
6686vn36.com
6686vn37.com
6686vn38.com
6686vn39.com
6686vn4.com
6686vn40.com
6686vn41.com
6686vn42.com
6686vn43.com
6686vn44.com
6686vn45.com
6686vn46.com
6686vn47.com
6686vn48.com
6686vn49.com
6686vn5.com
6686vn50.com
6686vn51.com
6686vn52.com
6686vn53.com
6686vn54.com
6686vn55.com
6686vn56.com
6686vn57.com
6686vn58.com
6686vn59.com
6686vn6.com
6686vn60.com
6686vn61.com
6686vn62.com
6686vn63.com
6686vn64.com
6686vn65.com
6686vn66.com
6686vn67.com
6686vn68.com
6686vn69.com
6686vn7.com
6686vn70.com
6686vn71.com
6686vn72.com
6686vn73.com
6686vn74.com
6686vn75.com
6686vn77.com
6686vn78.com
6686vn79.com
6686vn8.com
6686vn80.com
6686vn81.com
6686vn82.com
6686vn83.com
6686vn84.com
6686vn85.com
6686vn86.com
6686vn87.com
6686vn88.com
6686vn89.com
6686vn9.com
6686vn90.com
6686vn91.com
6686vn92.com
6686vn93.com
6686vn94.com
6686vn95.com
6686vn96.com
6686vn97.com
6686vn98.com
6686vn99.com
```
