### ISSUE TITLE
[BLOCK] cdn.adnz.co

### ISSUE THREAD

**Issue by patrick7** [StevenBlack/hosts#2721]
Is used to show the "u bad person using adblock" banner on blick.ch when using additional blockers like brave.

**Comment by StevenBlack** [comment]
Thank you for this issue Patrick @patrick7.

Your request does not contain enough information to motivate listing domain `cdn.adnz.co`.

I do not see any requests to domain `cdn.adnz.co` when I load this page.

Maybe I misunderstand?

**Comment by snapfast** [comment]
Please add base url for `javdock.com`.

**Comment by br1an-cloud** [comment]
It's part of the ad-network of a company called audienzz

following hosts should be blocked:

api.adnz.co
xd.adnz.co

not cdn.adnz.co because as the name suggests it's a CDN and they also serve non-ad files.

**Comment by StevenBlack** [comment]
Thank you for this clarification Brian @br1an-cloud.

I've added these two domains, and these will be live in the next release, due shortly.
