### ISSUE TITLE
Download the lists as txt?

### ISSUE THREAD

**Issue by Excidiar** [StevenBlack/hosts#2722]
Currently the only thing that can be downloaded directly is the main raw. The lists are so long trying to copypaste them literally makes my browser stop working.  I´ve tried waiting until the page stops loading, but then it is literally frozen in place, if i try to go down the list. I see no other alternative to get these hosts files.

**Comment by Lateralus138** [comment]
You should have the option of downloading the raw file via the download button:

![Capture3](https://github.com/user-attachments/assets/b251cfda-0309-4a19-827c-fccea90f4624)

Another option would be to use my [BlackHosts command line tool](https://github.com/Lateralus138/blackhosts) (instructions on how to use are found at the repository) as is suggested in the [Interesting Applications Section](https://github.com/StevenBlack/hosts#interesting-applications) in Steven's README.

And yet another option would be to copy the raw link and use either `curl` in Linux or `Invoke-WebRequest` in Windows Powershell to download via the command line:

Powershell

```Powershell
Invoke-WebRequest -Uri $("<RAW FILE URL>").Content | Out-File -FilePath .\hosts
```

Curl in Linux (and possibly Windows if you have the Windows version)

```Bash
curl -o hosts "<RAW FILE URL>"
```

**Comment by iam-py-test** [comment]
> and possibly Windows if you have the Windows version

That command works in Windows with no modification:
![image](https://github.com/user-attachments/assets/ef31b562-ead9-41b6-8460-e23e3ef4f3f5)
Thanks

**Comment by StevenBlack** [comment]
Qood question @Excidiar!  Thank you Ian @Lateralus138 for the assist, and thank you @iam-py-test for the clarification.

Closing!
