### ISSUE TITLE
Suggest blocking *.tt.omtrdc.net

### ISSUE THREAD

**Issue by voltagex** [StevenBlack/hosts#2724]
Seems to be a marketing domain.

(You might want to consider using GitHub issue templates so that people give you all the information you need first up)

**Comment by StevenBlack** [comment]
Thank you for for this suggestion @voltagex.

We already list 109 `omtrdc.net` domains, which include 53 `tt.omtrdc.net` domains.

So I think we've got this covered.

closing.

**Comment by voltagex** [comment]
No worries, I'll add the Telstra domain specifically. Any reason to list these by subdomain instead of wildcard?

**Comment by StevenBlack** [comment]
Good question @voltagex.  Hosts files are primitive, dating back to the first days or weeks of of the ARPANET, in the early 1970's.  There is no wild card support in hosts files; never was and probably never will be.

**Comment by voltagex** [comment]
Ah right! Thanks for the reminder. I'm using PiHole which has some support for wildcards, I think. Thanks for the info, and your work on these lists.
