### ISSUE TITLE
Remove demdex.net & dpm.demdex.net from the list

### ISSUE THREAD

**Issue by Baerbeisser** [StevenBlack/hosts#2727]
[It's from Adobe](https://experienceleague.adobe.com/en/docs/audience-manager/user-guide/reference/demdex-calls) and some online payment solutions use it.

**Comment by StevenBlack** [comment]
Thank you for this @Baerbeisser.

Like I've written many times before:

> It doesn't matter if listing a domain interferes with fundraising by the Holy Sisters relict of Mother Theresa of Calcutta. If the domain vehicles tracking, adware, or worse, it gets listed here. This project serves people who value privacy and online safety.

No fewer than four of our list curators flag domain `demdex.net` and its subdomain variations.  76 `demdex.net` domains in all.

I promise you: this isn't going to change.

But thank you nonetheless for the suggestion.

Closing.

**Comment by Baerbeisser** [comment]
Yeah, i thought first that (blocked demdex) was the culprit, but payment still didn't work anyway.
