### ISSUE TITLE
[BLOCK] ads-static.phonepe.com

### ISSUE THREAD

**Issue by tillcash** [StevenBlack/hosts#2729]
Please block `ads-static.phonepe.com`.

Note: I have already created an issue to block `ads.phonepe.com`: [AdAway Issue #202](https://github.com/AdAway/adaway.github.io/issues/202). Additionally, I created an issue to block `ads-static.phonepe.com`: [AdAway Issue #360](https://github.com/AdAway/adaway.github.io/issues/360), but it was not merged because the maintainer stepped down.

**Comment by StevenBlack** [comment]
Thank you @tillcash.  This is added in commit e7237a0bc and will reflect soon.
