### ISSUE TITLE
The vital importance to avoid blocking Google Ads and Google Analytics domains to avoid bugs and for normal operation of important and vital websites, services, apps... that need Google Ads and Google Analytics to function properly and the ultimate hope of pure standalone blocklist that blocks only malwares virus phishing without blocking ads trackers to avoid disrupting the normal operation of the ublock origin !

### ISSUE THREAD

**Issue by trimechee** [StevenBlack/hosts#2736]
Hello, thank you so much for these great amazing blocklists !

So the famous extension ublock origin developer says to avoid disrupting the normal operation of the ublock origin extension which blocks ads and trackers, we must avoid using dns which blocks ads and trackers otherwise blocking pub is disrupted and no longer becomes effective when using ublock origin,

so: i test with this famous site with my ad blocker extension disabled:

https://d3ward.github.io/toolz/adblock

and unfortunately, some essential google services for the proper functioning of websites, apps....are blocked like Google Ads and Google Analytics domains, so our ultimate dream please is blocklist that blocks malware viruses so no need to activate a heavy anti virus that destroys our battery and activates noisy fan and also blocklist that avoid blocking Google Ads and Google Analytics to avoid bugs and for normal operation of important and vital websites, services, apps... that need Google Ads and Google Analytics to function properly, and no need that this blocklist block ads because ublock origin extension manifest v2 in catsxp, brave, supermium, thorium, and firefox forks browsers can do that even in smartphones, and even in iphone ios and mac os with orion browser by kagi:

https://kagi.com/orion/

which supports the installation of extensions and adblockers like ublock origin in ios and mac os, thank you so much!

So to summarize, the dream please is balanced moderate blocklist without false positives and without blocking vital google domains and blocklist will also block out of the box malware viruses in the future, so we hope please blocklist will integrate by default some curated famous security blocklists like urlhaus security lists:

https://gitlab.com/malware-filter/urlhaus-filter

https://gitlab.com/malware-filter/phishing-filter

https://adguardteam.github.io/HostlistsRegistry/assets/filter_50. txt

and integrate also famous quad9 dns please that block malwares and are considered the best secure dns in the world:

https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/quad9_blocklist.txt

and we hope please blocklist will use some important blocklists like those found in the tags "trheatintelligence" and "cryptojacking" of Rethink dns so we no longer need to activate heavy anti virus heavy windows os security settings:
https://rethoughtdns.com/configure

https://github.com/serverless-dns/blocklists

so this blocklist of Mr Steven Black blocklist will become the best dns in the world out of the box safe and freedom anti censorship because several famous dns providers that block malware also block safe streaming site like unfortunately quad9 and dns0, thank you!

I talked to other DNS providers and even to one of the developers of Balanced Adguard DNS to ask them not to block vital Google ads and analytics domains but the answer is the blocking will be less effective if the domains are not blocked but I do not share not this opinion since ublock origin is effective and we can quickly activate/deactivate ublock origin in case of problems and false positives but the dns and the blocklist, it is more difficult to change the parameters of the dns and the blocklist... ....

Hence the capital importance of having a balanced blocklist that blocks malware viruses but does not block vital google domains and trackers to be used in ads blocker extension or with dns please! Thank you very much :)

**Comment by StevenBlack** [comment]
Thank you for this Anon @trimechee.

Above ⬆️ you present us with sentences that are 127 words, 93 words, 51 words, 48 words, and 46 words long.  That's just the longest five sentences.

Parsing this word salad is a cognitive burden. I don't have time for that, nor will I stand for that.

I am closing this issue now. 

You are welcome to open a fresh new issue, or several related issues, after you've thought about presenting your ideas in productive and actionable ways.  You could seek help for review before re-posting, that might be helpful too.

I'm not saying no, I'm just saying, I can't deal with that ⬆️, as presented here.

Thank you for understanding.  Here's a writing tip:  Short sentences: use them.
