### ISSUE TITLE
Norton 360 Liveupdate and Software Updater is blocked

### ISSUE THREAD

**Issue by Starfoxfs** [StevenBlack/hosts#2739]
Hi,

i have the newest Norton 360 v24.9 Version installed and your Blocklist Blocks the Norton LiveUpdate Server.

I think it´s the entry:
-ncc.avast.com
can you pls fix this thanks 

Norton and Avast merged in the past so this is the Gateway for Norton 360 App in some cases

**Comment by StevenBlack** [comment]
Thank you for this @Starfoxfs.

If the Norton 360 software update process relies on the domain `ncc.avast.com` being visible, that's on Norton.  Maybe raise this issue with them?

Closing.

**Comment by Starfoxfs** [comment]
Why that´s on Norton ? You have the Domain `ncc.avast.com` in your Blocklist so it would be blocked for all Users who use your Blocklist. I think Norton check the connectivity with this Domain.

All Users who use e.g. Pihole with your Blocklist as "Standard Blocklist" will have Problems with the Norton 360 App.

So in my opinion you should delete ncc.avast.com from your Blocklist for better compatility

**Comment by StevenBlack** [comment]
Thank you for your question @Starfoxfs.

Our goals here have nothing to do with "compatibility" with Norton.  Norton is garbage, and we list plenty of other subdomains of `avast.com`.  

Again, we are not here to serve people who believe in Norton.  We're here to serve people who "get" what's really going on, notably in the whole Norton and anti-virus industry cesspool.

Ask yourself, why does Norton rely on `avast.com`?  If that doesn't raise red-flags in your mind, then maybe you should go all-in with Norton and forget using anything else.

Again, thank you for your opinion, but we aren't here to fix Norton's shady business.

**Comment by SeriousHoax** [comment]
@StevenBlack Hi! In case you didn't know yet, Norton using Avast domains is not a red flag because Avast is owned by Norton and currently Norton is basically an Avast clone. Blocking telemetry domains is appreciated, but blocking something that breaks functionality is not ideal, even if you don't like the product itself, since Avast, AVG, Norton products are used by millions, and your filter is used by many while also being a dependency of some other popular filter lists.

**Comment by Starfoxfs** [comment]
Hi,
meanwhile i leaved Norton and Avast completly and switched from Windows to Linux.  In my case you can Block this Domains now. I also dont know if this Domain is needed for the Update Process in Norton with newer Norton Versions.

I am happy with Linux.

Keep on the good work
