### ISSUE TITLE
Blocking `plus.l.google.com` breaks `apis.google.com` and `keep.google.com`

### ISSUE THREAD

**Issue by aureq** [StevenBlack/hosts#2741]
When blocking `plus.l.google.com` this breaks `keep.google.com`. Specifically, Keep Notes cannot be synchronized anymore. The little spinner in the top right corner spins indefinitely and the Keep Notes are never synchronized.

Digging further and I found this is because `apis.google.com` CNAMEs onto `plus.l.google.com` ([ref](https://digwebinterface.com/?hostnames=apis.google.com&type=&ns=resolver&useresolver=9.9.9.10&nameservers=)).

I noticed `plus.l.google.com` is currently blocked in `social-only`, `social`, `fakenews-social-only` and `gambling-social-only`.

The change was introduced ~5 days ago with 21849a30b6ae7e0158037ae7b22e9bce48e7d2d1 (https://github.com/StevenBlack/hosts/blame/66144dff67ae4fd310020307f8de99679a8b63d4/alternates/social-only/hosts#L2273).

Not sure how, but I think upstream(s) should be notified too.

**Comment by StevenBlack** [comment]
Thank you for this Aurélien @aureq. 

This is actually a very cool issue, thank you for raising it in such detail. Last week I dropped one of our curated social media providers but, in the process, I didn't update a summary `hosts` file containing combined lists.

That's fixed now, in the latest release, which is online now 👍🏻 

Closing.

**Comment by aureq** [comment]
Thank you Steven @StevenBlack for the kind words and most importantly, thank you for your great work on those lists.
