### ISSUE TITLE
(Win10+Win11) Hosts file causes network to stay unconnected for several minutes after reboot

### ISSUE THREAD

**Issue by GregariousJB** [StevenBlack/hosts#2743]
* Using the `Unified hosts = (adware + malware)` hosts file
* Happens on Windows 10 21H2 and a fresh install of Windows 11 24H2 (both LTSC)
* Method: Copy/pasting hosts from the above file into the existing etc/Hosts file
* Restoring hosts file to its default state solves this issue

This issue is one of the reasons why I reformatted Windows 10 and upgraded to 11, and I'm just now realizing it's because of the hosts file. After driver updates, sfc /scannow's, and DISM analyzing not fixing anything, I thought my system was just getting old and corrupted. 

After a reboot, my internet won't connect for around 2-4 minutes. 

My guess is it has something to do with the top section of your hosts file since the rest of the entries are just for ads:

```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
ff00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
0.0.0.0 0.0.0.0
```

Can I just copy/paste all the advertisement links in there and ignore this first section? I'm a little scared to touch it now. And I assume using your update script will force these in there anyway.

**Comment by StevenBlack** [comment]
Thank you for this @GregariousJB. I'm sorry to hear you are going through this.

This is documented in the readme, in the section titled [Warning: Using this hosts file in Windows may require disabling DNS Cache service](https://github.com/StevenBlack/hosts).

This is an MS Windows bug that's been around since forever.  Every operating system on the planet has no problem with large hosts files, except Microsoft Windows.

Closing.

**Comment by Lateralus138** [comment]
This has been discussed many times here (please browse closed issues) as this is probably one of the top issues with Windows, but this issue stem from the DNS Cache service not being able to handle tons of lines very well. This is completely fixable by compressing the HOSTS file into 9 URLs per IP lines (0.0.0.0 url1.com url2.com ..., etc.) or disabling (which can cause other issues so I do not recommend). Please see my comment for more information on how to compress the HOSTS file: [https://github.com/StevenBlack/hosts/issues/2134#issuecomment-2375886842](https://github.com/StevenBlack/hosts/issues/2134#issuecomment-2375886842).

**Comment by StevenBlack** [comment]
Thank you, as always, for the assist Ian @Lateralus138.

**Comment by GregariousJB** [comment]
I apologize for being a statistic, then. 

If it's "been discussed many times" and is "probably one of the top issues", then maybe a better warning in the readme would prevent users like me from troubleshooting for 2 months before caving in and reformatting. Perhaps something closer to the top and in red text. Maybe even inside the hosts file itself as a comment for the users that grab & go.

**Comment by Lateralus138** [comment]
@GregariousJB I wasn't trying to be rude, was just saying that when making an issue it's best to look for old closed issues and that there are plenty enough of them that you would've found it. I think Steven has done quite enough to help with this issue, far more than he needs to as Windows DNS is a pain and none of this is his (or any of our) fault and doesn't just cater to Windows users. He's doing the public a favor, not the other way around (I do not attempt to speak for him, this is my grateful observation and appreciation). And as for "Grab and Go", that's fairly irresponsible and a primary reason there are so many issues on the internet in the first place.

All I was trying to do was help you. You're welcome.

**Comment by GregariousJB** [comment]
Oops, I didn't mean to imply any rudeness at all, I was just a stating a fact that I'm a statistic 😊.

Up to you guys. Just seems like the "cost to sales" ratio of amending the readme might be helpful to you. 

Thanks for clearing this up for me. I have the Unified Hosts Autoupdate thingy set up and it seems to be working well 👍

**Comment by Lateralus138** [comment]
@GregariousJB Then please excuse my curtness.
