### ISSUE TITLE
add flowto.it

### ISSUE THREAD

**Issue by Baerbeisser** [StevenBlack/hosts#2744]
That seems the right place to request additions?
Well, i got a spam mail today, i usually report them to the services used.
But flowto.it seems only to be used for phishing and isn't in the list yet.

**Comment by StevenBlack** [comment]
Thank you for this @Baerbeisser.  You're right: that domain seems sketch.

I've added this in commit 97d3df3b8 which will be in the next release, due soon.

Closing.
