### ISSUE TITLE
Apple Apps Store is blocked

### ISSUE THREAD

**Issue by markster1700** [StevenBlack/hosts#2748]
Some entry has been added or updated that prevents iOS Apps Store access.

**Comment by StevenBlack** [comment]
Thank you for this Mark @markster1700.

Can anyone shed light or clarity on this?  Which domain is it?

**Comment by markster1700** [comment]
I am still investigating. I run Unbound DNS on my home network and have few block rpm lists + pfsense firewall.
It seams that after I disable all Unbound RPZ lists things are working. I can access Apple Apps Store on iPhones.
I did not update my own static lists and the only 2 lists that are updated regularly is yours and urlhause.

Both are big lists and I am unable to point to a specific lists. I am still testing.

Mark

**Comment by markster1700** [comment]
Please close the issue. After long debugging I have determined that it was not your block list. 
Refreshed both this list and new urlhause list. Things started to work.

**Comment by StevenBlack** [comment]
Thanks Mark @markster1700.

Closing.
