### ISSUE TITLE
missing domain (api-visitor-analytics.intercom.com) in 3.14.121

### ISSUE THREAD

**Issue by strotee** [StevenBlack/hosts#2749]
The following domain (api-visitor-analytics.intercom.com) was [committed](https://github.com/StevenBlack/hosts/commit/308f0abdfeec7a2ea65dbd76a87460d623fa879a) but it wasn't saved correctly. I cannot find the domain when I searched the hosts file.

Thanks

**Comment by StevenBlack** [comment]
Thank you @strotee, good catch!

I just fixed this in commit 55b495315 which will reflect online in the next release.

Closing.
