### ISSUE TITLE
AdGuard

### ISSUE THREAD

**Issue by Syrubun** [StevenBlack/hosts#2758]
Can you please add an Adguard filter version?

I'd like to use this in Adguard as opposed to a Pi-hole or Windows hosts for compatibility reasons with some of the apps I use, if I disable the DNS cache it breaks a few things on my PC.

**Comment by Lateralus138** [comment]
> ...if I disable the DNS cache it breaks a few things on my PC

Hello @Syrubun, You do not have to disable DNS caching to use the HOSTS file directly and successfully in Windowss, compressing the HOSTS file works just fine as recommended in the same [section](https://github.com/StevenBlack/hosts#warning-using-this-hosts-file-in-windows-may-require-disabling-dns-cache-service) that talks about disabling DNS caching.

Excerpt from Steven's README pertaining to the subject:

> ***Disabling the DNS Cache Service can cause issues with services and applications like WSL and it's possible to compress the hosts file and negate the need to disable the DNS caching service. You can try the C++ Windows command line tool at [Hosts Compress - Windows](https://github.com/Lateralus138/hosts-compress-windows) (the recommended method) or the PowerShell compression script and check out the guide located at the [Hosts Compression Scripts](https://github.com/Lateralus138/hosts-compression-scripts) repository.***

I am the author of said compression software and it is in the [Interesting Applications section](https://github.com/StevenBlack/hosts?tab=readme-ov-file#interesting-applications) of this repository's README.

**Comment by StevenBlack** [comment]
Thank you cor the assist Ian @Lateralus138.

Does this ⬆️ address your concerns @Syrubun?

**Comment by StevenBlack** [comment]
Thank you for this suggestion @Syrubun.  We won't be providing an AdGuard-formatted version.

Closing.
