### ISSUE TITLE
block this domains.

### ISSUE THREAD

**Issue by olumolu** [StevenBlack/hosts#2759]
## Which domain(s) should be blocked?

https://rustdesk.io/
https://rustdesk.pl/
https://rustdesk.co.nz/
https://rustdesk.secure-box.de/
## Why should these domain(s) be blocked?

Block this domain
They are providing malwares
https://github.com/rustdesk/rustdesk/discussions/9679

**Comment by StevenBlack** [comment]
Thank you for this Aritra @olumolu.

These domains are added in commit e778618a6.

Closing.
