### ISSUE TITLE
Major social network is banned

### ISSUE THREAD

**Issue by sergeevabc** [StevenBlack/hosts#276]
General hosts (adware+malware) includes domain ```ok.ru``` which is large social network in Russia.
Could you be so kind to permanently white-list it?

**Comment by StevenBlack** [comment]
Hi Aleksandr @sergeevabc, thanks for the report.

Mitchell @mitchellkrogza, can I ask you to check your logs for this one?

**Comment by mitchellkrogza** [comment]
Thanks for the heads up @sergeevabc @StevenBlack fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/5cc4ade1b656d7ef2827017fac03ef084d93e0c9

**Comment by StevenBlack** [comment]
Thanks Mitchell @mitchellkrogza!

Aleksandr @sergeevabc this is reflected in commit ad93b087ead494 here.

Closing!

**Comment by sergeevabc** [comment]
Thank you @StevenBlack and @mitchellkrogza.
