### ISSUE TITLE
Are these domains possibly transcribed inaccuracies?

### ISSUE THREAD

**Issue by 217heidai** [StevenBlack/hosts#2760]
Are these domains([hosts](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts)) possibly transcribed inaccuracies?
domian list:
```
baidu.honker.inf
pgl.example0101
grid-bidder.criteo
castoola.tv.lan
```

**Comment by StevenBlack** [comment]
Thank you for this @217heidai.

I think Peter Lowe @pgl of yoyo.org uses `pgl.example0101` as a downstream marker.

Both `grid-bidder.criteo` and `castoola.tv.lan` are in my ad-hoc list and those are now fixed.

The domain `baidu.honker.inf` comes from the URLHaus list, and I'll report that upstream.
