### ISSUE TITLE
Add to Porn List

### ISSUE THREAD

**Issue by Xanhomey** [StevenBlack/hosts#2763]
manhwa18.cc
pornhwa.me
manhwasusu.com
manga18.club
manga18.me
pornhwa18.com
toongod.cc
manhwaus.net
manhwa18.net
manhwato.com
saucemanhwa.com
hentaibato.com
javlab.net
pornjav.tv
bestjavporn.me
javeng.com
jav-porn.io
jav.wine

@Sinfonietta

**Comment by StevenBlack** [comment]
Thank you for this @Xanhomey.

I've recently come to the decision that I won't advocate blocking art of any kind.

I'm sure @sinfonietta will see this, and decide how to curate his own list, but this isn't something I support on principle.

Closing.

**Comment by EMIDY643** [comment]
You can explore the adult games [here](https://www.5454.us/). Download the game now and play the 3D game. Download the game now [here](https://www.5454.us).
