### ISSUE TITLE
[Source] Sharing my Personal Curated list

### ISSUE THREAD

**Issue by Laicure** [StevenBlack/hosts#277]
Hi @StevenBlack,

I am sharing here my [list](https://raw.githubusercontent.com/Laicure/HostsY/master/custHost).

- Update Frequency: As new items detected
- if any domain inside my list contains any domains from [this](https://github.com/Laicure/HostsY#you-can-use-stevenblackhosts-data-sources) + [this](https://github.com/Laicure/HostsY#other-sources), the duplicated domain in my list _are removed_
- Criteria: _verified_ (←having encountered many times) Pop-ups, OnClick ads, or any ads that hinder the browsing or trackers
- Device and Browser used: PC/Laptop ([Waterfox](https://github.com/MrAlex94/Waterfox) with [adblockplus](https://adblockplus.org/)) and Rooted Note4 n910c with Android 5.1.1 ([Samsung Internet](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=en)) with [hosts file](https://forum.xda-developers.com/showpost.php?p=68978460&postcount=2)

**Comment by StevenBlack** [comment]
Added this as a data source in commit 0353f03.

**Comment by StevenBlack** [comment]
Thanks Laicurè @Laicure.

Closing.
