### ISSUE TITLE
Why is ncc.avast.com blacklisted?  It impedes Norton LiveUpdate

### ISSUE THREAD

**Issue by deafmetal1** [StevenBlack/hosts#2778]
### Discussed in https://github.com/StevenBlack/hosts/discussions/2777

<div type='discussions-op-text'>

<sup>Originally posted by **deafmetal1** December  4, 2024</sup>
Per the subject, why is the URL `ncc.avast.com` in the blacklist?  Norton acquired Avast a couple years ago and appears to be using their servers for LiveUpdate and Software Updater functions as of version 24.11.9615 (build 24.11.9615.891).</div>

**Comment by StevenBlack** [comment]
Thank you for your question @deafmetal1.

This is discussed, and I believe answered, in #2739.

Does this answer your question?

**Comment by deafmetal1** [comment]
Sorry, I swear I did a Norton search before posting, it must have only searched open issues.
