### ISSUE TITLE
How to create myhosts and whitelist files?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [StevenBlack/hosts#278]
The project homepage says 

> How do I include my own custom domain mappings?

>If you have custom hosts records, place them in file myhosts. The contents of this file are prepended to the unified hosts file during the update process.
The myhosts file is not tracked by git, so any changes you make won't be overridden when you git pull this repo from origin in the future.

>How do I prevent domains from being included?

>The domains you list in the whitelist file are excluded from the final hosts file.
The whitelist is not tracked by git, so any changes you make won't be overridden when you git pull this repo from origin in the future.

Okay, so how is that done on a Mac?
I don’t have a myhosts file, nor a whitelist file.

I made a section for my own block entries at the top of the hosts file, and pasted the addresses from the blocklist below.

And if I need to whitelist one I just delete it, but of course it returns every time the list is updated.

Just this week I ran into a problem with an address in the list that blocks data from loading on a department store’s flyer, so I’d like to figure out how to use a whitelist.

The address is f.wishabi.net.
There are a few wishabi.net entries in the list, but only that one appears to affect it.
I’ve never heard of them, but evidently they are a content provider?

The code for one image in the flyer contains this line:
img alt="1491932095" src="https://f.wishabi.net/flyers/1113275/thumbnail/1491932095.jpg"

**I’m using this list:
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts**

**Comment by StevenBlack** [comment]
See [Generate your own unified hosts file](https://github.com/StevenBlack/hosts#generate-your-own-unified-hosts-file).  MacOS comes with Python pre-installed.

**Comment by funilrys** [comment]
Hi there, 
is there any feedback on this ?

May I suggest the closure of this issue @StevenBlack ?
