### ISSUE TITLE
Possible false positive: `obituaries.eastvalleytribune.com`

### ISSUE THREAD

**Issue by sodle** [StevenBlack/hosts#2780]
It looks like this domain (a news/obituary website) is being mistakenly blocked by the Gravity list.

![image](https://github.com/user-attachments/assets/bf2f00da-741f-46aa-9152-34ac8ad4b0c5)

**Comment by StevenBlack** [comment]
Thank you for this Scott @NaelsonDouglas 

We don't block `obituaries.eastvalleytribune.com`.

If `eastvalleytribune.com` relies on `casmp.adperfect.com` to deliver obituaries, that's their scummy behaviour, so therefore it's on the East Valley Tribune to clean this up.

Closing.

**Comment by sodle** [comment]
Thanks for the clarification. AdPerfect appears to be a product purpose-built for building classified ad pages for newspaper sites, including obituary pages. 

This is unfortunate but I don’t know how you’d separate legitimate use cases from scummy ones 🤷🏻

**Comment by StevenBlack** [comment]
Thanks for this Scott @sodle.

It's not "separate legitimate use cases from scummy ones".

There are no "legitimate" websites here.

Like I've written here many times before:

> It doesn't matter if listing a domain interferes with fundraising by the Holy Sisters relict of Mother Theresa of Calcutta. If the domain vehicles tracking, adware, or worse, it gets listed here. This project serves people who value privacy and online safety.

I promise you: this isn't going to change 😄

**Comment by sodle** [comment]
Understood. 

Thanks for the transparency and for your work in maintaining these lists. 🫡 

I will allowlist on my network as needed.
