### ISSUE TITLE
entry "www."

### ISSUE THREAD

**Issue by alexishuxley** [StevenBlack/hosts#2785]
In https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts, there is a host listed simply as 'www.'   Is this a typo? It is the only entry in their without a domain (or without a host, depending which way you look at it).

**Comment by alexishuxley** [comment]
```
damson$ wget -q -O - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts | grep -n ' www\.$'
101943:0.0.0.0 www.
damson$ 
```

**Comment by StevenBlack** [comment]
Thank you for this Alexis @alexishuxley.

This is a bug! I have reported this upstream at https://github.com/FiltersHeroes/KADhosts/issues/84.

Our own domain parsers should have caught this.

**Comment by wallacebrf** [comment]
i use this block list on my fortigate firewall and i was having all kinds of problems accessing tons of sites like 
www.amazon.com
www.etsy.com
www.google.com
www.reddit.com

and so on. as soon as i disable this list
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

the issue goes away, so i am sure it is linked with the erroneous "www." entry

**Comment by StevenBlack** [comment]
Fixed!  Closing!

**Comment by StevenBlack** [comment]
Try it now @wallacebrf.

**Comment by wallacebrf** [comment]
> Try it now @wallacebrf.

just updated the lists and everything seems to be working now!
