### ISSUE TITLE
false positive: us-east-1.signin.aws

### ISSUE THREAD

**Issue by nebulous** [StevenBlack/hosts#2788]
us-east-1.signin.aws is the single signin domain for Amazon Web Services accounts. Definitely not spam and blew my mind for a bit until I realized my pihole was preventing me from logging into aws with SSO.

in
`/hosts/master/hosts`

**Comment by StevenBlack** [comment]
Thank you for this @nebulous.

This comes to us from upstream, in the KADhosts list.

Ping @hawkeye116477 or @krystian3w what do you think?

**Comment by krystian3w** [comment]
CERT Polska guilty:

![obraz](https://github.com/user-attachments/assets/b402f17b-20c8-45de-9a98-a9c65c130420)

https://hole.cert.pl/domains/v2/domains.json

Based on XML and raw JSON, CERT deleted banish:

![obraz](https://github.com/user-attachments/assets/772ebf30-ff74-42d7-afd6-a394b9e473f4)

![obraz](https://github.com/user-attachments/assets/cbea4b44-cb2d-4311-9262-e20733ffc76d)

https://hole.cert.pl/domains/v2/domains.xml

**Comment by StevenBlack** [comment]
Thank you for the assist @krystian3w!

@nebulous this will be reflected in the next release, coming shortly.

Closing.

**Comment by rs** [comment]
Handled by upstream https://github.com/StevenBlack/hosts/issues/2788
