### ISSUE TITLE
How can one suggest new entries?

### ISSUE THREAD

**Issue by ColinMaudry** [StevenBlack/hosts#279]
Hello,

I would like to know how I could suggest new domains to block? They would go in the porn category.

I'm familiar with Github, so making a PR is fine, but since this repo relies on external sources, I'd like to be sure this repo is the right place to do so.

**Comment by StevenBlack** [comment]
Hi @ColinMaudry, thanks for the good question.

The porn data sources are found in the [extensions folder for porn](https://github.com/StevenBlack/hosts/tree/master/extensions/porn).  So opening an issue with @clefspeare13 ([issues](https://github.com/Clefspeare13/pornhosts/issues)) or @sinfonietta ([issues](https://github.com/Sinfonietta/hostfiles/issues)) should get prompt attention as both are regular updaters.

**Comment by Jezza-x3** [comment]
@StevenBlack is there any way you could add in the readme a link to who to suggest edits to since I've opened a thread like this before and have seen others also.

**Comment by StevenBlack** [comment]
@Jezza-x3 good idea!

**Comment by ColinMaudry** [comment]
And with a PR, could it work this way:

1. I fork StevenBlack/hosts
2. I update hosts/extensions/porn/clefspeare13/hosts and hosts/extensions/porn/sinfonietta/hosts with the new entries
3. I make a PR in which I tag @sinfonietta and @clefspeare13
4. They validate it and merge it

Deal?

**Comment by StevenBlack** [comment]
The way it works is,

* Host file sources update their lists as they wish.
* Every few days [this repo updates itself to include their changes](https://github.com/StevenBlack/hosts/blob/2706f99c0fb08643284b344c30dd18ed8516ce0b/updateHostsFile.py#L248-L271).

**Therefore** for Github-based sources, either open an issue there, or fork/push to source repos.

**Alternately** if you have more than a passing interest in this, you could become a source of hosts.  In that case, fork this repo, and add yourself either to the [data folder](https://github.com/StevenBlack/hosts/tree/master/data) for general malware, or to the [extensions folder](https://github.com/StevenBlack/hosts/tree/master/extensions) for specialty lists like porn, gambling, etc.

Good?

**Comment by ColinMaudry** [comment]
Awesome. :+1:
