### ISSUE TITLE
myhosts vs blacklist file

### ISSUE THREAD

**Issue by redactedscribe** [StevenBlack/hosts#2793]
Hello. It seems both files would achieve the same result, i.e. adding additional hosts to the resulting hosts file. The only difference would appear to be myhosts is prepended to it, and blacklist is appended to it, i.e. added to the very bottom? Curious about why one would be used over the other.

Thanks.

**Comment by StevenBlack** [comment]
Hello @redactedscribe, thank you for your question.

This isn't by convention, or anything like that.

It just seemed reasonable to put myhosts near top of file so they are easily and quickly located.  

Then the amalgamated hosts and the personal blacklist, which are potentially very (extremely) lengthy and mostly of little particular interest, goes last.

I guess this is a case of, gotta pick something, and this is how it shook-out, a dozen years ago 😄 

Closing.
