### ISSUE TITLE
Apple store issues

### ISSUE THREAD

**Issue by liquidox** [StevenBlack/hosts#280]
I have been using the main hosts list on my Edgerouter for some months now, without any issues. Since recently I am having trouble downloading apps on my iPhone from the Apple store. This problem is gone when I disable the adblocker.

Any idea which entry could be causing this?

**Comment by StevenBlack** [comment]
Hi @liquidox it's hard to tell without examining the requests involved.  Tough to do that on iOS.

Does anyone have ideas on this?

**Comment by jac18281828** [comment]
I'm using the main hosts file on my Edgerouter+ as well.   I just updated to the latest hosts file and downloaded from the appstore.   No problem.    I think you might have a problem with your phone configuration.

You could turn on detailed traffic logging to try to see what is failing.

**Comment by liquidox** [comment]
Strange, but thanks for testing on your end. Haven't changed anything on my iPhone and the problem was gone immediately after the change on the ERL.

I will close this then, as jac has confirmed it's not an issue in the hosts list.
