### ISSUE TITLE
Blog service is banned

### ISSUE THREAD

**Issue by sergeevabc** [StevenBlack/hosts#281]
General hosts (adware+malware) includes ```liveinternet.ru``` and ```www.liveinternet.ru```.
[Liveinternet][1] is a Russian blog service, which exists since 2003. 
Could you be so kind to white-list it?

[1]: https://ru.wikipedia.org/wiki/LiveInternet

**Comment by StevenBlack** [comment]
Hi @sergeevabc, it appears that `liveinternet.ru` is flagged by

* [Badd-Boyz line 1924](https://github.com/StevenBlack/hosts/blob/master/data/Badd-Boyz-Hosts/hosts#L1924)
* [someonewhocares.org line 10722](https://github.com/StevenBlack/hosts/blob/master/data/someonewhocares.org/hosts#L10722)
* [yoyo.org line 122](https://github.com/StevenBlack/hosts/blob/master/data/yoyo.org/hosts#L122)

so therefore, no.

Maybe you could contact `liveinternet.ru` and ask them to stop being scumbags on the Internet?

**Alternately** you could clone this repo, [add `liveinternet.ru` to a file named `whitelist`](https://github.com/StevenBlack/hosts#how-do-i-prevent-domains-from-being-included), and use python to build your own version.

**Comment by sergeevabc** [comment]
@StevenBlack, the creator of Liveinternet, [German Klimenko][1], is the Kremlin’s official Internet adviser [since January 2016][2]. Is that reference enough for you to doubt that mentioned scumlists made a mistake? Verify liveinternet.ru by yourself. It is just a blog service, a Livejournal alternative. 

[1]: https://ru.wikipedia.org/wiki/Клименко,_Герман_Сергеевич
[2]: http://www.en.kremlin.ru/events/president/news/51137

**Comment by StevenBlack** [comment]
@sergeevabc `liveinternet.ru` is listed by three independent sources who study these things.

This repo is just an aggregation of many sources with options to customize and extend.

I can't help you with this; I trust the sources we use here.

**Comment by sergeevabc** [comment]
Have you ever questioned how those so-called independent sources are populated? For example, the first one, Badd-Boyz, is curated by a single person, [Mitchell Krog][1] aka @mitchellkrogza and his policy is, I quote, “this list of hosts is compiled from server logs on my own servers”. Now ask yourself, what makes some South African photographer an expert on Russian blog services to list one as scumbag? Ridiculous.

The only reason I could think why ```liveinternet.ru``` were ever mistakenly listed is that it displays ads for sure, but uses dedicated sub domain for that purpose (```ad.liveinternet.ru``` which I did not ask to remove) like Youtube's ```s.youtube.com```.

[1]: https://mitchellkrog.com/

**Comment by StevenBlack** [comment]
@sergeevabc that's completely unwarranted.

Get lost.
