### ISSUE TITLE
New source: Anti popads.net

### ISSUE THREAD

**Issue by betterwebleon** [StevenBlack/hosts#283]
Hello,
I've found a new data source on the website [FilterLists](https://filterlists.com/), where it scores highly.

It is called "[Anti popads.net](https://github.com/Yhonay/antipopads)". Raw file is [here](https://raw.githubusercontent.com/Yhonay/antipopads/master/popads.txt). Currently it has more than 970 entries and is updated frequently. Description: _"Blocks shady, annoying pop-under ads from the infamous PopAds ad network."_

Could you add it among sources for your unified hosts file?

**Comment by StevenBlack** [comment]
@betterwebleon sorry for the delay.  Hey thanks for pointing me to [FilterLists](https://filterlists.com/); that's cool!  I like how they present the sources and their contact facets.

I'm Currently traveling.  I plan to revisit this very soon.  Thanks for the suggestion.

**Comment by betterwebleon** [comment]
No problem, there's no hurry. Thank you for considering it!

FilterLists is comprehensive and well structured website indeed. I found it just recently, thanks to @gorhill from his [wiki page](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web) about custom filter lists for [uBlock Origin](https://github.com/gorhill/uBlock/) (his content blocker).

**Comment by Yhonay** [comment]
Hi, Yhonay here. I've added a list in a form of a hosts file to my git repo. I don't know how usefull it will be seeing how often popads.net adds new domains to their repertoire but if you'll find a use for it then [here it is](https://raw.githubusercontent.com/Yhonay/antipopads/master/hosts).

**Comment by StevenBlack** [comment]
Hi @Yhonay!  How are you sourcing the domains in [antipopads](https://raw.githubusercontent.com/Yhonay/antipopads/master/hosts)?  What's your process to find these?

**Comment by Yhonay** [comment]
Someone linked me to a list of a few thousands sites using popads.net. I pick a few dozen at random, unobfuscate everything between <script></script> and try to download any found .js file. Then I check if it matches a few keywords found in a standard popads.net .js file. If it matches then a domain that .js was downloaded from is added to the list.

I know it's a little naive but so far it works.

**Comment by FadeMind** [comment]
@StevenBlack  @betterwebleon 
https://github.com/FadeMind/hosts.extras/commit/6ad79e7e2de999bea0eb26bf9bf69115e074c1d2

**Comment by XhmikosR** [comment]
Has there been any progress about this? I see the original source is still active and going 🙂

**Comment by Zyt3x** [comment]
I calibrated it.

Check test-iq.com. I finished with 100% in just the time it took to press the correct answer.

**Comment by MrRawes** [comment]
it seems like "Anti popads.net" is a dead list

**Comment by bigdargon** [comment]
New repo anti-popads https://github.com/AdroitAdorKhan/antipopads-re

**Comment by FadeMind** [comment]
@StevenBlack PR awaits. 

CC @AdroitAdorKhan

**Comment by StevenBlack** [comment]
Using [ghosts](https://github.com/StevenBlack/ghosts) to evaluate: this would add `(27,306 - 794) = 26,512)` domains to our base list, a relative increase of 24%.

```
ghosts -c https://raw.githubusercontent.com/AdroitAdorKhan/antipopads-re/master/formats/hosts.txt     11:21:51
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Domains: 110,297
Bytes: 3.5 MB
----------------------------------------
Compared hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/AdroitAdorKhan/antipopads-re/master/formats/hosts.txt
Domains: 27,306
Bytes: 690 kB
Intersection: 794 domains
```

Looking at TLD:

```
ghosts -tld -m https://raw.githubusercontent.com/AdroitAdorKhan/antipopads-re/master/formats/hosts.txt
----------------------------------------
Base hosts file summary:
----------------------------------------
Location: https://raw.githubusercontent.com/AdroitAdorKhan/antipopads-re/master/formats/hosts.txt
Domains: 27,306
Bytes: 690 kB
TLD tally:  (130 unique TLD)
   com: 18,160
   top: 2,937
   xyz: 2,528
   net: 1,072
   club: 303
   info: 271
   pro: 261
   biz: 161
   site: 140
   cam: 133
   fun: 116
   me: 107
   casa: 101
   co: 96
   online: 86
   ru: 83
   life: 76
   org: 72
   pw: 36
   am: 34
   icu: 33
   one: 31
   io: 30
   space: 30
   website: 26
   name: 22
   work: 21
   gq: 16
   de: 16
   uk: 15
   link: 14
   click: 12
   tech: 11
   media: 11
   mobi: 11
   bid: 11
   cc: 11
   in: 9
   live: 9
   eu: 9
   network: 8
   tk: 7
   ml: 7
   us: 6
   nl: 6
   ga: 5
   rocks: 5
   cf: 5
   tv: 5
   best: 4
   app: 4
   ai: 4
   su: 3
   fr: 3
   to: 3
   win: 3
   cyou: 3
   sh: 3
   world: 3
   today: 3
   pl: 3
   digital: 2
   lv: 2
   ad: 2
   dev: 2
   bar: 2
   delivery: 2
   vip: 2
   house: 2
   vn: 2
   ph: 2
   sbs: 2
   au: 2
   dk: 2
   cloud: 2
   codes: 2
   by: 2
   trade: 2
   pk: 2
   za: 2
   jp: 2
   webcam: 2
   ca: 2
   wtf: 2
   my: 1
   nz: 1
   news: 1
   center: 1
   ag: 1
   agency: 1
   loan: 1
   ooo: 1
   st: 1
   ae: 1
   fm: 1
   gg: 1
   review: 1
   cfd: 1
   ws: 1
   zone: 1
   stream: 1
   zw: 1
   buzz: 1
   gt: 1
   supply: 1
   kr: 1
   se: 1
   services: 1
   download: 1
   support: 1
   il: 1
   systems: 1
   email: 1
   gs: 1
   ovh: 1
   land: 1
   global: 1
   at: 1
   uno: 1
   red: 1
   cn: 1
   glass: 1
   it: 1
   racing: 1
   is: 1
   men: 1
   marketing: 1
   re: 1
   ie: 1
   mx: 1
----------------------------------------
```

**Comment by StevenBlack** [comment]
Here is the main reason I'm tending towards declining this.

Who can explain this? 🤷🏻 

We have several curated sources that watch this stuff.  Many eyes watching. Over a long period of time. Some of our source lists are extremely diligent.

Now we see this proposed source with a collection where only 794 domains among 27,306 in its collection that overlap with our existing collection. Only `(794 / 27,306) = 3%` of the 27,306 domains overlap with all our other curated sources combined.

I would expect, what, 20% to 100% overlap?  Something in that range.

Very suspicious.

Can someone make the case why bloating our list by 24% makes it a better list, nevermind a 24% better list?

**Comment by bigdargon** [comment]
I don't know how the repo managed to collect the popup domains pretty well. Instead of me going to a website, a popup ad pops up, I review the domain log and block it.

Meaning I only collected a few domains, but here they collect so many with automatic updates. I often use it in piholes and filters in the browser. Wonderful!

**Comment by StevenBlack** [comment]
Hi @bigdargon I understand.

I suppose I should clarify: I'm not hearing about popup issues using the base list here.

Now you understand, if there was a lot of popup spam happening, I would hear about it. I'm not hearing about it.

So this 24% jack in our base list size feels like a solution in search of a problem? Does that make sense?

I'm not saying there's no popup problem, I'm saying I'm not hearing about popup problems from userland, nor from anywhere else.

**Comment by StevenBlack** [comment]
I've decided to decline adding this list.

Closing.
