### ISSUE TITLE
New porn sources

### ISSUE THREAD

**Issue by bryanjhv** [StevenBlack/hosts#284]
Speaking of Spanish porn sources, I have some more to investigate:

- ~~xvideos.com (it's just partially blocked)~~
- leche69.com
- petardas.com
- cumlouder.com
- petardashd,com

**Comment by StevenBlack** [comment]
Thanks @bryanjhv!

@Clefspeare13 check these out for possible inclusion?

**Comment by bryanjhv** [comment]
I can contribute some of them by inspecting network requests:

* **petardas\*.com**:
  - petardas.com
  - www.petardas.com
  - videos.petardas.com
  - videos-gratis.petardas.com
  - thumbs-gratis.petardas.com
  - petardashd.com
  - video.petardashd.com
  - 94.23.215.49
  - thumbs-gratis.petardashd.com
  - videos-porno9.petardashd.com (seems like it's 1 - 15)

**Comment by Jezza-x3** [comment]
The porn list could probably be upwards of 100 thousand URLs. 

@StevenBlack if I maintained a list of a bunch of porn URLs would you add me to your list?

**Comment by StevenBlack** [comment]
@Jezza-x3 sure, I'm always open to new well-curated sources.

But beware 😈     I'm happy the porn extension doesn't have 100k entries. 

My question: how much more expansive does it need to be?  We have less than 10k entries now, and blocking is arguably adequate.

**Comment by Clefspeare13** [comment]
I'll add missing domains today, I thought xvideos was already on there but I'll double check.

As far as the expansiveness is concerned, my list currently includes about 5.8k domains, which will cover most sites. Of course, having a fully exhaustive list is basically impossible, but I think that this will prevent a large enough percentage to be considered good enough.

**Comment by Jezza-x3** [comment]
www.xvideos.com is on there. (Maybe not your list but it's in the porn extension)

How is it partially blocked @bryanjhv ?

**Comment by Clefspeare13** [comment]
I added all except xvideos, which was already in the list. @bryanjhv Could you please elaborate on what was happening with xvideos?

**Comment by bryanjhv** [comment]
Well, looked at [alternates/porn/hosts](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts) yesterday and seen only `static.xvideos.com` blocked, network problem I guess.

**Comment by Clefspeare13** [comment]
https://i.imgur.com/n3IE5hU.png

There are actually 15 different domains with xvideos in alternates/porn/hosts, including xvideos.com

**Comment by StevenBlack** [comment]
Gonna close this one now.  😄  Thanks everybody!

**Comment by bryanjhv** [comment]
Didn't noticed, but the domains with `www.` apended at start still are accessible... Can a wildcard be used inside a `hosts` file?

**Comment by rautamiekka** [comment]
^ Absolutely not.

**Comment by gianmaxfactor** [comment]
www.amaporn.com is missing
