### ISSUE TITLE
I1.services.social.microsoft.com is not a malicious domain

### ISSUE THREAD

**Issue by antonygnanasekar** [StevenBlack/hosts#288]
Whitelist this entry in hosts file. 

 
![image](https://cloud.githubusercontent.com/assets/20095891/25821241/2f733aa4-33e9-11e7-9755-000f1fa0ad95.png)

**Comment by Jezza-x3** [comment]
No one said it's malicious? 

It's blocked because it's a Microsoft Tracking domain. 
https://github.com/tyzbit/hosts/blob/master/data/tyzbit/hosts
