### ISSUE TITLE
List of suggested URLs to block

### ISSUE THREAD

**Issue by Jezza-x3** [StevenBlack/hosts#289]
@StevenBlack 

Would it be fine to make an issue (like this) where people who have say 1-10 URLs they **think*** should be blocked that they can just comment on here instead of opening a new issue? Is there a better place to go about this? Thanks.

**think*** meaning someone such as yourself or another list maintainer should check them for validity.

If this is not a good idea just go ahead and close/lock this after you reply 👍

**Comment by Jezza-x3** [comment]
Ads:

media.net
mnetads.net
mnetads.com

**Comment by StevenBlack** [comment]
@Jezza-x3 please, no.

This repo amalgamates curated hosts files.

Please see the [data folder](https://github.com/StevenBlack/hosts/tree/master/data) for those who curate ads and malware hosts files.

I'm going to close this now.
