### ISSUE TITLE
private-eye isn't fake news

### ISSUE THREAD

**Issue by w-edwards** [StevenBlack/hosts#305]
Just found private-eye.co.uk in the fake news list. It's not fake news, it's a well established critical and satirical magazine.

It was mistakenly included in a list of fake news websites drawn up by an American academic at one point though, is that the source of this fake news list?

**Comment by StevenBlack** [comment]
CC @marktron  :-)

**Comment by marktron** [comment]
Thanks for the catch @w-edwards, my original personal list also blocked satire sites and I missed this when updating it for public use. It's been removed from my repo.

**Comment by StevenBlack** [comment]
Live and online as of yesterday.  Closing.
