### ISSUE TITLE
Router at 192.168.1.1 seems to be affected

### ISSUE THREAD

**Issue by ArneAnka** [StevenBlack/hosts#311]
Hi

So I have an EdgeRouter™ Lite router at home. And when using the hosts file, I cannot use the router interface at 192.168.1.1, charts and functionality disappear.

**Comment by Atavic** [comment]
https://192.168.1.1 isn't touched by this repository.

**Comment by Laicure** [comment]
Same thing happened to my router view but **no**, the hosts file is not the culprit.
The culprit may and I think lies on the active adblocker on your browser, if you have.
