### ISSUE TITLE
XNXX doesn't seem to be blocked. 

### ISSUE THREAD

**Issue by Jezza-x3** [StevenBlack/hosts#313]
xnxx.com, along with MANY more similar ones such as www.xnxx.com are in the hosts file. They are still allowing me to load the site. It's one of the only sites that doesn't cooperate with the hosts blocking. I'm not sure if anyone else has any problems?

**Comment by Leftyx** [comment]
Only

```
0.0.0.0 multi.xnxx.com
0.0.0.0 img.xnxx.com
```
are blocked.
You can add

```
0.0.0.0 www.xnxx.com
```

to your custom black list.

**Comment by StevenBlack** [comment]
I think we're fully covered and properly here.


    data/someonewhocares.org/hosts
    7928:0.0.0.0 img.xnxx.com
    8496:0.0.0.0 multi.xnxx.com

    extensions/porn/clefspeare13/hosts
    2092:0.0.0.0 forum.xnxx.com
    5637:0.0.0.0 xnxx.com

    extensions/porn/sinfonietta/hosts
    2662:127.0.0.1 forum.xnxx.com
    6650:127.0.0.1 xnxx.com
    6651:127.0.0.1 www.xnxx.com
    6652:127.0.0.1 www.xnxx.com

Closing.

**Comment by Jezza-x3** [comment]
@StevenBlack I have all of those in my hosts file. I still can access the website. Sending a video now.. (uploading)

Can you test it and see if it works for you?

**Comment by rautamiekka** [comment]
Could the multi occurrence be to blame ?

**Comment by Jezza-x3** [comment]
2 options. 

a) you have to download the video because some reason Google Drive wants to convert it to 360p
https://drive.google.com/file/d/0BzpMdr0-hwrOQy1CdmFHc2tNejg/view?usp=sharing
MD5: 99E6A51E794E98205962B8D4F6CDE586

b) download this rar and unzip it.
https://drive.google.com/open?id=0BzpMdr0-hwrONmNVemZxTnZ2eVk
MD5: 28725E888252FDE2F5179011AEBEDA97

**Comment by Jezza-x3** [comment]
@rautamiekka You don't have to. I'm on Windows 10 and everything is working just fine with 0.0.0.0 except xnxx.com

But I did try for you. Still didn't work.

**Comment by StevenBlack** [comment]
@Jezza-x3 you applied a proper DNS cache flush?

**Comment by Jezza-x3** [comment]
@StevenBlack If you mean *ipconfig /flushdns* then yes

**Comment by Jezza-x3** [comment]
And I know it worked because I deleted the hosts file and made sure the porn sites would load. I then put the hosts file in. (completely fresh from your page) and did the flushing. 

The porn sites stop loading and the block works... Except xnxx. 

Did you try it yourself?

**Comment by StevenBlack** [comment]
@Jezza-x3 I don't use Windows.

**Comment by Jezza-x3** [comment]
@StevenBlack I know. I just wanted you to see if the problem affected your system. What do you use btw?

**Comment by Jezza-x3** [comment]
Found the problem while writing this:

The problem still persists while using Arch Linux with Chrome dev build in the Cinnamon desktop. 

Extensions are uBlock Origin, LastPass, Hangouts, Https Everywhere (disabled and enabled still same), Grammarly, WebRTC Network Limiter, Google Data Saver.

Google Data Saver (basically a proxy) screws it up. https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac

After disabling it, it's blocked. It's only non-https sites the Data Saver works on, and xnxx is http only. With https everywhere off, it allowed xvideos to become http and was also unblocked. 

So as far as I know right now, the Data Saver is the problem.

**Comment by StevenBlack** [comment]
Thanks @Jezza-x3 !

**Comment by Jezza-x3** [comment]
No problem @StevenBlack

I already submitted feedback to Google Data Saver and HTTPS Everywhere.
