### ISSUE TITLE
aliexpress.com blocked

### ISSUE THREAD

**Issue by spacedingo** [StevenBlack/hosts#315]
aliexpress.com is a legitimate site. It's in Mitchell Krog's - Badd Boyz Hosts.

**Comment by rautamiekka** [comment]
Must be accidentally blocked along with something else. I'll have a look.

**Comment by StevenBlack** [comment]
Please note that a site can be a "legit site" and still have horrendous behind-the-scenes policies related to tracking, ad-serving, etc.

Currently three data sources block various facets of aliexpress.

    data/Badd-Boyz-Hosts/hosts
    277:0.0.0.0 aliexpress.com

    data/mvps.org/hosts
    317:0.0.0.0 adservice.aliexpress.com

    data/someonewhocares.org/hosts
    8784:0.0.0.0 pcookie.aliexpress.com

cc @mitchellkrogza

**Comment by mitchellkrogza** [comment]
@StevenBlack @rautamiekka @spacedingo 

A grep through my last 9 months of logs reveals only two occurrences of aliexpress.com, both innocent in nature, so hence I have removed it from my latest commit - https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/a73fc3fa5fae9fda077cb978b50850edb124a184

I like to keep my lists clean and relevant so perhaps some time in the past aliexpress.com used to use underhanded techniques but recent logs do not reveal this behavior anymore.
