### ISSUE TITLE
./makehosts crashing on macOS

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/hosts#318]
On macOS I'm getting this (below) for all data.

    Updating source ./data/adaway.org from https://...
    Error in updating source:  https://...
    Updating source ./data/add.2o7Net from https://...
    Error in updating source:  https://...
    etc...

Testing I find it works great at 65f0421, so commit 2ff5dc2 looks to be the cause.

**Comment by StevenBlack** [comment]
@gfyoung  ^^^

**Comment by gfyoung** [comment]
@StevenBlack : Can you replace the `print` statement with `raise` to see what the error is?  I don't have access to Mac, sorry :cry:

**Comment by gfyoung** [comment]
Also, I cannot reproduce that error either on Windows or Linux.

**Comment by gfyoung** [comment]
Are you sure that this is the commit that broke things?  I fail to see how that could have happened.

**Comment by StevenBlack** [comment]
No worries @gfyoung. It's the one commit.

The `path_join_robust()` thing isn't ready on macOS.

I really liked `get_defaults()` piece which was nice, though unrelated to `path_join_robust()`.

As of 26d73051 both `get_defaults()` and `path_join_robust()` are extracted. 

I don't yet know how `path_join_robust()` was failing on macOS.  I just know reverting `updateHostsFile.py` to 65f04210c1 fixes the issue.

 I'd love to see the `get_defaults()` piece re-submitted as a separate commit.

**Comment by gfyoung** [comment]
@StevenBlack : I actually know the error.  This patch is very quick.

**Comment by StevenBlack** [comment]
OK!

**Comment by gfyoung** [comment]
@StevenBlack : PR is up.  Could you pull down the branch to see if everything works for you now?
