### ISSUE TITLE
Legit WhiteSmoke blocked

### ISSUE THREAD

**Issue by i90rr** [StevenBlack/hosts#327]
Hello all,

Could you please check these domains? I'm sure they were wrongly added:
*.whitesmoke.com
.whitesmoke.us

Thanks!

**Comment by jjaaccoobb** [comment]
I'm not sure which digest this entry is located, but you could add said domain to your whitelist file. This project doesn't include a bad domain list, rather, it downloads and aggregates from various sources. 

I suggest adding whitesmoke.us to your whitelist file and close this.

**Comment by StevenBlack** [comment]
@i90rr `whitesmoke` is blocked by mvps.org, which is a super reputable source.

Here's the section in their data

    data/mvps.org/hosts
    11607:0.0.0.0 get.whitesmoke.com #[Adware.Zugo.B]
    11608:0.0.0.0 www.whitesmoke.com
    11609:0.0.0.0 www.whitesmoke.us

Adware.Zugo.B is nasty.

I remind everyone that a site can be 'legit' and still have terrible security/adware policies.

**Comment by i90rr** [comment]
Thanks for your feedback @jjaaccoobb, @StevenBlack.
