### ISSUE TITLE
vc.ru was blocked

### ISSUE THREAD

**Issue by Lourens-Rich** [StevenBlack/hosts#328]
Hello! https://vc.ru/ it`s a site about russian business, telecom and startups. May be you unblock this?
![screenshot_2017-05-30_09-36-51](https://cloud.githubusercontent.com/assets/22860367/26570916/a770396a-451b-11e7-9158-732e24e0398f.png)

**Comment by StevenBlack** [comment]
@mitchellkrogza can you please look into this one?  Thanks.

**Comment by mitchellkrogza** [comment]
@StevenBlack @Lourens-Rich  thanks for the heads up, fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/a68bf5c5d82f3dc592fc65f0ef1b7ff62ce44fc4

**Comment by StevenBlack** [comment]
Thanks @mitchellkrogza!

@Lourens-Rich new version is generated, commit 42128ab.
