### ISSUE TITLE
Add gambling sites from HGC

### ISSUE THREAD

**Issue by konqoro** [StevenBlack/hosts#330]
There is a blacklist here: https://www.gamingcommission.gov.gr/images/epopteia-kai-elegxos/blacklist/blacklist.xlsx from the Hellenic Gaming Commission.

**Comment by StevenBlack** [comment]
Hi @konqoro, thanks for the suggestion.

Unfortunaltely we can't deal with `.xslx` and any other proprietary file formats.  Impossible to diff, for example.

Also how is this list curated?

**Comment by konqoro** [comment]
The blacklist contains online gambling sites which fail to comply with the Greek laws (no permits, do not pay taxes). The 're more info at their site but are all in Greek. It is updated regularly (latest was at 13 of May previous at April). Currently (according to their site) contains 993 entries. I think you should reconsider or we can come up with a workaround, since is a good resource, your host file misses lots of its entries.

**Comment by StevenBlack** [comment]
This would require anyone who builds a consolidated hosts file to have Microsoft Excel or some sort of Excel parser installed, and to call this app or adapter to extract the data in the build process.

Not gonna happen   😄 .

Data sources need to be in an open format.  Maybe someone wants to create and maintain a data source based, in whole or in part, on this file?

**Comment by konqoro** [comment]
ok will see what I can do

**Comment by rautamiekka** [comment]
@StevenBlack I suppose it makes sense you're not aware there are so many methods to handle M$ formats outside spreadsheet softwares. You're already using some sorta automation in making this hosts list, so if you tried you could get that Micro$hit file auto-parsed for its data. ATM, column D, row 3, is where the list of domains (without subdomains) start.

I'll see about a method as well, particularly in Python 3.

**Comment by StevenBlack** [comment]
We won't ever supporting the parsing of proprietary data formats on all the platforms we currently support here.

Closing.

**Comment by rautamiekka** [comment]
So since the data needed to block the gambling sites is distributed in a proprietary format, the data won't be accepted no matter who or how it was extracted ?

**Comment by StevenBlack** [comment]
@rautamiekka please read the thread ⬆️⬆️⬆️.  I explicitly ask for this in [this, my comment, above ⬆️ ⬆️⬆️](https://github.com/StevenBlack/hosts/issues/330#issuecomment-305220180).

**Comment by fraxen** [comment]
@rautamiekka The way to go would be for someone (you) to (continually) parse the data and publish a clean hosts (text) file, that way it could be included as a source in this project.

**Comment by rautamiekka** [comment]
1 thing hit me in regards to this issue:
1) the hosts file doesn't have only the domain itself listed, but subdomains as well, like `example.com` and `sub.example.com`.
2) This spreadsheet has columns for
- web browser addresses which may have a subdomain, and/or may have address parts after that like `/index.html` (which can be stripped, no problem)
- main domain only

, so are the stripped web browser addresses as needed as just the main domains ? At first I had the impression just the main domains would be needed, but seeing that alone doesn't seem to do the blocking ...

**Comment by StevenBlack** [comment]
Hosts works with the exact domain.  So `0.0.0.0 foo.com` does not prevent `0.0.0.0 ads.foo.com`.

I wish hosts supported wildcards.

**Comment by rautamiekka** [comment]
^ In other words every address is needed.
