### ISSUE TITLE
add urls from http://blog.checkpoint.com/2017/06/01/fireball-chinese-malware-250-million-infection/

### ISSUE THREAD

**Issue by moonforeshot** [StevenBlack/hosts#331]
http://blog.checkpoint.com/2017/06/01/fireball-chinese-malware-250-million-infection/

at the bottom of the article, there's a list of urls to block

**Comment by StevenBlack** [comment]
Hi @moonforeshot, thanks for the suggestion.

We only amalgamate hosts from actively curated sources.  This source appears to be a blog post, so it's not normally subject to ongoing curation.

Please feel free to submit this source to [one of the curated lists we use](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Thanks again!  

Closing.
