### ISSUE TITLE
Why is Infowars categorized as "fake news" when CNN is not?

### ISSUE THREAD

**Issue by OkazakiLeir** [StevenBlack/hosts#334]
I couldn't care less about the author's political stance, but putting one and not the other makes the list clearly biased towards one side. What are your intentions by blocking only one of them?

Oh, you're from Canada... that sort of explains your views on the matter. I _suggest_ you not to be biased, at the very least, in this case.

Unless you want to be exposed, then feel free to defend yourself publicly on Twitter right after, or hide in shame like a good liberal.

**Comment by anupritaisno1** [comment]
Dude nobody really cares

**Comment by Jezza-x3** [comment]
First of all, this is very rude behavior. 
Second, this isn't the right place as Steven Black doesn't decide what is fake news.

https://github.com/marktron/fakenews

@Marktron

**Comment by Jezza-x3** [comment]
Also, see https://github.com/StevenBlack/hosts/issues/232

Steven Black said "The curator of Fake News is @marktron who's done, and continues to do, a fine job. He's a reasonable guy. He's not curating this because it's easy.

Originally both CNN and Fox News were on the list. As a Canadian, I feel both should probably be listed, but it's a close-call. I trust Mark."

**Comment by OkazakiLeir** [comment]
@anupritaisno1 when one is blocked from visiting a website with no valid reason other than biased 3rd party opinions, I guess many would care.

**Comment by Jezza-x3** [comment]
@OkazakiLeir It's not a biased opinion. He decides based on his criteria. You don't have to even use the Fake News extension. Also, you can whitelist your own sites.

**Comment by OkazakiLeir** [comment]
@Jezza-x3 Marktron clearly said he has a bias towards the left, so it's safe to assume that both he and Steven agree with such instance, since Steven didn't even bother to edit the, rather small, list.

**Comment by anupritaisno1** [comment]
What in this world isn't biased?

**Comment by Jezza-x3** [comment]
CNN was previously on the fakenews list. Why it was removed, I can't answer. Steven doesn't edit other's lists. He just is consolidating multiple sources.

**Comment by OkazakiLeir** [comment]
Does everything needs to be biased? Only narrow-minded people think like that.

**Comment by Jezza-x3** [comment]
What is the point of this? If you don't want your news blocked, either whitelist it, or don't use the fakenews extension.

**Comment by anupritaisno1** [comment]
Back on topic, all you're doing here is harassment. If you disagree with this repo, just leave it. Nobody wants to know (and hell nobody here really cares) how good you are at cyber-bullying

You could have submitted this complaint in a much peaceful manner

**Comment by OkazakiLeir** [comment]
I want to use the extension because I'm free to. I can obviously edit the list myself, like many unbiased people can. "Forcing" it upon those who can't is what is wrong.

**Comment by Jezza-x3** [comment]
Who is it being forced upon? Anyone can edit this list.

**Comment by anupritaisno1** [comment]
Name one person or one thing in this world that isn't biased

All that everyone here is trying to tell you is to be polite
This could've gone much smoother had you not started with your threats

**Comment by OkazakiLeir** [comment]
Now I'm "cyber-bullying?" You're reeking of political correctness. Anyone who **can** edit this list, will do so.

**Comment by Jezza-x3** [comment]
Yes you are @OkazakiLeir 

You started off calling Steven a Canadian like it's a bad thing and proceeding to passive aggressively cyber-bully him.

**Comment by OkazakiLeir** [comment]
He must be really offended, then. I'm even seeing him cry his eyes out over this issue. Oh wait, it's just you who is doing it for him.

**Comment by Jezza-x3** [comment]
Okay. Well I'm out. You are acting very childish and belittling people without reason. I'm just going to block you. Have a nice life.

**Comment by OkazakiLeir** [comment]
Thank you. Now let the unbiased adults talk.

**Comment by anupritaisno1** [comment]
Sigh. If you disapprove of this repo just don't use it
