### ISSUE TITLE
Adding Gitoffthelawn list

### ISSUE THREAD

**Issue by Gitoffthelawn** [StevenBlack/hosts#335]
I maintain a *very small* list at https://github.com/Gitoffthelawn/block_allow_lists/blob/master/block_list.txt

It is designed to be combined with your master list.

It primarily consists of the *most common* hosts that are not included in many standard lists.  The idea is to keep it as concise as possible.

There are probably a couple hosts in it that are too restrictive for some people, so I don't recommend including it in the unified list.  It can be added to your project as a **Unified hosts + Gitoffthelawn** list.

**Comment by Gitoffthelawn** [comment]
You're right, it doesn't work like the rest.  It's a list of hosts that many people will likely want to block, but cannot be added to the **Unified hosts** list because it might cause an issue for a group of users.

For example, it includes `graph.facebook.com`.  That particular host is used by literally tens of thousands of Android apps, and to my understanding, is used almost exclusively for tracking.  Many people probably don't want many of their Android apps contacting Facebook servers, yet they may not want to completely block Facebook from their systems.  Other hosts in the list have a similar logic to them.

**Comment by Jezza-x3** [comment]
You'd probably be best sorting them out and doing this for example...

Take the Facebook URL you just said and try to get it added to the social extension as it would probably be accepted.

**Comment by Gitoffthelawn** [comment]
Right, except that the idea is to not completely block social networks; the idea is block the most common trackers without completely disabling social networking, for example.

It's a balancing act: the **Unified list** must err on the side of caution, whereas this extension list is a little more aggressive.

**Comment by Jezza-x3** [comment]
I understand. I just think it won't be accepted as a new extension and the best you could do is what I suggested. Good luck though.

**Comment by rautamiekka** [comment]
It's a lot of work, but if a central place for these links with precise categorization would be implemented, it'd simplify at least some things ...

**Comment by Gitoffthelawn** [comment]
@Jezza-x3 Thank you.

@rautamiekka When you wrote "precise categorization", do you mean organizing each host into categorical sections?  That would take some work, but wouldn't be too hard.  Also what do you mean by "central place"?

**Comment by rautamiekka** [comment]
^ Yeah. Like every page on a wiki at Wikia can have multiple categories, or these issues in GitHub projects can have multiple tags, that sorta thing.

Central place as in, for example, a forum (although that's rather cumbersome, not the best form) where whatever source posts an address with such categories and when list makers compile their lists ppl can see why an address was added, and who sourced it.

**Comment by Gitoffthelawn** [comment]
BTW, it similar to Steven's list at https://github.com/StevenBlack/hosts/blob/master/data/StevenBlack/hosts

That list is included in **Unified hosts**, and although it causes a little breakage, Steven has determined the benefits outweigh the costs.

The list I created is similar, except it could possibly cause a little more breakage (hence I recommended not putting it in Unified).  It doesn't create any breakage for me, but that's a sample size of 1.  :)

Since I created this issue, I've automated integration of my list into Steven's list.  So this issue is really now just for the community's benefit, if there is desire.

**Comment by Jezza-x3** [comment]
@Gitoffthelawn Can you explain what domains could cause breakage and how?

**Comment by Gitoffthelawn** [comment]
Yes. :)

I think blocking `graph.facebook.com` could possibly interfere with some Facebook functions, although I don't know.
Same for `platform.twitter.com` for Twitter.

I've never had a problem blocking it, but blocking 'device-api.urbanairship' could possibly cause some breakage.

Outside of those 3 hosts, I don't think much breakage could happen.  But there are, of course, nearly infinite possibilities for mobile apps / desktop apps / websites.

**Comment by Jezza-x3** [comment]
Yeah I'd suggest those first two be added to social media and the others idk about. All up to @StevenBlack

**Comment by rautamiekka** [comment]
How thoroughly has these mentioned addresses been tested for breakages ?

**Comment by Gitoffthelawn** [comment]
Not at all, hence my recommendation to *not* include it in Unified Hosts.

The definite benefits outweigh any possible costs for me, but that may not be true for everyone.

**Comment by rautamiekka** [comment]
^ I mean `graph.facebook.com` and `device-api.urbanairship` (what a weird address there).

**Comment by Gitoffthelawn** [comment]
I have tested it myself, and have never had a breakage.  But the internet is enormous, so individual testing often does not apply to everyone.

**Comment by StevenBlack** [comment]
Interesting conversation.  Thanks, everyone, for your input.

Presently the data sources and extension sources are categorized and delineated by type.

This makes it difficult to slot potential new data sources and extensions that don't fit thematically with pre-existing types.

I think we can all agree that malware and tracking is a good general category.  Similarly the extensions are all good, to a point, and user-selectable to mix-in with adware and malware.

This is why a broad general list is problematic for inclusion in malware and adware.  It would be good to continue respecting people's boundaries.

 @Gitoffthelawn I'd be happy to consider an extension, or extensions, if those domains can be extracted and curated in the future.

**Comment by Gitoffthelawn** [comment]
@StevenBlack Sounds good.  Whatever you like is good by me.  I've created and am using a tool that integrates your lists with mine, so any extension you create is purely for the benefit community.

You may also desire to add some of my entries to your personal list that currently gets integrated into Unified Hosts.

**Comment by Atavic** [comment]
@rautamiekka [device-api.urbanairship.com](https://www.robtex.com/dns-lookup/device-api.urbanairship.com) is owned by Akamai Technologies.

[API](https://docs.urbanairship.com/api/ua/) and official [site](https://www.urbanairship.com/) tell alot like:

>Measure, analyze and predict customer behavior.

**Comment by rautamiekka** [comment]
^ Oh yeah, Akamai, seen that in some links and quickly figured to be just that. The stupid thing, at least over at AMD, is the direct links don't allow direct downloading.

**Comment by ScriptTiger** [comment]
There is an undocumented rule to handle issues like this already. He can either merge it with the data/StevenBlack/hosts or we can throw it in its own data directory. Either way the following changes MUST be made first to all entries in his list:

# 0.0.0.0 verify-this-block-list-is-included.com # Blah, blah, blah, description of what this is and why it's dangerous to be default

This is already standard in other sources.

**Comment by Gitoffthelawn** [comment]
@ScriptTiger I'm here... you don't have to refer to me in the third-person! :) :) :)

**Comment by ScriptTiger** [comment]
"He" is the generic scientific pronoun for female or male :P

**Comment by ScriptTiger** [comment]
But, seriously, you should still totally add your commented lines because people like myself that actually go through all the entries do find it helpful to have extra information, even if the average person doesn't use it.

**Comment by ScriptTiger** [comment]
As an afterthought, might it be useful to collect all such commented entries from the current sources and create a new extension to which Gitoffthelawn's list would fit nicely? It can be sourced both from the lists we already have and from dedicated sources such as Gitoffthelawn. Perhaps a "volatile" extension, or "at-your-own-risk", or something to that effect. That way it would get all those iffy ones in one place and make it easier for people to see what they're working with, since obviously such an extension would require more eyes-on before implementation.
