### ISSUE TITLE
"rootads.nl" domain not being blocked

### ISSUE THREAD

**Issue by cbuijs** [StevenBlack/hosts#336]
Dutch video-ads provider. Looks like "player.rootads.nl" is the domain-name to block. I added it manually and didn't seem to break stuff.

**Comment by StevenBlack** [comment]
Hi Chris @cbuijs 

We're just an aggregator. Can you please submit this to one of our [data sources](https://github.com/StevenBlack/hosts/tree/master/data)? Thanks!

Closing.
