### ISSUE TITLE
List of JUST Adware

### ISSUE THREAD

**Issue by justr00t** [StevenBlack/hosts#340]
Is there a way I could get a list of hosts that are just adware? The one on here also includes malware hosts. Can we get one that separates them?

**Comment by Jezza-x3** [comment]
I'm just curious, what is the point?

**Comment by StevenBlack** [comment]
There is no such distinction in any of our data sources.

Maybe the [ATS category at hp-hosts.net](https://hosts-file.net/?s=Browse)?  This is also called Malwarebytes.  We don't use hosts-file.net because their curation activity is relatively low.

**Comment by rautamiekka** [comment]
Besides, you can't always tell something is only an adware or only a malware, it could be both, it could be even something more.

**Comment by justr00t** [comment]
Well, I'm monitoring some of the network activity where I work and I want to see high risk activity first. I don't really care about adware at the moment. There's so much of it in our network that it's hiding the really bad stuff. If I could filter it out, that would be amazing. Or if there was a list of known malware sites, but at least be able to separate them somehow. 
-------- Original message --------From: Jezza-x3 <notifications@github.com> Date: 6/21/17  12:48 PM  (GMT-05:00) To: StevenBlack/hosts <hosts@noreply.github.com> Cc: justr00t <jnicoara11@gmail.com>, Author <author@noreply.github.com> Subject: Re: [StevenBlack/hosts] List of JUST Adware (#340) 
I'm just curious, what is the point?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/StevenBlack/hosts","title":"StevenBlack/hosts","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/StevenBlack/hosts"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Jezza-x3 in #340: I'm just curious, what is the point?"}],"action":{"name":"View Issue","url":"https://github.com/StevenBlack/hosts/issues/340#issuecomment-310138873"}}}

**Comment by justr00t** [comment]
Yeah, I was looking at the ATS Category. I think I might try that. Any idea on how to implement these lists in Splunk?

**Comment by fraxen** [comment]
As an alternative, maybe you can interface https://www.stopbadware.org/ somehow, or use the Google Safe Browsing API? https://developers.google.com/safe-browsing/?csw=1

**Comment by Jezza-x3** [comment]
Also you could try OpenDNS since you can choose to only block adware.

**Comment by funilrys** [comment]
Hi Steve @StevenBlack this one may be closed :smile_cat:
