### ISSUE TITLE
compile hosts

### ISSUE THREAD

**Issue by maravento** [StevenBlack/hosts#342]
Hi. great project. A doubt:
This link compile all hosts that are listed below? (adware + malware + fakenews + gambling + porn + social)
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
The idea is to include the permanent link in the data sheet of our [Blackweb Project](https://github.com/maravento/blackweb) 

Thanks

**Comment by Jezza-x3** [comment]
No. That link is for Adware and Malware only. 

Here is ALL of them. 

https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

**Comment by Jezza-x3** [comment]
I've read the readme of your project. Can you explain how it helps with the squid proxy software stuff?

**Comment by maravento** [comment]
Our script downloads public blacklists and compiles them to make them compatible with squid-cache and your lists contain black domains

To confirm:
Adware + malware: Https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Fakenews + gambling + porn + social: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

It is right?

**Comment by Jezza-x3** [comment]
@maravento The link I put is the one with everything.

**Comment by maravento** [comment]
To confirm: Does this link contain everything? (adware + malware + fakenews + gambling + porn + social)
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

**Comment by Jezza-x3** [comment]
Yes.

**Comment by maravento** [comment]
Thanks a lot. Congratulations on your project
