### ISSUE TITLE
Where to report bad address in list?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [StevenBlack/hosts#346]
I know the lists come from many sources, so is there ONE place where I can report an address in the list that causes problems for me?

The list I use is https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts

f.Wishabi.net causes fredmeyer.com not to load images in their ads.
https://www.fredmeyer.com/weeklyad

I have to manually remove it every time I update the hosts file.

**Comment by StevenBlack** [comment]
There is no one place to report issues with source data.

Each source has a `update.json` file wherein is all the information for that source.

For gambling the [update.json file](https://github.com/StevenBlack/hosts/blob/master/extensions/gambling/update.json) says this:

    {
        "name": "Sinfonietta's gambling blocking hosts file",
        "description": "A collection of category-specific host files.",
        "homeurl": "https://github.com/Sinfonietta/hostfiles",
        "frequency": "occasional",
        "issues": "https://github.com/Sinfonietta/hostfiles/issues",
        "url": "https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts"
    }

So please report this issue to https://github.com/Sinfonietta/hostfiles/issues

Thanks!
