### ISSUE TITLE
License coverage misleading

### ISSUE THREAD

**Issue by brarcher** [StevenBlack/hosts#350]
This project's license is MIT, however the project also sources host files from several other projects which do not have MIT compatible licenses. Digging through some of the dependencies finds some of the following:

- GPLv3
- CC BY-NC-SA 4.0
- CC Attribution 3.0
- (could not find license for a few)

If one were to attempt using the project believing that all of its content is covered by MIT, one may be surprised later to find that they are actually using a number of other licenses as well.

This issue is to clarify the coverage of the project's license. Certainly the license cannot cover the content of most of the hosts files, as they are sourced from other projects. Perhaps make a note of this somewhere, perhaps on the README.

**Comment by rautamiekka** [comment]
And what would that solve or help ?

**Comment by brarcher** [comment]
Licensing issue are typically legal issues. If one were interested in using the project, knowing that the license of the project only represents the python code (if that is the scope) will alert users that they will need to investigate each dependency in order to be confident they are legally allowed to use the dependencies. 

At first glance I believed that the license in the project represented all host files provided by the project. However, after further research I found this to be incorrect.

**Comment by StevenBlack** [comment]
@brarcher is right, the readme should say something about this.

**Comment by rautamiekka** [comment]
Is just that everything needed ? I've a feeling it's not, and unless someone understands the licensing to tell what to do ...

**Comment by StevenBlack** [comment]
Well, we already have a section devoted to the various data sources.  An extra mention that some of these sources have different licenses is a good idea.  

For example, some licenses require attribution so that's a sign to leave source file comments intact.

**Comment by brarcher** [comment]
As this repo is serving as a mirror for other's host files, certainly keeping the licenses in the hosted files is needed. The licenses do not appear at the top of the files, and it is not easy to determine the delimits of the individual files so that the licenses can be extracted. I would suggest putting at the top of each unified file the list of sources and their respective licenses. Example:
```
# This hosts file is a merged collection of hosts from reputable sources,
# with a dash of crowd sourcing via Github
#
# Date: July 04 2017
# Number of unique domains: 0
#
# Fetch the latest version of this file: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
# Project home page: https://github.com/StevenBlack/hosts
#
# Sources:
#
# AdAway: https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
# ...
#
# Licenses:
#
# CC Attribution 3.0: http://creativecommons.org/licenses/by/3.0/
# MIT: https://github.com/StevenBlack/hosts/blob/master/license.txt
# ...
#
# ===============================================================
```

What may be also helpful is listing a summary of the licenses which apply to specific host files in the Unified host files table:

<img width="926" alt="screen shot 2017-07-07 at 10 07 22 pm" src="https://user-images.githubusercontent.com/5264535/27981834-bc60dfe2-6360-11e7-9d0b-896241529ce9.png">

The license could also be shown in the Sources table:

<img width="925" alt="screen shot 2017-07-07 at 10 09 54 pm" src="https://user-images.githubusercontent.com/5264535/27981844-0901d3d8-6361-11e7-9954-21d0ecbd44b2.png">

This will make it much more clear what licenses apply to what host files, both before the files are downloaded and after. Do not worry about the legality of the licenses (as long as this project is following the license terms of the sources, that is) or even if the licenses are compatible. It is up to a user to determine which host files they are allow to use based on their restrictions or needs.

**Comment by brarcher** [comment]
I've a question about the unified list extensions. Where are the extensions sourced from? The readme says that the entries in the Sources table always make it into the unified files, so does that mean the sources for the extensions are not listed in the readme?

**Comment by StevenBlack** [comment]
Hi Branden @brarcher 

Sources for extensions are listed in the readmes for that recipe.

For example, https://github.com/StevenBlack/hosts/tree/master/alternates/fakenews-gambling-porn-social

**Comment by brarcher** [comment]
Oh, I did not realize that the Sources table was different for each readme. That makes sense. If you are satisfied with how the Sources table may look from my proposed change, I can help by adding that same format to the remaining readme's and take a first pass on filling out the licenses.

**Comment by StevenBlack** [comment]
Branden @brarcher go for it!  Thank you very much for this kind offer.  This will really improve the product here.

**Comment by brarcher** [comment]
@StevenBlack, are you interested in selecting a license for the "Steven Black's ad-hoc list" you provide? If so, can you document that in a LICENSE file somewhere and update the related json file?
