### ISSUE TITLE
OneDrive cannot connect or sign in

### ISSUE THREAD

**Issue by tienhuynh5312** [StevenBlack/hosts#351]
I have used your host file to set up adblock list in DNSMasq on my DDWRT router. However, if I turn on my VPN to a remote server (TorGuard VPN), onedrive can re-establish the connection.

**Comment by StevenBlack** [comment]
@tienhuynh5312 do you know which domain is being blocked?

Anyone else experiencing this?

**Comment by Laicure** [comment]
Weird, I'm always up-to-date (using Steven's default hosts list + other hpHosts sources) on my Win8.1Pro and onedrive syncs peacefully without any errors. Even on my Windows Phone and Note 4.

**Comment by tienhuynh5312** [comment]
I have spotted out the error causing this. Beside using DNSmasq adblock host, I turned on Encrypt DNS that use Adguard DNS (maybe other DNS in the ddwrt setting). After I disable Encrypt DNS, everything works just fine now. @StevenBlack

**Comment by StevenBlack** [comment]
@tienhuynh5312 that's interesting.  Thanks.

Closing.
