### ISSUE TITLE
Why do all the hosts describe total unique domains as 0?

### ISSUE THREAD

**Issue by onmyouji** [StevenBlack/hosts#352]

**Comment by Jezza-x3** [comment]
Where? Can you show what you mean?

**Comment by Jezza-x3** [comment]
Nevermind, I see. In the readme. @stevenblack

**Comment by onmyouji** [comment]
And also in the hosts file itself.

**Comment by gfyoung** [comment]
That's my bad.  I've been trying to refactor the code a bit, but I overlooked this.
