### ISSUE TITLE
Requesting Porn Only List

### ISSUE THREAD

**Issue by rcmpayne** [StevenBlack/hosts#358]
Using Unified hosts + porn, i find way too many false positives and its almost a full time job now to keep up with it. is it possible to create porn only list without the base Host?

**Comment by Jezza-x3** [comment]
What false positives are you getting?

You'll have to manually merge the two find here. https://github.com/StevenBlack/hosts/tree/master/extensions/porn

**Comment by rcmpayne** [comment]
Thanks, i was able to easily create a new porn list and block it. The issue i am having is with amazon and aws sites getting blocked or pictures with in. If you have a android device, install amazon app and attempt to use it and you will see what i mean.

**Comment by Jezza-x3** [comment]
I do have an Android and do not have the problem you have.
