### ISSUE TITLE
Other source found: eladkarako.com hosts files

### ISSUE THREAD

**Issue by timofonic** [StevenBlack/hosts#359]
@eladkarako has the following lists:

https://raw.githubusercontent.com/eladkarako/hosts.eladkarako.com/master/build/hosts.txt 127.0.0.1 version  13.7 MB 

https://raw.githubusercontent.com/eladkarako/hosts.eladkarako.com/master/build/hosts0.txt 0.0.0.0 version. 12.8 MB

I don't know how he got the data, but it seems he used [Robtex](https://www.robtex.com) service for something, according to [ Line number 28 of /eladkarako/hosts.eladkarako.com/_builder.js file](https://github.com/eladkarako/hosts.eladkarako.com/blame/master/_builder.js#L28).

**Comment by eladkarako** [comment]
<strong>I don't recommend adding/using ANY those list anywhere anymore.</strong>
<hr/>
they are not mainstream, and <strong>will</strong> often breaks websites.
and please don't use <code>https://raw.githubusercontent.com/eladkarako...</code>
you can fork it on your own as advised in the readme (<em>a.k.a. replace the USERNAME in <code>https://raw.githubusercontent.com/USERNAME/...</code>).
thank you.

**Comment by StevenBlack** [comment]
Thanks for the clarification, @eladkarako!

Closing.

**Comment by eladkarako** [comment]
@StevenBlack 
here are the updated links, <a href="http://hosts.eladkarako.com/">GitHub hosted</a>.

<pre>
HOSTS (HOSTS format)
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts0.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_with_localhost.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts0_with_localhost.txt

HOSTS (HOSTS in <strong>AdBlock format</strong> for the browser)
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock.txt

AdBlock lists
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_block.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_block_inline_script.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_hide.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_style_inject.txt
</pre>

<hr/>
TL;DR

<code>hosts_adblock_anti_annoyances_hide.txt</code> is a collection of hiding-rules,
<code>hosts_adblock_anti_annoyances_block.txt</code> is purely connection-blocking,

Those AdBlock-lists will <strong>work best with <a href="https://github.com/gorhill/uBlock/releases">uBlock-origin</a> <sup><a href="https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm">#1</a>, <a href="https://addons.mozilla.org/firefox/addon/ublock-origin/">#2</a></sup></strong> (and not other AdBlock extensions).

<code>hosts_adblock_anti_annoyances_block_inline_script.txt</code> designed to stop malicious-scripts before they are being executed at all,
<code>hosts_adblock_anti_annoyances_style_inject.txt</code> allow small fixes that can not be done by hiding-rules.
