### ISSUE TITLE
*.ypu.edu.tw

### ISSUE THREAD

**Issue by pinomeng** [StevenBlack/hosts#362]
This domain is Taiwan's University (Yuanpei University of Medical Technology)

**Comment by funilrys** [comment]
There's only [ypu.edu.tw](https://github.com/StevenBlack/hosts/blob/77c68a31bd4884ac623b2fdd729062eeaa786a7b/data/add.Risk/hosts#L3111) 

What do you think about this @FadeMind  ?

**Comment by pinomeng** [comment]
I was saw only "### Extra rules for @StevenBlack 's hosts project", so I report to you :-P

I just curious why university's website was added to hosts list.

**Comment by funilrys** [comment]
You were right @pinomeng ;)

**Comment by FadeMind** [comment]
I can simply whitelisting this domain if needed.

**Comment by StevenBlack** [comment]
This domain looks OK to me @FadeMind

**Comment by funilrys** [comment]
@StevenBlack unreachable per browser by me but reachable with nslookup ...

**Comment by FadeMind** [comment]
@StevenBlack fixed in https://github.com/FadeMind/hosts.extras/commit/346e219d768f98cfb27c4ec34616ed8502e281f0

**Comment by StevenBlack** [comment]
Thanks Tomasz @FadeMind and Pino @pinomeng.  New hosts file is live and online now.
