### ISSUE TITLE
False Positive: bestbuy.ca

### ISSUE THREAD

**Issue by kronflux** [StevenBlack/hosts#368]
I don't have the time right now to test without the hosts file, but bestbuy.ca is in the list(I use fakenews-gambling)
upon removing, still cannot access, so something it uses must also be blocked I assume.

**Comment by funilrys** [comment]
cc @mitchellkrogza

**Comment by mitchellkrogza** [comment]
Thanks @funilrys fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/d336f3edee7f1a67681c1015be24e85c9003ca15

**Comment by funilrys** [comment]
Can be closed @kronflux @StevenBlack :smile_cat:

**Comment by StevenBlack** [comment]
Thanks everybody!
