### ISSUE TITLE
Spotify ads

### ISSUE THREAD

**Issue by TerritorioJoven** [StevenBlack/hosts#37]
# [Spotify]

127.0.0.1 media-match.com
127.0.0.1 adclick.g.doublecklick.net
127.0.0.1 www.googleadservices.com
127.0.0.1 open.spotify.com
127.0.0.1 pagead2.googlesyndication.com
#127.0.0.1 desktop.spotify.com
127.0.0.1 googleads.g.doubleclick.net
127.0.0.1 pubads.g.doubleclick.net
127.0.0.1 securepubads.g.doubleclick.net
#127.0.0.1 audio2.spotify.com
#127.0.0.1 www.omaze.com
#127.0.0.1 omaze.com
#127.0.0.1 bounceexchange.com
127.0.0.1 core.insightexpressai.com 
127.0.0.1 content.bitsontherun.com
127.0.0.1 s0.2mdn.net
127.0.0.1 v.jwpcdn.com
127.0.0.1 d2gi7ultltnc2u.cloudfront.net
127.0.0.1 crashdump.spotify.com 
127.0.0.1 adeventtracker.spotify.com 
127.0.0.1 log.spotify.com 
127.0.0.1 analytics.spotify.com
127.0.0.1 ads-fa.spotify.com

**Comment by StevenBlack** [comment]
Thanks @TerritorioJoven.

The purpose of this repo is to consolidate and merge the work of several organizations on an ongoing basis.

I'm not keen on lists of domains that aren't actively curated and maintained.

Several of the domains you suggest are already here, like doubleclick and Google's.

But thanks for the suggestions.  I'll keep an eye on those Spotify domains.
