### ISSUE TITLE
Merge Tobias-B-Besemer/hosts

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [StevenBlack/hosts#371]
Some time ago (long time before I found your list), I started my own hosts-list...
...but I stopped working on it...
Maybe you wanna merge some of my data...
My list is here: https://github.com/Tobias-B-Besemer/hosts
(With also some sublists e.g. for CP...)

**Comment by StevenBlack** [comment]
Hi @Tobias-B-Besemer thank you for the suggestion.

At this juncture, and for the foreseeable future, I'm only considering actively curated data sources.  This is key to a good hosts file, in my view.

Happy computing!
