### ISSUE TITLE
Unified-Hosts-AutoUpdate For Windows

### ISSUE THREAD

**Issue by ScriptTiger** [StevenBlack/hosts#375]
I just uploaded a new script I made for Windows users that attempts to make the process even more user-friendly by updating their hosts file automatically and by not requiring Git or Python. I am not too savvy on how all the licensing and acknowledgments go, but I am open to any feedback and I apologize in advance if I made any serious mistakes in that area. I think it would be cool if it could be added to this project, but I am not sure what the consensus might be on that. It is strictly for making it easier on Windows users by downloading the latest pre-generated hosts files generated by Steven Black and injecting them into the local hosts file of the end user. It does not generate the files itself, as the other scripts here do. As the pre-generated hosts files of this project are updated rather regularly with new information, I thought it would be a performance increase for the script to just skip the generation and just download them. However, if generation is seen as an important aspect to be part of this project, it can be an easily added feature without requiring any additional executables.

https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate

I look forward to any feedback you all might have, the good, bad, and ugly. I have been a huge consumer and fan of this project for a while and have the utmost respect for those working on it. So even if the feedback is an immediate takedown request, I'm ready and willing to follow along with whatever guidance you have.

**Comment by rautamiekka** [comment]
The code would be orders of magnitude more readable if it was indented.

**Comment by ScriptTiger** [comment]
Definitely. I've kind of adapted my own style of blocking over the years, but it's definitely not compatible with the styles object-oriented programmers are used to. I'll definitely clean that up, thanks!

**Comment by ScriptTiger** [comment]
Also, since this issue is specifically plugging my AutoUpdate repo, I'll shamelessly just throw out I do have another repo specific to DualServer. I only mention that because after skimming through the issues there seems to be a lot of requests for different formats, so that's one I've got covered if anyone is interested.

**Comment by ScriptTiger** [comment]
I'll just let the readme raise awareness from here on out, I hate lingering open issues. But please don't forget to send me some feedback, even if it is positive and nothing is wrong.
