### ISSUE TITLE
Host file causing unable to load AWS website https://www.aws.training

### ISSUE THREAD

**Issue by qarqun** [StevenBlack/hosts#378]
i'm having problem to load that site if using the default Unified hosts file with no extensions installed.
I already update to the latest host file but the issue persist.

if i remove the host file and replace with windows original host in my windows machine, then no issue to access that website.

can assist to find what domain that has been blocked inside the host file that prevent this site to load successfully.
Please help. 

tq

**Comment by ScriptTiger** [comment]
Try removing munchkin.marketo.net from your hosts file and let us know the result.

**Comment by qarqun** [comment]
haha.. same..i just found the culprit 5 min ago...

confirmed... after commenting this, the site load successfully.
#0.0.0.0 munchkin.marketo.net

thanks.

**Comment by ScriptTiger** [comment]
No worries. Don't forget to close the ticket so our benevolent leader has less on his plate. If we continue to get hits on this, we'll comment it out of the final.

**Comment by qarqun** [comment]
Noted.
The domain included in **MVPS hosts file**.
I already report to them.

**Comment by ScriptTiger** [comment]
Nice, thanks.
