### ISSUE TITLE
Problem running the script

### ISSUE THREAD

**Issue by agucova** [StevenBlack/hosts#38]
Hello! I want to install the hosts on my osx... The problem is, whenever I try to run the script, I get:
"A line in the hostfile is going to cause problems because it is nonstandard
> The line reads 0.0.0.0
> please check your data files. Maybe you have a comment without a #?"

My actual hosts has no line with 0.0.0.0, and the hosts provided, has all the 0.0.0.0, mainly cause that blocks everything... 
Any ideas?
I'm using OSX 10.11.11 (Latest Version). And the sources have been updated.

**Comment by StevenBlack** [comment]
Yeah, it looks like the latest from `someonewhocares.org` is the culprit here.
