### ISSUE TITLE
Auto Git and hostfile Update .bat

### ISSUE THREAD

**Issue by GammaG** [StevenBlack/hosts#380]
Hey man I thought its a nice idea to build something that would pull the last version from your repository (master) and then directly patches up the host file. So I made some bat file to do this.
[updateProject.zip](https://github.com/StevenBlack/hosts/files/1214869/updateProject.zip)
Works nice for me now.
Regards

**Comment by ScriptTiger** [comment]
I like all the Windows support coming in recently. If I am not mistaken though the updateHostsWindows.bat is supposed to do just that. If you would like to contribute to it, can you send a PR and we'll check it out? I think they have been looking for some help with it, so I am sure it would be much appreciated.

**Comment by GammaG** [comment]
Thanks for your answer. Sure I'll put it on some repository and send that link then. 
Also thanks for your recommondations I'll change some parts. %temp% is a good idea.

**Comment by ScriptTiger** [comment]
And thank you for your interest and active participation in the project!

**Comment by GammaG** [comment]
OK I did some changes and have up it on a repository as well:
https://github.com/GammaG/HostUpdateMasterBat 
May I'll do some more if I got time.

**Comment by ScriptTiger** [comment]
All right, thanks!

**Comment by gfyoung** [comment]
@ScriptTiger : If you clone that branch, you should be able to update Windows `host` file from start to finish with no issues.  The name is a little misleading, as it's not really experimental anymore (at least for me).  Feel free to test it out if you're interested.

@GammaG : Cool that you did this!  A smaller repo is nicer to clone than one humongous one :smile:

**Comment by ScriptTiger** [comment]
If the point is just a quick repo to generate the file and it gets deleted less than a second later, perhaps "--depth 5" should be changed to "--depth 1".

**Comment by GammaG** [comment]
yeah thats a good point will do

**Comment by StevenBlack** [comment]
Closing.
