### ISSUE TITLE
Please block functionalclam.com

### ISSUE THREAD

**Issue by folknor** [StevenBlack/hosts#381]
https://github.com/easylist/easylist/commit/a4d380ad1a3b33a0fab679a1a8c5a791321622b3

https://news.ycombinator.com/item?id=14978228
Quote, comment from user "userbinator" on hn:

> Thanks, just added it to my HOSTS file...
> I don't know if the Streisand Effect is going to happen with this one, but it seems very odd that the DMCA could even be applicable here.
> Edit: https://www.copyright.gov/help/faq/faq-protect.html#domain
> _Can I copyright my domain name?_
> _Copyright law does not protect domain names._

So this is probably an invalid DMCA takedown request.
In any case, I'm going to block it entirely on my end - and I suspect many people will want to do the same.
So it might be worth adding.

**Comment by DazzaRPD** [comment]
Steven, or others, can you also confirm if this list is also safe from the DMCA?

It's all fair and well adding this entry now, but if Admiral or someone goes in and requests that we remove stuff from the hosts file, then we may have problems on our hands

**Comment by folknor** [comment]
Also note this https://pgl.yoyo.org/adservers/admiral-domains.txt
I believe all those domains will get included in https://github.com/StevenBlack/hosts/tree/master/data/yoyo.org on the next update.

**Comment by StevenBlack** [comment]
Indeed, this is in commit 59cc86477.

Closing.

**Comment by mrjackyliang** [comment]
I found 1,016 new Admiral domains, based off of my list and the `yoyo.org` list above. Not sure if I should post it here. I verified it all myself with the help of SecurityTrails also.

**Comment by llacb47** [comment]
See also https://github.com/jkrejcha/AdmiraList

**Comment by mrjackyliang** [comment]
@llacb47 Just checked! 74 domains expired on their list. And after double-checking, I have 1,014 domains now!
