### ISSUE TITLE
TERA EU login server being blocked

### ISSUE THREAD

**Issue by Atulin** [StevenBlack/hosts#385]
I recently decided to come back to playing TERA, the EU version, and it turns out their login server is being blocked by something. After restoring my .hosts file to the previous state, the game started working just fine.

I did do a quick Ctrl+F through the file looking for some entries that might be blocking that, but to no avail. And I'd rather not try every blocked entry one by one to see which one is responsible.

**Comment by ScriptTiger** [comment]
What OS are you running?

**Comment by ScriptTiger** [comment]
I'm not savvy on this game in particular, but I just searched about it real quick. Do you have the option to play it inside your browser? Independent of OS, if you can play it in your browser, you can F12 in Chrome and check the "Sources" tab for a short list of domains the site is pulling from. Now it might not be the same for your client, but if you notice you have the same problem with your browser, it's worth a shot and can be checked relatively quickly.

**Comment by ScriptTiger** [comment]
Also, does it have a special launcher executable? Like launcher.exe or something? They are usually pretty small and basically just display a webpage so they can easily update the ads and game news and updates and whatnot. If this is what you are using to start the actual game, you can attach that here as well so we can take a look at it to see what domains it is calling inside of it.

**Comment by Atulin** [comment]
It's Win10 x64, latest update, no Creator's Update.

Also, TERA is not a browser game. So, no, there's no option to play it in a browser.

Yes, it does have a launcher executable. I will attach it to the post if you say so.
[TERA-launcher.zip](https://github.com/StevenBlack/hosts/files/1226164/TERA-launcher.zip)

**Comment by Laicure** [comment]
/hmm can you look at the domains inside the [Resource Monitor](https://www.computerhope.com/jargon/r/resmon.htm) via the Network tab then expand the _Network Activity_ group. Well, use that method to see the domains being accessed by the respective exe (if you don't want to use a third party application).

![image](https://user-images.githubusercontent.com/8619566/29333370-193f7694-8236-11e7-84bb-b3e2b24063ec.png)

As for the IPs, I think we can convert that to their domain names?

**Comment by Atulin** [comment]
![image](https://user-images.githubusercontent.com/11233299/29335422-e38e60a8-820a-11e7-8a3b-68fd917bd3eb.png)
Looks like `*.iesnare.com` and `*.gfsrv.net` might be at fault.

**Comment by Laicure** [comment]
I did a quick look-up on the latest hosts file and ***.iesnare.com** has multiple entries.
```
admin.iesnare.com
ci-mpsnare.iesnare.com
dra.iesnare.com
iesnare.com
impsnare.iesnare.com
mpsnare.iesnare.com
mx.iesnare.com
snare.iesnare.com
www.admin.iesnare.com
www.ci-mpsnare.iesnare.com
www.iesnare.com
www.mpsnare.iesnare.com
```
***.gfsrv.net** only has _delivery.ads.gfsrv.net_ and _media.ads.gfsrv.net_

**Comment by Atulin** [comment]
I commented them all out just to be sure, and everything's working just peachy now. Thanks!
