### ISSUE TITLE
Small text change to readme

### ISSUE THREAD

**Issue by Jezza-x3** [StevenBlack/hosts#397]
https://github.com/StevenBlack/hosts#extensions

Perhaps add fake news to the list of extensions in the paragraph? I have no idea how to do a pull request so just opened an issue instead.

**Comment by ScriptTiger** [comment]
This has already been added to the template and will take effect the next time Steven runs the update script in the repo.

**Comment by ScriptTiger** [comment]
@gfyoung is going over the readme now with his official Chicago English Usage rule book.
