### ISSUE TITLE
fakenews-gambling-porn-social offline

### ISSUE THREAD

**Issue by maravento** [StevenBlack/hosts#398]
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

Error 503 first byte timeout
first byte timeout
Guru Mediation:
Details: cache-mia1324-MIA 1503493038 2169659452
Varnish cache server

**Comment by ScriptTiger** [comment]
This is a cloud-side error. It's affecting access to everyone's content on the raw.githubusercontent.com domain. If it persists, we'll shoot an e-mail to GitHub's support team. Since it's affected everyone, however, it should be  noticed and straightened out pretty quickly.

**Comment by ScriptTiger** [comment]
This issue has worked itself out and can be closed now.

**Comment by maravento** [comment]
thanks
