### ISSUE TITLE
Aflac Website

### ISSUE THREAD

**Issue by BennyTest** [StevenBlack/hosts#40]
Something in the Host file is preventing me from logging into Aflac's website. I can visit Aflac's website without any problem but if I use the Host file then I am prevented from logging in. I've captured the traffic and then scanned the file and cannot find a match.  This is the captured traffic:
Category                                                                          Website being accessed.
Business and Economy: Financial Data and Services   www.aflac.com
Information Technology: Search Engines and Portals  www.google.com
Information Technology                              vassg142.ocsp.omniroot.com
Information Technology                              vassg142.ocsp.omniroot.com
Information Technology                              ocsp.entrust.net
Information Technology                              ocsp.entrust.net
Information Technology                              ocsp.entrust.net
Information Technology                              ocsp.comodoca.com
Information Technology                              ocsp.entrust.net
Information Technology                              ocsp.geotrust.com
Information Technology                              gn.symcd.com
Information Technology                              gb.symcd.com
Information Technology                              gn.symcd.com
Information Technology                              g.symcd.com
Information Technology                              gn.symcd.com
Information Technology                              ocsp.geotrust.com
Information Technology                              gn.symcd.com
Information Technology                              ocsp.entrust.net
Information Technology                              ocsp.entrust.net
Information Technology                              gz.symcd.com
Information Technology                              gz.symcd.com
Information Technology                              ocsp.trustwave.com
Information Technology                              ocsp.trustwave.com
Information Technology                              ocsp.trustwave.com
Information Technology                              g.symcd.com
Information Technology                              ocsp.trustwave.com
Information Technology                              ocsp.comodoca.com
Information Technology                              gb.symcd.com
Miscellaneous: Web Infrastructure                   ocsp.digicert.com
Miscellaneous: Web Infrastructure                   ocsp.digicert.com
Miscellaneous: Web Infrastructure                   ocsp.godaddy.com
Miscellaneous: Web Infrastructure                   ocsp.digicert.com
Miscellaneous: Web Infrastructure                   ocsp.digicert.com
Miscellaneous: Web Infrastructure                   ocsp.godaddy.com
Miscellaneous: Web Infrastructure                   ocsp.godaddy.com
Miscellaneous: Web Infrastructure                   ocsp.godaddy.com
Miscellaneous: Web Infrastructure                   ocsp.godaddy.com
Miscellaneous: Web Infrastructure                   ocsp.godaddy.com
Miscellaneous: Web Infrastructure                   ocsp.godaddy.com
Miscellaneous: Web Infrastructure                   ocsp.godaddy.com
Miscellaneous: Web Infrastructure                   ocsp.digicert.com
Miscellaneous: Web Infrastructure                   ocsp.digicert.com
Information Technology                              ss.symcd.com
Information Technology                              gn.symcd.com
Information Technology                              gn.symcd.com
Information Technology                              ss.symcd.com
Information Technology                              ocsp.entrust.net
Information Technology                              ocsp.entrust.net
Information Technology                              api.wd.lenovo.com
Business and Economy: Financial Data and Services   www.aflac.com
Miscellaneous: Web Infrastructure                   ocsp.digicert.com
Miscellaneous: Web Infrastructure                   ocsp.digicert.com
Business and Economy: Financial Data and Services   www.aflac.com
Information Technology                              dl.javafx.com

**Comment by StevenBlack** [comment]
Hi @BennyTest I'm having a hard time parsing what you're trying to say. 

I investigated several of those domains and found nothing being blocked.  But this is something you should do yourself — figure out what's being blocked.  I have no way of knowing other than searching the generated hosts file for you.

If you find a blocked domain you need, add it to the `whitelist` file and re-generate the hosts file.  Let us know what you find.

**Comment by BennyTest** [comment]
Thanks, the block does not happen until the user logins in but watching the user log in does not show any links that are in the host file.

Benny Lane

**Comment by StevenBlack** [comment]
If you invoke the Chrome Developer Tools or install the [FireBug extension](https://getfirebug.com/downloads) and open it before logging in, you'll see all inaccessible requests and their URLs highlighted in red in the list of HTTP requests.

This tells you which domains can't be reached or, more specifically, which assets aren't getting to your browser.
