### ISSUE TITLE
seasonvar.ru

### ISSUE THREAD

**Issue by mitchellkrogza** [StevenBlack/hosts#401]
@StevenBlack 

As per  issue logged here - https://github.com/AdAway/AdAway/issues/934#issuecomment-326039368

On my own list Badd Boyz Hosts I have removed this entry as the web site is safe to visit as far as I am concerned and not actually in my opinion a bad host. This entry made it onto my list as I picked it up through fake referrer traffic on a number of my web sites, the data of which I use for my [Nginx](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker) and [Apache](https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker) Bad Bot & Referrer Blockers. 

So my latest commit to [Badd Boys](https://github.com/mitchellkrogza/Badd-Boyz-Hosts) > https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/a0181c421143c5cf29aa2b4c819a40ce0ad56408 has removed seasonvar.ru and instead introduced blocking of it's ad's with the addition of

serving.adbetclickin.pink
creatives.adbetclickin.pink
adbetclickin.pink

The latest build in progress on Badd Boyz, complete in about 2 hours time will also remove about 88 dead and no longer existent domains.

**Comment by StevenBlack** [comment]
Awesome.  Thanks Mitchell @mitchellkrogza.

**Comment by mitchellkrogza** [comment]
No problem @StevenBlack ... Next build will have additional domains 3 listed in https://github.com/AdAway/AdAway/issues/934#issuecomment-326268044 by @SMed79 and will also be cleaned of all dead and inactive domains. 

The builds take a good 2 hours due to the [funceble script](https://github.com/funilrys/funceble) used for checking for all the dead and inactive domains. But I like having clean lists which is why I have spent so much time with @funilrys helping him fine tune it to my needs and constantly throwing feature requests at him and he just kept stepping up to all the challenges and making them a reality. It's now truly a remarkable script.

**Comment by ScriptTiger** [comment]
@mitchellkrogza, thanks for linking that. I was actually going to ask you what you used for that. Definitely going to have to play with it later.

**Comment by mitchellkrogza** [comment]
@ScriptTiger I think you will be massively impressed with funceble. Through my constant pushing for features @funilrys achieved what I thought was impossible an autosave and continue mode for Travis to beat the 50 minute timeout. I have a major build test in progress on this repo been going 4 days and still about 5 or 6 left. Have a look at >>> https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist And https://travis-ci.org/mitchellkrogza/Ultimate.Hosts.Blacklist/builds

**Comment by SMed79** [comment]
Thank you for [funceble script](https://github.com/funilrys/funceble), it is the tool I was looking for.

I think it is better to check for dead domains more than one time and from different geo lock.
(_some hosts can down for a period of time or blocked by default in certain country_).

**Comment by mitchellkrogza** [comment]
@SMed79 all the credit must go to @funilrys .... what I am doing is building a list of dead domains which I store in the repo and it get's stripped out of input file before I create my hosts file. I keep this list of dead-domains in the repo so that it can be added to and also re-tested by itself every now and again for any sites which have become active again.
