### ISSUE TITLE
File host blocks onedrive link

### ISSUE THREAD

**Issue by difo** [StevenBlack/hosts#403]
1drv.ms
is not adware or malware are Microsoft Onedrive links

**Comment by StevenBlack** [comment]
@mitchellkrogza can you look into `1drv.ms`?  Thanks!

**Comment by mitchellkrogza** [comment]
@StevenBlack build in progress, will notify you once done.

**Comment by mitchellkrogza** [comment]
https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/fec3a4b85f0db9f72746389a5847f988e4730646 Fixes: #403

**Comment by StevenBlack** [comment]
Thanks Mitchell @mitchellkrogza.  And thank you, Francesco @difo, for flagging this.

Closing.

**Comment by mitchellkrogza** [comment]
:+1: @ StevenBlack now that I have started building my central repo of dead, inactive, whitelisted and false positives moving forward is going to be a breeze for curating
