### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by rdj2017** [StevenBlack/hosts#408]
Using Fakenews+Gambling list,

motherless.com (porn site) being blocked while NOT using porn list.

**Comment by StevenBlack** [comment]
Thank you @rdj2017.

`motherless.com` is blocked by the following sources:

    data/Badd-Boyz-Hosts/hosts (general)
    extensions/porn/clefspeare13/hosts (porn)
    extensions/porn/sinfonietta/hosts (porn)

@mitchellkrogza what's your read on motherless.com?  Is there a nefarious side to this one?  Thanks!

**Comment by mitchellkrogza** [comment]
Just take a look at it, should remain blocked and I receive referrer spam on my sites from them. So as far as my verdict goes it remains blocked.

**Comment by StevenBlack** [comment]
Good call.

@rdj2017 this one's not coming off the board anytime soon.  Thank you for inquiring!  We're always happy to spot-check things like this.

Closing.

**Comment by ScriptTiger** [comment]
@mitchellkrogza, calm down, you are being awesome at way too many things and making us all look bad.

**Comment by mitchellkrogza** [comment]
LOL sorry guys you should know me by now 😂😂😂
