### ISSUE TITLE
Huge source: adblock.mahakala.is

### ISSUE THREAD

**Issue by node1634** [StevenBlack/hosts#409]
I've used this source for a larger period of time and it works well. I don't know if the aim of this mod is to be as small as possible, if not this is an about 30MB big hosts file. Unfortunately I also don't know how many hosts are already persistent in the other hosts files, but if these lines get deleted automatically it shouldn't be that big of a problem. 

Source: http://adblock.mahakala.is

**Comment by funilrys** [comment]
Good mornig @mitchellkrogza,

If @StevenBlack don't add this to this repo you could add this source to our [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) repo :smile_cat: 

Have a nice day !

**Comment by mitchellkrogza** [comment]
@funilrys I did have this input source originally in [Ultimate Hosts Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) but removed it at one point as I found it a bit unreliable. But will re-implement it today now that we have the Centralized List Cleaning functions from our Central Repo controller for that.

**Comment by StevenBlack** [comment]
Hi @node1634 thanks for this suggestion.

We hope to strike a balance between safety and usability.  A 30 MB data source is quite beyond what's usable on some (most?) devices.

So closing.
