### ISSUE TITLE
[REQ] Add option to remove comment comment lines from source lists

### ISSUE THREAD

**Issue by kronflux** [StevenBlack/hosts#410]
I see there's the option to remove comments on the same lines as entries, but I don't see an option to leave out comments entirely.

There's a lot of whitespace and a lot of comments throughout. I'd love to be able to clean it up, and leave only the entries.
It's visually unappealing, but more importantly it contributes to filesize, which in the case of routers and similar devices can sometimes be very limited. The more space we can save, the more bad hosts we can block in the future!

It makes sense, of course, to have a line at the beginning of each list, such as "# Start of LIST X - Updated on Xtober XX 20XX" for credit, informational and organizational purposes, but further comments or whitespace are unnecessary, and are in inconsistent formatting due to being created/maintained by different people/groups.

Hopefully this is appealing to more than just me, but either way thanks in advance for considering the request!

Cheers!

**Comment by Laicure** [comment]
+1 for the above proposal, a **-min** (minimal) parameter will [do](https://github.com/Laicure/HostsY#hostsy).

Something like below:
![image](https://user-images.githubusercontent.com/8619566/31087478-c235611e-a7cf-11e7-9f36-f264cd62dec6.png)

**Comment by kronflux** [comment]
maybe a -min [default|fullmin] ?

default would only remove comments, and add credit lines above each list.

fullmin(or whatever you wanted to call it) would remove ALL comments, even credit lines, and perform an alphabetical sort on the list(Exactly like shown in @Laicure's example).

**Comment by kronflux** [comment]
Examples:
--clean:
![notepad _2017-10-02_10-45-30](https://user-images.githubusercontent.com/834451/31088704-dcffadd6-a75e-11e7-927d-6222990cd1b6.png)

--clean min:
![notepad _2017-10-02_10-39-55](https://user-images.githubusercontent.com/834451/31088741-fe846384-a75e-11e7-9ffc-7a1da3f97a97.png)

**Comment by ScriptTiger** [comment]
Depending on your uses, my scripts can automatically do this just by adding the comment characters to the ignore list (the syntax will vary depending on if it's regex or literal), and they already automatically clean white space. Just keep in mind the reason no one distributes such lists is that the distribution of uncredited files would be in violation of the respective licenses. So needless to say, this would be for personal use only.

**Comment by ScriptTiger** [comment]
This actually brings up an interesting segue for a network automation script I have for updating network devices automatically. I haven't made it public yet, but I have been curious as to the level of interest there might be for it.

**Comment by kronflux** [comment]
yeah the intent for removing the credits would be for low-end devices only, where space or memory are extremely minimal(or in some cases, the device may simply not be able to process a large hosts file). The default(and preferred) option would be to leave credits in place.

**Comment by ScriptTiger** [comment]
I'll work on a public version in the coming weeks. I will probably only officially support SSH/TELENT out of the box to start. I also have a version that does support automation through HTTP/HTTPS POSTing so you can make multiple changes with a single command to the network device and dramatically speeds things up, however I will need a lot more time to figure out how to make something that would be generic for anyone to use, as HTTP/HTTPS form data is not in a linear structure and is wildly different from device to device.

**Comment by StevenBlack** [comment]
Hi everyone, @kronflux @Laicure @ScriptTiger 

I don't think this can happen.  Here's why: It's all about licensing.

Simply put, some of our sources have licenses that require copyright and licensing notices to remain intact.

**Comment by kronflux** [comment]
Would that matter if it's not actually released in that format?
I would imagine keeping them in tact, and adding the option to use for personal cases should be perfectly fine, since it's the user's own use case, not something that's public.

It would be the same as me manually removing them in a text editor.
I'm not violating anything, because I'm not releasing anything anywhere.

I get where you're coming from, but since it would only be an option, which only runs in a manual use-case scenario, I don't see a problem.

**Comment by StevenBlack** [comment]
@kronflux good point. OK.

**Comment by ScriptTiger** [comment]
Yeah, it's all about the intent to distribute, as they say in the hood.
