### ISSUE TITLE
[New Category] Html Crypto MIners

### ISSUE THREAD

**Issue by AngelTs** [StevenBlack/hosts#413]
# Аntі-WеbМіnеr Ѕtаrt 1.0 43011
0.0.0.0 аzvјudwr.іnfо
0.0.0.0 сnhv.со
0.0.0.0 соіn-hіvе.соm
0.0.0.0 guѕ.hоѕt
0.0.0.0 јrоqvbvw.іnfо
0.0.0.0 јѕесоіn.соm
0.0.0.0 јуhfuqоh.іnfо
0.0.0.0 kdоwqlрt.іnfо
0.0.0.0 lіѕtаt.bіz
0.0.0.0 lmоdr.bіz
0.0.0.0 mаtаhаrіrаmа.хуz
0.0.0.0 mіnесrunсh.со
0.0.0.0 mіnеmуtrаffіс.соm
0.0.0.0 mіnеr.рr0grаmm.соm
0.0.0.0 rеаѕеdореr.рw
0.0.0.0 хbаѕfbnо.іnfо
# Аntі-WеbМіnеr Еnd

**Comment by WillPresley** [comment]
@AngelTs Do you have any interest in turning this into a proper list for this tool? Not for any negative reason, but because if you don't, I can toss it together and submit a pull request so it can be pulled upstream.

**Comment by Leftyx** [comment]
Found another list of coin miners [here](https://github.com/keraf/NoCoin/blob/master/src/blacklist.txt).

**Comment by ScriptTiger** [comment]
Having an up to date list of crypto minters is of course well and good and definitely falls within the mission statement of this project. However, I must insist if the list is going to continue to grow at this rate, can someone offer a curation solution for these, such as a scripted check to verify crypto mining is still actively being conducted by each of the listed entries? I know we are all doing our best to pull together and help out, but I just don't want to end up having something unmanageable and unchecked in the end.

**Comment by AngelTs** [comment]
# Аntі-WеbМіnеr Ѕtаrt NoCoin v1
0.0.0.0 coinhive.com
0.0.0.0 coin-hive.com
0.0.0.0 jsecoin.com
0.0.0.0 server.jsecoin.com
0.0.0.0 load.jsecoin.com
0.0.0.0 static.reasedoper.pw
0.0.0.0 mataharirama.xyz
0.0.0.0 listat.biz
0.0.0.0 lmodr.biz
0.0.0.0 minecrunch.co
0.0.0.0 minemytraffic.com
0.0.0.0 crypto-loot.com
0.0.0.0 2giga.link
0.0.0.0 2giga.link
0.0.0.0 ppoi.org
0.0.0.0 coinerra.com
0.0.0.0 coin-have.com
0.0.0.0 kisshentai.net
0.0.0.0 miner.pr0gramm.com
0.0.0.0 kiwifarms.net
0.0.0.0 anime.reactor.cc
0.0.0.0 joyreactor.cc
0.0.0.0 kissdoujin.com
0.0.0.0 ppoi.org
0.0.0.0 minero.pw
0.0.0.0 coinnebula.com
0.0.0.0 coinnebula.com
0.0.0.0 afminer.com
0.0.0.0 coinblind.com
0.0.0.0 webmine.cz
0.0.0.0 monerominer.rocks
0.0.0.0 monerominer.rocks
0.0.0.0 cdn.cloudcoins.co
0.0.0.0 coinlab.biz
0.0.0.0 papoto.com
0.0.0.0 cookiescript.info
0.0.0.0 cookiescriptcdn.pro
0.0.0.0 rocks.io
0.0.0.0 ad-miner.com
0.0.0.0 party-nngvitbizn.now.sh
0.0.0.0 cryptoloot.pro
0.0.0.0 host.d-ns.ga
0.0.0.0 baiduccdn1.com
0.0.0.0 jsccnn.com
0.0.0.0 jscdndel.com
0.0.0.0 mine.nahnoji.cz
0.0.0.0 goredirect.party
0.0.0.0 miner.pr0gramm.com
0.0.0.0 miner.cryptobara.com
0.0.0.0 digger.cryptobara.com
0.0.0.0 kickass.cd
0.0.0.0 morningdigit.com
0.0.0.0 webminepool.com
0.0.0.0 webminepool.tk
0.0.0.0 stackpathdns.com
0.0.0.0 cpu2cash.link
0.0.0.0 googleanalytcs.com
0.0.0.0 coinpirate.cf
0.0.0.0 webmine.pro
0.0.0.0 a-o.ninja
0.0.0.0 gasolina.ml
0.0.0.0 gasolina.ml
0.0.0.0 you.tubetitties.com
0.0.0.0 hive.tubetitties.com
0.0.0.0 playerassets.info
0.0.0.0 tokyodrift.ga
0.0.0.0 bewhoyouare.gq
0.0.0.0 sen-to-zdrowie.ml
0.0.0.0 freecontent.racing
0.0.0.0 freecontent.loan
0.0.0.0 chainblock.science
0.0.0.0 hodling.faith
0.0.0.0 freecontent.bid
0.0.0.0 1q2w3.fun
0.0.0.0 candid.zone
0.0.0.0 lewd.ninja
# Аntі-WеbМіnеr Еnd

**Comment by ScriptTiger** [comment]
These are certainly helpful suggestions for those creating custom lists locally, however for this repo I think we are close to a solution in https://github.com/StevenBlack/hosts/issues/462 and we should focus our efforts on a curated list. And I'm not going to check every single one of the domains listed above, but I can say I personally recognize a good number as already being in our stevenblack/hosts. One we get a dedicated curator for these established, then all further suggestions can be forwarded there so these can be better managed with the focus and attention due them.

**Comment by OtakuPL** [comment]
@AngelTs 
**a-o.ninja** has not miner for more than half a year.
Please delete the domain a-o.ninja from the list.
_Thank you_

**Comment by ScriptTiger** [comment]
This is an old issue. We source our crypto miners from @ZeroDot1's CoinBlockerlists now, https://gitlab.com/ZeroDot1/CoinBlockerLists. Issues with crypto miners should be made over there, https://gitlab.com/ZeroDot1/CoinBlockerLists/issues.

@StevenBlack, I think this can be safely closed.

**Comment by StevenBlack** [comment]
I agree @ScriptTiger.

Closing.
