### ISSUE TITLE
Three false positives and a comment about Badd Boyz Hosts list

### ISSUE THREAD

**Issue by holdit** [StevenBlack/hosts#415]
Hey,

I've found 3 false positives:

- analytics.google.com: This is a website were we go to see Google Analytics stats. As far as I know Google uses (*).google-analytics.com, not analytics.google.com, to collect data.

- piwik.org: Piwik is a free and open-source alternative to Google Analytics. It respects, by default, things like [Do Not Track](https://en.wikipedia.org/wiki/Do_Not_Track) and, because some websites/apps/etc need analytics, allows developers to collect information without giving it to Google.

- teslathemes.com: This is a website that sells WordPress themes. I've bought stuff from them and never had issues.

Now, about Badd Boyz...

I've been recommending and using these unified host files myself for two years now. As any host lists, sometimes domains are added by mistake but these usually never affected me too much. Things started to change when Badd Boyz was added... the number of times I had to manually remove hosts increased.

Today I was trying to access teslathemes.com to download something I bought a few months ago... and it was blocked. Looking at [previous Github issues](https://github.com/StevenBlack/hosts/issues?utf8=%E2%9C%93&q=Badd-Boyz-Hosts%20) we can see that other "good" hosts have been added to the list in the past (pastebin, aliexpress, addons.mozilla.org, etc). And looking at the list, it's easy spot false positives. Three quick examples:

- clinicasusanamota.pt: a Portuguese dental clinic (business);
- clinicabrunomontenegro.com.br: a Brazilian plastic surgeon (business);
- acmlp.pt: a school website (public institution);

While mitchellkrogza seems to be very responsive and quick to remove false positives, there's just too many false positives. If I spent more time, I could find more hosts and improve the list, but in the end it's useless because it's too easy to fake referrals. Blocking hosts with data from server logs will eventually lead to a bad list if there's nothing double checking the blocks.

Also, some domains just don't belong on the "adware + malware" list. +18 websites are supposed to be on the "Unified hosts + porn" list, but the default list includes these domains because these domains are on Badd Boyz list.

This is not something that affects me daily, but sometimes I have to remove a domain and it's a pain in the butt. If it happens on my phone (with Adaway), it's easier to go back to my computer than to make the change.

I understand that every list include (or will include) some host that should not be blocked - it happens and I'm fine with that - but in this case there's just too many false positives. For the reasons I mentioned, and unless something changes, I think that Badd Boyz should not be part of the default unified hosts file. Either this or a new unified list should be created with only "good quality lists".

Thanks for all your work.

**Comment by funilrys** [comment]
cc @mitchellkrogza

**Comment by mitchellkrogza** [comment]
@holdit @StevenBlack @funilrys thanks 

First 3 false positives listed addressed in https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/commit/dd70c44efbe686c8db7e3f40a2bb775520c4909f and stripped out automatically from Badd Boyz in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/ed70878a4b405e6ac9295875921b9ac239ab8db3

@holdit Badd Boyz list is under some manual review today and a lot of those false positives (easily faked referrers) will be addressed and removed. My intention is NOT to have inaccurate data and it will be addressed as I always do in a timely fashion and thank you for your time in reporting this.
