### ISSUE TITLE
false positive blocks video streaming on mtv.ca

### ISSUE THREAD

**Issue by kronflux** [StevenBlack/hosts#419]
Apparently this has been fixed by some of the source lists, as I found comments such as "affects video streaming"
but mtv.ca videos will not play due to a backend streaming service they use being blocked by this list.
the entry is:
s0.2mdn.net

thanks :)

**Comment by ScriptTiger** [comment]
We should probably pinpoint various CDNs/MDNs that deliver content/media for various entities as they can be abused but are not in themselves a culprit and affect multiple things when blocked. However, obviously some such networks are entirely shady and do indeed deserve to be blocked in total.

**Comment by StevenBlack** [comment]
@kronflux it turns out that `s0.2mdn.net` is flagged by three of our sources: someonewhocares.org, mvps.org, and adaway.org.

I understand that we all may want our MTV, but when they require sketchy partners, we have to draw the line.

**Comment by kronflux** [comment]
it's been commented out by 2 of those sources for this very reason, though. only one of those three leaves it uncommented.

**Comment by kronflux** [comment]
"This may interfere with some streaming " and "[affects video stream]" although I'm not positive which sources are which.

**Comment by StevenBlack** [comment]
ah, thanks Richard @kronflux I didn't notice that.  Good catch.

**Comment by ScriptTiger** [comment]
And on an unrelated note, nice Dire Straits reference.

**Comment by StevenBlack** [comment]
@ScriptTiger that's the way you do it.
