### ISSUE TITLE
Zarget - website visitors’ behaviour tracking

### ISSUE THREAD

**Issue by xetorixik** [StevenBlack/hosts#430]
Please add Zarget to the hosts list.
As described by Zarget: "Get detailed insights on website visitors’ behaviour".

Live example: www.sygic.com
Sygic track file: http://cdn.zarget.com/179341/476372.js

**Comment by ScriptTiger** [comment]
Can anyone confirm further URLs to be added for this?
zarget.com
cdn.zarget.com

That example link also brings up an interesting case for Facebook events:
facebook.net
connect.facebook.net

Can anyone confirm if those URLs are only analytics and if they will conflict with normal Facebook usage? Preferably by testing both from a desktop and mobile setting, as apps make different connections.

**Comment by StevenBlack** [comment]
Thanks @xetorixik and @ScriptTiger.  Closing.
