### ISSUE TITLE
Add these 2 adult sites too

### ISSUE THREAD

**Issue by shahid2k9** [StevenBlack/hosts#433]
Latest release of 01-Nov-2017 is not blocking the following 2 adult sites. I am using hosts which includes [Unified hosts + fakenews + gambling + porn]. 
Please add these sites in your next version.

https://new.naked.com/
http://www.only4adults.net/adults-en.html

Thanks in advance.

**Comment by StevenBlack** [comment]
@clefspeare13 can you add these two?

**Comment by Clefspeare13** [comment]
Done

**Comment by StevenBlack** [comment]
Closing.  Thanks @shahid2k9 and @Clefspeare13!
