### ISSUE TITLE
Can you support DNSCrypt blacklist?

### ISSUE THREAD

**Issue by bigdargon** [StevenBlack/hosts#434]
I am using dnscrypt and have support for domain blocking in blacklist. Would you please support adding dnscrypt or dnsmasq?
Or support the list of blocked domain as text without address 0.0.0.0?

**Comment by ScriptTiger** [comment]
@StevenBlack may correct me if I am wrong, but this repo on its own is already a handful to manage and curate, so I believe alternate formats are being delegated out elsewhere. I myself support a couple different formats and would be more than happy to take a look at any format suggestions you have. @bigdargon, can you give some example lines of the formats you want using the example below?

The DualServer format:

# This is an example comment line
example.domain.com=0.0.0.0

And, if applicable, any other special notes you may have about where the format may deviate or be case-by-case in some way would also be helpful.

**Comment by bigdargon** [comment]
DNSCrypt blacklist:
[domains-blacklist.txt](https://github.com/StevenBlack/hosts/files/1444749/domains-blacklist.txt)

dnsmasq format:
[dnsmasq.adblock.txt](https://github.com/StevenBlack/hosts/files/1444755/dnsmasq.adblock.txt)

**Comment by StevenBlack** [comment]
@bigdargon and @ScriptTiger I'd love to add this capability.

See also Issue #237, which also references [this repo](https://github.com/oznu/dns-zone-blacklist).

**Comment by bigdargon** [comment]
@StevenBlack it work! Many thanks!

**Comment by ScriptTiger** [comment]
In order to host pre-generated versions of these formats and include comments, do both of these formats accept the standard "#" for comment lines?  Or ";" or anything else?
