### ISSUE TITLE
latest commit breaks my generated dnsmasq.conf

### ISSUE THREAD

**Issue by jac18281828** [StevenBlack/hosts#440]
The latest commit:
commit 57451df2986f3ccbc15c0410caa6fcb662095045 (HEAD -> master, origin/master, origin/HEAD)
Author: Steven Black <steveb@stevenblack.com>
Date:   Thu Nov 16 20:58:38 2017 -0500

    New data from yoyo.org, someonewhocares.org, and Badd-Boyz.

Breaks my generated dnsmasq.  All hosts fail to resolve after it is loaded.

The script I'm using to generate is here: 

https://gist.github.com/jac18281828/31deef842ec0aa7a6f04bdc249da392f

I'm also attaching a diff between the good file and the bad one, but I can't tell what the problem is in my first pass at looking at it.

[adlist.generated.diff.txt](https://github.com/StevenBlack/hosts/files/1484615/adlist.generated.diff.txt)

**Comment by StevenBlack** [comment]
Hi @jac18281828 to confirm, are you using Python 3.5?  This could be related to the build error we see under Python 3.5, but seems fine in other versions.  See https://travis-ci.org/StevenBlack/hosts.

Let me know.

**Comment by mateoag** [comment]
Hi @StevenBlack, 

Thanks for providing us with these hosts files, It has given me peace of mind for quite some time.

I also encountered a problem with my dnsmasq lately upon the release of commit `57451df` 
for my case I was able to work around it for now by removing these 2 lines from the hosts file.

``` 
0.0.0.0 ɢoogle.com
0.0.0.0 secret.ɢoogle.com
```

I'm using the hosts file with this [script](https://github.com/graysky2/adblock-by_haarp/blob/master/adblock.sh)

I think the reason my dnsmasq got broken was the failure of either the script or my router to properly read the `ɢ` character from the latest hosts file.

Could there be another way to block these two domains without using the `ɢ` character?

**Comment by jac18281828** [comment]
@StevenBlack I am using a shell script not python.  I quoted the gist for this script in my post.

The solution suggested by @mateoag works for me as well the "G" in those domains converts to extra ".." (dots) in my dnsmasq.conf which appears to confuse/break dnsmasq.  

Removing those lines fixes the problem.

Thanks for the help both of you!

**Comment by jac18281828** [comment]
The latest hosts file also contains the following:

`0.0.0.0 streamillimité.com`

This problem is due to dnsmasq not handling unicode characters properly.   

I am able to resolve this by filtering with a simple python script.   I'm closing because I have a workaround.

```
import sys
for buffer in sys.stdin.read():
  for ch in buffer:
    if (ord(ch) < 128):
      sys.stdout.write(ch)
```
