### ISSUE TITLE
Why is this website blocked?

### ISSUE THREAD

**Issue by udit-001** [StevenBlack/hosts#446]
I don't know why, but this site doesn't seem to be fishy, but still it's blocked!
[herokuapp.com](http:/herokuapp.com)

**Comment by StevenBlack** [comment]
@mitchellkrogza can you please check Heroku’s history?  I’m guessing this could be a second order effect?  Thanks!

**Comment by mitchellkrogza** [comment]
@StevenBlack addressed in latest Build :+1:

**Comment by StevenBlack** [comment]
Thank you as always, Mitchell @mitchellkrogza!  And thank you Udit @udit-001 for signalling this.

Fixed in the latest build, live and online now.
