### ISSUE TITLE
Inadequate thanks provided for this effort

### ISSUE THREAD

**Issue by MattWeatherford** [StevenBlack/hosts#450]
Steven,

There is inadequate thanks expressed for your efforts here.   Thank you for working on this and providing it to the community!

Anyone else wishing to express thanks, please use this thread

**Comment by ScriptTiger** [comment]
Maybe we should pull together and create a fan portal or proper website for this repository, or maybe even just a PM-capable forum and/or IRC channel. I'm sure I am not the only one with a lot of passion for the goings on here, as my occasional "strafing" may indicate. The 2-dimensional and time-delayed nature of the issue threads here can be a bit annoying to have proper discussions and I truly apologize for my spam rants. In the future just know I am here if you need me, but I'll be reining in my comments in the future to cut down on the thread clutter.

**Comment by TorgoPM** [comment]
I would like to voice my appreciation for the time and effort put into the creation and maintenance of this project. The dependendable, trustworthy, and up-to-date host files provide an invaluable asset for blocking ads, trackers, and malware on all my computers and mobile devices. Thank you!

**Comment by Tsongming** [comment]
I created a GitHub account to say Thank you for putting your time and effort into building an extremely useful tool.

**Comment by AdKiller** [comment]
thank you much appreciated.

**Comment by averyfreeman** [comment]
Yeah, this is great. Top hit on google. Trying out my first ad block hosts file on my iPhone. Very nice of you. Why not put your PayPal or bitcoin for donations in readme.md(?)

**Comment by funilrys** [comment]
Thank you so much !! Without you and this awesome repository, I will never got the idea of Funceble nether PyFunceble. So big thanks again cause those two projects contributed to developing my skills in Shell and Python :+1: 

P.S: I wish you all a happy and successful year ! :tada:

**Comment by GeoffHale** [comment]
## A very big thank you and to all those who help.

Like others in this thread, I created a GitHub account just to say thank you - but got sidetracked.

I don't mind visiting the site but is there a push mechanism to find out when the latest unified file is ready?  If there is a way and I've missed it; I apologise, and could someone show me how!

It is interesting to read the threads and discussions, just wish I was able to help in some way.

_**Carry on the good works!**_

**Comment by ScriptTiger** [comment]
I don't think GitHub has e-mail notifications for repo changes, other than PRs, but I used to have a git application that ran in the background on system start-up that gave me pop-ups about changes in repos I had cloned. I'm sure there are plenty of modern git applications that have similar functionality. Also, if you're following @StevenBlack, his activity will show up if you're on https://github.com and logged in.

If you're on Windows and just need something to automatically manage your hosts file for you, you can also check out https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate.

**Comment by Jon-guy30** [comment]
Github has RSS functionality that you can use to stay up to date with the latest changes to the hosts file. It's what I do.

And yeah, this HOSTS is super useful.

**Comment by ScriptTiger** [comment]
@Jon-guy30, thanks! I didn't know about the RSS feeds, that's actually super awesome. So you can embed it into web pages or just set it up in your favorite RSS reader/client. I hope this helps anyone else who is interested:

https://github.com/StevenBlack/hosts/commits/master.atom

**Comment by Atavic** [comment]
This repo needs a proper forum, or a dedicated subsection on wilders or malwaretips for advanced discussions.

**Comment by ScriptTiger** [comment]
Maybe a subreddit.

**Comment by Balls0fSteel** [comment]
Thank you for your hard work. Been sing this list for decades now, it is the lifeblood of my Android devices. Thank you so much!

**Comment by 93RS** [comment]
Thank you very much! :)

**Comment by GeoffHale** [comment]
We can't let this thread go - This is an invaluable resource and the efforts are appreciated and I am personally most grateful.
Thank you.

**Comment by MattWeatherford** [comment]
Agreed - I am still using this awesome host list,  its relevant and makes a big difference in the security of the boxes I am managing. Thank you StevenBlack :O)

**Comment by 93RS** [comment]
Again, thank you very very much! The host list is AWESOME! :)

**Comment by funilrys** [comment]
.

**Comment by StevenBlack** [comment]
I think there is inadequate thanks provided for Nissar @funilrys here.  😄
