### ISSUE TITLE
Add these phishing sites 

### ISSUE THREAD

**Issue by udit-001** [StevenBlack/hosts#452]
Can you look into this list, and add these sites to your blacklist if possible?

(https://github.com/409H/EtherAddressLookup/blob/master/blacklists/domains.json)

**Comment by StevenBlack** [comment]
Thanks @udit-001.  This list appears to be very useful and, even better, it's actively curated.

Unfortunately the list is a json array, and not in host format.

So a prerequisite to adding this is supporting transformations when we refresh data.  That's Issue #180 ***Hooks to allow sourcing in other formats (.zip, etc)***.

This is also related to #413

**Comment by StevenBlack** [comment]
I've [left a note with the repo owner](https://github.com/409H/EtherAddressLookup/issues/203) thanking him for maintaining that list, and asking if he'd publish in hosts format.  That would be easier for us but, if not, I think this will be our first transformation extension to source domains in other formats.

**Comment by StevenBlack** [comment]
Done!  EtherAddressLookup is now included in our list of hosts sources.

Closing.
