### ISSUE TITLE
centralagier

### ISSUE THREAD

**Issue by mat41997** [StevenBlack/hosts#453]
![2017-12-08 20_07_40-elvenar - centrala gier](https://user-images.githubusercontent.com/5884000/33781086-89cf53da-dc53-11e7-9e4b-3727c1ea9a3f.png)
`https://centralagier.wp.pl/elvenar/graj`

Dan Pollock’s hosts file

https://github.com/MajkiIT/polish-ads-filter/issues/4803

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.130
chrome 62.0.3202.94

**Comment by StevenBlack** [comment]
Hi @mat41997, what is this about?

**Comment by mat41997** [comment]
white, i see white
