### ISSUE TITLE
Gigya - Build and Manage a Rich Customer Profile - behaviour tracking

### ISSUE THREAD

**Issue by xetorixik** [StevenBlack/hosts#455]
What about Gigya?
They are tracking visitors for user engagement and loyalty, and [integrations with third-party marketing and services platforms](https://en.wikipedia.org/wiki/Gigya).

Live example: https://bnnvara.nl (Dutch)
Site track file: https://cdns.gigya.com/js/gigya.js?apiKey=3_r5z7GAhuEeH4ohShtN7RXiRQ6K2r0HKb4eOF5gBUqTwnfi5tZkN1FKhSQzagdKib

Some of the Gigya trackers like counters.gigya.com are already blocked.
Fact to the matter is that they also track visitors via the cdns.gigya.com sub-domain.
Please block cdns.gigya.com.

P.s. Thanks for adding https://github.com/StevenBlack/hosts/issues/430 to the list.
I really appreciate it.

**Comment by StevenBlack** [comment]
Hi @xetorixik, thanks for the input.

As you may know, we're primarily an aggregator here.  We pull-together the work of various other projects, de-dupe the merged contents, and make it available in an extensible way.

Can you make a detailed request to some of the [sources of hosts data](https://github.com/StevenBlack/hosts) we use?  

Alternately I'm willing to entertain a pull request against [my little source file](https://github.com/StevenBlack/hosts/blob/master/data/StevenBlack/hosts), but that's up to you.

**Comment by ScriptTiger** [comment]
@xetorixik, just as a note, the existing entries for gigya.com are coming from someonewhocares.org (hosts@someonewhocares.org) and mvps.org (winhelp2002@gmail.com). Since they already have experience with those, you can probably just shoot either one an e-mail and they should be able to get back to you rather promptly about it, if you haven't already.

**Comment by xetorixik** [comment]
@StevenBlack I will first contact someonewhocares.org and mvps.org.
If this does not yield anything, you can still put it on your own list afterwards.
Thanks @ScriptTiger for the sites.

**Comment by xetorixik** [comment]
@StevenBlack and @ScriptTiger Sent to winhelp2002@gmail.com. Consider it done.
hosts@someonewhocares.org mail server keeps blocking, can't send it.

Someone volunteering to send the message to him?

Thanks.

**Comment by xetorixik** [comment]
Hmm Apparently succeeded.
http://someonewhocares.org/hosts/ is up-to-date now with cdns.gigya.com on the blocklist.
@StevenBlack Please update your list.

Thanks.

**Comment by ScriptTiger** [comment]
We should probably work on getting all of the entries in the data/StevenBlack/hosts absorbed by the the sources over time and just use it as more of an intermediate staging area/queue to block entries immediately while we work out negotiations with the sources. This is a bit unrelated, but I just wanted to make a note here for later when we get the docs rolled out.

**Comment by xetorixik** [comment]
Update.
https://github.com/StevenBlack/hosts/issues/430 
Added to http://someonewhocares.org/hosts/

**Comment by xetorixik** [comment]
@ScriptTiger True. Temp list with the possibility to block immediately, with the structural solution to offer the entry to the upstream lists elsewhere.

**Comment by xetorixik** [comment]
http://someonewhocares.org/hosts/ is open to new additions.
Today my third entry has been added.
Tip! If you have an interesting site, send it to > hosts@someonewhocares.org

**Comment by StevenBlack** [comment]
Closing!
