### ISSUE TITLE
Twitter is blocked

### ISSUE THREAD

**Issue by anudeepND** [StevenBlack/hosts#457]
Twitter.com in blocked in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

![screenshot_20171218-102411](https://user-images.githubusercontent.com/26179946/34090539-c6438ad4-e3dd-11e7-829d-6d36fdb26d92.png)

**Comment by StevenBlack** [comment]
Good catch @anudeepND.

**Comment by StevenBlack** [comment]
Fixed in the latest build, online now.
