### ISSUE TITLE
Using Windows DNS Server Instead Of Host File ?

### ISSUE THREAD

**Issue by emreozcant** [StevenBlack/hosts#458]
Hello, 

Thank you for great project.
I want to ask the possibility of using this project on DNS server instead of clients host?

BR
Emre

**Comment by ScriptTiger** [comment]
Absolutely. There are a number of different conversion projects related to DNS servers in the "Interesting Applications" section of the main README (https://github.com/StevenBlack/hosts), as well as possibly a few hidden gems mentioned in previous issues and PRs. What type of DNS server in particular are you looking to use?

Just as a personal plug, I maintain support for DualServer (https://scripttiger.github.io/dualserver/), which includes an updater script (https://github.com/ScriptTiger/DualServer/archive/master.zip) and some template config files to get you started.
