### ISSUE TITLE
Add NoCoin

### ISSUE THREAD

**Issue by As3ro** [StevenBlack/hosts#462]
This is very helpful, Wstream now doesn't use the 100% cpu

https://github.com/hoshsadiq/adblock-nocoin-list

**Comment by ScriptTiger** [comment]
@StevenBlack will, of course, have to check the curation rate and everything to see if it meets his specs, but we could definitely use a list like this to be well curated so we could unload the locally stored list of crypto miners on it.

**Comment by dnmTX** [comment]
Maybe you guys could consider adding []https://github.com/ZeroDot1/CoinBlockerLists().ZeroDot1 updates his list almost every day.It's worth checking it out.Just a suggestion.

**Comment by ScriptTiger** [comment]
The CoinBlockerLists link actually throws a mention to @mitchellkrogza. @mitchellkrogza, are these already included in the lists this project imports or is that a separate project you have them included in?

**Comment by mitchellkrogza** [comment]
@ScriptTiger I use the Coinblocker lists on this repo https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist

**Comment by anudeepND** [comment]
@dnmTX I was using CoinBlockerLists but it blocks many sites that are related to crypto currency sites like mining pools, exchange sites etc. I wish it was only blocked JS based mining sites.

**Comment by ScriptTiger** [comment]
@anudeepND, I think your concern is a valid one, but it's similar to the arguments we have had in the past related to analytics, https://github.com/StevenBlack/hosts/issues/256, blocking both the analytics management/dashboard sites as well as the analytics scripts themselves. As the vast majority of consumers are not web devs or admins, I think letting those of us who need special sites to be whitelisted is best left to us as individuals for now until we decide on more solid standards to keep. As I said, it's definitely a valid concern, but it shouldn't be a deal-breaker.

**Comment by dnmTX** [comment]
@anudeepND  i agree with @ScriptTiger  and yes,you can always whitelisted also @ZeroDot1 is well aware of this and based on reading some of the closed issues in his repo he already removed some from his list. Remember,it is a new project and there always be some flaws,but as long as he maintain it i'd say better safe then sorry.

**Comment by ZeroDot1** [comment]
I'm aware that sometimes there are false positives.
If you notice any problems, please let me know and I will take a look at it. 
https://github.com/ZeroDot1/CoinBlockerLists/issues
Thank you for using the CoinBlockerlists.

**Comment by FadeMind** [comment]
What EXACTLY file you want add to project? They are 3 hosts files here:
https://github.com/ZeroDot1/CoinBlockerLists

**Comment by FadeMind** [comment]
See
https://github.com/FadeMind/hosts.extras/commit/fdef0d846d9dee55dfe30192d0ac5593eff1afa1

https://github.com/FadeMind/hosts.extras/tree/master/CoinBlockerLists

https://github.com/FadeMind/hosts.extras/tree/master/adblock-nocoin-list
