### ISSUE TITLE
Newbie getting error when running script

### ISSUE THREAD

**Issue by gladiator26** [StevenBlack/hosts#463]
Please excuse my lack of expertise, but trying to learn here.
I am running the command: sudo python updateHostsFile.py -a -r and at the end I am  getting an error message and the hosts file remains unchanged. Any help is greatly appreciated.

sudo python updateHostsFile.py -a -r
Password:
Updating source Telemetry from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/Telemetry/hosts

Problem getting file:  https://raw.githubusercontent.com/FadeMind/hosts.extras/master/Telemetry/hosts

Skipping.
Updating source malwaredomainlist.com from https://www.malwaredomainlist.com/hostslist/hosts.txt

Updating source mvps.org from http://winhelp2002.mvps.org/hosts.txt

Updating source porn from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts
Updating source SpotifyAds from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/SpotifyAds/hosts
Updating source adaway.org from https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt

Updating source KADhosts from https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt

Updating source social from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/social-hosts

Updating source yoyo.org from https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0

Updating source UncheckyAds from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts

Updating source add.2o7Net from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts

Updating source add.Dead from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Dead/hosts

Updating source tyzbit from https://raw.githubusercontent.com/tyzbit/hosts/master/data/tyzbit/hosts

Updating source StevenBlack from https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts

Updating source gambling from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts

Updating source someonewhocares.org from http://someonewhocares.org/hosts/zero/hosts

Skipping.
Updating source add.Spam from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts

Updating source add.Risk from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts

Traceback (most recent call last):
  File "updateHostsFile.py", line 560, in <module>
    main()
  File "updateHostsFile.py", line 140, in main
    mergeFile = createInitialFile()
  File "updateHostsFile.py", line 294, in createInitialFile
    writeData(mergeFile, curFile.read())
  File "updateHostsFile.py", line 68, in writeData
    f.write(str(data).encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3270: ordinal not in range(128)

**Comment by StevenBlack** [comment]
Hi @gladiator26 this appears to be similar to Issue #372 – ***updateHostsFile.py fails to download from KADhosts under Python 2.7***

Every once in awhile one of our source files includes characters that can't be handled as `utf-8`.

Python 3 handles this sort of thing easily.  Are you able to try this under Python 3?

**Comment by gladiator26** [comment]
Thank you so much Steven, upgrading to Python3 fixed the error. You rock.
