### ISSUE TITLE
Great!  But not perfect

### ISSUE THREAD

**Issue by axaith** [StevenBlack/hosts#466]
First of all, I would like to say thank you for this project.  I find it very useful, I use it, and I recommend it to friends and family.  However, you make a mistake by including the "fake news" list, and the predictable list of domains included therein.  Also predictably i see there has been plenty of github issues opened and closed here regarding this.  Looking over these past discussions, I see the argument you make for its inclusion would normally be a solid one:  you mean well, nobody has to use this, and furthermore they can select which lists to include or exclude.

The problem with this is that prior to a few years ago, the term "fake news" was a legitimate term which was used to describe sites which pretend to be news sites but really are not, for the purpose of serving ads or malware or whatever the case might be.  Regardless of anyone's personal political leanings, this term has clearly since become a politicized term, hijacked for use as a disingenuous smear against opposing political ideologies.  This is evidenced by taking a look at the domains actually included in marktron's "fake news" list:  included are "right wing" political sites like infowars, drudge report, and the ron paul institute for peace and prosperity, "left wing" political sites like truthdig, RT, and washingtonsblog, even leak sites like dcleaks and liveleaks.  The salient issue here is that it is a list of political sites; even whistle-blower sites are included.  In a previous discussion you stated,

"So it's just like the porn or social media extensions. You would include those for specific reasons. Fake news, same thing."

Unfortunately it is not the same thing, and that itself is the issue.  pornhub is porn.  facebook is social media.  These things are appropriately labeled, and you can choose to include them or not based on their label.  An actually appropriate equivalence for this "fake news" list would be the inclusion of a list of sites related to social activism, environmentalism, feminism, black lives matter, civil rights, this sort of thing, and calling it the "terrorism" list, as has in fact become an increasingly popular tactic in certain politically-motivated rhetoric, much like the usage of the term "fake news" in recent times.

Ultimately, if you want to include a list of political sites in your thing, and people can either use it or not, great.  So call the list "politics" or "extreme politics" or something.  As long as you continue to include a mislabeled list here, your argument of "you can decide for yourself what to include" doesn't work so well, and you really do deserve all the flak you will inevitably continue to catch for it.

**Comment by StevenBlack** [comment]
@axaith "Fake News" is only included if you want it to be included.  By default, Fake News is not included.  Don't like it?  Take any version that doesn't include it.

As for ***you really do deserve all the flak you will inevitably continue to catch for it***, to be clear, I don't feel any flack whatsoever from this.

Thank you for expressing your concern.  Closing.

**Comment by ScriptTiger** [comment]
The curator, @marktron, addresses some of your concerns in the readme;
https://github.com/marktron/fakenews

He also somewhat agrees about more extensive and specific categorization being needed in the future:
>In the future, this list will be broken out by category (e.g. “Hoaxes”, “Satire”, “Propaganda” etc) to enable easier customization for the end user.

We have also talked about terrorist-related sites or sites promoting violence in loose relation to the porn/snuff category. Ultimately news should be news and not a call to action, as that would be illegally inciting by most nations' standards.
