### ISSUE TITLE
youtube, netflix blocked  

### ISSUE THREAD

**Issue by may215** [StevenBlack/hosts#467]
I am using the following file "Unified hosts + fakenews + gambling + porn" and it blocked youtube and netflix, do you know why?

nslookup results are fine.

**Comment by ScriptTiger** [comment]
YouTube and Netflix are not explicitly blocked. However, it is possible a specific CDN that delivers content to your local area for YouTube or Netflix is blocked. It is also possible that your ISP is actually blocking it, and in turn the redirected portal is blocked.

There are no mentions of Netflix at all, but the following are the URLs relevant to YouTube being blocked as ad services:
alternates\fakenews-gambling-porn\hosts:0.0.0.0 s2.youtube.com
alternates\fakenews-gambling-porn\hosts:0.0.0.0 s.youtube.com
alternates\fakenews-gambling-porn\hosts:0.0.0.0 ads.youtube.com
alternates\fakenews-gambling-porn\hosts:# 0.0.0.0  www.youtube-nocookie.com #[affects various videos]
alternates\fakenews-gambling-porn\hosts:# 0.0.0.0  static.2mdn.net #[affects Youtube]

I can personally attest to YouTube being fine with these entries, but I don't know about Netflix as I am not a subscriber. Are you aware of anything else that might be causing your connection to fail? Have you tried to visit those sites with a hosts files that does not contain any entries from this project?

**Comment by jac18281828** [comment]
Content providers sometimes block their content if the ad fails to load.     This is to prevent “free loading.”   But I haven’t found a case where a few retries didn’t cure it.

**Comment by dnmTX** [comment]
@may215  check your browser's ad blocker(if you have one),reset your hosts file and try again.Am also using the same hosts config and have no problems with youtube(another netflix no subscriber sorry).

**Comment by MDieperink** [comment]
s.youtube.com is for YouTube History, so that one shouldn't be on the list: https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

**Comment by ScriptTiger** [comment]
"History" could be considered a type of analytics/tracking by some. There are also some sites here blocked solely because of their use of cookies, so both internal and external history would seem to be frowned upon.

**Comment by ajvadv777-hue** [comment]
can u add pirated streaming sites like soap2day,m4uhd,fmovies etc.?
