### ISSUE TITLE
Invalid Domain

### ISSUE THREAD

**Issue by BBcan177** [StevenBlack/hosts#469]
FYI: Invalid Domain:

https://github.com/StevenBlack/hosts/blob/d82809d5149ef43c57b810fee6bd103bf44c2f5c/extensions/porn/sinfonietta/hosts#L5275

**Comment by ScriptTiger** [comment]
@sinfonietta, bump ^

**Comment by Sinfonietta** [comment]
Thanks @BBcan177, @ScriptTiger, fixed.

**Comment by funilrys** [comment]
Fixed as it's not present anymore (cf: https://github.com/StevenBlack/hosts/search?utf8=%E2%9C%93&q=sexdating&type=)

@StevenBlack you may want to close this ...
