### ISSUE TITLE
DuckDuckGo Privacy Essentials

### ISSUE THREAD

**Issue by ScriptTiger** [StevenBlack/hosts#476]
@StevenBlack has mentioned using the Tor Browser several times to keep yourself further protected when checking on sites you are not sure about. 

It uses HTTPS Everywhere and DuckDuckGo extensions. 

DuckDuckGo has just updated itself and is now called "*DuckDuckGo Privacy Essentials*" and blocks trackers, analytics, ads, etc.. 

So far the new DDG Privacy Essentials seems to be doing a good job as far as pages I view in the browser, similar to how Privoxy works, which I would also recommend if you ever want to set up a non-caching web proxy for Tor to make it even more secure.

**Comment by StevenBlack** [comment]
@ScriptTiger I edited the above to conform to the (1-paragraph = 1-idea) rule.  I also made it more concise.

I did this so I could then understand what you wrote.

Since there's no actionable issue here, I'm closing this.

**Comment by StevenBlack** [comment]
@ScriptTiger I've never recommended using Tor to "*Keep yourself further protected*" or anything like that.

I have recommended Tor to access domains that are blocked by hosts files.  

For example, if you occasionally use Google Analytics dashboards, but dislike being tracked, you can get to Google Analytics without changing the hosts files by using the Tor browser.
