### ISSUE TITLE
Using Iptables?

### ISSUE THREAD

**Issue by bloggervista** [StevenBlack/hosts#480]
Is there anyway to block using iptables in forward chain?  I know it is for hosts but any extension or port for iptables . Thanks :)

**Comment by funilrys** [comment]
Is this related to #416 ?

**Comment by bloggervista** [comment]
@funilrys  abit yeah but they are not workin

**Comment by funilrys** [comment]
How they are not working ?

**Comment by bloggervista** [comment]
this lines seems to have error

while read LINE
do
	if [[ $LINE =~ 0\.0\.0\.0.* ]]; then
		if [[ ${LINE:8} != "0.0.0.0" ]]; then
			printf "%s\n" "$PREFIX ${LINE:8} $POSTFIX" >> $TMPFILE
		fi
	fi
done < $HOSTSDIR/hosts

**Comment by funilrys** [comment]
Sorry I didn't read that script so much ... That script does work only what was needed ...

I don't generally do such things but as long as it can help the open source community, I wrote a short (and universal ? can someone confirm that ?) script https://github.com/funilrys/hosts2iptables .

I can write the python version if some people need it ...

Hope it'll help.

Cheers,
Nissar

**Comment by funilrys** [comment]
Any feedback @bloggervista ?

@StevenBlack It's been almost 10 days... You may want to close this ...

**Comment by bloggervista** [comment]
yes it was great . As many linux uses iptables instead of host it is better to use it :)

**Comment by funilrys** [comment]
It's really wrong ... As an Arch Linux user for many years, I can only recommend `hosts` file over iptables .... But that's my opinion. 

May I know what is your distribution?

**Comment by bloggervista** [comment]
Ubuntu. I have a reason over iptables.Suppose you want to distribute internet from eth0 to eth1 . Can hosts file do it? I use iptables forward chain to restrict bandwidth so i was searching for a way to block such unnecessary websites bro. If hosts file can block it i am happy to use it.

**Comment by funilrys** [comment]
Well, I do have iptables rules and hosts file at the same time. Why is that not possible in your case ?

**Comment by bloggervista** [comment]
It is due to setup like that of router
eth0 : Internet comes in So it is WAN
eth1: Internet Goes out so it is lan

From eth1 internet is distributed to around 700 computers..

Now using host how i can make it possible . I think iptables Forward chain  is only possible

**Comment by funilrys** [comment]
Did you ever try to set a random domain into hosts file and try to access that random domain from one of the 700 computers ? :thinking:

**Comment by funilrys** [comment]
You can still forward with iptables but block all undesirable domain with hosts file I think ... At least that's what I'll think first...

**Comment by bloggervista** [comment]
it won't go because lets say
in hosts file it  only blocks if it match the url
but if  user uses google dns server will only see ip which will not match the hosts as there are url version.
