### ISSUE TITLE
Instagram does not load 

### ISSUE THREAD

**Issue by SDMU** [StevenBlack/hosts#482]
One (or many) of the 4 disabled instagram.com links disables the feed on the instagram app.

![](https://i.imgur.com/CjmfuO9.png)

**Comment by funilrys** [comment]
Hello @SDMU and welcome here!
`black.ish.instagram.com` is indeed listed [here](https://github.com/StevenBlack/hosts/blob/cf5d6306d2c83a37fb1ec00f704b4f2eb68d4f5b/extensions/social/hosts#L321).

But, as it is on the social extension list I'll suggest you get one of the lists without the `social` extension in [the following list](https://github.com/StevenBlack/hosts#list-of-all-hosts-file-variants). 

Cheer.
