### ISSUE TITLE
cliqz.com

### ISSUE THREAD

**Issue by crssi** [StevenBlack/hosts#484]
Hi.
What would be the reason that [cliqz.com](https://cliqz.com/) is blocked?

Thank you
Cheers

**Comment by funilrys** [comment]
cc @mitchellkrogza I think this should be removed/whitelisted ...

**Comment by ScriptTiger** [comment]
@mitchellkrogza, bump ^

data\Badd-Boyz-Hosts\hosts:0.0.0.0 cliqz.com
data\Badd-Boyz-Hosts\hosts:0.0.0.0 hpn-collector.cliqz.com

**Comment by funilrys** [comment]
Thanks for the update @ScriptTiger I was going to make some research about it before whitelisting it (I have the write access to that repository). 

@crssi unless @mitchellkrogza decide something else, this is not going to be whitelisted.

**Comment by mitchellkrogza** [comment]
Thanks @funilrys and @ScriptTiger addressed in latest build (in progress)

**Comment by mitchellkrogza** [comment]
@funilrys @ScriptTiger sorry now I am confused ... whitelist this or not ???

**Comment by funilrys** [comment]
@mitchellkrogza this should not be whitelisted ... 

@ScriptTiger said: 
> And if you read the Wikipedia link above, it seems even their "privacy-oriented" browser is just a marketing ploy to collect data for advertisers.

**Comment by mitchellkrogza** [comment]
👍 my bad will stop current build and remove them from whitelisting

**Comment by StevenBlack** [comment]
Thank you, everyone.

Closing.
