### ISSUE TITLE
href.li

### ISSUE THREAD

**Issue by donnchawp** [StevenBlack/hosts#485]
Can you remove href.li from your list please? It's simply a redirection service to hide the referrer of a click in a browser. It doesn't host any malware.

Thanks.

**Comment by ScriptTiger** [comment]
data\someonewhocares.org\hosts:0.0.0.0 href.li

It's possible someone caught it being abused and redirecting to malware, but I tend to agree that short link services are not inherently bad, especially ones trying to help you out by increasing your privacy. However, if it helps, if you are using Chrome, there are plenty of header modification extensions you can look into that will keep your referrer information empty/bogus all the time. If you're a web developer, such extensions also come in handy for quickly testing out vhosts, different browser agents, and other things you might need to test out while your checking your stuff.

**Comment by donnchawp** [comment]
I contacted Dan Pollack who compiles the original list this was on. A few hours after I opened this issue he replied saying he had removed it. I should have responded here saying that, so I hope it'll be removed the next time the list is refreshed. :)

**Comment by ScriptTiger** [comment]
No worries, thanks for doing all the legwork for us! It will definitely drop off the next time the lists are generated, but you can always run the Python script yourself to get a head start.
