### ISSUE TITLE
Ads on watchbox.de

### ISSUE THREAD

**Issue by mueller-ma** [StevenBlack/hosts#487]
Hey,
I use this blacklist, but I still see ads on watchbox.de

**Comment by StevenBlack** [comment]
@mueller-ma what domains do those ads come-from?

**Comment by funilrys** [comment]
@StevenBlack He only says that the domains used for ads on that website are not listed here ... 

At least that is what I understand ...

**Comment by StevenBlack** [comment]
@funilrys that's what I understood as well.  I don't use watchbox.de.  We need to know, what domains serve ads for watchbox.de?

**Comment by funilrys** [comment]
@StevenBlack I found and tried the following but once blocked no video is playing ...

```
0.0.0.0 ssl.3.damoh.watchbox.de
0.0.0.0 ssl.2.damoh.watchbox.de
0.0.0.0 ssl.1.damoh.watchbox.de
```

**Comment by StevenBlack** [comment]
*sigh*.

Thanks for looking into this Nissar @funilrys.  

But we aren't in the business of chasing down the source of ads on individual websites.  This is not what we do here.  This is out of scope.

Closing.

**Comment by mueller-ma** [comment]
Ok, thanks for you effort :)

**Comment by mueller-ma** [comment]
I have looked at it and came to the same conclusion than @funilrys. They seem to deliver videos and ads over the same dns name.

**Comment by badmojr** [comment]
How about these domains for a start, @mueller-ma?
a4240511539.cdn.optimizely.com
adservice.google.com
adservice.google.de
bidder.criteo.com
bilder-a.akamaihd.net
cdn.static-fra.de
ce.lijit.com
d2wy8f7a9ursnm.cloudfront.net
engage.commander1.com
ip-s.nuggad.ad
ip-s.nuggad.net
irqs.ioam.de
logx.optimizely.com
sync-tm.everesttech.net
technical-service.net
trck.spoteffects.net
www.technical-service.net

**Comment by mueller-ma** [comment]
Videos dont play, when I block these domains.
When I look in the dev console, I can see connections to ssl.[123].damoh.watchbox.de while playing ads. When I block them, no vids are playing.

**Comment by winklevos** [comment]
Looks like d2wy8f7a9ursnm.cloudfront.net is required on crust.com.au for the site to work, can this be removed ?
