### ISSUE TITLE
Mangadex.com added to the adware/malware list in error

### ISSUE THREAD

**Issue by oznsfw** [StevenBlack/hosts#495]
mangadex.com has been added to the adware/malware base list in error as it does not contain any malware content.

**Comment by funilrys** [comment]
Hello @oznsfw and welcome here 👍 

Are you sure you are in the right repository?
I'm asking because I can't find any occurrence of `mangadex.com` into this repository.

**Comment by funilrys** [comment]
@StevenBlack @oznsfw I found it in Badd-Boyz-Hosts. I'm on it. Should be removed asap.


For reference: Also mentioned into https://github.com/mitchellkrogza/Badd-Boyz-Hosts/issues/5

**Comment by funilrys** [comment]
@StevenBlack the build/test may take some time but it's removed so an update should fix this issue 🎉

**Comment by StevenBlack** [comment]
Closing!
