### ISSUE TITLE
Spot.im

### ISSUE THREAD

**Issue by xetorixik** [StevenBlack/hosts#498]
Spot.im has been added to http://someonewhocares.org/hosts/ on February 12th.
Please update the upstream source..

About Spot.im

"Meet Your Community.
Take back ownership of your audience by building a thriving social community to drive conversation, pageviews, clicks, and revenue."

Thanks

**Comment by ScriptTiger** [comment]
Does the "pageviews, clicks" part involve analytics?

**Comment by funilrys** [comment]
As I can find `spot.im` into http://someonewhocares.org/hosts/ but I can't find any record into the repository, I think he's suggesting and/or excepting an update from @StevenBlack @ScriptTiger.

**Comment by StevenBlack** [comment]
@funilrys yup, the lates update includes spot.im.
