### ISSUE TITLE
Fastly is blocked

### ISSUE THREAD

**Issue by Biont** [StevenBlack/hosts#500]
Hello and thanks for this amazing project.

In adc8004272e770cf871a3046920c01505aaed887 fastly.net was blocked. See my comment here: https://github.com/StevenBlack/hosts/commit/adc8004272e770cf871a3046920c01505aaed887#r27558445

I haven't looked much into it, but it seems to me that this domain belongs to the fastly.com cloud hosting/CDN platform.

Thus, quite a lot of sites break in interesting ways. For example, I cannot pull packages from npm any longer:

```bash
$ dig registry.npmjs.org

; <<>> DiG 9.12.0 <<>> registry.npmjs.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42622
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 89f04e9839d36f70cddddfc25a845181401f2b38f062ec92 (good)
;; QUESTION SECTION:
;registry.npmjs.org.            IN      A

;; ANSWER SECTION:
registry.npmjs.org.     1222    IN      CNAME   a.sni.fastly.net.

;; Query time: 64 msec
;; SERVER: 192.168.188.1#53(192.168.188.1)
;; WHEN: Mi Feb 14 16:09:21 CET 2018
;; MSG SIZE  rcvd: 105

$ dig a.sni.fastly.net

; <<>> DiG 9.12.0 <<>> a.sni.fastly.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18904
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: a99b36271c65c76c1679c1565a845196c18e34d2239efa66 (good)
;; QUESTION SECTION:
;a.sni.fastly.net.              IN      A

;; ANSWER SECTION:
a.sni.fastly.net.       86400   IN      A       0.0.0.0

```

**Comment by funilrys** [comment]
Hey @FadeMind, can you take a look at this? 

It has been introduced by the `Spotify-Ad-free` list 👍 
________
# Occurrences search

`fastly.net` can be found in the following lists

```
./data/Spotify-Ad-free/hosts <== Entry point
./alternates/fakenews-porn/hosts
./alternates/fakenews-gambling/hosts
./alternates/social/hosts
./alternates/gambling/hosts
./alternates/fakenews-social/hosts
./alternates/porn-social/hosts
./alternates/gambling-porn/hosts
./alternates/fakenews-gambling-porn-social/hosts
./alternates/fakenews-gambling-porn/hosts
./alternates/porn/hosts
./alternates/fakenews/hosts
./alternates/gambling-porn-social/hosts
./alternates/fakenews-porn-social/hosts
./alternates/gambling-social/hosts
./alternates/fakenews-gambling-social/hosts
./hosts
```

**Comment by Biont** [comment]
I should have added I'm using the basic list without any add-ons. Broken sites include reddit, github and bandcamp

**Comment by funilrys** [comment]
@Biont We are talking about the same thing.

As it's also referenced in `./hosts` that means that `./data/Spotify-Ad-free/hosts` is part of the unified system which means that it's present in all extensions.

**Comment by FadeMind** [comment]
This is extended sources: https://github.com/CHEF-KOCH/Spotify-Ad-free

@CHEF-KOCH is maintainer of it.

**Comment by StevenBlack** [comment]
@Biont my concern is, `fastly.net` appears to have [landed on Sep 15, 2017](
https://github.com/CHEF-KOCH/Spotify-Ad-free/commit/579e271e0377ce65483213b01adec8e93edd0cbf).  

Also, I don't experience the failure modes you see.  What specific NPM, Reddit, etc errors are you seeing?

**Comment by Biont** [comment]
@StevenBlack I'm not sure I follow (but please pardon my ignorance, I am looking at this repo for the first time). Your link goes to a commit from [Spotify-Ad-free](https://github.com/CHEF-KOCH/Spotify-Ad-free), but it was only added to **this** repo's config by #492 which was merged 3 days ago. Then its rules themselves went in with adc8004272e770cf871a3046920c01505aaed887 (which I assume is the result of a script which updates all rules and documentation accordingly).

So **if** I understand correctly, it's perfectly understandable that I'm only seeing problems now despite the rules being added to the source repo back in September. I can only speculate why it hasn't caused issues *there* yet, though.


The errors I was seeing were: 

* registry.npmjs.org was gone entirely. You can see in my OP that it turned out to be a CNAME of a.sni.fastly.net which ended up being blocked.

* Assets from github cannot be loaded because assets-cdn.github.com is a CNAME of github.map.fastly.net

* Assets from bandbamp could not be loaded because s4.bcbits.com is a CNAME of n.ssl.global.fastly.net

(I'm actually not quite sure what the issue with reddit was. Let's ignore I mentioned it from now on :D )


I added ffastly.net to my local whitelist and everything worked again.

**Comment by funilrys** [comment]
@FadeMind Can you update the file? 👍

**Comment by FadeMind** [comment]
@funilrys  Talking about https://github.com/FadeMind/hosts.extras ??

**Comment by funilrys** [comment]
@Biont It should be fixed once @StevenBlack update the repository 👍

**Comment by FadeMind** [comment]
@funilrys  at hosts.extras are copies of lastest changes in `hphosts` and `spotify-ad-free`. See lastest changes, so I don't need update these hosts files all time.

**Comment by StevenBlack** [comment]
@FadeMind @funilrys done!
