### ISSUE TITLE
Disable DnsCache or not ?

### ISSUE THREAD

**Issue by Shuunen** [StevenBlack/hosts#51]
Hi,

I've seen dozen of thread online about disabling DnsCache service on Windows when using large hosts file, what do you think ?

Some quotes :
- "mvps reccommends to disable the DNS cache when the hosts file is over 135 kb" (http://forum.kaspersky.com/lofiversion/index.php/t63221.html)
- "if you use P2P software you won't want to disable it" 
- "I run the hphosts HOSTS file and have always had the local DNS service disabled (this is recommended when running a larger HOSTS file.)" (http://www.wilderssecurity.com/threads/with-opendns-why-not-disable-local-dns-cache.214871/)
- "With cache disabled, you waste this time, bandwidth etc. With hosts file in action, you further slow down your work by forcing the machine to check the hosts file for matches before hitting the internet." (http://www.wilderssecurity.com/threads/wanted-security-setup-opinions-antispy-malware-reccommendations.210614/#post-1250725)

I'm a bit lost :)

**Comment by StevenBlack** [comment]
Hi @Shuunen.

Thinking about this, some of these sources are old, dating from Windows XP's early days, and possibly based on Windows 98 experiences.

When I switch between a very large and minimalist hosts files, I don't notice slowness one way or another.

I'm on OSX latest, with modern hardware, a healthy broadband connection and, based on switching between 5-figure and single-digit host numbers, I'm certain that tinkering with DNS cache won't prove worthwhile.

**Comment by StevenBlack** [comment]
Closing.
