### ISSUE TITLE
pr0gramm.com blocked

### ISSUE THREAD

**Issue by Fusl** [StevenBlack/hosts#510]
Following up #509 which was closed but hasn't fixed the issue entirely:

pr0gramm.com is blocked although the website itself does not host any cryptocurrency miners. The pr0gramm miner is hosted on miner.pr0gramm.com which is opt-in and the only domain that should be blocked.

Note: Blocking pr0gramm.com was introduced in [1341e7af528e8e5d887cccf74c1734ca1310b076](https://github.com/StevenBlack/hosts/commit/1341e7af528e8e5d887cccf74c1734ca1310b076):
```
$ git show 1341e7af528e8e5d887cccf74c1734ca1310b076 | grep "^\+" | sort -u | fgrep pr0gramm.com
+0.0.0.0 app.pr0gramm.com
+0.0.0.0 avatar.pr0gramm.com
+0.0.0.0 escobar.pr0gramm.com
+0.0.0.0 full.pr0gramm.com
+0.0.0.0 hans.pr0gramm.com
+0.0.0.0 hurensohn.pr0gramm.com
+0.0.0.0 img.pr0gramm.com
+0.0.0.0 miner.pr0gramm.com
+0.0.0.0 m.pr0gramm.com
+0.0.0.0 pr0gramm.com
+0.0.0.0 thumb.pr0gramm.com
+0.0.0.0 vid.pr0gramm.com
+0.0.0.0 ww.pr0gramm.com
+0.0.0.0 www.pr0gramm.com
+0.0.0.0 www-tb7c.pr0gramm.com
```

The latest commit ([fab9fbc6909c5e6ef2e293bdd2af3639f59dc7aa](https://github.com/StevenBlack/hosts/commit/fab9fbc6909c5e6ef2e293bdd2af3639f59dc7aa)) does not fix this issue.

**Comment by dnmTX** [comment]
@Fusl  can you address this at  https://github.com/ZeroDot1/CoinBlockerLists  so @ZeroDot1 can review it and make the necessary changes please.@StevenBlack is only pulling the list from him and it doesn't maintain it.

**Comment by Fusl** [comment]
This was adresses in the origin repo but request for removal was declined: https://github.com/ZeroDot1/CoinBlockerLists/issues/50

**Comment by dnmTX** [comment]
Well that's why i suggested the CoinBlockerLists to be extension for cases like this one.Me personally don't want anything to be removed from it,i'd rather be safe then sorry but it's not my call.

**Comment by ByteRaper** [comment]
Why would you block pr0gramm.com... Its the german equivalent of imgur or 9gag. Even the miner is like Fusl said opt-in.

**Comment by ZeroDot1** [comment]
@Fusl @dnmTX I'm going to take a closer look at the problem now and fix it.

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/issues/50#issuecomment-368311994

**Comment by ScriptTiger** [comment]
I'm sure people can understand that "opt-in" or not, it's extremely easy to just copy their miner JS file, edit like a line or two to remove the "opt-in" features (probably made as easy to do as possible, with comments and all) , and then host it on their own site, while the primary domain is still used for communication with the pool. CoinHive even inadvertently admitted this the last time they switched servers and posted an announcement for an issue affecting those hosting their own script.

>Sat, Feb. 24th, 14:00 UTC - We moved servers tonight and unfortunately failed to copy our legacy WebAssembly binaries (cryptonight.wasm). If you self-host a version of our coinhive.min.js from before Nov. 2017, you may have been affected. The issue has been fixed now.
>
>If you are self-hosting the coinhive.min.js, please update it. The current version embeds the WebAssembly binaries directly and doesn't need to load any external files.

These services have designed the scripts entirely self-contained and know people are abusing it and the "opt-in" BS is just a friendly face for legal matters and debates with blockers like us. I don't know anything about the domain in this issue, but I will trust @ZeroDot1's decision, as we are all trusting him for his due diligence and trust he will not cave to peer pressure. But I know issues like this will become more and more a common occurrence and I truly hope people don't lose sight of the true intention of this extension, just like the business leadership of cryptominers don't lose sight of their true intentions.

**Comment by StevenBlack** [comment]
Thanks for clarifying this @Fusl.  Thanks for your attention to this, @ZeroDot1.  Nice olympic silver medal, btw!  👊

**Comment by Fusl** [comment]
@ScriptTiger That's why I said we should keep `miner.pr0gramm.com` itself blocked since that's the hosting the mining web frontend and also the backend server.

https://github.com/StevenBlack/hosts/blob/182d18ba208b746c35f98f9ffe2e79190b4b2709/data/CoinBlockerList/hosts#L479
https://github.com/StevenBlack/hosts/blob/90c5640341ff1a28b7e54f4ce26ff3c9557af100/data/StevenBlack/hosts#L235
https://github.com/StevenBlack/hosts/blob/1341e7af528e8e5d887cccf74c1734ca1310b076/data/someonewhocares.org/hosts#L2376

None of the other `pr0gramm.com` 3LD or the 2LD itself have a Miner embedded or are used to communicate with such, only the `miner.` which is dedicated to this purpose.

**Comment by ScriptTiger** [comment]
No worries. That's one of the reasons I have been promoting to find a curated list for these with someone who is dedicated to digging into such granularity. Next step is just clearing out the redundancy in data/StevenBlack/hosts.
