### ISSUE TITLE
help.evernote.com is blocked

### ISSUE THREAD

**Issue by luisspuerto** [StevenBlack/hosts#511]
Hi!

Why help.evernote.com is blocked?

**Comment by StevenBlack** [comment]
@luisspuerto thanks for the notification.

This has been blocked for awhile.  The Evernote browser add-in was just rude.  I'll unblock this now, hopefully it's better.  I'm definitely not into browser add-ins that open tabs and download hundreds of megabytes of unwanted video spam every time they version themselves.

**Comment by luisspuerto** [comment]
Thanks a lot!! 

I've been using the browser add-in for quite a couple of years, or perhaps more, and I didn't even experience the behavior you're describing. 

Anyhow, thanks a lot for unblocking it!
