### ISSUE TITLE
add spotify block list - here it is

### ISSUE THREAD

**Issue by 2pac1** [StevenBlack/hosts#515]
Hey Steven, 

 Any chance you could include spotify list as well?

#spotify-added
0.0.0.0 spclient.wg.spotify.com #[affects mobile app]
0.0.0.0 adeventtracker.spotify.com
0.0.0.0 ads-fa.spotify.com
0.0.0.0 analytics.spotify.com
0.0.0.0 audio2.spotify.com
0.0.0.0 content.bitsontherun.com
0.0.0.0 crashdump.spotify.com
0.0.0.0 d2gi7ultltnc2u.cloudfront.net
0.0.0.0 d3rt1990lpmkn.cloudfront.net
0.0.0.0 desktop.spotify.com
0.0.0.0 googleadservices.com
0.0.0.0 gtssl2-ocsp.geotrust.com
0.0.0.0 log.spotify.com
0.0.0.0 omaze.com
0.0.0.0 open.spotify.com # website might not open
0.0.0.0 redirector.gvt1.com
0.0.0.0 spclient.wg.spotify.com
0.0.0.0 v.jwpcdn.com
0.0.0.0 weblb-wg.gslb.spotify.com
0.0.0.0 pubads.g.doubleclick.net
0.0.0.0 gads.pubmatic.com
0.0.0.0 audio-ec.spotify.com
0.0.0.0 heads-ec.spotify.com
0.0.0.0 prod.spotify.map.fastlylb.net
0.0.0.0 sto3.spotify.com
0.0.0.0 upgrade.spotify.com #updating
0.0.0.0 www.spotify-desktop.com
0.0.0.0 sto3-accesspoint-a88.sto3.spotify.net
0.0.0.0 upgrade.scdn.co
0.0.0.0 beta.spotify.map.fastly.net
0.0.0.0 play.spotify.edgekey.net
0.0.0.0 edgekey.net
0.0.0.0 play.spotify.com #web player won’t work
0.0.0.0 apresolve.spotify.com
0.0.0.0 b.scorecardresearch.com
0.0.0.0 bounceexchange.com
0.0.0.0 bs.serving-sys.com
0.0.0.0 core.insightexpressai.com
0.0.0.0 doubleclick.net
0.0.0.0 ds.serving-sys.com
0.0.0.0 googleads.g.doubleclick.net
0.0.0.0 js.moatads.com
0.0.0.0 media-match.com
0.0.0.0 open.spotify.com
0.0.0.0 pagead46.l.doubleclick.net
0.0.0.0 pagead2.googlesyndication.com
0.0.0.0 partner.googleadservices.com
0.0.0.0 s0.2mdn.net
0.0.0.0 securepubads.g.doubleclick.net
0.0.0.0 tpc.googlesyndication.com
0.0.0.0 video-ad-stats.googlesyndication.com
0.0.0.0 www.googleadservices.com
0.0.0.0 www.googletagservices.com
0.0.0.0 www.omaze.com
0.0.0.0 upgrade.spotify.com
0.0.0.0 cs283.wpc.teliasoneracdn.net
0.0.0.0 cs126.wpc.teliasoneracdn.net
0.0.0.0 u.scdn.co
0.0.0.0 cs126.wpc.edgecastcdn.net
0.0.0.0 pagead.l.doubleclick.net
0.0.0.0 pagead-googlehosted.l.google.com
0.0.0.0 partnerad.l.doubleclick.net
0.0.0.0 adserver.adtechus.com
0.0.0.0 na.gmtdmp.com
0.0.0.0 anycast.pixel.adsafeprotected.com
0.0.0.0 ads.pubmatic.com
0.0.0.0 idsync-ext.rlcdn.com
0.0.0.0 googlehosted.l.googleusercontent.com
0.0.0.0 d361oi6ppvq2ym.cloudfront.net
0.0.0.0 ads-west-colo.adsymptotic.com
0.0.0.0 geo3.ggpht.com
0.0.0.0 showads33000.pubmatic.com
0.0.0.0 http://audio2.spotify.com
0.0.0.0 www.audio2.spotify.com

**Comment by 2pac1** [comment]
Also this:

0.0.0.0 roulettebotplus.com
0.0.0.0 www.roulettebotplus.com
0.0.0.0 oneclickdownloader.com
0.0.0.0 a.faireagle.com
0.0.0.0 faireagle.com
0.0.0.0 wxdownloadmanager.com
0.0.0.0 1click-downloader.net
0.0.0.0 www.1click-downloader.net
0.0.0.0 www1.clickdownloader.com
0.0.0.0 clickdownloader.com
0.0.0.0 unblockedpiratebay.com
0.0.0.0 webstatsdomain.com
0.0.0.0 kickasstorrents.ee
0.0.0.0 www.kickasstorrents.ee
0.0.0.0 adclick.g.doublecklick.net

Havent checked if this is present.

**Comment by FadeMind** [comment]
See: https://github.com/StevenBlack/hosts/issues/506

**Comment by funilrys** [comment]
This one seems to be very demanding ... Should not we create/add it to the extensions Steven @StevenBlack ? :thinking:

**Comment by 2pac1** [comment]
sorry?

Also, this prevents hijacking browser for crypto mining
That could be separate filter


0.0.0.0 coinhive.com
0.0.0.0 www.coinhive.com
0.0.0.0 coin-hive.com
0.0.0.0 www.coin-hive.com
0.0.0.0 jsecoin.com
0.0.0.0 www.jsecoin.com
0.0.0.0 server.jsecoin.com
0.0.0.0 load.jsecoin.com
0.0.0.0 static.reasedoper.pw
0.0.0.0 mataharirama.xyz
0.0.0.0 www.mataharirama.xyz
0.0.0.0 listat.biz
0.0.0.0 www.listat.biz
0.0.0.0 lmodr.biz
0.0.0.0 www.lmodr.biz
0.0.0.0 minecrunch.co
0.0.0.0 www.minecrunch.co
0.0.0.0 minemytraffic.com
0.0.0.0 www.minemytraffic.com
0.0.0.0 crypto-loot.com
0.0.0.0 www.crypto-loot.com
0.0.0.0 2giga.link
0.0.0.0 www.2giga.link
0.0.0.0 ppoi.org
0.0.0.0 www.ppoi.org
0.0.0.0 coinerra.com
0.0.0.0 www.coinerra.com
0.0.0.0 coin-have.com
0.0.0.0 www.coin-have.com
0.0.0.0 kisshentai.net
0.0.0.0 www.kisshentai.net
0.0.0.0 miner.pr0gramm.com
0.0.0.0 kiwifarms.net
0.0.0.0 www.kiwifarms.net
0.0.0.0 anime.reactor.cc
0.0.0.0 joyreactor.cc
0.0.0.0 www.joyreactor.cc
0.0.0.0 kissdoujin.com
0.0.0.0 www.kissdoujin.com
0.0.0.0 minero.pw
0.0.0.0 www.minero.pw
0.0.0.0 coinnebula.com
0.0.0.0 www.coinnebula.com
0.0.0.0 afminer.com
0.0.0.0 www.afminer.com
0.0.0.0 coinblind.com
0.0.0.0 www.coinblind.com
0.0.0.0 webmine.cz
0.0.0.0 www.webmine.cz
0.0.0.0 monerominer.rocks
0.0.0.0 www.monerominer.rocks
0.0.0.0 cdn.cloudcoins.co
0.0.0.0 coinlab.biz
0.0.0.0 www.coinlab.biz
0.0.0.0 www.papoto.com
0.0.0.0 papoto.com
0.0.0.0 cookiescript.info
0.0.0.0 www.cookiescript.info
0.0.0.0 cookiescriptcdn.pro
0.0.0.0 www.cookiescriptcdn.pro
0.0.0.0 rocks.io
0.0.0.0 www.rocks.io
0.0.0.0 ad-miner.com
0.0.0.0 www.ad-miner.com
0.0.0.0 party-nngvitbizn.now.sh
0.0.0.0 www.party-nngvitbizn.now.sh

**Comment by StevenBlack** [comment]
Hi @2pac1 thanks for your input.

@2pac1 @funilrys I'm not clear on what's being asked here.

@2pac1 I just added a coinblock list to the default hosts in the past few hours.  I botched that (see #509) but that's fixed now.  If we're missing domains in this category, user @ZeroDot1 curates this particular area.  I hope adding his list to this repo doesn't lead to hassles – @ZeroDot1 I'm sorry in advance 😺.

@2pac1 one more thing, I hope you understand, we do very little host list curation here.  Rather, we amalgamate lists from well-curated sources to provide a master list that's frequently updated, and we provide options to also filter porn, social media, fake news, etc.

We are always evaluating well-curated lists for inclusion here.  But the central-point is, we can't accept big lists of domains for inclusion.  We need lists that come with dedicated people who care about accuracy on an ongoing basis.  This could include you, @2pac1, but it must come with a commitment to the ongoing, never-ending battle.

**Comment by 2pac1** [comment]
keep up the good work
i just saw that you do have cryptocurrency mining blocking added, great great
might want to think about adding spotify mini list for ads to stop

**Comment by 2pac1** [comment]
also, your crypto list, doesnt have main coin hive domain from where they pull the javascript


peep at this mini list

https://coinhive.com/lib/miner.min.js
coinhive.com
www.coinhive.com
coin-hive.com
www.coin-hive.com
jsecoin.com
www.jsecoin.com
server.jsecoin.com
load.jsecoin.com
static.reasedoper.pw
mataharirama.xyz
www.mataharirama.xyz
listat.biz
www.listat.biz
lmodr.biz
www.lmodr.biz
minecrunch.co
www.minecrunch.co
minemytraffic.com
www.minemytraffic.com
crypto-loot.com
www.crypto-loot.com
2giga.link
www.2giga.link
ppoi.org
www.ppoi.org
coinerra.com
www.coinerra.com
coin-have.com
www.coin-have.com
kisshentai.net
www.kisshentai.net
miner.pr0gramm.com
kiwifarms.net
www.kiwifarms.net
anime.reactor.cc
joyreactor.cc
www.joyreactor.cc
kissdoujin.com
www.kissdoujin.com
minero.pw
www.minero.pw
coinnebula.com
www.coinnebula.com
afminer.com
www.afminer.com
coinblind.com
www.coinblind.com
webmine.cz
www.webmine.cz
monerominer.rocks
www.monerominer.rocks
cdn.cloudcoins.co
coinlab.biz
www.coinlab.biz
www.papoto.com
papoto.com
cookiescript.info
www.cookiescript.info
cookiescriptcdn.pro
www.cookiescriptcdn.pro
rocks.io
www.rocks.io
ad-miner.com
www.ad-miner.com
party-nngvitbizn.now.sh
www.party-nngvitbizn.now.sh

**Comment by StevenBlack** [comment]
@2pac1 I agree.

We had a Spotify list up until 7 days ago (see #506 and commit 2d3b88e) but the data source added a spotify domain that interrupted service in the browser so this was dropped on a temporary basis until I see that's resolved.

**Comment by 2pac1** [comment]
my bad, conhive is in there
ok cool
i am looking from the standpoint of using the spotify app, and that works
once again, @StevenBlack I salute!!!

**Comment by ZeroDot1** [comment]
@2pac1 The hosts from their list have all been included in the CoinBlockerLists since a long time.

**Comment by StevenBlack** [comment]
Again @2pac1 I can't deal with lists of domains submitted on an ah-hoc basis.

Maybe some of our [data sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant) are willing to take your suggestions?

**Comment by 2pac1** [comment]
I get you, it would be too much work yes
Might ping some people, but was just dropping in here saying Hi and to give props

**Comment by StevenBlack** [comment]
Thank you @2pac1 

I must tell you, it feels weird to be in a position to adjudicate how Spotify is experienced by so many people.  I'm a paying Spotify customer myself, so I don't see what most people see...

**Comment by funilrys** [comment]
I also a paying Spotify customer @StevenBlack but I was talking about the fact that the Spotify list can or could be added to the extensions lists as it seems to be very demanding out there (hosts files users) ... But anyway I think this can be now closed :+1:
