### ISSUE TITLE
SiFy Video Streaming Blocked

### ISSUE THREAD

**Issue by Robotia** [StevenBlack/hosts#52]
One of the hosts in the host file blocks streaming via SyFy. (i.e. [here](http://www.syfy.com/theexpanse/videos/102-the-big-empty)).

I reset the file to my OS default, refreshed the page and found the video loaded perfectly.

**Comment by StevenBlack** [comment]
Hi @Robotia,

Here's a screenshot of the elements that aren't coming in, highlighted in yellow.

Hard to say, in my case, whether the hosts file or [Ghostery](https://www.ghostery.com/) which I also run.

I have to say, it's exactly this sort of thing that this hosts file is designed to block.  That's just an excessive number of crap requests.

**That said** you could figure out which domain SyFy critically depends upon, and add it to the whitelist, then rebuild the hosts file.

![2015-12-26_23-09-41](https://cloud.githubusercontent.com/assets/80144/12008814/ec40635c-ac25-11e5-882e-9f44855598b1.jpg)

**Comment by Robotia** [comment]
@StevenBlack  I'm certain it's the hosts file. When I reset it, I changed nothing else and the site worked perfectly.

**Comment by Robotia** [comment]
@StevenBlack Found the issue... 

Line 20346, adm.fwmrm.net seems to have been accidentally re-added to the block list. It has the file crossdomain.xml that is needed for the site to work.

**Comment by StevenBlack** [comment]
Both [someonewhocares.org](http://someonewhocares.org/hosts/) and [mvps](http://winhelp2002.mvps.org/hosts.htm) flag `adm.fwmrm.net` so it's not accidental.

You're free to modify your whitelist file and rebuild the hosts file for your purposes.
