### ISSUE TITLE
false positive supportxmr.com

### ISSUE THREAD

**Issue by M5M400** [StevenBlack/hosts#521]
My Monero Mining pool supportxmr.com as well as a few subdomains are being blocked on your list. It is a legit cryptocoin mining pool, there are no ads on the page and no webmining scripts. Please remove.

**Comment by funilrys** [comment]
Hello @M5M400 and welcome here,
I'm really sorry but that issue should be addressed to @ZeroDot1's [repository](https://github.com/ZeroDot1/CoinBlockerLists).

Can you look into this @ZeroDot1? 

Thanks in advance and have a nice day!

_____________________________
# Occurence search

```
./data/CoinBlockerList/hosts <== Entry point
./alternates/fakenews-porn/hosts
./alternates/fakenews-gambling/hosts
./alternates/social/hosts
./alternates/gambling/hosts
./alternates/fakenews-social/hosts
./alternates/porn-social/hosts
./alternates/gambling-porn/hosts
./alternates/fakenews-gambling-porn-social/hosts
./alternates/fakenews-gambling-porn/hosts
./alternates/porn/hosts
./alternates/fakenews/hosts
./alternates/gambling-porn-social/hosts
./alternates/fakenews-porn-social/hosts
./alternates/gambling-social/hosts
./alternates/fakenews-gambling-social/hosts
./hosts
```

**Comment by M5M400** [comment]
thanks, I'll bring it up over there.
