### ISSUE TITLE
--replace should detect correct location of 'sudo', and check for OS

### ISSUE THREAD

**Issue by MitchWeaver** [StevenBlack/hosts#522]
Using a hardcoded `/usr/bin/sudo` isn't ideal, as this may not be where a particular OS stores this. Instead it should be searched in the environment to find the correct location.

As well, on OpenBSD for example, 'sudo' has been replaced by `doas`. A check to confirm distro and act accordingly would be ideal.

In the meantime, you can just copy the host file manually after the script fails. 😅

**Comment by funilrys** [comment]
Hello @MitchWeaver and welcome here!

There's a pending PR (#519) which is in wait for refactoring against continuous tests results so please be patient @FadeMind should fix that soon :wink: 

Have a nice weekend.
Nissar

**Comment by FadeMind** [comment]
@funilrys  This waiting for acceptance and consent and merge @StevenBlack 

I using this on my custom setup and works like a charm. (But I don't know why really travis scream out ⚠️ 

Regards

**Comment by funilrys** [comment]
@FadeMind You have to fix [the following](https://travis-ci.org/StevenBlack/hosts/jobs/346915934#L606-L609).

```
./updateHostsFile.py:1055:44: E201 whitespace after '['
./updateHostsFile.py:1076:48: E201 whitespace after '['
./updateHostsFile.py:1076:80: E501 line too long (80 > 79 characters)
./updateHostsFile.py:1088:40: E201 whitespace after '['
```

Cheers

**Comment by FadeMind** [comment]
@funilrys fixed/resolved.

**Comment by funilrys** [comment]
As #519 has been merged this can be closed @StevenBlack ... unless we still have to implement : 

> As well, on OpenBSD for example, `sudo` has been replaced by `doas`. A check to confirm distro and act accordingly would be ideal.

**Comment by StevenBlack** [comment]
This is still to-do since we don't have the string `doas` anywhere in this repo yet...

**Comment by funilrys** [comment]
Okay Steven, then a beautiful `pull request needed` and/or `help wanted` label may help future contributors to find something to contribute to. :+1:

**Comment by MitchWeaver** [comment]
Tiny fix, I have submitted the PR

**Comment by funilrys** [comment]
Hey Steven @StevenBlack, this can be closed due to #525 :+1:

**Comment by funilrys** [comment]
@StevenBlack ^

**Comment by StevenBlack** [comment]
Thanks Nissar @funilrys.  Closing.
