### ISSUE TITLE
Semver proposal

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/hosts#524]
I've been thinking about [semver](https://semver.org/) and how it should apply here.

This is because merging Issue #520 will introduce breaking changes for those who regularly pull this repo and generate their own hosts files, since #520 introduces new requirements.

The problem with semver is, some people will chose to download an official release rather than the latest `head` on branch `master`.  Our latest `head` on `master` typically contains the very latest hosts, which is clutch.

So I propose the following for using semver here:

**Major**: breaking changes, like when we merge #520.
**Minor**: Whenever we have updates to `*.py`.
**Patch**: for whenever we just update hosts.

This means we'll hava a patch release every few days, where the `diff` is only to hosts file contents.

Good?

**Comment by funilrys** [comment]
Looks good to me :+1: 

I'm not Windows friendly but we also have a `*.bat` :smile: ... But I do understand that you also (indirectly) include all not `hosts` files behind that `*.py` :wink:

**Comment by StevenBlack** [comment]
I just released [1.0.0](https://github.com/StevenBlack/hosts/releases/tag/v1.0.0) and I'm open to input on this.

Versioning like this seems sensible to me...

**Comment by ScriptTiger** [comment]
No problem with the versioning. Maybe we should rename the new script to makeHostsv1.py and leave the old one for compatibility reasons like you stated, and for those that may have automation going on with the current one and haven't checked it yet to know their current automation is going haywire. And then we can just remove the deprecated one after a 3-month phase-out. It may be overboard, like most of my proposals, but just mentioning it.

**Comment by ScriptTiger** [comment]
```
# This hosts file is a merged collection of hosts from reputable sources,
# with a dash of crowd sourcing via Github
#
# Date: March 18 2018
# Number of unique domains: 56,046
#
# Fetch the latest version of this file: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
# Project home page: https://github.com/StevenBlack/hosts
#
# ===============================================================
```

Now that we have release versioning, might it be helpful to add that info to the hosts header, as well?
