### ISSUE TITLE
Still issues with someonewhocares.org

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/hosts#528]
Hi Nissar @funilrys I wonder if you could address the following new side-effect.  No rush, but soon.

I just regenerated hosts and the diff of [someonewhocares.org data](http://someonewhocares.org/hosts/zero/hosts) shows the following.  We're mangling author comments here.  This is not good.

Can we please not mangle comment lines, especially these lines which are clear, simple comments?

![2018-03-04_14-03-46](https://user-images.githubusercontent.com/80144/36949411-07bee08a-1fb6-11e8-87b0-4fac5230abba.jpg)

**Comment by funilrys** [comment]
@StevenBlack For sure but later this week probably (Berlin Time) :smile:

# About line 281,283, 295 

That is really an issue which I have to deal with as that is a grave violation.

# About line 286

Well, this one is more delicate as for now I do not even read the full content of the line but that's the results of a simple `str.encode("UTF-8").decode("UTF-8")` ... 

But I still remember that you do not care about performance as long as it's working so I will start learning from comments :smile_cat: I'm sure there are many things to learn about encoding by reading diffs like you did :100: 

# Note
You're right I did not give the attention the comments deserve ... But one thing to note is that for example `&amp;` == `&` in HTML so are we sure we want to handle all cases in comments? 

I'm not against handling and learning all the cases (like I already did somewhere else) as we all learn from those cases but I'm just asking before starting to work on this issue :wink:

**Comment by StevenBlack** [comment]
Ya I figured the ampersand thing was the case.

Fortunately this should be performance pain-free.  First rule,  if the whitespace-trimmed line starts with `#` then write it and bail.

**Comment by funilrys** [comment]
Hey @StevenBlack, I still have many sources to test for the viability of my solution but is this what you want ? :smile: 

https://gist.github.com/funilrys/da3cf048f6f6a9e293fe151f882c18e2#file-current_work-patch-L72-L644

Have a nice day/night.

**Comment by StevenBlack** [comment]
@funilrys yes, thank you!

**Comment by funilrys** [comment]
Hello Steven @StevenBlack,

I may have broken my Arch again so can you check if this issue is still present?

Indeed, I synced [my fork](https://github.com/funilrys/hosts) and run everything from scratch and I'm unable to face this issue anymore. Is it me or should I test with another distribution?

```
$ python updateHostsFile.py -a &> /dev/null && grep -nE "shortcut-examples|hijack-sites|SpyBot" data/someonewhocares.org/hosts
280:#<shortcut-examples>
287:#</shortcut-examples>
289:#<hijack-sites>
292:# removal programs such as SpyBotS&D, AdAware or HijackThis to remove this 
301:#</hijack-sites>
```

Have a nice day/night.

Cheers,
Nissar.

**Comment by XhmikosR** [comment]
@StevenBlack Isn't this issue solved now?
