### ISSUE TITLE
Ads and trackers

### ISSUE THREAD

**Issue by josh78** [StevenBlack/hosts#531]
I found some ad trackers on mobile phones that you may want to look at:
www.appnext.com
usc.adserver.snapads.com
app-analytics.snapchat.com

**Comment by StevenBlack** [comment]
Thanks @josh78.

The first link leads to a home page.  Can you clarify where, exactly, to look.

The second link leads nowhere.

The third link leads to a json response that says

    {
      "clazz": "com.snapengine.security.authz.AuthorizationException",
      "message": "anonymous@ was not authorized"
    }

Thanks for trolling.  Closing.

**Comment by dnmTX** [comment]
@josh78  stfu troll.....and don't let the door hit ya....
