### ISSUE TITLE
Error when running updateHostsFile.py

### ISSUE THREAD

**Issue by neilrooney** [StevenBlack/hosts#532]
Hi, since yesterday I believe I am getting this error when running the below command: 

`sudo python3 updateHostsFile.py -e fakenews gambling`

```
Traceback (most recent call last):
  File "updateHostsFile.py", line 27, in <module>
    import lxml  # noqa: F401
ModuleNotFoundError: No module named 'lxml'
```

**Comment by funilrys** [comment]
Hello @neilrooney and welcome here !

This issue is because we update the `updateHostFile.py` recently.

To quote what Steven said [here](https://github.com/StevenBlack/hosts/releases/tag/v1.0.0):

>March 3, 2018: As a result of some [recent commits](https://github.com/StevenBlack/hosts/pull/520) this release introduces breaking changes for those who are building their own hosts files.
>
>Please see the [readme](https://github.com/StevenBlack/hosts/blob/master/readme.md) under the [Generate your own unified hosts file](https://github.com/StevenBlack/hosts/blob/master/readme.md#generate-your-own-unified-hosts-file) section where you may need to install new dependencies.

To quote the readme:

>**Note** if you are using Python 3, please install the dependencies with:
>
> ```
>pip3 install --user -r requirements.txt
>```
>**Note** if you are using Python 2, please install the dependencies with:
>
> ```
>pip2 install --user -r requirements_python2.txt
> ```
>**Note** we recommend the `--user` flag which installs the required dependencies at the user level. More information about it can be found on pip [documentation](https://pip.pypa.io/en/stable/reference/pip_install/?highlight=--user#cmdoption-user).
>
>To run unit tests, in the top level directory, just run:
>
> ```
>python testUpdateHostsFile.py
> ```

Have a nice day,
Nissar.

**Comment by neilrooney** [comment]
Thanks a million @funilrys. All working now.
