### ISSUE TITLE
Blocking Zscaler Proxy Services

### ISSUE THREAD

**Issue by vdias** [StevenBlack/hosts#533]
My company uses Zscaler Proxy services, and your list is blocking their services... why??? Do you consider them Malware? Spam? ... ...

**Comment by funilrys** [comment]
Hello @vdias and welcome here!

Are we talking about zscaler.net ?

**Comment by funilrys** [comment]
Hello @vdias to be clear, `zscaler.net`, `zscalerone.net` and `zscalertwo.net` can be found in [Badd-Boyz-Hosts](https://github.com/mitchellkrogza/Badd-Boyz-Hosts/). 

As Steven @StevenBlack do not take responsibility for a domain added into one of the sources - unless it comes from its own [data](https://github.com/StevenBlack/hosts/tree/master/data/StevenBlack) -, I did review this request.

As `zscaler.net`, `zscalerone.net` and `zscalertwo.net`  have been found probing one of @mitchellkrogza websites and they was impossible to reach, `zscaler.net`, `zscalerone.net` and `zscalertwo.net` have been added to [Badd-Boyz-Hosts](https://github.com/mitchellkrogza/Badd-Boyz-Hosts/). 

However, as `zscaler.net`, `zscalerone.net` and `zscalertwo.net`  are used only by subdomains for example `admin.zscaler.net` or `admin.zscalertwo.net` in a legitimate way, we decided to remove it from [Badd-Boyz-Hosts](https://github.com/mitchellkrogza/Badd-Boyz-Hosts/).

Thanks again for the contribution.

Have a nice day/night.
Nissar.

**Comment by vdias** [comment]
Yes.

**Comment by funilrys** [comment]
Please close as this has been fixed by https://github.com/StevenBlack/hosts/commit/86d0bedff9be2d9132d0e3880ccc5441b7dbc129.

**Comment by vdias** [comment]
Fixed.

Thanks.
