### ISSUE TITLE
Adblocker warning in spiegel.de

### ISSUE THREAD

**Issue by anudeepND** [StevenBlack/hosts#536]
Visiting spiegel.de with adblocker turned on throws up a warning to 'Disable Adblocker'. 
But this can be prevented by blocking `spiegel-de.spiegel.de`.
It doesn't break anything, images, texts, layouts everything works fine. I think it's better to add this to blacklist.

**Comment by anudeepND** [comment]
@StevenBlack you can close it after adding to host file.

**Comment by StevenBlack** [comment]
Closing.
