### ISSUE TITLE
Office 365: better, but...

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/hosts#538]
I use [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) on MacOS.  What a great product.  As a result, I'm very aware, and can fine-control, connections in or out.

Several months ago, merely starting Word from an Office 365 subscription triggered 19 attempts to connect to various servers.

This appears much better now, but as of today, starting Word and Excel (Office 365 subscription) on MacOS still triggers the following connection attempts.

    omextemplates.content.office.net
    config.edge.skype.com
    ocos-office365-s2s.msedge.net
    officeclient.microsoft.com
    nexus.officeapps.live.com
    d.docs.live.net
    client-office365-tas.msedge.net

Among other things above, I consider Word and Excel's attempts to connect to Skype are abhorrent.  What do you think?

**Comment by ScriptTiger** [comment]
Maybe we could get a business/corporate extension to handle Microsoft products and  IoT devices (https://github.com/StevenBlack/hosts/issues/493), as it's definitely extremely useful for users of related products but completely irrelevant to everyone else, which is the majority of users.

**Comment by funilrys** [comment]
Hello Steven @StevenBlack and @ScriptTiger, 

As I'm actually rebuilding the system behind [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) I also had to review our whitelist list. 
So maybe the following whitelists may help build what @ScriptTiger mentioned as it's one among others used by @pi-hole  ...

https://github.com/deathbybandaid/piholeparser/tree/master/ScriptLsts/Whitelsts/WhiteDomains

Have a nice day/night.

**Comment by ScriptTiger** [comment]
Nice, @funilrys. After looking through it, I think I'd like to revise the terminology of the target software to "bloatware" and call it a bloatware extension. I think that better describes what we're trying to squelch here.

**Comment by anudeepND** [comment]
@funilrys If you're looking for whitelists, take a look at my work https://github.com/anudeepND/whitelist

**Comment by funilrys** [comment]
Hey, @anudeepND to be sincere about that, I already look at that and once I saw `adf.ly` I got away from that list ... Sorry but I do prefer to be sincere, I do think that `adf.ly` should be whitelisted locally not by a global system like the one I'm building. 

Thanks anyway :+1:

**Comment by StevenBlack** [comment]
I would propose that, going forward, for for anyone who wants this level of "bells and whistles" from their document editor, that this hosts file is definitely and categorically NOT for them.

Somebody convince me otherwise?  I'm interested in the counterpoint.

We had a similar issue awhile ago, wherein the default Windows text editor is unable to distinguish line endings used in our hosts files.  My feeling then, as now, remains: anyone who is such a mass-market-grade computing user, these hosts are not made especially for you.

And just this week, somebody complaining that occasional areas (ads) on msn.com don't show anymore.  Really?  Let me debug that for you.

I'd like to propose that this hosts collection is for smart people who "get" it.  For the others, well, send them to Symantec or McAfee and wish them, good luck and happy computing!

**Comment by anupritaisno1** [comment]
Microsoft and security you say?
Never heard of it
