### ISSUE TITLE
China video site Youku play failed

### ISSUE THREAD

**Issue by chenwen6498** [StevenBlack/hosts#541]
Youku video play failed,because some hosts was blacked.it seems to detect we blacked its Ad.I tried to delete "*.youku.com" in hosts,but still failed.after I recover my hosts,the video normally plays.

**Comment by StevenBlack** [comment]
Thanks @chenwen6498 

Here are the sources that give us youku domains:

    data/mvps.org/hosts
    0.0.0.0 urchin.lstat.youku.com

    data/someonewhocares.org/hosts
    0.0.0.0 stat.youku.com
    0.0.0.0 atm.youku.com
    0.0.0.0 Fvid.atm.youku.com
    0.0.0.0 html.atm.youku.com
    0.0.0.0 lstat.youku.com
    0.0.0.0 speed.lstat.youku.com
    0.0.0.0 static.lstat.youku.com
    0.0.0.0 urchin.lstat.youku.com
    0.0.0.0 valb.atm.youku.com
    0.0.0.0 valc.atm.youku.com
    0.0.0.0 valf.atm.youku.com
    0.0.0.0 valo.atm.youku.com
    0.0.0.0 valp.atm.youku.com
    0.0.0.0 vid.atm.youku.com
    0.0.0.0 walp.atm.youku.com

someonewhocares.org is a very reputable source of hosts.  Very responsible, too.  Please bring your concerns to hosts@someonewhocares.org.
