### ISSUE TITLE
[txxx.com] wrong directory

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#542]
This is a porn site but the domain is present in "Unified hosts = (adware + malware)" for some reason.I think it should be moved to the porn directory.
CC @StevenBlack

**Comment by StevenBlack** [comment]
Thanks @dnmTX.

`txxx.com` is listed as malware by a number of our sources.  Sure, it's a porn site.  It's so much more too.  Another example of this is `tube8.com`.

We often get notifications like such-and-such.com is a legit site!!  Um, no it's not.  Happens all the time.

Closing.
