### ISSUE TITLE
Consider adding my hosts file

### ISSUE THREAD

**Issue by bjornstar** [StevenBlack/hosts#543]
I've been maintaining a hosts file for the past few years, maybe you'd like to add it to your collection.

https://github.com/bjornstar/hosts

I update it regularly, usually about once a month and it's made available for all uses under the unlicense.

**Comment by FadeMind** [comment]
https://github.com/FadeMind/hosts.extras/commit/60aec018f8f917e5fb58bf62f268b50ea7fc91b0

**Comment by FadeMind** [comment]
@bjornstar  @bjornstar 

https://github.com/StevenBlack/hosts/pull/546
