### ISSUE TITLE
Fixing the raw.githubusercontent.com issue

### ISSUE THREAD

**Issue by ScriptTiger** [StevenBlack/hosts#544]
I just pushed a PR for ZeroDot1 to fix this on his repo:
https://github.com/ZeroDot1/CoinBlockerLists/pull/130

The same strategy won't work currently with this repo because there's currently a gh-pages branch in place serving "stevenblack.github.io/hosts/". It hasn't been updated in 2 years and I am not sure if most people here even knew it existed, let alone ever visited it. If it was to be removed and allowed content to be served from the main branch, like in ZeroDot1's case, we could replace all of the "Raw Hosts" links and there would no longer be any need for the "Non Github mirror" column, possibly lessening confusion for any users using fetchers like HostsMan.

**Comment by dnmTX** [comment]
@ScriptTiger  correct me if i'm wrong but the new URL(https://zerodot1.github.io/CoinBlockerLists/) links to the main page and on that page every "download" link goes to "https://raw.githubusercontent.com/......".So how is that a fix cause i remember you said in the other post that HostMan will not accept anything from "raw.githubusercontent.com"?

**Comment by ScriptTiger** [comment]
@dnmTX, please see the changes and test the new URLs:
https://github.com/ZeroDot1/CoinBlockerLists/pull/130/files

**Comment by dnmTX** [comment]
Ok,i saw the new URL's,i tried one and looks like it's working so good job and sorry for the rushed question and thank you for helping man,much appreciated.

**Comment by StevenBlack** [comment]
@ScriptTiger I'd like to keep the Github Pages option open for a Jekyll home page for this repo.  

The non-Github mirror option works fine...

Closing.
