### ISSUE TITLE
www.googleapis.com

### ISSUE THREAD

**Issue by kielby** [StevenBlack/hosts#547]
This list seems to be blocking www.googleapis.com which breaks the Google Drive Windows app (Backup and Sync by Google).

**Comment by StevenBlack** [comment]
Ping @bjornstar.

Thanks @kielby please stand by.

**Comment by bjornstar** [comment]
I've updated my list, fixed in https://github.com/bjornstar/hosts/commit/8d091336e6e549a6bdcb05f125576b5765b3b5c3

**Comment by kvic-z** [comment]
I got burned too in Mail.app this morning where Gmail login failed. 

Intended to drop by and report the issue... thanks for the lists and quick fix.

Btw, I wrote a [little story](https://kazoo.ga/pixelserv-found-unexpected-gmail-login-failure/) about this incident on my blog.

**Comment by FadeMind** [comment]
@StevenBlack same thing with spotify >> https://github.com/bjornstar/hosts/issues/3

**Comment by StevenBlack** [comment]
Thanks everybody, @bjornstar I'm going to drop the repo for now until we can sort these things out.  Adding a new repo is always rough...

**Comment by StevenBlack** [comment]
Sorry about that @kvic-z a fix is imminent.  Thanks for your patience.

**Comment by StevenBlack** [comment]
OK, [release 1.3.9 is live and online](https://github.com/StevenBlack/hosts/releases/tag/v1.3.9), thanks to everyone.

**Comment by dnmTX** [comment]
I admit @bjornstar 's list was too customized for his personal needs(which is ok but not when it's part of much bigger lists that is intend for broader audience).Too many legit domains were blocked and it would need very careful revision.

**Comment by nomez** [comment]
Again googleadapis.l.google.com is blocked in recent hosts list which blocks google fonts and many other api related libraries.

**Comment by FadeMind** [comment]
Resolved in https://github.com/FadeMind/hosts.extras/commit/ea7682de538ea342381a101bdf7a4d27c59c6c68
