### ISSUE TITLE
Remove bjornstar because it is not well-curated

### ISSUE THREAD

**Issue by mikhaelkh** [StevenBlack/hosts#548]
It is stated that hosts are consolidated from several well-curated sources,
Well, bjornstar is not the case.
`yandex.ru`, [Alexa's 27](https://www.alexa.com/siteinfo/yandex.ru) is there since at least [2014](https://github.com/bjornstar/hosts/blame/8d091336e6e549a6bdcb05f125576b5765b3b5c3/hosts#L261)!

**Comment by FadeMind** [comment]
@mikhaelkh  spotify is blacklisted there too :scream:  :thinking:  aaand maintainer sent user to whitelist file cause DID NOT USE spotify.
BTW @StevenBlack I can maintain spotify valid hostsfile if needed (for from @CHEF-KOCH) if needed.

**Comment by StevenBlack** [comment]
If you could, Tomasz @FadeMind , that would be great.

@mikhaelkh adding a new source to this repo is always rough.  

But to your point, @mikhaelkh, presence on an Alexa list does **not** mean the domain isn't scummy.  Facebook is scummy, but not according to its "ranking" on most lists.  Popularity and digital ethics are quasi-orthogonal.

**Comment by StevenBlack** [comment]
Fixed in [Release 1.3.9](https://github.com/StevenBlack/hosts/releases/tag/v1.3.9).  Closing.

**Comment by mikhaelkh** [comment]
`Unified hosts = (adware + malware)`  and `yandex.ru` is neither of those, except
[Yandex.Metrica](https://yandex.com/support/metrica/) and [Yandex.DIrect](https://yandex.com/support/direct/) which are documented and blocked in more well-curated sources.
