### ISSUE TITLE
[tyzbit] telemetry domains 

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#550]
@tyzbit  i couldn't access your repo for some reason so i'll post it here.Found those while browsing through my registry.Windows Defender using them to send data to Microsoft.I think further investigation is needed cause i'm not sure what else could break.I personally not using Defender so i'm not worry but it's not just me here.
https://spynet2.microsoft.com
https://spynetalt.microsoft.com

**Comment by tyzbit** [comment]
https://blogs.technet.microsoft.com/clientsecurity/2011/02/22/microsoft-spynet/
Hmmm.

SpyNet appears to be a service where Defender uploads signatures and other data to.  This isn't _tracking_ per se, but antivirus data collection (which is useful and valuable for people to do, generally). 

But going by the goal of my list, I think this is desired blocking.  The purpose of my list specifically is to block/disable as much of the Windows/Microsoft based tracking and advertising.  SpyNet is a service that collects data from your computer.  I personally would want this blocked.  I'm open to more discussion though.

**Comment by StevenBlack** [comment]
Closing.
