### ISSUE TITLE
PGAtour.com - Can't log in

### ISSUE THREAD

**Issue by THEtomaso** [StevenBlack/hosts#553]
**Affected site**:
`https://www.pgatour.com/`

**Issue**:
Can't log in

**Problem filter**:
Dan Pollock's hosts file

**Problem rule**:
`cdns.gigya.com`

**Possible fix**:
`@@cdns.gigya.com$domain=pgatour.com`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.8.3 (x64)
- Adblock Extension/version: uBlock Origin v1.15.18

**Comment by StevenBlack** [comment]
Thanks @THEtomaso.  

`cdns.gigya.com` is flagged by someonewhocares.org and mvps.org.  These sources are among the best and they take this very seriously.

If this domain is flagged by both these sources, then I can telly you that there's likely something ethically reprehensible with `cdns.gigya.com`.

You can report someonewhocares.org issues by emailing  pollock@theorem.ca and at winhelp2002@gmail.com for the mvps.org list.

I suggest you also contact pgatour.com and tell them their login process is problematic.

Closing.

**Comment by StevenBlack** [comment]
@THEtomaso nonetheless, excellent bug report.  I'm sorry I can't help you beyond this.

**Comment by THEtomaso** [comment]
Actually, I'm using 'MVPS HOSTS' too.
You're right that it blocks many things @ gigya.com..
However, it does NOT block cdns.gigya.com, and therefore does NOT break the login function @ pgatour.com!

Frellwit's Swedish Filter also broke the login function, but after I filed a report, they fixed it:
`https://github.com/lassekongo83/Frellwits-filter-lists/issues/15/`

I don't have an account at pgatour.com myself, but simply noticed the problem because of this forum thread:
`https://forum.palemoon.org/viewtopic.php?f=3&t=18761/`

**Comment by THEtomaso** [comment]
> You can report someonewhocares.org issues by emailing pollock@theorem.ca

I did, and the issue has now been fixed in the latest filter update! :)

--

Question:
So, for any future issues with Dan Pollock's hosts file, I should send my reports to that e-mail address, instead of posting them here?

**Comment by StevenBlack** [comment]
That's great!

Yes, in the future, any problems should be addressed directly to the data providers.
