### ISSUE TITLE
New sharethrough.com domain spotted

### ISSUE THREAD

**Issue by kquinsland** [StevenBlack/hosts#554]
I've noticed that `sharethrough.com`is on several black lists (including `StevenBlack/hosts/master/hosts`) but this new `asap` subdomain is not.

`asap.sharethrough.com` appears to be used for what look like (android) SDK initialization pings.

I believe this makes it a good candidate for addition to the block lists.

*EDIT:* . I'd be happy to open my own PR if that's the preferred workflow

**Comment by StevenBlack** [comment]
Thanks @kquinsland I've added `asap.sharethrough.com` and it will be live shortly.
