### ISSUE TITLE
Bing cannot be reached with the host files installed

### ISSUE THREAD

**Issue by zayuim** [StevenBlack/hosts#555]
When I delete the host files, bing.com is accessible. When I install these host files, the site is blocked.

**Comment by ScriptTiger** [comment]
What operating system and browser are you working with?

**Comment by StevenBlack** [comment]
@tyzbit this appears due to `any.edge.bing.com`.

**Comment by anudeepND** [comment]
@StevenBlack bing.com is working fine for me with `any.edge.bing.com` blocked, any ideas?

**Comment by StevenBlack** [comment]
Sorry @tyzbit evidently I was unclear.  Can you review why `any.edge.bing.com` is listed in line 29 of https://gist.githubusercontent.com/tyzbit/83b3297cb8ce1e5af4c90d232b1f5886/raw?  Thanks.

    $ ack any.edge.bing.com
    data/tyzbit/hosts
    29:127.0.0.1 any.edge.bing.com

**Comment by tyzbit** [comment]
Comes from https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/block-telemetry.ps1#L48

**Comment by zayuim** [comment]
@ScriptTiger 

Ubuntu 17.10

Linux version 4.13.0-37-generic (buildd@lcy01-amd64-026) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3.2)) #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018

Mozilla Firefox 59.0.2

**Comment by StevenBlack** [comment]
Thanks for the issue @zayuim.  This is now resolved.
