### ISSUE TITLE
Unable to play videos on time.com

### ISSUE THREAD

**Issue by anudeepND** [StevenBlack/hosts#558]
Videos are blocked in time.com, this is due to `edge.api.brightcove.com` being blocked.

#### Before whitelisting

![screenshot_20180403-200438-01](https://user-images.githubusercontent.com/26179946/38287900-f9a2582c-37ea-11e8-94cc-34d8669af3ce.jpeg)

#### After whitelisting 

![screenshot_20180403-193813-01](https://user-images.githubusercontent.com/26179946/38287922-14e2a0ba-37eb-11e8-8e73-78816750130c.jpeg)

**Comment by FadeMind** [comment]
@StevenBlack there it is here

https://github.com/StevenBlack/hosts/blob/7849fd66007b1ba17326a8dc76a8bae885aac236/data/StevenBlack/hosts#L92

**Comment by StevenBlack** [comment]
Thanks @anudeepND and @FadeMind.  This is [fixed in release 1.3.16](https://github.com/StevenBlack/hosts/releases).
