### ISSUE TITLE
Spanish Forum Blocked

### ISSUE THREAD

**Issue by vdias** [StevenBlack/hosts#559]
![image](https://user-images.githubusercontent.com/2320553/38371840-bd215e3a-38ed-11e8-9d09-0f30e919b70d.png)

Don't understand why is the forum completely blocked... it is legal, talking about TV/HiFi/DVD, no piracy on here...

**Comment by StevenBlack** [comment]
Hi @vdias we aren't associated with uBlock Origin.

**Comment by vdias** [comment]
The problem is not about ublock origin... the filter is on your list.

**Comment by FadeMind** [comment]
This domain is not listed anywhere in @StevenBlack hosts files or https://github.com/FadeMind/hosts.extras.

**Comment by FadeMind** [comment]
@StevenBlack Github search did not found this domain but this domain is blocked in main hosts file indeed... But I must find source... 
```

```

**Comment by vdias** [comment]
![image](https://user-images.githubusercontent.com/2320553/38373522-c44a0316-38f1-11e8-9f09-b11b6f237493.png)

**Comment by StevenBlack** [comment]
`www.forodvd.com` – see the uBlock Origin screen shot – is not listed here.

`forodvd.com` comes from Badd-Boys.

Still doesn't change, we aren't affiliated with uBlock Origin.

**Comment by funilrys** [comment]
Hello there, 
Hope that everything goes right for you guys (and girls).

@vdias, I did not look deep into that domain yet but can you create an issue to https://github.com/mitchellkrogza/Badd-Boyz-Hosts so I can take a look at it when I have time? :+1:  

Thanks in advance and sorry for the inconvenience.
