### ISSUE TITLE
Spotify doesn't update on macOS

### ISSUE THREAD

**Issue by notDavid** [StevenBlack/hosts#560]
Just an fyi. To reproduce, open the Spotify app, click on the menu "Spotify -> About Spotify" and you will see a button "Download new version"  <- this button is only visible *if* an update is available for you...
After clicking the button, nothing happens.

Whitelisting `upgrade.scdn.co` fixes the problem, and Spotify will update itself again (after whitelisting, repeat the above steps.)

**Comment by funilrys** [comment]
I can't find `upgrade.scdn.co`  in the repository (I'm not talking about GitHub search) :thinking: 

Is that possible that you still have a copy of `Spotify-Ad-free` which was dropped by https://github.com/StevenBlack/hosts/commit/2d3b88ecfd11001bd92636bbbc8601deaf8af9fb ? :thinking:
