### ISSUE TITLE
[Enhancement] whitelist.skel with recommended whitelist domain list.

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#565]
Please consider provide default whitelist domain list against issues with various video and download center websites. 
Proper working mostly polish language websites I using following whitelist file:
```
2mdn.net
adocean.pl
any.edge.bing.com
criteo.com
facebook.net
fbcdn.net
flarecloud.net
gemius.pl
googleapis.com
googletagmanager.com
iplsc.com
npttech.com
onet.hit.gemius.pl
openload.co
openload.io
pro.hit.gemius.pl
s.tvp.pl
streamango.com
t.scdn.co
www.googletagmanager.com
```

@StevenBlack this file don't need to be `whitelist` named. Maybe better `whitelist.skel` or something like that.

**Comment by StevenBlack** [comment]
closing.
