### ISSUE TITLE
add more sites to porn list

### ISSUE THREAD

**Issue by tukusejssirs** [StevenBlack/hosts#566]
I found some porn sites that are not in the list:
```
thelesbianconnection.com
collegesexlives.com
dm.damcdn.net
viplocal-hookups.com
18girlsex.net
teenageslut.net
3dporntubex.info
```

**Comment by ScriptTiger** [comment]
Bump, @sinfonietta & @clefspeare13 ^

**Comment by g3n0k0m0** [comment]
I'll try my best to help research more obscure porn sites to help contribute to the cause ;)

**Comment by Clefspeare13** [comment]
I've added these domains

**Comment by StevenBlack** [comment]
This is in the [latest release](https://github.com/StevenBlack/hosts/releases).

Closing.

**Comment by tukusejssirs** [comment]
Thank you all for such a prompt response and fix. ;) :+1:
