### ISSUE TITLE
[question/social] Exclude Twitter or move to subdirectory?

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#570]
It's just a question and i'm not advocating or anything and let me say that i'm not really fan of the social networks in general that's why i'm using "social" with my list but every time i read something interesting on the web that has pictures most of the time they are linked to Twitter,therefore i can't see them.Kind of annoying.Is there any chance to exclude Twitter or move it to subdirectory? Looking at the block domains it doesn't look very "invasive" like,for example Facebook.
P.S. Using dnsmasq that it's installed on my router and i can only download ready lists,can't even modify it the way i like so i'm kind of dependent on what is already provided.
CC @StevenBlack

**Comment by StevenBlack** [comment]
Yeah, @dnmTX, I hear 'ya.

But... the whole point of the Social Media extension is to force-focus.  So what are you doing web-surfing when you're supposed to be working? 😺

**Comment by dnmTX** [comment]
@StevenBlack  the "surfing" part usually happens after hours but thanks for checking up on me...hehehe. I guess i'm gonna have to drop the "social" extension.Looks like there is no medium happy in my situation.Thanks for the reply Steven and the...humor  😄
Closing.....
