### ISSUE TITLE
Hosts split into segments

### ISSUE THREAD

**Issue by xetorixik** [StevenBlack/hosts#573]
@StevenBlack Perhaps it is an idea that the entire list is being split into segments. 
With ADS, trackers, telemetry etc etc.
This allows the end user to select (opt-in).

You can continue to discuss in the current way.
This makes it a lot clearer.

**Comment by StevenBlack** [comment]
Hi @xetorixik 

Easier said than done, unfortunately.

The curated lists come, thousands at once, as lists that don't differentiate.

This just isn't doable.   The best we can do is be thankful that some folks maintain pre-targeted lists for porn, social media, and gambling.

Now if you want to create and curate a list along the lines you propose, then I'm happy to entertain including it.

**Comment by xetorixik** [comment]
Understood.
@StevenBlack you are a great man.
Thanks for you list.
