### ISSUE TITLE
Reddit - Porn

### ISSUE THREAD

**Issue by ghost** [StevenBlack/hosts#583]
Can you add this list? https://pastebin.com/CBgrXbxV
Also amateurporn.com and switter.at 
Thanks

**Comment by funilrys** [comment]
Hello @paranoicogm and welcome here,

About the list you linked, we can't add it to this repository because that will include blocking `reddit.com` (the whole infrastructure). 

About `amateurporn.com` and `switter.at` it'll depend on @StevenBlack :smiley_cat: 

Please learn more about hosts file [here](https://github.com/StevenBlack/hosts#what-is-a-hosts-file).

Cheers,
Nissar

**Comment by StevenBlack** [comment]
Closing.  Thanks Nissar, this user's account has been deleted.

**Comment by ScriptTiger** [comment]
@Sinfonietta & @Clefspeare13, bump ^

The reddit thing is obviously a no-go, but they can look into amateurporn.com and switter.at.

Also, now that I am thinking about it, should reddit be on the social extension? It's not, but I think it qualifies? I think for people in a situation where they want to block social from their kids or what have you that should be using the Internet for research and homework and not watching funny videos or checking the latest memes, etc., reddit would definitely be a hole in that plan if it's opened. And if you're talking about something school-related, unless it's homework directly about reddit itself, you probably don't want your kids citing anything from reddit anyway. But in the end this is only one domain and easy to block on its own. Just opening that up for thought.

**Comment by dnmTX** [comment]
This is the same person from #531. Just another troll that don't give up. @StevenBlack if there is a way to block him in your repo i'd suggest you do so.

**Comment by ScriptTiger** [comment]
Oh, sorry, didn't catch that. I am working at the moment and didn't check the links. DISREGARD. Thanks, @dnmTX, for pointing that out. I edited my above comment. My reddit comment still checks out, I think.

I don't think there is a way to block someone via the GitHub web page as long as they keep deleting their user account and making a new one because all the bans are account-related. They are fair game to be reported to GitHub though and they can take a more dynamic approach to blocking them, since they are voiding the GitHub terms.

**Comment by StevenBlack** [comment]
@ScriptTiger yes I think Reddit would qualify for the social media extension.

Puzzling, isn't it, that nobody's mentioned that?  It's a fair point.

**Comment by ScriptTiger** [comment]
There is always so much hype over letting reddit run free and not putting the little guy down and letting the news of the people get out there and whatnot that it's running right out of its rightful category.

**Comment by thuel1** [comment]
👇Click for a free trial👇👇Click for a free trial👇👇Click for a free trial👇👇Click for a free trial👇
👇Click for a free trial👇👇Click for a free trial👇👇Click for a free trial👇👇Click for a free trial👇
Free deepnude ai :
Free deepnude ai :
Free deepnude ai : [https://bt-fr-cl.com/tds/ae?tdsId=s7451sto_r&tds_campaign=s7451sto&s1=ps&utm_source=int&utm_sub=opnfn&subid={subid}&subid2={subid2}&clickid={clickid}l&affid=181c7b69](https://bt-fr-cl.com/tds/ae?tdsId=s7451sto_r&tds_campaign=s7451sto&s1=ps&utm_source=int&utm_sub=opnfn&subid=%7Bsubid%7D&subid2=%7Bsubid2%7D&clickid=%7Bclickid%7Dl&affid=181c7b69)
Free deepnude ai :
Free deepnude ai : [https://bt-fr-cl.com/tds/ae?tdsId=s7451sto_r&tds_campaign=s7451sto&s1=ps&utm_source=int&utm_sub=opnfn&subid={subid}&subid2={subid2}&clickid={clickid}l&affid=181c7b69](https://bt-fr-cl.com/tds/ae?tdsId=s7451sto_r&tds_campaign=s7451sto&s1=ps&utm_source=int&utm_sub=opnfn&subid=%7Bsubid%7D&subid2=%7Bsubid2%7D&clickid=%7Bclickid%7Dl&affid=181c7b69)

**Comment by thuel1** [comment]
👇Click for a free trial👇👇Click for a free trial👇👇Click for a free trial👇👇Click for a free trial👇
👇Click for a free trial👇👇Click for a free trial👇👇Click for a free trial👇👇Click for a free trial👇
Free deepnude ai :
Free deepnude ai :
Free deepnude ai : [https://bt-fr-cl.com/tds/ae?tdsId=s7451sto_r&tds_campaign=s7451sto&s1=ps&utm_source=int&utm_sub=opnfn&subid={subid}&subid2={subid2}&clickid={clickid}l&affid=181c7b69](https://bt-fr-cl.com/tds/ae?tdsId=s7451sto_r&tds_campaign=s7451sto&s1=ps&utm_source=int&utm_sub=opnfn&subid=%7Bsubid%7D&subid2=%7Bsubid2%7D&clickid=%7Bclickid%7Dl&affid=181c7b69)
Free deepnude ai :
Free deepnude ai : [https://bt-fr-cl.com/tds/ae?tdsId=s7451sto_r&tds_campaign=s7451sto&s1=ps&utm_source=int&utm_sub=opnfn&subid={subid}&subid2={subid2}&clickid={clickid}l&affid=181c7b69](https://bt-fr-cl.com/tds/ae?tdsId=s7451sto_r&tds_campaign=s7451sto&s1=ps&utm_source=int&utm_sub=opnfn&subid=%7Bsubid%7D&subid2=%7Bsubid2%7D&clickid=%7Bclickid%7Dl&affid=181c7b69)

**Comment by ScriptTiger** [comment]
@StevenBlack, just following up on this really quick. It looks like they sent 2 within a short period of each other and wasn't sure if you missed the last/second one. I also reported them for good measure.

**Comment by StevenBlack** [comment]
Thank you @ScriptTiger
