### ISSUE TITLE
More lists to consider

### ISSUE THREAD

**Issue by lordraiden** [StevenBlack/hosts#584]
Please take a look to this site and consider add some of the lists sugested on it

https://www.linuxincluded.com/block-ads-malvertising-on-pfsense-using-pfblockerng-dnsbl/

**Comment by StevenBlack** [comment]
Thanks @lordraiden the information I need is a specific link to a specific list of hosts.

Linking to an article that embeds gists whose text contains text links that may or may not have much merit, that amounts to a wild goose chase for us.

Nevertheless, thank you for the suggestion.
