### ISSUE TITLE
Skillshare Block

### ISSUE THREAD

**Issue by tooxo** [StevenBlack/hosts#585]
Dont know about the PC but on android the streaming of the skillshare app gets blocked.

**Comment by StevenBlack** [comment]
Hi @tooxo do you have any deets?  At minimum we need to know, which domains the Skillshare app depends upon.

**Comment by tooxo** [comment]
dont know, is there a wireshark for android?

**Comment by anudeepND** [comment]
@tooxo Try whitelisting `edge.api.brightcove.com` and `players.brightcove.net`

**Comment by Rikk** [comment]
Packet Capture is a simple app for capturing packets; it can decode https traffic too: https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture

**Comment by tobibeer** [comment]
Thought it was a flash issue and then realized my hosts file broke SkillShare. Had to whitelist **f1.media.brightcove.com**.
