### ISSUE TITLE
ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by luntik2012** [StevenBlack/hosts#590]

**Comment by ryanku98** [comment]
I'm actually getting this issue now when running updateHostsWindows.bat -a (seemingly out of nowhere as it was working about a month ago). I've located the beautifulsoup files to confirm that they were installed and even tried reinstalling them, to no avail. Could someone link me to the fix that led this to be closed? Couldn't seem to find it anywhere... Thanks!

**Comment by ryanku98** [comment]
Hi @funilrys,
My apologies. I forgot to specify that that is how I tried to install them. Every time I try to install the dependencies with that line, it simply returns with the following lines:
~~~
Requirement already satisfied: lxml>=4.2.4 in c:\users\ryank\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 1)) (4.2.5)
Requirement already satisfied: beautifulsoup4==4.6.1 in c:\users\ryank\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 2)) (4.6.1)
~~~
Only after I uninstall them then reinstall them with that line does it say that they are installed, but then running updateHostsWindows.bat -a simply returns with the same error.

**Comment by funilrys** [comment]
Oh, you're on Windows! 
Try to uninstall then install without the `--user` flag :thinking:

**Comment by ryanku98** [comment]
That was what I tried first, which also returned the same lines saying that they're installed already 😔

**Comment by DonRichards** [comment]
Just tried this script and got that same error. Might want to address this. Possibly a missing step in the instructions.
