### ISSUE TITLE
[coin miners] watch and contribute if you can

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#592]
Very educational video worth watching:
 https://www.youtube.com/watch?v=hDQrSxud83k 
Our friend @ZeroDot1 is one of not too many who's keeping us safe against that arising malicious threat and he could really really use some donations due to the fact that he's working with very old tech that doesn't quite help the cause.Many of us here benefiting of his work and i think it's time to give back,i personally did and have no regrets.So...if you can afford it please visit:
https://www.amazon.de/hz/wishlist/ls/2DDEDPJU2996I?filter=unpurchased&language=en_GB&sort=price-asc&type=wishlist
look for "priority high/highest" and do so. **THANK YOU KINDLY**

**Comment by StevenBlack** [comment]
@dnmTX issue renamed to remove multiple exclamation marks ❗️❗️❗️❗️ ❗️

**Comment by ZeroDot1** [comment]
I created a homepage for the project CoinBlockerLists, there you can find more information about the project. 
https://zerodot1.github.io/CoinBlockerListsWeb/aboutthisproject.html
Every donation keeps the future development going. Thank you.

The complete homepage is handwritten, no WordPress or similar is used.

**Comment by matkoniecz** [comment]
From what I see CoinBlocker is already included - see https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant

Is there anything else that should be done?

**Comment by dnmTX** [comment]
@matkoniecz  yes....there is....if you willing.....my first comment would explain how 🙄

**Comment by funilrys** [comment]
@StevenBlack Please close as this take us anywhere ...

**Comment by StevenBlack** [comment]
Closing!

**Comment by dnmTX** [comment]
😞
