### ISSUE TITLE
Amazon Echo issue with device-metrics-us.amazon.com

### ISSUE THREAD

**Issue by Mrnt** [StevenBlack/hosts#596]
I'm seeing a problem where my Amazon Echo ceases to function after repeatedly being blocked from accessing `device-metrics-us.amazon.com`
Although I believe the domain has been in the host list for a while, it seems to have just started being an issue with the Echo in the last day or two.

**Comment by StevenBlack** [comment]
Thanks Gavin @Mrnt.  Keep an eye on this for us?

**Comment by anudeepND** [comment]
Hi @Mrnt recently a similar domain `device-metrics-us-2.amazon.com` is included in the list, does it interferes with Amazon echo?

**Comment by Mrnt** [comment]
Hi @anudeepND, @StevenBlack sorry for the delay - have been trying to sniff the traffic without to much success. It appears that `device-metrics-us.amazon.com` is also accessed by other things on my network - possibly the Alexa app running on mobile devices and also a Kindle. I saw [here](https://www.reddit.com/r/pihole/comments/7lvuz8/amazon_requesting_40k_dns_requests/) and [here](https://discourse.pi-hole.net/t/device-metrics-us-amazon-com-requests-like-crazy/5731/21) that blocking it from Kindles caused a dramatic decrease in battery life because they repeatedly try to access it on failure. I suspect that Amazon recently changed something on the Echo that causes it to fail if it is not able to report its usage stats via this domain.

Re `device-metrics-us-2.amazon.com` - that is still currently blocked on my network without any obvious adverse effects and the only devices that are occasionally accessing it seem to be mobile devices, presumably because of the Alexa or Amazon apps.

**Comment by jawz101** [comment]
fwiw I went ahead and removed these from Adaway today.
