### ISSUE TITLE
Deprecation warning when running testUpdateHostsFile.py

### ISSUE THREAD

**Issue by onmyouji** [StevenBlack/hosts#597]
Hi,

When running testUpdateHostsFile.py, I got this error message

> .......C:\Program Files\Python36\lib\site-packages\bs4\builder\_lxml.py:250: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
>   self.parser.feed(markup)

Does anyone else get this error message?

**Comment by StevenBlack** [comment]
Hi @onmyouji yes, I get same on MacOS.

**Comment by funilrys** [comment]
Will take the time this weekend (or part of the next week) to fix this along with #528 Steven @StevenBlack.

Cheers,
Nissar

**Comment by funilrys** [comment]
Hello @onmyouji, 
I mentioned it into #602 but for clarification for the others who think that it is a local issue, please report to #520 description:

> Please note that I have to submit an issue to upstream but if you see the following or related when runing the tests under `Python >= 3` it's not a local issue. 
>```
>/home/travis/miniconda3/envs/hosts/lib/python3.5/site-packages/bs4/builder/_lxml.py:250: >DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
>```

For now, the maintainers of `lxml` and especially `bs4` know that the following warning exists but consider that as not a priority to fix yet. 

I personally going to contact one of the maintainers to hear more from their part as that warning is full of sense but until then, we keep the current version of the scripts unless someone has another idea or Steven @StevenBlack decide to drop BeautifulSoup.

Have a nice day/night.

Cheers,
Nissar.

**Comment by onmyouji** [comment]
Thanks @funilrys
