### ISSUE TITLE
Bwahaha blocks all conservative and russian news as fakenews

### ISSUE THREAD

**Issue by Biorazero** [StevenBlack/hosts#601]
0.0.0.0 ruptly.tv
0.0.0.0 www.infowars.com
0.0.0.0 www.naturalnews.com
0.0.0.0 www.prisonplanet.com
0.0.0.0 www.rt.com
0.0.0.0 www.wnd.com
0.0.0.0 www.zerohedge.com

what a loser

**Comment by Biorazero** [comment]
Don't you think you should let your users know that the context of fakenews you're using is coming from a heavily biased viewpoint. If you only added clickbait sites such as yournewswire.com and others to the list it would have been different, but you added mainline ones like wnd and zerohedge, you're out of your effing mind.

What about this hosts file:

0.0.0.0 stevenblack.com

**Comment by Biorazero** [comment]
Is your so called "reputable source" snopes.com for example, a couple with a cat in a dorm room.

**Comment by dnmTX** [comment]
**NOTHING TO SEE FOLKS......JUST ANOTHER "CEO" BLOWING UP STEAM**

**Comment by Biorazero** [comment]
Allright, I may have been too quick to blame the repo owner, it's a consolidation from other curators, I apologize. But still, he seems to agree with it and going along with it so far.

**Comment by raziel-** [comment]
@Biorazero
You can whitelist anything, or you can completely skip Fakenews

**Comment by funilrys** [comment]
May I ask what is the real object behind this issue? 

If you want to blame, as a question or report an issue regarding the fake news extension please report to https://github.com/marktron/fakenews/issues.

@StevenBlack please close as this issue should be handled by @marktron.

**Comment by Biorazero** [comment]
@funilrys Yeah, I just couldn't get to it in the moment, fakenews has been going on since forever, and it just happens to be a big realization right now, however some are being falsely labeled while others that were fake all these years aren't given enough attention.

For example, there are a lot of youtube channels which literally make money off fake CGI-generated UFOs that don't exist, including taking official video from NASA ISS Livestream and modifying it making it look like that NASA "cut the feed" and inserting objects into the video that weren't seen in the actual livestream, such behavior discredits all the cases where there is a real genuine UFO or something.

So, are you going to ban youtube.com just because a few channels post fake UFOs - so if youtube.com isn't getting banned, why do other sites deserve this? Right now rt.com is being banned just because there's a few articles that are ofcoruse defending the country they originate from, aren't US sites defending their origin too? So it does not seem fair to blank-check ban a whole site, which has various content, and does a lot of other things that are non-political. I am aware that hosts can only block a whole domain and not specific pages, so it should be used with care.

I apologize for a little bit of attitude, might have not been the most optimal place, I made my point, I'll make it easier and close it myself.
