### ISSUE TITLE
stuck loading on resolving hosts

### ISSUE THREAD

**Issue by alphamonkey11** [StevenBlack/hosts#603]
Hi, 

since updating to the latest hosts, it takes a long time for my browser (chrome) to load pages. Keeps getting the message, resolving hosts. This happens after a reboot/wake from sleep on my pc.

Tried flushing DNS, did nothing. Any clues/solutions?

Thanks!

**Comment by StevenBlack** [comment]
Hi @alphamonkey11 what's your rig (OS, hardware, etc)?

**Comment by dnmTX** [comment]
@alphamonkey11  if you are on Windows see #593 for further help.

**Comment by alphamonkey11** [comment]
Hi @StevenBlack i have a laptop (Dell XPS 9560; 16gb ram, 512 gb ssd, i7 intel processor)

**Comment by dnmTX** [comment]
@StevenBlack  looks like OP here still waiting to for you to perform some miracle disregarding my reference where the issue was identical and solved.I'd say close this.
