### ISSUE TITLE
please remove the panopticlick EFF tracker protection domains unless they're actual trackers

### ISSUE THREAD

**Issue by jawz101** [StevenBlack/hosts#605]
I don't see the point of simply blocking these domains by hardcoding them in a list.
trackersimulator.org
eviltracker.net
do-not-tracker.org

If their purpose is to test certain fingerprinting techniques, why prevent them from doing that?  You're effectively breaking the test of techniques that thousands of actual tracking companies use by blocking these 3 innocuous domains.

I can't find the right words to explain that.

I liken this to cell phone companies overclocking your phone when running benchmark apps.  It helps your brand but we're actually trying to test something specific.

**Comment by StevenBlack** [comment]
@jawz101 all three of these come to us via adaway.org.

Please take up this issue with them, they have an [issues page](https://github.com/AdAway/AdAway/issues).

Closing.

**Comment by jawz101** [comment]
ok.  We'll see how that goes.  Their list hasn't had updates in 2 years https://github.com/AdAway/adaway.github.io/commits/master/hosts.txt
