### ISSUE TITLE
vuuwd.com - cryptominer host

### ISSUE THREAD

**Issue by DavidCWGA** [StevenBlack/hosts#606]
Source: https://arstechnica.com/information-technology/2018/05/hundreds-of-big-name-sites-hacked-converted-into-drive-by-currency-miners/

**Comment by dnmTX** [comment]
Thanks for the info @DavidCWGA 

CC @ZeroDot1

**Comment by ZeroDot1** [comment]
I have added the URL to the CoinBlockerLists 3 days ago, see following update: https://github.com/ZeroDot1/CoinBlockerLists/commit/533e09d380b04009628c50b6e9c20d724189f247

**Comment by DavidCWGA** [comment]
Seems to be irrelevant now. vuuwd.com now resolves to 127.0.0.1 - upstream, not from the dnsbl.

**Comment by dnmTX** [comment]
Yeah,why does it resolves to 127.0.0.1 instead of 0.0.0.0? Is that a bug or something? I can swear i did nslookup on vuuwd.com yesterday and was resolving showing me the real IP,so what changed since  yesterday i wonder?

**Comment by DavidCWGA** [comment]
I don't know what "bug" you would possibly refer to. It was resolving yesterday, but the upstream dns server has changed it to resolve to 127. No great mystery.

**Comment by dnmTX** [comment]
Thanks @DavidCWGA
