### ISSUE TITLE
Remove adf.ly from hosts

### ISSUE THREAD

**Issue by Extamov** [StevenBlack/hosts#607]
adf.ly is a url shortener that has ads, if adf.ly will be blocked, links shortenered with adf.ly will also be blocked.

**Comment by kronflux** [comment]
Agreed, But just to add emphasis and clarity to this, a very large portion of the purpose of this hosts list is to block ads.

adf.ly is NOT a standard url shortener, but rather an advertising redirect site intended to use proceeds from displaying ads to profit those using the service.
(IE: you sign up, you shorten links and provide the shortened link to someone, they click the link and view an ad, a portion of the ad revenue is then given to you)

I would recommend you try to avoid adf.ly links, but if you MUST use them, you have three options:
1) Remove the adf.ly entry from the hosts list manually
2) Use the provided scripts to generate a hosts list, using the whitelist file to add adf.ly
3) Use a 3rd party URL decoder service to convert the adf.ly link to the true URL(there are several out there, trueurl.net is one example)

**Comment by ExtendLord** [comment]
@StevenBlack @kronflux bc.vc is also an advertising redirect site but it is not blocked.
Why's that?
My counter bypasser can't bypass that while it can bypass adf.ly

**Comment by funilrys** [comment]
Well, thanks for pointing our `bc.vc` will be blocked.

**Comment by funilrys** [comment]
@StevenBlack `bc.vc` has been added to Badd-Boyz in order not to be `partial` regarding what @ExtendLord mentioned previously. 

No need to update yet it will be automatically added to the hosts file after PyFunceble finished its tests.

Cheers.
