### ISSUE TITLE
New list

### ISSUE THREAD

**Issue by gmscs** [StevenBlack/hosts#608]
Hi all, I'm working on some lists here https://github.com/gmscs/hosts 
If y'all wanna take a look at them, I hope they'll help somehow. These are websites that are missing from this hosts and its extensions.
If anything needs to be done to them for easier integration please tell me.
I'll be adding to the lists gradually.

**Comment by gmscs** [comment]
I'll commit to it. I'll keep the lists updates and keep adding to them.

**Comment by funilrys** [comment]
@gmscs Are you still into this ?

@StevenBlack  This may be closed as there is no new commit since the day OP started this issue.
