### ISSUE TITLE
rebelmouse.com

### ISSUE THREAD

**Issue by daniel-widrick** [StevenBlack/hosts#609]
Can't see a reason for this service to be blocked. rebelmouse.com

**Comment by StevenBlack** [comment]
@daniel-widrick rebelmouse is blocked by Badd-Boyz-Hosts.

Pinging @mitchellkrogza -- what do you think Mitchell?

**Comment by funilrys** [comment]
Hi @StevenBlack, Mitch is AFK until an undetermined date.

I created an issue so I can look at it asap :+1: 

Cheers and have a nice day/night.
Nissar

**Comment by StevenBlack** [comment]
Thanks Nissar @funilrys.

Closing.
