### ISSUE TITLE
Website inc.com is blocked

### ISSUE THREAD

**Issue by lencc** [StevenBlack/hosts#61]
The content on inc.com doesn't load. I suspect hosts file, because I also tested it with disabled adblocker and Firefox Tracking protection which doesn't help.

The problem is that I manually removed the entry <code>inc.com</code> from my hosts file and website still doesn't load.

**Comment by Laicure** [comment]
Saw the **0.0.0.0 inc.com** entry in the hosts file. Have you tried clearing up the browser cache?

**Comment by lencc** [comment]
Yes, I also cleaned all the history (including flash cookies) and restarted the browser, but unfortunatelly it doesn't help.

**Comment by StevenBlack** [comment]
inc.com is [blocked by yoyo](https://github.com/StevenBlack/hosts/blob/ded40d2fb2b48ee21623271e5272cde104ed5702/data/yoyo.org/hosts#L1589) at line 1589.

**Comment by lencc** [comment]
It must be some additional entry blocking content on the website. When opened, only top navigation bar appears, [as shown here](http://i.imgur.com/JZwCn1O.png).

**Comment by StevenBlack** [comment]
Closing this, not a bug here.
