### ISSUE TITLE
ping.ublock.org - uBlock tracking server

### ISSUE THREAD

**Issue by DavidCWGA** [StevenBlack/hosts#618]
uBlock (not Origin) has added a tracking feature. The server is ping.ublock.org, as can be found in this commit:

https://github.com/uBlockAdmin/uBlock/commit/76b89c0a22d20f3a66d7feab14e024f56ca65539

**Comment by StevenBlack** [comment]
Thanks David @DavidCWGA that's interesting.

**Comment by StevenBlack** [comment]
@DavidCWGA if someone doesn't pick up `ping.ublock.org` then I will.  Nissar @funilrys, is this one for you?

**Comment by funilrys** [comment]
Hi Steven @StevenBlack, I can add it into Badd-Boyz :+1:

**Comment by funilrys** [comment]
This one can be closed Steven @StevenBlack !
