### ISSUE TITLE
Office 365 CPU increase >20% 

### ISSUE THREAD

**Issue by tomakey** [StevenBlack/hosts#621]
Hey - just dropping off a note here as I just figured out why my O365 apps (Outlook. Excel, etc.) is taking up 20~25% for each process for no clear reason. I don't have this issue until I got upgraded to V1803 Build 9126.2152.

Fired up Process Explorer and ntdll.dll!TpReleaseTimer+0ex0 thread is consistently above 20%. Wireshark finally revealed that Outlook (or Excel) is consistently trying to get to:

settings-win.data.microsoft.com
v10.vortex-win.data.microsoft.com
nexus.officeapps.live.com
nexusrules.officeapps.live.com
mobile.pipe.aria.microsoft.com

I had to whitelist the domains above get back to normal CPU level again which is should be at low 0 at idle. 

In case anyone else also blackholing the domains above and O265 running high CPU (at least for build 9126; not sure abt the rest).

**Comment by StevenBlack** [comment]
Thanks @tomakey.  Interesting.

**Comment by tomakey** [comment]
Hey Steve - I believe what I experienced is temporary after the online upgrade. It's likely that O365 needs to make those connections to "finalize" the upgrade (albeit the fact that the apps work normally except the elevated CPU since the upgrade), The fact that I had the domains blocked all along likely prevented it from "completing" the upgrade until I white listed it this morning. I removed them from the whitelist now and things remain normal for now - so I guess those domains are needed somewhat after upgrade.

**Comment by StevenBlack** [comment]
Thanks @tomakey.

Closing.

**Comment by tomakey** [comment]
I can confirm this issue again with Office 365. Just had another release upgrade and any Office apps will take 20%+ until communication to mobile.pipe.aria.microsoft.com is allowed.

**Comment by spirillen** [comment]
https://www.virustotal.com/en/domain/mobile.pipe.aria.microsoft.com/information/

**Comment by dnmTX** [comment]
@tomakey  can you report that issue in [@crazy-max](https://github.com/crazy-max/WindowsSpyBlocker/issues) repo so he can do more testing.Thanks.
