### ISSUE TITLE
Directions for RHEL/CentOS

### ISSUE THREAD

**Issue by nanodeath** [StevenBlack/hosts#622]
According to [this page](https://support.rackspace.com/how-to/centos-hostname-change/) the way to re-read the hosts file on the above OSes is

```
$ sudo /etc/init.d/network restart
```

Can we get this added to the readme?

**Comment by StevenBlack** [comment]
Hi Max @nanodeath, I'd entertain a pull request on [`readme_template.md`](https://github.com/StevenBlack/hosts/blob/master/readme_template.md) for that.

**Comment by ScriptTiger** [comment]
Just to clarify the readme instructions, the main focus of the link you provided is to change the hostname of a device and gives instructions to edit two different files, `/etc/sysconfig/network` and `/etc/hosts`, as well as issue the `hostname` command. It then instructs your given command, `/etc/init.d/network restart`,  to be issued "to ensure that changes will persist on restart," but it's not clear if all of the changes need this command or only one or some of them need it to persist on restart. Have you personally tested this and know the answer to this? For the purposes of the readme, this is only relative if the command is required for the changes in `/etc/hosts` to persist. Again, this is just for clarification so the readme is as clear as possible. Personally I have not heard of a command needing to be issued for file changes to persistent other than a command to save the file, but I am not too savvy at Linux distros.

**Comment by gfyoung** [comment]
@ScriptTiger : The link provided is a bit of a red herring.  The relevant point for this repository is that you need to restart networking to ensure that the `host` file changes are incorporated.

**Comment by gfyoung** [comment]
> I'd entertain a pull request on readme_template.md for that.

@StevenBlack : You would also need to update the Python script to add the command.
