### ISSUE TITLE
Listings for Streaming Domains

### ISSUE THREAD

**Issue by ScriptTiger** [StevenBlack/hosts#624]
It has come to my attention that a good portion of those visiting my website to download various formats of the blacklists are using them in conjunction with remote DNS services, such as Google DNS, Cloudflare DNS, Tor DNS, OpenDNS, DNS over TLS, DNSCrypt, etc. 

What this means is that when they request DNS information, they are getting back results that may not be optimized for their own local areas as far as which servers are closest, and thus the performance of streaming services suffer. 

I realize those doing things like this for security/privacy reasons obviously value security/privacy over performance, but I have started a project to list streaming domains just to give those users an option if they don't mind sacrificing security/privacy for performance for only streaming domains. That way all of their other traffic is secured and private as usual while at the same time their entertainment traffic is optimized, so their ISPs can basically track DNS requests for what they're streaming but not for things that may be of a more sensitive nature.

https://github.com/ScriptTiger/Streamers

This list could also be used for other QoS (quality of service) models should people want to prioritize these domains in their traffic via some kind of traffic shaper, etc., but that's not necessarily relative to this community. But if you happen to have a personal interest in this aspect, that is also a possible use case.

**Comment by StevenBlack** [comment]
Hi @ScriptTiger I hope you don't mind, I added paragraph breaks to your text above ^^^.   One idea per paragraph is easier to [grok](http://www.dictionary.com/browse/grok?s=t) 😉 

Having done that, I'm still unable to identify something actionable here.

What are you suggesting for this hosts repo?

**Comment by ScriptTiger** [comment]
It's more of an RFC for the hosts repo community. Most of the Reddit and assorted forum posts about this topic are people from this community, so I thought I'd just drop this here as a central point of contact. I don't really want to separate audiences since all of the lists and people using them are intimately linked to this repo, and I definitely don't want to steal any credit from you on any of it. It can be deleted shortly, as I know your issues are mounting at present.

**Comment by kronflux** [comment]
Yeah, I'm really not sure what's being implied here per say.
IF streaming services are suffering from use of this block list, they're only suffering from initial requests. Once streaming/playback has begun, there is no loss of performance, as there's no new requests being given which could suffer from delay.

I can say from personal experience that I use both the block list as well as cloudflare DNS(1.1.1.1) and I have yet to experience any noticeable delay on ANY front.

If you're simply saying that DNS requests will not be optimized by area if a user chooses to use a custom DNS server, yeah, that's pretty common knowledge. People who understand WHAT a custom DNS server is also generally also understand that they are choosing it over their ISP's provided DNS server, and understand that there will be some performance CHANGE(not necessarily loss or gain, really depends. Most of the time Google DNS and some of the other more popular ones are FAR faster than the ones provided by ISPs which is actually one of the reasons most people prefer them)

Finally, I'd like to conclude that whatever it is you're saying _exactly_ - it's not relevant to this hosts list at all, and is far more of a general nature(unless of course I'm completely misunderstanding)

I think we can safely close this issue @StevenBlack

**Comment by dnmTX** [comment]
@ScriptTiger  you got me confused here as well man.As @kronflux already mentioned, i'm too using Cloudflare without any noticeable slowdown and the domains that you posted suppose to replace the cloudflare DNS or....? Can you please give better explanation and examples.

**Comment by ScriptTiger** [comment]
Thank you, @kronflux, I can totally see now how that might be confusing. I am not talking about the performance of DNS queries and responses, I am talking about the performance of streaming services. If I request a DNS entry from CloudFlare or Google DNS, yes, they have fast DNS performance, but they are not necessarily giving me the closest servers to my local area, so streaming performance suffers. There are regional DNS servers that provide DNS entries that are optimized for their locations, and using remote DNS does not know your location and cannot optimize for it. @dnmTX, I hope that also addresses your concerns. Let me know if it does.

And just as another point to @kronflux, I would like to be clear that the hosts repo does not in itself in any way impact the performance of streaming services, but this is just addressing related issues a sizable subset of users are having.

As I said, it's more of an RFC and announcement. Judging from @StevenBlack's reply, I think he understands what I am talking about, but I'll be closing it shortly anyway because, as stated, it's not actionable directly to this hosts repo but rather to a subset of the community that uses it.

**Comment by kronflux** [comment]
Ah. Yes, that clears it up completely. Thanks!

That being said, in the future you ought not post unrelated issues in a project just because some people using that project have experienced said unrelated issue. It's absolutely not relevant, and doesn't belong here in the slightest.

Although I appreciate what you were trying to do(Not trying to sound unappreciative or disrespectful), it's just not good GitHub/Development etiquette.

**Comment by StevenBlack** [comment]
Closing.
