### ISSUE TITLE
[redirect/tracking/ads] new domain(s)

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#634]
**click.linksynergy.com**  redirect and most likely tracking as well  so it belongs here

**ogp.me** (Open Graph Protocol) Used to deliver popup ads,wider testing is needed on this one,might break some Facebook functions,already blocked it on my end will update if i notice something weird.
**Update**: Yahoo is using it for ads.....tbc

**ero-advertising.com** domain that delivers ads(porn sites mostly)
_____________________________________________________________________________________________________________
Steven @StevenBlack  let's keep the issue open for now so i can keep adding if any,if there is nothing to add i'll  close it myself.Thank you.

**Comment by dnmTX** [comment]
Steven @StevenBlack is it possible(on your end) when all the hosts lists are arranged into one a line to be inserted at the beginning and the end of each individual lists.For example:
# KADhosts Start
domain.com
domain.com
domain.com
# KADhosts End
It would really help me remove things that i don't need(as we discussed yesterday with you),i managed to do it now but if you change the arrangement it will be a mess on my end

P.S. If it's too much trouble maybe just something to indicate the end will be sufficient also.
P.S.P.S. You didn't answer my question @ZeroDot1's repo,so i'm posting it here 😜

**Comment by StevenBlack** [comment]
@dnmTX sure, we can do that.

Is `# {source name} Start` and `# {source name} End` sufficient for your needs?

Asking because, for parsing purposes, I know that Is `# start {source name}` and `# end {source name}` seems easier.  

Also, I suggest normalizing the case of the `{source name}` to lowercase.

(I wish you had opened a new issue, rather than appending to a non-related issue.  I'll rename this and delete the first comment).

**Comment by dnmTX** [comment]
Steven @StevenBlack  many many thanks(i mean it).Lowercase...uppercase....doesn't really matter,whichever is easiest for you,either way i have to parse the whole thing in order "sed" to recognize it.**THANK YOU**

I realize that lately me opening a "issue" is me being picky,so i just trying not to and looking for a way to fix things on my end(which is also educational).Sorry about that and if you'd like i'll open a issue for this one.

**Comment by StevenBlack** [comment]
Turns out, I can't delete the top level comment to clean up this mess so, yes please, create a new issue.

Closing.
