### ISSUE TITLE
New lists to consider

### ISSUE THREAD

**Issue by lordraiden** [StevenBlack/hosts#636]
New lists to consider

https://www.openphish.com/feed.txt
https://data.phishtank.com/data/online-valid.csv.bz2 (may have false positives)
https://ransomwaretracker.abuse.ch/downloads/TC_C2_DOMBL.txt
https://ransomwaretracker.abuse.ch/downloads/RW_URLBL.txt
https://malc0de.com/bl/BOOT
Princeton - Login manager autofill abuse for tracking: https://gist.githubusercontent.com/BBcan177/b6df57cef74e28d90acf1eec93d62d3b/raw/f0996cf5248657ada2adb396f3636be8716b99eb/MS-4

**Comment by dnmTX** [comment]
http://sysctl.org/cameleon/
