### ISSUE TITLE
[question] KADhosts

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#641]
Steven @StevenBlack  looking at the domain entries in the KADhosts lists probably 85% are Polish. Isn't better if it has own extension,this way anyone in Poland can use it and be more secure and for the rest of us(non Polish residents) have lighter lists.You yourself mentioned that are getting concerned about the size of the hosts file and the number of domains in it.It's more like suggestion then a question and hopefully you'll consider.Other,more useful hosts lists can be substitute (see #636 ) instead,in my opinion.Thanks.

P.S. That lists was last updated on Feb 20......doesn't look like it's been maintained very good....just saying...

**Comment by StevenBlack** [comment]
Hi @dnmTX 

KADHosts has been updated [sixteen times in the past year](https://github.com/StevenBlack/hosts/commits/master/data/KADhosts/hosts).

I have no problem with KADhosts.

Closing.

**Comment by ScriptTiger** [comment]
@dnmTX, it's all about reliability and consistency over time. And personally even if it was 100% Polish, it's still making everyone safer. It would be great if we could have a specialist in every country.

**Comment by dnmTX** [comment]
@ScriptTiger  sure,at this point of view but me not browsing any Polish websites is just extra "weight" in my hosts file.I also realized how wrong i am to ask such a things(very selfish of me) when i can just modify it on my end cause this is something that i don't like,not the whole community here.Already found a solution,just waiting for @StevenBlack  to pull a PR and it will be perfect.Thanks for pitching in though 😋

**Comment by spirillen** [comment]
Polish or not.. I believe it should stay a good blocklist is a good blocklist, then it doesn't matter whether is mostly for one country (Some is actually rather large)

**Comment by dnmTX** [comment]
@spirillen  that issue was resolved on **[JUN 7](#644)**.No further comments are needed.The fuck is wrong with you?
