### ISSUE TITLE
None of the sbc.io mirror links work

### ISSUE THREAD

**Issue by AnielShri** [StevenBlack/hosts#642]
I use the mirror links on [sbc.io](http://sbc.io) to reduce the load to github (and to prevent your account from getting banned due to heavy request), but I noticed that non of the mirrors work. Every single link gives a **500 - Internal server error**. Even the [main site](http://sbc.io) won't load.

Can you check into that?

**Comment by StevenBlack** [comment]
@AnielShri thank you!  Investigating now.

**Comment by StevenBlack** [comment]
This bug report is greatly apprecietes Aniel @AnielShri.

All fixed now!
