### ISSUE TITLE
[change request] hosts lists arrangement

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#644]
Steven @StevenBlack is it possible(on your end) when all the hosts lists are arranged into one a line to be inserted at the beginning and the end of each individual lists.For example:
**# KADhosts Start**
domain.com
domain.com
domain.com
**# KADhosts End**
It would really help me remove things that i don't need(as we discussed yesterday with you: #641),
i managed to do it for now but if you change the arrangement it will be a mess on my end

P.S. If it's too much trouble maybe just something to indicate the end will be sufficient also.

**Comment by funilrys** [comment]
Just let me understand ... You do not use the whitelist system ?

**Comment by dnmTX** [comment]
@funilrys  i use only the ready hosts file from here and fetching it to my router's dnsmasq. If i have to do any modifications on the file i'm doing it with script loaded in my router,it's like portable Linux OS which has limited editing tools.My request here is custom but i'm pretty sure it would benefit others Linux users as well.Hope this answers your question.

**Comment by funilrys** [comment]
Okay understood only have to code that then :joy:

**Comment by dnmTX** [comment]
@funilrys  see #634 he gave some examples there,whatever is the easiest,just something to indicate where the lists starts and where it ends and to be permanent so i don't have to worry that if the arrangement changes i'd wipe out half of the entries there 😦

**Comment by funilrys** [comment]
Understood :+1:

**Comment by dnmTX** [comment]
@funilrys  see #641 as to why(just more info).Also checking on progress,not rushing or anything,juuust checking 😉
