### ISSUE TITLE
[important] CoinBlockerLists new URL's

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#646]
Steven @StevenBlack  @ZeroDot1 just finished with the moving and these are the new URL's:
https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/1

Browser only: https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
More complete one(he recommended it) : https://zerodot1.gitlab.io/CoinBlockerLists/hosts

Godspeed  👍

**Comment by StevenBlack** [comment]
Thanks @dnmTX, done!

**Comment by dnmTX** [comment]
@StevenBlack  i'm not sure that this is a bug but just in case to report it. CoinBlockerLists is merged with another lists (add.2o7Net),no separations,nothing.If it's a bug now you know...otherwise disregard.
 Thank you.

![bug](https://user-images.githubusercontent.com/34774426/41012970-cb38ca84-6909-11e8-9bf3-c496ee613ec7.png)

**Comment by StevenBlack** [comment]
Thanks @dnmTX I'll look into this.

(Laughing) what is it with you, appending unrelated new issues to existing issues (a closed one in this case) two days in a row? 😺

**Comment by dnmTX** [comment]
Sorry..(again)..about that.I wasn't sure that it's actual issue or just me being picky and imagining things.I'll do better....promise.

**Comment by StevenBlack** [comment]
@dnmTX no worries!

**Comment by ScriptTiger** [comment]
@dnmTX, @ZeroDot1, I'm sorry guys, I know this is completely off topic, but this issue is closed and I just had too :P And I provided two links for independent confirmation, you cannot escape Microsoft...
https://www.shodan.io/host/52.167.219.168
https://whatismyipaddress.com/ip/52.167.219.168

**Comment by dnmTX** [comment]
@ScriptTiger  while we are on the subject,here....check the links also:
https://github.com/privacytoolsIO/privacytools.io/issues/478#issuecomment-394891436

NOTE: Don't address ZeroDot1 here anymore,he is gone. Repo is closed.
