### ISSUE TITLE
[Inquiry] Any thoughts moving somewhere else (git)?

### ISSUE THREAD

**Issue by Laicure** [StevenBlack/hosts#647]
Hey @StevenBlack,

Just asking if you have thoughts on _moving somewhere else_ (like Gitlab or such)?
You know, because of this [one](https://blog.github.com/2018-06-04-github-microsoft).

If yes, please keep us posted.
We would like to still keep in touch as usual ♥

(close if dup 🗡)

**Comment by StevenBlack** [comment]
Hi @Laicure this repo is mirrored to Gitlab for now.

For the foreseeable future this repo will stay here.  I'll likely move all my private repos away, but that doesn't affect this repo....  We'll see.
