### ISSUE TITLE
[for contributors] ads domains for consideration

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#649]
Ok,this is what i did.From this link (http://sysctl.org/cameleon/hosts) 
(main site is: http://sysctl.org/cameleon/ ) i downloaded the lists (these are all ads domains) which contains 20567 entries (doesn't look like it's updated very often but most of the domains are active),i compared it to the @StevenBlack 's lists,removed the duplicates and what's left is a 8392 entries(most of them...again...are active).I still want to see how often that list gets updates but i just started tracking it so it would take a while and in the meantime does anyone from the contributors here willing to include and maintain that lists.If you do,please let me know so i don't have to download it every time as a addition to the StevenBlack's one.Thank you all (see attachment)
[ads_domains.txt](https://github.com/StevenBlack/hosts/files/2085728/ads_domains.txt)
#

**Comment by StevenBlack** [comment]
@dnmTX it doesn't seem to have any sort of license.

**Comment by dnmTX** [comment]
@StevenBlack  hmm never thought about that,what would you suggest in this case?

**Comment by StevenBlack** [comment]
@dnmTX I've seen no evidence we need more ad blocking at this juncture... 

I'm referring to http://sysctl.org/cameleon/hosts.  

The one you refer to is, I presume, `ads_domains.txt`?  I don't follow the reference.   I'm having difficulty parsing what you mean.

**Comment by dnmTX** [comment]
That's OK,no need to argue about such a small things.If there is no need for more ad blocking in the present will leave it for another time.
Closing......
