### ISSUE TITLE
"/" intended?

### ISSUE THREAD

**Issue by Laicure** [StevenBlack/hosts#65]
- 127.0.0.1 canuck-method.com/
- 127.0.0.1 www.canuck-method.com/

Saw those from your personal list, I tried opening those on my browser (Chrome) using your latest hosts file and it loaded.
Is it because of the "/"?

**Comment by Laicure** [comment]
Issue addressed: [Twitter Conversation](https://twitter.com/Lychorise/status/696520389933969408)

~Closed.

**Comment by ivso** [comment]
Shouldn't all these be `0.0.0.0` instead of `127.0.0.1`? Great resource, BTW! :+1:

**Comment by FadeMind** [comment]
@ivso script handle this and changing 1`27.0.0.1` to `0.0.0.0` exclude localhost.

**Comment by ivso** [comment]
I use that particular list in my uBlock0 setup, so I wasn't aware of that. Sorry for the chatter, though...
