### ISSUE TITLE
Support custom redirect entries

### ISSUE THREAD

**Issue by kentrogers** [StevenBlack/hosts#653]
I'm interested in forcing Google safe search for my kids' devices, with hosts entries like these:

216.239.38.120	www.google.com
216.239.38.120	encrypted.google.com
216.239.38.119	www.youtube.com
216.239.38.119	m.youtube.com
216.239.38.119	youtubei.googleapis.com
216.239.38.119	youtube.googleapis.com
216.239.38.119	www.youtube-nocookie.com
216.239.38.119	www.googleapis.com
216.239.38.119	googlevideo.com
204.79.197.220	www.bing.com

Would you consider support for a custom redirect list in the Magisk module and Android app, in addition to the whitelist and blacklist option?

**Comment by StevenBlack** [comment]
Hi @kentrogers, if you use [`updateHostsFile.py`](https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py) to generate your own version, you can use the [`myhosts`](https://github.com/StevenBlack/hosts/blob/master/myhosts) file to maintain your own additions to the hosts file.

If you've never used Python this is really easy.  If you have a decent OS then Python comes pre-loaded with the OS.  If you use Windows, you'll have to do the Windows thing and install yourself what the rest of the world has been getting all along.

Does this help?

**Comment by kentrogers** [comment]
I haven't used Python. But it doesn't look like that method is currently possible while using the Magisk module on Android. At least, I didn't see "myhosts" in the Magisk zip. However, it looks like modifying the system/bin/hosts file might allow for the addition of a "redirect" file to be merged into the hosts file along with the usual blacklist and whitelist.

**Comment by StevenBlack** [comment]
@kentrogers this repo is all about a maintaining and generating amalgamated hosts files.  What you're talking about is downstream from us, and therefore out of scope for this repo.

Thanks for stopping by.

Closing.
