### ISSUE TITLE
Hostsman Problems...

### ISSUE THREAD

**Issue by glimmerwell** [StevenBlack/hosts#654]
Hi, I've been using Hostsman for several years. I started using the StevenBlack list (non-Github mirror). It worked great. However; recently I noticed that Hostsman's built in editor can't "see" the StevenBlack hosts file or count how many entries it has (it used to work fine. Now is says Hostsnames: 0, File Size: 1.61k ). 

Using the regular text editor it appears Hostsman IS actually still updating the file, though.

I was able to test a different hosts file and Hostsman worked fine. The editor showed the whole file and the count was correct. So it appears there is a specific issue with this StevenBlack file.

1) Does anyone know of a reason for this or have a fix so I can continue using Hostsman?

2) Also, I notice that the Hostsman version I have and the one that is listed on their site is v4.7.105, but when you download it you get version HostsMan_4.8.106_installer. I emailed them but got no reply. Could Hostsman be abandonware? Their forum appears to be gone. Does anyone know if that "unofficial" version is ok to use? It checks out with VirusTotal (0/66).

3) Perhaps more importantly, what is the recommended way/software for updating the hosts file that allows easy checking to make sure it works, and easy on/off for testing when something doesn't work right? I am looking for something ideally that is actively supported.

Thanks!

**Comment by StevenBlack** [comment]
Hi @glimmerwell, the non-Github mirrors, which we maintain especially for Hostman, are working correctly.  Sorry Hostman's not working for you, but there's nothing we can do,  Maybe you should switch to something else?

Closing.

**Comment by ScriptTiger** [comment]
@glimmerwell, as everyone basically suggests, Hostsman is known to have many issues with it and @StevenBlack is justifiably tired of taking support requests for it as it's not related to this repo. As @dnmTX suggested, you can check out my AutoUpdate script for Windows or you can try any of the blacklists from the links below, which are all routinely synced with this repo.

Regular list, with some tweaks:
https://scripttiger.github.io/hosts-packages/

Alternatively formatted lists:
https://scripttiger.github.io/alts/
