### ISSUE TITLE
Unified hosts adblocker block navigation of news and social apps

### ISSUE THREAD

**Issue by davidzam12** [StevenBlack/hosts#656]
First, thank you for your work. I'm here to report a bug. So far, the fallowing apps get completely blocked fro the net. Oficial Twitter app, al Jazeera, messenger from Facebook, also backup process from What's app doesn't work when hosts module is activayed, the thing is that this blocking happen randomly, after deactivating the systemless hosts on magisk module all come back to normal, after rebooting the device. Also The guardian app it's unable to download news to be read off line when unified it's active. The issues come and go, its random, sometimes the apps work, sometimes just one breaks, but suddenly, another does it,app stops connection to the net. I've activated all the hosts aviable on the module, in using 6.0.1 under Magisk v16. Thanks

**Comment by StevenBlack** [comment]
Hi @davidzam12 I don't know what to say.  I need specifics about which domains are required by specific apps.  

This issue isn't actionable because it's too vague and non-specific.

If you have details about specific domains required to run specific apps, then I'm very interested.

Closing.

**Comment by davidzam12** [comment]
I'll look into it. As I said. It's random, sometimes work fine and the,
connection it's gone. I'll do some research when I have te time.

**Comment by StevenBlack** [comment]
Thanks for the heads-up @jawz101.  This is fixed in commit 26d027d.

**Comment by jawz101** [comment]
That may also close https://github.com/StevenBlack/hosts/issues/496, btw

**Comment by StevenBlack** [comment]
@jawz101 oh, thanks for that, good eye.  Issue #496 is now closed.

**Comment by davidzam12** [comment]
I use it in some. But the issue it's bigger. I put Instagram, Facebook and
Twitter on the regex white list. They appear to be working, the apps a
mean. But Twitter it's not showing any banner or image link or tweets with
images or videos embedded in them. Instagram was not giving any trouble,
but when I whitelisted Twitter, Instagram stopped working. So Facebook...
Something it's wrong with the hosts list I guess... It's a pity... Also if
I knew what to research or a bit more about this... But I don't. I'll just
deactivate social host... Until an update is reach on this matter that can
fix this.

**Comment by dnmTX** [comment]
@davidzam12  the social media lists is meant to block the entire domain not just parts of it,don't think that it will just block ads and tracking(if any).It will block everything.Just FYI.

**Comment by jawz101** [comment]
@davidzam what ad blocker are you using?

Adaway, netguard, and blokada should all have options to either log DNS queries, blocked queries, or notify you when they happen depending on which you use.

You may try messing with one of those apps to narrow down which domain causes your problems and test it with and without adding it to your ad blocker's whitelist.
