### ISSUE TITLE
.gitignore is toothless

### ISSUE THREAD

**Issue by matkoniecz** [StevenBlack/hosts#660]
```
myhosts
blacklist
whitelist
readmeData.json
hosts
hosts-*
```

are in repo, what means that .gitignore has no effect and is merely confusing - modifications to this files are still displayed by git

See https://stackoverflow.com/a/7072230/4130619 and https://stackoverflow.com/a/40272289/4130619 for some potential options

see https://github.com/StevenBlack/hosts/commits/master/.gitignore

As workaround everybody may run `git update-index --skip-worktree readmeData.json` etc.

**Comment by StevenBlack** [comment]
Closing.

**Comment by matkoniecz** [comment]
What was the reason for closing? From what I see it remains unfixed.

**Comment by funilrys** [comment]
@matkoniecz should be fixed by #736 if I understood correctly.

**Comment by matkoniecz** [comment]
hosts file is still both in repository (see https://github.com/StevenBlack/hosts ) and .gitignore ( https://github.com/StevenBlack/hosts/blob/f5d1d3b4ebee782683d7a944e16f35ff0fa3b1ca/.gitignore )

**Comment by funilrys** [comment]
Oh now I understand why he closed this ... This is issue will not be fixed soon ...

**Comment by funilrys** [comment]
You're talking about the hosts file. So this issue will actualy never be fixed because we actually distribute that host file...

**Comment by matkoniecz** [comment]
Then why it is in the `.gitignore` file? Fix would be simple, remove that line in the `.gitignore`

**Comment by funilrys** [comment]
@matkoniecz PR are welcome as you know!

**Comment by forthrin** [comment]
I didn't quite understand: Why are the following files not in `.gitignore`?

```
hosts
readmeData.json
data/.../hosts
extensions/.../hosts
```

They seem to be changed by `makeHosts` or `updateHosts`, but are they **also** distributed by `git pull`? Shouldn't it be one or the other? If not, how do I prevent getting a constantly soiled working tree?

**Comment by matkoniecz** [comment]
> They seem to be changed by makeHosts or updateHosts, but are they also distributed by git pull? Shouldn't it be one or the other?

I agree, though this is a different issue to this one.

Currently this repository contains constantly regenerated files and there is no way to avoid

> constantly soiled working tree

https://github.com/Jahhein/hosts/commit/09c4d9d24ce0188e2a5f34da66f75a9777046509 merely removed gitignore line that had no effect whatsoever (as file was checked in) so it was not caused by my PR.

**Comment by forthrin** [comment]
What I currently do to update the code and the sources, is:

```
$ git reset --hard
$ git pull --rebase
$ python3 updateHostsFile.py
```

1. Is this the best/recommended day-to-day practice, as long as things are the way that they are?

2. Wouldn't it be better to either a) **only** distribute source changes through Git and remove the possibility for updating locally, or b) **don't** distribute through Git and let people update locally? 

It would be interesting to hear the reason for this Winnie-the-Pooh approach, with its disadvantages.

**Comment by matkoniecz** [comment]
> remove the possibility for updating locally

What is the benefit of that? If someone prefers to avoid doing that - noone is forcing them?

Also, it is impossible without removal of source code from repo.

**Comment by forthrin** [comment]
What are the optimal CLI commands to keep the code and sources up-to-date on a day-to-day basis?
