### ISSUE TITLE
epicgames domain blocked by accident?

### ISSUE THREAD

**Issue by v-tron** [StevenBlack/hosts#661]
Not sure if this is intentional but the domain "eulatracking-public-service-prod06.ol.epicgames.com" is on the malware/adware list (must be relatively new, this only caused issues today) and with it blocked, Fortnite does not start. It definitely is not Malware or Adware. Suspect a false positive here.

**Comment by v-tron** [comment]
"metric-public-service-prod.ol.epicgames.com" is probaly also a false positive. This one does not cause issues yet, though.

**Comment by dnmTX** [comment]
CC @lightswitch05

**Comment by lightswitch05** [comment]
Removed, I guess I had already launched the game when I had tested this before. Sorry about that!

**Comment by v-tron** [comment]
No sweat, your lightning fast response makes up for it ;)

**Comment by StevenBlack** [comment]
...and this is now live and online in [Release 1.4.23](https://github.com/StevenBlack/hosts/releases/tag/v1.4.23).
