### ISSUE TITLE
[ero-advertising.com] more comprehensive lists

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#663]
@StevenBlack  did some research and found more sub domains that can be added to your lists(see attachment).Duplicates are removed,0.0.0.0 added(ready to go).If you think it's not needed you can close the issue.Thanks.
[ero-advertising.txt](https://github.com/StevenBlack/hosts/files/2107877/ero-advertising.txt)

If you ask me about license,there isn't one.Or i can paste them all 219 here and avoid that license confusion,up to you.

**Comment by StevenBlack** [comment]
Done!  Thanks @dnmTX.
