### ISSUE TITLE
[exoclick.com] 3 more to add

### ISSUE THREAD

**Issue by dnmTX** [StevenBlack/hosts#664]
@StevenBlack found 3 more sub domains(active).You can add them in the next release.Thank you.

secure.exoclick.com
syndication-evo.exoclick.com
www.exoclick.com

**Comment by funilrys** [comment]
@dnmTX please send a PR.

**Comment by dnmTX** [comment]
@funilrys  very embarrassed to say ti but i .....don't really know how to do it.........(don't judge....please)

**Comment by anudeepND** [comment]
@dnmTX @funilrys PR you say?

**Comment by funilrys** [comment]
@anudeepND Good but it'll be better to let newcomer learn about Git and its features in the future.

**Comment by anudeepND** [comment]
@funilrys sorry about that.....
@dnmTX take your time to read the articles provided by @funilrys, I will close this PR now. Go ahead and make your first contribution! :)

**Comment by dnmTX** [comment]
@funilrys  @anudeepND  where is that article?
