### ISSUE TITLE
DNS Rebinding

### ISSUE THREAD

**Issue by ScriptTiger** [StevenBlack/hosts#676]
DNS rebinding may be an attack type better suited to be detected and stopped by a different method, but I was curious if it would be possible to prevent it with this repo, as well. Obviously the nature of DNS rebinding would lend itself to a whole host of new bogus domains that may stretch the limits of what the purpose of this streamlined repo is for, but I was wondering if anyone had any other ideas around this. Would a streamlined and consolidated list be possible?

https://medium.com/@brannondorsey/attacking-private-networks-from-the-internet-with-dns-rebinding-ea7098a2d325

**Comment by CHEF-KOCH** [comment]
Every modern router firmware provides dos and dns rebind protection, to name some:
* Asus (merlin firmware)
* Fritz Box (official + freetz firmware)
* LEDGE (now again OpenWRT)
* Modded Tomato firmware

No a HOSTS list is not effective here. An example is given [here](https://github.com/mpgn/ByP-SOP).
