### ISSUE TITLE
Questions about hosts file

### ISSUE THREAD

**Issue by DBtn3PUSrL7jRRRf** [StevenBlack/hosts#685]
Hello, I have some question about your host files :

1) Why do you use all the subdomain of a website instead of just "*.website.ext"?
Exemple : 
Why do you use : 
0.0.0.0 ae0.bb01.ams2.tfbnw.net
0.0.0.0 ae0.bb01.atl1.tfbnw.net
0.0.0.0 ae0.bb01.bos2.tfbnw.net
(and hundreds more)

Instead of "*.tfbnw.net"

It should work the same no ?

2) Why do use the domains instead of the IP addresses ?
IP addresses will usually block the whole website (so no need for sub domains like in "1)"), so what the point of using domain name instead of IP addresses ? If it's because IP addresses can be changed... I can just say that domain names can too.

Thanks for you help, I really need to understand that.

By the way I really would like to thank you for creating these hosts files, this is the best thing I ever saw in github, thanks a lot for your work.

**Comment by ScriptTiger** [comment]
> By the way I really would like to thank you for creating these hosts files, this is the best thing I ever saw in github, thanks a lot for your work.

Lol, you like it so much, a repo that's sole purpose is to create a hosts file, that you made an entire issue to explain how you don't understand what a hosts file is or why the format is the way it is. Before you get blocked for trolling, I'll just save you the trouble googling the Wikipedia entry on hosts files:
https://en.wikipedia.org/wiki/Hosts_(file)

**Comment by StevenBlack** [comment]
Hi DB @DBtn3PUSrL7jRRRf thank you for your question.

The hosts file system doesn't support wildcards.  Maybe some day it will.
