### ISSUE TITLE
Blocking Weather Underground overlays

### ISSUE THREAD

**Issue by phaz** [StevenBlack/hosts#686]
Noticed an issue in the app Weather by Weather Underground. The overlay showing US weather fronts is blocked when using this hosts file. Has been happening for some time now. Just getting around to reporting now. Thanx

**Comment by StevenBlack** [comment]
Hi @phaz.  Do you know, which domains need to be unblocked here?

Can't fix without this info...

**Comment by phaz** [comment]
Wish I knew. I tried removing anything to do with wu, and others, to no avail. Tried looking on the wu site for them, no go. Even looked at the wu apis for info, also no go.

**Comment by jancm** [comment]
Looks like you need to whitelist both:
tessera.intellicast.com
tessera1.intellicast.com

In the process of researching this I think I found a few more that can get blacklisted (not really vetted though)
media.lowermybills.com
a1899.casalemedia.com
cdn3.doubleverify.com
tps11035.doubleverify.com

**Comment by StevenBlack** [comment]
Daniel @lightswitch05 why are we blocking Intellicast?

```
data/lightswitch05/hosts
4751:0.0.0.0 intellicast.com
4752:0.0.0.0 mobile-services.intellicast.com
4753:0.0.0.0 tessera.intellicast.com
4754:0.0.0.0 tessera1.intellicast.com
4755:0.0.0.0 tessera2.intellicast.com
```

Take note: `ads.intellicast.com` is already blocked by yoyo.org.

**Comment by lightswitch05** [comment]
I use Weather Underground app and those blocks did't seem to be causing me any issues, but I removed them anyways lightswitch05@e07dfe57e9029d677e5f778f98d1acc4603734fb

**Comment by lightswitch05** [comment]
btw, I found out that `ntellicast.com` is a pretty nasty domain while trying this one out

**Comment by phaz** [comment]
Tessera.whatever was it. Thanx for the help on this. I guess this can be closed.
