### ISSUE TITLE
Block adult sites (Lots of Hentai) updated 28/06/2018

### ISSUE THREAD

**Issue by Danilopereira82** [StevenBlack/hosts#689]
https://beta.sankakucomplex.com
https://chan.sankakucomplex.com
https://luscious.net
https://baixarhentai.net
https://leitura.baixarhentai.net (from the site above, if you trying to access will give 403 error, because it is only for the site files, like https://leitura.baixarhentai.net/read/trap_me_mama/pt-br/0/1/page/1)
https://e-hentai.org
http://rule34.paheal.net
https://rule34.xxx
https://e621.net
https://xbooru.com
http://www.hentaiseason.com
http://www.shadbase.com (hentai for pedophiles)
https://seasonhentaigallery.blogspot.com
http://thehentaicomics.com
https://www.tufos.com.br (please block this site, i hate this)
https://myhentaicomics.com
https://mymangacomics.com
https://myhentaimovie.com
http://myhentaiheaven.net
https://myrule34.com
http://hentaihaven.org
https://www.hentaistube.com
https://www.hentaisonlinehd.com
https://www.superhq.net
https://www.aniporn.net
https://hentaisgerais.blogspot.com (the first hentai site that I have accessed in my life)
https://gelbooru.com
http://hentai4manga.com
http://justicehentai.com/
http://www.doujinlife.com
http://hentai.animestigma.com/
http://hentaigasm.com
http://hentaischool.com
https://hentaifreak.org
https://101hentai.com
http://www.tubehentai.com
https://www.hentaicloud.com
https://myhentai.tv
https://muchohentai.com
http://hentai.animeholics.org
http://www.24hentai.com
http://hentaigaze.com ( Erro 502 but i think this site will be up soon)
http://hentaipulse.com
http://www.hentairon.net
http://www.comicxx.com
https://brasilhentai.com
http://javfor.me
https://idol.sankakucomplex.com
https://masturbese.com
https://sobrasileiras.com
https://www.boafoda.com
https://javfind.com
https://javfinder.is
http://javdub.com
http://javmovie.com/
https://www.javqd.com
https://www.javwhores.com
http://www.javmimi.com
http://sextop.net
http://jav.kim
https://jav.one
https://jav.guru
http://www.r18.com
https://hentaitokyo.com
http://javseen.com
http://javsexmovie.com
https://www.javdoe.com
http://javhihi.com
http://javporn.video
http://www.hq-jav.com
https://www.javwide.com
http://jphub.net
http://porn68jav.com
http://jav789.com
http://jav.sex
https://avgle.com

**Comment by StevenBlack** [comment]
Thanks @Danilopereira82.  Ping @sinfonietta.
