### ISSUE TITLE
Malwarebytes telemetry

### ISSUE THREAD

**Issue by anudeepND** [StevenBlack/hosts#692]
Hey @StevenBlack `telemetry.malwarebytes.com` is not included in the list, can you please add it?

**Comment by StevenBlack** [comment]
Sorry @anudeepND that's vague and non-specific.

Please explain.

**Comment by anudeepND** [comment]
Sorry @StevenBlack. I'm using [Malwarebytes Anti-malware](https://www.malwarebytes.com/) software, this domain shows up whenever I run the program. I had this domain in my black list for a few days, so far so good.
And program updates and definition updates are unaffected. Hope this helps :)

**Comment by StevenBlack** [comment]
@anudeepND  that's not really much clearer :-).

You say, `telemetry.malwarebytes.com is not included in the list`.  What list?

**Comment by anudeepND** [comment]
Oops... This one
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by StevenBlack** [comment]
One of our curators will eventually do it.  Closing.

**Comment by lightswitch05** [comment]
I run malwarebytes occasionally. Looks like another list I use already had it blocked, but I'm happy to add it to my own list. It will be in my next update 👍

**Comment by StevenBlack** [comment]
Thanks Daniel @lightswitch05.
