### ISSUE TITLE
Cannot use the hosts provided to block websites and ads in Windows 10 Pro 1803

### ISSUE THREAD

**Issue by lenkarin** [StevenBlack/hosts#693]
Has 2 months that I'm facing a trouble with the hosts files, that cannot be blocked in Windows 10 Pro 1803. I don't know why I can't use these hosts to block the websites, I was thinking that are the Kaspersky Total Security that was the problem, but it seems that is something in windows. Can you guys help me?

**Comment by xetorixik** [comment]
What have you tried already, and what went wrong?
Without specific information it is difficult to give a targeted solution.

In general, you might have a look at https://github.com/pi-hole/pi-hole

**Comment by lenkarin** [comment]
I just copy the hosts from Steven Black hosts and paste in the notepad and save , and them use the command in CMD ipconfig /flushdns and restart the computer and I can still access websites that in Steven black hosts block

**Comment by lenkarin** [comment]
I just find what is the problem, was Kaspersky Total Security, what I have to do was format my computer and make sure that has an exclusion in Kaspersky before paste the Steven Black Hosts to C:\Windows\System32\drivers\etc . After make an exclusion to the hosts file, I was able to block everything and all the annoying ads, before format the computer Kaspersky detect the hosts file has a virus so just make the file doesn't work properly and that's why are not allowing block the ads and the websites, so now everything works fine.
