### ISSUE TITLE
Blocking TVPage videos

### ISSUE THREAD

**Issue by anudeepND** [StevenBlack/hosts#699]
About TVpage company.

>TVPage, Inc. develops a cloud based video platform for merchants, brands, retailers, media companies, and content creators. Its platform enables retailers to upload and manage videos, and discovers new and earned content from users, influencers, and brands; generates commerce metadata for every video; matches products to videos and recommend the right products to promote with each video; and allows retailers to serve top-converting videos on any page of their sites with embeddable widgets and players. The company’s platform also enables media companies to deliver native and engaging video content to their audiences; sources video assets with integrated product associations and calls to action; serves video content by paid placement, performance, context, and audience data; and generates embeddable widgets and pages. TVPage, Inc. was incorporated in 2010 and is based in San Diego, California with an additional location in New York, New York.

In short, its a monetization service which can be used to embed videos into wepage. So my question is, do we need to block these domains?

Here's an example, www.bleepingcomputer.com

**With TVPage:**

![with](https://user-images.githubusercontent.com/26179946/42147032-3fcf2bba-7de9-11e8-9dcb-661d0783af20.JPG)

**Without TVPage:**

![without](https://user-images.githubusercontent.com/26179946/42147046-52a48d16-7de9-11e8-874c-dbb4e82307a1.JPG)

@ScriptTiger @dnmTX @xetorixik what do you guys think?

@StevenBlack If you approve this, I can create a PR :)

**Comment by StevenBlack** [comment]
@anudeepND this looks like adware to me.

**Comment by anudeepND** [comment]
@StevenBlack I don't think so, it appears on my mobile too. I successfully removed it by blocking few TVPage domains. And these domains are not present in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts.

**Comment by StevenBlack** [comment]
@anudeepND I’m sorry I may be misunderstanding you.

Are you saying this is not adware?  If it’s not adware, then what is it, in your view?  Why does visibility on mobile change this assessment?  Help me understand?

**Comment by anudeepND** [comment]
@StevenBlack TVPage is a advert service, it recommends videos on a webpage, so it does falls under the category of ads. If you look at the above screenshots, those videos on the right side is not relevant to the article, it's just a bunch of video ads...
