### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by khalyk** [StevenBlack/hosts#700]
Error in updating source:  https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Dead/hosts
Traceback (most recent call last):
  File "hosts/updateHostsFile.py", line 1513, in <module>
    main()
  File "hosts/updateHostsFile.py", line 168, in main
    update_all_sources(source_data_filename, settings["hostfilename"])
  File "hosts/updateHostsFile.py", line 595, in update_all_sources
    update_data = json.load(update_file)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 27: ordinal not in range(128)

Dockerfile attached.

`
docker run -it <image_id> /usr/bin/python3 hosts/updateHostsFile.py --auto --extensions social porn fakenews gambling
`

[Dockerfile.txt](https://github.com/StevenBlack/hosts/files/2156654/Dockerfile.txt)

Thanks!!

**Comment by StevenBlack** [comment]
Hi @khalyk what version of Python are you using?

**Comment by khalyk** [comment]
Hey @StevenBlack this is on Ubuntu and python3 (3.6.5-3).

Thanks!

**Comment by StevenBlack** [comment]
@khalyk is [this comment](https://github.com/StevenBlack/hosts/pull/670#issuecomment-398176613) helpful in your case?

![2018-07-02_20-12-15](https://user-images.githubusercontent.com/80144/42192042-48a55926-7e34-11e8-9b58-6d77159f746a.jpg)

**Comment by khalyk** [comment]
Thanks @StevenBlack I will add the above to the container environment and give it a try.

**Comment by funilrys** [comment]
This one is weird everything return error but still have 71 000 entries :thinking:

**Comment by funilrys** [comment]
Wait... @khalyk it's python 3.6.5 !? :scream:

**Comment by real-t0mg** [comment]
hi, 

same error happens in python  2.7.12 in Ubuntu 16.04.4 LTS and in Python 2.7.15 in Slackware 14.2, with C.UTF-8 locales and any other locale you set. 

Slackware: 

Traceback (most recent call last):
  File "updateHostsFile.py", line 1513, in <module>
    main()
  File "updateHostsFile.py", line 187, in main
    merge_file = create_initial_file()
  File "updateHostsFile.py", line 640, in create_initial_file
    write_data(merge_file, start + curFile.read() + end)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 19824: ordinal not in range(128)
Failed to update hosts file

Ubuntu: 

Failed to update hosts file
Traceback (most recent call last):
  File "updateHostsFile.py", line 1513, in <module>
    main()
  File "updateHostsFile.py", line 187, in main
    merge_file = create_initial_file()
  File "updateHostsFile.py", line 640, in create_initial_file
    write_data(merge_file, start + curFile.read() + end)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19824: ordinal not in range(128)
Failed to update hosts file

**Comment by funilrys** [comment]
What about using Python 3 @real-t0mg ?

**Comment by iharosi** [comment]
Experiencing the same on macOS High Sierra 10.13.6 with python version 2.7.10.

**Comment by lightswitch05** [comment]
Maybe time to drop support for Python 2 in this project? The [countdown](https://pythonclock.org/) has already begun, and it will also fix the failing travis-ci tests

**Comment by StevenBlack** [comment]
Yes, Daniel @lightswitch05, I think it's time to drop Python 2.7 support.

**Comment by anudeepND** [comment]
@StevenBlack @lightswitch05 I agree

![55cfce1](https://user-images.githubusercontent.com/26179946/43274390-b3918a3e-911c-11e8-880e-b5f3d3f66ee6.jpg)

**Comment by dohpaz42** [comment]
For those who are stuck using python 2.7 for any reason, you can [add the following two lines](https://stackoverflow.com/a/21190382) (right below the list of imports) to `updateHostsFile.py` to work around the above error:

```python
reload(sys)
sys.setdefaultencoding('utf8')
```

**Comment by funilrys** [comment]
Hello there, 

we are dropping Python 2 soon so please report to #729 and #769.

About this issue the comment of Steve @StevenBlack https://github.com/StevenBlack/hosts/issues/700#issuecomment-401974478 is clear and works as tested by many Python 2 users ...

Steve @StevenBlack Maybe it's time to close this and invite the Python 2 users to update their Python version or follow the discussion at #670 if they don't want to ...

**Comment by StevenBlack** [comment]
Thanks @dohpaz42.  I agree, @funilrys.

Closing.

**Comment by dohpaz42** [comment]
@funilrys I understand; I meant that to be for future users to find. Thank you though. :)
