### ISSUE TITLE
tealiumiq is needed for evernote.com

### ISSUE THREAD

**Issue by knbknb** [StevenBlack/hosts#703]
I have commented out line 19639 (in v1.4.33 of  Date: July 04 2018)
to make the "Evernote Web Clipper" browser extension (for Firefox v60.0.2)  work again.

    #0.0.0.0 collect.tealiumiq.com

Without this host, the Evernote login page does not display a textfield with the password box. The login page just hangs and then shows "Internal Error".

There are a couple of extra lines in the hosts file that I didn't comment out

    19640:0.0.0.0 collect-us-east-1.tealiumiq.com
    24342:0.0.0.0 tealium.hs.llnwd.net

Maybe this helps someone who experiences the same  issue. (no real action required here)

**Comment by StevenBlack** [comment]
Thanks Knut @knbknb.  Good catch.

**Comment by StevenBlack** [comment]
Knut @knbknb currently two of our hosts data sources flag `collect.tealiumiq.com`.  So getting this rectified could take awhile.

**Comment by funilrys** [comment]
Sorry for the (late or unneeded) comment but we may put `mvps.org` and @FadeMind :smile_cat: 

# Occurrences of `collect.tealiumiq.com`

```
./data/mvps.org/hosts <== Entry point
./data/add.Risk/hosts <== Entry point
./alternates/fakenews-porn/hosts
./alternates/fakenews-gambling/hosts
./alternates/social/hosts
./alternates/gambling/hosts
./alternates/fakenews-social/hosts
./alternates/porn-social/hosts
./alternates/gambling-porn/hosts
./alternates/fakenews-gambling-porn-social/hosts
./alternates/fakenews-gambling-porn/hosts
./alternates/porn/hosts
./alternates/fakenews/hosts
./alternates/gambling-porn-social/hosts
./alternates/fakenews-porn-social/hosts
./alternates/gambling-social/hosts
./alternates/fakenews-gambling-social/hosts
```

**Comment by FadeMind** [comment]
@StevenBlack  @funilrys  @knbknb resolved on my side.
