### ISSUE TITLE
Can I use this in AdAway?

### ISSUE THREAD

**Issue by erkin98** [StevenBlack/hosts#704]

**Comment by anudeepND** [comment]
Yes you can. It's already mentioned in adaway repo.
https://github.com/AdAway/AdAway/wiki/HostsSources

**Comment by erkin98** [comment]
But it look not available

**Comment by StevenBlack** [comment]
Thanks for responding @anudeepND.  You good, @erkin98?  We've been with AdAway for awhile...

Closing.
