### ISSUE TITLE
ravenjs cdn blocked by https://github.com/lightswitch05/hosts

### ISSUE THREAD

**Issue by Deprofets** [StevenBlack/hosts#705]
remove the whole list, most likely it's full of false positives.

**Comment by lightswitch05** [comment]
@Deprofets if you have issues with my list, you are welcome to [open a ticket](https://github.com/lightswitch05/hosts/issues). In fact, there is even link to it in the readme. This is a very active project and I don't want to add to the noise.

If you are interested in my opinion on ravenjs, you can read a conversation about it here: https://github.com/lightswitch05/hosts/commit/6a256c58cc46b43e5961373c3e5640743c178932#commitcomment-29581997

And related ticket: https://github.com/getsentry/sentry/issues/8918

I hope that clears things up :1+:

**Comment by StevenBlack** [comment]
@Deprofets Daniel @lightswitch05 has steered this to the right place, so I'm closing this now.
