### ISSUE TITLE
tensorcharts.com renders a blank page

### ISSUE THREAD

**Issue by Deprofets** [StevenBlack/hosts#706]
The issue stems from a recent update to the website that includes ravenjs library which is blocked due to tracking reasons.

if you're having issues with this site just comment line 58157

`#0.0.0.0 cdn.ravenjs.com`

See:
- https://github.com/StevenBlack/hosts/issues/705
- https://github.com/lightswitch05/hosts/commit/6a256c58cc46b43e5961373c3e5640743c178932#commitcomment-29581997

related:
- https://github.com/getsentry/sentry/issues/8918

Note:
I previously proposed the removal of @lightswitch05's hosts file because the blocked content does not serve ads, however ad blocking is not the sole purpose of this hosts file.

**Comment by lightswitch05** [comment]
![screen shot 2018-07-06 at 1 20 11 pm](https://user-images.githubusercontent.com/598803/42392037-e74e5be0-8140-11e8-81da-9333318dd4d5.png)

**Comment by lightswitch05** [comment]
@Deprofets you are still welcome to open tickets involving my list on my project page
