### ISSUE TITLE
Pingdom

### ISSUE THREAD

**Issue by angaron** [StevenBlack/hosts#707]
Hi, 

Is there any argument to block pingdom.com tools domains in hosts? 

```
0.0.0.0 fpt-api.pingdom.com
0.0.0.0 tools.pingdom.com
```

**Comment by lightswitch05** [comment]
I blocked those 9 days ago in this commit: lightswitch05@abdebb894e5e9e075dbaf02df3012401b179477d

I'm confused by the question. Are you asking them to be blocked, or are you asking why they are blocked?

**Comment by angaron** [comment]
Sorry, I'm asking why they are blocked.

**Comment by lightswitch05** [comment]
@angaron looks like `tools.pingdom.com` could be removed. Is leaving `fpt-api.pingdom.com` blocked causing you problems?

**Comment by angaron** [comment]
@lightswitch05 `tools.pingdom.com` will not work without `fpt-api.pingdom.com`.

**Comment by StevenBlack** [comment]
Closing!
