### ISSUE TITLE
ipinfo.io needed for ipinfo

### ISSUE THREAD

**Issue by spookykidmm** [StevenBlack/hosts#708]
ipinfo.io is a website to get, well, my ip info, mostly from the terminal. Not sure why it's being blocked.  Do other websites use it for tracking?

**Comment by lightswitch05** [comment]
Yes I've seen websites using it for geo-targeting. I can remove it if it's a big deal. Would this site not be easier to parse from the command line? http://checkip.dyndns.org/

**Comment by funilrys** [comment]
@lightswitch05 it does not beat `curl ipinfo.io` :smile_cat:

**Comment by lightswitch05** [comment]
removed in lightswitch05@6a4a43ea2f71943800f4217e75045583bcab505f

**Comment by funilrys** [comment]
@spookykidmm please close!
