### ISSUE TITLE
Minimal Python 2 version?

### ISSUE THREAD

**Issue by esparta** [StevenBlack/hosts#71]
I'd like to contribute to this project but have a question on what's the minimal version of Python are you supporting?

Seeing the code I can assume should be 2.6 because of the use of `"".format(...)`, and I'm thinking that with small changes can be lowered down to at least 2.4

BTW, I also would like to thank you not only for this, but also for all your previous work on the VFP community.

**Comment by esparta** [comment]
My suggestion is stick on Python 2.6 to use all the modern things like string.format(), and the with statements.

**Comment by StevenBlack** [comment]
Hi @esparta!  Thanks for those kind words.  

As we move forward supporting two versions is increasingly painful.   I could use some occasional help keeping the 2.x version alive with testing, and insight.

For Python 2.x I'm running Python 2.7.9 presently.  Any objection to this being the minimal Python 2 version?

**Comment by esparta** [comment]
I my opinion Python 2.7.x as minimal supported version is really good point, the differences on the micro versions (2.7.0 to 2.7.10 currently) shouldn't be a problem on what is currently done or will be used on the near future.

I also have other assumptions I'm seeing within the code:
- No external packages in order to minimize impact for final users.
- a single file to execute

Are these correct?

Here are some points I'd like to contribute:
- (kind-of) modernize and standardize  the code (move to classes, remove globals, etc, )
- unit testing
- once having unit test, a CI with travis or similar can be archived easily

**Comment by StevenBlack** [comment]
@esparta if you could make or suggest changes to `updateHostsFile.py` along those lines, that would be fantastic.

**Comment by StevenBlack** [comment]
Closing this now.
