### ISSUE TITLE
New suggestions

### ISSUE THREAD

**Issue by vitor251093** [StevenBlack/hosts#712]
I was blocking domains to my /etc/hosts file before discovering about this list. I've added it to my /etc/hosts file, but there were some in my list that aren't present in the actual adware+malware list. The hosts below are most probably all adware/malware websites, however I can't confirm that for sure since I used to block any domain that would open in pop-ups. 

Also, I may don't have a proper environment to check if those domains are really safe or not. I prefer to trust that judgement for those who have experience with that :)

```
0.0.0.0 www.apple.com-verified.cc
0.0.0.0 apugod.work
0.0.0.0 st.chatango.com
0.0.0.0 fastermac.fun
0.0.0.0 www.flixtools.com
0.0.0.0 gold-good.top
0.0.0.0 nl.installerquery.com
0.0.0.0 mackeeper.com
0.0.0.0 mackeeperapp.mackeeper.com
0.0.0.0 www.macsreason.com
0.0.0.0 queryinstaller.com
0.0.0.0 pzeny.social-datings.com
0.0.0.0 assets.kromtech.net
0.0.0.0 www.best10hot.website
0.0.0.0 www.adsupplyads.net
0.0.0.0 www.cliquefarma.com.br
0.0.0.0 getmacsoft.com
0.0.0.0 z6naousb.com
0.0.0.0 adskeeper.co.uk
0.0.0.0 network.nutaku.net
0.0.0.0 safety.apple.com.itink.lrqxe8trpxot6vcx.trade
0.0.0.0 llbmn.freehookup.link
0.0.0.0 br.1xbet.com
0.0.0.0 red-direct-n.com
0.0.0.0 certaken.com
0.0.0.0 k2s.cc
0.0.0.0 adv.li
0.0.0.0 lix.in
```

**Comment by StevenBlack** [comment]
@vitor251093 checking this list, many of these are already flagged.  Indeed some of these are flagged by several of our curates hosts sources already,

Closing.

**Comment by vitor251093** [comment]
Whops, sorry. I've downloaded the hosts list labeled **Unified hosts = (adware + malware)** in the repository description. I thought it was a compilation...

**Comment by piks** [comment]
st.chatango.com is not an advertisement/malware site, it's the script provider for the chat host chatango.com, blocking this also blocks access to any chat services hosted
