### ISSUE TITLE
Pirate Bay?

### ISSUE THREAD

**Issue by p1r473** [StevenBlack/hosts#713]
Previously, I enjoyed your hosts, as it didn't block anything but ads. The list name is even adware + malware.
But, blocking The Pirate Bay, is now inserting some level of censorship I am not happy with
Though I do not use this site, I am unhappy this ad and malware list is now censoring.

**Comment by StevenBlack** [comment]
@p1r473 [CoinBlockerList](https://gitlab.com/ZeroDot1/CoinBlockerLists) has added `thepiratebay.org`.  Are you able to take it up with them?

CoinBlockerList specializes in flagging domains that mine via client browsers.  So this isn't censorship, I assure you.

**Comment by p1r473** [comment]
Thanks. I will open a ticket with them.

**Comment by p1r473** [comment]
As a bitcoin miner, sadly, I can no longer use your list, because its now blocking a lot more than just Pirate Bay for me...

**Comment by lightswitch05** [comment]
@p1r473 have you tried making your own whitelist?
https://github.com/StevenBlack/hosts/blob/master/readme.md#how-do-i-prevent-domains-from-being-included

**Comment by p1r473** [comment]
Yea but I don't want to whitelist every mining pool I use... I liked this list because it didn't block anything good before

The coin miner list author gave his answer. I guess I will need to find a new list unless @StevenBlack would create a sublist that doesn't include this list

Their response:  I will not remove Pirate Bay as it is doubly bad for users. First, the domain is used for mining. Second, the site is bad for many people who make their money with their creativity, e.g. actors and singers.

All other tries to remove such obviously illegal pages from the lists will be ignored and deleted or reported.

So the discussion here is closed.

**Comment by funilrys** [comment]
You can create your own list without it just by deleting its data/sourcename directory before generating 🤔

**Comment by lightswitch05** [comment]
> Yea but I don't want to whitelist every mining pool I use

Its a copy & paste operation (minus the the `0.0.0.0 `) from the [CoinBlockerList](https://github.com/StevenBlack/hosts/blob/master/data/CoinBlockerList/hosts) into your `whitelist` file. If you are using this list through a pihole, that list would be `/etc/pihole/whitelist.txt`

A lot of work goes into these lists, saying that you don't feel like messing with a whitelist isn't going to get anyone here to listen to your ideas about moving the list into an optional extension

**Comment by p1r473** [comment]
I just like lists that work out of the box, where I dont have to spend time whitelisting things, like this list used to be

I really dont want my whitelist to be the entire coinbloickerlist.... a whitelist should be a few exclusions, not a list of 10s of thousands....

thanks anyways

**Comment by StevenBlack** [comment]
@p1r473 did you know... it's ridiculously easy to clone this repo and make your own host file variant?  If you are using Mac or Linux, you already have Python, just do it.  If you're a Windows user, install it, Python is free.

**Comment by p1r473** [comment]
Thanks I will see if I can figure it out

**Comment by IDKwhattoputhere** [comment]
https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/10#note_86995105
Looks to me like it's turning into a censorship issue.

**Comment by jaimelive** [comment]
I love this list and really appreciate the work that goes into it, which is why I'd like to start by thanking everyone for the commitment. However it worries me that the CoinBlockerLists are being merged when they clearly have censorious tendencies.

> ZeroDot1 @ZeroDot1 · 1 month ago
> Maintainer
>
>@p1r473 I will not remove Pirate Bay as it is doubly bad for users. First, the domain is used for mining. Second, the site is bad for many people who make their money with their creativity, e.g. actors and singers.
>
>All other tries to remove such obviously illegal pages from the lists will be ignored and deleted or reported.
>
>So the discussion here is closed.

Is this view shared by the maintainers of this list? Is it ok for one of the default lists on pihole to make these type of ethic judgements for their users?

**Comment by anudeepND** [comment]
@StevenBlack  here are my thoughts...

The main goal of this repo is to block ads, trackers, nasty malware and make internet browsing a pleasant experience. 
But including torrent sites in the unified host file is not a good idea. 
Another option is that we can maintain a list of torrent sites to block, if you agree, I will be glad to contribute to it.

**Comment by oblitum** [comment]
Why don't make a [variant](https://github.com/StevenBlack/hosts#list-of-all-hosts-file-variants) that have miners separated?

**Comment by dnmTX** [comment]
@funilrys  can't you code something so every user be able to whitelist specific domains on their end?

**Comment by funilrys** [comment]
@dnmTX This project already offers that.

To quote the [README template](https://github.com/StevenBlack/hosts/blob/master/readme_template.md#how-do-i-prevent-domains-from-being-included):

> ### How do I prevent domains from being included?
> 
> The domains you list in the `whitelist` file are excluded from the final hosts
> file.
> 
> The `whitelist` uses partial matching.  Therefore if you whitelist
> `google-analytics.com`, that domain and all its subdomains won't be merged
> into the final hosts file.
> 
> The `whitelist` is not tracked by git, so any changes you make won't be
> overridden when you `git pull` this repo  from `origin` in the future.

-----------------------
But if one needs a tool overall in the world and not necessarily this project, I already wrote: 

* [Ultimate-Hosts-Blacklis-Whitelist](https://github.com/Ultimate-Hosts-Blacklist/whitelist/tree/script) // Also available on [PyPi](https://pypi.org/project/ultimate-hosts-blacklist-whitelist/3.13.2/).
  * It can be used (by default) with the whitelist list of the Ultimate Hosts Blacklist project.
  * It can be used (while using the `--without-core` argument) without the whitelist list of the Ultimate Hosts Blacklist project.
  * It can be used with your own whitelist list (given to the tool with the `-w` argument).

It's actually a tool which can be used everywhere with your own list and not necessarily the one from the Ultimate Hosts Blacklist project. It's really focused on whitelisting and nothing else.

**Comment by dnmTX** [comment]
Thanks for the info @funilrys. I believe that that should settle once and for all the **PIRATE BAY SAGA**.
A way is provided to whitelist any desired domain,so,if this is not enough....this lists here is definitely not for you.
This is **GitHub** people.Hands on is required here.
