### ISSUE TITLE
The Pirate Bay blocked

### ISSUE THREAD

**Issue by Elijahg** [StevenBlack/hosts#714]
Seems that The Pirate Bay has ended up on your list, through the [CoinBlockerLists](https://gitlab.com/ZeroDot1/CoinBlockerLists). The maintainer of the CoinBlockerLists has [refused to remove](https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/10) The Pirate Bay from the list; therefore I would recommend no longer using their lists for anti-censorship reasons. 

Thanks for the awesome lists!

**Comment by holdit** [comment]
Yep, they're not just blocking hosts serving mining scripts, but also the websites using mining.

**Comment by funilrys** [comment]
Duplicate of #713.

**Comment by StevenBlack** [comment]
Yep, this is a duplicate.  Closing.

**Comment by Elijahg** [comment]
Oops sorry, searched but nothing came up. Probably misspelt TBP!!
