### ISSUE TITLE
Remove dead entries

### ISSUE THREAD

**Issue by jonashaag** [StevenBlack/hosts#715]
I just checked a random 1000 entries sample from the 60,000 entries list and got 16% dead/unresolvable entries. This could be stripped to reduce size of the hosts file.

How do you deal with dead entries? Should these be contributed back to the original lists? Or should we implement some process that regularly identifies dead entries and adds them to a dead list? I agree the former is more elegant but I'm not sure how responsible the people maintaining the other lists are.

**Comment by kronflux** [comment]
I believe that would be up to the list curators, but this is quite concerning, as one of the requirements for lists to be part of this project is that they are regularly curated.
Would love to hear @StevenBlack 's thoughts on this

**Comment by lightswitch05** [comment]
I would be interested in validating domains on my list. First, I use certificate transparency logs to discover subdomains. This works pretty good- but it can also leave me with domains that are either dead, or not publicly accessible. The good thing is since I add domains programmatically, it shouldn't be much harder to add a second step to [my script](https://github.com/lightswitch05/hosts/blob/master/update_hosts_file.py) to do a DNS lookup to verify its resolvable. One minor hurdle is that the script would have to do a direct DNS lookup to something like 1.1.1.1 - since I often already have the domains blocked before adding them to the list

**Comment by jonashaag** [comment]
Ran it again with 10k entries, similar numbers (1666 dead entries). Full list is here https://gist.github.com/jonashaag/bda82d96f2797df2ff7367a52f12a9e6

This is the script I've been using; note that it may contain false positives because it always boils out when nslookup takes longer than 3 seconds.

```
import random
import subprocess
import time
hosts = [l.strip().replace('\032', ' ').split()[1] for l in open('hosts2').read().splitlines() if l.strip()]
sample = random.sample(hosts, 10000)
nfound = []
for host in sample:
    print(host)
    try:
        subprocess.check_call(['nslookup', host], timeout=3)
    except Exception as e:
        print('not found', host, e)
        nfound.append(host)
print(nfound)
print(len(nfound))
```

**Comment by lightswitch05** [comment]
@jonashaag it would be helpful if you could include the source list in the output. Sources are located in [data](https://github.com/StevenBlack/hosts/tree/master/data)

**Comment by jonashaag** [comment]
Sorry can't tell what the 10k sample was but the source list was the main 60,000 entries list https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by StevenBlack** [comment]
Hi @jonashaag we rely on individual list curators to do this.

Offhand, I can probably "disappear" a domain fairly quickly, and reactivate it fairly quickly as well.  I'm talking, minutes, or hours at worse.   Depending on how you check, I can give you a false positive merely by disconnecting the box.  Or merely by editing a zone file.

If I was a trojan or virus author, I would certainly use this tactic.

I'm rather unconcerned with Type I errors, TBH.

Closing.

**Comment by funilrys** [comment]
Steven @StevenBlack did you meant Type II errors ? 🤔😄

**Comment by StevenBlack** [comment]
@funilrys  Right you are!   Although, in this case, it's whether ***Ho*** actually _is_.

![type-i-and-ii](https://user-images.githubusercontent.com/80144/42698814-011f79e0-868d-11e8-8bb1-3e6ea5d18f30.jpg)
