### ISSUE TITLE
issues with ipv4

### ISSUE THREAD

**Issue by abhijithvijayan** [StevenBlack/hosts#716]
My ipv4 local address changes from 10.1.1.x to 169.254.164.x and thus internet is down.

**Comment by abhijithvijayan** [comment]
I tried disabling Kaspersky Antivirus and still no luck. Resetting to Microsofts default host config fixes the issue.

**Comment by abhijithvijayan** [comment]
Why closed?

**Comment by StevenBlack** [comment]
Hosts files can't change your IP address.  It's just not possible.

**Comment by funilrys** [comment]
I can confirm that. Are you in a company environment ?

**Comment by abhijithvijayan** [comment]
@funilrys No I'm using home network. 

@StevenBlack As of now I don't have any antivirus or anything. After updating the host file, I can confirm the internet is down. Believe me I have tried like 20 times. I have updated the hosts with HostsMan, script by @ScriptTiger and even manually. Every time I update the host file and turn off and on wifi the internet is down. 

![2018-07-18_20-20-56](https://user-images.githubusercontent.com/34790378/42892244-febc14b0-8ace-11e8-870f-bf073a72b21b.png)

And if I reset the hosts file and flush dns and turn off and on wifi, no issues from then. 

![2018-07-18_21-11-55](https://user-images.githubusercontent.com/34790378/42892343-390ee7b4-8acf-11e8-952e-57bd587b5d63.png)

I use a PPPoE connection, our ISP uses Google DNS and I configured it to use OpenDNS.
No hosts -> everything works
Updated hosts -> Internet is down

Manually configuring the wifi to use an ipv4 10.1.1.x gives back internet.

**Comment by StevenBlack** [comment]
@abhijithvijayan if your connection to the WAN is down, check and update DNS.  It's really that simple sometimes.

**Comment by abhijithvijayan** [comment]
@StevenBlack nothing worked I reset the hosts file to the way it was in the first place

**Comment by kronflux** [comment]
have you tried flushing dns cache after using the hosts file? ( ipconfig /flushdns )
also, when you said manually configuring wifi gives back internet, do you mean with the hosts file or without?

**Comment by ScriptTiger** [comment]
This was actually a compression issue:
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/14#issuecomment-407015292

I am just following up on this in case any other similar issues arise in the future. I think for now the best thing to tell any Windows user with any seemingly random problem is just to try compressing it first and see if that solves their issue.

**Comment by abhijithvijayan** [comment]
@kronflux

https://github.com/StevenBlack/hosts/issues/716#issuecomment-407019362
