### ISSUE TITLE
resource.digitalinsight.com needed by online banking

### ISSUE THREAD

**Issue by tastewar** [StevenBlack/hosts#718]
Hello StevenBlack!

I was having an issue accessing my online banking system. Finally was able to track this down to pi-hole having resource.digitalinsight.com on its blacklist. Looking around a bit, this domain appears to host resources related to, online banking! I'm not sure why it got onto the black list, but I have whitelisted it for now in my own pi-hole, but would appreciate it if you'd remove it from your list. It may save someone else many hours of frustrating troubleshooting! Thanks for your consideration!

--Tom Stewart

**Comment by lightswitch05** [comment]
Sorry about, removed per https://github.com/lightswitch05/hosts/commit/de7a3b168e452eab495e7c5f9ca35a067077c63b

**Comment by AlexHowansky** [comment]
Heh @tastewar you and me both. My daughter just got her first paycheck and couldn't log in, she was in full panic mode ha ha. By the time I found the source of the issue, the fix was already in place. Thanks @lightswitch05 @StevenBlack

**Comment by StevenBlack** [comment]
Thanks everyone, this is fixed in Release 1.4.37.

**Comment by tastewar** [comment]
That's awesome -- thank you all!!
