### ISSUE TITLE
Whitelist request: d2c8v52ll5s99u.cloudfront.net

### ISSUE THREAD

**Issue by neeez** [StevenBlack/hosts#719]
Noticed that I was unable to play video on https://www.newyorker.com/news/daily-comment/the-unwinding-of-donald-trump

Found that whitelisting  d2c8v52ll5s99u.cloudfront.net allowed me to play video. 

Note that this *does* enable ads on video, but I would prefer to be able to see the video with an ad than to not see a video at all. 

Also referenced here: https://www.reddit.com/r/pihole/comments/74it6h/help_identifying_embedded_video_url_being_blocked/

Thanks!

**Comment by StevenBlack** [comment]
@neeez this is flagged by mvps.org, who are impeccable curators.

Please take this up with them by contacting winhelp2002@gmail.com.

Closing.

**Comment by StevenBlack** [comment]
@neeez the people at mvps.org are just great.  Take this up with them, please.

I’m sure you must understand, this domain has been observed to have nefarious intent.  If it “breaks” those sites, that’s tough.  If mvps.org decide to continue flagging this domain, then this repo will absolutely respect that decision.
