### ISSUE TITLE
Some spy domains

### ISSUE THREAD

**Issue by megapro17** [StevenBlack/hosts#722]
I found some spy domains:
analytics.twitter.com
graph.facebook.com
ebooks.prestigioplaza.com
log.sniperlog.ru

Is there exist a file with domains like that? In addition to these

**Comment by kronflux** [comment]
Can you be more specific as to why you consider them "spy" domains?

at the very least I imagine twitter analytics is left out because it breaks twitter on mobile devices when it's blocked.(specifically clicking links from twitter)

**Comment by lightswitch05** [comment]
Blocking 'graph.facebook.com' breaks facebook mobile and facebook-based logins. Been there, blocked that, pissed the wife off 😆 

`analytics.twitter.com` is actually already in the list, but commented out with a useful note: 

    # 0.0.0.0 analytics.twitter.com #[affects Twitter Dashboard]

I don't know anything about those other domains

**Comment by anudeepND** [comment]
@megapro17 same here.  graph.facebook.com is a very nasty domain. It is used by many android apps to deliver ads and track users.

**Comment by lightswitch05** [comment]
@megapro17 since you do not use facebook, you might be interested in the 'Social' extension which already has `graph.facebook.com` in it.

**Comment by StevenBlack** [comment]
@anudeepND I have no strong opinion, one way or another.  I don't facebook, so I can't gauge.

**Comment by StevenBlack** [comment]
I'm closing this.
