### ISSUE TITLE
Narvar sites

### ISSUE THREAD

**Issue by phaz** [StevenBlack/hosts#724]
Just noticed while trying to view tracking info on a package shipped via FedEx coming from Wal-Mart. The link supplied by Wal-Mart opens Wal-Mart.narvar.com, but it never opens. There are a few entries containing narvar, just haven't narrowed which it is yet. Removing all (around 10) allows the normal site operation.

**Comment by lightswitch05** [comment]
@phaz I moved the majority of narvar.com hosts to a different list. I did however leave `analytics.narvar.com` - I hope this fixes your issue while still blocking their analytics. Interestingly `walmart.narvar.com` isn't even in the list

**Comment by StevenBlack** [comment]
Thanks @phaz.  A new release is coming shortly, please let us know if that fixes it.

**Comment by phaz** [comment]
All good again. I can say assets.nervar.com, narvar.com and www.narvar.com were not the cause - I did test those 3.
Issue resolved, closing ticket.
