### ISSUE TITLE
Include talk99.cn

### ISSUE THREAD

**Issue by eternal-flame-AD** [StevenBlack/hosts#725]
talk99 is a mobile marketing, advertising and analytics provider in China. You can know more about this from [their website](http://www.talk99.cn/) (Use google translation if you don't speak Chinese:) )

Here I'll attach a domain list controlled by talk99:
```
0.0.0.0 lead.soperson.com
0.0.0.0 yun-static.soperson.com
0.0.0.0 www.soperson.com
0.0.0.0 soperson.com
0.0.0.0 talk99.cn
0.0.0.0 www.talk99.cn
```

**Comment by StevenBlack** [comment]
Thanks @eternal-flame-AD.

You got this, @anudeepND?

**Comment by anudeepND** [comment]
@StevenBlack Sure. Will add this to current PR

**Comment by StevenBlack** [comment]
Closing!  This will be in the next release.  Thanks everyone.

**Comment by eternal-flame-AD** [comment]
Thanks:)
