### ISSUE TITLE
Instagram App Ads

### ISSUE THREAD

**Issue by abhijithvijayan** [StevenBlack/hosts#727]
Add blocking for instagram ads. Added fakenews+porn+malware as host in AdAway but still ads are annoying.

**Comment by anudeepND** [comment]
@abhijithvijayan You cannot block those ads since both the content and ads are delivered using the same domain i.e; if you block the ads you will also block the content (same applies to Facebook, YouTube and so on...)

**Comment by abhijithvijayan** [comment]
@anudeepND Thanks
