### ISSUE TITLE
Remove python 2 support

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/hosts#729]
I think we've reached this point now.

Here's a [checklist in the wiki](https://github.com/StevenBlack/hosts/wiki/Dropping-Support-for-Python-2) for starters.

**Comment by funilrys** [comment]
Read to help ! 😊

**Comment by funilrys** [comment]
Ready to help!!

**Comment by oqbnaslyxt** [comment]
Does **Python 2** support require a lot of effort? I still use **Python 2**. I think that millions of other users also continue to use **Python 2**.

**Comment by MSF-Jarvis** [comment]
@oqbnaslyxt Python 2 will be completely EOL in about an year and a half so it's wise to upgrade to a longer supported version.

**Comment by oqbnaslyxt** [comment]
**Python 2** does it's job well. I see no reason why he should die in the near future. **Python 2** will surely die. But it will take many long years. Do not bury him by force. Now even **Cobol** continues to be used.

In general, I just wanted to know whether will complicate to continue to support **Python 2**? I would be very glad of this and would be immensely grateful.

Thanks.

**Comment by StevenBlack** [comment]
@oqbnaslyxt sorry man, it's been decided.  Python 2 support here is toast.

Closing.

**Comment by StevenBlack** [comment]
Sorry, reopening because, well, we're still working on this of course.

**Comment by gfyoung** [comment]
BTW, if we're going to use the EOL argument, I would say that we only support Python 3.5 and up.  Then you should check that the version does not dip below the minimum version.

**Comment by funilrys** [comment]
Hi Steven @StevenBlack, 
I think we can close this soon. 

Only need someone some testers for the python3only branch to ensure that nothing is broken then we can merge it into master.

From my side there is not python2 references in the python3only branch.

Cheers,
Nissar

**Comment by lightswitch05** [comment]
I just checked out `python3only` and re-ran my normal script without needing to make any adjustments 👍

**Comment by StevenBlack** [comment]
Thanks Nissar @funilrys.  I agree.  I've just created Issue #769 ***Everyone: please test the python3only branch***.

**Comment by gfyoung** [comment]
@StevenBlack @funilrys : BTW, once `python3only` is merged, we should go back and start closing issues related to Python 2 (I spotted a couple that are still open).

**Comment by StevenBlack** [comment]
@gfyoung and Nissar @funilrys, I've executed a test rebase here and everything looks good!

Once merged, I'll bump the version to 2.0.0, change a few things in the README, and bob's y'er uncle.

**Comment by StevenBlack** [comment]
The deed is done.  Announcing [Release 2.0.0](https://github.com/StevenBlack/hosts/releases/tag/v2.0.0)!

Thank you everybody!

Closing.
