### ISSUE TITLE
Whitelist mailfoogae.appspot.com for Streak CRM compatibility

### ISSUE THREAD

**Issue by timothyshrugged** [StevenBlack/hosts#732]
We're running into an issue with the hostname list that seems to be blocking Streak's extension from loading. I think this might be because of Streak's mail tracking option.

The address your blocking hosts the front-end half of the Streak extension, though, which means that we can't use both your list and the Streak extension. 

As an alternative, would it be possible to block just the tracking portion of Streak? All tracking seems to route through mailfoogae.appspot.com with "t" as a param (e.g. https://mailfoogae.appspot.com/t?), and it uses a specific IMG tag in emails.

**Comment by timothyshrugged** [comment]
The domain that seems to be blocked in the hosts file (https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) is `0.0.0.0 mailfoogae.appspot.com`

The Streak extension for Chrome can't load with that blocked, unfortunately.

**Comment by StevenBlack** [comment]
ah.  Thanks @timothyshrugged.

This domain is blocked because it comes from Dan Pollock over at `someonewhocares.org`.

You can reach Dan at hosts@someonewhocares.org.  Take this up with him?

Closing.
