### ISSUE TITLE
Skype is not working

### ISSUE THREAD

**Issue by mrdc** [StevenBlack/hosts#734]
Hi!
Recently my Skype has stopped working after I've used hosts file to block ads. The problem is that my hosts file is custom: it includes many sources also from StevenBlack... So it's hard to find which one made Skype unusable. Any ideas where to find hosts I should whitelist to unblock Skype?

**Comment by lightswitch05** [comment]
I use Skype and just updated my hosts to the latest version, so I can see if I have problems as well. As a side note, Skype has plenty of issues of its own, so I would be quicker to blame it in most cases

**Comment by StevenBlack** [comment]
@mrdc we'll need you to be more specific about your rig.  Skype is working fine here on MacOS latest.

**Comment by Laicure** [comment]
Using Skype everyday (with calls) on my Android phone (Xperia XZ2) and Windows PC (both with hosts file), no hiccups.

**Comment by TRaSH-** [comment]
Are you using Pi-Hole,
That's also a host file blocker.
But with more options and also the possibilities to show you what's blocked and which host file use blocking it.

**Comment by mrdc** [comment]
@StevenBlack 
I'm using CentOS 7 on VPS, dnsmaq serves as DNS server for my devices (laptops, mobile phones etc), hosts are dowloaded from many sources and then they are combined in 1 hosts file (duplicate records are excluded of course). So looks like I need to dig in and check hosts one-by-one to find out which one blocks Skype.
