### ISSUE TITLE
Scewfix issue (Popular UK DIY sales website)

### ISSUE THREAD

**Issue by btb23** [StevenBlack/hosts#741]
Thank you for maintaining this excellent resource.

I hope I am correct in identifying an issue with screwfix.com  If you search for an item for sale and try to view the 'Reviews' and 'Q&As' they don't load.

If I then whitelist <analytics-static.ugc.bazaarvoice.com> it resolves the problem. I hope this is the correct domain that is blocking these parts of their website, I'm new to all this and may be caught out by cached pages etc. Someone who knows better what they are doing may be able to confirm?

Srewfix is a popular site in the UK and to have it fully functional is quite useful.

**Comment by StevenBlack** [comment]
@btb23 the `analytics-static.ugc.bazaarvoice.com` domain is blocked by myself, lightswitch05, someonewhocares.org.  This is a pretty wide consensus on that.

My guess is, `analytics-static.ugc.bazaarvoice.com` is not the problem here.

**Comment by lightswitch05** [comment]
The domain that is needed is `screwfix.ugc.bazaarvoice.com` - which is not being blocked in this list. However, I just learned that uBlock Origin (and I guess the other version of uBlock) will automatically block any subdomains of a blocked domain.

![screen shot 2018-08-06 at 8 45 54 am](https://user-images.githubusercontent.com/598803/43717320-b29cccda-9976-11e8-8e70-773a5b7ef267.png)

So, I moved `ugc.bazaarvoice.com` from my standard list to my aggressive list, which is not in this project in commit https://github.com/lightswitch05/hosts/commit/d6337cb0cd30534196f1918aa60bffafeec71bad

**Comment by btb23** [comment]
Thank you for the further investigation and explanations. Moving the domain the aggressive list seems like a good solution.

**Comment by lightswitch05** [comment]
Any updates on this? It appears to have been resolved by removing `ugc.bazaarvoice.com`. Perhaps time to close

**Comment by btb23** [comment]
Thank you for the reminder. It is resolved and I will close.
