### ISSUE TITLE
National Express, UK coach company, unable to book journey.

### ISSUE THREAD

**Issue by btb23** [StevenBlack/hosts#742]
Thank you for maintaining this excellent resource.

I think I've found another 'broken' website

I use  National Express and with the hosts enabled I cannot progress through their website and book a journey.

https://www.nationalexpress.com/en

If you pick any location from their drop down list for travel 'from' and 'to' then pick 'date', the next thing is to click 'Find my journey'. When you do this the next page is only partially displayed with errors and you cannot proceed.

I've been unable to find which domain is blocking this, I think it maybe amazonaws, or cloudfront related.

National Express is a popular UK travel company and would be good to have it fully functional.

**Comment by StevenBlack** [comment]
Hi @btb23 we need to know, specifically, which blocked domain is affecting National Express.

**Comment by btb23** [comment]
Thank you for the reply.

I've tried with wireshark to see if I can find what the block is but I don't have enough knowledge to pin it down so easily.

I'll try again and see if I can find it and give you some better information.

**Comment by dnmTX** [comment]
@btb23  whitelist one at a time:

cdns.gigya.com   # very likely
www.googletagmanager.com  # not likely
stats.g.doubleclick.net   # not likely

**Comment by btb23** [comment]
Thank you for the tips...I'm busy with work today but will try when I get a chance. Your help is appreciated.

**Comment by lightswitch05** [comment]
Looks like mvps.org's list has `cdns.gigya.com` as well, but its commented out for causing problems on IHeartRadio

**Comment by c-edw** [comment]
You can open the devtools in your browser and look for a failed request in the Network tab. The blocked request will show up as red.

**Comment by btb23** [comment]
I'm really sorry for the late the reply. I can confirm that whitelisting cdns.gigya.com brings the National Express website back to life. So that is the offending address.

Thank you very much for your help and keeping these lists.

Shall I now close this issue or will you follow and then close? (I'm unsure of procedures).

**Comment by lightswitch05** [comment]
I'll fix this in my list later today

**Comment by StevenBlack** [comment]
Thanks Daniel @lightswitch05 and @btb23.  Let's keep this issue open until the changes land in the next release.

**Comment by lightswitch05** [comment]
I moved `*.gigya.com`to my aggressive list in https://github.com/lightswitch05/hosts/commit/78eba1c684e900845387f8e2cfdcbc770c266289

**Comment by StevenBlack** [comment]
This is resolved in [Release 1.4.47](https://github.com/StevenBlack/hosts/releases).

Closing.
