### ISSUE TITLE
Youtube In-video Ads

### ISSUE THREAD

**Issue by umang349** [StevenBlack/hosts#747]
Hello Steven,
Not sure if that is a suitable comment to make, but just want to draw your attention that Youtube in-vdeo ads have started showing up. 
Probably use youtube red would be a solution for some.
Thanks heaps for the great work you do.

**Comment by StevenBlack** [comment]
Thanks @umang349, we'd love to find a way to throttle those.

I notice now, when I "Skip Ad" after the obligatory delay, it fast-forwards to the end where we still have to watch the advertiser's call to action.

Since this issue contains nothing immediately actionable, I'm closing this now.
