### ISSUE TITLE
Pls check and add this

### ISSUE THREAD

**Issue by sanchil** [StevenBlack/hosts#748]
http://funsafetab.com/

**Comment by anudeepND** [comment]
@sanchil More information would be helpful...

**Comment by sanchil** [comment]
Ok .. what additional information or specific information are you looking for? This came up as a redirect while clicking on a link and I think it also had additional links to install some more softwares. Perhaps as browser plugins. Let me know if you need any specific information I'll try to capture it... like maybe a screen shot or something.

**Comment by sanchil** [comment]
http://funsafetab.com/lp2?pub_id=3491&sub_id=wV6JQO4PFL7PNNUFH9ENI1PI&srcid=862e19af-d8df-4d01-816b-e494d618d2cb_22027

The link as above was the complete link ... I had posted only the site link earlier.

**Comment by StevenBlack** [comment]
Closing.
