### ISSUE TITLE
Please also check a trenced dot com

### ISSUE THREAD

**Issue by sanchil** [StevenBlack/hosts#749]
https://trenced.com

**Comment by StevenBlack** [comment]
@sanchil PLEASE don't open a new issue for every domain you happen to come across.

We deal in orders of magnitude 10^=5 to 10^6 domains here.  Please show some consideration for scale and cognitive bandwidth.

Closing.

**Comment by sanchil** [comment]
Ok ... I'll collect them all and do a bulk reporting then. Sorry about that Steven ...apologies.
