### ISSUE TITLE
Allow user configuration of target ip?

### ISSUE THREAD

**Issue by XenonPK** [StevenBlack/hosts#75]
This is a small thing , but (seems to me) an easy to implement feature, why not provide a configuration file for things such as setting the target ip address?
I use your script in conjunction with a dnsmasq server that serves as a lan dns server and have an nginx http server serving blank pages (had to change the code TARGET_HOST         = '_________'
).
It works as expected, however if I set up say a cron job to update the script from git every month, I would have to go in and change the code after every update.

**Comment by StevenBlack** [comment]
This reflects exactly what's coming soon: configurable target IP, and daily chron update and regen so this repo always has the freshest hosts file.

This is among the next things on my list.
