### ISSUE TITLE
Reloading host files on Ubuntu

### ISSUE THREAD

**Issue by SUlbrichA** [StevenBlack/hosts#750]
Hi 

Reloading on ubuntu is outdated. Should be 

```
sudo service network-manager restart
```

Thanks for the project!

**Comment by funilrys** [comment]
HI @SUlbrichA and welcome here!

What is your version of Ubuntu ? Why are you talking about `service` when much Ubuntu are now under `systemd`/`systemctl` (since 2014) ?

Cheers,

**Comment by SUlbrichA** [comment]
Hi

the command on the readme did not work under 18.04 so I googled for
refresh/flush DNS and that was on the first hit
Plus, it worked :)

If there is a better alternative I'd be happy to know it (have not tried to
change startup scripts in a looong while)

Cheers
Stef

**Comment by funilrys** [comment]
@SUlbrichA Normally `sudo systemctl restart network.service` should work under Ubuntu as it use systemd :thinking:

**Comment by StevenBlack** [comment]
Thanks everybody.  When I regenerate the next release, it will say 
```
sudo service network-manager restart
```
... for Ubuntu.  This is straightforward and easier to remember, I feel.

Closing.  Thanks Stefan @SUlbrichA!
