### ISSUE TITLE
lxml==4.1.1 fails to build on macos with python3

### ISSUE THREAD

**Issue by tiiiecherle** [StevenBlack/hosts#751]
Hey, 

first of all thanks a lot for this project, very much appreciated.

I favor of changing to python3 I reworked my install and update script. Unfortunately when using on macos 10.13.6 with latest homebrew python 3.7.0 the package lxml==4.1.1 fails to build.

```
clang -bundle -undefined dynamic_lookup build/temp.macosx-10.13-x86_64-3.7/src/lxml/etree.o -L/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lxslt -lexslt -lxml2 -lz -lm -o build/lib.macosx-10.13-x86_64-3.7/lxml/etree.cpython-37m-darwin.so
  ld: file not found: /usr/lib/system/libsystem_containermanager.dylib for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for lxml
```

When I change it to lxml>=4.1.1 in requirements.txt it pulls lxml 4.2.4 and everything seems to work and build nicely.

I don`t know if it is just the requirements.txt file that has to be updated or if something else is needed.

Thanks for fixing in advance.

Kind regards

**Comment by funilrys** [comment]
Hi @tiiiecherle and welcome here ! 
Thanks for pointing out, I will update the requirements.txt along with my next PR regarding the `python3only` branch.

Have a nice day/night.

**Comment by tiiiecherle** [comment]
Thanks a lot.

Have a nice weekend ;)

**Comment by tiiiecherle** [comment]
Oh and one more thing... I put together a script that installs an update-script and and a launchd service that launches every morning and on every reboot to check if x days (in my case 4 days) are over and updates if true.

[https://github.com/tiiiecherle/osx_install_config/blob/master/09_launchd/9b_hosts_file/install_hosts_and_launchdservice.sh](https://github.com/tiiiecherle/osx_install_config/blob/master/09_launchd/9b_hosts_file/install_hosts_and_launchdservice.sh)

Just be sure when installing, that the directory structure from install script to update script are kept as is is in the repo.

The service and the update file are here:
[https://github.com/tiiiecherle/osx_install_config/tree/master/09_launchd/9b_hosts_file/launchd_and_script](https://github.com/tiiiecherle/osx_install_config/tree/master/09_launchd/9b_hosts_file/launchd_and_script)

Just in case it helps anyone ;)

**Comment by StevenBlack** [comment]
Those are neat scripts, @tiiiecherle.

I would be happy to entertain a PR that mentions these scripts in the [Interesting Applications section of the readme_template.md file](https://github.com/StevenBlack/hosts/blob/master/readme_template.md#interesting-applications).

Closing this issue now.  Thanks Nissar @funilrys for handling this.

**Comment by tiiiecherle** [comment]
>  Those are neat scripts, @tiiiecherle.
> 
> I would be happy to entertain a PR that mentions these scripts in the Interesting Applications section of the readme_template.md file.

Thanks, sure.

And perhaps the change to the requirements.txt file should also go to the master branch as it has two requirements files and the issue affects the one for python3. Thanks
