### ISSUE TITLE
Ero ads and general adware

### ISSUE THREAD

**Issue by matteocoder** [StevenBlack/hosts#753]
Here are some domains for your list (I've included the full links because if you just type the domain name on the search bar the server will just return a 403 error):

#### General adware
+ [https://notification-system.tools/notifications/video/3/index.html?subid_short=0910a30f25bb93ea136e8cee825bb665&p1=http%3A%2F%2Fwww.hibids10.com%2Fwatch%3Fkey%3D3f267a8bb5250097fa2f7b6f41f18d9f](url)

+ [http://install.myvideotab.com/?pid=52718&subid=OHZBBGP63W&clickid=eu7trrjymcsxddacxshn&pgs=1](url)

+ https://v1.your-notification.tools/notifications/robot/index.html?p1=https%253A%252F%252Fzme8o3l1c4.com%252Fi3mbvmnyk%253Fkey%253D3f267a8bb5250097fa2f7b6f41f18d9f&conversion_sub_id=VjN8MTQzODY4MTZ8MTI4MDkxOHwxMjE3NDkxfDE1MzMwMzg2NjR8MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwfDc5LjQyLjY5LjE3M3wxfHNoPThmMTc4YWJhM2VkZjIzODk0YzBjZTc4MmVlY2QyYzUwNTI3YjExYzg4M2E3MDRkNWExNzlkYWE4ZmQzODY3ZmUyYTY0MzE2NzQ0ZjhhZTA2YjE2ODZiMjMwYmZmYzg4NmE5ZGRhM2I4OTVhODFlZTA0YmQ1ZjMyOWZiMTExOGFjZTc0YjhhOWRlMTYwZTQ2ZjBlMjg3NjY1fDJhYWFjMDQ1MTRiYTlmMGIwYmQzYzNkYmU4Njk2ODE3&subid_short=01b23de4ffdfb1d99c85e6562274d003

+ https://v1.your-notification.tools/notifications/audio/index.html?p1=https%253A%252F%252Fzme8o3l1c4.com%252Fi3mbvmnyk%253Fkey%253D3f267a8bb5250097fa2f7b6f41f18d9f&conversion_sub_id=undefined&subid_short=aebd0a03db8be61ffa1fe1affedd0309

+ https://it.oggipremio.com/wingames/newcar500-2019/IT/step1

#### Ero ads

+ https://www.sexfortuna.com/?id=go.sexfortuna.com&utm_source=p79987DZDs1it&utm_medium=tempo

Thanks for all the hard work you put on this project!

**Comment by StevenBlack** [comment]
Thanks @matteocoder.  Can you please bring this up with one of our many [curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant)?

Closing.

**Comment by matteocoder** [comment]
@StevenBlack Do you mean that I should contact the maintainers of the main sources and submit these domains to them directly? Sure, no problem!

**Comment by StevenBlack** [comment]
@matteocoder yes please.  @clefspeare or @sinfonietta for the Ero, any of the others for the adware.  Thank you for your understanding!
