### ISSUE TITLE
blacklist porn proxy sites

### ISSUE THREAD

**Issue by abhijithvijayan** [StevenBlack/hosts#754]
sites like in #763

**Comment by anupritaisno1** [comment]
Bad idea. You realise that they aren't just for unblocking porn right?

**Comment by abhijithvijayan** [comment]
@anupritaisno1 Blocking porn proxy sites won't affect all the proxy sites which for browsing some specific blocked sites.

**Comment by lightswitch05** [comment]
To play devils advocate the majority of free proxies at best track/record everything you do, and at worst actively inject malware into the content [1][2]. But on the other side, people do still use these services and adding them to an adware + malware list could take them by surprise. Porn blockers regularly block proxies, so IMHO these would be right at home in the port extension list. But that would be up to one of those maintainers 

[1] https://krebsonsecurity.com/2015/06/free-proxies-arent-necessarily-free/#more-31322
[2] https://www.csoonline.com/article/2938914/microsoft-subnet/shady-free-proxies-and-tor-exit-nodes.html

**Comment by abhijithvijayan** [comment]
@StevenBlack What's the point in blocking all porn sites and leaving a loophole so as to visit the ones we blocked in the first place! :grinning:

**Comment by ScriptTiger** [comment]
Some similar arguments have been made before:
https://github.com/StevenBlack/hosts/issues/569
https://github.com/StevenBlack/hosts/issues/615

Proxies/anonymizers and torrents could all be consolidate to a single extension. I think an extension that automatically combines porn, gambling, and all of these would be a good standard parental control list, which is what I think most people are thinking about when they raise issues like this. And since this has come up numerous times, I think starting a discussion around starting such a list might be warranted.

**Comment by ScriptTiger** [comment]
I think we can get a pretty good head start on the torrents with my previous comment in the other issue:
https://github.com/StevenBlack/hosts/issues/569#issuecomment-388572787

For proxies, VPNs, and other anonymizers, I think we should focus on domain lists of web proxy portals and websites that provide lists of available proxy and VPN servers.

**Comment by abhijithvijayan** [comment]
added all the mentioned and submitted a PR #763 

feel free to add more to the list as it comes by.

**Comment by funilrys** [comment]
@StevenBlack, this can be closed :+1:

**Comment by dnmTX** [comment]
**MERRY CHRISTMAS ALL AND HAPPY NEW YEAR** 
Fingers crossed to be a better one 👍

**Comment by abhijithvijayan** [comment]
[Closing]

**Comment by lightswitch05** [comment]
I've been looking for a block list specifically for VPN and Proxy sites. I haven't been able to find one other then this minor list. Doesn't anyone else know of a list like that

**Comment by ione2121** [comment]
Please make hosts for pubgm cheat

Pada tanggal Sab, 7 Sep 2019 00:58, Daniel <notifications@github.com>
menulis:

**Comment by ScriptTiger** [comment]
All of the PUBGM cheats I've seen are based on overwriting the game data files, .OBB, etc., and don't require connecting to any external connections. If you have a cheat that requires you to do so, you're probably using scam software that is cryptomining in the background or auto-clicking ads.
