### ISSUE TITLE
zukxd6fkxqn.com

### ISSUE THREAD

**Issue by rohanvakharia** [StevenBlack/hosts#755]
```
zukxd6fkxqn.com
```
Add this domain to blacklist. I found that this domain is used to redirect Ad domain.

**Comment by StevenBlack** [comment]
Thanks @rohanvakharia.  Can you please bring this up with one of our many [curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant)?

Thanks.

Closing.
