### ISSUE TITLE
false positive: brakrock.be

### ISSUE THREAD

**Issue by Najoj** [StevenBlack/hosts#756]
brakrock.be should not be in the lists. It is the site of a small punk rock festival in Belgium.

Not a new issue: https://github.com/search?q=brakrock&type=Issues

**Comment by funilrys** [comment]
That one is for me @StevenBlack still waiting at https://github.com/mitchellkrogza/Badd-Boyz-Hosts/issues/44 this one is into my next whitelisting check session.

**Comment by StevenBlack** [comment]
Closing!
