### ISSUE TITLE
social breaks apis.google.com

### ISSUE THREAD

**Issue by xstnztk** [StevenBlack/hosts#761]
The "social" extension blocks plus.l.google.com . Unfortunately the dig command tells me that apis.google.com is (currently?) a CNAME for plus.l.google.com, so apis.google.com cannot be accessed when using the "social" extension:

`apis.google.com.        5184    IN      CNAME   plus.l.google.com.`

For me this had the effect that Google Keep did not work anymore (kept looping), and that I could not search for applications in the Google Play Store.

I have used the "social" extension for quite some time so perhaps the CNAME for apis.google.com is something new? I have whitelisted plus.l.google.com, and now everything works as before.

**Comment by StevenBlack** [comment]
Thanks @xstnztk.

Ping @sinfonietta, what do you think?

**Comment by TrigonaMinima** [comment]
plus.l.google.com is still there in the current "Unified hosts + fakenews + gambling + porn + social" file. It prevents the google calendar tiles from editing.

**Comment by StevenBlack** [comment]
Ping @sinfonietta...

**Comment by StevenBlack** [comment]
Thanks for the quick action @sinfonietta. 🌟 

Shivam @TrigonaMinima this will be reflected in the next release, likely soon.
