### ISSUE TITLE
Blacklisted official thepiratebay.org website

### ISSUE THREAD

**Issue by yeralin** [StevenBlack/hosts#766]
It might have happened by accident, but I see that thepiratebay.org was added to the list.

Can someone elaborate on that?

**Comment by StevenBlack** [comment]
Hi @yeralin this comes in as a result of CoinBlockerList, which indicates that this site may be crypto mining.

Can you please log this issue at https://gitlab.com/ZeroDot1/CoinBlockerLists/issues ?

**Comment by funilrys** [comment]
Duplicate of the discussion at #713.

(also) For reference:  #714

**Comment by yeralin** [comment]
> I will not remove Pirate Bay as it is doubly bad for users.
> First, the domain is used for mining.
> Second, the site is bad for many people who make their money with their creativity, e.g. actors and singers.
> All other tries to remove such obviously illegal pages from the lists will be ignored and deleted or reported.
> So the discussion here is closed.

Welp, the guy decided to become a god.

I'm removing my crontab for updating hosts
