### ISSUE TITLE
Everyone: please test the python3only branch

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/hosts#769]
Hello everybody.

I need people on a wide variety of OSes to test the `python3only` branch to ensure you can build hosts files in all its facets.

I hope to merge `python3only` into `master` very soon.

Upvote this issue with comments to declare your OS and what you get.  If someone has already tested your OS, then upvote with a 👍 to confirm.

Thanks!

**Comment by lightswitch05** [comment]
Result: Success ✅ 
OS: MacOS High Sierra (10.13.6)

**Comment by gfyoung** [comment]
Everyone's favorite: Windows 10! 😄

**Comment by StevenBlack** [comment]
Tested on ***Ubuntu 14.04.5 LTS***: works great after gyrations to get latest Python3, Pip3 updated.

One oddity: the base hosts file contains only 43,718 unique entries, compared to 60,777 entries here, after pausing for a long time on someonewhocares.org.

**Comment by StevenBlack** [comment]
[Release 2.0.0](https://github.com/StevenBlack/hosts/releases/tag/v2.0.0) is now live!

Thank you everyone!

Closing.

**Comment by gfyoung** [comment]
@StevenBlack :

https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

(in reference to my comment [above](https://github.com/StevenBlack/hosts/issues/769#issuecomment-418470914))

With Windows 7 extended support scheduled to be ended in about 15 months (and Microsoft dropping support entirely for anything earlier than that), what do you think about revisiting this?  Can discuss in a new thread if there is sufficient interest.

**Comment by StevenBlack** [comment]
@gfyoung I'm a card-carrying member of the National Fuck Microsoft Association, as you may know  😎 

As far as I know, we don't have any Windows 7-specific issues, do we?  What's the rush?

**Comment by gfyoung** [comment]
@StevenBlack : 🤦‍♂️ 

Sorry, the is no context to the question!  I'll phrase better in a subsequent comment.

**Comment by gfyoung** [comment]
Here is the context: automating the `hosts` file copying and DNS cache clearing.  I recall that one of your concerns was that there were too many versions of Windows out there in the wild.

However, if Microsoft isn't supporting many of the versions out there, and with Windows 7 (and up) adoption pretty high, I was thinking that maybe we could revisit this.

What do you think?
