### ISSUE TITLE
Trailing spaces/tabs breaks hosts file reading

### ISSUE THREAD

**Issue by raziel-** [StevenBlack/hosts#77]
On my platform trailing spaces/tabs brings up error messages about missing information for servers while being read in.

The lines in question are purely comment lines, so i'd like to ask if those trailing spaces/tabs could be removed?
I could do it with a rexx parser myself, but would need to perform this on every update.

The lines in question are:
17662
17663

17666
17667

17670

17672

17679

17681

17705
17706

Thanks a lot for this great hosts file

**Comment by StevenBlack** [comment]
Sure!  We can do that!

Just curious, what is your platform?

**Comment by raziel-** [comment]
Oh boy, missing the vital information once again...sorry

OS: AmigaOS4
CPU: PA6T-1682M

Thank you very much

**Comment by StevenBlack** [comment]
Closing.

**Comment by Gitoffthelawn** [comment]
@raziel- Sorry for the OT, but I have to ask.  What made you choose to use AmigaOS4?  Besides the CPU, what hardware are you using it on?

**Comment by raziel-** [comment]
@Gitoffthelawn 

No problem with me, but you could also email me ;-)

I went from the C64 over Amiga 500, Amiga 2000 to Amiga 4000.

I know the OS from version 1.2 onward, lived it, loved it and when a new version was announced i couldn't resist :-)

I'm using AmigaOS4 on an AmigaOne X1000 with a PA6T-1682 on 1.8 Ghz.
4 GB of Ram (where 2 GB can be used with AmigaOS4, more to be supported later)
Radeon HD 7750

I live with the flaws, try to circumvent it and always hope for a bug fix.
It has it's drawbacks, but it's still fun to use and work with, wouldn't miss it.

**Comment by raziel-** [comment]
@StevenBlack 

hmm, the trailing spaces/tabs are still in.

lines are
with spaces
17691, 17692
with tabs
17695, 17696, 17699, 17701, 17708, 17710

**Comment by StevenBlack** [comment]
Thanks Hubert @raziel- 

Reopening.

**Comment by raziel-** [comment]
@StevenBlack 

I just saw the "Unified Hosts" links on the main github page...awesome :-)

Though it seems the Gambling-Porn-Social one is down:
https://raw.githubusercontent.com/StevenBlack/hosts/raw/master/alternates/gambling-porn-social/hosts

and in those hosts the trailing spaces are also still in, sorry :-)

**Comment by Gitoffthelawn** [comment]
@raziel- Thanks for the info!  Sounds like you are having fun.  How do you view an email address of a fellow GitHub user for OT discussions?  I'm curious to know what uses you find for your Amiga.

**Comment by raziel-** [comment]
@Gitoffthelawn 

That is correct, it doesn't seem to be possible to send private emails in github (it worked in sf.net)

raziel(underscore)nosgoth(at)web(period)de

Sorry for the OT again

**Comment by Gitoffthelawn** [comment]
@raziel- Got it.  Thanks.  You can delete your last post, if you prefer.

**Comment by StevenBlack** [comment]
@raziel- hi, sorry this took so long.

How's that?

**Comment by OptimusNorris** [comment]
It looks like this change introduced an issue where the new-lines were removed from the comment headers of each consolidated host file, resulting in the first host line of each consolidated file becoming part of the comment header. Please refer to line 23 of the current version of the raw hosts file for an example.

**Comment by StevenBlack** [comment]
@OptimusNorris Doh!  Good catch, thanks.

**Comment by StevenBlack** [comment]
Closing.

**Comment by raziel-** [comment]
@StevenBlack 
I'm truly sorry to comment on a once again closed issue.

The trailing space are still in, but maybe my understanding on how it is supposed to work is flawed?

If i "direct download" from i.e. this address: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn-social/hosts
or any of the others given on the main page, the trailing spaces/tabs in question are still there.
Just search for *maybe-spy* and they'll start two rows beneath.

Are those direct links meant to go through a python script first which takes care of those on downloading/installing?
Because if so, i wouldn't be able to use the python script you provide...i'm stuck at python version 2.5.5.

Just so that i don't ask again, are the trailing spaces/tabs part of the linked file and won't be "fixed" there?

Because in this case i'd go and write me a local arexx script then.

Thank you very much for this great hosts files :-)

**Comment by StevenBlack** [comment]
@raziel- I'm not seeing any trailing spaces or tabs in that area.  I see spaces and tabs *before* comments, is that what you mean?

Are you on Windows?  I'm guessing yes.  What are you using to view the hosts files?  I'm trying to understand why you see trailing spaces and tabs, and I'm not.

**Comment by raziel-** [comment]
@StevenBlack 
Yes, that's exactly what i mean.
The (pure) comment lines (like i wrote in the first post) with trailing spaces/tabs keep letting my Internet Prefs complain.

I'm not on Windows, i'm on AmigaOS4, i use a simple ASCII editor and they are visible there aswell.
I know it's a workaround to silence errors i'm getting solely on my platform, so i'm grateful if you could get rid of those lines.

Thank you :-)

**Comment by StevenBlack** [comment]
I'm not seeing *any* trailing spaces on the pure comment lines...

**Comment by raziel-** [comment]
I doing something awfully wrong then...ok, i'll try to show you you what i mesn/see.
Get the host file from here:
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn-social/hosts

Load it into an editor:
Either search for "maybe-spy" or go directly to line 17638.
I have the following there:
#0.0.0.0 auto.search.msn.com  # Microsoft uses this server to redirect
                                # mistyped URLs to search engines. They
                                # log all such errors.
#0.0.0.0 sitefinder.verisign.com	# Verisign has joined the game
#0.0.0.0 sitefinder-idn.verisign.com	# of trying to hijack mistyped
					# URLs to their site.
					# May break iOS Game Center.

#0.0.0.0 s0.2mdn.net		# This may interfere with some streaming
				# video on sites such as cbc.ca
#0.0.0.0 ad.doubleclick.net   # This may interefere with www.sears.com
				# and potentially other sites.
0.0.0.0 media.fastclick.net
#0.0.0.0 ebay.doubleclick.net		# may interfere with ebay
#0.0.0.0 google-analytics.com			# breaks some sites
#0.0.0.0 ssl.google-analytics.com
#0.0.0.0 www.google-analytics.l.google.com
#0.0.0.0 stat.livejournal.com		# There are reports that this may mess
 					# up CSS on livejournal
#0.0.0.0 stats.surfaid.ihost.com	# This has been known cause
					# problems with NPR.org
#0.0.0.0 www.google-analytics.com		# breaks some sites
#0.0.0.0 ads.imeem.com		# Seems to interfere with the functioning of imeem.com
#</maybe-spy>

These trailing blanks i mean.
There are at least two more on lines 17683/17684

  # ads and track users across
  # the com.com family of sites

Those only have two spaces in front of the comment "#"

Is it possible to get rid of those?

**Comment by StevenBlack** [comment]
I see no trailing spaces at 17683/17684.

This conversation is over.
