### ISSUE TITLE
Fails if blacklist(.example), whitelist(.example), or myhosts(.example) files don't exist

### ISSUE THREAD

**Issue by chunjackie** [StevenBlack/hosts#773]
Re: https://github.com/StevenBlack/hosts/pull/736 and https://github.com/StevenBlack/hosts/commit/275590fcbb72c72e4d50aa732d593e0b1ecbd374

Up until today I've been using updateHostsFile.py as a standalone file with only a whitelist file (no blacklist or myhosts file). I noticed that my daily build failed and found the above two changes.

Error message:

```
Traceback (most recent call last):
  File "/home/updateHostsFile.py", line 1516, in <module>
    main()
  File "/home/updateHostsFile.py", line 183, in main
    merge_file = create_initial_file()
  File "/home/updateHostsFile.py", line 644, in create_initial_file
    maybe_copy_example_file(settings["blacklistfile"])
  File "/home/updateHostsFile.py", line 1232, in maybe_copy_example_file
    shutil.copyfile(example_file_path, file_path)
  File "/usr/lib/python3.4/shutil.py", line 107, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/blacklist.example'
```

Builds successfully if I manually create the blacklist and myhosts files.

A fix would be to update the maybe_copy_example_file function to add an additional check (`if os.path.isfile(example_file_path)`) to see if the .example files exist before attempting to copy:

https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py#L1230

```
if not os.path.isfile(file_path):
    example_file_path = file_path + ".example"
        if os.path.isfile(example_file_path):
            shutil.copyfile(example_file_path, file_path)

**Comment by StevenBlack** [comment]
Thanks @chunjackie, good catch!  That's a good remediation suggestion too.  

I wonder if this is an edge case since 

1. we include the `*.example` files in the repo, and
2. we have a major [semver](https://semver.org/) bump that signals the possible backward incompatibility.

Ping @gfyoung, what do you think?

**Comment by gfyoung** [comment]
IMO, this feels very edge-cased to me.  I always thought the use-case was clone the repo and run the script.

**Comment by StevenBlack** [comment]
I deleted the `.example` files, just as a test, and I feel differently after watching `updateHostsFile.py` just crash.

The `.example` files are scaffolding for optional userland features.  I feel better making this more robust in userland.

Moreover this arises so soon after release, which leads me to suspect, this may not be such an edge case.

@gfyoung thanks for your input on this!

**Comment by StevenBlack** [comment]
Closing.

**Comment by gfyoung** [comment]
> The .example files are scaffolding for optional userland features. I feel better making this more robust in userland.
