### ISSUE TITLE
Reconsider the inclusion of CoinBlockerLists

### ISSUE THREAD

**Issue by FatOrangutan** [StevenBlack/hosts#775]
This list goes beyond "prevent[ing] cryptomining in the browser" by blocking access to whole domains such as thepiratebay.org, even when less aggressive rules would suffice. The [maintainer's reasons](https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/10#note_86995105) make it quite clear that the list name is a misnomer now and the list is and will continue being used to block "obviously illegal pages" too. The maintainer (and apparently, their fans) are generally difficult to reason with, so taking up such issues to their repo is futile. All of this is part of why the list was [never included in uBlock Origin](https://github.com/gorhill/uBlock/issues/3600).

There are much better coin blocking lists already available that do what they say on the tin, such as NoCoin.

I realize that I can create my own unified list, but I'm filing this issue to reconsider the inclusion of this list by default. The unified list is described as `adware + malware` and TPB is clearly neither.

**Comment by StevenBlack** [comment]
@FatOrangutan it took me less than a minute of very basic searching to uncover an avalanche of recent news reports about Pirate Bay and crypto mining.

Please research you case, maybe for a minute, before submitting issues here.  Thank you.

**Comment by FatOrangutan** [comment]
>it took me less than a minute of very basic searching to uncover an avalanche of recent news reports about Pirate Bay and crypto mining.
  
I'm well aware of the coin miner on TPB; I thought I made it clear when I said (emphasis added):

>blocking access to whole domains such as thepiratebay.org, **even when less aggressive rules would suffice**

...or when I linked to the [developer's reasons](https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/10#note_86995105). It is quite literally in the footer of every TPB page too:

>By entering TPB you agree to XMR being mined using your CPU. If you don't agree please leave now or install an adBlocker

Your response also failed to cover why, exactly, a miner blocking list is blocking on the basis of "obviously illegal pages":
>Second, the site is bad for many people who make their money with their creativity, e.g. actors and singers.

Most filter lists / host file maintainers try to avoid blocking whole sites, especially if the issues can be resolved by simply blocking the miner or other offending connections that the site makes. Coincidentally, good maintainers try and avoid playing benevolent dictators too.

>Please research you case, maybe for a minute

Well, I will just ignore the patronizing response I guess.

**Comment by 894-572** [comment]
@StevenBlack I greatly hope that the project's goal isn't blocking websites solely because they run miners. As @FatOrangutan said the list creator's reasoning is based on ideological, not technical, reasons and CoinBlockerLists should be removed from the default sources.

**Comment by 894-572** [comment]
@StevenBlack Are websites blacklisted if they run miners?

I respect your decision to use your own name, I decided not to because defending torrent sites will potentially draw negative responses.

**Comment by kronflux** [comment]
@894-572 Just like to point out that there's nothing inherently wrong with torrents or websites hosting torrents. Torrents are very widely used for non-illegal activity, and discussing them as such would not bring any negativity toward you personally.
ThePirateBay itself actually hosts a very large number of completely legal torrents - and, while that's not what they're known for, they themselves are not technically "illegal"
Richard, btw. :P

@StevenBlack I do actually agree with one point, which is that I'd rather see the sources of those miners being blocked, rather than entire websites. That being said, I have absolutely no desire to defend any particular site, nor do I think it warrants the removal of CoinBlockerList.
Just thought it worth voicing the opinion :)

**Comment by FatOrangutan** [comment]
>recommend people to learn to read and understand a tool before using it.  
  
Why can't neither you nor Steven actually read what is written instead of just stating the obvious and being condescending on top?

>CoinBlockerList do its work for miners but talking about `censorship` is a bit excessive as I rarely know any censorship which result in entity having the choice.

Literally nobody in this issue had used the word `censor` to describe what CoinBlockerList is doing, *obviously* for the same reason you then went on to type. (Look at that, I can be patronizing too.)

>Indeed, we all have the choice! [...] We all have the choice!

The last para of my original description addresses this. Not going to quote myself, again, because this is getting tiring.

>Let's lock this out

Yes please.
