### ISSUE TITLE
apps.wixrestaurants.com

### ISSUE THREAD

**Issue by filbo** [StevenBlack/hosts#780]
Hi,

Trying to look at the menus of a restaurant: `https://www.dumplinggarden.com/menus` comes up blank until I whitelist `apps.wixrestaurants.com`, which was added in commit 96f0635ed02d110eef200bf21dd5aac733b4a871.  I assume this site was added by one of the upstream sites for serving some sort of ads.  What is your policy about sites which are both ad servers and non-ad, useful servers?

... After writing the above, I chased this back to the @lightswitch05 list, which added it to ads-and-tracking.txt and ads-and-tracking-extended.txt in commit 24b319ce1e2a16478d53e2445978aea0718ae7a7; so Daniel, please take this as an issue + question for your list as well.  (By the readme, I guess maybe it should remain in -extended but not in ads-and-tracking ?)

**Comment by lightswitch05** [comment]
I didn't seem nessary for the website I had discovered it on, but I'll try out the link @filbo gave, and if that is indeed the culprit, then I'm happy to remove it

**Comment by lightswitch05** [comment]
Removed in https://github.com/lightswitch05/hosts/commit/a3832e779c5be65c772bbd7576fbb52c384cb214

Sorry for the inconvenience! I wouldn't want anything to come between me some yummy dumplings either :plate_with_cutlery:

**Comment by filbo** [comment]
Thanks, @lightswitch05!  No problem, I understand how difficult it is to keep up with all this junk and there are going to be a few false accusations along the way.  As long as there's a reasonable channel to repair it; and I have two, my pihole whitelist + chasing around github...

**Comment by filbo** [comment]
p.s. the dumplings were pretty good

**Comment by StevenBlack** [comment]
This is fixed in the latest release.  Thanks everybody!

Closing.
