### ISSUE TITLE
block more adult sites

### ISSUE THREAD

**Issue by betzalel102** [StevenBlack/hosts#781]
0.0.0.0 sexeden.co.il
0.0.0.0 www.drsex.co.il
0.0.0.0 www.sex-ly.com
0.0.0.0 www.harmanit.co.il
0.0.0.0 m.uzit.co.il
0.0.0.0 www.tubev.sex
0.0.0.0 www.pornmovies.co.il
0.0.0.0 www.1800800.co.il
0.0.0.0 www.presidentescort.co.il
0.0.0.0 il.bongacams.com
0.0.0.0 hdxxx.top
0.0.0.0 xnxxsex.pro
0.0.0.0 balisex.co.il
0.0.0.0 www.sexadir.co.il
0.0.0.0 www.sexmovie.co.il
0.0.0.0 www.only4adults.net
0.0.0.0 xfinder.com
0.0.0.0 www.sexhubhd.com
0.0.0.0 www.museumofsex.com
0.0.0.0 www.freefuckvids.com
0.0.0.0 colliderporn.com

**Comment by StevenBlack** [comment]
Thanks @sinfonietta.

Closing.
