### ISSUE TITLE
Raven.js

### ISSUE THREAD

**Issue by Technetium1** [StevenBlack/hosts#785]
https://github.com/StevenBlack/hosts/blob/1e9311b9353ba95c34a05f297ac4fb3ca8b8be40/data/lightswitch05/hosts#L5241

Raven.js is not malicious and `cdn.ravenjs.com` should not be on this list

**Comment by funilrys** [comment]
Hi @Technetium1,
and welcome here!

I'm sure that @lightswitch05 will let you know about this.

Have a nice day/night.

**Comment by dnmTX** [comment]
Trackers and telemetry are not malicious either that doesn't mean they don't belong here.Looking at the domain in question looks like one of those.

**Comment by lightswitch05** [comment]
Also, duplicate this ticket is a duplicate of https://github.com/StevenBlack/hosts/issues/705

**Comment by StevenBlack** [comment]
Thanks everybody!

Closing.
