### ISSUE TITLE
ams1-ib.adnxs.com

### ISSUE THREAD

**Issue by raziel-** [StevenBlack/hosts#786]
I´ve found this to be a source of video ads which eats away cpu time, but i don´t know from which source it is being added.

Otherwise would it be possible to add it to your liste, please?

It´s used on the web.de freemail pages

**Comment by lightswitch05** [comment]
I have a ton of adnxs domains in my list, so I'm happy to add this one too. Added in https://github.com/lightswitch05/hosts/commit/3a5c1e6c1163b103f13e3e721fa8dce26b9b4cca

**Comment by raziel-** [comment]
Awesome, thanks a lot

**Comment by StevenBlack** [comment]
Thanks Hubert and Daniel! @raziel-  @lightswitch05
