### ISSUE TITLE
Latest AdAway development build only supports HTTPS sources

### ISSUE THREAD

**Issue by VincentJoshuaET** [StevenBlack/hosts#788]
Therefore, we won't be able to use this.

_Sent from my Redmi Note 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lightswitch05** [comment]
Is something wrong with the HTTPS source in the README?

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by VincentJoshuaET** [comment]
It also can't be reached by AdAway. AdAway has never been able to reach it even before actually.

**Comment by funilrys** [comment]
THen AdAway has a problem.

**Comment by lightswitch05** [comment]
@VincentJoshuaET does the JSDelivr proxy work? https://cdn.jsdelivr.net/gh/StevenBlack/hosts/hosts

**Comment by StevenBlack** [comment]
@lightswitch05 I just opened https://www.jsdelivr.com/ with [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) active.  It calls 14 domains, at least.  That's nasty.

```
d2axgrpnciinw7.cloudfront.net
b-cdn.net
cachefly.net
cf-china.info
cdn77.org
belugacdn.link
ahacdn.me
azioncdn.net
qtlglb.com
lswcdn.net
perfstack.net
gocache.net
perfops.net
jsdelivr.com
```

**Comment by lightswitch05** [comment]
Wow... uBlock Matrix doesn't show near that many

![image](https://user-images.githubusercontent.com/598803/46088761-9d205180-c19c-11e8-82c2-abadce76f746.png)

Its not a great option, but I am curious if it works or not since it can proxy any content on Github. Their [privacy policy as a CDN](https://github.com/jsdelivr/jsdelivr#privacy-policy) isn't the worst. But they have a different privacy policy per their website.

> jsDelivr might use information about downloaded files to build download stats per project and per file.
> jsDelivr does not store any user data and does not track any users in any way.
jsDelivr might use information about downloaded files to build download stats per project and per file.
> Here are the relevant policies of our CDN providers:
> * [Cloudflare](https://www.cloudflare.com/security-policy/)
> * [MaxCDN](https://www.maxcdn.com/legal/)
> * [Fastly](https://www.fastly.com/privacy/)
> * Only in China [Quantil](https://www.quantil.com/privacy-and-security-policy/)

**Comment by MartinKolarik** [comment]
@StevenBlack that's because we run our [RUM script](https://github.com/jsdelivr/jsdelivr#contribute-performance-data) on the website to measure performance of individual CDN providers. The CDN domain is completely separated and doesn't serve anything else than the requested content. Full privacy policy is also available [here](https://www.jsdelivr.com/privacy-policy-jsdelivr-net).

**Comment by patrickdrd** [comment]
(subscribe to issue post)

**Comment by funilrys** [comment]
As an alternative (for now), please follow https://github.com/StevenBlack/hosts/issues/731#issuecomment-424436689.

**Comment by funilrys** [comment]
@PerfectSlayer @Vankog
Please look at this as this is in some part your issue. 

Indeed, your application don't work with https://raw.githubusercontent.com (which is a well known domain for all GitHub users by the way) as mentioned by @lightswitch05 and @VincentJoshuaET previously.

Also, if I remember correctly from the past discussion here, your application use or propose this repository by default so your application logic may have a problem if it simply can't pull the file.

Have a nice day/night.

Cheers,
Nissar

**Comment by Vankog** [comment]
discussion about this is in #AdAway/AdAway#700

**Comment by patrickdrd** [comment]
> 
> 
> As an alternative (for now), please follow [#731 (comment)](https://github.com/StevenBlack/hosts/issues/731#issuecomment-424436689).

ok with sbc (steven black), but there are two more that don't work with https:
http://sysctl.org/cameleon/hosts.win and
http://winhelp2002.mvps.org/hosts.txt
are there any alternatives for these?

**Comment by dnmTX** [comment]
@patrickdrd  `http://sysctl.org/cameleon/hosts.win` is not maintained anymore, hasn't been for a while now. Therefore you need to download it only once,put it,let's say in your google drive and fetch it from there.Remember,using it together with StvenBlack's one,there are approximately 13,000+ duplicates,not sure is it worth the effort to be honest.You won't lose much without it.

**Comment by VincentJoshuaET** [comment]
Just tried the GitHub hosts link, it does work. But yeah, unknown update status is shown.

**Comment by PerfectSlayer** [comment]
@VincentJoshuaET I just implemented the workaround (not released yet).
See AdAway/AdAway#700 for AdAway related issue 😉
