### ISSUE TITLE
https for hosts file?

### ISSUE THREAD

**Issue by patrickdrd** [StevenBlack/hosts#789]
so after adaway's latest version (4.0.9),
we are blocked from using http hosts sources,
which renders sbc.io/hosts/hosts unusable,
is there an alternate url we can use?

**Comment by anudeepND** [comment]
@patrickdrd It is being discussed [here](https://github.com/StevenBlack/hosts/issues/788). I would suggest you to close the issue since the issue already exists.

**Comment by funilrys** [comment]
@StevenBlack Please close.

Duplicate of #788.
