### ISSUE TITLE
Detected as malicious by Windows Defender

### ISSUE THREAD

**Issue by MiguelRipoll23** [StevenBlack/hosts#79]
What happened? Why is the signature of this file reported as malicious?

**Comment by FadeMind** [comment]
Because python script want access to hosts file and made changes in, false alarm.

**Comment by MiguelRipoll23** [comment]
@FadeMind Oh, okay. I didn't know that the behavior of the program triggered it too, thanks.

**Comment by FadeMind** [comment]
@MiguelRipoll23 
py scipt have this:

    elif os.name == 'nt':
        print ("Automatically moving the hosts file in place is not yet supported.")
        print ("Please move the generated file to %SystemRoot%\system32\drivers\etc\hosts")

IMO thats why Windows Defender do false alarm.
User need manualy copy hosts file and replace original in proper path.
So, this is not automatic job. (I was wrong in previous comment about it)

**Comment by Gitoffthelawn** [comment]
Hmmm... if the py script is not actually modifying the hosts file (and is just printing a message), then Windows Defender is likely doing one of the following:

1. Reading the script line by line and identifying that it *can* change a hosts file (for other OS's)
2. Matching a signature with a section of the script
3. Identifying the entire script via a signature

If you want to see if it's item 3, just change a little bit of the script and see if Windows Defender still flags it.  Then report your findings here!
