### ISSUE TITLE
Social-only block list?

### ISSUE THREAD

**Issue by yegors** [StevenBlack/hosts#792]
Hi,

Thanks for all the work you do, but I was wondering, is there a social only block list, that doesn't include the "unified" contents?

**Comment by lightswitch05** [comment]
@yegors the social extension to this list currently only has a single source, so you can just pull it directly:

* Project Link: https://github.com/Sinfonietta/hostfiles/blob/master/social-hosts
* Direct Link: https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/social-hosts

**Comment by yegors** [comment]
Thanks
