### ISSUE TITLE
unocero ads

### ISSUE THREAD

**Issue by brunoherrera** [StevenBlack/hosts#795]
[ unocero.com](https://www.unocero.com/gadgets/gracias-a-estas-usb-los-password-seran-cosa-del-pasado/amp/) google ads showing up

they show up in small res, in pc you need to do f12, toggle device toolbar (ctrl + shift + M) select Pixel 2 XL, then refresh the page and just in case you're also using abp extension, disable it.

![2018-10-05 15 30 25](https://user-images.githubusercontent.com/32912794/46554838-e1f06a80-c8b7-11e8-9735-ed7232f2072d.png)

![2018-10-05](https://user-images.githubusercontent.com/32912794/46554844-e74db500-c8b7-11e8-9a03-5ee1225ec048.png)

**Comment by StevenBlack** [comment]
Bruno @brunoherrera I'm not seeing this problem here, regardless of device width or emulation, Pixel 2 XL or otherwise.

**Comment by brunoherrera** [comment]
@StevenBlack ok, sorry I can't debug this further, but this doesn't happen to me when I use 1hosts.cf, only with your hosts

**Comment by StevenBlack** [comment]
Closing.
