### ISSUE TITLE
Didn't add new line on OSX

### ISSUE THREAD

**Issue by frankcash** [StevenBlack/hosts#799]
# Describe the Issue

The program didn't add a new line at the end of my `/etc/hosts` which rendered it useless

## OS

`Mac OS High Sierra`

## Python Version

`Python 3.6.5`

**Comment by StevenBlack** [comment]
@frankcash do you have steps to reproduce?

**Comment by frankcash** [comment]
I initiated virtual env
downloaded the requirements
then ran `python updateHostsFile.py`

This might not be reproducible.

**Comment by StevenBlack** [comment]
@frankcash can you provide exact steps, please?  Also the screen output.  Thanks.

**Comment by StevenBlack** [comment]
Closing.
