### ISSUE TITLE
Is it possible to exclude hosts sources?

### ISSUE THREAD

**Issue by 894-572** [StevenBlack/hosts#800]
https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant

I know that I can easily fork the repo, but I'd have to repeat the process when StevenBlack/hosts is updated. Excluding unwanted sources is preferred, tracking changes on unwanted lists and manually adding domains to the whitelist isn't convenient.

**Comment by StevenBlack** [comment]
Just run [updateHostsFile.py](https://github.com/StevenBlack/hosts/blob/master/updateHostsFile.py) whenever you want to refresh your hosts file.

Closing.

**Comment by 894-572** [comment]
@StevenBlack I think that you didn't answer the question. I may want to block on the hosts sources:

- Steven Black's ad-hoc list
- Malware Domain List
- add.Dead
- add.Spam
- Dan Pollock – someonewhocares
- MVPS hosts file
- yoyo.org
- Mitchell Krog's - Badd Boyz Hosts
- CoinBlocker
- lightswitch05
- UncheckyAds
- add.2o7Net
- KADhosts
- AdAway
- add.Risk
