### ISSUE TITLE
click.email.newegg.com doesn't work

### ISSUE THREAD

**Issue by ccfman2004** [StevenBlack/hosts#805]
I can't access this address with this hosts file.  This address is for viewing the Newegg sales that you get sent to your email.

**Comment by StevenBlack** [comment]
The domain `click.email.newegg.com` is not in our hosts files.  In fact, there's nothing related to vanilla `newegg.com` in any of the hosts files here.

Some curated sources block `neweggstats.com` and `www.neweggstats.com`.  It's hard to imagine this will change.

Closing.

**Comment by dnmTX** [comment]
`click.email.newegg.com ` redirects to **`click.virt.s6.exacttarget.com`** which is blacklisted that's why.
PING @lightswitch05 !!!

**Comment by ccfman2004** [comment]
I'll just comment that link out for now.

**Comment by lightswitch05** [comment]
I can take a look at adding the `click`  subdomains of exacttarget to the whitelist- or maybe move them to my aggressive list. Without a doubt they are tracking, but click implies interaction at least and not passive tracking

**Comment by ccfman2004** [comment]
Yes commenting out the specified address fixes the issue of not being able to view Newegg's email site.
