### ISSUE TITLE
my internet isnt working anymore using list

### ISSUE THREAD

**Issue by 0lm** [StevenBlack/hosts#806]
hi

updated post: okay now i waited a minute and now internet works again. i noticed when i turn off the hosts and turn on again, i always need to wait some time for connection to work again. and i did that occassionally because, for a reason i dont know, reddit.com is in the host list. problem is, i set up switchhost!, the software im using to merge the hosts with my original host, to regulary update stevenblack host file, so it will prob always add reddit.com back into hosts when a new update comes. any idea how to solve that issue with turning on/off hosts, so i dont need to wait several minutes for the connection to work again? -  i read bout it, it seems like a DNS client server thingy.

**Comment by StevenBlack** [comment]
Hi @0lm I'm sorry, I have nothing to suggest.

Closing.
