### ISSUE TITLE
Sling tv on roku

### ISSUE THREAD

**Issue by zeus4848** [StevenBlack/hosts#808]
dms.p.sling.com Caused sling tv to return error1-2.

**Comment by StevenBlack** [comment]
Thanks Zeus @zeus4848.

Ping, Daniel @lightswitch05.

**Comment by lightswitch05** [comment]
I just tested sling and you are right @zeus4848. Looks like they released an update to make it required since I last tested this block. Removed in https://github.com/lightswitch05/hosts/commit/eb6274cbe49a844b852b2d8d2ddf066332d66ab4

**Comment by StevenBlack** [comment]
Closing.
