### ISSUE TITLE
so what's up with securepubads.g.doubleclick.net?

### ISSUE THREAD

**Issue by patrickdrd** [StevenBlack/hosts#809]
I saw that my android device was able to access this url and
by searching I found out that it is commented on stevenblack hosts file and
while it is included in various other sources I use,
this comment overrides them, at least with hostsman I used for my tests,

anyway, after searching with google I found out that it was commented maybe because of spotify?
sorry, but I don't use spotify actually, so I'm not interested, 
is there any stevenblack version with this one uncommented?

**Comment by lightswitch05** [comment]
@patrickdrd MVPS's hosts is the source that has it commented out. The issues link for this hosts file in the README has `winhelp2002@gmail.com` has the way to submit issues. My list also has `securepubads.g.doubleclick.net` - but it is not commented out. So it is in the generated hosts twice, once commented out and once not. I don't use hostsman so I do not know how it responds to this behavior, but if you want the commented out one removed then you'll need to send a request to that email address. I use the Spotify web player and I have not had any issues with the domain blocked, but I know the different players have different behaviors.

**Comment by patrickdrd** [comment]
well, I found it commented here:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by lightswitch05** [comment]
@patrickdrd please read the README. The first paragraph:

> This repository consolidates several reputable hosts files, and merges them into a unified hosts file with duplicates removed. A variety of tailored hosts files are provided.

**Comment by patrickdrd** [comment]
ok, thanks a lot, I've emailed winhelp2002@gmail.com and told them to remove it,
however I've just built using adaway and the output file did include the line without comment

**Comment by bronger** [comment]
FWIW, the German newspaper https://rp-online.de/ detects adblocking by probing securepubads.g.doubleclick.net.
