### ISSUE TITLE
List breaks iCloud sign-in on MBP with Mojave

### ISSUE THREAD

**Issue by kurankat** [StevenBlack/hosts#810]
Just a heads-up that blocking some domains on this list breaks signing into iCloud and may lock you out of Apple accounts and/or devices.

I just spent a few hours troubleshooting why every Mac and iPhone in our house has been having problems signing into iCloud after the upgrade to macOS Mojave and iOS 12.

The issues have resulted everyone in the house being forced to change our Apple IDs thanks to Apple's automated security policy.

It finally occurred to me to check the pi-hole logs, and found that three Apple domains were being contacted every time one of the devices attempted to log into iCloud:

- cf.iadsdk.apple.com 
- iadsdk.apple.com
- metrics.icloud.com

After whitelisting these domains, we've been able to re-connect the various devices, so at least one of these (or all three) are involved in Apple authentication.

**Comment by lightswitch05** [comment]
I do not have Mojave yet, but I’ve had iOS 12 for a month now and I haven’t had any iCloud issues. Did it take all three whitelisted to get things working? Could you try to narrow it down more?

**Comment by kurankat** [comment]
Sorry, there are other people affected and I'm not prepared to break things through trial and error at this stage. Once the general annoyance dies down, I'll have a crack.

Also, I can't say with certainty whether this is specific to Mojave or to a system update in general (resetting keychains?).

My suspicion is that metrics.icloud.com is probably not involved in authentication, though it was also being accessed each authentication attempt. I'll try re-blacklisting this domain first.

**Comment by kurankat** [comment]
As soon as I have time I'll try them one by one.

**Comment by lightswitch05** [comment]
@kurankat Any updates on this? Anyone else having issues?

**Comment by StevenBlack** [comment]
@lightswitch05 this is working fine for me, on MBP and iMac.

Closing.
