### ISSUE TITLE
iOS Telemetry Domains

### ISSUE THREAD

**Issue by cedws** [StevenBlack/hosts#811]
A while ago, I collected a list of domains used for telemetry by Apple on iOS. The repository is [here](https://github.com/c-edw/ios-telemetry). I think the goal of this project is more to block ads and other unwanted garbage rather than to block telemetry, but I thought I would raise an issue in case anybody has been looking for this.

**Comment by anudeepND** [comment]
@c-edw You are blocking way too many legit domains, some of them include `api.weather.com`, `weather.com` and Apple website too, both `apple.com` and `www.apple.com`.

**Comment by c-edw** [comment]
@anudeepND It's intentional. The Weather app on iOS is irremovable and contacts `api.weather.com`, sending your location whatever settings you have, so I consider this telemetry. As mentioned in the README, if somebody wants to use it, then it's their responsibility to remove the domains they don't want to block.

**Comment by anudeepND** [comment]
@c-edw I agree. We have to cherry pick the domains and add them to the list.

**Comment by lightswitch05** [comment]
I haven’t had an iPhone for long, but it looks like its removable. Am I missing something? 

https://i.imgur.com/VEEMMhH.jpg

**Comment by c-edw** [comment]
You're right, I just checked. I'm probably thinking of another app. There's other built-in apps with telemetry that really are irremovable, though.

**Comment by llacb47** [comment]
I made a fork of this repo and removed domains that cause breakages and I found are needed for iOS on iPhone. 
https://github.com/llacb47/apple-telemetry/blob/master/blacklist
