### ISSUE TITLE
Add iCloud Spear Phishing Regex

### ISSUE THREAD

**Issue by jhabdas** [StevenBlack/hosts#817]
Lost iPhone Spear Phishing Website: https://icloud.com-locations.in/?uid=e7XsV

I've got a dozen or so more for the regex. Here's my source: https://telegram.me/comfusion/953

**Comment by StevenBlack** [comment]
Chrome confirms this.

![2018-11-06_15-34-53](https://user-images.githubusercontent.com/80144/48092187-fe930180-e1d9-11e8-91ec-fbf9d18c1082.jpg)
