### ISSUE TITLE
Problems with the list

### ISSUE THREAD

**Issue by Havokdan** [StevenBlack/hosts#818]
Good morning, I use an application called [Host File Editor] (https://hostsfileseditor.weebly.com) to update the hosts, I noticed that my antivirus activates every time I use your list (+ fakenews + gambling). (Dead, Net, Risk, Spam), I noticed that however the antivirus only acts when I add it to your complete list (+ fakenews + gambling), or when adding Risk or Spam separately. Can you solve it? I use Windows 10 pro with Kaspersky Internet Security 19.0.0.1088 (c).

https://i.imgur.com/Xwk4y0r.png

**Comment by Atavic** [comment]
[Support Forum](https://forum.kaspersky.com/index.php?/topic/381506-improve-the-handling-of-hosts-file-on-windows/):

>  The "workaround" answers are all the same ...one needs to "make sure to add the HOSTS file to the exclusion list". 

Related: https://github.com/StevenBlack/hosts/issues/643

**Comment by spirillen** [comment]
@Havokdan That's actually a good thing... it's prove your antivirus program is working properly and do what is to be expected.

In a good antivirus program however you would be able to ad exclusions, here you should be able to add the %system32%/etc/hosts or %windir%/system32/etc/hosts (be aware they might be a typo as i don't use any microsoft myself)

Third option is to support a nonprofit project like http://www.mypdns.org (alpha stadium) and then point all your devices to an external DNS server blocking the same domains as all of these lists does, inclusive the newest threads (alpha), the benefit of this is, all your devices incl. your TV, radio and other IOT are protected from privacy harvesting....

**Comment by funilrys** [comment]
@pi-hole might be a good thing to look at (foor the third option) @spirillen.

**Comment by spirillen** [comment]
> @pi-hole might be a good thing to look at (foor the third option) @spirillen.

:) yes it crossed my mind after hitting the send comment....

**Comment by spirillen** [comment]
> > @pi-hole might be a good thing to look at (foor the third option) @spirillen.
> 
> :) yes it crossed my mind after hitting the send comment....



> @pi-hole might be a good thing to look at (foor the third option) @spirillen.

Absolutely, but pi-hole is mostly a inhouse DNS server thing.... and everyone have to run there own separate instance (here is though of time, and power) for what can be done by a 1gb 1cpu VPS for like 1000's of users
