### ISSUE TITLE
Exact Python version requirement?

### ISSUE THREAD

**Issue by xstnztk** [StevenBlack/hosts#820]
I noticed that several readme files (e.g. readme.md, readme_template.md) now say that Python version **3.7** is required to generate one's own hosts file whereas the first line in readme.md says that version **3.5+** is required.

I just used the default Python **3.6.6** on Ubuntu 18.04 to generate my hosts file with all extensions, and it seemed to work just fine. I think it would be useful to determine exactly which Python version is required so that people do not feel pressured to try to install a new version although their existing one would have worked anyway.

Does perhaps only certain functionality actually require version **3.7**? In this case it would be helpful to document this so that people can decide for themselves if this functionality is worth the effort to install a new Python version on their system.

**Comment by StevenBlack** [comment]
Merged in pr #821.  Closing.

**Comment by StevenBlack** [comment]
@xstnztk all readme files, including the root readme, are generated based on readme_template.md.
