### ISSUE TITLE
Merge with current /etc/hosts 

### ISSUE THREAD

**Issue by NightMachinary** [StevenBlack/hosts#823]
Add a -merge flag that merges the end result with the current /etc/hosts, giving priority in case of conflicts to /etc/hosts if invoked with 1, or to the script’s result in case of 0. Assume 1 if no input is given to the flag.

**Comment by StevenBlack** [comment]
@NightMachinary interesting idea.

We'd have to make it re-entrant, so we wouldn't end up with a double-merge on the second execution.

**Comment by NightMachinary** [comment]
What’s re-entrant?
I was thinking that we should put our output between two #BlackHostsBegin
#BlackHostsEnd, delete conflicting existing hosts if we have priority, or
delete conflicting hosts from out output if we don’t. On the next run, we
just don’t pay attention to this black hosts section when merging.
