### ISSUE TITLE
Why blocking random KryptoSites?!

### ISSUE THREAD

**Issue by lenusch** [StevenBlack/hosts#827]
Hi, why blocking all dascoin Sites 
dascoin, daswallet, das33.io and so on......... 
on PORN List?!
I took an hour to find this today.

**Comment by dnmTX** [comment]
@lenusch  it's actually KADhosts who's blocking them.You can open a [ISSUE](https://github.com/azet12/KADhosts/issues) there and discuss it further.

**Comment by dnmTX** [comment]
@lenusch  you can close this if you want as i see you got response from KADHosts and truth to be told,no one here can help you with your problem anyway.
