### ISSUE TITLE
Hungarian fake news and propaganda sites

### ISSUE THREAD

**Issue by rapliandras** [StevenBlack/hosts#828]
List of most commonly known Hungarian fake news and government propaganda sites:

```
origo.hu
888.hu
lokal.hu
ripost.hu
faktor.hu
magyaridok.hu
pestisracok.hu
```

I didn't want to extend this list too far but these sites produce fake news and lies in overwhelming majority. There are more if anyone requests it.

**Comment by StevenBlack** [comment]
Thank you Rápli @rapliandras!

Mark @marktron can you advise?

Rápli, Mark is our fake news curator.

**Comment by Biorazero** [comment]
@rapliandras so you got elected as the judge, jury and executor by whom?

**Comment by StevenBlack** [comment]
Ping @marktron...

**Comment by marktron** [comment]
@rapliandras I took a look at these sites but I don't see anything immediately obvious that would stand out as misleading or propaganda. But I had to rely on Google Translate and don't have a deep knowledge of Hungarian politics and culture so I'd definitely appreciate some more context.
