### ISSUE TITLE
Give preference to [Unified Hosts AutoUpdate]

### ISSUE THREAD

**Issue by Konfekt** [StevenBlack/hosts#829]
Regarding the section
```
## Updating hosts file on Windows
```
there is a single line at the end of it that points towards other solutions after recommending 
```
updateHostsWindows.bat
```
However, [Unified Hosts AutoUpdate](https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate "Unified Hosts AutoUpdate") by @ScriptTiger brought several advantages on my Windows 10 installation, such as

- replacing the system host file by a host file that left DNS lookup working (perhaps by using `CRLF`?),
- offering to add extensions (gamble, social, ...),
- offering to schedule the update, and
- not requiring the installation of a Python distribution and additional packages such as `beautifulsoup4`. 

Therefore, perhaps the `Windows 10` user should be hinted first towards 

[Unified Hosts AutoUpdate](https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate "Unified Hosts AutoUpdate")

and then to 

```
updateHostsWindows.bat
```

**Comment by Konfekt** [comment]
@StevenBlack Won't this be fixed or would such a pull request be welcomed?

**Comment by StevenBlack** [comment]
I don't understand.

We mention both.   Are you quibbling about the order of presentation?  Of course this repo's native assets come first.  I don't see a problem here.

Closing.

**Comment by Konfekt** [comment]
Yes, this issue is about the order of presentation. The suggestion was to mention  [Unified Hosts AutoUpdate](https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate "Unified Hosts AutoUpdate") by @ScriptTiger first because it brought several advantages on my Windows 10 installation, such as

- replacing the system host file by a host file that left DNS lookup working (perhaps by using `CRLF`?),
- offering to add extensions (gamble, social, ...),
- offering to schedule the update, and
- not requiring the installation of a Python distribution and additional packages such as `beautifulsoup4`.
