### ISSUE TITLE
Can I use this in AdAway?

### ISSUE THREAD

**Issue by zedascouves** [StevenBlack/hosts#83]
So not really an issue, more of a question. Can I had this host file to my AdAway sources? If yes, what URL should I use?
Thank you for this in any case!

**Comment by StevenBlack** [comment]
Yes :-)

URL to use would be [the raw versiom](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) at https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts.

I'm considering a new folder named `output` with subfolders for various versions, for instance `0.0.0.0` vs `127.0.0.1` and others like perhaps a gonzo-maxi version with 10^6 hosts, and surely others.  All regenerated daily with a chron job.

But for now, yeah, https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by Gitoffthelawn** [comment]
Do you mind if I reference this thread in the AdAway repo, for anyone interested?

**Comment by StevenBlack** [comment]
Please do.

**Comment by zedascouves** [comment]
Thanks for the reply. I did try that, but in AdAway's host sources section says "Online: not availabe". Is this a problem in AdAway or maybe it needs to point to an actual file URL.

**Comment by JonnyTech** [comment]
I did ask in the AdAway repo [(How To Import a hosts sources from the github??)](https://github.com/Free-Software-for-Android/AdAway/issues/700#issuecomment-183729282) but have had no reply yet.

**Comment by StevenBlack** [comment]
I have a question: considering that one of my sources is [AdAway](https://github.com/StevenBlack/hosts/tree/master/data/adaway.org), and if AdAway includes this repo, does this create a sigularity in the space-time vortex?

**Comment by Gitoffthelawn** [comment]
@StevenBlack 
In theory, it most certainly does. ;-)

I'm convinced this directly explains the missing sock in today's laundry.

In actuality, I think it results in a little wasted time as AdAway finds all the duplicates and removes them.

Now whether that's *wasted* time, or *missing* time is another discussion...

**Comment by JonnyTech** [comment]
Hehe..., indeed AdAway does remove duplicates, but why use AdAway to do that when it has been done here anyway - so I would like to just use this source as my starting point.

**Comment by Gitoffthelawn** [comment]
@JonnyTech I can think of a handful of reasons why someone may choose to use AdAway:

1. Integrate additional lists not included with this one.
2. Simplicity of updates via an app.
3. Easy whitelisting.
4. Easy redirection to a local webserver.
5. Logging of DNS requests.

**Comment by StevenBlack** [comment]
Closing.

**Comment by 07416** [comment]
When I add raw URL to AdAway, data is only downloaded from Github right? AdAway updates hosts file **every day** (in comparison, uBlock Origin only updates **every four days**) - hits servers hard, I'd rather only use Github.

**Comment by Gitoffthelawn** [comment]
@07416 You can set AdAway to only perform updates when you manually initiate them.

**Comment by Gitoffthelawn** [comment]
@StevenBlack Any chance you'll get https up and running on `sbc.io`?

**Comment by StevenBlack** [comment]
Hi @Gitoffthelawn, It's on my list!
