### ISSUE TITLE
Malware Domain List Down

### ISSUE THREAD

**Issue by remtcsbackup** [StevenBlack/hosts#832]
It appears that the Malware Domain List is now offline?

**Comment by StevenBlack** [comment]
Hi @remtcsbackup, this appears to be a https-related issue since it works under http.

**Comment by spirillen** [comment]
Just tested https://www.malwaredomainlist.com/hostslist/hosts.txt and it's up and running again.
This should be closing #832

**Comment by StevenBlack** [comment]
Thank you @spirillen.

Closing.

**Comment by spirillen** [comment]
Your welcome @StevenBlack and thx for a great program....
