### ISSUE TITLE
whitelist promodj.com

### ISSUE THREAD

**Issue by jimdi** [StevenBlack/hosts#833]
promodj.com is ok, that's not bad site =)

**Comment by StevenBlack** [comment]
Hi Jim @jimdi, `promodj.com` is not presently listed here 🤔 

Closing.  Not our bug 😄

**Comment by jimdi** [comment]
hmm, thx. need to check update

**Comment by funilrys** [comment]
It used to be into the list. 
I fixed it at https://github.com/mitchellkrogza/Badd-Boyz-Hosts/issues/56.
