### ISSUE TITLE
Exacttarget is not porn

### ISSUE THREAD

**Issue by atp0303** [StevenBlack/hosts#835]
exacttarget.com and other variants is added in porn blocklist.  I believe this is not the case as exacttarget.com is a Salesforce owned domain.

**Comment by StevenBlack** [comment]
Hi @atp0303 the `exacttarget.com` domains aren't flagged here as porn. None of our porn curators list `exacttarget.com`.

A metric crapton of `exacttarget.com` domains are flagged by several of our curators for a variety of nefarious behaviors.

I would say the odds of successfully appealing on behalf of `exacttarget.com` are close to zero, at this juncture.

Ping Daniel @lightswitch05.

Closing.

**Comment by lightswitch05** [comment]
Yup, they do targeted advertising, which means they are a perfect 👌 fit for my ads and tracking list

**Comment by atp0303** [comment]
But targeted advertising should go in the ad block list and not the porn block list?  There are legitimate needs to block porn sites but allow targeted ads.

**Comment by atp0303** [comment]
> Hi @atp0303 the `exacttarget.com` domains aren't flagged here as porn. None of our porn curators list `exacttarget.com`.
> 
> A metric crapton of `exacttarget.com` domains are flagged by several of our curators for a variety of nefarious behaviors.
> 
> I would say the odds of successfully appealing on behalf of `exacttarget.com` are close to zero, at this juncture.
> 
> Ping Daniel @lightswitch05.
> 
> Closing.

But i can find the `exacttarget.com` in this list:
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts

**Comment by StevenBlack** [comment]
@atp0303 the [readme](https://github.com/StevenBlack/hosts/blob/master/readme.md#unified-hosts-file-with-base-extensions) is pretty clear on this, I think.

The porn list (all variations of it) include the base list of scumbag domains.

If you want just a list that blocks porn, then use one of our [sources](https://github.com/StevenBlack/hosts/blob/master/alternates/porn/readme.md#sources-of-hosts-data-unified-in-this-variant) that specialize in that.  Each one of our variants has its own readme page.  Just search for `porn` in the list of sources used in any of our variants that include porn.
