### ISSUE TITLE
Delete nespresso.com from blocklist

### ISSUE THREAD

**Issue by maciboy** [StevenBlack/hosts#838]
Hi,
it seems as if Nespresso.com was added to the blocklist recently.

I wanted to order some coffee but was unable to open the side,
here is what my pi-hole told my when investigating:
 _Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   www.nespresso.com_

Was there a specific reason for that?
Please remove it if possible…

For now I put it on my whitelist manually.

**Comment by lightswitch05** [comment]
@maciboy I'm not able to find that domain anywhere in the list. Can you please recheck it?

**Comment by maciboy** [comment]
@lightswitch05 
Wow, you are right - I did not manually search through the latest version of the list…
Now, I manually let my pi-hole update its filter lists and the match is gone :D
Seems as if Nespresso.com was in that list before?!

Anyway, problem solved - should have made these steps in advance, sorry!
