### ISSUE TITLE
Walmart shipment tracker blocked

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [StevenBlack/hosts#841]
Walmart sends a tracking link in shipping confirmation emails that link to rptrcks.walmart.com.
Those links don’t work unless that hosts entry is removed.

The one I received was 
http://rptrcks.walmart.com/comm-smart-app/services/tracking/clickTracker?redirectTo=yz3xZ3tgQ4NiEKBECwFj6uhZaVaimA3NA9907I%2F4a5gRjDVI50ljjCjJOYgOTmw4rA6s5DZWIMYed4MJ%2FegrVqup0voLSueh4Jwov0zBbKvXUQFbIYQmk0%2FfQ%2B6kP4LwF2yDIc0E6k%2 **followed by about 1000 more characters.**

Obviously those links are very useful and millions of people use them.
Do they really need to be blocked?

Don’t tell me to report it to some list’s owner, because there a lot of 'em and who knows where it originated?

It’s in _your_ merged lists, I don’t know where you got it.
But I assume your algorithm can omit it as it does with duplicate entries.

**Comment by dnmTX** [comment]
PING @lightswitch05

**Comment by GitTheHellOutaHere** [comment]
Your cryptic reply is meaningless to me.

**Comment by lightswitch05** [comment]
Happy thanksgiving! This was in my list, thanks @dnmTX for getting my attention. This was the first update I’ve done entirely on my phone through SSH, can’t say it was a fun experience. Sorry about the false positive, maybe @GitTheHellOutaHere can lighten up a little now that it’s fixed. Where is my holiday pay 💰 😂

**Comment by StevenBlack** [comment]
Thanks everybody!  Closing.
