### ISSUE TITLE
mediadelivery.fi incorrectly blocked

### ISSUE THREAD

**Issue by theel0ja** [StevenBlack/hosts#846]
Breaks `hs.fi` and `hs.fi`.

**Comment by lightswitch05** [comment]
I removed the `mediadelivery.fi` root domain and all subdomains except for `is.mediadelivery.fi` in commit https://github.com/lightswitch05/hosts/commit/033ac17fbe7d4ab7e6498634687bae9f8b30c40e. As far as I can tell that fixes the website. Please let me know if you have more issues with `is.mediadelivery.fi` still being blocked.

**Comment by theel0ja** [comment]
Why is `is.mediadelivery.fi` blocked? `www.is.fi` uses them for the images.

**Comment by theel0ja** [comment]
<img width="748" alt="screen shot 2018-11-29 at 21 47 56" src="https://user-images.githubusercontent.com/5832930/49247648-755d9c00-f420-11e8-8f18-fcfdc2678fff.png">

**Comment by lightswitch05** [comment]
I don't remember why I blocked it initially and unfortunately I didn't have a useful commit message. I removed `is.mediadelivery.fi` in https://github.com/lightswitch05/hosts/commit/727db1981f3a56724acf7ad9e17fb43cb99598bf

**Comment by StevenBlack** [comment]
Fixed in the latest release.  Thanks everybody!
