### ISSUE TITLE
goooooooooogle.com should be blocked

### ISSUE THREAD

**Issue by LightningProd** [StevenBlack/hosts#851]
goooooooooogle.com is an adware site that does nothing except redirect you to a doubleclick ad.

Can it be listed in the hosts file too?
```0.0.0.0 goooooooooogle.com```

**Comment by johnaschmitt** [comment]
I run a hosts file on my router. When ads started appearing everywhere I was afraid the jig was up! Added this and they went away. I hope this doesn’t turn in to a whack-a-mole situation.

**Comment by StevenBlack** [comment]
Thanks everybody!  This will be in the next release.
