### ISSUE TITLE
Issues when logging/authorizing-chrome-extension on Tempo plugin from Jira

### ISSUE THREAD

**Issue by well1791** [StevenBlack/hosts#853]
Right now I'm not sure what domain is causing problem but, so far I've been struggling with this since yesterday and that was solved today by removing temporarily the `hosts` file (ad + malware), and then logging in. At the moment I'm still using the `hosts` file and I haven't had any other issues (although the console is full of errors).

However, I'll be checking this issue again during this week but, I just wanted to open the ticket if anyone else is having the same issues.

Btw, thanks for this project!

**Comment by spirillen** [comment]
You should open the dev-tool in your browser and look under the network tab and see which domains that ain't loading (404)
But it seems like you have something like bitbucket or atlassian.com in your hosts file.

Can you verify any of my suspected domains?
