### ISSUE TITLE
pixel.nymag.com blocks all of the pics on nymag.com

### ISSUE THREAD

**Issue by jawz101** [StevenBlack/hosts#855]
example page: http://nymag.com/intelligencer/2018/12/internal-emails-show-facebooks-focus-on-self-preservation.html

There should be a pic of The Zuck in the middle of the page playing on his cell phone.

**Comment by dnmTX** [comment]
Confirming that the domain in question delivers only images(at least on nymag.com).
PING @lightswitch05 
![capture](https://user-images.githubusercontent.com/34774426/49837156-0b6fbb80-fd6b-11e8-9b6f-b13485836bf1.PNG)

**Comment by lightswitch05** [comment]
Thanks for the heads up @dnmTX - I’m away from computer at the moment, but I’ll address it as soon as I can

**Comment by lightswitch05** [comment]
Removed in commit https://github.com/lightswitch05/hosts/commit/5a7ea09da8aa69384e3f7753310667a945d0f49f - sorry about the false positive

**Comment by jawz101** [comment]
np.  Anytime I see pixel.something I think the same thing.
