### ISSUE TITLE
Using with SOCKS5

### ISSUE THREAD

**Issue by pemyunupa** [StevenBlack/hosts#857]
I've recently started using my VPN provider's SOCKS5 on Firefox in conjunction with their WireGuard VPN servers. The result has been a significant speed increase as well as reduced CAPTCHAs.

The problem, of course, is that its bypassing my beloved hosts. Even with the usual privacy-focused Firefox extensions, I still feel uncomfortable. But I really want to keep the SOCKS5 for the reasons above.

Is there any way around this for me?

**Comment by lightswitch05** [comment]
You can use hosts lists with [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) for FireFox
