### ISSUE TITLE
sporcle.com is blocked

### ISSUE THREAD

**Issue by Ha3iSeldon** [StevenBlack/hosts#858]
I have the file which contains "Unified hosts + fakenews + gambling + porn + social" Don't think sporcle falls under any of that

**Comment by StevenBlack** [comment]
Hi @Ha3iSeldon.  The specific domain, `sporcle.com`, is not blocked by the hosts files in this repo.

We block `sporcle-tagan.adlightning.com` but that's not the domain you mention.

Closing.
