### ISSUE TITLE
whitelist

### ISSUE THREAD

**Issue by patrickdrd** [StevenBlack/hosts#860]
the following are wrongly in hosts file and should be whitelisted in my opinion:

> a.kickass.to
> adf.ly
> adfoc.us
> cdn.onesignal.com
> cdn.optimizely.com
> cdn3.optimizely.com
> cfvod.kaltura.com
> com.com
> cookie.monster.com
> d2c8v52ll5s99u.cloudfront.net
> device-metrics-us-2.amazon.com
> device-metrics-us.amazon.com
> fls-na.amazon.com
> g.msn.com
> googletagservices.com
> h-sdk.online-metrix.net
> jwpltx.com
> mobile.pipe.aria.microsoft.com
> mywot.com
> nexusrules.officeapps.live.com
> oas.monster.com
> om.cbsi.com
> piwik.org
> pixel.quantserve.com
> s.shopify.com
> s.youtube.com
> s.zkcdn.net
> s2.youtube.com
> serials.ws
> settings-win.data.microsoft.com
> softonic.com
> traffic.spot.im
> unk.vver.kiae.rr
> v10.events.data.microsoft.com
> v10.vortex-win.data.microsoft.com
> viglink.com
> www.googletagmanager.com
> www.googletagservices.com
> www.hotspotshield.com
> www.mywot.com
> www.serials.ws
>

**Comment by StevenBlack** [comment]
Hi Patrick @patrickdrd.   We're an aggregator.  We find high quality, well-curated hosts lists, merge them, dedupe the resultant list, and try to keep the list frequently updated and reasonably sized.  

We also adjudicate and petition, to some degree, with the curators, who may or may not agree with us.

Please take this up with [individual curators](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant) as I can't see the compelling reasons you may have, so I'm not inclined to petition for any of these.

**Comment by dnmTX** [comment]
@patrickdrd reading trough your list....led me to this:
![Alt Text](https://media3.giphy.com/media/Z8WX4rUQZvRhS/giphy.gif)

**Comment by anudeepND** [comment]
@patrickdrd oh boi! That's lot of ad domains!

**Comment by StevenBlack** [comment]
![imb_20181218010252_llih](https://user-images.githubusercontent.com/80144/50135177-383b3b80-0261-11e9-90dc-ec35b73490de.gif)

**Comment by patrickdrd** [comment]
well,
these are yours:

> cfvod.kaltura.com
> device-metrics-us-2.amazon.com
> device-metrics-us.amazon.com
> h-sdk.online-metrix.net
> mobile.pipe.aria.microsoft.com
> mywot.com
> nexusrules.officeapps.live.com
> s.zkcdn.net
> v10.events.data.microsoft.com
> v10.vortex-win.data.microsoft.com
> www.googletagmanager.com
> www.googletagservices.com
> www.mywot.com
>

**Comment by anudeepND** [comment]
@patrickdrd Unblocking googletagservices.com and googtagmanager.com will enable over 50% tracking on the internet. What makes you think it's safe to whitelist?

From Wikipedia:
`Google Tag Manager is a tag management system created by Google to manage JavaScript and HTML tags used for tracking and analytics on websites.`

**Comment by patrickdrd** [comment]
I've posted explanation here:
https://github.com/EnergizedProtection/block/issues/53#issuecomment-447883375

**Comment by patrickdrd** [comment]
> OK....i'll try to suppress my emotions....but still:
> ![Alt Text](https://camo.githubusercontent.com/4d5073c9d1d445ab125b89a7c94ee480bbf2b9a2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f47707953316c4a584a597570472f67697068792e676966)

f off already man, if you're not willing to help, stop posting bs, enough!

**Comment by patrickdrd** [comment]
very weird people around here?, 
not to say anything worse...

**Comment by patrickdrd** [comment]
I've got my own whitelist (1800 entries) and the above are in my whitelist for quite some time,
I thought about posting here to contribute to the community,
and I didn't expect at all those shitty reactions!

**Comment by dnmTX** [comment]
> I've got my own whitelist (1800 entries) and the above are in my whitelist for quite some time,
> I thought about posting here to contribute to the community,
> and I didn't expect at all those shitty reactions!

![Alt Text](https://giphy.com/gifs/onechicago-nbc-season-7-chicago-fire-vcKEsYOdjoCeJRpn95)

**Comment by patrickdrd** [comment]
@dnmTX please do me a favor and go somewhere else to masturbate, please buddy!

**Comment by anudeepND** [comment]
@patrickdrd Posting a bunch of domains and telling to whitelist them is not going to help unless a valid reason is given. 

I agree that `cdn.optimizlely.com` doesn't do tracking or send any analytics data. But `v10.vortex-win.data.microsoft.com` is used to send diagnostic data to Microsoft.

This is what the documentation states:
```
The Microsoft Data Management Service routes data back to our secure cloud storage. Only Microsoft personnel with a valid business justification are permitted access.

The following table defines the endpoints for Connected User Experiences and Telemetry component:

Diagnostics data: v10.vortex-win.data.microsoft.com/collect/v1

Windows Advanced Threat Protection is country specific and the prefix changes by country for example: de.vortex-win.data.microsoft.com/collect/v1
settings-win.data.microsoft.com
```

Read more about it [here](https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization).

Did you know that softoic tried (and failed) to bundle adware with their own installer?
[Source 1](https://www.esecurityplanet.com/malware/softonic-delivers-adware.html)
[Source 2](https://www.intego.com/mac-security-blog/softonic-download-site-briefly-delivers-trojan-adware-installer/)

Did you know that Quantserve, a product of Quantcast is the biggest audience targeting or targeted advertising company? 
Read more about it [here](https://www.theguardian.com/technology/2012/apr/23/quantcast-tracking-trackers-cookies-web-monitoring)

This is just a few example of the domains present in your so called "whitelist".

> @dnmTX please do me a favor and go somewhere else to masturbate, please buddy!

Provide some information about those domains instead of posting rubbish comments like this.

Have a nice day!

**Comment by patrickdrd** [comment]
instead of attacking my rubbish comments, you should attack your friend for filling the whole issue/page with his bullshit and which was the originator of all this...
but, I know, we never attack our friends, attacking a stranger is much easier... makes sense...

well, in my research the above domains are needed in various functions,
if I find it I'll post here,
I mean, blocking tracking is one thing, preventing the user from doing his job is another and
in my opinion the second comes first and should always come first..

**Comment by patrickdrd** [comment]
https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

**Comment by patrickdrd** [comment]
you see, clever guy,
the answer is never that simple and one should be very careful when blacklisting important urls!

because github and the internet is full of shitty lists

**Comment by patrickdrd** [comment]
Windows10 Update

Without the follwing Whitelist Entrys Windows10 update can’t be completed.
Default is blacklisting.

pihole -w settings-win.data.microsoft.com 
pihole -w v10.vortex-win.data.microsoft.com 

ok, go ahead and block the user's windows update, good job!

**Comment by dnmTX** [comment]
Windows Update is working just **FINE** here:
![Alt Text](https://i.imgur.com/8k6SHrC.gif)

***NEXT PLEASE...***

**Comment by anudeepND** [comment]
@patrickdrd Hold your horses,

Windows updates are never delivered via those domains. 

Microsoft documentation: 
```
Windows Update

The following endpoint is used for Windows Update downloads of apps and OS updates, including HTTP downloads or HTTP downloads blended with peers. If you turn off traffic for this endpoint, Windows Update downloads will not be managed, as critical metadata that is used to make downloads more resilient is blocked. Downloads may be impacted by corruption (resulting in re-downloads of full files). Additionally, downloads of the same update by multiple devices on the same local network will not use peer devices for bandwidth reduction.

The following endpoints are used to download operating system patches and updates. 

*.prod.do.dsp.mp.microsoft.com
*.windowsupdate.com
fg.download.windowsupdate.com.c.footprint.net
cds.d2s7q6s2.hwcdn.net
*wac.phicdn.net
*wac.edgecastcdn.net
*.tlu.dl.delivery.mp.microsoft.com.c.footprint.net
emdl.ws.microsoft.com
fe2.update.microsoft.com
fe3.delivery.mp.microsoft.com
fe3.delivery.dsp.mp.microsoft.com.nsatc.net
*.dl.delivery.mp.microsoft.com
sls.update.microsoft.com
tsfe.trafficshaping.dsp.mp.microsoft.com
a122.dscd.akamai.net
a1621.g.akamai.net
```

[Link](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints)
And this documentation is up to date with 1809 October update.

It is **clearly** mentioned here that,
`v10.vortex-win.data.microsoft.com/collect/v1` and `settings-win.data.microsoft.com` are used for collecting diagnostic data.

[Link](https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization)

I'm not posting this from thin air. It's from Microsoft itself.

**Comment by dnmTX** [comment]
Steve @StevenBlack  apologize up front as it's not related to the issue at hand here but it's just....
**TOO CUTE**:
![Alt Text](https://media3.giphy.com/media/xUA7bjSfizVAqDSWWc/giphy.gif)

**Comment by patrickdrd** [comment]
ok, ok, but the guys at discourse.pi-hole.net posted it, not me, anyway..

**Comment by StevenBlack** [comment]
Thanks, everyone, for you’re input on this.

This didn’t go very well so let’s learn from this, and move on.

Closing.

**Comment by sido420** [comment]
Can we at least put cdn.onesignal.com in whitelist? See the discussion in referenced issue.

**Comment by dnmTX** [comment]
no one **thumbs-upped** my **Kitty GIF**.That's just SAD  😢

**Comment by agneevX** [comment]
Whitelisting `onesignal.com` restored macOS Safari push notifications functionality for me.

**Comment by Laicure** [comment]
This was already closed.

Anyway.
This repo is just an aggregator and it is not this repo's fault why are those blocked. (we just hate tracking, ads and such, right?)
I am using [this (from Energized)](https://github.com/EnergizedProtection/unblock/raw/master/basic/formats/domains.txt) to unblock possible device/functionality breaking domains.

The only data source here that we can do reporting here is @StevenBlack's [own list](https://github.com/StevenBlack/hosts/tree/master/data/StevenBlack), that's the one he personally maintains while the others should not be reported here. (that's why the data sources has the update.json file that contains the issue link for their respective sites/repo)

I think @StevenBlack can remove (or move to a separate repo so this repo is not flooded with whitelist/blacklist issues) the generated hosts file altogether so the py tool is only left for usage.

**Comment by JAKAMI99** [comment]
https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/giphy.gif

That issue talk is just gold...

**Comment by JAKAMI99** [comment]
`<iframe src="https://giphy.com/embed/3oEjHI8WJv4x6UPDB6" width="480" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/smile-clap-laff-3oEjHI8WJv4x6UPDB6">via GIPHY</a></p>`


This issue talk is just gold

**Comment by JAKAMI99** [comment]
![](https://media0.giphy.com/media/3oEjHI8WJv4x6UPDB6/giphy.gif)

This issue talk is just gold ^^
