### ISSUE TITLE
Questions about YouTube’s urgent need to fix

### ISSUE THREAD

**Issue by LBBear** [StevenBlack/hosts#861]
After using this hosts, YouTube watch history can't be displayed.
My English is very poor, please forgive if the title is offensive.

**Comment by LBBear** [comment]
This problem has only appeared in the last week or two. There was no problem before.

**Comment by anudeepND** [comment]
@LBBear you need to whitelist `s.youtube.com` in order to record watch history.

**Comment by StevenBlack** [comment]
@LBBear I don't think this will change.  The domain `s.youtube.com` comes to us via `yoyo.org` and `someonewhocares.org`.  Both are respected curators.

Closing.
