### ISSUE TITLE
Found many unblocked porn sites

### ISSUE THREAD

**Issue by Schanzation** [StevenBlack/hosts#862]
Hello! I am using this filter.

https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/Steven-Blacks-Porn.txt

mypornbible.com is unblocked. But if you go to that site there are listed plenty of websites that are unblocked by the porn filter. Hope they will be blocked later. thnx

**Comment by StevenBlack** [comment]
Hi @Schanzation despite the URL, this is not related to this repo or to me.  It appears to be a copy of some sort?  You need to query user @deathbybandaid about this. 

Looks to me like mypornbible.com isn't a porn site.  It's a directory of porn sites.  

Closing.

**Comment by StevenBlack** [comment]
Ping @sinfonietta, maybe cross-check mypornbible.com's links?   I leave this up to you.
