### ISSUE TITLE
Question: Complete Generated List?

### ISSUE THREAD

**Issue by 0pLuS0** [StevenBlack/hosts#863]
Hello,

For someone that just wants to get a complete list of everything, this is all we need to download?

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Thanks

P.S. Really great Repo, keep up the great work!

**Comment by StevenBlack** [comment]
Hi @0pLuS0 the complete list with everything would be `Unified hosts + fakenews + gambling + porn + social`, here's the raw link for that: 
  https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

**Comment by 0pLuS0** [comment]
Digging through the History doesn't make it easy to understand if you simply use all of Dan's entries he uses?

Also I saw that link, https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

This looks like the one you are talking about at the Top of the Readme, but then you pointed me to a different link;

https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

Home link has 66052 lines.
Extensions link has 80492, which clearly shows this has more, so not sure why you are saying this is a host with everything in it?

**Comment by StevenBlack** [comment]
@0pLuS0 I don't understand what's unclear.

The base hosts file has its own readme here:

**Comment by 0pLuS0** [comment]
These are not the same, the first link is the one you are talking about at the top of the Readme correct?

```Here's the raw hosts file with base extensions containing 63,643 entries.```
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Then I asked if you had a host file with everything in it, and you pointed me to this link;

https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts

So now the question is, that second link you showed me with everything in it, is this listed on the Home too?

Sorry, I thought I made all this clear when I was asking, that I was simply looking for a link with a host file that had everything in it and you gave me that one. So now all I'm asking is this listed on the Home section to under the Readme? Because I have been looking but don't see.

So I hope I made it more clear now?

THANKS

**Comment by StevenBlack** [comment]
@0pLuS0 this list is on the home page readme, and in every other readme of this repo.  Each variant has its own readme.

![2018-12-24_00-28-19](https://user-images.githubusercontent.com/80144/50391462-66ae9000-0713-11e9-9580-4f97f44f5eaf.png)
