### ISSUE TITLE
How to whitelist Google Ads on Google searches

### ISSUE THREAD

**Issue by NightMachinary** [StevenBlack/hosts#865]
Google "linux hardening books". Clicking on the sponsored books at the top no longer works. Since these ads are quite relevant to me, I like to whitelist them. Preferably without whitelisting additional stuff. What do I need to put in my whitelist?

**Comment by dnmTX** [comment]
@NightMachinary  i'm kind of guesstimating here without doing any tests,hopefully it's the right one:
`adservice.google.com`

**Comment by NightMachinary** [comment]
Sorry sorry, it’s my finals time, I’ll update you as soon as I test. Thanks!

**Comment by NightMachinary** [comment]
@dnmTX I added “googleadservices.com
tracker.marinsm.com” to make it work. The second one is probably needed only for apple.com ads? Idk.
