### ISSUE TITLE
Remove Lufthansa (Lufthansa.com)

### ISSUE THREAD

**Issue by Ge0rges** [StevenBlack/hosts#867]
Seems like this list blocks Lufthansa.com through Lufthansa.com and lufthanzaairlines.com. Lufthansa is a legitimate German airline.

**Comment by lightswitch05** [comment]
Looks like `lufthansaairlines.com` is included in the `add.Risk` list managed by @FadeMind

**Comment by Ge0rges** [comment]
It also looks like they are using akadns.net <http://akadns.net/> which is also blocked.

**Comment by StevenBlack** [comment]
Luftansa, the legitimate German airline, is at https://www.lufthansa.com, which is not blocked.

**Comment by Ge0rges** [comment]
My mistake, you’re right it’s not blocked, on my side it was being blocked because it’s CDN was.
