### ISSUE TITLE
Coinbase and other crypto domain blocked

### ISSUE THREAD

**Issue by mikepatterson** [StevenBlack/hosts#869]
It looks like https://github.com/StevenBlack/hosts/pull/868 began blocking valid crypto-currency exchange domains (e.g. coinbase.com, bittrex.com, etc.) that aren't involved with browser mining.

This issue seems to have been brought up before by another user with: https://github.com/StevenBlack/hosts/issues/509

**Comment by tarvcode** [comment]
Looks like the last release added https://gitlab.com/ZeroDot1/CoinBlockerLists which blocks everything Crypto related.

I also require the use of a lot of those domains.

**Comment by tdickman** [comment]
Bump. This is affecting me as well. This is blocking a ton of valid cryptocurrency, non-mining related domains.

cc/ @StevenBlack @FadeMind

**Comment by StevenBlack** [comment]
Shit.  Thanks everybody.  Reverting now.
