### ISSUE TITLE
localhost entries incorrectly rewritten to 0.0.0.0

### ISSUE THREAD

**Issue by lucianf** [StevenBlack/hosts#87]
It looks like the filter that converts all IPs to the chosen target (e.g. the default 0.0.0.0) is a bit too greedy.  The valid localhost entries along with the broadcashost from the someonewhocares.org hosts file are incorrectly converted to 0.0.0.0.

Original file snippet:

```
#<localhost>
127.0.0.1       localhost
127.0.0.1       localhost.localdomain
255.255.255.255 broadcasthost
::1             localhost
127.0.0.1       local
#fe80::1%lo0    localhost
#</localhost>
```

Resulting hosts file:

```
#<localhost>
0.0.0.0 localhost.localdomain
0.0.0.0 broadcasthost
0.0.0.0 local
#fe80::1%lo0    localhost
#</localhost>
```

**Comment by StevenBlack** [comment]
@lucianf do you know of any issue that actually.arises from this?

**Comment by lucianf** [comment]
Of course it's an issue.

- localhost.localdomain is required if you have programs expecting to connect to a FQDN.  localhost.localdomain is a FQDN and can help avoid timeouts in certain applications (the very reason why this concept was introduced in the first place).  Certainly localhost.localdomain must resolve to 127.0.0.1 and not 0.0.0.0.  Also see [this](https://bbs.archlinux.org/viewtopic.php?id=156064).
- broadcasthost is useful for addressing all machines on the network.  See [this](https://discussions.apple.com/thread/2090228?tstart=0).

That being said, I think it would be a safe approach to not change anything the OS comes default with.  For example I couldn't find references on what "local" is used for (it may be something Windows-related) but the mere fact that this is part of the default hosts file should mean there was a valid reason to keep it there in the first place.

**Comment by StevenBlack** [comment]
OK, you've convinced me.
