### ISSUE TITLE
Why is getmonero.org blocked? It's the homepage for the Monero open source project.

### ISSUE THREAD

**Issue by pricead** [StevenBlack/hosts#871]
I noticed today (Jan 2, 2019) that GetMonero and related domains are now on the blocklist. This is the official homepage of the Monero open source project, so it doesn't seem to be the kind of domain that should be included on the blocklist.

**Comment by StevenBlack** [comment]
Hi Andrew @pricead, we don't have `getmonero.org` in any of our lists.

Closing.
