### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by itsthanasis1** [StevenBlack/hosts#873]
coinbase.com
thepiratebay.org

For the 2nd i know that it has a lot of malware but a lot of people use it for the clean stuff. It's too popular to be blocked.

**Comment by StevenBlack** [comment]
Hi @itsthanasis1 we don't currently block Coinbase.  We've had the Pirate Bay discussion many times before, it runs malware natively.  So, no.

Closing.

**Comment by itsthanasis1** [comment]
http://prntscr.com/m2m5ph

**Comment by StevenBlack** [comment]
@itsthanasis1 that's using an old version.  See Issue #869.
