### ISSUE TITLE
click.samash.rock doesn't work

### ISSUE THREAD

**Issue by ccfman2004** [StevenBlack/hosts#874]
This address is blocked and I don't know how to figure out what address on the hosts list that gets resolved to this address I need to comment out.

**Comment by dnmTX** [comment]
@ccfman2004  are you sure about the spelling? The way it it is it doesn't look like actual domain and every time i entered it in the browser it goes to  google search.

**Comment by ccfman2004** [comment]
Yes I am.  With the hosts file from here get Failed to Open Page.  Without it, I get redirected to samash's email preference page.  I can't give the full address as it's tied to my email address.

**Comment by dnmTX** [comment]
@ccfman2004  what is the exact message in your browser when it failed.It should point to that specific blocked domain.You need to give us more info,so far we got `click.samash.rock` which is non existent domain.

**Comment by StevenBlack** [comment]
Hi Charles @ccfman2004 

We don't block `click.samash.rock`.

Closing.

**Comment by ccfman2004** [comment]
I know you don't block click.samash.rock but some domain that resolves to it IS being blocked and I'm trying to find out what address that is.

**Comment by ccfman2004** [comment]
I take that back it's click.samash.rocks.  there is an S on rock.

**Comment by ccfman2004** [comment]
Looks like click.virt.s7.exacttarget.com was being blocked which resolves to click.samash.rocks.

**Comment by dnmTX** [comment]
@ccfman2004  non of the Aliases of `click.samash.rocks` are blocked.Not in any of the lists here including the extensions.They are:
`click.virt.s7.exacttarget.com`
`click.exacttarget.com.mdc.edgesuite.net`
`a1467.b.akamai.net`

**Comment by ccfman2004** [comment]
`click.virt.s7.exacttarget.com` is in the hosts file from here.  Once I commented it out I can now access the Sam Ash email preference site.

**Comment by dnmTX** [comment]
This is [LINK](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts) to the main hosts plus all the possible extensions included and **IT IS NOT THERE !!!**
You might need to update your hosts file.

**Comment by dnmTX** [comment]
> EDIT: It looks like the most recent version doesn't contain that address anymore.

OK,now we are on the same page.Please update your hosts file.
This is now officially resolved.
