### ISSUE TITLE
how to use --keepdomaincomments 

### ISSUE THREAD

**Issue by sido420** [StevenBlack/hosts#875]
I'm trying to remove the comments for domains but not sure how to use _--keepdomaincomments_ option.

I keep getting the following error:
```
updateHostsFile.py: error: argument --keepdomaincomments/-k: ignored explicit argument 'false'
```
I've tried the following:
```
--keepdomaincomments
--keepdomaincomments=false
--keepdomaincomments false
```

**Comment by dnmTX** [comment]
@sido420  try:  `-k: false`  . I believe that should do the trick.
@funilrys  can i get confirmation from you on this one. Thanks.

**Comment by sido420** [comment]
Thanks.

I haven't tried it yet as I dont have access to the container atm. But, I will reopen if either options do not work.

**Comment by dnmTX** [comment]
@funilrys  i got this from the front page(`readme.md`):
![readme](https://user-images.githubusercontent.com/34774426/51429059-6ef1d200-1bd0-11e9-8b4a-6c78731521ce.png)

There is no mention of `-a` argument there.If this is something new would advise to update the `readme.md` to avoid confusion in the feature.
