### ISSUE TITLE
more domains?

### ISSUE THREAD

**Issue by Laicure** [StevenBlack/hosts#879]
Hi @StevenBlack!

I just want to share my [list](https://gist.github.com/Laicure/cc9ca4d1d7f905581eccac0490162b7c).
Can you merge (not a separate data source) those into your own list?
or... I don't know, you may just want to merge those so I can clean-up the gist 😸 

How I stumble upon those list:
- Use Chrome Beta (v70) for **chrome://net-internals#dns** (because the new chrome stable version removed the net-internals)
- Visit my everyday sites like those random forums, tech news sites, p*rn sites, etc
- Clean DNS Cache via net-internals#dns > Visit site > check sketchy domains > list down sh*t domains > Clean DNS Cache > visit other site > rinse and repeat
- Verify the _sketchy_ domains by Googling it or by hand-picking them
- Sketchy to me are those domains that _shouldn't be there_, those who serve image ads, those domains who serve fake notification prompts, those domains that do ad redirects, and etc (you know, typical ad annoyance using mobile)

**Comment by lightswitch05** [comment]
I don't recognize any domains I've had issues with blocking

**Comment by funilrys** [comment]
Hm, interesting.

Why is `gearbest.com` in the list?

**Comment by anudeepND** [comment]
@Laicure yt3.ggpht.com may break YouTube thumbnails

**Comment by dnmTX** [comment]
> Why is gearbest.com in the list?
Agreed.Looks like legitimate site...which led me to check it out and see if there is something new to block.
And of course there is:
@StevenBlack  `api-bts.logsss.com` is for you as you already have `analytics.logsss.com` in your `#Analytics` section(same family)
@lightswitch05  `js.affasi.com` is for you.The script redirects to `www.firstgrabber.com` which i believe is a tracker.
Link to the actual script: `https://js.affasi.com/affasi_web.min.js`  for inspection (it's safe)

**Comment by Laicure** [comment]
oh I just added yt3.ggpht.com earlier, I'll remove that. Thanks!

and as for gearbest, I think I stumble on that on some site as ad but I think as a pop-up from them long time ago. I'll remove it.

**Comment by Laicure** [comment]
Closing this as my list is bleeding-edge. ;)
Though the list now resides in [here](https://raw.githubusercontent.com/Laicure/HostsY_hosts/master/shithosts).
