### ISSUE TITLE
DNS adblock

### ISSUE THREAD

**Issue by pengelana** [StevenBlack/hosts#885]
We are providing open resolver to block ad based on StevenBlack/No-Tracking raw data.

can be access from:

DNS-Over-HTTPS:  https://doh.tiar.app/dns-query 
DNS-Over-TLS: doh.tiar.app@853

DNSCrypt stamps:
sdns://AQMAAAAAAAAADTE0OS4yOC4xNTIuODEg75aAZujZlPBl2D7d0xru7fVthldGPkrKR83X_pfD1PYcMi5kbnNjcnlwdC1jZXJ0LmRucy50aWFyLmFwcA

**Comment by StevenBlack** [comment]
Thanks @pengelana, this is interesting!

Do you have any more information on this?  [https://doh.tiar.app/](https://doh.tiar.app/) just says, 

  `DNSSEC Validation, Block Ad/Ad-tracking, No Logging, Free!`

**Comment by pengelana** [comment]
doh.tiar.app and dnscrypt.tiar.app are located in Singapore, it's free to use and all the logs turn off by default. 

how to use in android/ios/desktop:

doh:
https://gist.github.com/pengelana/1f125c50ea9d5fa97827608db2ac19bc

dnscrypt:
https://gist.github.com/pengelana/adbe1464cd83ac79148db80a65d1ed83

**Comment by edtw** [comment]
@pengelana 
Excuse me,
Is it currently only using "StevenBlack" for ad filtering rules?

**Comment by pengelana** [comment]
combine with notracking domain/host.
