### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by SebastianTrautwein** [StevenBlack/hosts#888]
Hosts version: Newest master from Github.
Python version: Python 3.6.7
OS: Ubuntu 18.10 64bit

I'm doing the following:

> sudo python3 updateHostsFile.py --auto --replace

It updates the hosts file sources normally (extract to safe space):

> Updating source data/mvps.org from http://winhelp2002.mvps.org/hosts.txt

Then this happens:

> ==>fe00::0 ip6-localnet<==
> ==>ff00::0 ip6-mcastprefix<==
> ==>ff02::2 ip6-allrouters<==
> ==>ff02::3 ip6-allhosts<==
> Traceback (most recent call last):
>   File "/home/redacted/Adblocker/updateHostsFile.py", line 1526, in <module>
>     main()
>   File "/home/redacted/Adblocker/updateHostsFile.py", line 213, in main
>     sourcesdata=sources_data)
>   File "/home/redacted/Adblocker/updateHostsFile.py", line 1006, in update_readme_data
>     readme_data = json.load(f)
>   File "/usr/lib/python3.6/json/__init__.py", line 299, in load
>     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The host files in the data folder (data/source_name/hosts) are created and the consolidated hosts file in the script root folder is created as well. However the hosts file is not applied to the system hosts file in /etc/hosts.

**Comment by funilrys** [comment]
Hello @SebastianTrautwein and welcome here,
I synced my forks and I'm unable to reproduce :thinking: 

May I ask if the `readme_template.md` is present ?

**Comment by funilrys** [comment]
Actually the line 
```
File "/home/redacted/Adblocker/updateHostsFile.py", line 1006, in update_readme_data
readme_data = json.load(f)
```
is related to the `readmeData.json` file. Do you make any changes in there ?

**Comment by SebastianTrautwein** [comment]
Thanks for the hint. I fixed it by replacing the readmeData.json with the github master version. I noticed that it is present in .gitignore and I noticed that it deviated for some reason from the master. Now everything runs fine. Thanks again! :)
