### ISSUE TITLE
Few hostnames to block

### ISSUE THREAD

**Issue by 241d2** [StevenBlack/hosts#889]
Ad trackers and adwares
statistic.ads24h.net
ads24.net
ads-game-187f4.firebaseapp.com
apphack.mobi

**Comment by thanuj10** [comment]
Also please add www.letmejerk.com to porn hosts lists please.

**Comment by StevenBlack** [comment]
Ping @sinfonietta for letmejerk.com.

**Comment by thanuj10** [comment]
@Sinfonietta please add www.letmejerk.com to the porn hosts.
