### ISSUE TITLE
0.0.0.0 local line is not deleted

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#89]
I found weird line in hosts:
`#<localhost>`
`0.0.0.0 local`
`#fe80::1%lo0    localhost`
`#</localhost>`

This is from http://someonewhocares.org/hosts/zero/

![screenshot_20160219_150121](https://cloud.githubusercontent.com/assets/9846948/13177485/ac5558b4-d719-11e5-8bef-fee2bd6ea038.png)

**Comment by StevenBlack** [comment]
Ya, that's a side effect of a tweak I made earlier today,

Fixing now.
