### ISSUE TITLE
domains to block (ads/tracking)

### ISSUE THREAD

**Issue by chado99** [StevenBlack/hosts#892]
ads.flurry.com
rtb-csync.smartadserver.com
t.update.rubiconproject.com
i.liadm.com
r.casalemedia.com
csm.va.us.criteo.net
www.google-analytics.com
www.googletagservices.com
t.agentanalytics.com
101.xg4ken.com
mc.yandex.ru
securepubads.g.doubleclick.net
static.ads-twitter.com
www.summerhamster.com
analytics.twitter.com
cms.analytics.yahoo.com
v4.moatads.com
ads.everesttech.net
sync.adaptv.advertising.com
ssum-sec.casalemedia.com
ads.yieldmo.com
eb2.3lift.com
s0.doubleclick.net
match.prod.bidr.io
c.betrad.com
l.betrad.com
sstats.arstechnica.com
p.adsymptotic.com

**Comment by StevenBlack** [comment]
Ref Issue #893.
