### ISSUE TITLE
tparser.org is gone now

### ISSUE THREAD

**Issue by plusname** [StevenBlack/hosts#894]
tparser.org
now redirecting to ad site 
iyfsearch.com

**Comment by StevenBlack** [comment]
@plusname I'm sorry, what?  Please explain.

**Comment by dnmTX** [comment]
@plusname and how is that any concern of anyone who contributes here? 
If that website is down or whatever please refer to whoever maintains it!
@StevenBlack  it's a torrent site which is apparently down and Mr. @plusname here decided that you can magically bring it back to life.
Bunch of nonsense.You can close this one.
