### ISSUE TITLE
Real me 2 Pro

### ISSUE THREAD

**Issue by imbawania** [StevenBlack/hosts#895]
hii, i am using real me 2 pro and using dns66 app version 0.5.8 and latest host file but ads are not getting blocked & same file i am using in lenovo vibe k5 then ads are getting blocked. please help

**Comment by kowith337** [comment]
For application client problems, go to the app's repo issue.
https://github.com/julian-klode/dns66/issues

IMO, I think it's maybe a problem about battery saving settings, try whitelist or ignore the app to prevent Android system terminate it automatically.

**Comment by imbawania** [comment]
Please provide solution what should I do

**Comment by StevenBlack** [comment]
Sahil @imbawania help us out.  Do you have any links to what you're talking about?  

When I Google `virtual hosts APK`, and variants of that, from here in Canada, noting credible (or close) comes up in the first few search engine results.

So what, exactly, are you talking about?  And why are you asking here?  We make host files, not apps for Android.

**ANYWAY**  🙄 whenever you modify hosts, you should also flush DNS cache.

Try this: [How to Clear DNS Cache on Android Devices](https://beebom.com/how-to-clear-dns-cache-android-devices/).

Closing.

**Comment by imbawania** [comment]
![screenshot_2019-01-27-11-21-56-93](https://user-images.githubusercontent.com/46932334/51797252-f8834e80-2225-11e9-8f03-ac536e7335d6.png)
You can also check play store just search virtual hosts and you found an app which is similar to DNS 66.

**Comment by imbawania** [comment]
I am asking it because DNS 66 is not working but virtual host APK is working fine DNS 66 app is crashing but virtual host APK is working fine I was unable to block ads using DNS 66 in my real MI 2 pro but using virtual hosts APK I am able to block ad so I just want to know is it safe or not.

**Comment by dnmTX** [comment]
That screenshot size. Oh my......:dizzy_face:

**Comment by kowith337** [comment]
You can also try personalDNSFilter
