### ISSUE TITLE
Remove crash analytics domains

### ISSUE THREAD

**Issue by Dubz** [StevenBlack/hosts#896]
I'm not sure why they're listed, but you have three subdomains for crashlytics.com in your list for "ads"

This domain is meant for app crash reports, not ads. Blocking unnecessary/too many domains causes problems for apps, which then affects the users and developers.

e.crashlytics.com
reports.crashlytics.com
settings.crashlytics.com

I am not affiliated with crashlytics, nor do I use it, but it is causing issues. I know you/we can't check every domain that comes through, let alone review the existing list. It would be more work than anyone would like to commit. Taking a few that don't belong out here and there, though, will help everyone in the long run.

**Comment by patrickdrd** [comment]
I'm not interested in sending crash reports personally, sorry

**Comment by Dubz** [comment]
> I'm not interested in sending crash reports personally, sorry

That's your preference. Doesn't mean it should default to crippling developers' and users' experiences. If you don't want it sending, then you can add it to your personal blacklist. How many other domains would I have to go add to my whitelist to clean up the blocklist if that sort of attitude was used towards domains?
Granted, I don't believe developers should let their apps depend on such resources to function, whether on purpose or by coincidence. That's something they need to fix as well in such case.

Use a separate list if sending debugging feedback bothers you that much.

**Comment by StevenBlack** [comment]
Hi @Dubz, thank you for your input.

It's possible that you are mistaken; this project isn't just about "ads".  There are other hosts  sources if you want to block just ads.

The promise here is, we block adware and malware and that includes trackers, data miners, coin miners and cpu hogs, and others.

I use [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) and  if you saw the traffic crashlytics generates, as generally implemented, you wouldn't be a hot advocate for it.  In a word, it may be the worst.

Closing.

**Comment by Dubz** [comment]
Fair enough, I appreciate hearing your reasoning as well.
Thanks!
