### ISSUE TITLE
dns66 start crashing

### ISSUE THREAD

**Issue by imbawania** [StevenBlack/hosts#897]
hii, dns66 stoped working in lenovo vibe k5 while adding host file and going to done it stopped working unable to add host file.

**Comment by imbawania** [comment]
![screenshot_2019-01-24-11-35-37](https://user-images.githubusercontent.com/46932334/51657922-456be880-1fcc-11e9-808e-850c256e25f1.png)

**Comment by StevenBlack** [comment]
Hi Sahil @imbawania please don't open multiple issues related to the same thing.

Closing.
