### ISSUE TITLE
127.0.0.1 > 0.0.0.0 conversion

### ISSUE THREAD

**Issue by nomadturk** [StevenBlack/hosts#9]
On Linux I'm running this.
python updateHosts.py

OK, it gathers stuff. Removes the domains from the lists.
That's OK.

But when it comes to replacing 127.0.0.1 with 0.0.0.0 IP's, it fails on some of them.
For example the below part is from Yoyo list and

* 0.0.0.0 24log.com
* 0.0.0.0 24log.de
* 0.0.0.0 24pm-affiliation.com
* 0.0.0.0 2mdn.net
* 127.0.0.1 2o7.net
* 0.0.0.0 360yield.com
* 127.0.0.1 4affiliate.net
* 0.0.0.0 4d5.net
* 0.0.0.0 50websads.com
...

...

...
* 127.0.0.1 7adpower.com
* 127.0.0.1 7bpeople.com
* 127.0.0.1 7search.com

Also, it's not over.
The duplicate detection? Doesn't work as intended.
Right now I'm looking at 2x 0.0.0.0, 1x 127.0.0.1 references to ads.blog.com entries.

I've tried running your original git at a different machine, same result...

**Comment by StevenBlack** [comment]
Closing.

**Comment by StevenBlack** [comment]
@nomadturk what are your thoughts given this:  

Hacker news story comments
  Chrome routes http://0.0.0.0:* to Google Search: 
  https://news.ycombinator.com/item?id=9048811

  The bug (or feature) as filed with Google
  https://code.google.com/p/chromium/issues/detail?id=428046

I'm inclined to go back to 127.0.0.1 — thoughts?

**Comment by nomadturk** [comment]
OK,

As long as I'm concerned I don't care this type of behaviour since it
doesn't affect my browsing habits.
Since we don't need people using http://0.0.0.0 on their browsers, I don't
see how it affects us.

As for hosts file behaviour, it's still the same. I still see "DNS not
resolved" error in ads places.
So everything seems OK if you ask me.



*M. Ömer Gölgeli*
--
*Vultus est index animi*

**Comment by StevenBlack** [comment]
It's all-good :smile:
