### ISSUE TITLE
... a simple POSIX /bin/sh script may be more simple solution then 15000 bytes python script ...

### ISSUE THREAD

**Issue by vermaden** [StevenBlack/hosts#90]
```
#! /bin/sh

rm -f hosts.[0-9]*

cat << __EOF | while read LIST; do COUNT=$(( ${COUNT} + 1 )); echo "curl -g \"${LIST}\" | sed -e s/$'\r'//g 1> hosts.${COUNT}"; done | parallel
http://adaway.org/hosts.txt
http://netcologne.dl.sourceforge.net/project/adzhosts/FORADAWAY.txt
http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext
http://someonewhocares.org/hosts/hosts
http://winhelp2002.mvps.org/hosts.txt
http://www.malwaredomainlist.com/hostslist/hosts.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
__EOF

cat hosts.[0-9]* \
  | grep -v '^#' \
  | grep -v '^$' \
  | awk '{print $2}' \
  | sort -u -f \
  | while read I
    do
      echo 0.0.0.0 ${I}
    done | sed 1d 1> hosts


```

This one fetches all hosts sources in parallel and then merges them into a single 0.0.0.0 hosts file.

Regards,
vermaden

**Comment by StevenBlack** [comment]
@vermaden love this!

**Comment by vermaden** [comment]
Welcome ;)

I would also add this source:
http://netcologne.dl.sourceforge.net/project/adzhosts/FORADAWAY.txt

**Comment by Ultrabenosaurus** [comment]
Definitely simpler and maybe cooler, but completely abandons Windows (and possibly Mac). Anyone with python installed can run the python script and get the same results. I have git's shell installed on my Windows for obvious reasons but I regularly run into situations where downloaded scripts require extra binaries, or my version of the binaries don't have the correct flags available, and with [tldr](https://github.com/raylee/tldr) it wouldn't work at all because of the ~ operator being unsupported for comparisons - though updating my git fixed this, it may not always be the case.

**Comment by StevenBlack** [comment]
Also GNU Parallel is a dependency...

Is it just me or do others come across fascinating shell scripts on a quasi-daily basis?

**Comment by vermaden** [comment]
Here, a version without GNU parallel.

It will work without any issues on Apple Mac OSX.

You can also use CYGWIN or MINGW to run it on Windows. For me there is no difference if You install Python or one of these.

For Windows I would use PowerShell.


```
#! /bin/sh

rm -f hosts.[0-9]*

cat << __EOF | while read LIST; do COUNT=$(( ${COUNT} + 1 )); curl "${LIST}" | sed -e s/$'\r'//g 1> hosts.${COUNT}; done
http://adaway.org/hosts.txt
http://netcologne.dl.sourceforge.net/project/adzhosts/FORADAWAY.txt
http://pgl.yoyo.org/adservers/serverlist.php?showintro=0;hostformat=hosts
http://someonewhocares.org/hosts/hosts
http://winhelp2002.mvps.org/hosts.txt
http://www.malwaredomainlist.com/hostslist/hosts.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
__EOF

cat hosts.[0-9]* \
  | grep -v '^#' \
  | grep -v '^$' \
  | awk '{print $2}' \
  | sort -u -f \
  | while read I
    do
      echo 0.0.0.0 ${I}
    done 1> hosts
```

**Comment by FadeMind** [comment]
@vermaden 
`http://pgl.yoyo.org/adservers/serverlist.php?showintro=0;hostformat=hosts` is downloaded as HTML file.

Good script
In final file first line is just `0.0.0.0`. 
;)

**Comment by vermaden** [comment]
@FadeMind
Fixed both issues, in both parallel and non-parallel versions.

Thakns.

**Comment by FadeMind** [comment]
@vermaden NOPE. 3rd link downloading EMPTY file.
![screenshot_20160221_123744](https://cloud.githubusercontent.com/assets/9846948/13202344/f07818d6-d897-11e5-997d-80d5700e4f94.png)

**Comment by vermaden** [comment]
Disabled _'URL globbing parser'_, now works good.

From **curl(1)** man page:
```
        -g, --globoff
              This option switches off the "URL globbing parser". When you set
              this  option, you can specify URLs that contain the letters {}[]
              without having them being interpreted by curl itself. Note  that
              these  letters are not normal legal URL contents but they should
              be encoded according to the URI standard.
```

**Comment by matkoniecz** [comment]
@vermaden Note that this script is doing far less than current python script. Just download, deduplication and replacement of hosts file may be easily achieved in python script of comparable size with higher readability and better portability - just remove from the current python script everything that is not supported by this /bin/sh script.

Some functions may be probably dropped (how many people are manually entering additional domains to blacklist/whitelist on every update?) but some like myhosts or whitelist files are certainly necessary.

**Comment by xHN35RQ** [comment]
Don't re-invent the wheel, if you want a shell script, here's a good one: https://github.com/gaenserich/hostsblock

**Comment by vermaden** [comment]
@xHN35RQ
Are You kidding me?

First, my solution is in POSIX /bin/sh, not in Linuxish/Linuxism BASH ...

Second, my solution is less then 30 lines including URLs (configuration) and 'spaces' for formating, so it makes about 10 lines of code ... while this 'bash thing' is more then 300 lines of code split into several files without any configuration.

**Comment by xHN35RQ** [comment]
Ah, sorry - I spaced out on the POSIX vs. Bashisms. I know better. :anger:  I edited my previous comment.

**Comment by Rergis** [comment]
Suckless Philosophy in action! man i love this script!

**Comment by vermaden** [comment]
@Rergis
Thanks ;)

**Comment by xHN35RQ** [comment]
@vermaden I've been using your script (with a few changes) for about 3 months now. It works beautifully. Thanks! I'm ashamed I even linked to that other mess of code. :grimacing:

**Comment by StevenBlack** [comment]
Closing.
