### ISSUE TITLE
Keshe Foundation blocked

### ISSUE THREAD

**Issue by sheldrak** [StevenBlack/hosts#901]
Hello,
Why Keshe Foundation website is blocked with this hosts content? I just tried to enter on their website and I can't.
Please remove this line from hosts:
0.0.0.0 keshefoundation.org

**Comment by dnmTX** [comment]
Oh...that is your friend from KADhosts. You can open a [ISSUE](https://github.com/azet12/KADhosts/issues) 
 there and prey somebody to respond. Best of LUCK bud. 👍  👍  👍

**Comment by StevenBlack** [comment]
Hey @dnmTX, c'mon.  Thanks for steering to the issues page but I see [zero evidence supporting the snide aftercomments](https://github.com/azet12/KADhosts/issues?q=is%3Aissue+is%3Aclosed).  Quite the opposite, actually.

**Comment by dnmTX** [comment]
Sorryyyy!!! Didn't mean to be a d-bag. Editing my post.....

**Comment by sheldrak** [comment]
Posted. Thanks!

**Comment by dnmTX** [comment]
[RESOLVED](https://github.com/azet12/KADhosts/issues/18). Close please.
