### ISSUE TITLE
huit.re is blocked

### ISSUE THREAD

**Issue by s0r00t** [StevenBlack/hosts#902]
I've noticed that huit.re is blocked.

huit.re is a French URL shortener maintained by [Framasoft](https://framasoft.org/).

Why is it the case? Would it be possible to remove it from the domain list(s)?

Thanks.

**Comment by StevenBlack** [comment]
@s0r00t la source de `huit.re` est [ici](https://github.com/azet12/KADhosts/issues).  Fais ta requete là svp.  Merci.
