### ISSUE TITLE
Websites to block (Porn)

### ISSUE THREAD

**Issue by botistreamer** [StevenBlack/hosts#903]
https://pastebin.com/TvFEeVZ1

All these porn sites aren't blocked by the host file as of 29/1.

**Comment by StevenBlack** [comment]
Thanks @botistreamer.

Ping @sinfonietta!

**Comment by rdemongeot** [comment]
Hello,

I've found some more site to block on this category : 
* www.jacquieetmichel.net
* www.jacquieetmicheltv2.net

Is it possible to contribute and add some lines by ourself?

Best regards,

**Comment by funilrys** [comment]
@rdemongeot Yes at https://github.com/Sinfonietta/hostfiles for this category.

**Comment by botistreamer** [comment]
Sinfonietta has merged my PR which contains all websites mentioned in this issue.
Closing.
