### ISSUE TITLE
Strange issue while using updateHostsFile

### ISSUE THREAD

**Issue by asaddon** [StevenBlack/hosts#904]
Hi, I'm encountering a super strange issue and any help will be super appreciated.

I'm trying to add more data sources in the host file and there's one host file on GitHub which no matter what I do I'm not able to fetch properly.

This is the hosts repo:
**https://github.com/BlackJack8/iOSAdblockList**

And this is the file I'm trying to add:
**https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/iPv4Hosts.txt**

The thing is every time I run the updateHostsFile ( after off course adding all the necessary files in data folder ) I get this error:

```
Problem getting file:  https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/iPv4Hosts.txt
Error in updating source:  https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/iPv4Hosts.txt
```

But what's strange is If i try to fetch a different file on same repo, it fetches it alright but since that file is not in hosts format , it doesn't get added in generated host file.

I'm talking about this file:
**https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Hosts.txt**

**Comment by StevenBlack** [comment]
Hi Asad @asaddon I'm away from my desk right now but a couple of things to check.

[Line 922 is has an IP address but no domain](https://github.com/BlackJack8/iOSAdblockList/blob/master/iPv4Hosts.txt#L922), that might be an untested edge-case.

I would also check this file for an out-of-scope unicode character...

**Comment by asaddon** [comment]
Thanks for your reply, honestly I'm super new to all this and I just follow the readme and existing hosts files in data folder to add more, I don't really know how and what change I need to do to fix that so whenever you have time please test and let me know.

**Comment by dnmTX** [comment]
📞 PING 📞  @funilrys  for test and help

**Comment by StevenBlack** [comment]
Thanks Nissar @funilrys.
