### ISSUE TITLE
Block ad service

### ISSUE THREAD

**Issue by pcs3rd** [StevenBlack/hosts#906]
googleads.g.doubleclick.net
is not blocked by this host list or anyone elses in pi-hole.

**Comment by StevenBlack** [comment]
@pcs3rd this is used by whom, and where?

**Comment by dnmTX** [comment]
Steven @StevenBlack  anything `*.doubleclick.net` should be blocked in my opinion.
There is no **"good ones"** there. On the subject here,the domain mentioned by OP was listed here in the past by @lightswitch05's lists also @anudeepND's list has bunch of them as well.
@pcs3rd  you can either add it yourself,or add any of the mentioned lists above as a alternative.

**Comment by StevenBlack** [comment]
@pcs3rd I just checked.  We do indeed block `googleads.g.doubleclick.net` already.  It comes from three of our sources (adaway.org, mvps.org, and someonewhocared.org).

So we have that covered.  😎 

Closing.
