### ISSUE TITLE
Merge ads blacklist

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [StevenBlack/hosts#909]
Can you merge an [ads blacklist](https://gist.githubusercontent.com/opus-x/3e673a9d5db2a214df05929a4eee6a57/raw) that contains Spotify servers?

**Comment by MarcoDiFrancesco** [comment]
There is also the [description](https://gist.github.com/opus-x/3e673a9d5db2a214df05929a4eee6a57#gistcomment-2618502) of the blocked servers.

**Comment by StevenBlack** [comment]
Ciao Marco @MarcoDiFrancesco, we've had many conversations about Spotify in the past.

See for example the following issues:

* #668
* #619
* #560
* #552
* #515
* #507
* #506
* #483
* #270
* #153
* #37

So we are quite familiar with Spotify 😄 

The essential problem is, Spotify is on so many platforms (web, iOS, Android, integrated with Sonos and many others) so a blocklist that's fine for some people doesn't work and prevents facets of Spotify for others.  It's basically impossible to test this properly.

There's one very solid an reliable solution, however, one I recommend: subscribe.

Closing.
