### ISSUE TITLE
Porn Hosts List not reliable (websites can be accessed if www. is not typed)

### ISSUE THREAD

**Issue by Tomatoide** [StevenBlack/hosts#910]
Some websites on the list has 2 entries (one with www. and one without) and are blocked just fine, but there are other websites on the list that only has 1 entry (one with www.) and thus can be accessed easily if the user doesn't type www. at the beginning of the url.

**Comment by StevenBlack** [comment]
@Tomatoide @dnmTX there's nothing special or magical about `www` subdomains.  

If you find a particular subdomain isn't blocked, then mention it, or submit a PR.  That's what curation is all about.

But to claim `www` isn't being blocked and, based on this, the maintainers are negligent or whatever, that's just ignorant.  Subdomains are arbitrary strings, and that's increasingly true.

**Comment by Tomatoide** [comment]
@StevenBlack C'mon man, you're better than this, maybe you had a bad day or something
All I wanted to say is that, for example, a site like `www.pornhd.com` doesn't have its `pornhd.com` counterpart entry on the list making it easy to be accessed, same with other websites, so all entries need to be checked in a batch process for having 2 entries (one with and one without `www.`) for more reliable blocking. Maybe ping @Sinfonietta also for this
