### ISSUE TITLE
glassbox domains

### ISSUE THREAD

**Issue by Laicure** [StevenBlack/hosts#913]
Hey, 

I just stumbled upon this article from [The Verge](https://www.theverge.com/2019/2/6/18214578/apple-iphone-ios-session-replay-apps-recording-screen-hotel-travel).

This one (glassbox.aircanada.ca) hits the list as written from [The App Analyst](http://theappanalyst.com/aircanada.html).

Anyone have more domains to block for [Glassbox](glassbox) data collection and etc?

**Comment by dnmTX** [comment]
`report.usaa.glassboxdigital.io`

**Comment by StevenBlack** [comment]
Related, posted just a few hours ago:

[Apple tells app developers to disclose or remove screen recording code](https://techcrunch.com/2019/02/07/apple-glassbox-apps/)

**Comment by Laicure** [comment]
think anyone can absorb the domains in their list? hehe
so we can close this one ;)

**Comment by StevenBlack** [comment]
We presently carry the following three domains, which come to us via AdAway.  Which may or may not be related.

```
glassbox.aircanada.ca
glassboxdigital.com
theglassbox.com
```

Closing this since it's just old.
