### ISSUE TITLE
Spotify bans ad blockers in updated Terms of Service

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/hosts#914]
Interesting development, seeing this on Hacker News today.

[Spotify bans ad blockers in updated Terms of Service](https://www.theverge.com/2019/2/7/18215845/spotify-ad-blockers-terms-of-service)

[Here's the HN discussion](https://news.ycombinator.com/item?id=19108697), which I expect to evolve over the next few hours.

**Comment by thomasmerz** [comment]
I didn't get in any trouble with "some ads" being blocked by my Pi-Hole, yet… 🤔

**Comment by StevenBlack** [comment]
Closing.
