### ISSUE TITLE
CBS.com video streaming

### ISSUE THREAD

**Issue by evannnc** [StevenBlack/hosts#915]
looks like one of the addresses in the list is preventing videos from being played on CBS.com.  Any clue how i would narrow down what IP address is causing the problem? I know this isn't a problem on your end since you guys don't put the lists together, just thought someone her might have some advice.

**Comment by StevenBlack** [comment]
Hi Evan @evannnc the best way is using Chrome, right+click and select `Inspect`, then chose the network tab.

Now navigate to your streaming site.  You'll likely see several dozen HTTP requests in the network tab listing.  The ones that don't resolve will be colored red.

Here's a [YouTube video](https://youtu.be/nl8iKlo2NeM?t=22) – I've advanced you to the point of interest, skipping the boring intro 😄

**Comment by StevenBlack** [comment]
Evan @evannnc imma gonna close this, feel free to open a new issue if you discover what's causing the issue you're seeing.

**Comment by evannnc** [comment]
Great info, thanks for sharing!
