### ISSUE TITLE
False positive?  dgit.com

### ISSUE THREAD

**Issue by Zenexer** [StevenBlack/hosts#916]
I don't really know much about this site, but a coworker was trying to access an article on it and it was blocked.  The articles look pretty low-quality to me, but I don't know that I'd consider them bad enough to be in the primary hosts file.

Does anyone know why it was added?  Git blame shows 38869f636, but that's not really enough context.

**Comment by Zenexer** [comment]
Here's the commit reason:

> New data from yoyo.org, and new host records from commit 5b5e854.

It's not mentioned in commit 5b5e854; that looks like it's some IPv6 compatibility stuff.

If it was ever listed on yoyo.org, [it's not anymore](https://pgl.yoyo.org/as/details.php?hostname=dgit.com).

**Comment by Zenexer** [comment]
Apparently 38869f6 was just a line ending change or something (didn't really look closely).  The actual commit in which it was introduced is 2489eb6016f0a1f34bb76ec303b721ee1dd94018.

**Comment by dnmTX** [comment]
[Twitter](https://twitter.com/DanPollock)  or Email:  pollock@theorem.ca

**Comment by StevenBlack** [comment]
Thanks everybody.  Closing.
