### ISSUE TITLE
Remove blacklisted website

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [StevenBlack/hosts#917]
Can you remove `it.altervista.org` from the blacklisted website? This is just the Italian website for `altervista.org` not a website of advertisements.

**Comment by Laicure** [comment]
oh, I use altervista too.

**Comment by StevenBlack** [comment]
Marco @MarcoDiFrancesco and Laicurè @Laicure various `altervista.org` domains are blocked by the following curators:

* Badd-Boyz-Hosts
* add.Risk
* mvps.org
* yoyo.org

The specific domain `it.altervista.org` is blocked by `add.Risk`.  Can you please submit this to Tomasz' [issues page](https://github.com/FadeMind/hosts.extras/issues)?

Thanks!

Closing.
