### ISSUE TITLE
WannaCry shouldn't be filtered

### ISSUE THREAD

**Issue by JamieH** [StevenBlack/hosts#918]
If someone is infected with WannaCry and they're using your list on their DNS resolver (Pi-hole), the query will be blocked resulting in an infection... the domain name is sinkholed and safe so it should be unblocked.

Domains:
```
iuqerfsodp9ifjaposdfjhgosurijfaewrwergwea.com
www.iuqerfsodp9ifjaposdfjhgosurijfaewrwergwea.com
```

**Comment by StevenBlack** [comment]
Hi Jamie @JamieH, this host is blocked by one of our source curators, Dan Pollock, over at someonewhocares.org.

Can you please submit this request to him via email at hosts@someonewhocares.org?

Thanks!  

Closing this now.
