### ISSUE TITLE
Some pornsites domains to block

### ISSUE THREAD

**Issue by lordruler** [StevenBlack/hosts#922]
kindgirls.com
www.kindgirls.com
www.pornhub.net
www.porndabster.com
www.fineplaymates.com
www.boobpedia.com
www.spicybunnies.com
www.kporno.com
www.aziani.com
www.imgshost.net
www.letfab.com
pornoslab.com
www.pornoslab.com
www.pornslap.com
www.nudemodel.pics
cdn-l.pornstarblognetwork.com
www.clublindsaymarie.com
cdn1.pussyspot.net
cdn2.nsfw.exchange
cdn2.pussyspot.net
foliovision.com
lemmecheck.link
media.lemmecheckvideo.com
promo.stunners.com
stunners.com
www.stunners.com
styles.lemmecheck.net
timdir.com
www.hardcoreluv.com
www.lemmecheck.com
cdn.eroticbeauties.net
ftop.ru
www.thelordofporn.com
www.eroshow.ro
www.handy-porn.net
thefappeningblog.com
thefappeningtop.com
www.nudogram.com

**Comment by ScriptTiger** [comment]
^ Bump @Clefspeare13 and @Sinfonietta

**Comment by NymeriaXV** [comment]
I added your souggestions in my fork [of @Clefspeare13 s hostfile](NymeriaXV/pornhosts/), I'm currently applying to be a source.

**Comment by StevenBlack** [comment]
I checked a few of those... just for quality control.  And for science.

Presently http://www.eroshow.ro/ displays "under construction" but I suppose, based on the domain name, we can guess what's coming.

**Comment by saurabhs** [comment]
A type with www.letfab.com, its suppose to be www.letfap.com

**Comment by lordruler** [comment]
> 
> 
> A type with [www.letfab.com](http://www.letfab.com), its suppose to be [www.letfap.com](http://www.letfap.com)

typo*

**Comment by Clefspeare13** [comment]
All the ones I checked seemed worth putting on the list, my hostfile has been updated

**Comment by StevenBlack** [comment]
Thanks Niclas @Clefspeare13!

Closing.
