### ISSUE TITLE
Request for the files hosted on http://sbc.io/ 

### ISSUE THREAD

**Issue by mikhoul** [StevenBlack/hosts#924]
Since last week Adaway don't allow http (non secure) host for host files: https://github.com/AdAway/AdAway/issues/1112

So my request is could you add a Free SSL certificate to sbc.io host with https://letsencrypt.org, it's really easy ?

Regards :octocat:

**Comment by StevenBlack** [comment]
I'll be doing this shortly, @mikhoul.

This is a duplicate of #878 ***HTTPS for the non-github mirror*** so closing.

**Comment by mikhoul** [comment]
Thanks a lot @StevenBlack  :smile:
