### ISSUE TITLE
Facebooks Graph api

### ISSUE THREAD

**Issue by the4thfloor** [StevenBlack/hosts#925]
Hi,

I'm wondering why graph.instagram.com and graph.accountkit.com are listed in the main(?) list?

Is there any reason to list the official graph API endpoints? And if there is a reason, why is graph.facebook.com not listed?

Ralph

**Comment by herosworld** [comment]
I can find for http payload connected domains.So very Thank you

**Comment by StevenBlack** [comment]
Hi Ralph @the4thfloor, `graph.instagram.com` comes from yoyo.org, a very reliable curator.

`graph.accountkit.com` is listed in my ad-hoc source, added by Nissar @anudeepND [in this commit on April 7, 2018](https://github.com/StevenBlack/hosts/commit/eb0c76b8dd13e2c1a4d8a9a43d0efc307b313de8).  Nissar do you remember the reason for listing `graph.accountkit.com`?

**Comment by the4thfloor** [comment]
If you use the mobile Instagram app you need access to `graph.instagram.com` otherwise the app can't load the feed.

**Comment by StevenBlack** [comment]
Ralph @the4thfloor can you please take this up with yoyo?  Email: pgl@yoyo.org – this is [explained in the Readme](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Thanks!

**Comment by johnwick1** [comment]
> 
> 
> If you use the mobile Instagram app you need access to `graph.instagram.com` otherwise the app can't load the feed.

Same here, graph.instagram.com blocking the Instagram feed

**Comment by llacb47** [comment]
> > If you use the mobile Instagram app you need access to `graph.instagram.com` otherwise the app can't load the feed.
> 
> Same here, graph.instagram.com blocking the Instagram feed

Loads fine for me.

**Comment by johnwick1** [comment]
> 
> 
> > > If you use the mobile Instagram app you need access to `graph.instagram.com` otherwise the app can't load the feed.
> > 
> > 
> > Same here, graph.instagram.com blocking the Instagram feed
> 
> Loads fine for me.

are you running on web or mobile ?

**Comment by pgl** [comment]
Please see my reply in #1206

**Comment by XhmikosR** [comment]
@StevenBlack I believe you can close this issue and #1206 now that @pgl has removed the aforementioned domain 🙂
