### ISSUE TITLE
More presage.io subdomains

### ISSUE THREAD

**Issue by Deses** [StevenBlack/hosts#926]
Hi! I see you have two presage.io domains:
```
   l-v1.presage.io
   pl-v2.presage.io
```
Taking a look at my PiHole log, I've seen several other presage.io subdomains that maybe worth considering blocking:
```
   a-v2.presage.io
   p-v2.presage.io
   bip.presage.io
   t-v2.presage.io
```

**Comment by StevenBlack** [comment]
Hi Carlos @Deses.

Can you please submit this as a pull request?  Thank you!
