### ISSUE TITLE
Doesn't block youradchoices ads.

### ISSUE THREAD

**Issue by redsauce117** [StevenBlack/hosts#927]
Adchoices ads still pop up :c

**Comment by StevenBlack** [comment]
Hi @redsauce117 thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).  I imagine they will want to know reasons why, and to know exactly which domains are to be locked, in your opinion.

Closing.
