### ISSUE TITLE
Facebook site

### ISSUE THREAD

**Issue by toporivskiy** [StevenBlack/hosts#930]
wwwfacebook = www.facebook

**Comment by StevenBlack** [comment]
Thanks Andrew @toporivskiy.

Ping Tomasz @FadeMind – looks like Facebook owns this now, and it redirects to vanilla Facebook?  Thanks for looking into this.

**Comment by FadeMind** [comment]
@StevenBlack  what I need to do with this ISSUE?? Cause `www.facebook` is not valid DNS record... I using Cloudflare.

**Comment by StevenBlack** [comment]
@fademind Line 16 in dead hosts says...
  https://github.com/StevenBlack/hosts/blob/master/data/add.Dead/hosts#L16

`0.0.0.0 wwwfacebook.com`

That should be removed, I'm guessing.    Thanks.

**Comment by FadeMind** [comment]
@StevenBlack `RESOLVED` 😀
