### ISSUE TITLE
Fix for Parkmobile app broken/not loading when any unified hosts applied

### ISSUE THREAD

**Issue by Zackptg5** [StevenBlack/hosts#931]
I was confused as to why parkmobile app suddenly quit working one day on my android device. I eventually narrowed it down to something in the master hosts file and found it to be this entry:

api.branch.io

Whitelisting the above solved the problem and the app worked normally. Can this entry be removed from the hosts? Thanks

**Comment by StevenBlack** [comment]
Hi @Zackptg5 thank you for researching this.

The [branch.io](https://branch.io) domain is adware, analytics, mobile revenue, etc.

Domain `api.branch.io` was added in commit 1e52f6dd0d92b5d946 in April 2018.  

I don't see that changing, Zac.  Convince me otherwise; make a case.   A hard dependency by Parkmobile would not make a case; it's a bug in Parkmobile, amirite?

**Comment by Zackptg5** [comment]
I have no idea honestly. The tcpdump shows that it uses api.branch.io (present in master hosts) and cdn.branch.io (not present in master hosts - maybe you might want to add this one too if you're not going to remove api).

The app itself appears to use google maps so I'm wondering if the branch.io is used in relation to that and mapping out the user's location? 
Parkmobile seems to use localytics and crashlytics for most of it's ad related tracking though which are blocked fine. Below are the logcats of opening the app with api.branch.io blocked and not blocked if you want to look at the difference. In the blocked one, this line stands out to me: `03-14 17:24:57.223 26308 26308 I BRANCH SDK: Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later.`
After this line, the app pretty much dies and that's when I close it so my guess would be that this behavior is intentional. It makes it sound like it's required for the functionality of the app but I don't know for sure

[BranchBlocked-StuckOnSplashScreen.txt](https://github.com/StevenBlack/hosts/files/2968554/BranchBlocked-StuckOnSplashScreen.txt)
[BranchNotBlocked-Works.txt](https://github.com/StevenBlack/hosts/files/2968555/BranchNotBlocked-Works.txt)
