### ISSUE TITLE
dickssportinggoods.com blocked (Unclear why)

### ISSUE THREAD

**Issue by chado99** [StevenBlack/hosts#932]
Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   dickssportinggoods.com

This common shopping website is blocked. The metrics.dickssportinggoods.com is also blocked (appropriate) but it seems strange Dick's sporting goods main site is also. Please remove from blacklist. Thanks!

**Comment by StevenBlack** [comment]
Ping Mitchell @mitchellkrogza can you look into this for us?  Thanks!

**Comment by mitchellkrogza** [comment]
Thanks for alert @StevenBlack @chado99 indeed one of the very old false positives from early on will be removed this morning in commit
