### ISSUE TITLE
Top level google domain blocked

### ISSUE THREAD

**Issue by Oodledoodley** [StevenBlack/hosts#936]
Google.com is being blocked, is this intentional?

 Exact match for google.com found in:
   https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by funilrys** [comment]
Hi @Oodledoodley and welcome here,

can you tell us please how do you determine the following ?

>Exact match for google.com found in:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

I'm unable to find any line which blocks `google.com`...

Cheers,
Nissar

**Comment by Oodledoodley** [comment]
Hi, I used the tool in Pihole to query my lists as I was having it blocked for some reason. I updated the lists and pihole is still for some reason parsing the list and adding Google.com from your list. I think it's more odd behavior from my pihole rather than your list, sorry about that!
