### ISSUE TITLE
More Hentai and JAV sites UPDATED 23/03/2019

### ISSUE THREAD

**Issue by Danilopereira82** [StevenBlack/hosts#938]
http://www.ver-hentai.com/
http://hentaisd.tv/
https://doujinhentai.net/
https://hentaila.com/
https://www.underhentai.net/
https://hentaistream.com/
https://ohentai.org/
https://hentaihaven.me/
https://www.18hentaionline.net/
http://www.hmangasearcher.com/
https://mundohentai.club/
http://hentaimama.com/
http://www.hentai-id.tv/
https://yaoimangaonline.com/
https://myreadingmanga.info
https://www.drporno.xxx/hentai/
http://hentai-share.tv/
https://www.hentaihome.net
https://www.filmesporno.blog
https://www.javbus.com/
https://www.javbus.org
https://javsin.com/
https://jav18.org/
http://javflash.net/
http://www.xvidzz.com/
https://xbombo.com/
https://nudevista.club/
https://javhdmovies.com
https://see.xxx/
https://javhd.mobi/
https://thai-setup.com
https://javpornmovie.com/
https://animopron.com/
https://3dhentaivideo.com
https://besthentaigames.com/
https://hentainiches.com/
https://hentaipicsworld.com/
https://planetcomixxx.com/
https://yaoimoviearchive.com/
https://miohentai.com
https://miojav.com/
https://hentaidude.com/
http://hentaimama.com/
http://3dtube.xxx/

**Comment by StevenBlack** [comment]
Thanks @Danilopereira82  –  thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant), particularly the porn hosts curators.

Closing.
