### ISSUE TITLE
script blocks chatango.com

### ISSUE THREAD

**Issue by piks** [StevenBlack/hosts#939]
the blacklist of st.chatango.com blocks the site chatango.com

st.chatango.com is the script host for the chat site chatango.com, it is not malware or an advertisment host, 

chatango.com is a known chatsite where people can get together and chat with others, it runs almost fully on javascript files accessed via st.chatango.com (most of them pointing to http://st.chatango.com/js/gz/emb_fullsize.js which is the chat container)

this is also referenced in #712 

tested by:
trying to load any chat on chatango.com [I used examplegroup.chatango.com ]
whitelisting st.chatango.com -confirmed chat loads

**Comment by StevenBlack** [comment]
Hi @piks we don't block `chatango.com`.

The domain `st.chatango.com` is blocked by MVPs.org.   Please take this up with them.  This repo's readme explains how to do that.

Closing.

**Comment by piks** [comment]
Ah, my apologies, I came here cause my pi-hole server said this was the repo for the domain being blocked I'll try to email then.
