### ISSUE TITLE
Hosts to be blocked

### ISSUE THREAD

**Issue by taprobana** [StevenBlack/hosts#940]
Following ad domains are not blocked:
ads.lrb.co.uk
ads.qz.com
api.deep.bi 
api3.accengage.com
api2.accengage.com
api1.accengage.com
apigw.scmp.com
apiproxy3.accengage.com
buf-lemonde-fr-cddc.at-o.net
cdn.concert.io
cdn.gotraffic.net  
cdn.keywee.co
cmp.evolok.net
cs22.wpc.v0cdn.net
cs593.adn.mucdn.net
data.flw.li
reenakun.com
tmgdpr.zedo.net.  
zedo.net
zedo.com

**Comment by taprobana** [comment]
xsgcobwd.com
tldw.me

**Comment by StevenBlack** [comment]
Hi @taprobana thank you for this.

This repo acts is an aggregation.  We monitor reputable, well-curated sources of hosts, combine them in various ways, deduplicate the results, and make these results widely available.

I can't accept a list of hosts like this, which implies that I have to curate these forever, without solid reasons to justify that.  Just submitting a list of domains does not justify that.

Closing.

**Comment by StevenBlack** [comment]
Thank you @taprobana for this.

This repo is an aggregation.  We monitor well-curated sources of hosts, combine them in various ways, deduplicate the results, and make these widely available.

I can't accept this list without some solid reasons for each domain.  If I accept this list, without justification, that means I have to blindly curate these domains forever, never knowing, from the outset, why these domains are listed.   

Looking at your Github profile, there's nothing identifying you, nor is there a track record that would give me any degree of confidence.  Therefore, I'm sorry, I must decline.

Closing.

**Comment by taprobana** [comment]
@StevenBlack No problem. Thanks for all your work!
