### ISSUE TITLE
Possible generic tracking by Avast

### ISSUE THREAD

**Issue by Ultrabenosaurus** [StevenBlack/hosts#941]
A while ago I installed [AdGuard Home](https://github.com/AdguardTeam/AdGuardHome) on a lonely Raspberry Pi 3 Model B and immediately noticed several truck loads of traffic to `avaststat.mailshell.net` with approximately one request every 5 seconds. All of these requests came from my laptop and never from any other device, including my Android 8 phone which is running Avast Mobile. After much searching online I could find no explanation of what it does, and I never got an answer when [I asked on the Avast forums](https://forum.avast.com/index.php?topic=225502.0). 

About a month ago, a week after posting on the Avast forums, I decided to block it via AdGuard Home and have since had absolutely no issues, errors, pop-ups, bugs, or failures with my Avast Internet Security - including the update function - so it really seems like it does nothing of benefit to users. 

[Looking the subdomain up on ICANN](https://whois.icann.org/en/lookup?name=avaststat.mailshell.net) yields no ownership information and [another domain info tool](https://whois.domaintools.com/mailshell.net) proclaims the main domain is running on a Linode instance in Australia? 

![Screen Shot 2019-03-25 at 19 07 19-fullpage](https://user-images.githubusercontent.com/1901532/54947054-56d06300-4f31-11e9-9cf9-b66047900030.png)

Whether or not this is actually related to Avast at all it seems like the only purpose it serves is to track when users' computers are on and connected to the Internet. I have prepended it to my own copy of this hosts file via HostsMan for the time being, but unless someone who knows how to probe domains proves I'm just paranoid then I would suggest adding it to this collection.

**Comment by dnmTX** [comment]
@Ultrabenosaurus it's definitely a reporting domain but it looks like it's connected to your mail clients spam folder and it's reporting the spam mail to Avast, i guess for diagnostics and feature blocking.It's coming from aswSpam module.I'd be cautious on blocking it as it will break some of the features.Their(in general) reporting and ads domains are different,this one is not one of them and also as somebody already replied to you in the forum you can easily opt out of any advertisements in the settings as you have the paid version. I hope this helps.

**Comment by Ultrabenosaurus** [comment]
Hi @dnmTX and thanks for investigating this so quickly. I initially suspected it might be the anti-spam part of Avast, but the odd thing is that I don't use the Windows Mail app and only have Outlook open briefly when I need it. I do most of my email on my phone and rarely open any email software, or even gmail in my browser, so I don't understand why it's pinging every 5 seconds constantly without pause?

**Comment by dnmTX** [comment]
@Ultrabenosaurus doesn't matter how often or you ever open it,as long as you have any mail client in your system and the Avast mail shield active/installed Avast will always have access to it(you can't stop this).Avast in general have access to everything in your system with high privileges(call it however you want,me.personally i call it AVAST VIRUS).Why it's pinging so often,i don't know.I guess that's how it's coded and maybe,just maybe if you complain long enough in their forum they might do some changes.
Keep in mind also that Avast have full access to your hosts file and anything that contains the word "avast"(don't matter good or bad) is being erased,so mine as well double check if the domain that you added with HostsMan is even there.
