### ISSUE TITLE
New hosts

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [StevenBlack/hosts#942]
Hi,
`adcolony.com`
`adcolony.com.lan`
could you blacklist these hosts as wildcard (like `*.adcolony.com.lan`)?
I found `adcolony.com.lan` and `ads30.adcolony.com`.
Thanks.

**Comment by StevenBlack** [comment]
Hi Marco @MarcoDiFrancesco several `adcolony.com` domains are blocked already by several of our hosts sources.  I'll add `ads30.adcolony.com`.

Unfortunately wildcards don't work with hosts...
