### ISSUE TITLE
Apple News on Mojave 

### ISSUE THREAD

**Issue by vinniefm** [StevenBlack/hosts#944]
Not 100% sure that my Apple News app in Mojave broke because of the hosts file and I've tried commenting out lines seemingly pointing to Apple but no luck. Any ideas? When I launch the app I just get a spinner and the Apple News logo.

**Comment by lightswitch05** [comment]
Mine still works, just my two cents

**Comment by StevenBlack** [comment]
Hi Vince @vinniefm what flavour of hosts file are you using?  [We offer several](https://github.com/StevenBlack/hosts#list-of-all-hosts-file-variants).

**Comment by vinniefm** [comment]
Thanks for the reply.  Here's the heading comment on the file I got:

`# This hosts file is a merged collection of hosts from reputable sources,
# with a dash of crowd sourcing via Github
#
# Date: 24 February 2019 02:59:41 (UTC)
# Number of unique domains: 38,977
#
# Fetch the latest version of this file: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
# Project home page: https://github.com/StevenBlack/hosts
# Project releases: https://github.com/StevenBlack/hosts/releases
#
# ===============================================================`

> Hi Vince @vinniefm what flavour of hosts file are you using? [We offer several](https://github.com/StevenBlack/hosts#list-of-all-hosts-file-variants).

**Comment by StevenBlack** [comment]
Does anybody else use Apple news?  Please confirm or comment?   I also need the domain(s) to investigate to pass along to curators, etc...

**Comment by vinniefm** [comment]
Thanks for looking at this Steven and accept my apologies for sending you
down a rabbit hole before I investigated further on my side. Ended up being
an issue with iCloud backups. I'm using your hosts file which are great and
I've got my Apple News app working again.

Thanks again,
Vince

**Comment by StevenBlack** [comment]
Thanks Vince @vinniefm.

Closing.
