### ISSUE TITLE
NVIDIA GeForce Experience telemetry not blocked

### ISSUE THREAD

**Issue by staticsafe** [StevenBlack/hosts#945]
Hi y'all:

Just noticed that telemetry.gfe.nvidia.com is not blocked by this list or any of the other lists Pi-hole uses. Probably a good candidate to add to the list!

**Comment by dnmTX** [comment]
> is not blocked by this list or any of the other lists Pi-hole uses
I guess there is a reason for that.If you using GeForce Experience some of the features will stop working without it(i've seen complaints in the past).
If you not using it,just unzip(unrar) the `.exe` and get rid of the whole telemetry folder before install the driver.

**Comment by dnmTX** [comment]
Just following up on this one( i felt that i had to).Well...looks like as of their latest driver 430.39 Nvidia backed up their telemetry deep into the driver and whatever worked in the past(unrar+remove some of the folders),does not anymore. Plan B is to block the reporting domains but i'm still not sure if there will be any side effects for whoever is using GeForce Experience.I don't use it personally and i blocked them on my end and so far so good.More feedback is needed if Steven @StevenBlack  decide to add them,for sure.Attaching here screenshot from the created Nvidia telemetry log,which points all the domains for reference and testing:

![Capture](https://user-images.githubusercontent.com/34774426/56613838-1ff77680-65dd-11e9-9e06-62c5db8f90b2.PNG)

**Comment by Chaython** [comment]
NV telemetry seems to be necessary for updating profiles especially with their new AI features.

**Comment by dnmTX** [comment]
new domains or some might say...addition:
![Capture](https://user-images.githubusercontent.com/34774426/57681109-a9a2ce80-75f4-11e9-9a26-a9e133344cb6.PNG)

**Comment by StevenBlack** [comment]
Everybody happy if I close this?

**Comment by dnmTX** [comment]
👍
