### ISSUE TITLE
New Domains

### ISSUE THREAD

**Issue by thagxt** [StevenBlack/hosts#946]
Hi, 
here are some more domains ( those playing the ads on dplay.com )
```
fwmrm.net
mssl.fwmrm.net
be6b.v.fwmrm.net
dnitv.com
adops.mercury.dnitv.com
adsafeprotected.com
vpaid.adsafeprotected.com
```

**Comment by StevenBlack** [comment]
Hi Jack @thagxt   –  thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
