### ISSUE TITLE
reddit with new version not work any more

### ISSUE THREAD

**Issue by AngelTs** [StevenBlack/hosts#947]
reddit not work correct any more.
With social before some months was ok, but  with present/new version it is not and reddit is broken
Any help?
in whitelist:
reddit.com
redd.it

**Comment by AngelTs** [comment]
One not so good resolution. I replaced in social/hosts all reddit with the oldest on from 1.Oct.2018:
127.0.0.1 i.reddit.com
127.0.0.1 nsfw.reddit.com
127.0.0.1 redd.it
127.0.0.1 reddit.com
127.0.0.1 www.reddit.com
127.0.0.1 amp-reddit-com.cdn.ampproject.org
127.0.0.1 old.reddit.com
127.0.0.1 new.reddit.com

**Comment by StevenBlack** [comment]
Hi @AngelTs it's been like this [this commit](https://github.com/StevenBlack/hosts/commit/2daf2b0352ce1a8632610fd92e9db8238bdaab06) in January, three months ago.

I don't see this changing; this is the point of the social media extension.

Closing.
