### ISSUE TITLE
Some pornsites domains to block 

### ISSUE THREAD

**Issue by lordruler** [StevenBlack/hosts#948]
127.0.0.1 assets.wowmodels.com
127.0.0.1 nats.ultrafilms.com
127.0.0.1 pornstar4k.com
127.0.0.1 www.nubileporn.net
127.0.0.1 www.pieceinsert.link
127.0.0.1 www.ultrafilms.org
127.0.0.1 www.wowgirls.xxx
127.0.0.1 access.aziani.com
127.0.0.1 cdn.gyrls.com
127.0.0.1 cdn.penthouse.com
127.0.0.1 cdn1.image.tube8.phncdn.com
127.0.0.1 cdn1e.image.tube8.phncdn.com
127.0.0.1 cdn2.image.tube8.phncdn.com
127.0.0.1 cdn2.image.youporn.phncdn.com
127.0.0.1 cdn2e.image.tube8.phncdn.com
127.0.0.1 cdn4.image.youporn.phncdn.com
127.0.0.1 cdn5.image.youporn.phncdn.com
127.0.0.1 cdna.pics.youjizz.com
127.0.0.1 code.jquery.comembed.redtube.com
127.0.0.1 et0.xhamster.com
127.0.0.1 et1.xhamster.com
127.0.0.1 et3.xhamster.com
127.0.0.1 et5.xhamster.com
127.0.0.1 et6.xhamster.com
127.0.0.1 et7.xhamster.com
127.0.0.1 et9.xhamster.com
127.0.0.1 i0.cdn2a.image.pornhub.phncdn.com
127.0.0.1 i0.cdn2b.image.pornhub.phncdn.com
127.0.0.1 i1.cdn2b.image.pornhub.phncdn.com
127.0.0.1 images.sexy-beauties.com
127.0.0.1 img-hw.xvideos.com
127.0.0.1 img-l3.xvideos.com
127.0.0.1 img.l3.cdn.redtubefiles.com
127.0.0.1 img100-007.xvideos.com
127.0.0.1 img100-055.xvideos.com
127.0.0.1 img100-135.xvideos.com
127.0.0.1 img100-159.xvideos.com
127.0.0.1 img100-281.xvideos.com
127.0.0.1 img100-361.xvideos.com
127.0.0.1 img100-376.xvideos.com
127.0.0.1 img100-532.xvideos.com
127.0.0.1 img100-574.xvideos.com
127.0.0.1 img100-582.xvideos.com
127.0.0.1 img100-616.xvideos.com
127.0.0.1 img100-704.xvideos.com
127.0.0.1 img100-738.xvideos.com
127.0.0.1 img100-779.xvideos.com
127.0.0.1 img100-870.xvideos.com
127.0.0.1 img100-881.xvideos.com
127.0.0.1 img100-923.xvideos.com
127.0.0.1 join.penthouse.com
127.0.0.1 m.babesandstars.com
127.0.0.1 mature-sex-milfs.com
127.0.0.1 onlinexxxtop.com
127.0.0.1 penthousegold.com
127.0.0.1 pics.wikifeet.com
127.0.0.1 roomimg.stream.highwebmedia.com
127.0.0.1 sexhd.picsstatic.babesandstars.com
127.0.0.1 stream.nudzz.com
127.0.0.1 sweet-maturewomen.com
127.0.0.1 thumb-v.xhcdn.com
127.0.0.1 thumbs.wikifeet.com
127.0.0.1 truesnaps.comvip.sexhd.pics
127.0.0.1 www.babesandgirls.co
127.0.0.1 mwww.barelist.com
127.0.0.1 www.gyrls.com
127.0.0.1 www.humphole.com
127.0.0.1 www.morazzia.com
127.0.0.1 www.novoporn.com
127.0.0.1 www.tubepornstars.com
127.0.0.1 www.wikifeetx.com
127.0.0.1 www.xxxkindgirls.com
127.0.0.1 xxxmomsonline.com
127.0.0.1 images.nonstopfap.com
127.0.0.1 js.nonstopfap.com
127.0.0.1 nonstopfap.com
127.0.0.1 www.galleryhost.com
127.0.0.1 www.petitenympha.com
127.0.0.1 cdn.iamxxx.com
127.0.0.1 img1.pornflip.com
127.0.0.1 m.pornflip.com
127.0.0.1 static-m.pornflip.com
127.0.0.1 www.asspoint.com
127.0.0.1 www.babezzz.com
127.0.0.1 www.errrotica.com
127.0.0.1 www.nudezz.com
127.0.0.1 www.stonkeep.net

**Comment by StevenBlack** [comment]
Ping @sinfonietta

**Comment by Sinfonietta** [comment]
Done @StevenBlack.

**Comment by StevenBlack** [comment]
Closing!
