### ISSUE TITLE
Coin Blocker Choice Question 

### ISSUE THREAD

**Issue by Thomas499** [StevenBlack/hosts#949]
I noticed your list uses https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser I was just curious why it doesn't use https://zerodot1.gitlab.io/CoinBlockerLists/hosts instead. Looking at the two sites, they say there were both updated on the same day, yet /host list more host. 6,367 more host currently. 

![image](https://user-images.githubusercontent.com/38442058/55805401-3822ae00-5a93-11e9-80f4-752b283b5226.png)

![image](https://user-images.githubusercontent.com/38442058/55805206-d5311700-5a92-11e9-8e3b-85a3ab315fed.png)

I am wondering if the /host file is the host that is actually updated and if /host_browser doesn't always receive the update. 

Is there a reason you use the /host one instead? Is it more reliable or is it the one scanned for dead links and updated accordingly to take dead links out?

**Comment by dnmTX** [comment]
see #868  and then the result of it: #869

**Comment by StevenBlack** [comment]
Thanks for the question Thomas @Thomas499 and thanks for replying @dnmTX.

Closing.

**Comment by dnmTX** [comment]
Yep
