### ISSUE TITLE
Add malware site

### ISSUE THREAD

**Issue by NAThompson** [StevenBlack/hosts#951]
territoriality.space

Truly loathesome site. Hit after a redirect after mistyping washingtonpost.com.

**Comment by StevenBlack** [comment]
Hi Nick @NAThompson  – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
