### ISSUE TITLE
Sonos iOS application is broken 

### ISSUE THREAD

**Issue by Bubu92** [StevenBlack/hosts#953]
Hi. 

I am missing now all songs cover photos. 

Also, the connection to music services is impossible. 

Thanks.

**Comment by StevenBlack** [comment]
Sonos is working perfectly here @Bubu92.  And you give zero details about OS, versions, platforms, etc.

Closing.

**Comment by Bubu92** [comment]
Steven if you need extra information you could just ask.... iOS 12.2, Adblock 4.1

Anyway, having a chat with Blackjack8 I found out that Adblock application was responsible for the problem. Still trying to figure out what is the problem. Cheers
