### ISSUE TITLE
Openload File Sharing Website Fully Blocked [False]

### ISSUE THREAD

**Issue by hyperxpro** [StevenBlack/hosts#954]
File sharing website Openload is fully blocked in Master Host. 

URL: openload.co

Unblock it!

**Comment by StevenBlack** [comment]
Blocked by two or our curated sources.  And, Aayush @hyperxpro, you're just rude.

Closing.

**Comment by hyperxpro** [comment]
@StevenBlack Oh well, okay. And how I am rude? Hahahahaha

**Comment by spirillen** [comment]
> File sharing website Openload is fully blocked in Master Host.
> 
> URL: openload.co
> 
> **_Unblock it!_**

You are talking as @StevenBlack was you're shell prompt with "**_DO IT!_**"

By the way, there are several good reasons for blocking openload.co

- Privacy
- Tracking
- Ads
- (Porn for those whom it concerns)
- Malware
- Spyware
- etc.

**Comment by hyperxpro** [comment]
You guys got ego and attitude problem. Can't help. Look for professional help if needed 😂😂😂😂 

However, never mind Openload.
