### ISSUE TITLE
socket.io was blocked

### ISSUE THREAD

**Issue by PlatinShadow** [StevenBlack/hosts#956]
Recently (porbably) during the last update socket.io was added to the hosts list.. and from what I know socket.io is not a bad site ? 🤔 

It's just hosting dev resources about socketio.. ?

**Comment by dnmTX** [comment]
@PlatinShadow  it was already [reported](https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/29) to the curator of the lists which blocked it and it will be removed in their next update.

**Comment by StevenBlack** [comment]
Thanks Lars @PlatinShadow and D' @dnmTX.

**Comment by PlatinShadow** [comment]
Alright. Thank you all for responding so quickly and for providing this awesome list :)

**Comment by dnmTX** [comment]
@PlatinShadow  just a heads up.Next update might bring that domain back into the list.
I already [reported it](https://gitlab.com/ZeroDot1/CoinBlockerLists/commit/7fcb10dbe402f02e8fa9f600488a32d603e07c64#note_164835872) to the curator.

**Comment by StevenBlack** [comment]
Oh, good catch Dan @dnmTX.
