### ISSUE TITLE
Breaks Hulu app on smart TV

### ISSUE THREAD

**Issue by thedannywahl** [StevenBlack/hosts#958]
The adblock list creates an odd, breaking behavior on the Hulu app on my smart TV.

The app functions perfectly when watching an episode of TV, however, when the episode ends and another episode auto-plays, or is selected manually, an immediate "playback error occurred" alert is displayed with "OK" and "retry"  Retry continually fails.  Selecting "OK" and then navigating to any other video in the Hulu library results in the same error.

The only way to resolve the error is to exit the app on the TV and relaunch.  The issue reappears after watching an episode of anything.  The issue also occurs if you exit an episode before it ends and try to resume or play another episode.

The issue does not occur when the list is removed from the router.  The issue does not occur if an alternate list is used without ad blocking.

I've tried to capture some of the traffic and so far all I can find is multicast search requests `239.255.255.250:1900` and requests that terminate at Akamai `23.222.28.99:443`

This issue does not occur using hulu on a mobile phone or laptop on the same network.

I have the ad-free hulu subscription as well.

* Vizio E60-C3 v2.1.180.0180
* Yahoo TV v1.7.35.2
* App Container 1.7.221.26
* HuluHtml5Launcher 3.0

**Comment by thedannywahl** [comment]
I forgot to mention I've also tried commenting out all lines with "Hulu" or "Akamai" in them in the hosts file to no avail.
`sed -i 's/.*hulu.*/# Removed Hulu/' /tmp/hosts`
`sed -i 's/.*akamai.*/# Removed Akamai/' /tmp/hosts`

**Comment by dnmTX** [comment]
@thedannywahl i see you're on Linux system.If you have **dnsmasq** installed i can walk you trough how to start logging dns request so you can catch exactly which blocked domain is at fault here. Without that information your guess is everyone's guess.

**Comment by thedannywahl** [comment]
@dnmTX yes, I'm running a basic linux w/ busybox which has dnsmasq on the router.  I also have various other clients which could be used.

If you give me the instructions, I'll start logging :)

**Comment by dnmTX** [comment]
@thedannywahl great. Ok,as i'm not sure which firmware you using on your router i'll give you the basics and i'm pretty sure that you are smart enough to figure out the rest.
First you need to find out which directory is the volatile one(resides in the memory) as the log file you're about to create will fill up fast.Usually is the `/tmp`.
Next you need to locate the `dnsmasq.conf` file and add few options there but make sure that after restarting dnsmasq those options will remain there,so if your router's GUI has field for additional dnsmasq options you do it from there.
Once you done with the above add to `dnsmasq.conf`:
`log-queries`
`log-facility=/tmp/dnsmasq.log`
`log-async`
save and **restart dnsmasq**(very important),every firmware is different so find out which command on yours restarts services.
Next,open shell and execute `tail -f /tmp/dnsmasq.log` and if you've done all of the above properly you'll start seeing every incoming and outgoing dns request also the blocked once.
You can start reproducing  your issue and it will show you exactly which blocked domain is at fault.
After you finish your troubleshooting remember to remove the mentioned options above from `dnsmasq.conf` and delete the log file as well.
See,it's simple as that,good luck and if any problems please ask,i'll do my best to help 👍

**Comment by thedannywahl** [comment]
[dnsmasq.log](https://github.com/StevenBlack/hosts/files/3096891/dnsmasq.log)

log file is attached, filtered to only the TV's traffic.

the hits are:

```
geo.yahoo.com
b.scorecardresearch.com
secure-us.imrworldwide.com
```

The last one, `secure-us.imrworldwide.com` appears to be the culprit - as it's second entry in the log is the result of me pressing "retry" on the button on hulu.

**Comment by thedannywahl** [comment]
`secure-au.imrworldwide.com` is whitelisted, no other country alternates are, however.  I haven't had a chance to run `git blame` for the US entry or the AU entry, but the AU entry is recommended for whitelisting here: 
https://github.com/StevenBlack/hosts/issues/174#issue-176266851

**Comment by thedannywahl** [comment]
after commenting out the referenced line and restarting dnsmasq, the issue is resolved.

**Comment by dnmTX** [comment]
@thedannywahl  i'm glad that you got it done. Next step is to report it to the curator of that lists.
You need to write him email `hosts@someonewhocares.org` as he doesn't have repo here.You can also reference our conversation here in the email.
About `geo.yahoo.com` and `b.scorecardresearch.com`,don't worry about them,they're known offenders and they won't break anything by being blocked.Also the comment(#174) that you referenced above,don't worry about that either as most of it bull.
**Enjoy your HULU shows** 📺 🎈 🎈 🎈  👍

**Comment by thedannywahl** [comment]
I have notified the author of the issue, thanks for your help.

Regarding the FW, I will look into it, but the router's 10 years old so it's doubtful.  But I double check that I've locked it down to the best of my ability.

**Comment by StevenBlack** [comment]
Thanks everybody.

Closing.

**Comment by thedannywahl** [comment]
This site was whitelisted upstream by the author.
