### ISSUE TITLE
Unblock s2.youtube.com

### ISSUE THREAD

**Issue by cmdshft** [StevenBlack/hosts#960]
It says right in the comment that blocking that will cause issues with saving videos to history. Can this please be unblocked?

**Comment by dnmTX** [comment]
@cmdshft  that domain goes straight up into category **tracking** and that's why it was blocked but you can submit request to the curator of that lists (`hosts@someonewhocares.org`) and go from there.

**Comment by StevenBlack** [comment]
Hi C @cmdshft — this has been discussed before.  For example: #860, #467, #267, #263, #254, #172.

It is what it is.

Closing.
