### ISSUE TITLE
Question on ads showing in Wordscapes app

### ISSUE THREAD

**Issue by ZooBuZZ** [StevenBlack/hosts#965]
Hi,

I am using an asus router ( RT- AC88U) and running the latest version of Merlin.  I have been using diversion for a year plus and almost never see any ads.  As of last week I started seeing ads in the Wordscapes app and now I have seen ads in another app.  Everything seems to be working in diversion and it is blocking ads on websites.  I am not sure why only a few places the ads are getting through.

edit: - I forgot to mention I am using the built in "Medium" level of blocking within diversion.  As far as I know this basically uses the entire "stevenblack git hub list" and this previously blocked all ads but still let me view pretty much everything I needed to view.  My wife occasionally complained about something being blocked on Facebook, but that was it.  

I tried troubleshooting it some on my own by adding applovin.com and compute-1.amazonaws.com to my blacklist but that didn't help.  (I used a packet capture app to try to see the dns for the ads, but I must not be doing it correctly).  I am far from an expert here, but I know I don't like the ads.  Would someone else be able to help?  I will include a few screenshots of the ads/app.  I am seeing it both with android and iOS devices.  So far I have seen ads in Wordscapes and Memedroid.  It seems like last week something was maybe removed from one of the host files that shouldn't have been?  Thoughts?  Thanks!
![Screenshot_20190429-104016](https://user-images.githubusercontent.com/50112999/56909041-16529080-6a6d-11e9-831c-4a10ae202e67.png)
![Screenshot_20190429-104025](https://user-images.githubusercontent.com/50112999/56909056-1c487180-6a6d-11e9-8cc0-39dc65046de4.png)
![Screenshot_20190429-104035](https://user-images.githubusercontent.com/50112999/56909057-1c487180-6a6d-11e9-9eab-1b5d00ecbc8a.png)

**Comment by Chaython** [comment]
click to view more details, would probably bring you to "addlovin" then add the domain to the hosts file

**Comment by ZooBuZZ** [comment]
Hi,

I clicked on the more details and it takes me to dash.applovin.com/p/how-applovin-shows-you-ads

I added dash.applovin.com to my blacklist, but it still didn't block the ad at the bottom of the screen.  I think normally I have to play about 3-4 rounds before the ads show up.  I think you have to maybe get in like 10 rounds or so before the ads start?  FYI - the full screen ads are properly blocked for me, it just skips right over those.  I am only having trouble with the ads at the bottom of the page. 

Off topic notes: Haha, my wife enjoys the game and we sometimes play a few rounds together.  It does get tougher as you progress.

**Comment by StevenBlack** [comment]
Hi @ZooBuZZ – if you come to an actionable conclusion, please let us know.

Closing.
