### ISSUE TITLE
Google APIs

### ISSUE THREAD

**Issue by monkinco** [StevenBlack/hosts#967]
Again `googleadapis.l.google.com` is blocked which translates into a lot of non-working things, eg: web fonts.

**Comment by dnmTX** [comment]
ping @tiuxo

**Comment by StevenBlack** [comment]
Thanks @monkinco.  We'll get this sorted shortly.

**Comment by StevenBlack** [comment]
New build, coming right now, that fixes this!

**Comment by monkinco** [comment]
Thanks for fast response as I see domain `fonts.gstatic.com`that operates Google Web Fonts needs `gstaticadssl.l.google.com` to work correctly.  It's blocked on line _40364_ when using ["Unified hosts + fakenews + gambling + porn + social"](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts).

Unblocking it too will fix everything. :)

**Comment by dnmTX** [comment]
![Capture](https://user-images.githubusercontent.com/34774426/57199511-56ba7e80-6f45-11e9-8d4b-b5c47c06c86b.PNG)

ping @brianclemens (i hope i pinged the right.....person this time 😉 )

**Comment by brianclemens** [comment]
@StevenBlack I just removed gstaticadssl.l.google.com, should be good to go.  I'm going to take a tour of [the pihole forum](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212/7) and slap together a whitelist to sanity-check against.

**Comment by StevenBlack** [comment]
Fixed in [Release 2\.4\.3](https://github.com/StevenBlack/hosts/releases/tag/2.4.3).

Thanks everybody!

Closing.

**Comment by DRSDavidSoft** [comment]
👀
