### ISSUE TITLE
Blocking all emails on Outlook App (Android)

### ISSUE THREAD

**Issue by jellydonuts** [StevenBlack/hosts#970]
I have your list being pulled by my pi-hole blocker and noticed that whenever I am on my home network, the Outlook App on my mobile phone stops being able to load email messages.

I tracked it down to a blocked query of "mobile.pipe.aria.microsoft.com" which you have listed as "Office 2016 'Connected User Experience' Telemetry" "OneNote Telemetry Service"

**Comment by hopeseekr** [comment]
mobile.pipe.aria.microsoft.com is one of the worst privacy offenders on my personal network. Skype uses it to, among other things, apparently eavesdrop in still unknown ways.

https://www.pcministry.com/win10_telemetry/summary_stats_and_conclusions/

**Comment by dnmTX** [comment]
Some programs(Avast for example) are using Google's DNS to resolve the domains responsible for updates and whatnot:
![Capture](https://user-images.githubusercontent.com/34774426/57573190-86f09a00-73e9-11e9-9a61-678d464ca8b4.PNG)

Blocking `8.8.8.8` here,in such a popular lists is not a option.

**Comment by jellydonuts** [comment]
given your post and information regarding what else goes through this hostname it's probably a good idea to keep it on the blocklist. I think I'll stop using the default Outlook app on my phone for mail and switch to something better.

Any suggestions?

**Comment by spirillen** [comment]
> given your post and information regarding what else goes through this hostname it's probably a good idea to keep it on the blocklist. I think I'll stop using the default Outlook app on my phone for mail and switch to something better.
> 
> Any suggestions?

protonmail.com is a good safe place with encourage to use PGP encrypted mails

**Comment by hopeseekr** [comment]
@dnmTX I really don't want to derail this conversation, but your point is *exactly* why 8.8.8.8 needs to be blocked. Don't you see the rampant privacy problems with *Google* being queried by third parties without your knowledge, informed consent, and going against 5 decades of how DNS server derivation (either via DHCP or static configuration) has been done?

**Comment by spirillen** [comment]
> 8.8.8.8

that exactly why [AS15169](https://www.radb.net/query?advanced_query=&keywords=AS15169&-T+option=&ip_option=&-i+option=) is blocked in my routers firewall :smiley:

**Comment by jawz101** [comment]
> mobile.pipe.aria.microsoft.com is one of the worst privacy offenders on my personal network. Skype uses it to, among other things, apparently eavesdrop in still unknown ways.
> 
> https://www.pcministry.com/win10_telemetry/summary_stats_and_conclusions/
> 
> This issue may be more like whether we should or should not block 8.8.8.8 and 8.8.4.4 on our networks, as part of the greater anti-dystopia war we have all found ourselves in circa 2015/2016.
> 
> Sure, blocking 8.8.8.8 used to cause my Google Chromecast to seize up, claiming the Internet had gone down. But enough of us put our foot down and, after I had already migrated to another piece of hardware, apparently Google backpedaled and did the right thing and now 8.8.8.8 can be blocked and Chromecast works fine.
> 
> Other browsers, like Chrome on Android are/were hardcoding 8.8.8.8 as the DNS, so you lose privacy no matter what your personal actions are, without blocking those two public IPs. Next, I guess, they'll just start using secretive DNS IPs :-/

I personally block mobile.pipe.aria.microsoft.com but - according to the link you supplied- I don't actually see that it is a privacy offender.  Without any real inspection, you could deduce that it could be some keepalive request since it is frequently called.  It just gives us a warm fuzzy to see that it gets blocked a lot but it might be something that polls for new mail more frequently or something.

As for the 8.8.8.8 thingy, one thing I do on my pfSense firewall is redirect any DNS requests _not_ going to my local DNS resolver to actually use it.  For example, if destination isn't 192.168.1.1 and TCP/UDP port 53, send it to 192.168.1.1 port 53.  Something like that.  I also include TCP/UDP port 853 since that is the common DNS over HTTPS/TLS port used.
