### ISSUE TITLE
Found Several Scam sites to block

### ISSUE THREAD

**Issue by thesaver233** [StevenBlack/hosts#971]
microsoftsupport.xyz
himicrosoft.com
Himicrosoft.com will ask for a "support key" which will download a fastsupport client.

**Comment by StevenBlack** [comment]
Hi Nick @thesaver233 – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
