### ISSUE TITLE
hosts blocks parts of Google Play and Amazon Kindle Downloads

### ISSUE THREAD

**Issue by francwalter** [StevenBlack/hosts#972]
Hallo
I use the hosts list indirectly by using NetGuard, see [Ad Blocking with NetGuard](https://github.com/M66B/NetGuard/blob/master/ADBLOCKING.md).
I noticed since a while, when I use NetGuard with that hosts file, I  have partly problems to open Google Play (I am on Android 9.0). Some icons would't show, often the download takes time or won't success. If I deactivate NetGuard (using that hosts file) I have no problems.
Similar problems my friend has with Amazon Kindle App on Android. There the Book Downloads arent working with NetGuard.
I cannot exactly tell, which addresses of Google Play or Amazon Kindle are blocked by the hosts list, but I know that it must be the list.

Is there a way to kick out these addresses of the list?
Are they known anyway?

Thanks.

frank

**Comment by StevenBlack** [comment]
Hi Franc @francwalter.

We will need to know, which variant of our hosts file is used here.

Also, we will need to know which domains to consider and examine.

**Comment by dnmTX** [comment]
@francwalter  this was taken from [NetGuard's manual](https://github.com/M66B/NetGuard/blob/master/ADBLOCKING.md):

> You'll need to enable filtering and (temporarily) logging for this (you can do this by using the Configure button; check both options) and you'll need to wait until the address appears (you can speed this up by opening some apps with in-app ads). Note that ads are likely being cached, so this may not take effect immediately.

see if you can enable logging and post the blocked domains here

**Comment by francwalter** [comment]
Unfortunately I cannot tell if there is a context between all the blocked addresses and Google Play / Amazon Kindle Downloads. NetGuard does not log the app which is blocked but sets only a "root" as origin of blocked addresses (its netd, running as root). 
So I could give a log file of blocked addresses, but I don't know if they are parts of Google Play.
When looking into the log, I didn't see any resemblance of addresses to Google Play. But I am not very skilled at looking into logs ;)

**Comment by dnmTX** [comment]
@francwalter  try to reproduce it as close as you can(turn logging on then open Google Play then try to download something) and if possible upload the log file here so we can take a look.Also,would advise to open a issue in the developer's repo as well to make sure that it's not the app itself messing something up.

**Comment by refriedfood** [comment]
```
0.0.0.0 clients.l.google.com
0.0.0.0 clients1.google.com
```
Is for the google maps app. Try commenting those out.
