### ISSUE TITLE
Add alternet.org to fake news list

### ISSUE THREAD

**Issue by infinitytec** [StevenBlack/hosts#974]
Alternet.org is owned by Raw Story, which is on the fake news blocklist already.

**Comment by StevenBlack** [comment]
Ping Mark @marktron — can you eval this suggestion for us?

**Comment by hopeseekr** [comment]
https://mediabiasfactcheck.com/alternet/

They're so far left that apparently only blatant leftist tyranny can be any more to the left. Several independent websites declare that it is "an activist news service for the left" (Wikipedia).

https://www.allsides.com/news-source/alternet

The Harvard Field Guide of Fake News (circa March 2017) listed AlterNet as a leading example of extreme bias on the Left: https://www.nationalreview.com/2017/03/harvard-fake-news-guide-proves-leftist-media-bias/

**Comment by marktron** [comment]
@hopeseekr They are definitely hyper-partisan. I'd rate the quality of the content as about equal to Fox News or the New York Post: the facts they report are generally verifiable with other reputable sources, but they apply extremely heavy layers of spin. I personally wouldn't use Alternet or Fox News as my source for news, but I don't think either meets the level of disinformation that would warrant blocking them for a large audience in a list like this.

**Comment by StevenBlack** [comment]
Thanks @marktron 

Closing.

**Comment by hopeseekr** [comment]
From the same watchdog:

![image](https://user-images.githubusercontent.com/1125541/57575901-5f192a80-7419-11e9-9e77-cc9ff1b1f614.png)

![image](https://user-images.githubusercontent.com/1125541/57575907-79eb9f00-7419-11e9-9375-e88f3d8849e4.png)

Keywords for Fox News are "moderately to strongly biased". 

Fox News also doesn't, to my knowledge, define itself as a "political action" organization: 

On https://www.alternet.org/about-alternet/

> AlterNet’s aim is to inspire action and advocacy on the environment, human rights and civil liberties, social justice, media, health care issues, and more

In recent times, places are banning this sort of conservative "call to action" communities (Alex Jones, etc.) left and right, and yet turning a blind eye to even more extreme Leftist organizations.

**Comment by infinitytec** [comment]
I would also add this, which in no way backs up its claims, and recent information has stated that their claims here are false:
![image](https://user-images.githubusercontent.com/13670462/57575977-56295880-741b-11e9-8896-edd3f310c743.png)

**Comment by StevenBlack** [comment]
Locking this thread.
