### ISSUE TITLE
Google Fonts not working / gstaticadssl.l.google.com

### ISSUE THREAD

**Issue by tricoos** [StevenBlack/hosts#975]
According to my pi-hole installation gstaticadssl.l.google.com is blocked by this:
 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   gstaticadssl.l.google.com

This would not be a problem but...
fonts.gstatic.com.      300     IN      CNAME   gstaticadssl.l.google.com.
gstaticadssl.l.google.com. 300  IN      A       172.217.21.3

This means that all CDN Google fonts used will not work anymore. 
However, given the name "g static ad ssl" this might be a change that would show more Google ads probably.

This is however very annoying. Though I could just add a custom exception in pi-hole I think I'm not the only one who does not like Google Fonts not working anymore per default.

**Comment by dnmTX** [comment]
@tricoos  it's already been [FIXED](https://github.com/StevenBlack/hosts/issues/967#issuecomment-489473316). Update your lists please.

**Comment by tricoos** [comment]
@dnmTX Ah, thanks. I did search for "fonts" before posting but failed to search in closed issues. Sorry.
