### ISSUE TITLE
Domains To Block

### ISSUE THREAD

**Issue by nrai1** [StevenBlack/hosts#978]
Found some new domains to block 

admaster.total-stream.net
browsergames2019.com 
walmart.swrmw5j8xs.top
target.swrmw5j8xs.top
secure.freeadult.games
www.cyber.game
www.winningpokernetwork.com
wordpress.winningpokernetwork.com
roolgage.com
wacowla.com
americascardroomcom.pokermanagement.com
www.americascardroom.eu
tracking.wpnetwork.eu
vabid.prod.sift.co
trustednotice.news
allmyverygreatlife.com
find-my-great-life.com
crrepo.com
mygoodlives.com
 s.w.org

**Comment by StevenBlack** [comment]
Hi @nrai1  – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
