### ISSUE TITLE
iTunes MusicMatch

### ISSUE THREAD

**Issue by Quorum75** [StevenBlack/hosts#979]
Hi.

It is impossible to update Apple MusicMatch iCloud library. Genius update shows an error 4001.

By replacing the Host file by macOS original one I could nevertheless update my iCloud library.

I guess there is something in the Host file which prevents to upload new songs to update MusicMatch library.

Thanks for your help.
James

**Comment by StevenBlack** [comment]
Hi @Quorum75 thanks for the input.

Gonna need to know, at minimum, what domains are causing the problem?

**Comment by Quorum75** [comment]
Hi @StevenBlack thanks for your response.

If I knew I would have sent it to you ;-) I really have no idea which domain(s) iTunes is calling. 
Also, macOS Network utility did not help. I could not find anything useful in the system logs and because I am not using a firewall I have no visibility of the outgoing process and target domain.

No worries, I will just put on stand-by the Host file every time I need to update the library, which less frequent that it used to be.

At least you have the info.

BTW thanks for having Buffer app on the whitelist.

Cheers
James

**Comment by Tntdruid** [comment]
iTunes MusicMatch works fine for me.
