### ISSUE TITLE
[file request] Adding hosts.skel file with DEFAULT values without blocking rules.

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#98]
@StevenBlack Please add to `hosts` repository file `hosts.skel`with content:

```
#
# /etc/hosts: static lookup table for host names
#

#<ip-address>   <hostname.domain.org>   <hostname>
127.0.0.1   localhost.localdomain   localhost
::1     localhost.localdomain   localhost

# End of file
```

This is default hosts file looking. OFC can be extended and include full list:

```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost
```

**Comment by StevenBlack** [comment]
Hi Tomasz @FadeMind what do you mean, "OFC"?

**Comment by FadeMind** [comment]
@StevenBlack OFC = [of course](https://www.urbandictionary.com/define.php?term=ofc)

FIXED `hosts.skel` file (with extended IP pools)


    #
    # /etc/hosts: static lookup table for host names
    #
    
    #<ip-address>     <hostname.domain.org>	<hostname>
    127.0.0.1	      localhost.localdomain	localhost
    127.0.0.1         local
    255.255.255.255   broadcasthost
    ::1	              localhost.localdomain	localhost
    fe80::1%lo0       localhost.localdomain	localhost
    # End of file

**Comment by gfyoung** [comment]
"OFC" = "of course"

I'm a little confused by this request.  Is it to show what a bare hosts file looks like (as backup)?

**Comment by ScriptTiger** [comment]
*Bump* Can we prune this out of the active issues? It's been over a year and no clarification.

**Comment by StevenBlack** [comment]
Closing.
