### ISSUE TITLE
Request: Include GoodbyeAds & more

### ISSUE THREAD

**Issue by gloschtla** [StevenBlack/hosts#980]
Would you please include https://github.com/jerryn70/GoodbyeAds 

And would you also add the recommendations from jerryn70 ?

AdAway, Blokada, DNS66, hBlock, gasmask

**Comment by StevenBlack** [comment]
Thanks @gloschtla I'll take that under advisement.

To be honest, though, it looks a bit of a mash.

For example, how does one curate a 69,000-line file that isn't sorted?   For example, I count 133 references to `doubleclick` — that's good! — but these are on line 275, 872, 1180, 1353.... how does one curate that?  The answer can only be, not easily.

**Comment by gloschtla** [comment]
Yeah, indeed. At least you will find interesting addresses, such as _graph.faizbook.com_

**Comment by Chaython** [comment]
https://github.com/StevenBlack/hosts/issues/980#issuecomment-492420989
A notepad++ script?

**Comment by funilrys** [comment]
Why not (mention/ping) @jerryn70 ? :thinking: It's his repo after all :man_shrugging: :man_facepalming:

**Comment by StevenBlack** [comment]
I've decided not to proceed with this.

Thanks for the suggestion @gloschtla.

Closing.
