### ISSUE TITLE
CSS blocked on gravatar.com

### ISSUE THREAD

**Issue by donnchawp** [StevenBlack/hosts#983]
Hi,

s.gravatar.com is blocked by your list but it's only used to serve the css styles on the website gravatar.com

Can you remove it please?
Donncha

**Comment by ScriptTiger** [comment]
^Bump @brianclemens, this one is coming from the tiuxo list.

I will say though, just at a glance, they do have a number of jQuery and other JS scripts hosted there, as well, it's not only CSS.

**Comment by brianclemens** [comment]
Fixed

**Comment by StevenBlack** [comment]
Release 2.4.7 is live, and includes this.

Closing.
