### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by edtw** [StevenBlack/hosts#985]
Hello there,
Can these addresses be included in the blockade?

api.zhy333.com
m.bihutg.com
m.yyfymj.com
m.zhaibei112.top
r1oman.com
zry8181.com
lap-click.tr.line.me

 thanks you!

**Comment by StevenBlack** [comment]
Hi @edtw  – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
