### ISSUE TITLE
Remove zaobao.com.sg

### ISSUE THREAD

**Issue by thexile** [StevenBlack/hosts#986]
Please remove zaobao.com.sg. This domain belongs to Singapore local Chinese newspaper.

**Comment by StevenBlack** [comment]
Ping Mitchell @mitchellkrogza.  Thanks!

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/aaf6c5614ec942c2f945c6576418375cd4927e89 @thexile @StevenBlack

**Comment by StevenBlack** [comment]
Thanks Mitchell @mitchellkrogza!

Closing.
