### ISSUE TITLE
submit AD and Privacy leak domains 

### ISSUE THREAD

**Issue by Justsoos** [StevenBlack/hosts#988]
AD sites:

cdn.moji.com
show-g.mediav.com
show.g.mediav.com
360.mediav.com
material.mediav.com
cm.mediav.com
max-l.mediav.com
s1.shucaixiaoshuo.com

Privacy leak sites:

android.bugly.qq.com
mxvp-feature-toggle-prod-1.zenmxapps.com
mxase.clmbtech.com
settings.crashlytics.com
androidapi.mxplay.com
androidc.mxplay.com
evt.mxplay.com
mxvp-feature-toggle-prod-1.zenmxapps.com

**Comment by StevenBlack** [comment]
Hi @Justsoos  – thanks for this input.  And sorry for the delay replying.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
