### ISSUE TITLE
Blocking outwar.com mistakingly

### ISSUE THREAD

**Issue by petesimard** [StevenBlack/hosts#990]
The domain outwar.com is used for a browser based MMORPG and serves no advertising. This block is causing issues for pihole users trying to play the game.

**Comment by StevenBlack** [comment]
Hi Pete @petesimard.  I'm sure you know... it's not just about advertising.

`outwar.com` comes to us via mvps.org which is an extremely professional, well-respected curator of hosts.  They block four of outwar's domains.  Take note of the comment on the last one here:

```
outwar.com
sigil.outwar.com
torax.outwar.com
www.outwar.com #[Trojan.Win32.VB.iy][ADW_OUTWAR.A]
```

So `outwar.com` is hardly bening, it seems, at least according to these fine folks.

Please report this to winhelp2002@gmail.com if you still feel like it.

Closing.
