### ISSUE TITLE
Please block this website

### ISSUE THREAD

**Issue by gacpac** [StevenBlack/hosts#991]
![image](https://user-images.githubusercontent.com/47924627/58762762-0b35c900-8521-11e9-845b-f06f5e942a74.png)

**Comment by spirillen** [comment]
hi @gacpac may I ask on what ground you've like that domain blocked? All i get is this

![Screenshot_2019-06-03 Error 502 (Server Error) 1](https://user-images.githubusercontent.com/44526987/58768047-24785d00-8595-11e9-85ea-1545375dcd5b.png)

**Comment by StevenBlack** [comment]
Hi @gacpac  – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.

**Comment by gacpac** [comment]
Maybe they took it down already.

This was a phishing email redirecting to Office 365 to get your
credentials. And this is hosted in Google servers. Since they are having an
outage today, this could be related.

I also report it to Google directly. This was impacting the company I work
for.

Guillermo Castillo

**Comment by spirillen** [comment]
Thanks @gacpac i'll add it to my [RPZ zones](https://gitlab.com/dns-firewall/dns/matrix/matrix/issues/80) right away just to be sure

**Comment by gacpac** [comment]
AWESOME!!


Guillermo Castillo
