### ISSUE TITLE
Add redtext.biz

### ISSUE THREAD

**Issue by mrinc** [StevenBlack/hosts#992]
I'm not sure 100% what to class this site as but it fakes being a google recaptcha site to get you to allow notifications on your pc.

https://pasteboard.co/IhTrjWs.png <- screen snip

It adds number ranges from 0 -> unknown to try get around blocks in the front of the hostname

**Comment by mrinc** [comment]
Found another one: https://clickjump.biz/?p=mmzdkyrxme5gi3bpge4dg&sub1=Coltin&sub2=demo.v4&a=a#

**Comment by mrinc** [comment]
https://yellowfakeagent.top/j6Kc3y?se_referrer=https%3A%2F%2Fwww.google.com%2F&default_keyword=Flow%20Control%20Valves%20%E2%80%93%20Ultra%20Control%20Valves%20%7C%20Total%20Valve%20Solutions&&frm=script&_cid=871ce1de-2202-5cc8-f641-3ffefc549b6d

**Comment by mrinc** [comment]
Seems a website was hacked and set to redirect these urls 

So maybe malware?

**Comment by StevenBlack** [comment]
Hi Mitchell @mrinc  – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.

**Comment by mrinc** [comment]
Hey

Steven Black's ad-hoc list | Additional sketch domains as I come across them. | link | raw | occasionally | MIT | issues

That links to here :) 

Should I pushed a merge req for your sketch list instead?

**Comment by StevenBlack** [comment]
Hi Mitchell @mrinc – no, please submit this request, and its full explanation, to one of our curators.  This is what they do.
