### ISSUE TITLE
porn social link only 6 hosts download out of 55,202

### ISSUE THREAD

**Issue by dgall65** [StevenBlack/hosts#994]
I am using pfsense pfblocker I have several block lists that upload successfully other then steves list on the DNSBL feeds  but when I try to upload the porn social list  from steveblack list from the following links 
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-social/hosts or
http://sbc.io/hosts/alternates/fakenews-porn-social/hosts only 6 hosts out of the 55,202 download to the firewall rules list what am I doing wrong

**Comment by dgall65** [comment]
Got it figured out

**Comment by ScriptTiger** [comment]
Glad to hear you figured it out. If you think your solution would be helpful to others, please don't be shy to share it. And since this issue was solved, also don't forget to close it just to keep Steven's workflow tidy.
