### ISSUE TITLE
Add Samsnung TV ads in hostfile

### ISSUE THREAD

**Issue by krabe** [StevenBlack/hosts#996]
Hello, can somebody add 
0.0.0.0   ads.samsungsads.com
0.0.0.0   config.samsungads.com

to block Samsung TV Plus crap/scam future. thx

**Comment by StevenBlack** [comment]
Hi @krabe  – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.
