### ISSUE TITLE
New URLs to block

### ISSUE THREAD

**Issue by Quorum75** [StevenBlack/hosts#997]
URLs to block. Identified in spam messages. Added to my custom list. Thanks

0.0.0.0 krishnachemicalsindia.com  
0.0.0.0 pixafoto.com 
0.0.0.0 click.email.manhunt.net

**Comment by StevenBlack** [comment]
Hi @Quorum75 – thanks for this input.

We're mostly an aggregator of hosts files from active and reputable curators of hosts files, and we package these amalgamated hosts files in various ways.

Please submit this request to [one of our curated sources](https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant).

Closing.

**Comment by Quorum75** [comment]
No worries, I will add them to my private section. Faster and I will sure they are in ;-)
