### ISSUE TITLE
MacOS mail links blocked

### ISSUE THREAD

**Issue by tthkbw** [StevenBlack/hosts#999]
I am using unified hosts-addware+malware host file on macOS 10.14.5.

I receive an email newsletter from quartz and this hosts file blocks access to the domain email-tracking.qz.com. I have been unsuccessful in finding anything that looks like this domain in the hosts file. How is it being blocked? And how can I disable this blocking?

**Comment by StevenBlack** [comment]
Hi @tthkbw you're right: we don't clock anything in domain `qz.com` or its subdomains.

Closing, though others are free to speculate.
